neg(eqo("conf/sigmod/AboulnagaC99","xnDzelm2t1QJ")).
neg(eqo("conf/sigmod/AcharyaGPR99","5vntH4boqdgJ")).
neg(eqo("conf/sigmod/AdelbergGW97","NbLabaGWoh4J")).
neg(eqo("conf/sigmod/AdyaGLM95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1041423%26type%3Dpdf")).
neg(eqo("conf/sigmod/Aggarwal02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/AggarwalWY99","wjKnsQWl5ZoJ")).
neg(eqo("conf/sigmod/AggarwalY00","PcAKDUTqlgoJ")).
neg(eqo("conf/sigmod/AgrawalASY97","kGu_qus_CjQJ")).
neg(eqo("conf/sigmod/AgrawalASY97","uUOJ1ozJGk0J")).
neg(eqo("conf/sigmod/AgrawalCFGHIIMMSS94","bXnzC8MN_joJ")).
neg(eqo("conf/sigmod/AgrawalK03","AaKiSc1klw8J")).
neg(eqo("conf/sigmod/AgrawalW00","z_u25f56I8UJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","fQNdA5cjapAJ")).
neg(eqo("conf/sigmod/BabcockBDM03","a2wqpKma5J4J")).
neg(eqo("conf/sigmod/BabuGR01","0BySK5DgSXAJ")).
neg(eqo("conf/sigmod/Bampahl95","KKiefntReoUJ")).
neg(eqo("conf/sigmod/Bampahl95","mNSgRCHwQvAJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","VKDhNI5dc5oJ")).
neg(eqo("conf/sigmod/Bernstein96","DoBdPSgKQnMJ")).
neg(eqo("conf/sigmod/BersonGM95","efwTNo1wRnMJ")).
neg(eqo("conf/sigmod/BertinoCF01","E9WYK5aZNYQJ")).
neg(eqo("conf/sigmod/BilirisFOP96","Gkwwl16X1JEJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","3aUZ-RtpdV8J")).
neg(eqo("conf/sigmod/BlohsfeldKS99","OfWTbnGGiGkJ")).
neg(eqo("conf/sigmod/BohlenBD99","RAcoVQuEzD8J")).
neg(eqo("conf/sigmod/BouguettayaBH99","scJJ9N_LfA0J")).
neg(eqo("conf/sigmod/Brewer98","k4UNrsGeUuAJ")).
neg(eqo("conf/sigmod/BrinMUT97","A7Mm5kFK3zwJ")).
neg(eqo("conf/sigmod/BrinMUT97","nJycrIdh5E4J")).
neg(eqo("conf/sigmod/BrinMUT97","pxbwpA8pQ0IJ")).
neg(eqo("conf/sigmod/BrodskyK95","SFmnhrhoQzgJ")).
neg(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","owyH_Om16GAJ")).
neg(eqo("conf/sigmod/CarinoKKB01","lZGtV8TM9yoJ")).
neg(eqo("conf/sigmod/CarinoKKB01","lvU4b-jL6-EJ")).
neg(eqo("conf/sigmod/CatarciS01","frbExwv4DiwJ")).
neg(eqo("conf/sigmod/Chan98","nPayw9W0gcoJ")).
neg(eqo("conf/sigmod/ChangH02","00ZFKasHBv4J")).
neg(eqo("conf/sigmod/Chaudhuri97","u-8KapWYyWkJ")).
neg(eqo("conf/sigmod/ChaudhuriD97","NB2m5mx1TpcJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","dxvwQEOjBJQJ")).
neg(eqo("conf/sigmod/ChaudhuriGN02","FevB9JHob-AJ")).
neg(eqo("conf/sigmod/ChaudhuriKN03","q2ZF-a_JbOoJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","vpYxtyuveFQJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","ClO4zHQ7RYsJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","X5N075lVgBMJ")).
neg(eqo("conf/sigmod/ChawatheRGW96","RUn5McMYx8YJ")).
neg(eqo("conf/sigmod/CohenM03","8G0beCh-o78J")).
neg(eqo("conf/sigmod/ColletC95","lQnI0zKr5kYJ")).
neg(eqo("conf/sigmod/DavisonG95","P7VGXBo_mlsJ")).
neg(eqo("conf/sigmod/DavisonG95","Yyed3mGH-JcJ")).
neg(eqo("conf/sigmod/DeHaanTCO03","gyYBYgpB63sJ")).
neg(eqo("conf/sigmod/DeHaanTCO03","url:http://doi.wiley.com/10.1002/he.13.abs")).
neg(eqo("conf/sigmod/Dietterich94","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3DN8332711AH")).
neg(eqo("conf/sigmod/DogacAEOADAOS94","lvIPWxkN4YAJ")).
neg(eqo("conf/sigmod/Dyreson03","KGeFsGtIROsJ")).
neg(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
neg(eqo("conf/sigmod/FranklinZ98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945727%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/FukudaMMT96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D122057%26type%3Dpdf")).
neg(eqo("conf/sigmod/FukudaMMT96a","B8_0dK37qcsJ")).
neg(eqo("conf/sigmod/GangulyGR03","kGboYXuVQLAJ")).
neg(eqo("conf/sigmod/GangulyGR03","zQCRmiH6jo4J")).
neg(eqo("conf/sigmod/GarofalakisI96","hlxSx6MENxwJ")).
neg(eqo("conf/sigmod/GarofalakisI96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141831%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GibbsBT94","iS9rQqelSjMJ")).
neg(eqo("conf/sigmod/GionisGK01","mXye9G0HHEwJ")).
neg(eqo("conf/sigmod/GodfreyGXZ01","N1PCJXbeG-oJ")).
neg(eqo("conf/sigmod/GoldsteinL01","-6bnMVTzX-sJ")).
neg(eqo("conf/sigmod/GoldsteinL01","hK54XBUbySoJ")).
neg(eqo("conf/sigmod/GorelikWD94","RAJm11MPBiYJ")).
neg(eqo("conf/sigmod/GraySEBW94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GreenwaldK01","CiumYR8Q4WcJ")).
neg(eqo("conf/sigmod/GriffinH97","WWaxLMIptTMJ")).
neg(eqo("conf/sigmod/GrumbachRS98","RnmBv4e85pMJ")).
neg(eqo("conf/sigmod/GuhaRS98","wiE9QG5qC2wJ")).
neg(eqo("conf/sigmod/GuoSBS03","3xcsKWPVcCoJ")).
neg(eqo("conf/sigmod/GuptaLM03","9bRPA_aTYh4J")).
neg(eqo("conf/sigmod/HammerGNYBV97","t9nmZzSMVAAJ")).
neg(eqo("conf/sigmod/Han96","7e_EwULfgusJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","QHUtoLECZzgJ")).
neg(eqo("conf/sigmod/HeC03","UAO4T_2ylPkJ")).
neg(eqo("conf/sigmod/HellersteinW02","roWVK9vv248J")).
neg(eqo("conf/sigmod/HjaltasonS98","Fa4WQ1Q4k08J")).
neg(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
neg(eqo("conf/sigmod/HsiaoN00","6YjI0pS4i1QJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","GeKcRoQ6AIwJ")).
neg(eqo("conf/sigmod/IvesFFLW99","6ituoubvieMJ")).
neg(eqo("conf/sigmod/Jagadish94","XYBfAojuBzsJ")).
neg(eqo("conf/sigmod/JagadishJOT01","K2E0YdZ8oEEJ")).
neg(eqo("conf/sigmod/JagatheesanR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083798%26type%3Dpdf")).
neg(eqo("conf/sigmod/Jamil99","z5EfiutEfScJ")).
neg(eqo("conf/sigmod/JohnsonD03","5OYgUpRggiMJ")).
neg(eqo("conf/sigmod/KalnisP01","7LqBuZpperIJ")).
neg(eqo("conf/sigmod/KalnisP01","qS4jhfgPbm8J")).
neg(eqo("conf/sigmod/KarbhariRXD02","Mw3xLuyR3qQJ")).
neg(eqo("conf/sigmod/Kohler99","I3ZDfrschkIJ")).
neg(eqo("conf/sigmod/KornJF97","TT5lSHZcN4IJ")).
neg(eqo("conf/sigmod/KriegelMPS01","ztczzwPyHuEJ")).
neg(eqo("conf/sigmod/Kulkarni94","SqDNg30d4-sJ")).
neg(eqo("conf/sigmod/LabioZWGGW97","TVx7zsQQGYUJ")).
neg(eqo("conf/sigmod/Lassettre98","yjsXspk2XrgJ")).
neg(eqo("conf/sigmod/LibkinMW96","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565142%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LiefkeS00","N0eowMtIAukJ")).
neg(eqo("conf/sigmod/LiefkeS00","z7J4u1sJ52cJ")).
neg(eqo("conf/sigmod/LiuFP03","egn46hGLw7gJ")).
neg(eqo("conf/sigmod/Lomet00","nTGRCBK3RBQJ")).
neg(eqo("conf/sigmod/LuMSS95","FjM5TTIe56oJ")).
neg(eqo("conf/sigmod/LuWYBLY02","I5tangbWwOMJ")).
neg(eqo("conf/sigmod/LuoKMPWLN02","dZoF6CUKmQEJ")).
neg(eqo("conf/sigmod/Mamoulis03","PYmxUbU7ERYJ")).
neg(eqo("conf/sigmod/Mamoulis03","QRYYBShocawJ")).
neg(eqo("conf/sigmod/MerialdoAMMP00","6c3XQZ-_HDUJ")).
neg(eqo("conf/sigmod/Mohan01","YLQPbM_N-icJ")).
neg(eqo("conf/sigmod/Mohan94","pBTSyxiQA04J")).
neg(eqo("conf/sigmod/MumickP94","DyApmXH5ZosJ")).
neg(eqo("conf/sigmod/MumickQM97","NWIELbagzysJ")).
neg(eqo("conf/sigmod/ONeilQ97","rN34VXyq84YJ")).
neg(eqo("conf/sigmod/PaparizosACJLNPSWWY03","jhi4Xyt-JnkJ")).
neg(eqo("conf/sigmod/ParkCY95","8CqjZ166ScEJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","Bw0BeUCcPJcJ")).
neg(eqo("conf/sigmod/PhanN02","a_DYyxqi-8QJ")).
neg(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
neg(eqo("conf/sigmod/RadekeBBEKKN95","LclVYrb7vJoJ")).
neg(eqo("conf/sigmod/RajagopalanML98","xufwWHmOf6IJ")).
neg(eqo("conf/sigmod/Ramakrishnan00","XX7VcrTv0ZsJ")).
neg(eqo("conf/sigmod/RamakrishnanD98","url:http://www.springerlink.com/index/W777210182V767H3.pdf")).
neg(eqo("conf/sigmod/Ramanan02","VGe-IBWyMm4J")).
neg(eqo("conf/sigmod/RamaswamyRS00","gF4nPxSCcOMJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","nsN_2BnT_mMJ")).
neg(eqo("conf/sigmod/RaoZML02","7VHYdQzMpUsJ")).
neg(eqo("conf/sigmod/ReinwaldP98","RlH2shMtkfwJ")).
neg(eqo("conf/sigmod/RodriguezR00","MCDgDxsc8rcJ")).
neg(eqo("conf/sigmod/Rosenthal01","NFUWsBXtCncJ")).
neg(eqo("conf/sigmod/RoussopoulosKR97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D16857%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RundensteinerKZWLLN99","C1Hl-dwC-HQJ")).
neg(eqo("conf/sigmod/SeshadriLR94","B855ccGhBu4J")).
neg(eqo("conf/sigmod/SeshadriLR94","o-fZP19Hu2IJ")).
neg(eqo("conf/sigmod/ShanmugasundaramNSR99","HWFnrGXJ6IIJ")).
neg(eqo("conf/sigmod/Shasha97","Q-KG8a3_BmIJ")).
neg(eqo("conf/sigmod/Sheth95","eU-7sSXW5jEJ")).
neg(eqo("conf/sigmod/ShuklaD00","kcrWfQEI9G8J")).
neg(eqo("conf/sigmod/SionAP03","_L0DhCpFaXMJ")).
neg(eqo("conf/sigmod/SistlaW95","KO3FcQ57_rkJ")).
neg(eqo("conf/sigmod/SistlaW95","OjZoGJLFGqIJ")).
neg(eqo("conf/sigmod/SistlaW95","oZl1XlsRVo4J")).
neg(eqo("conf/sigmod/SwamiS94","AYEI8XDoY9wJ")).
neg(eqo("conf/sigmod/SzalayGKT00","HlyrHaVc0HoJ")).
neg(eqo("conf/sigmod/TatarinovVBSSZ02","gYWmOPwa7mwJ")).
neg(eqo("conf/sigmod/TomasicGS94","xrTlYcyFKtwJ")).
neg(eqo("conf/sigmod/Vaskevitch94","mVK23-2iOugJ")).
neg(eqo("conf/sigmod/Vaskevitch94","s6Ax0WdZp6IJ")).
neg(eqo("conf/sigmod/VriesMNK02","6OfJSMB4vOcJ")).
neg(eqo("conf/sigmod/YangM97","ZWwmBQlLFV8J")).
neg(eqo("conf/sigmod/YerneniLGU99","hnMltY0uSf0J")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","OmYc0wE1j4kJ")).
neg(eqo("conf/sigmod/ZhaoDNS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245907%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ZhouR02","9KiPVAodKnYJ")).
neg(eqo("conf/sigmod/ZhuS03","Ynt8Na5eF4sJ")).
neg(eqo("conf/sigmod/ZouS96","v96aue1u9n0J")).
neg(eqo("conf/vldb/AdiBEY00","7kC8fo78d6sJ")).
neg(eqo("conf/vldb/Adler01","OWe20vDyYO4J")).
neg(eqo("conf/vldb/Adler01","_kyazmYDM6oJ")).
neg(eqo("conf/vldb/AgrawalK02","qCvXLXmB6J8J")).
neg(eqo("conf/vldb/AgrawalK02","url:http://www.ingentaconnect.com/content/els/09505849/2002/00000044/00000001/art00210")).
neg(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","3zf3WSt0B6UJ")).
neg(eqo("conf/vldb/AlonsoHST97","BSE2se70OMYJ")).
neg(eqo("conf/vldb/AltinelF00","n6T-QmZgYI8J")).
neg(eqo("conf/vldb/ArunJ98","1dqeMksCm74J")).
neg(eqo("conf/vldb/AshwinGG02","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/Atal96","oPuJo0VHT88J")).
neg(eqo("conf/vldb/BamfordAP99","dpY-2P1Wpw8J")).
neg(eqo("conf/vldb/Bar-YossefBCFW00","url:http://doi.wiley.com/10.1002/he.11205")).
neg(eqo("conf/vldb/BaralisPT97","tuGrmSkM_PkJ")).
neg(eqo("conf/vldb/Baumann03","cdhtlz7lXZ4J")).
neg(eqo("conf/vldb/BawaBA03","_RMZmSBR_PUJ")).
neg(eqo("conf/vldb/BerchtoldKK96","_AA2qEg_o30J")).
neg(eqo("conf/vldb/BerckenSW97","GJ8U-hYnCzgJ")).
neg(eqo("conf/vldb/BliujuteJSS98","QRkvhgn2PHAJ")).
neg(eqo("conf/vldb/BouganimFV96","pqzG7nfdWS0J")).
neg(eqo("conf/vldb/Bowker00","bquALpDKegsJ")).
neg(eqo("conf/vldb/Bowker00","fAHjV8C1hLcJ")).
neg(eqo("conf/vldb/BrinkhoffK94","egvBPvtoaMMJ")).
neg(eqo("conf/vldb/Carey00","d5vsP1FGBC4J")).
neg(eqo("conf/vldb/Carey00","url:http://portal.acm.org/citation.cfm%3Fid%3D223784%26dl%3DGUIDE%26dl%3DACM%26type%3Dproceeding%26idx%3D223784%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/CareyKRLABFLOPQRSSUVWY01","s_ZBkg2D6VoJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","zuIhKVPjN_IJ")).
neg(eqo("conf/vldb/ChakrabartiSST00","0s6troo_Y1AJ")).
neg(eqo("conf/vldb/ChanGR02","VFNvUH5yaVsJ")).
neg(eqo("conf/vldb/ChandrasekaranF02","gPvyDDUyrg4J")).
neg(eqo("conf/vldb/ChaudhuriG99","yniboichufIJ")).
neg(eqo("conf/vldb/ChaudhuriN97","Hc9_3eDVOpkJ")).
neg(eqo("conf/vldb/ChaudhuriS01","gYWmOPwa7mwJ")).
neg(eqo("conf/vldb/ChenJLP03","jJyGKE2N34gJ")).
neg(eqo("conf/vldb/ChenRS95","R0xUZUxSGmwJ")).
neg(eqo("conf/vldb/CherniackFZ01","49EWG8vzsXUJ")).
neg(eqo("conf/vldb/ChienTZ01","4MK0cvw924EJ")).
neg(eqo("conf/vldb/ChienTZ01","tuVp_18tFv8J")).
neg(eqo("conf/vldb/ChienVZTZ02","ZQyBjtpbhvIJ")).
neg(eqo("conf/vldb/ChoG00","UeIDI44G0zYJ")).
neg(eqo("conf/vldb/ChungCLL01","mJiDvbtTKWoJ")).
neg(eqo("conf/vldb/CooperSFHS01","PAfEdPwJ8tgJ")).
neg(eqo("conf/vldb/CotterB00","DYp_oU6znPkJ")).
neg(eqo("conf/vldb/DavisonG94","vNxnMHNfRt8J")).
neg(eqo("conf/vldb/DayalHL01","lBq7bzIzng4J")).
neg(eqo("conf/vldb/DeRose99","ElXj_wVez0kJ")).
neg(eqo("conf/vldb/Deshpande00","aBiqHXGXoJEJ")).
neg(eqo("conf/vldb/DeutschPT99","p6eac5JRYyQJ")).
neg(eqo("conf/vldb/DillKMRST01","x70Y3qaTL40J")).
neg(eqo("conf/vldb/Draluk01","xQzrilMR-QQJ")).
neg(eqo("conf/vldb/DyresonBJ99","zI3Z-hgIxJAJ")).
neg(eqo("conf/vldb/Faloutsos02","hHeeDo6tEX0J")).
neg(eqo("conf/vldb/FangSGMU98","3BEA_0Au2UsJ")).
neg(eqo("conf/vldb/GaoS03","OoapOBBdaN8J")).
neg(eqo("conf/vldb/GehaniJR94","Nz8zwxjBoyYJ")).
neg(eqo("conf/vldb/Gentili01","Mg0A5yz-_wYJ")).
neg(eqo("conf/vldb/GhoshPSH02","PJwykJAk2qkJ")).
neg(eqo("conf/vldb/GoldmanW97","_lvdMphdfvEJ")).
neg(eqo("conf/vldb/GravanoG95","PsoYENGEh9cJ")).
neg(eqo("conf/vldb/GravanoG97","JmGdMWsJuK0J")).
neg(eqo("conf/vldb/GrumbachRS00","Opm5VlTzQTAJ")).
neg(eqo("conf/vldb/GuPS00","_BsVmIUER44J")).
neg(eqo("conf/vldb/Gupta96","2vfsC9OZoUYJ")).
neg(eqo("conf/vldb/Gupta96","oNuyvaETq2AJ")).
neg(eqo("conf/vldb/HageJPST03","xDDdtO9n_pwJ")).
neg(eqo("conf/vldb/HasanM95","iFsr76th3iYJ")).
neg(eqo("conf/vldb/HristidisGP03","HLqmreti7SQJ")).
neg(eqo("conf/vldb/HristidisP02","5k-GwvznWRUJ")).
neg(eqo("conf/vldb/Huyn01","url:http://www.springerlink.com/index/K3TX565702123283.pdf")).
neg(eqo("conf/vldb/Jacobs97","url:http://portal.acm.org/citation.cfm%3Fid%3D237301")).
neg(eqo("conf/vldb/JagadishLRSS94","U7lA2_zAqTYJ")).
neg(eqo("conf/vldb/JagadishNSSK97","NiyGvhgzXxAJ")).
neg(eqo("conf/vldb/JensenL01","rZcRXL6ueUMJ")).
neg(eqo("conf/vldb/JosifovskiR99","S7PvJkEe0iQJ")).
neg(eqo("conf/vldb/KeimH99","VWd7jhLXfV0J")).
neg(eqo("conf/vldb/KerstenWFKBC03","gUJrOpj89tQJ")).
neg(eqo("conf/vldb/KiesslingK02","lPWuMxTX9yYJ")).
neg(eqo("conf/vldb/Koch03","P9sDu6nOGAYJ")).
neg(eqo("conf/vldb/KonigW99","9MlAuURfKhYJ")).
neg(eqo("conf/vldb/KonopnickiS95","VbPeo_JSln8J")).
neg(eqo("conf/vldb/KornMS02","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/Kornacker99","J8sGEkYqAFcJ")).
neg(eqo("conf/vldb/KossmannRR02","W80_hO4TTCYJ")).
neg(eqo("conf/vldb/Kotidis01","nJV2gWah5i0J")).
neg(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
neg(eqo("conf/vldb/LabioG96","PAtbGvXDP1wJ")).
neg(eqo("conf/vldb/LaudBCSR02","Njn8LdfyjkUJ")).
neg(eqo("conf/vldb/LeeHJT03","5KdceadGf8cJ")).
neg(eqo("conf/vldb/LimWPVP02","MM6MtjmMIzIJ")).
neg(eqo("conf/vldb/LockemannKKKN97","9qOUH5DfZ64J")).
neg(eqo("conf/vldb/LuSL95","CV02BGCrMo8J")).
neg(eqo("conf/vldb/LuoN01","TRWSf77xoWsJ")).
neg(eqo("conf/vldb/MadhavanBR01","c968fN8dF_QJ")).
neg(eqo("conf/vldb/Malaika96","LNGZsCHYRuwJ")).
neg(eqo("conf/vldb/Malaika96","x3kLSd1FahoJ")).
neg(eqo("conf/vldb/ManegoldBK02","_BJOL8YHKo4J")).
neg(eqo("conf/vldb/ManolescuFKXO00","c22l_WX_ADwJ")).
neg(eqo("conf/vldb/MehtaD95","lInqqSAPeeIJ")).
neg(eqo("conf/vldb/MeoPC96","4j5ryW5xA7YJ")).
neg(eqo("conf/vldb/MillinerBP95","kYl-9cV8gloJ")).
neg(eqo("conf/vldb/Mohan01","pBTSyxiQA04J")).
neg(eqo("conf/vldb/MohaniaS94","gbjXwFztQTsJ")).
neg(eqo("conf/vldb/Moni96","NCdoZrZA0esJ")).
neg(eqo("conf/vldb/Moni96","kPE8xMuxhlkJ")).
neg(eqo("conf/vldb/Norvag99","HsAQIEugJ8YJ")).
neg(eqo("conf/vldb/Ogawa96","RmC0H5QsQYgJ")).
neg(eqo("conf/vldb/PapadiasMD98","tRDJ-o_7gxcJ")).
neg(eqo("conf/vldb/PapadiasTS03","fDWfHiQ6BR4J")).
neg(eqo("conf/vldb/PellenkoftLK97","dpeR1StWTysJ")).
neg(eqo("conf/vldb/PoosalaI96","-aml_OMAQNgJ")).
neg(eqo("conf/vldb/PoosalaI97","0Yw58WvaBxEJ")).
neg(eqo("conf/vldb/RaghavanG03","jp9ptMpdoGwJ")).
neg(eqo("conf/vldb/RamakrishnanR96","K9jUyjxRaCwJ")).
neg(eqo("conf/vldb/Ramaswamy00","CToUoWq9c64J")).
neg(eqo("conf/vldb/RantzauCHM02","krAZ7iDMEOQJ")).
neg(eqo("conf/vldb/RiedelGF98","DFXKdJJtFsQJ")).
neg(eqo("conf/vldb/RizviH02","3ku_XOqYuawJ")).
neg(eqo("conf/vldb/RosenthalS94","16tlmwHi2EwJ")).
neg(eqo("conf/vldb/RoussopoulosK98","W-dtWIGKQHcJ")).
neg(eqo("conf/vldb/Sarawagi02","glmeeRSDdmIJ")).
neg(eqo("conf/vldb/Sarawagi02","rKbVwzF70I4J")).
neg(eqo("conf/vldb/Sarawagi95","Ndo_zcq-A-MJ")).
neg(eqo("conf/vldb/Sarawagi95","gz92a8BdTLUJ")).
neg(eqo("conf/vldb/SavasereON95","CG-_La4oAYkJ")).
neg(eqo("conf/vldb/Schnase00","KhFBQ-mAwisJ")).
neg(eqo("conf/vldb/ShanmugasundaramSBCLPR00","KTGNIGcCxdQJ")).
neg(eqo("conf/vldb/Shenker03","5yETsE57mzgJ")).
neg(eqo("conf/vldb/Sheth96","0CD9uUPdnbUJ")).
neg(eqo("conf/vldb/ShiSZ03","ZsJPzGv3_DgJ")).
neg(eqo("conf/vldb/ShiSZ03","gndV1O-oEkMJ")).
neg(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
neg(eqo("conf/vldb/Slutz98","Q_JRmsXFEM4J")).
neg(eqo("conf/vldb/Spaccapietra94","JrWT-SgnATkJ")).
neg(eqo("conf/vldb/SrikantA95","IYlFcGFiCBgJ")).
neg(eqo("conf/vldb/StolteA02","t4qJ1rlU01sJ")).
neg(eqo("conf/vldb/TanSHCR01","2r4nQqSEOQwJ")).
neg(eqo("conf/vldb/TanSHCR01","hPcNG0tPwgIJ")).
neg(eqo("conf/vldb/TatbulCZCS03","F42wOOy-KR0J")).
neg(eqo("conf/vldb/Tsur00","lQnI0zKr5kYJ")).
neg(eqo("conf/vldb/UrhanF01","jC-TppzLPuEJ")).
neg(eqo("conf/vldb/VassalosP97","Ody9SrSpEtIJ")).
neg(eqo("conf/vldb/VriesDBA99","BEdwlAzJmRUJ")).
neg(eqo("conf/vldb/Wang95","fGjH6yeVKU4J")).
neg(eqo("conf/vldb/WangHH00","url:http://journals.cambridge.org/action/displayFulltext%3Ftype%3D1%26fid%3D328165%26jid%3DUHY%26volumeId%3D32%26issueId%3D01%26aid%3D328164")).
neg(eqo("conf/vldb/WienerN95","6mbu5T69NFEJ")).
neg(eqo("conf/vldb/WuYCT95","wP_GYyvWXaQJ")).
neg(eqo("conf/vldb/X00a","PliMUidDd3EJ")).
neg(eqo("conf/vldb/X00a","umvcERjfNE4J")).
neg(eqo("conf/vldb/YangKL97","OUZ7DdZuFLQJ")).
neg(eqo("conf/vldb/YuV00","Zkh1f-3Pq0gJ")).
neg(eqo("conf/vldb/YuV00","imYd4ew7JWQJ")).
neg(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
neg(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02b","YUtQ8KXNntYJ")).
neg(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Abiteboul99","XTa-ElbpjZ8J")).
neg(eqo("journals/sigmod/Abiteboul99","gIKwrx708HMJ")).
neg(eqo("journals/sigmod/Abiteboul99","v80FFBUTW_0J")).
neg(eqo("journals/sigmod/AbiteboulH95","W1Wqm0F1KukJ")).
neg(eqo("journals/sigmod/AilamakiFFSV03","7-Suml1GqBQJ")).
neg(eqo("journals/sigmod/AilamakiG03","25xRkmL_4BsJ")).
neg(eqo("journals/sigmod/AtzeniMM97","v1aol6mmLdMJ")).
neg(eqo("journals/sigmod/BallMRZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BargaL02","h_EKR1nrXV0J")).
neg(eqo("journals/sigmod/BergamaschiCV99","D0bX5bzh8FUJ")).
neg(eqo("journals/sigmod/BergamaschiCV99","cH46MV7BljUJ")).
neg(eqo("journals/sigmod/BertinoEH03","Aq_TE_cWEQkJ")).
neg(eqo("journals/sigmod/BerzalM02","8TcpKdIK1r0J")).
neg(eqo("journals/sigmod/BollKB98","HMbFbVYcCuwJ")).
neg(eqo("journals/sigmod/BoulosO99","Fyek_kCB-qkJ")).
neg(eqo("journals/sigmod/BrunieK96","Llr0ikQ8yIIJ")).
neg(eqo("journals/sigmod/CampbellEM03","sogqXf1HZwkJ")).
neg(eqo("journals/sigmod/CaplinskasEV02","jNh5KYeFejkJ")).
neg(eqo("journals/sigmod/Chang03","64fMPB-atd8J")).
neg(eqo("journals/sigmod/Chen94","48tNIIhyVtsJ")).
neg(eqo("journals/sigmod/CherniakV03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ClementiniF00","igcvBI4EBhIJ")).
neg(eqo("journals/sigmod/ConradHHKRSS99","_xkbPYKMIscJ")).
neg(eqo("journals/sigmod/CrestaniG02","Da1u-SVbqfMJ")).
neg(eqo("journals/sigmod/DadamK97","7hQge_9oGMMJ")).
neg(eqo("journals/sigmod/Danish98","r2fA9pX0Y-UJ")).
neg(eqo("journals/sigmod/Dogac96","62uEWBKYqgoJ")).
neg(eqo("journals/sigmod/DogacAOD95","EwU0KYwx0BkJ")).
neg(eqo("journals/sigmod/Domingo-FerrerH98","gpjVvUtM6H8J")).
neg(eqo("journals/sigmod/EisenbergM00","5ko7rUR9rJ8J")).
neg(eqo("journals/sigmod/EisenbergM00","IqEw9ssJ2QAJ")).
neg(eqo("journals/sigmod/EisenbergM00","yzlys0OQkt8J")).
neg(eqo("journals/sigmod/ErdurD02","eU-7sSXW5jEJ")).
neg(eqo("journals/sigmod/Fankhauser01","url:http://www.extenza-eps.com/WOI/doi/abs/10.5555/bilc.2005.1.St_Lucia.297")).
neg(eqo("journals/sigmod/Finkelstein95","KhgA_ImRGREJ")).
neg(eqo("journals/sigmod/Franklin00","CMA57sPAk_4J")).
neg(eqo("journals/sigmod/Franklin00b","ufjnZovcIb4J")).
neg(eqo("journals/sigmod/Franklin00b","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Franklin98a","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/Franklin98a","url:http://doi.wiley.com/10.1002/he.21")).
neg(eqo("journals/sigmod/Franklin99a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604271%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin99b","98k6qrbdmsYJ")).
neg(eqo("journals/sigmod/Franklin99b","b4XxIzOVVy0J")).
neg(eqo("journals/sigmod/FreemanG96","f5cqkpUXl0kJ")).
neg(eqo("journals/sigmod/Gallagher94","njMtLCOhsLEJ")).
neg(eqo("journals/sigmod/GatziuJSV99","XDGpuS06D3EJ")).
neg(eqo("journals/sigmod/GerlhofKM96","GDoFPiEzEhQJ")).
neg(eqo("journals/sigmod/GobleR02","fX2cmd-DJykJ")).
neg(eqo("journals/sigmod/GrayG97","0jjlzyj_NlQJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","BMcP1NpdMRoJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Halevy03","lDTPyBMtHVwJ")).
neg(eqo("journals/sigmod/HalkidiBV02a","9wQ6RWWcHRIJ")).
neg(eqo("journals/sigmod/Han98","url:http://www.springerlink.com/index/X5782X1J74H4434P.pdf")).
neg(eqo("journals/sigmod/Hanson99","srdaGlUMXP0J")).
neg(eqo("journals/sigmod/HansonN99","zMK02pxd4OEJ")).
neg(eqo("journals/sigmod/Huyn01","9OYLimeDdj0J")).
neg(eqo("journals/sigmod/JacobS99","3-iiSyJLwLkJ")).
neg(eqo("journals/sigmod/JajodiaBBKMSW97","YvPVdFdjWo8J")).
neg(eqo("journals/sigmod/KennedyMB96","th84duaygi4J")).
neg(eqo("journals/sigmod/Kim94","wJTN8d8md7oJ")).
neg(eqo("journals/sigmod/KuokFW98","fb50Eco-otgJ")).
neg(eqo("journals/sigmod/LeeCL95","qS4jhfgPbm8J")).
neg(eqo("journals/sigmod/Liu02","darWCYZjZHcJ")).
neg(eqo("journals/sigmod/Liu02a","lAH2JjWSJCgJ")).
neg(eqo("journals/sigmod/Liu03a","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/Liu03b","xeceK06Z5DIJ")).
neg(eqo("journals/sigmod/Lomet98","XNiDYAanN2QJ")).
neg(eqo("journals/sigmod/LuoI02","url:http://doi.wiley.com/10.1002/tl.66")).
neg(eqo("journals/sigmod/MalaikaEM03","U7glO1ebLPYJ")).
neg(eqo("journals/sigmod/MalaikaEM03","Y0wuvZquTBEJ")).
neg(eqo("journals/sigmod/Mani03","UjWUKmJyMyYJ")).
neg(eqo("journals/sigmod/MarchiLPT03","oeMU1XoJSesJ")).
neg(eqo("journals/sigmod/MaximilienS02","ih9HP7iuVQQJ")).
neg(eqo("journals/sigmod/MedeirosP94","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565142%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MedskerCS95","9qYCh56nCtMJ")).
neg(eqo("journals/sigmod/MeersmanS02","-dQ0fco4WQYJ")).
neg(eqo("journals/sigmod/MillerHHYHFP01","GQ8o6AjsXrUJ")).
neg(eqo("journals/sigmod/MusickC99","r9sQJGBdBLoJ")).
neg(eqo("journals/sigmod/MusickC99","tzUxfh8dD9sJ")).
neg(eqo("journals/sigmod/Nascimento03","8Yt1Mba9-wQJ")).
neg(eqo("journals/sigmod/Neven02","w7a_HRYK67UJ")).
neg(eqo("journals/sigmod/NobleS95","egn46hGLw7gJ")).
neg(eqo("journals/sigmod/OrlandicLS02","IscadjYlgrcJ")).
neg(eqo("journals/sigmod/Ouksel03","Q2y53UR0g6oJ")).
neg(eqo("journals/sigmod/OukselS99","YeVWiZOxB9IJ")).
neg(eqo("journals/sigmod/Ozsu02","a8yZEGFm7hUJ")).
neg(eqo("journals/sigmod/Palpanas00","5n6Cgku4uVIJ")).
neg(eqo("journals/sigmod/PissinouSEMOPSTD94","fSKoYnVJbwwJ")).
neg(eqo("journals/sigmod/PitouraB95","xfWGb928UfcJ")).
neg(eqo("journals/sigmod/PossasMCR00","C3swZi1md5YJ")).
neg(eqo("journals/sigmod/Qian94","OoxAB5XZBawJ")).
neg(eqo("journals/sigmod/Qian94a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian95b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian97","3ET_IEkoGjYJ")).
neg(eqo("journals/sigmod/RamDD99","7N9SPJc18OcJ")).
neg(eqo("journals/sigmod/RamanathanH97","odFtqwn5ZVcJ")).
neg(eqo("journals/sigmod/RashidS00","e0GH54HirssJ")).
neg(eqo("journals/sigmod/RashidS00","t-ewAHmbSigJ")).
neg(eqo("journals/sigmod/Ritter98","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D017405550037AI")).
neg(eqo("journals/sigmod/Rosenthal98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290604%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Rosneblatt94","D1RdxKP6_6YJ")).
neg(eqo("journals/sigmod/RossCGJBV99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossFLOSSVW00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossFS02","fuZuBO3VltcJ")).
neg(eqo("journals/sigmod/RossNO03","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/RossNO03","ki6h8TZDRb4J")).
neg(eqo("journals/sigmod/RossNO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Roussopoulos98","qrfeEEm1pcQJ")).
neg(eqo("journals/sigmod/Roussopoulos98","z1eJxsU4sQkJ")).
neg(eqo("journals/sigmod/SegevJS95","RalvsjDuKzsJ")).
neg(eqo("journals/sigmod/Sidell96","TJB2I4YYDgkJ")).
neg(eqo("journals/sigmod/SilberschatzZ97","q3STvfAaC1kJ")).
neg(eqo("journals/sigmod/Snodgrass00b","7AaDeU0TRFQJ")).
neg(eqo("journals/sigmod/Snodgrass01a","HA3wM_i-y3YJ")).
neg(eqo("journals/sigmod/Snodgrass02b","KENWBobILMwJ")).
neg(eqo("journals/sigmod/Snodgrass03","l7ElxBfCtFgJ")).
neg(eqo("journals/sigmod/Snodgrass94","l7ElxBfCtFgJ")).
neg(eqo("journals/sigmod/Snodgrass94","rEKcHMTrlSEJ")).
neg(eqo("journals/sigmod/Snodgrass99b","suRM3zI6_sUJ")).
neg(eqo("journals/sigmod/Stonebraker02","0G3TECvMM6IJ")).
neg(eqo("journals/sigmod/Stonebraker02","DDyZXuEtGiwJ")).
neg(eqo("journals/sigmod/TanK03","izvcAVqGLm0J")).
neg(eqo("journals/sigmod/TanakaV01","q9FSSXk_4vcJ")).
neg(eqo("journals/sigmod/TatarinovIMHSDDKMM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130872%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/VetterliVS00","dAF5Z861mZgJ")).
neg(eqo("journals/sigmod/Wade96","yysPPwId4XUJ")).
neg(eqo("journals/sigmod/Widom95","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Widom95","url:http://portal.acm.org/citation.cfm%3Fid%3D233269%26dl%3DGUIDE%26dl%3DGUIDE%26type%3Dproceeding%26idx%3D233269%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom96b","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Wiegand02","9WTNlminW6AJ")).
neg(eqo("journals/sigmod/Wiegand02","mFYtlJu__iMJ")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/citation.cfm%3Fid%3D1083784.1083802")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1041425%26type%3Dpdf")).
neg(eqo("journals/sigmod/Winslett94","sfQlMM3SXpAJ")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084829")).
neg(eqo("journals/sigmod/Wong95","PylKCZTK3JEJ")).
neg(eqo("journals/sigmod/Wong95","rn2Z46_1EE8J")).
neg(eqo("journals/sigmod/WuY00","Jn1zTJX3EJMJ")).
neg(eqo("journals/sigmod/WuY00","rtnpqb22gGcJ")).
neg(eqo("journals/sigmod/Yang94","QST0nxMh-SUJ")).
neg(eqo("journals/sigmod/Zhang95","XDGpuS06D3EJ")).
neg(eqo("journals/tods/AikenHW95","tihup0QeJqgJ")).
neg(eqo("journals/tods/BaralisCP96","BVbod3z-M3gJ")).
neg(eqo("journals/tods/BaralisW00","Rg1D_8nULtAJ")).
neg(eqo("journals/tods/BellNNS96","pz2VRTdXq1cJ")).
neg(eqo("journals/tods/CeriFPT94","lHS9z1A75f0J")).
neg(eqo("journals/tods/CeriFPT95","DoS7NkmUyYgJ")).
neg(eqo("journals/tods/ChaudhuriS99","xxkUtjfGpvAJ")).
neg(eqo("journals/tods/ChrysanthisR94","pMEMBFnwKzsJ")).
neg(eqo("journals/tods/CiacciaP02","RAcoVQuEzD8J")).
neg(eqo("journals/tods/CliffordC94","wLG-N_iOaRIJ")).
neg(eqo("journals/tods/EiterLLS01","k8EsgEuKhQ0J")).
neg(eqo("journals/tods/Galindo-LegariaR97","R4fJ14rUjAAJ")).
neg(eqo("journals/tods/Kim94","-crUGhltmyQJ")).
neg(eqo("journals/tods/Kim94","5aSVaxWgGUMJ")).
neg(eqo("journals/tods/KonopnickiS98","EhLr80JWT-gJ")).
neg(eqo("journals/tods/LakshmananSS01","NQShGztSLaoJ")).
neg(eqo("journals/tods/LiC01","01LHBmI_rUcJ")).
neg(eqo("journals/tods/MamoulisP01","iiDnwfRlCYgJ")).
neg(eqo("journals/tods/MelnikG03","xFMIULHu95kJ")).
neg(eqo("journals/tods/MokNE96","RtMuK3d5NY4J")).
neg(eqo("journals/tods/PolyzoisG94","c5JB2YhdGscJ")).
neg(eqo("journals/tods/ScioreSR94","YHAGLm9QCGAJ")).
neg(eqo("journals/tods/ShashaLSV95","dRWF-i-4-x0J")).
neg(eqo("journals/tods/Snodgrass01a","64zuXFJE90EJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/U2P4PV601173R065.pdf")).
neg(eqo("journals/tods/SrivastavaSRN95","oMOJqD6Nl5YJ")).
neg(eqo("journals/tods/StolboushkinT98","2wRdgm_1ujwJ")).
neg(eqo("journals/tods/WangBBJ97","uaaJl906vYoJ")).
neg(eqo("journals/vldb/AgrawalAJL95","Gcencl5cfTIJ")).
neg(eqo("journals/vldb/AgrawalAJL95","nnDOmy8TvcIJ")).
neg(eqo("journals/vldb/AilamakiDH02","DAkUJ8vDsHsJ")).
neg(eqo("journals/vldb/AlbanoGO95","vrD2aAK6G-wJ")).
neg(eqo("journals/vldb/AntoshenkovZ96","V18cLJP_f8QJ")).
neg(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/RTCC57FUUW3CADRF.pdf")).
neg(eqo("journals/vldb/Bertino94","4m-WmWU5iGYJ")).
neg(eqo("journals/vldb/Bertino94","ersSWTLza1sJ")).
neg(eqo("journals/vldb/BraumandlKKKKSS01","dURGvGhlWbsJ")).
neg(eqo("journals/vldb/CandanLS00","nXvDy_QqSd4J")).
neg(eqo("journals/vldb/CatarciSC97","-qsHBe_0vI4J")).
neg(eqo("journals/vldb/CatarciSC97","Nz8zwxjBoyYJ")).
neg(eqo("journals/vldb/ChakrabartiGRS01","1KckBFVfgyMJ")).
neg(eqo("journals/vldb/ChanFGR02","ORkxHLb7dvcJ")).
neg(eqo("journals/vldb/ChanFGR02","zmwPMSd8rGgJ")).
neg(eqo("journals/vldb/ChangG01","3mVAyjsRXiwJ")).
neg(eqo("journals/vldb/CliftonGB95","puxBXWQMfNcJ")).
neg(eqo("journals/vldb/DerrMP94","AkeqieT-JTAJ")).
neg(eqo("journals/vldb/DiazJ97","RKAY1aZAeCoJ")).
neg(eqo("journals/vldb/EvangelidisS97","EbGZKQPyH_4J")).
neg(eqo("journals/vldb/FengYLH02","Nd7-CTB1lRgJ")).
neg(eqo("journals/vldb/Guting94","5GuJb1pfy3AJ")).
neg(eqo("journals/vldb/Guting94","PylKCZTK3JEJ")).
neg(eqo("journals/vldb/GutingS95","GStvcdzFfB8J")).
neg(eqo("journals/vldb/Halevy02","CYJR7X2NtGMJ")).
neg(eqo("journals/vldb/Han98","2kDtSxYI5DgJ")).
neg(eqo("journals/vldb/HarrisR96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1053425")).
neg(eqo("journals/vldb/HuangDT99","xF8s5N7oUIMJ")).
neg(eqo("journals/vldb/JagadishACLNPPSWWY02","8B-KY_3fXlkJ")).
neg(eqo("journals/vldb/LawLG99","feUBtHjRq0cJ")).
neg(eqo("journals/vldb/Li03","ami_BUuBa4UJ")).
neg(eqo("journals/vldb/LiangOY00","vib3UvvceRsJ")).
neg(eqo("journals/vldb/MaratheS02","1WAVR-zTvXAJ")).
neg(eqo("journals/vldb/MedjahedBE03","M0FH31YCEU0J")).
neg(eqo("journals/vldb/MehtaD97","dahaBAYvs5AJ")).
neg(eqo("journals/vldb/MehtaD97","fJACk48ag-4J")).
neg(eqo("journals/vldb/PanagosB97","Nj1OIKaaipYJ")).
neg(eqo("journals/vldb/PanagosB97","dXegp-RmzXEJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","OqykX1gdBFwJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","a1CLM5GoVtYJ")).
neg(eqo("journals/vldb/WhangKW94","eevFR0eJuZsJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","t8KDgCSg9RIJ")).
pos(eqo("conf/sigmod/AdaliBSS98","YQ90BYSVqbsJ")).
pos(eqo("conf/sigmod/AdelbergGK95","NbLabaGWoh4J")).
pos(eqo("conf/sigmod/AggarwalY00","OV5GSHDaYNMJ")).
pos(eqo("conf/sigmod/AgrawalASY97","C85vtVHZmjUJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","1rW7ao6gK-QJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","EQ0ys8s10vcJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x8fDHaNkSUIJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","y55xkFQJvxAJ")).
pos(eqo("conf/sigmod/Al-KhalifaYJ03","boJKiPCpIxkJ")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","YAkpVC1qgaIJ")).
pos(eqo("conf/sigmod/AnnamalaiCD00","0Igfv6jL3jwJ")).
pos(eqo("conf/sigmod/ArasuG03","jp9ptMpdoGwJ")).
pos(eqo("conf/sigmod/ArefBV95","K7mfVCHc3noJ")).
pos(eqo("conf/sigmod/ArefBV95","ht_8Iq3SZ80J")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","6_FvrRYnxHYJ")).
pos(eqo("conf/sigmod/Aulakh98","xFK4CkKj14EJ")).
pos(eqo("conf/sigmod/BarbaraI94","7N0H3ra1FFsJ")).
pos(eqo("conf/sigmod/BarbaraI94","kooQijVBMscJ")).
pos(eqo("conf/sigmod/BarclaySG00","7br3WXwZRQ4J")).
pos(eqo("conf/sigmod/BarclaySG00","JTEJ-q3T1vsJ")).
pos(eqo("conf/sigmod/BarclaySG00","Yiyko_0KiEIJ")).
pos(eqo("conf/sigmod/BarclaySG00","tKeGALC3uFMJ")).
pos(eqo("conf/sigmod/BargaL99","QGxyK7bJQOMJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","mXKKjAJUm-oJ")).
pos(eqo("conf/sigmod/BerchtoldK98","PKMN5Cdy7KcJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","-CQaLTpGJLQJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","-lYgZoLNtioJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","gWmqoNZHKAAJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","zguNkU2zLY0J")).
pos(eqo("conf/sigmod/BersonGM95","-A4ypXVd348J")).
pos(eqo("conf/sigmod/BilirisDGJR94","3Lzo6p8X-n4J")).
pos(eqo("conf/sigmod/BilirisDGJR94","lG6uSYhEGnQJ")).
pos(eqo("conf/sigmod/BlakeleyD00","url:http://portal.acm.org/citation.cfm%3Fid%3D335191.335480%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BlakeleyP98","yotsUgKBK44J")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97a","JntLVX4TPi0J")).
pos(eqo("conf/sigmod/BraumandlKK99","4fjXoCHhe1kJ")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/BreunigKKS01","3ET_IEkoGjYJ")).
pos(eqo("conf/sigmod/BrunoCG01","8KJ9XFv1ESAJ")).
pos(eqo("conf/sigmod/BrunoCG01","XWF4kOtaoJkJ")).
pos(eqo("conf/sigmod/CallanCD99","eWVreKOw_QgJ")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","0oPBNo-ofPkJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","5wcgt7bNx7YJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","PPV8eOf-uooJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","jMc3U-zRTPEJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","mt8Q1YmVRkMJ")).
pos(eqo("conf/sigmod/ChakrabartiDI98","qtVVVrzTLr4J")).
pos(eqo("conf/sigmod/ChangBCLLS00","dM9iTzhspEUJ")).
pos(eqo("conf/sigmod/Chaudhuri97","9GsZHpVf2_cJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","U0w9W7YcsZwJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","clNmwzm-5acJ")).
pos(eqo("conf/sigmod/ChenZCKR01","15Xnu2VYNAQJ")).
pos(eqo("conf/sigmod/ChoG00","yUZCropW2lQJ")).
pos(eqo("conf/sigmod/Chong98","W-6r_OOEHLUJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","GpGg0czXSQcJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","nDl2k1YSi8AJ")).
pos(eqo("conf/sigmod/ChungMS02","mEfTTKdu6soJ")).
pos(eqo("conf/sigmod/ChungMS02","vA_YTBbNegEJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","fDiU6std8e0J")).
pos(eqo("conf/sigmod/DanS95","nTu7PUukM1wJ")).
pos(eqo("conf/sigmod/DarEGP98","ewnL82c8kiMJ")).
pos(eqo("conf/sigmod/DarR94","TtV6gGLQ9NMJ")).
pos(eqo("conf/sigmod/DavisonG95","Ed8EH4p2vBMJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","3PH--zwkZO8J")).
pos(eqo("conf/sigmod/DoRD99","Rviij1nqEcoJ")).
pos(eqo("conf/sigmod/DraperHW01","6MdiqTp20aoJ")).
pos(eqo("conf/sigmod/DraperHW01","sURGDemFSsUJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","N9NHi5y3K38J")).
pos(eqo("conf/sigmod/FernandezFKLS98","W3H34LBUMtoJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","vVYs-3fNuZAJ")).
pos(eqo("conf/sigmod/FlorescuGKR02","uam2rv99rxsJ")).
pos(eqo("conf/sigmod/FlorescuLMS99","mH0XY3h8UlcJ")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GangulyGMS96","05ZgvGyhSC0J")).
pos(eqo("conf/sigmod/GardarinMP95","IOqPoq2MSvQJ")).
pos(eqo("conf/sigmod/GardarinMP95","l-9pykkOVrkJ")).
pos(eqo("conf/sigmod/GarofalakisI96","6lvBOS-XO3EJ")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/GodfreySE98","f5cqkpUXl0kJ")).
pos(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
pos(eqo("conf/sigmod/GoldsteinL01","xufwWHmOf6IJ")).
pos(eqo("conf/sigmod/GorelikWD94","h10FxbLW6zAJ")).
pos(eqo("conf/sigmod/GravanoCGP97","1xxRTUP64bwJ")).
pos(eqo("conf/sigmod/GravanoCGP97","8jTTpoQc2RkJ")).
pos(eqo("conf/sigmod/GravanoCGP97","FHEK09LJKfwJ")).
pos(eqo("conf/sigmod/GravanoGT94","OYFpMlm5yCQJ")).
pos(eqo("conf/sigmod/GravanoGT94","iwS7dFGYcyEJ")).
pos(eqo("conf/sigmod/GraySEBW94","JT61IMQEZ-QJ")).
pos(eqo("conf/sigmod/Grust02","FYfyf-SjQNIJ")).
pos(eqo("conf/sigmod/GuhaRS98","-L22HvEHwH8J")).
pos(eqo("conf/sigmod/GuhaRS98","YCjIP8n8UnMJ")).
pos(eqo("conf/sigmod/GuhaRS98","iSkco-aumngJ")).
pos(eqo("conf/sigmod/GuhaRS98","nMzsE-ScW4MJ")).
pos(eqo("conf/sigmod/GuhaRS98","oWVyLUIy9JwJ")).
pos(eqo("conf/sigmod/GuptaMR95","2GUwicKtWTUJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","ahrxo47nJtMJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","pzPZuUoWej8J")).
pos(eqo("conf/sigmod/HammerGNYBV97","uPHrOdEDjlEJ")).
pos(eqo("conf/sigmod/HanFWCZK96","v9BdA55u_XMJ")).
pos(eqo("conf/sigmod/HanPY00","mwSZ7Yejt8sJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Fyek_kCB-qkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","JM1X7hho718J")).
pos(eqo("conf/sigmod/HarinarayanRU96","Qv7KYn9x-SQJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","V6KNPMKdyagJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","sLvivSi__BcJ")).
pos(eqo("conf/sigmod/HellersteinHW97","1n-1Xj-lfLAJ")).
pos(eqo("conf/sigmod/Hidber99","HkBKH9ZUJEcJ")).
pos(eqo("conf/sigmod/HjaltasonS98","hFnyy0PFe1MJ")).
pos(eqo("conf/sigmod/HoAMS97","LWXzOXyOy24J")).
pos(eqo("conf/sigmod/HsuLG00","kxIpDxLD46gJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","7qv9IC8F_WQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","9KBHBWVwKZsJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","WkcdtG_5kfgJ")).
pos(eqo("conf/sigmod/Jagadish94","eH69_dCm18wJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","XpY2UPc6vP0J")).
pos(eqo("conf/sigmod/JajodiaSSB97","p-m7MMOS2aUJ")).
pos(eqo("conf/sigmod/KanthRA02","RgDMwqhT30wJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","A3TmzWOtgmYJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","jCudeTapg5IJ")).
pos(eqo("conf/sigmod/KornMZ03","6VAQeD6muakJ")).
pos(eqo("conf/sigmod/Kramer97","noTo81QxmHQJ")).
pos(eqo("conf/sigmod/KrollW94","kUzm9ofgc1UJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","Hxnlcwm_RhMJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","YWzkq7-TA5MJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","uzpyy9XRpgYJ")).
pos(eqo("conf/sigmod/LangS01","FFQc9XpGFRsJ")).
pos(eqo("conf/sigmod/LeeWMS01","4rJJdFvMmgYJ")).
pos(eqo("conf/sigmod/LehnerSPC00","HQRcmyswIHcJ")).
pos(eqo("conf/sigmod/LiBKN03","micx2kyGfKIJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","P25_yh3lBhoJ")).
pos(eqo("conf/sigmod/LiuPBHPT00","q_o5zij9nCEJ")).
pos(eqo("conf/sigmod/Maguire01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375742%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/MaheshwariL97","DI_v0vb6784J")).
pos(eqo("conf/sigmod/MaratheS99","z6JEYoArZmsJ")).
pos(eqo("conf/sigmod/MarklL02","5fSqMJg7FV4J")).
pos(eqo("conf/sigmod/MeccaAMMS98","I-fmtPvluKEJ")).
pos(eqo("conf/sigmod/MiloAABN03","P7vZf4MkRO4J")).
pos(eqo("conf/sigmod/MogiK96","hxWB8uQMCdgJ")).
pos(eqo("conf/sigmod/MogiK96","ybgxHuCAS_8J")).
pos(eqo("conf/sigmod/Mohan01","IGS3TtqfKUgJ")).
pos(eqo("conf/sigmod/MoonWH02","rlfxeE4k2p4J")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/NguyenACP01","A57h1N3H3pgJ")).
pos(eqo("conf/sigmod/NguyenS96","T8llXFznCOwJ")).
pos(eqo("conf/sigmod/NguyenS96","uD0NKv4AwaQJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","O-TrhFwhKM8J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/OriaOILY00","9SbEzfHLSooJ")).
pos(eqo("conf/sigmod/PadmanabhanBMCH03","wI75uFSs0bwJ")).
pos(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/ParkCY95","A3XtQdi1j5UJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","4eUqHKdkGNoJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","Zp7wEnhqAykJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","gfRbQIzfux4J")).
pos(eqo("conf/sigmod/QunLO03","eBXNcn6PwAEJ")).
pos(eqo("conf/sigmod/RajagopalanML98","AUR-p53CsK8J")).
pos(eqo("conf/sigmod/RajagopalanML98","vbi6XDjg0X8J")).
pos(eqo("conf/sigmod/RajagopalanML98","wO6VeeLIXAsJ")).
pos(eqo("conf/sigmod/RodriguezR00","Bzj3hMdoqVoJ")).
pos(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
pos(eqo("conf/sigmod/RodriguezR00","fL_WoorIDAoJ")).
pos(eqo("conf/sigmod/RoySSB00","0MCbJO8XsEoJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","38HoFGLnxkQJ")).
pos(eqo("conf/sigmod/SagonasSW94","0hHYO7tQJUgJ")).
pos(eqo("conf/sigmod/SagonasSW94","nF5iGEtihWYJ")).
pos(eqo("conf/sigmod/SagonasSW94","uAoWmK-jEGAJ")).
pos(eqo("conf/sigmod/SagonasSW94","xc8KEoeRT9sJ")).
pos(eqo("conf/sigmod/SagonasSW94","zOre6B5JTkoJ")).
pos(eqo("conf/sigmod/Seshadri99","B855ccGhBu4J")).
pos(eqo("conf/sigmod/ShuklaD00","yGz8BLxbPPcJ")).
pos(eqo("conf/sigmod/SistlaW95","J3XZUbzCxjEJ")).
pos(eqo("conf/sigmod/Squire95","ery6k1e8h_sJ")).
pos(eqo("conf/sigmod/StoltePAG03","9WTNlminW6AJ")).
pos(eqo("conf/sigmod/SzalayGKT00","1kKap3JyndkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","5Q_6HLwZ2YIJ")).
pos(eqo("conf/sigmod/SzalayGKT00","6Kdau1eh-hMJ")).
pos(eqo("conf/sigmod/SzalayGKT00","T4os1oo8vT4J")).
pos(eqo("conf/sigmod/SzalayGKT00","ZXB1xI2h-HkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","oPgy1SYoptgJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","8C_VEbqmySgJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","kKk4xIJfQ70J")).
pos(eqo("conf/sigmod/TsurUACMNR98","Css8RIPajcoJ")).
pos(eqo("conf/sigmod/Ubell94","lPxeU6-K_9EJ")).
pos(eqo("conf/sigmod/Ubell94","lphlTARDI9YJ")).
pos(eqo("conf/sigmod/VanceM96","QgKRpqigXEsJ")).
pos(eqo("conf/sigmod/ViglasN02","4QupwyuXHi8J")).
pos(eqo("conf/sigmod/VitterW99","P5oJUiow7lsJ")).
pos(eqo("conf/sigmod/WattezCBFF00","1SA9LhktHsUJ")).
pos(eqo("conf/sigmod/WitkowskiBBDFGSS03","ygCe1xRFuKgJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","19VIHSiMAXcJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","TDIVG8_n_esJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","Mib0RzjUNC0J")).
pos(eqo("conf/sigmod/YangWYH02","xsaovu54vl4J")).
pos(eqo("conf/sigmod/YuMWL01","h95306-8rjEJ")).
pos(eqo("conf/sigmod/ZadorozhnyRVUB02","xmE1380_4E4J")).
pos(eqo("conf/sigmod/ZhuS03","J28mMeNrts4J")).
pos(eqo("conf/vldb/AbiteboulAAACHHMMMMSTV99","2MSe6dRu6OcJ")).
pos(eqo("conf/vldb/AbiteboulACEMM99","OYOTbj4m7JYJ")).
pos(eqo("conf/vldb/AbiteboulACEMM99","hh9fQmB-eEEJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","0MJZbBBMixgJ")).
pos(eqo("conf/vldb/AdiBEY00","W2UXiwB8On8J")).
pos(eqo("conf/vldb/AggarwalHWY03","ZFtAmPKKRBQJ")).
pos(eqo("conf/vldb/AggarwalHWY03","szlqyCesMpgJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","LitNePng-ckJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","VhJatmjKuU8J")).
pos(eqo("conf/vldb/AgrawalPWZ95","x_ykbVlfyP8J")).
pos(eqo("conf/vldb/AgrawalS94","1lpNNpHnY_kJ")).
pos(eqo("conf/vldb/AgrawalS94","2Z_X3zsf4CoJ")).
pos(eqo("conf/vldb/AgrawalS94","551mHiCJRjoJ")).
pos(eqo("conf/vldb/AgrawalS94","CKm9XhI_8k4J")).
pos(eqo("conf/vldb/AgrawalS94","P0age7qyZacJ")).
pos(eqo("conf/vldb/AgrawalS94","QlSaVou-Zt4J")).
pos(eqo("conf/vldb/AgrawalSX01","P3GB0IRKc2IJ")).
pos(eqo("conf/vldb/AlonsoHST97","iRJV85kKVgwJ")).
pos(eqo("conf/vldb/AshwinRSSS97","JB684f38DiwJ")).
pos(eqo("conf/vldb/Bar-YossefBCFW00","-gm97JzyHJsJ")).
pos(eqo("conf/vldb/BargaP95","IjqFtks5dBgJ")).
pos(eqo("conf/vldb/BargaP95","SwFgF_a7RooJ")).
pos(eqo("conf/vldb/BargaP95","iKnoUWXFoaAJ")).
pos(eqo("conf/vldb/BargaP95","uMcOOFSnvRMJ")).
pos(eqo("conf/vldb/BarjaPFWD94","qhl9_KGvjcUJ")).
pos(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
pos(eqo("conf/vldb/BohmMSW01","Uv3mhmUGwdcJ")).
pos(eqo("conf/vldb/Brin95","CuCm_rmA28cJ")).
pos(eqo("conf/vldb/Brin95","ficuvb1Q0aUJ")).
pos(eqo("conf/vldb/Brin95","gOuz-7q2rRUJ")).
pos(eqo("conf/vldb/Brin95","srjTPThCwrwJ")).
pos(eqo("conf/vldb/Brodie03","deEJ1JsF8RwJ")).
pos(eqo("conf/vldb/BrownG01","aJoPVuDNDSsJ")).
pos(eqo("conf/vldb/BrownMCL94","xfAfu8uJ6NAJ")).
pos(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
pos(eqo("conf/vldb/CareyD96","5xe-dQqXfI8J")).
pos(eqo("conf/vldb/CareyD96","riS5qD1-odUJ")).
pos(eqo("conf/vldb/CatozziR95","8ftKLh07LM0J")).
pos(eqo("conf/vldb/Celis96","Bg5vcyRBKd8J")).
pos(eqo("conf/vldb/CeriCW00","K1psyoQRPpgJ")).
pos(eqo("conf/vldb/CeriCW00","LlZwS4UrRtkJ")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","-2Ib1nqgXbcJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChangG97","0NK87fQBfPUJ")).
pos(eqo("conf/vldb/ChangG97","mXye9G0HHEwJ")).
pos(eqo("conf/vldb/ChengGKLLQS99","_pYZZxn2SjYJ")).
pos(eqo("conf/vldb/ChirkovaHS01","NdmocXlpq9QJ")).
pos(eqo("conf/vldb/Chiueh94","PKK2ak_IzrgJ")).
pos(eqo("conf/vldb/Chiueh94","_YFIPoyVC3UJ")).
pos(eqo("conf/vldb/ChristodoulakisTZ97","D0z0BDnbnFcJ")).
pos(eqo("conf/vldb/CiacciaPZ97","q-qZWa6vF7EJ")).
pos(eqo("conf/vldb/CosleyLP02","22ZTae8fNuIJ")).
pos(eqo("conf/vldb/CowleyP00","scg5F1reod0J")).
pos(eqo("conf/vldb/Deshpande00","2DiLFd0rgPgJ")).
pos(eqo("conf/vldb/DeutschPT99","0aJOXauNqYIJ")).
pos(eqo("conf/vldb/DiaoF03","Crt1JZ1eEj0J")).
pos(eqo("conf/vldb/DidriksenGD95","0TNJ5d1tfkEJ")).
pos(eqo("conf/vldb/DiligentiCLGG00","XCP3p-Hk8bMJ")).
pos(eqo("conf/vldb/Duranti01","gQW6iYG5Vh0J")).
pos(eqo("conf/vldb/DuttaDMRT00","q0Ovw6QUk3MJ")).
pos(eqo("conf/vldb/FaloutsosJS97","YOmjd7tKrWgJ")).
pos(eqo("conf/vldb/Fecteau95","LhjvKpDcJKUJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","9rofzgQ6HtcJ")).
pos(eqo("conf/vldb/FrohnLU94","iarLqyQmZ7IJ")).
pos(eqo("conf/vldb/FuC94","ReboDjzo5y0J")).
pos(eqo("conf/vldb/GalanisWJD03","JvthmGX_uoQJ")).
pos(eqo("conf/vldb/Galindo-LegariaPK94","47fE4F2kahEJ")).
pos(eqo("conf/vldb/Galindo-LegariaPK94","R4fJ14rUjAAJ")).
pos(eqo("conf/vldb/Ganguly98","a8cB2S6Td-sJ")).
pos(eqo("conf/vldb/GardarinGT96","kOSE6UVijD8J")).
pos(eqo("conf/vldb/GardarinGT96","ywDvUjqsiPQJ")).
pos(eqo("conf/vldb/GarofalakisI97","-cCndG3a8ukJ")).
pos(eqo("conf/vldb/GarofalakisI97","aCvCz2wg854J")).
pos(eqo("conf/vldb/GehrkeRG98","G8JSWUAO2lMJ")).
pos(eqo("conf/vldb/Gibbons01","tYtl6ZxQ-_YJ")).
pos(eqo("conf/vldb/GibbonsMP97","QKnjF3UgncMJ")).
pos(eqo("conf/vldb/GilbertKMS02","kxGdQhvpi_sJ")).
pos(eqo("conf/vldb/GingrasL98","VSBQl2qbF8UJ")).
pos(eqo("conf/vldb/GoodmanRS94","8CCHAKnGJ1EJ")).
pos(eqo("conf/vldb/GravanoG95","2nMktwioqOYJ")).
pos(eqo("conf/vldb/GravanoG95","DNh5uw1WWUEJ")).
pos(eqo("conf/vldb/GravanoG95","F2mmoq6cRGMJ")).
pos(eqo("conf/vldb/GravanoG95","jXClQzlN5SgJ")).
pos(eqo("conf/vldb/GravanoG95","zbJYyUhl2cIJ")).
pos(eqo("conf/vldb/GravanoG97","CduLyvAaxVsJ")).
pos(eqo("conf/vldb/GrustKT03","CKiAavnrRH4J")).
pos(eqo("conf/vldb/Hallmark95","tiAgO7G7YuAJ")).
pos(eqo("conf/vldb/Hammond96","LDxiVdRU6EEJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","7y9SomIIAG0J")).
pos(eqo("conf/vldb/HuebschHLLSS03","B_Gmn8T4IDQJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
pos(eqo("conf/vldb/Huyn97","9OYLimeDdj0J")).
pos(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
pos(eqo("conf/vldb/IoannidisLGP96","kDWGwVa8dykJ")).
pos(eqo("conf/vldb/IoannidisLGP96","qb-jf_sQ_5kJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/vldb/JaedickeM99","XR50nxmrvFcJ")).
pos(eqo("conf/vldb/JagatheesanMPW03","InqySB8bkKkJ")).
pos(eqo("conf/vldb/JensenL01","yUDkYbmDTXIJ")).
pos(eqo("conf/vldb/JoshiBLL98","RufEbUPZNbYJ")).
pos(eqo("conf/vldb/JosifovskiR99","a58OzgW7AvUJ")).
pos(eqo("conf/vldb/KamelF94","A7WoAzxOJ9YJ")).
pos(eqo("conf/vldb/KamelF94","ONuqAb6sM3oJ")).
pos(eqo("conf/vldb/KamelF94","SuPC457J-a0J")).
pos(eqo("conf/vldb/KemperK94","qUfWV4VVxegJ")).
pos(eqo("conf/vldb/KerstenWFKBC03","Ub6YwssjyiYJ")).
pos(eqo("conf/vldb/KilgerM94","OzgnxugGCWMJ")).
pos(eqo("conf/vldb/KonigW99","6HMffRHCspAJ")).
pos(eqo("conf/vldb/KornLKF98","ewsBMN0qVa4J")).
pos(eqo("conf/vldb/KornLKF98","jKZaGhVU1WkJ")).
pos(eqo("conf/vldb/KoudasIM00","w0kVbjS1psIJ")).
pos(eqo("conf/vldb/KumarRRT99","1xbD4ssSjjUJ")).
pos(eqo("conf/vldb/KumaranH03","wW6dUVL80RYJ")).
pos(eqo("conf/vldb/LabioG96","B3unqvqyJrMJ")).
pos(eqo("conf/vldb/LernerS03","GsTq8-R1uaMJ")).
pos(eqo("conf/vldb/LernerS03","Xs8A5V9n3okJ")).
pos(eqo("conf/vldb/LiM01","vkMYwC5tzUgJ")).
pos(eqo("conf/vldb/LiRS99","cGbo_ZtYKwYJ")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/LlirbatST97","v1fsWCSPn2MJ")).
pos(eqo("conf/vldb/LuoNEW03","8n1UIzMm4VMJ")).
pos(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
pos(eqo("conf/vldb/ManegoldBK00","-7hYJxFD-AsJ")).
pos(eqo("conf/vldb/ManegoldBK00","JgdpgBpMDr4J")).
pos(eqo("conf/vldb/ManegoldBK02","KB9ZbekVNzoJ")).
pos(eqo("conf/vldb/MargaritisFT01","WOiDxLKSioAJ")).
pos(eqo("conf/vldb/MehtaD95","7c5g0Tl1lO0J")).
pos(eqo("conf/vldb/MehtaD95","lRiSWgNjNtIJ")).
pos(eqo("conf/vldb/Mina98","ButmJWjGXusJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("conf/vldb/NgH94","JA55PRiwrMQJ")).
pos(eqo("conf/vldb/OoiGT98","LJdSx1Di81MJ")).
pos(eqo("conf/vldb/OzsoyogluAAOUO02","Pb3y_NGGwjwJ")).
pos(eqo("conf/vldb/PapadiasT01","2V2bnIgsY1kJ")).
pos(eqo("conf/vldb/PapadiasT01","JtQbB9D7zkwJ")).
pos(eqo("conf/vldb/PereiraFJLS01","CZTJ00lolvYJ")).
pos(eqo("conf/vldb/PereiraFLS00","KAW0nLm2wVAJ")).
pos(eqo("conf/vldb/PoulovassilisS94","0BMQ7HirTaUJ")).
pos(eqo("conf/vldb/RamakrishnanGRSWZ95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.756661")).
pos(eqo("conf/vldb/RamamrithamABEGP00","jYGXFESkS-YJ")).
pos(eqo("conf/vldb/RamaswamyMS98","WTYQ40Rn_tUJ")).
pos(eqo("conf/vldb/RaoR99","N8XkcmIO0ysJ")).
pos(eqo("conf/vldb/RaoR99","tv4rTR2Z-I8J")).
pos(eqo("conf/vldb/RiedelGF98","xAph8JHK5WsJ")).
pos(eqo("conf/vldb/SahuguetA99","Mi0eqxwTUwEJ")).
pos(eqo("conf/vldb/SahuguetA99","PAcS8vELrawJ")).
pos(eqo("conf/vldb/SahuguetA99","VT_vPPmEIEIJ")).
pos(eqo("conf/vldb/SatheS01","L1IBwD8w1G0J")).
pos(eqo("conf/vldb/Schnase00","OdaRU442nm0J")).
pos(eqo("conf/vldb/SeligmanBNSW95","T6a86CQCuHoJ")).
pos(eqo("conf/vldb/SeshadriLR96","-Pmsximl_moJ")).
pos(eqo("conf/vldb/SetzerZ94","1tmW1mOCZqIJ")).
pos(eqo("conf/vldb/ShahDR03","FR1h4tU9FosJ")).
pos(eqo("conf/vldb/ShengBDM02","6GxdJ4jZUokJ")).
pos(eqo("conf/vldb/ShengBDM02","TdjMAASfHFoJ")).
pos(eqo("conf/vldb/ShethKMWDLPLS96","tKPVyvxSJA8J")).
pos(eqo("conf/vldb/SistlaYH94","FT4Sfn-Z7GUJ")).
pos(eqo("conf/vldb/Spaccapietra94","ZpVzTb1a7VoJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","aCZo57LF-4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","n5yJ4y54WbwJ")).
pos(eqo("conf/vldb/StillgerLMK01","OYAPM1C1DW8J")).
pos(eqo("conf/vldb/SubietaKL95","gEFY87Ma0XUJ")).
pos(eqo("conf/vldb/TamuraK99","rAHGAfoqookJ")).
pos(eqo("conf/vldb/TheodoratosS97","inPPL3lI3CcJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
pos(eqo("conf/vldb/Uhl02","n5SsAbtjBpAJ")).
pos(eqo("conf/vldb/Vieille98","nlyEH7GkrjoJ")).
pos(eqo("conf/vldb/VorugantiOU99","ItOlYY7ITt0J")).
pos(eqo("conf/vldb/Wadler01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672033")).
pos(eqo("conf/vldb/WangC03","B1uNI67mfJcJ")).
pos(eqo("conf/vldb/WangC03","yjZolbzEP6wJ")).
pos(eqo("conf/vldb/WuYCT95","A5s_U6Ixg3EJ")).
pos(eqo("conf/vldb/YanA94","8j5i7YJQnNAJ")).
pos(eqo("conf/vldb/YanA94","OcLgpNTQxIsJ")).
pos(eqo("conf/vldb/YanG95","baVAtfo4WCoJ")).
pos(eqo("conf/vldb/YanG95","lr_Kq9SZLY8J")).
pos(eqo("conf/vldb/YanL95","9B2oMksKaMMJ")).
pos(eqo("conf/vldb/YanL95","BNyeiu2AmWAJ")).
pos(eqo("conf/vldb/YanL95","JLzIM-AHdW8J")).
pos(eqo("conf/vldb/YanL95","uy8MOTvPkOsJ")).
pos(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
pos(eqo("conf/vldb/ZimbraoS98","1KckBFVfgyMJ")).
pos(eqo("conf/vldb/ZirintsisKM99","_UYteGcmBKIJ")).
pos(eqo("conf/vldb/ZirintsisKM99","sldCppj0qOEJ")).
pos(eqo("journals/sigmod/ACT-NET96","AWM-7zzaO7wJ")).
pos(eqo("journals/sigmod/Aberer01","7CLhi_LOtoUJ")).
pos(eqo("journals/sigmod/Aberer03a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","5tuINV43CDUJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","JHVWab3P4zIJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","OgBSNzmsvHUJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","qiD9O54GtckJ")).
pos(eqo("journals/sigmod/BabuW01","EWzSBh-jV3IJ")).
pos(eqo("journals/sigmod/BabuW01","kGjvvtQzEtAJ")).
pos(eqo("journals/sigmod/Baeza-YatesN96","W3NucQtmzesJ")).
pos(eqo("journals/sigmod/BerndtssonH96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381889%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BernsteinHP00","FFzJxlpy6TsJ")).
pos(eqo("journals/sigmod/BichlerSZ98","goq6Z9bDeSsJ")).
pos(eqo("journals/sigmod/BonifatiC00","EP5trsliqVMJ")).
pos(eqo("journals/sigmod/BonifatiC00","hBGcwElxNoQJ")).
pos(eqo("journals/sigmod/BunemanRU97","V6CmNS2__nUJ")).
pos(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
pos(eqo("journals/sigmod/BurtonM98","LOXd8JPfhpwJ")).
pos(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
pos(eqo("journals/sigmod/Camps96","mDj9X3EN9ycJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","OhiGJ7Gy3KgJ")).
pos(eqo("journals/sigmod/CarmelMS01","bolov3CrMYwJ")).
pos(eqo("journals/sigmod/Chang03","B55TCVoUsnoJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","IdNPV86IxM0J")).
pos(eqo("journals/sigmod/ChaudhuriD97","P-TOW5Z1snMJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","PiSKQ2TBfisJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","mzlMwJTYaDcJ")).
pos(eqo("journals/sigmod/CheungF98","ujeEtXpQFIsJ")).
pos(eqo("journals/sigmod/ClementLGMK97","To_EjIKwfSAJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","3aPleydkcIoJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","nmEhI0tiWGAJ")).
pos(eqo("journals/sigmod/CruzKLSWY02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/EisenbergM98","-RAYAJbKLNUJ")).
pos(eqo("journals/sigmod/ErdurD02","9OcrAEypDhMJ")).
pos(eqo("journals/sigmod/Etzion99","url:http://portal.acm.org/citation.cfm%3Fid%3D344816.344820%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FininJ02","rg8576nvnkUJ")).
pos(eqo("journals/sigmod/FlorescuLM98","FCcDKONgJVYJ")).
pos(eqo("journals/sigmod/FlorescuLM98","_SR_pRTnA6IJ")).
pos(eqo("journals/sigmod/FlorescuLM98","rGNdajM-asAJ")).
pos(eqo("journals/sigmod/FowlerPNB99","Mo-tkboGfcoJ")).
pos(eqo("journals/sigmod/GatziuJSV99","HtqrJuo7GSsJ")).
pos(eqo("journals/sigmod/GerlhofKM96","xsV7dkJi-YMJ")).
pos(eqo("journals/sigmod/Giorgini03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959084%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
pos(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
pos(eqo("journals/sigmod/Hainaut03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959087%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Halevy03","706PCMwA_E4J")).
pos(eqo("journals/sigmod/Han98","Y0GdVVrbzfQJ")).
pos(eqo("journals/sigmod/Han98","fowjYeJoaxgJ")).
pos(eqo("journals/sigmod/HansonN99","O5m6UXQ_Xv4J")).
pos(eqo("journals/sigmod/HansonN99","id1te58YJlUJ")).
pos(eqo("journals/sigmod/HasanFV96","m2CCumFeAWgJ")).
pos(eqo("journals/sigmod/HummerLW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JenningsNF98","vgi1l8lbDcsJ")).
pos(eqo("journals/sigmod/KaradimitriouT97","SrCBkHnIFL8J")).
pos(eqo("journals/sigmod/KiyokiKH94","xT3mwY4t5kEJ")).
pos(eqo("journals/sigmod/KlasS94","Opow89YK6a8J")).
pos(eqo("journals/sigmod/LeeCL95","G1E5PwzwdSMJ")).
pos(eqo("journals/sigmod/LightstoneLZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601873%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/McClatcheyV97","mbFxAqrWXbYJ")).
pos(eqo("journals/sigmod/MeltonE01","619anaISuGEJ")).
pos(eqo("journals/sigmod/MeltonMJKS02","cvBAdEvcTSkJ")).
pos(eqo("journals/sigmod/MusickC99","U8aV2wgTNdYJ")).
pos(eqo("journals/sigmod/MusickC99","mA4kKq9Z3tYJ")).
pos(eqo("journals/sigmod/OrlandicLS02","eLf0eStn5G4J")).
pos(eqo("journals/sigmod/PalpanasPKG03","KQ6elbYA84QJ")).
pos(eqo("journals/sigmod/PalpanasPKG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959074%26type%3Dpdf%26dl%3DGUIDE%26dl%3Dacm%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/PapianiWDN99","EHBFbc1r9oIJ")).
pos(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
pos(eqo("journals/sigmod/RisheSBDOALOSS95","pGU2Ew1AQkoJ")).
pos(eqo("journals/sigmod/Ritter98","mzqmEYGGT_IJ")).
pos(eqo("journals/sigmod/RoantreeMH99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Rosenthal98","ZMMeRrWUlOoJ")).
pos(eqo("journals/sigmod/SayginVC01","Tp9iVMsAzocJ")).
pos(eqo("journals/sigmod/Sidell96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245906%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Snodgrass03","m-l6e98xxOsJ")).
pos(eqo("journals/sigmod/SpynsMJ02","GVrDsGpbJGsJ")).
pos(eqo("journals/sigmod/SpynsMJ02","QWfa2xEybLcJ")).
pos(eqo("journals/sigmod/TanK03","-JwOe0wd0HkJ")).
pos(eqo("journals/sigmod/TanakaV01","sQu8znidi50J")).
pos(eqo("journals/sigmod/TaninBS96","KUB7XvwH30AJ")).
pos(eqo("journals/sigmod/TaninBS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245891%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/VassiliadisS99","uexel5Cdu4wJ")).
pos(eqo("journals/sigmod/Weikum02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601867%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/YanG95","tMXkkRDxvkQJ")).
pos(eqo("journals/sigmod/YauLMS99","bhVBJw9Rp3QJ")).
pos(eqo("journals/tods/AndriesCPB01","6gK7k-OqgEUJ")).
pos(eqo("journals/tods/AndriesCPB01","iMGwasyHkgIJ")).
pos(eqo("journals/tods/Bohm00","i5nEuutK3H4J")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/tods/CasatiCPP99","12JXvv17ugoJ")).
pos(eqo("journals/tods/CuiWW00","HEAX8OOSpKgJ")).
pos(eqo("journals/tods/CuiWW00","yWDXpb_76z0J")).
pos(eqo("journals/tods/Galindo-LegariaR97","Vjga5yC23KIJ")).
pos(eqo("journals/tods/GoldmanL94","VxMarpzwtzQJ")).
pos(eqo("journals/tods/GutingBEJLSV00","cURCJR2xHE0J")).
pos(eqo("journals/tods/KossmannS00","PnGVbzQCWY0J")).
pos(eqo("journals/tods/LitwinN96","eKvrxzDXW0AJ")).
pos(eqo("journals/tods/LitwinN96","l0W27c1C3NwJ")).
pos(eqo("journals/tods/LitwinN96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093386%26type%3Dpdf")).
pos(eqo("journals/tods/MuralidharS99","dKvepAPYBmcJ")).
pos(eqo("journals/tods/OliverS94","RUyqFOxZyDoJ")).
pos(eqo("journals/tods/OliverS94","zAczQV37xxsJ")).
pos(eqo("journals/tods/Revesz98","dr8s9hbwjR0J")).
pos(eqo("journals/tods/SrivastavaSRN95","zm3D83ZiU4UJ")).
pos(eqo("journals/tods/TendickM94","FxCxfE4m1rUJ")).
pos(eqo("journals/tods/WijesekeraJPH03","oui-frSWZCAJ")).
pos(eqo("journals/tods/Wijsen99","1C4Uh8BlYaEJ")).
pos(eqo("journals/tods/Wijsen99","_D3JPE9NgNgJ")).
pos(eqo("journals/tods/WinslettSQ94","lvZTVlP7s7oJ")).
pos(eqo("journals/tods/WolfsonJH97","FlC-FF1hbbUJ")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/vldb/AbadiCCCCLSTZ03","gBVNSFeS4P8J")).
pos(eqo("journals/vldb/AslanM99","vZcZ-UX6h7UJ")).
pos(eqo("journals/vldb/ChakrabartiRS03","idfox84uNHUJ")).
pos(eqo("journals/vldb/ChanGR03","wUcXmf9G52gJ")).
pos(eqo("journals/vldb/ChuIT94","IDo3ZQocZE4J")).
pos(eqo("journals/vldb/DanYC95","SsOLRJZrmtYJ")).
pos(eqo("journals/vldb/DerrMP94","a-QMCFr5yJYJ")).
pos(eqo("journals/vldb/DesslochHMMT98","4D2HQE6fXXEJ")).
pos(eqo("journals/vldb/EyalM01","ntrSSBumclMJ")).
pos(eqo("journals/vldb/GrefenVA01","fohOTTsEtIwJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","B10xHVasKUoJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","T1c1QfSdUVQJ")).
pos(eqo("journals/vldb/KellerB96","tVoqZpEEHv8J")).
pos(eqo("journals/vldb/LinJF94","EgX8AQ2wfhAJ")).
pos(eqo("journals/vldb/MehrotraKS97","6XxswNrUSk4J")).
pos(eqo("journals/vldb/PeckhamMD95","zOfVTNgEwz0J")).
pos(eqo("journals/vldb/RamakrishnanSSS94","K9jUyjxRaCwJ")).
pos(eqo("journals/vldb/RamakrishnanSSS94","rgA2DgNVPBUJ")).
pos(eqo("journals/vldb/RamamurthyDS03","vGFdY2gG8YsJ")).
pos(eqo("journals/vldb/SofferS98","miubKxLrikUJ")).
pos(eqo("journals/vldb/VaghaniRKSSLH94","B3E3_clrrrYJ")).
pos(eqo("journals/vldb/WidomS00","url:http://www.springerlink.com/index/JWGUMV8YDL893E3V.pdf")).
