neg(eqo("conf/sigmod/AbiteboulCM95","f2Lea-RN8dsJ")).
neg(eqo("conf/sigmod/AcharyaFZ97","FDPwbRQbfIAJ")).
neg(eqo("conf/sigmod/AdaliSS99","t137aLGaf-QJ")).
neg(eqo("conf/sigmod/Al-KhalifaYJ03","8unPFhv3TWEJ")).
neg(eqo("conf/sigmod/AshleyFHLNP95","s6Ax0WdZp6IJ")).
neg(eqo("conf/sigmod/BarclaySG00","7br3WXwZRQ4J")).
neg(eqo("conf/sigmod/BaulierBGGHJKKMMNNRSSSWW99","7aUag74jtdIJ")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","pzie6gFnxrkJ")).
neg(eqo("conf/sigmod/BornhovdAKMPR03","EGI4nUVWFFcJ")).
neg(eqo("conf/sigmod/BuchmannDZH95","Hi4CNHm5GfgJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","g6XLqjCRkFcJ")).
neg(eqo("conf/sigmod/ColeG94","Lg8yEjB8jmAJ")).
neg(eqo("conf/sigmod/CranorGJSS02","89Avc7qz9YoJ")).
neg(eqo("conf/sigmod/DoRD99","Rviij1nqEcoJ")).
neg(eqo("conf/sigmod/Dyreson03","rqdq3L2hw7UJ")).
neg(eqo("conf/sigmod/Fernandez94","KNuVT-oWvbEJ")).
neg(eqo("conf/sigmod/FlorescuLMS99","t19PsyGam1EJ")).
neg(eqo("conf/sigmod/GotoK03","CKScFHA8hPkJ")).
neg(eqo("conf/sigmod/GravanoCGP97","SG0_awVJwi8J")).
neg(eqo("conf/sigmod/GravanoGT94","zSO1Y5W7WkwJ")).
neg(eqo("conf/sigmod/GrayHOS96","jjhaBNByh5QJ")).
neg(eqo("conf/sigmod/Han96","ufd-pLPLfTEJ")).
neg(eqo("conf/sigmod/JoshiA01","K1nbpKn1IbsJ")).
neg(eqo("conf/sigmod/KalnisNOPT02","2bT7DvQa1lkJ")).
neg(eqo("conf/sigmod/KanthRSB99","BPCzmP7gxDMJ")).
neg(eqo("conf/sigmod/KemperKM98","qq2lTNrNTBUJ")).
neg(eqo("conf/sigmod/Kohler99","ohbpsLp-5XwJ")).
neg(eqo("conf/sigmod/Kohler99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369277%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KornackerMH97","ATI3rg3kUs4J")).
neg(eqo("conf/sigmod/LakhamrajuRSS00","NavG71q60BAJ")).
neg(eqo("conf/sigmod/McIverK94","MUXTIMdJLjgJ")).
neg(eqo("conf/sigmod/Mohan99","f9JfEpe5a24J")).
neg(eqo("conf/sigmod/MohanN94","XppwYYxOpksJ")).
neg(eqo("conf/sigmod/MumickP94","CSZqQQPMXJIJ")).
neg(eqo("conf/sigmod/Nori00","qc5WgDyRuDoJ")).
neg(eqo("conf/sigmod/PaparizosACJLNPSWWY03","HGVP9NAoF-gJ")).
neg(eqo("conf/sigmod/RamaswamyK95","lLZvMD1hjfkJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","YMluKoJrxMcJ")).
neg(eqo("conf/sigmod/Stonebraker03","SyOHqrZQEeYJ")).
neg(eqo("conf/sigmod/Stonebraker98","LjfcoraomoEJ")).
neg(eqo("conf/sigmod/TomasicGS94","IvMJ4bK708kJ")).
neg(eqo("conf/sigmod/Toyama98","nkW4iN6JqfAJ")).
neg(eqo("conf/sigmod/Weininger02","T4os1oo8vT4J")).
neg(eqo("conf/sigmod/WoelkBJOTU95","fowjYeJoaxgJ")).
neg(eqo("conf/sigmod/Wu99","h0uuqAstOPUJ")).
neg(eqo("conf/vldb/AdityaBCHNS02","2vzhAz4Yll4J")).
neg(eqo("conf/vldb/AgrawalLSS95","E7cKUUkwc1kJ")).
neg(eqo("conf/vldb/AgrawalS94","XK-KPRa2qjcJ")).
neg(eqo("conf/vldb/AmsalegFG95","-9bXTTM_M4cJ")).
neg(eqo("conf/vldb/Baumann03","0ZG8Ug23ujYJ")).
neg(eqo("conf/vldb/BlokWZPAKJ01","W9wJnFy0TDAJ")).
neg(eqo("conf/vldb/BohannonGKNS02","Fh1QPZpWHUMJ")).
neg(eqo("conf/vldb/Carey00","W6ROObWo3bIJ")).
neg(eqo("conf/vldb/ChaudhuriS94","U0w9W7YcsZwJ")).
neg(eqo("conf/vldb/Fox02","eybUiurX77sJ")).
neg(eqo("conf/vldb/GardarinGT95","DAUHADa6RjQJ")).
neg(eqo("conf/vldb/GehrkeRG98","tuVp_18tFv8J")).
neg(eqo("conf/vldb/Gentili01","5dRWr1vhXyoJ")).
neg(eqo("conf/vldb/George98","lDNAWc5SrmIJ")).
neg(eqo("conf/vldb/HaberIL95","UM1ZozyrJnIJ")).
neg(eqo("conf/vldb/HaberIL95","yAM4aRfQ5dAJ")).
neg(eqo("conf/vldb/HasanM94","iDM62ywTERUJ")).
neg(eqo("conf/vldb/HoelS95","F1bohDXUiJ4J")).
neg(eqo("conf/vldb/Ioannidis03","PshdxPlweLkJ")).
neg(eqo("conf/vldb/JagatheesanMPW03","X8Xvh1yuR0YJ")).
neg(eqo("conf/vldb/JagatheesanMPW03","hHMtxXFlyu8J")).
neg(eqo("conf/vldb/JarkeKL00","hJ8VP7FyOL0J")).
neg(eqo("conf/vldb/KeimH99","28GZ8M1ZPVYJ")).
neg(eqo("conf/vldb/KoudasGGSV03","Ecf5IeJpGi4J")).
neg(eqo("conf/vldb/LabioG96","gF4nPxSCcOMJ")).
neg(eqo("conf/vldb/LabrinidisR03","0GMNedjfVV0J")).
neg(eqo("conf/vldb/ManolescuFK01","ghIMekzCkMQJ")).
neg(eqo("conf/vldb/Mattos96","888w59-TqzYJ")).
neg(eqo("conf/vldb/MillinerBP95","kYl-9cV8gloJ")).
neg(eqo("conf/vldb/Mohan02a","5C2yfBIpwDsJ")).
neg(eqo("conf/vldb/Mohan02a","m9ZL9DoH17YJ")).
neg(eqo("conf/vldb/OrensteinK95","7ZDURed14q0J")).
neg(eqo("conf/vldb/OuzzaniAB94","LGUn5gzSItIJ")).
neg(eqo("conf/vldb/PacittMS99","cIJQ0qxrkMIJ")).
neg(eqo("conf/vldb/PereiraFLS00","LbVRMb7P_50J")).
neg(eqo("conf/vldb/RohmBSS02","CQOvghgKDEkJ")).
neg(eqo("conf/vldb/SavasereON95","y1hmJODjq7UJ")).
neg(eqo("conf/vldb/Schoning98","91_UXRZrcqkJ")).
neg(eqo("conf/vldb/ShanmugasundaramKSFF01","C5YenAgwlOsJ")).
neg(eqo("conf/vldb/Shmueli01","rEwEqoAns-gJ")).
neg(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
neg(eqo("conf/vldb/SrikantA95","_BsVmIUER44J")).
neg(eqo("conf/vldb/TaoPS02","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/WangC03","xHFVBtP2yxQJ")).
neg(eqo("journals/sigmod/Aberer03b","g2ZQ4_Qy228J")).
neg(eqo("journals/sigmod/Ahlberg96","z0jnqe4PgW8J")).
neg(eqo("journals/sigmod/BerzalM02","KNYDz76C_HsJ")).
neg(eqo("journals/sigmod/BilirisP96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.234290")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381892%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/CuiJO02","OiPYjhtc8QoJ")).
neg(eqo("journals/sigmod/DarwenD95","KUB7XvwH30AJ")).
neg(eqo("journals/sigmod/EisenbergM98a","Z1P9QnSfDuAJ")).
neg(eqo("journals/sigmod/Fong97","rgJU30QjbhkJ")).
neg(eqo("journals/sigmod/FowlerPNB99","Mo-tkboGfcoJ")).
neg(eqo("journals/sigmod/Franklin00","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/GatziuKBF98","ytRfS_upf-0J")).
neg(eqo("journals/sigmod/Gunther97","9W1idUKFt2YJ")).
neg(eqo("journals/sigmod/HanBP01","8-eaDTdtfY4J")).
neg(eqo("journals/sigmod/HanBP01","mBC03oUT8yAJ")).
neg(eqo("journals/sigmod/Libkin99a","Mi6XFWbxZ6oJ")).
neg(eqo("journals/sigmod/LinP96","907LcNUlb8oJ")).
neg(eqo("journals/sigmod/Liu03","MNvk8SChYf0J")).
neg(eqo("journals/sigmod/Liu03c","skOc65LTInYJ")).
neg(eqo("journals/sigmod/OrlandicLS02","4uCpHzY3ITgJ")).
neg(eqo("journals/sigmod/PuSW01","oAVbM_vepr8J")).
neg(eqo("journals/sigmod/Qian96","9jyzas_rFd4J")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossAJS02","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/RossGR03","Gw060IxF8VQJ")).
neg(eqo("journals/sigmod/SantucciT96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Segev95","jrDSC1jKTI4J")).
neg(eqo("journals/sigmod/ShinM94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141405%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass03c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SycaraKWL99","mdkjmWiKRr8J")).
neg(eqo("journals/sigmod/TianDCZ02","7VwJMgNYL6UJ")).
neg(eqo("journals/sigmod/VelACM01","fc8y9x82jqAJ")).
neg(eqo("journals/sigmod/Vianu03","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://pep/jae/2003/00000217/00000003/art00001%26unc%3D")).
neg(eqo("journals/sigmod/Weikum02","aUP_dQ6r-bkJ")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601871%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Winslett02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637435%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Yang94","lUXze7HIpeoJ")).
neg(eqo("journals/tods/BaralisW00","FfVIV1GfgZUJ")).
neg(eqo("journals/tods/CeriFPT94","LV6lOpI0U7QJ")).
neg(eqo("journals/tods/DekhtyarRS01","jZShiF9wrikJ")).
neg(eqo("journals/tods/DeyS96","ntqMqfgRXM4J")).
neg(eqo("journals/tods/DeySB99","DbLGmJX7UJ8J")).
neg(eqo("journals/tods/EiterLLS01","FEnoIcB6GwsJ")).
neg(eqo("journals/tods/GuoSW96","V8Ls_TYs6mgJ")).
neg(eqo("journals/tods/JacoxS03","QAhsPX__MK8J")).
neg(eqo("journals/tods/Jagadish95","gDFpwto83b4J")).
neg(eqo("journals/tods/MayL02","uIEsWFITMpIJ")).
neg(eqo("journals/tods/WinslettSQ94","khCTqDvgt10J")).
neg(eqo("journals/tods/WolfsonJH97","Ngou52TV_R4J")).
neg(eqo("journals/vldb/ApersCS02","url:http://www.springerlink.com/index/J206181T84860874.pdf")).
neg(eqo("journals/vldb/AtluriJY03","N4nyJ3C99iMJ")).
neg(eqo("journals/vldb/ChienTZ02","5smJVUm1KAYJ")).
neg(eqo("journals/vldb/Guting94","bFNUZoN0LhsJ")).
neg(eqo("journals/vldb/Han98","2MEHXBATx9EJ")).
neg(eqo("journals/vldb/LinJF94","D0L3ufxOyx4J")).
neg(eqo("journals/vldb/MaedcheMS03","8XpICeyGC2YJ")).
neg(eqo("journals/vldb/RamakrishnanSSS94","url:http://doi.wiley.com/10.1002/ace.182")).
neg(eqo("journals/vldb/TsatalosSI96","--1aoAaGkgQJ")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","Rjb06zlxbLIJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","Hf3gZHIcm58J")).
pos(eqo("conf/sigmod/AcharyaFZ97","qdCTR7WpuFUJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
pos(eqo("conf/sigmod/AdaliCPS96","I8qFyTX4FhoJ")).
pos(eqo("conf/sigmod/AdaliCPS96","_CkpzhLiR30J")).
pos(eqo("conf/sigmod/AdaliSS99","Cbwq3JSxrSAJ")).
pos(eqo("conf/sigmod/AdaliSS99","bhWLVCoDuNQJ")).
pos(eqo("conf/sigmod/AgrawalASY97","C85vtVHZmjUJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","rSTewQ1dQkYJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AltinelABFSZ99","ebmulQBhqZEJ")).
pos(eqo("conf/sigmod/BabcockBDM03","a2wqpKma5J4J")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","oulaZpEWkMQJ")).
pos(eqo("conf/sigmod/BraumandlKK99","4fjXoCHhe1kJ")).
pos(eqo("conf/sigmod/BrunoKS02","4pZ4Shr2bMwJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","GmUD1o-uPvYJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","xc1E6MOfP80J")).
pos(eqo("conf/sigmod/ChanI98","VC7Jbwgn_O0J")).
pos(eqo("conf/sigmod/ChaudhuriN98","qGTxTpQXTDsJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","JyEX0YVMP5oJ")).
pos(eqo("conf/sigmod/ChenZCKR01","RHoy5iOHsJwJ")).
pos(eqo("conf/sigmod/ClossmanSHKPB98","Q0Jr0CGWn5MJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","R4fVVmv_YvoJ")).
pos(eqo("conf/sigmod/FernandezS96","lMKrltuk53EJ")).
pos(eqo("conf/sigmod/ForlizziGNS00","vtX2CRPJunMJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","fSKep047pbgJ")).
pos(eqo("conf/sigmod/GebhardtJJ97","zbxsamf4QY8J")).
pos(eqo("conf/sigmod/GrossmanHQ95","Z_kXgQsN0W0J")).
pos(eqo("conf/sigmod/GrossmanQ94","yjqdBeNw5WoJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","QHUtoLECZzgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","ofxLw3VrJB8J")).
pos(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
pos(eqo("conf/sigmod/KaushikBNK02","xJQAjLzvlB0J")).
pos(eqo("conf/sigmod/KiesslingHFE01","tNzM8E3W2K4J")).
pos(eqo("conf/sigmod/KriegelBKPS03","i0c65loyE60J")).
pos(eqo("conf/sigmod/LaursenOP94","fTbCV3Lh8W0J")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","3tRtdT5VfDkJ")).
pos(eqo("conf/sigmod/LoR94","3CMnzSHX7KoJ")).
pos(eqo("conf/sigmod/MaddenFHH03","qz24tfFNHuoJ")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/NazeriBO01","2E9I_lugGC4J")).
pos(eqo("conf/sigmod/RafieiM97","F9KzvnDpCPUJ")).
pos(eqo("conf/sigmod/RamaswamyK95","g9Y0KAu_UHQJ")).
pos(eqo("conf/sigmod/RamaswamyK95","xnNIRajBihoJ")).
pos(eqo("conf/sigmod/RamaswamyRS00","VJIHPbki2uAJ")).
pos(eqo("conf/sigmod/RamaswamyRS00","o0vnSBVzRQcJ")).
pos(eqo("conf/sigmod/Rodriguez-Martinez00","ZX_Rn4h2st0J")).
pos(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","imAsAkfukSYJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","y8Sm4Sh4hokJ")).
pos(eqo("conf/sigmod/SagonasSW94","nDGblldnEGAJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","a7v0bHRrpjMJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wnMZjFGvYVQJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","zM0o4FoKRXIJ")).
pos(eqo("conf/sigmod/ShouCTRH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375755%26type%3Dpdf%26dl%3DGUIDE%26dl%3DGUIDE%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","0HlMHEPJRH4J")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","gYWmOPwa7mwJ")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/VanceM96","QgKRpqigXEsJ")).
pos(eqo("conf/sigmod/VingralekBW94","qtSeY_1Q5YUJ")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/YerneniLGU99","L9rzYv5OWpgJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VCc6IQulRJ4J")).
pos(eqo("conf/sigmod/ZaianeHLCC98","tFB9gJLG4_UJ")).
pos(eqo("conf/vldb/AgrawalS94","0haDaGr-V3oJ")).
pos(eqo("conf/vldb/AgrawalS94","2Z_X3zsf4CoJ")).
pos(eqo("conf/vldb/AgrawalS94","cIJQ0qxrkMIJ")).
pos(eqo("conf/vldb/AgrawalS94","kAi6HssDySgJ")).
pos(eqo("conf/vldb/AilamakiDHS01","BQtJOT7gAIIJ")).
pos(eqo("conf/vldb/AksoyZF01","z6Z1hQYHTAMJ")).
pos(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
pos(eqo("conf/vldb/BohannonGKNS02","jj64xkk75ZIJ")).
pos(eqo("conf/vldb/ChristopheBPV00","hNOti13KB_8J")).
pos(eqo("conf/vldb/CiacciaPZ97","urL_oXzvBBUJ")).
pos(eqo("conf/vldb/DarEGP98","D6gxih90YU4J")).
pos(eqo("conf/vldb/DillKMRST01","_dtqcPU4NdkJ")).
pos(eqo("conf/vldb/FegarasE01","pinPEM3Rvm0J")).
pos(eqo("conf/vldb/FuhDCMTLDRM99","nh2FuiC6fHgJ")).
pos(eqo("conf/vldb/GarofalakisOS97","dW_pRNemQfsJ")).
pos(eqo("conf/vldb/GuptaHQ95","CtRFDjCGDg8J")).
pos(eqo("conf/vldb/HaasB03","52x78w6qgcwJ")).
pos(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
pos(eqo("conf/vldb/HaasKWY97","aDDbEmg7oYYJ")).
pos(eqo("conf/vldb/HaasKWY97","o_WTRsrkx_EJ")).
pos(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
pos(eqo("conf/vldb/LeeL99","szHsyFiOuwAJ")).
pos(eqo("conf/vldb/MadhavanH03","ujCYoqKS6BcJ")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/OzsuVU98","tftfK6qWKJcJ")).
pos(eqo("conf/vldb/PedersenJD99","KG_0Ks9lFAUJ")).
pos(eqo("conf/vldb/PedersenJD99","a36_v9H699oJ")).
pos(eqo("conf/vldb/PedersenJD99","sAUncbolYJ8J")).
pos(eqo("conf/vldb/PereiraFLS00","GzZSEeVoAiUJ")).
pos(eqo("conf/vldb/PoosalaI97","QIG8th9DHbQJ")).
pos(eqo("conf/vldb/RezendeH98","njuthCBUMPAJ")).
pos(eqo("conf/vldb/RysNS96","sRcMuuo3-BEJ")).
pos(eqo("conf/vldb/SantiniG02","J3cfnmFB4lsJ")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/vldb/SchindlerAG03","CsWyDorgQF4J")).
pos(eqo("conf/vldb/Schoning98","HEJ1Z4Q_xXMJ")).
pos(eqo("conf/vldb/SeligmanBNSW95","T6a86CQCuHoJ")).
pos(eqo("conf/vldb/TheodoratosS97","inPPL3lI3CcJ")).
pos(eqo("conf/vldb/YangG01","xQYKEHCggZQJ")).
pos(eqo("conf/vldb/ZhouS03","NlDvk5J0WwEJ")).
pos(eqo("journals/sigmod/ArpinarD00","YQQMvRraFBwJ")).
pos(eqo("journals/sigmod/BargaL02","QTzV3iNq2O8J")).
pos(eqo("journals/sigmod/BergamaschiCV99","4C9A2HGs4qsJ")).
pos(eqo("journals/sigmod/BestavrosLS96","RalvsjDuKzsJ")).
pos(eqo("journals/sigmod/BorgidaCS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BuchnerM98","-3LEFj2dY-UJ")).
pos(eqo("journals/sigmod/BusslerFM02","m56HUW18JKAJ")).
pos(eqo("journals/sigmod/FernandezFLS97","9NlVdFCl2ysJ")).
pos(eqo("journals/sigmod/FernandezFLS97","LJKpMU1tIlcJ")).
pos(eqo("journals/sigmod/Geller02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HuangKL02","yyUMt1X2WXcJ")).
pos(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
pos(eqo("journals/sigmod/Huyn01","KNYDz76C_HsJ")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/Palpanas00","MGG31wuhuUIJ")).
pos(eqo("journals/sigmod/QuixSJ02","BrO3XOrt66MJ")).
pos(eqo("journals/sigmod/Ritter98","mzqmEYGGT_IJ")).
pos(eqo("journals/sigmod/SureSS02","v0tY6g0DHMcJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/Weikum02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601867%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","QTzuiNlMnR4J")).
pos(eqo("journals/tods/DekhtyarRS01","5HstPUbtZ1QJ")).
pos(eqo("journals/tods/DekhtyarRS01","ywEAyex_frMJ")).
pos(eqo("journals/tods/EiterLLS01","lTwQVB8E7SIJ")).
pos(eqo("journals/tods/FukudaMMT01","lmXiI4fB9vgJ")).
pos(eqo("journals/tods/GravanoGT99","NCv4Y_aV23EJ")).
pos(eqo("journals/tods/KarpSP03","mAQIVsd2VOMJ")).
pos(eqo("journals/tods/MuralidharS99","dKvepAPYBmcJ")).
pos(eqo("journals/tods/RosenthalR94","zM422IjZcPgJ")).
pos(eqo("journals/tods/TariSS97","iMM-Ho95algJ")).
pos(eqo("journals/vldb/BalkirO98","pSf0S8boiZ0J")).
pos(eqo("journals/vldb/BarbaraI95","7N0H3ra1FFsJ")).
pos(eqo("journals/vldb/CombiP01","8YoYzQtOgYoJ")).
pos(eqo("journals/vldb/DattaDVRN01","q0Ovw6QUk3MJ")).
pos(eqo("journals/vldb/GeorgakopoulosRL94","G85JsnuAjzMJ")).
pos(eqo("journals/vldb/Halevy01","NXKx0V8rHQQJ")).
pos(eqo("journals/vldb/HelmerM03","lqAgqxpXpxMJ")).
pos(eqo("journals/vldb/KrivokapicKG99","VGodNh5ztPkJ")).
pos(eqo("journals/vldb/Navarro02","ZAtWrc5XBlQJ")).
pos(eqo("journals/vldb/NybergBCGL95","A1phylxPkl4J")).
pos(eqo("journals/vldb/PottingerH01","M2zV0WBF7XYJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","HKM-zP0LT_UJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","ZQyBjtpbhvIJ")).
pos(eqo("journals/vldb/SheikholeslamiCZ00","Eo0JhvpLGj0J")).
