neg(eqo("conf/sigmod/AcharyaFZ97","9OEjtHuRUzsJ")).
neg(eqo("conf/sigmod/Agarwal96","EYV1vwJwBkcJ")).
neg(eqo("conf/sigmod/AggarwalY00","lsm05WjMep4J")).
neg(eqo("conf/sigmod/AgrawalS00","Yt-cq_4cfE8J")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","url:http://doi.wiley.com/10.1002/ace.106")).
neg(eqo("conf/sigmod/BertinoCF01","TJyp_PuBAWoJ")).
neg(eqo("conf/sigmod/BohlenBD99","J2ZZeE5FQvQJ")).
neg(eqo("conf/sigmod/BressanGFJHKLMPQSS97","x5OGe871yFkJ")).
neg(eqo("conf/sigmod/ChanI99","BqsA0P52CtoJ")).
neg(eqo("conf/sigmod/ChangG99","wk-LiYibt8wJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","CWZ-rse9wAgJ")).
neg(eqo("conf/sigmod/ChenCPPSTM00","iNp6OM8GywoJ")).
neg(eqo("conf/sigmod/ChenRW02","e6llu4bIOxUJ")).
neg(eqo("conf/sigmod/Cohen98","HEnlcR2tDd0J")).
neg(eqo("conf/sigmod/DeutschFS99","81K1fo8iT-gJ")).
neg(eqo("conf/sigmod/FegarasM95","ykGQlI-IaJkJ")).
neg(eqo("conf/sigmod/FernandezFKLS98","cifMTT3UYjQJ")).
neg(eqo("conf/sigmod/FernandezMS01","xqo8QahjsN0J")).
neg(eqo("conf/sigmod/Freeston95","5VR8C6g8DNoJ")).
neg(eqo("conf/sigmod/Gray95","jiJgbmwO0lAJ")).
neg(eqo("conf/sigmod/GuhaRS98","NiswbODuzhAJ")).
neg(eqo("conf/sigmod/GuoSBS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141405%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Hammond99","-ndr_jftgFkJ")).
neg(eqo("conf/sigmod/Han96","CZGjStvTkZUJ")).
neg(eqo("conf/sigmod/Hellerstein00","dtYwk-vb8DUJ")).
neg(eqo("conf/sigmod/HuangSW94","c_zaXEno5tcJ")).
neg(eqo("conf/sigmod/JonssonFS98","5fb1l1MyGisJ")).
neg(eqo("conf/sigmod/JoshiA01","H9bMRYKnXMQJ")).
neg(eqo("conf/sigmod/KangN03","CqbNc79TtBsJ")).
neg(eqo("conf/sigmod/KangN03","XDGpuS06D3EJ")).
neg(eqo("conf/sigmod/KanthAS98","YQQMvRraFBwJ")).
neg(eqo("conf/sigmod/KiesslingHFE01","e6llu4bIOxUJ")).
neg(eqo("conf/sigmod/KoudasS03","IdK_JWGTHCUJ")).
neg(eqo("conf/sigmod/Kulkarni94","dBZpkoxFR2sJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97","7zzvk7QwqJYJ")).
neg(eqo("conf/sigmod/MaddenFHH03","NXakCefUcdUJ")).
neg(eqo("conf/sigmod/Mamoulis03","e7IW2FqjtrMJ")).
neg(eqo("conf/sigmod/McAuliffeCS96","MmpM31Xn2qQJ")).
neg(eqo("conf/sigmod/Mohan01","IhBufqjoXj4J")).
neg(eqo("conf/sigmod/Mohan01","oACVY7cjTqMJ")).
neg(eqo("conf/sigmod/MoleskyR95","dfSPs7YoyWsJ")).
neg(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304245%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Pruscino03","fTbCV3Lh8W0J")).
neg(eqo("conf/sigmod/Raghavan03","__uz_kINodMJ")).
neg(eqo("conf/sigmod/Ramanan02","sX5VObgm1aIJ")).
neg(eqo("conf/sigmod/RundensteinerKRCJM96","YyqaHVc_bMoJ")).
neg(eqo("conf/sigmod/RundensteinerKZWLLN99","6x9JSA5YuNcJ")).
neg(eqo("conf/sigmod/ShenNSHS03","LjrsWIr3rhAJ")).
neg(eqo("conf/sigmod/SionAP03","pd6xxTBzc8IJ")).
neg(eqo("conf/sigmod/SzalayGTKMRSv02","P8SQPINQRHQJ")).
neg(eqo("conf/sigmod/TaoP02","cifMTT3UYjQJ")).
neg(eqo("conf/sigmod/WhiteD94","8M_z-OUkoxYJ")).
neg(eqo("conf/sigmod/WynblattN01","M77rJKiiFwYJ")).
neg(eqo("conf/sigmod/WynblattN01","Url4UfUC9yEJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D16343%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/AgrawalKSX02","DLymXxpy2qYJ")).
neg(eqo("conf/vldb/BunemanDHOW95","95LnCs7V35YJ")).
neg(eqo("conf/vldb/CasatiS00","jPx0tvkJ-fUJ")).
neg(eqo("conf/vldb/ChandrasekaranF02","url:http://www.springerlink.com/index/NXE3D2CUHN61XMMH.pdf")).
neg(eqo("conf/vldb/ChaudhuriG99","HuTZ23tc7Z8J")).
neg(eqo("conf/vldb/ChaudhuriG99","_8O1lwWiXaQJ")).
neg(eqo("conf/vldb/ChenDZ03","cCpHMzAXRnsJ")).
neg(eqo("conf/vldb/DeWittKLPY94","HsAQIEugJ8YJ")).
neg(eqo("conf/vldb/FlescaFM03","uLGZJiB9AiAJ")).
neg(eqo("conf/vldb/GalanisWJD03","ZbMPvS5i_osJ")).
neg(eqo("conf/vldb/GehrkeRG98","f6JFkfhawW8J")).
neg(eqo("conf/vldb/Gibbons01","4Gp77kxHdQ4J")).
neg(eqo("conf/vldb/GuPS00","wnke8ff8hYUJ")).
neg(eqo("conf/vldb/GuptaHQ95","LLvLD2lfW9AJ")).
neg(eqo("conf/vldb/Guting94","9KiPVAodKnYJ")).
neg(eqo("conf/vldb/HageJPST03","cVgF0jn9q6MJ")).
neg(eqo("conf/vldb/HammadFAE03","ko97r39oC3QJ")).
neg(eqo("conf/vldb/HuntAI01","0GT_dHqK5roJ")).
neg(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
neg(eqo("conf/vldb/IshikawaSF98","V3c_ivUAs34J")).
neg(eqo("conf/vldb/KeimH99","1ambq2RMGMoJ")).
neg(eqo("conf/vldb/KnorrN99","YgouJdrCoZQJ")).
neg(eqo("conf/vldb/MehtaD95","lRiSWgNjNtIJ")).
neg(eqo("conf/vldb/MorimotoIM97","3enylshvOl8J")).
neg(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
neg(eqo("conf/vldb/OzsuLON01","qqdXmdgAaMgJ")).
neg(eqo("conf/vldb/PalpanasSCP02","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/PoosalaI97","ZCere-V5xAEJ")).
neg(eqo("conf/vldb/RusinkiewiczKTWM95","oF7dI1wiKUIJ")).
neg(eqo("conf/vldb/Sarawagi95","551mHiCJRjoJ")).
neg(eqo("conf/vldb/ScheuermannSV96","sYxm_6FWG_kJ")).
neg(eqo("conf/vldb/SeshadriLR96","cL_OKIQDvmQJ")).
neg(eqo("conf/vldb/SeshadriLR97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D126494%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/ShiSZ03","5EjrRrS54fsJ")).
neg(eqo("conf/vldb/ShiSZ03","GM-rQKHqbHwJ")).
neg(eqo("conf/vldb/SreenathS94","OonCcbfDKpsJ")).
neg(eqo("conf/vldb/Toivonen96","H14pRBdznp4J")).
neg(eqo("conf/vldb/VelegrakisMP03","nOF-SuSEaaEJ")).
neg(eqo("conf/vldb/WeberSB98","nXl6rktYESYJ")).
neg(eqo("journals/sigmod/Aberer02","WryeHhngM_oJ")).
neg(eqo("journals/sigmod/AndlerHEMBE96","oNYOKYvjoKgJ")).
neg(eqo("journals/sigmod/Bernstein98","AYEI8XDoY9wJ")).
neg(eqo("journals/sigmod/BohmR94","wLNJcNvsulkJ")).
neg(eqo("journals/sigmod/Bussler02","Phcd3C1cfLcJ")).
neg(eqo("journals/sigmod/Date03","y4ZZN4xhKnUJ")).
neg(eqo("journals/sigmod/Datta94","Ey7Mbh6IdQIJ")).
neg(eqo("journals/sigmod/Domingo-FerrerH98","bnzUppOZricJ")).
neg(eqo("journals/sigmod/Franklin97","4NPsBQIM3KcJ")).
neg(eqo("journals/sigmod/Franklin97a","_cil6uzFNtsJ")).
neg(eqo("journals/sigmod/Franklin98a","8Dj_i69XP60J")).
neg(eqo("journals/sigmod/GroskySF02","HA3wM_i-y3YJ")).
neg(eqo("journals/sigmod/Han98","UkHY6IWce_wJ")).
neg(eqo("journals/sigmod/JensenCEGHJ94","WJ_VcY3mmEkJ")).
neg(eqo("journals/sigmod/JukicV97","yZbJS0Cd6cAJ")).
neg(eqo("journals/sigmod/KambhampatiK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369289%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/KeetonPH98","9xH94cKF-CYJ")).
neg(eqo("journals/sigmod/Keim96","f5l7pBBr8foJ")).
neg(eqo("journals/sigmod/Keim96","yLcOnaP14zoJ")).
neg(eqo("journals/sigmod/Kim99","gU-dOX4-eeYJ")).
neg(eqo("journals/sigmod/KoubarakisTID03","g8mLb6UD-QUJ")).
neg(eqo("journals/sigmod/Labrinidis01","HdSwBBjSjN0J")).
neg(eqo("journals/sigmod/LeeCL95","url:http://portal.acm.org/citation.cfm%3Fid%3D983070.983072%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Libkin99","OfZWx8jhQvwJ")).
neg(eqo("journals/sigmod/Liu03a","8CKDKUPVOnwJ")).
neg(eqo("journals/sigmod/McHughW97","OFJiEhOkDwUJ")).
neg(eqo("journals/sigmod/NgH95","n7TUr9zgAuIJ")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","GfvntjAdvVYJ")).
neg(eqo("journals/sigmod/RossAA02","bURBdAYFSAgJ")).
neg(eqo("journals/sigmod/Segev94a","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/ShethM02","A0p0Ao13d-0J")).
neg(eqo("journals/sigmod/ShethMKA01","Q-f3lLhATCkJ")).
neg(eqo("journals/sigmod/VelACM01","url:http://doi.wiley.com/10.1002/tl.3")).
neg(eqo("journals/sigmod/Wade96","NKlbiD9mCVEJ")).
neg(eqo("journals/sigmod/Wu02","nOUmvN1TzdMJ")).
neg(eqo("journals/tods/BertinoBFS98","BTIrFatQWQsJ")).
neg(eqo("journals/tods/BunemanO96","xCbXlJHLR48J")).
neg(eqo("journals/tods/KemmeA00","NlMndaTvroEJ")).
neg(eqo("journals/tods/KossmannS00","DOWitkb7PbUJ")).
neg(eqo("journals/tods/Lerner00","mUjwOoR-X5MJ")).
neg(eqo("journals/tods/MamoulisP01","qXHdy9ingMoJ")).
neg(eqo("journals/tods/MelnikG03","LNGZsCHYRuwJ")).
neg(eqo("journals/tods/PetersO97","YaNyX_JR1ysJ")).
neg(eqo("journals/vldb/AbiteboulCM98","Gg_hzK5ZPW0J")).
neg(eqo("journals/vldb/ChakrabartiGRS01","htMO0uWGzvoJ")).
neg(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
neg(eqo("journals/vldb/DoanMDDH03","A8Wi3lvJYV8J")).
neg(eqo("journals/vldb/Halevy02","url:http://www.springerlink.com/index/CBHRGBHFTW90N54X.pdf")).
neg(eqo("journals/vldb/Ozsu03","3GY5tow6VagJ")).
neg(eqo("journals/vldb/RamamohanaraoH94","GdvZvvRTXIAJ")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","AxpQwgyRyLgJ")).
pos(eqo("conf/sigmod/Agarwal96","Ca-BABwlsQAJ")).
pos(eqo("conf/sigmod/AgrawalCFGHIIMMSS94","bXnzC8MN_joJ")).
pos(eqo("conf/sigmod/BersonGMJ94","wsG_Q2jbgCAJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","2J_9scP1caYJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","wF2-sxlGAu4J")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/BreunigKKS01","3ET_IEkoGjYJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","GmUD1o-uPvYJ")).
pos(eqo("conf/sigmod/ChaudhuriGN02","y461yNb2GEcJ")).
pos(eqo("conf/sigmod/ChenRW02","05ShsIGjnKkJ")).
pos(eqo("conf/sigmod/ChoG00","7TNK4262ozwJ")).
pos(eqo("conf/sigmod/DraperHW01","6csUZFROjIEJ")).
pos(eqo("conf/sigmod/DreyerDS95","Qf8OS1o2YM4J")).
pos(eqo("conf/sigmod/GriffinL95","6QZGeKna5lgJ")).
pos(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","VEDf7vb98i8J")).
pos(eqo("conf/sigmod/GuoSBS03","p_PDgjVRUS4J")).
pos(eqo("conf/sigmod/HacigumusILM02","zMRWZaFMRhQJ")).
pos(eqo("conf/sigmod/HanKS97","XFCkL9QhTjIJ")).
pos(eqo("conf/sigmod/HanPY00","2xwKDuA0DI8J")).
pos(eqo("conf/sigmod/HanPY00","GlNt7w28aE8J")).
pos(eqo("conf/sigmod/HanPY00","oeBeDPX7b9kJ")).
pos(eqo("conf/sigmod/HellersteinN96","PrDCERVl9dUJ")).
pos(eqo("conf/sigmod/HellersteinN96","vCvPdFwbKWkJ")).
pos(eqo("conf/sigmod/KoudasS97","sB-nvl5829EJ")).
pos(eqo("conf/sigmod/LarsonG98","QmBz3hMOFh4J")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","3tRtdT5VfDkJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","9Ho84Ho6xuIJ")).
pos(eqo("conf/sigmod/Miller98","0B1XRTZ8cHkJ")).
pos(eqo("conf/sigmod/Miller98","_ExuZq1BkEkJ")).
pos(eqo("conf/sigmod/Miller98","fW6JIoNRqAQJ")).
pos(eqo("conf/sigmod/MiloAABN03","P7vZf4MkRO4J")).
pos(eqo("conf/sigmod/MistryRSR01","r62IMncHe0IJ")).
pos(eqo("conf/sigmod/Mohan02","qbrkg2DRU3AJ")).
pos(eqo("conf/sigmod/MotakisZ97","HPPJQPCzTEcJ")).
pos(eqo("conf/sigmod/MotakisZ97","e8OIK3dEo6EJ")).
pos(eqo("conf/sigmod/Mylopoulos98","vU_Vo2059VUJ")).
pos(eqo("conf/sigmod/NatsevRS99","Y3nejQSVKnUJ")).
pos(eqo("conf/sigmod/OlstonWACELSS98","UTYa5uf9zSIJ")).
pos(eqo("conf/sigmod/ParkCY95","A3XtQdi1j5UJ")).
pos(eqo("conf/sigmod/ParkCY95","ko0i4AzclBgJ")).
pos(eqo("conf/sigmod/PatelD96","Goan1fI4O_oJ")).
pos(eqo("conf/sigmod/QunLO03","BnNNuVfklfcJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","nyHFfFtClVsJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","3OxZS395vDcJ")).
pos(eqo("conf/sigmod/Team99","DphRY0uPqi8J")).
pos(eqo("conf/sigmod/Team99","bcR9TErOrKQJ")).
pos(eqo("conf/sigmod/ViglasN02","2aeb_pBP7lcJ")).
pos(eqo("conf/sigmod/YanMHF01","8hRWaIVZ2ykJ")).
pos(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
pos(eqo("conf/sigmod/ZouS96","qPCh8M_RSwEJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","VhJatmjKuU8J")).
pos(eqo("conf/vldb/AgrawalPWZ95","mB8W6em6zi8J")).
pos(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","-FP8UTv_smkJ")).
pos(eqo("conf/vldb/AmielBDS94","hBak02oe1GMJ")).
pos(eqo("conf/vldb/BarjaPFWD94","qhl9_KGvjcUJ")).
pos(eqo("conf/vldb/BenediktCFRZZ02","7xe6Gp9fIEEJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/Bhashyam96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245908%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/BliujuteJSS98","gybR2qK1ib8J")).
pos(eqo("conf/vldb/BliujuteJSS98","qWGJZFXi414J")).
pos(eqo("conf/vldb/BohannonLRSSS97","GzK2N5eQ0pQJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","Vj1kbPjzSHwJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","thTt2lg4_Z8J")).
pos(eqo("conf/vldb/BouganimP02","PhERWOcOkOgJ")).
pos(eqo("conf/vldb/CarinoO98","q0LbTnnGsIsJ")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChienTZ01","eWCz_YJFqjcJ")).
pos(eqo("conf/vldb/ChienVZTZ02","uUmeAkW_FFUJ")).
pos(eqo("conf/vldb/ChoG00","0ofvccnIJ-0J")).
pos(eqo("conf/vldb/ChoG00","wiJ5R_mwWAYJ")).
pos(eqo("conf/vldb/DarFJST96","ThLxMqqAxjIJ")).
pos(eqo("conf/vldb/DarFJST96","Ui5dxm-mCN8J")).
pos(eqo("conf/vldb/DeWittKLPY94","WbnSYesbN8QJ")).
pos(eqo("conf/vldb/GrustKT03","CKiAavnrRH4J")).
pos(eqo("conf/vldb/Guting94","ykx565n8SRkJ")).
pos(eqo("conf/vldb/HulgeriS03","l5_H15LkpCsJ")).
pos(eqo("conf/vldb/IoannidisP99","BlALg9KQCLAJ")).
pos(eqo("conf/vldb/LakshmiZ98","3XwLBVHUBvAJ")).
pos(eqo("conf/vldb/LernerS03","Xs8A5V9n3okJ")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/MarronL01","MiMYGwqrGY8J")).
pos(eqo("conf/vldb/MorimotoFMTY98","9sydmlCRr4cJ")).
pos(eqo("conf/vldb/MorishimaKKT01","8hDo6qczOzMJ")).
pos(eqo("conf/vldb/OrensteinK95","Trw6DEZeqTsJ")).
pos(eqo("conf/vldb/OuzzaniAB94","p0TLPzS0K4oJ")).
pos(eqo("conf/vldb/PardonA00","Bax8yKEV6McJ")).
pos(eqo("conf/vldb/RiedelGF98","DFXKdJJtFsQJ")).
pos(eqo("conf/vldb/RiedelGF98","f2N_DxLirWIJ")).
pos(eqo("conf/vldb/SavasereON95","c4m40zywvWsJ")).
pos(eqo("conf/vldb/SavasereON95","tX0hBHC5_UQJ")).
pos(eqo("conf/vldb/SeshadriLR97","ad-TVNZBg8YJ")).
pos(eqo("conf/vldb/SeshadriLR97","jSAtXghimR0J")).
pos(eqo("conf/vldb/SevcikK96","GiHrMj3vbSAJ")).
pos(eqo("conf/vldb/ShahDR03","HGJu1Uyq-OcJ")).
pos(eqo("conf/vldb/ShahDR03","Zlk6Tn-sPxwJ")).
pos(eqo("conf/vldb/ShegalovWBL02","JJU5rDt2jsYJ")).
pos(eqo("conf/vldb/ShengBDM02","ZQdRRjCxEX0J")).
pos(eqo("conf/vldb/Suciu96","GwvN1w9_ZZoJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/Tygar98","lWMzZgqNlSEJ")).
pos(eqo("conf/vldb/VriesDBA99","3o-rUvRsdUwJ")).
pos(eqo("conf/vldb/WeberSB98","ZLYsIub53eoJ")).
pos(eqo("journals/sigmod/Baeza-YatesN96","1avO1fqtQ6QJ")).
pos(eqo("journals/sigmod/Baeza-YatesN96","W3NucQtmzesJ")).
pos(eqo("journals/sigmod/BergamaschiCV99","4C9A2HGs4qsJ")).
pos(eqo("journals/sigmod/BergamaschiCV99","rIm9uDX6PHUJ")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","SRemicnI-ncJ")).
pos(eqo("journals/sigmod/Fankhauser01","_sltXCfRKhYJ")).
pos(eqo("journals/sigmod/FrankNS02","YeD6vittJSMJ")).
pos(eqo("journals/sigmod/HalkidiBV02","GHjgDrEbqM4J")).
pos(eqo("journals/sigmod/Han98","fowjYeJoaxgJ")).
pos(eqo("journals/sigmod/Han98","lwZ7EjZwrZ0J")).
pos(eqo("journals/sigmod/KimballS95","E6Z68tQL1BsJ")).
pos(eqo("journals/sigmod/KimballS95","ga66OWjHdoUJ")).
pos(eqo("journals/sigmod/Kumar03","VuNnpxJwvQkJ")).
pos(eqo("journals/sigmod/MalaikaEM03","OGh0R54BW0MJ")).
pos(eqo("journals/sigmod/MalaikaEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945739%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltonE01","619anaISuGEJ")).
pos(eqo("journals/sigmod/Seshadri98","XijyPb231fAJ")).
pos(eqo("journals/sigmod/SonDT96","62uEWBKYqgoJ")).
pos(eqo("journals/sigmod/StolfoLCFE01","lvIPWxkN4YAJ")).
pos(eqo("journals/sigmod/Yang94","sHJ914nPZtUJ")).
pos(eqo("journals/tods/DekhtyarRS01","9U0LKc8qS2kJ")).
pos(eqo("journals/tods/DeyS96","l2y2U5f48WcJ")).
pos(eqo("journals/tods/DeyS96","uZVc1wSi3y4J")).
pos(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
pos(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
pos(eqo("journals/tods/FukudaMMT01","sOBRaiLLvZgJ")).
pos(eqo("journals/tods/GravanoGT99","aXLcAfb2y5kJ")).
pos(eqo("journals/tods/KonopnickiS98","5cWufy7ZrAoJ")).
pos(eqo("journals/tods/LitwinN96","l0W27c1C3NwJ")).
pos(eqo("journals/tods/LitwinN96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093386%26type%3Dpdf")).
pos(eqo("journals/vldb/AslanM99","vZcZ-UX6h7UJ")).
pos(eqo("journals/vldb/DoanMDDH03","InzqepkG0W8J")).
pos(eqo("journals/vldb/KellerB96","Y5-Iqr5NcY8J")).
pos(eqo("journals/vldb/LandauST95","E8U_krxA1dsJ")).
pos(eqo("journals/vldb/NgS98","I6aKO-jLBmgJ")).
pos(eqo("journals/vldb/PapadiasS94","kEte3P_QB60J")).
pos(eqo("journals/vldb/RamamohanaraoH94","UiWvxN_y9SAJ")).
pos(eqo("journals/vldb/RamamohanaraoH94","bFNUZoN0LhsJ")).
