neg(eqo("conf/sigmod/AcharyaAFZ95","zISF-4KuUw4J")).
neg(eqo("conf/sigmod/Aggarwal02","YfRa7vdel-kJ")).
neg(eqo("conf/sigmod/AgrawalGGR98","x8fDHaNkSUIJ")).
neg(eqo("conf/sigmod/ArefBV95","ELtcV7mOQDgJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","c57d3rgd3IcJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","_hDCldPyum0J")).
neg(eqo("conf/sigmod/ChaudhuriMN99","PiSKQ2TBfisJ")).
neg(eqo("conf/sigmod/ChenGM01","uTTqPSoH_YgJ")).
neg(eqo("conf/sigmod/CluetDSS98","eU-7sSXW5jEJ")).
neg(eqo("conf/sigmod/Colliat03","url:http://portal.acm.org/citation.cfm%3Fid%3D50225")).
neg(eqo("conf/sigmod/DoRD99","OewAZ4AUDOQJ")).
neg(eqo("conf/sigmod/FaginKS03","Z_Nekpp5eloJ")).
neg(eqo("conf/sigmod/FaloutsosL95","x_IDS457oq8J")).
neg(eqo("conf/sigmod/FaloutsosRM94","4JLP54QgDmkJ")).
neg(eqo("conf/sigmod/FernandezS96","66uAX5EPtKcJ")).
neg(eqo("conf/sigmod/FreedmanD95","dt4Mxy8b2hwJ")).
neg(eqo("conf/sigmod/FukudaMMT96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GardarinMP95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031591%26type%3Dpdf")).
neg(eqo("conf/sigmod/GarofalakisI96","M-1Nbw1n-PQJ")).
neg(eqo("conf/sigmod/GuptaMR95","75BD5JhAlbsJ")).
neg(eqo("conf/sigmod/Han96","MqDNCsx8TYkJ")).
neg(eqo("conf/sigmod/HanKS97","YkKV8PCox8IJ")).
neg(eqo("conf/sigmod/IoannidisP95","23K90oRfbbsJ")).
neg(eqo("conf/sigmod/JaedickeM98","wMwVFe45a9AJ")).
neg(eqo("conf/sigmod/Jagadish94","DDsUsPo4f2YJ")).
neg(eqo("conf/sigmod/JagatheesanR03","62dYhKYVkNYJ")).
neg(eqo("conf/sigmod/KarbhariRXD02","OQz4P5Iv-g0J")).
neg(eqo("conf/sigmod/LabrinidisR00","6rcTxplRGoEJ")).
neg(eqo("conf/sigmod/LacroixSC98","MyaiGcr-oYkJ")).
neg(eqo("conf/sigmod/LiuHBPT99","PKQ1dCQIwi0J")).
neg(eqo("conf/sigmod/MaratheS99","z6JEYoArZmsJ")).
neg(eqo("conf/sigmod/MassariPSC95","RKNGp2gmOTUJ")).
neg(eqo("conf/sigmod/Mohan01","p76h6FURbykJ")).
neg(eqo("conf/sigmod/Mohan94","qbrkg2DRU3AJ")).
neg(eqo("conf/sigmod/MoonSL00","4QQGBxlTlXUJ")).
neg(eqo("conf/sigmod/Ojjeh99","viaGlgrkhgEJ")).
neg(eqo("conf/sigmod/Olson95","j2GYY75JSWsJ")).
neg(eqo("conf/sigmod/OlstonW02","QcUC-6OtvLMJ")).
neg(eqo("conf/sigmod/Perna95","kEhVApwrTEwJ")).
neg(eqo("conf/sigmod/PolyzotisG02","E9ois9WJH38J")).
neg(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
neg(eqo("conf/sigmod/ProcopiucJAM02","RWfEPrcTAMkJ")).
neg(eqo("conf/sigmod/QuassWGHLMNRRAUW96","s54pMOqTUR8J")).
neg(eqo("conf/sigmod/Ramanan02","CXXD8FE-zpIJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","hYBvJ9mXIZ4J")).
neg(eqo("conf/sigmod/RamaswamyRS00","wMhXlYbxeZ8J")).
neg(eqo("conf/sigmod/RinfretOO01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290604%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Rodriguez-Martinez00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369289%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SalemBCL00","sq9LoMHDC3gJ")).
neg(eqo("conf/sigmod/SeshadriP97","II0NxgqC0KIJ")).
neg(eqo("conf/sigmod/SeshadriP97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107500%26type%3Dpdf")).
neg(eqo("conf/sigmod/SrikantA96","Cm66C3yYtdgJ")).
neg(eqo("conf/sigmod/SubramanianV98","yZy4PLAKiKsJ")).
neg(eqo("conf/sigmod/YuMWL01","lkreWUl_euYJ")).
neg(eqo("conf/sigmod/ZhouR02","GBFOUFQht4wJ")).
neg(eqo("conf/sigmod/ZhuS03","Ynt8Na5eF4sJ")).
neg(eqo("conf/vldb/AltinelF00","bcLR5pNZMvAJ")).
neg(eqo("conf/vldb/AmmannJR95","HLrteP7x0doJ")).
neg(eqo("conf/vldb/AshwinGG02","nBHS2BTx-GkJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","lQnI0zKr5kYJ")).
neg(eqo("conf/vldb/Chiueh94","PKK2ak_IzrgJ")).
neg(eqo("conf/vldb/ChristopheBPV00","q42RuW4_FogJ")).
neg(eqo("conf/vldb/CuiW01","6iNHLbMgFaEJ")).
neg(eqo("conf/vldb/DiligentiCLGG00","_lfz6ZJS2P0J")).
neg(eqo("conf/vldb/DongHLPW01","5RS8T9xjeLQJ")).
neg(eqo("conf/vldb/FaloutsosJS97","LWkKHDF9dEgJ")).
neg(eqo("conf/vldb/Ganguly98","7y9SomIIAG0J")).
neg(eqo("conf/vldb/Gibbons01","p-6-ZHIZ9DYJ")).
neg(eqo("conf/vldb/GravanoG95","DNh5uw1WWUEJ")).
neg(eqo("conf/vldb/Gupta96","ELtcV7mOQDgJ")).
neg(eqo("conf/vldb/HaasKU99","Qm-R5P341asJ")).
neg(eqo("conf/vldb/Jamil97","A6w0vRtdzswJ")).
neg(eqo("conf/vldb/JohnsonM98","9-uzLKJstwYJ")).
neg(eqo("conf/vldb/Kiessling02","6Rn6hsdao-wJ")).
neg(eqo("conf/vldb/LabioYCGW00","-UILVcP4CZ8J")).
neg(eqo("conf/vldb/LongS03","kHi1YOTBmlkJ")).
neg(eqo("conf/vldb/MatiasVW00","7SeTnikjovEJ")).
neg(eqo("conf/vldb/MengLYWCR98","k8EsgEuKhQ0J")).
neg(eqo("conf/vldb/Mohan02a","eE98qv4oVnQJ")).
neg(eqo("conf/vldb/Mohan99","x5Po0pdoKcQJ")).
neg(eqo("conf/vldb/NetzCBF00","mRIRFxOC8A8J")).
neg(eqo("conf/vldb/OzsoyogluAAOUO02","0Yw58WvaBxEJ")).
neg(eqo("conf/vldb/PedersenJD99","sAUncbolYJ8J")).
neg(eqo("conf/vldb/RoussopoulosK98","YRDHJBm9jTIJ")).
neg(eqo("conf/vldb/RysNS96","KUB7XvwH30AJ")).
neg(eqo("conf/vldb/Sacks-Davis96","nXl6rktYESYJ")).
neg(eqo("conf/vldb/SeshadriLR96","i2KB69gKpXUJ")).
neg(eqo("conf/vldb/ShanmugasundaramSBCLPR00","yxo4sa8_vQoJ")).
neg(eqo("conf/vldb/StolteA02","itZZmTVKRREJ")).
neg(eqo("conf/vldb/StolteA02","qVljiTzm2-cJ")).
neg(eqo("conf/vldb/TorloneA03","2f7-ISogcpcJ")).
neg(eqo("conf/vldb/TorloneA03","url:http://portal.acm.org/citation.cfm%3Fid%3D1041410.1041433")).
neg(eqo("conf/vldb/Uhl02","bIQj-GxuezAJ")).
neg(eqo("conf/vldb/VenkataramanZ98","qln9vrX5_boJ")).
neg(eqo("conf/vldb/WangHH00","NiyGvhgzXxAJ")).
neg(eqo("journals/sigmod/Aberer03d","g2ZQ4_Qy228J")).
neg(eqo("journals/sigmod/Aberer03d","url:http://doi.wiley.com/10.1002/he.103")).
neg(eqo("journals/sigmod/AbererCH02","4GT0Krd9RP0J")).
neg(eqo("journals/sigmod/AbererCH02","IHPilG_MCDoJ")).
neg(eqo("journals/sigmod/BargaL02","url:http://doi.wiley.com/10.1002/ace.78")).
neg(eqo("journals/sigmod/ChaudhuriD97","k25oXJit8HoJ")).
neg(eqo("journals/sigmod/ChristoffelPSL98","F7QAoJ5PGekJ")).
neg(eqo("journals/sigmod/ChristoffelPSL98","xfWGb928UfcJ")).
neg(eqo("journals/sigmod/DogacDKOONEHAKKM95","wTJy5XquCpsJ")).
neg(eqo("journals/sigmod/Franklin00","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/GottlobKP03a","dYLoII0SKa8J")).
neg(eqo("journals/sigmod/HellersteinHM03","krZxZPqdG6wJ")).
neg(eqo("journals/sigmod/HummerLW02","YWKrXdECxbwJ")).
neg(eqo("journals/sigmod/JenningsNF98","YiZVv5kVDb4J")).
neg(eqo("journals/sigmod/KimballS95","p_ywF1JfkAAJ")).
neg(eqo("journals/sigmod/KuoM96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1027550%26type%3Dpdf")).
neg(eqo("journals/sigmod/KuoM96","vmwgqLkw0NUJ")).
neg(eqo("journals/sigmod/Ley00","-ogWbJjtYnUJ")).
neg(eqo("journals/sigmod/MeltonMJKSZ01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000003/art00025")).
neg(eqo("journals/sigmod/QuixSJ02","UQNt6tlbxaQJ")).
neg(eqo("journals/sigmod/RoantreeMH99","61cw9DcC6qsJ")).
neg(eqo("journals/sigmod/RoddickABDEGHLMMMW00","YemauUgIzlcJ")).
neg(eqo("journals/sigmod/RoddickABDEGHLMMMW00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344789%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SantucciT96","B2kQ4R1DIQcJ")).
neg(eqo("journals/sigmod/SayginVC01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604271%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SnodgrassGIMSU98","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/SouzaS99","szcVumclSzoJ")).
neg(eqo("journals/sigmod/TianDCZ02","qsBf32GZ2EoJ")).
neg(eqo("journals/sigmod/Widom95","RFd0c3lXk1AJ")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/citation.cfm%3Fid%3D1083784.1083802")).
neg(eqo("journals/sigmod/ZobelMR96","tdDLf6RffisJ")).
neg(eqo("journals/tods/BunemanO96","e7IW2FqjtrMJ")).
neg(eqo("journals/tods/FormicaGM98","7KESeQnHfHkJ")).
neg(eqo("journals/tods/FranklinCL97","_Ur0Rv3cKb8J")).
neg(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
neg(eqo("journals/tods/HjaltasonS03","9Wan9sPNUAYJ")).
neg(eqo("journals/tods/ScioreSR94","url:http://portal.acm.org/citation.cfm%3Fid%3D192593.197379%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D192593%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Multimedia%2520Conference%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/ChanFGR02","AJ7Qj_bt0ZoJ")).
neg(eqo("journals/vldb/ChuIT94","HEnlcR2tDd0J")).
neg(eqo("journals/vldb/ChuIT94","k3znuHyMD0oJ")).
neg(eqo("journals/vldb/CliftonGB95","Ns71H6psQOgJ")).
neg(eqo("journals/vldb/GrefenVA01","_dOpWA3QWOEJ")).
neg(eqo("journals/vldb/LawLG99","bE9NgyKXDBAJ")).
neg(eqo("journals/vldb/ManegoldBK00","Qp4ZDk8gl8UJ")).
neg(eqo("journals/vldb/ShyyASL96","kkW473K7AGsJ")).
pos(eqo("conf/sigmod/AboulnagaC99","WWaxLMIptTMJ")).
pos(eqo("conf/sigmod/AdaliBSS98","YQ90BYSVqbsJ")).
pos(eqo("conf/sigmod/AdaliCPS96","pw234_REfHUJ")).
pos(eqo("conf/sigmod/AdaliCPS96","zE4iM0h4W2sJ")).
pos(eqo("conf/sigmod/AgrawalASY97","-XBy73K2jq0J")).
pos(eqo("conf/sigmod/AgrawalASY97","bDiNQAdf8nEJ")).
pos(eqo("conf/sigmod/AndersonBKW98","H6eMdbXATmkJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","K1ZdQsRoNloJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","jSUcrxtXhw4J")).
pos(eqo("conf/sigmod/BabyCY01","rNoNn5hWsroJ")).
pos(eqo("conf/sigmod/BarbaraI94","UI4WYndJlyIJ")).
pos(eqo("conf/sigmod/BerchtoldK98","VuMPPr6k95AJ")).
pos(eqo("conf/sigmod/BreitbartKRSS99","XV2lpkhWCsYJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","_1drQdYrtmsJ")).
pos(eqo("conf/sigmod/CallanCD99","eWVreKOw_QgJ")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/CandanLLHA01","efYVCK07AwMJ")).
pos(eqo("conf/sigmod/CareyK97","G2RzED0JGvoJ")).
pos(eqo("conf/sigmod/CareyMN97","6YXYnLb8CyYJ")).
pos(eqo("conf/sigmod/Chaudhuri97","QkyXMep2bWsJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","4zZ7Lxt4PPIJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","jsapF3OoWXcJ")).
pos(eqo("conf/sigmod/ChawatheG97","5O88Bum19wAJ")).
pos(eqo("conf/sigmod/ChenDLT00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.336560")).
pos(eqo("conf/sigmod/CookKWZ96","5MTgNlhnyTgJ")).
pos(eqo("conf/sigmod/DeshpandeNGS03","aBiqHXGXoJEJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","SYV3r4_a5EsJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","fsa72WmA67kJ")).
pos(eqo("conf/sigmod/DoppelhammerHKK97","LUfRqM48JaEJ")).
pos(eqo("conf/sigmod/DoppelhammerHKK97","q_A8Y8KY9WkJ")).
pos(eqo("conf/sigmod/FreireHRRS02","Pg-vbrBME1cJ")).
pos(eqo("conf/sigmod/GillmannWSWW00","3bYCefUMXr8J")).
pos(eqo("conf/sigmod/GillmannWSWW00","L61_1TEGBLYJ")).
pos(eqo("conf/sigmod/GravanoGT94","OYFpMlm5yCQJ")).
pos(eqo("conf/sigmod/GriffinL95","6QZGeKna5lgJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","ASfROcKWFmgJ")).
pos(eqo("conf/sigmod/HanFHCC94","dvmROCT52KoJ")).
pos(eqo("conf/sigmod/HanPLJ01","H_tzR6yoJLEJ")).
pos(eqo("conf/sigmod/JagatheesanR03","InqySB8bkKkJ")).
pos(eqo("conf/sigmod/JohnsonD03","5OYgUpRggiMJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","A3TmzWOtgmYJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","vO7aBWspoyMJ")).
pos(eqo("conf/sigmod/KemperKM98","Z0oCigN4pVMJ")).
pos(eqo("conf/sigmod/KiesslingHFE01","tNzM8E3W2K4J")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/KotidisR99","qzjtGDo7OuMJ")).
pos(eqo("conf/sigmod/Larson01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375792%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/LeeKOTM00","C8RLbWKCgicJ")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/Maguire01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375742%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/NatsevRS99","r2jkzqMSE0gJ")).
pos(eqo("conf/sigmod/Nori00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.335474")).
pos(eqo("conf/sigmod/ParkKKLPC98","F8CacVSkztEJ")).
pos(eqo("conf/sigmod/PatelD96","Goan1fI4O_oJ")).
pos(eqo("conf/sigmod/PatelYKTNBHRLEKGDN97","0inuMFZSQ50J")).
pos(eqo("conf/sigmod/RaoZML02","c2PgXbSSAFcJ")).
pos(eqo("conf/sigmod/RiedewaldAA02","nQvBo5KHITYJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","38HoFGLnxkQJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","CXih3vmijaoJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","nyHFfFtClVsJ")).
pos(eqo("conf/sigmod/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/ShashaB02a","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/SistlaW95","gLjn4f4f63wJ")).
pos(eqo("conf/sigmod/TatarinovIHW01","zEHD3Nn_9nsJ")).
pos(eqo("conf/sigmod/Ubell94","lphlTARDI9YJ")).
pos(eqo("conf/sigmod/YangM97","d2tXju_pTkYJ")).
pos(eqo("conf/sigmod/YangWYH02","xsaovu54vl4J")).
pos(eqo("conf/vldb/AbiteboulACEMM99","hh9fQmB-eEEJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","VhJatmjKuU8J")).
pos(eqo("conf/vldb/AksoyZF01","A92KQRVdZaoJ")).
pos(eqo("conf/vldb/AmmannJR95","x-H7BqZ0Hw8J")).
pos(eqo("conf/vldb/BelussiF95","C-Hz6btw11gJ")).
pos(eqo("conf/vldb/BrownG01","aJoPVuDNDSsJ")).
pos(eqo("conf/vldb/BrownS95","F-v-VG2RBQoJ")).
pos(eqo("conf/vldb/ChungCLL01","mJiDvbtTKWoJ")).
pos(eqo("conf/vldb/DoR02","0oPfKUylwgEJ")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("conf/vldb/GilbertKMS02","kxGdQhvpi_sJ")).
pos(eqo("conf/vldb/GilbertKMS02","xziY9wNuVzwJ")).
pos(eqo("conf/vldb/GoldmanSVG98","b3H6Yt4f7hAJ")).
pos(eqo("conf/vldb/GoldmanSVG98","pweOUtA2iTAJ")).
pos(eqo("conf/vldb/HasanM95","-aml_OMAQNgJ")).
pos(eqo("conf/vldb/HristidisP02","rZJLf9oQ_hEJ")).
pos(eqo("conf/vldb/JagadishKMPSS98","0TmcLmakam0J")).
pos(eqo("conf/vldb/JagadishKNS99","GtXc02EJjCgJ")).
pos(eqo("conf/vldb/JohnsonM98","cTZLUZ5_cfkJ")).
pos(eqo("conf/vldb/LakshmananPZ03","zbzO-4fuIwUJ")).
pos(eqo("conf/vldb/LakshmananSS96","AVyGNVp-ENcJ")).
pos(eqo("conf/vldb/LakshmananSS96","GDmbzrUbyzAJ")).
pos(eqo("conf/vldb/LakshmananSS96","IJyunaAcul8J")).
pos(eqo("conf/vldb/LakshmananSS96","XPjpq3h5BhUJ")).
pos(eqo("conf/vldb/LitwinNS94","Ass0qgT-aa4J")).
pos(eqo("conf/vldb/LitwinNS94","Nag68vKZFLgJ")).
pos(eqo("conf/vldb/LuTD95","U9EN84liiRoJ")).
pos(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
pos(eqo("conf/vldb/May01","Fb4oYRM9N4EJ")).
pos(eqo("conf/vldb/Moni96","gbjXwFztQTsJ")).
pos(eqo("conf/vldb/OConnellWG01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672185")).
pos(eqo("conf/vldb/PapadiasT01","JtQbB9D7zkwJ")).
pos(eqo("conf/vldb/PardonA00","Bax8yKEV6McJ")).
pos(eqo("conf/vldb/PottingerL00","mpnnRdFUUJQJ")).
pos(eqo("conf/vldb/Shmueli01","rEwEqoAns-gJ")).
pos(eqo("conf/vldb/Spaccapietra94","ZpVzTb1a7VoJ")).
pos(eqo("conf/vldb/Vaskevitch95","s6Ax0WdZp6IJ")).
pos(eqo("conf/vldb/VenkataramanZ98","KrAyBSajhZEJ")).
pos(eqo("conf/vldb/WienerN95","LJ4M8B9mNWAJ")).
pos(eqo("conf/vldb/ZhouS03","NlDvk5J0WwEJ")).
pos(eqo("journals/sigmod/CalvaneseGLV03","pGcIRyDyFG8J")).
pos(eqo("journals/sigmod/CareyS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310071%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Chang03","B55TCVoUsnoJ")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","SYV3r4_a5EsJ")).
pos(eqo("journals/sigmod/GrayG97","aYtTMXVoTiMJ")).
pos(eqo("journals/sigmod/Hampapur99","I-r1LE1najAJ")).
pos(eqo("journals/sigmod/Han98","2kDtSxYI5DgJ")).
pos(eqo("journals/sigmod/KaradimitriouT97","SrCBkHnIFL8J")).
pos(eqo("journals/sigmod/LabrinidisM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603886%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MaximilienS02","HqytuZsDNx8J")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/TheodoridisN00","DXTczW8Dv4MJ")).
pos(eqo("journals/sigmod/VassiliadisS99","eGARASwVBrUJ")).
pos(eqo("journals/sigmod/WestmannKHM00","BmJKyK7NlOoJ")).
pos(eqo("journals/sigmod/YauLMS99","bhVBJw9Rp3QJ")).
pos(eqo("journals/sigmod/YauLMS99","vWwVQvcIrbEJ")).
pos(eqo("journals/tods/AndriesCPB01","iMGwasyHkgIJ")).
pos(eqo("journals/tods/BellNNS96","0MteXOu7gzcJ")).
pos(eqo("journals/tods/BellNNS96","pz2VRTdXq1cJ")).
pos(eqo("journals/tods/ChrysanthisR94","q2yP1EWKhTcJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0252444CI")).
pos(eqo("journals/tods/GunopulosKMSTS03","5cAIVZJShAEJ")).
pos(eqo("journals/tods/LeveneL99","iwPgaJ1eQrkJ")).
pos(eqo("journals/tods/Meo00","NQShGztSLaoJ")).
pos(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
pos(eqo("journals/vldb/BerendtS00","_0meUij3ZJEJ")).
pos(eqo("journals/vldb/BerendtS00","nm9rCU6yVNwJ")).
pos(eqo("journals/vldb/JagadishKNS00","GtXc02EJjCgJ")).
pos(eqo("journals/vldb/MehrotraKS97","6XxswNrUSk4J")).
pos(eqo("journals/vldb/NybergBCGL95","A1phylxPkl4J")).
pos(eqo("journals/vldb/RahmB01","GJtc6TCE-hIJ")).
pos(eqo("journals/vldb/RahmB01","OmmFvfvPT6MJ")).
pos(eqo("journals/vldb/RoySSSA98","vitgygjdz3AJ")).
