neg(eqo("conf/sigmod/AcharyaAFZ95","rO4-yA3tlfoJ")).
neg(eqo("conf/sigmod/AcharyaGPR99","I8PUKJzlR8AJ")).
neg(eqo("conf/sigmod/AcharyaPR99","WOjMKlT2eUAJ")).
neg(eqo("conf/sigmod/AdyaGLM95","A-OLnk5NCxwJ")).
neg(eqo("conf/sigmod/Aggarwal03","FrphfeAtIXwJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","4q4PDOS45uIJ")).
neg(eqo("conf/sigmod/AggarwalY00","RbBzMy1XNyQJ")).
neg(eqo("conf/sigmod/AggarwalY00","dfSPs7YoyWsJ")).
neg(eqo("conf/sigmod/AggarwalY01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107500%26type%3Dpdf")).
neg(eqo("conf/sigmod/AgrawalGGR98","NDKJPUgy_K4J")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","6-v7jQO-oEUJ")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","fm69LHjS4T0J")).
neg(eqo("conf/sigmod/ArasuG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BarbosaMKL02","htTH8PrZ0dYJ")).
neg(eqo("conf/sigmod/BarbosaMKL02","oUisL_YUScYJ")).
neg(eqo("conf/sigmod/BaruGLMPVC99","-i2fQfLpX2wJ")).
neg(eqo("conf/sigmod/Bayardo98","WpkxYoe4DQYJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","1tZ74y0DNLIJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","LD4ZySpn7OkJ")).
neg(eqo("conf/sigmod/BerensonBGMOO95","wi8177RdPBYJ")).
neg(eqo("conf/sigmod/BersonGM95","YkPqPzGFnZIJ")).
neg(eqo("conf/sigmod/BersonGMJ94","wsG_Q2jbgCAJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","axCznBuwRQYJ")).
neg(eqo("conf/sigmod/BohlenBD99","KnT-lucS26AJ")).
neg(eqo("conf/sigmod/Bonnet02","2CGpGez2zWAJ")).
neg(eqo("conf/sigmod/BonnetBCCCHKMMOSS99","rwcoEES-qDkJ")).
neg(eqo("conf/sigmod/Bosworth03","DaKuxChQNzEJ")).
neg(eqo("conf/sigmod/BouguettayaBH99","m8ZMx1EQVkMJ")).
neg(eqo("conf/sigmod/BreunigKKS01","3ET_IEkoGjYJ")).
neg(eqo("conf/sigmod/BreunigKNS00","9wQ6RWWcHRIJ")).
neg(eqo("conf/sigmod/CandanLLHA01","ryaV3kTsJ2IJ")).
neg(eqo("conf/sigmod/Carey94","7uUM3wXuL74J")).
neg(eqo("conf/sigmod/CareyCNVDRSM99","W6ROObWo3bIJ")).
neg(eqo("conf/sigmod/CareyMN97","Aa9t5-2FNM4J")).
neg(eqo("conf/sigmod/CeriFPP95","wl01w-v-JzIJ")).
neg(eqo("conf/sigmod/ChangG99","BYkCvtDCxzcJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","p6zcWuHfGd0J")).
neg(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ChaudhuriG96","Fh1QPZpWHUMJ")).
neg(eqo("conf/sigmod/ChaudhuriGGM03","GbKwENZEG40J")).
neg(eqo("conf/sigmod/ChaudhuriGS03","QkyXMep2bWsJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","LPNhDh6p-wwJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","OFGtGwUHhUQJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","5CrxUuWV5ggJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","RYeFLYha0ewJ")).
neg(eqo("conf/sigmod/ChenGMV02","Rnb14C5iGIEJ")).
neg(eqo("conf/sigmod/Chong98","dlAojWWn5zsJ")).
neg(eqo("conf/sigmod/ChristophidesCM96","h0uuqAstOPUJ")).
neg(eqo("conf/sigmod/ChristophidesCM96","oV9gJ0B7-3kJ")).
neg(eqo("conf/sigmod/ClaypoolRZSK01","XWto9ZaCrPcJ")).
neg(eqo("conf/sigmod/CluetDSS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D126494%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Cohen98a","JNAxc8WwVXQJ")).
neg(eqo("conf/sigmod/Cohen98a","qfD_kxYt-dsJ")).
neg(eqo("conf/sigmod/ColbyGLMT96","YQQMvRraFBwJ")).
neg(eqo("conf/sigmod/Cotton02","sn_R4N1q2SwJ")).
neg(eqo("conf/sigmod/CruzALRZ97","YPhNi0dzUvUJ")).
neg(eqo("conf/sigmod/DavulcuFKR99","TDyW6V4cc7MJ")).
neg(eqo("conf/sigmod/DeligiannakisR03","ll8GRo5AxaMJ")).
neg(eqo("conf/sigmod/DeshpandeRSN98","ebk6YqPreaUJ")).
neg(eqo("conf/sigmod/DobraGGR02","5fw03ImttPUJ")).
neg(eqo("conf/sigmod/DobraGGR02","M28BJMp5H3kJ")).
neg(eqo("conf/sigmod/DogacAEOADAOS94","ywQwkD1ov7IJ")).
neg(eqo("conf/sigmod/DreyerDS95","oPXBu1tWLpQJ")).
neg(eqo("conf/sigmod/Ellison95","1urLrX5xC3MJ")).
neg(eqo("conf/sigmod/Englert94","KOpz_NXJ3WUJ")).
neg(eqo("conf/sigmod/Englert94","lC5GjK5OpD0J")).
neg(eqo("conf/sigmod/FaloutsosL95","dyDxQvd8OHoJ")).
neg(eqo("conf/sigmod/FegarasM95","MHubEDlndWYJ")).
neg(eqo("conf/sigmod/FlorescuGKR02","JfsgE81fWdkJ")).
neg(eqo("conf/sigmod/French95","E8ICGS9Be2QJ")).
neg(eqo("conf/sigmod/FukudaMMT96","ctDS9w1d04cJ")).
neg(eqo("conf/sigmod/FukudaMMT96a","LseDURw3BXMJ")).
neg(eqo("conf/sigmod/GeneserethKD97","A3Ff3DJjhmYJ")).
neg(eqo("conf/sigmod/GillmannWW02","9OcrAEypDhMJ")).
neg(eqo("conf/sigmod/GillmannWW02","YHUN_yiwIOUJ")).
neg(eqo("conf/sigmod/GionisGK01","qAGM_an5sxMJ")).
neg(eqo("conf/sigmod/GotoK03","CxABHnOorAMJ")).
neg(eqo("conf/sigmod/GotoK03","PSQ-qYD4aiAJ")).
neg(eqo("conf/sigmod/GotoK03","yIGe3Lv-S-EJ")).
neg(eqo("conf/sigmod/GravanoGT94","ibM_wn8NzLgJ")).
neg(eqo("conf/sigmod/GrayHOS96","4XZfE3MOUYsJ")).
neg(eqo("conf/sigmod/GrayHOS96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057835")).
neg(eqo("conf/sigmod/GraySEBW94","bbWXEbBUueYJ")).
neg(eqo("conf/sigmod/GriffinL95","43K14Y5xa0YJ")).
neg(eqo("conf/sigmod/GrossmanQ94","H9bMRYKnXMQJ")).
neg(eqo("conf/sigmod/GrumbachRS98","iQ3Zi3crc9wJ")).
neg(eqo("conf/sigmod/HanFHCC94","tP3aYZrHuEwJ")).
neg(eqo("conf/sigmod/HanKS97","71MLBCKrxOwJ")).
neg(eqo("conf/sigmod/HanPDW01","R-ERjYdCskcJ")).
neg(eqo("conf/sigmod/HeC03","w2d8Zp-t7AUJ")).
neg(eqo("conf/sigmod/HoAMS97","nqHrA_PROnsJ")).
neg(eqo("conf/sigmod/Hope95","darWCYZjZHcJ")).
neg(eqo("conf/sigmod/HristidisKP01","Y05RdRNQWhYJ")).
neg(eqo("conf/sigmod/HsiaoCY94","LEi_Rzm1iH0J")).
neg(eqo("conf/sigmod/HuangSW94","5Chw6HN64vEJ")).
neg(eqo("conf/sigmod/Ivinskis95","9FaaDi_zGnEJ")).
neg(eqo("conf/sigmod/JagadishJOT01","cTdDBKsvthYJ")).
neg(eqo("conf/sigmod/JagadishLMSV99","7VHYdQzMpUsJ")).
neg(eqo("conf/sigmod/JohnsonD03","_uAjDh22Y_EJ")).
neg(eqo("conf/sigmod/JosifovskiSHL02","xA9KNostV4cJ")).
neg(eqo("conf/sigmod/KangN03","ciavnyh4U8UJ")).
neg(eqo("conf/sigmod/Keim96","GBZiTCbChZQJ")).
neg(eqo("conf/sigmod/KementsietsidisAM03","mDj9X3EN9ycJ")).
neg(eqo("conf/sigmod/Kleissner95","DB8lVC2D9fcJ")).
neg(eqo("conf/sigmod/Kohler99","vdQb4UlMa28J")).
neg(eqo("conf/sigmod/KornM00","gt44wy948iMJ")).
neg(eqo("conf/sigmod/KornackerSH98","YgouJdrCoZQJ")).
neg(eqo("conf/sigmod/KotidisR98","04utamFvle4J")).
neg(eqo("conf/sigmod/KotidisR99","6SBwemr2zscJ")).
neg(eqo("conf/sigmod/LakshmananNHP99","NffWJWoUDK0J")).
neg(eqo("conf/sigmod/LehnerSPC00","MsjL7Aj1KCIJ")).
neg(eqo("conf/sigmod/LiBCS00","6H_GC92Fs70J")).
neg(eqo("conf/sigmod/LibkinMW96","OfZWx8jhQvwJ")).
neg(eqo("conf/sigmod/LibkinMW96","uxD8p47apUYJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97a","bF9t6EpjL14J")).
neg(eqo("conf/sigmod/MaddenH02","JUsFf9Sx1UYJ")).
neg(eqo("conf/sigmod/Mamoulis03","0YTOHF51qi8J")).
neg(eqo("conf/sigmod/MamoulisP99","xdAsc3yVWvYJ")).
neg(eqo("conf/sigmod/MaratheS99","LIUl6zpveGQJ")).
neg(eqo("conf/sigmod/MeccaAMMS98","TppC2jA5UXMJ")).
neg(eqo("conf/sigmod/MiloAABN03","ndCsNX4d4o8J")).
neg(eqo("conf/sigmod/MissikoffT94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107505%26type%3Dpdf")).
neg(eqo("conf/sigmod/Mohan94","JHJ-NMsTtL0J")).
neg(eqo("conf/sigmod/Mohan94","ulDehVmIgfAJ")).
neg(eqo("conf/sigmod/Mohan99","JHJ-NMsTtL0J")).
neg(eqo("conf/sigmod/NazeriBO01","K8zARc0Bno0J")).
neg(eqo("conf/sigmod/NazeriBO01","pJsnj7fi9LIJ")).
neg(eqo("conf/sigmod/PapadopoulosM98","6jeHlSgjCskJ")).
neg(eqo("conf/sigmod/PeiMHZ00","rrVffAsoKEIJ")).
neg(eqo("conf/sigmod/PengC03","LjrsWIr3rhAJ")).
neg(eqo("conf/sigmod/PhanN02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/PolyzotisG02","FK5GEhwW7uQJ")).
neg(eqo("conf/sigmod/PopaDST00","RzStO28Xh-EJ")).
neg(eqo("conf/sigmod/QunLO03","_p_a1FowsR8J")).
neg(eqo("conf/sigmod/RafieiM97","S_jh-ZtVr08J")).
neg(eqo("conf/sigmod/RamanH02","YX1NHLqXfbkJ")).
neg(eqo("conf/sigmod/RodriguezR00","fL_WoorIDAoJ")).
neg(eqo("conf/sigmod/Ross00","CPLSjpgMM20J")).
neg(eqo("conf/sigmod/RoussopoulosKS99","fJ1L5XSB4PMJ")).
neg(eqo("conf/sigmod/RoySSB00","AALG-gjgU5gJ")).
neg(eqo("conf/sigmod/RoySSB00","OV6n7LhOe_cJ")).
neg(eqo("conf/sigmod/SagonasSW94","uAoWmK-jEGAJ")).
neg(eqo("conf/sigmod/SagonasSW94","xc8KEoeRT9sJ")).
neg(eqo("conf/sigmod/SistlaW95","F1bohDXUiJ4J")).
neg(eqo("conf/sigmod/SlivinskasJS01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245907%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SrikantA96","ExOv1ThwJiYJ")).
neg(eqo("conf/sigmod/Stonebraker03","Pu1KpNrzYGUJ")).
neg(eqo("conf/sigmod/Stonebraker03","hUQBQ_9ohcgJ")).
neg(eqo("conf/sigmod/TaoP02","chcojj8yN1sJ")).
neg(eqo("conf/sigmod/TatarinovVBSSZ02","Ng8CP2M8eUQJ")).
neg(eqo("conf/sigmod/Team95a","hk9P76dJfcAJ")).
neg(eqo("conf/sigmod/TheobaldW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565139%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","2cnL-gQPLdcJ")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","5Trj9q_RI8YJ")).
neg(eqo("conf/sigmod/ThomasDM95","xxp4Im8OG9AJ")).
neg(eqo("conf/sigmod/Ullman03","NVS_rDpScp0J")).
neg(eqo("conf/sigmod/Ullman03","d1odiafnX9MJ")).
neg(eqo("conf/sigmod/WangSCRZP97","UOXm9cb58YUJ")).
neg(eqo("conf/sigmod/WangSCRZP97","wXmmbYxfRu8J")).
neg(eqo("conf/sigmod/WilschutFA95","wPhDoeiINQsJ")).
neg(eqo("conf/sigmod/WoelkBJOTU95","TDIVG8_n_esJ")).
neg(eqo("conf/sigmod/WuAA01","aJtfpkxS-ycJ")).
neg(eqo("conf/sigmod/YangM97","cF4jzvngOVgJ")).
neg(eqo("conf/sigmod/YangWYH02","v2WnsQZXpNAJ")).
neg(eqo("conf/sigmod/YuMWL01","qXHdy9ingMoJ")).
neg(eqo("conf/sigmod/ZaharioudakisCLPU00","ixz5LdVw9_8J")).
neg(eqo("conf/sigmod/ZhangNBB94","5XWWxb87_74J")).
neg(eqo("conf/sigmod/ZhangRL96","2tuXRrSSJg8J")).
neg(eqo("conf/sigmod/ZhouR02","a5djJMe9uAIJ")).
neg(eqo("conf/sigmod/ZhouR02","wVkpqzhO5eUJ")).
neg(eqo("conf/sigmod/ZouS96","yYffvOfsaiwJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","kNKWc8ETyvMJ")).
neg(eqo("conf/vldb/AdiBEY00","RkjggE7xhN0J")).
neg(eqo("conf/vldb/AgarwalADGNRS96","Cs3YM9yMq5QJ")).
neg(eqo("conf/vldb/AggarwalHWY03","3axhCWXQQN0J")).
neg(eqo("conf/vldb/AggarwalHWY03","hUoyTdstE7sJ")).
neg(eqo("conf/vldb/AgrawalSX01","cUVJ8Svrad0J")).
neg(eqo("conf/vldb/AgrawalSX01","p9UAHVBitfwJ")).
neg(eqo("conf/vldb/AndreiV01","A4lUwOD7AeYJ")).
neg(eqo("conf/vldb/BalminPP00","KU0X0_4bKz0J")).
neg(eqo("conf/vldb/BamfordBKM98","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/09505849/1998/00000040/00000003/art00047%26unc%3D")).
neg(eqo("conf/vldb/Banerjee00","RzLHe-SyBFgJ")).
neg(eqo("conf/vldb/BaralisW94","H4YOA_NQto4J")).
neg(eqo("conf/vldb/Bernstein94","N3Bry6sSMw8J")).
neg(eqo("conf/vldb/BernsteinHSSZ97","62aA4DYB0MQJ")).
neg(eqo("conf/vldb/BlottK02","oBYXJwR985kJ")).
neg(eqo("conf/vldb/BonczMK99","28GZ8M1ZPVYJ")).
neg(eqo("conf/vldb/Brin95","dXegp-RmzXEJ")).
neg(eqo("conf/vldb/BrodieC99","VhVTUQPQYq4J")).
neg(eqo("conf/vldb/CarusoCGLM00","X5LKJRsuqgUJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","aowwkB8T3W8J")).
neg(eqo("conf/vldb/ChakrabartiSD98","jNb5aoFeS7wJ")).
neg(eqo("conf/vldb/ChanGR02","wUcXmf9G52gJ")).
neg(eqo("conf/vldb/ChanI99","1qWnrA_8DUIJ")).
neg(eqo("conf/vldb/ChaudhuriG99","D7w6TQwatE0J")).
neg(eqo("conf/vldb/ChaudhuriN97","RYeFLYha0ewJ")).
neg(eqo("conf/vldb/ChaudhuriN97","eHM4OCdJA9YJ")).
neg(eqo("conf/vldb/ChaudhuriS01","url:http://doi.wiley.com/10.1002/tl.3")).
neg(eqo("conf/vldb/ChenL03","WaSgR87oMpcJ")).
neg(eqo("conf/vldb/ChienTZ01","j4wcclZqY0oJ")).
neg(eqo("conf/vldb/ChienTZ01","oBpe7jg0YHYJ")).
neg(eqo("conf/vldb/ChienVZTZ02","uUmeAkW_FFUJ")).
neg(eqo("conf/vldb/ChoG00","RtBmJGOaO5IJ")).
neg(eqo("conf/vldb/ChoG00","lBGzJFYu6YQJ")).
neg(eqo("conf/vldb/Cluet03","mOi9LhweqNwJ")).
neg(eqo("conf/vldb/ColletCS94","pzmTeD6SFSAJ")).
neg(eqo("conf/vldb/CormodeKMS03","ONxNYqv7q-UJ")).
neg(eqo("conf/vldb/CuiW01","SaOd6rDz5ZgJ")).
neg(eqo("conf/vldb/Cuppens96","9kl_hTyQtmQJ")).
neg(eqo("conf/vldb/DarmontS99","-HZznEiZzJ4J")).
neg(eqo("conf/vldb/DeutschT03","F3PUyQu1skYJ")).
neg(eqo("conf/vldb/DoR02","aZa9Vq7sHikJ")).
neg(eqo("conf/vldb/DongHLPW01","aOmma8tnFKIJ")).
neg(eqo("conf/vldb/Dyreson96","jbDLUWfnCpkJ")).
neg(eqo("conf/vldb/Dyreson96","vQVMrRkJwSIJ")).
neg(eqo("conf/vldb/FlescaFM03","uqh6Sfc5428J")).
neg(eqo("conf/vldb/FukudaMMT96","KVxxP3vLKvQJ")).
neg(eqo("conf/vldb/GallersdorferN95","95LnCs7V35YJ")).
neg(eqo("conf/vldb/GarofalakisG02","JtBgY68GgRoJ")).
neg(eqo("conf/vldb/GarofalakisI97","4LD2Y596NgwJ")).
neg(eqo("conf/vldb/GarofalakisI97","ktuEGK9MoYAJ")).
neg(eqo("conf/vldb/George98","QHnRqzbv2NwJ")).
neg(eqo("conf/vldb/GilbertKMS02","OkCz_NK5cbMJ")).
neg(eqo("conf/vldb/GoldmanSVG98","ONxNYqv7q-UJ")).
neg(eqo("conf/vldb/GoldmanSVG98","_5uwdZyabgMJ")).
neg(eqo("conf/vldb/GottlobKP02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1101915%26type%3Dpdf")).
neg(eqo("conf/vldb/GravanoG97","zbJYyUhl2cIJ")).
neg(eqo("conf/vldb/Greco98","6F2UHbg25sQJ")).
neg(eqo("conf/vldb/Gupta96","17A4hoNAFWgJ")).
neg(eqo("conf/vldb/GuptaHQ95","xkK5sMFddeUJ")).
neg(eqo("conf/vldb/Hallmark95","8SYZpKAeTwQJ")).
neg(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
neg(eqo("conf/vldb/HoelS95","hwBMsP8-fXcJ")).
neg(eqo("conf/vldb/HristidisP02","0Yw58WvaBxEJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","X_QH7A2c_1EJ")).
neg(eqo("conf/vldb/HulgeriS03","xGcM9AuhrBMJ")).
neg(eqo("conf/vldb/IdrisGC94","I5fV3jpcrmAJ")).
neg(eqo("conf/vldb/IlyasAE02","nQsk3GveFP0J")).
neg(eqo("conf/vldb/JagadishNSSK97","FzUYum7hqhQJ")).
neg(eqo("conf/vldb/JohnsonM98","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D200124027168CE%26recid%3DN9210562AH")).
neg(eqo("conf/vldb/King02","0beHvgeW9TMJ")).
neg(eqo("conf/vldb/Korth95","AoVZJ8ExSN4J")).
neg(eqo("conf/vldb/Korth95","zSUluHQ4WaUJ")).
neg(eqo("conf/vldb/KoudasIM00","vQVMrRkJwSIJ")).
neg(eqo("conf/vldb/LabioG96","Z4PFhbrweWMJ")).
neg(eqo("conf/vldb/LeeHJT03","Sko145Nl9roJ")).
neg(eqo("conf/vldb/LockemannKKKN97","ejQ9kBpYmBoJ")).
neg(eqo("conf/vldb/LometT95","P7GUGC5bz7wJ")).
neg(eqo("conf/vldb/LudascherMP02","cxnuI54po5EJ")).
neg(eqo("conf/vldb/ManegoldBK00","gkbM-pRDcSwJ")).
neg(eqo("conf/vldb/MatthesS94","6dAWUHYKqFUJ")).
neg(eqo("conf/vldb/McHughW99","KvsmVlCdtKAJ")).
neg(eqo("conf/vldb/MeccaCM01","SjYOl_fLmMsJ")).
neg(eqo("conf/vldb/Meier95","vvKirGP5TQsJ")).
neg(eqo("conf/vldb/Mina98","69oWwBGZI_kJ")).
neg(eqo("conf/vldb/Mina98","TU9kuQtFuvMJ")).
neg(eqo("conf/vldb/Mina98","yPjOtPqa0pIJ")).
neg(eqo("conf/vldb/MuntzR94","0GMNedjfVV0J")).
neg(eqo("conf/vldb/NgH94","g8e0xiRUkIwJ")).
neg(eqo("conf/vldb/OConnellWG01","1bBjnX0qrokJ")).
neg(eqo("conf/vldb/Objectivity98","D_1D4P70SdkJ")).
neg(eqo("conf/vldb/OuzzaniAB94","0XYRlW9tvw8J")).
neg(eqo("conf/vldb/PacittMS99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D200111010707MT%26recid%3DA0032641AH")).
neg(eqo("conf/vldb/PalpanasSCP02","NxYaoolVv64J")).
neg(eqo("conf/vldb/PapadiasMD98","d24yd6IygmoJ")).
neg(eqo("conf/vldb/PardonA00","mhSKh8h0x2oJ")).
neg(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
neg(eqo("conf/vldb/Pogue98","u2T3MhgoWJQJ")).
neg(eqo("conf/vldb/PoosalaI97","OBOFH2EyYRwJ")).
neg(eqo("conf/vldb/PossP03","IpgzF9NKp7gJ")).
neg(eqo("conf/vldb/PoulovassilisS94","url:http://adsabs.harvard.edu/abs/1994ttw..conf.....L")).
neg(eqo("conf/vldb/QianZXP03","ydHzAK2kRGYJ")).
neg(eqo("conf/vldb/RahmM95","6ioboOxJvQIJ")).
neg(eqo("conf/vldb/RamanH01","J3bObN0lQwMJ")).
neg(eqo("conf/vldb/Ramanan03","By-zZ14p7kAJ")).
neg(eqo("conf/vldb/RamasamyPNK00","ph4a4-BRtRUJ")).
neg(eqo("conf/vldb/RusinkiewiczKTWM95","dXegp-RmzXEJ")).
neg(eqo("conf/vldb/Sarawagi00","BJ0pr7FqzzoJ")).
neg(eqo("conf/vldb/Sarawagi00","nKNpemeXlikJ")).
neg(eqo("conf/vldb/Sarawagi99","z5DmAoBjsjAJ")).
neg(eqo("conf/vldb/SarawagiS96","7GpYSr7yaWAJ")).
neg(eqo("conf/vldb/Schoning03","Q3KRd34IjYgJ")).
neg(eqo("conf/vldb/Schoning03","jgDisPHDrlkJ")).
neg(eqo("conf/vldb/SevcikK96","GiHrMj3vbSAJ")).
neg(eqo("conf/vldb/SevcikK96","PAfEdPwJ8tgJ")).
neg(eqo("conf/vldb/ShahRS02","O9A-15rmzOsJ")).
neg(eqo("conf/vldb/ShanmugasundaramGTZDN99","iME-SCx_DIgJ")).
neg(eqo("conf/vldb/ShiSZ03","N9u28V6NZTIJ")).
neg(eqo("conf/vldb/SilversteinBMU98","ewnL82c8kiMJ")).
neg(eqo("conf/vldb/SistlaYH94","FT4Sfn-Z7GUJ")).
neg(eqo("conf/vldb/SistlaYH94","_KKkrRdguAgJ")).
neg(eqo("conf/vldb/SrinivasaK03","JvthmGX_uoQJ")).
neg(eqo("conf/vldb/Sripada02","n5SsAbtjBpAJ")).
neg(eqo("conf/vldb/StanoiRAA01","LRiBvg5EPo4J")).
neg(eqo("conf/vldb/SteinbrunnPMK95","tuVp_18tFv8J")).
neg(eqo("conf/vldb/StolteA02","U0JhB6VKSTUJ")).
neg(eqo("conf/vldb/Sullivan96","ozt0Yalh_WEJ")).
neg(eqo("conf/vldb/TaoPS02","TmcyYF1CNsYJ")).
neg(eqo("conf/vldb/Taylor00","Af_4cNCu3MwJ")).
neg(eqo("conf/vldb/TeisseirePC94","C1SSnou9z8oJ")).
neg(eqo("conf/vldb/TengCY03","mH0vNFMcLxsJ")).
neg(eqo("conf/vldb/Toivonen96","3bAcp3Ey8aIJ")).
neg(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
neg(eqo("conf/vldb/Wang95","-O2gEZDOEWYJ")).
neg(eqo("conf/vldb/Wang95","m2YhzoMq9_IJ")).
neg(eqo("conf/vldb/WangHH00","4zJO_jnSBJ4J")).
neg(eqo("conf/vldb/WienerN95","Q-_JIZ0MaWEJ")).
neg(eqo("conf/vldb/WienerN95","f1PnB8Owd7AJ")).
neg(eqo("conf/vldb/WuYCT95","JXI-CvxzElQJ")).
neg(eqo("conf/vldb/YanL95","yFaUjmOQp1wJ")).
neg(eqo("journals/sigmod/Aberer01a","mt8Q1YmVRkMJ")).
neg(eqo("journals/sigmod/Aberer01a","url:http://www.ingentaconnect.com/content/els/13891286/2001/00000035/00000002/art00170")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/citation.cfm%3Fid%3D603867.603869%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AbererCDDHPS03","jxL7i2xXm2EJ")).
neg(eqo("journals/sigmod/AilamakiG03","t4JoRwvUNZoJ")).
neg(eqo("journals/sigmod/AlonsoCIM95","4aSEl4haaq4J")).
neg(eqo("journals/sigmod/ArpinarD00","qhKZP4rFBvkJ")).
neg(eqo("journals/sigmod/AtkinsonDJPS96","JHVWab3P4zIJ")).
neg(eqo("journals/sigmod/BarbaraCJW01","EGwNxdEHaeQJ")).
neg(eqo("journals/sigmod/BarbaraCJW01","Ezc9JkX8VhgJ")).
neg(eqo("journals/sigmod/Bernstein01","_xo5kC5HWU0J")).
neg(eqo("journals/sigmod/Bernstein98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083791%26type%3Dpdf")).
neg(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BertinoEH03","Ub6YwssjyiYJ")).
neg(eqo("journals/sigmod/Bestavros96","JyDEoz9hvJQJ")).
neg(eqo("journals/sigmod/BilirisP96","aU7XlTpoxRgJ")).
neg(eqo("journals/sigmod/BrunieK96","6Wvy1bxGVPMJ")).
neg(eqo("journals/sigmod/BrunieK96","NiahIu-wQacJ")).
neg(eqo("journals/sigmod/BunemanFSW01","CAKcsKXFoCoJ")).
neg(eqo("journals/sigmod/BunemanFSW01","FLey09ZW6NgJ")).
neg(eqo("journals/sigmod/Bussche00","36_Z5VHBVsgJ")).
neg(eqo("journals/sigmod/CaplinskasEV02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507367%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/CeriFP99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310071%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D984505.984507%26dl%3DACM%26dl%3DACM%26idx%3D984505%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Chang03","fxgs50zXfVEJ")).
neg(eqo("journals/sigmod/ChangGKRS98","Ip82P4QfKyEJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","QkyXMep2bWsJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","YzmJ1_3EBB0J")).
neg(eqo("journals/sigmod/Chen94","5lEMgr1_eQwJ")).
neg(eqo("journals/sigmod/ChenHKPW94","TBPXGTh9VAAJ")).
neg(eqo("journals/sigmod/CruzKLSWY02","chcojj8yN1sJ")).
neg(eqo("journals/sigmod/David03","m2Mf-4BgLP4J")).
neg(eqo("journals/sigmod/DoanPSB97","H7Pi4AQU00YJ")).
neg(eqo("journals/sigmod/Dogac96","qD22zNTUoLYJ")).
neg(eqo("journals/sigmod/Dogac96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507340%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/DreyerDS94","UTe8b9IiclUJ")).
neg(eqo("journals/sigmod/Eisenberg96","tFbkjO2wcFMJ")).
neg(eqo("journals/sigmod/EisenbergM01","6uelfg3RgEoJ")).
neg(eqo("journals/sigmod/EisenbergM01","GKUflKzgAVEJ")).
neg(eqo("journals/sigmod/EisenbergM98","e3s4OFTeBqwJ")).
neg(eqo("journals/sigmod/EisenbergM98a","AatoNnELw78J")).
neg(eqo("journals/sigmod/Elderini02","qIBrxCTdrUMJ")).
neg(eqo("journals/sigmod/Finkelstein95","cNfcQTKVmOQJ")).
neg(eqo("journals/sigmod/Franklin97b","DiWYJABnOuMJ")).
neg(eqo("journals/sigmod/Franklin98a","hB-ZA0wX-fsJ")).
neg(eqo("journals/sigmod/Gaffney96","odFtqwn5ZVcJ")).
neg(eqo("journals/sigmod/GeppertD94","DDyZXuEtGiwJ")).
neg(eqo("journals/sigmod/Goethals02","RajquHU2NoIJ")).
neg(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","9VvN0Pfp3woJ")).
neg(eqo("journals/sigmod/GuptaHR97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988603%26type%3Dpdf")).
neg(eqo("journals/sigmod/GuptaHR97","xkK5sMFddeUJ")).
neg(eqo("journals/sigmod/Hainaut03","GeMycbLXZUkJ")).
neg(eqo("journals/sigmod/Halevy03","NXKx0V8rHQQJ")).
neg(eqo("journals/sigmod/HalkidiBV02a","GHjgDrEbqM4J")).
neg(eqo("journals/sigmod/Hammer01","lHS20twyYZAJ")).
neg(eqo("journals/sigmod/Hammer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Hanson99","35NMD2cIprEJ")).
neg(eqo("journals/sigmod/HasselbringHHKRRS00","HvcVF-h_pocJ")).
neg(eqo("journals/sigmod/Jagadish00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D382417%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/KappelR98","LnNHfHLFsEcJ")).
neg(eqo("journals/sigmod/KiyokiKH94","qnbfdzE--oQJ")).
neg(eqo("journals/sigmod/KlasS94","Opow89YK6a8J")).
neg(eqo("journals/sigmod/KlasS94","qolJkVC2MoYJ")).
neg(eqo("journals/sigmod/Konig-RiesMMPPRSVW02","9OcrAEypDhMJ")).
neg(eqo("journals/sigmod/Labrinidis01","Ix9niWleaW4J")).
neg(eqo("journals/sigmod/Labrinidis01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1101992%26type%3Dpdf")).
neg(eqo("journals/sigmod/LabrinidisM01","9ZhDPDECMQ8J")).
neg(eqo("journals/sigmod/LawderK01","QWMmTUgNyPsJ")).
neg(eqo("journals/sigmod/Liu02c","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Liu03a","0W2XcpqyLIAJ")).
neg(eqo("journals/sigmod/Mani03","6sVFj-qWy60J")).
neg(eqo("journals/sigmod/Manola98","VIjfH9f94xkJ")).
neg(eqo("journals/sigmod/MarchiLPT03","9dgFU6XaLrwJ")).
neg(eqo("journals/sigmod/MedskerCS95","QhLqCCTIVlkJ")).
neg(eqo("journals/sigmod/MeltzerC98","H5IdN0_MQw4J")).
neg(eqo("journals/sigmod/MusickC99","A-OWMulBkOoJ")).
neg(eqo("journals/sigmod/Neven02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202671%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Ouksel03","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565131%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Ozsu02a","U7OwxK6Bpy4J")).
neg(eqo("journals/sigmod/PapianiWDN99","ZNV5NsBuGgQJ")).
neg(eqo("journals/sigmod/PossasMCR00","zctGLtEC2VIJ")).
neg(eqo("journals/sigmod/Qian94","MkRJhOROQjsJ")).
neg(eqo("journals/sigmod/Qian95","PNd7jkHAWhwJ")).
neg(eqo("journals/sigmod/Qian95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RoantreeMH99","TabFkjNTLMsJ")).
neg(eqo("journals/sigmod/RoantreeS02","KB9ZbekVNzoJ")).
neg(eqo("journals/sigmod/Rosenthal98","FLBFge9zwNoJ")).
neg(eqo("journals/sigmod/RossHKRRSS01","uPBlQ76s_g4J")).
neg(eqo("journals/sigmod/Roussopoulos98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D16857%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SchmidtWKFCMB01","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D560244CI")).
neg(eqo("journals/sigmod/Segev94","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Segev94a","SiEozDoAbfwJ")).
neg(eqo("journals/sigmod/Seligman97","EcCCKrmbnQQJ")).
neg(eqo("journals/sigmod/ShahMFH01","url:http://api.ingentaconnect.com/content/bpl/area/2001/00000033/00000002/art00025")).
neg(eqo("journals/sigmod/ShanmugasundaramSKKVNT01","HKM-zP0LT_UJ")).
neg(eqo("journals/sigmod/SilberschatzSU96","soiN2U4tXykJ")).
neg(eqo("journals/sigmod/SlivinskasJS02","2kiNfwTpqp4J")).
neg(eqo("journals/sigmod/Snodgrass02b","UFKz6Q0wVi4J")).
neg(eqo("journals/sigmod/Snodgrass02b","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084832")).
neg(eqo("journals/sigmod/Snodgrass94","aXPiJgR6HCoJ")).
neg(eqo("journals/sigmod/Snodgrass94","nLbW09uNfmsJ")).
neg(eqo("journals/sigmod/Snodgrass97","tsgQfUnm5dgJ")).
neg(eqo("journals/sigmod/Snodgrass98a","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/Snodgrass99a","pOMM8OVTDLYJ")).
neg(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","MWbzCv_v4gsJ")).
neg(eqo("journals/sigmod/SnodgrassGIMSU98","C8I_Ns46iLQJ")).
neg(eqo("journals/sigmod/StolfoLCFE01","z6Dk4vfdPN8J")).
neg(eqo("journals/sigmod/TanakaV01","JQTeaBWzwy0J")).
neg(eqo("journals/sigmod/TsotrasK96","GtcDPEq5es4J")).
neg(eqo("journals/sigmod/TsotrasK96","lCw-7Q4LbsYJ")).
neg(eqo("journals/sigmod/VetterliVS00","JTwcPfsLuxYJ")).
neg(eqo("journals/sigmod/Wade96","EKqpEdn3kDMJ")).
neg(eqo("journals/sigmod/Widom94","3TVyZeq1-i4J")).
neg(eqo("journals/sigmod/Widom95a","_cil6uzFNtsJ")).
neg(eqo("journals/sigmod/Winslett01","0-FUXURm1FQJ")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141405%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601871%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Winslett03a","9xLgP0cCIy4J")).
neg(eqo("journals/sigmod/WinslettCDHZZ02","url:http://ieeexplore.ieee.org/iel5/9217/29235/01320093.pdf%3Farnumber%3D1320093")).
neg(eqo("journals/sigmod/ZobelMR96","gIZvbo_lu2IJ")).
neg(eqo("journals/tods/Alagic99","5mghjxz5EwkJ")).
neg(eqo("journals/tods/BeneventanoBS03","rRH6Z1oP78cJ")).
neg(eqo("journals/tods/BunemanO96","y2dZ5cRja_IJ")).
neg(eqo("journals/tods/CaldersNW02","SU2XS1MVb40J")).
neg(eqo("journals/tods/CeriFPT94","JUmzUX26it0J")).
neg(eqo("journals/tods/CeriFPT94","YIT10NaTvJ8J")).
neg(eqo("journals/tods/ChaudhuriS99","H5IdN0_MQw4J")).
neg(eqo("journals/tods/ChaudhuriS99","QkyXMep2bWsJ")).
neg(eqo("journals/tods/ChoG03","Hd90xxjjPokJ")).
neg(eqo("journals/tods/CuiWW00","HIDW-CpBP0cJ")).
neg(eqo("journals/tods/CuiWW00","dKvepAPYBmcJ")).
neg(eqo("journals/tods/DeyS96","Bho8kTicu-8J")).
neg(eqo("journals/tods/FormicaGM98","adU4gkHmcg8J")).
neg(eqo("journals/tods/FranklinCL97","7Vl3hysT9_cJ")).
neg(eqo("journals/tods/GraefeC95","OJjwkoZbhL0J")).
neg(eqo("journals/tods/Hellerstein98","dvlv3BMgYrIJ")).
neg(eqo("journals/tods/Hellerstein98","pHHvswIOFfAJ")).
neg(eqo("journals/tods/IoannidisR95","Q7aTHp0uDOMJ")).
neg(eqo("journals/tods/IoannidisR95","TJDMWbCXMtgJ")).
neg(eqo("journals/tods/Keen97","xuoJNqOArTsJ")).
neg(eqo("journals/tods/KonopnickiS98","Nghy20uM-5oJ")).
neg(eqo("journals/tods/KrishnakumarB94","8ZjEDOBUd_QJ")).
neg(eqo("journals/tods/KrishnakumarB94","9NSJ60mSACsJ")).
neg(eqo("journals/tods/LakshmananLN03","Jg81WYtxtZoJ")).
neg(eqo("journals/tods/LakshmananLN03","PsXOoGuK0ogJ")).
neg(eqo("journals/tods/LakshmananSS01","1I1VNEHN4jYJ")).
neg(eqo("journals/tods/MamoulisP01","xdAsc3yVWvYJ")).
neg(eqo("journals/tods/MumickFPR96","E688ACygfTEJ")).
neg(eqo("journals/tods/ParsonsW00","TbQE3xcc7m0J")).
neg(eqo("journals/tods/ShashaLSV95","anyz3BJ8xjoJ")).
neg(eqo("journals/tods/Snodgrass01","uOcOPUShONEJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/RV67P1J713229350.pdf")).
neg(eqo("journals/tods/Suciu02","UC80gLhicTAJ")).
neg(eqo("journals/tods/Suciu02","_vOvQUzSV-gJ")).
neg(eqo("journals/tods/TaoPZ02","T6iQ-tsNBNAJ")).
neg(eqo("journals/tods/TendickM94","2e-NAgqt-joJ")).
neg(eqo("journals/tods/WandSW99","r0dPAo1eZm4J")).
neg(eqo("journals/tods/Wijsen99","Ult4nmnmJp8J")).
neg(eqo("journals/tods/Wijsen99","ic6J0v-7DjwJ")).
neg(eqo("journals/vldb/AbiteboulB95","Qq6giK3KqJoJ")).
neg(eqo("journals/vldb/AbiteboulB95","url:http://portal.acm.org/citation.cfm%3Fid%3D325405.325439")).
neg(eqo("journals/vldb/AbiteboulCM98","-cQmLk2JnawJ")).
neg(eqo("journals/vldb/AbiteboulCM98","rZcRXL6ueUMJ")).
neg(eqo("journals/vldb/AgrawalHK03","url:http://portal.acm.org/citation.cfm%3Fid%3D98749%26coll%3Dportal%26dl%3DACM")).
neg(eqo("journals/vldb/AgrawalHK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D957074%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/AguileraCMVV02","_BsVmIUER44J")).
neg(eqo("journals/vldb/AlbanoGO95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202671%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/AlbanoGO95","vrD2aAK6G-wJ")).
neg(eqo("journals/vldb/AtluriJY03","tZ8ckEl9UrUJ")).
neg(eqo("journals/vldb/Barbara-MillaG94","lyVxY_nXI38J")).
neg(eqo("journals/vldb/ChandrasekaranF03","xmScCNs16i0J")).
neg(eqo("journals/vldb/ChangG01","k6PcAIbeWhcJ")).
neg(eqo("journals/vldb/ChidlovskiiB00","jkYutLHUIXEJ")).
neg(eqo("journals/vldb/ChuIT94","_dOpWA3QWOEJ")).
neg(eqo("journals/vldb/Cobb97","2tw4hil58GoJ")).
neg(eqo("journals/vldb/DattaDVRN01","57N49yQNYIAJ")).
neg(eqo("journals/vldb/DesslochHMMT98","4D2HQE6fXXEJ")).
neg(eqo("journals/vldb/DiazJ97","9KM1MkzWaWoJ")).
neg(eqo("journals/vldb/FerrariAABC02","4MrVmWl33coJ")).
neg(eqo("journals/vldb/FungKL03","lv2DKcTInCwJ")).
neg(eqo("journals/vldb/GrefenVA01","I-Ha4jdx5swJ")).
neg(eqo("journals/vldb/Guting94","hoNylhoOWr4J")).
neg(eqo("journals/vldb/GutingS95","geJ7rBZtg94J")).
neg(eqo("journals/vldb/Halevy02","M3ELKAZ4wBMJ")).
neg(eqo("journals/vldb/HarderR96","jpJMa9UNggoJ")).
neg(eqo("journals/vldb/HarderST99","28BvOA9bYjAJ")).
neg(eqo("journals/vldb/HuangDT99","aEhVgTfCykUJ")).
neg(eqo("journals/vldb/HuntAI02","6uelfg3RgEoJ")).
neg(eqo("journals/vldb/LeeSC01","Hz_TU6kUj08J")).
neg(eqo("journals/vldb/MaratheS02","vCvPdFwbKWkJ")).
neg(eqo("journals/vldb/MedjahedBBNE03","Jml6flDOu7QJ")).
neg(eqo("journals/vldb/MihailaRT02","Ih5hY-NRmFgJ")).
neg(eqo("journals/vldb/PanagosB97","bFnDGrZ_4voJ")).
neg(eqo("journals/vldb/PapadiasS94","OAwaGi7f4skJ")).
neg(eqo("journals/vldb/PapazogluK97a","3kdPEIM6y6oJ")).
neg(eqo("journals/vldb/RafieiM02","WpkxYoe4DQYJ")).
neg(eqo("journals/vldb/RamakrishnanSSS94","P_97uhnD9TwJ")).
neg(eqo("journals/vldb/Sarawagi01","4bvjebYsdRkJ")).
neg(eqo("journals/vldb/TorpJS00","u0pFjzAcl78J")).
neg(eqo("journals/vldb/VaghaniRKSSLH94","neCCsiTktDAJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","a1esMNRsK_UJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","s064OghlyIUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","t8KDgCSg9RIJ")).
pos(eqo("conf/sigmod/AdiBEY01","3jUi_Yf4DfIJ")).
pos(eqo("conf/sigmod/AdyaGLM95","7YMi5qKSe2EJ")).
pos(eqo("conf/sigmod/AdyaGLM95","EP8u32KwMe4J")).
pos(eqo("conf/sigmod/AgichteinG03","url:http://portal.acm.org/citation.cfm%3Fid%3D872851")).
pos(eqo("conf/sigmod/AgrawalS00","ufPUBsN4eg0J")).
pos(eqo("conf/sigmod/Ahn94","5s6b10Hik30J")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","L7XmLpQLXBIJ")).
pos(eqo("conf/sigmod/ArasuBBDIRW03","1DKKwROqEeYJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","E_eOZJYat6IJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","aCCAyNhJFtsJ")).
pos(eqo("conf/sigmod/AshleyFHLNP95","FnnILIjz08EJ")).
pos(eqo("conf/sigmod/Aulakh98","xFK4CkKj14EJ")).
pos(eqo("conf/sigmod/BarclaySG00","Yiyko_0KiEIJ")).
pos(eqo("conf/sigmod/BargaL99","hf84fEpX5agJ")).
pos(eqo("conf/sigmod/BaruFGHJPW95","mFOSML8c0s4J")).
pos(eqo("conf/sigmod/BerchtoldK98","PKMN5Cdy7KcJ")).
pos(eqo("conf/sigmod/BerchtoldK98","irJbh9rrinoJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","-CQaLTpGJLQJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","FIpzjIEyMgMJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","KpQrgYyji34J")).
pos(eqo("conf/sigmod/BerensonBGMOO95","MOGnM6t6l3MJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","gWmqoNZHKAAJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","tsQbSCfQTooJ")).
pos(eqo("conf/sigmod/BohannonDGKLNS03","83wqw4ciNWoJ")).
pos(eqo("conf/sigmod/BohannonMR01","ChD3-mp23f8J")).
pos(eqo("conf/sigmod/BouguettayaBH99","U-Kd4GQ_vCMJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294191CI")).
pos(eqo("conf/sigmod/CareyFZ94","EN1nFWJxnoIJ")).
pos(eqo("conf/sigmod/CareyFZ94","UBpDljYCfGgJ")).
pos(eqo("conf/sigmod/CareyK97","b_lpj8wu7BEJ")).
pos(eqo("conf/sigmod/CareyMN97","u64n4yMnma4J")).
pos(eqo("conf/sigmod/Cattell94","zSoTbEtLuqEJ")).
pos(eqo("conf/sigmod/Chakrabarti99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304231%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChenJDTW00","5Trj9q_RI8YJ")).
pos(eqo("conf/sigmod/ChenJDTW00","fg5EE6R7xYwJ")).
pos(eqo("conf/sigmod/ChoG00","yUZCropW2lQJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","I0KBB-n-eF8J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/ChristophidesACS94","T8v6sQ1R3zoJ")).
pos(eqo("conf/sigmod/ChristophidesACS94","WYSBGO-zyoEJ")).
pos(eqo("conf/sigmod/ChungMS02","UmPir9n5JloJ")).
pos(eqo("conf/sigmod/ChungMS02","n8tscFMeBtwJ")).
pos(eqo("conf/sigmod/ChungMS02","vA_YTBbNegEJ")).
pos(eqo("conf/sigmod/ColeG94","z_W8jZ203sUJ")).
pos(eqo("conf/sigmod/CranorJSS03","b0ayPKpqTwsJ")).
pos(eqo("conf/sigmod/CranorJSS03","eXt7Nvd060MJ")).
pos(eqo("conf/sigmod/CranorJSS03","gya0M9b1KrgJ")).
pos(eqo("conf/sigmod/DanS95","nTu7PUukM1wJ")).
pos(eqo("conf/sigmod/DanS95","qjHzY4uEG7gJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","3PH--zwkZO8J")).
pos(eqo("conf/sigmod/DeHaanTCO03","gyYBYgpB63sJ")).
pos(eqo("conf/sigmod/DewanSHH94","GUdXGx4blW8J")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","p6ro8VCQBwcJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","zf5eI7As5kAJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","GnjIUQVlZ0UJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","XE1zjDexb64J")).
pos(eqo("conf/sigmod/Dullmann99","5bp8rSFAkzEJ")).
pos(eqo("conf/sigmod/EmbleyJN99","O_SMlr3bFBMJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","ek26aiEheesJ")).
pos(eqo("conf/sigmod/FernandezS96","66uAX5EPtKcJ")).
pos(eqo("conf/sigmod/FernandezS96","9bgA6C_HqvQJ")).
pos(eqo("conf/sigmod/FernandezS96","iLwFjrX22vYJ")).
pos(eqo("conf/sigmod/FernandezS96","lMKrltuk53EJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","WOCgxlV_LgoJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","Y8UdbAPhYpUJ")).
pos(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
pos(eqo("conf/sigmod/GarofalakisI96","MfPbk62EdyQJ")).
pos(eqo("conf/sigmod/GehrkeKS01","tOTe7iddlmMJ")).
pos(eqo("conf/sigmod/GeneserethKD97","2Nl65Vp7bxUJ")).
pos(eqo("conf/sigmod/GeorgeH97","Ah9B3bWU0jEJ")).
pos(eqo("conf/sigmod/GeorgeH97","b9F3YB4bHxQJ")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/Gerber95","wlxZ0FqTy_MJ")).
pos(eqo("conf/sigmod/GillmannWSWW00","L61_1TEGBLYJ")).
pos(eqo("conf/sigmod/GingrasLSPS97","D0EVu0EZM-UJ")).
pos(eqo("conf/sigmod/GoldsteinL01","dxvwQEOjBJQJ")).
pos(eqo("conf/sigmod/GorelikWD94","1QvhrpZ7KBgJ")).
pos(eqo("conf/sigmod/GorelikWD94","h10FxbLW6zAJ")).
pos(eqo("conf/sigmod/GrayHOS96","Mopy3Yg3i60J")).
pos(eqo("conf/sigmod/GrayHOS96","imwZsCcZvFQJ")).
pos(eqo("conf/sigmod/GrayHOS96","pDjbDK0ZzsMJ")).
pos(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
pos(eqo("conf/sigmod/GuhaRS98","Y8HMa1ZZE6sJ")).
pos(eqo("conf/sigmod/GuhaRS98","dD4qUMoxnpEJ")).
pos(eqo("conf/sigmod/GuhaRS98","dV7p-cfTjUQJ")).
pos(eqo("conf/sigmod/GuhaRS98","eQlApCaSdEEJ")).
pos(eqo("conf/sigmod/GuhaRS98","oWVyLUIy9JwJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","2rysKgS6lugJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","ahrxo47nJtMJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","uPHrOdEDjlEJ")).
pos(eqo("conf/sigmod/Hammond99","-ndr_jftgFkJ")).
pos(eqo("conf/sigmod/HanKS97","yzL3Kfsz8scJ")).
pos(eqo("conf/sigmod/HanPY00","2xwKDuA0DI8J")).
pos(eqo("conf/sigmod/HanPY00","R-ERjYdCskcJ")).
pos(eqo("conf/sigmod/HanPY00","YkKV8PCox8IJ")).
pos(eqo("conf/sigmod/HanPY00","aUm_NiRzVOIJ")).
pos(eqo("conf/sigmod/HanPY00","fKrgMlFaEJsJ")).
pos(eqo("conf/sigmod/HanPY00","hlrRtJigGbYJ")).
pos(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
pos(eqo("conf/sigmod/HellersteinN96","5vvOcgfpjUgJ")).
pos(eqo("conf/sigmod/HellersteinN96","vCvPdFwbKWkJ")).
pos(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
pos(eqo("conf/sigmod/HinneburgKW02","VWd7jhLXfV0J")).
pos(eqo("conf/sigmod/HouZ95","AeRUCf7iBqYJ")).
pos(eqo("conf/sigmod/IvesLPST00","4-FwpSOweRAJ")).
pos(eqo("conf/sigmod/JaedickeM98","LrJw7qiWElQJ")).
pos(eqo("conf/sigmod/JaedickeM98","MswqiEweEGUJ")).
pos(eqo("conf/sigmod/JagatheesanR03","fobv5DPqKUcJ")).
pos(eqo("conf/sigmod/JonssonFS98","5fb1l1MyGisJ")).
pos(eqo("conf/sigmod/KabraD98","V9XUvirmVEEJ")).
pos(eqo("conf/sigmod/KanthRSB99","yPFlbrVJFJoJ")).
pos(eqo("conf/sigmod/Keim96","VMUQxO5sWMUJ")).
pos(eqo("conf/sigmod/KiesslingHFE01","tNzM8E3W2K4J")).
pos(eqo("conf/sigmod/KimC03","BWV2Oys1VXsJ")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/KotidisR98","CpHJwU8o-BkJ")).
pos(eqo("conf/sigmod/KrishnamurthyBN99","qS4jhfgPbm8J")).
pos(eqo("conf/sigmod/KuhnTS94","JnV4W3TKPxMJ")).
pos(eqo("conf/sigmod/LabrinidisR00","DKUouEkK_b4J")).
pos(eqo("conf/sigmod/LangS01","OubIayl1628J")).
pos(eqo("conf/sigmod/LarsonG03","14VyjJ0mnBMJ")).
pos(eqo("conf/sigmod/LarsonG03","w8uge-ZzJV0J")).
pos(eqo("conf/sigmod/LiS98","Vxg-4KP7FfEJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","WSQzzj42AkEJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","izDXhqRW9AYJ")).
pos(eqo("conf/sigmod/LuMSS95","Kk87yanaI1AJ")).
pos(eqo("conf/sigmod/LuoKMPWLN02","zQfzn1t6Xq8J")).
pos(eqo("conf/sigmod/McAuliffeCS96","C0vLucG1HBMJ")).
pos(eqo("conf/sigmod/McAuliffeCS96","c__Nxyn_uvwJ")).
pos(eqo("conf/sigmod/McIverK94","LMV_K5t2am0J")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/MinPC03","JjrRZt4ONqMJ")).
pos(eqo("conf/sigmod/MogiK96","hxWB8uQMCdgJ")).
pos(eqo("conf/sigmod/MogiK96","ybgxHuCAS_8J")).
pos(eqo("conf/sigmod/NestorovAM98","5icRoG_Vmc0J")).
pos(eqo("conf/sigmod/NestorovAM98","XP7FEaxDfuAJ")).
pos(eqo("conf/sigmod/Nori00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.335474")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","I0KBB-n-eF8J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/ONeilQ97","FOruO1PeowAJ")).
pos(eqo("conf/sigmod/ONeilQ97","cyNtXv744CQJ")).
pos(eqo("conf/sigmod/ONeilQ97","rN34VXyq84YJ")).
pos(eqo("conf/sigmod/OhHP00","o8cVWUElfUsJ")).
pos(eqo("conf/sigmod/OrdonezC00","yWkfJz_YMPkJ")).
pos(eqo("conf/sigmod/ParkCY95","8CqjZ166ScEJ")).
pos(eqo("conf/sigmod/ParkCY95","hLrdara3zskJ")).
pos(eqo("conf/sigmod/ParkCY95","ko0i4AzclBgJ")).
pos(eqo("conf/sigmod/PeiMHZ00","UyhrqiH_-MoJ")).
pos(eqo("conf/sigmod/Pirahesh94","VG96hL8afvgJ")).
pos(eqo("conf/sigmod/RafieiM97","F9KzvnDpCPUJ")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","PurSnqtdtCgJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","fKiXyCQ0LNgJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","y8Sm4Sh4hokJ")).
pos(eqo("conf/sigmod/RundensteinerKZWLLN99","2XRfNjwuDrsJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","QZQt-pSMhYQJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","a7v0bHRrpjMJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","e0UYPB4kRCYJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wnMZjFGvYVQJ")).
pos(eqo("conf/sigmod/SeidlK98","B8MoLkcvms4J")).
pos(eqo("conf/sigmod/SeshadriLR94","G4N8qaBAG4kJ")).
pos(eqo("conf/sigmod/SeshadriP97","f9POLlECN2gJ")).
pos(eqo("conf/sigmod/SeshadriP97","wozKEQCoZvwJ")).
pos(eqo("conf/sigmod/ShanmugasundaramNSR99","eQjFv7QxsQQJ")).
pos(eqo("conf/sigmod/Sheth95","0CD9uUPdnbUJ")).
pos(eqo("conf/sigmod/Sheth95","eU-7sSXW5jEJ")).
pos(eqo("conf/sigmod/ShintaniK98","9dllFM2Tr5oJ")).
pos(eqo("conf/sigmod/ShuklaD00","07dT02YX07AJ")).
pos(eqo("conf/sigmod/ShuklaD00","yGz8BLxbPPcJ")).
pos(eqo("conf/sigmod/Stonebraker98","Tpkccl5rvR0J")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","1tKWKmyczaYJ")).
pos(eqo("conf/sigmod/TatarinovIHW01","zEHD3Nn_9nsJ")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","0HlMHEPJRH4J")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","gYWmOPwa7mwJ")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","W1IuO3EFDJ8J")).
pos(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
pos(eqo("conf/sigmod/WangSSZZW00","CaplZan57x4J")).
pos(eqo("conf/sigmod/WangSSZZW00","ryDHZM31rmwJ")).
pos(eqo("conf/sigmod/WangZS95","QHrpE-XaLoMJ")).
pos(eqo("conf/sigmod/WhiteCF98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/WhiteD94","qeHXdJ2x7eMJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","GfRmtB2qhgYJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VCc6IQulRJ4J")).
pos(eqo("conf/sigmod/ZhangNBB94","qOgXuRc7f4QJ")).
pos(eqo("conf/sigmod/ZhangNDLL01","ryaV3kTsJ2IJ")).
pos(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
pos(eqo("conf/sigmod/ZhaoDN97","b-Va1c3t13gJ")).
pos(eqo("conf/sigmod/ZhouR02","-hUVSdRv5UUJ")).
pos(eqo("conf/sigmod/ZhuS03","J28mMeNrts4J")).
pos(eqo("conf/sigmod/ZhuS03","QZs7L6Y94_UJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","lUxILYnWlLYJ")).
pos(eqo("conf/vldb/AbiteboulBBCCDMMP03","fANcvlGA8WAJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","OqpwlRWdIMgJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","kuueK-yBQqMJ")).
pos(eqo("conf/vldb/AcharyaFZ96","ccEW59Ac84MJ")).
pos(eqo("conf/vldb/AcharyaFZ96","qTCsXcCsI7UJ")).
pos(eqo("conf/vldb/AcharyaFZ96","sSwdOhIGec0J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AgrawalK02","qCvXLXmB6J8J")).
pos(eqo("conf/vldb/AilamakiDHS01","265Cu1i6gvQJ")).
pos(eqo("conf/vldb/AnSVKIG01","HosSI1GtRY8J")).
pos(eqo("conf/vldb/AnandBH94","-UpQkB1uPLMJ")).
pos(eqo("conf/vldb/AnciauxBBPV01","H2qCU9-_uykJ")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/vldb/AndreiV01","Ms4IJoI6-34J")).
pos(eqo("conf/vldb/BamfordBKM98","rfuptELfgLkJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","4AcfxYXwZnIJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","AgqQVeQ7A0AJ")).
pos(eqo("conf/vldb/BestavrosB95","LDv4my6gWJQJ")).
pos(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","IROKbaAxI6QJ")).
pos(eqo("conf/vldb/BraumandlCK98","rH5VOr1x-a8J")).
pos(eqo("conf/vldb/BrownG01","aJoPVuDNDSsJ")).
pos(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("conf/vldb/CasatiDGS01","bFnDGrZ_4voJ")).
pos(eqo("conf/vldb/CeriCW00","HbrsuuNPd1QJ")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","jNb5aoFeS7wJ")).
pos(eqo("conf/vldb/ChangG97","2SYiXa0vGN4J")).
pos(eqo("conf/vldb/ChaudhuriG99","l-Sn0enuHxkJ")).
pos(eqo("conf/vldb/Chawathe99","w6VtZRVAZV8J")).
pos(eqo("conf/vldb/ChenCFGJMTW99","Hq3W65us8dkJ")).
pos(eqo("conf/vldb/ChenDZ03","cCpHMzAXRnsJ")).
pos(eqo("conf/vldb/ChenHWW02","kgXRJZKRxZQJ")).
pos(eqo("conf/vldb/CosleyLP02","BTalXWt3faUJ")).
pos(eqo("conf/vldb/CotterB00","SJ6PiY04ebMJ")).
pos(eqo("conf/vldb/DarFJST96","95lS1rShpqQJ")).
pos(eqo("conf/vldb/DarFJST96","cM4adSkCTK0J")).
pos(eqo("conf/vldb/DarFJST96","sRhjAJHtl-sJ")).
pos(eqo("conf/vldb/DattaDTVRF01","8_5A88ESaQ0J")).
pos(eqo("conf/vldb/DattaDTVRF01","rDObsYKVroMJ")).
pos(eqo("conf/vldb/DayalHL01","XuhtK-DsK6gJ")).
pos(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
pos(eqo("conf/vldb/DittrichSTW02","egCgEjikCgAJ")).
pos(eqo("conf/vldb/DongHLPW01","C_H34ddegI8J")).
pos(eqo("conf/vldb/FankhauserGLMT98","JnwUAxUMwvQJ")).
pos(eqo("conf/vldb/FernandezSCMS03","FjmyLJQ2TrYJ")).
pos(eqo("conf/vldb/FernandezSCMS03","sn_R4N1q2SwJ")).
pos(eqo("conf/vldb/FlescaFM03","LXjSnbxB7EsJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","OEpwAcnqlWwJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","RZZjZ_7yJb8J")).
pos(eqo("conf/vldb/GalhardasFSSS01","XtFcz806WQEJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","otGW0G5B6AYJ")).
pos(eqo("conf/vldb/GardarinST96","OHR5iQWPuyYJ")).
pos(eqo("conf/vldb/GardarinST96","RB2VKRwnXywJ")).
pos(eqo("conf/vldb/GilbertKMS01","9rDLhwM_4mYJ")).
pos(eqo("conf/vldb/GoldsteinR00","30fMB9_zBm0J")).
pos(eqo("conf/vldb/GottlobKP02","lmLjPf_m6jwJ")).
pos(eqo("conf/vldb/GoyalHSS95","2w2qkhr3k3kJ")).
pos(eqo("conf/vldb/GravanoIJKMS01","iAYjhuQV_qMJ")).
pos(eqo("conf/vldb/Greco98","CCr8CUlHeNsJ")).
pos(eqo("conf/vldb/GrumbachRS00","iQ3Zi3crc9wJ")).
pos(eqo("conf/vldb/GuPS00","mRWLGqueLNsJ")).
pos(eqo("conf/vldb/HaasB03","52x78w6qgcwJ")).
pos(eqo("conf/vldb/HasanM95","-aml_OMAQNgJ")).
pos(eqo("conf/vldb/HasanM95","8cd64f0t0-EJ")).
pos(eqo("conf/vldb/HelmerWM98","5ipPVLRhDqoJ")).
pos(eqo("conf/vldb/HelmerWM98","7Ycm8V-i9g0J")).
pos(eqo("conf/vldb/HinneburgAK00","wQy061nMBCgJ")).
pos(eqo("conf/vldb/HoelS95","7KsyQNj74A4J")).
pos(eqo("conf/vldb/HuebschHLLSS03","B_Gmn8T4IDQJ")).
pos(eqo("conf/vldb/IwerksSS03","4B_LhCns0WoJ")).
pos(eqo("conf/vldb/JagadishLRSS94","Yiwh22hbTAcJ")).
pos(eqo("conf/vldb/JagadishMN99","9rDll5YAQnoJ")).
pos(eqo("conf/vldb/JiangWL03","s3bawcAka-EJ")).
pos(eqo("conf/vldb/JohnsonM98","cTZLUZ5_cfkJ")).
pos(eqo("conf/vldb/JosifovskiR99","rR9r4Kuzq-4J")).
pos(eqo("conf/vldb/KamelF94","Gr7nw0PAH1sJ")).
pos(eqo("conf/vldb/Keogh02","rKIsQpbRiM0J")).
pos(eqo("conf/vldb/KerstenWFKBC03","Ub6YwssjyiYJ")).
pos(eqo("conf/vldb/KossmannRR02","iGlztgiSTe4J")).
pos(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
pos(eqo("conf/vldb/KoudasIM00","w0kVbjS1psIJ")).
pos(eqo("conf/vldb/KriegelPS00","DOOggMfdGYoJ")).
pos(eqo("conf/vldb/KriegelPS00","VSQ0v1UlIvoJ")).
pos(eqo("conf/vldb/KumarRRT99","fJn_2E8aihYJ")).
pos(eqo("conf/vldb/Ladin00","kPTa4IiS_sgJ")).
pos(eqo("conf/vldb/LeeHJT03","BSE2se70OMYJ")).
pos(eqo("conf/vldb/LevyRO96","VYN0FaeVomUJ")).
pos(eqo("conf/vldb/LevyRO96","bbeft23FHAkJ")).
pos(eqo("conf/vldb/LevyRO96","biHvq8aD3_QJ")).
pos(eqo("conf/vldb/LevyRO96","lrocSfnfPrMJ")).
pos(eqo("conf/vldb/Leymann03","url:http://www.vldb.org/conf/2003/papers/S32P01.pdf")).
pos(eqo("conf/vldb/LiCHPALHAY01","Nn0x6RmkrVwJ")).
pos(eqo("conf/vldb/LongS03","zU4MULiFRrYJ")).
pos(eqo("conf/vldb/Mattos96","EpBlTCJ0_dUJ")).
pos(eqo("conf/vldb/MeccaCM01","Ph7ZpmdNOPEJ")).
pos(eqo("conf/vldb/MengLYWCR98","EcpPzbn2EaIJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("conf/vldb/NgH94","9S2apUr1vPMJ")).
pos(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
pos(eqo("conf/vldb/NgH94","JA55PRiwrMQJ")).
pos(eqo("conf/vldb/NgH94","WjnMy2NiG10J")).
pos(eqo("conf/vldb/NgH94","ltzWlNOJavwJ")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/Objectivity98","o3fkxpcCBskJ")).
pos(eqo("conf/vldb/Orenstein98","VfWJDzGt9JYJ")).
pos(eqo("conf/vldb/OzdenBRS94","ARyxUwGOA10J")).
pos(eqo("conf/vldb/OzdenBRS94","DZ9bjjJVU64J")).
pos(eqo("conf/vldb/OzdenBRS94","T4zyjvy9GdcJ")).
pos(eqo("conf/vldb/OzsuLON01","TJjvg-oIQQsJ")).
pos(eqo("conf/vldb/PacittMS99","jJyGKE2N34gJ")).
pos(eqo("conf/vldb/PapadiasMD98","7vbPCi-dbawJ")).
pos(eqo("conf/vldb/PappasC00","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671850")).
pos(eqo("conf/vldb/PereiraFLS00","KAW0nLm2wVAJ")).
pos(eqo("conf/vldb/PereiraFLS00","WvmKiLA-CqMJ")).
pos(eqo("conf/vldb/PfoserJT00","YBNEZgmh540J")).
pos(eqo("conf/vldb/Pogue98","bYLjqg3pPNgJ")).
pos(eqo("conf/vldb/RamakrishnanR96","3y1e-H-FdC0J")).
pos(eqo("conf/vldb/RamamurthyDS02","uem5wXLoU0wJ")).
pos(eqo("conf/vldb/RamanH01","YX1NHLqXfbkJ")).
pos(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
pos(eqo("conf/vldb/RamanRH99","QLJhG6Rz2T0J")).
pos(eqo("conf/vldb/RastogiS98","AyWUeJ5k2IoJ")).
pos(eqo("conf/vldb/RastogiS98","GDlHdL-s4tIJ")).
pos(eqo("conf/vldb/RastogiS98","yztQfwBZU6EJ")).
pos(eqo("conf/vldb/RezendeH98","njuthCBUMPAJ")).
pos(eqo("conf/vldb/RiedelGF98","xAph8JHK5WsJ")).
pos(eqo("conf/vldb/Sacks-Davis96","GkINzG_IffAJ")).
pos(eqo("conf/vldb/SatheS01","L1IBwD8w1G0J")).
pos(eqo("conf/vldb/ScheuermannSV96","N3Hyyb1Qw8sJ")).
pos(eqo("conf/vldb/ScheuermannSV96","TCAOiofZaFIJ")).
pos(eqo("conf/vldb/SchmidtWKCMB02","CvGGYMrKR2sJ")).
pos(eqo("conf/vldb/SeidlK97","HAG0kCjBu4EJ")).
pos(eqo("conf/vldb/ShaferAM96","5HHRNLsy0sAJ")).
pos(eqo("conf/vldb/ShaferAM96","Jl3IrO4qDqMJ")).
pos(eqo("conf/vldb/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/vldb/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/vldb/SheikholeslamiCZ98","Snx8LBMXFJUJ")).
pos(eqo("conf/vldb/Shenker03","5yETsE57mzgJ")).
pos(eqo("conf/vldb/ShuklaDNR96","Qdw5iM0aKwAJ")).
pos(eqo("conf/vldb/ShuklaDNR96","gTSn7nMr9dQJ")).
pos(eqo("conf/vldb/SindoniTABFGMPPT01","0zdXnl9cQysJ")).
pos(eqo("conf/vldb/SizovGT03","UbQPXbPLMCAJ")).
pos(eqo("conf/vldb/StolteA02","N3Bry6sSMw8J")).
pos(eqo("conf/vldb/Suciu96","GwvN1w9_ZZoJ")).
pos(eqo("conf/vldb/SundaraHCAS01","nUFhC9syaNsJ")).
pos(eqo("conf/vldb/TanEO01","1A06w64wjvcJ")).
pos(eqo("conf/vldb/TianD03","l7glyH7ltuQJ")).
pos(eqo("conf/vldb/TsatalosSI94","--1aoAaGkgQJ")).
pos(eqo("conf/vldb/Tygar98","Q8cPIOWKZZ4J")).
pos(eqo("conf/vldb/Tygar98","lWMzZgqNlSEJ")).
pos(eqo("conf/vldb/VeltriCV01","itG_XrygxXIJ")).
pos(eqo("conf/vldb/VeltriCV01","wN-4Rn5hFnwJ")).
pos(eqo("conf/vldb/VenkataramanZ98","RGh6Gep4ym8J")).
pos(eqo("conf/vldb/Vieille98","nlyEH7GkrjoJ")).
pos(eqo("conf/vldb/Wadler01","TyF71uAlnLsJ")).
pos(eqo("conf/vldb/Wang95","kYYJq-JrCn0J")).
pos(eqo("conf/vldb/WangHH00","qbxHq9qXVrUJ")).
pos(eqo("conf/vldb/WangSG03","T1TgIax4zVcJ")).
pos(eqo("conf/vldb/WangYM97","OnLLKkgfyLUJ")).
pos(eqo("conf/vldb/WangYM97","RiOvjzg_MJwJ")).
pos(eqo("conf/vldb/WangYM97","bnkP_MXjTPcJ")).
pos(eqo("conf/vldb/WeikumMHZ02","W_b-Eo5VaOgJ")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/YanL95","VwsS71_KQX8J")).
pos(eqo("conf/vldb/YangG01","LN1TWlAUa0wJ")).
pos(eqo("conf/vldb/ZirintsisKM99","_UYteGcmBKIJ")).
pos(eqo("journals/sigmod/ACT-NET96","AWM-7zzaO7wJ")).
pos(eqo("journals/sigmod/ACT-NET96","RzsJoG-0KaIJ")).
pos(eqo("journals/sigmod/AndersonS94","aDk2IS_xwToJ")).
pos(eqo("journals/sigmod/AnyanwuS02","LoDGuFLlvsAJ")).
pos(eqo("journals/sigmod/AshishK97","3zbpGI3YqXUJ")).
pos(eqo("journals/sigmod/AshishK97","GiEo36f1syYJ")).
pos(eqo("journals/sigmod/AshishK97","rWfbcLnj7_YJ")).
pos(eqo("journals/sigmod/BabuW01","EWzSBh-jV3IJ")).
pos(eqo("journals/sigmod/BarbaraBFLS94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187455%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BerndtssonH96","8Dj_i69XP60J")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","CuNhtOboaGoJ")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","oFiEYaenxe4J")).
pos(eqo("journals/sigmod/BernsteinDK99","Ye5fTBiMoUwJ")).
pos(eqo("journals/sigmod/BichlerSZ98","goq6Z9bDeSsJ")).
pos(eqo("journals/sigmod/BohmR94","GXApzwcGl78J")).
pos(eqo("journals/sigmod/BonifatiC00","XCdMiXLp41IJ")).
pos(eqo("journals/sigmod/BurtonM98","LOXd8JPfhpwJ")).
pos(eqo("journals/sigmod/BusslerFM02","MkHxLPaNdqoJ")).
pos(eqo("journals/sigmod/BusslerFM02","m56HUW18JKAJ")).
pos(eqo("journals/sigmod/BusslerFM02","ql3mj0XUchsJ")).
pos(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
pos(eqo("journals/sigmod/CaleroPR03","zWoRcQffsq8J")).
pos(eqo("journals/sigmod/CampbellEM03","N9u28V6NZTIJ")).
pos(eqo("journals/sigmod/Chang03","B55TCVoUsnoJ")).
pos(eqo("journals/sigmod/Chaudhri98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D273247%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DoanPSB97","fdM1W8iEk_YJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","vG5FK8BJkZgJ")).
pos(eqo("journals/sigmod/DongS00","gH_HDDJghbAJ")).
pos(eqo("journals/sigmod/DrewHKKLLLSW95","9fcJjh5vHn8J")).
pos(eqo("journals/sigmod/DrewHKKLLLSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219769%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Eisenberg96","ODNMCIJO6xMJ")).
pos(eqo("journals/sigmod/Eisenberg96","yzlys0OQkt8J")).
pos(eqo("journals/sigmod/EisenbergM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290604%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FreemanG96","RzHjAQK7XTsJ")).
pos(eqo("journals/sigmod/Gal99","mOsVdVKwhjwJ")).
pos(eqo("journals/sigmod/GeppertD94","P9xX0UDXnRcJ")).
pos(eqo("journals/sigmod/GottlobKP03a","rDRdlwdHGb0J")).
pos(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
pos(eqo("journals/sigmod/HaritsaS96","qA7JBQahK3wJ")).
pos(eqo("journals/sigmod/HasselbringHHKRRS00","JW49QfQtuTMJ")).
pos(eqo("journals/sigmod/JacobS99","3-iiSyJLwLkJ")).
pos(eqo("journals/sigmod/JaegerF95","oacFELqmw0cJ")).
pos(eqo("journals/sigmod/JainH94","sj_7DWnVQ5gJ")).
pos(eqo("journals/sigmod/KappelR98","XmQ-hlR_wwkJ")).
pos(eqo("journals/sigmod/KaradimitriouT97","SrCBkHnIFL8J")).
pos(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
pos(eqo("journals/sigmod/Kosch02","_avm808LQocJ")).
pos(eqo("journals/sigmod/LacroixB03","url:http://portal.acm.org/citation.cfm%3Fid%3D640990.641003%26dl%3Dportal%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LightstoneLZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601873%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LinP96","mzEHvKsUv5QJ")).
pos(eqo("journals/sigmod/LometBCLN98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MalaikaEM03","OGh0R54BW0MJ")).
pos(eqo("journals/sigmod/MalaikaEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945739%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MaximilienS02","hgjhR8PwNVwJ")).
pos(eqo("journals/sigmod/MedeirosP94","tnHDLJxMoQcJ")).
pos(eqo("journals/sigmod/MedskerCS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltonE02","6uelfg3RgEoJ")).
pos(eqo("journals/sigmod/MeltonE02","IqEw9ssJ2QAJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","IoNxL_rg2_cJ")).
pos(eqo("journals/sigmod/MeltzerC98","77mq-gn4LiAJ")).
pos(eqo("journals/sigmod/NormanZT96","rPFgPOAANuQJ")).
pos(eqo("journals/sigmod/NorrieBSW94","q6YVJJgD1uQJ")).
pos(eqo("journals/sigmod/PalpanasPKG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959074%26type%3Dpdf%26dl%3DGUIDE%26dl%3Dacm%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/PourabbasR02","QyNfyYDySawJ")).
pos(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245909%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RamamrithamS97","HR-yLNuhtl4J")).
pos(eqo("journals/sigmod/RoantreeMH99","7-Suml1GqBQJ")).
pos(eqo("journals/sigmod/SantucciT96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245898%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","mkfP-JNsNZoJ")).
pos(eqo("journals/sigmod/SegevJS95","2kiNfwTpqp4J")).
pos(eqo("journals/sigmod/Seshadri98","XijyPb231fAJ")).
pos(eqo("journals/sigmod/ShethGJRSWW96","ub2wqqQgD40J")).
pos(eqo("journals/sigmod/Sidell96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245906%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SlivinskasJS02","xTPSs2k_pUIJ")).
pos(eqo("journals/sigmod/Stonebraker02","0HMk-YUh4i8J")).
pos(eqo("journals/sigmod/SureSS02","A-OWMulBkOoJ")).
pos(eqo("journals/sigmod/TanakaV01","sQu8znidi50J")).
pos(eqo("journals/sigmod/TheodoridisN00","DXTczW8Dv4MJ")).
pos(eqo("journals/sigmod/TheodoridisN00","NegSmYlF-awJ")).
pos(eqo("journals/sigmod/TsotrasK96","-FGfZQ_8TxIJ")).
pos(eqo("journals/sigmod/TsotrasK96","9HEdn3A13BQJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/Wedekind94","gqehj3-ukjIJ")).
pos(eqo("journals/sigmod/Winslett94","hZOXZJ6x2xUJ")).
pos(eqo("journals/sigmod/WinslettCDHZZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Wong95","7F9iCGggYVgJ")).
pos(eqo("journals/tods/AikenHW95","XLld3hq3vt0J")).
pos(eqo("journals/tods/AndriesCPB01","iMGwasyHkgIJ")).
pos(eqo("journals/tods/BaralisW00","4RrNbX-RjpsJ")).
pos(eqo("journals/tods/Bohm00","i5nEuutK3H4J")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/tods/BunemanO96","xT4l9LBtTcUJ")).
pos(eqo("journals/tods/CastanoAFP98","X7wtR1g63qEJ")).
pos(eqo("journals/tods/CliffordC94","OY6BjHhbz2cJ")).
pos(eqo("journals/tods/EiterLLS01","tEZIquYevQoJ")).
pos(eqo("journals/tods/FernandezKSMT02","ckrgSn0vBOMJ")).
pos(eqo("journals/tods/Hellerstein98","q8m4M7OxSSAJ")).
pos(eqo("journals/tods/KossmannS00","XyQ6cXyNPN4J")).
pos(eqo("journals/tods/LakshmananLN03","g8e0xiRUkIwJ")).
pos(eqo("journals/tods/LakshmananLRS97","UByN6paxEXwJ")).
pos(eqo("journals/tods/LiuM96","xeceK06Z5DIJ")).
pos(eqo("journals/tods/SistlaWYS98","4owPoyytTP4J")).
pos(eqo("journals/tods/Subrahmanian94","MWxdDHB-vH8J")).
pos(eqo("journals/tods/Subrahmanian94","UumKoUpnFSwJ")).
pos(eqo("journals/tods/Subrahmanian94","YAkzY3hCPxQJ")).
pos(eqo("journals/tods/TaoP03","faqaX7J_Kl8J")).
pos(eqo("journals/tods/TaoPZ02","CxBJwFNdozAJ")).
pos(eqo("journals/tods/TaoSP03","FBp7oibu4ygJ")).
pos(eqo("journals/tods/WangBBJ97","NYQMkdaH2egJ")).
pos(eqo("journals/tods/WangBBJ97","uaaJl906vYoJ")).
pos(eqo("journals/vldb/Antoshenkov97","gleX-n_dgkcJ")).
pos(eqo("journals/vldb/BerendtS00","nm9rCU6yVNwJ")).
pos(eqo("journals/vldb/BerendtS00","zh9CAewEvisJ")).
pos(eqo("journals/vldb/BohmAnY97","PALTnITURBcJ")).
pos(eqo("journals/vldb/C95b","url:http://www.springerlink.com/index/J267M1G774146066.pdf")).
pos(eqo("journals/vldb/ChakrabartiDAR98","0EbuWDceVnoJ")).
pos(eqo("journals/vldb/ChanGR03","wUcXmf9G52gJ")).
pos(eqo("journals/vldb/ChandrasekaranF03","b9r9U3OwrkcJ")).
pos(eqo("journals/vldb/DanYC95","SsOLRJZrmtYJ")).
pos(eqo("journals/vldb/DiazJ97","RKAY1aZAeCoJ")).
pos(eqo("journals/vldb/EvangelidisS97","5dnYlEMQTb0J")).
pos(eqo("journals/vldb/GrefenVA01","fohOTTsEtIwJ")).
pos(eqo("journals/vldb/GruserRZZ00","9EBKpmSLc_oJ")).
pos(eqo("journals/vldb/HalkidiNVV03","J0hrpRuvSgMJ")).
pos(eqo("journals/vldb/HarderR96","pWXIPx5lA7gJ")).
pos(eqo("journals/vldb/HjaltasonS02","FH41DtWf_jAJ")).
pos(eqo("journals/vldb/IvesHW02","Bbm74R5b5yoJ")).
pos(eqo("journals/vldb/Li03","XkdLpQ5x-YIJ")).
pos(eqo("journals/vldb/MehtaD97","zppqMPNFTQIJ")).
pos(eqo("journals/vldb/OoiTCH98","xv1webZ985MJ")).
pos(eqo("journals/vldb/OzsuPSILM95","2Y6WYH71fO0J")).
pos(eqo("journals/vldb/OzsuPSILM95","gld2wLKYWpsJ")).
pos(eqo("journals/vldb/PottingerH01","Kv3ZFRUKCogJ")).
pos(eqo("journals/vldb/PottingerH01","M2zV0WBF7XYJ")).
pos(eqo("journals/vldb/PottingerH01","mpnnRdFUUJQJ")).
pos(eqo("journals/vldb/RahmB01","707RPzHAB8YJ")).
pos(eqo("journals/vldb/RahmB01","nXi88wdaXIkJ")).
pos(eqo("journals/vldb/RamanRH00","CgiCp6N9XZQJ")).
pos(eqo("journals/vldb/SaltenisJ02","HSEOZDaC8ZUJ")).
pos(eqo("journals/vldb/Seshadri98","yXXD9DeXoAgJ")).
pos(eqo("journals/vldb/ShyyASL96","zdkN438QOV4J")).
pos(eqo("journals/vldb/SinghalS97","3fO2448hZgwJ")).
pos(eqo("journals/vldb/TanGO00","url:http://www.springerlink.com/index/4N8LT3XHXGCR8DLW.pdf")).
pos(eqo("journals/vldb/WhiteD95","qeHXdJ2x7eMJ")).
