neg(eqo("conf/sigmod/AggarwalWY99","ehQdT03ejIgJ")).
neg(eqo("conf/sigmod/AggarwalWY99","lAbG3uFZvVUJ")).
neg(eqo("conf/sigmod/BabcockO03","AQOcKd6cVZsJ")).
neg(eqo("conf/sigmod/BaumannDFRW98","rLKRzM3xpA0J")).
neg(eqo("conf/sigmod/BenediktCFFR03","F2hJ_IGiHj8J")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","oulaZpEWkMQJ")).
neg(eqo("conf/sigmod/BressanGOT00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BressanGOT00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776990%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
neg(eqo("conf/sigmod/BrunoCG01","SGmfFHnOf4IJ")).
neg(eqo("conf/sigmod/Cattell94","UYAoi4DYOXUJ")).
neg(eqo("conf/sigmod/Chan98","oo2mr5fbMggJ")).
neg(eqo("conf/sigmod/ChangG99","m9eI-g89UagJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","6YgzNu3UQqMJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","Lm25su-wny0J")).
neg(eqo("conf/sigmod/DogacHKOONDMAKE96","GnjIUQVlZ0UJ")).
neg(eqo("conf/sigmod/Ellison95","f1PnB8Owd7AJ")).
neg(eqo("conf/sigmod/FegarasM95","bKhGCJV3l6sJ")).
neg(eqo("conf/sigmod/FegarasSRM00","oBfyEPhQ5TsJ")).
neg(eqo("conf/sigmod/GrayHOS96","FpZW-VfKnCYJ")).
neg(eqo("conf/sigmod/GraySEBW94","JT61IMQEZ-QJ")).
neg(eqo("conf/sigmod/GuptaS03","7ggq-jY7UEYJ")).
neg(eqo("conf/sigmod/HaasH99","YRqk67QvqLkJ")).
neg(eqo("conf/sigmod/JosifovskiSHL02","hnMltY0uSf0J")).
neg(eqo("conf/sigmod/KrishnamurthyBN99","qS4jhfgPbm8J")).
neg(eqo("conf/sigmod/Melling94","29btu5OspbAJ")).
neg(eqo("conf/sigmod/Meseck01","NQShGztSLaoJ")).
neg(eqo("conf/sigmod/Mohan94","Ft1YZIFfu0cJ")).
neg(eqo("conf/sigmod/MumickP94","L61_1TEGBLYJ")).
neg(eqo("conf/sigmod/PatelD96","GAQbbOw3ICQJ")).
neg(eqo("conf/sigmod/RaoZML02","7Ucs6vmjHN0J")).
neg(eqo("conf/sigmod/RiedelFGN00","X3jpFEH_f5UJ")).
neg(eqo("conf/sigmod/RodriguezR00","MCDgDxsc8rcJ")).
neg(eqo("conf/sigmod/RossSS96","KamrJHXS4JgJ")).
neg(eqo("conf/sigmod/SarawagiTA98","ZjYNpcdNJnUJ")).
neg(eqo("conf/sigmod/Wu99","xl1Jscb79KEJ")).
neg(eqo("conf/vldb/AmsalegFG95","F2ecYx97F2sJ")).
neg(eqo("conf/vldb/AnkerstBKS98","YXQzCfAREjYJ")).
neg(eqo("conf/vldb/BerchtoldKK96","vI9c-zUADl8J")).
neg(eqo("conf/vldb/Brin95","dXegp-RmzXEJ")).
neg(eqo("conf/vldb/CabreraRH95","NbLabaGWoh4J")).
neg(eqo("conf/vldb/Carey00","d5pctGrBJ8wJ")).
neg(eqo("conf/vldb/CarneyCCCLSSTZ02","rrHY2sIxHd4J")).
neg(eqo("conf/vldb/ChangG00","O2cGL7dA2Q0J")).
neg(eqo("conf/vldb/ChatziantoniouR97","0GMNedjfVV0J")).
neg(eqo("conf/vldb/CherniackZ98","h6R5rXre-_QJ")).
neg(eqo("conf/vldb/CotterB00","OOrFZpsJBAUJ")).
neg(eqo("conf/vldb/EleftheriouBCDHLPPABDDDGJHLRSVW03","ml-oFmPRY6AJ")).
neg(eqo("conf/vldb/EsterKSWX98","ZRmUC-fhmFEJ")).
neg(eqo("conf/vldb/FaloutsosG96","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/GilbertKMS01","9rDLhwM_4mYJ")).
neg(eqo("conf/vldb/GionisIM99","a1_mvYBrjyAJ")).
neg(eqo("conf/vldb/GoyalHSS95","fPgtEqv986IJ")).
neg(eqo("conf/vldb/HuntAI01","0i8ezRQ6tJIJ")).
neg(eqo("conf/vldb/Huyn97","LcX8Pm2ABJsJ")).
neg(eqo("conf/vldb/IlyasAE03","Y385z1Dxp84J")).
neg(eqo("conf/vldb/IoannidisP99","ocU8aFaXuPwJ")).
neg(eqo("conf/vldb/Jamil97","ofxLw3VrJB8J")).
neg(eqo("conf/vldb/Johnson99","lMhJmpFBjO0J")).
neg(eqo("conf/vldb/KerstenWFKBC03","h7_vmoCZRbIJ")).
neg(eqo("conf/vldb/Korth95","gtNSqHrvPY0J")).
neg(eqo("conf/vldb/Korth95","uaBFEbrUTdkJ")).
neg(eqo("conf/vldb/LempelM02","wZDydpS4xiwJ")).
neg(eqo("conf/vldb/LiM01","Axu6UlX-pPYJ")).
neg(eqo("conf/vldb/MeekPK03","cR1ikuFsE1wJ")).
neg(eqo("conf/vldb/Mohan99","YJlUtEk7zwkJ")).
neg(eqo("conf/vldb/MoserKK95","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/OConnellWG01","ftWHg08h9poJ")).
neg(eqo("conf/vldb/PoosalaI96","ZnJEzO1Fj_EJ")).
neg(eqo("conf/vldb/SeidlK97","TodiMgxv4vMJ")).
neg(eqo("conf/vldb/ShuklaDNR96","mDj9X3EN9ycJ")).
neg(eqo("conf/vldb/SilversteinBMU98","9MlAuURfKhYJ")).
neg(eqo("conf/vldb/SimonD95","rl8LrhUBqIQJ")).
neg(eqo("conf/vldb/SreenathS94","GikTB2GHnJoJ")).
neg(eqo("conf/vldb/SrikantA95","bpWvAVOZLbwJ")).
neg(eqo("conf/vldb/SteinbrunnPMK95","RNWqTt8Ib5cJ")).
neg(eqo("conf/vldb/StohrMR00","XD-dPSkTs1oJ")).
neg(eqo("conf/vldb/Suciu96","Y7kHpHu3nP0J")).
neg(eqo("conf/vldb/TeisseirePC94","JCQQgBm1c-UJ")).
neg(eqo("conf/vldb/ZellerK02","UIWreKZndVQJ")).
neg(eqo("journals/sigmod/AilamakiH03","S30IXg4ClFIJ")).
neg(eqo("journals/sigmod/AnyanwuS02","VsotCt1y5zUJ")).
neg(eqo("journals/sigmod/Bernstein98","m42J4EvvK_wJ")).
neg(eqo("journals/sigmod/BohmR94","6ussAgzdL6oJ")).
neg(eqo("journals/sigmod/CaplinskasEV02","IyeZMyQsfx8J")).
neg(eqo("journals/sigmod/CeriFP99","zCbDZVfxWhAJ")).
neg(eqo("journals/sigmod/Cetintemel01","CAKcsKXFoCoJ")).
neg(eqo("journals/sigmod/DadamK97","OFGtGwUHhUQJ")).
neg(eqo("journals/sigmod/Domingo-FerrerH98","C3hXJgGQpHkJ")).
neg(eqo("journals/sigmod/Eisenberg96","tFbkjO2wcFMJ")).
neg(eqo("journals/sigmod/Franklin00","WHWa6vBvwJ0J")).
neg(eqo("journals/sigmod/Hellerstein03","ALy38oHr8P8J")).
neg(eqo("journals/sigmod/Jhingran00","x4yg_lA5VUsJ")).
neg(eqo("journals/sigmod/Keim96","uypnc5Gb9iIJ")).
neg(eqo("journals/sigmod/LaenderRST02","UYAoi4DYOXUJ")).
neg(eqo("journals/sigmod/LawderK01","_OiJpjTV4D0J")).
neg(eqo("journals/sigmod/Liu01a","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/NorrieBSW94","6FB5cvNH9cwJ")).
neg(eqo("journals/sigmod/PaepckeGRC00","7zzvk7QwqJYJ")).
neg(eqo("journals/sigmod/PuSW01","nkW4iN6JqfAJ")).
neg(eqo("journals/sigmod/Qian95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Rosenthal98","XXITu1aTrGsJ")).
neg(eqo("journals/sigmod/Rosneblatt94","ZMAMIWxralYJ")).
neg(eqo("journals/sigmod/RossIJP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass94","G2DIA_Pr5jYJ")).
neg(eqo("journals/sigmod/Ulusoy95","oo2mr5fbMggJ")).
neg(eqo("journals/sigmod/WangD03","SIkbMfbKvDUJ")).
neg(eqo("journals/sigmod/Wu02","SFs0XOMPphIJ")).
neg(eqo("journals/tods/BellNNS96","BUlvAkEuODkJ")).
neg(eqo("journals/tods/ChomickiTB01","eFDhA7HrBdsJ")).
neg(eqo("journals/tods/JajodiaSSS01","Ak43QQOWecoJ")).
neg(eqo("journals/tods/Ng01","1j3MnZC_Gi8J")).
neg(eqo("journals/tods/PetersO97","mQp5jjo-npAJ")).
neg(eqo("journals/tods/StolboushkinT98","YSQbMPHnheoJ")).
neg(eqo("journals/tods/Suciu02","Ikk1rb4o66UJ")).
neg(eqo("journals/tods/ZaharioudakisCF97","O3XEz9_L2LUJ")).
neg(eqo("journals/vldb/ApersCS02","url:http://www.springerlink.com/index/L4H4H12200406465.pdf")).
neg(eqo("journals/vldb/AtkinsonM95","C7Vuxp5KVsAJ")).
neg(eqo("journals/vldb/BalkirO98","v-kvo2hnsgkJ")).
neg(eqo("journals/vldb/ChangG01","rQ-X0nQkvkQJ")).
neg(eqo("journals/vldb/ChenHY97","WdhkPQb0YJYJ")).
neg(eqo("journals/vldb/HarrisR96","H6ZRBGuMeSMJ")).
neg(eqo("journals/vldb/KraissW98","K0aOFYBWg3AJ")).
neg(eqo("journals/vldb/MylopoulosCPST96","Ey7Mbh6IdQIJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","EqMVP0jriNIJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","S4xa9eBPvc0J")).
neg(eqo("journals/vldb/SivasankaranSTPR96","r-Jx4g42sfgJ")).
neg(eqo("journals/vldb/TsatalosSI96","ZrOcCXxAdP0J")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","VlVV2mEnoQ4J")).
pos(eqo("conf/sigmod/AgichteinGV01","z8s4kW1y7LMJ")).
pos(eqo("conf/sigmod/ArasuG03","zN8ngmWNDlgJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","3SHIgRrrL5QJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","nTC3FQGaT_YJ")).
pos(eqo("conf/sigmod/BerchtoldK98","9UYo0M1RV7oJ")).
pos(eqo("conf/sigmod/BorkarDS01","nsoA6Gcc_jsJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294191CI")).
pos(eqo("conf/sigmod/Brown99","itP4yy9sLUUJ")).
pos(eqo("conf/sigmod/CareyFZ94","_Dtj6cJQFAQJ")).
pos(eqo("conf/sigmod/CareyFZ94","xuE2g4v2AjYJ")).
pos(eqo("conf/sigmod/Cattell94","QgR0DgMbdgIJ")).
pos(eqo("conf/sigmod/Cattell94","zSoTbEtLuqEJ")).
pos(eqo("conf/sigmod/ChanI98","MsOTH7U9VnkJ")).
pos(eqo("conf/sigmod/ChanI98","VC7Jbwgn_O0J")).
pos(eqo("conf/sigmod/ChristophidesCS00","R7tBLAw0O3wJ")).
pos(eqo("conf/sigmod/ColeG94","z_W8jZ203sUJ")).
pos(eqo("conf/sigmod/CrescenziMM02","pI0WktymowwJ")).
pos(eqo("conf/sigmod/DeligiannakisR03","zMgbS5u_GwYJ")).
pos(eqo("conf/sigmod/DeshpandeGR01","0Ta25VSGl7kJ")).
pos(eqo("conf/sigmod/DraperHW01","6MdiqTp20aoJ")).
pos(eqo("conf/sigmod/EmbleyJN99","x8uC_9_IzUEJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","R4fVVmv_YvoJ")).
pos(eqo("conf/sigmod/FernandezS96","iLwFjrX22vYJ")).
pos(eqo("conf/sigmod/FernandezS96","lMKrltuk53EJ")).
pos(eqo("conf/sigmod/GodfreySE98","-H3tXntLhowJ")).
pos(eqo("conf/sigmod/GuhaRS98","Dux-7sONElwJ")).
pos(eqo("conf/sigmod/GuhaRS98","LoR0K8QRGkgJ")).
pos(eqo("conf/sigmod/GuhaRS98","dD4qUMoxnpEJ")).
pos(eqo("conf/sigmod/GuhaRS98","dV7p-cfTjUQJ")).
pos(eqo("conf/sigmod/GuptaS03","6ditJPVnXAQJ")).
pos(eqo("conf/sigmod/KanthRSB99","I48hanU3OR4J")).
pos(eqo("conf/sigmod/Kim94","GzJII5F7OzAJ")).
pos(eqo("conf/sigmod/KotidisR99","323DOAMQyUkJ")).
pos(eqo("conf/sigmod/KriegelBKPS03","tsqBH6P4jMcJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","8a9NXXE4xiwJ")).
pos(eqo("conf/sigmod/MaheshwariL97","VcVAYDLTty8J")).
pos(eqo("conf/sigmod/NazeriBO01","2E9I_lugGC4J")).
pos(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
pos(eqo("conf/sigmod/PatelD96","Goan1fI4O_oJ")).
pos(eqo("conf/sigmod/PatelD96","oPdpBiAjcisJ")).
pos(eqo("conf/sigmod/QuassW97","3o4t-svHQfcJ")).
pos(eqo("conf/sigmod/QuassW97","RFd0c3lXk1AJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","QzW5By67KwcJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","l1tbsG6UXaMJ")).
pos(eqo("conf/sigmod/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","aym35wwVDlQJ")).
pos(eqo("conf/sigmod/ZouS96","DYFIQvOg7rgJ")).
pos(eqo("conf/vldb/AbiteboulAAACHHMMMMSTV99","zHCrzBCoweAJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","E4fU9kpfXQsJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/BonczRK98","965BXzMPxSoJ")).
pos(eqo("conf/vldb/CareyHMW96","Nz8zwxjBoyYJ")).
pos(eqo("conf/vldb/DagevilleZ02","x9bmOZxOlE8J")).
pos(eqo("conf/vldb/Dayal99","OoknnZ3rbfwJ")).
pos(eqo("conf/vldb/DongHLPW01","eOTkoLDux4wJ")).
pos(eqo("conf/vldb/DonjerkovicR99","Eq1w4LPv_igJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","X-jmxnecLOEJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","jimNuiynSDIJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","lWVWAhlsyYYJ")).
pos(eqo("conf/vldb/GardarinGT95","DAUHADa6RjQJ")).
pos(eqo("conf/vldb/GionisIM99","3RR94IxW5CUJ")).
pos(eqo("conf/vldb/GottlobKP02","e5Gm5upjQnkJ")).
pos(eqo("conf/vldb/GottlobKP02","gF4nPxSCcOMJ")).
pos(eqo("conf/vldb/HaasKU99","jteJcGoGxnMJ")).
pos(eqo("conf/vldb/HellersteinNP95","V1M4safuoecJ")).
pos(eqo("conf/vldb/KemmeA00","-McZOyw__qQJ")).
pos(eqo("conf/vldb/KnorrN98","yFmekFZgZmwJ")).
pos(eqo("conf/vldb/KoschBBHHLRT01","xvNBOkc3UkcJ")).
pos(eqo("conf/vldb/LabrinidisR03","0GMNedjfVV0J")).
pos(eqo("conf/vldb/LernerS03","Xs8A5V9n3okJ")).
pos(eqo("conf/vldb/LevyRO96","biHvq8aD3_QJ")).
pos(eqo("conf/vldb/LimWPVP02","9kl_hTyQtmQJ")).
pos(eqo("conf/vldb/ManolescuFK01","ckjlnFHOwd8J")).
pos(eqo("conf/vldb/ManolescuFKXO00","t19PsyGam1EJ")).
pos(eqo("conf/vldb/MaratheS97","HcgXkUDB-wYJ")).
pos(eqo("conf/vldb/MoserKK95","A2OQAUw2OHIJ")).
pos(eqo("conf/vldb/MoserKK95","RAKdMsfUX6QJ")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/ShahDR03","Zlk6Tn-sPxwJ")).
pos(eqo("conf/vldb/ShengBDM02","TdjMAASfHFoJ")).
pos(eqo("conf/vldb/SistlaYH94","FT4Sfn-Z7GUJ")).
pos(eqo("conf/vldb/SrikantA95","KIPDo6ym8BUJ")).
pos(eqo("conf/vldb/SrikantA95","OqO-ZxObnjgJ")).
pos(eqo("conf/vldb/SrikantA95","fIcZeXoZ4bIJ")).
pos(eqo("conf/vldb/SrikantA95","kAi6HssDySgJ")).
pos(eqo("conf/vldb/StathatosRB97","PJ755vWjC9MJ")).
pos(eqo("conf/vldb/TsatalosSI94","--1aoAaGkgQJ")).
pos(eqo("conf/vldb/WangYM97","bnkP_MXjTPcJ")).
pos(eqo("conf/vldb/WangYM97","o5dSRIunsUUJ")).
pos(eqo("conf/vldb/YanA94","8j5i7YJQnNAJ")).
pos(eqo("conf/vldb/YanG95","lr_Kq9SZLY8J")).
pos(eqo("conf/vldb/ZhangL98","ZjHAEBJYahAJ")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/BarbaraS97","iOxtnjbC4SEJ")).
pos(eqo("journals/sigmod/BertinoEH03","4m-WmWU5iGYJ")).
pos(eqo("journals/sigmod/BestavrosLS96","RalvsjDuKzsJ")).
pos(eqo("journals/sigmod/Bussche00","abRCzV130REJ")).
pos(eqo("journals/sigmod/DreyerDS94","GCf11c7YuucJ")).
pos(eqo("journals/sigmod/EnglertGH95","WYE9fKutj70J")).
pos(eqo("journals/sigmod/Geller02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KannanKIK03","h_tDfTvsR0QJ")).
pos(eqo("journals/sigmod/MeltzerC98","77mq-gn4LiAJ")).
pos(eqo("journals/sigmod/MusickC99","mA4kKq9Z3tYJ")).
pos(eqo("journals/sigmod/PourabbasR00","3y6y5AXu-j0J")).
pos(eqo("journals/sigmod/RosenthalS99","c6lzPzSWbKAJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","psdMY-oUz4cJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","vUONDuuNNCQJ")).
pos(eqo("journals/sigmod/TsotrasJS98","f3-E7x12K4gJ")).
pos(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
pos(eqo("journals/tods/BeneventanoBS03","rRH6Z1oP78cJ")).
pos(eqo("journals/tods/ChomickiTB01","1DbQL6R2tzMJ")).
pos(eqo("journals/tods/CiacciaTZ96","rkCKzi1v0-0J")).
pos(eqo("journals/tods/KemmeA00","wiUPadLpCvoJ")).
pos(eqo("journals/tods/LiuHD98","ts7DF925TR8J")).
pos(eqo("journals/vldb/AbiteboulCM98","XTa-ElbpjZ8J")).
pos(eqo("journals/vldb/ChirkovaHS02","NdmocXlpq9QJ")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/GruserRZZ00","9EBKpmSLc_oJ")).
pos(eqo("journals/vldb/Guting94","2HXoDqKjpXYJ")).
pos(eqo("journals/vldb/Guting94","NE_HjaA2eAAJ")).
pos(eqo("journals/vldb/HuntAI02","LiYp5oaDwbMJ")).
pos(eqo("journals/vldb/MehtaGPN98","sS3KWBs3gEcJ")).
pos(eqo("journals/vldb/RoySSSA98","5VcKjo7jBOMJ")).
pos(eqo("journals/vldb/RoySSSA98","JB684f38DiwJ")).
pos(eqo("journals/vldb/ShethTP03","Svbxes_XzdUJ")).
