neg(eqo("conf/sigmod/2002","3rBlVqEbkbcJ")).
neg(eqo("conf/sigmod/AbiteboulBCMM03","FtMoh58D330J")).
neg(eqo("conf/sigmod/AbiteboulCM95","CnNejipGlmkJ")).
neg(eqo("conf/sigmod/AcharyaAFZ95","_-yXA5HLnqoJ")).
neg(eqo("conf/sigmod/AdaliSS99","oNPjyBZrURgJ")).
neg(eqo("conf/sigmod/Agarwal96","8pT8PMD8diUJ")).
neg(eqo("conf/sigmod/Aggarwal02","4GzKkSWGohYJ")).
neg(eqo("conf/sigmod/Aggarwal02","4l2AKokjzgkJ")).
neg(eqo("conf/sigmod/Aggarwal02","OuVZjeR64pMJ")).
neg(eqo("conf/sigmod/Aggarwal03","2p2A5_qGf5cJ")).
neg(eqo("conf/sigmod/Aggarwal03","YUtQ8KXNntYJ")).
neg(eqo("conf/sigmod/AggarwalWY99","PBSfHF8A1AQJ")).
neg(eqo("conf/sigmod/AggarwalWY99","ehQdT03ejIgJ")).
neg(eqo("conf/sigmod/AggarwalY00","Qq0WheHyVv8J")).
neg(eqo("conf/sigmod/AgrawalK03","HfEQzVOD9tsJ")).
neg(eqo("conf/sigmod/AgrawalS00","vT6v9qSkI2UJ")).
neg(eqo("conf/sigmod/Al-KhalifaYJ03","KVCNrVHQ3ZoJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","DFubU20j1OIJ")).
neg(eqo("conf/sigmod/Arpaci-DusseauACHP97","sl4RHQ8jHfwJ")).
neg(eqo("conf/sigmod/Aulakh98","IsIOUCR79t8J")).
neg(eqo("conf/sigmod/BarbaraI94","GXhaGGajWZkJ")).
neg(eqo("conf/sigmod/BarclaySG00","3dbNl8ysmWYJ")).
neg(eqo("conf/sigmod/BaruFGHJPW95","TaDjboy5cvoJ")).
neg(eqo("conf/sigmod/BerensonBGMOO95","EKqpEdn3kDMJ")).
neg(eqo("conf/sigmod/BergstraesserBPS99","5FJjEO5B31AJ")).
neg(eqo("conf/sigmod/BersonGM95","_RpELIR-GU8J")).
neg(eqo("conf/sigmod/BertinoCF01","5M1rXxWiqn8J")).
neg(eqo("conf/sigmod/BlakeleyP98","RaOQG4YyzM4J")).
neg(eqo("conf/sigmod/BorkarDS01","XeXDbxZoB-YJ")).
neg(eqo("conf/sigmod/Bosworth03","2gm4auh3-XoJ")).
neg(eqo("conf/sigmod/Bosworth03","DaKuxChQNzEJ")).
neg(eqo("conf/sigmod/BrinMUT97","n2HWVedEvkoJ")).
neg(eqo("conf/sigmod/BrinMUT97","vIwsSOGQOWAJ")).
neg(eqo("conf/sigmod/BrinkhoffKSS94a","EycNQ5gLEx4J")).
neg(eqo("conf/sigmod/BrinkhoffKSS94a","ryyvz4-SdEMJ")).
neg(eqo("conf/sigmod/BunemanDHS96","rNVPCLfguuMJ")).
neg(eqo("conf/sigmod/Carey00","LzJnQP5FoNAJ")).
neg(eqo("conf/sigmod/Carey00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945741%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Carey94","CZSegvSr3zwJ")).
neg(eqo("conf/sigmod/CeriFPP95","DOWitkb7PbUJ")).
neg(eqo("conf/sigmod/Chakravarthy97","3M_0Kd8NNjgJ")).
neg(eqo("conf/sigmod/Chakravarthy97","3ShkGHsL2JgJ")).
neg(eqo("conf/sigmod/ChangG99","S6TMGRGUq1IJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","AeRUCf7iBqYJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","4MaErPILRq8J")).
neg(eqo("conf/sigmod/ChaudhuriKN03","-f2FsG-EC9IJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","KAf2DUUVabIJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","Tagq11E6HfAJ")).
neg(eqo("conf/sigmod/ChawatheRGW96","xPkLZK36UBUJ")).
neg(eqo("conf/sigmod/ChenDLT00","url:http://doi.wiley.com/10.1002/he.10906")).
neg(eqo("conf/sigmod/ChengKP03","EID4UO0Kv04J")).
neg(eqo("conf/sigmod/ChoALS03","url:http://doi.wiley.com/10.1002/tl.102")).
neg(eqo("conf/sigmod/Chong98","KyiVzfH5uNAJ")).
neg(eqo("conf/sigmod/ChooOLCGBPS96","KOpz_NXJ3WUJ")).
neg(eqo("conf/sigmod/CluetDSS98","lOZF0Ee3rUQJ")).
neg(eqo("conf/sigmod/Cohen98a","hsqjQUgj3y0J")).
neg(eqo("conf/sigmod/Cohen98a","nPayw9W0gcoJ")).
neg(eqo("conf/sigmod/ColbyGLMT96","qERv6U2F3hoJ")).
neg(eqo("conf/sigmod/Colliat03","url:http://doi.wiley.com/10.1002/he.119")).
neg(eqo("conf/sigmod/ConsensM94","L1m30vG-d5sJ")).
neg(eqo("conf/sigmod/DarEGP98","bv21uJEzUwAJ")).
neg(eqo("conf/sigmod/DasuJMS02","POt1WbTBB4cJ")).
neg(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
neg(eqo("conf/sigmod/DuSD95","Vl7gY6FsOOYJ")).
neg(eqo("conf/sigmod/Ellison95","etkRTDHKDRoJ")).
neg(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
neg(eqo("conf/sigmod/FernandezFKLS98","jzwiskpRLOUJ")).
neg(eqo("conf/sigmod/FlokstraKS94","9NSJ60mSACsJ")).
neg(eqo("conf/sigmod/FlokstraKS94","ewnL82c8kiMJ")).
neg(eqo("conf/sigmod/FukudaMMT96","Xo4KXwq9XIcJ")).
neg(eqo("conf/sigmod/Galhardas00","GxDfgCi-rq4J")).
neg(eqo("conf/sigmod/GarofalakisG02","ovF40iPyEqUJ")).
neg(eqo("conf/sigmod/GatziuGD95","3aUZ-RtpdV8J")).
neg(eqo("conf/sigmod/GetoorTK01","QIG8th9DHbQJ")).
neg(eqo("conf/sigmod/GillmannWSWW00","8but_7FuryIJ")).
neg(eqo("conf/sigmod/GotoK03","YXokXpbjCFsJ")).
neg(eqo("conf/sigmod/GoyalHKMS96","oo2mr5fbMggJ")).
neg(eqo("conf/sigmod/GraySSU03","-MNdDpWC-sgJ")).
neg(eqo("conf/sigmod/GreenwaldK01","mkodS8HfvFAJ")).
neg(eqo("conf/sigmod/GriffinH97","E495OjIQrqkJ")).
neg(eqo("conf/sigmod/GriffinL95","GzJII5F7OzAJ")).
neg(eqo("conf/sigmod/GriffinL95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GuhaRS98","WHHfHdG_ougJ")).
neg(eqo("conf/sigmod/GuptaS03","7ggq-jY7UEYJ")).
neg(eqo("conf/sigmod/HammerGIPUW95","eA8gNVxHRJ4J")).
neg(eqo("conf/sigmod/HanPY00","A2f8fVoGhZkJ")).
neg(eqo("conf/sigmod/HeC03","MNmlxFx4l-8J")).
neg(eqo("conf/sigmod/HellersteinA00","Gsb6dnkFBMoJ")).
neg(eqo("conf/sigmod/HellersteinHW97","bsfsN1NtuOMJ")).
neg(eqo("conf/sigmod/HellersteinW02","5vvOcgfpjUgJ")).
neg(eqo("conf/sigmod/Hidber99","frRQkHZ98CAJ")).
neg(eqo("conf/sigmod/HinneburgKW02","xxp4Im8OG9AJ")).
neg(eqo("conf/sigmod/Hope95","1urLrX5xC3MJ")).
neg(eqo("conf/sigmod/HristidisKP01","itG_XrygxXIJ")).
neg(eqo("conf/sigmod/ImielinskiV95","3-iiSyJLwLkJ")).
neg(eqo("conf/sigmod/Jagadish94","u1lEQC0sAAIJ")).
neg(eqo("conf/sigmod/JagadishLMSV99","ksjM0TK2-DwJ")).
neg(eqo("conf/sigmod/JajodiaSSB97","9helCh8mlFIJ")).
neg(eqo("conf/sigmod/Jamil99","z5EfiutEfScJ")).
neg(eqo("conf/sigmod/JarkeQBLMS99","KxwymZ2AGNQJ")).
neg(eqo("conf/sigmod/JarkeQCLFLVV00","bl_VrPzIIPwJ")).
neg(eqo("conf/sigmod/Jhingran00","S3BkPvUCbXYJ")).
neg(eqo("conf/sigmod/JohnsonD03","llGIoKCzsiYJ")).
neg(eqo("conf/sigmod/JonkerS95","p1mxeWp73cMJ")).
neg(eqo("conf/sigmod/JonkerS95","wsJ1nllw0KAJ")).
neg(eqo("conf/sigmod/KanthAS98","Z9VhfoCchlwJ")).
neg(eqo("conf/sigmod/KanthRA02","url:http://adsabs.harvard.edu/abs/2002STIN..276305O")).
neg(eqo("conf/sigmod/Keim99","rKIdcFtH4jUJ")).
neg(eqo("conf/sigmod/KementsietsidisAM03","kdePOIm2ZokJ")).
neg(eqo("conf/sigmod/KemperMPS94","EPtaqugcCyMJ")).
neg(eqo("conf/sigmod/KiepuszewskiMO98","zJCsqgMH5bUJ")).
neg(eqo("conf/sigmod/Kim94","5aSVaxWgGUMJ")).
neg(eqo("conf/sigmod/KornackerSH98","sqMoJhYYiCMJ")).
neg(eqo("conf/sigmod/KotidisR99","3aPleydkcIoJ")).
neg(eqo("conf/sigmod/KrishnanVI96","CTvc34ghAtkJ")).
neg(eqo("conf/sigmod/KrollW94","zd_8s13rNRoJ")).
neg(eqo("conf/sigmod/Kulkarni94","YPhNi0dzUvUJ")).
neg(eqo("conf/sigmod/LabrinidisR00","zlbJ-7JZdP0J")).
neg(eqo("conf/sigmod/LakshmananPZ03a","tcnjvKELfs0J")).
neg(eqo("conf/sigmod/Larson01","ZqFPwDkLN7oJ")).
neg(eqo("conf/sigmod/Larson01","nhKudG-HKt8J")).
neg(eqo("conf/sigmod/LeeWMS01","EhR3fz7f7vcJ")).
neg(eqo("conf/sigmod/LibkinMW96","jrHCcV5J998J")).
neg(eqo("conf/sigmod/LiefkeS00","N0eowMtIAukJ")).
neg(eqo("conf/sigmod/LiuHBPT99","uFVf0mEOih4J")).
neg(eqo("conf/sigmod/LiuPBHPT00","MmgmzLbsqI0J")).
neg(eqo("conf/sigmod/Lomet00","ZYHHgT8p5P8J")).
neg(eqo("conf/sigmod/Lomet00","url:http://ieeexplore.ieee.org/iel5/9217/29235/01320095.pdf%3Farnumber%3D1320095")).
neg(eqo("conf/sigmod/LometT99","rRvcD6HKhasJ")).
neg(eqo("conf/sigmod/LuMSS95","1sGr4qMsCeMJ")).
neg(eqo("conf/sigmod/MaddenSHR02","dLP8AfWQ7r0J")).
neg(eqo("conf/sigmod/Maguire01","VsHDmKLPFfEJ")).
neg(eqo("conf/sigmod/Mamoulis03","xAtFEIlf5RsJ")).
neg(eqo("conf/sigmod/Mamoulis03","z9MQwq7G3GYJ")).
neg(eqo("conf/sigmod/MarklL02","KKiefntReoUJ")).
neg(eqo("conf/sigmod/MattosM95","4ygpC0j5uugJ")).
neg(eqo("conf/sigmod/MeccaAMMS98","f5cqkpUXl0kJ")).
neg(eqo("conf/sigmod/Melling94","plBitL4sxucJ")).
neg(eqo("conf/sigmod/Mohan01","cAIvcFCeB6oJ")).
neg(eqo("conf/sigmod/Mohan94","6rkYIagTMckJ")).
neg(eqo("conf/sigmod/Nori00","_dw16ur5RZgJ")).
neg(eqo("conf/sigmod/Olson95","6VAQeD6muakJ")).
neg(eqo("conf/sigmod/OrdonezC00","yWkfJz_YMPkJ")).
neg(eqo("conf/sigmod/Ozsu99","Z6ep1mmb4A4J")).
neg(eqo("conf/sigmod/PadmanabhanBMCH03","W8eFyD3itoAJ")).
neg(eqo("conf/sigmod/PapadiasTFS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1024703%26type%3Dpdf")).
neg(eqo("conf/sigmod/PapakonstantinouPV02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Perna95","cjagTXtUZRcJ")).
neg(eqo("conf/sigmod/PonnekantiK00","c0D02SzWH9MJ")).
neg(eqo("conf/sigmod/PonnekantiK00","url:http://portal.acm.org/citation.cfm%3Fid%3D335191.335494%26dl%3DGUIDE%26dl%3DACM%26idx%3D335191%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Pruscino03","1F4AqnFvZxQJ")).
neg(eqo("conf/sigmod/Rajaraman99","bjtnGkW6L3kJ")).
neg(eqo("conf/sigmod/Rajaraman99","cnNLe97Pd2sJ")).
neg(eqo("conf/sigmod/Ramakrishnan00","6BxVtSMgjSkJ")).
neg(eqo("conf/sigmod/Ramanan02","nEwLN1SKensJ")).
neg(eqo("conf/sigmod/RiedewaldAA02","rg8576nvnkUJ")).
neg(eqo("conf/sigmod/RinfretOO01","pyqtmrPg24YJ")).
neg(eqo("conf/sigmod/Rosenthal01","ozA5VkHaGfQJ")).
neg(eqo("conf/sigmod/RothAHCCFSTW96","6SBwemr2zscJ")).
neg(eqo("conf/sigmod/RundensteinerKRCJM96","WrrEnOJswS4J")).
neg(eqo("conf/sigmod/Sahuguet01","url:http://www.springerlink.com/index/V077257007611033.pdf")).
neg(eqo("conf/sigmod/Sahuguet01","xb63RaGQYmYJ")).
neg(eqo("conf/sigmod/SeshadriLR94","zSO1Y5W7WkwJ")).
neg(eqo("conf/sigmod/ShouCTRH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959078%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SionAP03","Z5nBebaPAA8J")).
neg(eqo("conf/sigmod/SionAP03","rZe5ozhlslMJ")).
neg(eqo("conf/sigmod/SlivinskasJS01","f86VsMJZ9gAJ")).
neg(eqo("conf/sigmod/SrikantA96","Ve-JH2yNN0kJ")).
neg(eqo("conf/sigmod/Stonebraker98","WKPAnzKYw_8J")).
neg(eqo("conf/sigmod/SwamiS94","aBiqHXGXoJEJ")).
neg(eqo("conf/sigmod/SzalayGKT00","oknYUaMY28MJ")).
neg(eqo("conf/sigmod/Team95","eSPpim_OX4QJ")).
neg(eqo("conf/sigmod/Team95c","r5oJTEjlOPgJ")).
neg(eqo("conf/sigmod/TheobaldW02","QPpUo7m3A7cJ")).
neg(eqo("conf/sigmod/WaasG00","hVNv6KElmEMJ")).
neg(eqo("conf/sigmod/WangPFY03","enUg70kEpM8J")).
neg(eqo("conf/sigmod/Weininger02","yCQf5tQglE0J")).
neg(eqo("conf/sigmod/WynblattN01","CjHl-lb-eVsJ")).
neg(eqo("conf/sigmod/YuMWL01","VYz19hnZH_cJ")).
neg(eqo("conf/sigmod/YuMWL01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000002/art00017")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","CnAw9v-vEjwJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","Q2y53UR0g6oJ")).
neg(eqo("conf/sigmod/ZhouLP99","AVA1Zqx-ULUJ")).
neg(eqo("conf/sigmod/ZhouR02","a5djJMe9uAIJ")).
neg(eqo("conf/vldb/AbiteboulBMMW02","VMxzeJA08CoJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/AcharyaFZ96","FDPwbRQbfIAJ")).
neg(eqo("conf/vldb/AgrawalKSX02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/AgrawalLSS95","Y799jSppkKEJ")).
neg(eqo("conf/vldb/AgrawalPWZ95","aerbSILVnAwJ")).
neg(eqo("conf/vldb/AgrawalS94","Yt-cq_4cfE8J")).
neg(eqo("conf/vldb/AgrawalSX02","BzZbvP23pRQJ")).
neg(eqo("conf/vldb/AgrawalSX02","MtPcOYWFAcoJ")).
neg(eqo("conf/vldb/AltinelF00","6eheB6Kct4MJ")).
neg(eqo("conf/vldb/Amer-YahiaCD98","Zf8g79-uYNQJ")).
neg(eqo("conf/vldb/AmirKN01","oZnwIDQVeJ0J")).
neg(eqo("conf/vldb/Baru96","J0m81YEtjbgJ")).
neg(eqo("conf/vldb/Baru96","url:http://portal.acm.org/citation.cfm%3Fid%3D171926.172001")).
neg(eqo("conf/vldb/BaulierBKS98","-JBcR2Pwn7sJ")).
neg(eqo("conf/vldb/Bayer95","hZo7t0zFVFsJ")).
neg(eqo("conf/vldb/BelussiF95","a78Lxr80kJUJ")).
neg(eqo("conf/vldb/Bernstein94","WPwddc9X3C0J")).
neg(eqo("conf/vldb/BernsteinHJRW00","KlPsHutXQi8J")).
neg(eqo("conf/vldb/BernsteinHJRW00","Knzz_bkGA00J")).
neg(eqo("conf/vldb/BlottK02","_RyWKB28b6oJ")).
neg(eqo("conf/vldb/BonczRK98","NSf0FyKV_ZoJ")).
neg(eqo("conf/vldb/BridgeJKLLM97","fpI2ez86iIkJ")).
neg(eqo("conf/vldb/BrinkhoffK94","1_70kaMJsVAJ")).
neg(eqo("conf/vldb/Brodie00","MCDgDxsc8rcJ")).
neg(eqo("conf/vldb/Brodie03","d0DA9BbHi0kJ")).
neg(eqo("conf/vldb/Brodie03","jtWvNxTZ794J")).
neg(eqo("conf/vldb/BrownS95","eezVksY3W5YJ")).
neg(eqo("conf/vldb/CareyK98","LzJnQP5FoNAJ")).
neg(eqo("conf/vldb/CarneyCCCLSSTZ02","wnke8ff8hYUJ")).
neg(eqo("conf/vldb/CatozziR95","umrivnVIoj0J")).
neg(eqo("conf/vldb/ChakrabartiGRS00","_BsVmIUER44J")).
neg(eqo("conf/vldb/ChakrabartiM00","JDhUBcEpalAJ")).
neg(eqo("conf/vldb/ChaudhuriS96","xxkUtjfGpvAJ")).
neg(eqo("conf/vldb/ChenHWW02","RjUzaSW-JMsJ")).
neg(eqo("conf/vldb/CherniackZ98","SU9-zg4pdt8J")).
neg(eqo("conf/vldb/ChienTZ01","z9WrxlYfVl0J")).
neg(eqo("conf/vldb/Chiueh94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1101181%26type%3Dpdf")).
neg(eqo("conf/vldb/CochinwalaB94","W6T8UnS2cFUJ")).
neg(eqo("conf/vldb/CohenMKS03","6OfJSMB4vOcJ")).
neg(eqo("conf/vldb/CormodeKMS03","p0BhmCGCEM0J")).
neg(eqo("conf/vldb/DaynesC02","f2Lea-RN8dsJ")).
neg(eqo("conf/vldb/Deshpande00","mzbabulPonMJ")).
neg(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
neg(eqo("conf/vldb/Dyreson96","grj0oJlLSw8J")).
neg(eqo("conf/vldb/EicklerKK97","2W5e-Yd4BFYJ")).
neg(eqo("conf/vldb/EvangelidisLS95","-yDqW5e2MZwJ")).
neg(eqo("conf/vldb/FaloutsosG96","GGmfi7ywI4gJ")).
neg(eqo("conf/vldb/FaloutsosMS96","Asi-zTpzZysJ")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","bFNUZoN0LhsJ")).
neg(eqo("conf/vldb/FlorescuLSY99","aUElZKC-txIJ")).
neg(eqo("conf/vldb/GalhardasFSSS01","jn3pvb3hRzwJ")).
neg(eqo("conf/vldb/GallersdorferN95","PUaojR5kDikJ")).
neg(eqo("conf/vldb/GaoS03","YiJojduGXXkJ")).
neg(eqo("conf/vldb/GardarinGT95","kOSE6UVijD8J")).
neg(eqo("conf/vldb/GarofalakisG01","t_XrLlqtRckJ")).
neg(eqo("conf/vldb/GibsonKR98","4bvjebYsdRkJ")).
neg(eqo("conf/vldb/GoldsteinR00","uFVGy53KPTUJ")).
neg(eqo("conf/vldb/Graefe99","N5VKg7C4oiAJ")).
neg(eqo("conf/vldb/Graefe99","g_GL0oqW0_MJ")).
neg(eqo("conf/vldb/GravanoIJKMS01","do041BhhaX0J")).
neg(eqo("conf/vldb/GuPS00","mRWLGqueLNsJ")).
neg(eqo("conf/vldb/HageJPST03","ciNaUBiURnAJ")).
neg(eqo("conf/vldb/HageJPST03","url:http://doi.wiley.com/10.1002/ace.105")).
neg(eqo("conf/vldb/HanF95","CZGjStvTkZUJ")).
neg(eqo("conf/vldb/HellersteinNP95","4wHLoLkVcS8J")).
neg(eqo("conf/vldb/HelmerM97","vInYFLVq0uIJ")).
neg(eqo("conf/vldb/Hess96","5LE8kAZCShUJ")).
neg(eqo("conf/vldb/HoelS95","url:http://doi.wiley.com/10.1002/he.60")).
neg(eqo("conf/vldb/HulgeriS03","xGcM9AuhrBMJ")).
neg(eqo("conf/vldb/HumborstadSHT97","SEV-9px9auoJ")).
neg(eqo("conf/vldb/HuntAI01","bXRF6rASxhgJ")).
neg(eqo("conf/vldb/Huyn97","-Aw9zi3h104J")).
neg(eqo("conf/vldb/HvasshovdBT00","m7WdGieTDYoJ")).
neg(eqo("conf/vldb/IlyasAE02","2TdRPx4vN2cJ")).
neg(eqo("conf/vldb/IlyasAE02","o5V_jbeVe_IJ")).
neg(eqo("conf/vldb/IoannidisLGP96","kDWGwVa8dykJ")).
neg(eqo("conf/vldb/IshikawaSF98","D1HCBThHOkcJ")).
neg(eqo("conf/vldb/JagadishLRSS94","szG3swGuIocJ")).
neg(eqo("conf/vldb/JohnsonM98","XeK-exduCywJ")).
neg(eqo("conf/vldb/JohnsonS94","CQOvghgKDEkJ")).
neg(eqo("conf/vldb/KeidlSSK02","LZbKL6khHMcJ")).
neg(eqo("conf/vldb/KemmeA00","PAfEdPwJ8tgJ")).
neg(eqo("conf/vldb/King02","bpWvAVOZLbwJ")).
neg(eqo("conf/vldb/King02","omJMHXass6gJ")).
neg(eqo("conf/vldb/Koch03","rhxIrsQkm5AJ")).
neg(eqo("conf/vldb/KonopnickiS95","E8ICGS9Be2QJ")).
neg(eqo("conf/vldb/KornSFSP96","AhnsJnjlnV4J")).
neg(eqo("conf/vldb/Korth95","5iohkq8tSIwJ")).
neg(eqo("conf/vldb/Korth95","jJb2G9hkNNQJ")).
neg(eqo("conf/vldb/LakshmananNWZJ02","C_8ItDQfrRwJ")).
neg(eqo("conf/vldb/LakshmananPH02","s5rDZ6KYPXEJ")).
neg(eqo("conf/vldb/LakshmananPH02","w_FOwUavk0kJ")).
neg(eqo("conf/vldb/LaneEN00","j3tw1KQn79MJ")).
neg(eqo("conf/vldb/Lesk94","nL5wl20jB-kJ")).
neg(eqo("conf/vldb/Leymann01","U9al_oQxpxYJ")).
neg(eqo("conf/vldb/LimWPVP02","lIzeOJ5cqeMJ")).
neg(eqo("conf/vldb/LinLYZ03","WA52h-tCVkMJ")).
neg(eqo("conf/vldb/LingLL00","YjusI8i6iRwJ")).
neg(eqo("conf/vldb/LingLL00","sRcMuuo3-BEJ")).
neg(eqo("conf/vldb/LuL00","F5vRA2qownQJ")).
neg(eqo("conf/vldb/LubbersGJ03","T3nGiiT3tbsJ")).
neg(eqo("conf/vldb/MadhavanH03","5ZAWJCffWgEJ")).
neg(eqo("conf/vldb/MarronL01","HsAQIEugJ8YJ")).
neg(eqo("conf/vldb/MatiasVW00","9aQ-4aCzmAQJ")).
neg(eqo("conf/vldb/May01","8FlPUUe8DwMJ")).
neg(eqo("conf/vldb/MeccaCM01","eynVF0FSPjkJ")).
neg(eqo("conf/vldb/MengLLA03","MNuT46WJZaQJ")).
neg(eqo("conf/vldb/MignetMAC01","KkI-NuyDkDQJ")).
neg(eqo("conf/vldb/NatsevCSLV01","56fEnbhIekAJ")).
neg(eqo("conf/vldb/NaumannLF99","qv9JuA63NQMJ")).
neg(eqo("conf/vldb/NetzCBF00","3OTNpeTJ1vEJ")).
neg(eqo("conf/vldb/NetzCBF00","a18d_UObWvwJ")).
neg(eqo("conf/vldb/NgH94","_kyazmYDM6oJ")).
neg(eqo("conf/vldb/Nori02","RAcoVQuEzD8J")).
neg(eqo("conf/vldb/Norvag99","KB9ZbekVNzoJ")).
neg(eqo("conf/vldb/Novaretti01","cy_Fe935WMAJ")).
neg(eqo("conf/vldb/OrensteinK95","Trw6DEZeqTsJ")).
neg(eqo("conf/vldb/OzsuLON01","6ituoubvieMJ")).
neg(eqo("conf/vldb/Padmanabhan96","6kiYvzSHBvEJ")).
neg(eqo("conf/vldb/Padmanabhan96","qqwCU74AGhIJ")).
neg(eqo("conf/vldb/PantiSG00","1n7AY641YyAJ")).
neg(eqo("conf/vldb/PapadiasZMT03","hJ8VP7FyOL0J")).
neg(eqo("conf/vldb/PapadiasZMT03","n63MkRrhLIUJ")).
neg(eqo("conf/vldb/PapakonstantinouAG96","vzumHh_MFGAJ")).
neg(eqo("conf/vldb/PappasC00","8CKDKUPVOnwJ")).
neg(eqo("conf/vldb/PedersenJD00","pPJsIkioV9wJ")).
neg(eqo("conf/vldb/PereiraFJLS01","teLJrEN-7j4J")).
neg(eqo("conf/vldb/RamamrithamABEGP00","jYGXFESkS-YJ")).
neg(eqo("conf/vldb/RamamurthyDS02","egCgEjikCgAJ")).
neg(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
neg(eqo("conf/vldb/RothS97","8vJEjrhM7foJ")).
neg(eqo("conf/vldb/RothS97","CG1iYAb8orsJ")).
neg(eqo("conf/vldb/Sacks-Davis96","2Yy0kQZvT0EJ")).
neg(eqo("conf/vldb/Sacks-Davis96","8EInhbOVFgMJ")).
neg(eqo("conf/vldb/Sacks-Davis96","lDTPyBMtHVwJ")).
neg(eqo("conf/vldb/SakuraiYKU01","7SLjR-09mFkJ")).
neg(eqo("conf/vldb/SakuraiYUK00","GPEkH-UohLYJ")).
neg(eqo("conf/vldb/Sarawagi00","wkgGoKqPVzQJ")).
neg(eqo("conf/vldb/Sarawagi95","C8lF7grRFcMJ")).
neg(eqo("conf/vldb/Sarawagi95","wkgGoKqPVzQJ")).
neg(eqo("conf/vldb/SarawagiBKM02","5qP0DOqO6VwJ")).
neg(eqo("conf/vldb/SattlerGS03","7y1DNkciIFQJ")).
neg(eqo("conf/vldb/SavasereON95","XG4Y1UB1rhAJ")).
neg(eqo("conf/vldb/SavasereON95","XZgDbb1XypMJ")).
neg(eqo("conf/vldb/ScheuermannSV96","vBYtmDEYeK0J")).
neg(eqo("conf/vldb/SellisRF97","RO5oBaYCifMJ")).
neg(eqo("conf/vldb/SellisRF97","lx0csm6_FdgJ")).
neg(eqo("conf/vldb/SetzerZ94","RmyORCW6qn8J")).
neg(eqo("conf/vldb/SetzerZ94","krAZ7iDMEOQJ")).
neg(eqo("conf/vldb/ShaferAM96","5HHRNLsy0sAJ")).
neg(eqo("conf/vldb/ShaferAM96","TlgwZUNfJaAJ")).
neg(eqo("conf/vldb/ShaferAM96","oVWSNBlWR84J")).
neg(eqo("conf/vldb/ShanmugasundaramSBCLPR00","RkjggE7xhN0J")).
neg(eqo("conf/vldb/ShengBDM02","6GxdJ4jZUokJ")).
neg(eqo("conf/vldb/Sheth96","nlNwMrr7SPIJ")).
neg(eqo("conf/vldb/SimonD95","lHa19HQLLv8J")).
neg(eqo("conf/vldb/SrikantA95","WSVs3nCRe8EJ")).
neg(eqo("conf/vldb/SrivastavaDJL96","-gQb5oEVQgYJ")).
neg(eqo("conf/vldb/StaudtJ96","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/StillgerLMK01","NeQFdN-6LVEJ")).
neg(eqo("conf/vldb/Suciu96a","Ikk1rb4o66UJ")).
neg(eqo("conf/vldb/Suciu96a","Z9e9dqy5KBgJ")).
neg(eqo("conf/vldb/Toivonen96","5jNwzR2cnnYJ")).
neg(eqo("conf/vldb/TriantafillouP97","wPm8dQxiK5UJ")).
neg(eqo("conf/vldb/TsatalosSI94","RjNjSB-PwJ0J")).
neg(eqo("conf/vldb/Tsur00","-UhETNxnIuMJ")).
neg(eqo("conf/vldb/VermeerA96","0kqFsLkdI1MJ")).
neg(eqo("conf/vldb/Wadler01","Isbc9SlTYT8J")).
neg(eqo("conf/vldb/Wang95","yIVBmSacODIJ")).
neg(eqo("conf/vldb/WangC03","B1uNI67mfJcJ")).
neg(eqo("conf/vldb/WeberSB98","pPJsIkioV9wJ")).
neg(eqo("conf/vldb/WienerN95","Y1lEnVPl6d8J")).
neg(eqo("conf/vldb/WiesnerK01","tvi_iYz-A8oJ")).
neg(eqo("conf/vldb/X00a","rIn20xqxpkUJ")).
neg(eqo("conf/vldb/YiF00","CiGKfXghikcJ")).
neg(eqo("conf/vldb/ZhouR03","B3ZbcgdtgP0J")).
neg(eqo("conf/vldb/ZhouS03","url:http://www.springerlink.com/index/MV301H2472338044.pdf")).
neg(eqo("conf/vldb/ZouS98","7uHaZzL1yXIJ")).
neg(eqo("journals/sigmod/Aberer01","fnt5G2r4MaYJ")).
neg(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637423%26dl%3Dportal%26dl%3DACM%26type%3Dissue%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604274%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03c","M3ELKAZ4wBMJ")).
neg(eqo("journals/sigmod/Aberer03d","piVAR0_E0IEJ")).
neg(eqo("journals/sigmod/Abiteboul99","13NBtnaNfIEJ")).
neg(eqo("journals/sigmod/Ahlberg96","r-a0B7-qYnEJ")).
neg(eqo("journals/sigmod/Alonso94a","bA8eKd7mQVgJ")).
neg(eqo("journals/sigmod/ArenasKKKMM03","SYZdbPLsPWAJ")).
neg(eqo("journals/sigmod/ArenasKKKMM03","lC5GjK5OpD0J")).
neg(eqo("journals/sigmod/AshishK97","UTYa5uf9zSIJ")).
neg(eqo("journals/sigmod/AtzeniMM97","mA4kKq9Z3tYJ")).
neg(eqo("journals/sigmod/BabuW01","1FiD8j3CibgJ")).
neg(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","oMn0NXWTlNUJ")).
neg(eqo("journals/sigmod/BerzalM02","-iis302p2MkJ")).
neg(eqo("journals/sigmod/Bestavros96","Q2y53UR0g6oJ")).
neg(eqo("journals/sigmod/Bohlen95","ZraSxoh9ZZoJ")).
neg(eqo("journals/sigmod/BohmR94","mFVZqqx2yfMJ")).
neg(eqo("journals/sigmod/BollKB98","k7Nb3hZIot8J")).
neg(eqo("journals/sigmod/BollKB98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271095%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BonnetBDL03","gpjVvUtM6H8J")).
neg(eqo("journals/sigmod/Bussler02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083797%26type%3Dpdf")).
neg(eqo("journals/sigmod/CasatiDS00","dLZH3Tao7xUJ")).
neg(eqo("journals/sigmod/CeriFP99","0aJOXauNqYIJ")).
neg(eqo("journals/sigmod/CeriFP99","zCbDZVfxWhAJ")).
neg(eqo("journals/sigmod/CfP99","1RggnOMvJUkJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","lkreWUl_euYJ")).
neg(eqo("journals/sigmod/Chen94","R4W8iS5PAZIJ")).
neg(eqo("journals/sigmod/Chen94","fDBG9BpfX9QJ")).
neg(eqo("journals/sigmod/ChengP03","3IFlpeKgLlAJ")).
neg(eqo("journals/sigmod/CherniakV03","uPBlQ76s_g4J")).
neg(eqo("journals/sigmod/ChienTZ01","eWCz_YJFqjcJ")).
neg(eqo("journals/sigmod/ClementLGMK97","U-98tPsJi6EJ")).
neg(eqo("journals/sigmod/CruzKLSWY02","19ridA84Q4gJ")).
neg(eqo("journals/sigmod/CuiJO02","2APmJ-GQBbwJ")).
neg(eqo("journals/sigmod/CuiJO02","O6js44BVQOwJ")).
neg(eqo("journals/sigmod/DarwenD95","-iis302p2MkJ")).
neg(eqo("journals/sigmod/Date03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Dogac02","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/13891286/2000/00000034/00000006/art00152%26unc%3D")).
neg(eqo("journals/sigmod/Dogac96","hYFEbFhIQdEJ")).
neg(eqo("journals/sigmod/DogacDKOONEHAKKM95","xPQe2xQdsCwJ")).
neg(eqo("journals/sigmod/Domingo-FerrerH98","ndB8lePl0VEJ")).
neg(eqo("journals/sigmod/Eisenberg96","enYoi4XT7n0J")).
neg(eqo("journals/sigmod/EisenbergM01","6uelfg3RgEoJ")).
neg(eqo("journals/sigmod/EisenbergM98a","GKUflKzgAVEJ")).
neg(eqo("journals/sigmod/FernandezFLS97","LJKpMU1tIlcJ")).
neg(eqo("journals/sigmod/FlorescuLM98","_SR_pRTnA6IJ")).
neg(eqo("journals/sigmod/Fong97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D223859%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/FowlerPNB99","IgAEpc8ulvYJ")).
neg(eqo("journals/sigmod/Franklin00a","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Franklin00a","url:http://doi.wiley.com/10.1002/ev.1000")).
neg(eqo("journals/sigmod/Franklin97b","fNVk1Vq2txEJ")).
neg(eqo("journals/sigmod/Franklin98","1Cce-J3lgFkJ")).
neg(eqo("journals/sigmod/Franklin98","bZj9gl0_YUIJ")).
neg(eqo("journals/sigmod/Franklin98","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Franklin98","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin99","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin99a","xgdBJbatYcIJ")).
neg(eqo("journals/sigmod/Franklin99b","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/GamacheS95","CToHZL-xBSMJ")).
neg(eqo("journals/sigmod/GeppertD94","ckAgGjJN5xAJ")).
neg(eqo("journals/sigmod/GobleR02a","PBtu7Xy2Z_cJ")).
neg(eqo("journals/sigmod/Hammer02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D584455%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Hampapur99","wI75uFSs0bwJ")).
neg(eqo("journals/sigmod/Han98","52F3k8X3Z8gJ")).
neg(eqo("journals/sigmod/Han98","uEbdEtnaCXMJ")).
neg(eqo("journals/sigmod/HanBP01","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294143CI")).
neg(eqo("journals/sigmod/Hanson99","44R_vYrStiQJ")).
neg(eqo("journals/sigmod/HasanMV96","bLbjFFkQJdIJ")).
neg(eqo("journals/sigmod/Ioannidis96","MmgmzLbsqI0J")).
neg(eqo("journals/sigmod/Jannink95","ESZwkhGzOboJ")).
neg(eqo("journals/sigmod/KannanKIK03","23qa1GAuB3AJ")).
neg(eqo("journals/sigmod/KantM00","1m9BmEzgbBYJ")).
neg(eqo("journals/sigmod/KaradimitriouT97","SrCBkHnIFL8J")).
neg(eqo("journals/sigmod/Keim96","uypnc5Gb9iIJ")).
neg(eqo("journals/sigmod/KempsterST99","qtB6bRLBYTQJ")).
neg(eqo("journals/sigmod/KuanL99","oQwbs_kHvysJ")).
neg(eqo("journals/sigmod/Kumar03","NzhcJdwmwJMJ")).
neg(eqo("journals/sigmod/KuokFW98","21ZWY0PM8YAJ")).
neg(eqo("journals/sigmod/KuokFW98","GzJII5F7OzAJ")).
neg(eqo("journals/sigmod/LabrinidisR00","rKbwxobcJZYJ")).
neg(eqo("journals/sigmod/LeeC00","uLM2hSJfovQJ")).
neg(eqo("journals/sigmod/LeveneP02","umqiMNB4904J")).
neg(eqo("journals/sigmod/LeveneP02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031591%26type%3Dpdf")).
neg(eqo("journals/sigmod/Libkin99a","xeceK06Z5DIJ")).
neg(eqo("journals/sigmod/Liu01","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Liu02","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu02","mpvuUKYJxOoJ")).
neg(eqo("journals/sigmod/Liu02c","zc1TRuoDDwgJ")).
neg(eqo("journals/sigmod/Liu03c","0W2XcpqyLIAJ")).
neg(eqo("journals/sigmod/Liu03c","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/LudwigG00","KF6x15l8ZHQJ")).
neg(eqo("journals/sigmod/LuoI02","NgZRvq9MRbEJ")).
neg(eqo("journals/sigmod/Manola98","oRp455a_YpsJ")).
neg(eqo("journals/sigmod/MaximilienS02","dbRvyt7SJA0J")).
neg(eqo("journals/sigmod/NgH95","aUrn2M0LjSYJ")).
neg(eqo("journals/sigmod/OrlandicLS02","ZrOcCXxAdP0J")).
neg(eqo("journals/sigmod/Palpanas00","2kiNfwTpqp4J")).
neg(eqo("journals/sigmod/PalpanasPKG03","gqehj3-ukjIJ")).
neg(eqo("journals/sigmod/PhatakSSS96","url:http://portal.acm.org/citation.cfm%3Fid%3D984505.984507%26dl%3DACM%26dl%3DACM%26idx%3D984505%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PitouraAPSV03","hn2MANNgz9sJ")).
neg(eqo("journals/sigmod/Qian95a","4Y125m3-bsYJ")).
neg(eqo("journals/sigmod/Qian95a","HxQoc9PkFOMJ")).
neg(eqo("journals/sigmod/RamDD99","0zAnlO8DT98J")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","et7qrerDPrYJ")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","oIa0XUaETVMJ")).
neg(eqo("journals/sigmod/RiekertMW97","ExOv1ThwJiYJ")).
neg(eqo("journals/sigmod/RosenthalS99","JYHcz-HpKjEJ")).
neg(eqo("journals/sigmod/Rosneblatt94","FABnS2qYAZYJ")).
neg(eqo("journals/sigmod/Rosneblatt94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130318%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossAA02","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/RossCGJBV99","O4bjxqnHGSIJ")).
neg(eqo("journals/sigmod/RossIJP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Roussopoulos98","DqFexxIXVz4J")).
neg(eqo("journals/sigmod/Roussopoulos98","IM6tKYvzWAcJ")).
neg(eqo("journals/sigmod/Segev94a","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Segev94a","url:http://doi.wiley.com/10.1002/ace.53")).
neg(eqo("journals/sigmod/Segev94b","zc1TRuoDDwgJ")).
neg(eqo("journals/sigmod/ShethMKA01","aAquT4Ws6fcJ")).
neg(eqo("journals/sigmod/ShinM94","hnpTcGMYR80J")).
neg(eqo("journals/sigmod/Snodgrass01a","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/Snodgrass02a","gYWmOPwa7mwJ")).
neg(eqo("journals/sigmod/Snodgrass03a","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084832")).
neg(eqo("journals/sigmod/Snodgrass03c","Q1SaDAfpg38J")).
neg(eqo("journals/sigmod/Snodgrass03c","c-5n9qQKLaEJ")).
neg(eqo("journals/sigmod/Snodgrass94","VwZQmafqkE0J")).
neg(eqo("journals/sigmod/Snodgrass98b","Tp6vV_Q_xVEJ")).
neg(eqo("journals/sigmod/SouzaS99","2OkIz_x8O_EJ")).
neg(eqo("journals/sigmod/Stonebraker94","LNogBuKPOaQJ")).
neg(eqo("journals/sigmod/Suciu01","1sGr4qMsCeMJ")).
neg(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
neg(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
neg(eqo("journals/sigmod/Suciu02","9CKU75VaJlQJ")).
neg(eqo("journals/sigmod/SureSS02","v0tY6g0DHMcJ")).
neg(eqo("journals/sigmod/TheodoridisN00","ppGZ8x9cUcMJ")).
neg(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
neg(eqo("journals/sigmod/VelACM01","LseDURw3BXMJ")).
neg(eqo("journals/sigmod/Widom94","hqDtMiCwjGoJ")).
neg(eqo("journals/sigmod/Widom94","zWrQD-2VvWgJ")).
neg(eqo("journals/sigmod/Widom96","ciB46ylPwJ8J")).
neg(eqo("journals/sigmod/Widom96","lAbG3uFZvVUJ")).
neg(eqo("journals/sigmod/Widom96b","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Widom96b","dTORuW_9YRoJ")).
neg(eqo("journals/sigmod/Widom96b","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Wiegand02","RAcoVQuEzD8J")).
neg(eqo("journals/sigmod/Wiegand03","IXO8f3i-f3QJ")).
neg(eqo("journals/sigmod/Winslett03c","hQt4gv-PZfMJ")).
neg(eqo("journals/sigmod/Wu02","srdYIauWgK0J")).
neg(eqo("journals/sigmod/X95","ilCT5UFnHxgJ")).
neg(eqo("journals/sigmod/ZobelMR96","tdDLf6RffisJ")).
neg(eqo("journals/tods/BertinoBFS98","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D1318565")).
neg(eqo("journals/tods/CaldersNW02","epaREw6k28MJ")).
neg(eqo("journals/tods/Chen95a","7wpWE6a7ljUJ")).
neg(eqo("journals/tods/Chen95a","OqyZE7MuP6sJ")).
neg(eqo("journals/tods/Chomicki95","cCWmetAkfQwJ")).
neg(eqo("journals/tods/DeyS96","gkUt2UgB_pUJ")).
neg(eqo("journals/tods/FegarasM00","NlMndaTvroEJ")).
neg(eqo("journals/tods/GibbonsMP02","qXiPPUqVwHwJ")).
neg(eqo("journals/tods/GoldmanL94","56mvyCaTq3QJ")).
neg(eqo("journals/tods/HjaltasonS99","slxJA5rAVaMJ")).
neg(eqo("journals/tods/HjaltasonS99","zA5IBcNU_dYJ")).
neg(eqo("journals/tods/Jimenez-PerisPAK03","isbLxdyMst8J")).
neg(eqo("journals/tods/KarpSP03","mAQIVsd2VOMJ")).
neg(eqo("journals/tods/KemmeA00","wiUPadLpCvoJ")).
neg(eqo("journals/tods/Kim94","LoL0Yu6h4VAJ")).
neg(eqo("journals/tods/Kuo96","7l3gzxMIiFEJ")).
neg(eqo("journals/tods/LitwinN96","99nKpf7A4uIJ")).
neg(eqo("journals/tods/MayL02","MobmihLvrkEJ")).
neg(eqo("journals/tods/MehrotraRKS98","qOgXuRc7f4QJ")).
neg(eqo("journals/tods/RaschidL96","IbLCMHG2GVgJ")).
neg(eqo("journals/tods/Revesz98","KMiFsjvmlxwJ")).
neg(eqo("journals/tods/Revesz98","vk55UFDkIwQJ")).
neg(eqo("journals/tods/SalemGS94","9pzp7hDFL1kJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/LD48KCXJWTCRACDL.pdf")).
neg(eqo("journals/tods/Snodgrass01a","8vtUokULDisJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/0JGDE6A9JHWT3CF5.pdf")).
neg(eqo("journals/tods/ZobelMR98","6NbNX8nSta0J")).
neg(eqo("journals/vldb/AbbadiSW01","url:http://portal.acm.org/citation.cfm%3Fid%3D945721.945727%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/AguileraCMVV02","wN-4Rn5hFnwJ")).
neg(eqo("journals/vldb/Atkinson00","UF-RyjST87cJ")).
neg(eqo("journals/vldb/Atkinson00","yKnPPSNrDb0J")).
neg(eqo("journals/vldb/Barbara-MillaG94","bfdZNz7ylx8J")).
neg(eqo("journals/vldb/Barbara-MillaG94","l4DnnmJEd24J")).
neg(eqo("journals/vldb/ChakrabartiDAR98","AyDb4G2EiGwJ")).
neg(eqo("journals/vldb/ChenHY97","JcHiZlbsts0J")).
neg(eqo("journals/vldb/ChienTZ02","RovnC1D7mTsJ")).
neg(eqo("journals/vldb/ChienTZ02","lmLjPf_m6jwJ")).
neg(eqo("journals/vldb/DesslochHMMT98","QSAjeHyUP0QJ")).
neg(eqo("journals/vldb/Guting94","2d-pftfMGhoJ")).
neg(eqo("journals/vldb/Halevy02","5NE7g6XtYVkJ")).
neg(eqo("journals/vldb/Halevy02","CYJR7X2NtGMJ")).
neg(eqo("journals/vldb/Han98","CKScFHA8hPkJ")).
neg(eqo("journals/vldb/Han98","uEbdEtnaCXMJ")).
neg(eqo("journals/vldb/HansonCDERTX98","cuQ1EnNR_1EJ")).
neg(eqo("journals/vldb/HarderR96","pWXIPx5lA7gJ")).
neg(eqo("journals/vldb/HjaltasonS02","3mwWUz_ORNYJ")).
neg(eqo("journals/vldb/IoannidisNSS97","ofRNwQLX6XQJ")).
neg(eqo("journals/vldb/JagadishACLNPPSWWY02","zaDlTkyGASQJ")).
neg(eqo("journals/vldb/KashyapS96","NTlGMs3lqNEJ")).
neg(eqo("journals/vldb/LometS97","c-VaonA7Z7EJ")).
neg(eqo("journals/vldb/ManegoldBK00","FRa5WkvIgwQJ")).
neg(eqo("journals/vldb/MaratheS02","7Ns7fve9P0AJ")).
neg(eqo("journals/vldb/MehrotraKS97","vGxIrjbMVH4J")).
neg(eqo("journals/vldb/Navarro02","hMsWZU5TJWYJ")).
neg(eqo("journals/vldb/NgS98","en4pt0I9R_EJ")).
neg(eqo("journals/vldb/NgS98","i2ZgXBF_cGcJ")).
neg(eqo("journals/vldb/OzsuPSILM95","9MI4jOOqkn4J")).
neg(eqo("journals/vldb/PeckhamMD95","HCQSN0M-6mcJ")).
neg(eqo("journals/vldb/RafieiM02","kZFfJieudW4J")).
neg(eqo("journals/vldb/Sarawagi01","0KLcrS1Co_kJ")).
neg(eqo("journals/vldb/Sarawagi01","z5DmAoBjsjAJ")).
neg(eqo("journals/vldb/ScheuermannWZ98","kxebBNLKWl4J")).
neg(eqo("journals/vldb/Sciore94","8JNGARIepUYJ")).
neg(eqo("journals/vldb/Sciore94","xsh0C_nCllsJ")).
neg(eqo("journals/vldb/ShegalovGW01","TcvA-v-99rsJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","dFK3q-SkTC4J")).
pos(eqo("conf/sigmod/AbadiCCCCEGHMRSSTXYZ03","gBVNSFeS4P8J")).
pos(eqo("conf/sigmod/AbiteboulCM95","DakOA4Ew-poJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","2fO9nM2FoGYJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","h2z51QPXcSkJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","9OEjtHuRUzsJ")).
pos(eqo("conf/sigmod/AcharyaGP00","WGWZ2cNZW2YJ")).
pos(eqo("conf/sigmod/AcharyaPR99","0dY1brFaEzgJ")).
pos(eqo("conf/sigmod/AcharyaPR99","KrVgTXcNPPUJ")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/AdelbergGK95","NbLabaGWoh4J")).
pos(eqo("conf/sigmod/AdyaGLM95","EP8u32KwMe4J")).
pos(eqo("conf/sigmod/AdyaGLM95","FlE1JdgElGQJ")).
pos(eqo("conf/sigmod/Agarwal96","ALk7huiKjWAJ")).
pos(eqo("conf/sigmod/Agarwal96","Ca-BABwlsQAJ")).
pos(eqo("conf/sigmod/Agarwal96","Fd0jPlSwFWcJ")).
pos(eqo("conf/sigmod/AggarwalY00","dfSPs7YoyWsJ")).
pos(eqo("conf/sigmod/AggarwalY00","x5jeMyauzWgJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","rSTewQ1dQkYJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x8fDHaNkSUIJ")).
pos(eqo("conf/sigmod/AgrawalS00","ufPUBsN4eg0J")).
pos(eqo("conf/sigmod/AshleyFHLNP95","tL67lYBCRO4J")).
pos(eqo("conf/sigmod/Atkinson95","url:http://portal.acm.org/citation.cfm%3Fid%3D223874")).
pos(eqo("conf/sigmod/BabuGR01","zQCRmiH6jo4J")).
pos(eqo("conf/sigmod/BarbaraI94","XfvqAOX1qo4J")).
pos(eqo("conf/sigmod/BaruGLMPVC99","arQIThq-W4gJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wsNuAYMG0QEJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","-CQaLTpGJLQJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","w9IzqrZAa74J")).
pos(eqo("conf/sigmod/BilirisFOP96","VakyeJZNPM0J")).
pos(eqo("conf/sigmod/BilirisP94","KYhmilHkq_IJ")).
pos(eqo("conf/sigmod/BohmA96","978pJCGhaGoJ")).
pos(eqo("conf/sigmod/BreunigKNS00","KILdAgEb2OsJ")).
pos(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/BumbulisB02","Ev27auQiecUJ")).
pos(eqo("conf/sigmod/BunemanDHS96","R128Of6zyGgJ")).
pos(eqo("conf/sigmod/Carey94","Lj8CI8ALd9UJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/CatarciS94","ga4l4QhCXU4J")).
pos(eqo("conf/sigmod/Cattell94","QgR0DgMbdgIJ")).
pos(eqo("conf/sigmod/CeriFP98","iUGa3pKj-20J")).
pos(eqo("conf/sigmod/ChangG99","vjxJ_rBwdMkJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","4zZ7Lxt4PPIJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","gY652XXjHB8J")).
pos(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
pos(eqo("conf/sigmod/ChaudhuriGN02","KrfR8djb3C8J")).
pos(eqo("conf/sigmod/ChaudhuriGN02","y461yNb2GEcJ")).
pos(eqo("conf/sigmod/ChenJDTW00","KlxPr0YoE_sJ")).
pos(eqo("conf/sigmod/ChenJDTW00","OsfWKJek9L8J")).
pos(eqo("conf/sigmod/ChenZCKR01","RHoy5iOHsJwJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","tGBhWHHU7hsJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","0FohHTWs5toJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","fDiU6std8e0J")).
pos(eqo("conf/sigmod/ColeG94","_6wwPJEGUiAJ")).
pos(eqo("conf/sigmod/ColeG94","qpYRj0BgQz4J")).
pos(eqo("conf/sigmod/ColeG94","z_W8jZ203sUJ")).
pos(eqo("conf/sigmod/Cotton02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564792%26type%3Dpdf")).
pos(eqo("conf/sigmod/DeshpandeNGS03","aBiqHXGXoJEJ")).
pos(eqo("conf/sigmod/DeutschFS99","2lypQEgzfb8J")).
pos(eqo("conf/sigmod/DeutschFS99","De_3PkxkhzIJ")).
pos(eqo("conf/sigmod/DeutschFS99","QxtGOVsCF78J")).
pos(eqo("conf/sigmod/DeutschFS99","SYaXErlVlcAJ")).
pos(eqo("conf/sigmod/DeutschFS99","kDYpG4mLjLkJ")).
pos(eqo("conf/sigmod/DeutschFS99","twQNwr-jFmoJ")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/DogacTPPLKTK02","VAOk1X8Ja30J")).
pos(eqo("conf/sigmod/DogacTPPLKTK02","juQlvnYuPxwJ")).
pos(eqo("conf/sigmod/DogacTPPLKTK02","wi8177RdPBYJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","Sqy1tqGEnxsJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","qsWDIfzBxiQJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","4BpkEHas0LcJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","ek26aiEheesJ")).
pos(eqo("conf/sigmod/FernandezS96","9bgA6C_HqvQJ")).
pos(eqo("conf/sigmod/FranklinZ98","K_qOxjIJWpQJ")).
pos(eqo("conf/sigmod/FreireHRRS02","YKkMxZntSUQJ")).
pos(eqo("conf/sigmod/Galhardas00","QhUFQCApL8wJ")).
pos(eqo("conf/sigmod/Galindo-Legaria94","iEs59H5EFHwJ")).
pos(eqo("conf/sigmod/GangulyGMS96","zeikJQZ2KM4J")).
pos(eqo("conf/sigmod/GebhardtJJ97","9mbr0dyW1NgJ")).
pos(eqo("conf/sigmod/GebhardtJJ97","ks4Wxa8dHNIJ")).
pos(eqo("conf/sigmod/GetoorTK01","bvdJYU3xG_YJ")).
pos(eqo("conf/sigmod/GibbonsM98","4EgMtIywBRUJ")).
pos(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
pos(eqo("conf/sigmod/GravanoGT94","81oh7EDAYeoJ")).
pos(eqo("conf/sigmod/GravanoGT94","VxiP2MuiMM0J")).
pos(eqo("conf/sigmod/GravanoGT94","We2mw93oKL4J")).
pos(eqo("conf/sigmod/GravanoGT94","nAJnhh70_0kJ")).
pos(eqo("conf/sigmod/GravanoGT94","z26H2tQo7bkJ")).
pos(eqo("conf/sigmod/GrayHOS96","OLt5pqtQf3YJ")).
pos(eqo("conf/sigmod/GrayHOS96","_pjwP11t_y8J")).
pos(eqo("conf/sigmod/GraySEBW94","SG9kpHg_arUJ")).
pos(eqo("conf/sigmod/GuoSBS03","p_PDgjVRUS4J")).
pos(eqo("conf/sigmod/GuptaMR95","7ggq-jY7UEYJ")).
pos(eqo("conf/sigmod/GuptaMR95","InJyYTfzN50J")).
pos(eqo("conf/sigmod/HaasH01","tHEP1S1typgJ")).
pos(eqo("conf/sigmod/HanKK97","-X-ZldO8A7kJ")).
pos(eqo("conf/sigmod/HanKK97","NIfccqToMb8J")).
pos(eqo("conf/sigmod/HanKS97","nD_Yjp9TNuIJ")).
pos(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
pos(eqo("conf/sigmod/HanPDW01","XyYCahzDAh8J")).
pos(eqo("conf/sigmod/HanPY00","2xwKDuA0DI8J")).
pos(eqo("conf/sigmod/HanPY00","GlNt7w28aE8J")).
pos(eqo("conf/sigmod/HanPY00","R-ERjYdCskcJ")).
pos(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
pos(eqo("conf/sigmod/HanPY00","aUm_NiRzVOIJ")).
pos(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
pos(eqo("conf/sigmod/HanWDPW02","nwWpGh3Mx7MJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","8A_9ucHRXyIJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Fyek_kCB-qkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Qv7KYn9x-SQJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","ofxLw3VrJB8J")).
pos(eqo("conf/sigmod/HarinarayanRU96","uKGmcc4xUG4J")).
pos(eqo("conf/sigmod/Hellerstein94","Nn0LzB8rUPEJ")).
pos(eqo("conf/sigmod/Hellerstein94","r4adn1YKOFIJ")).
pos(eqo("conf/sigmod/HellersteinN96","5vvOcgfpjUgJ")).
pos(eqo("conf/sigmod/HellersteinN96","_hDCldPyum0J")).
pos(eqo("conf/sigmod/HernandezS95","IHy3bqAuSOUJ")).
pos(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
pos(eqo("conf/sigmod/HuangSW94","5Chw6HN64vEJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","8EC1IBh8MZkJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","9KBHBWVwKZsJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","AhacU8AzwSUJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","MdMdCC38z4UJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","V-LO20klzSYJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","VdUSfNE_8i8J")).
pos(eqo("conf/sigmod/IoannidisL94","dDHNsS9sisEJ")).
pos(eqo("conf/sigmod/IvesLPST00","4-FwpSOweRAJ")).
pos(eqo("conf/sigmod/JohnsonD03","5OYgUpRggiMJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","jCudeTapg5IJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","vO7aBWspoyMJ")).
pos(eqo("conf/sigmod/KimC03","BWV2Oys1VXsJ")).
pos(eqo("conf/sigmod/Kleissner95","DB8lVC2D9fcJ")).
pos(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
pos(eqo("conf/sigmod/LazaridisM01","IvMJ4bK708kJ")).
pos(eqo("conf/sigmod/LeeWMS01","6NI_YrVysEMJ")).
pos(eqo("conf/sigmod/LeeWMS01","OFXL5KsJiWcJ")).
pos(eqo("conf/sigmod/LiCHH97","vjqDlXKHfzoJ")).
pos(eqo("conf/sigmod/LibkinMW96","OfZWx8jhQvwJ")).
pos(eqo("conf/sigmod/LibkinMW96","uxD8p47apUYJ")).
pos(eqo("conf/sigmod/LiefkeS00","GFCznyVaj5UJ")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/LiskovACDGGMMS96","0Mj8N23H1QEJ")).
pos(eqo("conf/sigmod/LiskovACDGGMMS96","Ey7Mbh6IdQIJ")).
pos(eqo("conf/sigmod/LoR94","3CMnzSHX7KoJ")).
pos(eqo("conf/sigmod/MankuRL99","X94gDE70Zn0J")).
pos(eqo("conf/sigmod/MankuRL99","vry1-y-mFF8J")).
pos(eqo("conf/sigmod/MarklL02","5fSqMJg7FV4J")).
pos(eqo("conf/sigmod/MatiasVW98","6WjESNMzLvgJ")).
pos(eqo("conf/sigmod/MayrS99","1lRZz4bZvxEJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/Miller98","7f6Q9GgXsmgJ")).
pos(eqo("conf/sigmod/Mohan96","C-yzbvoAg00J")).
pos(eqo("conf/sigmod/Moore95","uh57sQuxYuIJ")).
pos(eqo("conf/sigmod/NgLHM99","YemauUgIzlcJ")).
pos(eqo("conf/sigmod/NguyenACP01","A57h1N3H3pgJ")).
pos(eqo("conf/sigmod/ONeilQ97","359PjJkfNhQJ")).
pos(eqo("conf/sigmod/ONeilQ97","6twtfqrudGcJ")).
pos(eqo("conf/sigmod/ONeilQ97","lMTodOXT45MJ")).
pos(eqo("conf/sigmod/ONeilQ97","tK0HTC7qEmcJ")).
pos(eqo("conf/sigmod/OhHP00","cFpgCsBTSBEJ")).
pos(eqo("conf/sigmod/OlstonWL01","I_YprPVQ45QJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","du5GsqT0_vQJ")).
pos(eqo("conf/sigmod/PatelYKTNBHRLEKGDN97","0inuMFZSQ50J")).
pos(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","uveOdmVtqRMJ")).
pos(eqo("conf/sigmod/RafieiM97","N-kEDX56ek0J")).
pos(eqo("conf/sigmod/RafieiM97","UBACGF9cQ2UJ")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/RamakrishnanD98","LSNo-7ii1vEJ")).
pos(eqo("conf/sigmod/RamakrishnanD98","url:http://portal.acm.org/citation.cfm%3Fid%3D276305.276361%26dl%3DGUIDE%26dl%3DACM%26idx%3D276305%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RamaswamyRS00","o0vnSBVzRQcJ")).
pos(eqo("conf/sigmod/RaoR00","wp2_GObi-XkJ")).
pos(eqo("conf/sigmod/RaoR98","iqZZMPppeKAJ")).
pos(eqo("conf/sigmod/RodriguezR00","MCDgDxsc8rcJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","yfTTlN56sCUJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","00c1qmRdM5IJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
pos(eqo("conf/sigmod/RundensteinerCLCZNJLW99","SADcQZhMqgEJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","nyHFfFtClVsJ")).
pos(eqo("conf/sigmod/RundensteinerKZWLLN99","2XRfNjwuDrsJ")).
pos(eqo("conf/sigmod/SalemBCL00","FElMcikK2GUJ")).
pos(eqo("conf/sigmod/Sarawagi00","-cYYeoF2GwMJ")).
pos(eqo("conf/sigmod/Sarawagi00","H_bdYlpD79oJ")).
pos(eqo("conf/sigmod/SarawagiTA98","0Vmsc0oib2kJ")).
pos(eqo("conf/sigmod/SarawagiTA98","ZLUo-gCGx5EJ")).
pos(eqo("conf/sigmod/SarawagiTA98","ut4Y99B1094J")).
pos(eqo("conf/sigmod/Tajima96","IZSzLlgi8tUJ")).
pos(eqo("conf/sigmod/TsueiPK97","DpQGq6n1jnkJ")).
pos(eqo("conf/sigmod/Ubell94","lphlTARDI9YJ")).
pos(eqo("conf/sigmod/VingralekBW94","rM8Ecg1WL4kJ")).
pos(eqo("conf/sigmod/VriesMNK02","dVn0Led5JLAJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","_Xj-7At79joJ")).
pos(eqo("conf/sigmod/WangSSZZW00","CaplZan57x4J")).
pos(eqo("conf/sigmod/WilschutFA95","Zdfxvjh6ca8J")).
pos(eqo("conf/sigmod/WodtkeWWDM97","XoAeyeaR-yAJ")).
pos(eqo("conf/sigmod/Wu99","xl1Jscb79KEJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qzxeS4RQAhwJ")).
pos(eqo("conf/sigmod/ZhangNBB94","HItpqMOcE8gJ")).
pos(eqo("conf/sigmod/ZhangNBB94","bymQ_6SSse4J")).
pos(eqo("conf/sigmod/ZhaoDN97","b-Va1c3t13gJ")).
pos(eqo("conf/sigmod/ZhaoDN97","chYdQDE8cPsJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","36ibNcuzKVAJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","SSwR2rhkJk0J")).
pos(eqo("conf/sigmod/ZhugeGHW95","_XLK2p-e2pYJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","lUxILYnWlLYJ")).
pos(eqo("conf/sigmod/ZuzartePMCLW03","url:http://portal.acm.org/citation.cfm%3Fid%3D872757.872840")).
pos(eqo("conf/vldb/AboulnagaAN01","OBbDFGQNEDQJ")).
pos(eqo("conf/vldb/AboulnagaAN01","P6wBeL9DsREJ")).
pos(eqo("conf/vldb/AbrolLMMMRTWZ01","w9Ma-YjZHYkJ")).
pos(eqo("conf/vldb/AcharyaFZ96","ccEW59Ac84MJ")).
pos(eqo("conf/vldb/AcharyaFZ96","oH_xfQI8wIgJ")).
pos(eqo("conf/vldb/AcharyaFZ96","sSwdOhIGec0J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","E4fU9kpfXQsJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","jugePLZ8yKcJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/AgrawalCN00","U8CMJBaJyX8J")).
pos(eqo("conf/vldb/AgrawalCN00","b9uF_OTTHIEJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","wu8UrFu8Tu8J")).
pos(eqo("conf/vldb/AgrawalSX02","a1CLM5GoVtYJ")).
pos(eqo("conf/vldb/AmielBDS94","hBak02oe1GMJ")).
pos(eqo("conf/vldb/AnSVKIG01","HosSI1GtRY8J")).
pos(eqo("conf/vldb/AnanthakrishnaCG02","FFKP2GRm2LEJ")).
pos(eqo("conf/vldb/AnciauxBP03","gYELZxhiJx8J")).
pos(eqo("conf/vldb/AnkerstBKS98","DbLGmJX7UJ8J")).
pos(eqo("conf/vldb/AshwinGG02","YiJojduGXXkJ")).
pos(eqo("conf/vldb/BalminPP00","FoAVdcYe0tsJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/BargaP95","3CDeAczlaSUJ")).
pos(eqo("conf/vldb/BargaP95","Rp6i1uA3RYQJ")).
pos(eqo("conf/vldb/BargaP95","clqEOLT55pUJ")).
pos(eqo("conf/vldb/Baumann03","pJ2UEKVG_hoJ")).
pos(eqo("conf/vldb/BenediktCFRZZ02","7xe6Gp9fIEEJ")).
pos(eqo("conf/vldb/BerchtoldKK96","G__T5t9i4ZwJ")).
pos(eqo("conf/vldb/BerchtoldKK96","KLzrIupmRloJ")).
pos(eqo("conf/vldb/BerchtoldKK96","S-aEcHjpLBMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WcxbHqh4FfkJ")).
pos(eqo("conf/vldb/BerchtoldKK96","knyp-i1eDwwJ")).
pos(eqo("conf/vldb/Bernstein94","TqLyg1wbo5UJ")).
pos(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
pos(eqo("conf/vldb/Bhashyam96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245908%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/BliujuteJSS98","gybR2qK1ib8J")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BohannonFHRRS02","zYfyg0fCzEsJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","GzK2N5eQ0pQJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","Vj1kbPjzSHwJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","thTt2lg4_Z8J")).
pos(eqo("conf/vldb/BouguettayaEMO01","n-tA57d7ydcJ")).
pos(eqo("conf/vldb/BratsbergH01","x-oQarjjgccJ")).
pos(eqo("conf/vldb/BrownCC94","E-1nAx7gc-8J")).
pos(eqo("conf/vldb/BrownS95","F-v-VG2RBQoJ")).
pos(eqo("conf/vldb/Cabrera03","url:http://wwwdb.informatik.uni-rostock.de/vldb2003/papers/S31P01.pdf")).
pos(eqo("conf/vldb/Campbell99","m1eeQnYWL0oJ")).
pos(eqo("conf/vldb/CareyCNVDRSM99","JpMllVmmnkAJ")).
pos(eqo("conf/vldb/CareyD96","g8jnRVyQukAJ")).
pos(eqo("conf/vldb/CareyD96","lW_0wZmDIaIJ")).
pos(eqo("conf/vldb/CarneyCCCLSSTZ02","4-igDwZdi-QJ")).
pos(eqo("conf/vldb/CarneyCCCLSSTZ02","KUYFJk7kXGEJ")).
pos(eqo("conf/vldb/CasatiS00","yGYyg3tCPEcJ")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","QyBDbs7EpmsJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChakrabartiGRS00","2TVYDBNYioIJ")).
pos(eqo("conf/vldb/ChakrabartiSD98","oBDL7axDwG4J")).
pos(eqo("conf/vldb/ChandrasekaranF02","Yu4Tvuy_WiAJ")).
pos(eqo("conf/vldb/ChaudhuriG99","yniboichufIJ")).
pos(eqo("conf/vldb/ChaudhuriW00","OuM0E0BhEXIJ")).
pos(eqo("conf/vldb/Chiueh94","PKK2ak_IzrgJ")).
pos(eqo("conf/vldb/ChristodoulakisTZ97","D0z0BDnbnFcJ")).
pos(eqo("conf/vldb/ChungCLL01","mJiDvbtTKWoJ")).
pos(eqo("conf/vldb/CosleyLP02","22ZTae8fNuIJ")).
pos(eqo("conf/vldb/DattaRT99","gckQTLQjsj8J")).
pos(eqo("conf/vldb/DeWittKLPY94","xcwQARsnK4gJ")).
pos(eqo("conf/vldb/DillKMRST01","eZoS-yciSRsJ")).
pos(eqo("conf/vldb/EvangelidisLS95","hR9tpdTkYkcJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","ume4RGX6sI4J")).
pos(eqo("conf/vldb/FlodinR95","b5vbAhJ4xxMJ")).
pos(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","OEpwAcnqlWwJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","RZZjZ_7yJb8J")).
pos(eqo("conf/vldb/GalhardasFSSS01","Z8jYTylZtkEJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","nlOAkKW_ry8J")).
pos(eqo("conf/vldb/GarofalakisOS97","dW_pRNemQfsJ")).
pos(eqo("conf/vldb/GarofalakisRS99","9aNUdPCEMmwJ")).
pos(eqo("conf/vldb/GarofalakisRS99","poso7AKokFMJ")).
pos(eqo("conf/vldb/GoldsteinR00","FncQ86sO2agJ")).
pos(eqo("conf/vldb/GoodmanRS94","8CCHAKnGJ1EJ")).
pos(eqo("conf/vldb/GottlobKP02","Pk09A5EmsOoJ")).
pos(eqo("conf/vldb/GottlobKP02","fnIXflrczOEJ")).
pos(eqo("conf/vldb/Graefe99","3m-KKBVF8KkJ")).
pos(eqo("conf/vldb/GravanoG95","2nMktwioqOYJ")).
pos(eqo("conf/vldb/GravanoG95","4HVB6aRvsk8J")).
pos(eqo("conf/vldb/GravanoG95","DNh5uw1WWUEJ")).
pos(eqo("conf/vldb/GravanoG95","zbJYyUhl2cIJ")).
pos(eqo("conf/vldb/GrovlenHT98","xjVz8hIW-8sJ")).
pos(eqo("conf/vldb/GuntzerBK00","id3rk1JgWx0J")).
pos(eqo("conf/vldb/HaasKWY97","ZQG-8D6v7BoJ")).
pos(eqo("conf/vldb/HaasKWY97","aDDbEmg7oYYJ")).
pos(eqo("conf/vldb/HaasKWY97","fsoE2pQM6G8J")).
pos(eqo("conf/vldb/HammelP02","SU2XS1MVb40J")).
pos(eqo("conf/vldb/HeMYW03","cBe5X4EKjIEJ")).
pos(eqo("conf/vldb/HellersteinNP95","AC19Z_yOCTUJ")).
pos(eqo("conf/vldb/HellersteinNP95","V1M4safuoecJ")).
pos(eqo("conf/vldb/HelmerWM98","5ipPVLRhDqoJ")).
pos(eqo("conf/vldb/HjelsvoldM94","5Wuyp1aLBocJ")).
pos(eqo("conf/vldb/HristidisP02","5k-GwvznWRUJ")).
pos(eqo("conf/vldb/HulgeriS02","syoqNSarAscJ")).
pos(eqo("conf/vldb/HulgeriS02","xGcM9AuhrBMJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","_83yTuPv-NAJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","o2qGdf4L94MJ")).
pos(eqo("conf/vldb/IwerksSS03","4B_LhCns0WoJ")).
pos(eqo("conf/vldb/JagadishLRSS94","Yiwh22hbTAcJ")).
pos(eqo("conf/vldb/JagadishLRSS94","em_mB-ifc80J")).
pos(eqo("conf/vldb/JagadishNSSK97","ZG9yClLgWnsJ")).
pos(eqo("conf/vldb/JagatheesanMPW03","InqySB8bkKkJ")).
pos(eqo("conf/vldb/Jamil97","tLpAE7ZSkLsJ")).
pos(eqo("conf/vldb/JiangSLB00","eZwzDZ7QhzoJ")).
pos(eqo("conf/vldb/JohnsonM98","V4PVzPaBOBUJ")).
pos(eqo("conf/vldb/JohnsonM98","cTZLUZ5_cfkJ")).
pos(eqo("conf/vldb/JohnsonM98","gm9Ist67nJQJ")).
pos(eqo("conf/vldb/KahveciS01","i6KmypFd39AJ")).
pos(eqo("conf/vldb/KaushikBNS02","dL5oJVHK10kJ")).
pos(eqo("conf/vldb/KeidlSSK02","Wc1ViFeRa54J")).
pos(eqo("conf/vldb/KeidlSSK02","dTval1yE6p8J")).
pos(eqo("conf/vldb/KiesslingK02","3VHepuiTGHUJ")).
pos(eqo("conf/vldb/KiesslingK02","4XP24_IFvPsJ")).
pos(eqo("conf/vldb/Klots96","dTORuW_9YRoJ")).
pos(eqo("conf/vldb/KnorrN98","oCPpSbHhL3IJ")).
pos(eqo("conf/vldb/KornMS02","mClzTQppJE4J")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/vldb/KornSFSP96","51VkEWUxxLIJ")).
pos(eqo("conf/vldb/KornSFSP96","QjbxSG6_-WIJ")).
pos(eqo("conf/vldb/Kornacker99","aOmma8tnFKIJ")).
pos(eqo("conf/vldb/Korth95","UZAQL1o-c0MJ")).
pos(eqo("conf/vldb/KossmannRR02","iGlztgiSTe4J")).
pos(eqo("conf/vldb/KumarKA97","hhHVHYnMd6kJ")).
pos(eqo("conf/vldb/LabioG96","1JLlGYW8cDAJ")).
pos(eqo("conf/vldb/LakshmananSS96","GDmbzrUbyzAJ")).
pos(eqo("conf/vldb/LakshmananSS96","XPjpq3h5BhUJ")).
pos(eqo("conf/vldb/LakshmananSS99","RSpmu6WtYBMJ")).
pos(eqo("conf/vldb/LeeL99","szHsyFiOuwAJ")).
pos(eqo("conf/vldb/LempelM02","DcSYGPdhxwoJ")).
pos(eqo("conf/vldb/LernerS03","KtkbM7ohXrEJ")).
pos(eqo("conf/vldb/LiRS99","cGbo_ZtYKwYJ")).
pos(eqo("conf/vldb/LingLL00","lNvW4tc-B2EJ")).
pos(eqo("conf/vldb/LingLL00","yKnPPSNrDb0J")).
pos(eqo("conf/vldb/LuSL95","AvfsXnSTA24J")).
pos(eqo("conf/vldb/LuSL95","h24eSPFv8MoJ")).
pos(eqo("conf/vldb/Madnick95","CVQyvLe8w38J")).
pos(eqo("conf/vldb/Madnick95","UHLfs0GGqAAJ")).
pos(eqo("conf/vldb/MaratheS97","HcgXkUDB-wYJ")).
pos(eqo("conf/vldb/McKennaBHT96","0tZaTV3W05wJ")).
pos(eqo("conf/vldb/MeekPK03","BV6S1LOk4XwJ")).
pos(eqo("conf/vldb/MeekPK03","cR1ikuFsE1wJ")).
pos(eqo("conf/vldb/MendelzonV00","AQLsLBctUI4J")).
pos(eqo("conf/vldb/MendelzonV00","Ah3ENTVwMj4J")).
pos(eqo("conf/vldb/MignetMAC01","VaDXNMtPZ4oJ")).
pos(eqo("conf/vldb/MignetMAC01","XirELrPeTd4J")).
pos(eqo("conf/vldb/Mohan01","tAO-l_SkmSwJ")).
pos(eqo("conf/vldb/Mohan02","eyxIItge9MQJ")).
pos(eqo("conf/vldb/NetzCBF00","mRIRFxOC8A8J")).
pos(eqo("conf/vldb/NgC97","eTDBrdfpGNEJ")).
pos(eqo("conf/vldb/NgH94","AJ7Qj_bt0ZoJ")).
pos(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
pos(eqo("conf/vldb/NgH94","EsSRui40spgJ")).
pos(eqo("conf/vldb/NgH94","JA55PRiwrMQJ")).
pos(eqo("conf/vldb/NgH94","WjnMy2NiG10J")).
pos(eqo("conf/vldb/NgH94","WlNAuSKoGN4J")).
pos(eqo("conf/vldb/NgH94","XfblD8N3jT8J")).
pos(eqo("conf/vldb/NgH94","ltzWlNOJavwJ")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/OzsoyogluAAOUO02","Pb3y_NGGwjwJ")).
pos(eqo("conf/vldb/OzsuLON01","qqdXmdgAaMgJ")).
pos(eqo("conf/vldb/Padmanabhan96","1IjlMvLBFC0J")).
pos(eqo("conf/vldb/PereiraFJLS01","CZTJ00lolvYJ")).
pos(eqo("conf/vldb/PereiraFJLS01","Cd6A4nsDnkQJ")).
pos(eqo("conf/vldb/PirotteZMY94","8s-SP8sAvQAJ")).
pos(eqo("conf/vldb/RaghavanG01","LcX8Pm2ABJsJ")).
pos(eqo("conf/vldb/RaghavanG01","MytkkvQ5ieMJ")).
pos(eqo("conf/vldb/RamakrishnanGRSWZ95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.756661")).
pos(eqo("conf/vldb/Ramanan03","QCJEyGp-iZcJ")).
pos(eqo("conf/vldb/RastogiS98","AyWUeJ5k2IoJ")).
pos(eqo("conf/vldb/RysNS96","pwxPfVlOqQUJ")).
pos(eqo("conf/vldb/Sarawagi99","W_CVz6V80csJ")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/SavasereON95","c4m40zywvWsJ")).
pos(eqo("conf/vldb/SavasereON95","rHLmfJRQUu0J")).
pos(eqo("conf/vldb/SavasereON95","tX0hBHC5_UQJ")).
pos(eqo("conf/vldb/SchindlerAG03","CsWyDorgQF4J")).
pos(eqo("conf/vldb/SeshadriLR96","-Pmsximl_moJ")).
pos(eqo("conf/vldb/SeshadriLR96","K62EwWeSRKUJ")).
pos(eqo("conf/vldb/ShaferAM96","Jl3IrO4qDqMJ")).
pos(eqo("conf/vldb/ShaferAM96","pRMh6pGr-XUJ")).
pos(eqo("conf/vldb/ShahDR03","HGJu1Uyq-OcJ")).
pos(eqo("conf/vldb/ShahabiFKF00","ln1yHhG7gdgJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","ZQyBjtpbhvIJ")).
pos(eqo("conf/vldb/ShashaB02","6nTs7QjnfDcJ")).
pos(eqo("conf/vldb/SistlaYH94","QWD1EGMbTQYJ")).
pos(eqo("conf/vldb/SistlaYH94","_jl3bN2QlE4J")).
pos(eqo("conf/vldb/SistlaYH94","bDH4OmzDSLEJ")).
pos(eqo("conf/vldb/SistlaYLL95","HtTNmhCJY-oJ")).
pos(eqo("conf/vldb/SrikantA95","DLymXxpy2qYJ")).
pos(eqo("conf/vldb/SrikantA95","K1nbpKn1IbsJ")).
pos(eqo("conf/vldb/SrikantA95","OUdGxoZdSxAJ")).
pos(eqo("conf/vldb/SrikantA95","bibMn8zFnksJ")).
pos(eqo("conf/vldb/StaudtJ96","6moFnThDHW0J")).
pos(eqo("conf/vldb/SteenhagenABB94","IgWfWMn1_AAJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","aCZo57LF-4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","n5yJ4y54WbwJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","EPtaqugcCyMJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","k-IlQ6VnmKsJ")).
pos(eqo("conf/vldb/StolteA02","N3Bry6sSMw8J")).
pos(eqo("conf/vldb/Suciu96","GwvN1w9_ZZoJ")).
pos(eqo("conf/vldb/TamuraK99","N0yBbMrpeUwJ")).
pos(eqo("conf/vldb/TamuraK99","rAHGAfoqookJ")).
pos(eqo("conf/vldb/TanEO01","1A06w64wjvcJ")).
pos(eqo("conf/vldb/TanSHCR01","hPcNG0tPwgIJ")).
pos(eqo("conf/vldb/TeisseirePC94","w17spSGfEXYJ")).
pos(eqo("conf/vldb/TengCY03","wJjaZnzD6pAJ")).
pos(eqo("conf/vldb/TianD03","l7glyH7ltuQJ")).
pos(eqo("conf/vldb/Toivonen96","tZpeMfkDl8cJ")).
pos(eqo("conf/vldb/Toivonen96","ut53pjEsmxEJ")).
pos(eqo("conf/vldb/TsatalosSI94","--1aoAaGkgQJ")).
pos(eqo("conf/vldb/VassalosP97","5DKaP73v7FQJ")).
pos(eqo("conf/vldb/VassalosP97","9MlAuURfKhYJ")).
pos(eqo("conf/vldb/VassalosP97","jmYHA7e95XAJ")).
pos(eqo("conf/vldb/VassalosP97","kG-k9420fGMJ")).
pos(eqo("conf/vldb/VelegrakisMP03","gP3ld61I__kJ")).
pos(eqo("conf/vldb/VorugantiOU99","ItOlYY7ITt0J")).
pos(eqo("conf/vldb/WangYM97","OnLLKkgfyLUJ")).
pos(eqo("conf/vldb/WangYM97","RiOvjzg_MJwJ")).
pos(eqo("conf/vldb/WangYM97","hcYKj7CHbWYJ")).
pos(eqo("conf/vldb/WangYM97","o5dSRIunsUUJ")).
pos(eqo("conf/vldb/WeikumMHZ02","W_b-Eo5VaOgJ")).
pos(eqo("conf/vldb/YangG01","UZBoDXflaXoJ")).
pos(eqo("conf/vldb/YangG01","xQYKEHCggZQJ")).
pos(eqo("conf/vldb/YuPM03","sP3bZMqHmZsJ")).
pos(eqo("conf/vldb/ZengBNN01","MA7NWFIgTaoJ")).
pos(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
pos(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637424%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AndlerHEMBE96","3Isoplo_hi0J")).
pos(eqo("journals/sigmod/AndlerHEMBE96","J82SdCmczAcJ")).
pos(eqo("journals/sigmod/ArenasKKKMM03","rl50qPw8UaEJ")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","Syu5W-3uFFAJ")).
pos(eqo("journals/sigmod/BernsteinDK99","MsK0xHsckUIJ")).
pos(eqo("journals/sigmod/BernsteinDK99","ne7WhiSL9QYJ")).
pos(eqo("journals/sigmod/BernsteinHP00","FFzJxlpy6TsJ")).
pos(eqo("journals/sigmod/BernsteinHP00","oHXkI3GgweIJ")).
pos(eqo("journals/sigmod/BernsteinHP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369289%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BertinoEH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373684%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BorgidaCS98","iPbD7vPHzgYJ")).
pos(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373708%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BoucelmaCGJLL02","I9JXY0-R4GgJ")).
pos(eqo("journals/sigmod/Bussler02","Phcd3C1cfLcJ")).
pos(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D641006")).
pos(eqo("journals/sigmod/ChaudhuriD97","IdNPV86IxM0J")).
pos(eqo("journals/sigmod/ChaudhuriD97","oXTd748VmwMJ")).
pos(eqo("journals/sigmod/CheungF98","ujeEtXpQFIsJ")).
pos(eqo("journals/sigmod/Danish98","mKZyoPZArGcJ")).
pos(eqo("journals/sigmod/EisenbergM01","GKUflKzgAVEJ")).
pos(eqo("journals/sigmod/EisenbergM01","lTNqBpBUA5sJ")).
pos(eqo("journals/sigmod/Fankhauser01","_sltXCfRKhYJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","5PisY7JvbzQJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","93C5Prxx5YcJ")).
pos(eqo("journals/sigmod/Gallagher94","PVm9r7wHzDAJ")).
pos(eqo("journals/sigmod/GerlaX03","KKiefntReoUJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","_q3scPb8vbgJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","url:http://portal.acm.org/citation.cfm%3Fid%3D333607.333616%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Hampapur99","I-r1LE1najAJ")).
pos(eqo("journals/sigmod/Hampapur99","xW--Ei3c_qwJ")).
pos(eqo("journals/sigmod/Hellerstein03","5FSG85HbUygJ")).
pos(eqo("journals/sigmod/JainH94","taphZimnV-gJ")).
pos(eqo("journals/sigmod/KimballS95","E6Z68tQL1BsJ")).
pos(eqo("journals/sigmod/KuanL99","lkrtCULVA6oJ")).
pos(eqo("journals/sigmod/LabrinidisR00","TppC2jA5UXMJ")).
pos(eqo("journals/sigmod/LeeC00","Knzz_bkGA00J")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/McClatcheyV97","mbFxAqrWXbYJ")).
pos(eqo("journals/sigmod/MeltonE02","6uelfg3RgEoJ")).
pos(eqo("journals/sigmod/MusickM98","gt83e4uB09wJ")).
pos(eqo("journals/sigmod/ONeilG95","51gKshu0CWcJ")).
pos(eqo("journals/sigmod/ONeilG95","RlH2shMtkfwJ")).
pos(eqo("journals/sigmod/ONeilG95","YNkY3rC_4zQJ")).
pos(eqo("journals/sigmod/Ouksel02","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565131%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/OukselS99","YeVWiZOxB9IJ")).
pos(eqo("journals/sigmod/PaepckeGRC00","hxFRuvCtvGEJ")).
pos(eqo("journals/sigmod/PapianiWDN99","aU7XlTpoxRgJ")).
pos(eqo("journals/sigmod/PourabbasR00","3y6y5AXu-j0J")).
pos(eqo("journals/sigmod/RoddickABDEGHLMMMW00","eA8gNVxHRJ4J")).
pos(eqo("journals/sigmod/RosenthalS99","ZYnsLI6mz2cJ")).
pos(eqo("journals/sigmod/RosenthalSMBTL95","-_FyboGgZkkJ")).
pos(eqo("journals/sigmod/Rosneblatt94","D1RdxKP6_6YJ")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","mkfP-JNsNZoJ")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603872%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ShethGJRSWW96","HOvgrl8NmmoJ")).
pos(eqo("journals/sigmod/ShethMKA01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604286%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SpynsMJ02","QWfa2xEybLcJ")).
pos(eqo("journals/sigmod/TheodoridisN00","DXTczW8Dv4MJ")).
pos(eqo("journals/sigmod/TheodoridisN00","NegSmYlF-awJ")).
pos(eqo("journals/sigmod/TsotrasJS98","FBZw8n-gojUJ")).
pos(eqo("journals/sigmod/VetterliVS00","h7RBOvmQHhEJ")).
pos(eqo("journals/sigmod/Wedekind94","gqehj3-ukjIJ")).
pos(eqo("journals/sigmod/YanG95","tMXkkRDxvkQJ")).
pos(eqo("journals/sigmod/YuenCLL00","Ip82P4QfKyEJ")).
pos(eqo("journals/tods/AikenHW95","XLld3hq3vt0J")).
pos(eqo("journals/tods/AikenHW95","cHpmOFVpTi8J")).
pos(eqo("journals/tods/CasatiCPP99","6F_cUJERo6sJ")).
pos(eqo("journals/tods/CasatiCPP99","b6-zHfA02TgJ")).
pos(eqo("journals/tods/CasatiCPP99","bWa_AKkBbn8J")).
pos(eqo("journals/tods/ChakrabartiKMP02","QTzuiNlMnR4J")).
pos(eqo("journals/tods/CliffordC94","9txS2mlA2DMJ")).
pos(eqo("journals/tods/DattaVCK99","3BbftjVsIEIJ")).
pos(eqo("journals/tods/DattaVCK99","L_EKDuVUoIEJ")).
pos(eqo("journals/tods/DattaVCK99","VaO8O5WO0IcJ")).
pos(eqo("journals/tods/DekhtyarRS01","Bho8kTicu-8J")).
pos(eqo("journals/tods/DekhtyarRS01","jZShiF9wrikJ")).
pos(eqo("journals/tods/DeyS96","l2y2U5f48WcJ")).
pos(eqo("journals/tods/DyresonS98","dvlv3BMgYrIJ")).
pos(eqo("journals/tods/FranklinCL97","-iaSLKFHwUkJ")).
pos(eqo("journals/tods/FranklinCL97","vqboZ3T4n4AJ")).
pos(eqo("journals/tods/GoldmanL94","VxMarpzwtzQJ")).
pos(eqo("journals/tods/GuoSW96","V8Ls_TYs6mgJ")).
pos(eqo("journals/tods/KrishnakumarB94","8ZjEDOBUd_QJ")).
pos(eqo("journals/tods/Lerner00","YFKv4PEG_5EJ")).
pos(eqo("journals/tods/LeveneL99","iwPgaJ1eQrkJ")).
pos(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
pos(eqo("journals/tods/LiuHD98","ts7DF925TR8J")).
pos(eqo("journals/tods/ScioreSR94","fW9j2V5gnUMJ")).
pos(eqo("journals/tods/SrivastavaSRN95","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0219026CI")).
pos(eqo("journals/tods/TaoP03","faqaX7J_Kl8J")).
pos(eqo("journals/tods/Wijsen99","_D3JPE9NgNgJ")).
pos(eqo("journals/tods/YanG94","X7w4rQXqf70J")).
pos(eqo("journals/tods/YanG94","Xh9AnV9p-REJ")).
pos(eqo("journals/tods/YanG94","fx6kDLBa8q8J")).
pos(eqo("journals/vldb/Antoshenkov97","gleX-n_dgkcJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","Hc9uWxJu840J")).
pos(eqo("journals/vldb/Barbara-MillaG94","md3DWyujCrQJ")).
pos(eqo("journals/vldb/BerchtoldKK97","VHo2go6vjYsJ")).
pos(eqo("journals/vldb/BerendtS00","zh9CAewEvisJ")).
pos(eqo("journals/vldb/CandanLS00","nXvDy_QqSd4J")).
pos(eqo("journals/vldb/ChakrabartiDAR98","0EbuWDceVnoJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","2TVYDBNYioIJ")).
pos(eqo("journals/vldb/ConstantopoulosJMV95","_da6PvkQBM4J")).
pos(eqo("journals/vldb/CuiW03","SaOd6rDz5ZgJ")).
pos(eqo("journals/vldb/DesslochHMMT98","4D2HQE6fXXEJ")).
pos(eqo("journals/vldb/GeorgeH00","2L-UFpDof3UJ")).
pos(eqo("journals/vldb/GutingS95","A4lUwOD7AeYJ")).
pos(eqo("journals/vldb/GutingS95","rjQa8odFpMwJ")).
pos(eqo("journals/vldb/HarderST99","KGyKFmRfspAJ")).
pos(eqo("journals/vldb/JagadishKNS00","GtXc02EJjCgJ")).
pos(eqo("journals/vldb/JagadishKNS00","W8O7pgTYGTYJ")).
pos(eqo("journals/vldb/KabraD99","pWEfI0xFFcoJ")).
pos(eqo("journals/vldb/KnorrNT00","SggrbO99AJgJ")).
pos(eqo("journals/vldb/LawLG99","TOXrbhbbNJ4J")).
pos(eqo("journals/vldb/MuthOPW00","WFygKYK0NVQJ")).
pos(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
pos(eqo("journals/vldb/OoiTCH98","xv1webZ985MJ")).
pos(eqo("journals/vldb/OzsuPSILM95","2Y6WYH71fO0J")).
pos(eqo("journals/vldb/OzsuPSILM95","E02lExYdRYwJ")).
pos(eqo("journals/vldb/OzsuPSILM95","epUf9ogilogJ")).
pos(eqo("journals/vldb/OzsuPSILM95","g7SusKnyItEJ")).
pos(eqo("journals/vldb/PapazogluK97","kFQl7LX8OQkJ")).
pos(eqo("journals/vldb/PucheralBVB01","K9Qbh3haBCMJ")).
pos(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
pos(eqo("journals/vldb/RahmB01","GJtc6TCE-hIJ")).
pos(eqo("journals/vldb/RahmB01","TBoS0CBe1vQJ")).
pos(eqo("journals/vldb/RahmB01","b9ikqvr7Bb4J")).
pos(eqo("journals/vldb/ShegalovGW01","_6ErNQyZwXsJ")).
pos(eqo("journals/vldb/SinghalS97","3fO2448hZgwJ")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","FnypYUw9pwEJ")).
pos(eqo("journals/vldb/TsatalosSI96","--1aoAaGkgQJ")).
pos(eqo("journals/vldb/VerykiosME03","khdP4spNnPoJ")).
pos(eqo("journals/vldb/ZezulaSAR98","DM9hrpKpqmMJ")).
