neg(eqo("conf/sigmod/2003","mMBaBUVatqoJ")).
neg(eqo("conf/sigmod/AcharyaPR99","s064OghlyIUJ")).
neg(eqo("conf/sigmod/AdaliBSS98","wF_GdZPkCnQJ")).
neg(eqo("conf/sigmod/AdamY98","3aPleydkcIoJ")).
neg(eqo("conf/sigmod/AfratiLU01","5FiyBEZ3v70J")).
neg(eqo("conf/sigmod/Aggarwal02","XzSqN32OqgMJ")).
neg(eqo("conf/sigmod/Aggarwal03","ulDBbXl-6Q4J")).
neg(eqo("conf/sigmod/Aggarwal03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083696%26type%3Dpdf")).
neg(eqo("conf/sigmod/AgichteinG03","I_YprPVQ45QJ")).
neg(eqo("conf/sigmod/AgrawalASY97","CqbNc79TtBsJ")).
neg(eqo("conf/sigmod/AgrawalS00","e5SJ3zgdwgEJ")).
neg(eqo("conf/sigmod/AgrawalS00","rsxdUf1DVNQJ")).
neg(eqo("conf/sigmod/Al-KhalifaYJ03","aepGxosl6YoJ")).
neg(eqo("conf/sigmod/AltinelLKMPLWB02","jxL7i2xXm2EJ")).
neg(eqo("conf/sigmod/AmbiteABKMMMPT98","irJbh9rrinoJ")).
neg(eqo("conf/sigmod/AndersonAF98","PBtu7Xy2Z_cJ")).
neg(eqo("conf/sigmod/ArefBV95","l5NUrO6uRf4J")).
neg(eqo("conf/sigmod/AtzeniT97","XaKiz5S-cqUJ")).
neg(eqo("conf/sigmod/BabcockO03","dNvFuZGBx0YJ")).
neg(eqo("conf/sigmod/Ballinger94","xGGBIZmLvmgJ")).
neg(eqo("conf/sigmod/BarclaySG00","_lfz6ZJS2P0J")).
neg(eqo("conf/sigmod/BarclaySG00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776997%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BargaL99","gTwgcXrpOxMJ")).
neg(eqo("conf/sigmod/BaruFGHJPW95","zO0DfwHqXKUJ")).
neg(eqo("conf/sigmod/BaruGLMPVC99","3SHIgRrrL5QJ")).
neg(eqo("conf/sigmod/BenediktCFFR03","wt0Qa1pYrqIJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","KxwymZ2AGNQJ")).
neg(eqo("conf/sigmod/BerchtoldK98","AvSmUv4YXmsJ")).
neg(eqo("conf/sigmod/BerckenDS00","3IFlpeKgLlAJ")).
neg(eqo("conf/sigmod/BergstraesserBPS99","pmtY1d0NLe4J")).
neg(eqo("conf/sigmod/BhargavaGI95","TXvfEP4WTD0J")).
neg(eqo("conf/sigmod/BhattacharyaMBNHS02","2J_9scP1caYJ")).
neg(eqo("conf/sigmod/Bierman03","DJte_7xhQr4J")).
neg(eqo("conf/sigmod/BlohsfeldKS99","hFnEDWudza8J")).
neg(eqo("conf/sigmod/BlohsfeldKS99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3DA8622973AH")).
neg(eqo("conf/sigmod/BohmA96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369277%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Bonnet02","VP2ddhGdqm4J")).
neg(eqo("conf/sigmod/BonnetBCCCHKMMOSS99","CFA7wfqYL6EJ")).
neg(eqo("conf/sigmod/BressanGOT00","c92hfzTG4RIJ")).
neg(eqo("conf/sigmod/BrinMUT97","bjZ8SxYnrd0J")).
neg(eqo("conf/sigmod/BrinMUT97","n2HWVedEvkoJ")).
neg(eqo("conf/sigmod/BrodskyK95","SFmnhrhoQzgJ")).
neg(eqo("conf/sigmod/BrodskySCE99","jnBo-gBTmAcJ")).
neg(eqo("conf/sigmod/BryanMCLG94","q--vBJhnNiYJ")).
neg(eqo("conf/sigmod/BunemanKTT02","NriDTL0qCqYJ")).
neg(eqo("conf/sigmod/Bussler01","M_Ao8zDvquEJ")).
neg(eqo("conf/sigmod/CallanCD99","yjsXspk2XrgJ")).
neg(eqo("conf/sigmod/Carey94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CareyDNAGS97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294143CI")).
neg(eqo("conf/sigmod/CatarciS94","PgzcABl76dQJ")).
neg(eqo("conf/sigmod/CeriFPP95","NuH-9L-FlooJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","n8VsQfg-qDsJ")).
neg(eqo("conf/sigmod/ChanI99","VTSs_WSxdMkJ")).
neg(eqo("conf/sigmod/ChanI99","oF386g76F2AJ")).
neg(eqo("conf/sigmod/ChangC01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141004%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Chaudhuri97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1016031%26type%3Dpdf")).
neg(eqo("conf/sigmod/ChaudhuriDY95","lLARMvKaIQMJ")).
neg(eqo("conf/sigmod/ChaudhuriGN02","g6XLqjCRkFcJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","BYAyZpRK7k0J")).
neg(eqo("conf/sigmod/ChaudhuriMN98","8OyqJKNuu14J")).
neg(eqo("conf/sigmod/ChaudhuriMN99","Tagq11E6HfAJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","TqXFdQBTW6kJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","niAPzsMp2igJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","xAwNq-a4ju0J")).
neg(eqo("conf/sigmod/ChenDLT00","7aUag74jtdIJ")).
neg(eqo("conf/sigmod/ChenDLT00","mAQ6BedgjXQJ")).
neg(eqo("conf/sigmod/ChenGK01","AtjjFL5IdBcJ")).
neg(eqo("conf/sigmod/ChenGK01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000003/art00025")).
neg(eqo("conf/sigmod/ChenGM01","rlfxeE4k2p4J")).
neg(eqo("conf/sigmod/ChoSG00","ilJdCU_qODkJ")).
neg(eqo("conf/sigmod/Cohen98","NbU35wXNPhIJ")).
neg(eqo("conf/sigmod/ColbyGLMT96","ES56WbYJgBoJ")).
neg(eqo("conf/sigmod/ColletC95","D-ay87SsQWsJ")).
neg(eqo("conf/sigmod/ColletC95","mVUz-dIo-MoJ")).
neg(eqo("conf/sigmod/CorralMTV00","kj9zlG2nFDsJ")).
neg(eqo("conf/sigmod/CorralMTV00","url:http://portal.acm.org/citation.cfm%3Fid%3D354384.376423%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D354384%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Multimedia%2520Conference%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CranorGJSS02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CuiOTS03","5MTgNlhnyTgJ")).
neg(eqo("conf/sigmod/CuiOTS03","wsJ1nllw0KAJ")).
neg(eqo("conf/sigmod/DanS95","77mq-gn4LiAJ")).
neg(eqo("conf/sigmod/DasuJMS02","jN8ws_LDhNUJ")).
neg(eqo("conf/sigmod/DasuJMS02","tbZ0J3HLI18J")).
neg(eqo("conf/sigmod/DattaDTVSR02","krAZ7iDMEOQJ")).
neg(eqo("conf/sigmod/DavulcuFKR99","KKiefntReoUJ")).
neg(eqo("conf/sigmod/DeligiannakisR03","rKbwxobcJZYJ")).
neg(eqo("conf/sigmod/DeshpandeGR01","fPr5tKFFemIJ")).
neg(eqo("conf/sigmod/DeshpandeGR01","oAVbM_vepr8J")).
neg(eqo("conf/sigmod/DeshpandeRSN98","UEaXoXn3DicJ")).
neg(eqo("conf/sigmod/DeshpandeRSN98","zpPpdKu9z_wJ")).
neg(eqo("conf/sigmod/Deutsch95","HTvxhMKB69AJ")).
neg(eqo("conf/sigmod/DeutschFS99","GbKwENZEG40J")).
neg(eqo("conf/sigmod/DeutschFS99","q2F2htxNUCwJ")).
neg(eqo("conf/sigmod/FernandezFKLS97","biOXpzHUZR4J")).
neg(eqo("conf/sigmod/FernandezS96","9bgA6C_HqvQJ")).
neg(eqo("conf/sigmod/FlorescuLMS99","8nMpxu9m2AIJ")).
neg(eqo("conf/sigmod/French95","_6Ouz1U_RjwJ")).
neg(eqo("conf/sigmod/FukudaMMT96","_2f7zWIzK0QJ")).
neg(eqo("conf/sigmod/Galhardas00","i52ExbKAqDAJ")).
neg(eqo("conf/sigmod/GaoW02","V-qZ7eNK8AMJ")).
neg(eqo("conf/sigmod/GardarinMP95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D333608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GarofalakisRRS99","zJ6gN0riEsQJ")).
neg(eqo("conf/sigmod/Gerber95","s5Xou_NoHA0J")).
neg(eqo("conf/sigmod/GibbonsM98","yaY3OF1lVEsJ")).
neg(eqo("conf/sigmod/GoelI96","g9GbYehWeJkJ")).
neg(eqo("conf/sigmod/GoyalHKMSZ97","OcGPxRYxbsUJ")).
neg(eqo("conf/sigmod/Greer99","1dx6J3POJdMJ")).
neg(eqo("conf/sigmod/Greer99","5ObmwcHCFQsJ")).
neg(eqo("conf/sigmod/GriffinH97","E495OjIQrqkJ")).
neg(eqo("conf/sigmod/HaasH99","-iis302p2MkJ")).
neg(eqo("conf/sigmod/HammerGNYBV97","9bgA6C_HqvQJ")).
neg(eqo("conf/sigmod/HanFHCC94","_rlpIiNduaYJ")).
neg(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
neg(eqo("conf/sigmod/HanPY00","hADArm8mP0cJ")).
neg(eqo("conf/sigmod/HanWDPW02","Sy6KA50PawsJ")).
neg(eqo("conf/sigmod/HanWDPW02","bLbjFFkQJdIJ")).
neg(eqo("conf/sigmod/Hellerstein94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564788%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/HellersteinN96","zQ7jYs2fvuQJ")).
neg(eqo("conf/sigmod/HjaltasonS98","RzsJoG-0KaIJ")).
neg(eqo("conf/sigmod/ImielinskiV95","-c0YEk5L0LUJ")).
neg(eqo("conf/sigmod/JaedickeM98","9eSx_Gd0JoQJ")).
neg(eqo("conf/sigmod/Jagadish94","urKua_D0KVoJ")).
neg(eqo("conf/sigmod/JagadishJOT01","z_Y7zhQNcgAJ")).
neg(eqo("conf/sigmod/JagatheesanR03","zEqoFM380CAJ")).
neg(eqo("conf/sigmod/JoshiA01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D101082%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KanthAS98","7prk7Udu3r0J")).
neg(eqo("conf/sigmod/Keim96","Y9z1tHEoHyIJ")).
neg(eqo("conf/sigmod/Kennamer98","tQZWeE_nsa0J")).
neg(eqo("conf/sigmod/KiesslingHFE01","I8PUKJzlR8AJ")).
neg(eqo("conf/sigmod/Kim94","Aa9t5-2FNM4J")).
neg(eqo("conf/sigmod/Kim94","lnl57OhZHz8J")).
neg(eqo("conf/sigmod/KornJF97","j3gou1McdaAJ")).
neg(eqo("conf/sigmod/KornM00","KuYVVTlHVXcJ")).
neg(eqo("conf/sigmod/KornM00","aepGxosl6YoJ")).
neg(eqo("conf/sigmod/KotidisR99","ylSQWkUrmxoJ")).
neg(eqo("conf/sigmod/KoudasS03","aU7XlTpoxRgJ")).
neg(eqo("conf/sigmod/KriegelMPS01","tsPOU-H3A94J")).
neg(eqo("conf/sigmod/KrishnamurthyBN99","url:http://ieeexplore.ieee.org/iel1/2206/2685/00081889.pdf%3Farnumber%3D81889")).
neg(eqo("conf/sigmod/KrishnanVI96","zGRQ_2im_9MJ")).
neg(eqo("conf/sigmod/KuhnTS94","pE7UO9nMCZUJ")).
neg(eqo("conf/sigmod/LakshmananPZ03","pci2lDLAWzMJ")).
neg(eqo("conf/sigmod/LeeKC99","3SHIgRrrL5QJ")).
neg(eqo("conf/sigmod/LeeKC99","sfQlMM3SXpAJ")).
neg(eqo("conf/sigmod/LeflerSW96","LjrsWIr3rhAJ")).
neg(eqo("conf/sigmod/LehnerSPC00","Hc9_3eDVOpkJ")).
neg(eqo("conf/sigmod/Levine95","beuEvcUdgMMJ")).
neg(eqo("conf/sigmod/Levine95","fo_-ucVyZHgJ")).
neg(eqo("conf/sigmod/LiBCS00","dFK3q-SkTC4J")).
neg(eqo("conf/sigmod/LiBKN03","11D-BwNUPQkJ")).
neg(eqo("conf/sigmod/LiYVGPUV98","v6aIcEAaCSUJ")).
neg(eqo("conf/sigmod/LitwinS00","ffkXKk8Hkt0J")).
neg(eqo("conf/sigmod/LiuHBPT99","3tRtdT5VfDkJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97a","ZWwmBQlLFV8J")).
neg(eqo("conf/sigmod/LoR94","url:http://pubs.rsc.org/ej/CC/2002/b207661f.pdf")).
neg(eqo("conf/sigmod/LometW98","5SmDfJWfFvUJ")).
neg(eqo("conf/sigmod/Maguire01","-8kwWt7zoR8J")).
neg(eqo("conf/sigmod/Maguire01","BK7C2yvT-MwJ")).
neg(eqo("conf/sigmod/Mamoulis03","RLR4UZxPb3QJ")).
neg(eqo("conf/sigmod/Mamoulis03","url:http://portal.acm.org/citation.cfm%3Fid%3D957013.957121")).
neg(eqo("conf/sigmod/MankuRL99","LlPkfgH5fCIJ")).
neg(eqo("conf/sigmod/MankuRL99","M2bWqRDDfkUJ")).
neg(eqo("conf/sigmod/MeccaAMMS98","1_mk0EMIrwsJ")).
neg(eqo("conf/sigmod/Melling94","j4O-xhs1QAgJ")).
neg(eqo("conf/sigmod/MelnikRB03","veL-zDfjXrEJ")).
neg(eqo("conf/sigmod/Miller98","iOTlbR0LkZIJ")).
neg(eqo("conf/sigmod/MiloAABN03","B3VEtdJeSCAJ")).
neg(eqo("conf/sigmod/MinPC03","C9imFvgrSvAJ")).
neg(eqo("conf/sigmod/MinPC03","QgdyJIO3TbAJ")).
neg(eqo("conf/sigmod/Mohan99","p0wBdI_JiXMJ")).
neg(eqo("conf/sigmod/MohanN94","QEK2BsKiXBcJ")).
neg(eqo("conf/sigmod/Moore95","4aSEl4haaq4J")).
neg(eqo("conf/sigmod/Ojjeh99","1PPb2Y8X7rAJ")).
neg(eqo("conf/sigmod/OlstonW02","D1h_jOHVyA4J")).
neg(eqo("conf/sigmod/Ozsu99","okSXCoQ76_IJ")).
neg(eqo("conf/sigmod/PadmanabhanBMCH03","wI75uFSs0bwJ")).
neg(eqo("conf/sigmod/PapadopoulosM98","rC8uCIcZDrIJ")).
neg(eqo("conf/sigmod/PhanN02","vd1YI-h9WLcJ")).
neg(eqo("conf/sigmod/PoosalaIHS96","-NB01PtLzKYJ")).
neg(eqo("conf/sigmod/RadekeBBEKKN95","bDN03rZhUQEJ")).
neg(eqo("conf/sigmod/Ramakrishnan00","R2nrdEk_BGwJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","DC4Juhd354UJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","mbvAHGfVZ9EJ")).
neg(eqo("conf/sigmod/ReveszCKLLW00","nSKzTBqurCwJ")).
neg(eqo("conf/sigmod/RiedelFGN00","di9_RtTD3SMJ")).
neg(eqo("conf/sigmod/RodriguezR00","1sGr4qMsCeMJ")).
neg(eqo("conf/sigmod/RodriguezR00","f-BMhdW_E6UJ")).
neg(eqo("conf/sigmod/RoySSB00","hvtR9cqi8REJ")).
neg(eqo("conf/sigmod/SagonasSW94","4fjXoCHhe1kJ")).
neg(eqo("conf/sigmod/Sahuguet01","VT_vPPmEIEIJ")).
neg(eqo("conf/sigmod/Sahuguet01","VZ0OEyqSM44J")).
neg(eqo("conf/sigmod/Sarawagi00","H_bdYlpD79oJ")).
neg(eqo("conf/sigmod/SarawagiTA98","z5DmAoBjsjAJ")).
neg(eqo("conf/sigmod/Seshadri03","_nIg_hi8PAAJ")).
neg(eqo("conf/sigmod/ShashaB02","TLpKPgfMMcgJ")).
neg(eqo("conf/sigmod/SinghTW94","u64n4yMnma4J")).
neg(eqo("conf/sigmod/SrikantA96","Cm66C3yYtdgJ")).
neg(eqo("conf/sigmod/SrikantA96","v7i1i5y_nHgJ")).
neg(eqo("conf/sigmod/Stonebraker98","8OvGNqrl8bEJ")).
neg(eqo("conf/sigmod/Stonebraker98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/StonebrakerH01","6ussAgzdL6oJ")).
neg(eqo("conf/sigmod/StonebrakerH01","lasxhCBiPGYJ")).
neg(eqo("conf/sigmod/Team02","r5oJTEjlOPgJ")).
neg(eqo("conf/sigmod/TrisoliniLN99","NuRYi07yqLIJ")).
neg(eqo("conf/sigmod/UrhanFA98","nZO8ZA4eYzYJ")).
neg(eqo("conf/sigmod/WangTYGWP02","wJTN8d8md7oJ")).
neg(eqo("conf/sigmod/WattezCBFF00","PlitMluIJyYJ")).
neg(eqo("conf/sigmod/WhiteD95","h8WCSPS3psEJ")).
neg(eqo("conf/sigmod/WoelkBJOTU95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083786%26type%3Dpdf")).
neg(eqo("conf/sigmod/Wu99","Em19Rs4TqmIJ")).
neg(eqo("conf/sigmod/Wu99","oI-U6VfqtfcJ")).
neg(eqo("conf/sigmod/WynblattN01","M77rJKiiFwYJ")).
neg(eqo("conf/sigmod/ZhangZPTL03","6EG_etjjm7EJ")).
neg(eqo("conf/sigmod/ZhuS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D126493%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ZhuSZ03","QZs7L6Y94_UJ")).
neg(eqo("conf/vldb/AcharyaGP99","4GCzG8LIHuQJ")).
neg(eqo("conf/vldb/AgrawalCN00","_tle794_iKcJ")).
neg(eqo("conf/vldb/AgrawalK02","CKm9XhI_8k4J")).
neg(eqo("conf/vldb/AgrawalKSX02","HypA8oN4PqsJ")).
neg(eqo("conf/vldb/AgrawalS94","XK-KPRa2qjcJ")).
neg(eqo("conf/vldb/AltinelBKMPR03","wIlHF5DfRbMJ")).
neg(eqo("conf/vldb/AmielBDS94","6TzBS2n2C_EJ")).
neg(eqo("conf/vldb/ArionBCDMP03","TmcyYF1CNsYJ")).
neg(eqo("conf/vldb/BamfordBKM98","U04OC6OSBT0J")).
neg(eqo("conf/vldb/BamfordBKM98","bwDLNV_0XaYJ")).
neg(eqo("conf/vldb/BaralisPT97","ANV3iCMnGQYJ")).
neg(eqo("conf/vldb/BaulierBKS98","dNK16sHm9eUJ")).
neg(eqo("conf/vldb/Baumann03","pJ2UEKVG_hoJ")).
neg(eqo("conf/vldb/BaumannDFRW99","k3WA-AE7Sh4J")).
neg(eqo("conf/vldb/BaumannFRW97","7rJ35WBjoOAJ")).
neg(eqo("conf/vldb/BaumgartnerFG01","lhEP-ANTkfgJ")).
neg(eqo("conf/vldb/BawaBA03","ZjIllDHwkSoJ")).
neg(eqo("conf/vldb/Bayer95","W3l3pQ62_YMJ")).
neg(eqo("conf/vldb/Bayer95","fr6PXjmREQcJ")).
neg(eqo("conf/vldb/BelloDDFNSWZ98","laYa1No1nisJ")).
neg(eqo("conf/vldb/BelussiF95","KyEht2u1AwsJ")).
neg(eqo("conf/vldb/BerchtoldKK96","vmxFQL7lhKoJ")).
neg(eqo("conf/vldb/BerckenS01","j3NIm0w0xA8J")).
neg(eqo("conf/vldb/Blecken00","zu5vKMJQ_xUJ")).
neg(eqo("conf/vldb/BlottK02","Bsn9nylMcXYJ")).
neg(eqo("conf/vldb/Blum99","oNi93qMM9hgJ")).
neg(eqo("conf/vldb/Blum99","xgAaGMHEQrsJ")).
neg(eqo("conf/vldb/BohlenSS96","my4BalOLmAsJ")).
neg(eqo("conf/vldb/BouganimFV96","4bvjebYsdRkJ")).
neg(eqo("conf/vldb/Bowker00","jTVvZO4O0fgJ")).
neg(eqo("conf/vldb/BratsbergH01","SHDQQrfJ3BMJ")).
neg(eqo("conf/vldb/BrinkhoffK94","IINRwK8hovkJ")).
neg(eqo("conf/vldb/BrinkhoffK94","_5abBnDtzPgJ")).
neg(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
neg(eqo("conf/vldb/CasatiDGS01","zue36yrQxVwJ")).
neg(eqo("conf/vldb/CeriFP99","iUGa3pKj-20J")).
neg(eqo("conf/vldb/ChakrabartiDAR97","XojbAfbtdvcJ")).
neg(eqo("conf/vldb/ChangG00","rQ-X0nQkvkQJ")).
neg(eqo("conf/vldb/ChangG97","EkmUvRCP29QJ")).
neg(eqo("conf/vldb/ChaudhuriN97","4bS3tvLQ-LAJ")).
neg(eqo("conf/vldb/ChaudhuriN97","ci04dpI4WvYJ")).
neg(eqo("conf/vldb/ChaudhuriS96","TqXFdQBTW6kJ")).
neg(eqo("conf/vldb/ChaudhuriW00","zO0DfwHqXKUJ")).
neg(eqo("conf/vldb/ChawatheCY94","dXegp-RmzXEJ")).
neg(eqo("conf/vldb/ChenDZ03","E68j7SONtT4J")).
neg(eqo("conf/vldb/ChenHWW02","BNyOKJXXvDUJ")).
neg(eqo("conf/vldb/ChenRS95","D4eIIOUC1uUJ")).
neg(eqo("conf/vldb/ChoALS02","6RXMO_EQ4GMJ")).
neg(eqo("conf/vldb/ChoG00","cuQ1EnNR_1EJ")).
neg(eqo("conf/vldb/ChoenniV00","R1j3CdeOlwsJ")).
neg(eqo("conf/vldb/ChristodoulakisTZ97","jUt_LkRxJyUJ")).
neg(eqo("conf/vldb/CochranePM96","NRLEnDsPlOkJ")).
neg(eqo("conf/vldb/CosleyLP02","BTalXWt3faUJ")).
neg(eqo("conf/vldb/CuiW01","JSnG7MV0zjoJ")).
neg(eqo("conf/vldb/DattaRT99","gckQTLQjsj8J")).
neg(eqo("conf/vldb/DeRose99","aeP41XPjOVgJ")).
neg(eqo("conf/vldb/Deshpande00","2DiLFd0rgPgJ")).
neg(eqo("conf/vldb/DesslochM97","oS-ZSy84FDQJ")).
neg(eqo("conf/vldb/Draluk01","FhNjU1YhINUJ")).
neg(eqo("conf/vldb/FaloutsosJS97","IvmBi-V8RZ0J")).
neg(eqo("conf/vldb/FankhauserGLMT98","JnwUAxUMwvQJ")).
neg(eqo("conf/vldb/FerrandinaMZFM95","Ulg4PC4-auoJ")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
neg(eqo("conf/vldb/Fox02","eybUiurX77sJ")).
neg(eqo("conf/vldb/FukudaMMT96","DPzWVBnoYcQJ")).
neg(eqo("conf/vldb/GalhardasFSSS01","nlOAkKW_ry8J")).
neg(eqo("conf/vldb/Ganguly98","fRo4fx_Q6gIJ")).
neg(eqo("conf/vldb/GarciaLL98","hM920cBVn1wJ")).
neg(eqo("conf/vldb/Gawlick96","Y5OJk6_D-ZUJ")).
neg(eqo("conf/vldb/George98","TOL8CzLs984J")).
neg(eqo("conf/vldb/George98","xACnzf6RhVwJ")).
neg(eqo("conf/vldb/GeorgeH98","B7Mw8CQYZTEJ")).
neg(eqo("conf/vldb/Gibbons01","8hDo6qczOzMJ")).
neg(eqo("conf/vldb/GoldmanSVG98","c2UQ3AM5_f8J")).
neg(eqo("conf/vldb/GotoK02","8E0dpyU306cJ")).
neg(eqo("conf/vldb/GuntzerBK00","VkwdBzsEd2IJ")).
neg(eqo("conf/vldb/Guting94","LF2aUSIWko4J")).
neg(eqo("conf/vldb/HaasKU99","aDDbEmg7oYYJ")).
neg(eqo("conf/vldb/HaasNSS95","q4YYDWKhoZwJ")).
neg(eqo("conf/vldb/HammelP02","xYQmZDKjXeEJ")).
neg(eqo("conf/vldb/HeMYW03","Cf90HYwUgc8J")).
neg(eqo("conf/vldb/HellersteinNP95","5vvOcgfpjUgJ")).
neg(eqo("conf/vldb/HelmerM97","7KawVN8Kj10J")).
neg(eqo("conf/vldb/HelmerM97","xsh0C_nCllsJ")).
neg(eqo("conf/vldb/HinneburgLH03","xC2efRb-WrQJ")).
neg(eqo("conf/vldb/HoelS95","hwBMsP8-fXcJ")).
neg(eqo("conf/vldb/HumborstadSHT97","HdLCpRPEzrkJ")).
neg(eqo("conf/vldb/Huyn97","9OYLimeDdj0J")).
neg(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
neg(eqo("conf/vldb/Jacobs97","Q3csi8pRX0gJ")).
neg(eqo("conf/vldb/JaedickeM99","1NZsxf_zwF4J")).
neg(eqo("conf/vldb/JagadishMN99","xGcM9AuhrBMJ")).
neg(eqo("conf/vldb/JagadishNSSK97","DiQk_RsrwjMJ")).
neg(eqo("conf/vldb/Jamil97","A6w0vRtdzswJ")).
neg(eqo("conf/vldb/JensenL01","JjHfbnn9YowJ")).
neg(eqo("conf/vldb/JosifovskiR99","xA9KNostV4cJ")).
neg(eqo("conf/vldb/KalusD95","8Ojx7Me_oz0J")).
neg(eqo("conf/vldb/KaushikBNS02","l7glyH7ltuQJ")).
neg(eqo("conf/vldb/KemperK94","jQYEiVS0CIgJ")).
neg(eqo("conf/vldb/KemperK94","qUfWV4VVxegJ")).
neg(eqo("conf/vldb/Keogh02","-4UR6G523i0J")).
neg(eqo("conf/vldb/KerstenWFKBC03","jELnwotIy9kJ")).
neg(eqo("conf/vldb/Kiessling02","6Rn6hsdao-wJ")).
neg(eqo("conf/vldb/KietzRS97","_fF5I-bkUSQJ")).
neg(eqo("conf/vldb/Kleewein96","4xVgnSsKyn8J")).
neg(eqo("conf/vldb/KnorrN99","oCPpSbHhL3IJ")).
neg(eqo("conf/vldb/KochBG03","mZNcc1O3Nl8J")).
neg(eqo("conf/vldb/KornackerB95","a1ftVESqEVsJ")).
neg(eqo("conf/vldb/Korth95","--mfZGla0CoJ")).
neg(eqo("conf/vldb/Korth95","5SjS94w5n-gJ")).
neg(eqo("conf/vldb/Korth95","jJb2G9hkNNQJ")).
neg(eqo("conf/vldb/Korth95","qECJWgRHaKsJ")).
neg(eqo("conf/vldb/Kotidis01","lRL4LmMtwnYJ")).
neg(eqo("conf/vldb/KoudasS03","DHYgW_wrTUgJ")).
neg(eqo("conf/vldb/LabioG96","VYYKHi96iQkJ")).
neg(eqo("conf/vldb/LakshmananPH02","1I1VNEHN4jYJ")).
neg(eqo("conf/vldb/LakshmananPZ03","11D-BwNUPQkJ")).
neg(eqo("conf/vldb/LamKR02","cvBAdEvcTSkJ")).
neg(eqo("conf/vldb/LaudBCSR02","n8LgSbKmF1sJ")).
neg(eqo("conf/vldb/LeeL99","4887FNMtR0EJ")).
neg(eqo("conf/vldb/LeeLWS97","cXCXCB-8Z0gJ")).
neg(eqo("conf/vldb/LeslieJBY95","xT5O3jc7jd0J")).
neg(eqo("conf/vldb/LiC94","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/LiC94","hrHLKxM0BSYJ")).
neg(eqo("conf/vldb/LiCHPALHAY01","eSC19V7zgtsJ")).
neg(eqo("conf/vldb/LifantsevC02","HLrteP7x0doJ")).
neg(eqo("conf/vldb/LinR98","Lpg1VkCQhdAJ")).
neg(eqo("conf/vldb/LinR98","lDNAWc5SrmIJ")).
neg(eqo("conf/vldb/LingLL00","YP7qrouFTZIJ")).
neg(eqo("conf/vldb/LitwinNS94","-9bXTTM_M4cJ")).
neg(eqo("conf/vldb/LlirbatST97","v1fsWCSPn2MJ")).
neg(eqo("conf/vldb/LudascherMP02","68uHowRSGWUJ")).
neg(eqo("conf/vldb/LuoN01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601879%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/LuoNEW03","t0AE_Iti5R0J")).
neg(eqo("conf/vldb/MadhavanBR01","tTe6F_wLjGMJ")).
neg(eqo("conf/vldb/MaedaT01","dipeGpTdsoQJ")).
neg(eqo("conf/vldb/MankuM02","dkoIJqatfrsJ")).
neg(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
neg(eqo("conf/vldb/MatiasVW00","QMaKj5tjyosJ")).
neg(eqo("conf/vldb/McHughW99","97o0rfRHu9MJ")).
neg(eqo("conf/vldb/McHughW99","ZTH7OGW9FogJ")).
neg(eqo("conf/vldb/MiklauS03","aeP41XPjOVgJ")).
neg(eqo("conf/vldb/Mina98","b2x2hBSQfvoJ")).
neg(eqo("conf/vldb/Moerkotte98","bDJcfbalxoUJ")).
neg(eqo("conf/vldb/MogiK95","ybgxHuCAS_8J")).
neg(eqo("conf/vldb/Mohan01","14cgU3tAHtgJ")).
neg(eqo("conf/vldb/Mohan01","gyPwIEnKIC0J")).
neg(eqo("conf/vldb/Mohan01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373713%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/Mohan02a","enYJ_2U2NdUJ")).
neg(eqo("conf/vldb/MuthOPW98","7MULqneuph0J")).
neg(eqo("conf/vldb/NgH94","6HlejBWokfkJ")).
neg(eqo("conf/vldb/NicklasGS03","GDmbzrUbyzAJ")).
neg(eqo("conf/vldb/NicklasGS03","neYtYlQkgrYJ")).
neg(eqo("conf/vldb/NinkHR99","I03F9IwZCuwJ")).
neg(eqo("conf/vldb/Padmanabhan96","Miq6ILV7Fl0J")).
neg(eqo("conf/vldb/PalpanasSCP02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093384%26type%3Dpdf")).
neg(eqo("conf/vldb/PapadiasT01","2V2bnIgsY1kJ")).
neg(eqo("conf/vldb/PardonA00","eYiIHvpcnFQJ")).
neg(eqo("conf/vldb/PardonA00","rZJLf9oQ_hEJ")).
neg(eqo("conf/vldb/PellenkoftLK97","nLQnCYxLxFUJ")).
neg(eqo("conf/vldb/PirotteZMY94","7ZyV9ivZySQJ")).
neg(eqo("conf/vldb/PirotteZMY94","KrAyBSajhZEJ")).
neg(eqo("conf/vldb/PitouraC99","6VU-VxcDsFsJ")).
neg(eqo("conf/vldb/Pogue98","Cg8CVYNv-lQJ")).
neg(eqo("conf/vldb/RamamurthyDS02","5xe-dQqXfI8J")).
neg(eqo("conf/vldb/Ramaswamy00","nEwLN1SKensJ")).
neg(eqo("conf/vldb/RantzauCHM02","YXQd3uRooD8J")).
neg(eqo("conf/vldb/RastogiS98","AyWUeJ5k2IoJ")).
neg(eqo("conf/vldb/ReuterCGSW95","yxbj7LnTjjwJ")).
neg(eqo("conf/vldb/RohmBSS02","CWzVt5zvElUJ")).
neg(eqo("conf/vldb/Sarawagi02","1_g448rjyZUJ")).
neg(eqo("conf/vldb/SchmidtWKCMB02","CvGGYMrKR2sJ")).
neg(eqo("conf/vldb/SeligmanBNSW95","YBqFtj5_H2UJ")).
neg(eqo("conf/vldb/Selinger02","rYI3Unjq4LIJ")).
neg(eqo("conf/vldb/SevcikK96","gPvyDDUyrg4J")).
neg(eqo("conf/vldb/ShahRS02","O9A-15rmzOsJ")).
neg(eqo("conf/vldb/SilversteinBMU98","bCj7bOIqDc0J")).
neg(eqo("conf/vldb/SimonD95","hT7HpOmuztgJ")).
neg(eqo("conf/vldb/SimonD95","x70Y3qaTL40J")).
neg(eqo("conf/vldb/SizovGT03","UbQPXbPLMCAJ")).
neg(eqo("conf/vldb/SizovGT03","vqwFI9DE9jgJ")).
neg(eqo("conf/vldb/SkubiszewskiV97","3mgk6qNKT9QJ")).
neg(eqo("conf/vldb/Slutz98","CzVyfZe-kj0J")).
neg(eqo("conf/vldb/Sondag01","tAO-l_SkmSwJ")).
neg(eqo("conf/vldb/SrikantA95","21ZWY0PM8YAJ")).
neg(eqo("conf/vldb/SrikantA95","WSVs3nCRe8EJ")).
neg(eqo("conf/vldb/StillgerLMK01","9gqrE7EK8GQJ")).
neg(eqo("conf/vldb/Suciu96a","EgntjistnXQJ")).
neg(eqo("conf/vldb/Sullivan96","mxACmnKeiBwJ")).
neg(eqo("conf/vldb/TanSHCR01","004z3CTw0DEJ")).
neg(eqo("conf/vldb/TanSHCR01","AMC9N7ys24MJ")).
neg(eqo("conf/vldb/TatbulCZCS03","OXkeVhbzu-IJ")).
neg(eqo("conf/vldb/Tsur00","vHZqeBwfYL4J")).
neg(eqo("conf/vldb/Tygar98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276373%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/VermeerA96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988600%26type%3Dpdf")).
neg(eqo("conf/vldb/WangHH00","rLJSEgt6UbMJ")).
neg(eqo("conf/vldb/WangZL03","4Q1LWUvVTsIJ")).
neg(eqo("conf/vldb/WhiteheadSM97","ojEcoQCzdkMJ")).
neg(eqo("conf/vldb/WitkowskiBBFGSS03","201dEhaoIQEJ")).
neg(eqo("conf/vldb/YanA94","8j5i7YJQnNAJ")).
neg(eqo("conf/vldb/ZhouLZLZJT01","fJQ7Col2vYsJ")).
neg(eqo("conf/vldb/ZimbraoS98","SdP6nzjdq5QJ")).
neg(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03a","url:http://doi.wiley.com/10.1002/tl.102")).
neg(eqo("journals/sigmod/Aberer03d","7CLhi_LOtoUJ")).
neg(eqo("journals/sigmod/Abiteboul99","pddFB3GG6hMJ")).
neg(eqo("journals/sigmod/Aggarwal01","0KLcrS1Co_kJ")).
neg(eqo("journals/sigmod/Aggarwal01","I-taeStropMJ")).
neg(eqo("journals/sigmod/AilamakiG03","lZGtV8TM9yoJ")).
neg(eqo("journals/sigmod/AilamakiH03","VJIHPbki2uAJ")).
neg(eqo("journals/sigmod/AndlerHEMBE96","6SBwemr2zscJ")).
neg(eqo("journals/sigmod/AtzeniMM97","Dwm4JPPzVHUJ")).
neg(eqo("journals/sigmod/BargaL02","_iGkapqiXRMJ")).
neg(eqo("journals/sigmod/Bernstein98","BmV2iPuXZeMJ")).
neg(eqo("journals/sigmod/BollKB98","8CKDKUPVOnwJ")).
neg(eqo("journals/sigmod/BollKB98","FsUsuIlOKRUJ")).
neg(eqo("journals/sigmod/BonifatiC00","Fw7xITy4kZcJ")).
neg(eqo("journals/sigmod/BrunieK96","jg44bLCzUH0J")).
neg(eqo("journals/sigmod/BunemanRU97","q6YVJJgD1uQJ")).
neg(eqo("journals/sigmod/BurtonM98","qAjakY5_QAMJ")).
neg(eqo("journals/sigmod/ButtlerCCFHLPRX02","JScvAMYcsmoJ")).
neg(eqo("journals/sigmod/Cardelli01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988601%26type%3Dpdf")).
neg(eqo("journals/sigmod/CeriKKLOSV00","DwOoADL5qYkJ")).
neg(eqo("journals/sigmod/CeriKKLOSV00","Z3TQt0XDpioJ")).
neg(eqo("journals/sigmod/Cetintemel01","FzQJ4sjA7cYJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","YdgdoWFuCvoJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","fWJiFV-stmMJ")).
neg(eqo("journals/sigmod/ClementiniF00","YgouJdrCoZQJ")).
neg(eqo("journals/sigmod/ConradHHKRSS99","YNkFEhVvi0wJ")).
neg(eqo("journals/sigmod/CoxEH96","kcrWfQEI9G8J")).
neg(eqo("journals/sigmod/DadamK97","LRvwfovtPQ8J")).
neg(eqo("journals/sigmod/DadamK97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083795%26type%3Dpdf")).
neg(eqo("journals/sigmod/DoanPK95","Pa_ObVyi9TcJ")).
neg(eqo("journals/sigmod/DoanPSB97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945741%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Dogac98","TriLgFt_ETgJ")).
neg(eqo("journals/sigmod/DogacAOD95","m2TZhXciD3EJ")).
neg(eqo("journals/sigmod/DreyerDS94","eznFJ2e_pQQJ")).
neg(eqo("journals/sigmod/Eisenberg96","jux1eHt7GhQJ")).
neg(eqo("journals/sigmod/EisenbergM00","4mD1eFCHKKwJ")).
neg(eqo("journals/sigmod/EisenbergM00","rtnpqb22gGcJ")).
neg(eqo("journals/sigmod/FengJH01","uA-E1lBgLe0J")).
neg(eqo("journals/sigmod/Finkelstein95","s4PbZOOvdAQJ")).
neg(eqo("journals/sigmod/FowlerPNB99","JHVWab3P4zIJ")).
neg(eqo("journals/sigmod/FowlerPNB99","ZflHZYysWAsJ")).
neg(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","5PisY7JvbzQJ")).
neg(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","9fcJjh5vHn8J")).
neg(eqo("journals/sigmod/Franklin00b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/Franklin97","url:http://www.roc.noaa.gov/news/vol1is4.pdf")).
neg(eqo("journals/sigmod/Franklin97b","q72T2LraKw4J")).
neg(eqo("journals/sigmod/Franklin98b","VZ0OEyqSM44J")).
neg(eqo("journals/sigmod/Franklin98b","url:http://portal.acm.org/citation.cfm%3Fid%3D362084%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Gallagher94","PVm9r7wHzDAJ")).
neg(eqo("journals/sigmod/Grohe02","h0uuqAstOPUJ")).
neg(eqo("journals/sigmod/Grohe02","jzwiskpRLOUJ")).
neg(eqo("journals/sigmod/Hainaut03","i2LI1TWifbYJ")).
neg(eqo("journals/sigmod/HalkidiBV02a","egn46hGLw7gJ")).
neg(eqo("journals/sigmod/Han98","MfWZUBAVPFUJ")).
neg(eqo("journals/sigmod/Han98","_AA2qEg_o30J")).
neg(eqo("journals/sigmod/Huyn01","D1h_jOHVyA4J")).
neg(eqo("journals/sigmod/JajodiaBBKMSW97","5of4EKVXdOgJ")).
neg(eqo("journals/sigmod/JenningsNF98","rlfxeE4k2p4J")).
neg(eqo("journals/sigmod/JensenCEGHJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Jonsson03","hBp32fcRngAJ")).
neg(eqo("journals/sigmod/Kemper02","blWHtT2jE90J")).
neg(eqo("journals/sigmod/Kemper02","jQYEiVS0CIgJ")).
neg(eqo("journals/sigmod/Kim94","Ip82P4QfKyEJ")).
neg(eqo("journals/sigmod/Kim94","W34JQQUUM84J")).
neg(eqo("journals/sigmod/KokkotosIPS95","wW6dUVL80RYJ")).
neg(eqo("journals/sigmod/Kosch02","_avm808LQocJ")).
neg(eqo("journals/sigmod/LabrinidisM01","Hc9_3eDVOpkJ")).
neg(eqo("journals/sigmod/LabrinidisR00","DJfe8WSeLFAJ")).
neg(eqo("journals/sigmod/LiefkeS00","epCsER2LDJgJ")).
neg(eqo("journals/sigmod/Liu01b","T75dvUTVzMsJ")).
neg(eqo("journals/sigmod/Liu02","GbuDRP9YYosJ")).
neg(eqo("journals/sigmod/Liu02","_cil6uzFNtsJ")).
neg(eqo("journals/sigmod/Liu02a","qXiPPUqVwHwJ")).
neg(eqo("journals/sigmod/Liu02c","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu03b","KOEjbYynxl4J")).
neg(eqo("journals/sigmod/Mani03","UjWUKmJyMyYJ")).
neg(eqo("journals/sigmod/Manola98","vJAOFPT9644J")).
neg(eqo("journals/sigmod/MarchiLPT03","ED0oE7EMbZQJ")).
neg(eqo("journals/sigmod/MeersmanS02","5NE7g6XtYVkJ")).
neg(eqo("journals/sigmod/MusickC99","09nCxGk1-_cJ")).
neg(eqo("journals/sigmod/NascimentoSP03","yGpADrgW6mUJ")).
neg(eqo("journals/sigmod/NestorovAM97","XP7FEaxDfuAJ")).
neg(eqo("journals/sigmod/Neven02","HjwbHpPjvasJ")).
neg(eqo("journals/sigmod/OrlandicLS02","T4p7tzuWDx4J")).
neg(eqo("journals/sigmod/OukselS99","dGbuUkhWNhMJ")).
neg(eqo("journals/sigmod/OukselS99","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565131%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Ozsu01a","b4zoO1NrYgQJ")).
neg(eqo("journals/sigmod/PitouraAPSV03","p1mxeWp73cMJ")).
neg(eqo("journals/sigmod/Qian94a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245909%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96b","4Y125m3-bsYJ")).
neg(eqo("journals/sigmod/Qian97","ExOv1ThwJiYJ")).
neg(eqo("journals/sigmod/RamamrithamS97","8qlmryXP3BsJ")).
neg(eqo("journals/sigmod/Ritter98","IGS3TtqfKUgJ")).
neg(eqo("journals/sigmod/Ritter98","gbnxN3MpucMJ")).
neg(eqo("journals/sigmod/Rosenthal98","bP_Id4YrAjoJ")).
neg(eqo("journals/sigmod/RosenthalSMBTL95","Z6ep1mmb4A4J")).
neg(eqo("journals/sigmod/RossAKSSY00","sV_M1OKzsrcJ")).
neg(eqo("journals/sigmod/RossCGJBV99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossHLW01","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/Segev94","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Segev94a","9wQ6RWWcHRIJ")).
neg(eqo("journals/sigmod/Segev94b","_uAjDh22Y_EJ")).
neg(eqo("journals/sigmod/SmithO99","rRvcD6HKhasJ")).
neg(eqo("journals/sigmod/Snodgrass01","BkrEiSZ3mcYJ")).
neg(eqo("journals/sigmod/Snodgrass03b","l7ElxBfCtFgJ")).
neg(eqo("journals/sigmod/Snodgrass94","PmIVKWJ5_V4J")).
neg(eqo("journals/sigmod/SnodgrassGIMSU98","S4A1NDJkmCcJ")).
neg(eqo("journals/sigmod/Stonebraker02","D1sTvLkF_iQJ")).
neg(eqo("journals/sigmod/SycaraKWL99","cejTJ8s8w_0J")).
neg(eqo("journals/sigmod/Widom95a","url:http://portal.acm.org/citation.cfm%3Fid%3D219713%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom96a","M3QKdCEFIRMJ")).
neg(eqo("journals/sigmod/Winslett02a","hZOXZJ6x2xUJ")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/citation.cfm%3Fid%3D182591.182654%26dl%3DACM%26dl%3DACM%26type%3Dseries%26idx%3D182591%26part%3DProceedings%26WantType%3DProceedings%26title%3DSymposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601870%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Yang94","5tRy51B5G3MJ")).
neg(eqo("journals/sigmod/Yang94","p_k0_rphEOcJ")).
neg(eqo("journals/sigmod/YeungHL94","qS4jhfgPbm8J")).
neg(eqo("journals/tods/AmmannJR97","8svXvz9jckcJ")).
neg(eqo("journals/tods/BaekgaardM95","5DHjdE0sKzgJ")).
neg(eqo("journals/tods/BaralisW00","2R6A5QJmMPYJ")).
neg(eqo("journals/tods/CeriFPT94","R770JeqiAyYJ")).
neg(eqo("journals/tods/ChaudhuriS99","GL8XEeYm7GsJ")).
neg(eqo("journals/tods/ChoG03","ilJdCU_qODkJ")).
neg(eqo("journals/tods/CliffordDIJS97","sflWMxkOH2cJ")).
neg(eqo("journals/tods/DeySB99","rhRvVUDJg2YJ")).
neg(eqo("journals/tods/EiterLLS01","XHDfN81WKpQJ")).
neg(eqo("journals/tods/EiterLLS01","oKSKGd3yeyQJ")).
neg(eqo("journals/tods/GutingBEJLSV00","V7byawkFcZMJ")).
neg(eqo("journals/tods/Kim94","RETGb_jFnQIJ")).
neg(eqo("journals/tods/KonopnickiS98","qWp7w2u4cZEJ")).
neg(eqo("journals/tods/LechtenborgerV03","thaZWhMPxEkJ")).
neg(eqo("journals/tods/LechtenborgerV03","zI9Je52o_NEJ")).
neg(eqo("journals/tods/LiuHD98","MwrHr8gaUxIJ")).
neg(eqo("journals/tods/PolyzoisG94","IxbpxwykMXoJ")).
neg(eqo("journals/tods/ScioreSR94","fB2xVdlMTtwJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/L4H4H12200406465.pdf")).
neg(eqo("journals/tods/TaoPZ02","7HvPXnU4DB8J")).
neg(eqo("journals/tods/TaoSP03","Ft52Yx9kdnMJ")).
neg(eqo("journals/vldb/AgrawalHK03","9FLoZ2A_9XMJ")).
neg(eqo("journals/vldb/AgrawalHK03","XK-KPRa2qjcJ")).
neg(eqo("journals/vldb/AnGSVKI02","kBzZ1GUoa1AJ")).
neg(eqo("journals/vldb/ApersCS02","url:http://www.springerlink.com/index/JJJG5825415765X2.pdf")).
neg(eqo("journals/vldb/AtkinsonM95","x70Y3qaTL40J")).
neg(eqo("journals/vldb/Baumann94","BSE2se70OMYJ")).
neg(eqo("journals/vldb/BernsteinIR03","cDN9oOqsTE0J")).
neg(eqo("journals/vldb/Bertino94","ylP7n4GU-DQJ")).
neg(eqo("journals/vldb/ChakrabartiRS03","RattDSiOs7IJ")).
neg(eqo("journals/vldb/ChangG01","H4BAFnrsTbwJ")).
neg(eqo("journals/vldb/ChidlovskiiB00","vDY9LKD8scoJ")).
neg(eqo("journals/vldb/ChienTZ02","RovnC1D7mTsJ")).
neg(eqo("journals/vldb/CuiW03","aWV0Ws90BloJ")).
neg(eqo("journals/vldb/DanYC95","rhMVQzYRA6wJ")).
neg(eqo("journals/vldb/DeWittNSV96","ZJGVQVmFsZMJ")).
neg(eqo("journals/vldb/DeyBS96","_Hqit9e1SjgJ")).
neg(eqo("journals/vldb/FernandezFLS00","GukaCxN-t58J")).
neg(eqo("journals/vldb/FiletoLPAM03","VWbm4EeeFNMJ")).
neg(eqo("journals/vldb/GarofalakisOS98","ImADir74KWIJ")).
neg(eqo("journals/vldb/GibsonKR00","NcyE0pgyMUkJ")).
neg(eqo("journals/vldb/GutingS95","FBT3TKOs5KQJ")).
neg(eqo("journals/vldb/Halevy02","tZ8ckEl9UrUJ")).
neg(eqo("journals/vldb/Halevy02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D765219%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/Han98","32AYdsd8K3kJ")).
neg(eqo("journals/vldb/Han98","CZGjStvTkZUJ")).
neg(eqo("journals/vldb/HansonCDERTX98","gptavB55TnYJ")).
neg(eqo("journals/vldb/IoannidisNSS97","U3sURDcacksJ")).
neg(eqo("journals/vldb/IvesHW02","gfGSKwuJXO8J")).
neg(eqo("journals/vldb/IvesHW02","url:http://portal.acm.org/citation.cfm%3Fid%3D872757.872833%26dl%3Dportal%26dl%3DA%2520CM%26type%3Dseries%26idx%3D872757%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/KabraD99","q2F2htxNUCwJ")).
neg(eqo("journals/vldb/KornLKF00","9OYLimeDdj0J")).
neg(eqo("journals/vldb/KornLKF00","Og3OyCFeNyYJ")).
neg(eqo("journals/vldb/LeeSC01","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/08830355/2001/00000035/00000004/art00033%26unc%3D")).
neg(eqo("journals/vldb/MirbelPSTV00","E9eHIYcWjDMJ")).
neg(eqo("journals/vldb/MirbelPSTV00","OrcuRCfNJDAJ")).
neg(eqo("journals/vldb/MirbelPSTV00","UmguN2RCVtEJ")).
neg(eqo("journals/vldb/NanopoulosM02","WMRVHOa0dy8J")).
neg(eqo("journals/vldb/NanopoulosM02","zaDlTkyGASQJ")).
neg(eqo("journals/vldb/NgS98","JA55PRiwrMQJ")).
neg(eqo("journals/vldb/Ozsu03","url:http://www.springerlink.com/index/3G9E0YCGLRQFPN89.pdf")).
neg(eqo("journals/vldb/PottingerH01","Kv3ZFRUKCogJ")).
neg(eqo("journals/vldb/RamakrishnanSSS94","32NqR2_pT_UJ")).
neg(eqo("journals/vldb/RamakrishnanSSS94","Jtos3UQPkeEJ")).
neg(eqo("journals/vldb/Sarawagi01","enw6z1VV07UJ")).
neg(eqo("journals/vldb/Seshadri98","FR0smpjABLMJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","0XYRlW9tvw8J")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","Snx8LBMXFJUJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","btydMRJMBqoJ")).
neg(eqo("journals/vldb/ShethTP03","WvNsp5oCGgkJ")).
neg(eqo("journals/vldb/TenienteO95","Ns71H6psQOgJ")).
neg(eqo("journals/vldb/TsatalosSI96","I3DBXw7WWWkJ")).
neg(eqo("journals/vldb/TurkerG01","flSUunhe1Q4J")).
neg(eqo("journals/vldb/VerykiosME03","gs3RcCAyi9kJ")).
neg(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
pos(eqo("conf/sigmod/AcharyaFZ97","9OEjtHuRUzsJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","QCAu6wPhnAAJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","qdCTR7WpuFUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","a1esMNRsK_UJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","mOngiXbKrNkJ")).
pos(eqo("conf/sigmod/AcharyaPR99","KrVgTXcNPPUJ")).
pos(eqo("conf/sigmod/AfratiLU01","U8adXFUIr3EJ")).
pos(eqo("conf/sigmod/AfratiLU01","k7zpSukSfYsJ")).
pos(eqo("conf/sigmod/Agarwal96","ALk7huiKjWAJ")).
pos(eqo("conf/sigmod/Agarwal96","Fd0jPlSwFWcJ")).
pos(eqo("conf/sigmod/AggarwalY01","6i8hYEhbelEJ")).
pos(eqo("conf/sigmod/AgrawalES03","HypA8oN4PqsJ")).
pos(eqo("conf/sigmod/AgrawalES03","Wrue2IkpGyEJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","1rW7ao6gK-QJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","DHbEJyv20WMJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","UYQpDoh0wo0J")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","IgRat6Xyu2EJ")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","fm69LHjS4T0J")).
pos(eqo("conf/sigmod/AntonJLPZZ02","89P3EdEDuOEJ")).
pos(eqo("conf/sigmod/AtzeniT97","KFmRUQEedY8J")).
pos(eqo("conf/sigmod/AvnurHLORRRW98","bEu_llku9NMJ")).
pos(eqo("conf/sigmod/BabcockBDM03","RFNZUHZBP_oJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","JYHcz-HpKjEJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","nTC3FQGaT_YJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wTXunETZhPwJ")).
pos(eqo("conf/sigmod/BerchtoldBBKK97","BMkGN7AiGhYJ")).
pos(eqo("conf/sigmod/BerchtoldK97","DNVHTz7tMywJ")).
pos(eqo("conf/sigmod/BerchtoldK97","lYpquDAEzrIJ")).
pos(eqo("conf/sigmod/BergstraesserBPS99","qcZ2tYThtK0J")).
pos(eqo("conf/sigmod/BeyerR99","6Cdfxiuibd0J")).
pos(eqo("conf/sigmod/BohlenBD99","X2odIfnOC88J")).
pos(eqo("conf/sigmod/BouguettayaBH99","ER8571wXl6EJ")).
pos(eqo("conf/sigmod/BozkayaO97","9QOCoTIXz9kJ")).
pos(eqo("conf/sigmod/Brewer98","k4UNrsGeUuAJ")).
pos(eqo("conf/sigmod/BrinDG95","7mNCkZ7D-R8J")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/BrunoKS02","GahdNMZNCWgJ")).
pos(eqo("conf/sigmod/BuchmannDZH95","IU1cjdPVT6cJ")).
pos(eqo("conf/sigmod/CandanLLHA01","efYVCK07AwMJ")).
pos(eqo("conf/sigmod/Carey00","RRLtMwMOBe4J")).
pos(eqo("conf/sigmod/CareyCNVDRSM99","W6ROObWo3bIJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","GmUD1o-uPvYJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","xc1E6MOfP80J")).
pos(eqo("conf/sigmod/CareyK97","ucdmk8xwaTsJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/CarinoKKB01","p5XsTaZaGcIJ")).
pos(eqo("conf/sigmod/ChakrabartiDI98","qtVVVrzTLr4J")).
pos(eqo("conf/sigmod/Chakravarthy97","5Ng-bLUNAsQJ")).
pos(eqo("conf/sigmod/Chakravarthy97","xAwNq-a4ju0J")).
pos(eqo("conf/sigmod/Chan98","oo2mr5fbMggJ")).
pos(eqo("conf/sigmod/ChangG99","vjxJ_rBwdMkJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","D7w6TQwatE0J")).
pos(eqo("conf/sigmod/ChaudhuriN98","eHM4OCdJA9YJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","AiXOfJPvvpUJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","Y-kXztd20YQJ")).
pos(eqo("conf/sigmod/ChenJDTW00","5Trj9q_RI8YJ")).
pos(eqo("conf/sigmod/ChenJDTW00","EKNLKC2nEGwJ")).
pos(eqo("conf/sigmod/ChenJDTW00","JcnZJ-eE2XsJ")).
pos(eqo("conf/sigmod/ChenJDTW00","KlxPr0YoE_sJ")).
pos(eqo("conf/sigmod/ChenJDTW00","OsfWKJek9L8J")).
pos(eqo("conf/sigmod/CherniackZ98","_wJZsVYdrr8J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","I0KBB-n-eF8J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/ChristophidesCS00","Xssa5A6mJ1UJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","g6fFCiX6GtMJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","hEOX0Vu4-JcJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","qZppq83SJEYJ")).
pos(eqo("conf/sigmod/CranorJSS03","nHesT9ADTdEJ")).
pos(eqo("conf/sigmod/CruzALRZ97","uh2lQGa6hQUJ")).
pos(eqo("conf/sigmod/DanS95","qYsoOX4e1noJ")).
pos(eqo("conf/sigmod/DeshpandeGR01","0Ta25VSGl7kJ")).
pos(eqo("conf/sigmod/DeshpandeNGS03a","Thoke4oYLt4J")).
pos(eqo("conf/sigmod/Deutsch95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223880")).
pos(eqo("conf/sigmod/DeutschFS99","-KuX7UT0JIIJ")).
pos(eqo("conf/sigmod/DeutschFS99","SR_yVgZnYpMJ")).
pos(eqo("conf/sigmod/DeutschFS99","SYaXErlVlcAJ")).
pos(eqo("conf/sigmod/DeutschFS99","XrybyHOI16kJ")).
pos(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
pos(eqo("conf/sigmod/DeutschFS99","twQNwr-jFmoJ")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","SYV3r4_a5EsJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","fsa72WmA67kJ")).
pos(eqo("conf/sigmod/EmbleyJN99","54w4cIKL11UJ")).
pos(eqo("conf/sigmod/EmbleyJN99","x8uC_9_IzUEJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","fSKep047pbgJ")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GangulyGMS96","zeikJQZ2KM4J")).
pos(eqo("conf/sigmod/GardarinMP95","IOqPoq2MSvQJ")).
pos(eqo("conf/sigmod/GehrkeKS01","f6JFkfhawW8J")).
pos(eqo("conf/sigmod/GibbonsM98","4EgMtIywBRUJ")).
pos(eqo("conf/sigmod/GibbonsM98","7jANIPngJrIJ")).
pos(eqo("conf/sigmod/GibbonsM98","GEBNdHM0xSgJ")).
pos(eqo("conf/sigmod/GibbonsM98","HrdG_-EcnP8J")).
pos(eqo("conf/sigmod/GibbonsM98","x4HkJDEYFmYJ")).
pos(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
pos(eqo("conf/sigmod/GravanoCGP97","PsoYENGEh9cJ")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/GrayHOS96","3mFpWorR_ucJ")).
pos(eqo("conf/sigmod/GrayHOS96","92XgZkibRYwJ")).
pos(eqo("conf/sigmod/GrayHOS96","GFJeoxHwEnkJ")).
pos(eqo("conf/sigmod/GrayHOS96","OLt5pqtQf3YJ")).
pos(eqo("conf/sigmod/GrayHOS96","_pjwP11t_y8J")).
pos(eqo("conf/sigmod/GrayHOS96","jH3KeKroDfQJ")).
pos(eqo("conf/sigmod/GrayHOS96","pDjbDK0ZzsMJ")).
pos(eqo("conf/sigmod/GrayHOS96","t2B4EAmKqnAJ")).
pos(eqo("conf/sigmod/Greer99","oNPjyBZrURgJ")).
pos(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
pos(eqo("conf/sigmod/Grust02","F3sNx_8p3McJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","ASfROcKWFmgJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","VEDf7vb98i8J")).
pos(eqo("conf/sigmod/HaasH99","UHF2uPETWC8J")).
pos(eqo("conf/sigmod/HaasH99","fz1XAzoKPo0J")).
pos(eqo("conf/sigmod/HammerGNYBV97","FEWg8Ea2CycJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","pzPZuUoWej8J")).
pos(eqo("conf/sigmod/HammerGNYBV97","uPHrOdEDjlEJ")).
pos(eqo("conf/sigmod/HanPY00","63XKDNdtzp8J")).
pos(eqo("conf/sigmod/HanPY00","GlNt7w28aE8J")).
pos(eqo("conf/sigmod/HanPY00","R-ERjYdCskcJ")).
pos(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
pos(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
pos(eqo("conf/sigmod/HanPY00","rLJSEgt6UbMJ")).
pos(eqo("conf/sigmod/HanWDPW02","tcyoSdrkaRMJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","4OrM17Osz64J")).
pos(eqo("conf/sigmod/HarinarayanRU96","Qv7KYn9x-SQJ")).
pos(eqo("conf/sigmod/Hellerstein94","r4adn1YKOFIJ")).
pos(eqo("conf/sigmod/HellersteinA00","-GYSZmXrx-UJ")).
pos(eqo("conf/sigmod/HellersteinN96","5vvOcgfpjUgJ")).
pos(eqo("conf/sigmod/HernandezS95","7EYR1qDwKg0J")).
pos(eqo("conf/sigmod/HernandezS95","Al2MFiRHz9sJ")).
pos(eqo("conf/sigmod/HernandezS95","CckDkmI4U3wJ")).
pos(eqo("conf/sigmod/HernandezS95","KJyo5lhO_vAJ")).
pos(eqo("conf/sigmod/HinneburgK99","C9imFvgrSvAJ")).
pos(eqo("conf/sigmod/HinneburgKW02","VWd7jhLXfV0J")).
pos(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
pos(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
pos(eqo("conf/sigmod/JaedickeM98","Py0wIlQRPCkJ")).
pos(eqo("conf/sigmod/JagatheesanR03","InqySB8bkKkJ")).
pos(eqo("conf/sigmod/JagatheesanR03","QDqI_QZyy10J")).
pos(eqo("conf/sigmod/JajodiaSSB97","4_fm8LWVWHMJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","s3CWa_4OiW0J")).
pos(eqo("conf/sigmod/KanthAS98","4O5JTAQZf7IJ")).
pos(eqo("conf/sigmod/KanthAS98","LImRBeAtjMQJ")).
pos(eqo("conf/sigmod/KanthRA02","RgDMwqhT30wJ")).
pos(eqo("conf/sigmod/KeimK95","CWmL7TxRQ44J")).
pos(eqo("conf/sigmod/Kennamer98","RQ9qLR4St8sJ")).
pos(eqo("conf/sigmod/Kennamer98","url:http://portal.acm.org/citation.cfm%3Fid%3D276304.276373%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D276304%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","909hLNR8130J")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","DDxRgcJirBMJ")).
pos(eqo("conf/sigmod/KornJF97","o5T-Jfvv930J")).
pos(eqo("conf/sigmod/KornM00","N11b8vV9qIkJ")).
pos(eqo("conf/sigmod/KuhnTS94","JnV4W3TKPxMJ")).
pos(eqo("conf/sigmod/Kulkarni94","eN_4FTimCKYJ")).
pos(eqo("conf/sigmod/LarsonG98","tPG--ikWjGcJ")).
pos(eqo("conf/sigmod/LiBCS00","4abl38Q9iH4J")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/LitwinS00","HI2KgQdo39gJ")).
pos(eqo("conf/sigmod/LitwinS00","fx0s58TJ75EJ")).
pos(eqo("conf/sigmod/LitwinS00","qzeu5GQ_2p0J")).
pos(eqo("conf/sigmod/LiuHBPT99","BIox2W-EPfEJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","0e3PPUvtZ0MJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","3tRtdT5VfDkJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","ezlAkB7ijDUJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","1rcDwhVp-o8J")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","9Ho84Ho6xuIJ")).
pos(eqo("conf/sigmod/LoR94","3CMnzSHX7KoJ")).
pos(eqo("conf/sigmod/LometT99","JvZ9JWtn72QJ")).
pos(eqo("conf/sigmod/LometW98","QPpUo7m3A7cJ")).
pos(eqo("conf/sigmod/MaheshwariL97","1hXAkApUm3kJ")).
pos(eqo("conf/sigmod/MankuRL99","X94gDE70Zn0J")).
pos(eqo("conf/sigmod/MaratheS99","z6JEYoArZmsJ")).
pos(eqo("conf/sigmod/Martin94","ogow-Rtc3fEJ")).
pos(eqo("conf/sigmod/MerialdoAMMP00","Qq0WheHyVv8J")).
pos(eqo("conf/sigmod/Miller98","r0ZzrEjVO4UJ")).
pos(eqo("conf/sigmod/MissikoffT94","nxNSfctbGWAJ")).
pos(eqo("conf/sigmod/MohanN94","_2hj6snS3foJ")).
pos(eqo("conf/sigmod/MumickQM97","8m_6OmUvYJwJ")).
pos(eqo("conf/sigmod/MumickQM97","c_n0wQe1FhAJ")).
pos(eqo("conf/sigmod/MumickQM97","cvHvC7tUSrIJ")).
pos(eqo("conf/sigmod/Mylopoulos98","5eBjuTrKTwoJ")).
pos(eqo("conf/sigmod/Mylopoulos98","vU_Vo2059VUJ")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/citation.cfm%3Fid%3D304245%26coll%3Dportal%26dl%3DACM")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304245%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
pos(eqo("conf/sigmod/OlstonW02","pBKI-JCAlcIJ")).
pos(eqo("conf/sigmod/OriaOILY00","9SbEzfHLSooJ")).
pos(eqo("conf/sigmod/PangCL94","beMsu5ebf30J")).
pos(eqo("conf/sigmod/PoosalaIHS96","4eUqHKdkGNoJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","bvyqSciFIjcJ")).
pos(eqo("conf/sigmod/RafieiM97","Hd2lugurqEYJ")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/Rajaraman99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304246%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RamanH02","F0T3KimkbGcJ")).
pos(eqo("conf/sigmod/RamanH02","Oh2u3cZ3zJ0J")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375796%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","2i9wDNdFZM8J")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","QzW5By67KwcJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","efwTNo1wRnMJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","fKiXyCQ0LNgJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","y8Sm4Sh4hokJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","Rh68dFgQfS4J")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","UEaXoXn3DicJ")).
pos(eqo("conf/sigmod/SagonasSW94a","nDGblldnEGAJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","Klh7nU-G4-IJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","odsY0ehPPhIJ")).
pos(eqo("conf/sigmod/SarawagiTA98","0Vmsc0oib2kJ")).
pos(eqo("conf/sigmod/SarawagiTA98","SLmQWvsYtKYJ")).
pos(eqo("conf/sigmod/SchusterW01","59akjz-Qe9IJ")).
pos(eqo("conf/sigmod/SeidlK98","B8MoLkcvms4J")).
pos(eqo("conf/sigmod/SeshadriP97","f9POLlECN2gJ")).
pos(eqo("conf/sigmod/SeshadriP97","wozKEQCoZvwJ")).
pos(eqo("conf/sigmod/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/SinghTW94","uAQ-tJ0j4nkJ")).
pos(eqo("conf/sigmod/SistlaW95","KO3FcQ57_rkJ")).
pos(eqo("conf/sigmod/Spiro98","u4ZAi-DRoHkJ")).
pos(eqo("conf/sigmod/StonebrakerH01","opMsehfY-XoJ")).
pos(eqo("conf/sigmod/SzalayGKT00","2ikeMlH1BGsJ")).
pos(eqo("conf/sigmod/SzalayGKT00","zxOI0ZD8jeIJ")).
pos(eqo("conf/sigmod/TatarinovIHW01","-FOJZJj6NLEJ")).
pos(eqo("conf/sigmod/TatarinovIHW01","YiEpyN4HDEsJ")).
pos(eqo("conf/sigmod/Team95a","P-jrIizJxEgJ")).
pos(eqo("conf/sigmod/TheobaldW02","w5_HkketH-wJ")).
pos(eqo("conf/sigmod/TrisoliniLN99","cFMtMf7bLzIJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","aym35wwVDlQJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","ij8LH1U0bgQJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","w5i-zY0c1jAJ")).
pos(eqo("conf/sigmod/UrhanFA98","ufjnZovcIb4J")).
pos(eqo("conf/sigmod/WangCMSSZ94","W1IuO3EFDJ8J")).
pos(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
pos(eqo("conf/sigmod/WattezCBFF00","1SA9LhktHsUJ")).
pos(eqo("conf/sigmod/WodtkeWWDM97","XoAeyeaR-yAJ")).
pos(eqo("conf/sigmod/WodtkeWWDM97","tnXqwH3BXW0J")).
pos(eqo("conf/sigmod/WoelkBJOTU95","--PsNHvlpbIJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","19VIHSiMAXcJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","TDIVG8_n_esJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","ToumGDmKbXgJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","iFiv0xEJvIkJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","4n3d9sH99XsJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","Mib0RzjUNC0J")).
pos(eqo("conf/sigmod/WolfsonSXZC99","vwdWTx0dk7QJ")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","Pbl_CbLYKWYJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qzxeS4RQAhwJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","Mqg5svJwsCoJ")).
pos(eqo("conf/sigmod/ZhangNDLL01","ryaV3kTsJ2IJ")).
pos(eqo("conf/sigmod/ZhangRL96","46aixXBMD6sJ")).
pos(eqo("conf/sigmod/ZhangRL96","CcBKCycL0gwJ")).
pos(eqo("conf/sigmod/ZhangRL96","IVWPCLaGIPcJ")).
pos(eqo("conf/sigmod/ZhangRL96","KUGjzt-IgpoJ")).
pos(eqo("conf/sigmod/ZhangRL96","Koo3549nY2kJ")).
pos(eqo("conf/sigmod/ZhangRL96","Q4JDSTBf5_oJ")).
pos(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
pos(eqo("conf/sigmod/ZhangRL96","kBlynBey41QJ")).
pos(eqo("conf/sigmod/ZhangRL96","mbeIcD0N1rQJ")).
pos(eqo("conf/sigmod/ZhangZPTL03","S3lELcdpzTkJ")).
pos(eqo("conf/sigmod/ZhuS03","QZs7L6Y94_UJ")).
pos(eqo("conf/vldb/AbiteboulACEMM99","OYOTbj4m7JYJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/AgrawalCN00","U8CMJBaJyX8J")).
pos(eqo("conf/vldb/AgrawalCN00","jq5VkbTyBksJ")).
pos(eqo("conf/vldb/AgrawalK02","4weou-KgkM8J")).
pos(eqo("conf/vldb/AgrawalK02","5GDHzHaNiscJ")).
pos(eqo("conf/vldb/AgrawalK02","NDKJPUgy_K4J")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","LitNePng-ckJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","mB8W6em6zi8J")).
pos(eqo("conf/vldb/AgrawalPWZ95","wu8UrFu8Tu8J")).
pos(eqo("conf/vldb/AgrawalPWZ95","x_ykbVlfyP8J")).
pos(eqo("conf/vldb/AlonsoHST97","iRJV85kKVgwJ")).
pos(eqo("conf/vldb/AltinelF00","JhWxdEDCPdUJ")).
pos(eqo("conf/vldb/AltinelF00","onPj3O8mJEAJ")).
pos(eqo("conf/vldb/AmbiteKKMST01","9bzGIloFctIJ")).
pos(eqo("conf/vldb/AmbiteKKMST01","F4DtzxvVZnoJ")).
pos(eqo("conf/vldb/AnKR03","Z9dkL1yphh8J")).
pos(eqo("conf/vldb/AnciauxBBPV01","PFEvlg2DiMkJ")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/vldb/AtzeniMM97","7Ivl47egSlUJ")).
pos(eqo("conf/vldb/AtzeniMM97","GOMaqU-ZlTIJ")).
pos(eqo("conf/vldb/BalminHKPSW03","8xRHvInl0_0J")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/Bar-YossefBCFW00","-gm97JzyHJsJ")).
pos(eqo("conf/vldb/BarjaPFWD94","yXC9t87hjwsJ")).
pos(eqo("conf/vldb/BassiliadesV95","B1kJzsffXEwJ")).
pos(eqo("conf/vldb/BassiliadesV95","url:http://portal.acm.org/citation.cfm%3Fid%3D673137")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","4AcfxYXwZnIJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","Q6jRYrIlTM4J")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","h73uxQEBESwJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","62aA4DYB0MQJ")).
pos(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
pos(eqo("conf/vldb/BohannonFHRRS02","zYfyg0fCzEsJ")).
pos(eqo("conf/vldb/BohmMSW01","23cNr1EhPGwJ")).
pos(eqo("conf/vldb/BohmMSW01","Uv3mhmUGwdcJ")).
pos(eqo("conf/vldb/BonczRK98","965BXzMPxSoJ")).
pos(eqo("conf/vldb/BonczRK98","ts5vu2eNQgYJ")).
pos(eqo("conf/vldb/BouganimFV96","TiffIV1Y6AMJ")).
pos(eqo("conf/vldb/BouganimNPW03","5oXuo8dJ6qAJ")).
pos(eqo("conf/vldb/Brin95","CuCm_rmA28cJ")).
pos(eqo("conf/vldb/Brin95","ficuvb1Q0aUJ")).
pos(eqo("conf/vldb/Brin95","jXvsW6VxbMYJ")).
pos(eqo("conf/vldb/Brin95","srjTPThCwrwJ")).
pos(eqo("conf/vldb/Brin95","ytOUXklnAooJ")).
pos(eqo("conf/vldb/Brodie03","deEJ1JsF8RwJ")).
pos(eqo("conf/vldb/BrownCC94","E-1nAx7gc-8J")).
pos(eqo("conf/vldb/BrownCC94","jMku9rPCt9sJ")).
pos(eqo("conf/vldb/BrownCC94","oayI0FKl-nQJ")).
pos(eqo("conf/vldb/CareyD96","ulDUAu6vLr4J")).
pos(eqo("conf/vldb/CarinoO98","lDNAWc5SrmIJ")).
pos(eqo("conf/vldb/CarinoO98","q0LbTnnGsIsJ")).
pos(eqo("conf/vldb/ChakrabartiM00","tRBRXzjtm14J")).
pos(eqo("conf/vldb/ChangG00","H4BAFnrsTbwJ")).
pos(eqo("conf/vldb/ChaudhuriGS95","77Sb5mlyASgJ")).
pos(eqo("conf/vldb/ChaudhuriN97","g6XLqjCRkFcJ")).
pos(eqo("conf/vldb/Chawathe99","1-mxxSvIMB8J")).
pos(eqo("conf/vldb/ChenHWW02","kgXRJZKRxZQJ")).
pos(eqo("conf/vldb/CherniackZ98","So_H9Oer6lsJ")).
pos(eqo("conf/vldb/ChienVZTZ02","7gDXEIuMUIIJ")).
pos(eqo("conf/vldb/ChoALS02","_-JZT1cOuZ8J")).
pos(eqo("conf/vldb/Cluet03","faRBjw1op8YJ")).
pos(eqo("conf/vldb/CormodeKMS03","0ZQnv8tOzBwJ")).
pos(eqo("conf/vldb/CotterB00","SJ6PiY04ebMJ")).
pos(eqo("conf/vldb/DarFJST96","8OsKvVqzz58J")).
pos(eqo("conf/vldb/DarFJST96","95lS1rShpqQJ")).
pos(eqo("conf/vldb/DarFJST96","R9tpZP8C0xsJ")).
pos(eqo("conf/vldb/DarFJST96","cM4adSkCTK0J")).
pos(eqo("conf/vldb/DattaDTVRF01","mPBmOUreSecJ")).
pos(eqo("conf/vldb/DoR02","-AsVP3NqvlAJ")).
pos(eqo("conf/vldb/DongHLPW01","C_H34ddegI8J")).
pos(eqo("conf/vldb/DyresonBJ99","FkPcMtplo18J")).
pos(eqo("conf/vldb/EsterKSWX98","MC7KlhmEQt8J")).
pos(eqo("conf/vldb/EsterKSWX98","ebJMvVO8zp0J")).
pos(eqo("conf/vldb/EvangelidisLS95","3TOqLeL1G64J")).
pos(eqo("conf/vldb/EvangelidisLS95","hR9tpdTkYkcJ")).
pos(eqo("conf/vldb/FankhauserGLMT98","jGFfS5lAyLQJ")).
pos(eqo("conf/vldb/FernandezSCMS03","FjmyLJQ2TrYJ")).
pos(eqo("conf/vldb/FerrandinaMZ94","yQ2TMZ92GaIJ")).
pos(eqo("conf/vldb/FlescaFM03","LXjSnbxB7EsJ")).
pos(eqo("conf/vldb/FrohnLU94","iarLqyQmZ7IJ")).
pos(eqo("conf/vldb/Ganguly98","a8cB2S6Td-sJ")).
pos(eqo("conf/vldb/GarciaLL98","5MO7a6e0-GQJ")).
pos(eqo("conf/vldb/GardarinGT95","uMkO2KGQJwwJ")).
pos(eqo("conf/vldb/GardarinST96","BBKhPPAqasIJ")).
pos(eqo("conf/vldb/GarofalakisG01","PIhBWXtNTvUJ")).
pos(eqo("conf/vldb/GarofalakisG01","SHDQQrfJ3BMJ")).
pos(eqo("conf/vldb/GarofalakisG02","ImADir74KWIJ")).
pos(eqo("conf/vldb/GarofalakisRS99","7BITau8qhpEJ")).
pos(eqo("conf/vldb/GarofalakisRS99","Xm3ygCvkmN8J")).
pos(eqo("conf/vldb/GehrkeRG98","hobnzQKRlK4J")).
pos(eqo("conf/vldb/GoldmanSVG98","b3H6Yt4f7hAJ")).
pos(eqo("conf/vldb/GoldmanW97","_lvdMphdfvEJ")).
pos(eqo("conf/vldb/GoldsteinR00","zydIJyhwgPEJ")).
pos(eqo("conf/vldb/GrustKT03","CKiAavnrRH4J")).
pos(eqo("conf/vldb/GuptaM96","I0Kfdt6sh0gJ")).
pos(eqo("conf/vldb/GuptaM96","I83l_B0knOgJ")).
pos(eqo("conf/vldb/HaasNSS95","EfczBs13YHIJ")).
pos(eqo("conf/vldb/HasanM95","-aml_OMAQNgJ")).
pos(eqo("conf/vldb/HasanM95","JmlFFnMD_D0J")).
pos(eqo("conf/vldb/HristidisGP03","B2rShDD99xwJ")).
pos(eqo("conf/vldb/HsuLOMTX02","Px35BrWc6_EJ")).
pos(eqo("conf/vldb/IshikawaSF98","9MDCp_a1roUJ")).
pos(eqo("conf/vldb/IshikawaSF98","D1HCBThHOkcJ")).
pos(eqo("conf/vldb/IshikawaSF98","V3c_ivUAs34J")).
pos(eqo("conf/vldb/JaedickeM99","XR50nxmrvFcJ")).
pos(eqo("conf/vldb/KangC02","gndV1O-oEkMJ")).
pos(eqo("conf/vldb/KoschBBHHLRT01","xvNBOkc3UkcJ")).
pos(eqo("conf/vldb/KossmannRR02","iGlztgiSTe4J")).
pos(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
pos(eqo("conf/vldb/KriegelPS00","VSQ0v1UlIvoJ")).
pos(eqo("conf/vldb/LakshmananSS96","8sohtsoGrycJ")).
pos(eqo("conf/vldb/LakshmananSS96","Yuccv3uXgUQJ")).
pos(eqo("conf/vldb/LeeL96","tuVp_18tFv8J")).
pos(eqo("conf/vldb/LevyRO96","CWzG-HRtqZIJ")).
pos(eqo("conf/vldb/LevyRO96","biHvq8aD3_QJ")).
pos(eqo("conf/vldb/LevyRO96","e_vUPQi8-xIJ")).
pos(eqo("conf/vldb/LiC94","O0rvK0GFmBEJ")).
pos(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
pos(eqo("conf/vldb/MarianS03","JVvFcEnXBmkJ")).
pos(eqo("conf/vldb/MarronL01","a3aecJJ58NIJ")).
pos(eqo("conf/vldb/Mattos03","HeE1NxaX5t8J")).
pos(eqo("conf/vldb/MehtaD95","lRiSWgNjNtIJ")).
pos(eqo("conf/vldb/MignetMAC01","VaDXNMtPZ4oJ")).
pos(eqo("conf/vldb/MignetMAC01","XirELrPeTd4J")).
pos(eqo("conf/vldb/MignetMAC01","zLzYMIR2Ar4J")).
pos(eqo("conf/vldb/MiklauS03","cJUP6vfSm50J")).
pos(eqo("conf/vldb/MiningGroup96","fGw7o-RlqlcJ")).
pos(eqo("conf/vldb/Moerkotte98","HcCevkoobDsJ")).
pos(eqo("conf/vldb/MorimotoIM97","wkD289iFVAIJ")).
pos(eqo("conf/vldb/MoserKK95","DFZ5hU-q0BIJ")).
pos(eqo("conf/vldb/NathDKGKS03","FirBsg8jxtkJ")).
pos(eqo("conf/vldb/NathDKGKS03","ltxTkDtIbnAJ")).
pos(eqo("conf/vldb/NgY94","5e8pCA8tKKAJ")).
pos(eqo("conf/vldb/NgY94","Uny-rlVr5-MJ")).
pos(eqo("conf/vldb/NicklasGS03","zApMW7wX5-AJ")).
pos(eqo("conf/vldb/Ogawa96","my4BalOLmAsJ")).
pos(eqo("conf/vldb/Ogawa96","zQDbTpO9kH4J")).
pos(eqo("conf/vldb/PalpanasSCP02","nlh2WXZT3VIJ")).
pos(eqo("conf/vldb/PanRAMOHAMV02","F9Fe5NfpK6MJ")).
pos(eqo("conf/vldb/PapadiasMD98","_6JbypCpDqgJ")).
pos(eqo("conf/vldb/PedersenJD99","a36_v9H699oJ")).
pos(eqo("conf/vldb/PoulovassilisS94","0BMQ7HirTaUJ")).
pos(eqo("conf/vldb/RahmM95","6ioboOxJvQIJ")).
pos(eqo("conf/vldb/RahmM95","m9m0YpwaO4YJ")).
pos(eqo("conf/vldb/RamakrishnanR96","3y1e-H-FdC0J")).
pos(eqo("conf/vldb/RamanRH99","6uP3E_WEkCAJ")).
pos(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
pos(eqo("conf/vldb/RamaswamyMS98","WTYQ40Rn_tUJ")).
pos(eqo("conf/vldb/ReuterCGSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.673318")).
pos(eqo("conf/vldb/RisheYACLMVSV00","JGuPo8c_vZkJ")).
pos(eqo("conf/vldb/SadriZZA01","89l6j2Mbe2kJ")).
pos(eqo("conf/vldb/Sarawagi99","W_CVz6V80csJ")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/ScheuermannSV96","EnrllAo58CMJ")).
pos(eqo("conf/vldb/ScheuermannSV96","N3Hyyb1Qw8sJ")).
pos(eqo("conf/vldb/Selinger02","76u3c8hIWqoJ")).
pos(eqo("conf/vldb/ShaferA97","O4UcgdEM7vYJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","MSw9OnOdcVEJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","ZQyBjtpbhvIJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","_bdp5T8SSuoJ")).
pos(eqo("conf/vldb/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/vldb/ShashaB02","6nTs7QjnfDcJ")).
pos(eqo("conf/vldb/ShashaB02","url:http://portal.acm.org/citation.cfm%3Fid%3D564691.564798%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D564691%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/ShethKMWDLPLS96","vGeegEztVl8J")).
pos(eqo("conf/vldb/SubietaKL95","gEFY87Ma0XUJ")).
pos(eqo("conf/vldb/Sullivan96","zGRQ_2im_9MJ")).
pos(eqo("conf/vldb/TanSHCR01","hPcNG0tPwgIJ")).
pos(eqo("conf/vldb/TaoP02","7ZyV9ivZySQJ")).
pos(eqo("conf/vldb/TatbulCZCS03","F42wOOy-KR0J")).
pos(eqo("conf/vldb/VelegrakisMP03","gP3ld61I__kJ")).
pos(eqo("conf/vldb/VorugantiOU99","nlwMBvJt988J")).
pos(eqo("conf/vldb/Wang95","7FUOWtSbiogJ")).
pos(eqo("conf/vldb/WangC03","nXj_8Y7lmHsJ")).
pos(eqo("conf/vldb/WangHH00","qbxHq9qXVrUJ")).
pos(eqo("conf/vldb/WeikumMHZ02","W_b-Eo5VaOgJ")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/WuYCT95","uv6nMj7jEggJ")).
pos(eqo("conf/vldb/YagoubFIV00","195Hlqu94qEJ")).
pos(eqo("conf/vldb/YagoubFIV00","oHJaZrizZesJ")).
pos(eqo("conf/vldb/YangG01","UZBoDXflaXoJ")).
pos(eqo("conf/vldb/YangG01","W_35UkRxtf4J")).
pos(eqo("conf/vldb/YuPM03","sP3bZMqHmZsJ")).
pos(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
pos(eqo("conf/vldb/ZhouLZLZJT01","IqjYD8NRzR0J")).
pos(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
pos(eqo("journals/sigmod/ACT-NET96","FTDeavdkHpsJ")).
pos(eqo("journals/sigmod/Aggarwal01","JKGSOO_3GjUJ")).
pos(eqo("journals/sigmod/Aggarwal01","OE8gpNwz8MkJ")).
pos(eqo("journals/sigmod/BaaderJN97","dr4SzOhnLB8J")).
pos(eqo("journals/sigmod/BaaderJN97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D274461%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarbaraS97","l72i358_vjYJ")).
pos(eqo("journals/sigmod/BargaL02","fY3kkkzBLw8J")).
pos(eqo("journals/sigmod/BerndtssonH96","8Dj_i69XP60J")).
pos(eqo("journals/sigmod/Bertram94","qaSgL5tVq1AJ")).
pos(eqo("journals/sigmod/Bhashyam96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245908%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BohmR94","GXApzwcGl78J")).
pos(eqo("journals/sigmod/BollKB98","IBg3vuolFUwJ")).
pos(eqo("journals/sigmod/BonifatiC00","XCdMiXLp41IJ")).
pos(eqo("journals/sigmod/BorgidaCS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BrunieK96","spI2g7jFHuYJ")).
pos(eqo("journals/sigmod/BuchnerM98","dkWnTbi9xnEJ")).
pos(eqo("journals/sigmod/BuchnerM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D306124%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CeriFP99","mr8XDkQ7adAJ")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641006%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChangGKRS98","5FiyBEZ3v70J")).
pos(eqo("journals/sigmod/ChangGKRS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290607%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChaudhuriD97","1oCTwvC32jkJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","IdNPV86IxM0J")).
pos(eqo("journals/sigmod/ChaudhuriD97","oahM5itk_dAJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","zO0DfwHqXKUJ")).
pos(eqo("journals/sigmod/CheungF98","ig7B9agTOMAJ")).
pos(eqo("journals/sigmod/ChienTZ01","cjBpI3TcSWsJ")).
pos(eqo("journals/sigmod/Cingil02","2K6rhX16hXwJ")).
pos(eqo("journals/sigmod/ClementLGMK97","J7Y20fYLGbcJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","cjvOCqu3cJgJ")).
pos(eqo("journals/sigmod/CuiJO02","LIUl6zpveGQJ")).
pos(eqo("journals/sigmod/DiazJPa94","sG7PCEiN2xAJ")).
pos(eqo("journals/sigmod/DoanPSB97","fdM1W8iEk_YJ")).
pos(eqo("journals/sigmod/DogacAOD95","oUOuTMrB0esJ")).
pos(eqo("journals/sigmod/DunhamH95a","CiumYR8Q4WcJ")).
pos(eqo("journals/sigmod/Eisenberg96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245907%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Eisenberg96","yzlys0OQkt8J")).
pos(eqo("journals/sigmod/Geller02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GottlobKP03","rDRdlwdHGb0J")).
pos(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
pos(eqo("journals/sigmod/Hainaut03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959087%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Hellerstein03","5FSG85HbUygJ")).
pos(eqo("journals/sigmod/HellersteinHM03","6ussAgzdL6oJ")).
pos(eqo("journals/sigmod/HuangKL02","g4mWc14U8m4J")).
pos(eqo("journals/sigmod/HuangKL02","yyUMt1X2WXcJ")).
pos(eqo("journals/sigmod/Keim96","vkUvhZOw-1YJ")).
pos(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
pos(eqo("journals/sigmod/KlasS94","c1vjKqGLkp4J")).
pos(eqo("journals/sigmod/KuokFW98","qyXhN3CrVQ8J")).
pos(eqo("journals/sigmod/LiefkeS00","4q4PDOS45uIJ")).
pos(eqo("journals/sigmod/LiefkeS00","N0eowMtIAukJ")).
pos(eqo("journals/sigmod/Loeffen94","nSkolxxp1y0J")).
pos(eqo("journals/sigmod/LudwigG00","T7hbL2VkOhsJ")).
pos(eqo("journals/sigmod/MalaikaEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945739%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MedeirosP94","chmPCuLihZoJ")).
pos(eqo("journals/sigmod/MeltzerC98","77mq-gn4LiAJ")).
pos(eqo("journals/sigmod/MillerHHYHFP01","Zb2SExJNfkMJ")).
pos(eqo("journals/sigmod/MillerHHYHFP01","q_MyUzye5SoJ")).
pos(eqo("journals/sigmod/NascimentoSP03","G3QWq2T08SEJ")).
pos(eqo("journals/sigmod/ONeilG95","51gKshu0CWcJ")).
pos(eqo("journals/sigmod/ONeilG95","RlH2shMtkfwJ")).
pos(eqo("journals/sigmod/ONeilG95","YNkY3rC_4zQJ")).
pos(eqo("journals/sigmod/ONeilG95","ZF4UVaOvyTIJ")).
pos(eqo("journals/sigmod/Qian95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Qian96","NiswbODuzhAJ")).
pos(eqo("journals/sigmod/Qian96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245909%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RafanelliBT96","MfWZUBAVPFUJ")).
pos(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
pos(eqo("journals/sigmod/RashidS00","e0GH54HirssJ")).
pos(eqo("journals/sigmod/Richey95","2p2A5_qGf5cJ")).
pos(eqo("journals/sigmod/RossHLW01","url:http://portal.acm.org/citation.cfm%3Fid%3D1041410.1041430")).
pos(eqo("journals/sigmod/SantucciT96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245898%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ShethBS99","cqlnSEkt12EJ")).
pos(eqo("journals/sigmod/ShethGJRSWW96","V3LZdq417gsJ")).
pos(eqo("journals/sigmod/ShethGJRSWW96","ub2wqqQgD40J")).
pos(eqo("journals/sigmod/Snodgrass02b","KENWBobILMwJ")).
pos(eqo("journals/sigmod/Snodgrass03","m-l6e98xxOsJ")).
pos(eqo("journals/sigmod/SommerGB02","8l5_eKZcCh8J")).
pos(eqo("journals/sigmod/SommerGB02","fFLey-_2UM4J")).
pos(eqo("journals/sigmod/SpynsMJ02","GVrDsGpbJGsJ")).
pos(eqo("journals/sigmod/SpynsMJ02","QWfa2xEybLcJ")).
pos(eqo("journals/sigmod/SpynsMJ02","jD6nDNmhP3AJ")).
pos(eqo("journals/sigmod/Stonebraker02","0HMk-YUh4i8J")).
pos(eqo("journals/sigmod/Stonebraker94","url:http://portal.acm.org/citation.cfm%3Fid%3D181551")).
pos(eqo("journals/sigmod/Suciu02","Ikk1rb4o66UJ")).
pos(eqo("journals/sigmod/TatarinovIMHSDDKMM03","0JPhnHlRGOoJ")).
pos(eqo("journals/sigmod/VetterliVS00","dAF5Z861mZgJ")).
pos(eqo("journals/sigmod/Weikum02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601867%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Wiegand02","RAcoVQuEzD8J")).
pos(eqo("journals/sigmod/YuenCLL00","Ip82P4QfKyEJ")).
pos(eqo("journals/tods/AmmannJR97","2e-NAgqt-joJ")).
pos(eqo("journals/tods/BellNNS96","pz2VRTdXq1cJ")).
pos(eqo("journals/tods/CasatiCPP99","b6-zHfA02TgJ")).
pos(eqo("journals/tods/CasatiCPP99","bWa_AKkBbn8J")).
pos(eqo("journals/tods/CeriFPT94","39m5BLDo1zYJ")).
pos(eqo("journals/tods/CeriFPT94","tyaWVyKPyw0J")).
pos(eqo("journals/tods/DeyS96","Jfo57_VwkfUJ")).
pos(eqo("journals/tods/DeyS96","uZVc1wSi3y4J")).
pos(eqo("journals/tods/FormicaGM98","PtcmzsfKYrsJ")).
pos(eqo("journals/tods/FukudaMMT01","k6ukzru4nX8J")).
pos(eqo("journals/tods/FukudaMMT01","sOBRaiLLvZgJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","vMVuIqz5BiwJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","5cAIVZJShAEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("journals/tods/Jimenez-PerisPAK03","gcTZH6tRjXIJ")).
pos(eqo("journals/tods/Kim94","url:http://portal.acm.org/citation.cfm%3Fid%3D202106.569784%26coll%3Dportal%26dl%3DACM%26idx%3DJ777%26part%3Dtransaction%26WantType%3Dtransaction%26title%3DACM%2520Transactions%2520on%2520Database%2520Systems%2520(TODS)%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
pos(eqo("journals/tods/LitwinN96","d7by8a0ArhIJ")).
pos(eqo("journals/tods/LitwinN96","l0W27c1C3NwJ")).
pos(eqo("journals/tods/LitwinN96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093386%26type%3Dpdf")).
pos(eqo("journals/tods/PetersO97","er0r8doAGUQJ")).
pos(eqo("journals/tods/StolboushkinT98","ZnWLup8HMkUJ")).
pos(eqo("journals/tods/Subrahmanian94","KnKwXVSXN_wJ")).
pos(eqo("journals/tods/TaoSP03","FBp7oibu4ygJ")).
pos(eqo("journals/tods/TendickM94","FxCxfE4m1rUJ")).
pos(eqo("journals/tods/WandSW99","pYtOkFSgdXYJ")).
pos(eqo("journals/tods/WolfsonJH97","lcqKNOEczxsJ")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/vldb/AntoshenkovZ96","N8syKKPN6IoJ")).
pos(eqo("journals/vldb/BarbaraI95","7N0H3ra1FFsJ")).
pos(eqo("journals/vldb/BarbaraI95","kooQijVBMscJ")).
pos(eqo("journals/vldb/BerendtS00","nm9rCU6yVNwJ")).
pos(eqo("journals/vldb/ChanGR03","7rn7AHVs1YUJ")).
pos(eqo("journals/vldb/ChanGR03","wUcXmf9G52gJ")).
pos(eqo("journals/vldb/ChienTZ02","j4wcclZqY0oJ")).
pos(eqo("journals/vldb/DesslochHMMT98","4D2HQE6fXXEJ")).
pos(eqo("journals/vldb/GarofalakisOS98","byJ0lVRijnkJ")).
pos(eqo("journals/vldb/GutingS95","CBHicx5w3ocJ")).
pos(eqo("journals/vldb/GutingS95","ae7u4oyTu80J")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/HalkidiNVV03","J0hrpRuvSgMJ")).
pos(eqo("journals/vldb/HalkidiNVV03","tFe0FjHYe2MJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","T1c1QfSdUVQJ")).
pos(eqo("journals/vldb/KabraD99","UAxAXYysL-UJ")).
pos(eqo("journals/vldb/KellerB96","XTnTJ3s9yr0J")).
pos(eqo("journals/vldb/KellerB96","Y5-Iqr5NcY8J")).
pos(eqo("journals/vldb/KieslingSSD94","bvFRYOianJUJ")).
pos(eqo("journals/vldb/LaurentLSV01","TTIgIh9uC_YJ")).
pos(eqo("journals/vldb/Li03","XkdLpQ5x-YIJ")).
pos(eqo("journals/vldb/LometS97","5EjrRrS54fsJ")).
pos(eqo("journals/vldb/LometS97","o4XsUOzknMUJ")).
pos(eqo("journals/vldb/NgS98","8vJEjrhM7foJ")).
pos(eqo("journals/vldb/OoiHLT96","EclgEUrqHQAJ")).
pos(eqo("journals/vldb/OzsuPSILM95","gld2wLKYWpsJ")).
pos(eqo("journals/vldb/PacittiS00","9ReaNbX2I-IJ")).
pos(eqo("journals/vldb/RamamohanaraoH94","UiWvxN_y9SAJ")).
pos(eqo("journals/vldb/Sarawagi01","Xx6kw0tCeQIJ")).
pos(eqo("journals/vldb/ScheuermannWZ98","Q_JRmsXFEM4J")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","HKM-zP0LT_UJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","MSw9OnOdcVEJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","QOf55i6m6bUJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","ZQyBjtpbhvIJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","_bdp5T8SSuoJ")).
pos(eqo("journals/vldb/SheikholeslamiCZ00","eFgoWIVr71IJ")).
pos(eqo("journals/vldb/ShethTP03","Svbxes_XzdUJ")).
pos(eqo("journals/vldb/SofferS98","miubKxLrikUJ")).
pos(eqo("journals/vldb/SuHHHLWLPLL01","GRzquCzL_OUJ")).
pos(eqo("journals/vldb/SuHHHLWLPLL01","xcRKDHBIUb8J")).
pos(eqo("journals/vldb/SwamiS95","S6TmnZKgmxwJ")).
pos(eqo("journals/vldb/TurkerG01","Jab63JLU3N0J")).
