neg(eqo("conf/sigmod/AbadiC02","-ZB0n4P2DDIJ")).
neg(eqo("conf/sigmod/AcharyaAFZ95","eYabDtrkXaYJ")).
neg(eqo("conf/sigmod/AcharyaAFZ95","rO4-yA3tlfoJ")).
neg(eqo("conf/sigmod/AcharyaGPR99a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141831%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/AcharyaPR99","0dY1brFaEzgJ")).
neg(eqo("conf/sigmod/AcharyaPR99","Qmv55n1HpkAJ")).
neg(eqo("conf/sigmod/AcharyaPR99","gKOsM57uFB4J")).
neg(eqo("conf/sigmod/AdelbergGK95","JrU1gnfH1sYJ")).
neg(eqo("conf/sigmod/AdyaGLM95","EP8u32KwMe4J")).
neg(eqo("conf/sigmod/AdyaGLM95","q_A8Y8KY9WkJ")).
neg(eqo("conf/sigmod/Aggarwal02","ewnL82c8kiMJ")).
neg(eqo("conf/sigmod/Aggarwal02","tKeGALC3uFMJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","Bn8s7u5T9SAJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","bKp266-v6gUJ")).
neg(eqo("conf/sigmod/AggarwalWY99","1_sc8sGtQQYJ")).
neg(eqo("conf/sigmod/AggarwalY00","url:http://www.springerlink.com/index/U1K1UFAD34N3XXVT.pdf")).
neg(eqo("conf/sigmod/AgrawalCN01","5FJjEO5B31AJ")).
neg(eqo("conf/sigmod/AgrawalES03","DN2VfNy0oecJ")).
neg(eqo("conf/sigmod/AgrawalGGR98","UYQpDoh0wo0J")).
neg(eqo("conf/sigmod/AgrawalGGR98","url:http://portal.acm.org/citation.cfm%3Fid%3D1027641")).
neg(eqo("conf/sigmod/AgrawalK03","A5qgqEDykVwJ")).
neg(eqo("conf/sigmod/AgrawalK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083795%26type%3Dpdf")).
neg(eqo("conf/sigmod/AgrawalW00","-ha8fD8Kj_oJ")).
neg(eqo("conf/sigmod/AndersonBKW98","0J9hku6q20cJ")).
neg(eqo("conf/sigmod/Atkinson95","url:http://portal.acm.org/citation.cfm%3Fid%3D223874")).
neg(eqo("conf/sigmod/Aulakh98","xFK4CkKj14EJ")).
neg(eqo("conf/sigmod/BabyCY01","ZqFPwDkLN7oJ")).
neg(eqo("conf/sigmod/BarbaraI94","a7v0bHRrpjMJ")).
neg(eqo("conf/sigmod/BargaL99","hf84fEpX5agJ")).
neg(eqo("conf/sigmod/BaulierBGGHJKKMMNNRSSSWW99","zo5i5LKtKHEJ")).
neg(eqo("conf/sigmod/Bayardo98","9sBMwTQGbmoJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","1BUzNx9y9SIJ")).
neg(eqo("conf/sigmod/BergstraesserBPS99","CE5YSzlMeTIJ")).
neg(eqo("conf/sigmod/BersonGMJ94","bV8_CDuW2gMJ")).
neg(eqo("conf/sigmod/BertinoCF01","Ar4BO3p42CcJ")).
neg(eqo("conf/sigmod/BreunigKKS01","EKqpEdn3kDMJ")).
neg(eqo("conf/sigmod/BrinMS97","OiHYG-Al8G8J")).
neg(eqo("conf/sigmod/BrinkhoffKSS94a","EnycLFKkzpUJ")).
neg(eqo("conf/sigmod/Brown99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D1664587CI")).
neg(eqo("conf/sigmod/Cabrera03","FJoxML30MmkJ")).
neg(eqo("conf/sigmod/CallanCD99","zs9d5ynKmXMJ")).
neg(eqo("conf/sigmod/CarinoKKB01","8bcTG9YsbskJ")).
neg(eqo("conf/sigmod/ChangH02","xxp4Im8OG9AJ")).
neg(eqo("conf/sigmod/Chaudhuri97","oHdZmd_4AaAJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","g6XLqjCRkFcJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","urOf37FreHwJ")).
neg(eqo("conf/sigmod/ChaudhuriKN03","0rViZf2YXmAJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","Tagq11E6HfAJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","hNwdALHnVGQJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","tsQbSCfQTooJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","wC5sfkAhms8J")).
neg(eqo("conf/sigmod/ChenRW02","CER66z1lh0MJ")).
neg(eqo("conf/sigmod/ChoG00","s7K6rICx3fkJ")).
neg(eqo("conf/sigmod/ChoiC02","XabEiBSE1WMJ")).
neg(eqo("conf/sigmod/ChristophidesCM96","GpGg0czXSQcJ")).
neg(eqo("conf/sigmod/ChristophidesCS00","GpGg0czXSQcJ")).
neg(eqo("conf/sigmod/ChristophidesCS00","wOEzWDOEIjwJ")).
neg(eqo("conf/sigmod/ColbyKLMR97","Tw8-f4saqb0J")).
neg(eqo("conf/sigmod/Cotton02","mClzTQppJE4J")).
neg(eqo("conf/sigmod/DarR94","7HN2VSn735sJ")).
neg(eqo("conf/sigmod/DarR94","jxSoIrEY21EJ")).
neg(eqo("conf/sigmod/DeligiannakisR03","t3GxPAGPqDoJ")).
neg(eqo("conf/sigmod/Deutsch95","w-G8RpKFnVAJ")).
neg(eqo("conf/sigmod/Ellison95","AgpGguTHfGsJ")).
neg(eqo("conf/sigmod/FaginKS03","sEwpr2jGK1sJ")).
neg(eqo("conf/sigmod/FaloutsosSTT00","ZXB1xI2h-HkJ")).
neg(eqo("conf/sigmod/Fegaras98","2L79Kz4nDmkJ")).
neg(eqo("conf/sigmod/FlorescuLMS99","MuZnT5oVElQJ")).
neg(eqo("conf/sigmod/FukudaMMT96","Y8UdbAPhYpUJ")).
neg(eqo("conf/sigmod/FukudaMMT96","s9hhR-EdDGgJ")).
neg(eqo("conf/sigmod/Galhardas00","lNOI5c435a4J")).
neg(eqo("conf/sigmod/GaoW02","IQ_MbfJGh0kJ")).
neg(eqo("conf/sigmod/GardarinMP95","VOxehNSHEWQJ")).
neg(eqo("conf/sigmod/GarofalakisG02","ovF40iPyEqUJ")).
neg(eqo("conf/sigmod/GarofalakisI96","5Trj9q_RI8YJ")).
neg(eqo("conf/sigmod/GibbonsM98","2k9bgRJC-hYJ")).
neg(eqo("conf/sigmod/GibbonsM98","YL1K_N6Jn-4J")).
neg(eqo("conf/sigmod/GionisGK01","bMlT78VM_iMJ")).
neg(eqo("conf/sigmod/GrayHOS96","R7k9puhsrScJ")).
neg(eqo("conf/sigmod/GrayHOS96","iKmQWoUYl-0J")).
neg(eqo("conf/sigmod/GrossmanQ94","u_9TTQd-iT0J")).
neg(eqo("conf/sigmod/HammerGNYBV97","ahrxo47nJtMJ")).
neg(eqo("conf/sigmod/HanPY00","YkKV8PCox8IJ")).
neg(eqo("conf/sigmod/HanWDPW02","v9BdA55u_XMJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","QHUtoLECZzgJ")).
neg(eqo("conf/sigmod/Hellerstein94","Nn0LzB8rUPEJ")).
neg(eqo("conf/sigmod/HellersteinA00","Gsb6dnkFBMoJ")).
neg(eqo("conf/sigmod/HellersteinHW97","6ussAgzdL6oJ")).
neg(eqo("conf/sigmod/HillyerS96","e_vUPQi8-xIJ")).
neg(eqo("conf/sigmod/HjaltasonS98","Kw-JxYkuxdkJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","MdMdCC38z4UJ")).
neg(eqo("conf/sigmod/Jagadish94","h0uuqAstOPUJ")).
neg(eqo("conf/sigmod/Jamil99","c0D02SzWH9MJ")).
neg(eqo("conf/sigmod/JonssonFS98","J7Y20fYLGbcJ")).
neg(eqo("conf/sigmod/KalnisNOPT02","SUDBjtdzV1MJ")).
neg(eqo("conf/sigmod/KaushikBNK02","-NzSdQ84uY0J")).
neg(eqo("conf/sigmod/Kennamer98","url:http://portal.acm.org/citation.cfm%3Fid%3D276304.276373%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D276304%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KimC03","3IFlpeKgLlAJ")).
neg(eqo("conf/sigmod/KimCK01","egc4wGonDjwJ")).
neg(eqo("conf/sigmod/KornM00","HlhXdvHzlvwJ")).
neg(eqo("conf/sigmod/KoudasS97","0u8r8MJWgKAJ")).
neg(eqo("conf/sigmod/KoudasS97","C9gekNV3XgYJ")).
neg(eqo("conf/sigmod/Kramer97","JxP-0xYMRUMJ")).
neg(eqo("conf/sigmod/Kramer97","rNVPCLfguuMJ")).
neg(eqo("conf/sigmod/LarsonG98","QmBz3hMOFh4J")).
neg(eqo("conf/sigmod/LazaridisM01","e6llu4bIOxUJ")).
neg(eqo("conf/sigmod/LiBKN03","micx2kyGfKIJ")).
neg(eqo("conf/sigmod/LiuHBPT99","PKQ1dCQIwi0J")).
neg(eqo("conf/sigmod/LiuPTBBZBHY98","bF9t6EpjL14J")).
neg(eqo("conf/sigmod/MaddenSHR02","elxOZKWuSAsJ")).
neg(eqo("conf/sigmod/MerialdoAMMP00","Eczpw2rzarkJ")).
neg(eqo("conf/sigmod/MiloAABN03","uexel5Cdu4wJ")).
neg(eqo("conf/sigmod/MinPC03","pScXi8veb-oJ")).
neg(eqo("conf/sigmod/Mohan01","m9ZL9DoH17YJ")).
neg(eqo("conf/sigmod/Mohan99","C-yzbvoAg00J")).
neg(eqo("conf/sigmod/MoonWH02","WGWZ2cNZW2YJ")).
neg(eqo("conf/sigmod/MorpainCFP96","eQjFv7QxsQQJ")).
neg(eqo("conf/sigmod/NatsevRS99","MBtC3DSeJmYJ")).
neg(eqo("conf/sigmod/ONeilQ97","rN34VXyq84YJ")).
neg(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565119%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/OlstonJW03","Sg5UhqcDrS0J")).
neg(eqo("conf/sigmod/OlstonJW03","mr8XDkQ7adAJ")).
neg(eqo("conf/sigmod/OlstonW02","1ZkeBqSLAkcJ")).
neg(eqo("conf/sigmod/OlstonWACELSS98","tzmaIcLn5gsJ")).
neg(eqo("conf/sigmod/PadmanabhanBMCH03","wI75uFSs0bwJ")).
neg(eqo("conf/sigmod/PangCL94","SBKjIGdxMM0J")).
neg(eqo("conf/sigmod/PapakonstantinouV99","uMYecZGSCv4J")).
neg(eqo("conf/sigmod/ParkCY95","XZgDbb1XypMJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083795%26type%3Dpdf")).
neg(eqo("conf/sigmod/PonnekantiK00","Sn5j6HJ-bA8J")).
neg(eqo("conf/sigmod/QuassW97","3o4t-svHQfcJ")).
neg(eqo("conf/sigmod/QuassWGHLMNRRAUW96","y_3TQGFQ_H0J")).
neg(eqo("conf/sigmod/RafieiM97","LSWVPfB8TC4J")).
neg(eqo("conf/sigmod/Ramanan02","Pk09A5EmsOoJ")).
neg(eqo("conf/sigmod/Ramanan02","eU67ssiJ9GYJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","bE9NgyKXDBAJ")).
neg(eqo("conf/sigmod/RaoR98","uHX7_KIw8uYJ")).
neg(eqo("conf/sigmod/ReissK03","LNZ04qjRN7oJ")).
neg(eqo("conf/sigmod/RiedewaldAA02","nQvBo5KHITYJ")).
neg(eqo("conf/sigmod/RoySSB00","AJ7Qj_bt0ZoJ")).
neg(eqo("conf/sigmod/RoySSB00","t4qJ1rlU01sJ")).
neg(eqo("conf/sigmod/RundensteinerWYD02","-OjxUjTen2QJ")).
neg(eqo("conf/sigmod/SagonasSW94","uAoWmK-jEGAJ")).
neg(eqo("conf/sigmod/SagonasSW94a","uAoWmK-jEGAJ")).
neg(eqo("conf/sigmod/SalemBCL00","wRVEXN3YXD0J")).
neg(eqo("conf/sigmod/SchleimerWA03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083799%26type%3Dpdf")).
neg(eqo("conf/sigmod/SeshadriLR94","XvKzOSXKGKUJ")).
neg(eqo("conf/sigmod/ShahC01","7ML1mmPqIooJ")).
neg(eqo("conf/sigmod/ShanmugasundaramNSR99","Pbjz4-UPrZ8J")).
neg(eqo("conf/sigmod/Shasha97","Q-KG8a3_BmIJ")).
neg(eqo("conf/sigmod/Shasha97","s8ZGD0r4M0wJ")).
neg(eqo("conf/sigmod/Sheth95","m-dE1QSz3LAJ")).
neg(eqo("conf/sigmod/Shivakumar03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641006%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ShivakumarG97","SrCBkHnIFL8J")).
neg(eqo("conf/sigmod/SlivinskasJS01","ea4aEaV4ikUJ")).
neg(eqo("conf/sigmod/Squire95","Fv8XJKV0XG8J")).
neg(eqo("conf/sigmod/Squire95","ery6k1e8h_sJ")).
neg(eqo("conf/sigmod/Stonebraker03","0s68uZWLQogJ")).
neg(eqo("conf/sigmod/Stonebraker03","ALsywYLSDOcJ")).
neg(eqo("conf/sigmod/Stonebraker98","ZflHZYysWAsJ")).
neg(eqo("conf/sigmod/Stonebraker98","lasxhCBiPGYJ")).
neg(eqo("conf/sigmod/SzalayGKT00","NwxpeiAlEmcJ")).
neg(eqo("conf/sigmod/TatarinovVBSSZ02","jD6nDNmhP3AJ")).
neg(eqo("conf/sigmod/Team95b","qq2lTNrNTBUJ")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","ifOM4z6uxXUJ")).
neg(eqo("conf/sigmod/TomasicGS94","n8krnsf_y30J")).
neg(eqo("conf/sigmod/Ubell94","3kiGwvDkkJUJ")).
neg(eqo("conf/sigmod/Ubell94","W00kENZKPR0J")).
neg(eqo("conf/sigmod/Ullman03","1j5AKUwRFK8J")).
neg(eqo("conf/sigmod/Ullman03","EKqpEdn3kDMJ")).
neg(eqo("conf/sigmod/WhiteCF98","tORqjZEtKvMJ")).
neg(eqo("conf/sigmod/WilschutFA95","vgoFTdXYHZ0J")).
neg(eqo("conf/sigmod/WitkowskiBBDFGSS03","ygCe1xRFuKgJ")).
neg(eqo("conf/sigmod/Wu99","1S-vlkBOdmkJ")).
neg(eqo("conf/sigmod/YuMWL01","xv0Zt25NSBwJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","JYYcPQLrBw8J")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","TOXrbhbbNJ4J")).
neg(eqo("conf/sigmod/ZhouR02","-hUVSdRv5UUJ")).
neg(eqo("conf/vldb/Adler01","y4_VKQwHk88J")).
neg(eqo("conf/vldb/AilamakiDHW99","cVgF0jn9q6MJ")).
neg(eqo("conf/vldb/AilamakiDHW99","gsPFCGACgtEJ")).
neg(eqo("conf/vldb/AksoyZF01","3Vd-HExv4gsJ")).
neg(eqo("conf/vldb/AksoyZF01","nOF-SuSEaaEJ")).
neg(eqo("conf/vldb/AlonsoHST97","iRJV85kKVgwJ")).
neg(eqo("conf/vldb/AltinelF00","w7ZbYeKbLlYJ")).
neg(eqo("conf/vldb/AmirKN01","oeMU1XoJSesJ")).
neg(eqo("conf/vldb/AmmannJR95","2e-NAgqt-joJ")).
neg(eqo("conf/vldb/AnSVKIG01","CETFNYmi9S0J")).
neg(eqo("conf/vldb/ArgePRSV98","GH3UmB-SLb0J")).
neg(eqo("conf/vldb/Banerjee00","kFQl7LX8OQkJ")).
neg(eqo("conf/vldb/Baru96","url:http://portal.acm.org/citation.cfm%3Fid%3D171926.171941")).
neg(eqo("conf/vldb/BaumgartnerFG01","8DRB_dYz2CgJ")).
neg(eqo("conf/vldb/BawaBA03","ZN5RvepdJFgJ")).
neg(eqo("conf/vldb/BelloDDFNSWZ98","mgyKBoeLNS4J")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","url:http://portal.acm.org/citation.cfm%3Fid%3D335168.335220%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D335168%26part%3DProceedings%26WantType%3DProceedings%26title%3DSymposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/BerckenS01","BJ8i-uzFQi4J")).
neg(eqo("conf/vldb/BohlenSS96","0XWjlzHVMdMJ")).
neg(eqo("conf/vldb/Brin95","gOuz-7q2rRUJ")).
neg(eqo("conf/vldb/BrownCC94","K1o894GE6S0J")).
neg(eqo("conf/vldb/CareyD96","5xe-dQqXfI8J")).
neg(eqo("conf/vldb/CarneyCZRCS03","y5h2qhOGUSgJ")).
neg(eqo("conf/vldb/CatozziR01","9MlAuURfKhYJ")).
neg(eqo("conf/vldb/ChakrabartiRS02","ksMnxMtMViQJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","-2Ib1nqgXbcJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","idfox84uNHUJ")).
neg(eqo("conf/vldb/ChandrasekaranF02","EMq1-Lnb-3oJ")).
neg(eqo("conf/vldb/ChandrasekaranF02","nqosSM46lCkJ")).
neg(eqo("conf/vldb/ChangG97","nMt5JG_iuVAJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","ClO4zHQ7RYsJ")).
neg(eqo("conf/vldb/ChaudhuriN97","QCFUIVkspywJ")).
neg(eqo("conf/vldb/ChaudhuriS94","QkyXMep2bWsJ")).
neg(eqo("conf/vldb/ChaudhuriS94","bd-Lu1jeg-AJ")).
neg(eqo("conf/vldb/ChaudhuriS96","AiXOfJPvvpUJ")).
neg(eqo("conf/vldb/ChaudhuriS96","yESwE-_dXAkJ")).
neg(eqo("conf/vldb/ChaudhuriW00","JyEX0YVMP5oJ")).
neg(eqo("conf/vldb/ChaudhuriW00","hAqEljGAcFsJ")).
neg(eqo("conf/vldb/CherniackFZ01","49EWG8vzsXUJ")).
neg(eqo("conf/vldb/CherniackFZ01","4KgGF3UJxvYJ")).
neg(eqo("conf/vldb/ChirkovaHS01","iM6vRWljKpAJ")).
neg(eqo("conf/vldb/ChoG00","p8GcBA1zfXsJ")).
neg(eqo("conf/vldb/CohenMKS03","gRoNHWLN1WMJ")).
neg(eqo("conf/vldb/DeWittKLPY94","1cAIQfWLoG8J")).
neg(eqo("conf/vldb/DeWittKLPY94","MfcO8Tf1h5QJ")).
neg(eqo("conf/vldb/DeutschPT99","v8PaKd-M2-AJ")).
neg(eqo("conf/vldb/DingGS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344819%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/DoR02","bey6io4rYbgJ")).
neg(eqo("conf/vldb/DongHLPW01","dRemTC899xcJ")).
neg(eqo("conf/vldb/DonjerkovicR99","0AGITJqfktsJ")).
neg(eqo("conf/vldb/Draluk01","Axu6UlX-pPYJ")).
neg(eqo("conf/vldb/Draluk01","FhNjU1YhINUJ")).
neg(eqo("conf/vldb/Duranti01","gQW6iYG5Vh0J")).
neg(eqo("conf/vldb/EvangelidisLS95","hR9tpdTkYkcJ")).
neg(eqo("conf/vldb/FaloutsosG96","u_9qWSpjaO4J")).
neg(eqo("conf/vldb/FaloutsosJS97","IWZsSVPC6HMJ")).
neg(eqo("conf/vldb/FaloutsosMS96","RLjlTtFM36IJ")).
neg(eqo("conf/vldb/FegarasE01","4fN0QEu0KeAJ")).
neg(eqo("conf/vldb/Fox02","_jKcq80n8uIJ")).
neg(eqo("conf/vldb/FuC94","1hazaAEoGTAJ")).
neg(eqo("conf/vldb/FuhDCMTLDRM99","YJEUk3qvVD0J")).
neg(eqo("conf/vldb/GallersdorferN95","k_O40ldI0LgJ")).
neg(eqo("conf/vldb/GarofalakisI97","mSFixV8XNwYJ")).
neg(eqo("conf/vldb/GarofalakisI97","zJ6gN0riEsQJ")).
neg(eqo("conf/vldb/GarofalakisRS99","nqosSM46lCkJ")).
neg(eqo("conf/vldb/GehaniJR94","e43IB-oHaQgJ")).
neg(eqo("conf/vldb/GehrkeRG98","XCP3p-Hk8bMJ")).
neg(eqo("conf/vldb/Gibbons01","A_fR7k2IVgsJ")).
neg(eqo("conf/vldb/GoldmanSVG98","b3H6Yt4f7hAJ")).
neg(eqo("conf/vldb/GoldmanW97","jkg7MvHFHQUJ")).
neg(eqo("conf/vldb/GottlobKP02","RovnC1D7mTsJ")).
neg(eqo("conf/vldb/GoyalHSS95","puxBXWQMfNcJ")).
neg(eqo("conf/vldb/GravanoIJKMS01","dkdyz41-JesJ")).
neg(eqo("conf/vldb/GravanoIJKMS01","iAYjhuQV_qMJ")).
neg(eqo("conf/vldb/GuPS00","atMH7HI0kgIJ")).
neg(eqo("conf/vldb/Gupta96","JMkb2vl7jT4J")).
neg(eqo("conf/vldb/Guting94","DCUu4jysue0J")).
neg(eqo("conf/vldb/Guting94","NZYZOztyAqoJ")).
neg(eqo("conf/vldb/HaberIL95","csgD6L3ktD8J")).
neg(eqo("conf/vldb/Hamilton99","k_O40ldI0LgJ")).
neg(eqo("conf/vldb/Hamilton99","x3ipTUM3SdsJ")).
neg(eqo("conf/vldb/HammadFAE03","vfCFumS9QtkJ")).
neg(eqo("conf/vldb/HanF95","OdpKxDyMwhsJ")).
neg(eqo("conf/vldb/HanF95","_rlpIiNduaYJ")).
neg(eqo("conf/vldb/HankinsP03","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/HelmerM97","KJ8d3evJm4oJ")).
neg(eqo("conf/vldb/HelmerM97","fz4PKDuWGmoJ")).
neg(eqo("conf/vldb/Hess96","Gia7489k5t4J")).
neg(eqo("conf/vldb/HeymannTKWRMF02","iGvvjzBz_kAJ")).
neg(eqo("conf/vldb/HuangJR97","QMpKELHEzRoJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","7y9SomIIAG0J")).
neg(eqo("conf/vldb/HuntAI01","6dAWUHYKqFUJ")).
neg(eqo("conf/vldb/Jacobs97","FhkbdYqNZvMJ")).
neg(eqo("conf/vldb/JaedickeM99","0GMNedjfVV0J")).
neg(eqo("conf/vldb/JaedickeM99","MxiDXlvxakAJ")).
neg(eqo("conf/vldb/JagadishLS99","5d1R2mD-7MkJ")).
neg(eqo("conf/vldb/JermaineDO99","m7vgjeCVUnEJ")).
neg(eqo("conf/vldb/JohnsonA00","UwOgoqlmVyoJ")).
neg(eqo("conf/vldb/JohnsonM98","VJ51OvhObJEJ")).
neg(eqo("conf/vldb/KahveciS01","EqF1i1bl7GIJ")).
neg(eqo("conf/vldb/KahveciS01","iMGwasyHkgIJ")).
neg(eqo("conf/vldb/KalusD95","csgD6L3ktD8J")).
neg(eqo("conf/vldb/KemmeA00","_FNrQSD-huEJ")).
neg(eqo("conf/vldb/KemperK94","2-jnVu2TIPUJ")).
neg(eqo("conf/vldb/King02","0beHvgeW9TMJ")).
neg(eqo("conf/vldb/KornSFSP96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057805")).
neg(eqo("conf/vldb/KossmannRR02","url:http://doi.wiley.com/10.1002/he.94")).
neg(eqo("conf/vldb/KounevB02","nqosSM46lCkJ")).
neg(eqo("conf/vldb/KumarRRT99","1xbD4ssSjjUJ")).
neg(eqo("conf/vldb/LabioG96","PAtbGvXDP1wJ")).
neg(eqo("conf/vldb/LakshmananPZ03","4weou-KgkM8J")).
neg(eqo("conf/vldb/LamKR02","FtWc55hx6LkJ")).
neg(eqo("conf/vldb/LeeHJT03","BSE2se70OMYJ")).
neg(eqo("conf/vldb/LempelM02","za6ySySnGH8J")).
neg(eqo("conf/vldb/LeslieJBY95","N3Bry6sSMw8J")).
neg(eqo("conf/vldb/LevyRO96","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/Leymann01","VfKOqNP73HYJ")).
neg(eqo("conf/vldb/LiCHH97","5qg4BNiroqMJ")).
neg(eqo("conf/vldb/LimWPVP02","Frv36jzaY1wJ")).
neg(eqo("conf/vldb/LimWPVP02","GU1B3LSbkTIJ")).
neg(eqo("conf/vldb/LitwinNS94","mwox19EH9esJ")).
neg(eqo("conf/vldb/LohmanL02","z6JEYoArZmsJ")).
neg(eqo("conf/vldb/LongS03","7ZaWAOK_DX4J")).
neg(eqo("conf/vldb/ManolescuFKXO00","t19PsyGam1EJ")).
neg(eqo("conf/vldb/Mattos96","9L2aD_a7dyoJ")).
neg(eqo("conf/vldb/Mattos96","k3znuHyMD0oJ")).
neg(eqo("conf/vldb/Moerkotte02","YUMysWRHicsJ")).
neg(eqo("conf/vldb/MogiK95","ybgxHuCAS_8J")).
neg(eqo("conf/vldb/Mohan01","_2hj6snS3foJ")).
neg(eqo("conf/vldb/Mohan02","lI_yxVw-IuAJ")).
neg(eqo("conf/vldb/MohanBWSZ00","I_uiN_1CoisJ")).
neg(eqo("conf/vldb/MorimotoFMTY98","9sydmlCRr4cJ")).
neg(eqo("conf/vldb/MorimotoFMTY98","epUf9ogilogJ")).
neg(eqo("conf/vldb/NinkHR99","iPGQr-Uv4OQJ")).
neg(eqo("conf/vldb/NipplM98","uEx6DGPm-sAJ")).
neg(eqo("conf/vldb/Novaretti01","01iwVR6RAU8J")).
neg(eqo("conf/vldb/OzsuLON01","WCiYIZ6x4jkJ")).
neg(eqo("conf/vldb/OzsuVU98","tftfK6qWKJcJ")).
neg(eqo("conf/vldb/PacittMS99","Bn8s7u5T9SAJ")).
neg(eqo("conf/vldb/Padmanabhan96","ghIMekzCkMQJ")).
neg(eqo("conf/vldb/PapadiasMD98","ES56WbYJgBoJ")).
neg(eqo("conf/vldb/PoosalaI97","gKOsM57uFB4J")).
neg(eqo("conf/vldb/RaghavanG03","JrulZz43BaMJ")).
neg(eqo("conf/vldb/RamakrishnanR96","Lpg1VkCQhdAJ")).
neg(eqo("conf/vldb/RamamurthyDS02","WLNi7oBmsCcJ")).
neg(eqo("conf/vldb/RamasamyPNK00","6OfJSMB4vOcJ")).
neg(eqo("conf/vldb/RantzauCHM02","yVIwwbQbgT0J")).
neg(eqo("conf/vldb/Sacks-Davis96","4w_6_iLYHIkJ")).
neg(eqo("conf/vldb/Sarawagi00","49BUF_66HgcJ")).
neg(eqo("conf/vldb/Schek00","kEWc1UPSB-kJ")).
neg(eqo("conf/vldb/Schoning03","6BjGqZ3WisIJ")).
neg(eqo("conf/vldb/Selinger02","6MaM88h1VoAJ")).
neg(eqo("conf/vldb/ShaferA97","5HHRNLsy0sAJ")).
neg(eqo("conf/vldb/ShahRS02","9jNw_wKmZgUJ")).
neg(eqo("conf/vldb/ShanmugasundaramGTZDN99","hYQ_6_v-Cd4J")).
neg(eqo("conf/vldb/Sheth96","eyl8gnuvxDUJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","rT9Jb9sW6C4J")).
neg(eqo("conf/vldb/Spintzik95","MxiDXlvxakAJ")).
neg(eqo("conf/vldb/StolteA02","HLu7MvWb5rMJ")).
neg(eqo("conf/vldb/SubietaKL95","1VEHUogTMZMJ")).
neg(eqo("conf/vldb/TaoP02","DzlO7azI3rUJ")).
neg(eqo("conf/vldb/Taylor00","JrOawEomxesJ")).
neg(eqo("conf/vldb/TianD03","hBrgosYDi3oJ")).
neg(eqo("conf/vldb/TreschPL95","7j1pKfzfgNYJ")).
neg(eqo("conf/vldb/Tygar98","jJyGKE2N34gJ")).
neg(eqo("conf/vldb/UrhanF01","0-FUXURm1FQJ")).
neg(eqo("conf/vldb/Vieille98","nlyEH7GkrjoJ")).
neg(eqo("conf/vldb/VriesDBA99","diz7pEBdXDgJ")).
neg(eqo("conf/vldb/Wadler01","m3dGlRp9NeIJ")).
neg(eqo("conf/vldb/Wang95","url:http://portal.acm.org/citation.cfm%3Fid%3D1027527.1027770")).
neg(eqo("conf/vldb/WangZL03","n0q3Jafl1BEJ")).
neg(eqo("conf/vldb/WitkowskiBBFGSS03","sCMuAA4gnsMJ")).
neg(eqo("conf/vldb/WuFSP00","XojbAfbtdvcJ")).
neg(eqo("conf/vldb/YagoubFIV00","NwBwLRnC0QkJ")).
neg(eqo("conf/vldb/YanA94","8j5i7YJQnNAJ")).
neg(eqo("conf/vldb/YangLH03","Ltf5yQsl8sMJ")).
neg(eqo("conf/vldb/YuAA03","SHpVAoVPUHYJ")).
neg(eqo("conf/vldb/YuAA03","y2dZ5cRja_IJ")).
neg(eqo("conf/vldb/YuSLJ02","jJym5UnL5poJ")).
neg(eqo("conf/vldb/ZhangL97","5FMbn9I1QeEJ")).
neg(eqo("conf/vldb/ZirintsisKM99","NLklGN91cZgJ")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637423%26dl%3Dportal%26dl%3DACM%26type%3Dissue%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03b","6MY_fFzgHtgJ")).
neg(eqo("journals/sigmod/Aberer03d","P30a3k6zSv8J")).
neg(eqo("journals/sigmod/AbererCH02","RSNC3ApuY3AJ")).
neg(eqo("journals/sigmod/Abiteboul99","lV0HWh9QLUQJ")).
neg(eqo("journals/sigmod/Ahlberg96","RU01fPjfV70J")).
neg(eqo("journals/sigmod/Alonso94b","fLhbRkGdZ-IJ")).
neg(eqo("journals/sigmod/Alonso95","U5N-48XkepoJ")).
neg(eqo("journals/sigmod/AnyanwuS02","OeY8zow1buwJ")).
neg(eqo("journals/sigmod/AnyanwuS02","dOL7ytHorkQJ")).
neg(eqo("journals/sigmod/AshishK97","_avm808LQocJ")).
neg(eqo("journals/sigmod/AshishK97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D156895%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Barbara01","0whivG_IK1wJ")).
neg(eqo("journals/sigmod/BargaL02","QgKRpqigXEsJ")).
neg(eqo("journals/sigmod/BawaCCDGGKMSSVY03","P5oJUiow7lsJ")).
neg(eqo("journals/sigmod/Bernstein01","WjDgwWnHHe4J")).
neg(eqo("journals/sigmod/Bernstein98","Gr3-L-wyIOcJ")).
neg(eqo("journals/sigmod/BernsteinHP00","3-iiSyJLwLkJ")).
neg(eqo("journals/sigmod/BertinoEH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219766%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BunemanLSTW94","nmEhI0tiWGAJ")).
neg(eqo("journals/sigmod/Bussler02","RaOQG4YyzM4J")).
neg(eqo("journals/sigmod/Camps96","fnmqvPVRYBAJ")).
neg(eqo("journals/sigmod/Chang03","Em3qp7RGalkJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","1oCTwvC32jkJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","thTt2lg4_Z8J")).
neg(eqo("journals/sigmod/Chen94","xufwWHmOf6IJ")).
neg(eqo("journals/sigmod/CherniakV03","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/ClementLGMK97","bfcbZlt6vngJ")).
neg(eqo("journals/sigmod/ClementLGMK97","fuwnNbW8EscJ")).
neg(eqo("journals/sigmod/DadamK97","9Ai_9dZChG4J")).
neg(eqo("journals/sigmod/DadamK97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202672%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/DoanPSB97","isW9Z4PIs0YJ")).
neg(eqo("journals/sigmod/DoanPSB97","r30CyoxOeycJ")).
neg(eqo("journals/sigmod/Dogac98","347oyb_b7DAJ")).
neg(eqo("journals/sigmod/DogacDATKCD98","Il_0XhdELTAJ")).
neg(eqo("journals/sigmod/DunhamH95a","CiumYR8Q4WcJ")).
neg(eqo("journals/sigmod/EisenbergM00","AatoNnELw78J")).
neg(eqo("journals/sigmod/EisenbergM99","wSMRX5CsNVoJ")).
neg(eqo("journals/sigmod/Fagin02","KX-j-c9FXLUJ")).
neg(eqo("journals/sigmod/Fankhauser01","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D20021211001548MT%26recid%3DA8622909AH")).
neg(eqo("journals/sigmod/FlorescuLM98","q5OOyzSAlC8J")).
neg(eqo("journals/sigmod/FlorescuLM98","tbUQW4M8rrkJ")).
neg(eqo("journals/sigmod/Fong97","JlS5P7ZUhp0J")).
neg(eqo("journals/sigmod/Franklin97","JHuJHooGoNUJ")).
neg(eqo("journals/sigmod/Franklin97","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin97a","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Franklin98","fNVk1Vq2txEJ")).
neg(eqo("journals/sigmod/Franklin98","szcVumclSzoJ")).
neg(eqo("journals/sigmod/Franklin98","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Franklin98b","vgcXH5aVpdgJ")).
neg(eqo("journals/sigmod/Franklin99a","jrDSC1jKTI4J")).
neg(eqo("journals/sigmod/Gallagher94","wiJW7Do2r84J")).
neg(eqo("journals/sigmod/GobleR02","xmZ0b0yNt_0J")).
neg(eqo("journals/sigmod/GolabO03","jGb8C7wu8aYJ")).
neg(eqo("journals/sigmod/GolabO03","rO4-yA3tlfoJ")).
neg(eqo("journals/sigmod/GottlobKP03","gvRotI4FkqwJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","url:http://portal.acm.org/citation.cfm%3Fid%3D333607.333616%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/GuptaHR97","GPEkH-UohLYJ")).
neg(eqo("journals/sigmod/Halevy03","url:http://doi.wiley.com/10.1002/he.71")).
neg(eqo("journals/sigmod/HalkidiBV02","MZqMXLhtCXUJ")).
neg(eqo("journals/sigmod/Hammer01","url:http://portal.acm.org/citation.cfm%3Fid%3D984488.984489%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Han98","mwSZ7Yejt8sJ")).
neg(eqo("journals/sigmod/Hanna95","EKqpEdn3kDMJ")).
neg(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
neg(eqo("journals/sigmod/JajodiaBBKMSW97","ZsHfcZJwFQQJ")).
neg(eqo("journals/sigmod/JajodiaBBKMSW97","p9EcCI4VpQYJ")).
neg(eqo("journals/sigmod/Jarke95","sllUMGYq2X0J")).
neg(eqo("journals/sigmod/KannanKIK03","KQ6elbYA84QJ")).
neg(eqo("journals/sigmod/Kemper02","fiQJ-t1ktOIJ")).
neg(eqo("journals/sigmod/KennedyMB96","aUc6nWul6acJ")).
neg(eqo("journals/sigmod/Kim02","CASwBynYiosJ")).
neg(eqo("journals/sigmod/KoksalAD98","ryaV3kTsJ2IJ")).
neg(eqo("journals/sigmod/KoksalAD98","vG5FK8BJkZgJ")).
neg(eqo("journals/sigmod/Labrinidis01","url:http://portal.acm.org/citation.cfm%3Fid%3D582318.582325")).
neg(eqo("journals/sigmod/LenzeriniNNS01","url:http://portal.acm.org/citation.cfm%3Fid%3D640990.641003%26dl%3Dportal%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Liu01a","WkldV8dE4ncJ")).
neg(eqo("journals/sigmod/Liu02","HWFatrRxFRAJ")).
neg(eqo("journals/sigmod/Liu02","xeceK06Z5DIJ")).
neg(eqo("journals/sigmod/Liu03a","pE4UwP5xQo4J")).
neg(eqo("journals/sigmod/Liu03b","FF4u5cqjanQJ")).
neg(eqo("journals/sigmod/Liu03c","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Lomet01","fTbCV3Lh8W0J")).
neg(eqo("journals/sigmod/Lomet98","7uHaZzL1yXIJ")).
neg(eqo("journals/sigmod/LudascherMM01","oXTd748VmwMJ")).
neg(eqo("journals/sigmod/LudwigG00","rXU769f0cnsJ")).
neg(eqo("journals/sigmod/Mani03","DBh8U9xhCocJ")).
neg(eqo("journals/sigmod/Mani03","RwEmYOdbkQEJ")).
neg(eqo("journals/sigmod/Mani03","hO_32Nq5uMkJ")).
neg(eqo("journals/sigmod/Manola98","5fw03ImttPUJ")).
neg(eqo("journals/sigmod/Manola98","HgnNz_pPbV8J")).
neg(eqo("journals/sigmod/MaximilienS02","LcAXz1gaw5cJ")).
neg(eqo("journals/sigmod/McClatcheyV97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/McHughW97","uzqVcPOKd6sJ")).
neg(eqo("journals/sigmod/MeltonMJKS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MusickC99","24k4abFyy9sJ")).
neg(eqo("journals/sigmod/NgH95","gvRotI4FkqwJ")).
neg(eqo("journals/sigmod/NormanZT96","u64n4yMnma4J")).
neg(eqo("journals/sigmod/OConnellW03","H5IdN0_MQw4J")).
neg(eqo("journals/sigmod/OrlandicLS02","30i2w66KFhQJ")).
neg(eqo("journals/sigmod/OrlandicLS02","8zFEVer1rBUJ")).
neg(eqo("journals/sigmod/OrlandicLS02","R65BNwJZA9IJ")).
neg(eqo("journals/sigmod/OrlandicLS02","oABGXQlfGKcJ")).
neg(eqo("journals/sigmod/OukselS99","S-LYnzS1K70J")).
neg(eqo("journals/sigmod/Ozsoyoglu00","svPdI1xOUCcJ")).
neg(eqo("journals/sigmod/PalpanasPKG03","KQ6elbYA84QJ")).
neg(eqo("journals/sigmod/PalpanasPKG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959074%26type%3Dpdf%26dl%3DGUIDE%26dl%3Dacm%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PitouraB95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130879%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PoessF00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D74122%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian94","-TPeMEC6_UkJ")).
neg(eqo("journals/sigmod/Qian94","NiswbODuzhAJ")).
neg(eqo("journals/sigmod/Qian95b","url:http://portal.acm.org/citation.cfm%3Fid%3D248603.248618%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RisheSBDOALOSS95","FfYkDJrlW4wJ")).
neg(eqo("journals/sigmod/RoantreeMH99","IWEa-GPfwXEJ")).
neg(eqo("journals/sigmod/Rosenthal98","miubKxLrikUJ")).
neg(eqo("journals/sigmod/RossFLOSSVW00","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/RossFLOSSVW00","fC7F6_y4ArkJ")).
neg(eqo("journals/sigmod/RossGN03","eeX9g9Ac1GIJ")).
neg(eqo("journals/sigmod/RossKMV02","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/SantucciT96","ywOivEt15ZEJ")).
neg(eqo("journals/sigmod/SchmidtWKFCMB01","qPjw1RIWLAQJ")).
neg(eqo("journals/sigmod/SchmidtWKFCMB01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603872%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SilberschatzSU96","F9DV57ns9yMJ")).
neg(eqo("journals/sigmod/Snodgrass00a","niAGPBSYvBIJ")).
neg(eqo("journals/sigmod/Snodgrass02","V1QUdDtkH5AJ")).
neg(eqo("journals/sigmod/Snodgrass03","VwZQmafqkE0J")).
neg(eqo("journals/sigmod/Snodgrass94","QHLQZQwlbTsJ")).
neg(eqo("journals/sigmod/Snodgrass99","V1DwPxXlTD4J")).
neg(eqo("journals/sigmod/Stonebraker02","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D1320096")).
neg(eqo("journals/sigmod/Stonebraker02","z8UTEms4_WsJ")).
neg(eqo("journals/sigmod/TatarinovIMHSDDKMM03","S53lfd4tC1kJ")).
neg(eqo("journals/sigmod/TsotrasJS98","rHG_ZjKIUQMJ")).
neg(eqo("journals/sigmod/TsotrasK96","bqtRaOoJ87AJ")).
neg(eqo("journals/sigmod/UrbanDG96","F9DV57ns9yMJ")).
neg(eqo("journals/sigmod/Vassilakis00","nZO8ZA4eYzYJ")).
neg(eqo("journals/sigmod/VassiliadisS99","kSd7Sk769EsJ")).
neg(eqo("journals/sigmod/Weikum02","hQHDSQZVuQkJ")).
neg(eqo("journals/sigmod/Winslett03b","IrTKBa0mgEsJ")).
neg(eqo("journals/sigmod/WinslettCDHZZ02","RjkfjmhJKFUJ")).
neg(eqo("journals/sigmod/WinslettMY03","url:http://portal.acm.org/citation.cfm%3Fid%3D1041410.1041425")).
neg(eqo("journals/sigmod/WinslettMY03","vB2-tiNWKpkJ")).
neg(eqo("journals/sigmod/Wong95","4pTCoy1yFqEJ")).
neg(eqo("journals/sigmod/Yang94","KOpz_NXJ3WUJ")).
neg(eqo("journals/tods/BunemanO96","EEeqwt9n5yQJ")).
neg(eqo("journals/tods/ChaudhuriS99","QAhsPX__MK8J")).
neg(eqo("journals/tods/Chen95a","qfD_kxYt-dsJ")).
neg(eqo("journals/tods/DiaoAFZF03","fREDZIbZVdEJ")).
neg(eqo("journals/tods/EiterLLS01","appznj0qU2MJ")).
neg(eqo("journals/tods/FranklinCL97","Ngou52TV_R4J")).
neg(eqo("journals/tods/FraternaliT95","8k0tS22xvPcJ")).
neg(eqo("journals/tods/GhandeharizadehHJ96","OSJDwtdGZ-QJ")).
neg(eqo("journals/tods/GoldmanL94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093386%26type%3Dpdf")).
neg(eqo("journals/tods/GutingBEJLSV00","uslMCdq5gUsJ")).
neg(eqo("journals/tods/Kuo96","EupCg3q482AJ")).
neg(eqo("journals/tods/LechtenborgerV03","pRIP3vfQtpEJ")).
neg(eqo("journals/tods/Revesz98","ikeqv3BhoR4J")).
neg(eqo("journals/tods/ScioreSR94","fB2xVdlMTtwJ")).
neg(eqo("journals/tods/Snodgrass01","XS0g9j8J7woJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/P074T33638T88V55.pdf")).
neg(eqo("journals/tods/Subrahmanian94","ZxYlVKM6krAJ")).
neg(eqo("journals/tods/TaoP03","fDWfHiQ6BR4J")).
neg(eqo("journals/tods/Wijsen99","NyPmlzkK4M8J")).
neg(eqo("journals/tods/YanG99","RkoUJsL6BTkJ")).
neg(eqo("journals/tods/YanG99","beRPESOXfs4J")).
neg(eqo("journals/tods/ZaharioudakisCF97","3GY5tow6VagJ")).
neg(eqo("journals/vldb/AnGSVKI02","mlNoe-1jmygJ")).
neg(eqo("journals/vldb/Antoshenkov97","Z1Lb7YfN8vUJ")).
neg(eqo("journals/vldb/Atkinson00","rqTxO0ix3qUJ")).
neg(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/CWANCL0VWN1MKL0M.pdf")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.springerlink.com/index/0YKCKU5LKG6G102T.pdf")).
neg(eqo("journals/vldb/BraumandlCKK00","R65BNwJZA9IJ")).
neg(eqo("journals/vldb/C94b","evCVWHRZwIsJ")).
neg(eqo("journals/vldb/CatarciSC97","dvzXmzEc9o8J")).
neg(eqo("journals/vldb/ChakrabartiRS03","Zi9aiRG5VoYJ")).
neg(eqo("journals/vldb/ChangG01","dkoIJqatfrsJ")).
neg(eqo("journals/vldb/ChuIT94","VYTG-BeYAM8J")).
neg(eqo("journals/vldb/DeWittNSV96","JqV63F6w9GkJ")).
neg(eqo("journals/vldb/DerrMP94","ulDehVmIgfAJ")).
neg(eqo("journals/vldb/DoanMDDH03","9kl_hTyQtmQJ")).
neg(eqo("journals/vldb/GrefenVA01","IcYH5NnWx7AJ")).
neg(eqo("journals/vldb/Guting94","s23KDOsPdOoJ")).
neg(eqo("journals/vldb/Halevy01","z5DmAoBjsjAJ")).
neg(eqo("journals/vldb/Han98","uEbdEtnaCXMJ")).
neg(eqo("journals/vldb/HansonCDERTX98","jJym5UnL5poJ")).
neg(eqo("journals/vldb/HarderR96","pWXIPx5lA7gJ")).
neg(eqo("journals/vldb/IvesHW02","9Xt-vnr5cXgJ")).
neg(eqo("journals/vldb/JagadishACLNPPSWWY02","LHqsHaHPpfgJ")).
neg(eqo("journals/vldb/LiangOY00","-f2FsG-EC9IJ")).
neg(eqo("journals/vldb/MedjahedBBNE03","Jml6flDOu7QJ")).
neg(eqo("journals/vldb/MedjahedBE03","-Aw9zi3h104J")).
neg(eqo("journals/vldb/MehtaD97","lLR1A9bENSwJ")).
neg(eqo("journals/vldb/NanopoulosM02","tHwh-sh2TBMJ")).
neg(eqo("journals/vldb/NybergBCGL95","A1phylxPkl4J")).
neg(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
neg(eqo("journals/vldb/PeckhamMD95","7ZDURed14q0J")).
neg(eqo("journals/vldb/PoulovassilisS96","VCSbj6MwKlgJ")).
neg(eqo("journals/vldb/PoulovassilisS96","oeal9PAkZYIJ")).
neg(eqo("journals/vldb/Sarawagi01","2eEJYCOCb8sJ")).
neg(eqo("journals/vldb/Sarawagi01","gz92a8BdTLUJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","_bdp5T8SSuoJ")).
neg(eqo("journals/vldb/ShegalovGW01","_6ErNQyZwXsJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","btydMRJMBqoJ")).
neg(eqo("journals/vldb/StonebrakerALPSSSY96","9BuBq-Tj0TUJ")).
neg(eqo("journals/vldb/SuHHHLWLPLL01","46PsbfuQ8_8J")).
neg(eqo("journals/vldb/TurkerG01","z5DmAoBjsjAJ")).
pos(eqo("conf/sigmod/AbiteboulCM95","DakOA4Ew-poJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","FDPwbRQbfIAJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","NDzryNtTyL8J")).
pos(eqo("conf/sigmod/AcharyaFZ97","QCAu6wPhnAAJ")).
pos(eqo("conf/sigmod/AcharyaGP00","smzeHDQ3zbMJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","IkNOhDqEY18J")).
pos(eqo("conf/sigmod/AdaliCPS96","uMmcsye0YCkJ")).
pos(eqo("conf/sigmod/AdaliCPS96","zE4iM0h4W2sJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/AdyaGLM95","FlE1JdgElGQJ")).
pos(eqo("conf/sigmod/AggarwalWY99","s9hhR-EdDGgJ")).
pos(eqo("conf/sigmod/AggarwalY01","6i8hYEhbelEJ")).
pos(eqo("conf/sigmod/AggarwalY01","QkTd5WogN-AJ")).
pos(eqo("conf/sigmod/AgrawalASY97","-XBy73K2jq0J")).
pos(eqo("conf/sigmod/AgrawalASY97","7Of1HyK-VnkJ")).
pos(eqo("conf/sigmod/AgrawalASY97","bDiNQAdf8nEJ")).
pos(eqo("conf/sigmod/AgrawalCD02","iABZEL2Zoz8J")).
pos(eqo("conf/sigmod/AgrawalGGR98","1rW7ao6gK-QJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","rSTewQ1dQkYJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x8fDHaNkSUIJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","y55xkFQJvxAJ")).
pos(eqo("conf/sigmod/Al-KhalifaYJ03","boJKiPCpIxkJ")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","fm69LHjS4T0J")).
pos(eqo("conf/sigmod/AnnamalaiCD00","0Igfv6jL3jwJ")).
pos(eqo("conf/sigmod/BaruFGHJPW95","mFOSML8c0s4J")).
pos(eqo("conf/sigmod/Bayardo98","O05yYxasf6UJ")).
pos(eqo("conf/sigmod/BerchtoldK98","9UYo0M1RV7oJ")).
pos(eqo("conf/sigmod/BersonGM95","AdvsjAZhCc8J")).
pos(eqo("conf/sigmod/BersonGM95","YkPqPzGFnZIJ")).
pos(eqo("conf/sigmod/BettiniWBJ95","wZkNJJn90yAJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","cg01BqanXhUJ")).
pos(eqo("conf/sigmod/Bierman03","vQcfluHWCeAJ")).
pos(eqo("conf/sigmod/BilirisDGJR94","3Lzo6p8X-n4J")).
pos(eqo("conf/sigmod/Blakeley96","1fs-qN_SdH4J")).
pos(eqo("conf/sigmod/Blakeley96","37_iwO5NlgwJ")).
pos(eqo("conf/sigmod/BreitbartKRSS99","XV2lpkhWCsYJ")).
pos(eqo("conf/sigmod/BreunigKKS01","LxyVmHubIfUJ")).
pos(eqo("conf/sigmod/BrunoCG01","SGmfFHnOf4IJ")).
pos(eqo("conf/sigmod/BrunoCG01","XWF4kOtaoJkJ")).
pos(eqo("conf/sigmod/Bussler01","UYIeOe280OwJ")).
pos(eqo("conf/sigmod/CandanLLHA01","efYVCK07AwMJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","5wcgt7bNx7YJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","GJ_7cqL0d70J")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","jMc3U-zRTPEJ")).
pos(eqo("conf/sigmod/CareyK97","2OPEy9_6BlEJ")).
pos(eqo("conf/sigmod/CareyK97","G2RzED0JGvoJ")).
pos(eqo("conf/sigmod/CareyK97","b_lpj8wu7BEJ")).
pos(eqo("conf/sigmod/CareyK97","ucdmk8xwaTsJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/CareyMN97","nM9bJESsWNoJ")).
pos(eqo("conf/sigmod/CarinoKKB01","a9HFF_bwiH4J")).
pos(eqo("conf/sigmod/CarinoKKB01","p5XsTaZaGcIJ")).
pos(eqo("conf/sigmod/CasatiS01","2_VG_VUkHH8J")).
pos(eqo("conf/sigmod/CatarciS01","frbExwv4DiwJ")).
pos(eqo("conf/sigmod/ChanI99","uLiEqn5nA_IJ")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","onlybp6SAAsJ")).
pos(eqo("conf/sigmod/ChaudhuriDY95","0LRr6nTypA4J")).
pos(eqo("conf/sigmod/ChaudhuriGGM03","H5IdN0_MQw4J")).
pos(eqo("conf/sigmod/ChaudhuriGS03","OFGtGwUHhUQJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","U0w9W7YcsZwJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","clNmwzm-5acJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","Xz0ZPMLOwcgJ")).
pos(eqo("conf/sigmod/CherniackZ98","_wJZsVYdrr8J")).
pos(eqo("conf/sigmod/Chong98","W-6r_OOEHLUJ")).
pos(eqo("conf/sigmod/CluetDSS98","63Y-t4R2RycJ")).
pos(eqo("conf/sigmod/CluetDSS98","lOZF0Ee3rUQJ")).
pos(eqo("conf/sigmod/CluetDSS98","q9yRMEgjLOAJ")).
pos(eqo("conf/sigmod/ColletC95","vP27NkXI4MEJ")).
pos(eqo("conf/sigmod/DarR94","TtV6gGLQ9NMJ")).
pos(eqo("conf/sigmod/DasuJMS02","Qywc8AsElxEJ")).
pos(eqo("conf/sigmod/DattaDTVSR02","orxvLy4vVEQJ")).
pos(eqo("conf/sigmod/DewanSHH94","GUdXGx4blW8J")).
pos(eqo("conf/sigmod/DraperHW01","6MdiqTp20aoJ")).
pos(eqo("conf/sigmod/FabretJLPRS01","IHZ0cEpqnPkJ")).
pos(eqo("conf/sigmod/FaginKS03","dOY1djmoy04J")).
pos(eqo("conf/sigmod/Fegaras98","XVtlJYx2G_wJ")).
pos(eqo("conf/sigmod/FranklinZ98","K_qOxjIJWpQJ")).
pos(eqo("conf/sigmod/FreireHRRS02","Pg-vbrBME1cJ")).
pos(eqo("conf/sigmod/FreireHRRS02","z8IglVK-XnEJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","Y8UdbAPhYpUJ")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
pos(eqo("conf/sigmod/GardarinMP95","l-9pykkOVrkJ")).
pos(eqo("conf/sigmod/GarofalakisG02","6EaC2CmjsmAJ")).
pos(eqo("conf/sigmod/GibbsBT94","6oKFObEbS5oJ")).
pos(eqo("conf/sigmod/GibbsBT94","cRvuoTzIXRYJ")).
pos(eqo("conf/sigmod/GibbsBT94","iS9rQqelSjMJ")).
pos(eqo("conf/sigmod/Golding95","uJj9OgotYeEJ")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/Grust02","F3sNx_8p3McJ")).
pos(eqo("conf/sigmod/GuhaRS98","Y8HMa1ZZE6sJ")).
pos(eqo("conf/sigmod/GuhaRS98","oWVyLUIy9JwJ")).
pos(eqo("conf/sigmod/GuptaMR95","ELtcV7mOQDgJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","pzPZuUoWej8J")).
pos(eqo("conf/sigmod/HammerGNYBV97","t9nmZzSMVAAJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","uPHrOdEDjlEJ")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanKS97","_EEZCcB1BPYJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","4OrM17Osz64J")).
pos(eqo("conf/sigmod/HarinarayanRU96","8A_9ucHRXyIJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","9Ue5hZp8H68J")).
pos(eqo("conf/sigmod/HarinarayanRU96","ESZwkhGzOboJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Qv7KYn9x-SQJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","V6KNPMKdyagJ")).
pos(eqo("conf/sigmod/HellersteinA00","-GYSZmXrx-UJ")).
pos(eqo("conf/sigmod/HellersteinA00","VlRO0WwUy3wJ")).
pos(eqo("conf/sigmod/HellersteinW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564788%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Hidber99","HkBKH9ZUJEcJ")).
pos(eqo("conf/sigmod/Hidber99","Rn-E82gM1RQJ")).
pos(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
pos(eqo("conf/sigmod/HinneburgKW02","T1dmP2NL1aYJ")).
pos(eqo("conf/sigmod/HinneburgKW02","VWd7jhLXfV0J")).
pos(eqo("conf/sigmod/HungYK96","NY5e4MkJ6VYJ")).
pos(eqo("conf/sigmod/HwangLYMMGCSS94","AWah9GLEFTAJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","U04OC6OSBT0J")).
pos(eqo("conf/sigmod/IoannidisLANT97","kDWGwVa8dykJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","qb-jf_sQ_5kJ")).
pos(eqo("conf/sigmod/JagatheesanR03","InqySB8bkKkJ")).
pos(eqo("conf/sigmod/JagatheesanR03","fobv5DPqKUcJ")).
pos(eqo("conf/sigmod/KabraD98","E0nhpX8pYsQJ")).
pos(eqo("conf/sigmod/KabraD98","WOHxNqdNMZoJ")).
pos(eqo("conf/sigmod/KalnisNOPT02","ipAB8UMS7QkJ")).
pos(eqo("conf/sigmod/KanthAS98","tG_s5R-BKcAJ")).
pos(eqo("conf/sigmod/KeimK95","34xG3yx9iiwJ")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","DDxRgcJirBMJ")).
pos(eqo("conf/sigmod/KimC03","BWV2Oys1VXsJ")).
pos(eqo("conf/sigmod/KotidisR99","323DOAMQyUkJ")).
pos(eqo("conf/sigmod/KotidisR99","5sb4hr4Ton0J")).
pos(eqo("conf/sigmod/KotidisR99","qzjtGDo7OuMJ")).
pos(eqo("conf/sigmod/KrollW94","AMvcOVWQiNEJ")).
pos(eqo("conf/sigmod/KrollW94","SX1_Z3Z000YJ")).
pos(eqo("conf/sigmod/KrollW94","kUzm9ofgc1UJ")).
pos(eqo("conf/sigmod/LazaridisM01","IvMJ4bK708kJ")).
pos(eqo("conf/sigmod/LeflerSW96","4b12cZc8QK4J")).
pos(eqo("conf/sigmod/LiCHH97","mNqvFihFg1AJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","4zDGoqCAWOoJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","6jeHlSgjCskJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","oQtxPA_0PCYJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","xLs_uumSG84J")).
pos(eqo("conf/sigmod/LiefkeS00","SvVh9QQcgDwJ")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/LiefkeS00","vnc0Ml_3BFsJ")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/MaratheS99","z6JEYoArZmsJ")).
pos(eqo("conf/sigmod/MatiasVW98","6WjESNMzLvgJ")).
pos(eqo("conf/sigmod/McAuliffeCS96","c__Nxyn_uvwJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","v2KwhRi-OrMJ")).
pos(eqo("conf/sigmod/Meseck01","hWiIngXs5I0J")).
pos(eqo("conf/sigmod/MiloAABN03","P7vZf4MkRO4J")).
pos(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
pos(eqo("conf/sigmod/Mohan94","E2zhARKv5dsJ")).
pos(eqo("conf/sigmod/MumickQM97","c_n0wQe1FhAJ")).
pos(eqo("conf/sigmod/NestorovAM98","XP7FEaxDfuAJ")).
pos(eqo("conf/sigmod/NgLHM99","YemauUgIzlcJ")).
pos(eqo("conf/sigmod/NguyenS96","uD0NKv4AwaQJ")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/citation.cfm%3Fid%3D304245%26coll%3Dportal%26dl%3DACM")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304245%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/OlstonWACELSS98","UTYa5uf9zSIJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/PaparizosACJLNPSWWY03","HuPDChjYd44J")).
pos(eqo("conf/sigmod/ParkKKLPC98","aepGxosl6YoJ")).
pos(eqo("conf/sigmod/PeiMHZ00","UyhrqiH_-MoJ")).
pos(eqo("conf/sigmod/PiatkoYLS96","3NMPG1vUNgwJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","4eUqHKdkGNoJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","gfRbQIzfux4J")).
pos(eqo("conf/sigmod/PoosalaIHS96","lMlFez_Iq2gJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","uveOdmVtqRMJ")).
pos(eqo("conf/sigmod/QuassW97","TfIJHxpZeJIJ")).
pos(eqo("conf/sigmod/RafieiM97","Z8kRr4T21JYJ")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/Ramanan02","VGe-IBWyMm4J")).
pos(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
pos(eqo("conf/sigmod/RodriguezR00","MCDgDxsc8rcJ")).
pos(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","l1tbsG6UXaMJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","r3GI5ly9cuIJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","Elpbl8vygYoJ")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","SipDBj3SOb4J")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","Z2CAABdqG5UJ")).
pos(eqo("conf/sigmod/SlivinskasJS01","oAVbM_vepr8J")).
pos(eqo("conf/sigmod/Smith01","WfKk1v3VamgJ")).
pos(eqo("conf/sigmod/SrikantA96","Cm66C3yYtdgJ")).
pos(eqo("conf/sigmod/SrikantA96","KVEv4thH4CgJ")).
pos(eqo("conf/sigmod/SrikantA96","ZBuWjiVOE94J")).
pos(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
pos(eqo("conf/sigmod/StonebrakerH01","ltEmsluBrYkJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","P8SQPINQRHQJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","kKk4xIJfQ70J")).
pos(eqo("conf/sigmod/VanceM96","-tCYCLPZLvYJ")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/VitterW99","1UFq52qqErUJ")).
pos(eqo("conf/sigmod/WynblattN01","PVUtZWBcxlAJ")).
pos(eqo("conf/sigmod/YanMHF01","adm7QWgi-BAJ")).
pos(eqo("conf/sigmod/YangWYH02","xsaovu54vl4J")).
pos(eqo("conf/sigmod/YerneniLGU99","2MbaeG3IVV0J")).
pos(eqo("conf/sigmod/YerneniLGU99","Gnb52DoKdJwJ")).
pos(eqo("conf/sigmod/ZadorozhnyRVUB02","xmE1380_4E4J")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qzxeS4RQAhwJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","GfRmtB2qhgYJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","Mqg5svJwsCoJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VAX1F7QPNfsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","6AK0GF7jAtsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","I5JNUp7RoGgJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","XurM_pCyadcJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","mBC03oUT8yAJ")).
pos(eqo("conf/sigmod/ZhouLP99","0OwKmPjQpd0J")).
pos(eqo("conf/sigmod/ZhouWGGZWXYF03","AwFxLUGiceUJ")).
pos(eqo("conf/vldb/AdiBEY00","RkjggE7xhN0J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AggarwalHWY03","ZFtAmPKKRBQJ")).
pos(eqo("conf/vldb/AggarwalHWY03","yFMUnqONfGwJ")).
pos(eqo("conf/vldb/AltinelBKMPR03","wIlHF5DfRbMJ")).
pos(eqo("conf/vldb/AmmannJR95","x-H7BqZ0Hw8J")).
pos(eqo("conf/vldb/AnanthakrishnaCG02","SByuGUSfTtYJ")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/vldb/ArgePRSV98","A5Eiwdh71m0J")).
pos(eqo("conf/vldb/ArgePRSV98","c3yObnVI65cJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/BamfordBKM98","rfuptELfgLkJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","Q6jRYrIlTM4J")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","h73uxQEBESwJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","L2c8XblCSicJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BliujuteJSS98","wbGdc_RsI14J")).
pos(eqo("conf/vldb/BlokWZPAKJ01","4Ga0Ts2_rp0J")).
pos(eqo("conf/vldb/BonczRK98","965BXzMPxSoJ")).
pos(eqo("conf/vldb/BonifatiCDS01","tCrfb27dXiwJ")).
pos(eqo("conf/vldb/BouganimP02","PhERWOcOkOgJ")).
pos(eqo("conf/vldb/CareyHMW96","Nz8zwxjBoyYJ")).
pos(eqo("conf/vldb/CareyKRLABFLOPQRSSUVWY01","_pAcjtd1nbEJ")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("conf/vldb/CarinoO98","iaOLRaqTWmEJ")).
pos(eqo("conf/vldb/CarneyCZRCS03","JubkWSUFbbcJ")).
pos(eqo("conf/vldb/ChakrabartiRS02","idfox84uNHUJ")).
pos(eqo("conf/vldb/ChaudhuriN97","g6XLqjCRkFcJ")).
pos(eqo("conf/vldb/ChaudhuriN97","hAqEljGAcFsJ")).
pos(eqo("conf/vldb/ChaudhuriS96","4MaErPILRq8J")).
pos(eqo("conf/vldb/ChaudhuriS96","QCFUIVkspywJ")).
pos(eqo("conf/vldb/ChaudhuriS96","hk2lzbke6hQJ")).
pos(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
pos(eqo("conf/vldb/ChenHWW02","kgXRJZKRxZQJ")).
pos(eqo("conf/vldb/Chiueh94","PKK2ak_IzrgJ")).
pos(eqo("conf/vldb/ChoG00","D4MiKRaC-rEJ")).
pos(eqo("conf/vldb/ChoG00","Gvb8XPHg9nUJ")).
pos(eqo("conf/vldb/ChristopheBPV00","q42RuW4_FogJ")).
pos(eqo("conf/vldb/CiacciaPZ97","6cRuX7GDFCoJ")).
pos(eqo("conf/vldb/CiacciaPZ97","V9DtLHHIBxEJ")).
pos(eqo("conf/vldb/ColletCS94","mK2NI9HpmOAJ")).
pos(eqo("conf/vldb/ColletCS94","sZwecq6zUmMJ")).
pos(eqo("conf/vldb/DayalHL01","XuhtK-DsK6gJ")).
pos(eqo("conf/vldb/DesslochM97","OY4EswVULVcJ")).
pos(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
pos(eqo("conf/vldb/DittrichSTW02","egCgEjikCgAJ")).
pos(eqo("conf/vldb/DongHLPW01","eOTkoLDux4wJ")).
pos(eqo("conf/vldb/DonjerkovicR99","Eq1w4LPv_igJ")).
pos(eqo("conf/vldb/DonjerkovicR99","SgokkSrdkyAJ")).
pos(eqo("conf/vldb/EicklerGK95","63QhLG57QssJ")).
pos(eqo("conf/vldb/FangSGMU98","E7yZtVJa2xAJ")).
pos(eqo("conf/vldb/FangSGMU98","z5tz9vybRmIJ")).
pos(eqo("conf/vldb/Fecteau95","LhjvKpDcJKUJ")).
pos(eqo("conf/vldb/FegarasE01","pinPEM3Rvm0J")).
pos(eqo("conf/vldb/FlorescuKLP97","-Zb4WBd1aNUJ")).
pos(eqo("conf/vldb/GaasterlandL94","oIFrkS2rPrcJ")).
pos(eqo("conf/vldb/GallersdorferN95","U8jfPCxfXicJ")).
pos(eqo("conf/vldb/GardarinST96","BBKhPPAqasIJ")).
pos(eqo("conf/vldb/GardarinST96","RB2VKRwnXywJ")).
pos(eqo("conf/vldb/GarofalakisG02","Hz7TBeGZRz8J")).
pos(eqo("conf/vldb/GarofalakisRS99","7BITau8qhpEJ")).
pos(eqo("conf/vldb/GarofalakisRS99","Xm3ygCvkmN8J")).
pos(eqo("conf/vldb/GeorgeH98","2L-UFpDof3UJ")).
pos(eqo("conf/vldb/GibsonKR98","9FBwT6XFOssJ")).
pos(eqo("conf/vldb/GilbertKMS02","xziY9wNuVzwJ")).
pos(eqo("conf/vldb/GoldmanW97","l5GboAkBH1AJ")).
pos(eqo("conf/vldb/GravanoG95","F2mmoq6cRGMJ")).
pos(eqo("conf/vldb/GravanoG95","jXClQzlN5SgJ")).
pos(eqo("conf/vldb/GravanoG95","w7ohoqbphkAJ")).
pos(eqo("conf/vldb/GravanoG95","zbJYyUhl2cIJ")).
pos(eqo("conf/vldb/GrustKT03","25xRkmL_4BsJ")).
pos(eqo("conf/vldb/GuPS00","W-hUzvTqikcJ")).
pos(eqo("conf/vldb/GuPS00","mRWLGqueLNsJ")).
pos(eqo("conf/vldb/HaasKWY97","6TrmUUoylzIJ")).
pos(eqo("conf/vldb/HaasKWY97","fsoE2pQM6G8J")).
pos(eqo("conf/vldb/HaasKWY97","o_WTRsrkx_EJ")).
pos(eqo("conf/vldb/HaasKWY97","yIRQRtTEzSAJ")).
pos(eqo("conf/vldb/HaasNSS95","x70Y3qaTL40J")).
pos(eqo("conf/vldb/HristidisP02","5k-GwvznWRUJ")).
pos(eqo("conf/vldb/ImielinskiB02","IQ_MbfJGh0kJ")).
pos(eqo("conf/vldb/IoannidisLGP96","U04OC6OSBT0J")).
pos(eqo("conf/vldb/IoannidisLGP96","kDWGwVa8dykJ")).
pos(eqo("conf/vldb/IoannidisLGP96","qb-jf_sQ_5kJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/vldb/JaedickeM99","XR50nxmrvFcJ")).
pos(eqo("conf/vldb/JaedickeM99","zh6yaOX2xiQJ")).
pos(eqo("conf/vldb/JensenL01","yUDkYbmDTXIJ")).
pos(eqo("conf/vldb/Jermaine03","393ZqH9szo0J")).
pos(eqo("conf/vldb/JiangWL03","s3bawcAka-EJ")).
pos(eqo("conf/vldb/JonscherD94","1R21hO7j9sQJ")).
pos(eqo("conf/vldb/JonscherD94","yv7vyZT9-YEJ")).
pos(eqo("conf/vldb/KarayannidisTSPMRFEB02","9KiPVAodKnYJ")).
pos(eqo("conf/vldb/KiesslingK02","4XP24_IFvPsJ")).
pos(eqo("conf/vldb/KonigW99","6HMffRHCspAJ")).
pos(eqo("conf/vldb/KonopnickiS95","z5Z9vSNOznMJ")).
pos(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
pos(eqo("conf/vldb/KumarKA97","EhTWppk6No8J")).
pos(eqo("conf/vldb/LakshmananNWZJ02","qfw7Pu1wVcIJ")).
pos(eqo("conf/vldb/LakshmananSS99","RSpmu6WtYBMJ")).
pos(eqo("conf/vldb/LempelM02","DcSYGPdhxwoJ")).
pos(eqo("conf/vldb/Levy96","G7CJNSIBp10J")).
pos(eqo("conf/vldb/LevyRO96","QTsbBZX9zrAJ")).
pos(eqo("conf/vldb/LevyRO96","VYN0FaeVomUJ")).
pos(eqo("conf/vldb/LevyRO96","lrocSfnfPrMJ")).
pos(eqo("conf/vldb/LiCHH97","DmGBKpaiyGEJ")).
pos(eqo("conf/vldb/LiCHH97","mGOC_IQppxQJ")).
pos(eqo("conf/vldb/LitwinNS94","FhyWT1pyLnUJ")).
pos(eqo("conf/vldb/LitwinNS94","Nag68vKZFLgJ")).
pos(eqo("conf/vldb/LongS03","zU4MULiFRrYJ")).
pos(eqo("conf/vldb/MadhavanBR01","5mM4rpgyeNoJ")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/MadhavanH03","mu31RuCR_E4J")).
pos(eqo("conf/vldb/MadhavanH03","ujCYoqKS6BcJ")).
pos(eqo("conf/vldb/MahnkeMS02","VhxIKKG8oWYJ")).
pos(eqo("conf/vldb/ManolescuFK01","O8eIfc2eSjcJ")).
pos(eqo("conf/vldb/ManolescuFK01","ckjlnFHOwd8J")).
pos(eqo("conf/vldb/MarianS03","Bv5AM_5dziMJ")).
pos(eqo("conf/vldb/MarronL01","MiMYGwqrGY8J")).
pos(eqo("conf/vldb/MatthesS94","SxhsoBnl-TsJ")).
pos(eqo("conf/vldb/MiloZ98","a7XtgKiAJFMJ")).
pos(eqo("conf/vldb/MogiK95","39DBh8H18iEJ")).
pos(eqo("conf/vldb/MorimotoFMTY98","31YuS02mFq8J")).
pos(eqo("conf/vldb/NatsevCSLV01","173qcCip5coJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("conf/vldb/NgH94","6OfJSMB4vOcJ")).
pos(eqo("conf/vldb/NgH94","WlNAuSKoGN4J")).
pos(eqo("conf/vldb/NgH94","XfblD8N3jT8J")).
pos(eqo("conf/vldb/NgH94","ltzWlNOJavwJ")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/NinkHR99","tZBIZ9ZHdTkJ")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/Novaretti01","tZtnFoH5lY0J")).
pos(eqo("conf/vldb/PappasC00","BsQtFZrn3fsJ")).
pos(eqo("conf/vldb/PellenkoftLK97","793XPMTdcBEJ")).
pos(eqo("conf/vldb/PellenkoftLK97","mCU3zHcPfCsJ")).
pos(eqo("conf/vldb/PopaVMHF02","J0jQGfOjVZ4J")).
pos(eqo("conf/vldb/PopaVMHF02","kyO1P49ldlEJ")).
pos(eqo("conf/vldb/PopaVMHF02","qJ4lzBFzjdgJ")).
pos(eqo("conf/vldb/PottingerL00","eXceb1SMqE4J")).
pos(eqo("conf/vldb/PottingerL00","llb7DerHoGIJ")).
pos(eqo("conf/vldb/PoulovassilisS94","0BMQ7HirTaUJ")).
pos(eqo("conf/vldb/RamakrishnanGRSWZ95","JAMaus2HrE0J")).
pos(eqo("conf/vldb/Ramanan03","ruVmVa1bhoUJ")).
pos(eqo("conf/vldb/RezendeS98","niRuvMkp4r4J")).
pos(eqo("conf/vldb/RizviH02","sP982xq0nU4J")).
pos(eqo("conf/vldb/RosenthalS94","NFUWsBXtCncJ")).
pos(eqo("conf/vldb/RothOH99","OslUAjJi_B4J")).
pos(eqo("conf/vldb/RothOH99","c-Kalb26vykJ")).
pos(eqo("conf/vldb/SahuguetA99","Mi0eqxwTUwEJ")).
pos(eqo("conf/vldb/SahuguetA99","NrXmzugArgoJ")).
pos(eqo("conf/vldb/SahuguetA99","VT_vPPmEIEIJ")).
pos(eqo("conf/vldb/SantiniG02","J3cfnmFB4lsJ")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/vldb/SavasereON95","CG-_La4oAYkJ")).
pos(eqo("conf/vldb/SavasereON95","N-o3NPu-nbIJ")).
pos(eqo("conf/vldb/SavasereON95","ohjoG-bi4OgJ")).
pos(eqo("conf/vldb/SavasereON95","r-BkIPtpff4J")).
pos(eqo("conf/vldb/SayalCDS02","0acvmJtaI8QJ")).
pos(eqo("conf/vldb/Schoning98","p4Hdrawf0Z0J")).
pos(eqo("conf/vldb/SeifertS02","4-4KVRS7-Y0J")).
pos(eqo("conf/vldb/SeshadriLR96","ifOM4z6uxXUJ")).
pos(eqo("conf/vldb/SilversteinBMU98","_GLI7Izv17cJ")).
pos(eqo("conf/vldb/SistlaYLL95","n1ixxafAD_EJ")).
pos(eqo("conf/vldb/SteenhagenABB94","IgWfWMn1_AAJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","aCZo57LF-4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","n5yJ4y54WbwJ")).
pos(eqo("conf/vldb/Suciu96","D45fvUWVon0J")).
pos(eqo("conf/vldb/SumiyaYTSI95","ZoMjwB0ps2kJ")).
pos(eqo("conf/vldb/SundaraHCAS01","nUFhC9syaNsJ")).
pos(eqo("conf/vldb/Taylor00","Af_4cNCu3MwJ")).
pos(eqo("conf/vldb/TreschPL95","1rPUqMFsS3AJ")).
pos(eqo("conf/vldb/Vaskevitch95","s6Ax0WdZp6IJ")).
pos(eqo("conf/vldb/VelegrakisMP03","JYQUV-XahekJ")).
pos(eqo("conf/vldb/WangSG03","T1TgIax4zVcJ")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/WildfogelY97","uqYakLN84x0J")).
pos(eqo("conf/vldb/WitkowskiBBFGSS03","Oti_CoAPH9IJ")).
pos(eqo("conf/vldb/XieH94","7P8_zVPEW64J")).
pos(eqo("conf/vldb/YangLH03","hUMTG7HNlyAJ")).
pos(eqo("conf/vldb/YuAA03","4bvjebYsdRkJ")).
pos(eqo("conf/vldb/ZemankovaI94","Y1ZxtWV-qeUJ")).
pos(eqo("journals/sigmod/AbererCH02","YUtQ8KXNntYJ")).
pos(eqo("journals/sigmod/Abiteboul99","13NBtnaNfIEJ")).
pos(eqo("journals/sigmod/AbiteboulH95","kUA9e6YP8igJ")).
pos(eqo("journals/sigmod/AilamakiG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AshishK97","GiEo36f1syYJ")).
pos(eqo("journals/sigmod/AtzeniMM97","Hdq-Mlh3fcMJ")).
pos(eqo("journals/sigmod/AtzeniMM97","Mb78Vc7skzMJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BerndtssonH96","8Dj_i69XP60J")).
pos(eqo("journals/sigmod/Bernstein98","AYEI8XDoY9wJ")).
pos(eqo("journals/sigmod/Bohlen95","v5P_NFXdOR8J")).
pos(eqo("journals/sigmod/BrunieK96","spI2g7jFHuYJ")).
pos(eqo("journals/sigmod/BuchnerM98","4J5CvdomBmsJ")).
pos(eqo("journals/sigmod/BuchnerM98","dkWnTbi9xnEJ")).
pos(eqo("journals/sigmod/BuchnerM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D306124%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BunemanLSTW94","lkreWUl_euYJ")).
pos(eqo("journals/sigmod/CasatiDS00","jPx0tvkJ-fUJ")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641006%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChenHKPW94","HTvxhMKB69AJ")).
pos(eqo("journals/sigmod/ClementLGMK97","To_EjIKwfSAJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","cjvOCqu3cJgJ")).
pos(eqo("journals/sigmod/Datta94","PPH2NlobSwsJ")).
pos(eqo("journals/sigmod/Dogac98","diQK7Y_z3XwJ")).
pos(eqo("journals/sigmod/Domingo-FerrerH98","ajq2idLfpHMJ")).
pos(eqo("journals/sigmod/EisenbergM99","LL9Guuh490sJ")).
pos(eqo("journals/sigmod/EisenbergM99","ciavnyh4U8UJ")).
pos(eqo("journals/sigmod/Etzion99","aDxXrqrMy9IJ")).
pos(eqo("journals/sigmod/Fankhauser01","_sltXCfRKhYJ")).
pos(eqo("journals/sigmod/FininJ02","rg8576nvnkUJ")).
pos(eqo("journals/sigmod/FlorescuLM98","FCcDKONgJVYJ")).
pos(eqo("journals/sigmod/FlorescuLM98","rGNdajM-asAJ")).
pos(eqo("journals/sigmod/FlorescuLM98","xfzQQjDwnfcJ")).
pos(eqo("journals/sigmod/FlorescuLM98","ywQwkD1ov7IJ")).
pos(eqo("journals/sigmod/FrankNS02","YeD6vittJSMJ")).
pos(eqo("journals/sigmod/Gallagher94","PVm9r7wHzDAJ")).
pos(eqo("journals/sigmod/GamacheS95","vqgfvx71hgQJ")).
pos(eqo("journals/sigmod/Giorgini03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959084%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GobleR02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Grohe02","RnmBv4e85pMJ")).
pos(eqo("journals/sigmod/Grohe02","jzwiskpRLOUJ")).
pos(eqo("journals/sigmod/Hammer00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Hammer01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Hammer02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D584455%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Hammer03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Han98","Y0GdVVrbzfQJ")).
pos(eqo("journals/sigmod/HasanFV96","m2CCumFeAWgJ")).
pos(eqo("journals/sigmod/HasanFV96","vIBvTfMLL4UJ")).
pos(eqo("journals/sigmod/HasanFV96","ybOBcBXRBqUJ")).
pos(eqo("journals/sigmod/HasanMV96","bLbjFFkQJdIJ")).
pos(eqo("journals/sigmod/JainH94","iQMUP3fkvo4J")).
pos(eqo("journals/sigmod/JainH94","taphZimnV-gJ")).
pos(eqo("journals/sigmod/JenningsNF98","YiZVv5kVDb4J")).
pos(eqo("journals/sigmod/JenningsNF98","vgi1l8lbDcsJ")).
pos(eqo("journals/sigmod/Jhingran00","lrGge6mTVckJ")).
pos(eqo("journals/sigmod/KarlapalemLS95","B_m0Yp4aycUJ")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/Klein94","kG86HB6N1xEJ")).
pos(eqo("journals/sigmod/KuokFW98","3oLpUbHFATsJ")).
pos(eqo("journals/sigmod/KuokFW98","LwZe_nTD__UJ")).
pos(eqo("journals/sigmod/KuokFW98","qyXhN3CrVQ8J")).
pos(eqo("journals/sigmod/LenzVJS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959083%26type%3Dpdf")).
pos(eqo("journals/sigmod/LudascherMM01","16yr6uv8Rn8J")).
pos(eqo("journals/sigmod/MaximilienS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637417%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltonE02","IqEw9ssJ2QAJ")).
pos(eqo("journals/sigmod/MillerHHYHFP01","0ckpOQsv-vAJ")).
pos(eqo("journals/sigmod/Nascimento03","url:http://portal.acm.org/citation.cfm%3Fid%3D776985.776996%26dl%3Dportal%26dl%3DACM%26idx%3D776985%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NgH95","qolJkVC2MoYJ")).
pos(eqo("journals/sigmod/NobleS95","Xh4z_InAi4AJ")).
pos(eqo("journals/sigmod/NobleS95","egn46hGLw7gJ")).
pos(eqo("journals/sigmod/NobleS95","rRvcD6HKhasJ")).
pos(eqo("journals/sigmod/PaepckeGRC00","5ObmwcHCFQsJ")).
pos(eqo("journals/sigmod/PaepckeGRC00","hxFRuvCtvGEJ")).
pos(eqo("journals/sigmod/PapazoglouH99","WbsAK4ZE17YJ")).
pos(eqo("journals/sigmod/PapazoglouH99","d5BG9F7_LGMJ")).
pos(eqo("journals/sigmod/PapianiWDN99","HxmnEeCigX8J")).
pos(eqo("journals/sigmod/RamDD99","kHE9-cv77fwJ")).
pos(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
pos(eqo("journals/sigmod/RoantreeMH99","7-Suml1GqBQJ")).
pos(eqo("journals/sigmod/RoantreeMH99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SantucciT96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245898%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SayginVC01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604271%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ShethM02","B_axrPz8j5EJ")).
pos(eqo("journals/sigmod/SilberschatzZ97","7JRwRy6VapMJ")).
pos(eqo("journals/sigmod/SilberschatzZ97","7ne6Kriy0mEJ")).
pos(eqo("journals/sigmod/SlivinskasJS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565119%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SlivinskasJS02","xTPSs2k_pUIJ")).
pos(eqo("journals/sigmod/SpynsMJ02","GVrDsGpbJGsJ")).
pos(eqo("journals/sigmod/Stacey95","2GKNc8zlLRwJ")).
pos(eqo("journals/sigmod/VassiliadisS99","eGARASwVBrUJ")).
pos(eqo("journals/sigmod/Wade96","AYtrcxExrbkJ")).
pos(eqo("journals/sigmod/Wiegand02","RAcoVQuEzD8J")).
pos(eqo("journals/sigmod/Yang94","sHJ914nPZtUJ")).
pos(eqo("journals/tods/BaralisCP96","hiNs_zWcwlgJ")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/tods/Chen95","1px2xYEVMzwJ")).
pos(eqo("journals/tods/CliffordC94","l4zJZIJGgyQJ")).
pos(eqo("journals/tods/CuiWW00","yWDXpb_76z0J")).
pos(eqo("journals/tods/EiterLLS01","lTwQVB8E7SIJ")).
pos(eqo("journals/tods/FranklinCL97","vqboZ3T4n4AJ")).
pos(eqo("journals/tods/GibbonsMP02","QKnjF3UgncMJ")).
pos(eqo("journals/tods/GoldmanL94","VxMarpzwtzQJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","y5JyKlYjnI4J")).
pos(eqo("journals/tods/Jimenez-PerisPAK03","yj7oLWfPR4gJ")).
pos(eqo("journals/tods/KossmannS00","PnGVbzQCWY0J")).
pos(eqo("journals/tods/LakshmananSS01","FqrVkPwzd3kJ")).
pos(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
pos(eqo("journals/tods/LitwinN96","d7by8a0ArhIJ")).
pos(eqo("journals/tods/LitwinN96","eKvrxzDXW0AJ")).
pos(eqo("journals/tods/LitwinN96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093386%26type%3Dpdf")).
pos(eqo("journals/tods/ParsonsW00","Z5rWzHBxtEEJ")).
pos(eqo("journals/tods/PolyzoisG94","p7x1zGD_bkEJ")).
pos(eqo("journals/tods/ShashaLSV95","0aVKzjogLlAJ")).
pos(eqo("journals/tods/SrivastavaSRN95","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0219026CI")).
pos(eqo("journals/tods/WandSW99","pYtOkFSgdXYJ")).
pos(eqo("journals/tods/WangBBJ97","I-yhgAxp9OQJ")).
pos(eqo("journals/tods/WangBBJ97","kp2T3GlqI3cJ")).
pos(eqo("journals/tods/WangBBJ97","uaaJl906vYoJ")).
pos(eqo("journals/tods/WinslettSQ94","lvZTVlP7s7oJ")).
pos(eqo("journals/vldb/AilamakiDH02","J9MeFW0vDJAJ")).
pos(eqo("journals/vldb/AlbanoGO95","_tswCGHoswMJ")).
pos(eqo("journals/vldb/AlbanoGO95","vrD2aAK6G-wJ")).
pos(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
pos(eqo("journals/vldb/AtkinsonM95","dahaBAYvs5AJ")).
pos(eqo("journals/vldb/BalkirO98","pSf0S8boiZ0J")).
pos(eqo("journals/vldb/BernsteinIR03","url:http://www.springerlink.com/index/RTCC57FUUW3CADRF.pdf")).
pos(eqo("journals/vldb/BernsteinPS00","08d5th2jiqcJ")).
pos(eqo("journals/vldb/BohmAnY97","XsTFqLpfsfgJ")).
pos(eqo("journals/vldb/ChuIT94","IDo3ZQocZE4J")).
pos(eqo("journals/vldb/ConstantopoulosJMV95","_da6PvkQBM4J")).
pos(eqo("journals/vldb/DoanMDDH03","HmE1BtE68dYJ")).
pos(eqo("journals/vldb/EyalM01","ntrSSBumclMJ")).
pos(eqo("journals/vldb/GeorgakopoulosRL94","G85JsnuAjzMJ")).
pos(eqo("journals/vldb/GruserRZZ00","9EBKpmSLc_oJ")).
pos(eqo("journals/vldb/Guting94","2HXoDqKjpXYJ")).
pos(eqo("journals/vldb/Guting94","hoNylhoOWr4J")).
pos(eqo("journals/vldb/GutingS95","A4lUwOD7AeYJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/GutingS95","rjQa8odFpMwJ")).
pos(eqo("journals/vldb/GutingS95","x02_XqK_fGMJ")).
pos(eqo("journals/vldb/HaasCLS97","kUUIJxLeO9QJ")).
pos(eqo("journals/vldb/Halevy01","jeJRCl54kasJ")).
pos(eqo("journals/vldb/IshakbeyogluO98","O9A-15rmzOsJ")).
pos(eqo("journals/vldb/JagadishKNS00","GtXc02EJjCgJ")).
pos(eqo("journals/vldb/JagadishKNS00","W8O7pgTYGTYJ")).
pos(eqo("journals/vldb/KnorrNT00","SggrbO99AJgJ")).
pos(eqo("journals/vldb/LawLG99","TOXrbhbbNJ4J")).
pos(eqo("journals/vldb/Li03","XkdLpQ5x-YIJ")).
pos(eqo("journals/vldb/LiCHH01","Tw8-f4saqb0J")).
pos(eqo("journals/vldb/MedjahedBBNE03","18FFG2HC51oJ")).
pos(eqo("journals/vldb/MedjahedBE03","M0FH31YCEU0J")).
pos(eqo("journals/vldb/MehtaGPN98","7Zf8Y2idDb0J")).
pos(eqo("journals/vldb/MirbelPSTV00","tUEcojf_6BUJ")).
pos(eqo("journals/vldb/NanopoulosM02","icoWjIZ_6IIJ")).
pos(eqo("journals/vldb/Ozsu03","url:http://www.springerlink.com/index/3G9E0YCGLRQFPN89.pdf")).
pos(eqo("journals/vldb/PacittiS00","9ReaNbX2I-IJ")).
pos(eqo("journals/vldb/PacittiS00","UvvmhI5lqbsJ")).
pos(eqo("journals/vldb/PacittiS00","ZmvL3_H6DqUJ")).
pos(eqo("journals/vldb/PacittiS00","vHZqeBwfYL4J")).
pos(eqo("journals/vldb/PeckhamMD95","zOfVTNgEwz0J")).
pos(eqo("journals/vldb/PoulovassilisS96","0BMQ7HirTaUJ")).
pos(eqo("journals/vldb/RafieiM02","kZFfJieudW4J")).
pos(eqo("journals/vldb/RahmB01","707RPzHAB8YJ")).
pos(eqo("journals/vldb/RahmB01","b9ikqvr7Bb4J")).
pos(eqo("journals/vldb/SheikholeslamiCZ00","2GWXn3jT0uwJ")).
pos(eqo("journals/vldb/ShyyASL96","cZ5JZQyhb1MJ")).
pos(eqo("journals/vldb/ShyyASL96","n8EWz5rQancJ")).
pos(eqo("journals/vldb/ShyyASL96","zdkN438QOV4J")).
pos(eqo("journals/vldb/SofferS98","miubKxLrikUJ")).
