neg(eqo("conf/sigmod/AbiteboulCM95","-cQmLk2JnawJ")).
neg(eqo("conf/sigmod/AcharyaAFZ95","9OEjtHuRUzsJ")).
neg(eqo("conf/sigmod/AcharyaGPR99a","0dY1brFaEzgJ")).
neg(eqo("conf/sigmod/AdaliCPS96","uMmcsye0YCkJ")).
neg(eqo("conf/sigmod/AdaliSS99","W-_FOg4UBzoJ")).
neg(eqo("conf/sigmod/AdelbergGK95","6syclrA0QK8J")).
neg(eqo("conf/sigmod/AggarwalWY99","Z8zZYBJYVusJ")).
neg(eqo("conf/sigmod/AggarwalY00","dfSPs7YoyWsJ")).
neg(eqo("conf/sigmod/AgrawalCD02","b9uF_OTTHIEJ")).
neg(eqo("conf/sigmod/AgrawalS00","9ErVOrAc4xgJ")).
neg(eqo("conf/sigmod/Ahn94","url:http://adsabs.harvard.edu/abs/1994mit..reptQ....L")).
neg(eqo("conf/sigmod/Al-KhalifaYJ03","V5G64xtuV4QJ")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","AYtrcxExrbkJ")).
neg(eqo("conf/sigmod/BaruFGHJPW95","ZsN793nKQFsJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","LcWOOOC8hTMJ")).
neg(eqo("conf/sigmod/BerensonBGMOO95","w9IzqrZAa74J")).
neg(eqo("conf/sigmod/BersonGMJ94","GBZiTCbChZQJ")).
neg(eqo("conf/sigmod/BertinoCF01","kdU4iiwLli8J")).
neg(eqo("conf/sigmod/BilirisDGJR94","e3s4OFTeBqwJ")).
neg(eqo("conf/sigmod/BlottRS96","RQXAKvj3fs0J")).
neg(eqo("conf/sigmod/BohmBKK01","Vl7gY6FsOOYJ")).
neg(eqo("conf/sigmod/BraumandlKK99","uYxoiK7dCcoJ")).
neg(eqo("conf/sigmod/BraumandlKK99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
neg(eqo("conf/sigmod/BrodskyK95","_cUSf4sG_28J")).
neg(eqo("conf/sigmod/Brown99","ZTHjFt2qUAYJ")).
neg(eqo("conf/sigmod/Brown99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564792%26type%3Dpdf")).
neg(eqo("conf/sigmod/BunemanM95","ZTBiopwBpLgJ")).
neg(eqo("conf/sigmod/Bussler01","rZ2_UFZ4ALoJ")).
neg(eqo("conf/sigmod/ButtlerLPP01","f6JFkfhawW8J")).
neg(eqo("conf/sigmod/CallanCD99","eWVreKOw_QgJ")).
neg(eqo("conf/sigmod/Carey00","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
neg(eqo("conf/sigmod/CareyK97","NVgd3HFBZAQJ")).
neg(eqo("conf/sigmod/CatarciS94","-qsHBe_0vI4J")).
neg(eqo("conf/sigmod/CatarciS94","frbExwv4DiwJ")).
neg(eqo("conf/sigmod/ChangG99","bZlpjMDZD5UJ")).
neg(eqo("conf/sigmod/Chaudhuri97","Q8UBGvwM2pgJ")).
neg(eqo("conf/sigmod/ChaudhuriD97","4zZ7Lxt4PPIJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","oXTd748VmwMJ")).
neg(eqo("conf/sigmod/ChaudhuriGGM03","4bS3tvLQ-LAJ")).
neg(eqo("conf/sigmod/ChaudhuriGGM03","qfohkpyTawoJ")).
neg(eqo("conf/sigmod/ChaudhuriGGM03","xxkUtjfGpvAJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","u-8KapWYyWkJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","WYgQ_Mhdp9sJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","Xud-KgE4stEJ")).
neg(eqo("conf/sigmod/ChenCPPSTM00","8Yt1Mba9-wQJ")).
neg(eqo("conf/sigmod/ChenDLT00","_uAjDh22Y_EJ")).
neg(eqo("conf/sigmod/ChenGK01","5jCk6Y-HDJ8J")).
neg(eqo("conf/sigmod/ChenGM01","oiIvgWifmIEJ")).
neg(eqo("conf/sigmod/ChenRW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373713%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CherniackZ96","ZsHfcZJwFQQJ")).
neg(eqo("conf/sigmod/ChoG00","s7K6rICx3fkJ")).
neg(eqo("conf/sigmod/ColbyKLMR97","0FohHTWs5toJ")).
neg(eqo("conf/sigmod/ConsensM94","_UkQViQHdGUJ")).
neg(eqo("conf/sigmod/CookWZ94","bhVBJw9Rp3QJ")).
neg(eqo("conf/sigmod/CranorJSS03","nHesT9ADTdEJ")).
neg(eqo("conf/sigmod/CrescenziMM02","SjYOl_fLmMsJ")).
neg(eqo("conf/sigmod/CuiOTS03","-szfOOtC4UwJ")).
neg(eqo("conf/sigmod/DattaDTVSR02","orxvLy4vVEQJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03","7SHvos0YnaYJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03","B55TCVoUsnoJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03a","sfB17Fi4MZsJ")).
neg(eqo("conf/sigmod/DewanSHH94","GUdXGx4blW8J")).
neg(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
neg(eqo("conf/sigmod/DogacTPPLKTK02","yLZEwTZpIQ4J")).
neg(eqo("conf/sigmod/Ellison95","etkRTDHKDRoJ")).
neg(eqo("conf/sigmod/EmbleyJN99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107506%26type%3Dpdf")).
neg(eqo("conf/sigmod/Englert94","KOpz_NXJ3WUJ")).
neg(eqo("conf/sigmod/Englert94","ZsN793nKQFsJ")).
neg(eqo("conf/sigmod/FaloutsosRM94","Gr2vzVzLZTUJ")).
neg(eqo("conf/sigmod/FaloutsosRM94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/FaloutsosRM94","xsaovu54vl4J")).
neg(eqo("conf/sigmod/FaloutsosSTT00","vwcVawlOJn0J")).
neg(eqo("conf/sigmod/FegarasM95","isDzUrHSh-8J")).
neg(eqo("conf/sigmod/FernandezFKLS97","N9NHi5y3K38J")).
neg(eqo("conf/sigmod/FernandezFKLS98","K4-_PRtN_zkJ")).
neg(eqo("conf/sigmod/FlorescuLMS99","z_giOprYRtkJ")).
neg(eqo("conf/sigmod/French95","p-vhRwBl8kcJ")).
neg(eqo("conf/sigmod/FungSG02","5NxOE2HVIkEJ")).
neg(eqo("conf/sigmod/FungSG02","YERfAnxw2RcJ")).
neg(eqo("conf/sigmod/FungSG02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031591%26type%3Dpdf")).
neg(eqo("conf/sigmod/FungSG02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959078%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Gal00","AMqU9oJPrzQJ")).
neg(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
neg(eqo("conf/sigmod/GebhardtJJ97","9mbr0dyW1NgJ")).
neg(eqo("conf/sigmod/GeneserethKD97","Cc188eYk0qMJ")).
neg(eqo("conf/sigmod/Gerber95","gHZiygKDLXsJ")).
neg(eqo("conf/sigmod/Gettys95","D_t6J9U-vYgJ")).
neg(eqo("conf/sigmod/GoldmanW00","bq_WJCWTVeUJ")).
neg(eqo("conf/sigmod/GoldmanW00","dfSPs7YoyWsJ")).
neg(eqo("conf/sigmod/GoldsteinL01","0qMM7muEkC8J")).
neg(eqo("conf/sigmod/GotoK03","CxABHnOorAMJ")).
neg(eqo("conf/sigmod/Gray95","GRB4rsisUxgJ")).
neg(eqo("conf/sigmod/Gray95","HhUCea7De6YJ")).
neg(eqo("conf/sigmod/GreenwaldK01","Ey7Mbh6IdQIJ")).
neg(eqo("conf/sigmod/GriffinH97","UwOPyY_jchkJ")).
neg(eqo("conf/sigmod/GriffinL95","6moFnThDHW0J")).
neg(eqo("conf/sigmod/GrumbachRS98","NXakCefUcdUJ")).
neg(eqo("conf/sigmod/GuhaRS98","qRnB_07lQVMJ")).
neg(eqo("conf/sigmod/HammerGNYBV97","t9nmZzSMVAAJ")).
neg(eqo("conf/sigmod/Han96","8HBfc5L6QdIJ")).
neg(eqo("conf/sigmod/Han96","BrzjCnZCyzAJ")).
neg(eqo("conf/sigmod/HanFHCC94","CZGjStvTkZUJ")).
neg(eqo("conf/sigmod/HanPDW01","2xwKDuA0DI8J")).
neg(eqo("conf/sigmod/HanPDW01","iY5wlS4jsg0J")).
neg(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
neg(eqo("conf/sigmod/HanPY00","fg5EE6R7xYwJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","V6KNPMKdyagJ")).
neg(eqo("conf/sigmod/HellersteinA00","Gsb6dnkFBMoJ")).
neg(eqo("conf/sigmod/HellersteinN96","V1M4safuoecJ")).
neg(eqo("conf/sigmod/HellersteinW02","url:http://portal.acm.org/citation.cfm%3Fid%3D592206.592545")).
neg(eqo("conf/sigmod/HjaltasonS98","I8PUKJzlR8AJ")).
neg(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
neg(eqo("conf/sigmod/HristidisKP01","0PyiTSOYkoQJ")).
neg(eqo("conf/sigmod/HungYK96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381897%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/HwangLYMMGCSS94","WhHHYLOQwXsJ")).
neg(eqo("conf/sigmod/HwangLYMMGCSS94","izvcAVqGLm0J")).
neg(eqo("conf/sigmod/HwangLYMMGCSS94","oABGXQlfGKcJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","Xr2RguUzt-gJ")).
neg(eqo("conf/sigmod/IoannidisL94","umrivnVIoj0J")).
neg(eqo("conf/sigmod/IvesLPST00","rtnpqb22gGcJ")).
neg(eqo("conf/sigmod/JaedickeM98","zh6yaOX2xiQJ")).
neg(eqo("conf/sigmod/Jagadish94","GW1U1s3PwlYJ")).
neg(eqo("conf/sigmod/JagadishKS00","-_FyboGgZkkJ")).
neg(eqo("conf/sigmod/JagadishLMSV99","f5cqkpUXl0kJ")).
neg(eqo("conf/sigmod/JohnsonD03","QlpOU9O3VxEJ")).
neg(eqo("conf/sigmod/JosifovskiSHL02","e3sceOHNES8J")).
neg(eqo("conf/sigmod/KanthAS98","fTbCV3Lh8W0J")).
neg(eqo("conf/sigmod/Keim99","hsRCWQE_sx0J")).
neg(eqo("conf/sigmod/KemperMPS94","HhUCea7De6YJ")).
neg(eqo("conf/sigmod/Kim94","Tlv-A9lX8owJ")).
neg(eqo("conf/sigmod/Kim94","xZQZ4IzUmdoJ")).
neg(eqo("conf/sigmod/KornMZ03","a2wqpKma5J4J")).
neg(eqo("conf/sigmod/KornackerSH98","micx2kyGfKIJ")).
neg(eqo("conf/sigmod/KornackerSH98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058156%26type%3Dpdf")).
neg(eqo("conf/sigmod/KotidisR99","b5uRDGKYrcMJ")).
neg(eqo("conf/sigmod/KriegelMPS01","Ha6Br08Pt1kJ")).
neg(eqo("conf/sigmod/KriegelMPS01","xCbrh53ji4MJ")).
neg(eqo("conf/sigmod/KrishnamurthyBN99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D333608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KrishnanVI96","1tJmHu9hOgQJ")).
neg(eqo("conf/sigmod/LahiriG01","h6URH43MYjIJ")).
neg(eqo("conf/sigmod/LahiriG01","vkUvhZOw-1YJ")).
neg(eqo("conf/sigmod/LarsonG98","yEIHjCL5UykJ")).
neg(eqo("conf/sigmod/Lassettre98","AA42qg6F7RQJ")).
neg(eqo("conf/sigmod/LiGS02","KNEHaqNaiXkJ")).
neg(eqo("conf/sigmod/LiS98","hWiIngXs5I0J")).
neg(eqo("conf/sigmod/LitwinS00","99nKpf7A4uIJ")).
neg(eqo("conf/sigmod/LitwinS00","gG3KqvrYi3IJ")).
neg(eqo("conf/sigmod/LiuPBHPT00","8TcpKdIK1r0J")).
neg(eqo("conf/sigmod/LoR96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Lomet00","xLM0YVcccUgJ")).
neg(eqo("conf/sigmod/LometT03","P7GUGC5bz7wJ")).
neg(eqo("conf/sigmod/LometW98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107503%26type%3Dpdf")).
neg(eqo("conf/sigmod/Maguire01","c9pkCWR5tAQJ")).
neg(eqo("conf/sigmod/Martin94","6VAQeD6muakJ")).
neg(eqo("conf/sigmod/Melling94","_EaTs8FjKq4J")).
neg(eqo("conf/sigmod/MelnikRB03","bkpTodGryDAJ")).
neg(eqo("conf/sigmod/MiloAABN03","KNXVeDITFQsJ")).
neg(eqo("conf/sigmod/MogiK96","hxWB8uQMCdgJ")).
neg(eqo("conf/sigmod/Mohan94","4N472VSotmMJ")).
neg(eqo("conf/sigmod/Mohan94","IGS3TtqfKUgJ")).
neg(eqo("conf/sigmod/Mohan94","xYApP2tZROYJ")).
neg(eqo("conf/sigmod/Moore95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D223859%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/MumickP94","fuRZHDk_Xf8J")).
neg(eqo("conf/sigmod/MumickP94","uS2p93Q_0YcJ")).
neg(eqo("conf/sigmod/NestorovAM98","NVS_rDpScp0J")).
neg(eqo("conf/sigmod/NgLHM99","wO6VeeLIXAsJ")).
neg(eqo("conf/sigmod/Nori00","QVJykO8Yy9UJ")).
neg(eqo("conf/sigmod/Norrie95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D223883%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/OhHP00","TbQE3xcc7m0J")).
neg(eqo("conf/sigmod/OlstonWACELSS98","dMzBLOYl70UJ")).
neg(eqo("conf/sigmod/OzdenRSS96","ZNOZlLbosBMJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","F8CacVSkztEJ")).
neg(eqo("conf/sigmod/PatelD96","oNPjyBZrURgJ")).
neg(eqo("conf/sigmod/Perna95","JzCT0YlD1rUJ")).
neg(eqo("conf/sigmod/PonnekantiK00","AQLsLBctUI4J")).
neg(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
neg(eqo("conf/sigmod/RafieiM97","omhk81_X_mQJ")).
neg(eqo("conf/sigmod/RamanH02","PZSlVNV6e9IJ")).
neg(eqo("conf/sigmod/Ramanan02","VGe-IBWyMm4J")).
neg(eqo("conf/sigmod/RamaswamyRS00","mX-oqtUEPZ4J")).
neg(eqo("conf/sigmod/RaoBG96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D984537%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RaoR00","nD_Yjp9TNuIJ")).
neg(eqo("conf/sigmod/RaoR98","uHX7_KIw8uYJ")).
neg(eqo("conf/sigmod/RaoZML02","SFs0XOMPphIJ")).
neg(eqo("conf/sigmod/ReissK03","iudgysm8LcgJ")).
neg(eqo("conf/sigmod/RodriguezR00","ZXB1xI2h-HkJ")).
neg(eqo("conf/sigmod/SchusterW01","-iis302p2MkJ")).
neg(eqo("conf/sigmod/SchusterW01","GbKwENZEG40J")).
neg(eqo("conf/sigmod/SchusterW01","JrzYDC75O68J")).
neg(eqo("conf/sigmod/ShanmugasundaramNSR99","eQjFv7QxsQQJ")).
neg(eqo("conf/sigmod/Spiro98","TUdCqoRkkcsJ")).
neg(eqo("conf/sigmod/SrikantA96","UAO4T_2ylPkJ")).
neg(eqo("conf/sigmod/Stonebraker98","0s68uZWLQogJ")).
neg(eqo("conf/sigmod/Stonebraker98","ZflHZYysWAsJ")).
neg(eqo("conf/sigmod/StonebrakerH01","Ikk1rb4o66UJ")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","h95306-8rjEJ")).
neg(eqo("conf/sigmod/TomasicGS94","lEQ4uPFcizcJ")).
neg(eqo("conf/sigmod/TrisoliniLN99","NFUWsBXtCncJ")).
neg(eqo("conf/sigmod/Vaskevitch94","x-k7JsynxU4J")).
neg(eqo("conf/sigmod/WhiteD94","5Trj9q_RI8YJ")).
neg(eqo("conf/sigmod/WhitneyS01","6ituoubvieMJ")).
neg(eqo("conf/sigmod/WilschutFA95","H5IdN0_MQw4J")).
neg(eqo("conf/sigmod/WilschutFA95","ycyOGNNmFUkJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","5tRy51B5G3MJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","N3Bry6sSMw8J")).
neg(eqo("conf/sigmod/ZaharioudakisCLPU00","eRSkDzxP1JcJ")).
neg(eqo("conf/sigmod/ZhouR02","J1CLaoEhUTwJ")).
neg(eqo("conf/sigmod/ZhuS03","iuyRrJJDBcIJ")).
neg(eqo("conf/vldb/AcharyaFZ96","ccEW59Ac84MJ")).
neg(eqo("conf/vldb/AgrawalS94","a1CLM5GoVtYJ")).
neg(eqo("conf/vldb/AlsabtiRS97","wP_GYyvWXaQJ")).
neg(eqo("conf/vldb/AmirKN01","msRerFt292wJ")).
neg(eqo("conf/vldb/AmmannJR95","G4Js4jqjua0J")).
neg(eqo("conf/vldb/AnSVKIG01","Zyp4RN261u4J")).
neg(eqo("conf/vldb/AnanthakrishnaCG02","_RMZmSBR_PUJ")).
neg(eqo("conf/vldb/AnciauxBP03","gYELZxhiJx8J")).
neg(eqo("conf/vldb/AndreiV01","Ms4IJoI6-34J")).
neg(eqo("conf/vldb/ArgePRSV98","Vg-xjJtfd_0J")).
neg(eqo("conf/vldb/ArgePRSV98","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/AshwinGG02","DK1HpJEO_mwJ")).
neg(eqo("conf/vldb/AshwinGG02","iGlztgiSTe4J")).
neg(eqo("conf/vldb/BamfordBKM98","uS43GVHJ3jQJ")).
neg(eqo("conf/vldb/Baru96","THsXADj2A2oJ")).
neg(eqo("conf/vldb/BaulierBKS98","oZnwIDQVeJ0J")).
neg(eqo("conf/vldb/Baumann03","pJ2UEKVG_hoJ")).
neg(eqo("conf/vldb/BenediktCFRZZ02","7xe6Gp9fIEEJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","gGTcBcX5FKsJ")).
neg(eqo("conf/vldb/BerckenS96","S3sZeGwdAuYJ")).
neg(eqo("conf/vldb/Bernstein94","AYEI8XDoY9wJ")).
neg(eqo("conf/vldb/Bernstein94","ilZMdAv1KCUJ")).
neg(eqo("conf/vldb/BettiniJWW02","ghIMekzCkMQJ")).
neg(eqo("conf/vldb/Blum99","EYfIweE8pHEJ")).
neg(eqo("conf/vldb/BohannonLRSSS97","Vj1kbPjzSHwJ")).
neg(eqo("conf/vldb/BohlenSS96","EAZ5Gz22bIUJ")).
neg(eqo("conf/vldb/BohmMSW01","hjuGWEzCIB4J")).
neg(eqo("conf/vldb/BouguettayaEMO01","3n8xQr4O5aUJ")).
neg(eqo("conf/vldb/Brodie03","dLxEC1zbITQJ")).
neg(eqo("conf/vldb/Campbell99","qJ4lzBFzjdgJ")).
neg(eqo("conf/vldb/CareyKRLABFLOPQRSSUVWY01","J-KuIA1V8zsJ")).
neg(eqo("conf/vldb/CasatiDGS01","xb63RaGQYmYJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","zmBMRUNv8sQJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","TqXFdQBTW6kJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","lXZzpSDzRnwJ")).
neg(eqo("conf/vldb/ChaudhuriS96","X79ymH_j8zkJ")).
neg(eqo("conf/vldb/ChavdaW97","E9AsPVyCDlMJ")).
neg(eqo("conf/vldb/ChavdaW97","ojCqQ9yEGAUJ")).
neg(eqo("conf/vldb/ChengGKLLQS99","g220AYhyDPYJ")).
neg(eqo("conf/vldb/CherniackZ98","cSEKNVCkb3sJ")).
neg(eqo("conf/vldb/ChienVZTZ02","SgUc7R0GR6QJ")).
neg(eqo("conf/vldb/Chiueh94","nOF-SuSEaaEJ")).
neg(eqo("conf/vldb/ChoALS02","94TyP9PsptAJ")).
neg(eqo("conf/vldb/ChoALS02","jj64xkk75ZIJ")).
neg(eqo("conf/vldb/ChoN02","casX2njLbDIJ")).
neg(eqo("conf/vldb/CliftonFHKLS03","url:http://www.springerlink.com/index/L56M40V76870H0W6.pdf")).
neg(eqo("conf/vldb/Deshpande00","oIFrkS2rPrcJ")).
neg(eqo("conf/vldb/DoR02","iGKoS8f6vTIJ")).
neg(eqo("conf/vldb/FangSGMU98","dm3xutmyi_0J")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","YCNz-qSGj9kJ")).
neg(eqo("conf/vldb/GantiLR00","yfqsf7gLpzQJ")).
neg(eqo("conf/vldb/GaoS03","_dOpWA3QWOEJ")).
neg(eqo("conf/vldb/GarciaLL98","yTegJEaoT4MJ")).
neg(eqo("conf/vldb/Gibbons01","A4lUwOD7AeYJ")).
neg(eqo("conf/vldb/GilbertKMS01","Z9rLcqMb4ikJ")).
neg(eqo("conf/vldb/GinisHKMT97","b6wj1DwIXVEJ")).
neg(eqo("conf/vldb/GoldmanW97","_lvdMphdfvEJ")).
neg(eqo("conf/vldb/GottlobKP02","kdxKq47tgowJ")).
neg(eqo("conf/vldb/GoyalHSS95","2sGH4SLcdL4J")).
neg(eqo("conf/vldb/GravanoG95","4HVB6aRvsk8J")).
neg(eqo("conf/vldb/Greco98","Jp9LEvXjiJAJ")).
neg(eqo("conf/vldb/Greco98","nbyDOftnxewJ")).
neg(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
neg(eqo("conf/vldb/HageJPST03","JFDVe7g1QVkJ")).
neg(eqo("conf/vldb/Hallmark95","p_LYmS9ONoYJ")).
neg(eqo("conf/vldb/HammadFAE03","biVrK7MrU4QJ")).
neg(eqo("conf/vldb/HelmerWM98","8-HpAN0xpjcJ")).
neg(eqo("conf/vldb/HerlekarDRGS02","DPEmE3E5xzoJ")).
neg(eqo("conf/vldb/HoelS95","7KsyQNj74A4J")).
neg(eqo("conf/vldb/HoelS95","Sc0JK0gBvQEJ")).
neg(eqo("conf/vldb/HoskingC99","8Pt19BiLeHEJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","S53lfd4tC1kJ")).
neg(eqo("conf/vldb/IlyasAE03","_RMZmSBR_PUJ")).
neg(eqo("conf/vldb/ImielinskiB02","7qv9IC8F_WQJ")).
neg(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
neg(eqo("conf/vldb/IshikawaSF98","9MDCp_a1roUJ")).
neg(eqo("conf/vldb/JagadishLRSS94","EIeV9avucy0J")).
neg(eqo("conf/vldb/JiangSLB00","kMnXGU8LNgEJ")).
neg(eqo("conf/vldb/Johnson99","g39HMDLUxp0J")).
neg(eqo("conf/vldb/JoshiBLL98","W-dtWIGKQHcJ")).
neg(eqo("conf/vldb/KamelF94","A7WoAzxOJ9YJ")).
neg(eqo("conf/vldb/KaushikBNS02","W_b-Eo5VaOgJ")).
neg(eqo("conf/vldb/King02","aK4zTCdP-xcJ")).
neg(eqo("conf/vldb/KnorrN98","VhVTUQPQYq4J")).
neg(eqo("conf/vldb/KnorrN98","oCPpSbHhL3IJ")).
neg(eqo("conf/vldb/Koch03","3k61gi_ld_UJ")).
neg(eqo("conf/vldb/Kornacker99","O81USJg2EhwJ")).
neg(eqo("conf/vldb/Korth95","LyurghK6iekJ")).
neg(eqo("conf/vldb/Korth95","kpPDCQy-JSQJ")).
neg(eqo("conf/vldb/Kotidis01","W8O7pgTYGTYJ")).
neg(eqo("conf/vldb/Kotidis01","iyHWaC-OBo0J")).
neg(eqo("conf/vldb/KraftSRM03","dkdyz41-JesJ")).
neg(eqo("conf/vldb/LabioG96","nsN_2BnT_mMJ")).
neg(eqo("conf/vldb/LakshmananPH02","mucWlNKEUwoJ")).
neg(eqo("conf/vldb/LamKR02","GdvZvvRTXIAJ")).
neg(eqo("conf/vldb/LevyMS94","oHdZmd_4AaAJ")).
neg(eqo("conf/vldb/LiM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375755%26type%3Dpdf%26dl%3DGUIDE%26dl%3DGUIDE%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/LingLL00","SNX-QhXeObMJ")).
neg(eqo("conf/vldb/LuoN01","TRWSf77xoWsJ")).
neg(eqo("conf/vldb/MatiasVW00","EtmLqag8Y3cJ")).
neg(eqo("conf/vldb/MeccaCM01","wY2YGWDeOSYJ")).
neg(eqo("conf/vldb/MendelzonV00","hsXG2LUIyWQJ")).
neg(eqo("conf/vldb/MendelzonV00","vQVMrRkJwSIJ")).
neg(eqo("conf/vldb/Mihalisin98","lWY2GRwhJxYJ")).
neg(eqo("conf/vldb/MillerHH00","JWT6z9eSHQ8J")).
neg(eqo("conf/vldb/Moerkotte98","xsV7dkJi-YMJ")).
neg(eqo("conf/vldb/Mohan01","C-yzbvoAg00J")).
neg(eqo("conf/vldb/Mohan01","p0wBdI_JiXMJ")).
neg(eqo("conf/vldb/NatsevCSLV01","lD7OgF3Xw6wJ")).
neg(eqo("conf/vldb/NetzCBF00","ANV3iCMnGQYJ")).
neg(eqo("conf/vldb/NishioSTTL01","gC9e7htdT7UJ")).
neg(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
neg(eqo("conf/vldb/OoiYTJ01","RFEE_MNM8IUJ")).
neg(eqo("conf/vldb/OzsuVU98","GIlUG9H3gUUJ")).
neg(eqo("conf/vldb/PalpanasSCP02","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/PantiSG00","gBTmOEmEzWYJ")).
neg(eqo("conf/vldb/PappasC00","_Z_KQsngcxoJ")).
neg(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
neg(eqo("conf/vldb/PoosalaI97","Qmv55n1HpkAJ")).
neg(eqo("conf/vldb/RaghavanG01","hPWDomB8y6wJ")).
neg(eqo("conf/vldb/RamaswamyMS98","54w4cIKL11UJ")).
neg(eqo("conf/vldb/RamaswamyMS98","p22KQv7U_aYJ")).
neg(eqo("conf/vldb/RastogiS98","AyWUeJ5k2IoJ")).
neg(eqo("conf/vldb/RossS97","uHX7_KIw8uYJ")).
neg(eqo("conf/vldb/RothS97","KsQP5X9AyUgJ")).
neg(eqo("conf/vldb/RoussopoulosK98","qvK3zyPsVq4J")).
neg(eqo("conf/vldb/Sarawagi00","7GpYSr7yaWAJ")).
neg(eqo("conf/vldb/Sarawagi95","ut4Y99B1094J")).
neg(eqo("conf/vldb/SarawagiS96","3k61gi_ld_UJ")).
neg(eqo("conf/vldb/SavasereON95","y1hmJODjq7UJ")).
neg(eqo("conf/vldb/SayalCDS02","XuhtK-DsK6gJ")).
neg(eqo("conf/vldb/SchaeferBBJ00","E9AsPVyCDlMJ")).
neg(eqo("conf/vldb/SeshadriLR96","cL_OKIQDvmQJ")).
neg(eqo("conf/vldb/ShaferA97","O4UcgdEM7vYJ")).
neg(eqo("conf/vldb/Shaw98","prAhtXw7Yf8J")).
neg(eqo("conf/vldb/SimonD95","GauriO4hIWwJ")).
neg(eqo("conf/vldb/SrikantA95","5RM0cJ401eIJ")).
neg(eqo("conf/vldb/StillgerLMK01","R43ssyRp674J")).
neg(eqo("conf/vldb/StohrMR00","xm3TG_Hr6agJ")).
neg(eqo("conf/vldb/Suciu96","8bcTG9YsbskJ")).
neg(eqo("conf/vldb/Suciu96","Ikk1rb4o66UJ")).
neg(eqo("conf/vldb/TanEO01","CPgFBlL9t_QJ")).
neg(eqo("conf/vldb/Toivonen96","yd2dxAbjvTAJ")).
neg(eqo("conf/vldb/TreschPL95","rCxAgmY4ptEJ")).
neg(eqo("conf/vldb/TriantafillouP97","Z0l7zr67jb0J")).
neg(eqo("conf/vldb/Tygar98","wFdjOo3j3r8J")).
neg(eqo("conf/vldb/UrhanF01","mEbYDdSNeS8J")).
neg(eqo("conf/vldb/VermeerA96","-NBU7dxYkiMJ")).
neg(eqo("conf/vldb/ViverosNR96","D45fvUWVon0J")).
neg(eqo("conf/vldb/ViverosNR96","spI2g7jFHuYJ")).
neg(eqo("conf/vldb/Wang95","YHUN_yiwIOUJ")).
neg(eqo("conf/vldb/WangZ00","FYaY6FhJVxUJ")).
neg(eqo("conf/vldb/WangZL03","tbuNzuDUSFYJ")).
neg(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
neg(eqo("conf/vldb/WiesnerK01","s_ZBkg2D6VoJ")).
neg(eqo("conf/vldb/WuFSP00","T7FkQT7t6WUJ")).
neg(eqo("conf/vldb/XinHLW03","hBrgosYDi3oJ")).
neg(eqo("conf/vldb/YagoubFIV00a","4j8fh4q5kFEJ")).
neg(eqo("conf/vldb/ZellerK02","4HVB6aRvsk8J")).
neg(eqo("conf/vldb/ZhouR03","MvbChqWgFawJ")).
neg(eqo("conf/vldb/ZhouR03","bLI5eWO9AAsJ")).
neg(eqo("conf/vldb/ZirintsisKM99","c-MP8R47zVIJ")).
neg(eqo("conf/vldb/ZouS98","DYFIQvOg7rgJ")).
neg(eqo("journals/sigmod/Aberer02b","igM_dVQLhtEJ")).
neg(eqo("journals/sigmod/Aberer03c","347oyb_b7DAJ")).
neg(eqo("journals/sigmod/Abiteboul99","2bafas1GXWQJ")).
neg(eqo("journals/sigmod/Abiteboul99","BoSfRzB01ZQJ")).
neg(eqo("journals/sigmod/AilamakiG03","BWV2Oys1VXsJ")).
neg(eqo("journals/sigmod/Anonymous96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373713%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AtzeniMM97","sARbiNQPPWQJ")).
neg(eqo("journals/sigmod/BallMRZ02","DfOLEzMoEaEJ")).
neg(eqo("journals/sigmod/BarbaraCJW01","vG5FK8BJkZgJ")).
neg(eqo("journals/sigmod/BerraNT95","DDyZXuEtGiwJ")).
neg(eqo("journals/sigmod/BertinoEH03","oRWtcCo6xlAJ")).
neg(eqo("journals/sigmod/Bertram94","hSqlyqC11TgJ")).
neg(eqo("journals/sigmod/Bestavros96","eLENYy7eMqIJ")).
neg(eqo("journals/sigmod/Bohlen95","-fKxr07m604J")).
neg(eqo("journals/sigmod/Bohlen95","WnwPjh0a0twJ")).
neg(eqo("journals/sigmod/Bohlen95","v5P_NFXdOR8J")).
neg(eqo("journals/sigmod/BorgidaCS98","Bw0BeUCcPJcJ")).
neg(eqo("journals/sigmod/ButtlerCCFHLPRX02","mClzTQppJE4J")).
neg(eqo("journals/sigmod/CaleroPR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Camps96","oMHbGkwztk8J")).
neg(eqo("journals/sigmod/CatarciC96","nrZ9v864SDUJ")).
neg(eqo("journals/sigmod/CfP99","SFs0XOMPphIJ")).
neg(eqo("journals/sigmod/CfP99","kgl4TaGT2mIJ")).
neg(eqo("journals/sigmod/Chen94","3nXBlVy0-HUJ")).
neg(eqo("journals/sigmod/ChienTZ01","CER66z1lh0MJ")).
neg(eqo("journals/sigmod/ChristoffelPSL98","Wqb3BIk1SpkJ")).
neg(eqo("journals/sigmod/CiliaB02","djHxzF4Ao28J")).
neg(eqo("journals/sigmod/ConstantopoulosCP01","KHACQIbQzNYJ")).
neg(eqo("journals/sigmod/CoxEH96","EvsGKxyp5OkJ")).
neg(eqo("journals/sigmod/CuiJO02","UYIeOe280OwJ")).
neg(eqo("journals/sigmod/Danish98","O5PR3qesmekJ")).
neg(eqo("journals/sigmod/Datta94","I8PUKJzlR8AJ")).
neg(eqo("journals/sigmod/DemersGRTY03","7ovBf4FndXsJ")).
neg(eqo("journals/sigmod/DiazJPa94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974138%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Dogac96","j6v2b9hN-R4J")).
neg(eqo("journals/sigmod/Dogac98","GyhnzPMUQKAJ")).
neg(eqo("journals/sigmod/DogacAOD95","BLsUQMD2pA4J")).
neg(eqo("journals/sigmod/DunhamH95","R5GvmgnnwBIJ")).
neg(eqo("journals/sigmod/EisenbergM98a","-RAYAJbKLNUJ")).
neg(eqo("journals/sigmod/EisenbergM99","wgK6p4mDSIMJ")).
neg(eqo("journals/sigmod/EisenbergM99a","ne4v3zrmFSQJ")).
neg(eqo("journals/sigmod/FifeG03","xfzQQjDwnfcJ")).
neg(eqo("journals/sigmod/FlorescuLM98","28BvOA9bYjAJ")).
neg(eqo("journals/sigmod/FlorescuLM98","JfsgE81fWdkJ")).
neg(eqo("journals/sigmod/Fong97","naOUejlqjs0J")).
neg(eqo("journals/sigmod/FowlerPNB99","9OcrAEypDhMJ")).
neg(eqo("journals/sigmod/Franklin00","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Franklin00a","f-u1S3gbi2UJ")).
neg(eqo("journals/sigmod/Franklin98","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/Franklin98","iDBvvrHwj7YJ")).
neg(eqo("journals/sigmod/Franklin99a","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/FrewD97","url:http://portal.acm.org/citation.cfm%3Fid%3D50225")).
neg(eqo("journals/sigmod/Geller02","HMEvi2ebAv0J")).
neg(eqo("journals/sigmod/GobleR02","2PwEpiJIqgIJ")).
neg(eqo("journals/sigmod/GobleR02a","9gAyBKYxhpgJ")).
neg(eqo("journals/sigmod/GobleR02a","B-u4advaVBkJ")).
neg(eqo("journals/sigmod/GottlobKP03","CCP9RsKObC4J")).
neg(eqo("journals/sigmod/HalkidiBV02","tQZWeE_nsa0J")).
neg(eqo("journals/sigmod/Han98","AOXjUq9H2cwJ")).
neg(eqo("journals/sigmod/Han98","GeMycbLXZUkJ")).
neg(eqo("journals/sigmod/Han98","hajx9Chg0-EJ")).
neg(eqo("journals/sigmod/Hanson99","IREL9rBYR48J")).
neg(eqo("journals/sigmod/HasanFV96","ybOBcBXRBqUJ")).
neg(eqo("journals/sigmod/HummerLW02","-DvIEFe1vQ0J")).
neg(eqo("journals/sigmod/Jagadish00","gDFpwto83b4J")).
neg(eqo("journals/sigmod/Jarke95","jSdtciNSHbUJ")).
neg(eqo("journals/sigmod/JukicV97","yZbJS0Cd6cAJ")).
neg(eqo("journals/sigmod/KambhampatiK03","xfzQQjDwnfcJ")).
neg(eqo("journals/sigmod/KantM00","hvtR9cqi8REJ")).
neg(eqo("journals/sigmod/KeetonPH98","9bRPA_aTYh4J")).
neg(eqo("journals/sigmod/Keim96","AF9vuEJOr6cJ")).
neg(eqo("journals/sigmod/Kosch02","1WWaLnHadZMJ")).
neg(eqo("journals/sigmod/KramerNKRLKLZ97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D984537%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Labrinidis01","UaNb6Hq0RUsJ")).
neg(eqo("journals/sigmod/LawderK01","wKxK3oAcP_4J")).
neg(eqo("journals/sigmod/LeeC00","bEu_llku9NMJ")).
neg(eqo("journals/sigmod/LenzeriniNNS01","lTNqBpBUA5sJ")).
neg(eqo("journals/sigmod/Liu01","skOc65LTInYJ")).
neg(eqo("journals/sigmod/Liu01","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Liu02","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Liu02a","EhycjBB7pb8J")).
neg(eqo("journals/sigmod/Liu02c","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Liu03c","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Manola98","4wUTpq8VhJYJ")).
neg(eqo("journals/sigmod/McClatcheyV97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MeersmanS02","rqTxO0ix3qUJ")).
neg(eqo("journals/sigmod/MeltzerC98","B0juzGSCqrIJ")).
neg(eqo("journals/sigmod/NadoH97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/NejdlSS03","A2f8fVoGhZkJ")).
neg(eqo("journals/sigmod/ONeilG95","dGbuUkhWNhMJ")).
neg(eqo("journals/sigmod/OrlandicLS02","WscYgOrzaTMJ")).
neg(eqo("journals/sigmod/OrlandicLS02","rMV2yNFwvggJ")).
neg(eqo("journals/sigmod/Ozsu03a","Qz8ImlM7dwcJ")).
neg(eqo("journals/sigmod/PaepckeGRC00","jfjQTKJ_iyUJ")).
neg(eqo("journals/sigmod/PitouraAPSV03","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
neg(eqo("journals/sigmod/Qian94a","M04eDZqVLgQJ")).
neg(eqo("journals/sigmod/Qian94a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187462%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RafanelliBT96","7tWlPOyjEdQJ")).
neg(eqo("journals/sigmod/RamDD99","eQPLe8gg-mIJ")).
neg(eqo("journals/sigmod/RashidS00","e0GH54HirssJ")).
neg(eqo("journals/sigmod/RisheSBDOALOSS95","KAf2DUUVabIJ")).
neg(eqo("journals/sigmod/RosenthalS99","c6lzPzSWbKAJ")).
neg(eqo("journals/sigmod/RosenthalSMBTL95","-_FyboGgZkkJ")).
neg(eqo("journals/sigmod/RossAA02","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/RossCGJBV99","uxyYuvZlGhIJ")).
neg(eqo("journals/sigmod/RossGR03","H5IdN0_MQw4J")).
neg(eqo("journals/sigmod/RossKMV02","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/Scholl01","0H7oJ5HZJQgJ")).
neg(eqo("journals/sigmod/Segev94a","p0QHT_9_NSkJ")).
neg(eqo("journals/sigmod/ShethBS99","6zK8ZOO8HUsJ")).
neg(eqo("journals/sigmod/ShethBS99","aCZ0SOXTz5oJ")).
neg(eqo("journals/sigmod/SlivinskasJS02","8lafnpE84ocJ")).
neg(eqo("journals/sigmod/Snodgrass02","i7dLYB6NnW0J")).
neg(eqo("journals/sigmod/Snodgrass94","_qopgNiYmXQJ")).
neg(eqo("journals/sigmod/Snodgrass97a","nMt5JG_iuVAJ")).
neg(eqo("journals/sigmod/Snodgrass99a","faJ3Wc9vlzEJ")).
neg(eqo("journals/sigmod/Snodgrass99b","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/SommerGB02","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637432%26coll%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Suciu02","8bcTG9YsbskJ")).
neg(eqo("journals/sigmod/SureSS02","1NZsxf_zwF4J")).
neg(eqo("journals/sigmod/TsotrasK96","Pvh4vhSxHaIJ")).
neg(eqo("journals/sigmod/Wade96","zw3-t-veNvAJ")).
neg(eqo("journals/sigmod/Wedekind94","785fjqMo-nkJ")).
neg(eqo("journals/sigmod/Wedekind94","78cZTDj9GkkJ")).
neg(eqo("journals/sigmod/Widom95","a26F7CKv-SwJ")).
neg(eqo("journals/sigmod/Widom96b","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Wiegand02","uoZUYDuROa8J")).
neg(eqo("journals/sigmod/Winslett01a","ASxgVVDtcXEJ")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/citation.cfm%3Fid%3D507338.507358%26coll%3DGUIDE%26dl%3Dacm%26idx%3D984378%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/WinslettCDHZZ02","url:http://portal.acm.org/citation.cfm%3Fid%3D101077.390002%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
neg(eqo("journals/sigmod/YeungHL94","I4OQfQZRU1gJ")).
neg(eqo("journals/tods/BaekgaardM95","BVUWvwkj9CsJ")).
neg(eqo("journals/tods/Chen95","Gj_1DewUbPgJ")).
neg(eqo("journals/tods/Chen95","Z8jYTylZtkEJ")).
neg(eqo("journals/tods/Chomicki95","uqYakLN84x0J")).
neg(eqo("journals/tods/CliffordC94","j4O-xhs1QAgJ")).
neg(eqo("journals/tods/FegarasM00","8ZaEIj0imacJ")).
neg(eqo("journals/tods/FukudaMMT01","_7GYrw1HJlYJ")).
neg(eqo("journals/tods/FukudaMMT01","cFMtMf7bLzIJ")).
neg(eqo("journals/tods/FukudaMMT01","k6ukzru4nX8J")).
neg(eqo("journals/tods/GuoSW96","SHeVWt2HhgEJ")).
neg(eqo("journals/tods/GuoSW96","uQN3b_IsnKsJ")).
neg(eqo("journals/tods/HjaltasonS03","url:http://portal.acm.org/citation.cfm%3Fid%3D957137%26dl%3DACM%26coll%3Dportal%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/HjaltasonS99","9Wan9sPNUAYJ")).
neg(eqo("journals/tods/IoannidisR95","ocU8aFaXuPwJ")).
neg(eqo("journals/tods/Jimenez-PerisPAK03","ghbPaRnqFeEJ")).
neg(eqo("journals/tods/Keen97","lLKf_jtuViMJ")).
neg(eqo("journals/tods/Keen97","qN1APPIGZMMJ")).
neg(eqo("journals/tods/KemmeA00","wiUPadLpCvoJ")).
neg(eqo("journals/tods/Kim94","mD90fw6IrtIJ")).
neg(eqo("journals/tods/LeveneL99","7gzs66FFgq8J")).
neg(eqo("journals/tods/LiC01","gGm5xFGbl2AJ")).
neg(eqo("journals/tods/LitwinN96","qzeu5GQ_2p0J")).
neg(eqo("journals/tods/LiuHD98","HUFJqSyD5SsJ")).
neg(eqo("journals/tods/MamoulisP01","fXHqHRgpG8sJ")).
neg(eqo("journals/tods/MelnikG03","qjl6LeTJRroJ")).
neg(eqo("journals/tods/PolyzoisG94","9rnT6AgafkoJ")).
neg(eqo("journals/tods/Snodgrass01a","8vtUokULDisJ")).
neg(eqo("journals/tods/SrivastavaSRN95","yPVmmJpyYw4J")).
neg(eqo("journals/vldb/AbadiCCCCLSTZ03","A8qZGxwlDiYJ")).
neg(eqo("journals/vldb/AbbadiSW01","M3ELKAZ4wBMJ")).
neg(eqo("journals/vldb/AbbadiSW01","TriLgFt_ETgJ")).
neg(eqo("journals/vldb/AbbadiSW01","cDN9oOqsTE0J")).
neg(eqo("journals/vldb/AbbadiSW01","url:http://www.springerlink.com/index/CWANCL0VWN1MKL0M.pdf")).
neg(eqo("journals/vldb/AguileraCMVV02","eZwzDZ7QhzoJ")).
neg(eqo("journals/vldb/AnGSVKI02","kBzZ1GUoa1AJ")).
neg(eqo("journals/vldb/Antoshenkov97","RllxrA_MxREJ")).
neg(eqo("journals/vldb/AntoshenkovZ96","B8_0dK37qcsJ")).
neg(eqo("journals/vldb/AntoshenkovZ96","N8syKKPN6IoJ")).
neg(eqo("journals/vldb/AtzeniM00","GBXjNUn2GJEJ")).
neg(eqo("journals/vldb/BraumandlCKK00","kreFjtCAZ7QJ")).
neg(eqo("journals/vldb/C95a","QLeWwLgl5KsJ")).
neg(eqo("journals/vldb/C95a","url:http://portal.acm.org/citation.cfm%3Fid%3D615232.615235%26dl%3DGUIDE%26dl%3DGUIDE%26type%3Dissue%26idx%3DJ869%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DThe%2520VLDB%2520Journal%2520%2526mdash%253B%2520The%2520International%2520Journal%2520on%2520Very%2520Large%2520Data%2520Bases%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/ChakrabartiDAR98","QyBDbs7EpmsJ")).
neg(eqo("journals/vldb/ChanFGR02","e5Gm5upjQnkJ")).
neg(eqo("journals/vldb/ChangG01","03teGNXTdh4J")).
neg(eqo("journals/vldb/Cobb97","Bqr37pufJbUJ")).
neg(eqo("journals/vldb/CuiW03","4j9Ur0dYEHgJ")).
neg(eqo("journals/vldb/DerrMP94","hAqEljGAcFsJ")).
neg(eqo("journals/vldb/EvangelidisS97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271095%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/EyalM01","1ZsldF-YhNsJ")).
neg(eqo("journals/vldb/EyalM01","yaY3OF1lVEsJ")).
neg(eqo("journals/vldb/FahlR97","m1ECCPPPUE8J")).
neg(eqo("journals/vldb/FernandezFLS00","ek26aiEheesJ")).
neg(eqo("journals/vldb/GeorgeH00","Ah9B3bWU0jEJ")).
neg(eqo("journals/vldb/GeorgeH00","iiAXqIhbnNIJ")).
neg(eqo("journals/vldb/GruserRZZ00","0BRPIr5yd80J")).
neg(eqo("journals/vldb/GutingS95","x02_XqK_fGMJ")).
neg(eqo("journals/vldb/Halevy02","3rwpLn-qoCoJ")).
neg(eqo("journals/vldb/HansonCDERTX98","wP_GYyvWXaQJ")).
neg(eqo("journals/vldb/HuangDT99","url:http://www.springerlink.com/index/T41121PP41071878.pdf")).
neg(eqo("journals/vldb/JagadishACLNPPSWWY02","m7ksiYu5pi4J")).
neg(eqo("journals/vldb/JiangE98","ufqCs6N_orAJ")).
neg(eqo("journals/vldb/KabraD99","EiA-0VkeBT4J")).
neg(eqo("journals/vldb/KnorrNT00","SggrbO99AJgJ")).
neg(eqo("journals/vldb/LawLG99","xmE1380_4E4J")).
neg(eqo("journals/vldb/Li03","3R5ShNb_tt8J")).
neg(eqo("journals/vldb/LinJF94","url:http://doi.wiley.com/10.1002/he.155")).
neg(eqo("journals/vldb/MehtaD97","GhCgLiSfDvcJ")).
neg(eqo("journals/vldb/NanopoulosM02","t7cKx4raSM0J")).
neg(eqo("journals/vldb/OoiTCH98","bVqN5obN3hIJ")).
neg(eqo("journals/vldb/PoulovassilisS96","IZSzLlgi8tUJ")).
neg(eqo("journals/vldb/RahmB01","8XRiREu23GcJ")).
neg(eqo("journals/vldb/SaltenisJ02","ZhRylINOSS4J")).
neg(eqo("journals/vldb/SaltenisJ02","wnMZjFGvYVQJ")).
neg(eqo("journals/vldb/Sciore94","usInMDLNQ-MJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","vecGlq3YYF0J")).
neg(eqo("journals/vldb/SofferS98","lG_CPUQrdxsJ")).
neg(eqo("journals/vldb/TorpJS00","HUnIV3us_YIJ")).
neg(eqo("journals/vldb/YangW03","msqzNc2ox4IJ")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","AxpQwgyRyLgJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","2fO9nM2FoGYJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","h2z51QPXcSkJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","FDPwbRQbfIAJ")).
pos(eqo("conf/sigmod/AcharyaPR99","2RuI2vzDUW8J")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/AdaliBSS98","YQ90BYSVqbsJ")).
pos(eqo("conf/sigmod/AdaliBSS98","rYC-j_j4Yv0J")).
pos(eqo("conf/sigmod/AdelbergGW97","zZo47Z-jVX4J")).
pos(eqo("conf/sigmod/AfratiLU01","U8adXFUIr3EJ")).
pos(eqo("conf/sigmod/Aggarwal03","qbubaA6mQawJ")).
pos(eqo("conf/sigmod/AggarwalWY99","s9hhR-EdDGgJ")).
pos(eqo("conf/sigmod/AggarwalY00","x5jeMyauzWgJ")).
pos(eqo("conf/sigmod/AgichteinGV01","GDoFPiEzEhQJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","1rW7ao6gK-QJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","5E5gcM0xPFAJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","DHbEJyv20WMJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","UYQpDoh0wo0J")).
pos(eqo("conf/sigmod/AgrawalGGR98","_LE5T2vKPUcJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x8fDHaNkSUIJ")).
pos(eqo("conf/sigmod/Ahn94","5s6b10Hik30J")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","L7XmLpQLXBIJ")).
pos(eqo("conf/sigmod/AndersonAF98","_EbKUPc1jYAJ")).
pos(eqo("conf/sigmod/AndersonBKW98","H6eMdbXATmkJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","E_eOZJYat6IJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","OaNzji_-7tsJ")).
pos(eqo("conf/sigmod/AtzeniT97","XaKiz5S-cqUJ")).
pos(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
pos(eqo("conf/sigmod/AvnurHLORRRW98","bEu_llku9NMJ")).
pos(eqo("conf/sigmod/BabcockBDM03","RIDEvTXNpaAJ")).
pos(eqo("conf/sigmod/BabcockBDM03","a2wqpKma5J4J")).
pos(eqo("conf/sigmod/BabcockBDM03","rnakKC_M9-kJ")).
pos(eqo("conf/sigmod/Ballinger94","xGGBIZmLvmgJ")).
pos(eqo("conf/sigmod/BargaL99","QGxyK7bJQOMJ")).
pos(eqo("conf/sigmod/BaruFGHJPW95","C60KJG_xVm0J")).
pos(eqo("conf/sigmod/BaruGLMPVC99","3SHIgRrrL5QJ")).
pos(eqo("conf/sigmod/BaumannDFRW98","k3WA-AE7Sh4J")).
pos(eqo("conf/sigmod/BerchtoldBBKK97","BMkGN7AiGhYJ")).
pos(eqo("conf/sigmod/BersonGMJ94","bw_c9Mk0_7IJ")).
pos(eqo("conf/sigmod/BersonGMJ94","wsG_Q2jbgCAJ")).
pos(eqo("conf/sigmod/BlottRS96","4aSEl4haaq4J")).
pos(eqo("conf/sigmod/BlottRS96","pS2unAe-n_gJ")).
pos(eqo("conf/sigmod/BohlenBD99","X2odIfnOC88J")).
pos(eqo("conf/sigmod/BohmBKK01","C4XcBh6anhAJ")).
pos(eqo("conf/sigmod/BorkarDS01","8fu2bhk_i9EJ")).
pos(eqo("conf/sigmod/BorkarDS01","nsoA6Gcc_jsJ")).
pos(eqo("conf/sigmod/BratsbergT00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335477%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BrinDG95","7mNCkZ7D-R8J")).
pos(eqo("conf/sigmod/BrinMUT97","0cOrb6RuPW0J")).
pos(eqo("conf/sigmod/BrinMUT97","77hnYp9ky9IJ")).
pos(eqo("conf/sigmod/BrinMUT97","FtMoh58D330J")).
pos(eqo("conf/sigmod/BrinMUT97","JBB4svDpBF8J")).
pos(eqo("conf/sigmod/BrinMUT97","vIwsSOGQOWAJ")).
pos(eqo("conf/sigmod/BrinkhoffKSS94a","yp82ArYEGxIJ")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/Bussler01","UYIeOe280OwJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","5wcgt7bNx7YJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","GJ_7cqL0d70J")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","PPV8eOf-uooJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","dP-pHDZ7oawJ")).
pos(eqo("conf/sigmod/CareyK97","ucdmk8xwaTsJ")).
pos(eqo("conf/sigmod/CarinoKKB01","a9HFF_bwiH4J")).
pos(eqo("conf/sigmod/Cattell94","QgR0DgMbdgIJ")).
pos(eqo("conf/sigmod/Cattell94","zSoTbEtLuqEJ")).
pos(eqo("conf/sigmod/CeriFP98","iUGa3pKj-20J")).
pos(eqo("conf/sigmod/Chakrabarti99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304231%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
pos(eqo("conf/sigmod/ChaudhuriGN02","y461yNb2GEcJ")).
pos(eqo("conf/sigmod/ChawatheG97","oHUiSrycKdgJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","Xz0ZPMLOwcgJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","vBlDkLyxeQkJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","xPkLZK36UBUJ")).
pos(eqo("conf/sigmod/ChenGK01","8OgkUeiawO0J")).
pos(eqo("conf/sigmod/ChenGM01","dyXJODAynUgJ")).
pos(eqo("conf/sigmod/ChengKP03","kSt-Pqp2ilYJ")).
pos(eqo("conf/sigmod/Chong98","W-6r_OOEHLUJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","5awQcPWFBrcJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/ChristophidesACS94","WYSBGO-zyoEJ")).
pos(eqo("conf/sigmod/ChristophidesACS94","wOEzWDOEIjwJ")).
pos(eqo("conf/sigmod/CluetDSS98","63Y-t4R2RycJ")).
pos(eqo("conf/sigmod/CluetDSS98","lOZF0Ee3rUQJ")).
pos(eqo("conf/sigmod/CuiOTS03","qx5oR09jmMwJ")).
pos(eqo("conf/sigmod/DeshpandeNGS03","fU6zoUKeXe8J")).
pos(eqo("conf/sigmod/DeshpandeNGS03a","Thoke4oYLt4J")).
pos(eqo("conf/sigmod/DeutschFS99","-KuX7UT0JIIJ")).
pos(eqo("conf/sigmod/DeutschFS99","De_3PkxkhzIJ")).
pos(eqo("conf/sigmod/DeutschFS99","QxtGOVsCF78J")).
pos(eqo("conf/sigmod/DoanDH01","Lv0bggWzgeoJ")).
pos(eqo("conf/sigmod/EmbleyJN99","54w4cIKL11UJ")).
pos(eqo("conf/sigmod/FaginKS03","tQZWeE_nsa0J")).
pos(eqo("conf/sigmod/FaloutsosL95","GGmfi7ywI4gJ")).
pos(eqo("conf/sigmod/FaloutsosL95","RLjlTtFM36IJ")).
pos(eqo("conf/sigmod/FaloutsosL95","roK09GarWdcJ")).
pos(eqo("conf/sigmod/FaloutsosL95","yFaUjmOQp1wJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","s-BT0x6h2qUJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","Sqy1tqGEnxsJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","XMC0W6CQJJIJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","qsWDIfzBxiQJ")).
pos(eqo("conf/sigmod/Fernandez94","PmrthJYk66cJ")).
pos(eqo("conf/sigmod/FranklinZ98","5Cj9Wx8llkwJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","WOCgxlV_LgoJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","Y8UdbAPhYpUJ")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GarofalakisGR02","ImADir74KWIJ")).
pos(eqo("conf/sigmod/GeneserethKD97","V1GBio3oeqMJ")).
pos(eqo("conf/sigmod/Gerber95","wlxZ0FqTy_MJ")).
pos(eqo("conf/sigmod/GetoorTK01","99N4rXNdaqMJ")).
pos(eqo("conf/sigmod/GodfreyGXZ01","LNnvt5TpBhkJ")).
pos(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
pos(eqo("conf/sigmod/GrayHOS96","5cw83MyqYrMJ")).
pos(eqo("conf/sigmod/GrayHOS96","OLt5pqtQf3YJ")).
pos(eqo("conf/sigmod/GrayHOS96","cS8_6Qp-JYUJ")).
pos(eqo("conf/sigmod/GrayHOS96","pDjbDK0ZzsMJ")).
pos(eqo("conf/sigmod/GriffinL95","RuYYq5xDgNYJ")).
pos(eqo("conf/sigmod/GriffinL95","nXT3j4XaZxIJ")).
pos(eqo("conf/sigmod/Han96","DlQd7WIkVF0J")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanKK97","MqdtZ_cUxDEJ")).
pos(eqo("conf/sigmod/HanPLJ01","H_tzR6yoJLEJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","-RzBfKSBxpgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Fyek_kCB-qkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","JM1X7hho718J")).
pos(eqo("conf/sigmod/HarinarayanRU96","Qv7KYn9x-SQJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","S-7KOPYObKcJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","uKGmcc4xUG4J")).
pos(eqo("conf/sigmod/HellersteinN96","_hDCldPyum0J")).
pos(eqo("conf/sigmod/Hidber99","HkBKH9ZUJEcJ")).
pos(eqo("conf/sigmod/Hidber99","Rn-E82gM1RQJ")).
pos(eqo("conf/sigmod/IoannidisP95","mKsxPS2lFXcJ")).
pos(eqo("conf/sigmod/JaedickeM98","9eSx_Gd0JoQJ")).
pos(eqo("conf/sigmod/JaedickeM98","MswqiEweEGUJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","XpY2UPc6vP0J")).
pos(eqo("conf/sigmod/Jamil99","z5EfiutEfScJ")).
pos(eqo("conf/sigmod/JohnsonD03","5OYgUpRggiMJ")).
pos(eqo("conf/sigmod/KanthRSB99","yPFlbrVJFJoJ")).
pos(eqo("conf/sigmod/KarbhariRXD02","Mw3xLuyR3qQJ")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/KotidisR99","nsASp-dCJBQJ")).
pos(eqo("conf/sigmod/KoudasS97","0u8r8MJWgKAJ")).
pos(eqo("conf/sigmod/KoudasS97","Z3hu6UPm8eQJ")).
pos(eqo("conf/sigmod/KoudasS97","sB-nvl5829EJ")).
pos(eqo("conf/sigmod/KrishnamurthyBN99","qS4jhfgPbm8J")).
pos(eqo("conf/sigmod/KrollW94","SX1_Z3Z000YJ")).
pos(eqo("conf/sigmod/LabioWGG00","EhR3fz7f7vcJ")).
pos(eqo("conf/sigmod/LakhamrajuRSS00","DyGC4KFw5mgJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","ALUnDjtT1OAJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","DfOLEzMoEaEJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","fZSRCe60AUcJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","lduaYmELtHoJ")).
pos(eqo("conf/sigmod/LakshmananPZ03a","pci2lDLAWzMJ")).
pos(eqo("conf/sigmod/LeeKOTM00","C8RLbWKCgicJ")).
pos(eqo("conf/sigmod/LiCHH97","mNqvFihFg1AJ")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/LiskovACDGGMMS96","0Mj8N23H1QEJ")).
pos(eqo("conf/sigmod/LiskovACDGGMMS96","Ey7Mbh6IdQIJ")).
pos(eqo("conf/sigmod/Lomet00","FiPJDs_jm54J")).
pos(eqo("conf/sigmod/LometW98","QPpUo7m3A7cJ")).
pos(eqo("conf/sigmod/MaddenSHR02","7n7LvbccBZoJ")).
pos(eqo("conf/sigmod/MaddenSHR02","DkgClKWAyEIJ")).
pos(eqo("conf/sigmod/MaddenSHR02","zobnUjtYSe8J")).
pos(eqo("conf/sigmod/Martin94","ogow-Rtc3fEJ")).
pos(eqo("conf/sigmod/MassariPSC95","O2FrN68p5PUJ")).
pos(eqo("conf/sigmod/MatiasVW98","6WjESNMzLvgJ")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/MissikoffT94","nxNSfctbGWAJ")).
pos(eqo("conf/sigmod/MistryRSR01","r62IMncHe0IJ")).
pos(eqo("conf/sigmod/Mohan96","C-yzbvoAg00J")).
pos(eqo("conf/sigmod/Moore95","uh57sQuxYuIJ")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/Mylopoulos98","vU_Vo2059VUJ")).
pos(eqo("conf/sigmod/NgLK98","kJVhJ4ruw6sJ")).
pos(eqo("conf/sigmod/Nori00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.335474")).
pos(eqo("conf/sigmod/NybergBCGL94","fXziEl_Htv8J")).
pos(eqo("conf/sigmod/NybergBCGL94","kd-0q-M1O2gJ")).
pos(eqo("conf/sigmod/PapadiasTFS03","PJ9152AhkuwJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","Y7J0sm6WO2kJ")).
pos(eqo("conf/sigmod/PeiMHZ00","UyhrqiH_-MoJ")).
pos(eqo("conf/sigmod/QunLO03","eBXNcn6PwAEJ")).
pos(eqo("conf/sigmod/RafieiM97","UBACGF9cQ2UJ")).
pos(eqo("conf/sigmod/RajagopalanML98","6bxNVhIp7FAJ")).
pos(eqo("conf/sigmod/RajagopalanML98","AUR-p53CsK8J")).
pos(eqo("conf/sigmod/RajagopalanML98","HVP6eYl30IgJ")).
pos(eqo("conf/sigmod/Ramakrishnan00","aHpKrjJEJk4J")).
pos(eqo("conf/sigmod/RamakrishnanD98","LSNo-7ii1vEJ")).
pos(eqo("conf/sigmod/RaoR00","wp2_GObi-XkJ")).
pos(eqo("conf/sigmod/RundensteinerCLCZNJLW99","SADcQZhMqgEJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","Rh68dFgQfS4J")).
pos(eqo("conf/sigmod/RundensteinerKZWLLN99","2XRfNjwuDrsJ")).
pos(eqo("conf/sigmod/Sahuguet01","xb63RaGQYmYJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","LMm4_4_uNNoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","Q1TF7XE9xkAJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","QZQt-pSMhYQJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","odsY0ehPPhIJ")).
pos(eqo("conf/sigmod/SeshadriLR94","60I0j0qUHVYJ")).
pos(eqo("conf/sigmod/Shasha97","Q-KG8a3_BmIJ")).
pos(eqo("conf/sigmod/Shasha97","r2TwyhAdYecJ")).
pos(eqo("conf/sigmod/Sheth95","0CD9uUPdnbUJ")).
pos(eqo("conf/sigmod/Sheth95","eU-7sSXW5jEJ")).
pos(eqo("conf/sigmod/ShklarSKT95","4IaWCBK6dMQJ")).
pos(eqo("conf/sigmod/SrikantA96","Cm66C3yYtdgJ")).
pos(eqo("conf/sigmod/SrikantA96","KVEv4thH4CgJ")).
pos(eqo("conf/sigmod/SrikantA96","WSVs3nCRe8EJ")).
pos(eqo("conf/sigmod/SrikantA96","WkXM8o_flrEJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","P8SQPINQRHQJ")).
pos(eqo("conf/sigmod/TrisoliniLN99","cFMtMf7bLzIJ")).
pos(eqo("conf/sigmod/Ubell94","ZrMjnFuPnI0J")).
pos(eqo("conf/sigmod/Ubell94","lphlTARDI9YJ")).
pos(eqo("conf/sigmod/VitterW99","1UFq52qqErUJ")).
pos(eqo("conf/sigmod/VitterW99","P5oJUiow7lsJ")).
pos(eqo("conf/sigmod/WangJLY03","EQsWWZdE45wJ")).
pos(eqo("conf/sigmod/WangPFY03","jpNXw9L7pxgJ")).
pos(eqo("conf/sigmod/WangPFY03","y5zNcYc9dqsJ")).
pos(eqo("conf/sigmod/WhiteD95","6SBwemr2zscJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","SHi3jbyB9t0J")).
pos(eqo("conf/sigmod/WolfsonSXZC99","vwdWTx0dk7QJ")).
pos(eqo("conf/sigmod/WuAA01","QKlyEeIFW24J")).
pos(eqo("conf/sigmod/YangM97","57m7NniyTrkJ")).
pos(eqo("conf/sigmod/YerneniLGU99","2MbaeG3IVV0J")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qW_oF_qWmvQJ")).
pos(eqo("conf/sigmod/ZhouLP99","0OwKmPjQpd0J")).
pos(eqo("conf/vldb/AbiteboulBMMW02","0MJZbBBMixgJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","YtqWhs8DYBUJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","mm3mXWb8QS0J")).
pos(eqo("conf/vldb/AbiteboulMRVW98","OqpwlRWdIMgJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","kuueK-yBQqMJ")).
pos(eqo("conf/vldb/AboulnagaAN01","OBbDFGQNEDQJ")).
pos(eqo("conf/vldb/AgrawalCN00","0KLcrS1Co_kJ")).
pos(eqo("conf/vldb/AgrawalCN00","U8CMJBaJyX8J")).
pos(eqo("conf/vldb/AgrawalCN00","b9uF_OTTHIEJ")).
pos(eqo("conf/vldb/AgrawalCN00","jq5VkbTyBksJ")).
pos(eqo("conf/vldb/AgrawalLSS95","HugNLG7z-Z4J")).
pos(eqo("conf/vldb/AgrawalLSS95","PbZkvDhTeyEJ")).
pos(eqo("conf/vldb/AgrawalLSS95","Y799jSppkKEJ")).
pos(eqo("conf/vldb/AgrawalLSS95","iJc7iMSuwowJ")).
pos(eqo("conf/vldb/AgrawalLSS95","kvFoPg6MAoYJ")).
pos(eqo("conf/vldb/AgrawalS94","0haDaGr-V3oJ")).
pos(eqo("conf/vldb/AgrawalS94","2Z_X3zsf4CoJ")).
pos(eqo("conf/vldb/AgrawalS94","551mHiCJRjoJ")).
pos(eqo("conf/vldb/AgrawalS94","E7cKUUkwc1kJ")).
pos(eqo("conf/vldb/AgrawalS94","VwFLRQytbu4J")).
pos(eqo("conf/vldb/AgrawalS94","_NISJ-0lKiAJ")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/vldb/AnkerstBKS98","DbLGmJX7UJ8J")).
pos(eqo("conf/vldb/AshwinGG02","YiJojduGXXkJ")).
pos(eqo("conf/vldb/BargaP95","3CDeAczlaSUJ")).
pos(eqo("conf/vldb/BelussiF95","a78Lxr80kJUJ")).
pos(eqo("conf/vldb/BerchtoldKK96","2EJhvKyW8AoJ")).
pos(eqo("conf/vldb/BerchtoldKK96","S-aEcHjpLBMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WcxbHqh4FfkJ")).
pos(eqo("conf/vldb/BerchtoldKK96","pMqgAz_KzPgJ")).
pos(eqo("conf/vldb/BerckenS96","GfvntjAdvVYJ")).
pos(eqo("conf/vldb/BestavrosB95","LDv4my6gWJQJ")).
pos(eqo("conf/vldb/BliujuteJSS98","qWGJZFXi414J")).
pos(eqo("conf/vldb/BohlenSS96","MqokIdCr2oIJ")).
pos(eqo("conf/vldb/BohlenSS96","gcoLSYEk0HIJ")).
pos(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
pos(eqo("conf/vldb/BonczMK99","jsNNCDiD0yIJ")).
pos(eqo("conf/vldb/BonczRK98","965BXzMPxSoJ")).
pos(eqo("conf/vldb/Bowker00","fAHjV8C1hLcJ")).
pos(eqo("conf/vldb/BrownCC94","oayI0FKl-nQJ")).
pos(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
pos(eqo("conf/vldb/CareyCNVDRSM99","JpMllVmmnkAJ")).
pos(eqo("conf/vldb/CareyD96","lW_0wZmDIaIJ")).
pos(eqo("conf/vldb/CarinoOBS99","47kAOej6WIQJ")).
pos(eqo("conf/vldb/CasatiDGS01","bFnDGrZ_4voJ")).
pos(eqo("conf/vldb/CeriFP99","L1xeH5yC0fgJ")).
pos(eqo("conf/vldb/ChanGR02","7rn7AHVs1YUJ")).
pos(eqo("conf/vldb/ChanGR02","wUcXmf9G52gJ")).
pos(eqo("conf/vldb/ChaudhuriN97","g6XLqjCRkFcJ")).
pos(eqo("conf/vldb/ChaudhuriS01","-jtu5QeiAKQJ")).
pos(eqo("conf/vldb/ChaudhuriS96","4MaErPILRq8J")).
pos(eqo("conf/vldb/ChaudhuriS96","QCFUIVkspywJ")).
pos(eqo("conf/vldb/ChaudhuriW00","OuM0E0BhEXIJ")).
pos(eqo("conf/vldb/ChengGKLLQS99","_pYZZxn2SjYJ")).
pos(eqo("conf/vldb/CherniackFZ01","49EWG8vzsXUJ")).
pos(eqo("conf/vldb/ChienVZTZ02","uUmeAkW_FFUJ")).
pos(eqo("conf/vldb/CochinwalaB94","Bp69wMYw9DAJ")).
pos(eqo("conf/vldb/CooperSFHS01","PAfEdPwJ8tgJ")).
pos(eqo("conf/vldb/DarFJST96","8OsKvVqzz58J")).
pos(eqo("conf/vldb/DarFJST96","95lS1rShpqQJ")).
pos(eqo("conf/vldb/DarFJST96","ThLxMqqAxjIJ")).
pos(eqo("conf/vldb/DarFJST96","Ui5dxm-mCN8J")).
pos(eqo("conf/vldb/DarFJST96","gkbM-pRDcSwJ")).
pos(eqo("conf/vldb/Dayal99","OoknnZ3rbfwJ")).
pos(eqo("conf/vldb/DesslochM97","OY4EswVULVcJ")).
pos(eqo("conf/vldb/DillKMRST01","_dtqcPU4NdkJ")).
pos(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
pos(eqo("conf/vldb/EleftheriouBCDHLPPABDDDGJHLRSVW03","hRToevpkaa0J")).
pos(eqo("conf/vldb/GalhardasFSSS01","RZZjZ_7yJb8J")).
pos(eqo("conf/vldb/GalhardasFSSS01","XtFcz806WQEJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","Z8jYTylZtkEJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","otGW0G5B6AYJ")).
pos(eqo("conf/vldb/GaoS03","BEpwgIQR6r4J")).
pos(eqo("conf/vldb/GarofalakisG02","ImADir74KWIJ")).
pos(eqo("conf/vldb/GarofalakisOS97","3p2a2ZKrCjcJ")).
pos(eqo("conf/vldb/GarofalakisOS97","dW_pRNemQfsJ")).
pos(eqo("conf/vldb/GarofalakisRS99","9aNUdPCEMmwJ")).
pos(eqo("conf/vldb/GarofalakisRS99","Xm3ygCvkmN8J")).
pos(eqo("conf/vldb/GarofalakisRS99","q87jrCR_GqQJ")).
pos(eqo("conf/vldb/GeorgeH98","2L-UFpDof3UJ")).
pos(eqo("conf/vldb/GibbonsMP97","QKnjF3UgncMJ")).
pos(eqo("conf/vldb/GinisHKMT97","GBVvAWWCTcgJ")).
pos(eqo("conf/vldb/GolabO03","6K9FhI2pFEgJ")).
pos(eqo("conf/vldb/GoldmanSVG98","pweOUtA2iTAJ")).
pos(eqo("conf/vldb/GutierrezPST94","VUU_DceCRXAJ")).
pos(eqo("conf/vldb/HaberIL95","UM1ZozyrJnIJ")).
pos(eqo("conf/vldb/HalversonBKKRTVWND03","oR7DmJ9JJDYJ")).
pos(eqo("conf/vldb/HanF95","76X91rVs8BQJ")).
pos(eqo("conf/vldb/HanF95","AOXjUq9H2cwJ")).
pos(eqo("conf/vldb/HanF95","GeMycbLXZUkJ")).
pos(eqo("conf/vldb/HanF95","pNBgTa_UPDEJ")).
pos(eqo("conf/vldb/HelmerM97","vInYFLVq0uIJ")).
pos(eqo("conf/vldb/HelmerM97","xsh0C_nCllsJ")).
pos(eqo("conf/vldb/HulgeriS02","syoqNSarAscJ")).
pos(eqo("conf/vldb/HulgeriS02","xGcM9AuhrBMJ")).
pos(eqo("conf/vldb/HulgeriS03","l5_H15LkpCsJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","_83yTuPv-NAJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","zbaMbE17LyQJ")).
pos(eqo("conf/vldb/IlyasAE03","Y385z1Dxp84J")).
pos(eqo("conf/vldb/IoannidisP99","2k9bgRJC-hYJ")).
pos(eqo("conf/vldb/IwerksSS03","4B_LhCns0WoJ")).
pos(eqo("conf/vldb/JagadishKMPSS98","0iiNS8BIbsUJ")).
pos(eqo("conf/vldb/JagadishLS99","5d1R2mD-7MkJ")).
pos(eqo("conf/vldb/JagadishLS99","FLHi5haA7AQJ")).
pos(eqo("conf/vldb/JarkeKL00","hRr_IBVG0-YJ")).
pos(eqo("conf/vldb/JosifovskiR99","a58OzgW7AvUJ")).
pos(eqo("conf/vldb/JosifovskiR99","rR9r4Kuzq-4J")).
pos(eqo("conf/vldb/KahveciS01","bYV1jynEEO8J")).
pos(eqo("conf/vldb/KarayannidisTSPMRFEB02","9KiPVAodKnYJ")).
pos(eqo("conf/vldb/KeidlSSK02","dTval1yE6p8J")).
pos(eqo("conf/vldb/KnorrN98","r8uYvAGT6swJ")).
pos(eqo("conf/vldb/KnorrN98","yFmekFZgZmwJ")).
pos(eqo("conf/vldb/KonopnickiS95","SHYtwo2v-LAJ")).
pos(eqo("conf/vldb/KonopnickiS95","cA1Zsnlz-tIJ")).
pos(eqo("conf/vldb/KonopnickiS95","fAZ2KwztkLoJ")).
pos(eqo("conf/vldb/KonopnickiS95","z5Z9vSNOznMJ")).
pos(eqo("conf/vldb/KornLKF98","ewsBMN0qVa4J")).
pos(eqo("conf/vldb/KornLKF98","jKZaGhVU1WkJ")).
pos(eqo("conf/vldb/KornMS02","mClzTQppJE4J")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/vldb/KornSFSP96","I8YNDqO9pg8J")).
pos(eqo("conf/vldb/KornSFSP96","QjbxSG6_-WIJ")).
pos(eqo("conf/vldb/KornSFSP96","xQU9GXs4k50J")).
pos(eqo("conf/vldb/Kornacker99","aOmma8tnFKIJ")).
pos(eqo("conf/vldb/KounevB02","mq4cLaNqTDQJ")).
pos(eqo("conf/vldb/KumarKA97","8bLd-1l1at4J")).
pos(eqo("conf/vldb/KumarKA97","EhTWppk6No8J")).
pos(eqo("conf/vldb/KumarRRT99","1xbD4ssSjjUJ")).
pos(eqo("conf/vldb/LabioG96","1JLlGYW8cDAJ")).
pos(eqo("conf/vldb/LabioG96","B3unqvqyJrMJ")).
pos(eqo("conf/vldb/LakshmananSS96","8sohtsoGrycJ")).
pos(eqo("conf/vldb/LakshmananSS96","AVyGNVp-ENcJ")).
pos(eqo("conf/vldb/LakshmananSS96","GDmbzrUbyzAJ")).
pos(eqo("conf/vldb/LevyMS94","8AHaTrvwsJoJ")).
pos(eqo("conf/vldb/LevyRO96","3v8fGnfTuVMJ")).
pos(eqo("conf/vldb/LevyRO96","TiS6j9mg9xoJ")).
pos(eqo("conf/vldb/LevyRO96","bbeft23FHAkJ")).
pos(eqo("conf/vldb/LevyRO96","e_vUPQi8-xIJ")).
pos(eqo("conf/vldb/LiCHH97","DmGBKpaiyGEJ")).
pos(eqo("conf/vldb/LiCHH97","mGOC_IQppxQJ")).
pos(eqo("conf/vldb/LiRS99","Bf44yXvb6EAJ")).
pos(eqo("conf/vldb/LiRS99","cGbo_ZtYKwYJ")).
pos(eqo("conf/vldb/LitwinNS94","SnkWnX5WoKwJ")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/MadhavanBR01","wRHapJxb_-QJ")).
pos(eqo("conf/vldb/ManolopoulosT01","hr5OGCJqc2MJ")).
pos(eqo("conf/vldb/MeekPK03","BV6S1LOk4XwJ")).
pos(eqo("conf/vldb/MeekPK03","cR1ikuFsE1wJ")).
pos(eqo("conf/vldb/MendelzonV00","AQLsLBctUI4J")).
pos(eqo("conf/vldb/MendelzonV00","Ah3ENTVwMj4J")).
pos(eqo("conf/vldb/MengLYWCR98","EcpPzbn2EaIJ")).
pos(eqo("conf/vldb/MeoPC96","SNIbAV2EN0MJ")).
pos(eqo("conf/vldb/MiklauS03","cJUP6vfSm50J")).
pos(eqo("conf/vldb/Mohan96","wYwNJy4GsEYJ")).
pos(eqo("conf/vldb/MorimotoFMTY98","31YuS02mFq8J")).
pos(eqo("conf/vldb/MorimotoFMTY98","9sydmlCRr4cJ")).
pos(eqo("conf/vldb/NicklasGS03","zApMW7wX5-AJ")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/OoiYTJ01","T8BPorXB1VsJ")).
pos(eqo("conf/vldb/OuzzaniAB94","p0TLPzS0K4oJ")).
pos(eqo("conf/vldb/PanRAMOHAMV02","F9Fe5NfpK6MJ")).
pos(eqo("conf/vldb/PantiSG00","C7Vuxp5KVsAJ")).
pos(eqo("conf/vldb/PapadiasTS03","TmcyYF1CNsYJ")).
pos(eqo("conf/vldb/PapadiasZMT03","hJ8VP7FyOL0J")).
pos(eqo("conf/vldb/PardonA00","k7G60pXtD58J")).
pos(eqo("conf/vldb/PfoserJT00","YBNEZgmh540J")).
pos(eqo("conf/vldb/PirotteZMY94","8s-SP8sAvQAJ")).
pos(eqo("conf/vldb/PolyzotisG02","krAZ7iDMEOQJ")).
pos(eqo("conf/vldb/PoosalaI97","QIG8th9DHbQJ")).
pos(eqo("conf/vldb/PopaVMHF02","qJ4lzBFzjdgJ")).
pos(eqo("conf/vldb/RamakrishnanGRSWZ95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.756661")).
pos(eqo("conf/vldb/RamakrishnanR96","3y1e-H-FdC0J")).
pos(eqo("conf/vldb/RamamrithamABEGP00","jYGXFESkS-YJ")).
pos(eqo("conf/vldb/RamanRH99","6uP3E_WEkCAJ")).
pos(eqo("conf/vldb/RamanRH99","QLJhG6Rz2T0J")).
pos(eqo("conf/vldb/RaoR99","N8XkcmIO0ysJ")).
pos(eqo("conf/vldb/RaoR99","tv4rTR2Z-I8J")).
pos(eqo("conf/vldb/RothS97","1fQr1rJ4yCwJ")).
pos(eqo("conf/vldb/RothS97","9xWSlRBwaPIJ")).
pos(eqo("conf/vldb/RothS97","GRLUYc-u9X8J")).
pos(eqo("conf/vldb/RothS97","eo2xdvfnpzsJ")).
pos(eqo("conf/vldb/Sarawagi00","z5DmAoBjsjAJ")).
pos(eqo("conf/vldb/SellisRF97","-ISlDUVRtjcJ")).
pos(eqo("conf/vldb/SeshadriLR97","ad-TVNZBg8YJ")).
pos(eqo("conf/vldb/ShahabiFKF00","ln1yHhG7gdgJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GIlUG9H3gUUJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","JqfEbjic16sJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","hYQ_6_v-Cd4J")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","wd9dp08MveIJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","ZQyBjtpbhvIJ")).
pos(eqo("conf/vldb/ShengBDM02","ZQdRRjCxEX0J")).
pos(eqo("conf/vldb/Shenker03","5yETsE57mzgJ")).
pos(eqo("conf/vldb/SistlaYH94","QWD1EGMbTQYJ")).
pos(eqo("conf/vldb/SistlaYH94","bDH4OmzDSLEJ")).
pos(eqo("conf/vldb/Spaccapietra94","ZpVzTb1a7VoJ")).
pos(eqo("conf/vldb/StathatosRB97","ubOeBh7Lk8sJ")).
pos(eqo("conf/vldb/StohrR01","jn3pvb3hRzwJ")).
pos(eqo("conf/vldb/TanGO99","CcTZvs8xd2sJ")).
pos(eqo("conf/vldb/TanSHCR01","hPcNG0tPwgIJ")).
pos(eqo("conf/vldb/VassalosP97","2DJipXynj5wJ")).
pos(eqo("conf/vldb/VassalosP97","9MlAuURfKhYJ")).
pos(eqo("conf/vldb/VassalosP97","_Va8sQkrP2kJ")).
pos(eqo("conf/vldb/VassalosP97","jmYHA7e95XAJ")).
pos(eqo("conf/vldb/VassalosP97","kG-k9420fGMJ")).
pos(eqo("conf/vldb/VenkataramanZ98","RGh6Gep4ym8J")).
pos(eqo("conf/vldb/VermeerA96","bEddMdwB2_4J")).
pos(eqo("conf/vldb/VieiraM03","sUtdmV9XsIcJ")).
pos(eqo("conf/vldb/WangC03","B1uNI67mfJcJ")).
pos(eqo("conf/vldb/WangC03","nXj_8Y7lmHsJ")).
pos(eqo("conf/vldb/WangYM97","xW3AafG2xKgJ")).
pos(eqo("conf/vldb/WangZ00","WtD34B68XEUJ")).
pos(eqo("conf/vldb/WeberSB98","TkaEMuHGE9cJ")).
pos(eqo("conf/vldb/WeberSB98","ZLYsIub53eoJ")).
pos(eqo("conf/vldb/WeberSNSS03","TMPrfw4VcFAJ")).
pos(eqo("conf/vldb/WuYCT95","A5s_U6Ixg3EJ")).
pos(eqo("conf/vldb/YuPM03","sP3bZMqHmZsJ")).
pos(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
pos(eqo("conf/vldb/ZhouS03","NlDvk5J0WwEJ")).
pos(eqo("conf/vldb/ZirintsisKM99","_UYteGcmBKIJ")).
pos(eqo("conf/vldb/ZirintsisKM99","sldCppj0qOEJ")).
pos(eqo("conf/vldb/ZurekS99","mEdoUlcnDsgJ")).
pos(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AbererCH02","YUtQ8KXNntYJ")).
pos(eqo("journals/sigmod/AbiteboulH95","kUA9e6YP8igJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","JHVWab3P4zIJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","OgBSNzmsvHUJ")).
pos(eqo("journals/sigmod/BaaderJN97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D274461%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BergamaschiCV99","4C9A2HGs4qsJ")).
pos(eqo("journals/sigmod/BergamaschiCV99","rIm9uDX6PHUJ")).
pos(eqo("journals/sigmod/Bestavros96","Q2y53UR0g6oJ")).
pos(eqo("journals/sigmod/BestavrosLS96","RalvsjDuKzsJ")).
pos(eqo("journals/sigmod/BoucelmaCGJLL02","I9JXY0-R4GgJ")).
pos(eqo("journals/sigmod/ButtlerCCFHLPRX02","JScvAMYcsmoJ")).
pos(eqo("journals/sigmod/CareyS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310071%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CarmelMS01","bolov3CrMYwJ")).
pos(eqo("journals/sigmod/CarmelMS01","hB-ZA0wX-fsJ")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D641006")).
pos(eqo("journals/sigmod/ChaudhuriD97","LROAexi_0UEJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","jsapF3OoWXcJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","oahM5itk_dAJ")).
pos(eqo("journals/sigmod/ClementLGMK97","J7Y20fYLGbcJ")).
pos(eqo("journals/sigmod/ClementLGMK97","To_EjIKwfSAJ")).
pos(eqo("journals/sigmod/ClementiniF00","9_GTdteKEYsJ")).
pos(eqo("journals/sigmod/CrestaniG02","tyZxVraNgTsJ")).
pos(eqo("journals/sigmod/CuiJO02","LIUl6zpveGQJ")).
pos(eqo("journals/sigmod/DiazJPa94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181555%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DoanPSB97","r30CyoxOeycJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","vG5FK8BJkZgJ")).
pos(eqo("journals/sigmod/EisenbergM99","LL9Guuh490sJ")).
pos(eqo("journals/sigmod/EisenbergM99","ciavnyh4U8UJ")).
pos(eqo("journals/sigmod/EisenbergM99a","e3s4OFTeBqwJ")).
pos(eqo("journals/sigmod/ErdurD02","9OcrAEypDhMJ")).
pos(eqo("journals/sigmod/FrewD97","Xo4KXwq9XIcJ")).
pos(eqo("journals/sigmod/GatziuKBF98","H1JxB_3PZy4J")).
pos(eqo("journals/sigmod/GeppertD94","P9xX0UDXnRcJ")).
pos(eqo("journals/sigmod/GobleR02a","YL0TdeqwA-EJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","ihljCMaS2UsJ")).
pos(eqo("journals/sigmod/Han98","2kDtSxYI5DgJ")).
pos(eqo("journals/sigmod/Han98","fowjYeJoaxgJ")).
pos(eqo("journals/sigmod/Han98","qmIdBy8oNgEJ")).
pos(eqo("journals/sigmod/HansonN99","O5m6UXQ_Xv4J")).
pos(eqo("journals/sigmod/HansonN99","id1te58YJlUJ")).
pos(eqo("journals/sigmod/Huyn01","KNYDz76C_HsJ")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/Keim96","vkUvhZOw-1YJ")).
pos(eqo("journals/sigmod/KennedyMB96","vBYtmDEYeK0J")).
pos(eqo("journals/sigmod/Kosch02","_avm808LQocJ")).
pos(eqo("journals/sigmod/KoubarakisTID03","6b15hteKSM4J")).
pos(eqo("journals/sigmod/KoubarakisTID03","VtCTqej5JSQJ")).
pos(eqo("journals/sigmod/KuokFW98","qyXhN3CrVQ8J")).
pos(eqo("journals/sigmod/Manola98","VIjfH9f94xkJ")).
pos(eqo("journals/sigmod/McHughW97","dAnyGPqToQEJ")).
pos(eqo("journals/sigmod/MukhopadhyayGS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776989%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MusickM98","gt83e4uB09wJ")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/OukselS99","S-LYnzS1K70J")).
pos(eqo("journals/sigmod/OukselS99","YeVWiZOxB9IJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","ZsUpDroAFBQJ")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","mkfP-JNsNZoJ")).
pos(eqo("journals/sigmod/Seshadri98","_nIg_hi8PAAJ")).
pos(eqo("journals/sigmod/ShethBS99","cqlnSEkt12EJ")).
pos(eqo("journals/sigmod/ShethBS99","uTsHgv9-zdUJ")).
pos(eqo("journals/sigmod/ShethGJRSWW96","ub2wqqQgD40J")).
pos(eqo("journals/sigmod/ShethM02","uwGRgxWWCtUJ")).
pos(eqo("journals/sigmod/Stacey95","rdXUggm5kg0J")).
pos(eqo("journals/sigmod/StolfoLCFE01","lvIPWxkN4YAJ")).
pos(eqo("journals/sigmod/TomasicS97","-MNdDpWC-sgJ")).
pos(eqo("journals/sigmod/TsotrasK96","-FGfZQ_8TxIJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/VelACM01","LseDURw3BXMJ")).
pos(eqo("journals/sigmod/WuY00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D362096%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Yang94","sHJ914nPZtUJ")).
pos(eqo("journals/sigmod/YaoG02","M7PRDh2-0EIJ")).
pos(eqo("journals/sigmod/YeungHL94","yQv94p3tE1IJ")).
pos(eqo("journals/tods/AikenHW95","cHpmOFVpTi8J")).
pos(eqo("journals/tods/Alagic99","Gq6D6zMEPxoJ")).
pos(eqo("journals/tods/AndriesCPB01","6gK7k-OqgEUJ")).
pos(eqo("journals/tods/BellNNS96","pz2VRTdXq1cJ")).
pos(eqo("journals/tods/Bohm00","i5nEuutK3H4J")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/tods/CasatiCPP99","12JXvv17ugoJ")).
pos(eqo("journals/tods/CasatiCPP99","b6-zHfA02TgJ")).
pos(eqo("journals/tods/CasatiCPP99","bWa_AKkBbn8J")).
pos(eqo("journals/tods/CasatiCPP99","vFYKSBlZfK4J")).
pos(eqo("journals/tods/CastanoAFP98","tm7SUvdcOHYJ")).
pos(eqo("journals/tods/CliffordC94","OY6BjHhbz2cJ")).
pos(eqo("journals/tods/DekhtyarRS01","AnNzb6Gr7HkJ")).
pos(eqo("journals/tods/DeyS96","l2y2U5f48WcJ")).
pos(eqo("journals/tods/DeyS96","uZVc1wSi3y4J")).
pos(eqo("journals/tods/GunopulosKMSTS03","-q1BFuUI27EJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","v5mRJmMZOTMJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","y5JyKlYjnI4J")).
pos(eqo("journals/tods/Jimenez-PerisPAK03","yj7oLWfPR4gJ")).
pos(eqo("journals/tods/MuralidharS99","dKvepAPYBmcJ")).
pos(eqo("journals/tods/OliverS94","zAczQV37xxsJ")).
pos(eqo("journals/tods/RaschidL96","rUpu2pcFa8cJ")).
pos(eqo("journals/tods/SalemGS94","7IBL1cudvR0J")).
pos(eqo("journals/tods/StolboushkinT98","ZnWLup8HMkUJ")).
pos(eqo("journals/tods/Subrahmanian94","wl8Wa2O28_oJ")).
pos(eqo("journals/tods/TaoSP03","FBp7oibu4ygJ")).
pos(eqo("journals/tods/TendickM94","FxCxfE4m1rUJ")).
pos(eqo("journals/vldb/AgrawalAJL95","EyOHVek12P0J")).
pos(eqo("journals/vldb/AguileraCMVV02","4OUQOD2i52sJ")).
pos(eqo("journals/vldb/AtkinsonM95","rFdqdXVhLooJ")).
pos(eqo("journals/vldb/BeckerGOSW96","K53EIcG4ta8J")).
pos(eqo("journals/vldb/CombiP01","8YoYzQtOgYoJ")).
pos(eqo("journals/vldb/FahlR97","iM6vRWljKpAJ")).
pos(eqo("journals/vldb/GeorgeH00","2L-UFpDof3UJ")).
pos(eqo("journals/vldb/GrefenVA01","fohOTTsEtIwJ")).
pos(eqo("journals/vldb/HalkidiNVV03","C_X4Frh2wHIJ")).
pos(eqo("journals/vldb/HalkidiNVV03","tFe0FjHYe2MJ")).
pos(eqo("journals/vldb/HelmerM03","lqAgqxpXpxMJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","T1c1QfSdUVQJ")).
pos(eqo("journals/vldb/KabraD99","pWEfI0xFFcoJ")).
pos(eqo("journals/vldb/LaurentLSV01","TTIgIh9uC_YJ")).
pos(eqo("journals/vldb/LawLG99","TOXrbhbbNJ4J")).
pos(eqo("journals/vldb/Li03","HlXyqUIDobMJ")).
pos(eqo("journals/vldb/LinJF94","8-USisLIGMMJ")).
pos(eqo("journals/vldb/LinJF94","vmxFQL7lhKoJ")).
pos(eqo("journals/vldb/ManegoldBK00","8yhbBSPKZEoJ")).
pos(eqo("journals/vldb/ManegoldBK00","jsNNCDiD0yIJ")).
pos(eqo("journals/vldb/MuckP97","yHSQJtyFciMJ")).
pos(eqo("journals/vldb/NybergBCGL95","A1phylxPkl4J")).
pos(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
pos(eqo("journals/vldb/PacittiS00","ZmvL3_H6DqUJ")).
pos(eqo("journals/vldb/PapadiasS94","kEte3P_QB60J")).
pos(eqo("journals/vldb/RafieiM02","kZFfJieudW4J")).
pos(eqo("journals/vldb/RahmB01","707RPzHAB8YJ")).
pos(eqo("journals/vldb/RahmB01","OmmFvfvPT6MJ")).
pos(eqo("journals/vldb/RamamurthyDS03","uem5wXLoU0wJ")).
pos(eqo("journals/vldb/RamamurthyDS03","vGFdY2gG8YsJ")).
pos(eqo("journals/vldb/ScheuermannWZ98","Q_JRmsXFEM4J")).
pos(eqo("journals/vldb/SinghalS97","3fO2448hZgwJ")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","FnypYUw9pwEJ")).
pos(eqo("journals/vldb/WhiteD95","jKBaGqWJK2oJ")).
pos(eqo("journals/vldb/WidomS00","url:http://www.springerlink.com/index/JWGUMV8YDL893E3V.pdf")).
