neg(eqo("conf/sigmod/AbiteboulCM95","-NNuFjchxnMJ")).
neg(eqo("conf/sigmod/AbiteboulCM95","XTa-ElbpjZ8J")).
neg(eqo("conf/sigmod/AggarwalY01","x5jeMyauzWgJ")).
neg(eqo("conf/sigmod/AgrawalCD02","6Cdfxiuibd0J")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","WA52h-tCVkMJ")).
neg(eqo("conf/sigmod/BilirisDGJR94","3Lzo6p8X-n4J")).
neg(eqo("conf/sigmod/BlakeleyD00","ZSR-MThg9UEJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","tK5ap9cBMIsJ")).
neg(eqo("conf/sigmod/BohmBKK01","atNo_T9JmBMJ")).
neg(eqo("conf/sigmod/CareyMN97","Aa9t5-2FNM4J")).
neg(eqo("conf/sigmod/CatarciS94","-qsHBe_0vI4J")).
neg(eqo("conf/sigmod/ChaudhuriG96","GHjgDrEbqM4J")).
neg(eqo("conf/sigmod/CherniackZ98","lc7d2bpuBCMJ")).
neg(eqo("conf/sigmod/CluetDSS98","lOZF0Ee3rUQJ")).
neg(eqo("conf/sigmod/CookWZ94","VcVAYDLTty8J")).
neg(eqo("conf/sigmod/FaloutsosRM94","LAaKiNCBkmAJ")).
neg(eqo("conf/sigmod/FukudaMMT96","Y8UdbAPhYpUJ")).
neg(eqo("conf/sigmod/GatziuGD95","xXD5q6P9u2wJ")).
neg(eqo("conf/sigmod/GionisGK01","A8rGBQif7MIJ")).
neg(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
neg(eqo("conf/sigmod/GuoSBS03","P8lAsCCNIgQJ")).
neg(eqo("conf/sigmod/Han96","f86VsMJZ9gAJ")).
neg(eqo("conf/sigmod/HinneburgKW02","L61_1TEGBLYJ")).
neg(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
neg(eqo("conf/sigmod/Mamoulis03","nfaiuLafjSUJ")).
neg(eqo("conf/sigmod/McAuliffeCS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D232628%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Miller98","7f6Q9GgXsmgJ")).
neg(eqo("conf/sigmod/Mohan99","M4G18MfKn2oJ")).
neg(eqo("conf/sigmod/MohanN94","XppwYYxOpksJ")).
neg(eqo("conf/sigmod/Moore95","url:http://www.ncbi.nlm.nih.gov/entrez/query.fcgi%3Fcmd%3DRetrieve%26db%3DPubMed%26list_uids%3D748423%26dopt%3DCitation")).
neg(eqo("conf/sigmod/OzdenRSS96","TsShfxPwF6YJ")).
neg(eqo("conf/sigmod/RamanH02","4692SthNStUJ")).
neg(eqo("conf/sigmod/RamaswamyK95","g9Y0KAu_UHQJ")).
neg(eqo("conf/sigmod/RodriguezR00","bF9t6EpjL14J")).
neg(eqo("conf/sigmod/RundensteinerCCSO00","9wQ6RWWcHRIJ")).
neg(eqo("conf/sigmod/Seshadri99","aXLcAfb2y5kJ")).
neg(eqo("conf/sigmod/SismanisDRK02","Y21HA44xuQ4J")).
neg(eqo("conf/sigmod/Stonebraker98","z8UTEms4_WsJ")).
neg(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
neg(eqo("conf/sigmod/ZaianeHLCC98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776990%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ZhouLP99","6uelfg3RgEoJ")).
neg(eqo("conf/sigmod/ZouS96","qPCh8M_RSwEJ")).
neg(eqo("conf/vldb/AcharyaFZ96","2fO9nM2FoGYJ")).
neg(eqo("conf/vldb/AgrawalSX01","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/AgrawalSX01","ujWZNcj2qkgJ")).
neg(eqo("conf/vldb/AmbiteKKMST01","JAqN-p0bwPAJ")).
neg(eqo("conf/vldb/AnciauxBP03","D48Ssn95H34J")).
neg(eqo("conf/vldb/ArunJ98","5JKmsN-7Q9UJ")).
neg(eqo("conf/vldb/AshwinGG02","6n2-0XOjwV4J")).
neg(eqo("conf/vldb/BlottKS98","njuthCBUMPAJ")).
neg(eqo("conf/vldb/BohannonFHRRS02","url:http://www.springerlink.com/index/G541544051U4243L.pdf")).
neg(eqo("conf/vldb/BohannonGKNS02","A8qZGxwlDiYJ")).
neg(eqo("conf/vldb/BunemanDHOW95","4k4fUbwNV8UJ")).
neg(eqo("conf/vldb/CareyK98","v-kvo2hnsgkJ")).
neg(eqo("conf/vldb/ChaudhuriN97","hWNG6uakIt0J")).
neg(eqo("conf/vldb/ChenRS95","oGxLABq_hAoJ")).
neg(eqo("conf/vldb/ChienVZTZ02","eybUiurX77sJ")).
neg(eqo("conf/vldb/ChoN02","GukaCxN-t58J")).
neg(eqo("conf/vldb/ChoenniV00","R1j3CdeOlwsJ")).
neg(eqo("conf/vldb/DattaDTVRF01","8_5A88ESaQ0J")).
neg(eqo("conf/vldb/DiwanRSS96","0NK87fQBfPUJ")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D200308250549CI%26recid%3D200308500246EA")).
neg(eqo("conf/vldb/FlorescuLS98","j0VFhTfD8yMJ")).
neg(eqo("conf/vldb/FukudaMMT96","hjuGWEzCIB4J")).
neg(eqo("conf/vldb/GaasterlandL94","9rDLhwM_4mYJ")).
neg(eqo("conf/vldb/GarofalakisI97","ImADir74KWIJ")).
neg(eqo("conf/vldb/GarofalakisRS99","zJ6gN0riEsQJ")).
neg(eqo("conf/vldb/Gentili01","KuYNNvJtkeMJ")).
neg(eqo("conf/vldb/Graefe99","N2Q6TnVleTIJ")).
neg(eqo("conf/vldb/HaberIL95","DLsoji25xSAJ")).
neg(eqo("conf/vldb/HanF95","t8W8vA4VvpAJ")).
neg(eqo("conf/vldb/HankinsP03","uSsvtrcPrRAJ")).
neg(eqo("conf/vldb/HelmerM97","lwRMZsUhny0J")).
neg(eqo("conf/vldb/JohnsonM98","FqxbaJQMigIJ")).
neg(eqo("conf/vldb/JohnsonS94","qaSgL5tVq1AJ")).
neg(eqo("conf/vldb/KahveciS01","gZ60Ten2H7oJ")).
neg(eqo("conf/vldb/KraftSRM03","url:http://doi.wiley.com/10.1002/tl.123")).
neg(eqo("conf/vldb/LiCHPALHAY01","100PFCYhqIgJ")).
neg(eqo("conf/vldb/MengLYWCR98","qtwJ7XWG9JIJ")).
neg(eqo("conf/vldb/Novaretti01","tZtnFoH5lY0J")).
neg(eqo("conf/vldb/PalpanasSCP02","szlqyCesMpgJ")).
neg(eqo("conf/vldb/PantiSG00","K6oim0ysxRgJ")).
neg(eqo("conf/vldb/PoosalaI97","_r6fTVXSbn4J")).
neg(eqo("conf/vldb/RamakrishnanR96","d_oZjh9vWLkJ")).
neg(eqo("conf/vldb/SakuraiYKU01","OQMYc3S0Ny8J")).
neg(eqo("conf/vldb/Sarawagi00","sRcMuuo3-BEJ")).
neg(eqo("conf/vldb/Sarawagi99","K1o894GE6S0J")).
neg(eqo("conf/vldb/SavasereON95","y1hmJODjq7UJ")).
neg(eqo("conf/vldb/SeligmanBNSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.673303%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/ShuklaDNR96","gTSn7nMr9dQJ")).
neg(eqo("conf/vldb/StillgerLMK01","j31DFYaBvVoJ")).
neg(eqo("conf/vldb/StolteA02","U0JhB6VKSTUJ")).
neg(eqo("conf/vldb/StolteA02","htMO0uWGzvoJ")).
neg(eqo("conf/vldb/Uhl02","lovlkpxUzUsJ")).
neg(eqo("conf/vldb/VermeerA96","bEddMdwB2_4J")).
neg(eqo("conf/vldb/ZhouLZLZJT01","url:http://www.ingentaconnect.com/content/els/09505849/2001/00000043/00000014/art00205")).
neg(eqo("journals/sigmod/BertinoEH01","nMATqL8oZ4IJ")).
neg(eqo("journals/sigmod/BertinoEH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373684%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BertinoEH03","bF9t6EpjL14J")).
neg(eqo("journals/sigmod/Chen94","VUguEWkqzvoJ")).
neg(eqo("journals/sigmod/CherniakV03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Cingil02","Scvi9CgaQ_YJ")).
neg(eqo("journals/sigmod/David03","D-ovsaXJxZgJ")).
neg(eqo("journals/sigmod/EisenbergM02","JHVWab3P4zIJ")).
neg(eqo("journals/sigmod/FernandezFLS97","rgk1HYJbTNEJ")).
neg(eqo("journals/sigmod/Franklin99b","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/GolabO03","jGb8C7wu8aYJ")).
neg(eqo("journals/sigmod/Group94","3NULIkA1kgQJ")).
neg(eqo("journals/sigmod/Han98","GeMycbLXZUkJ")).
neg(eqo("journals/sigmod/Han98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/JukicNV03","eN_4FTimCKYJ")).
neg(eqo("journals/sigmod/Kim99","nu5nhxl6WXQJ")).
neg(eqo("journals/sigmod/KuanL99","yt6km18gHIIJ")).
neg(eqo("journals/sigmod/Liu02c","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Liu03a","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/MarchiLPT03","9dgFU6XaLrwJ")).
neg(eqo("journals/sigmod/MarchiLPT03","ePf9ainjNqwJ")).
neg(eqo("journals/sigmod/Ozsu02a","csz36g3kmqcJ")).
neg(eqo("journals/sigmod/PitouraAPSV03","hn2MANNgz9sJ")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","yN9f4dSKC9QJ")).
neg(eqo("journals/sigmod/RosenthalSMBTL95","-_FyboGgZkkJ")).
neg(eqo("journals/sigmod/RossGR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Roussopoulos98","u2jFZnoPLM8J")).
neg(eqo("journals/sigmod/SantucciT96","f86VsMJZ9gAJ")).
neg(eqo("journals/sigmod/Scholl01","url:http://portal.acm.org/citation.cfm%3Fid%3D604275")).
neg(eqo("journals/sigmod/Segev94","dr9pItw3BZUJ")).
neg(eqo("journals/sigmod/Snodgrass03b","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084832")).
neg(eqo("journals/sigmod/Snodgrass03c","KENWBobILMwJ")).
neg(eqo("journals/sigmod/SnodgrassACFLLORRSV99","Ng15BDhGEWsJ")).
neg(eqo("journals/sigmod/StolfoLCFE01","lvIPWxkN4YAJ")).
neg(eqo("journals/sigmod/Stonebraker02","b9sQcMYi3F4J")).
neg(eqo("journals/sigmod/Widom95a","hqDtMiCwjGoJ")).
neg(eqo("journals/sigmod/Wong95","url:http://www.ncbi.nlm.nih.gov/entrez/query.fcgi%3Fcmd%3DRetrieve%26db%3DPubMed%26list_uids%3D15654733%26dopt%3DCitation")).
neg(eqo("journals/sigmod/YaoG02","aDk2IS_xwToJ")).
neg(eqo("journals/tods/EiterGM97","2hyvWKKnJOUJ")).
neg(eqo("journals/tods/HsuSY01","5F8zDLScIK0J")).
neg(eqo("journals/tods/JacoxS03","hshhy8lzrR8J")).
neg(eqo("journals/tods/LeveneL99","43v9FSxyXVgJ")).
neg(eqo("journals/tods/SalemGS94","og1PK9Js-EcJ")).
neg(eqo("journals/tods/Suciu02","zUk4Gy_sOy0J")).
neg(eqo("journals/vldb/AbiteboulB95","NQY7cpXcwPoJ")).
neg(eqo("journals/vldb/AguileraCMVV02","SdVmepmUgQIJ")).
neg(eqo("journals/vldb/CasatiSG01","omw6Mamq1_AJ")).
neg(eqo("journals/vldb/ChidlovskiiB00","dtDVvyN332sJ")).
neg(eqo("journals/vldb/CliftonGB95","8B-KY_3fXlkJ")).
neg(eqo("journals/vldb/CuiW03","nwbcR_-V7ScJ")).
neg(eqo("journals/vldb/FahlR97","hIdEy-va1vQJ")).
neg(eqo("journals/vldb/FernandezFLS00","LJKpMU1tIlcJ")).
neg(eqo("journals/vldb/GibsonKR00","lmDWqPhISnwJ")).
neg(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
neg(eqo("journals/vldb/TenienteO95","D45fvUWVon0J")).
neg(eqo("journals/vldb/VaghaniRKSSLH94","r8fWKfXfbOEJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","ZdWKBKSoMUQJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","cHxtmO9talkJ")).
pos(eqo("conf/sigmod/BargaL99","hf84fEpX5agJ")).
pos(eqo("conf/sigmod/CandanLLHA01","efYVCK07AwMJ")).
pos(eqo("conf/sigmod/Chakravarthy97","pCsAI2xXTPoJ")).
pos(eqo("conf/sigmod/ChenJDTW00","JcnZJ-eE2XsJ")).
pos(eqo("conf/sigmod/ChenJDTW00","fg5EE6R7xYwJ")).
pos(eqo("conf/sigmod/ColeG94","_6wwPJEGUiAJ")).
pos(eqo("conf/sigmod/CranorGJSS02","Up9QQITiHzAJ")).
pos(eqo("conf/sigmod/DanS95","qjHzY4uEG7gJ")).
pos(eqo("conf/sigmod/FreireHRRS02","YKkMxZntSUQJ")).
pos(eqo("conf/sigmod/GehrkeKS01","KIp3KSU4whsJ")).
pos(eqo("conf/sigmod/GingrasLSPS97","D0EVu0EZM-UJ")).
pos(eqo("conf/sigmod/GoyalHKMSZ97","D-1jnVnmWnQJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","ASfROcKWFmgJ")).
pos(eqo("conf/sigmod/HanPY00","R-ERjYdCskcJ")).
pos(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
pos(eqo("conf/sigmod/HanPY00","mwSZ7Yejt8sJ")).
pos(eqo("conf/sigmod/IvesLPST00","4-FwpSOweRAJ")).
pos(eqo("conf/sigmod/KaushikBNK02","xJQAjLzvlB0J")).
pos(eqo("conf/sigmod/KeoghCMP01","Cy8VDlIamc8J")).
pos(eqo("conf/sigmod/KeoghCMP01","_nOW6fmEcTEJ")).
pos(eqo("conf/sigmod/KeoghCMP01","eHY42LnL_lsJ")).
pos(eqo("conf/sigmod/KriegelBKPS03","i0c65loyE60J")).
pos(eqo("conf/sigmod/LakshmananPZ03","F1aaWSFF8TcJ")).
pos(eqo("conf/sigmod/LibkinMW96","OfZWx8jhQvwJ")).
pos(eqo("conf/sigmod/MaddenH02","NXakCefUcdUJ")).
pos(eqo("conf/sigmod/MerialdoAMMP00","Qq0WheHyVv8J")).
pos(eqo("conf/sigmod/PangCL94","beMsu5ebf30J")).
pos(eqo("conf/sigmod/RoussopoulosKV95","efwTNo1wRnMJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","LMm4_4_uNNoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","QZQt-pSMhYQJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wnMZjFGvYVQJ")).
pos(eqo("conf/sigmod/SrikantA96","KwgLlNLlaTcJ")).
pos(eqo("conf/sigmod/SrikantA96","Sf7DDYXGGD8J")).
pos(eqo("conf/sigmod/SrikantA96","WSVs3nCRe8EJ")).
pos(eqo("conf/sigmod/SrikantA96","tTQpdbZYZGoJ")).
pos(eqo("conf/sigmod/SzalayGKT00","oPgy1SYoptgJ")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","W1IuO3EFDJ8J")).
pos(eqo("conf/sigmod/YanMHF01","8hRWaIVZ2ykJ")).
pos(eqo("conf/sigmod/YanMHF01","z1HqFeqNEjgJ")).
pos(eqo("conf/sigmod/ZhangRL96","8UbrDL0jsOYJ")).
pos(eqo("conf/sigmod/ZhangRL96","CcBKCycL0gwJ")).
pos(eqo("conf/sigmod/ZhangRL96","ICoe8GLPWMIJ")).
pos(eqo("conf/sigmod/ZhangRL96","PdBcau_cG-AJ")).
pos(eqo("conf/sigmod/ZhangRL96","Q4JDSTBf5_oJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","0MJZbBBMixgJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","YtqWhs8DYBUJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AgrawalCN00","3s20zaTMLZQJ")).
pos(eqo("conf/vldb/AgrawalCN00","49BUF_66HgcJ")).
pos(eqo("conf/vldb/AgrawalCN00","Jx63MEaw52oJ")).
pos(eqo("conf/vldb/AksoyZF01","z6Z1hQYHTAMJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","62aA4DYB0MQJ")).
pos(eqo("conf/vldb/BestavrosB95","LDv4my6gWJQJ")).
pos(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
pos(eqo("conf/vldb/BonczMK99","6GAoBRINv7kJ")).
pos(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
pos(eqo("conf/vldb/ChandrasekaranF02","nqosSM46lCkJ")).
pos(eqo("conf/vldb/ChandrasekaranF02","y-0iu9SS36YJ")).
pos(eqo("conf/vldb/ChangG00","H4BAFnrsTbwJ")).
pos(eqo("conf/vldb/ChaudhuriG99","l-Sn0enuHxkJ")).
pos(eqo("conf/vldb/ChenDZ03","cCpHMzAXRnsJ")).
pos(eqo("conf/vldb/FlodinR95","b5vbAhJ4xxMJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","OEpwAcnqlWwJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","XtFcz806WQEJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","nlOAkKW_ry8J")).
pos(eqo("conf/vldb/GalhardasFSSS01","otGW0G5B6AYJ")).
pos(eqo("conf/vldb/GantiLR00","Vd-lSpZc0cYJ")).
pos(eqo("conf/vldb/GarofalakisRS99","7BITau8qhpEJ")).
pos(eqo("conf/vldb/GarofalakisRS99","Xm3ygCvkmN8J")).
pos(eqo("conf/vldb/GarofalakisRS99","poso7AKokFMJ")).
pos(eqo("conf/vldb/GarofalakisRS99","q87jrCR_GqQJ")).
pos(eqo("conf/vldb/GolabO03","6K9FhI2pFEgJ")).
pos(eqo("conf/vldb/GoldsteinR00","FncQ86sO2agJ")).
pos(eqo("conf/vldb/GoldsteinR00","ylZFc8RNoeQJ")).
pos(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
pos(eqo("conf/vldb/HaberIL95","UM1ZozyrJnIJ")).
pos(eqo("conf/vldb/HoskingC99","8Pt19BiLeHEJ")).
pos(eqo("conf/vldb/KalusD95","r1xwwqWr2K0J")).
pos(eqo("conf/vldb/KonopnickiS95","VbPeo_JSln8J")).
pos(eqo("conf/vldb/KonopnickiS95","cA1Zsnlz-tIJ")).
pos(eqo("conf/vldb/KonopnickiS95","z5Z9vSNOznMJ")).
pos(eqo("conf/vldb/LakshmananPZ03","tcnjvKELfs0J")).
pos(eqo("conf/vldb/LakshmananSS96","7Xoa7OiZLXMJ")).
pos(eqo("conf/vldb/LakshmananSS96","XPjpq3h5BhUJ")).
pos(eqo("conf/vldb/LempelM02","DcSYGPdhxwoJ")).
pos(eqo("conf/vldb/LockemannKKKN97","mFJzfuwL1jcJ")).
pos(eqo("conf/vldb/Mattos03","HeE1NxaX5t8J")).
pos(eqo("conf/vldb/MedianoCD94","qwjRkZuiMHsJ")).
pos(eqo("conf/vldb/MengLLA03","_dOpWA3QWOEJ")).
pos(eqo("conf/vldb/Mohan96","wYwNJy4GsEYJ")).
pos(eqo("conf/vldb/Mohan99","4N472VSotmMJ")).
pos(eqo("conf/vldb/MorishimaKKT01","8hDo6qczOzMJ")).
pos(eqo("conf/vldb/NathDKGKS03","pF6EW_yKYyYJ")).
pos(eqo("conf/vldb/NatsevCSLV01","173qcCip5coJ")).
pos(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
pos(eqo("conf/vldb/PapadiasMD98","7vbPCi-dbawJ")).
pos(eqo("conf/vldb/PatonG01","mHCrMuxQnBsJ")).
pos(eqo("conf/vldb/RamsakMFZEB00","4fN0QEu0KeAJ")).
pos(eqo("conf/vldb/RizviH02","3ku_XOqYuawJ")).
pos(eqo("conf/vldb/StaudtJ96","6moFnThDHW0J")).
pos(eqo("conf/vldb/YuPM03","ZEEZqsnVCyYJ")).
pos(eqo("journals/sigmod/BarbaraBFLS94","sF4xdH31mDAJ")).
pos(eqo("journals/sigmod/BernsteinDK99","MsK0xHsckUIJ")).
pos(eqo("journals/sigmod/BernsteinDK99","Ye5fTBiMoUwJ")).
pos(eqo("journals/sigmod/BernsteinDK99","ne7WhiSL9QYJ")).
pos(eqo("journals/sigmod/BrunieK96","spI2g7jFHuYJ")).
pos(eqo("journals/sigmod/CeriKKLOSV00","nLbW09uNfmsJ")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","oAO74aolStoJ")).
pos(eqo("journals/sigmod/EisenbergM00","4mD1eFCHKKwJ")).
pos(eqo("journals/sigmod/EisenbergM00","O5S8QV9TOXAJ")).
pos(eqo("journals/sigmod/JainH94","iQMUP3fkvo4J")).
pos(eqo("journals/sigmod/Ouksel03","8M_z-OUkoxYJ")).
pos(eqo("journals/sigmod/PitouraB95","KlM6IrItVpcJ")).
pos(eqo("journals/sigmod/Seshadri98","XijyPb231fAJ")).
pos(eqo("journals/sigmod/ShethGJRSWW96","yI5E8TGu5BwJ")).
pos(eqo("journals/sigmod/SonDT96","62uEWBKYqgoJ")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/SureSS02","v0tY6g0DHMcJ")).
pos(eqo("journals/sigmod/SycaraKWL99","-IaXJNRxKVEJ")).
pos(eqo("journals/sigmod/SycaraKWL99","foOIj5nrS-gJ")).
pos(eqo("journals/sigmod/TanK03","qIzj09N-Qr8J")).
pos(eqo("journals/sigmod/Vianu03","JgenqfLQC1UJ")).
pos(eqo("journals/sigmod/Widom94","lAbG3uFZvVUJ")).
pos(eqo("journals/tods/BohlenJS00","6eheB6Kct4MJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","Cy8VDlIamc8J")).
pos(eqo("journals/tods/ChakrabartiKMP02","_nOW6fmEcTEJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","eHY42LnL_lsJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","5cAIVZJShAEJ")).
pos(eqo("journals/tods/KarpSP03","mAQIVsd2VOMJ")).
pos(eqo("journals/tods/LakshmananLRS97","UByN6paxEXwJ")).
pos(eqo("journals/tods/LakshmananLRS97","dOscxZFxArwJ")).
pos(eqo("journals/tods/MokNE96","xUeP4X8k5SoJ")).
pos(eqo("journals/tods/SalemGS94","7IBL1cudvR0J")).
pos(eqo("journals/tods/StoreyCDGS97","NL_8pNIYC-0J")).
pos(eqo("journals/tods/Subrahmanian94","KnKwXVSXN_wJ")).
pos(eqo("journals/tods/Subrahmanian94","MWxdDHB-vH8J")).
pos(eqo("journals/tods/Subrahmanian94","UumKoUpnFSwJ")).
pos(eqo("journals/tods/TaoSP03","FBp7oibu4ygJ")).
pos(eqo("journals/vldb/AguileraCMVV02","itG_XrygxXIJ")).
pos(eqo("journals/vldb/EyalM01","ntrSSBumclMJ")).
pos(eqo("journals/vldb/Guting94","TruJ2Gi7fiQJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/GutingS95","dm3xutmyi_0J")).
pos(eqo("journals/vldb/HansonCDERTX98","F6Ko8ZvWypUJ")).
pos(eqo("journals/vldb/HelmerM03","lqAgqxpXpxMJ")).
pos(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
pos(eqo("journals/vldb/PucheralBVB01","8DRB_dYz2CgJ")).
pos(eqo("journals/vldb/SivasankaranSTPR96","url:http://ieeexplore.ieee.org/iel2/997/7843/00331718.pdf%3Farnumber%3D331718")).
pos(eqo("journals/vldb/SivasankaranSTPR96","x2c_pMyVtCoJ")).
pos(eqo("journals/vldb/WhiteD95","qeHXdJ2x7eMJ")).
