neg(eqo("conf/sigmod/AdelbergGW97","26TvUQo5rkYJ")).
neg(eqo("conf/sigmod/BarclaySG00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D333608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BersonGMJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058156%26type%3Dpdf")).
neg(eqo("conf/sigmod/BlottRS96","Fz7LXJ1UckkJ")).
neg(eqo("conf/sigmod/BryanMCLG94","ie9hhRD7fVQJ")).
neg(eqo("conf/sigmod/BumbulisB02","BTalXWt3faUJ")).
neg(eqo("conf/sigmod/ButtlerLPP01","c0D02SzWH9MJ")).
neg(eqo("conf/sigmod/CeriFPP95","zSM0goBgDdsJ")).
neg(eqo("conf/sigmod/Chakrabarti99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304231%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ChaudhuriKN03","enUg70kEpM8J")).
neg(eqo("conf/sigmod/ChawatheG97","c-5n9qQKLaEJ")).
neg(eqo("conf/sigmod/ChawatheG97","zmjSyKEk-dIJ")).
neg(eqo("conf/sigmod/CherniackZ96","iZWCGwe_WMQJ")).
neg(eqo("conf/sigmod/Colliat03","ycyOGNNmFUkJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03a","pF6EW_yKYyYJ")).
neg(eqo("conf/sigmod/Ellison95","ESge0RjQQ40J")).
neg(eqo("conf/sigmod/FaginKS03","lvfwZlkxHq8J")).
neg(eqo("conf/sigmod/FlorescuGKR02","uam2rv99rxsJ")).
neg(eqo("conf/sigmod/GarofalakisRRS99","VTBK-oipkLgJ")).
neg(eqo("conf/sigmod/Gerber95","ztpceRBO43EJ")).
neg(eqo("conf/sigmod/GillmannWSWW00","ddSt2iZAvvEJ")).
neg(eqo("conf/sigmod/GrossmanHQ95","yjqdBeNw5WoJ")).
neg(eqo("conf/sigmod/HanKK97","GDoFPiEzEhQJ")).
neg(eqo("conf/sigmod/Hellerstein94","SZ5SSKr5GFwJ")).
neg(eqo("conf/sigmod/HristidisKP01","c-5n9qQKLaEJ")).
neg(eqo("conf/sigmod/IoannidisP95","mJrYUt7HaOEJ")).
neg(eqo("conf/sigmod/KalnisNOPT02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373709%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Kleissner95","DB8lVC2D9fcJ")).
neg(eqo("conf/sigmod/Kohler99","FBZw8n-gojUJ")).
neg(eqo("conf/sigmod/LitwinS00","RQ9fpPAS2h8J")).
neg(eqo("conf/sigmod/LlirbatFS97","hnAG1QBlnbwJ")).
neg(eqo("conf/sigmod/MankuRL99","M2bWqRDDfkUJ")).
neg(eqo("conf/sigmod/McIverK94","-fXblp3TRRoJ")).
neg(eqo("conf/sigmod/Mohan01","4N472VSotmMJ")).
neg(eqo("conf/sigmod/Raghavan03","MC7lRbeNCUkJ")).
neg(eqo("conf/sigmod/RamakrishnanD98","url:http://portal.acm.org/citation.cfm%3Fid%3D276305.276361%26dl%3DGUIDE%26dl%3DACM%26idx%3D276305%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RamaswamyRS00","hOcniOdybHQJ")).
neg(eqo("conf/sigmod/RaoBG96","29btu5OspbAJ")).
neg(eqo("conf/sigmod/RiedewaldAA02","nQvBo5KHITYJ")).
neg(eqo("conf/sigmod/RiedewaldAA02","xrGxxmqz4G8J")).
neg(eqo("conf/sigmod/Ross00","RBRJ4CpAtPEJ")).
neg(eqo("conf/sigmod/Tajima96","pnIaP8Ps4QgJ")).
neg(eqo("conf/sigmod/WangCMSSZ94","zNuhEWxo2iUJ")).
neg(eqo("conf/vldb/AbiteboulACEMM99","fpI2ez86iIkJ")).
neg(eqo("conf/vldb/AcharyaFZ96","gJPWbysKyQgJ")).
neg(eqo("conf/vldb/AcharyaGP99","BOlDJUneX8sJ")).
neg(eqo("conf/vldb/Adler01","uAdfU0W_T-UJ")).
neg(eqo("conf/vldb/AggarwalY02","W9wJnFy0TDAJ")).
neg(eqo("conf/vldb/AnanthakrishnaCG02","gU-dOX4-eeYJ")).
neg(eqo("conf/vldb/BargaP95","SsOLRJZrmtYJ")).
neg(eqo("conf/vldb/Baru96","3V6BTODTE_QJ")).
neg(eqo("conf/vldb/BergerBSW03","01iwVR6RAU8J")).
neg(eqo("conf/vldb/BergerBSW03","Wjg_SYCySOsJ")).
neg(eqo("conf/vldb/Bernstein94","pb3OQtY3SyMJ")).
neg(eqo("conf/vldb/BonczMK99","3nXBlVy0-HUJ")).
neg(eqo("conf/vldb/Campbell99","137tkLGO17kJ")).
neg(eqo("conf/vldb/CarusoCGLM00","PcAKDUTqlgoJ")).
neg(eqo("conf/vldb/CasatiS00","Z98EPUjBiL0J")).
neg(eqo("conf/vldb/CeriM03","F8MvqYWDkp4J")).
neg(eqo("conf/vldb/ChaudhuriG99","H5IdN0_MQw4J")).
neg(eqo("conf/vldb/ChaudhuriGS95","ThEw8obz2UsJ")).
neg(eqo("conf/vldb/ChaudhuriN97","99oqRZGWAYMJ")).
neg(eqo("conf/vldb/ChoG00","fDYygiJXShQJ")).
neg(eqo("conf/vldb/GalhardasFSSS01","otGW0G5B6AYJ")).
neg(eqo("conf/vldb/GaoS03","BEpwgIQR6r4J")).
neg(eqo("conf/vldb/Gawlick96","Rp6i1uA3RYQJ")).
neg(eqo("conf/vldb/GilbertKMS01","OkCz_NK5cbMJ")).
neg(eqo("conf/vldb/GuntzerBK00","94TyP9PsptAJ")).
neg(eqo("conf/vldb/Gupta96","qz0FSt_aTPwJ")).
neg(eqo("conf/vldb/HoelS95","BSE2se70OMYJ")).
neg(eqo("conf/vldb/HumborstadSHT97","Sko145Nl9roJ")).
neg(eqo("conf/vldb/JagadishLS99","07Ec8cH2UhAJ")).
neg(eqo("conf/vldb/KeimH99","url:http://pubs.acs.org/cgi-bin/abstract.cgi/achre4/2005/38/i02/abs/ar020247w.html")).
neg(eqo("conf/vldb/King02","YXQd3uRooD8J")).
neg(eqo("conf/vldb/MadhavanBR01","f9q1hWU6JLYJ")).
neg(eqo("conf/vldb/Mattos03","HeE1NxaX5t8J")).
neg(eqo("conf/vldb/Mohan01","GR7rWnh1g6gJ")).
neg(eqo("conf/vldb/PapadiasMD98","7vbPCi-dbawJ")).
neg(eqo("conf/vldb/PardonA00","oIFrkS2rPrcJ")).
neg(eqo("conf/vldb/PirotteZMY94","6zFG1vxb3RYJ")).
neg(eqo("conf/vldb/PossP03","Xibam4t157UJ")).
neg(eqo("conf/vldb/Sacks-Davis96","0HahngOAgPQJ")).
neg(eqo("conf/vldb/ShaferAM96","oVWSNBlWR84J")).
neg(eqo("conf/vldb/ShuklaDNR96","tJtSq968rwgJ")).
neg(eqo("conf/vldb/TanSHCR01","gJppRzmzaWoJ")).
neg(eqo("conf/vldb/TsatalosSI94","I3DBXw7WWWkJ")).
neg(eqo("conf/vldb/WeberSB98","6D0Qt6Sjp8cJ")).
neg(eqo("conf/vldb/WeikumMHZ02","NbDF9UBuTsEJ")).
neg(eqo("journals/sigmod/Aberer03c","CYJR7X2NtGMJ")).
neg(eqo("journals/sigmod/BollKB98","EvdMClrP1SIJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141004%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/CoxEH96","0HMk-YUh4i8J")).
neg(eqo("journals/sigmod/CruzKLSWY02","T1dmP2NL1aYJ")).
neg(eqo("journals/sigmod/DogacAOD95","rKIdcFtH4jUJ")).
neg(eqo("journals/sigmod/DogacDKOONEHAKKM95","OCJOsTjec7wJ")).
neg(eqo("journals/sigmod/ErdurD02","ig7B9agTOMAJ")).
neg(eqo("journals/sigmod/FifeG03","To_EjIKwfSAJ")).
neg(eqo("journals/sigmod/Franklin00a","iDBvvrHwj7YJ")).
neg(eqo("journals/sigmod/Franklin97a","zc1TRuoDDwgJ")).
neg(eqo("journals/sigmod/Franklin97b","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/Franklin98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","Sg5UhqcDrS0J")).
neg(eqo("journals/sigmod/Han98","ehSjmvsHTmMJ")).
neg(eqo("journals/sigmod/Jarke95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202671%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Libkin99","zSO1Y5W7WkwJ")).
neg(eqo("journals/sigmod/Liu02a","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu02c","r3hFnyB0LAQJ")).
neg(eqo("journals/sigmod/Lomet98","o4XsUOzknMUJ")).
neg(eqo("journals/sigmod/Lomet98","yQv94p3tE1IJ")).
neg(eqo("journals/sigmod/Manola98","4wUTpq8VhJYJ")).
neg(eqo("journals/sigmod/NascimentoM99","TyJ-eq-pdkIJ")).
neg(eqo("journals/sigmod/Neven02","url:http://www.springerlink.com/index/5G6L5CVD7NA9HCJJ.pdf")).
neg(eqo("journals/sigmod/PapianiWDN99","HxmnEeCigX8J")).
neg(eqo("journals/sigmod/PossasMCR00","bZj9gl0_YUIJ")).
neg(eqo("journals/sigmod/RashidS00","uFg3AWTRxYYJ")).
neg(eqo("journals/sigmod/Snodgrass00a","UE24twi-1wMJ")).
neg(eqo("journals/sigmod/SpynsMJ02","zjqjS0Ol0OEJ")).
neg(eqo("journals/sigmod/Stacey95","kgl4TaGT2mIJ")).
neg(eqo("journals/sigmod/Suciu97","QCgt1vJkfosJ")).
neg(eqo("journals/sigmod/Winslett01","ftxXMRhxDJEJ")).
neg(eqo("journals/sigmod/Winslett02b","PqG4yAX-PnUJ")).
neg(eqo("journals/sigmod/ZobelMR96","tdDLf6RffisJ")).
neg(eqo("journals/tods/ChakrabartiKMP02","vql9YVBySmEJ")).
neg(eqo("journals/tods/FegarasM00","ykGQlI-IaJkJ")).
neg(eqo("journals/tods/GunopulosKMSTS03","-q1BFuUI27EJ")).
neg(eqo("journals/tods/Keen97","Xq63G-3bpBoJ")).
neg(eqo("journals/tods/LakshmananSS01","0VHtbuWJCQUJ")).
neg(eqo("journals/tods/ScioreSR94","fB2xVdlMTtwJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/LD48KCXJWTCRACDL.pdf")).
neg(eqo("journals/tods/Subrahmanian94","RUyqFOxZyDoJ")).
neg(eqo("journals/tods/TaoSP03","Qmv55n1HpkAJ")).
neg(eqo("journals/tods/Wijsen99","url:http://www.springerlink.com/index/P13QGW28761T2060.pdf")).
neg(eqo("journals/vldb/AbiteboulCM98","5FiyBEZ3v70J")).
neg(eqo("journals/vldb/Atkinson00","hFoh_5Q0A1EJ")).
neg(eqo("journals/vldb/BraumandlKKKKSS01","dURGvGhlWbsJ")).
neg(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
neg(eqo("journals/vldb/FernandezFLS00","LJKpMU1tIlcJ")).
neg(eqo("journals/vldb/Li03","nbtZN1mHlNIJ")).
neg(eqo("journals/vldb/OzsuPSILM95","gld2wLKYWpsJ")).
neg(eqo("journals/vldb/RamamohanaraoH94","AgjBNoJVumgJ")).
pos(eqo("conf/sigmod/AbadiCCCCEGHMRSSTXYZ03","eBnT7lhV2LwJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","h2z51QPXcSkJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","FDPwbRQbfIAJ")).
pos(eqo("conf/sigmod/Atkinson95","url:http://portal.acm.org/citation.cfm%3Fid%3D223874")).
pos(eqo("conf/sigmod/BreunigKNS00","4ZBs-U7sOk0J")).
pos(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","eHM4OCdJA9YJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","qGTxTpQXTDsJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","xPkLZK36UBUJ")).
pos(eqo("conf/sigmod/ChenJDTW00","OsfWKJek9L8J")).
pos(eqo("conf/sigmod/CorralMTV00","TsShfxPwF6YJ")).
pos(eqo("conf/sigmod/DanielsDDEHJJLSSS94","fLNHwVFqnbIJ")).
pos(eqo("conf/sigmod/DasuJMS02","POt1WbTBB4cJ")).
pos(eqo("conf/sigmod/DasuJMS02","zTF5z0v_nh0J")).
pos(eqo("conf/sigmod/DavulcuFKR99","TDyW6V4cc7MJ")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/GillmannWW02","Pbjz4-UPrZ8J")).
pos(eqo("conf/sigmod/GravanoCGP97","1xxRTUP64bwJ")).
pos(eqo("conf/sigmod/GravanoCGP97","PsoYENGEh9cJ")).
pos(eqo("conf/sigmod/GravanoGT94","VxiP2MuiMM0J")).
pos(eqo("conf/sigmod/GravanoGT94","mO77XJl45iEJ")).
pos(eqo("conf/sigmod/GravanoGT94","nAJnhh70_0kJ")).
pos(eqo("conf/sigmod/GravanoGT94","z26H2tQo7bkJ")).
pos(eqo("conf/sigmod/GraySEBW94","JT61IMQEZ-QJ")).
pos(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/HernandezS95","CckDkmI4U3wJ")).
pos(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","1H_A7k3QsbQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","V-LO20klzSYJ")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/KrollW94","kUzm9ofgc1UJ")).
pos(eqo("conf/sigmod/KrollW94","zd_8s13rNRoJ")).
pos(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
pos(eqo("conf/sigmod/LeeKOTM00","C8RLbWKCgicJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","WSQzzj42AkEJ")).
pos(eqo("conf/sigmod/MayrS99","1lRZz4bZvxEJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","I-fmtPvluKEJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/PalmerF00","cnNLe97Pd2sJ")).
pos(eqo("conf/sigmod/ParkCY95","pN4pq6qELakJ")).
pos(eqo("conf/sigmod/ParkCY95","x5By8kBxxpwJ")).
pos(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","CXih3vmijaoJ")).
pos(eqo("conf/sigmod/SchleimerWA03","nCRFjDfhOmcJ")).
pos(eqo("conf/sigmod/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/ShuklaD00","kcrWfQEI9G8J")).
pos(eqo("conf/sigmod/WangZS95","QHrpE-XaLoMJ")).
pos(eqo("conf/sigmod/WhitneyS01","bZj9gl0_YUIJ")).
pos(eqo("conf/sigmod/WilschutFA95","Zdfxvjh6ca8J")).
pos(eqo("conf/sigmod/WilschutFA95","vgoFTdXYHZ0J")).
pos(eqo("conf/sigmod/YangYW00","JQuwW88-2_0J")).
pos(eqo("conf/sigmod/ZhuS03","QZs7L6Y94_UJ")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AltinelF00","JhWxdEDCPdUJ")).
pos(eqo("conf/vldb/AltinelF00","onPj3O8mJEAJ")).
pos(eqo("conf/vldb/BouguettayaEMO01","n-tA57d7ydcJ")).
pos(eqo("conf/vldb/Brin95","srjTPThCwrwJ")).
pos(eqo("conf/vldb/CareyD96","5HV8kccLoZ4J")).
pos(eqo("conf/vldb/CarinoOBS99","47kAOej6WIQJ")).
pos(eqo("conf/vldb/CasatiS00","OjOQRHgD-qwJ")).
pos(eqo("conf/vldb/ChanFFGR02","ZFI7XBuonJAJ")).
pos(eqo("conf/vldb/ChenL03","WaSgR87oMpcJ")).
pos(eqo("conf/vldb/CherniackZ98","So_H9Oer6lsJ")).
pos(eqo("conf/vldb/Chiueh94","PKK2ak_IzrgJ")).
pos(eqo("conf/vldb/ChungCLL01","mJiDvbtTKWoJ")).
pos(eqo("conf/vldb/DeWittKLPY94","WbnSYesbN8QJ")).
pos(eqo("conf/vldb/DeutschPT99","0aJOXauNqYIJ")).
pos(eqo("conf/vldb/GardarinGT95","DAUHADa6RjQJ")).
pos(eqo("conf/vldb/GarofalakisI97","aCvCz2wg854J")).
pos(eqo("conf/vldb/GrovlenHT98","SDXBxc0lIeYJ")).
pos(eqo("conf/vldb/HelmerM97","xsh0C_nCllsJ")).
pos(eqo("conf/vldb/HuntAI01","0GT_dHqK5roJ")).
pos(eqo("conf/vldb/ImielinskiB02","IQ_MbfJGh0kJ")).
pos(eqo("conf/vldb/KiesslingK02","4XP24_IFvPsJ")).
pos(eqo("conf/vldb/KiesslingK02","Z8bBN2cO11UJ")).
pos(eqo("conf/vldb/KnorrN98","yFmekFZgZmwJ")).
pos(eqo("conf/vldb/KonopnickiS95","SHYtwo2v-LAJ")).
pos(eqo("conf/vldb/KonopnickiS95","cA1Zsnlz-tIJ")).
pos(eqo("conf/vldb/KonopnickiS95","fAZ2KwztkLoJ")).
pos(eqo("conf/vldb/MarronL01","MiMYGwqrGY8J")).
pos(eqo("conf/vldb/MarronL01","a3aecJJ58NIJ")).
pos(eqo("conf/vldb/MillerHH00","6vtHcpLApB8J")).
pos(eqo("conf/vldb/MillerHH00","kfTc_TsqiP8J")).
pos(eqo("conf/vldb/NatsevCSLV01","173qcCip5coJ")).
pos(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/ScheuermannSV96","N3Hyyb1Qw8sJ")).
pos(eqo("conf/vldb/SenkulKT02","g7HDbO4GCN4J")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","C5EoaXfZ7BsJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","kaq5eLrzrQsJ")).
pos(eqo("conf/vldb/ShethKMWDLPLS96","tKPVyvxSJA8J")).
pos(eqo("conf/vldb/ShuklaDNR96","Qdw5iM0aKwAJ")).
pos(eqo("conf/vldb/ShuklaDNR96","gTSn7nMr9dQJ")).
pos(eqo("conf/vldb/ShuklaDNR96","vnezjPI8jYIJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","4bf1BkOuUNAJ")).
pos(eqo("conf/vldb/TatbulCZCS03","lPIihZrHfg8J")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/Tygar98","Q8cPIOWKZZ4J")).
pos(eqo("conf/vldb/YiF00","1XJk5BWEVe8J")).
pos(eqo("journals/sigmod/AndlerHEMBE96","WZ823oj6x3cJ")).
pos(eqo("journals/sigmod/BernsteinDK99","MsK0xHsckUIJ")).
pos(eqo("journals/sigmod/Bohlen95","v5P_NFXdOR8J")).
pos(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
pos(eqo("journals/sigmod/CiliaB02","Y1HVgTopekIJ")).
pos(eqo("journals/sigmod/Danish98","J2Mi5B81Il0J")).
pos(eqo("journals/sigmod/Danish98","mKZyoPZArGcJ")).
pos(eqo("journals/sigmod/FowlerPNB99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310060%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GlavitschSW94","IQjGtYPrUFUJ")).
pos(eqo("journals/sigmod/GuptaHR97","YSgaDQ95dfEJ")).
pos(eqo("journals/sigmod/Hampapur99","xW--Ei3c_qwJ")).
pos(eqo("journals/sigmod/JaegerF95","r1xWRhy7WVUJ")).
pos(eqo("journals/sigmod/JukicV97","yZbJS0Cd6cAJ")).
pos(eqo("journals/sigmod/KokkotosIPS95","-IvY8_ki_psJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","Fjyenk1hvFkJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","IoNxL_rg2_cJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","_u9eNZTiNSoJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373709%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","ZsUpDroAFBQJ")).
pos(eqo("journals/sigmod/Rosenthal98","ZMMeRrWUlOoJ")).
pos(eqo("journals/sigmod/RosenthalS99","AaKiSc1klw8J")).
pos(eqo("journals/tods/AikenHW95","XLld3hq3vt0J")).
pos(eqo("journals/tods/LitwinN96","l0W27c1C3NwJ")).
pos(eqo("journals/tods/MamoulisP01","Rg8V7NSK9tMJ")).
pos(eqo("journals/vldb/AbiteboulCM98","XTa-ElbpjZ8J")).
pos(eqo("journals/vldb/Barbara-MillaG94","IvPHHa01uUkJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","md3DWyujCrQJ")).
pos(eqo("journals/vldb/CliftonGB95","YkIvdNOC64cJ")).
pos(eqo("journals/vldb/FiebigHKMNSW02","w_FOwUavk0kJ")).
pos(eqo("journals/vldb/Han98","url:http://www.springerlink.com/index/YTPAB711B92NCE7J.pdf")).
pos(eqo("journals/vldb/JagadishKNS00","GtXc02EJjCgJ")).
pos(eqo("journals/vldb/OzsuPSILM95","epUf9ogilogJ")).
pos(eqo("journals/vldb/PacittiS00","UvvmhI5lqbsJ")).
pos(eqo("journals/vldb/PacittiS00","ZmvL3_H6DqUJ")).
pos(eqo("journals/vldb/PapazogluK97","3k9vWWMJiWYJ")).
pos(eqo("journals/vldb/RamamrithamC96","LAvs6Oe0ygMJ")).
pos(eqo("journals/vldb/RamamrithamC96","xbpaZ5AHFV0J")).
pos(eqo("journals/vldb/SheikholeslamiCZ00","2GWXn3jT0uwJ")).
pos(eqo("journals/vldb/TempletonHMB95","RKNGp2gmOTUJ")).
