neg(eqo("conf/sigmod/AbadiC02","YMcmy4FOXi8J")).
neg(eqo("conf/sigmod/AbiteboulCM95","6QKLA7Lgu_8J")).
neg(eqo("conf/sigmod/AcharyaGP00","v80FFBUTW_0J")).
neg(eqo("conf/sigmod/AcharyaGPR99","F2wVTEYkBWAJ")).
neg(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
neg(eqo("conf/sigmod/AdaliSS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290604%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Adelberg98","NbLabaGWoh4J")).
neg(eqo("conf/sigmod/Agarwal96","XzSqN32OqgMJ")).
neg(eqo("conf/sigmod/AgrawalGGR98","23GbcclZy6gJ")).
neg(eqo("conf/sigmod/Ahn94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381897%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/AltinelABFSZ99","WZDgK2THjbQJ")).
neg(eqo("conf/sigmod/AvnurHLORRRW98","7b-nJDMGtwUJ")).
neg(eqo("conf/sigmod/AvnurHLORRRW98","rNu93TfKkd4J")).
neg(eqo("conf/sigmod/Ballinger94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083803%26type%3Dpdf")).
neg(eqo("conf/sigmod/BaulierBGGHJKKMMNNRSSSWW99","LOKNVC3Rz1MJ")).
neg(eqo("conf/sigmod/BaumannDFRW98","OS4_l9VMXxQJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","_vewVM0SjwIJ")).
neg(eqo("conf/sigmod/BerchtoldK98","O8hTucqqWBMJ")).
neg(eqo("conf/sigmod/BerchtoldK98","rivzCRXhoAkJ")).
neg(eqo("conf/sigmod/BilirisFOP96","tS25MvqXwHEJ")).
neg(eqo("conf/sigmod/BlakeleyD00","ZSR-MThg9UEJ")).
neg(eqo("conf/sigmod/BlottRS96","3OxZS395vDcJ")).
neg(eqo("conf/sigmod/BrinMUT97","29xzHOD5g8cJ")).
neg(eqo("conf/sigmod/Brown99","tmZIHxrZrU4J")).
neg(eqo("conf/sigmod/Brown99","vYsliFiTu4AJ")).
neg(eqo("conf/sigmod/BrownCL96","FiPJDs_jm54J")).
neg(eqo("conf/sigmod/BrownCL96","MIFTqKFUH88J")).
neg(eqo("conf/sigmod/BumbulisB02","Ev27auQiecUJ")).
neg(eqo("conf/sigmod/BunemanM95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1041434%26type%3Dpdf")).
neg(eqo("conf/sigmod/CallanCD99","G5pMFbUSLEEJ")).
neg(eqo("conf/sigmod/Carey00","DDnZOOrD_jYJ")).
neg(eqo("conf/sigmod/CatarciS01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000004/art00031")).
neg(eqo("conf/sigmod/Chan98","oo2mr5fbMggJ")).
neg(eqo("conf/sigmod/ChangG99","Pf0k8vsuiBIJ")).
neg(eqo("conf/sigmod/ChangG99","vZcZ-UX6h7UJ")).
neg(eqo("conf/sigmod/Chaudhuri97","QCFUIVkspywJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","zlbJ-7JZdP0J")).
neg(eqo("conf/sigmod/ChaudhuriGGM03","GKUflKzgAVEJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","HuTZ23tc7Z8J")).
neg(eqo("conf/sigmod/ChaudhuriMN99","sAYCyUcugbYJ")).
neg(eqo("conf/sigmod/ChawatheRGW96","ilCT5UFnHxgJ")).
neg(eqo("conf/sigmod/ChenGM01","IuyDb53VoG0J")).
neg(eqo("conf/sigmod/ChooOLCGBPS96","WrrEnOJswS4J")).
neg(eqo("conf/sigmod/Cohen98a","E4S-NQtAWXwJ")).
neg(eqo("conf/sigmod/Cotton02","sPXEpxfQfs8J")).
neg(eqo("conf/sigmod/DasGR03","1R1GcHS7Me8J")).
neg(eqo("conf/sigmod/Dietterich94","rMV2yNFwvggJ")).
neg(eqo("conf/sigmod/DogacTPPLKTK02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776990%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Dyreson03","H9bMRYKnXMQJ")).
neg(eqo("conf/sigmod/FabretJLPRS01","n9_CfMTousYJ")).
neg(eqo("conf/sigmod/Faloutsos95","x0k9DRcKYjQJ")).
neg(eqo("conf/sigmod/Fegaras98","gqehj3-ukjIJ")).
neg(eqo("conf/sigmod/Fernandez94","8KJ9XFv1ESAJ")).
neg(eqo("conf/sigmod/FernandezFKLS97","F2hJ_IGiHj8J")).
neg(eqo("conf/sigmod/FernandezS96","66uAX5EPtKcJ")).
neg(eqo("conf/sigmod/Freeston95","Fr8CPbK-IFIJ")).
neg(eqo("conf/sigmod/FukudaMMT96","rUpu2pcFa8cJ")).
neg(eqo("conf/sigmod/FukudaMMT96","tjd9D2eFeZ4J")).
neg(eqo("conf/sigmod/FungSG02","smz8Khpcf98J")).
neg(eqo("conf/sigmod/Galhardas00","otGW0G5B6AYJ")).
neg(eqo("conf/sigmod/GangulyGMS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GeneserethKD97","s8ZGD0r4M0wJ")).
neg(eqo("conf/sigmod/GillmannWSWW00","tYXzABUZYxQJ")).
neg(eqo("conf/sigmod/GionisGK01","4QW8Wm_KUpcJ")).
neg(eqo("conf/sigmod/GionisGK01","HLu7MvWb5rMJ")).
neg(eqo("conf/sigmod/GoldsteinL01","Fh1QPZpWHUMJ")).
neg(eqo("conf/sigmod/GotoK03","2P9nOMK9_0MJ")).
neg(eqo("conf/sigmod/GotoK03","2Pc6rKYB8ykJ")).
neg(eqo("conf/sigmod/GravanoCGP97","1xxRTUP64bwJ")).
neg(eqo("conf/sigmod/GriffinH97","6oGIgK6aIi8J")).
neg(eqo("conf/sigmod/GriffinH97","fS7vZrd0gPcJ")).
neg(eqo("conf/sigmod/GriffinL95","v2jpkmgnJuoJ")).
neg(eqo("conf/sigmod/HaasH99","bsfsN1NtuOMJ")).
neg(eqo("conf/sigmod/Han96","t8W8vA4VvpAJ")).
neg(eqo("conf/sigmod/Han96","uwRewT_C-HkJ")).
neg(eqo("conf/sigmod/HanPY00","63XKDNdtzp8J")).
neg(eqo("conf/sigmod/HinneburgKW02","VWd7jhLXfV0J")).
neg(eqo("conf/sigmod/HuangSW94","bbNTKoyX4mYJ")).
neg(eqo("conf/sigmod/HwangLYMMGCSS94","nbU59lK7JJYJ")).
neg(eqo("conf/sigmod/JagatheesanR03","5s6fOcc1C60J")).
neg(eqo("conf/sigmod/JarkeQBLMS99","98sRAujVnC4J")).
neg(eqo("conf/sigmod/JoshiA01","wI75uFSs0bwJ")).
neg(eqo("conf/sigmod/JosifovskiSHL02","Hr5oECSj9U8J")).
neg(eqo("conf/sigmod/KalnisNOPT02","6LAgDHttAVMJ")).
neg(eqo("conf/sigmod/KalnisP01","-YhMJ43VntgJ")).
neg(eqo("conf/sigmod/KemperMPS94","ZYVYh-g07YQJ")).
neg(eqo("conf/sigmod/KiepuszewskiMO98","ajP7a2ZOOa8J")).
neg(eqo("conf/sigmod/KimCK01","X8aW3tR7uPYJ")).
neg(eqo("conf/sigmod/KimCK01","egc4wGonDjwJ")).
neg(eqo("conf/sigmod/Kohler99","jpNXw9L7pxgJ")).
neg(eqo("conf/sigmod/KornMZ03","DfOLEzMoEaEJ")).
neg(eqo("conf/sigmod/KotidisR98","mKYn4hiPJkIJ")).
neg(eqo("conf/sigmod/KoudasS03","UJOjz_zCPSEJ")).
neg(eqo("conf/sigmod/Kramer97","0mMOYPIw24EJ")).
neg(eqo("conf/sigmod/Kramer97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D273247%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KriegelMPS01","kdU4iiwLli8J")).
neg(eqo("conf/sigmod/KriegelMPS01","tsPOU-H3A94J")).
neg(eqo("conf/sigmod/KriegelMPS01","xV4VWiwR28MJ")).
neg(eqo("conf/sigmod/LabioWGG00","57T2gTRKZEEJ")).
neg(eqo("conf/sigmod/LangS01","FFQc9XpGFRsJ")).
neg(eqo("conf/sigmod/Larson01","IiCLH_wsBkcJ")).
neg(eqo("conf/sigmod/Levine95","ARLe7W8EvDoJ")).
neg(eqo("conf/sigmod/Levine95","ami_BUuBa4UJ")).
neg(eqo("conf/sigmod/LiBKN03","micx2kyGfKIJ")).
neg(eqo("conf/sigmod/LiefkeS00","c54ZClhl5EMJ")).
neg(eqo("conf/sigmod/LiuPBHPT00","2aeb_pBP7lcJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97","_WdzGpdohwoJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97","eq249ewqsHMJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97","iZAxWAFtyNoJ")).
neg(eqo("conf/sigmod/Maguire01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375742%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Martin94","7c0UgWqwRQoJ")).
neg(eqo("conf/sigmod/MelnikRB03","6NbNX8nSta0J")).
neg(eqo("conf/sigmod/Meseck01","uGXRy7xmoIYJ")).
neg(eqo("conf/sigmod/Mohan01","Hc029KXUhX8J")).
neg(eqo("conf/sigmod/Mohan99","IGS3TtqfKUgJ")).
neg(eqo("conf/sigmod/MoonSL00","ImxhV9-VU1AJ")).
neg(eqo("conf/sigmod/MotakisZ97","abi92bI5Il0J")).
neg(eqo("conf/sigmod/Mylopoulos98","GHz2PmQwW2UJ")).
neg(eqo("conf/sigmod/Mylopoulos98","jsJJXMHfgxAJ")).
neg(eqo("conf/sigmod/NaumanS98","L3OeJHUJECwJ")).
neg(eqo("conf/sigmod/NestorovAM98","0mk_QzaJKHEJ")).
neg(eqo("conf/sigmod/NgLK98","lWY2GRwhJxYJ")).
neg(eqo("conf/sigmod/ONeilQ97","359PjJkfNhQJ")).
neg(eqo("conf/sigmod/OlstonWL01","QVDW9nJubnAJ")).
neg(eqo("conf/sigmod/OrdonezC00","3HttWcaA4_gJ")).
neg(eqo("conf/sigmod/OrdonezC00","SADcQZhMqgEJ")).
neg(eqo("conf/sigmod/PadmanabhanBMCH03","d8gRjk3iEi0J")).
neg(eqo("conf/sigmod/PalmerF00","uH7cCwOk7xYJ")).
neg(eqo("conf/sigmod/PapakonstantinouPV02","GHjgDrEbqM4J")).
neg(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
neg(eqo("conf/sigmod/PatelYKTNBHRLEKGDN97","EVifEeUZwrQJ")).
neg(eqo("conf/sigmod/PeiMHZ00","UyhrqiH_-MoJ")).
neg(eqo("conf/sigmod/PengC03","ihljCMaS2UsJ")).
neg(eqo("conf/sigmod/Perna95","4citUVaHukMJ")).
neg(eqo("conf/sigmod/Perna95","url:http://portal.acm.org/citation.cfm%3Fid%3D171926.172011")).
neg(eqo("conf/sigmod/Rajaraman99","0B-keNfFqUgJ")).
neg(eqo("conf/sigmod/Ramakrishnan00","6VAQeD6muakJ")).
neg(eqo("conf/sigmod/Ramakrishnan00","hnH7lHHAW44J")).
neg(eqo("conf/sigmod/RamakrishnanD98","url:http://www.springerlink.com/index/85D6LYCWB48DWBKW.pdf")).
neg(eqo("conf/sigmod/Ramanan02","VYYKHi96iQkJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","AygQeIp71_YJ")).
neg(eqo("conf/sigmod/RaoR00","1tKWKmyczaYJ")).
neg(eqo("conf/sigmod/ReveszCKLLW00","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294187CI")).
neg(eqo("conf/sigmod/RiedewaldAA02","C60KJG_xVm0J")).
neg(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
neg(eqo("conf/sigmod/RodriguezR00","gi7N9eQiTx4J")).
neg(eqo("conf/sigmod/Rosenthal01","ZMMeRrWUlOoJ")).
neg(eqo("conf/sigmod/RossSS96","FfYkDJrlW4wJ")).
neg(eqo("conf/sigmod/Sahuguet01","GHjgDrEbqM4J")).
neg(eqo("conf/sigmod/SaltenisJLL00","OFXL5KsJiWcJ")).
neg(eqo("conf/sigmod/Sarawagi00","vkUvhZOw-1YJ")).
neg(eqo("conf/sigmod/SeshadriLR94","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D914832")).
neg(eqo("conf/sigmod/ShanmugasundaramNSR99","w_oXiQ-bR70J")).
neg(eqo("conf/sigmod/ShashaB02","kUIPiVP04s8J")).
neg(eqo("conf/sigmod/ShouCTRH01","wfjeWtEY2NcJ")).
neg(eqo("conf/sigmod/SionAP03","F7AdjoH_uTcJ")).
neg(eqo("conf/sigmod/SionAP03","Z5nBebaPAA8J")).
neg(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
neg(eqo("conf/sigmod/StonebrakerH01","VIjfH9f94xkJ")).
neg(eqo("conf/sigmod/SunAA03","wR6CGftUyH0J")).
neg(eqo("conf/sigmod/SwamiS94","lrGge6mTVckJ")).
neg(eqo("conf/sigmod/Tajima96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058156%26type%3Dpdf")).
neg(eqo("conf/sigmod/Team99","bcR9TErOrKQJ")).
neg(eqo("conf/sigmod/TomasicGS94","lEQ4uPFcizcJ")).
neg(eqo("conf/sigmod/VanceM96","CMMaMlYwgPkJ")).
neg(eqo("conf/sigmod/Vaskevitch94","cr7xWKidCnYJ")).
neg(eqo("conf/sigmod/WaasG00","SN85bO7F7xMJ")).
neg(eqo("conf/sigmod/WaasG00","TsShfxPwF6YJ")).
neg(eqo("conf/sigmod/WangCMSSZ94","hBak02oe1GMJ")).
neg(eqo("conf/sigmod/WangSCRZP97","TMC5WeUFbbAJ")).
neg(eqo("conf/sigmod/WangSCRZP97","f2Lea-RN8dsJ")).
neg(eqo("conf/sigmod/Weininger02","e5Gm5upjQnkJ")).
neg(eqo("conf/sigmod/WhitneyS01","bZj9gl0_YUIJ")).
neg(eqo("conf/sigmod/WolfsonSXZC99","4dbCEDwsluQJ")).
neg(eqo("conf/sigmod/WolfsonSXZC99","NkwCBYfWKicJ")).
neg(eqo("conf/sigmod/Wu99","4IVlvcg-EycJ")).
neg(eqo("conf/sigmod/Wu99","8AHaTrvwsJoJ")).
neg(eqo("conf/sigmod/YangWYH02","sG7PCEiN2xAJ")).
neg(eqo("conf/sigmod/YangYW00","TW9vLlADliUJ")).
neg(eqo("conf/sigmod/ZhouLP99","rMV2yNFwvggJ")).
neg(eqo("conf/vldb/AbiteboulACEMM99","pB5rahMH904J")).
neg(eqo("conf/vldb/AbiteboulACEMM99","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","kuueK-yBQqMJ")).
neg(eqo("conf/vldb/AboulnagaAN01","9DodgncDmegJ")).
neg(eqo("conf/vldb/AboulnagaAN01","P7GUGC5bz7wJ")).
neg(eqo("conf/vldb/AboulnagaAN01","p-Xkl1fZarEJ")).
neg(eqo("conf/vldb/AcharyaGP99","u5vlxTi4BmAJ")).
neg(eqo("conf/vldb/AdityaBCHNS02","dMRIRjR_KAAJ")).
neg(eqo("conf/vldb/AggarwalY02","PPYUfW_gKOAJ")).
neg(eqo("conf/vldb/AgrawalLSS95","Y799jSppkKEJ")).
neg(eqo("conf/vldb/AgrawalS94","9ErVOrAc4xgJ")).
neg(eqo("conf/vldb/AgrawalS94","OUdGxoZdSxAJ")).
neg(eqo("conf/vldb/AgrawalSX01","6YRecuEYQX8J")).
neg(eqo("conf/vldb/AgrawalSX01","I8gEFwnlUp0J")).
neg(eqo("conf/vldb/AgrawalSX01","Yt-cq_4cfE8J")).
neg(eqo("conf/vldb/AgrawalSX01","wu8UrFu8Tu8J")).
neg(eqo("conf/vldb/AmielBDS94","bBvZMwOE1aYJ")).
neg(eqo("conf/vldb/AnSVKIG01","TyF71uAlnLsJ")).
neg(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
neg(eqo("conf/vldb/BaralisW94","q-td2YANr18J")).
neg(eqo("conf/vldb/BassiliadesV95","0FLbdrpouaQJ")).
neg(eqo("conf/vldb/BasuFP00","9PJWqPPVlQwJ")).
neg(eqo("conf/vldb/Bayer95","tt29bvgnB9MJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","4N472VSotmMJ")).
neg(eqo("conf/vldb/BerchtoldKK96","G__T5t9i4ZwJ")).
neg(eqo("conf/vldb/BernsteinD94","qUfWV4VVxegJ")).
neg(eqo("conf/vldb/BernsteinHSSZ97","a1CLM5GoVtYJ")).
neg(eqo("conf/vldb/BernsteinPS99","JcHiZlbsts0J")).
neg(eqo("conf/vldb/BestavrosB95","E9AsPVyCDlMJ")).
neg(eqo("conf/vldb/Bhashyam96","jtWvNxTZ794J")).
neg(eqo("conf/vldb/BlottK02","4OUQOD2i52sJ")).
neg(eqo("conf/vldb/BohannonGKNS02","J5HQj5rH5icJ")).
neg(eqo("conf/vldb/BouguettayaEMO01","gp59PReoSu4J")).
neg(eqo("conf/vldb/Brin95","ou7jNSncdB0J")).
neg(eqo("conf/vldb/Brin95","sMTC_d3fbYcJ")).
neg(eqo("conf/vldb/Campbell99","m1eeQnYWL0oJ")).
neg(eqo("conf/vldb/Carey00","eDPpmxjoypoJ")).
neg(eqo("conf/vldb/CasatiS00","DsE_JLwF9ZYJ")).
neg(eqo("conf/vldb/CatozziR95","anRMQBzK70sJ")).
neg(eqo("conf/vldb/ChanGR02","vJmqNzV42j8J")).
neg(eqo("conf/vldb/ChaudhuriN97","SA9NEkfzS0EJ")).
neg(eqo("conf/vldb/ChaudhuriS96","QCFUIVkspywJ")).
neg(eqo("conf/vldb/ChaudhuriS96","ThEw8obz2UsJ")).
neg(eqo("conf/vldb/Chawathe99","WGSzAXFNWr8J")).
neg(eqo("conf/vldb/ChawatheCY94","oHUiSrycKdgJ")).
neg(eqo("conf/vldb/ChenL03","7eu0IZf_OpwJ")).
neg(eqo("conf/vldb/ChenL03","JnCZDIqNNTUJ")).
neg(eqo("conf/vldb/ChengGKLLQS99","zYfyg0fCzEsJ")).
neg(eqo("conf/vldb/CherniackZ98","01Qk-8Zek58J")).
neg(eqo("conf/vldb/CherniackZ98","egCgEjikCgAJ")).
neg(eqo("conf/vldb/ChirkovaHS01","gUJrOpj89tQJ")).
neg(eqo("conf/vldb/ConradGJM02","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/DaynesC02","SU2XS1MVb40J")).
neg(eqo("conf/vldb/DeutschPT99","0OwKmPjQpd0J")).
neg(eqo("conf/vldb/DiaoLCT00","hdDsjafWJIwJ")).
neg(eqo("conf/vldb/DillKMRST01","oQ5vKgMq9WAJ")).
neg(eqo("conf/vldb/DingGS00","GM-rQKHqbHwJ")).
neg(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
neg(eqo("conf/vldb/DongHLPW01","EWdjCIv1enwJ")).
neg(eqo("conf/vldb/Draluk01","M-b0kaZFbiQJ")).
neg(eqo("conf/vldb/Dyreson96","PhERWOcOkOgJ")).
neg(eqo("conf/vldb/EicklerGK95","63QhLG57QssJ")).
neg(eqo("conf/vldb/EsterKSWX98","ebJMvVO8zp0J")).
neg(eqo("conf/vldb/EvangelidisLS95","EbGZKQPyH_4J")).
neg(eqo("conf/vldb/FaloutsosG96","qsWDIfzBxiQJ")).
neg(eqo("conf/vldb/FernandezSCMS03","GwvN1w9_ZZoJ")).
neg(eqo("conf/vldb/GallersdorferN95","CN7qRr53peIJ")).
neg(eqo("conf/vldb/GallersdorferN95","PUaojR5kDikJ")).
neg(eqo("conf/vldb/GantiLR00","bU7wSVKvhscJ")).
neg(eqo("conf/vldb/GardarinST96","eZwzDZ7QhzoJ")).
neg(eqo("conf/vldb/GarofalakisG01","jC-TppzLPuEJ")).
neg(eqo("conf/vldb/GarofalakisI97","9aNUdPCEMmwJ")).
neg(eqo("conf/vldb/GeorgeH98","a6y0DCQ4H3EJ")).
neg(eqo("conf/vldb/GeorgeH98","zbzO-4fuIwUJ")).
neg(eqo("conf/vldb/GinisHKMT97","DBbZw9EPv4QJ")).
neg(eqo("conf/vldb/GottlobKP02","VYYKHi96iQkJ")).
neg(eqo("conf/vldb/Graefe99","3m-KKBVF8KkJ")).
neg(eqo("conf/vldb/Graefe99","GKmk6o_x9pcJ")).
neg(eqo("conf/vldb/Graefe99","kFYP08zmbAgJ")).
neg(eqo("conf/vldb/GraefeBC98","HsAQIEugJ8YJ")).
neg(eqo("conf/vldb/Greco98","oq5PTrqeB9cJ")).
neg(eqo("conf/vldb/Guting94","z8eqPKzmjM4J")).
neg(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
neg(eqo("conf/vldb/Hammond96","X1UqyvzFlB8J")).
neg(eqo("conf/vldb/HanF95","2kDtSxYI5DgJ")).
neg(eqo("conf/vldb/HasanM94","8cd64f0t0-EJ")).
neg(eqo("conf/vldb/HasanM94","kZaX18AOqfQJ")).
neg(eqo("conf/vldb/HasanM95","8cd64f0t0-EJ")).
neg(eqo("conf/vldb/HelmerM97","x3wm5TY4qtUJ")).
neg(eqo("conf/vldb/HelmerNM03","vInYFLVq0uIJ")).
neg(eqo("conf/vldb/HerlekarDRGS02","S6PWjHRFORYJ")).
neg(eqo("conf/vldb/HvasshovdBT00","2njaHdhfzAoJ")).
neg(eqo("conf/vldb/IshikawaSF98","2Lwh21KUjw0J")).
neg(eqo("conf/vldb/IwerksSS03","RXLOgsTshF4J")).
neg(eqo("conf/vldb/JaedickeM99","zh6yaOX2xiQJ")).
neg(eqo("conf/vldb/Johnson99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0411949CI")).
neg(eqo("conf/vldb/JohnsonA00","EPVkQkFM2osJ")).
neg(eqo("conf/vldb/JohnsonA00","dig58dUY97UJ")).
neg(eqo("conf/vldb/JonscherD94","1R21hO7j9sQJ")).
neg(eqo("conf/vldb/KamelF94","0DbOS1AuDO0J")).
neg(eqo("conf/vldb/KarayannidisTSPMRFEB02","X1MBCvIuINwJ")).
neg(eqo("conf/vldb/Keogh02","MYeV_2ohJIcJ")).
neg(eqo("conf/vldb/KiesslingK02","Des-PSLVQi4J")).
neg(eqo("conf/vldb/KietzRS97","4yED9m0LinwJ")).
neg(eqo("conf/vldb/King02","lwsdRCy-ek0J")).
neg(eqo("conf/vldb/King02","ws3cSkrAzqYJ")).
neg(eqo("conf/vldb/KnorrN98","oedVPUUsKEQJ")).
neg(eqo("conf/vldb/KnorrN99","7lkCBMe603kJ")).
neg(eqo("conf/vldb/KnorrN99","gQVLY8V1hekJ")).
neg(eqo("conf/vldb/KochBG03","ymWgTrY4RlAJ")).
neg(eqo("conf/vldb/KornMZ03","fIcZeXoZ4bIJ")).
neg(eqo("conf/vldb/Korth95","5gtQngFnPJUJ")).
neg(eqo("conf/vldb/Korth95","MqxNUpod-BYJ")).
neg(eqo("conf/vldb/KoschBBHHLRT01","5syUm1lil2cJ")).
neg(eqo("conf/vldb/KounevB02","RmyORCW6qn8J")).
neg(eqo("conf/vldb/KumarKA97","JuKBWdantQEJ")).
neg(eqo("conf/vldb/KumarRRT99","0XWjlzHVMdMJ")).
neg(eqo("conf/vldb/LabrinidisR01","PFEvlg2DiMkJ")).
neg(eqo("conf/vldb/LabrinidisR01","rKbwxobcJZYJ")).
neg(eqo("conf/vldb/LakshmananNWZJ02","rZcRXL6ueUMJ")).
neg(eqo("conf/vldb/LeeLWS97","56hiJThi2TYJ")).
neg(eqo("conf/vldb/LeeWMS02","hulo0jCbUIMJ")).
neg(eqo("conf/vldb/LitwinNS94","71HSaDWFXQcJ")).
neg(eqo("conf/vldb/LohmanL02","dVn0Led5JLAJ")).
neg(eqo("conf/vldb/LuTD95","U9EN84liiRoJ")).
neg(eqo("conf/vldb/Malaika96","55zEnoFzRtcJ")).
neg(eqo("conf/vldb/ManegoldBK00","JgdpgBpMDr4J")).
neg(eqo("conf/vldb/ManegoldBK00","UbvFPd7olt0J")).
neg(eqo("conf/vldb/ManolopoulosT01","DqZEgt_ABcYJ")).
neg(eqo("conf/vldb/MargaritisFT01","Ph7ZpmdNOPEJ")).
neg(eqo("conf/vldb/Mattos96","978pJCGhaGoJ")).
neg(eqo("conf/vldb/MeoPC96","4j5ryW5xA7YJ")).
neg(eqo("conf/vldb/MiloZ98","N-wq3niLDHYJ")).
neg(eqo("conf/vldb/MiloZ98","qXtUtp078_gJ")).
neg(eqo("conf/vldb/Mohan01","ZEh9UFMj3-EJ")).
neg(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
neg(eqo("conf/vldb/NetzCBF00","qqwCU74AGhIJ")).
neg(eqo("conf/vldb/NgH94","JhWxdEDCPdUJ")).
neg(eqo("conf/vldb/NicklasGS03","zApMW7wX5-AJ")).
neg(eqo("conf/vldb/Novaretti01","UGA_yZn0Q_YJ")).
neg(eqo("conf/vldb/Padmanabhan96","3V6BTODTE_QJ")).
neg(eqo("conf/vldb/PalpanasSCP02","ak63oe42C-oJ")).
neg(eqo("conf/vldb/PalpanasSCP02","k3x5pXEQcmQJ")).
neg(eqo("conf/vldb/PalpanasSCP02","kNKWc8ETyvMJ")).
neg(eqo("conf/vldb/PapadiasTS03","Fir6kPDNKpQJ")).
neg(eqo("conf/vldb/PapakonstantinouAG96","gkbvvgj8kdUJ")).
neg(eqo("conf/vldb/PolyzotisG02","DqKXdCehnGcJ")).
neg(eqo("conf/vldb/Raghavan96","A8rGBQif7MIJ")).
neg(eqo("conf/vldb/RahmM95","fzL4ixVpc6IJ")).
neg(eqo("conf/vldb/RamanRH99","v-kvo2hnsgkJ")).
neg(eqo("conf/vldb/RaoR99","2j-X_DAqspUJ")).
neg(eqo("conf/vldb/RastogiS98","7Eag6wnw6FkJ")).
neg(eqo("conf/vldb/ReuterCGSW95","ouP9YWyn9tMJ")).
neg(eqo("conf/vldb/RosenthalS94","ii-QQ8y3FiUJ")).
neg(eqo("conf/vldb/SakuraiYUK00","DKxOG8pvJOQJ")).
neg(eqo("conf/vldb/Sarawagi00","7GpYSr7yaWAJ")).
neg(eqo("conf/vldb/Sarawagi00","gz92a8BdTLUJ")).
neg(eqo("conf/vldb/Sarawagi95","0AwSc88rnUIJ")).
neg(eqo("conf/vldb/SarawagiS96","6rD0bKSrRAEJ")).
neg(eqo("conf/vldb/SarawagiS96","EkmUvRCP29QJ")).
neg(eqo("conf/vldb/SayalCDS02","0acvmJtaI8QJ")).
neg(eqo("conf/vldb/ScheuermannSV96","EnrllAo58CMJ")).
neg(eqo("conf/vldb/SeidlK97","VIe8nPSWDugJ")).
neg(eqo("conf/vldb/SellisRF97","FUXcNB3HHi4J")).
neg(eqo("conf/vldb/SeshadriLR97","lLl_ZSV1alYJ")).
neg(eqo("conf/vldb/ShaferA97","SoPEoRftQBcJ")).
neg(eqo("conf/vldb/ShahabiFKF00","GVogVdXDGmcJ")).
neg(eqo("conf/vldb/ShatdalKN94","27-P8X0mjfcJ")).
neg(eqo("conf/vldb/ShatdalKN94","KAyi60nog2AJ")).
neg(eqo("conf/vldb/SheikholeslamiCZ98","dm3xutmyi_0J")).
neg(eqo("conf/vldb/SheikholeslamiCZ98","url:http://portal.acm.org/citation.cfm%3Fid%3D288549")).
neg(eqo("conf/vldb/Sheth96","JrkRUbNsLwEJ")).
neg(eqo("conf/vldb/SkubiszewskiV97","tfGCi5bs7FkJ")).
neg(eqo("conf/vldb/Spaccapietra94","RmyORCW6qn8J")).
neg(eqo("conf/vldb/SrikantA95","RE_sI8I74igJ")).
neg(eqo("conf/vldb/SripadaW94","xWgxEU5Vop0J")).
neg(eqo("conf/vldb/StathatosRB97","n8LgSbKmF1sJ")).
neg(eqo("conf/vldb/Sterling98","kZaX18AOqfQJ")).
neg(eqo("conf/vldb/StohrMR00","_BvJZACWQnIJ")).
neg(eqo("conf/vldb/StohrR01","url:http://doi.wiley.com/10.1002/he.32.abs")).
neg(eqo("conf/vldb/Suciu96","GwvN1w9_ZZoJ")).
neg(eqo("conf/vldb/Suciu96a","8bcTG9YsbskJ")).
neg(eqo("conf/vldb/SundaraHCAS01","lPWuMxTX9yYJ")).
neg(eqo("conf/vldb/TanSHCR01","ntrSSBumclMJ")).
neg(eqo("conf/vldb/Tsur00","4OQkamP3puYJ")).
neg(eqo("conf/vldb/VermeerA96","F1bohDXUiJ4J")).
neg(eqo("conf/vldb/VermeerA96","z87gIqJ_wg0J")).
neg(eqo("conf/vldb/VorugantiOU99","6LAgDHttAVMJ")).
neg(eqo("conf/vldb/WangYM97","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/WuYCT95","k8EsgEuKhQ0J")).
neg(eqo("conf/vldb/X00","nJDl_1OtHqwJ")).
neg(eqo("conf/vldb/XinHLW03","pufIy0P0-iMJ")).
neg(eqo("conf/vldb/YuAA03","4bvjebYsdRkJ")).
neg(eqo("conf/vldb/ZellerK02","ap_csO-7bFMJ")).
neg(eqo("conf/vldb/ZhouR03","Za4prFsmCsMJ")).
neg(eqo("conf/vldb/ZhuS02","hIGjgc6mx0cJ")).
neg(eqo("conf/vldb/ZouS98","DYFIQvOg7rgJ")).
neg(eqo("conf/vldb/ZurekS99","X8NQL_-NIMgJ")).
neg(eqo("journals/sigmod/AbelTK97","eznFJ2e_pQQJ")).
neg(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/citation.cfm%3Fid%3D945721.945727%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02c","2r6t9GEZb28J")).
neg(eqo("journals/sigmod/Aberer02c","g2ZQ4_Qy228J")).
neg(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959078%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03a","V9zIFZ4CbDIJ")).
neg(eqo("journals/sigmod/AbiteboulH95","kUA9e6YP8igJ")).
neg(eqo("journals/sigmod/Ahlberg96","cExZWIT9LZcJ")).
neg(eqo("journals/sigmod/AndersonS94","aDk2IS_xwToJ")).
neg(eqo("journals/sigmod/AtkinsonDJPS96","OgBSNzmsvHUJ")).
neg(eqo("journals/sigmod/AtzeniMM97","Hdq-Mlh3fcMJ")).
neg(eqo("journals/sigmod/BallMRZ02","tYXzABUZYxQJ")).
neg(eqo("journals/sigmod/Bernstein98","gKdxwCWE4ssJ")).
neg(eqo("journals/sigmod/BertinoEH03","GzS33AXiPScJ")).
neg(eqo("journals/sigmod/BhargavaAP95","tsQbSCfQTooJ")).
neg(eqo("journals/sigmod/BiancheriPP01","93BBbthtYOUJ")).
neg(eqo("journals/sigmod/CabreraLM01","0inuMFZSQ50J")).
neg(eqo("journals/sigmod/CabreraLM01","iZakw-9ZuvgJ")).
neg(eqo("journals/sigmod/CalvaneseGLV03","hRLZLQmC-cAJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","ZPoFYhxgaTMJ")).
neg(eqo("journals/sigmod/Chaudhri95","oacFELqmw0cJ")).
neg(eqo("journals/sigmod/Chen94","vJTSU6Y2XsgJ")).
neg(eqo("journals/sigmod/CheungF98","OuMumdGAaq8J")).
neg(eqo("journals/sigmod/ChrysanthisSZ03","2PwEpiJIqgIJ")).
neg(eqo("journals/sigmod/ConradHHKRSS99","G3dX_RTA26MJ")).
neg(eqo("journals/sigmod/ConradHHKRSS99","zJCsqgMH5bUJ")).
neg(eqo("journals/sigmod/CuiJO02","2APmJ-GQBbwJ")).
neg(eqo("journals/sigmod/Danish98","lQFeNd7gt-UJ")).
neg(eqo("journals/sigmod/Datta94","rLmyZVaI5twJ")).
neg(eqo("journals/sigmod/Dogac02","CqN0lBzsmEoJ")).
neg(eqo("journals/sigmod/Dogac02","O0IEHbFkD3oJ")).
neg(eqo("journals/sigmod/Dogac02","qFFoieo76QIJ")).
neg(eqo("journals/sigmod/DogacAOD95","uPBlQ76s_g4J")).
neg(eqo("journals/sigmod/DogacDATKCD98","ChD3-mp23f8J")).
neg(eqo("journals/sigmod/EisenbergM98a","Ciq01lHglkAJ")).
neg(eqo("journals/sigmod/EisenbergM98a","GKUflKzgAVEJ")).
neg(eqo("journals/sigmod/EnglertGH95","WYE9fKutj70J")).
neg(eqo("journals/sigmod/Etzion99","BoSfRzB01ZQJ")).
neg(eqo("journals/sigmod/FlorescuLM98","O8eIfc2eSjcJ")).
neg(eqo("journals/sigmod/ForteHWDCVHFS99","QTzuiNlMnR4J")).
neg(eqo("journals/sigmod/Franklin97","p0QHT_9_NSkJ")).
neg(eqo("journals/sigmod/Franklin98","5Cj9Wx8llkwJ")).
neg(eqo("journals/sigmod/Franklin98","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin99a","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin99b","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/FreemanG96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141379%26type%3Dpdf")).
neg(eqo("journals/sigmod/Geller02","KNYDz76C_HsJ")).
neg(eqo("journals/sigmod/GeppertD94","3ytw-QvDC4IJ")).
neg(eqo("journals/sigmod/GeppertD94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/GerlaX03","CqbNc79TtBsJ")).
neg(eqo("journals/sigmod/GlavitschSW94","T3Zm8WKD_FYJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","xAK3v_PeQBoJ")).
neg(eqo("journals/sigmod/Hammer02","GU1B3LSbkTIJ")).
neg(eqo("journals/sigmod/Hammer03","FtXJAWDJgS8J")).
neg(eqo("journals/sigmod/Hampapur99","taphZimnV-gJ")).
neg(eqo("journals/sigmod/Han98","DlQd7WIkVF0J")).
neg(eqo("journals/sigmod/Han98","url:http://doi.wiley.com/10.1002/he.72")).
neg(eqo("journals/sigmod/HasanFV96","ybOBcBXRBqUJ")).
neg(eqo("journals/sigmod/Hoffner03","in96yyjJzlwJ")).
neg(eqo("journals/sigmod/Ioannidis96","ARcoG5X61VIJ")).
neg(eqo("journals/sigmod/JacobS99","7fhXnQVjxXgJ")).
neg(eqo("journals/sigmod/Jarke95","_nIg_hi8PAAJ")).
neg(eqo("journals/sigmod/JukicNV03","eR43Urfx-hcJ")).
neg(eqo("journals/sigmod/Kemper02","O5S8QV9TOXAJ")).
neg(eqo("journals/sigmod/Kim99","5lfXNkRahEgJ")).
neg(eqo("journals/sigmod/KimballS95","url:http://www.springerlink.com/index/X256555608656055.pdf")).
neg(eqo("journals/sigmod/KlasS94","_Hv8j-kS6QgJ")).
neg(eqo("journals/sigmod/Kosch02","-OS_AX3M8oAJ")).
neg(eqo("journals/sigmod/KramerNKRLKLZ97","1sBvG9OXpMAJ")).
neg(eqo("journals/sigmod/Kumar03","4zZ7Lxt4PPIJ")).
neg(eqo("journals/sigmod/Kumar03","rVppv4BaXa8J")).
neg(eqo("journals/sigmod/Labrinidis01","K54C3yEb3mkJ")).
neg(eqo("journals/sigmod/Labrinidis01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000004/art00038")).
neg(eqo("journals/sigmod/LinP96","7AbvgtyX8Y0J")).
neg(eqo("journals/sigmod/Liu02c","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/Liu02c","eKF1zVNKP0gJ")).
neg(eqo("journals/sigmod/Liu02c","zSO1Y5W7WkwJ")).
neg(eqo("journals/sigmod/Liu03","dO8czlfdENQJ")).
neg(eqo("journals/sigmod/Liu03","xeceK06Z5DIJ")).
neg(eqo("journals/sigmod/Liu03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D957098%26type%3Dpdf%26dl%3DACM%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Liu03c","SBnd4KSIDQ4J")).
neg(eqo("journals/sigmod/Liu03c","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/MeltonMJKSZ01","oRjQM7ybEdkJ")).
neg(eqo("journals/sigmod/MeltonMJKSZ01","zMK02pxd4OEJ")).
neg(eqo("journals/sigmod/NgH95","OoiYRo8bGpUJ")).
neg(eqo("journals/sigmod/OoiST03","BZfdROjhbhwJ")).
neg(eqo("journals/sigmod/OrlandicLS02","nCRYsSuGrV0J")).
neg(eqo("journals/sigmod/Ouksel03","_p_a1FowsR8J")).
neg(eqo("journals/sigmod/Ozsu02a","0acvmJtaI8QJ")).
neg(eqo("journals/sigmod/PhatakSSS96","PVm9r7wHzDAJ")).
neg(eqo("journals/sigmod/PhatakSSS96","url:http://portal.acm.org/citation.cfm%3Fid%3D333607.333616%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PitouraB95","zd_8s13rNRoJ")).
neg(eqo("journals/sigmod/Qian94","_RpELIR-GU8J")).
neg(eqo("journals/sigmod/Qian94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96b","Zy3vRcypVx4J")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RafanelliBT96","7hQge_9oGMMJ")).
neg(eqo("journals/sigmod/RamDD99","56U2j96vsRsJ")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","J7mY8RlpTKMJ")).
neg(eqo("journals/sigmod/RashidS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974142%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Rosenthal98","YiZVv5kVDb4J")).
neg(eqo("journals/sigmod/RosenthalS99","2cbB8em2uAIJ")).
neg(eqo("journals/sigmod/RossCGJBV99","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/RossGR03","TaBnIzl130QJ")).
neg(eqo("journals/sigmod/RossIJP00","8qafMLFnNR0J")).
neg(eqo("journals/sigmod/RossIJP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SayginVC01","Tp9iVMsAzocJ")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390002%26type%3Dpdf")).
neg(eqo("journals/sigmod/Segev94a","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Seligman97","xSkLdLrsKU0J")).
neg(eqo("journals/sigmod/SellisV95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219766%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Seshadri98","QTl0cVx5cJUJ")).
neg(eqo("journals/sigmod/ShethMKA01","3PnawciG4BAJ")).
neg(eqo("journals/sigmod/SilberschatzSU96","4IaWCBK6dMQJ")).
neg(eqo("journals/sigmod/Snodgrass01a","PmIVKWJ5_V4J")).
neg(eqo("journals/sigmod/Snodgrass02a","V1QUdDtkH5AJ")).
neg(eqo("journals/sigmod/Snodgrass02a","eGARASwVBrUJ")).
neg(eqo("journals/sigmod/Snodgrass97","5rPFkhuQNOkJ")).
neg(eqo("journals/sigmod/Snodgrass99b","EEXwq2Gx3goJ")).
neg(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","9PhYz-N58A8J")).
neg(eqo("journals/sigmod/SouzaS99","bDiNQAdf8nEJ")).
neg(eqo("journals/sigmod/Stirling03","rk6G2m3bSQgJ")).
neg(eqo("journals/sigmod/Suciu01","8bcTG9YsbskJ")).
neg(eqo("journals/sigmod/TanakaV01","h43touEiLyAJ")).
neg(eqo("journals/sigmod/TanakaV01","nmEhI0tiWGAJ")).
neg(eqo("journals/sigmod/TsotrasJS98","9p26ehRk5mAJ")).
neg(eqo("journals/sigmod/Ulusoy95","BVye0luu-zkJ")).
neg(eqo("journals/sigmod/UlusoyB96","GYR0v7CFkP0J")).
neg(eqo("journals/sigmod/Wade96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130297%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom95","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Widom95a","dO8czlfdENQJ")).
neg(eqo("journals/sigmod/Winslett02b","UVsqO1tB5BkJ")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/citation.cfm%3Fid%3D1083784.1083802")).
neg(eqo("journals/sigmod/Winslett02c","B-u4advaVBkJ")).
neg(eqo("journals/sigmod/Winslett03","CU6yaSQ6Vr8J")).
neg(eqo("journals/sigmod/Winslett03","hQt4gv-PZfMJ")).
neg(eqo("journals/sigmod/Winslett03b","aY6k7-pTueUJ")).
neg(eqo("journals/sigmod/Winslett94","8lafnpE84ocJ")).
neg(eqo("journals/sigmod/WolfsonSDNR95","1TlF_qJDshoJ")).
neg(eqo("journals/sigmod/Wong95","2aSkUIY38VMJ")).
neg(eqo("journals/sigmod/X94b","PaVA9OlhvrkJ")).
neg(eqo("journals/tods/BrunoCG02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/ChaudhuriS99","QCFUIVkspywJ")).
neg(eqo("journals/tods/Chen95a","cyCDESl6W3kJ")).
neg(eqo("journals/tods/CiacciaP02","t_XrLlqtRckJ")).
neg(eqo("journals/tods/DattaVCK99","qDx2SICqs0gJ")).
neg(eqo("journals/tods/DeyS96","gkUt2UgB_pUJ")).
neg(eqo("journals/tods/DiaoAFZF03","6UycFCZooDoJ")).
neg(eqo("journals/tods/FranklinCL97","vqboZ3T4n4AJ")).
neg(eqo("journals/tods/GravanoGT99","81oh7EDAYeoJ")).
neg(eqo("journals/tods/GuoSW96","m55V1zAE12cJ")).
neg(eqo("journals/tods/HjaltasonS03","9Wan9sPNUAYJ")).
neg(eqo("journals/tods/IoannidisR95","dZqd3KKXBiQJ")).
neg(eqo("journals/tods/KonopnickiS98","BKUtItHoTX8J")).
neg(eqo("journals/tods/KossmannFDA00","PJIhA9hs2tsJ")).
neg(eqo("journals/tods/Kuo96","gbjXwFztQTsJ")).
neg(eqo("journals/tods/LitwinN96","yLNTNdNR65cJ")).
neg(eqo("journals/tods/LiuHD98","S4A1NDJkmCcJ")).
neg(eqo("journals/tods/SistlaWYS98","3mLKQfhVh3cJ")).
neg(eqo("journals/tods/SistlaWYS98","GDR-Ve8Wn1oJ")).
neg(eqo("journals/tods/Snodgrass01","XS0g9j8J7woJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/L4H4H12200406465.pdf")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/N2VQ4NK4H736R74T.pdf")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/J6425476814Q6X0K.pdf")).
neg(eqo("journals/tods/StolboushkinT98","7C1w4dd8VyUJ")).
neg(eqo("journals/tods/TaoP03","7HvPXnU4DB8J")).
neg(eqo("journals/tods/Wijsen99","cH46MV7BljUJ")).
neg(eqo("journals/tods/YanG94","hMVhQ07qD9EJ")).
neg(eqo("journals/vldb/AbbadiSW01","O0IEHbFkD3oJ")).
neg(eqo("journals/vldb/AbiteboulCM98","ANlO5j9KIQkJ")).
neg(eqo("journals/vldb/AgrawalAJL95","VDLcWcM5fUoJ")).
neg(eqo("journals/vldb/Amer-YahiaCLS02","b2r9OZJJ4sgJ")).
neg(eqo("journals/vldb/Antoshenkov97","gleX-n_dgkcJ")).
neg(eqo("journals/vldb/Antoshenkov97","mm3mXWb8QS0J")).
neg(eqo("journals/vldb/AntoshenkovZ96","29APzgaC3f4J")).
neg(eqo("journals/vldb/Barbara-MillaG94","url:http://portal.acm.org/citation.cfm%3Fid%3D192593.197423")).
neg(eqo("journals/vldb/BarbaraI95","iOxtnjbC4SEJ")).
neg(eqo("journals/vldb/Baumann94","CVQSGBNUQOMJ")).
neg(eqo("journals/vldb/BeckerGOSW96","JnCZDIqNNTUJ")).
neg(eqo("journals/vldb/BerendtS00","8Xq9qerJCwUJ")).
neg(eqo("journals/vldb/BraumandlKKKKSS01","dURGvGhlWbsJ")).
neg(eqo("journals/vldb/CandanLS00","36DpVSDdzQIJ")).
neg(eqo("journals/vldb/ChuIT94","dOj3eLRwD4AJ")).
neg(eqo("journals/vldb/CombiP01","8YoYzQtOgYoJ")).
neg(eqo("journals/vldb/DiazJ97","S7PvJkEe0iQJ")).
neg(eqo("journals/vldb/DoanMDDH03","urKua_D0KVoJ")).
neg(eqo("journals/vldb/FangGM96","ktESz1RmXjQJ")).
neg(eqo("journals/vldb/FiebigHKMNSW02","w_FOwUavk0kJ")).
neg(eqo("journals/vldb/GeorgakopoulosRL94","G85JsnuAjzMJ")).
neg(eqo("journals/vldb/GeorgeH00","b9F3YB4bHxQJ")).
neg(eqo("journals/vldb/Han98","uEbdEtnaCXMJ")).
neg(eqo("journals/vldb/HarderST99","0hv_gvpYQBUJ")).
neg(eqo("journals/vldb/HarderST99","6R5S9wsQSOYJ")).
neg(eqo("journals/vldb/HarderST99","AL770KWRcoUJ")).
neg(eqo("journals/vldb/HarderST99","PK8Qs1QbQSQJ")).
neg(eqo("journals/vldb/HarderST99","aRFJ3t6iZjIJ")).
neg(eqo("journals/vldb/HuangDT99","01iwVR6RAU8J")).
neg(eqo("journals/vldb/IoannidisNSS97","qUfWV4VVxegJ")).
neg(eqo("journals/vldb/KamelWS94","X1MBCvIuINwJ")).
neg(eqo("journals/vldb/KnorrNT00","0Lm5yfrUjqEJ")).
neg(eqo("journals/vldb/KnorrNT00","gBDSoVhbJ_IJ")).
neg(eqo("journals/vldb/KornLKF00","niAGPBSYvBIJ")).
neg(eqo("journals/vldb/Li03","nsFFKjYz19cJ")).
neg(eqo("journals/vldb/MaratheS02","qGD7ZWZazLEJ")).
neg(eqo("journals/vldb/MylopoulosCPST96","S5QZuOo4AF8J")).
neg(eqo("journals/vldb/NgS98","-Kc_QLyo_-AJ")).
neg(eqo("journals/vldb/NguSHL01","bpWvAVOZLbwJ")).
neg(eqo("journals/vldb/NguSHL01","djYvVVRYNTwJ")).
neg(eqo("journals/vldb/PacittiS00","jJyGKE2N34gJ")).
neg(eqo("journals/vldb/PapazogluK97","vH6_IBLBx5sJ")).
neg(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
neg(eqo("journals/vldb/Sciore94","pzmTeD6SFSAJ")).
neg(eqo("journals/vldb/Seshadri98","CTDpT1x-0g8J")).
neg(eqo("journals/vldb/Seshadri98","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D914832")).
neg(eqo("journals/vldb/ShegalovGW01","_6ErNQyZwXsJ")).
neg(eqo("journals/vldb/SivasankaranSTPR96","bFNUZoN0LhsJ")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","AxpQwgyRyLgJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","2fO9nM2FoGYJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","9OEjtHuRUzsJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","qdCTR7WpuFUJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","C221gFS5VVoJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","ahfoveFQC2sJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","mYFf63cZ4lUJ")).
pos(eqo("conf/sigmod/AcharyaPR99","KrVgTXcNPPUJ")).
pos(eqo("conf/sigmod/AdaliBSS98","69JsZwNpla0J")).
pos(eqo("conf/sigmod/AdaliBSS98","rYC-j_j4Yv0J")).
pos(eqo("conf/sigmod/AdaliCPS96","BpZjLfob1eIJ")).
pos(eqo("conf/sigmod/AdaliCPS96","_CkpzhLiR30J")).
pos(eqo("conf/sigmod/AdaliCPS96","uMmcsye0YCkJ")).
pos(eqo("conf/sigmod/AdaliCPS96","zE4iM0h4W2sJ")).
pos(eqo("conf/sigmod/AdamY98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276350%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Adelberg98","5I0ArBmDRcEJ")).
pos(eqo("conf/sigmod/Adelberg98","lyTJMJmpo8IJ")).
pos(eqo("conf/sigmod/AdelbergGK95","NbLabaGWoh4J")).
pos(eqo("conf/sigmod/AdiBEY01","3jUi_Yf4DfIJ")).
pos(eqo("conf/sigmod/AggarwalY00","OV5GSHDaYNMJ")).
pos(eqo("conf/sigmod/AggarwalY00","dfSPs7YoyWsJ")).
pos(eqo("conf/sigmod/AggarwalY00","x5jeMyauzWgJ")).
pos(eqo("conf/sigmod/AgrawalASY97","-XBy73K2jq0J")).
pos(eqo("conf/sigmod/AgrawalASY97","bDiNQAdf8nEJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","_LE5T2vKPUcJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","rSTewQ1dQkYJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x8fDHaNkSUIJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x92Yw8H9uH4J")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","DFubU20j1OIJ")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","wGxcAPsmHgIJ")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","7-b5YXuGJS0J")).
pos(eqo("conf/sigmod/AndersonBKW98","H6eMdbXATmkJ")).
pos(eqo("conf/sigmod/AndersonBKW98","j6v2b9hN-R4J")).
pos(eqo("conf/sigmod/BarbaraI94","kooQijVBMscJ")).
pos(eqo("conf/sigmod/BargaL99","QGxyK7bJQOMJ")).
pos(eqo("conf/sigmod/BaulierBGGHJKKMMNNRSSSWW99","wgRWDYY7q_8J")).
pos(eqo("conf/sigmod/BerchtoldBBKK97","BMkGN7AiGhYJ")).
pos(eqo("conf/sigmod/BersonGM95","YkPqPzGFnZIJ")).
pos(eqo("conf/sigmod/BersonGMJ94","bw_c9Mk0_7IJ")).
pos(eqo("conf/sigmod/BlakeleyD00","url:http://portal.acm.org/citation.cfm%3Fid%3D335191.335480%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BlottRS96","8J0wmqs6RfIJ")).
pos(eqo("conf/sigmod/BlottRS96","pS2unAe-n_gJ")).
pos(eqo("conf/sigmod/BohlenBD99","X2odIfnOC88J")).
pos(eqo("conf/sigmod/BohmA96","978pJCGhaGoJ")).
pos(eqo("conf/sigmod/BorkarDS01","8fu2bhk_i9EJ")).
pos(eqo("conf/sigmod/BratsbergT00","356Jyb4b6rYJ")).
pos(eqo("conf/sigmod/BratsbergT00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335477%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BraumandlKK99","4fjXoCHhe1kJ")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
pos(eqo("conf/sigmod/BreunigKKS01","h-tyLTytlh4J")).
pos(eqo("conf/sigmod/Brown99","itP4yy9sLUUJ")).
pos(eqo("conf/sigmod/BrunoKS02","2VpRW4Tf08EJ")).
pos(eqo("conf/sigmod/BunemanDHS96","AtUsoMh8rY4J")).
pos(eqo("conf/sigmod/BunemanDHS96","R128Of6zyGgJ")).
pos(eqo("conf/sigmod/BunemanDHS96","Wo7In8pIWJ4J")).
pos(eqo("conf/sigmod/ButtlerLPP01","8TcpKdIK1r0J")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","5wcgt7bNx7YJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","dP-pHDZ7oawJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","mt8Q1YmVRkMJ")).
pos(eqo("conf/sigmod/CareyK97","b_lpj8wu7BEJ")).
pos(eqo("conf/sigmod/CareyK97","ucdmk8xwaTsJ")).
pos(eqo("conf/sigmod/ChakrabartiM99","Jg81WYtxtZoJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","D7w6TQwatE0J")).
pos(eqo("conf/sigmod/ChaudhuriD97","jsapF3OoWXcJ")).
pos(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","RYeFLYha0ewJ")).
pos(eqo("conf/sigmod/ChenCPPSTM00","Ab6MIDVDzhAJ")).
pos(eqo("conf/sigmod/ChenGK01","8OgkUeiawO0J")).
pos(eqo("conf/sigmod/ChenJDTW00","5Trj9q_RI8YJ")).
pos(eqo("conf/sigmod/ChenJDTW00","OsfWKJek9L8J")).
pos(eqo("conf/sigmod/ChristophidesCM96","-LUnZ7Zwr1QJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","nDl2k1YSi8AJ")).
pos(eqo("conf/sigmod/Cohen98","_ICk4vgjlgsJ")).
pos(eqo("conf/sigmod/Cohen98a","qfD_kxYt-dsJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","0FohHTWs5toJ")).
pos(eqo("conf/sigmod/CrescenziMM02","pI0WktymowwJ")).
pos(eqo("conf/sigmod/DattaDTVSR02","5N2k30IYlWoJ")).
pos(eqo("conf/sigmod/DeutschFS99","2lypQEgzfb8J")).
pos(eqo("conf/sigmod/DeutschFS99","SYaXErlVlcAJ")).
pos(eqo("conf/sigmod/DeutschFS99","XrybyHOI16kJ")).
pos(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
pos(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
pos(eqo("conf/sigmod/Dyreson03","l7KC1qG6OGEJ")).
pos(eqo("conf/sigmod/FaginKS03","tQZWeE_nsa0J")).
pos(eqo("conf/sigmod/FernandezFKLS98","N9NHi5y3K38J")).
pos(eqo("conf/sigmod/FernandezFKLS98","i5coyXNfHCkJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","rgk1HYJbTNEJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","x-Xcm921UTMJ")).
pos(eqo("conf/sigmod/FlorescuGKR02","uam2rv99rxsJ")).
pos(eqo("conf/sigmod/FukudaMMT96","sOBRaiLLvZgJ")).
pos(eqo("conf/sigmod/Gal00","SudUID_rEy0J")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GarofalakisG02","r4a_VlMfu38J")).
pos(eqo("conf/sigmod/GarofalakisGR02","ImADir74KWIJ")).
pos(eqo("conf/sigmod/GarofalakisGR02","S6PWjHRFORYJ")).
pos(eqo("conf/sigmod/GatziuGD95","NU4yPbIkZpsJ")).
pos(eqo("conf/sigmod/GatziuGD95","RvtHXIfsMasJ")).
pos(eqo("conf/sigmod/GehrkeKS01","KIp3KSU4whsJ")).
pos(eqo("conf/sigmod/GeneserethKD97","2Nl65Vp7bxUJ")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/Gerber95","wlxZ0FqTy_MJ")).
pos(eqo("conf/sigmod/Golding95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223865%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D223784%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
pos(eqo("conf/sigmod/GravanoCGP97","PsoYENGEh9cJ")).
pos(eqo("conf/sigmod/GrayHOS96","5cw83MyqYrMJ")).
pos(eqo("conf/sigmod/GrayHOS96","Mopy3Yg3i60J")).
pos(eqo("conf/sigmod/GrayHOS96","_pjwP11t_y8J")).
pos(eqo("conf/sigmod/GrayHOS96","pDjbDK0ZzsMJ")).
pos(eqo("conf/sigmod/GriffinL95","RuYYq5xDgNYJ")).
pos(eqo("conf/sigmod/GrossmanQ94","yjqdBeNw5WoJ")).
pos(eqo("conf/sigmod/GuhaRS98","H7UayPkDxRQJ")).
pos(eqo("conf/sigmod/GuhaRS98","LoR0K8QRGkgJ")).
pos(eqo("conf/sigmod/GuhaRS98","Y8HMa1ZZE6sJ")).
pos(eqo("conf/sigmod/GuhaRS98","iSkco-aumngJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","VEDf7vb98i8J")).
pos(eqo("conf/sigmod/GuoSBS03","p_PDgjVRUS4J")).
pos(eqo("conf/sigmod/GuptaMR95","7ggq-jY7UEYJ")).
pos(eqo("conf/sigmod/GuptaMR95","ELtcV7mOQDgJ")).
pos(eqo("conf/sigmod/GuptaMR95","InJyYTfzN50J")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanKK97","MqdtZ_cUxDEJ")).
pos(eqo("conf/sigmod/HanPLJ01","H_tzR6yoJLEJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","-RzBfKSBxpgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","8A_9ucHRXyIJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Fyek_kCB-qkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","V6KNPMKdyagJ")).
pos(eqo("conf/sigmod/Hellerstein94","r4adn1YKOFIJ")).
pos(eqo("conf/sigmod/HellersteinN96","5vvOcgfpjUgJ")).
pos(eqo("conf/sigmod/HungYK96","bTI28RjBpPwJ")).
pos(eqo("conf/sigmod/IlyasRLGL03","qCnvlNwYp6cJ")).
pos(eqo("conf/sigmod/ImielinskiV95","dKMRgoNRQDgJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","7FHudYbEkF0J")).
pos(eqo("conf/sigmod/ImielinskiVB94","7qv9IC8F_WQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","9KBHBWVwKZsJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","V-LO20klzSYJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/JagadishKS00","OZRYdxoJqXMJ")).
pos(eqo("conf/sigmod/JagadishLS99","p5n3KKoHgMgJ")).
pos(eqo("conf/sigmod/JonssonFS98","t6-LjSlCUmcJ")).
pos(eqo("conf/sigmod/JoshiA01","H9bMRYKnXMQJ")).
pos(eqo("conf/sigmod/KalnisNOPT02","Qyeg-VuH-2kJ")).
pos(eqo("conf/sigmod/KaushikBNK02","8M2rLLD3DlQJ")).
pos(eqo("conf/sigmod/KimCK01","EYI-OULRIz8J")).
pos(eqo("conf/sigmod/KotidisR98","CpHJwU8o-BkJ")).
pos(eqo("conf/sigmod/KrollW94","kUzm9ofgc1UJ")).
pos(eqo("conf/sigmod/KrollW94","zd_8s13rNRoJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","lduaYmELtHoJ")).
pos(eqo("conf/sigmod/LeeWMS01","OFXL5KsJiWcJ")).
pos(eqo("conf/sigmod/LiBCS00","4abl38Q9iH4J")).
pos(eqo("conf/sigmod/LiYVGPUV98","oQtxPA_0PCYJ")).
pos(eqo("conf/sigmod/LibkinMW96","OfZWx8jhQvwJ")).
pos(eqo("conf/sigmod/LibkinMW96","uxD8p47apUYJ")).
pos(eqo("conf/sigmod/LiskovACDGGMMS96","Ey7Mbh6IdQIJ")).
pos(eqo("conf/sigmod/LitwinS00","99nKpf7A4uIJ")).
pos(eqo("conf/sigmod/LitwinS00","R7Z-NlUo_YUJ")).
pos(eqo("conf/sigmod/LitwinS00","RQ9fpPAS2h8J")).
pos(eqo("conf/sigmod/LitwinS00","fx0s58TJ75EJ")).
pos(eqo("conf/sigmod/LiuFP03","5BY1upUmSTUJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","0e3PPUvtZ0MJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","ezlAkB7ijDUJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/LoR96","em5eiGpRZFkJ")).
pos(eqo("conf/sigmod/LometW98","F2ecYx97F2sJ")).
pos(eqo("conf/sigmod/MaddenSHR02","DkgClKWAyEIJ")).
pos(eqo("conf/sigmod/MaddenSHR02","WhBHQqg-7l8J")).
pos(eqo("conf/sigmod/MaddenSHR02","zobnUjtYSe8J")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/McAuliffeCS96","c__Nxyn_uvwJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","v2KwhRi-OrMJ")).
pos(eqo("conf/sigmod/MelnikRB03","bkpTodGryDAJ")).
pos(eqo("conf/sigmod/Miller98","0B1XRTZ8cHkJ")).
pos(eqo("conf/sigmod/Miller98","_ExuZq1BkEkJ")).
pos(eqo("conf/sigmod/Miller98","fW6JIoNRqAQJ")).
pos(eqo("conf/sigmod/MiloAABN03","P7vZf4MkRO4J")).
pos(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
pos(eqo("conf/sigmod/MissikoffT94","nxNSfctbGWAJ")).
pos(eqo("conf/sigmod/Mohan02","YJlUtEk7zwkJ")).
pos(eqo("conf/sigmod/Mohan96","C-yzbvoAg00J")).
pos(eqo("conf/sigmod/Mohan96","ZEh9UFMj3-EJ")).
pos(eqo("conf/sigmod/MoleskyR95","mSR0bA8pIOwJ")).
pos(eqo("conf/sigmod/MumickQM97","cvHvC7tUSrIJ")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/OhHP00","T91d5LI-xIwJ")).
pos(eqo("conf/sigmod/OhHP00","o8cVWUElfUsJ")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304245%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
pos(eqo("conf/sigmod/ParkCY95","-VGXHx94MXgJ")).
pos(eqo("conf/sigmod/ParkCY95","hLrdara3zskJ")).
pos(eqo("conf/sigmod/ParkCY95","ko0i4AzclBgJ")).
pos(eqo("conf/sigmod/ParkCY95","pN4pq6qELakJ")).
pos(eqo("conf/sigmod/ParkCY95","x5By8kBxxpwJ")).
pos(eqo("conf/sigmod/PonnekantiK00","IddFq2o4ZsoJ")).
pos(eqo("conf/sigmod/RajagopalanML98","6bxNVhIp7FAJ")).
pos(eqo("conf/sigmod/RajagopalanML98","HVP6eYl30IgJ")).
pos(eqo("conf/sigmod/RajagopalanML98","M2bWqRDDfkUJ")).
pos(eqo("conf/sigmod/RajagopalanML98","iUtn70TmoZIJ")).
pos(eqo("conf/sigmod/Rajaraman99","m_n55lcmF-sJ")).
pos(eqo("conf/sigmod/Rajaraman99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304246%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RaoR98","iqZZMPppeKAJ")).
pos(eqo("conf/sigmod/RaoR98","uHX7_KIw8uYJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","Rh68dFgQfS4J")).
pos(eqo("conf/sigmod/SaltenisJLL00","odsY0ehPPhIJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wISxjPqlwZoJ")).
pos(eqo("conf/sigmod/SarawagiTA98","SLmQWvsYtKYJ")).
pos(eqo("conf/sigmod/SarawagiTA98","kT7z4mcwLrYJ")).
pos(eqo("conf/sigmod/SarawagiTA98","ut4Y99B1094J")).
pos(eqo("conf/sigmod/SchleimerWA03","nCRFjDfhOmcJ")).
pos(eqo("conf/sigmod/SelfridgeSW96","4ucV5h3-YvMJ")).
pos(eqo("conf/sigmod/SeshadriLR94","60I0j0qUHVYJ")).
pos(eqo("conf/sigmod/SeshadriLR94","G4N8qaBAG4kJ")).
pos(eqo("conf/sigmod/ShenNSHS03","LjrsWIr3rhAJ")).
pos(eqo("conf/sigmod/ShuklaD00","kcrWfQEI9G8J")).
pos(eqo("conf/sigmod/StonebrakerH01","opMsehfY-XoJ")).
pos(eqo("conf/sigmod/SubramanianV98","KxwymZ2AGNQJ")).
pos(eqo("conf/sigmod/SzalayGKT00","4yvrgPBJUBYJ")).
pos(eqo("conf/sigmod/SzalayGKT00","YVCi81Vp9KAJ")).
pos(eqo("conf/sigmod/SzalayGKT00","oPgy1SYoptgJ")).
pos(eqo("conf/sigmod/TomasicGS94","n8krnsf_y30J")).
pos(eqo("conf/sigmod/TomasicGS94","wFwk1sJZ2SYJ")).
pos(eqo("conf/sigmod/Toyama98","h4OQc4N4kjIJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","EkZGcIaXlkIJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","ij8LH1U0bgQJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","w5i-zY0c1jAJ")).
pos(eqo("conf/sigmod/VitterW99","1UFq52qqErUJ")).
pos(eqo("conf/sigmod/VitterW99","P5oJUiow7lsJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","4QUIJRy2NdMJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
pos(eqo("conf/sigmod/WangZS95","86-DS0U0jY0J")).
pos(eqo("conf/sigmod/WangZS95","QHrpE-XaLoMJ")).
pos(eqo("conf/sigmod/WhiteCF98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/WhiteD94","jKBaGqWJK2oJ")).
pos(eqo("conf/sigmod/WilschutFA95","Zdfxvjh6ca8J")).
pos(eqo("conf/sigmod/WilschutFA95","vgoFTdXYHZ0J")).
pos(eqo("conf/sigmod/WitkowskiBBDFGSS03","ygCe1xRFuKgJ")).
pos(eqo("conf/sigmod/YangM97","57m7NniyTrkJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","Pbl_CbLYKWYJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qzxeS4RQAhwJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","I5JNUp7RoGgJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","MjGo7AhsPSsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","Wg8o4cj8Cq4J")).
pos(eqo("conf/sigmod/ZhaoDNS98","mBC03oUT8yAJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","KjM8fKqooDQJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","SSwR2rhkJk0J")).
pos(eqo("conf/sigmod/ZhugeGHW95","_XLK2p-e2pYJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","lUxILYnWlLYJ")).
pos(eqo("conf/sigmod/ZuzartePMCLW03","url:http://portal.acm.org/citation.cfm%3Fid%3D872757.872840")).
pos(eqo("conf/vldb/AbiteboulACEMM99","hh9fQmB-eEEJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","OqpwlRWdIMgJ")).
pos(eqo("conf/vldb/Adler01","Tnuonq9Zi4cJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","1bXX8uOvfQAJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","E4fU9kpfXQsJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/AggarwalHWY03","ZFtAmPKKRBQJ")).
pos(eqo("conf/vldb/AggarwalHWY03","ZympjYazs6QJ")).
pos(eqo("conf/vldb/AggarwalHWY03","szlqyCesMpgJ")).
pos(eqo("conf/vldb/AgrawalCN00","U8CMJBaJyX8J")).
pos(eqo("conf/vldb/AgrawalCN00","b9uF_OTTHIEJ")).
pos(eqo("conf/vldb/AgrawalLSS95","HugNLG7z-Z4J")).
pos(eqo("conf/vldb/AgrawalLSS95","PbZkvDhTeyEJ")).
pos(eqo("conf/vldb/AlsabtiRS97","-0Lu8VIRYtEJ")).
pos(eqo("conf/vldb/AnkerstBKS98","DbLGmJX7UJ8J")).
pos(eqo("conf/vldb/ArgePRSV98","A5Eiwdh71m0J")).
pos(eqo("conf/vldb/ArgePRSV98","c3yObnVI65cJ")).
pos(eqo("conf/vldb/BalminPP00","FoAVdcYe0tsJ")).
pos(eqo("conf/vldb/BaralisW94","nqaF5CzBelgJ")).
pos(eqo("conf/vldb/BargaP95","-lqp87W0EZ4J")).
pos(eqo("conf/vldb/BargaP95","QsXNubRv-HUJ")).
pos(eqo("conf/vldb/BargaP95","SwFgF_a7RooJ")).
pos(eqo("conf/vldb/BelussiF95","5FEmoD1TIdwJ")).
pos(eqo("conf/vldb/BelussiF95","7BDCL140Kx4J")).
pos(eqo("conf/vldb/BelussiF95","A-Fi-3YSz0IJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","62aA4DYB0MQJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
pos(eqo("conf/vldb/BohannonGKNS02","jj64xkk75ZIJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","GzK2N5eQ0pQJ")).
pos(eqo("conf/vldb/BonifatiCDS01","tCrfb27dXiwJ")).
pos(eqo("conf/vldb/BrinkhoffK94","egvBPvtoaMMJ")).
pos(eqo("conf/vldb/BrodieC99","80T8-ddj8OsJ")).
pos(eqo("conf/vldb/CarinoO98","iaOLRaqTWmEJ")).
pos(eqo("conf/vldb/CarinoO98","lDNAWc5SrmIJ")).
pos(eqo("conf/vldb/CatozziR01","UQY439hXMEgJ")).
pos(eqo("conf/vldb/CatozziR01","x_mqIy3GCmAJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","8IR1NrQ4zm8J")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChaudhuriG99","l-Sn0enuHxkJ")).
pos(eqo("conf/vldb/ChaudhuriS01","-jtu5QeiAKQJ")).
pos(eqo("conf/vldb/ChenDZ03","cCpHMzAXRnsJ")).
pos(eqo("conf/vldb/Chiueh94","PKK2ak_IzrgJ")).
pos(eqo("conf/vldb/ChoN02","GzOK_PJlOwQJ")).
pos(eqo("conf/vldb/ChungCLL01","mJiDvbtTKWoJ")).
pos(eqo("conf/vldb/DarmontS99","1GWsEQSvJmoJ")).
pos(eqo("conf/vldb/DattaRT99","gckQTLQjsj8J")).
pos(eqo("conf/vldb/Dayal99","url:http://portal.acm.org/citation.cfm%3Fid%3D645925.671502")).
pos(eqo("conf/vldb/DaynesC02","Ug0Yk0QhILMJ")).
pos(eqo("conf/vldb/DeWittKLPY94","ENb3jCRhOi8J")).
pos(eqo("conf/vldb/DesslochM97","CjtIFow-OWcJ")).
pos(eqo("conf/vldb/DoR02","-AsVP3NqvlAJ")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("conf/vldb/DoR02","poUtz1rrj6kJ")).
pos(eqo("conf/vldb/Draluk01","xQzrilMR-QQJ")).
pos(eqo("conf/vldb/FangSGMU98","E7yZtVJa2xAJ")).
pos(eqo("conf/vldb/FangSGMU98","z5tz9vybRmIJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","Ulg4PC4-auoJ")).
pos(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
pos(eqo("conf/vldb/FlorescuLSY99","aUElZKC-txIJ")).
pos(eqo("conf/vldb/FuhDCMTLDRM99","nh2FuiC6fHgJ")).
pos(eqo("conf/vldb/GarofalakisG02","ImADir74KWIJ")).
pos(eqo("conf/vldb/GarofalakisG02","S6PWjHRFORYJ")).
pos(eqo("conf/vldb/GarofalakisRS99","q87jrCR_GqQJ")).
pos(eqo("conf/vldb/GibsonKR98","9FBwT6XFOssJ")).
pos(eqo("conf/vldb/GingrasL98","VSBQl2qbF8UJ")).
pos(eqo("conf/vldb/GottlobKP02","Pk09A5EmsOoJ")).
pos(eqo("conf/vldb/GottlobKP02","e5Gm5upjQnkJ")).
pos(eqo("conf/vldb/GravanoG95","2nMktwioqOYJ")).
pos(eqo("conf/vldb/GravanoG97","CduLyvAaxVsJ")).
pos(eqo("conf/vldb/Greco98","CCr8CUlHeNsJ")).
pos(eqo("conf/vldb/GrumbachRS00","iQ3Zi3crc9wJ")).
pos(eqo("conf/vldb/HageJPST03","-JYQE7IPu_4J")).
pos(eqo("conf/vldb/HageJPST03","6dAWUHYKqFUJ")).
pos(eqo("conf/vldb/HageJPST03","xDDdtO9n_pwJ")).
pos(eqo("conf/vldb/HammadFAE03","vfCFumS9QtkJ")).
pos(eqo("conf/vldb/HammelP02","SU2XS1MVb40J")).
pos(eqo("conf/vldb/HelmerM97","xsh0C_nCllsJ")).
pos(eqo("conf/vldb/HelmerNM03","8-HpAN0xpjcJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","o2qGdf4L94MJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","zbaMbE17LyQJ")).
pos(eqo("conf/vldb/IpeirotisG02","JmGdMWsJuK0J")).
pos(eqo("conf/vldb/IwerksSS03","4B_LhCns0WoJ")).
pos(eqo("conf/vldb/IyerW94","5smJVUm1KAYJ")).
pos(eqo("conf/vldb/JagadishKMPSS98","0TmcLmakam0J")).
pos(eqo("conf/vldb/JagadishKMPSS98","TB8sxeXqHRQJ")).
pos(eqo("conf/vldb/JagadishLRSS94","Yiwh22hbTAcJ")).
pos(eqo("conf/vldb/JohnsonM98","V4PVzPaBOBUJ")).
pos(eqo("conf/vldb/JohnsonM98","cTZLUZ5_cfkJ")).
pos(eqo("conf/vldb/JohnsonM98","eFynrwKK_T0J")).
pos(eqo("conf/vldb/JohnsonM98","gm9Ist67nJQJ")).
pos(eqo("conf/vldb/JonscherD94","iBEI8pUanCEJ")).
pos(eqo("conf/vldb/Keogh02","rKIsQpbRiM0J")).
pos(eqo("conf/vldb/KiesslingK02","OuVZjeR64pMJ")).
pos(eqo("conf/vldb/KnorrN98","kKQ_2bg6WXAJ")).
pos(eqo("conf/vldb/Kornacker99","aOmma8tnFKIJ")).
pos(eqo("conf/vldb/KornackerB95","IN_sibgHb9MJ")).
pos(eqo("conf/vldb/KumarKA97","8bLd-1l1at4J")).
pos(eqo("conf/vldb/KumarKA97","EhTWppk6No8J")).
pos(eqo("conf/vldb/LabioG96","1JLlGYW8cDAJ")).
pos(eqo("conf/vldb/LabioG96","nsN_2BnT_mMJ")).
pos(eqo("conf/vldb/LabrinidisR01","9ZhDPDECMQ8J")).
pos(eqo("conf/vldb/LahiriSCMC01","MbzMAsLHlfEJ")).
pos(eqo("conf/vldb/LakshmananSS99","RSpmu6WtYBMJ")).
pos(eqo("conf/vldb/LeeLWS97","3k61gi_ld_UJ")).
pos(eqo("conf/vldb/LeeLWS97","fHKhYR-6ksMJ")).
pos(eqo("conf/vldb/LevyRO96","3v8fGnfTuVMJ")).
pos(eqo("conf/vldb/Leymann03","url:http://www.vldb.org/conf/2003/papers/S32P01.pdf")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/LitwinNS94","FhyWT1pyLnUJ")).
pos(eqo("conf/vldb/LuOT94","ZFXYXT4yEcAJ")).
pos(eqo("conf/vldb/LuSL95","AvfsXnSTA24J")).
pos(eqo("conf/vldb/LuSL95","h24eSPFv8MoJ")).
pos(eqo("conf/vldb/MadhavanBR01","66dWDpWjbbwJ")).
pos(eqo("conf/vldb/MadhavanBR01","wRHapJxb_-QJ")).
pos(eqo("conf/vldb/ManegoldBK00","-7hYJxFD-AsJ")).
pos(eqo("conf/vldb/ManegoldBK00","sZmrat79cF0J")).
pos(eqo("conf/vldb/MarronL01","a3aecJJ58NIJ")).
pos(eqo("conf/vldb/Mattos03","0ZvKAMWwp80J")).
pos(eqo("conf/vldb/McKennaBHT96","0tZaTV3W05wJ")).
pos(eqo("conf/vldb/MendelzonV00","AQLsLBctUI4J")).
pos(eqo("conf/vldb/MendelzonV00","Ah3ENTVwMj4J")).
pos(eqo("conf/vldb/MengLLA03","_dOpWA3QWOEJ")).
pos(eqo("conf/vldb/MengLLA03","s0v2kYtOvgoJ")).
pos(eqo("conf/vldb/MengLYWCR98","EcpPzbn2EaIJ")).
pos(eqo("conf/vldb/MignetMAC01","VaDXNMtPZ4oJ")).
pos(eqo("conf/vldb/MignetMAC01","XirELrPeTd4J")).
pos(eqo("conf/vldb/MillerHH00","6vtHcpLApB8J")).
pos(eqo("conf/vldb/MillerHH00","YQ0D98oeJKMJ")).
pos(eqo("conf/vldb/MiloZ98","UF-Z2VPtU6sJ")).
pos(eqo("conf/vldb/MiloZ98","a7XtgKiAJFMJ")).
pos(eqo("conf/vldb/MoserKK95","A2OQAUw2OHIJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("conf/vldb/NgH94","AJ7Qj_bt0ZoJ")).
pos(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
pos(eqo("conf/vldb/NgH94","HLu7MvWb5rMJ")).
pos(eqo("conf/vldb/NgH94","W1di9S0fUsEJ")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/OzdenGHNSDGGW01","ZzYmVTAjsnQJ")).
pos(eqo("conf/vldb/Padmanabhan96","1IjlMvLBFC0J")).
pos(eqo("conf/vldb/PatonG01","mHCrMuxQnBsJ")).
pos(eqo("conf/vldb/PirotteZMY94","8s-SP8sAvQAJ")).
pos(eqo("conf/vldb/PitouraC99","6VU-VxcDsFsJ")).
pos(eqo("conf/vldb/PottingerL00","M2zV0WBF7XYJ")).
pos(eqo("conf/vldb/RamamrithamABEGP00","jYGXFESkS-YJ")).
pos(eqo("conf/vldb/RamamurthyDS02","DAlyofX710AJ")).
pos(eqo("conf/vldb/RaoR99","N8XkcmIO0ysJ")).
pos(eqo("conf/vldb/RosenthalS94","NFUWsBXtCncJ")).
pos(eqo("conf/vldb/RossS97","-rTWS2erFQcJ")).
pos(eqo("conf/vldb/RossS97","mrH-8zANwLwJ")).
pos(eqo("conf/vldb/SakuraiYKU01","OQMYc3S0Ny8J")).
pos(eqo("conf/vldb/SattlerGS03","7y1DNkciIFQJ")).
pos(eqo("conf/vldb/ScheuermannSV96","N3Hyyb1Qw8sJ")).
pos(eqo("conf/vldb/ScheuermannSV96","TCAOiofZaFIJ")).
pos(eqo("conf/vldb/ScheuermannSV96","kxebBNLKWl4J")).
pos(eqo("conf/vldb/SeidlK97","HAG0kCjBu4EJ")).
pos(eqo("conf/vldb/SevcikK96","GiHrMj3vbSAJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","ZQyBjtpbhvIJ")).
pos(eqo("conf/vldb/ShivakumarGC98","GHz2PmQwW2UJ")).
pos(eqo("conf/vldb/SistlaYH94","bDH4OmzDSLEJ")).
pos(eqo("conf/vldb/StathatosRB97","ubOeBh7Lk8sJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","EPtaqugcCyMJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","k-IlQ6VnmKsJ")).
pos(eqo("conf/vldb/StohrMR00","7fCRAqLTNeUJ")).
pos(eqo("conf/vldb/Sullivan96","zGRQ_2im_9MJ")).
pos(eqo("conf/vldb/TamuraK99","rAHGAfoqookJ")).
pos(eqo("conf/vldb/TamuraK99","w2W3fqz4M7IJ")).
pos(eqo("conf/vldb/TengCY03","wJjaZnzD6pAJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
pos(eqo("conf/vldb/Tygar98","lWMzZgqNlSEJ")).
pos(eqo("conf/vldb/VassalosP97","2DJipXynj5wJ")).
pos(eqo("conf/vldb/VassalosP97","vPKoA4R_sU8J")).
pos(eqo("conf/vldb/ViglasNB03","GGX9LS25OhwJ")).
pos(eqo("conf/vldb/VorugantiOU99","yi0fC_dpTUkJ")).
pos(eqo("conf/vldb/VriesDBA99","3o-rUvRsdUwJ")).
pos(eqo("conf/vldb/Wadler01","TyF71uAlnLsJ")).
pos(eqo("conf/vldb/WangC03","nXj_8Y7lmHsJ")).
pos(eqo("conf/vldb/WangC03","yjZolbzEP6wJ")).
pos(eqo("conf/vldb/WangYM97","RiOvjzg_MJwJ")).
pos(eqo("conf/vldb/WangYM97","o5dSRIunsUUJ")).
pos(eqo("conf/vldb/WangYM97","t5wcMnkbsiUJ")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/YanG95","baVAtfo4WCoJ")).
pos(eqo("conf/vldb/YuPM03","sP3bZMqHmZsJ")).
pos(eqo("conf/vldb/ZengBNN01","MA7NWFIgTaoJ")).
pos(eqo("conf/vldb/ZirintsisKM99","sldCppj0qOEJ")).
pos(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
pos(eqo("conf/vldb/ZouS98","fPzfCbyzqsoJ")).
pos(eqo("journals/sigmod/AbelTK97","yK-yqVAiXekJ")).
pos(eqo("journals/sigmod/AilamakiG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AndlerHEMBE96","WZ823oj6x3cJ")).
pos(eqo("journals/sigmod/BaaderJN97","SxT807RR-NsJ")).
pos(eqo("journals/sigmod/BaaderJN97","dr4SzOhnLB8J")).
pos(eqo("journals/sigmod/Baeza-YatesN96","1avO1fqtQ6QJ")).
pos(eqo("journals/sigmod/Baeza-YatesN96","W3NucQtmzesJ")).
pos(eqo("journals/sigmod/BallMRZ02","Mfc9xsb7BuQJ")).
pos(eqo("journals/sigmod/BernsteinDK99","Ye5fTBiMoUwJ")).
pos(eqo("journals/sigmod/BernsteinDK99","ne7WhiSL9QYJ")).
pos(eqo("journals/sigmod/BerraNT95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202670%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BollKB98","IBg3vuolFUwJ")).
pos(eqo("journals/sigmod/BorgidaCS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CampbellEM03","N9u28V6NZTIJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","Axu6UlX-pPYJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","OhiGJ7Gy3KgJ")).
pos(eqo("journals/sigmod/CasatiDS00","jPx0tvkJ-fUJ")).
pos(eqo("journals/sigmod/CuiJO02","Llr0ikQ8yIIJ")).
pos(eqo("journals/sigmod/Danish98","J2Mi5B81Il0J")).
pos(eqo("journals/sigmod/Eisenberg96","tFbkjO2wcFMJ")).
pos(eqo("journals/sigmod/EisenbergM01","lTNqBpBUA5sJ")).
pos(eqo("journals/sigmod/EisenbergM98","-RAYAJbKLNUJ")).
pos(eqo("journals/sigmod/ElmagarmidJF95","CJK2SWLYrRYJ")).
pos(eqo("journals/sigmod/FengJH01","SUT-QTwqFNkJ")).
pos(eqo("journals/sigmod/FlorescuLM98","_SR_pRTnA6IJ")).
pos(eqo("journals/sigmod/FreemanG96","VlHke7OkYwQJ")).
pos(eqo("journals/sigmod/GatziuKBF98","C8tPNXRbNnIJ")).
pos(eqo("journals/sigmod/GatziuKBF98","GlHmit1yw6AJ")).
pos(eqo("journals/sigmod/GobleR02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","_q3scPb8vbgJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","ihljCMaS2UsJ")).
pos(eqo("journals/sigmod/HalkidiBV02","SFs0XOMPphIJ")).
pos(eqo("journals/sigmod/HansonN99","id1te58YJlUJ")).
pos(eqo("journals/sigmod/HasselbringHHKRRS00","X9PsaiaoDJ4J")).
pos(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
pos(eqo("journals/sigmod/Jarke95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202671%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JenningsNF98","YiZVv5kVDb4J")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/JenningsNF98","vgi1l8lbDcsJ")).
pos(eqo("journals/sigmod/KambhampatiK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KeetonPH98","6MtRlhEClPEJ")).
pos(eqo("journals/sigmod/KeetonPH98","9xH94cKF-CYJ")).
pos(eqo("journals/sigmod/KennedyMB96","vBYtmDEYeK0J")).
pos(eqo("journals/sigmod/Klein94","kG86HB6N1xEJ")).
pos(eqo("journals/sigmod/Konig-RiesMMPPRSVW02","FIxl60DSBqgJ")).
pos(eqo("journals/sigmod/KuanL99","BZfdROjhbhwJ")).
pos(eqo("journals/sigmod/Kumar03","VuNnpxJwvQkJ")).
pos(eqo("journals/sigmod/KuokFW98","LwZe_nTD__UJ")).
pos(eqo("journals/sigmod/LeeC00","Knzz_bkGA00J")).
pos(eqo("journals/sigmod/LenzVJS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959083%26type%3Dpdf")).
pos(eqo("journals/sigmod/LiefkeS00","4q4PDOS45uIJ")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MalaikaEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945739%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MaximilienS02","HqytuZsDNx8J")).
pos(eqo("journals/sigmod/MaximilienS02","hgjhR8PwNVwJ")).
pos(eqo("journals/sigmod/MedeirosP94","chmPCuLihZoJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","Fjyenk1hvFkJ")).
pos(eqo("journals/sigmod/MotroA03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959085%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Ouksel03","8M_z-OUkoxYJ")).
pos(eqo("journals/sigmod/OukselS99","S-LYnzS1K70J")).
pos(eqo("journals/sigmod/Palpanas00","MGG31wuhuUIJ")).
pos(eqo("journals/sigmod/Palpanas00","wqWcfwbLjIYJ")).
pos(eqo("journals/sigmod/PitouraB95","KlM6IrItVpcJ")).
pos(eqo("journals/sigmod/Qian97","url:http://portal.acm.org/citation.cfm%3Fid%3D248603.248618%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RafanelliBT96","MfWZUBAVPFUJ")).
pos(eqo("journals/sigmod/RoddickABDEGHLMMMW00","eA8gNVxHRJ4J")).
pos(eqo("journals/sigmod/RosenthalS99","AaKiSc1klw8J")).
pos(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202672%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ShethBS99","uTsHgv9-zdUJ")).
pos(eqo("journals/sigmod/ShethMKA01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604286%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Snodgrass94","i7dLYB6NnW0J")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","64iWa-ZiPRcJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","h1zPIDDnNxEJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","vUONDuuNNCQJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94a","12xRfc32PXoJ")).
pos(eqo("journals/sigmod/SonDT96","62uEWBKYqgoJ")).
pos(eqo("journals/sigmod/StolfoLCFE01","lvIPWxkN4YAJ")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
pos(eqo("journals/sigmod/TanakaV01","sQu8znidi50J")).
pos(eqo("journals/sigmod/WestmannKHM00","Cm209Vuk17cJ")).
pos(eqo("journals/sigmod/WestmannKHM00","aLDnCruGaqYJ")).
pos(eqo("journals/sigmod/WestmannKHM00","q9rwlM_FKqkJ")).
pos(eqo("journals/sigmod/Winslett01","m2Mf-4BgLP4J")).
pos(eqo("journals/sigmod/Winslett94","hZOXZJ6x2xUJ")).
pos(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181569%26type%3Dpdf")).
pos(eqo("journals/sigmod/Wu02","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637426%26dl%3DGUIDE%26dl%3DACM%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Wu02","zCrDiwnKRHIJ")).
pos(eqo("journals/sigmod/YeungHL94","yQv94p3tE1IJ")).
pos(eqo("journals/sigmod/Zhang95","f86VsMJZ9gAJ")).
pos(eqo("journals/tods/AikenHW95","U8ZlWhxgtxYJ")).
pos(eqo("journals/tods/AikenHW95","XLld3hq3vt0J")).
pos(eqo("journals/tods/AikenHW95","cHpmOFVpTi8J")).
pos(eqo("journals/tods/BaekgaardM95","6UycFCZooDoJ")).
pos(eqo("journals/tods/BozkayaO99","0znTIa901S8J")).
pos(eqo("journals/tods/ChenHM95","pO6SFdVGt5QJ")).
pos(eqo("journals/tods/CliffordC94","wLG-N_iOaRIJ")).
pos(eqo("journals/tods/DattaVCK99","VaO8O5WO0IcJ")).
pos(eqo("journals/tods/DekhtyarRS01","9U0LKc8qS2kJ")).
pos(eqo("journals/tods/DekhtyarRS01","AnNzb6Gr7HkJ")).
pos(eqo("journals/tods/DekhtyarRS01","ywEAyex_frMJ")).
pos(eqo("journals/tods/DeyS96","l2y2U5f48WcJ")).
pos(eqo("journals/tods/EiterLLS01","tEZIquYevQoJ")).
pos(eqo("journals/tods/GravanoGT99","NCv4Y_aV23EJ")).
pos(eqo("journals/tods/GravanoGT99","aXLcAfb2y5kJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","-q1BFuUI27EJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","5cAIVZJShAEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","y5JyKlYjnI4J")).
pos(eqo("journals/tods/Jimenez-PerisPAK03","yj7oLWfPR4gJ")).
pos(eqo("journals/tods/KorthS94","w40iTKlpWEQJ")).
pos(eqo("journals/tods/KossmannS00","PnGVbzQCWY0J")).
pos(eqo("journals/tods/KossmannS00","XyQ6cXyNPN4J")).
pos(eqo("journals/tods/RaschidL96","rUpu2pcFa8cJ")).
pos(eqo("journals/tods/SistlaWYS98","4owPoyytTP4J")).
pos(eqo("journals/tods/Subrahmanian94","YAkzY3hCPxQJ")).
pos(eqo("journals/tods/Subrahmanian94","wl8Wa2O28_oJ")).
pos(eqo("journals/tods/Wijsen99","_D3JPE9NgNgJ")).
pos(eqo("journals/tods/WolfsonJH97","FlC-FF1hbbUJ")).
pos(eqo("journals/vldb/AbiteboulCM98","WzT3S2G1FjcJ")).
pos(eqo("journals/vldb/AbiteboulCM98","XTa-ElbpjZ8J")).
pos(eqo("journals/vldb/AnGSVKI02","kBzZ1GUoa1AJ")).
pos(eqo("journals/vldb/AtkinsonM95","MRgoVIYcARoJ")).
pos(eqo("journals/vldb/AtkinsonM95","rFdqdXVhLooJ")).
pos(eqo("journals/vldb/FahlR97","zXSCJ9LzZ8cJ")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/Halevy01","NXKx0V8rHQQJ")).
pos(eqo("journals/vldb/HalkidiNVV03","C_X4Frh2wHIJ")).
pos(eqo("journals/vldb/HansonCDERTX98","F6Ko8ZvWypUJ")).
pos(eqo("journals/vldb/HarderST99","KGyKFmRfspAJ")).
pos(eqo("journals/vldb/HelmerM03","lqAgqxpXpxMJ")).
pos(eqo("journals/vldb/HjaltasonS02","Z24x2fvsNQgJ")).
pos(eqo("journals/vldb/IshakbeyogluO98","O9A-15rmzOsJ")).
pos(eqo("journals/vldb/KrivokapicKG99","9YwFrtrNlaIJ")).
pos(eqo("journals/vldb/KrivokapicKG99","A8qZGxwlDiYJ")).
pos(eqo("journals/vldb/LandauST95","E8U_krxA1dsJ")).
pos(eqo("journals/vldb/LandauST95","SoejoqQZHg0J")).
pos(eqo("journals/vldb/LometS97","o4XsUOzknMUJ")).
pos(eqo("journals/vldb/LometS97","qjLiaKLJ6eQJ")).
pos(eqo("journals/vldb/MehtaD97","zppqMPNFTQIJ")).
pos(eqo("journals/vldb/PacittiS00","9ReaNbX2I-IJ")).
pos(eqo("journals/vldb/PacittiS00","ZmvL3_H6DqUJ")).
pos(eqo("journals/vldb/PapazogluK97","3k9vWWMJiWYJ")).
pos(eqo("journals/vldb/PapazogluK97","kFQl7LX8OQkJ")).
pos(eqo("journals/vldb/RahmB01","GJtc6TCE-hIJ")).
pos(eqo("journals/vldb/RahmB01","OmmFvfvPT6MJ")).
pos(eqo("journals/vldb/RahmB01","TBoS0CBe1vQJ")).
pos(eqo("journals/vldb/RahmB01","b9ikqvr7Bb4J")).
pos(eqo("journals/vldb/RahmB01","nXi88wdaXIkJ")).
pos(eqo("journals/vldb/RamamohanaraoH94","UiWvxN_y9SAJ")).
pos(eqo("journals/vldb/RamamrithamC96","xbpaZ5AHFV0J")).
pos(eqo("journals/vldb/RamamurthyDS03","DAlyofX710AJ")).
pos(eqo("journals/vldb/RamanRH00","CgiCp6N9XZQJ")).
pos(eqo("journals/vldb/Sarawagi01","Xx6kw0tCeQIJ")).
pos(eqo("journals/vldb/TempletonHMB95","RKNGp2gmOTUJ")).
pos(eqo("journals/vldb/TenienteO95","aC-8qspy24wJ")).
pos(eqo("journals/vldb/ZezulaSAR98","DM9hrpKpqmMJ")).
