neg(eqo("conf/sigmod/BerensonBGMOO95","J7Y20fYLGbcJ")).
neg(eqo("conf/sigmod/BerensonBGMOO95","vBYtmDEYeK0J")).
neg(eqo("conf/sigmod/BlakeleyD00","bkmF6EiB7UwJ")).
neg(eqo("conf/sigmod/BrinMUT97","CnTgirrsL3EJ")).
neg(eqo("conf/sigmod/DattaDRTV01","5N2k30IYlWoJ")).
neg(eqo("conf/sigmod/DeutschFS99","-KuX7UT0JIIJ")).
neg(eqo("conf/sigmod/DobraGGR02","LNsWSlqILosJ")).
neg(eqo("conf/sigmod/FernandezFKLS98","WwdBNahl3OMJ")).
neg(eqo("conf/sigmod/French95","Rp6i1uA3RYQJ")).
neg(eqo("conf/sigmod/GangulyGMS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988601%26type%3Dpdf")).
neg(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
neg(eqo("conf/sigmod/HaasH99","bsfsN1NtuOMJ")).
neg(eqo("conf/sigmod/Han96","oGKKTxiRq9kJ")).
neg(eqo("conf/sigmod/Hellerstein00","5FSG85HbUygJ")).
neg(eqo("conf/sigmod/Hellerstein00","pHHvswIOFfAJ")).
neg(eqo("conf/sigmod/HellersteinW02","nQvBo5KHITYJ")).
neg(eqo("conf/sigmod/ImielinskiV95","ay4Vn5YYDGkJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","0mk_QzaJKHEJ")).
neg(eqo("conf/sigmod/KaushikBNK02","Ymx00_iKLR4J")).
neg(eqo("conf/sigmod/KotidisR98","CpHJwU8o-BkJ")).
neg(eqo("conf/sigmod/LakshmananNHP99","94DIEgTTg_oJ")).
neg(eqo("conf/sigmod/LibkinMW96","vM_HYDYFeJ0J")).
neg(eqo("conf/sigmod/LoR96","KMdcT8EaBnUJ")).
neg(eqo("conf/sigmod/Mohan94","ZEh9UFMj3-EJ")).
neg(eqo("conf/sigmod/MumickP94","QEK2BsKiXBcJ")).
neg(eqo("conf/sigmod/PangCL94","7gJjI63FlyYJ")).
neg(eqo("conf/sigmod/PapakonstantinouV99","4IVlvcg-EycJ")).
neg(eqo("conf/sigmod/Ramanan02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335459%26type%3Dpdf%26dl%3DGUIDE%26dl%3DGUIDE%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SchusterW01","q7-5lG_wIKkJ")).
neg(eqo("conf/sigmod/SeshadriHPLRSSS96","KxwymZ2AGNQJ")).
neg(eqo("conf/sigmod/ShintaniK98","lkreWUl_euYJ")).
neg(eqo("conf/sigmod/SionAP03","YGzSkYiibuIJ")).
neg(eqo("conf/sigmod/Stonebraker98","D1sTvLkF_iQJ")).
neg(eqo("conf/sigmod/Stonebraker98","lasxhCBiPGYJ")).
neg(eqo("conf/sigmod/TomasicGS94","ytRfS_upf-0J")).
neg(eqo("conf/sigmod/YerneniLGU99","9dYkAfCK0mAJ")).
neg(eqo("conf/sigmod/YuMWL01","mX-oqtUEPZ4J")).
neg(eqo("conf/vldb/AbiteboulMRVW98","kuueK-yBQqMJ")).
neg(eqo("conf/vldb/AboulnagaAN01","OBbDFGQNEDQJ")).
neg(eqo("conf/vldb/AltinelF00","SXHPvzZDrFMJ")).
neg(eqo("conf/vldb/BergerBSW03","7rn7AHVs1YUJ")).
neg(eqo("conf/vldb/BernsteinPS99","JcHiZlbsts0J")).
neg(eqo("conf/vldb/BonczMK99","OcDmEcVhfEQJ")).
neg(eqo("conf/vldb/ChakrabartiGRS00","SHDQQrfJ3BMJ")).
neg(eqo("conf/vldb/ChaudhuriN97","XTa-ElbpjZ8J")).
neg(eqo("conf/vldb/CuiW01","BnM4bTYXkjEJ")).
neg(eqo("conf/vldb/EvangelidisLS95","EbGZKQPyH_4J")).
neg(eqo("conf/vldb/GantiLR00","gkbM-pRDcSwJ")).
neg(eqo("conf/vldb/GraefeBC98","khLFwTataoQJ")).
neg(eqo("conf/vldb/HasanM94","8cd64f0t0-EJ")).
neg(eqo("conf/vldb/HristidisP02","5k-GwvznWRUJ")).
neg(eqo("conf/vldb/KamelF94","wj0jfugMaCoJ")).
neg(eqo("conf/vldb/Korth95","DRXwLQfCaQgJ")).
neg(eqo("conf/vldb/LeslieJBY95","E02lExYdRYwJ")).
neg(eqo("conf/vldb/LevyMS94","8AHaTrvwsJoJ")).
neg(eqo("conf/vldb/Madnick95","zCraKEGNG4IJ")).
neg(eqo("conf/vldb/MarronL01","MqgSlx1jbPsJ")).
neg(eqo("conf/vldb/Mihalisin98","E9AsPVyCDlMJ")).
neg(eqo("conf/vldb/Mina98","3Ozte0ucNJAJ")).
neg(eqo("conf/vldb/NathDKGKS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D957113%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
neg(eqo("conf/vldb/NetzCBF00","mRIRFxOC8A8J")).
neg(eqo("conf/vldb/NieKH03","S-ct8QQhdXMJ")).
neg(eqo("conf/vldb/OuzzaniAB94","-Aw9zi3h104J")).
neg(eqo("conf/vldb/OzdenGHNSDGGW01","ZzYmVTAjsnQJ")).
neg(eqo("conf/vldb/PitouraC99","KlM6IrItVpcJ")).
neg(eqo("conf/vldb/PoosalaI97","NTlGMs3lqNEJ")).
neg(eqo("conf/vldb/SadriZZA01","H6XGSfr9v6MJ")).
neg(eqo("conf/vldb/SimonD95","RFEE_MNM8IUJ")).
neg(eqo("conf/vldb/SteinbrunnPMK95","ONxNYqv7q-UJ")).
neg(eqo("conf/vldb/Suciu96a","8bcTG9YsbskJ")).
neg(eqo("conf/vldb/Uhl02","BNrPCPu4qiMJ")).
neg(eqo("conf/vldb/VermeerA96","TtU32oCSnj4J")).
neg(eqo("conf/vldb/ViverosNR96","x3WHLHvq-SEJ")).
neg(eqo("conf/vldb/Wadler01","XhW_bzHOMSUJ")).
neg(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
neg(eqo("conf/vldb/ZhuS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/citation.cfm%3Fid%3D945721.945727%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637423%26dl%3Dportal%26dl%3DACM%26type%3Dissue%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AshishK97","ES6QyfgebIcJ")).
neg(eqo("journals/sigmod/AtkinsonDJPS96","JHVWab3P4zIJ")).
neg(eqo("journals/sigmod/BonifatiC00","pHHvswIOFfAJ")).
neg(eqo("journals/sigmod/CarmelMS01","_oTVh5WQeEsJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","1bcKeOSw50MJ")).
neg(eqo("journals/sigmod/ClementiniF00","z9MQwq7G3GYJ")).
neg(eqo("journals/sigmod/Danish98","miubKxLrikUJ")).
neg(eqo("journals/sigmod/Datta94","j4O-xhs1QAgJ")).
neg(eqo("journals/sigmod/Datta94","rq15XKzAPyMJ")).
neg(eqo("journals/sigmod/Franklin00","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Gaffney96","4b12cZc8QK4J")).
neg(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
neg(eqo("journals/sigmod/Jagadish00","bB0aoG0xvjAJ")).
neg(eqo("journals/sigmod/JukicNV03","eR43Urfx-hcJ")).
neg(eqo("journals/sigmod/Kim94","5VR8C6g8DNoJ")).
neg(eqo("journals/sigmod/Kosch02","RvZ7yr7IoYMJ")).
neg(eqo("journals/sigmod/Libkin99a","DYZlq4rntjwJ")).
neg(eqo("journals/sigmod/Liu03","ZsHfcZJwFQQJ")).
neg(eqo("journals/sigmod/Liu03c","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/Lomet01","fI5o4MfWwzIJ")).
neg(eqo("journals/sigmod/Qian96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RosenthalSMBTL95","Xo4KXwq9XIcJ")).
neg(eqo("journals/sigmod/Roussopoulos98","GZwDHAB2Eb8J")).
neg(eqo("journals/sigmod/VelACM01","LOXd8JPfhpwJ")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031579%26type%3Dpdf")).
neg(eqo("journals/tods/ChaudhuriS99","g6XLqjCRkFcJ")).
neg(eqo("journals/tods/IoannidisR95","0TNYLui0n0UJ")).
neg(eqo("journals/tods/IoannidisR95","4Y125m3-bsYJ")).
neg(eqo("journals/tods/PolyzoisG94","c38zjmKdgFkJ")).
neg(eqo("journals/vldb/AbadiCCCCLSTZ03","GDmbzrUbyzAJ")).
neg(eqo("journals/vldb/ChirkovaHS02","e0bl6GkMQzsJ")).
neg(eqo("journals/vldb/DeyBS96","JFFRMqra-ZcJ")).
neg(eqo("journals/vldb/FengYLH02","url:http://doi.wiley.com/10.1002/tl.66")).
neg(eqo("journals/vldb/FungKL03","J5HQj5rH5icJ")).
neg(eqo("journals/vldb/GibsonKR00","cVgF0jn9q6MJ")).
neg(eqo("journals/vldb/HarderST99","JM5T7TdjsGgJ")).
neg(eqo("journals/vldb/HarderST99","VKL01W7jM14J")).
neg(eqo("journals/vldb/IoannidisNSS97","0TNYLui0n0UJ")).
neg(eqo("journals/vldb/KellerB96","tVoqZpEEHv8J")).
neg(eqo("journals/vldb/TurkerG01","Kl3cf1fa64oJ")).
pos(eqo("conf/sigmod/Adelberg98","UT0h0HcwLyUJ")).
pos(eqo("conf/sigmod/BarbaraI94","XfvqAOX1qo4J")).
pos(eqo("conf/sigmod/BarbaraI94","kooQijVBMscJ")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/BumbulisB02","Ev27auQiecUJ")).
pos(eqo("conf/sigmod/CarinoKKB01","a9HFF_bwiH4J")).
pos(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","fDiU6std8e0J")).
pos(eqo("conf/sigmod/DarR94","TtV6gGLQ9NMJ")).
pos(eqo("conf/sigmod/FranklinZ98","5Cj9Wx8llkwJ")).
pos(eqo("conf/sigmod/FranklinZ98","K_qOxjIJWpQJ")).
pos(eqo("conf/sigmod/FreireHRRS02","YKkMxZntSUQJ")).
pos(eqo("conf/sigmod/FreireHRRS02","z8IglVK-XnEJ")).
pos(eqo("conf/sigmod/GebhardtJJ97","ks4Wxa8dHNIJ")).
pos(eqo("conf/sigmod/GodfreySE98","-H3tXntLhowJ")).
pos(eqo("conf/sigmod/GuptaS03","darWCYZjZHcJ")).
pos(eqo("conf/sigmod/LeeWMS01","OFXL5KsJiWcJ")).
pos(eqo("conf/sigmod/MerialdoAMMP00","Qq0WheHyVv8J")).
pos(eqo("conf/sigmod/MotakisZ97","8hMkXAIa8vEJ")).
pos(eqo("conf/sigmod/MotakisZ97","HPPJQPCzTEcJ")).
pos(eqo("conf/sigmod/NatsevRS99","OtJVavxuuYgJ")).
pos(eqo("conf/sigmod/NatsevRS99","Y3nejQSVKnUJ")).
pos(eqo("conf/sigmod/OlstonJW03","D1h_jOHVyA4J")).
pos(eqo("conf/sigmod/OlstonWL01","I_YprPVQ45QJ")).
pos(eqo("conf/sigmod/OoiTZGLLLNSWZ03","l78OeieL4ZsJ")).
pos(eqo("conf/sigmod/Pirahesh94","VG96hL8afvgJ")).
pos(eqo("conf/sigmod/PonnekantiK00","IddFq2o4ZsoJ")).
pos(eqo("conf/sigmod/RamaswamyRS00","VJIHPbki2uAJ")).
pos(eqo("conf/sigmod/SzalayGKT00","ZXB1xI2h-HkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","oPgy1SYoptgJ")).
pos(eqo("conf/sigmod/Vaskevitch94","cr7xWKidCnYJ")).
pos(eqo("conf/sigmod/WhiteD95","6SBwemr2zscJ")).
pos(eqo("conf/sigmod/WilschutFA95","Zdfxvjh6ca8J")).
pos(eqo("conf/sigmod/WolfsonSXZC99","vwdWTx0dk7QJ")).
pos(eqo("conf/sigmod/YanMHF01","8hRWaIVZ2ykJ")).
pos(eqo("conf/sigmod/YanMHF01","adm7QWgi-BAJ")).
pos(eqo("conf/sigmod/ZhuS03","J28mMeNrts4J")).
pos(eqo("conf/vldb/AbiteboulMRVW98","OqpwlRWdIMgJ")).
pos(eqo("conf/vldb/AmirKN01","dEwdHTZZYWYJ")).
pos(eqo("conf/vldb/AnciauxBP03","gYELZxhiJx8J")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/CasatiS00","yGYyg3tCPEcJ")).
pos(eqo("conf/vldb/CeriM03","hFPNVe44A04J")).
pos(eqo("conf/vldb/ChakrabartiDAR97","2LdUbNy0hWwJ")).
pos(eqo("conf/vldb/ChakravarthyKAK94","ZPoFYhxgaTMJ")).
pos(eqo("conf/vldb/ChristodoulakisTZ97","D0z0BDnbnFcJ")).
pos(eqo("conf/vldb/CiacciaPZ97","HQQsPfQN7q0J")).
pos(eqo("conf/vldb/DarFJST96","ThLxMqqAxjIJ")).
pos(eqo("conf/vldb/FernandezSCMS03","FjmyLJQ2TrYJ")).
pos(eqo("conf/vldb/GaoS03","BEpwgIQR6r4J")).
pos(eqo("conf/vldb/GarofalakisG02","Hz7TBeGZRz8J")).
pos(eqo("conf/vldb/GarofalakisG02","ImADir74KWIJ")).
pos(eqo("conf/vldb/GarofalakisG02","S6PWjHRFORYJ")).
pos(eqo("conf/vldb/GarofalakisOS97","dW_pRNemQfsJ")).
pos(eqo("conf/vldb/GehrkeRG98","hobnzQKRlK4J")).
pos(eqo("conf/vldb/GutierrezPST94","VUU_DceCRXAJ")).
pos(eqo("conf/vldb/HageJPST03","-JYQE7IPu_4J")).
pos(eqo("conf/vldb/HammadFAE03","vfCFumS9QtkJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/vldb/KamelF94","SuPC457J-a0J")).
pos(eqo("conf/vldb/KnorrN98","r8uYvAGT6swJ")).
pos(eqo("conf/vldb/KornMS02","mClzTQppJE4J")).
pos(eqo("conf/vldb/KornSFSP96","I8YNDqO9pg8J")).
pos(eqo("conf/vldb/KornSFSP96","QjbxSG6_-WIJ")).
pos(eqo("conf/vldb/Kornacker99","aOmma8tnFKIJ")).
pos(eqo("conf/vldb/LahiriSCMC01","MbzMAsLHlfEJ")).
pos(eqo("conf/vldb/LiM01","9vDm1Q41J8oJ")).
pos(eqo("conf/vldb/LiM01","yXnK2wPwLzkJ")).
pos(eqo("conf/vldb/LingLL00","lNvW4tc-B2EJ")).
pos(eqo("conf/vldb/Mihalisin98","FuzSLPzjrokJ")).
pos(eqo("conf/vldb/MiningGroup96","fGw7o-RlqlcJ")).
pos(eqo("conf/vldb/MorimotoIM97","wkD289iFVAIJ")).
pos(eqo("conf/vldb/OzdenBRS94","DZ9bjjJVU64J")).
pos(eqo("conf/vldb/OzdenBRS94","T4zyjvy9GdcJ")).
pos(eqo("conf/vldb/OzdenBRS94","vmqBhGBa8o0J")).
pos(eqo("conf/vldb/PapadiasMD98","7vbPCi-dbawJ")).
pos(eqo("conf/vldb/PapadiasMD98","_6JbypCpDqgJ")).
pos(eqo("conf/vldb/PoosalaI97","QIG8th9DHbQJ")).
pos(eqo("conf/vldb/RamamrithamABEGP00","jYGXFESkS-YJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","KureLsKbUXYJ")).
pos(eqo("conf/vldb/RysNS96","sRcMuuo3-BEJ")).
pos(eqo("conf/vldb/Sacks-Davis96","GkINzG_IffAJ")).
pos(eqo("conf/vldb/Sarawagi95","w9je55hjOlwJ")).
pos(eqo("conf/vldb/SayalCDS02","0acvmJtaI8QJ")).
pos(eqo("conf/vldb/ShengBDM02","ZQdRRjCxEX0J")).
pos(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","EPtaqugcCyMJ")).
pos(eqo("conf/vldb/TanSHCR01","hPcNG0tPwgIJ")).
pos(eqo("conf/vldb/WeberSB98","ZLYsIub53eoJ")).
pos(eqo("journals/sigmod/BergamaschiCV99","rIm9uDX6PHUJ")).
pos(eqo("journals/sigmod/Bestavros96","Q2y53UR0g6oJ")).
pos(eqo("journals/sigmod/Bohlen95","WnwPjh0a0twJ")).
pos(eqo("journals/sigmod/BonnetBDL03","aovCRhocZUcJ")).
pos(eqo("journals/sigmod/DiazJPa94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181555%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","GnjIUQVlZ0UJ")).
pos(eqo("journals/sigmod/DomenigD99","S6TMGRGUq1IJ")).
pos(eqo("journals/sigmod/EisenbergM01","GKUflKzgAVEJ")).
pos(eqo("journals/sigmod/EisenbergM01","lTNqBpBUA5sJ")).
pos(eqo("journals/sigmod/FowlerPNB99","2cbB8em2uAIJ")).
pos(eqo("journals/sigmod/FowlerPNB99","VgTAaMMYkvAJ")).
pos(eqo("journals/sigmod/FowlerPNB99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310060%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GatziuKBF98","C8tPNXRbNnIJ")).
pos(eqo("journals/sigmod/GolabO03","MTZdbBk3MQsJ")).
pos(eqo("journals/sigmod/GolabO03","jGb8C7wu8aYJ")).
pos(eqo("journals/sigmod/HalkidiBV02a","SFs0XOMPphIJ")).
pos(eqo("journals/sigmod/HanBP01","-OEJgpIAScMJ")).
pos(eqo("journals/sigmod/JaegerF95","oacFELqmw0cJ")).
pos(eqo("journals/sigmod/LabrinidisR00","Wcbvsi-QDtcJ")).
pos(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
pos(eqo("journals/sigmod/SureSS02","A-OWMulBkOoJ")).
pos(eqo("journals/sigmod/SureSS02","SQ-G-IKtM9cJ")).
pos(eqo("journals/sigmod/TsotrasK96","-FGfZQ_8TxIJ")).
pos(eqo("journals/sigmod/YuenCLL00","Ip82P4QfKyEJ")).
pos(eqo("journals/tods/AikenHW95","cHpmOFVpTi8J")).
pos(eqo("journals/tods/BaralisCP96","6Njy0-27w5cJ")).
pos(eqo("journals/tods/CasatiCPP99","bWa_AKkBbn8J")).
pos(eqo("journals/tods/KotidisR01","04utamFvle4J")).
pos(eqo("journals/tods/MamoulisP01","Rg8V7NSK9tMJ")).
pos(eqo("journals/vldb/CliftonGB95","YkIvdNOC64cJ")).
pos(eqo("journals/vldb/OzsuPSILM95","E02lExYdRYwJ")).
pos(eqo("journals/vldb/OzsuPSILM95","epUf9ogilogJ")).
