neg(eqo("conf/sigmod/AcharyaGPR99a","CfSSRKwHk6UJ")).
neg(eqo("conf/sigmod/AgichteinGV01","ihljCMaS2UsJ")).
neg(eqo("conf/sigmod/AgrawalS00","21ZWY0PM8YAJ")).
neg(eqo("conf/sigmod/AgrawalS00","OUdGxoZdSxAJ")).
neg(eqo("conf/sigmod/BaruFGHJPW95","dLubh8QRlKoJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","NRo_g9y0TV8J")).
neg(eqo("conf/sigmod/BerensonBGMOO95","-CQaLTpGJLQJ")).
neg(eqo("conf/sigmod/BersonGMJ94","LTX0u-XkO4IJ")).
neg(eqo("conf/sigmod/BressanGFJHKLMPQSS97","ZCere-V5xAEJ")).
neg(eqo("conf/sigmod/BrownCL96","HoeekG1E88EJ")).
neg(eqo("conf/sigmod/BunemanKTT02","CeQCT0Dqc08J")).
neg(eqo("conf/sigmod/CallanCD99","BDqVxxWQSqgJ")).
neg(eqo("conf/sigmod/CareyDNAGS97","mt8Q1YmVRkMJ")).
neg(eqo("conf/sigmod/Chan98","EdrkmGegTE8J")).
neg(eqo("conf/sigmod/Chan98","mUq22_ybEZcJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","gY652XXjHB8J")).
neg(eqo("conf/sigmod/ChenDLT00","B-u4advaVBkJ")).
neg(eqo("conf/sigmod/ChenRW02","05ShsIGjnKkJ")).
neg(eqo("conf/sigmod/ChenZCKR01","r1LUbgx-ZlwJ")).
neg(eqo("conf/sigmod/Cotton02","itP4yy9sLUUJ")).
neg(eqo("conf/sigmod/CuiOTS03","lAPeBMU4KPMJ")).
neg(eqo("conf/sigmod/FaloutsosL95","hvI_joppSEQJ")).
neg(eqo("conf/sigmod/GangulyGR03","t_ET-5_BlCYJ")).
neg(eqo("conf/sigmod/GarofalakisRRS99","dnkNb86izIQJ")).
neg(eqo("conf/sigmod/GehrkeKS01","QxtGOVsCF78J")).
neg(eqo("conf/sigmod/Gibson95","eT4MVK_YjDcJ")).
neg(eqo("conf/sigmod/GuhaRS98","Iom_VGC_DO8J")).
neg(eqo("conf/sigmod/Hammond99","QGBYlJ3tbJMJ")).
neg(eqo("conf/sigmod/Han96","znCz2ArvcNgJ")).
neg(eqo("conf/sigmod/HanPY00","2xwKDuA0DI8J")).
neg(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
neg(eqo("conf/sigmod/Jagadish94","GG8qabJI1w8J")).
neg(eqo("conf/sigmod/JarkeQBLMS99","sQxIAZeq1bgJ")).
neg(eqo("conf/sigmod/KalnisP01","rNu93TfKkd4J")).
neg(eqo("conf/sigmod/KriegelBKPS03","i0c65loyE60J")).
neg(eqo("conf/sigmod/LazaridisM01","fDWfHiQ6BR4J")).
neg(eqo("conf/sigmod/LiBCS00","bzILe3oHezgJ")).
neg(eqo("conf/sigmod/LibkinMW96","6Cdfxiuibd0J")).
neg(eqo("conf/sigmod/MohanN94","KvhuIhTTj_YJ")).
neg(eqo("conf/sigmod/Olson95","nSpF_Vz0yCUJ")).
neg(eqo("conf/sigmod/RoussopoulosKV95","QiQE9TAuXGoJ")).
neg(eqo("conf/sigmod/SchleimerWA03","nCRFjDfhOmcJ")).
neg(eqo("conf/sigmod/SlivinskasJS01","P1F_-y0o8EQJ")).
neg(eqo("conf/sigmod/SrikantA96","ZBuWjiVOE94J")).
neg(eqo("conf/sigmod/Team02","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DENV%26recid%3D8913258")).
neg(eqo("conf/sigmod/Team95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083797%26type%3Dpdf")).
neg(eqo("conf/sigmod/ThomasDM95","OVbo251Jji0J")).
neg(eqo("conf/sigmod/VriesMNK02","-IvY8_ki_psJ")).
neg(eqo("conf/sigmod/WangSSZZW00","iBEI8pUanCEJ")).
neg(eqo("conf/sigmod/Wu99","GdNAE4JOeN0J")).
neg(eqo("conf/sigmod/YangYW00","bzILe3oHezgJ")).
neg(eqo("conf/sigmod/YerneniLGU99","GWmqDua2TskJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","9Ft0BSj3FqMJ")).
neg(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637432%26coll%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/AnSVKIG01","vpHpX4gkv8QJ")).
neg(eqo("conf/vldb/AnanthakrishnaCG02","VwsS71_KQX8J")).
neg(eqo("conf/vldb/AshwinGG02","B3aOIHI2J4AJ")).
neg(eqo("conf/vldb/BerckenS96","k13xD0uym1oJ")).
neg(eqo("conf/vldb/Campbell99","uPCxgroIuysJ")).
neg(eqo("conf/vldb/CarinoJ98","dmFdqexjJskJ")).
neg(eqo("conf/vldb/ChenCFGJMTW99","Hq3W65us8dkJ")).
neg(eqo("conf/vldb/CherniackZ98","mH0vNFMcLxsJ")).
neg(eqo("conf/vldb/CosleyLP02","BTalXWt3faUJ")).
neg(eqo("conf/vldb/DeckerK03","es2kSNccUGMJ")).
neg(eqo("conf/vldb/FerrandinaMZFM95","QmkA__M9kqcJ")).
neg(eqo("conf/vldb/GarofalakisI97","aCvCz2wg854J")).
neg(eqo("conf/vldb/GottlobKP02","Pk09A5EmsOoJ")).
neg(eqo("conf/vldb/Gupta96","d8X29Wujn6QJ")).
neg(eqo("conf/vldb/ImielinskiB02","AI_fVKWNHyoJ")).
neg(eqo("conf/vldb/KamelF94","QC82YAGnU-kJ")).
neg(eqo("conf/vldb/KumarRRT99","RZ7sgm_D6JYJ")).
neg(eqo("conf/vldb/LimWV03","iM6vRWljKpAJ")).
neg(eqo("conf/vldb/MadhavanBR01","-f2FsG-EC9IJ")).
neg(eqo("conf/vldb/MadhavanBR01","wP_GYyvWXaQJ")).
neg(eqo("conf/vldb/MatiasVW00","56U_HeDJYggJ")).
neg(eqo("conf/vldb/MiloZ98","qXtUtp078_gJ")).
neg(eqo("conf/vldb/Mohan01","bfLZp1c7E1cJ")).
neg(eqo("conf/vldb/PossP03","ye64tXcJa3kJ")).
neg(eqo("conf/vldb/RahmM95","6kiYvzSHBvEJ")).
neg(eqo("conf/vldb/SavasereON95","y1hmJODjq7UJ")).
neg(eqo("conf/vldb/SevcikK96","n-7FAV7tJZYJ")).
neg(eqo("conf/vldb/Shenker03","5yETsE57mzgJ")).
neg(eqo("conf/vldb/SistlaYH94","QWD1EGMbTQYJ")).
neg(eqo("conf/vldb/StolteA02","hsRCWQE_sx0J")).
neg(eqo("conf/vldb/TanEO01","1A06w64wjvcJ")).
neg(eqo("conf/vldb/TanGO99","CcTZvs8xd2sJ")).
neg(eqo("conf/vldb/TsatalosSI94","KKWDSls8pkEJ")).
neg(eqo("conf/vldb/Tsur00","Jq7R6badO4cJ")).
neg(eqo("conf/vldb/VorugantiOU99","nlwMBvJt988J")).
neg(eqo("journals/sigmod/Aberer02","SQ-G-IKtM9cJ")).
neg(eqo("journals/sigmod/Aberer03c","gETqmiI3Y2cJ")).
neg(eqo("journals/sigmod/AbererCH02","fhTF0xc3Dh4J")).
neg(eqo("journals/sigmod/AbererCH02","ptuyWPJ6tf4J")).
neg(eqo("journals/sigmod/AbiteboulH95","kUA9e6YP8igJ")).
neg(eqo("journals/sigmod/AilamakiFFSV03","FfYkDJrlW4wJ")).
neg(eqo("journals/sigmod/AndlerHEMBE96","ZbMPvS5i_osJ")).
neg(eqo("journals/sigmod/Bernstein98","0KiQzAIFlJkJ")).
neg(eqo("journals/sigmod/BertinoEH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373684%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Bestavros96","GYKT_CbZTvAJ")).
neg(eqo("journals/sigmod/Bestavros96","HdBZt9clVdYJ")).
neg(eqo("journals/sigmod/BilirisP96","pVzuVkEC4jwJ")).
neg(eqo("journals/sigmod/BollKB98","J9jnNNuerS8J")).
neg(eqo("journals/sigmod/CeriFP99","CpA5QWyIRr4J")).
neg(eqo("journals/sigmod/Darwen96","S5ACWqUv95kJ")).
neg(eqo("journals/sigmod/Dogac98","O0IEHbFkD3oJ")).
neg(eqo("journals/sigmod/EisenbergM98a","GKUflKzgAVEJ")).
neg(eqo("journals/sigmod/Franklin98a","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/GerlaX03","B2rShDD99xwJ")).
neg(eqo("journals/sigmod/Han98","2kDtSxYI5DgJ")).
neg(eqo("journals/sigmod/Han98","yt7ARSTjaY0J")).
neg(eqo("journals/sigmod/HanBP01","D1RdxKP6_6YJ")).
neg(eqo("journals/sigmod/JaegerF95","mJrYUt7HaOEJ")).
neg(eqo("journals/sigmod/JainH94","sj_7DWnVQ5gJ")).
neg(eqo("journals/sigmod/KiyokiKH94","Rjb06zlxbLIJ")).
neg(eqo("journals/sigmod/Liu03c","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Lomet98","DC4Juhd354UJ")).
neg(eqo("journals/sigmod/MeltonMJKSZ01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373709%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/OrlandicLS02","ky-2yjNGtW8J")).
neg(eqo("journals/sigmod/Ozsoyoglu00","u0pFjzAcl78J")).
neg(eqo("journals/sigmod/Palpanas00","H1E3GuQcoUAJ")).
neg(eqo("journals/sigmod/PalpanasPKG03","fI5o4MfWwzIJ")).
neg(eqo("journals/sigmod/PitouraB95","Qq0WheHyVv8J")).
neg(eqo("journals/sigmod/PossasMCR00","LeZe18CtF9wJ")).
neg(eqo("journals/sigmod/Rosenthal98","ozA5VkHaGfQJ")).
neg(eqo("journals/sigmod/Roussopoulos98","GfjHZswtM0EJ")).
neg(eqo("journals/sigmod/Roussopoulos98","cL06_NviyTQJ")).
neg(eqo("journals/sigmod/Roussopoulos98","eEglmR7PqEQJ")).
neg(eqo("journals/sigmod/SayginVC01","sfQlMM3SXpAJ")).
neg(eqo("journals/sigmod/SpynsMJ02","LwZe_nTD__UJ")).
neg(eqo("journals/sigmod/Winslett01a","d5vsP1FGBC4J")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/citation.cfm%3Fid%3D507338.507358%26coll%3DGUIDE%26dl%3Dacm%26idx%3D984378%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/WinslettCDHZZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/BaekgaardM95","kNKWc8ETyvMJ")).
neg(eqo("journals/tods/Chomicki95","tBL3dkJe0jwJ")).
neg(eqo("journals/tods/GravanoGT99","KGyKFmRfspAJ")).
neg(eqo("journals/tods/HjaltasonS03","3mwWUz_ORNYJ")).
neg(eqo("journals/tods/LiC01","1dGvNxGa83MJ")).
neg(eqo("journals/tods/MehrotraRKS98","77mq-gn4LiAJ")).
neg(eqo("journals/vldb/Antoshenkov97","DK1HpJEO_mwJ")).
neg(eqo("journals/vldb/AntoshenkovZ96","Z0l7zr67jb0J")).
neg(eqo("journals/vldb/Baumann94","tT3xJO6uRtEJ")).
neg(eqo("journals/vldb/BernsteinPS00","T2fr86fsQcsJ")).
neg(eqo("journals/vldb/C95a","9jPrZSfTe2cJ")).
neg(eqo("journals/vldb/ChanFGR02","BJBeZ446Yc0J")).
neg(eqo("journals/vldb/Cobb97","2vfsC9OZoUYJ")).
neg(eqo("journals/vldb/FengYLH02","xGcM9AuhrBMJ")).
neg(eqo("journals/vldb/JagadishKNS00","W8O7pgTYGTYJ")).
neg(eqo("journals/vldb/KrivokapicKG99","S6TMGRGUq1IJ")).
neg(eqo("journals/vldb/MuckP97","umrivnVIoj0J")).
neg(eqo("journals/vldb/NanopoulosM02","Des-PSLVQi4J")).
neg(eqo("journals/vldb/NanopoulosM02","O05yYxasf6UJ")).
neg(eqo("journals/vldb/NguSHL01","aOmma8tnFKIJ")).
neg(eqo("journals/vldb/PeckhamMD95","UuvASZYBquEJ")).
neg(eqo("journals/vldb/RamamohanaraoH94","UiWvxN_y9SAJ")).
neg(eqo("journals/vldb/TorpJS00","WdS-meVyUgoJ")).
neg(eqo("journals/vldb/VerykiosME03","xNNBiNmxAqcJ")).
pos(eqo("conf/sigmod/AbiteboulCM95","DakOA4Ew-poJ")).
pos(eqo("conf/sigmod/AdyaGLM95","EP8u32KwMe4J")).
pos(eqo("conf/sigmod/AgrawalK03","ewoQO00BuFoJ")).
pos(eqo("conf/sigmod/Ahn94","5s6b10Hik30J")).
pos(eqo("conf/sigmod/Al-KhalifaYJ03","boJKiPCpIxkJ")).
pos(eqo("conf/sigmod/AndersonAF98","_EbKUPc1jYAJ")).
pos(eqo("conf/sigmod/AndersonBKW98","zabWzVjkZNYJ")).
pos(eqo("conf/sigmod/BaulierBGGHJKKMMNNRSSSWW99","wgRWDYY7q_8J")).
pos(eqo("conf/sigmod/BerensonBGMOO95","KpQrgYyji34J")).
pos(eqo("conf/sigmod/BerensonBGMOO95","w9IzqrZAa74J")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","cg01BqanXhUJ")).
pos(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
pos(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
pos(eqo("conf/sigmod/ChawatheG97","oHUiSrycKdgJ")).
pos(eqo("conf/sigmod/ChenCPPSTM00","Ab6MIDVDzhAJ")).
pos(eqo("conf/sigmod/ChenGM01","dyXJODAynUgJ")).
pos(eqo("conf/sigmod/CluetDSS98","DBPQai0tf1QJ")).
pos(eqo("conf/sigmod/CranorJSS03","b0ayPKpqTwsJ")).
pos(eqo("conf/sigmod/CuiOTS03","qx5oR09jmMwJ")).
pos(eqo("conf/sigmod/Dyreson03","UIDFB3gRjlUJ")).
pos(eqo("conf/sigmod/FaginKS03","tQZWeE_nsa0J")).
pos(eqo("conf/sigmod/FaloutsosL95","I0Kn3dzF4TgJ")).
pos(eqo("conf/sigmod/FaloutsosL95","roK09GarWdcJ")).
pos(eqo("conf/sigmod/FaloutsosL95","vbvO-dB6wiIJ")).
pos(eqo("conf/sigmod/FreireHRRS02","YKkMxZntSUQJ")).
pos(eqo("conf/sigmod/FreireHRRS02","z8IglVK-XnEJ")).
pos(eqo("conf/sigmod/FukudaMMT96","sOBRaiLLvZgJ")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GarofalakisRRS99","z7J4u1sJ52cJ")).
pos(eqo("conf/sigmod/GeneserethKD97","V1GBio3oeqMJ")).
pos(eqo("conf/sigmod/GrayHOS96","OLt5pqtQf3YJ")).
pos(eqo("conf/sigmod/Grust02","FYfyf-SjQNIJ")).
pos(eqo("conf/sigmod/GuhaRS98","nMzsE-ScW4MJ")).
pos(eqo("conf/sigmod/HellersteinHW97","IP5tZ_N2KXYJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","XpY2UPc6vP0J")).
pos(eqo("conf/sigmod/KanthRA02","RgDMwqhT30wJ")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","Hxnlcwm_RhMJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","uzpyy9XRpgYJ")).
pos(eqo("conf/sigmod/LakshmananPZ03a","pci2lDLAWzMJ")).
pos(eqo("conf/sigmod/LiuFP03","_97cTemKZnMJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/MankuRL99","LlPkfgH5fCIJ")).
pos(eqo("conf/sigmod/MankuRL99","X94gDE70Zn0J")).
pos(eqo("conf/sigmod/Martin94","ogow-Rtc3fEJ")).
pos(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
pos(eqo("conf/sigmod/MistryRSR01","r62IMncHe0IJ")).
pos(eqo("conf/sigmod/OhHP00","T91d5LI-xIwJ")).
pos(eqo("conf/sigmod/OhHP00","cFpgCsBTSBEJ")).
pos(eqo("conf/sigmod/RajagopalanML98","wO6VeeLIXAsJ")).
pos(eqo("conf/sigmod/RamakrishnanD98","url:http://portal.acm.org/citation.cfm%3Fid%3D276305.276361%26dl%3DGUIDE%26dl%3DACM%26idx%3D276305%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RundensteinerCLCZNJLW99","SADcQZhMqgEJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","Q1TF7XE9xkAJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","QZQt-pSMhYQJ")).
pos(eqo("conf/sigmod/VitterW99","1UFq52qqErUJ")).
pos(eqo("conf/sigmod/VriesMNK02","dVn0Led5JLAJ")).
pos(eqo("conf/sigmod/WhiteD94","qeHXdJ2x7eMJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","4dbCEDwsluQJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","vwdWTx0dk7QJ")).
pos(eqo("conf/vldb/Adler01","Tnuonq9Zi4cJ")).
pos(eqo("conf/vldb/BaralisW94","q-td2YANr18J")).
pos(eqo("conf/vldb/BelussiF95","A-Fi-3YSz0IJ")).
pos(eqo("conf/vldb/BouganimCDDGS99","Ult4nmnmJp8J")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChaudhuriGN03","sAYCyUcugbYJ")).
pos(eqo("conf/vldb/ChristopheBPV00","K9Qbh3haBCMJ")).
pos(eqo("conf/vldb/CochinwalaB94","Bp69wMYw9DAJ")).
pos(eqo("conf/vldb/DeWittKLPY94","AR8Phh8yvNEJ")).
pos(eqo("conf/vldb/DeWittKLPY94","ENb3jCRhOi8J")).
pos(eqo("conf/vldb/DeWittKLPY94","xcwQARsnK4gJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","OEpwAcnqlWwJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","XtFcz806WQEJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","Z8jYTylZtkEJ")).
pos(eqo("conf/vldb/GardarinST96","BBKhPPAqasIJ")).
pos(eqo("conf/vldb/GardarinST96","OHR5iQWPuyYJ")).
pos(eqo("conf/vldb/GardarinST96","RB2VKRwnXywJ")).
pos(eqo("conf/vldb/GilbertKMS01","9rDLhwM_4mYJ")).
pos(eqo("conf/vldb/GoldmanW97","Ye9iUyg5mL0J")).
pos(eqo("conf/vldb/GoldmanW97","l5GboAkBH1AJ")).
pos(eqo("conf/vldb/GuntzerBK00","3Gf3m5rkq0UJ")).
pos(eqo("conf/vldb/GuptaHQ95","dP1tJuCiK2cJ")).
pos(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
pos(eqo("conf/vldb/HaasKWY97","fsoE2pQM6G8J")).
pos(eqo("conf/vldb/HaasKWY97","t9e1f-xi0VsJ")).
pos(eqo("conf/vldb/JohnsonM98","cTZLUZ5_cfkJ")).
pos(eqo("conf/vldb/KamelF94","A7WoAzxOJ9YJ")).
pos(eqo("conf/vldb/KamelF94","Gr7nw0PAH1sJ")).
pos(eqo("conf/vldb/KamelF94","ONuqAb6sM3oJ")).
pos(eqo("conf/vldb/KamelF94","b1gS8kz09xcJ")).
pos(eqo("conf/vldb/KriegelPS00","VSQ0v1UlIvoJ")).
pos(eqo("conf/vldb/LiCHH97","DmGBKpaiyGEJ")).
pos(eqo("conf/vldb/Lindsay95","RIpWKrKho0MJ")).
pos(eqo("conf/vldb/MahnkeMS02","VhxIKKG8oWYJ")).
pos(eqo("conf/vldb/MiloZ98","UF-Z2VPtU6sJ")).
pos(eqo("conf/vldb/Mohan02","eyxIItge9MQJ")).
pos(eqo("conf/vldb/MohanBWSZ00","zCY0pFken7wJ")).
pos(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
pos(eqo("conf/vldb/NatsevCSLV01","e6dXyX0MKEIJ")).
pos(eqo("conf/vldb/PereiraFLS00","KAW0nLm2wVAJ")).
pos(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
pos(eqo("conf/vldb/RezendeS98","niRuvMkp4r4J")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/Shaw98","sZZVwXivu-kJ")).
pos(eqo("conf/vldb/ShuklaDNR96","Qdw5iM0aKwAJ")).
pos(eqo("conf/vldb/SistlaYLL95","n1ixxafAD_EJ")).
pos(eqo("conf/vldb/SrikantA95","OqO-ZxObnjgJ")).
pos(eqo("conf/vldb/SrikantA95","bibMn8zFnksJ")).
pos(eqo("conf/vldb/SrikantA95","kAi6HssDySgJ")).
pos(eqo("conf/vldb/SrikantA95","v7i1i5y_nHgJ")).
pos(eqo("conf/vldb/Sterling98","LlP2Fn3bzUMJ")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/VassalosP97","5DKaP73v7FQJ")).
pos(eqo("conf/vldb/VassalosP97","vPKoA4R_sU8J")).
pos(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
pos(eqo("conf/vldb/WhiteheadSM97","CiYPfP3-5_kJ")).
pos(eqo("conf/vldb/YanG95","baVAtfo4WCoJ")).
pos(eqo("conf/vldb/YangG01","LN1TWlAUa0wJ")).
pos(eqo("conf/vldb/YangG01","UZBoDXflaXoJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Bohlen95","43K14Y5xa0YJ")).
pos(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373708%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BunemanLSTW94","eKF1zVNKP0gJ")).
pos(eqo("journals/sigmod/Bussler02","Phcd3C1cfLcJ")).
pos(eqo("journals/sigmod/CrestaniG02","tyZxVraNgTsJ")).
pos(eqo("journals/sigmod/DiazJPa94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181555%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/EnglertGH95","JRXuKm3E_foJ")).
pos(eqo("journals/sigmod/EnglertGH95","WYE9fKutj70J")).
pos(eqo("journals/sigmod/HalkidiBV02","SFs0XOMPphIJ")).
pos(eqo("journals/sigmod/Hellerstein03","5FSG85HbUygJ")).
pos(eqo("journals/sigmod/Hellerstein03","pHHvswIOFfAJ")).
pos(eqo("journals/sigmod/MaximilienS02","hgjhR8PwNVwJ")).
pos(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
pos(eqo("journals/sigmod/ShethGJRSWW96","V3LZdq417gsJ")).
pos(eqo("journals/sigmod/Snodgrass03c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","64iWa-ZiPRcJ")).
pos(eqo("journals/sigmod/StolfoLCFE01","lvIPWxkN4YAJ")).
pos(eqo("journals/sigmod/SycaraKWL99","7OyvdUHeptMJ")).
pos(eqo("journals/sigmod/SycaraKWL99","YgouJdrCoZQJ")).
pos(eqo("journals/sigmod/WestmannKHM00","q9rwlM_FKqkJ")).
pos(eqo("journals/sigmod/Zhang95","f86VsMJZ9gAJ")).
pos(eqo("journals/tods/BaralisCP96","6Njy0-27w5cJ")).
pos(eqo("journals/tods/CastanoAFP98","tm7SUvdcOHYJ")).
pos(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
pos(eqo("journals/tods/FukudaMMT01","sOBRaiLLvZgJ")).
pos(eqo("journals/tods/IoannidisR95","TJDMWbCXMtgJ")).
pos(eqo("journals/tods/KonopnickiS98","BKUtItHoTX8J")).
pos(eqo("journals/tods/KossmannS00","XyQ6cXyNPN4J")).
pos(eqo("journals/tods/KotidisR01","04utamFvle4J")).
pos(eqo("journals/tods/LitwinN96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093386%26type%3Dpdf")).
pos(eqo("journals/tods/ScioreSR94","RJt8UiSzDTkJ")).
pos(eqo("journals/tods/Subrahmanian94","iD6ppXF5sx4J")).
pos(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
pos(eqo("journals/vldb/DerrMP94","SZbsK5kMevAJ")).
pos(eqo("journals/vldb/NguSHL01","djYvVVRYNTwJ")).
pos(eqo("journals/vldb/OzsuPSILM95","2Y6WYH71fO0J")).
pos(eqo("journals/vldb/ShethTP03","tReKvTMB7pcJ")).
pos(eqo("journals/vldb/YangW03","IJDg4R1pw6EJ")).
