neg(eqo("conf/sigmod/AbadiC02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373708%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/AbiteboulCM95","N14PBymOIIQJ")).
neg(eqo("conf/sigmod/AgrawalW00","YfRa7vdel-kJ")).
neg(eqo("conf/sigmod/Atkinson95","_TsHsqV0EOUJ")).
neg(eqo("conf/sigmod/Bierman03","sEB9vBW8yr8J")).
neg(eqo("conf/sigmod/BryanMCLG94","oWVdOJS4pDQJ")).
neg(eqo("conf/sigmod/CandanLLHA01","SipDBj3SOb4J")).
neg(eqo("conf/sigmod/Chaudhuri97","ktuEGK9MoYAJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","HuTZ23tc7Z8J")).
neg(eqo("conf/sigmod/ChaudhuriKN03","ClO4zHQ7RYsJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","IBg3vuolFUwJ")).
neg(eqo("conf/sigmod/Cohen98a","qfD_kxYt-dsJ")).
neg(eqo("conf/sigmod/CuiOTS03","MNmlxFx4l-8J")).
neg(eqo("conf/sigmod/DoRD99","rO4-yA3tlfoJ")).
neg(eqo("conf/sigmod/DogacHKOONDMAKE96","XE1zjDexb64J")).
neg(eqo("conf/sigmod/GangulyGR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GarofalakisG02","j6v2b9hN-R4J")).
neg(eqo("conf/sigmod/GionisGK01","BF1530nSQNsJ")).
neg(eqo("conf/sigmod/GrayHOS96","b201QeqnlNkJ")).
neg(eqo("conf/sigmod/GuhaRS98","Dux-7sONElwJ")).
neg(eqo("conf/sigmod/GuptaS03","iuP2JP2MOB0J")).
neg(eqo("conf/sigmod/Hellerstein94","dtYwk-vb8DUJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","FfeWtXdskZgJ")).
neg(eqo("conf/sigmod/JagadishJOT01","tVDUYwBqJAcJ")).
neg(eqo("conf/sigmod/Jamil99","f3XKQltCeL8J")).
neg(eqo("conf/sigmod/JonkerS95","IGP0aMosThEJ")).
neg(eqo("conf/sigmod/KrishnanVI96","FwWJsFY8wMwJ")).
neg(eqo("conf/sigmod/LamCKNH01","RzsJoG-0KaIJ")).
neg(eqo("conf/sigmod/Larson01","sV9JrR4NUW4J")).
neg(eqo("conf/sigmod/LeeWMS01","Fv4Tp1X7MqwJ")).
neg(eqo("conf/sigmod/NestorovAM98","DY6x1fDAy9EJ")).
neg(eqo("conf/sigmod/PapadiasTSE95","iww2iTLBdtEJ")).
neg(eqo("conf/sigmod/Perna95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D24823%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Rosenthal01","ZYnsLI6mz2cJ")).
neg(eqo("conf/sigmod/Rosenthal01","hXhqzGsA-rAJ")).
neg(eqo("conf/sigmod/Ross00","GbKwENZEG40J")).
neg(eqo("conf/sigmod/SeshadriP97","6YmlwN93as0J")).
neg(eqo("conf/sigmod/ShahC01","FSKgYYRr4UgJ")).
neg(eqo("conf/sigmod/Stonebraker03","D1sTvLkF_iQJ")).
neg(eqo("conf/sigmod/Stonebraker03","SyOHqrZQEeYJ")).
neg(eqo("conf/sigmod/TatarinovVBSSZ02","8XRiREu23GcJ")).
neg(eqo("conf/sigmod/TheobaldW02","w5_HkketH-wJ")).
neg(eqo("conf/sigmod/TomasicGS94","KUB7XvwH30AJ")).
neg(eqo("conf/sigmod/VriesMNK02","tnXqwH3BXW0J")).
neg(eqo("conf/sigmod/WodtkeWWDM97","Xcf3wrV7uAIJ")).
neg(eqo("conf/sigmod/ZhouLP99","zI3Z-hgIxJAJ")).
neg(eqo("conf/vldb/AgrawalK02","JclQFC-1s18J")).
neg(eqo("conf/vldb/AgrawalS94","BzZbvP23pRQJ")).
neg(eqo("conf/vldb/AlonsoHST97","QoMPfdkG6dsJ")).
neg(eqo("conf/vldb/Amer-YahiaCD98","lr7mG_jpvgsJ")).
neg(eqo("conf/vldb/BargaP95","Rp6i1uA3RYQJ")).
neg(eqo("conf/vldb/BernsteinD94","d7vY6vDq_7EJ")).
neg(eqo("conf/vldb/Bowker00","-jlufr76ww4J")).
neg(eqo("conf/vldb/BrinkhoffK94","EycNQ5gLEx4J")).
neg(eqo("conf/vldb/BrownCC94","8C5x73XZTQEJ")).
neg(eqo("conf/vldb/CarneyCZRCS03","JubkWSUFbbcJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","EVifEeUZwrQJ")).
neg(eqo("conf/vldb/ChakrabartiSST00","Jn1zTJX3EJMJ")).
neg(eqo("conf/vldb/ChanI99","8xz3v-RLsWQJ")).
neg(eqo("conf/vldb/ChaudhuriG99","i8bNEKiFihYJ")).
neg(eqo("conf/vldb/ChenRS95","JubkWSUFbbcJ")).
neg(eqo("conf/vldb/CosleyLP02","ubJ57pbu2KwJ")).
neg(eqo("conf/vldb/DattaDTVRF01","CXamH0oNwCAJ")).
neg(eqo("conf/vldb/DavisonG94","N5celzIzAKcJ")).
neg(eqo("conf/vldb/FaloutsosMS96","6gObqDQ3iwoJ")).
neg(eqo("conf/vldb/FangSGMU98","MdwCZg0RBHYJ")).
neg(eqo("conf/vldb/FlodinR95","WmtiDGY_BdoJ")).
neg(eqo("conf/vldb/FlodinR95","qXXDtlJmvwwJ")).
neg(eqo("conf/vldb/FlorescuKLP97","91X0HLAVjkEJ")).
neg(eqo("conf/vldb/GardarinGT95","kOSE6UVijD8J")).
neg(eqo("conf/vldb/GhoshPSH02","2dlOojuSNeIJ")).
neg(eqo("conf/vldb/HaasKWY97","ZQyBjtpbhvIJ")).
neg(eqo("conf/vldb/Huyn97","1dbUaQY8eEgJ")).
neg(eqo("conf/vldb/JermaineDO99","BPtDpGrQ4rAJ")).
neg(eqo("conf/vldb/KerstenWFKBC03","j4iZqFs00_AJ")).
neg(eqo("conf/vldb/KornMS02","eZq7OGI9DGEJ")).
neg(eqo("conf/vldb/Kornacker99","F4Hc2lTCVEkJ")).
neg(eqo("conf/vldb/KoudasIM00","w0kVbjS1psIJ")).
neg(eqo("conf/vldb/LinR98","uFEmZ1p0w20J")).
neg(eqo("conf/vldb/MartinC94","Ur6-XAMj3tIJ")).
neg(eqo("conf/vldb/MogiK95","39DBh8H18iEJ")).
neg(eqo("conf/vldb/Mohan01","C-yzbvoAg00J")).
neg(eqo("conf/vldb/Mohan02a","JX1Eda-ya_YJ")).
neg(eqo("conf/vldb/Mohan99","GR7rWnh1g6gJ")).
neg(eqo("conf/vldb/MorimotoIM97","3enylshvOl8J")).
neg(eqo("conf/vldb/PapadiasMD98","_6JbypCpDqgJ")).
neg(eqo("conf/vldb/PottingerB03","Q6pHDaV3sG4J")).
neg(eqo("conf/vldb/RamakrishnanR96","jDBzAX6KrDQJ")).
neg(eqo("conf/vldb/RothS97","LJgXl8u26jUJ")).
neg(eqo("conf/vldb/Selinger02","rgL1d5Q1cngJ")).
neg(eqo("conf/vldb/StohrMR00","7fCRAqLTNeUJ")).
neg(eqo("conf/vldb/Wang95","rrHY2sIxHd4J")).
neg(eqo("conf/vldb/WangZL99","ypHBb35DGMgJ")).
neg(eqo("conf/vldb/WeikumMHZ02","MZqMXLhtCXUJ")).
neg(eqo("conf/vldb/WeikumMHZ02","QGHfP3631csJ")).
neg(eqo("conf/vldb/YagoubFIV00","TDgQhn1OqbsJ")).
neg(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/citation.cfm%3Fid%3D603867.603869%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AbererCH02","xf1Sp2cCPb0J")).
neg(eqo("journals/sigmod/AilamakiG03","-mTrpy_n8PYJ")).
neg(eqo("journals/sigmod/Bohlen95","yZbJS0Cd6cAJ")).
neg(eqo("journals/sigmod/BollKB98","R1j3CdeOlwsJ")).
neg(eqo("journals/sigmod/CampbellEM03","e-nYGVGiikkJ")).
neg(eqo("journals/sigmod/CfP99","FnTHCghPm48J")).
neg(eqo("journals/sigmod/ChangASS98","-3MeHyntZNoJ")).
neg(eqo("journals/sigmod/Cingil02","LOXd8JPfhpwJ")).
neg(eqo("journals/sigmod/CruzKLSWY02","bDk2zsjQ1UcJ")).
neg(eqo("journals/sigmod/David03","UGSj0oWPm7MJ")).
neg(eqo("journals/sigmod/Dogac98","5NE7g6XtYVkJ")).
neg(eqo("journals/sigmod/Dogac98","url:http://www.springerlink.com/index/H58452Q268H44281.pdf")).
neg(eqo("journals/sigmod/Domingo-FerrerH98","hwPiaqFIpgQJ")).
neg(eqo("journals/sigmod/EisenbergM99","url:http://portal.acm.org/citation.cfm%3Fid%3D604264.604279%26coll%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/FlorescuLM98","O73WtNNtPvAJ")).
neg(eqo("journals/sigmod/Franklin97a","url:http://portal.acm.org/citation.cfm%3Fid%3D197445")).
neg(eqo("journals/sigmod/Franklin99","JHuJHooGoNUJ")).
neg(eqo("journals/sigmod/Franklin99a","3mwWUz_ORNYJ")).
neg(eqo("journals/sigmod/Franklin99b","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/GottlobKP03","O_11YxVvf8oJ")).
neg(eqo("journals/sigmod/HalkidiBV02","8KJ9XFv1ESAJ")).
neg(eqo("journals/sigmod/Hammer03","url:http://portal.acm.org/citation.cfm%3Fid%3D984488.984489%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Hampapur99","F7AdjoH_uTcJ")).
neg(eqo("journals/sigmod/HellersteinHM03","6ussAgzdL6oJ")).
neg(eqo("journals/sigmod/Kim99","url:http://portal.acm.org/citation.cfm%3Fid%3D122058%26dl%3Dportal%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Kosch02","mFVZqqx2yfMJ")).
neg(eqo("journals/sigmod/Libkin99","ItOlYY7ITt0J")).
neg(eqo("journals/sigmod/Liu02","LN80ltmD4mEJ")).
neg(eqo("journals/sigmod/Mani03","micx2kyGfKIJ")).
neg(eqo("journals/sigmod/OConnellW03","SeDkIL_DlRwJ")).
neg(eqo("journals/sigmod/Qian97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","kezAM71rts0J")).
neg(eqo("journals/sigmod/RiekertMW97","jnBo-gBTmAcJ")).
neg(eqo("journals/sigmod/Roussopoulos98","GfjHZswtM0EJ")).
neg(eqo("journals/sigmod/Segev94b","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Segev94b","url:http://doi.wiley.com/10.1002/ev.1658")).
neg(eqo("journals/sigmod/SilberschatzSU96","_ZsI_bVIJMwJ")).
neg(eqo("journals/sigmod/Snodgrass02b","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084832")).
neg(eqo("journals/sigmod/Suciu01","LEi_Rzm1iH0J")).
neg(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
neg(eqo("journals/sigmod/TsotrasJS98","Cg8CVYNv-lQJ")).
neg(eqo("journals/sigmod/Widom96","rVFh4WHFxoUJ")).
neg(eqo("journals/sigmod/X94","5xx69X1kg5MJ")).
neg(eqo("journals/tods/GoldmanL94","aD3jAQWyvJQJ")).
neg(eqo("journals/tods/GoldmanL94","h0U_L4ktUR8J")).
neg(eqo("journals/tods/Kim94","PcMqnvwNcBIJ")).
neg(eqo("journals/tods/StolboushkinT98","bWa_AKkBbn8J")).
neg(eqo("journals/vldb/BarbaraI95","aaQEdfkjWN8J")).
neg(eqo("journals/vldb/ChanFGR02","itZZmTVKRREJ")).
neg(eqo("journals/vldb/Ozsu03","url:http://www.springerlink.com/index/3G9E0YCGLRQFPN89.pdf")).
neg(eqo("journals/vldb/RamanRH00","HQuS5fNPqZYJ")).
pos(eqo("conf/sigmod/Adelberg98","ahVfYoqGq6gJ")).
pos(eqo("conf/sigmod/AdiBEY01","url:http://portal.acm.org/citation.cfm%3Fdoid%3D375663.375759")).
pos(eqo("conf/sigmod/BorkarDS01","8fu2bhk_i9EJ")).
pos(eqo("conf/sigmod/BorkarDS01","8zFEVer1rBUJ")).
pos(eqo("conf/sigmod/BreunigKNS00","4ZBs-U7sOk0J")).
pos(eqo("conf/sigmod/BrinDG95","QmhdqC_PIWsJ")).
pos(eqo("conf/sigmod/CandanLLHA01","E1oiXxVyfXwJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/CasatiS01","2_VG_VUkHH8J")).
pos(eqo("conf/sigmod/CasatiS01","7H9j9z0x_3UJ")).
pos(eqo("conf/sigmod/ChangG99","8Yt1Mba9-wQJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","99oqRZGWAYMJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","qGTxTpQXTDsJ")).
pos(eqo("conf/sigmod/ChawatheG97","5O88Bum19wAJ")).
pos(eqo("conf/sigmod/ChenR94","WJDiW8pl0OcJ")).
pos(eqo("conf/sigmod/ChenR94","hlQJGQCSurIJ")).
pos(eqo("conf/sigmod/DavisonG95","Ed8EH4p2vBMJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","CD_xefdItVkJ")).
pos(eqo("conf/sigmod/Faloutsos95","R0xUZUxSGmwJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","5fCkUaG8A-gJ")).
pos(eqo("conf/sigmod/FreedmanD95","2bao_dZfCuQJ")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/GoelI96","_Vn4nSui5UMJ")).
pos(eqo("conf/sigmod/GunopulosKTD00","VEDf7vb98i8J")).
pos(eqo("conf/sigmod/GuoSBS03","p_PDgjVRUS4J")).
pos(eqo("conf/sigmod/GuptaMR95","ELtcV7mOQDgJ")).
pos(eqo("conf/sigmod/HanKS97","yzL3Kfsz8scJ")).
pos(eqo("conf/sigmod/HanWDPW02","nwWpGh3Mx7MJ")).
pos(eqo("conf/sigmod/HellersteinA00","VlRO0WwUy3wJ")).
pos(eqo("conf/sigmod/HellersteinA00","ZuCOw9hYVU8J")).
pos(eqo("conf/sigmod/HsuLG00","kxIpDxLD46gJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","MdMdCC38z4UJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/KoudasS97","0u8r8MJWgKAJ")).
pos(eqo("conf/sigmod/LamCKNH01","8hdQohffF48J")).
pos(eqo("conf/sigmod/LiYVGPUV98","6jeHlSgjCskJ")).
pos(eqo("conf/sigmod/LiuFP03","5BY1upUmSTUJ")).
pos(eqo("conf/sigmod/LiuPBHPT00","q_o5zij9nCEJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","3tRtdT5VfDkJ")).
pos(eqo("conf/sigmod/MoleskyR95","mSR0bA8pIOwJ")).
pos(eqo("conf/sigmod/MoonWH02","rlfxeE4k2p4J")).
pos(eqo("conf/sigmod/MotakisZ97","e8OIK3dEo6EJ")).
pos(eqo("conf/sigmod/NguyenS96","T8llXFznCOwJ")).
pos(eqo("conf/sigmod/OlstonJW03","D1h_jOHVyA4J")).
pos(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","uveOdmVtqRMJ")).
pos(eqo("conf/sigmod/QunLO03","BnNNuVfklfcJ")).
pos(eqo("conf/sigmod/RafieiM97","IlN1Z8UC688J")).
pos(eqo("conf/sigmod/RafieiM97","N-kEDX56ek0J")).
pos(eqo("conf/sigmod/RafieiM97","UBACGF9cQ2UJ")).
pos(eqo("conf/sigmod/RajagopalanML98","HVP6eYl30IgJ")).
pos(eqo("conf/sigmod/RajagopalanML98","iUtn70TmoZIJ")).
pos(eqo("conf/sigmod/RajagopalanML98","wO6VeeLIXAsJ")).
pos(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375796%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RundensteinerCCSO00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335496%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","Rh68dFgQfS4J")).
pos(eqo("conf/sigmod/SeshadriLR94","G4N8qaBAG4kJ")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","gYWmOPwa7mwJ")).
pos(eqo("conf/sigmod/TomasicABKNR97","_fF5I-bkUSQJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","EkZGcIaXlkIJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","_Xj-7At79joJ")).
pos(eqo("conf/sigmod/WhiteD94","qeHXdJ2x7eMJ")).
pos(eqo("conf/sigmod/YangWYH02","xsaovu54vl4J")).
pos(eqo("conf/sigmod/ZhaoDNS98","6AK0GF7jAtsJ")).
pos(eqo("conf/vldb/AmmannJR95","x-H7BqZ0Hw8J")).
pos(eqo("conf/vldb/AnSVKIG01","HosSI1GtRY8J")).
pos(eqo("conf/vldb/AtzeniMM97","GOMaqU-ZlTIJ")).
pos(eqo("conf/vldb/AtzeniMM97","nzG3d6r0BmcJ")).
pos(eqo("conf/vldb/AtzeniMM97","sARbiNQPPWQJ")).
pos(eqo("conf/vldb/BaralisPT97","UUiSb7q5PHgJ")).
pos(eqo("conf/vldb/BettiniJWW02","ghIMekzCkMQJ")).
pos(eqo("conf/vldb/Brin95","srjTPThCwrwJ")).
pos(eqo("conf/vldb/Brin95","ytOUXklnAooJ")).
pos(eqo("conf/vldb/BrownG01","aJoPVuDNDSsJ")).
pos(eqo("conf/vldb/CareyD96","oynyctdLMcoJ")).
pos(eqo("conf/vldb/ChaudhuriS96","31oH64SXpRcJ")).
pos(eqo("conf/vldb/DattaDTVRF01","8_5A88ESaQ0J")).
pos(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
pos(eqo("conf/vldb/DyresonBJ99","FkPcMtplo18J")).
pos(eqo("conf/vldb/FrohnLU94","iarLqyQmZ7IJ")).
pos(eqo("conf/vldb/HageJPST03","-JYQE7IPu_4J")).
pos(eqo("conf/vldb/HageJPST03","6dAWUHYKqFUJ")).
pos(eqo("conf/vldb/HellersteinNP95","AC19Z_yOCTUJ")).
pos(eqo("conf/vldb/JagadishKMPSS98","TB8sxeXqHRQJ")).
pos(eqo("conf/vldb/JohnsonS94","FqxbaJQMigIJ")).
pos(eqo("conf/vldb/KiesslingK02","OuVZjeR64pMJ")).
pos(eqo("conf/vldb/KiesslingK02","Z8bBN2cO11UJ")).
pos(eqo("conf/vldb/KonigW99","6HMffRHCspAJ")).
pos(eqo("conf/vldb/KornSFSP96","xQU9GXs4k50J")).
pos(eqo("conf/vldb/LakshmananPZ03","tcnjvKELfs0J")).
pos(eqo("conf/vldb/LifantsevC02","gPvyDDUyrg4J")).
pos(eqo("conf/vldb/LohmanL02","jC-TppzLPuEJ")).
pos(eqo("conf/vldb/MadhavanH03","mu31RuCR_E4J")).
pos(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
pos(eqo("conf/vldb/MignetMAC01","VaDXNMtPZ4oJ")).
pos(eqo("conf/vldb/MiloZ98","UF-Z2VPtU6sJ")).
pos(eqo("conf/vldb/Mohan02","qbrkg2DRU3AJ")).
pos(eqo("conf/vldb/NaumannLF99","MEQuU1E4vdoJ")).
pos(eqo("conf/vldb/RiedelGF98","f2N_DxLirWIJ")).
pos(eqo("conf/vldb/RiedelGF98","xAph8JHK5WsJ")).
pos(eqo("conf/vldb/SavasereON95","c4m40zywvWsJ")).
pos(eqo("conf/vldb/SchmidtWKCMB02","ET_i3QwZryQJ")).
pos(eqo("conf/vldb/SizovGT03","UbQPXbPLMCAJ")).
pos(eqo("conf/vldb/SrikantA95","KIPDo6ym8BUJ")).
pos(eqo("conf/vldb/SrikantA95","rnfILQoQrBYJ")).
pos(eqo("conf/vldb/Sterling98","LlP2Fn3bzUMJ")).
pos(eqo("conf/vldb/VieiraM03","sUtdmV9XsIcJ")).
pos(eqo("conf/vldb/YanG95","lr_Kq9SZLY8J")).
pos(eqo("conf/vldb/ZengBNN01","MA7NWFIgTaoJ")).
pos(eqo("journals/sigmod/ACT-NET96","RzsJoG-0KaIJ")).
pos(eqo("journals/sigmod/BrunieK96","spI2g7jFHuYJ")).
pos(eqo("journals/sigmod/ClementLGMK97","J7Y20fYLGbcJ")).
pos(eqo("journals/sigmod/Datta94","3TVyZeq1-i4J")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","XE1zjDexb64J")).
pos(eqo("journals/sigmod/KoksalAD98","c2UQ3AM5_f8J")).
pos(eqo("journals/sigmod/Libkin99","V_FnUWKirh8J")).
pos(eqo("journals/sigmod/Lomet01","fI5o4MfWwzIJ")).
pos(eqo("journals/sigmod/McClatcheyV97","mbFxAqrWXbYJ")).
pos(eqo("journals/sigmod/McClatcheyV97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MedeirosP94","tnHDLJxMoQcJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","Fjyenk1hvFkJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","fSKoYnVJbwwJ")).
pos(eqo("journals/sigmod/Snodgrass02b","KENWBobILMwJ")).
pos(eqo("journals/sigmod/VetterliVS00","h7RBOvmQHhEJ")).
pos(eqo("journals/tods/Chen95","1px2xYEVMzwJ")).
pos(eqo("journals/tods/CliffordC94","9txS2mlA2DMJ")).
pos(eqo("journals/tods/EiterLLS01","tEZIquYevQoJ")).
pos(eqo("journals/tods/FraternaliT95","AH97X6QvKJ0J")).
pos(eqo("journals/tods/Galindo-LegariaR97","TQ8M8qOzJO8J")).
pos(eqo("journals/tods/LiuHD98","aYjE-ILUHaoJ")).
pos(eqo("journals/tods/WangBBJ97","I-yhgAxp9OQJ")).
pos(eqo("journals/tods/Wijsen99","_D3JPE9NgNgJ")).
pos(eqo("journals/vldb/AilamakiDH02","J9MeFW0vDJAJ")).
pos(eqo("journals/vldb/AtkinsonM95","MRgoVIYcARoJ")).
pos(eqo("journals/vldb/BunemanFS00","E_CQlx3K0W4J")).
pos(eqo("journals/vldb/ChanFGR02","LfS9Vr-FSZEJ")).
pos(eqo("journals/vldb/DesslochHMMT98","4D2HQE6fXXEJ")).
pos(eqo("journals/vldb/EvangelidisS97","5dnYlEMQTb0J")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/Guting94","NE_HjaA2eAAJ")).
pos(eqo("journals/vldb/KnorrNT00","SggrbO99AJgJ")).
pos(eqo("journals/vldb/ManegoldBK00","6GAoBRINv7kJ")).
pos(eqo("journals/vldb/ManegoldBK00","xWYu2JWiF_kJ")).
pos(eqo("journals/vldb/NanopoulosM02","icoWjIZ_6IIJ")).
pos(eqo("journals/vldb/RoySSSA98","JB684f38DiwJ")).
pos(eqo("journals/vldb/VaghaniRKSSLH94","B3E3_clrrrYJ")).
pos(eqo("journals/vldb/WhiteD95","qeHXdJ2x7eMJ")).
