neg(eqo("conf/sigmod/AcharyaAFZ95","zFDGosx1SRsJ")).
neg(eqo("conf/sigmod/AcharyaFZ97","-LRzTMJvt9UJ")).
neg(eqo("conf/sigmod/AfratiLU01","oWVdOJS4pDQJ")).
neg(eqo("conf/sigmod/AgrawalK03","url:http://portal.acm.org/citation.cfm%3Fid%3D98749%26coll%3Dportal%26dl%3DACM")).
neg(eqo("conf/sigmod/AgrawalS00","4MA-P43On8sJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","m5WstA_DsYAJ")).
neg(eqo("conf/sigmod/BarclaySG00","snWxBtd7kK8J")).
neg(eqo("conf/sigmod/BlakeleyD00","0ZG8Ug23ujYJ")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97a","zSM0goBgDdsJ")).
neg(eqo("conf/sigmod/BreitbartKRSS99","McorMeCrkHgJ")).
neg(eqo("conf/sigmod/BreitbartKRSS99","XV2lpkhWCsYJ")).
neg(eqo("conf/sigmod/BrownCL96","sP5LCmJNjo4J")).
neg(eqo("conf/sigmod/CeriFP98","zmL3wOjc7uAJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","TqXFdQBTW6kJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","U0w9W7YcsZwJ")).
neg(eqo("conf/sigmod/ChenGK01","GdNAE4JOeN0J")).
neg(eqo("conf/sigmod/CorralMTV00","YQQMvRraFBwJ")).
neg(eqo("conf/sigmod/FaloutsosSTT00","lJvmD13lHJIJ")).
neg(eqo("conf/sigmod/Fegaras98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181569%26type%3Dpdf")).
neg(eqo("conf/sigmod/FukudaMMT96","Y8UdbAPhYpUJ")).
neg(eqo("conf/sigmod/GarofalakisG02","oNPjyBZrURgJ")).
neg(eqo("conf/sigmod/GraySEBW94","v6NAtq0dkpMJ")).
neg(eqo("conf/sigmod/GuhaRS98","dV7p-cfTjUQJ")).
neg(eqo("conf/sigmod/HaasH01","mUiAtmLwLEMJ")).
neg(eqo("conf/sigmod/HanPY00","-hUVSdRv5UUJ")).
neg(eqo("conf/sigmod/HsiaoCY94","7VHYdQzMpUsJ")).
neg(eqo("conf/sigmod/HsiaoN00","3LBPVCRwCfwJ")).
neg(eqo("conf/sigmod/KeimK95","urATzh4SZEgJ")).
neg(eqo("conf/sigmod/KriegelMPS01","B1F0Sv4j0zUJ")).
neg(eqo("conf/sigmod/Kulkarni94","rPFgPOAANuQJ")).
neg(eqo("conf/sigmod/LometT99","qjLiaKLJ6eQJ")).
neg(eqo("conf/sigmod/MohanN94","wI6vEf7tAE0J")).
neg(eqo("conf/sigmod/Mylopoulos98","jsJJXMHfgxAJ")).
neg(eqo("conf/sigmod/OhHP00","s0v_n9_44AwJ")).
neg(eqo("conf/sigmod/RajagopalanML98","9GsZHpVf2_cJ")).
neg(eqo("conf/sigmod/SeshadriP97","url:http://portal.acm.org/citation.cfm%3Fid%3D304182.304226")).
neg(eqo("conf/sigmod/TrisoliniLN99","cFMtMf7bLzIJ")).
neg(eqo("conf/sigmod/VanceM96","bJuudDqUVEEJ")).
neg(eqo("conf/sigmod/ZhangNBB94","7U5nAHQRjaYJ")).
neg(eqo("conf/sigmod/ZhaoDN97","9OcrAEypDhMJ")).
neg(eqo("conf/sigmod/ZhaoDNS98","t4JoRwvUNZoJ")).
neg(eqo("conf/sigmod/ZhuS03","5kuf6fpDvWsJ")).
neg(eqo("conf/sigmod/ZuzartePMCLW03","OFGtGwUHhUQJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","msqzNc2ox4IJ")).
neg(eqo("conf/vldb/AgrawalK02","5GDHzHaNiscJ")).
neg(eqo("conf/vldb/BridgeJKLLM97","8SYZpKAeTwQJ")).
neg(eqo("conf/vldb/Brodie00","oIFrkS2rPrcJ")).
neg(eqo("conf/vldb/Campbell99","ZdyV7fpHadQJ")).
neg(eqo("conf/vldb/CareyHMW96","Kz20knx0y5oJ")).
neg(eqo("conf/vldb/CarinoOBS99","cyt2N1lgyxwJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","Projg8pBjYIJ")).
neg(eqo("conf/vldb/ChaudhuriW00","99oqRZGWAYMJ")).
neg(eqo("conf/vldb/ChienVZTZ02","jn3pvb3hRzwJ")).
neg(eqo("conf/vldb/FlodinR95","4h5A_XPegUMJ")).
neg(eqo("conf/vldb/FlorescuKLP97","k87JcS1cpX4J")).
neg(eqo("conf/vldb/Fox02","ipk43Quye-kJ")).
neg(eqo("conf/vldb/GarofalakisG02","rDEKkswGx7gJ")).
neg(eqo("conf/vldb/GoodmanRS94","2MEHXBATx9EJ")).
neg(eqo("conf/vldb/Greco98","1mnQdiXPWY8J")).
neg(eqo("conf/vldb/GuptaHQ95","xkK5sMFddeUJ")).
neg(eqo("conf/vldb/HammelP02","T6FlOGz83SMJ")).
neg(eqo("conf/vldb/HasanM95","JW7LRQwx_goJ")).
neg(eqo("conf/vldb/HinneburgLH03","yie13VF7cV0J")).
neg(eqo("conf/vldb/HuangJR97","P7GUGC5bz7wJ")).
neg(eqo("conf/vldb/Huyn01","NsmcRO_yEMEJ")).
neg(eqo("conf/vldb/Keogh02","9OYLimeDdj0J")).
neg(eqo("conf/vldb/KornMZ03","11D-BwNUPQkJ")).
neg(eqo("conf/vldb/Korth95","9JhejaSsZPoJ")).
neg(eqo("conf/vldb/KoschBBHHLRT01","url:http://www.vldb.org/conf/2003/papers/S32P01.pdf")).
neg(eqo("conf/vldb/KossmannRR02","Ma-V_tUPwQwJ")).
neg(eqo("conf/vldb/KraftSRM03","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/LabrinidisR03","94m93uP4GM4J")).
neg(eqo("conf/vldb/LeeLWS97","M9YKyXJNGBgJ")).
neg(eqo("conf/vldb/LeeLWS97","szlqyCesMpgJ")).
neg(eqo("conf/vldb/LevyMS94","bXRF6rASxhgJ")).
neg(eqo("conf/vldb/LevyMS94","dxqRZbQruVwJ")).
neg(eqo("conf/vldb/LiPHCAAT03","f_akBX2UdlYJ")).
neg(eqo("conf/vldb/LohmanL02","kW0RhYOnStYJ")).
neg(eqo("conf/vldb/LuL00","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/NgH94","h95306-8rjEJ")).
neg(eqo("conf/vldb/Novaretti01","tZtnFoH5lY0J")).
neg(eqo("conf/vldb/PanRAMOHAMV02","F9Fe5NfpK6MJ")).
neg(eqo("conf/vldb/Sarawagi00","E02lExYdRYwJ")).
neg(eqo("conf/vldb/Sarawagi99","BJ0pr7FqzzoJ")).
neg(eqo("conf/vldb/SeligmanBNSW95","T6a86CQCuHoJ")).
neg(eqo("conf/vldb/TorloneA03","8j5i7YJQnNAJ")).
neg(eqo("conf/vldb/VassalosP97","9MlAuURfKhYJ")).
neg(eqo("conf/vldb/YangLH03","_EDhM4bq8b0J")).
neg(eqo("conf/vldb/YuSLJ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/ZhuS02","iGKoS8f6vTIJ")).
neg(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ArenasKKKMM03","biVrK7MrU4QJ")).
neg(eqo("journals/sigmod/BawaCCDGGKMSSVY03","Kr9mD9JyqdkJ")).
neg(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
neg(eqo("journals/sigmod/CalvaneseGLV03","xaiONMf39PwJ")).
neg(eqo("journals/sigmod/DoanPSB97","fdM1W8iEk_YJ")).
neg(eqo("journals/sigmod/Dogac02","YG9Js5mJbV0J")).
neg(eqo("journals/sigmod/Dogac98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D765219%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/DogacDKOONEHAKKM95","GnjIUQVlZ0UJ")).
neg(eqo("journals/sigmod/DunhamH95a","abEzjLwwX4IJ")).
neg(eqo("journals/sigmod/Franklin99b","GbKwENZEG40J")).
neg(eqo("journals/sigmod/Franklin99b","K_qOxjIJWpQJ")).
neg(eqo("journals/sigmod/Franklin99b","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/FreemanG96","1rEaoZ9xuC4J")).
neg(eqo("journals/sigmod/GamacheS95","zzP3Eju66twJ")).
neg(eqo("journals/sigmod/Gardels97","oMOJqD6Nl5YJ")).
neg(eqo("journals/sigmod/Giorgini03","uA036pMuqw8J")).
neg(eqo("journals/sigmod/Hainaut03","fnt5G2r4MaYJ")).
neg(eqo("journals/sigmod/Han98","rsI0sKgJzlsJ")).
neg(eqo("journals/sigmod/Jagadish00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Jarke95","l5DIpKYgodkJ")).
neg(eqo("journals/sigmod/KennedyMB96","9mwyzsFG89wJ")).
neg(eqo("journals/sigmod/Kim94","5aSVaxWgGUMJ")).
neg(eqo("journals/sigmod/KuanL99","-tZe06rxiUIJ")).
neg(eqo("journals/sigmod/Kumar03","vLsj0AQ4ee4J")).
neg(eqo("journals/sigmod/LinP96","eLENYy7eMqIJ")).
neg(eqo("journals/sigmod/LinP96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D333608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Liu01a","_cil6uzFNtsJ")).
neg(eqo("journals/sigmod/Liu02","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/MarchiLPT03","9dgFU6XaLrwJ")).
neg(eqo("journals/sigmod/RosenthalS99","url:http://portal.acm.org/citation.cfm%3Fid%3D277953")).
neg(eqo("journals/sigmod/RossGN03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","On_0bnZ5smoJ")).
neg(eqo("journals/sigmod/Sidell96","4Uf5sjXgwhoJ")).
neg(eqo("journals/sigmod/SlivinskasJS02","xTPSs2k_pUIJ")).
neg(eqo("journals/sigmod/Snodgrass01a","VwZQmafqkE0J")).
neg(eqo("journals/sigmod/Snodgrass02b","vUONDuuNNCQJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom94","oUisL_YUScYJ")).
neg(eqo("journals/sigmod/Wong95","YrR7nYIYctMJ")).
neg(eqo("journals/sigmod/Wong95","otyPKNE679oJ")).
neg(eqo("journals/sigmod/YanG95","NNWQbYNLLrgJ")).
neg(eqo("journals/tods/ChomickiTB01","zc9i-P-OfU4J")).
neg(eqo("journals/tods/LechtenborgerV03","zC15-wrsmswJ")).
neg(eqo("journals/tods/StoreyCDGS97","NL_8pNIYC-0J")).
neg(eqo("journals/vldb/AtluriJY03","347oyb_b7DAJ")).
neg(eqo("journals/vldb/AtluriJY03","url:http://portal.acm.org/citation.cfm%3Fid%3D599610.599633")).
neg(eqo("journals/vldb/AtluriJY03","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
neg(eqo("journals/vldb/FiletoLPAM03","VWbm4EeeFNMJ")).
neg(eqo("journals/vldb/Guting94","0augooXyPa0J")).
neg(eqo("journals/vldb/HansonCDERTX98","94AZQoNhGrwJ")).
neg(eqo("journals/vldb/KraissW98","url:http://www.springerlink.com/index/TX55N550P815VR75.pdf")).
neg(eqo("journals/vldb/Li03","_tAMP_olJ-wJ")).
neg(eqo("journals/vldb/NybergBCGL95","W34JQQUUM84J")).
pos(eqo("conf/sigmod/AcharyaAFZ95","h2z51QPXcSkJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","9OEjtHuRUzsJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","C221gFS5VVoJ")).
pos(eqo("conf/sigmod/AdaliBSS98","69JsZwNpla0J")).
pos(eqo("conf/sigmod/AdaliSS99","Cbwq3JSxrSAJ")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","L7XmLpQLXBIJ")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","YAkpVC1qgaIJ")).
pos(eqo("conf/sigmod/ArasuG03","zN8ngmWNDlgJ")).
pos(eqo("conf/sigmod/BarbaraI94","7N0H3ra1FFsJ")).
pos(eqo("conf/sigmod/BohmA96","978pJCGhaGoJ")).
pos(eqo("conf/sigmod/BohmBKK01","C4XcBh6anhAJ")).
pos(eqo("conf/sigmod/BrinDG95","7mNCkZ7D-R8J")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","qk4kfo7BXvUJ")).
pos(eqo("conf/sigmod/BuchmannDZH95","QzpePwRoku8J")).
pos(eqo("conf/sigmod/Bussler01","UYIeOe280OwJ")).
pos(eqo("conf/sigmod/DoanDH01","Lv0bggWzgeoJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","ek26aiEheesJ")).
pos(eqo("conf/sigmod/Galhardas00","QhUFQCApL8wJ")).
pos(eqo("conf/sigmod/GodfreyGXZ01","LNnvt5TpBhkJ")).
pos(eqo("conf/sigmod/GriffinL95","RuYYq5xDgNYJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","9KBHBWVwKZsJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","RcmGrB81X-4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","VdUSfNE_8i8J")).
pos(eqo("conf/sigmod/JagadishJOT01","OM7n6h8R8CoJ")).
pos(eqo("conf/sigmod/JagatheesanR03","fobv5DPqKUcJ")).
pos(eqo("conf/sigmod/LeeKOTM00","C8RLbWKCgicJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","9Ho84Ho6xuIJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","izDXhqRW9AYJ")).
pos(eqo("conf/sigmod/LuoKMPWLN02","zQfzn1t6Xq8J")).
pos(eqo("conf/sigmod/NestorovAM98","5icRoG_Vmc0J")).
pos(eqo("conf/sigmod/NestorovAM98","XP7FEaxDfuAJ")).
pos(eqo("conf/sigmod/OlstonJW03","fW0CpIqoV7QJ")).
pos(eqo("conf/sigmod/RamakrishnanD98","url:http://portal.acm.org/citation.cfm%3Fid%3D276305.276361%26dl%3DGUIDE%26dl%3DACM%26idx%3D276305%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RamaswamyK95","g9Y0KAu_UHQJ")).
pos(eqo("conf/sigmod/ReinwaldP98","QAjOGW-ffQIJ")).
pos(eqo("conf/sigmod/Sahuguet01","xb63RaGQYmYJ")).
pos(eqo("conf/sigmod/SismanisDRK02","seSeL2gsCJoJ")).
pos(eqo("conf/sigmod/ThomasDM95","1W3ieFgA2dUJ")).
pos(eqo("conf/sigmod/TsueiPK97","DpQGq6n1jnkJ")).
pos(eqo("conf/sigmod/YangM97","TUQ51ASLNI0J")).
pos(eqo("conf/sigmod/ZhangDWEMPMDR03","gWslyEjd3BYJ")).
pos(eqo("conf/sigmod/ZhaoDN97","b-Va1c3t13gJ")).
pos(eqo("conf/sigmod/ZhouLP99","0OwKmPjQpd0J")).
pos(eqo("conf/sigmod/ZhugeGHW95","KjM8fKqooDQJ")).
pos(eqo("conf/vldb/AbiteboulBBCCDMMP03","fANcvlGA8WAJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","E4fU9kpfXQsJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","OMzQ1Ah1IVQJ")).
pos(eqo("conf/vldb/AgrawalK02","NDKJPUgy_K4J")).
pos(eqo("conf/vldb/AgrawalK02","qCvXLXmB6J8J")).
pos(eqo("conf/vldb/AgrawalLSS95","C0bXQSqGnF4J")).
pos(eqo("conf/vldb/AgrawalLSS95","iJc7iMSuwowJ")).
pos(eqo("conf/vldb/BargaP95","3CDeAczlaSUJ")).
pos(eqo("conf/vldb/BargaP95","Rp6i1uA3RYQJ")).
pos(eqo("conf/vldb/BaumgartnerFG01a","GGyAHg9kwysJ")).
pos(eqo("conf/vldb/BernsteinPS99","JcHiZlbsts0J")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("conf/vldb/ChakrabartiSD98","oBDL7axDwG4J")).
pos(eqo("conf/vldb/ChatziantoniouR97","Xx-pSjq7Mv8J")).
pos(eqo("conf/vldb/ChaudhuriS96","hk2lzbke6hQJ")).
pos(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
pos(eqo("conf/vldb/ChenDZ03","cCpHMzAXRnsJ")).
pos(eqo("conf/vldb/ChoenniV00","R1j3CdeOlwsJ")).
pos(eqo("conf/vldb/CooperSFHS01","PAfEdPwJ8tgJ")).
pos(eqo("conf/vldb/DarFJST96","ThLxMqqAxjIJ")).
pos(eqo("conf/vldb/DongHLPW01","eOTkoLDux4wJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","Ag5ikOm9dB0J")).
pos(eqo("conf/vldb/GarofalakisIO98","i7AX4VpJJbYJ")).
pos(eqo("conf/vldb/GarofalakisRS99","q87jrCR_GqQJ")).
pos(eqo("conf/vldb/GilbertKMS01","9rDLhwM_4mYJ")).
pos(eqo("conf/vldb/GionisIM99","a1_mvYBrjyAJ")).
pos(eqo("conf/vldb/HanF95","jQaZA3mmmakJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
pos(eqo("conf/vldb/ImielinskiB02","IQ_MbfJGh0kJ")).
pos(eqo("conf/vldb/KahveciS01","i6KmypFd39AJ")).
pos(eqo("conf/vldb/Keogh02","rKIsQpbRiM0J")).
pos(eqo("conf/vldb/KerstenWFKBC03","Ub6YwssjyiYJ")).
pos(eqo("conf/vldb/KoudasS03","F0VufxHFRP8J")).
pos(eqo("conf/vldb/KumarKA97","8bLd-1l1at4J")).
pos(eqo("conf/vldb/LevyRO96","lrocSfnfPrMJ")).
pos(eqo("conf/vldb/ManegoldBK00","JgdpgBpMDr4J")).
pos(eqo("conf/vldb/ManegoldBK00","sZmrat79cF0J")).
pos(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
pos(eqo("conf/vldb/MarronL01","MiMYGwqrGY8J")).
pos(eqo("conf/vldb/MillerHH00","KTp2S_xbXfYJ")).
pos(eqo("conf/vldb/MillerHH00","kfTc_TsqiP8J")).
pos(eqo("conf/vldb/Moerkotte02","jiGdThcReckJ")).
pos(eqo("conf/vldb/Ogawa96","my4BalOLmAsJ")).
pos(eqo("conf/vldb/OlstonW00","R_hYW6eIUuYJ")).
pos(eqo("conf/vldb/OoiGT98","LJdSx1Di81MJ")).
pos(eqo("conf/vldb/OoiYTJ01","T8BPorXB1VsJ")).
pos(eqo("conf/vldb/PirotteZMY94","8s-SP8sAvQAJ")).
pos(eqo("conf/vldb/PossP03","DYZlq4rntjwJ")).
pos(eqo("conf/vldb/RamamurthyDS02","DAlyofX710AJ")).
pos(eqo("conf/vldb/Ramanan03","QCJEyGp-iZcJ")).
pos(eqo("conf/vldb/Ramanan03","ruVmVa1bhoUJ")).
pos(eqo("conf/vldb/RiedelGF98","xAph8JHK5WsJ")).
pos(eqo("conf/vldb/SarawagiS96","GzBmx-QUxFYJ")).
pos(eqo("conf/vldb/ShuklaDNR96","gTSn7nMr9dQJ")).
pos(eqo("conf/vldb/ShuklaDNR96","vnezjPI8jYIJ")).
pos(eqo("conf/vldb/SrikantA95","K1nbpKn1IbsJ")).
pos(eqo("conf/vldb/StillgerLMK01","R43ssyRp674J")).
pos(eqo("conf/vldb/StohrMR00","7fCRAqLTNeUJ")).
pos(eqo("conf/vldb/Tygar98","Q8cPIOWKZZ4J")).
pos(eqo("conf/vldb/Vaskevitch95","s6Ax0WdZp6IJ")).
pos(eqo("journals/sigmod/AbererCDDHPS03","hBrgosYDi3oJ")).
pos(eqo("journals/sigmod/ArpinarD00","YQQMvRraFBwJ")).
pos(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
pos(eqo("journals/sigmod/BuchnerM98","dkWnTbi9xnEJ")).
pos(eqo("journals/sigmod/CampbellEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777002%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChaudhuriD97","6YgzNu3UQqMJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","P-TOW5Z1snMJ")).
pos(eqo("journals/sigmod/David03","vhUs7wTpUOoJ")).
pos(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
pos(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
pos(eqo("journals/sigmod/JaegerF95","oacFELqmw0cJ")).
pos(eqo("journals/sigmod/JainH94","iQMUP3fkvo4J")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/KuokFW98","3oLpUbHFATsJ")).
pos(eqo("journals/sigmod/MeltonE02","IqEw9ssJ2QAJ")).
pos(eqo("journals/sigmod/NascimentoSP03","G3QWq2T08SEJ")).
pos(eqo("journals/sigmod/PapianiWDN99","aU7XlTpoxRgJ")).
pos(eqo("journals/sigmod/RoantreeMH99","JJK6WGPyubgJ")).
pos(eqo("journals/sigmod/Snodgrass98a","CGvD6Du5kaoJ")).
pos(eqo("journals/sigmod/TomasicS97","-MNdDpWC-sgJ")).
pos(eqo("journals/sigmod/VelACM01","LseDURw3BXMJ")).
pos(eqo("journals/sigmod/VenkatraoP95","qk3LVAuS2SUJ")).
pos(eqo("journals/tods/BrightHP94","m9DBN5PHWDAJ")).
pos(eqo("journals/tods/CaldersNW02","DSl0gT8EgR0J")).
pos(eqo("journals/tods/Chen95","1px2xYEVMzwJ")).
pos(eqo("journals/tods/DattaVCK99","3BbftjVsIEIJ")).
pos(eqo("journals/tods/EiterLLS01","lTwQVB8E7SIJ")).
pos(eqo("journals/tods/Hellerstein98","q8m4M7OxSSAJ")).
pos(eqo("journals/tods/RaschidL96","rUpu2pcFa8cJ")).
pos(eqo("journals/tods/Revesz98","dr8s9hbwjR0J")).
pos(eqo("journals/tods/SistlaWYS98","3mLKQfhVh3cJ")).
pos(eqo("journals/tods/Subrahmanian94","YAkzY3hCPxQJ")).
pos(eqo("journals/tods/Subrahmanian94","iD6ppXF5sx4J")).
pos(eqo("journals/tods/WijesekeraJPH03","oui-frSWZCAJ")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/vldb/BernsteinPS00","08d5th2jiqcJ")).
pos(eqo("journals/vldb/DeyBS96","q8IL-AZTmcgJ")).
pos(eqo("journals/vldb/FengYLH02","Uxh3R2hfBOAJ")).
pos(eqo("journals/vldb/Guting94","2HXoDqKjpXYJ")).
pos(eqo("journals/vldb/Guting94","NE_HjaA2eAAJ")).
pos(eqo("journals/vldb/Guting94","TruJ2Gi7fiQJ")).
pos(eqo("journals/vldb/LiCHH01","Tw8-f4saqb0J")).
pos(eqo("journals/vldb/TenienteO95","G9tB3j46MoEJ")).
