neg(eqo("conf/sigmod/AbiteboulCM95","3k9vWWMJiWYJ")).
neg(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
neg(eqo("conf/sigmod/AcharyaGP00","WGWZ2cNZW2YJ")).
neg(eqo("conf/sigmod/AdelbergGK95","fNDX0gaFmB0J")).
neg(eqo("conf/sigmod/AdelbergGW97","6RhdcFYAZW4J")).
neg(eqo("conf/sigmod/Agarwal96","5Pb8x5tWIZ8J")).
neg(eqo("conf/sigmod/Aggarwal02","2p2A5_qGf5cJ")).
neg(eqo("conf/sigmod/Aggarwal03","4GzKkSWGohYJ")).
neg(eqo("conf/sigmod/Aggarwal03","jzwiskpRLOUJ")).
neg(eqo("conf/sigmod/AgrawalCN01","1eCp1f8DhasJ")).
neg(eqo("conf/sigmod/AgrawalCN01","yAod353y_40J")).
neg(eqo("conf/sigmod/AgrawalGGR98","8hRWaIVZ2ykJ")).
neg(eqo("conf/sigmod/AshleyFHLNP95","oulaZpEWkMQJ")).
neg(eqo("conf/sigmod/BabuGR01","aUhrABodKtcJ")).
neg(eqo("conf/sigmod/BarbaraI94","7N0H3ra1FFsJ")).
neg(eqo("conf/sigmod/BaruFGHJPW95","zO0DfwHqXKUJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","7hQge_9oGMMJ")).
neg(eqo("conf/sigmod/BerchtoldK97","2EJhvKyW8AoJ")).
neg(eqo("conf/sigmod/BersonGM95","vwdWTx0dk7QJ")).
neg(eqo("conf/sigmod/Bierman03","gyPwIEnKIC0J")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","SvL_dU_R8msJ")).
neg(eqo("conf/sigmod/Brown99","ESge0RjQQ40J")).
neg(eqo("conf/sigmod/CallanCD99","d_YS_CCYWt8J")).
neg(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","5wcgt7bNx7YJ")).
neg(eqo("conf/sigmod/CareyDNAGS97","f86VsMJZ9gAJ")).
neg(eqo("conf/sigmod/CareyMN97","Y_8HItm7yCkJ")).
neg(eqo("conf/sigmod/ChakrabartiDI98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107512%26type%3Dpdf")).
neg(eqo("conf/sigmod/ChangG99","8Yt1Mba9-wQJ")).
neg(eqo("conf/sigmod/Chaudhuri97","FNqBp7hox0kJ")).
neg(eqo("conf/sigmod/Chaudhuri97","OFGtGwUHhUQJ")).
neg(eqo("conf/sigmod/Chaudhuri97","QkyXMep2bWsJ")).
neg(eqo("conf/sigmod/ChaudhuriD97","D7w6TQwatE0J")).
neg(eqo("conf/sigmod/ChaudhuriD97","Ody9SrSpEtIJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","zO0DfwHqXKUJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","U09WdB3GIK4J")).
neg(eqo("conf/sigmod/ChaudhuriGN02","g6XLqjCRkFcJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","_OLNvAeDNyYJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","gY652XXjHB8J")).
neg(eqo("conf/sigmod/ChaudhuriN98","xxkUtjfGpvAJ")).
neg(eqo("conf/sigmod/ChawatheG97","ATI3rg3kUs4J")).
neg(eqo("conf/sigmod/ChenCPPSTM00","ANAQ2j41ts0J")).
neg(eqo("conf/sigmod/ChenCPPSTM00","MTZdbBk3MQsJ")).
neg(eqo("conf/sigmod/ChenGM01","P8SQPINQRHQJ")).
neg(eqo("conf/sigmod/ChenGM01","jDVeecM54GkJ")).
neg(eqo("conf/sigmod/ChenGMV02","kZFfJieudW4J")).
neg(eqo("conf/sigmod/ChenJDTW00","EWzSBh-jV3IJ")).
neg(eqo("conf/sigmod/CherniackZ98","7DFhNMAE13QJ")).
neg(eqo("conf/sigmod/ChristophidesCS00","R7tBLAw0O3wJ")).
neg(eqo("conf/sigmod/ChristophidesCS00","UEaXoXn3DicJ")).
neg(eqo("conf/sigmod/Cohen98","VzQQwoEdG1sJ")).
neg(eqo("conf/sigmod/Cohen98a","TS5KYOz9RFcJ")).
neg(eqo("conf/sigmod/CohenM03","ReOfuE1ytx4J")).
neg(eqo("conf/sigmod/ColbyKLMR97","_ROCNqI9z1wJ")).
neg(eqo("conf/sigmod/ColeG94","FOYb_Kd8j8sJ")).
neg(eqo("conf/sigmod/CorralMTV00","bMHHuMc66JAJ")).
neg(eqo("conf/sigmod/CrescenziMM02","pI0WktymowwJ")).
neg(eqo("conf/sigmod/DanielsDDEHJJLSSS94","darWCYZjZHcJ")).
neg(eqo("conf/sigmod/DarEGP98","5icRoG_Vmc0J")).
neg(eqo("conf/sigmod/DattaDRTV01","qK-N8yVLSWUJ")).
neg(eqo("conf/sigmod/DattaDTVSR02","QqNeEQfjMMoJ")).
neg(eqo("conf/sigmod/DattaDTVSR02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D984537%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Deutsch95","-MNdDpWC-sgJ")).
neg(eqo("conf/sigmod/DobraGGR02","K3tAbYt1W90J")).
neg(eqo("conf/sigmod/DobraGGR02","PXJQPLyXOk8J")).
neg(eqo("conf/sigmod/DobraGGR02","qf4764Q6M6YJ")).
neg(eqo("conf/sigmod/Dyreson03","3nxl8d4c0t4J")).
neg(eqo("conf/sigmod/FabretJLPRS01","rVxCHd6e1oYJ")).
neg(eqo("conf/sigmod/FaginKS03","dOY1djmoy04J")).
neg(eqo("conf/sigmod/FaloutsosSTT00","igM_dVQLhtEJ")).
neg(eqo("conf/sigmod/FegarasM95","tzUxfh8dD9sJ")).
neg(eqo("conf/sigmod/Fernandez94","ZM65itnp_E4J")).
neg(eqo("conf/sigmod/FernandezFKLS98","W3H34LBUMtoJ")).
neg(eqo("conf/sigmod/FernandezMS01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776999%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/FranklinZ98","a5kWURMYg38J")).
neg(eqo("conf/sigmod/FukudaMMT96a","WOCgxlV_LgoJ")).
neg(eqo("conf/sigmod/FukudaMMT96a","eGARASwVBrUJ")).
neg(eqo("conf/sigmod/Gal00","DKEdwRMEvDgJ")).
neg(eqo("conf/sigmod/Galindo-LegariaJ01","Fdl8VLTOlJ8J")).
neg(eqo("conf/sigmod/Gibson95","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0177775CI")).
neg(eqo("conf/sigmod/GionisGK01","PsXOoGuK0ogJ")).
neg(eqo("conf/sigmod/GoelI96","HA3wM_i-y3YJ")).
neg(eqo("conf/sigmod/GoelI96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245888%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GravanoCGP97","PsoYENGEh9cJ")).
neg(eqo("conf/sigmod/GravanoGT94","ilCT5UFnHxgJ")).
neg(eqo("conf/sigmod/GreenwaldK01","2u0CxnsZaT4J")).
neg(eqo("conf/sigmod/GrossmanQ94","MeBkhUbAbEEJ")).
neg(eqo("conf/sigmod/GuptaLM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369289%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GuptaS03","Chp-3UwMgTQJ")).
neg(eqo("conf/sigmod/HaasH99","8t-lBAluiAcJ")).
neg(eqo("conf/sigmod/HacigumusILM02","NMgExE-JRD0J")).
neg(eqo("conf/sigmod/HacigumusILM02","o2vqik6QeLYJ")).
neg(eqo("conf/sigmod/HanFHCC94","vn7mB1e7YdIJ")).
neg(eqo("conf/sigmod/HanFWCZK96","5h6Jx1j7US4J")).
neg(eqo("conf/sigmod/HarinarayanRU96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564792%26type%3Dpdf")).
neg(eqo("conf/sigmod/Hellerstein00","DJIdLJUbKikJ")).
neg(eqo("conf/sigmod/HellersteinN96","3UPcL18cS9wJ")).
neg(eqo("conf/sigmod/HernandezMHYHT01","iM5fj7fRHdsJ")).
neg(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
neg(eqo("conf/sigmod/Hope95","ppGZ8x9cUcMJ")).
neg(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
neg(eqo("conf/sigmod/HsuLG00","kxIpDxLD46gJ")).
neg(eqo("conf/sigmod/IvesFFLW99","HtxGbMkTXdsJ")).
neg(eqo("conf/sigmod/Jamil99","yafpq21LfmQJ")).
neg(eqo("conf/sigmod/JohnsonD03","tBnhQPI6yJoJ")).
neg(eqo("conf/sigmod/Kennamer98","zJCsqgMH5bUJ")).
neg(eqo("conf/sigmod/Kim94","5aSVaxWgGUMJ")).
neg(eqo("conf/sigmod/KimCK01","bi68bm0miqkJ")).
neg(eqo("conf/sigmod/Kohler99","OGd3xxeSZy4J")).
neg(eqo("conf/sigmod/KornJF97","4Qn3gnSp-acJ")).
neg(eqo("conf/sigmod/KriegelBKPS03","7JN4hf25wasJ")).
neg(eqo("conf/sigmod/KrishnanVI96","8tFA4ENYqKQJ")).
neg(eqo("conf/sigmod/KrishnanVI96","cMR7qEn25m8J")).
neg(eqo("conf/sigmod/KrollW94","AYtrcxExrbkJ")).
neg(eqo("conf/sigmod/LabrinidisR00","rKbwxobcJZYJ")).
neg(eqo("conf/sigmod/LabrinidisR00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LakshmananPZ03a","pci2lDLAWzMJ")).
neg(eqo("conf/sigmod/LangS01","kG86HB6N1xEJ")).
neg(eqo("conf/sigmod/Larson01","KZG37M76v5sJ")).
neg(eqo("conf/sigmod/Lassettre98","WlSXiMaxGlQJ")).
neg(eqo("conf/sigmod/Lassettre98","ulDBbXl-6Q4J")).
neg(eqo("conf/sigmod/LaursenOP94","E6Z68tQL1BsJ")).
neg(eqo("conf/sigmod/LeeKC99","qcmyX5t_p6oJ")).
neg(eqo("conf/sigmod/LehnerSPC00","hxWB8uQMCdgJ")).
neg(eqo("conf/sigmod/Levine95","WqdCiTToYxUJ")).
neg(eqo("conf/sigmod/LiBCS00","hnAG1QBlnbwJ")).
neg(eqo("conf/sigmod/Lomet00","1YpHQXqkPv4J")).
neg(eqo("conf/sigmod/Lomet00","P7GUGC5bz7wJ")).
neg(eqo("conf/sigmod/Lomet00","aGas8XEqu0wJ")).
neg(eqo("conf/sigmod/LometT03","kLnJCd1otuUJ")).
neg(eqo("conf/sigmod/MaddenFHH03","I0rYiR1aUHYJ")).
neg(eqo("conf/sigmod/MarklL02","SUDBjtdzV1MJ")).
neg(eqo("conf/sigmod/Meseck01","hWiIngXs5I0J")).
neg(eqo("conf/sigmod/Mohan94","bfLZp1c7E1cJ")).
neg(eqo("conf/sigmod/Mohan94","ulDehVmIgfAJ")).
neg(eqo("conf/sigmod/Mohan96","iXVERLO3KkQJ")).
neg(eqo("conf/sigmod/MumickQM97","8m_6OmUvYJwJ")).
neg(eqo("conf/sigmod/MumickQM97","c_n0wQe1FhAJ")).
neg(eqo("conf/sigmod/Nori00","sA7TNyWDhPAJ")).
neg(eqo("conf/sigmod/OhHP00","YMluKoJrxMcJ")).
neg(eqo("conf/sigmod/OlstonWACELSS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/OlstonWL01","HvCLHmeoPxIJ")).
neg(eqo("conf/sigmod/PaparizosACJLNPSWWY03","W1IcM8IUwAEJ")).
neg(eqo("conf/sigmod/PatelD96","3UPcL18cS9wJ")).
neg(eqo("conf/sigmod/PatelD96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107506%26type%3Dpdf")).
neg(eqo("conf/sigmod/PoosalaIHS96","W_sqUstx5iAJ")).
neg(eqo("conf/sigmod/QunLO03","bV8_CDuW2gMJ")).
neg(eqo("conf/sigmod/RamanH02","6uP3E_WEkCAJ")).
neg(eqo("conf/sigmod/Ramanan02","b2r9OZJJ4sgJ")).
neg(eqo("conf/sigmod/RaoR98","6MtRlhEClPEJ")).
neg(eqo("conf/sigmod/ReinwaldP98","ZqFPwDkLN7oJ")).
neg(eqo("conf/sigmod/ReinwaldP98","y_H9p9Lqj3IJ")).
neg(eqo("conf/sigmod/ReveszCKLLW00","qxShx7aNiuEJ")).
neg(eqo("conf/sigmod/Rosenthal01","Py5otnOcc8cJ")).
neg(eqo("conf/sigmod/SagonasSW94a","tYXzABUZYxQJ")).
neg(eqo("conf/sigmod/Sahuguet01","pK5bydjeZFIJ")).
neg(eqo("conf/sigmod/SchusterW01","Bn1MQ6uuG9QJ")).
neg(eqo("conf/sigmod/Seshadri99","pH6zRbG6CZUJ")).
neg(eqo("conf/sigmod/SinghTW94","uAQ-tJ0j4nkJ")).
neg(eqo("conf/sigmod/SrikantA96","USBXg-_E4FgJ")).
neg(eqo("conf/sigmod/Stonebraker03","-IsKQcTBYi4J")).
neg(eqo("conf/sigmod/Stonebraker03","ycyOGNNmFUkJ")).
neg(eqo("conf/sigmod/Tajima96","oPXBu1tWLpQJ")).
neg(eqo("conf/sigmod/Team95","NVS_rDpScp0J")).
neg(eqo("conf/sigmod/ThomasDM95","1W3ieFgA2dUJ")).
neg(eqo("conf/sigmod/Toyama98","fn4O_OpXLAwJ")).
neg(eqo("conf/sigmod/VanceM96","CMMaMlYwgPkJ")).
neg(eqo("conf/sigmod/VanceM96","tRjx0-XhQ3QJ")).
neg(eqo("conf/sigmod/Vaskevitch94","yzbCsw2erkcJ")).
neg(eqo("conf/sigmod/VingralekBW94","cjRXXRA1geoJ")).
neg(eqo("conf/sigmod/VossenW99","f86VsMJZ9gAJ")).
neg(eqo("conf/sigmod/WangJLY03","EQsWWZdE45wJ")).
neg(eqo("conf/sigmod/WangSSZZW00","gfkyZS9B1ZMJ")).
neg(eqo("conf/sigmod/WangWYY02","DRp1iFn7znkJ")).
neg(eqo("conf/sigmod/Weininger02","6HlejBWokfkJ")).
neg(eqo("conf/sigmod/WhiteD94","S6PWjHRFORYJ")).
neg(eqo("conf/sigmod/WitkowskiBBDFGSS03","Fir6kPDNKpQJ")).
neg(eqo("conf/sigmod/WoelkBJOTU95","E8ICGS9Be2QJ")).
neg(eqo("conf/sigmod/Wu99","QlGIRp4zaeMJ")).
neg(eqo("conf/sigmod/ZhangNBB94","VRF1chV0HOIJ")).
neg(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
neg(eqo("conf/sigmod/ZhouR02","1B0JvMSHkLgJ")).
neg(eqo("conf/vldb/AbiteboulACEMM99","TD1X4Bo-eYsJ")).
neg(eqo("conf/vldb/AbiteboulBMMW02","6OfJSMB4vOcJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","t0Asg9xms9YJ")).
neg(eqo("conf/vldb/AboulnagaAN01","p4IXF74uW6oJ")).
neg(eqo("conf/vldb/AcharyaFZ96","gJPWbysKyQgJ")).
neg(eqo("conf/vldb/AcharyaFZ96","rO4-yA3tlfoJ")).
neg(eqo("conf/vldb/Adler01","TJyp_PuBAWoJ")).
neg(eqo("conf/vldb/AggarwalHWY03","79NKRYC6cAoJ")).
neg(eqo("conf/vldb/AgrawalCN00","YQBFozC2x18J")).
neg(eqo("conf/vldb/AgrawalK02","JV8yJIRlYcUJ")).
neg(eqo("conf/vldb/AgrawalKSX02","HWFatrRxFRAJ")).
neg(eqo("conf/vldb/AgrawalLSS95","xkvXoYlg2-cJ")).
neg(eqo("conf/vldb/AgrawalPWZ95","2vzhAz4Yll4J")).
neg(eqo("conf/vldb/AgrawalSX01","aHFDLZ_L21kJ")).
neg(eqo("conf/vldb/AgrawalSX02","RiQ-W5K0n6YJ")).
neg(eqo("conf/vldb/AgrawalSX02","e7eYvS2bm7gJ")).
neg(eqo("conf/vldb/AltinelF00","W1di9S0fUsEJ")).
neg(eqo("conf/vldb/AnkerstBKS98","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/BamfordBKM98","LF2aUSIWko4J")).
neg(eqo("conf/vldb/BaralisPT97","bbdecz2VGtIJ")).
neg(eqo("conf/vldb/BaulierBGJGKKMMNNRSS98","zUk4Gy_sOy0J")).
neg(eqo("conf/vldb/BergerBSW03","b6wj1DwIXVEJ")).
neg(eqo("conf/vldb/BernsteinHJRW00","-Jy9LL4TzYYJ")).
neg(eqo("conf/vldb/BernsteinHJRW00","m1xqrODaQAoJ")).
neg(eqo("conf/vldb/BettiniJWW02","ZbMPvS5i_osJ")).
neg(eqo("conf/vldb/BohannonLRSSS97","IROKbaAxI6QJ")).
neg(eqo("conf/vldb/BohannonLRSSS97","ISHUERiNswsJ")).
neg(eqo("conf/vldb/BouganimNPW03","5oXuo8dJ6qAJ")).
neg(eqo("conf/vldb/Bowker00","rgL1d5Q1cngJ")).
neg(eqo("conf/vldb/BratsbergH01","0s6troo_Y1AJ")).
neg(eqo("conf/vldb/Brin95","V4kgrR0eURgJ")).
neg(eqo("conf/vldb/Brodie03","deEJ1JsF8RwJ")).
neg(eqo("conf/vldb/Carey00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/CarinoJ98","caykA_O2cRoJ")).
neg(eqo("conf/vldb/CasatiDGS01","BoSfRzB01ZQJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","jNb5aoFeS7wJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
neg(eqo("conf/vldb/ChakravarthyKAK94","5Ng-bLUNAsQJ")).
neg(eqo("conf/vldb/ChangG97","xW3AafG2xKgJ")).
neg(eqo("conf/vldb/ChavdaW97","UuvASZYBquEJ")).
neg(eqo("conf/vldb/ChawatheCY94","62I9Xi01u_8J")).
neg(eqo("conf/vldb/ChenL03","tZBIZ9ZHdTkJ")).
neg(eqo("conf/vldb/CooperSFHS01","YczJAmfzmzsJ")).
neg(eqo("conf/vldb/DarmontS99","4wHLoLkVcS8J")).
neg(eqo("conf/vldb/DarmontS99","qv9JuA63NQMJ")).
neg(eqo("conf/vldb/DattaRT99","gckQTLQjsj8J")).
neg(eqo("conf/vldb/Dayal99","LxniCtne0QYJ")).
neg(eqo("conf/vldb/DayalHL01","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/DayalHL01","url:http://portal.acm.org/citation.cfm%3Fid%3D38713")).
neg(eqo("conf/vldb/DeWittKLPY94","cehAAlTq4s8J")).
neg(eqo("conf/vldb/DiaoLCT00","N0gea3ZN-0cJ")).
neg(eqo("conf/vldb/DidriksenGD95","0TNJ5d1tfkEJ")).
neg(eqo("conf/vldb/DonjerkovicR99","Eq1w4LPv_igJ")).
neg(eqo("conf/vldb/DonjerkovicR99","TofLoTnu3bgJ")).
neg(eqo("conf/vldb/EicklerKK97","U74KQC_5LGgJ")).
neg(eqo("conf/vldb/FernandezSCMS03","Nz8zwxjBoyYJ")).
neg(eqo("conf/vldb/FerrandinaMZFM95","9rofzgQ6HtcJ")).
neg(eqo("conf/vldb/Fox02","KB9ZbekVNzoJ")).
neg(eqo("conf/vldb/FrohnLU94","v6NAtq0dkpMJ")).
neg(eqo("conf/vldb/GalanisWJD03","kKwsIC5HmsUJ")).
neg(eqo("conf/vldb/GalhardasFSSS01","xVPrGgGcBgUJ")).
neg(eqo("conf/vldb/Garcia-MolinaLY98","tN97O2TH4b0J")).
neg(eqo("conf/vldb/GarofalakisI97","NCPSEqg7mpsJ")).
neg(eqo("conf/vldb/Gentili01","rIqIRaIVpMMJ")).
neg(eqo("conf/vldb/George98","QHnRqzbv2NwJ")).
neg(eqo("conf/vldb/GilbertKMS01","UIWreKZndVQJ")).
neg(eqo("conf/vldb/GoldmanSVG98","H7RaxvYLKTYJ")).
neg(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
neg(eqo("conf/vldb/HaberIL95","nW1etYVHL-MJ")).
neg(eqo("conf/vldb/HaberIL95","r_89gABzU0UJ")).
neg(eqo("conf/vldb/HelmerWM98","lqAgqxpXpxMJ")).
neg(eqo("conf/vldb/HinneburgLH03","T1dmP2NL1aYJ")).
neg(eqo("conf/vldb/HsuLOMTX02","yWknRsgStIcJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","B_Gmn8T4IDQJ")).
neg(eqo("conf/vldb/HumborstadSHT97","pqqmiVGbjEkJ")).
neg(eqo("conf/vldb/HuntAI01","SEV-9px9auoJ")).
neg(eqo("conf/vldb/JagadishLRSS94","Tpb-LwPZJNMJ")).
neg(eqo("conf/vldb/JagadishLS99","EAZ5Gz22bIUJ")).
neg(eqo("conf/vldb/Jamil97","28GZ8M1ZPVYJ")).
neg(eqo("conf/vldb/JarkeKL00","l5DIpKYgodkJ")).
neg(eqo("conf/vldb/JiangSLB00","JOfKVdX9hYYJ")).
neg(eqo("conf/vldb/JonscherD94","83XwvQg-YQUJ")).
neg(eqo("conf/vldb/KalusD95","r1xwwqWr2K0J")).
neg(eqo("conf/vldb/KarayannidisTSPMRFEB02","QuZh8rL7pbsJ")).
neg(eqo("conf/vldb/KemmeA00","_FNrQSD-huEJ")).
neg(eqo("conf/vldb/KnorrN99","x5jeMyauzWgJ")).
neg(eqo("conf/vldb/KochBG03","Uv3mhmUGwdcJ")).
neg(eqo("conf/vldb/KornackerB95","TjG5memyVWIJ")).
neg(eqo("conf/vldb/Korth95","E7H04svX7v8J")).
neg(eqo("conf/vldb/KoudasMJ99","hnMltY0uSf0J")).
neg(eqo("conf/vldb/KumarKA97","8p0ad6wEQcEJ")).
neg(eqo("conf/vldb/KumarKA97","N9_oACTp3uAJ")).
neg(eqo("conf/vldb/LabioG96","EBXh5GwbeNMJ")).
neg(eqo("conf/vldb/LabioG96","N3Bry6sSMw8J")).
neg(eqo("conf/vldb/LabrinidisR01","IvMJ4bK708kJ")).
neg(eqo("conf/vldb/LakshmananJN00","Rhh7boxG52IJ")).
neg(eqo("conf/vldb/LeslieJBY95","gZ60Ten2H7oJ")).
neg(eqo("conf/vldb/LevyMS94","1S-vlkBOdmkJ")).
neg(eqo("conf/vldb/Leymann01","eRh9hA637AMJ")).
neg(eqo("conf/vldb/LiHKSPAC02","iP9s_nlGG9oJ")).
neg(eqo("conf/vldb/LiM01","vkMYwC5tzUgJ")).
neg(eqo("conf/vldb/LongS03","jj64xkk75ZIJ")).
neg(eqo("conf/vldb/LuSL95","Fr8CPbK-IFIJ")).
neg(eqo("conf/vldb/LuSL95","QsPxm6zhtecJ")).
neg(eqo("conf/vldb/ManolescuFKXO00","t19PsyGam1EJ")).
neg(eqo("conf/vldb/ManolopoulosT01","gyPwIEnKIC0J")).
neg(eqo("conf/vldb/MaratheS97","ae7u4oyTu80J")).
neg(eqo("conf/vldb/Moerkotte02","y9_JN2ozsjoJ")).
neg(eqo("conf/vldb/Mohan02a","E2zhARKv5dsJ")).
neg(eqo("conf/vldb/Mohan02a","EGK_VJfkvY8J")).
neg(eqo("conf/vldb/Mohan99","VT0oJBgVFosJ")).
neg(eqo("conf/vldb/Mohan99","qbrkg2DRU3AJ")).
neg(eqo("conf/vldb/MorimotoIM97","3enylshvOl8J")).
neg(eqo("conf/vldb/MorishimaKKT01","do041BhhaX0J")).
neg(eqo("conf/vldb/NetzCBF00","3OTNpeTJ1vEJ")).
neg(eqo("conf/vldb/NetzCBF00","tIn5XIu8si0J")).
neg(eqo("conf/vldb/NgH94","QPaG2PoXGwoJ")).
neg(eqo("conf/vldb/NgH94","SXHPvzZDrFMJ")).
neg(eqo("conf/vldb/NgY94","hQ2iRlFtfGUJ")).
neg(eqo("conf/vldb/NipplM98","mH0vNFMcLxsJ")).
neg(eqo("conf/vldb/Nori00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1027771%26type%3Dpdf")).
neg(eqo("conf/vldb/Norvag99","kn-50YWUci4J")).
neg(eqo("conf/vldb/OConnellWG01","l3aPI4eb1i8J")).
neg(eqo("conf/vldb/OuzzaniAB94","CgoUJ7DogcwJ")).
neg(eqo("conf/vldb/PapadiasMD98","oRp455a_YpsJ")).
neg(eqo("conf/vldb/PereiraFJLS01","Cd6A4nsDnkQJ")).
neg(eqo("conf/vldb/RaghavanG03","A3GM0TrgbwIJ")).
neg(eqo("conf/vldb/RamakrishnanR96","_BJOL8YHKo4J")).
neg(eqo("conf/vldb/RamsakMFZEB00","I5fV3jpcrmAJ")).
neg(eqo("conf/vldb/RezendeH98","Kw-JxYkuxdkJ")).
neg(eqo("conf/vldb/RosenthalS94","8p0ad6wEQcEJ")).
neg(eqo("conf/vldb/Sarawagi95","w9je55hjOlwJ")).
neg(eqo("conf/vldb/Sarawagi99","z5DmAoBjsjAJ")).
neg(eqo("conf/vldb/SarawagiBKM02","Jm8lRWYv2Y4J")).
neg(eqo("conf/vldb/SarawagiS96","gz92a8BdTLUJ")).
neg(eqo("conf/vldb/SavasereON95","eE98qv4oVnQJ")).
neg(eqo("conf/vldb/SavasereON95","nAMnQu4_BmAJ")).
neg(eqo("conf/vldb/SchaeferBBJ00","zzhq-sLtZ34J")).
neg(eqo("conf/vldb/SchmidtWKCMB02","CvGGYMrKR2sJ")).
neg(eqo("conf/vldb/Schoning98","91_UXRZrcqkJ")).
neg(eqo("conf/vldb/ShahDR03","1WArdj4NhEoJ")).
neg(eqo("conf/vldb/ShanmugasundaramKSFF01","w0_0inAwV_QJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","6mbu5T69NFEJ")).
neg(eqo("conf/vldb/ShuklaDN98","1eCp1f8DhasJ")).
neg(eqo("conf/vldb/Sondag01","SgIXTyCqCJUJ")).
neg(eqo("conf/vldb/Sondag01","mAMudiY-q5YJ")).
neg(eqo("conf/vldb/StolteA02","o0vnSBVzRQcJ")).
neg(eqo("conf/vldb/Suciu96","m2CCumFeAWgJ")).
neg(eqo("conf/vldb/Sullivan96","OiHYG-Al8G8J")).
neg(eqo("conf/vldb/TanEO01","WpkxYoe4DQYJ")).
neg(eqo("conf/vldb/TanSHCR01","l-Sn0enuHxkJ")).
neg(eqo("conf/vldb/Taylor00","Iw6L0NDtL5AJ")).
neg(eqo("conf/vldb/Taylor00","vVDiaj-ngQUJ")).
neg(eqo("conf/vldb/Tygar98","O8hTucqqWBMJ")).
neg(eqo("conf/vldb/VassalosP97","Gz8ddfSS5H0J")).
neg(eqo("conf/vldb/VassalosP97","tRBJeQzcthwJ")).
neg(eqo("conf/vldb/VelegrakisMP03","y2dZ5cRja_IJ")).
neg(eqo("conf/vldb/Wadler01","BZzoqvKEW3IJ")).
neg(eqo("conf/vldb/WangHH00","qbxHq9qXVrUJ")).
neg(eqo("conf/vldb/WuFSP00","tr_rawv-6SMJ")).
neg(eqo("conf/vldb/XinHLW03","9MlAuURfKhYJ")).
neg(eqo("conf/vldb/YangG01","LN1TWlAUa0wJ")).
neg(eqo("conf/vldb/YangKL97","CRhr7dm8WIgJ")).
neg(eqo("conf/vldb/ZhouLZLZJT01","IqjYD8NRzR0J")).
neg(eqo("journals/sigmod/Aberer02b","_hb7jvkdltcJ")).
neg(eqo("journals/sigmod/Aberer02c","WryeHhngM_oJ")).
neg(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565129%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03c","gETqmiI3Y2cJ")).
neg(eqo("journals/sigmod/Aberer03d","fnt5G2r4MaYJ")).
neg(eqo("journals/sigmod/Abiteboul99","u6aWxu1dur8J")).
neg(eqo("journals/sigmod/AilamakiG03","-mTrpy_n8PYJ")).
neg(eqo("journals/sigmod/AilamakiG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Alonso95a","lqi3ilJp8rwJ")).
neg(eqo("journals/sigmod/AlonsoCIM95","OfZWx8jhQvwJ")).
neg(eqo("journals/sigmod/AndersonS94","Xh4z_InAi4AJ")).
neg(eqo("journals/sigmod/ArenasKKKMM03","Hxnlcwm_RhMJ")).
neg(eqo("journals/sigmod/BabuW01","5Chw6HN64vEJ")).
neg(eqo("journals/sigmod/BarbaraBFLS94","M-1Nbw1n-PQJ")).
neg(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
neg(eqo("journals/sigmod/Bernstein98","heE03EvbflsJ")).
neg(eqo("journals/sigmod/Bernstein98","k7rs7gIQMgQJ")).
neg(eqo("journals/sigmod/BestavrosLS96","drh9KspqNUwJ")).
neg(eqo("journals/sigmod/BilirisP96","GHyJHoIn2-gJ")).
neg(eqo("journals/sigmod/BonnetBDL03","OrVfYI6q8ggJ")).
neg(eqo("journals/sigmod/BonnetBDL03","_4ARkdpRArQJ")).
neg(eqo("journals/sigmod/BuchnerM98","PF-rFkrW2nIJ")).
neg(eqo("journals/sigmod/Camps96","FCcDKONgJVYJ")).
neg(eqo("journals/sigmod/Camps96","ijOvUNOeICYJ")).
neg(eqo("journals/sigmod/CarmelMS01","bvOP8YD9hBwJ")).
neg(eqo("journals/sigmod/Cetintemel01","FLBFge9zwNoJ")).
neg(eqo("journals/sigmod/Chang03","8JSwKJipBnIJ")).
neg(eqo("journals/sigmod/Chang03","J7Y20fYLGbcJ")).
neg(eqo("journals/sigmod/Chen94","175GVbHyl8wJ")).
neg(eqo("journals/sigmod/Chen94","WB0GheSnLtYJ")).
neg(eqo("journals/sigmod/ChenHKPW94","GXApzwcGl78J")).
neg(eqo("journals/sigmod/ChienTZ01","8YoYzQtOgYoJ")).
neg(eqo("journals/sigmod/CruzKLSWY02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/DadamK97","CFjExtypOCYJ")).
neg(eqo("journals/sigmod/DarwenD95","url:http://portal.acm.org/citation.cfm%3Fid%3D245882.245886%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/DogacAOD95","EwU0KYwx0BkJ")).
neg(eqo("journals/sigmod/DongS00","que4v9cvspwJ")).
neg(eqo("journals/sigmod/DongS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058159%26type%3Dpdf")).
neg(eqo("journals/sigmod/EisenbergM02","6uelfg3RgEoJ")).
neg(eqo("journals/sigmod/EisenbergM98a","6uelfg3RgEoJ")).
neg(eqo("journals/sigmod/EisenbergM98a","tFbkjO2wcFMJ")).
neg(eqo("journals/sigmod/ElmagarmidJF95","TsxYoh7f5ocJ")).
neg(eqo("journals/sigmod/Fagin02","ngyv_wpNFOgJ")).
neg(eqo("journals/sigmod/Fong95","vhUs7wTpUOoJ")).
neg(eqo("journals/sigmod/Franklin00","R61_mG3Y_ssJ")).
neg(eqo("journals/sigmod/Franklin00b","Hq7uOX0f1pcJ")).
neg(eqo("journals/sigmod/Franklin00b","rSo0-VVmB5cJ")).
neg(eqo("journals/sigmod/Franklin98","1Y-pKWumDNkJ")).
neg(eqo("journals/sigmod/Franklin98","url:http://www.roc.noaa.gov/news/vol1is4.pdf")).
neg(eqo("journals/sigmod/Franklin98b","p0QHT_9_NSkJ")).
neg(eqo("journals/sigmod/GalianoM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945741%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Gardels97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0234325CI")).
neg(eqo("journals/sigmod/GroskyFS94","mt8Q1YmVRkMJ")).
neg(eqo("journals/sigmod/GunopulosK01","4Ns56TPqqcsJ")).
neg(eqo("journals/sigmod/Halevy00","M2zV0WBF7XYJ")).
neg(eqo("journals/sigmod/Halevy03","Di-EjDZ_abYJ")).
neg(eqo("journals/sigmod/Halevy03","YD_7W5RczNoJ")).
neg(eqo("journals/sigmod/Halevy03","b38Lp5XCBDYJ")).
neg(eqo("journals/sigmod/HanBP01","eFDhA7HrBdsJ")).
neg(eqo("journals/sigmod/Hanson99","elH7P-eUgmAJ")).
neg(eqo("journals/sigmod/Huyn01","I2Md2kGPQ6cJ")).
neg(eqo("journals/sigmod/Ioannidis96","I6b3ilZNDB4J")).
neg(eqo("journals/sigmod/Ioannidis96","ewbCbUmnolUJ")).
neg(eqo("journals/sigmod/JainH94","nwPlm2GAwR4J")).
neg(eqo("journals/sigmod/Jannink95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130872%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/JenningsNF98","N3dP98KHZhkJ")).
neg(eqo("journals/sigmod/Jhingran00","X3jpFEH_f5UJ")).
neg(eqo("journals/sigmod/KambhampatiK03","n0q3Jafl1BEJ")).
neg(eqo("journals/sigmod/KantM00","v37c334QjhoJ")).
neg(eqo("journals/sigmod/KennedyMB96","l9H6480kRhgJ")).
neg(eqo("journals/sigmod/KiyokiKH94","bnzUppOZricJ")).
neg(eqo("journals/sigmod/KokkotosIPS95","KztAWeTx7hwJ")).
neg(eqo("journals/sigmod/Konig-RiesL97","4qdJwc-ZySsJ")).
neg(eqo("journals/sigmod/Labrinidis01","rPkYH6NBK6QJ")).
neg(eqo("journals/sigmod/LabrinidisR00","3Ozte0ucNJAJ")).
neg(eqo("journals/sigmod/LacroixB03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058163%26type%3Dpdf")).
neg(eqo("journals/sigmod/LaenderRST02","paQAZ2KXFgAJ")).
neg(eqo("journals/sigmod/LeeF01","a08IZM12vyUJ")).
neg(eqo("journals/sigmod/Liu01a","3IFlpeKgLlAJ")).
neg(eqo("journals/sigmod/Liu01a","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Liu01b","DiWYJABnOuMJ")).
neg(eqo("journals/sigmod/Liu01b","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Liu02","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Liu02a","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu02b","rlfxeE4k2p4J")).
neg(eqo("journals/sigmod/Liu02c","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/LohmanGFS01","RJG51SMOacwJ")).
neg(eqo("journals/sigmod/Lomet01","-pVUk-m11BMJ")).
neg(eqo("journals/sigmod/McHughW97","PZTESZecfnQJ")).
neg(eqo("journals/sigmod/MedeirosP94","5ziID0k2zsUJ")).
neg(eqo("journals/sigmod/MedskerCS95","OfWTbnGGiGkJ")).
neg(eqo("journals/sigmod/MedskerCS95","oMVxci3xVU4J")).
neg(eqo("journals/sigmod/Mendelzon00","2hzHQA8MjBkJ")).
neg(eqo("journals/sigmod/MusickC99","hnMltY0uSf0J")).
neg(eqo("journals/sigmod/OoiST03","url:http://www.kluweronline.com/article.asp%3FPIPS%3D321076%26PDF%3D1")).
neg(eqo("journals/sigmod/Ouksel03","S-LYnzS1K70J")).
neg(eqo("journals/sigmod/OukselS99","WrjPBdw8fhkJ")).
neg(eqo("journals/sigmod/OukselS99","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565131%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Ozsu03a","PU2nYKuoaCwJ")).
neg(eqo("journals/sigmod/PapazoglouH99","WbsAK4ZE17YJ")).
neg(eqo("journals/sigmod/Qian96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96a","ojEcoQCzdkMJ")).
neg(eqo("journals/sigmod/RamDD99","kBGc5SbAMjoJ")).
neg(eqo("journals/sigmod/RashidS00","darWCYZjZHcJ")).
neg(eqo("journals/sigmod/RosenthalHRS97","g4p3K22hY_oJ")).
neg(eqo("journals/sigmod/RosenthalS99","ix1k9dPzH9EJ")).
neg(eqo("journals/sigmod/RossAJS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossCGLLM01","OuUUuk369jQJ")).
neg(eqo("journals/sigmod/RossHLW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossNO03","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/SantucciT96","7gJjI63FlyYJ")).
neg(eqo("journals/sigmod/Segev94","xW--Ei3c_qwJ")).
neg(eqo("journals/sigmod/Segev94a","mBC03oUT8yAJ")).
neg(eqo("journals/sigmod/Sidell96","P9iKjuM8kF8J")).
neg(eqo("journals/sigmod/SlivinskasJS02","M1pLuxdh_m0J")).
neg(eqo("journals/sigmod/Snodgrass03","M04eDZqVLgQJ")).
neg(eqo("journals/sigmod/Snodgrass03c","Ey7Mbh6IdQIJ")).
neg(eqo("journals/sigmod/Snodgrass03c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass94","VwZQmafqkE0J")).
neg(eqo("journals/sigmod/Snodgrass94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D24823%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass99","8gLwx5DXh7wJ")).
neg(eqo("journals/sigmod/Snodgrass99b","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","L61_1TEGBLYJ")).
neg(eqo("journals/sigmod/SnodgrassACFLLORRSV99","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","T7xkvfglxxcJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","loz3KpVndVMJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SpynsMJ02","EQsWWZdE45wJ")).
neg(eqo("journals/sigmod/SycaraKWL99","eqXOBb8gKkQJ")).
neg(eqo("journals/sigmod/TianDCZ02","C-M5DwS55kcJ")).
neg(eqo("journals/sigmod/VelACM01","0PyiTSOYkoQJ")).
neg(eqo("journals/sigmod/VelACM01","tO0OVpz2o9sJ")).
neg(eqo("journals/sigmod/Wedekind94","NetR1satwasJ")).
neg(eqo("journals/sigmod/WeikumSR03","hFPNVe44A04J")).
neg(eqo("journals/sigmod/WestmannKHM00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom94","3y6y5AXu-j0J")).
neg(eqo("journals/sigmod/Widom96a","5Ca6WOB3X-wJ")).
neg(eqo("journals/sigmod/Winslett03","1moimGNoBBcJ")).
neg(eqo("journals/sigmod/Winslett03","url:http://doi.wiley.com/10.1002/ace.111")).
neg(eqo("journals/sigmod/YeungHL94","itzFKEuPvScJ")).
neg(eqo("journals/sigmod/Zhang95","PbZkvDhTeyEJ")).
neg(eqo("journals/tods/BrightHP94","5CAfGmHl5GkJ")).
neg(eqo("journals/tods/BrightHP94","eWVreKOw_QgJ")).
neg(eqo("journals/tods/BrightHP94","oJnAzS-tkukJ")).
neg(eqo("journals/tods/BunemanO96","OvNkI-zRsskJ")).
neg(eqo("journals/tods/CeriFPT95","TE7m9Lvta08J")).
neg(eqo("journals/tods/ChaudhuriS99","4zZ7Lxt4PPIJ")).
neg(eqo("journals/tods/Chen95","1SszwaWWQLgJ")).
neg(eqo("journals/tods/Chen95a","WB_-7kkaJHUJ")).
neg(eqo("journals/tods/ChenHM95","nqXEzE6KVmQJ")).
neg(eqo("journals/tods/Chomicki03","9INE8y1uDRkJ")).
neg(eqo("journals/tods/Chomicki95","pHuL-9kHWH0J")).
neg(eqo("journals/tods/Chomicki95","vhOu8QYt5t4J")).
neg(eqo("journals/tods/CiacciaTZ96","urL_oXzvBBUJ")).
neg(eqo("journals/tods/DyresonS98","OZrhMCDq4IAJ")).
neg(eqo("journals/tods/FraternaliT95","8SlR6f52AtIJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","FHDrVCE5cjoJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","Rg8V7NSK9tMJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
neg(eqo("journals/tods/GraefeC95","_6wwPJEGUiAJ")).
neg(eqo("journals/tods/IoannidisR95","h_OMj8y8FmMJ")).
neg(eqo("journals/tods/KemmeA00","sQ4LNOP-qooJ")).
neg(eqo("journals/tods/Kim94","url:http://portal.acm.org/citation.cfm%3Fid%3D202106.569784%26coll%3Dportal%26dl%3DACM%26idx%3DJ777%26part%3Dtransaction%26WantType%3Dtransaction%26title%3DACM%2520Transactions%2520on%2520Database%2520Systems%2520(TODS)%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/LiuDL02","8tkAk8aaEfMJ")).
neg(eqo("journals/tods/MamoulisP01","vE7HAHpSauwJ")).
neg(eqo("journals/tods/Meo00","UHHPqc33sqQJ")).
neg(eqo("journals/tods/PolyzoisG94","9rnT6AgafkoJ")).
neg(eqo("journals/tods/ScioreSR94","fW9j2V5gnUMJ")).
neg(eqo("journals/tods/ShashaLSV95","qmrGOToSJn0J")).
neg(eqo("journals/tods/SistlaWYS98","BtAgT5tQr14J")).
neg(eqo("journals/tods/Suciu02","GwvN1w9_ZZoJ")).
neg(eqo("journals/vldb/AbbadiSW01","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
neg(eqo("journals/vldb/AbiteboulB95","AzywSPMzNE8J")).
neg(eqo("journals/vldb/AgrawalAJL95","TBdnfqqLsLwJ")).
neg(eqo("journals/vldb/AgrawalHK03","RSSGIouxL0IJ")).
neg(eqo("journals/vldb/AgrawalHK03","bL4jBJECdB0J")).
neg(eqo("journals/vldb/AntoshenkovZ96","mRwNY8Pj4oEJ")).
neg(eqo("journals/vldb/Atkinson00","KPTq63wCGV4J")).
neg(eqo("journals/vldb/Barbara-MillaG94","JTmjAiPfYcEJ")).
neg(eqo("journals/vldb/Baumann94","qd1WgYXJB4gJ")).
neg(eqo("journals/vldb/BerendtS00","eJqKisRZ6msJ")).
neg(eqo("journals/vldb/ChakrabartiGRS01","rcSfDxBif40J")).
neg(eqo("journals/vldb/ChangG01","b_nC-gMKlXEJ")).
neg(eqo("journals/vldb/ChienTZ02","lmLjPf_m6jwJ")).
neg(eqo("journals/vldb/CliftonGB95","SNX-QhXeObMJ")).
neg(eqo("journals/vldb/Cobb97","R6XK3NbfZrgJ")).
neg(eqo("journals/vldb/DerrMP94","XZY4Jj8PsykJ")).
neg(eqo("journals/vldb/EvangelidisS97","6HyjyllsSvQJ")).
neg(eqo("journals/vldb/EvangelidisS97","gFGXgzstK08J")).
neg(eqo("journals/vldb/FahlR97","z6JEYoArZmsJ")).
neg(eqo("journals/vldb/HalkidiNVV03","tFe0FjHYe2MJ")).
neg(eqo("journals/vldb/Han98","Nul0aglOPZYJ")).
neg(eqo("journals/vldb/HarderST99","I53LgrENfGIJ")).
neg(eqo("journals/vldb/HarderST99","fGVRrdFuc1IJ")).
neg(eqo("journals/vldb/HarrisR96","tZBIZ9ZHdTkJ")).
neg(eqo("journals/vldb/HelmerM03","3jiJvBah6eAJ")).
neg(eqo("journals/vldb/IoannidisNSS97","cxJXffJUdbsJ")).
neg(eqo("journals/vldb/KrivokapicKG99","UeLjlfHU_gkJ")).
neg(eqo("journals/vldb/LometS97","Hov18raBHwIJ")).
neg(eqo("journals/vldb/MaedcheMS03","rrHUOuKLn1gJ")).
neg(eqo("journals/vldb/MehtaGPN98","7Zf8Y2idDb0J")).
neg(eqo("journals/vldb/NanopoulosM02","VWd7jhLXfV0J")).
neg(eqo("journals/vldb/PanagosB97","hRToevpkaa0J")).
neg(eqo("journals/vldb/PeckhamMD95","YwsodDTO8PwJ")).
neg(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
neg(eqo("journals/vldb/Sarawagi01","MOvQoZozEmcJ")).
neg(eqo("journals/vldb/Seshadri98","MRfEjJe2PzoJ")).
neg(eqo("journals/vldb/SinghalS97","3mgk6qNKT9QJ")).
neg(eqo("journals/vldb/SofferS98","x4i6X_N1JBMJ")).
neg(eqo("journals/vldb/StonebrakerALPSSSY96","_RMZmSBR_PUJ")).
neg(eqo("journals/vldb/TenienteO95","aC-8qspy24wJ")).
neg(eqo("journals/vldb/TurkerG01","kg0UicKszK8J")).
neg(eqo("journals/vldb/VaghaniRKSSLH94","url:http://portal.acm.org/citation.cfm%3Fid%3D126482.126494%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/WhiteD95","jKBaGqWJK2oJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AdaliSS99","bhWLVCoDuNQJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/AdelbergGK95","NbLabaGWoh4J")).
pos(eqo("conf/sigmod/AdyaGLM95","FlE1JdgElGQJ")).
pos(eqo("conf/sigmod/AdyaGLM95","bfcbZlt6vngJ")).
pos(eqo("conf/sigmod/Aggarwal03","qbubaA6mQawJ")).
pos(eqo("conf/sigmod/AggarwalWY99","wjKnsQWl5ZoJ")).
pos(eqo("conf/sigmod/ArasuG03","jp9ptMpdoGwJ")).
pos(eqo("conf/sigmod/ArasuG03","zN8ngmWNDlgJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","1tZ74y0DNLIJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","5bjtbk4ZdZIJ")).
pos(eqo("conf/sigmod/BersonGM95","YkPqPzGFnZIJ")).
pos(eqo("conf/sigmod/BlakeleyD00","url:http://portal.acm.org/citation.cfm%3Fid%3D335191.335480%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BlohsfeldKS99","PQbi3PaRh84J")).
pos(eqo("conf/sigmod/BornhovdAKMPR03","4qtu0-tW0IcJ")).
pos(eqo("conf/sigmod/BrinMUT97","VBB3teN9P6EJ")).
pos(eqo("conf/sigmod/BrinMUT97","aOBNgdooDHAJ")).
pos(eqo("conf/sigmod/BrinMUT97","bjZ8SxYnrd0J")).
pos(eqo("conf/sigmod/BrinMUT97","vIwsSOGQOWAJ")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/BrunoCG01","8KJ9XFv1ESAJ")).
pos(eqo("conf/sigmod/BrunoCG01","XWF4kOtaoJkJ")).
pos(eqo("conf/sigmod/Carey00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","vF-KpOq9TdIJ")).
pos(eqo("conf/sigmod/CareyK97","2OPEy9_6BlEJ")).
pos(eqo("conf/sigmod/CareyMN97","nM9bJESsWNoJ")).
pos(eqo("conf/sigmod/Chamberlin03","_F5D4QMbZ0sJ")).
pos(eqo("conf/sigmod/Chan98","oo2mr5fbMggJ")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","MNuT46WJZaQJ")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","onlybp6SAAsJ")).
pos(eqo("conf/sigmod/ChangG99","BYkCvtDCxzcJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","AiXOfJPvvpUJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","JyEX0YVMP5oJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","Y-kXztd20YQJ")).
pos(eqo("conf/sigmod/ChawatheG97","5O88Bum19wAJ")).
pos(eqo("conf/sigmod/ChawatheG97","oHUiSrycKdgJ")).
pos(eqo("conf/sigmod/ChenCPPSTM00","Ab6MIDVDzhAJ")).
pos(eqo("conf/sigmod/ChenGMV02","IqV3EploPP4J")).
pos(eqo("conf/sigmod/ChoSG00","ilJdCU_qODkJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","GpGg0czXSQcJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","nDl2k1YSi8AJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","tGBhWHHU7hsJ")).
pos(eqo("conf/sigmod/Cotton02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564792%26type%3Dpdf")).
pos(eqo("conf/sigmod/DasuJMS02","POt1WbTBB4cJ")).
pos(eqo("conf/sigmod/DeshpandeGR01","0Ta25VSGl7kJ")).
pos(eqo("conf/sigmod/DeshpandeNGS03","fU6zoUKeXe8J")).
pos(eqo("conf/sigmod/Deutsch95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223880")).
pos(eqo("conf/sigmod/FabretJLPRS01","8lBDhvljrAEJ")).
pos(eqo("conf/sigmod/FabretJLPRS01","uaOB9o42w5AJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","6WIF-_hBZZgJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","R4fVVmv_YvoJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","s-BT0x6h2qUJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","XMC0W6CQJJIJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","rgk1HYJbTNEJ")).
pos(eqo("conf/sigmod/ForlizziGNS00","AHozbGex7VUJ")).
pos(eqo("conf/sigmod/FranklinZ98","5Cj9Wx8llkwJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","Y8UdbAPhYpUJ")).
pos(eqo("conf/sigmod/GarofalakisG02","6EaC2CmjsmAJ")).
pos(eqo("conf/sigmod/GarofalakisGR02","Hz7TBeGZRz8J")).
pos(eqo("conf/sigmod/GarofalakisI96","6lvBOS-XO3EJ")).
pos(eqo("conf/sigmod/GarofalakisI96","MfPbk62EdyQJ")).
pos(eqo("conf/sigmod/GeneserethKD97","2Nl65Vp7bxUJ")).
pos(eqo("conf/sigmod/GillmannWSWW00","3bYCefUMXr8J")).
pos(eqo("conf/sigmod/GoelI96","_Vn4nSui5UMJ")).
pos(eqo("conf/sigmod/GorelikWD94","X2URoOMjJv4J")).
pos(eqo("conf/sigmod/GoyalHKMS96","uUcmU_hKF2kJ")).
pos(eqo("conf/sigmod/GrayHOS96","5cw83MyqYrMJ")).
pos(eqo("conf/sigmod/GrayHOS96","J_QkWJ4HlOUJ")).
pos(eqo("conf/sigmod/GrayHOS96","imwZsCcZvFQJ")).
pos(eqo("conf/sigmod/GrayHOS96","t2B4EAmKqnAJ")).
pos(eqo("conf/sigmod/Grust02","-3LAxRNpDJIJ")).
pos(eqo("conf/sigmod/GunopulosD01","oYtmj53qV0UJ")).
pos(eqo("conf/sigmod/HaasH99","fz1XAzoKPo0J")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanKS97","_EEZCcB1BPYJ")).
pos(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
pos(eqo("conf/sigmod/HanWDPW02","tcyoSdrkaRMJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","9Ue5hZp8H68J")).
pos(eqo("conf/sigmod/HarinarayanRU96","Fyek_kCB-qkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","JM1X7hho718J")).
pos(eqo("conf/sigmod/HarinarayanRU96","QHUtoLECZzgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","sLvivSi__BcJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","uKGmcc4xUG4J")).
pos(eqo("conf/sigmod/HellersteinA00","Gsb6dnkFBMoJ")).
pos(eqo("conf/sigmod/HellersteinA00","VlRO0WwUy3wJ")).
pos(eqo("conf/sigmod/HellersteinA00","iFbXSEmnpzgJ")).
pos(eqo("conf/sigmod/HernandezMHYHT01","89WHY6hZ22UJ")).
pos(eqo("conf/sigmod/HernandezS95","7EYR1qDwKg0J")).
pos(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
pos(eqo("conf/sigmod/HoAMS97","4YsYF_8QeogJ")).
pos(eqo("conf/sigmod/HoAMS97","LWXzOXyOy24J")).
pos(eqo("conf/sigmod/HoAMS97","r1um7d3ckAYJ")).
pos(eqo("conf/sigmod/HoAMS97","rUNHnYf8TtEJ")).
pos(eqo("conf/sigmod/HoAMS97","xbt2t9kYWLwJ")).
pos(eqo("conf/sigmod/HsiaoCY94","LEi_Rzm1iH0J")).
pos(eqo("conf/sigmod/IlyasRLGL03","qCnvlNwYp6cJ")).
pos(eqo("conf/sigmod/Jamil99","z5EfiutEfScJ")).
pos(eqo("conf/sigmod/KabraD98","V9XUvirmVEEJ")).
pos(eqo("conf/sigmod/KabraD98","WOHxNqdNMZoJ")).
pos(eqo("conf/sigmod/Kennamer98","RQ9qLR4St8sJ")).
pos(eqo("conf/sigmod/KotidisR99","323DOAMQyUkJ")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/LabioWGG00","EhR3fz7f7vcJ")).
pos(eqo("conf/sigmod/LahiriJJC98","qtwJ7XWG9JIJ")).
pos(eqo("conf/sigmod/LakshmananPZ03","-EMZt7FrF4QJ")).
pos(eqo("conf/sigmod/LehnerSPC00","UFKz6Q0wVi4J")).
pos(eqo("conf/sigmod/LiBKN03","micx2kyGfKIJ")).
pos(eqo("conf/sigmod/LiCHH97","vjqDlXKHfzoJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","4zDGoqCAWOoJ")).
pos(eqo("conf/sigmod/LibkinMW96","3QgOnuIwVZMJ")).
pos(eqo("conf/sigmod/LibkinMW96","OfZWx8jhQvwJ")).
pos(eqo("conf/sigmod/LiskovACDGGMMS96","Ey7Mbh6IdQIJ")).
pos(eqo("conf/sigmod/LitwinS00","fx0s58TJ75EJ")).
pos(eqo("conf/sigmod/LitwinS00","qzeu5GQ_2p0J")).
pos(eqo("conf/sigmod/LiuPBHPT00","q_o5zij9nCEJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","3tRtdT5VfDkJ")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/Maguire01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375742%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Mamoulis03","8-eaDTdtfY4J")).
pos(eqo("conf/sigmod/MeccaAMMS98","I-fmtPvluKEJ")).
pos(eqo("conf/sigmod/Miller98","0B1XRTZ8cHkJ")).
pos(eqo("conf/sigmod/Miller98","fW6JIoNRqAQJ")).
pos(eqo("conf/sigmod/Mohan94","E2zhARKv5dsJ")).
pos(eqo("conf/sigmod/Mohan94","Ft1YZIFfu0cJ")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/NazeriBO01","2E9I_lugGC4J")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/Nori00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.335474")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D280357%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/OlstonJW03","D1h_jOHVyA4J")).
pos(eqo("conf/sigmod/PangCL94","beMsu5ebf30J")).
pos(eqo("conf/sigmod/ParkCY95","8CqjZ166ScEJ")).
pos(eqo("conf/sigmod/ParkCY95","pN4pq6qELakJ")).
pos(eqo("conf/sigmod/ParkCY95","v9preswS6YUJ")).
pos(eqo("conf/sigmod/RajagopalanML98","6bxNVhIp7FAJ")).
pos(eqo("conf/sigmod/RajagopalanML98","AUR-p53CsK8J")).
pos(eqo("conf/sigmod/RajagopalanML98","HVP6eYl30IgJ")).
pos(eqo("conf/sigmod/RamanH02","4692SthNStUJ")).
pos(eqo("conf/sigmod/RamanH02","F0T3KimkbGcJ")).
pos(eqo("conf/sigmod/RinfretOO01","pyqtmrPg24YJ")).
pos(eqo("conf/sigmod/RodriguezR00","MCDgDxsc8rcJ")).
pos(eqo("conf/sigmod/RodriguezR00","gi7N9eQiTx4J")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","2i9wDNdFZM8J")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","PurSnqtdtCgJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","QzW5By67KwcJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","r3GI5ly9cuIJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","yfTTlN56sCUJ")).
pos(eqo("conf/sigmod/RoySSB00","OV6n7LhOe_cJ")).
pos(eqo("conf/sigmod/RundensteinerKZWLLN99","2XRfNjwuDrsJ")).
pos(eqo("conf/sigmod/SarawagiTA98","SLmQWvsYtKYJ")).
pos(eqo("conf/sigmod/SarawagiTA98","wkgGoKqPVzQJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","Elpbl8vygYoJ")).
pos(eqo("conf/sigmod/SeshadriLR94","cL_OKIQDvmQJ")).
pos(eqo("conf/sigmod/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","SipDBj3SOb4J")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","ZJRIE5CMDZAJ")).
pos(eqo("conf/sigmod/SrikantA96","9t4Mce85HT4J")).
pos(eqo("conf/sigmod/SrikantA96","OASIyc-vi9EJ")).
pos(eqo("conf/sigmod/SrikantA96","Sf7DDYXGGD8J")).
pos(eqo("conf/sigmod/SrikantA96","WSVs3nCRe8EJ")).
pos(eqo("conf/sigmod/SrikantA96","ZBuWjiVOE94J")).
pos(eqo("conf/sigmod/SrikantA96","oAlX0rVQqlIJ")).
pos(eqo("conf/sigmod/SrikantA96","tTQpdbZYZGoJ")).
pos(eqo("conf/sigmod/Suciu99","FOpGGQJyLLsJ")).
pos(eqo("conf/sigmod/SzalayGKT00","1kKap3JyndkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","4yvrgPBJUBYJ")).
pos(eqo("conf/sigmod/SzalayGKT00","5Q_6HLwZ2YIJ")).
pos(eqo("conf/sigmod/SzalayGKT00","GYR0v7CFkP0J")).
pos(eqo("conf/sigmod/SzalayGKT00","ZXB1xI2h-HkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","oPgy1SYoptgJ")).
pos(eqo("conf/sigmod/SzalayGKT00","zxOI0ZD8jeIJ")).
pos(eqo("conf/sigmod/TaoP02","fDWfHiQ6BR4J")).
pos(eqo("conf/sigmod/Team99","bcR9TErOrKQJ")).
pos(eqo("conf/sigmod/TomasicGS94","wFwk1sJZ2SYJ")).
pos(eqo("conf/sigmod/TrisoliniLN99","cFMtMf7bLzIJ")).
pos(eqo("conf/sigmod/VingralekBW94","rM8Ecg1WL4kJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","iFiv0xEJvIkJ")).
pos(eqo("conf/sigmod/YerneniLGU99","L9rzYv5OWpgJ")).
pos(eqo("conf/sigmod/YerneniLGU99","hnMltY0uSf0J")).
pos(eqo("conf/sigmod/YerneniLGU99","p7jagU7k2-IJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VCc6IQulRJ4J")).
pos(eqo("conf/sigmod/ZhangMCMR02","rvZQMrCOQ1MJ")).
pos(eqo("conf/sigmod/ZhangNBB94","bymQ_6SSse4J")).
pos(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
pos(eqo("conf/sigmod/ZhaoDN97","chYdQDE8cPsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","miytzHylgMAJ")).
pos(eqo("conf/vldb/AboulnagaAN01","OBbDFGQNEDQJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","OMzQ1Ah1IVQJ")).
pos(eqo("conf/vldb/AgrawalCN00","34SSHLGhNKsJ")).
pos(eqo("conf/vldb/AgrawalCN00","49BUF_66HgcJ")).
pos(eqo("conf/vldb/AgrawalCN00","U8CMJBaJyX8J")).
pos(eqo("conf/vldb/AgrawalCN00","_tle794_iKcJ")).
pos(eqo("conf/vldb/AgrawalLSS95","HugNLG7z-Z4J")).
pos(eqo("conf/vldb/AgrawalLSS95","Zbv89s2eSnwJ")).
pos(eqo("conf/vldb/AgrawalLSS95","iJc7iMSuwowJ")).
pos(eqo("conf/vldb/AgrawalS94","3MzTom30SiMJ")).
pos(eqo("conf/vldb/AgrawalS94","E7cKUUkwc1kJ")).
pos(eqo("conf/vldb/AgrawalS94","HfEQzVOD9tsJ")).
pos(eqo("conf/vldb/AgrawalS94","QlSaVou-Zt4J")).
pos(eqo("conf/vldb/AgrawalS94","XzSqN32OqgMJ")).
pos(eqo("conf/vldb/AgrawalS94","_NISJ-0lKiAJ")).
pos(eqo("conf/vldb/AgrawalS94","bKp266-v6gUJ")).
pos(eqo("conf/vldb/AgrawalS94","e5SJ3zgdwgEJ")).
pos(eqo("conf/vldb/AgrawalSX01","bpWvAVOZLbwJ")).
pos(eqo("conf/vldb/AksoyZF01","z6Z1hQYHTAMJ")).
pos(eqo("conf/vldb/AnciauxBBPV01","H2qCU9-_uykJ")).
pos(eqo("conf/vldb/AnciauxBBPV01","PFEvlg2DiMkJ")).
pos(eqo("conf/vldb/BalminPP00","FoAVdcYe0tsJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
pos(eqo("conf/vldb/Baumann03","pJ2UEKVG_hoJ")).
pos(eqo("conf/vldb/BaumannFRW97","Z4Cq4f5fKr8J")).
pos(eqo("conf/vldb/BelussiF95","5FEmoD1TIdwJ")).
pos(eqo("conf/vldb/BelussiF95","A-Fi-3YSz0IJ")).
pos(eqo("conf/vldb/BelussiF95","C-Hz6btw11gJ")).
pos(eqo("conf/vldb/BelussiF95","a78Lxr80kJUJ")).
pos(eqo("conf/vldb/BergerBSW03","Wjg_SYCySOsJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","L2c8XblCSicJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/BettiniJWW02","ghIMekzCkMQJ")).
pos(eqo("conf/vldb/BettiniJWW02","tFuA828CptUJ")).
pos(eqo("conf/vldb/Blecken00","hCSzil0nuVEJ")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BohannonGKNS02","9BuBq-Tj0TUJ")).
pos(eqo("conf/vldb/BohannonGKNS02","jj64xkk75ZIJ")).
pos(eqo("conf/vldb/BonczMK99","6GAoBRINv7kJ")).
pos(eqo("conf/vldb/BonczMK99","jsNNCDiD0yIJ")).
pos(eqo("conf/vldb/BridgeJKLLM97","8SYZpKAeTwQJ")).
pos(eqo("conf/vldb/BridgeJKLLM97","JO9Jnx_gGIUJ")).
pos(eqo("conf/vldb/BrownG01","aJoPVuDNDSsJ")).
pos(eqo("conf/vldb/BrownMCL94","xfAfu8uJ6NAJ")).
pos(eqo("conf/vldb/CareyHMW96","Nz8zwxjBoyYJ")).
pos(eqo("conf/vldb/CasatiDGS01","bFnDGrZ_4voJ")).
pos(eqo("conf/vldb/CasatiS00","OjOQRHgD-qwJ")).
pos(eqo("conf/vldb/CasatiS00","yGYyg3tCPEcJ")).
pos(eqo("conf/vldb/Celis96","Bg5vcyRBKd8J")).
pos(eqo("conf/vldb/ChandrasekaranF02","Yu4Tvuy_WiAJ")).
pos(eqo("conf/vldb/Chawathe99","1-mxxSvIMB8J")).
pos(eqo("conf/vldb/ChawatheCY94","VPwP1w9wvhEJ")).
pos(eqo("conf/vldb/ChenRS95","4TMZhO1wdwsJ")).
pos(eqo("conf/vldb/CiacciaPZ97","q-qZWa6vF7EJ")).
pos(eqo("conf/vldb/Cuppens96","8_HtXom0CVgJ")).
pos(eqo("conf/vldb/DarmontS99","Ebi8v9FZXcgJ")).
pos(eqo("conf/vldb/DesslochM97","OY4EswVULVcJ")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("conf/vldb/DoR02","bey6io4rYbgJ")).
pos(eqo("conf/vldb/DoR02","poUtz1rrj6kJ")).
pos(eqo("conf/vldb/DonjerkovicR99","SgokkSrdkyAJ")).
pos(eqo("conf/vldb/FaloutsosJS97","TyxKh_eSfCIJ")).
pos(eqo("conf/vldb/FaloutsosJS97","u_9qWSpjaO4J")).
pos(eqo("conf/vldb/Fecteau95","5JMz3UpESeQJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","Ulg4PC4-auoJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","ume4RGX6sI4J")).
pos(eqo("conf/vldb/FlorescuHKLRWCSA03","U30GdgmfAncJ")).
pos(eqo("conf/vldb/Fox02","eybUiurX77sJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","Z8jYTylZtkEJ")).
pos(eqo("conf/vldb/GarofalakisG01","SHDQQrfJ3BMJ")).
pos(eqo("conf/vldb/GarofalakisG01","rcSfDxBif40J")).
pos(eqo("conf/vldb/GarofalakisG02","Hz7TBeGZRz8J")).
pos(eqo("conf/vldb/GarofalakisIO98","ReV4xpbiC6EJ")).
pos(eqo("conf/vldb/GhoshPSH02","2dlOojuSNeIJ")).
pos(eqo("conf/vldb/GibsonKR98","9FBwT6XFOssJ")).
pos(eqo("conf/vldb/GinisHKMT97","GBVvAWWCTcgJ")).
pos(eqo("conf/vldb/GionisIM99","3RR94IxW5CUJ")).
pos(eqo("conf/vldb/GoldmanSVG98","4qYPBQ1l07YJ")).
pos(eqo("conf/vldb/GoldmanW97","EM5uAeHdNEIJ")).
pos(eqo("conf/vldb/GoldmanW97","Ye9iUyg5mL0J")).
pos(eqo("conf/vldb/GoldmanW97","xK7GOJjKJzgJ")).
pos(eqo("conf/vldb/GoldsteinR00","ylZFc8RNoeQJ")).
pos(eqo("conf/vldb/GoodmanRS94","8CCHAKnGJ1EJ")).
pos(eqo("conf/vldb/GottlobKP02","e5Gm5upjQnkJ")).
pos(eqo("conf/vldb/GoyalHSS95","fPgtEqv986IJ")).
pos(eqo("conf/vldb/GraefeBC98","v-kvo2hnsgkJ")).
pos(eqo("conf/vldb/GuPS00","W-hUzvTqikcJ")).
pos(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
pos(eqo("conf/vldb/HammadFAE03","vfCFumS9QtkJ")).
pos(eqo("conf/vldb/HelmerNM03","8-HpAN0xpjcJ")).
pos(eqo("conf/vldb/HjelsvoldM94","5Wuyp1aLBocJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","7y9SomIIAG0J")).
pos(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
pos(eqo("conf/vldb/HumborstadSHT97","TjJZGlCajbMJ")).
pos(eqo("conf/vldb/HuntAI01","0GT_dHqK5roJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","V98z3uzuvpQJ")).
pos(eqo("conf/vldb/JagadishLRSS94","Yiwh22hbTAcJ")).
pos(eqo("conf/vldb/JagadishMN99","RPWDtUmq6_QJ")).
pos(eqo("conf/vldb/JagadishMN99","YtVG0hVxFI8J")).
pos(eqo("conf/vldb/JarkeKL00","6c3XQZ-_HDUJ")).
pos(eqo("conf/vldb/JarkeKL00","hRr_IBVG0-YJ")).
pos(eqo("conf/vldb/JensenL01","yUDkYbmDTXIJ")).
pos(eqo("conf/vldb/JermaineDO99","h6R5rXre-_QJ")).
pos(eqo("conf/vldb/KamelF94","ONuqAb6sM3oJ")).
pos(eqo("conf/vldb/KamelF94","SuPC457J-a0J")).
pos(eqo("conf/vldb/KeimH99","28GZ8M1ZPVYJ")).
pos(eqo("conf/vldb/Keogh02","rKIsQpbRiM0J")).
pos(eqo("conf/vldb/Kleewein96","rXaCSxty6AAJ")).
pos(eqo("conf/vldb/KnorrN98","r8uYvAGT6swJ")).
pos(eqo("conf/vldb/KnorrN99","7J-gi_InWY0J")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/vldb/KornSFSP96","I8YNDqO9pg8J")).
pos(eqo("conf/vldb/KornSFSP96","VL_cnRotMQcJ")).
pos(eqo("conf/vldb/KornSFSP96","qdLbwgIRnvgJ")).
pos(eqo("conf/vldb/KornSFSP96","xQU9GXs4k50J")).
pos(eqo("conf/vldb/KoschBBHHLRT01","xvNBOkc3UkcJ")).
pos(eqo("conf/vldb/KumarRRT99","fJn_2E8aihYJ")).
pos(eqo("conf/vldb/LempelM02","DcSYGPdhxwoJ")).
pos(eqo("conf/vldb/LiCHPALHAY01","Nn0x6RmkrVwJ")).
pos(eqo("conf/vldb/LiRS99","cGbo_ZtYKwYJ")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/LockemannKKKN97","mFJzfuwL1jcJ")).
pos(eqo("conf/vldb/MadhavanBR01","66dWDpWjbbwJ")).
pos(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
pos(eqo("conf/vldb/MeccaCM01","zd9Ql77Uk2gJ")).
pos(eqo("conf/vldb/MeekPK03","cR1ikuFsE1wJ")).
pos(eqo("conf/vldb/MeoPC96","_jeGsG2xolAJ")).
pos(eqo("conf/vldb/MillerHH00","6vtHcpLApB8J")).
pos(eqo("conf/vldb/MillerHH00","KTp2S_xbXfYJ")).
pos(eqo("conf/vldb/MillerHH00","YQ0D98oeJKMJ")).
pos(eqo("conf/vldb/MillerHH00","kfTc_TsqiP8J")).
pos(eqo("conf/vldb/Mohan96","wYwNJy4GsEYJ")).
pos(eqo("conf/vldb/MohaniaS94","JORYEDHKYSMJ")).
pos(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
pos(eqo("conf/vldb/NatsevCSLV01","lD7OgF3Xw6wJ")).
pos(eqo("conf/vldb/NicklasGS03","zApMW7wX5-AJ")).
pos(eqo("conf/vldb/OConnellWG01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672185")).
pos(eqo("conf/vldb/Objectivity98","o3fkxpcCBskJ")).
pos(eqo("conf/vldb/Ogawa96","zQDbTpO9kH4J")).
pos(eqo("conf/vldb/OlstonW00","1uei4ivV-PgJ")).
pos(eqo("conf/vldb/OlstonW00","R_hYW6eIUuYJ")).
pos(eqo("conf/vldb/OzsuVU98","tftfK6qWKJcJ")).
pos(eqo("conf/vldb/PardonA00","k7G60pXtD58J")).
pos(eqo("conf/vldb/PellenkoftLK97","793XPMTdcBEJ")).
pos(eqo("conf/vldb/PetrovicBJ03","nIuz3dc8yHMJ")).
pos(eqo("conf/vldb/PfoserJT00","YBNEZgmh540J")).
pos(eqo("conf/vldb/PottingerL00","M2zV0WBF7XYJ")).
pos(eqo("conf/vldb/QianZXP03","Chp-3UwMgTQJ")).
pos(eqo("conf/vldb/RastogiS98","yztQfwBZU6EJ")).
pos(eqo("conf/vldb/RohmBSS02","YMcmy4FOXi8J")).
pos(eqo("conf/vldb/RothOH99","OslUAjJi_B4J")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","019zSr3Lx4EJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","T2fm7Wb1ak4J")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/ScheuermannSV96","42whesD5Rl8J")).
pos(eqo("conf/vldb/ScheuermannSV96","kxebBNLKWl4J")).
pos(eqo("conf/vldb/Schoning03","4NM5WR1WtPcJ")).
pos(eqo("conf/vldb/SeligmanBNSW95","T6a86CQCuHoJ")).
pos(eqo("conf/vldb/SeshadriLR96","K62EwWeSRKUJ")).
pos(eqo("conf/vldb/SeshadriLR96","ifOM4z6uxXUJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/ShegalovWBL02","CzVyfZe-kj0J")).
pos(eqo("conf/vldb/ShengBDM02","TdjMAASfHFoJ")).
pos(eqo("conf/vldb/Shmueli01","rEwEqoAns-gJ")).
pos(eqo("conf/vldb/SindoniTABFGMPPT01","0zdXnl9cQysJ")).
pos(eqo("conf/vldb/SistlaYLL95","lkNgibBst0MJ")).
pos(eqo("conf/vldb/SistlaYLL95","n1ixxafAD_EJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","01ZVDudF4WAJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","WvvY_Ao19mAJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","oQJNqlgXUbgJ")).
pos(eqo("conf/vldb/StaudtJ96","6moFnThDHW0J")).
pos(eqo("conf/vldb/SteenhagenABB94","IgWfWMn1_AAJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Xr2RguUzt-gJ")).
pos(eqo("conf/vldb/StohrR01","jn3pvb3hRzwJ")).
pos(eqo("conf/vldb/TanEO01","1A06w64wjvcJ")).
pos(eqo("conf/vldb/TanEO01","bTjeXC-1wf4J")).
pos(eqo("conf/vldb/TanSHCR01","hPcNG0tPwgIJ")).
pos(eqo("conf/vldb/Toivonen96","R3wCZGqY0nYJ")).
pos(eqo("conf/vldb/Tygar98","Q8cPIOWKZZ4J")).
pos(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
pos(eqo("conf/vldb/VassalosP97","5DKaP73v7FQJ")).
pos(eqo("conf/vldb/VassalosP97","i6gPl8JN3ycJ")).
pos(eqo("conf/vldb/VassalosP97","vPKoA4R_sU8J")).
pos(eqo("conf/vldb/VenkataramanZ98","KrAyBSajhZEJ")).
pos(eqo("conf/vldb/VenkataramanZ98","RGh6Gep4ym8J")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/WuFSP00","XojbAfbtdvcJ")).
pos(eqo("conf/vldb/YangG01","0Chz95gOxHMJ")).
pos(eqo("conf/vldb/YangG01","g8raVwL_ICIJ")).
pos(eqo("conf/vldb/YangG01","xQYKEHCggZQJ")).
pos(eqo("conf/vldb/ZellerK02","UIWreKZndVQJ")).
pos(eqo("conf/vldb/ZhangL98","ZjHAEBJYahAJ")).
pos(eqo("conf/vldb/ZhuS02","iuyRrJJDBcIJ")).
pos(eqo("conf/vldb/ZurekS99","mEdoUlcnDsgJ")).
pos(eqo("journals/sigmod/Aberer01","7CLhi_LOtoUJ")).
pos(eqo("journals/sigmod/Aberer02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aggarwal01","OE8gpNwz8MkJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","qiD9O54GtckJ")).
pos(eqo("journals/sigmod/BaaderJN97","SxT807RR-NsJ")).
pos(eqo("journals/sigmod/BaaderJN97","dr4SzOhnLB8J")).
pos(eqo("journals/sigmod/BabuW01","VLOGPMjpyZ0J")).
pos(eqo("journals/sigmod/Barbara01","U8tEHzJ2Xj0J")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarclayBGS94","v1aol6mmLdMJ")).
pos(eqo("journals/sigmod/BargaL02","fY3kkkzBLw8J")).
pos(eqo("journals/sigmod/BergamaschiCV99","iiyN4FT7v90J")).
pos(eqo("journals/sigmod/Bernstein98","AYEI8XDoY9wJ")).
pos(eqo("journals/sigmod/Bernstein98","qCvPRNWJZNEJ")).
pos(eqo("journals/sigmod/BernsteinDK99","MsK0xHsckUIJ")).
pos(eqo("journals/sigmod/BernsteinDK99","Ye5fTBiMoUwJ")).
pos(eqo("journals/sigmod/Bohlen95","LwKKzfi_MpUJ")).
pos(eqo("journals/sigmod/Bohlen95","OE9R26sjxoUJ")).
pos(eqo("journals/sigmod/BohmR94","GXApzwcGl78J")).
pos(eqo("journals/sigmod/BoulosO99","yzbCsw2erkcJ")).
pos(eqo("journals/sigmod/CampbellEM03","N9u28V6NZTIJ")).
pos(eqo("journals/sigmod/CatarciC96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245888%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Chaudhri95","DY6x1fDAy9EJ")).
pos(eqo("journals/sigmod/CheungF98","ujeEtXpQFIsJ")).
pos(eqo("journals/sigmod/ClementiniF00","9_GTdteKEYsJ")).
pos(eqo("journals/sigmod/Critchlow01","wuQbvQAcACsJ")).
pos(eqo("journals/sigmod/Danish98","J2Mi5B81Il0J")).
pos(eqo("journals/sigmod/Danish98","mKZyoPZArGcJ")).
pos(eqo("journals/sigmod/DarwenD95","DVnOcHunv7MJ")).
pos(eqo("journals/sigmod/DarwenD95","Ppe_v5Zt140J")).
pos(eqo("journals/sigmod/DarwenD95","Xa_whOlvG7gJ")).
pos(eqo("journals/sigmod/Datta94","3TVyZeq1-i4J")).
pos(eqo("journals/sigmod/Dogac96","url:http://portal.acm.org/citation.cfm%3Fid%3D234889.234900%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DogacAOD95","oUOuTMrB0esJ")).
pos(eqo("journals/sigmod/EisenbergM99","Ciq01lHglkAJ")).
pos(eqo("journals/sigmod/ElmagarmidJF95","CJK2SWLYrRYJ")).
pos(eqo("journals/sigmod/FininJ02","rg8576nvnkUJ")).
pos(eqo("journals/sigmod/FowlerPNB99","Mo-tkboGfcoJ")).
pos(eqo("journals/sigmod/FowlerPNB99","OewAZ4AUDOQJ")).
pos(eqo("journals/sigmod/FowlerPNB99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310060%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ERqqWPMwU2sJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","HJRR7GGfD6sJ")).
pos(eqo("journals/sigmod/FreemanG96","Em3qp7RGalkJ")).
pos(eqo("journals/sigmod/GatziuKBF98","C8tPNXRbNnIJ")).
pos(eqo("journals/sigmod/GatziuKBF98","GlHmit1yw6AJ")).
pos(eqo("journals/sigmod/GatziuKBF98","YERfAnxw2RcJ")).
pos(eqo("journals/sigmod/GolabO03","MTZdbBk3MQsJ")).
pos(eqo("journals/sigmod/Grohe02","RnmBv4e85pMJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","ihljCMaS2UsJ")).
pos(eqo("journals/sigmod/GuptaHR97","-ha8fD8Kj_oJ")).
pos(eqo("journals/sigmod/Hainaut03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959087%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HansonN99","vM_HYDYFeJ0J")).
pos(eqo("journals/sigmod/HaritsaS96","qA7JBQahK3wJ")).
pos(eqo("journals/sigmod/HasselbringHHKRRS00","X9PsaiaoDJ4J")).
pos(eqo("journals/sigmod/HasselbringHHKRRS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369277%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JainH94","iQMUP3fkvo4J")).
pos(eqo("journals/sigmod/JajodiaBBKMSW97","url:http://portal.acm.org/citation.cfm%3Fid%3D271095")).
pos(eqo("journals/sigmod/Jannink95","22yR9rN5xuQJ")).
pos(eqo("journals/sigmod/JenningsNF98","vgi1l8lbDcsJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","CFMujYunuKcJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","WJ_VcY3mmEkJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","rRrT0v_j7tkJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JensenCEGHJ94","xFQWX4M8E2YJ")).
pos(eqo("journals/sigmod/KannanKIK03","h_tDfTvsR0QJ")).
pos(eqo("journals/sigmod/KarlapalemLS95","B_m0Yp4aycUJ")).
pos(eqo("journals/sigmod/Keim96","vkUvhZOw-1YJ")).
pos(eqo("journals/sigmod/KlasS94","bViLh5-jVsAJ")).
pos(eqo("journals/sigmod/KoksalAD98","c2UQ3AM5_f8J")).
pos(eqo("journals/sigmod/Konig-RiesL97","3fQBks2g-BMJ")).
pos(eqo("journals/sigmod/KuanL99","lkrtCULVA6oJ")).
pos(eqo("journals/sigmod/Libkin99","V_FnUWKirh8J")).
pos(eqo("journals/sigmod/Libkin99","zSO1Y5W7WkwJ")).
pos(eqo("journals/sigmod/McClatcheyV97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MedskerCS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltzerC98","-wQ-mpGIWdMJ")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NascimentoSP03","G3QWq2T08SEJ")).
pos(eqo("journals/sigmod/NestorovAM97","NVS_rDpScp0J")).
pos(eqo("journals/sigmod/NgH95","url:http://portal.acm.org/citation.cfm%3Fid%3D202660.202665%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/PoessF00","t4-_Dfpk2SMJ")).
pos(eqo("journals/sigmod/PoessF00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369291%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/PourabbasR00","3y6y5AXu-j0J")).
pos(eqo("journals/sigmod/PourabbasR00","odFtqwn5ZVcJ")).
pos(eqo("journals/sigmod/Qian96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/QuixSJ02","BrO3XOrt66MJ")).
pos(eqo("journals/sigmod/RosenthalS99","AaKiSc1klw8J")).
pos(eqo("journals/sigmod/RosenthalS99","ZYnsLI6mz2cJ")).
pos(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D202672")).
pos(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202672%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Snodgrass03b","PmIVKWJ5_V4J")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","64iWa-ZiPRcJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","psdMY-oUz4cJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","vUONDuuNNCQJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94a","biv7Nf9qwBYJ")).
pos(eqo("journals/sigmod/SycaraKWL99","-IaXJNRxKVEJ")).
pos(eqo("journals/sigmod/SycaraKWL99","7OyvdUHeptMJ")).
pos(eqo("journals/sigmod/SycaraKWL99","foOIj5nrS-gJ")).
pos(eqo("journals/sigmod/TianDCZ02","eeCoB5sDWK4J")).
pos(eqo("journals/sigmod/TsotrasK96","9HEdn3A13BQJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/VelACM01","LseDURw3BXMJ")).
pos(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
pos(eqo("journals/sigmod/dOnofrioP03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776990%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/BaekgaardM95","6UycFCZooDoJ")).
pos(eqo("journals/tods/BeneventanoBS03","rRH6Z1oP78cJ")).
pos(eqo("journals/tods/BertinoBFS98","BTIrFatQWQsJ")).
pos(eqo("journals/tods/BohlenJS00","6eheB6Kct4MJ")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/tods/CasatiCPP99","12JXvv17ugoJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","_nOW6fmEcTEJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","eHY42LnL_lsJ")).
pos(eqo("journals/tods/Chen95a","qexCEm3QaUgJ")).
pos(eqo("journals/tods/EiterLLS01","lTwQVB8E7SIJ")).
pos(eqo("journals/tods/EiterLLS01","tEZIquYevQoJ")).
pos(eqo("journals/tods/FraternaliT95","sh-E7oORhVMJ")).
pos(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
pos(eqo("journals/tods/FukudaMMT01","_2f7zWIzK0QJ")).
pos(eqo("journals/tods/FukudaMMT01","lmXiI4fB9vgJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","TQ8M8qOzJO8J")).
pos(eqo("journals/tods/Galindo-LegariaR97","Vjga5yC23KIJ")).
pos(eqo("journals/tods/Hellerstein98","dtYwk-vb8DUJ")).
pos(eqo("journals/tods/Hellerstein98","q8m4M7OxSSAJ")).
pos(eqo("journals/tods/Hellerstein98","zp--hf4KJMAJ")).
pos(eqo("journals/tods/LitwinN96","l0W27c1C3NwJ")).
pos(eqo("journals/tods/LiuHD98","aYjE-ILUHaoJ")).
pos(eqo("journals/tods/LiuHD98","ts7DF925TR8J")).
pos(eqo("journals/tods/LiuM96","moMP8RcSDhgJ")).
pos(eqo("journals/tods/LiuM96","xeceK06Z5DIJ")).
pos(eqo("journals/tods/Meo00","NQShGztSLaoJ")).
pos(eqo("journals/tods/MokNE96","xUeP4X8k5SoJ")).
pos(eqo("journals/tods/Ross96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D232628%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/SchuldtABS02","zrQPbIIo2E8J")).
pos(eqo("journals/tods/TariSS97","iMM-Ho95algJ")).
pos(eqo("journals/tods/ZobelMR98","nX85t01_KugJ")).
pos(eqo("journals/tods/ZobelMR98","tdDLf6RffisJ")).
pos(eqo("journals/vldb/AilamakiDH02","J9MeFW0vDJAJ")).
pos(eqo("journals/vldb/AlbanoGO95","_tswCGHoswMJ")).
pos(eqo("journals/vldb/AntoshenkovZ96","N8syKKPN6IoJ")).
pos(eqo("journals/vldb/BarbaraI95","7N0H3ra1FFsJ")).
pos(eqo("journals/vldb/BarbaraI95","F7azEOfg-Q0J")).
pos(eqo("journals/vldb/BarbaraI95","UI4WYndJlyIJ")).
pos(eqo("journals/vldb/BarbaraI95","bMUUwjP72hwJ")).
pos(eqo("journals/vldb/BarbaraI95","bTYTn8VG5hIJ")).
pos(eqo("journals/vldb/BarbaraI95","gyC0D8oJbQMJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","2TVYDBNYioIJ")).
pos(eqo("journals/vldb/ChanFGR02","sheXatSCreQJ")).
pos(eqo("journals/vldb/ChandrasekaranF03","b9r9U3OwrkcJ")).
pos(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
pos(eqo("journals/vldb/DattaDVRN01","q0Ovw6QUk3MJ")).
pos(eqo("journals/vldb/DiazJ97","RKAY1aZAeCoJ")).
pos(eqo("journals/vldb/GeorgakopoulosRL94","G85JsnuAjzMJ")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/Guting94","2HXoDqKjpXYJ")).
pos(eqo("journals/vldb/Guting94","NE_HjaA2eAAJ")).
pos(eqo("journals/vldb/Guting94","hoNylhoOWr4J")).
pos(eqo("journals/vldb/Halevy02","url:http://www.springerlink.com/index/6UEYKJ4UQTK18H6D.pdf")).
pos(eqo("journals/vldb/HelmerM03","lqAgqxpXpxMJ")).
pos(eqo("journals/vldb/KabraD99","UAxAXYysL-UJ")).
pos(eqo("journals/vldb/KraissW98","LMz7v87sxxYJ")).
pos(eqo("journals/vldb/LeeSC01","Hz_TU6kUj08J")).
pos(eqo("journals/vldb/LinJF94","vmxFQL7lhKoJ")).
pos(eqo("journals/vldb/ManegoldBK00","6GAoBRINv7kJ")).
pos(eqo("journals/vldb/ManegoldBK00","bPCHuDzkKY4J")).
pos(eqo("journals/vldb/ManegoldBK00","jsNNCDiD0yIJ")).
pos(eqo("journals/vldb/MehtaD97","VPX141ia9EcJ")).
pos(eqo("journals/vldb/MylopoulosCPST96","F5liQDe9lB8J")).
pos(eqo("journals/vldb/RafieiM02","kZFfJieudW4J")).
pos(eqo("journals/vldb/RamamurthyDS03","uem5wXLoU0wJ")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","FnypYUw9pwEJ")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","dWgXDMGuFd4J")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","xomFMCDegw8J")).
pos(eqo("journals/vldb/TanGO00","url:http://www.springerlink.com/index/4N8LT3XHXGCR8DLW.pdf")).
pos(eqo("journals/vldb/TsatalosSI96","zt5Ck1PrGf0J")).
pos(eqo("journals/vldb/TurkerG01","Jab63JLU3N0J")).
pos(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
pos(eqo("journals/vldb/ZezulaSAR98","DM9hrpKpqmMJ")).
