neg(eqo("conf/sigmod/AcharyaFZ97","oH_xfQI8wIgJ")).
neg(eqo("conf/sigmod/AcharyaGPR99","WbsAK4ZE17YJ")).
neg(eqo("conf/sigmod/AcharyaGPR99a","smzeHDQ3zbMJ")).
neg(eqo("conf/sigmod/AdaliBSS98","rYC-j_j4Yv0J")).
neg(eqo("conf/sigmod/AdamY98","xn5WXTbF5aAJ")).
neg(eqo("conf/sigmod/AdelbergGK95","b87rz7o7R94J")).
neg(eqo("conf/sigmod/Aggarwal02","UP5J0RMIptAJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","vT6v9qSkI2UJ")).
neg(eqo("conf/sigmod/AggarwalY00","wi8177RdPBYJ")).
neg(eqo("conf/sigmod/AgrawalASY97","AkicmAIQVYsJ")).
neg(eqo("conf/sigmod/AltinelABFSZ99","6x6fxq-N6cEJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","VJIHPbki2uAJ")).
neg(eqo("conf/sigmod/AntonJLPZZ02","url:http://www.springerlink.com/index/Q4G405N136278G44.pdf")).
neg(eqo("conf/sigmod/AshleyFHLNP95","24bBDJoQZwoJ")).
neg(eqo("conf/sigmod/Atkinson95","OxVQMeJsXngJ")).
neg(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
neg(eqo("conf/sigmod/Ballinger94","jj8LgniKbsMJ")).
neg(eqo("conf/sigmod/Bampahl95","MbgdgwgZCIUJ")).
neg(eqo("conf/sigmod/BarbaraI94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D273247%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BaumannDFRW98","7iDOOYCF5MQJ")).
neg(eqo("conf/sigmod/BaumannDFRW98","T9mhgoged8AJ")).
neg(eqo("conf/sigmod/BaumannDFRW98","jxL7i2xXm2EJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","S-aEcHjpLBMJ")).
neg(eqo("conf/sigmod/BersonGM95","4fjXoCHhe1kJ")).
neg(eqo("conf/sigmod/BhattacharyaMBNHS02","KxwymZ2AGNQJ")).
neg(eqo("conf/sigmod/BilirisDGJR94","lG6uSYhEGnQJ")).
neg(eqo("conf/sigmod/BilirisP94","KYhmilHkq_IJ")).
neg(eqo("conf/sigmod/BohmBKK01","C4XcBh6anhAJ")).
neg(eqo("conf/sigmod/BohmBKK01","k_WEhF7DpYkJ")).
neg(eqo("conf/sigmod/BornhovdAKMPR03","Yi03tvebyKUJ")).
neg(eqo("conf/sigmod/BrinDG95","bUvKrCjhep0J")).
neg(eqo("conf/sigmod/Brown99","SDHfnislCbwJ")).
neg(eqo("conf/sigmod/BryanMCLG94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D101082%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BunemanDHS96","hn2MANNgz9sJ")).
neg(eqo("conf/sigmod/CallanCD99","eU-7sSXW5jEJ")).
neg(eqo("conf/sigmod/Carey94","HKczT7lMewAJ")).
neg(eqo("conf/sigmod/CareyK97","Y1HVgTopekIJ")).
neg(eqo("conf/sigmod/CatarciS01","ga4l4QhCXU4J")).
neg(eqo("conf/sigmod/CatarciS94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974142%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CeriFP98","8zFEVer1rBUJ")).
neg(eqo("conf/sigmod/CeriFP98","QyA8LLrWIloJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","DZI4GwpYBOcJ")).
neg(eqo("conf/sigmod/Chan98","-i2fQfLpX2wJ")).
neg(eqo("conf/sigmod/Chaudhuri97","jsapF3OoWXcJ")).
neg(eqo("conf/sigmod/Chaudhuri97","qfohkpyTawoJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","6YgzNu3UQqMJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","TqXFdQBTW6kJ")).
neg(eqo("conf/sigmod/ChenDLT00","YemauUgIzlcJ")).
neg(eqo("conf/sigmod/ChenGM01","ebUGYYz71SsJ")).
neg(eqo("conf/sigmod/ChenR94","4Hhh-d__bksJ")).
neg(eqo("conf/sigmod/ChoALS03","bZj9gl0_YUIJ")).
neg(eqo("conf/sigmod/Chong98","7R2MwKC9EIQJ")).
neg(eqo("conf/sigmod/ChooOLCGBPS96","qolJkVC2MoYJ")).
neg(eqo("conf/sigmod/ChristophidesCM96","4EgMtIywBRUJ")).
neg(eqo("conf/sigmod/ClaypoolRZSK01","HzwYxTRODBIJ")).
neg(eqo("conf/sigmod/Cohen98","a3j5YRXnPIQJ")).
neg(eqo("conf/sigmod/Cohen98a","9_HY4pYNlpAJ")).
neg(eqo("conf/sigmod/Cohen98a","CrpDX_PsEMIJ")).
neg(eqo("conf/sigmod/ColbyKLMR97","25hGiPZCMqoJ")).
neg(eqo("conf/sigmod/Colliat03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390002%26type%3Dpdf")).
neg(eqo("conf/sigmod/CrescenziMM02","r3Td_K_A2J4J")).
neg(eqo("conf/sigmod/CruzJ99","JWodDU0EKaUJ")).
neg(eqo("conf/sigmod/CuiOTS03","qx5oR09jmMwJ")).
neg(eqo("conf/sigmod/DasGR03","JaJKfzmaEBYJ")).
neg(eqo("conf/sigmod/DraperHW01","mITL2ypCNK0J")).
neg(eqo("conf/sigmod/Epstein95","FdkHUCk1ocUJ")).
neg(eqo("conf/sigmod/FegarasSRM00","yXuSqhXBMa0J")).
neg(eqo("conf/sigmod/Fernandez94","SnkWnX5WoKwJ")).
neg(eqo("conf/sigmod/Freeston95","Bhv77X8SnakJ")).
neg(eqo("conf/sigmod/FreireHRRS02","4Uf5sjXgwhoJ")).
neg(eqo("conf/sigmod/Gal00","L1NPuPUFsMcJ")).
neg(eqo("conf/sigmod/Galindo-LegariaJ01","E6Z68tQL1BsJ")).
neg(eqo("conf/sigmod/GarofalakisRRS99","url:http://portal.acm.org/citation.cfm%3Fid%3D882082.882084%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GebhardtJJ97","Vj1kbPjzSHwJ")).
neg(eqo("conf/sigmod/Gerber95","ztpceRBO43EJ")).
neg(eqo("conf/sigmod/GetoorTK01","WOjMKlT2eUAJ")).
neg(eqo("conf/sigmod/Gibson95","Z3KjBnqZLtkJ")).
neg(eqo("conf/sigmod/GodfreySE98","coNBTxEjQIUJ")).
neg(eqo("conf/sigmod/Golding95","FN5Faq5Glz0J")).
neg(eqo("conf/sigmod/GoldsteinL01","94TyP9PsptAJ")).
neg(eqo("conf/sigmod/GotoK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D872837%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GravanoGT94","MDuQ-F6T9hcJ")).
neg(eqo("conf/sigmod/GraySSU03","X94gDE70Zn0J")).
neg(eqo("conf/sigmod/Greer99","gUOGySLStAsJ")).
neg(eqo("conf/sigmod/HammerGNYBV97","8-eaDTdtfY4J")).
neg(eqo("conf/sigmod/Han96","mRfBKq6_RKkJ")).
neg(eqo("conf/sigmod/HanKK97","MqdtZ_cUxDEJ")).
neg(eqo("conf/sigmod/HanPDW01","XyYCahzDAh8J")).
neg(eqo("conf/sigmod/Hellerstein00","9mbr0dyW1NgJ")).
neg(eqo("conf/sigmod/HellersteinN96","_hDCldPyum0J")).
neg(eqo("conf/sigmod/HernandezS95","XtiA4VL9SHwJ")).
neg(eqo("conf/sigmod/HsuLG00","vM8TnB6ToEcJ")).
neg(eqo("conf/sigmod/Jagadish94","b5TqRnEMMGkJ")).
neg(eqo("conf/sigmod/JajodiaSSB97","AYtrcxExrbkJ")).
neg(eqo("conf/sigmod/JarkeQBLMS99","Gq6D6zMEPxoJ")).
neg(eqo("conf/sigmod/Jhingran00","5ABoNn0c3FUJ")).
neg(eqo("conf/sigmod/JonssonFS98","5fb1l1MyGisJ")).
neg(eqo("conf/sigmod/KanthAS98","t_HlE-Mxf74J")).
neg(eqo("conf/sigmod/KanthRSB99","oulaZpEWkMQJ")).
neg(eqo("conf/sigmod/Keim99","ujg5Elnh7scJ")).
neg(eqo("conf/sigmod/KiepuszewskiMO98","CTDpT1x-0g8J")).
neg(eqo("conf/sigmod/Kim94","mqyrrGBsGD0J")).
neg(eqo("conf/sigmod/KotidisR98","_q4Zfz6cXOkJ")).
neg(eqo("conf/sigmod/KotidisR99","EWDPecQbT1AJ")).
neg(eqo("conf/sigmod/KoudasS03","F0VufxHFRP8J")).
neg(eqo("conf/sigmod/KoudasS97","BZfdROjhbhwJ")).
neg(eqo("conf/sigmod/KoudasS97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D71039%26type%3Dpdf")).
neg(eqo("conf/sigmod/Kulkarni94","5CEZ0sZyArYJ")).
neg(eqo("conf/sigmod/LakshmananNHP99","NffWJWoUDK0J")).
neg(eqo("conf/sigmod/LarsonG98","u99HqlQt9jEJ")).
neg(eqo("conf/sigmod/LehnerSPC00","da9nUyVHeXcJ")).
neg(eqo("conf/sigmod/Levine95","SsOLRJZrmtYJ")).
neg(eqo("conf/sigmod/Levine95","eKMjugY6j10J")).
neg(eqo("conf/sigmod/LibkinMW96","6ussAgzdL6oJ")).
neg(eqo("conf/sigmod/LiuPTBBZBHY98","ezlAkB7ijDUJ")).
neg(eqo("conf/sigmod/LometW98","JvZ9JWtn72QJ")).
neg(eqo("conf/sigmod/LometW98","_nchwJeHhNUJ")).
neg(eqo("conf/sigmod/LuoEHN02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1041419%26type%3Dpdf")).
neg(eqo("conf/sigmod/MaddenSHR02","WTL1JzbWWjIJ")).
neg(eqo("conf/sigmod/MarklL02","11Ns5975X2gJ")).
neg(eqo("conf/sigmod/McAuliffeCS96","MmpM31Xn2qQJ")).
neg(eqo("conf/sigmod/Mohan01","bfLZp1c7E1cJ")).
neg(eqo("conf/sigmod/Mohan94","7w05tSBkqmcJ")).
neg(eqo("conf/sigmod/Mohan94","YJlUtEk7zwkJ")).
neg(eqo("conf/sigmod/MoleskyR95","F7AdjoH_uTcJ")).
neg(eqo("conf/sigmod/MoonSL00","1m9BmEzgbBYJ")).
neg(eqo("conf/sigmod/MoonSL00","qK-N8yVLSWUJ")).
neg(eqo("conf/sigmod/Mylopoulos98","Gw_ENWFYGJQJ")).
neg(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
neg(eqo("conf/sigmod/Nori00","KxwymZ2AGNQJ")).
neg(eqo("conf/sigmod/ONeilQ97","I9JXY0-R4GgJ")).
neg(eqo("conf/sigmod/OlstonWACELSS98","M8vY5Zp_--gJ")).
neg(eqo("conf/sigmod/OlstonWL01","BgYYrXgmX7sJ")).
neg(eqo("conf/sigmod/OlstonWL01","wneAqf0i-REJ")).
neg(eqo("conf/sigmod/PangCL94","Pbjz4-UPrZ8J")).
neg(eqo("conf/sigmod/PangCL94","tzN6jRgEfdsJ")).
neg(eqo("conf/sigmod/PapakonstantinouPV02","Syu5W-3uFFAJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","Hj3vyh0TJVsJ")).
neg(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
neg(eqo("conf/sigmod/Pruscino03","C8zZR4fIq2AJ")).
neg(eqo("conf/sigmod/RadekeBBEKKN95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202672%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RajagopalanML98","PVUtZWBcxlAJ")).
neg(eqo("conf/sigmod/RajagopalanML98","SUT-QTwqFNkJ")).
neg(eqo("conf/sigmod/RamakrishnanD98","61cw9DcC6qsJ")).
neg(eqo("conf/sigmod/RamakrishnanD98","Zqu15MYjpFYJ")).
neg(eqo("conf/sigmod/Ramanan02","xrGxxmqz4G8J")).
neg(eqo("conf/sigmod/RamaswamyRS00","HLu7MvWb5rMJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","QsmO94ilmrEJ")).
neg(eqo("conf/sigmod/RaoZML02","odFtqwn5ZVcJ")).
neg(eqo("conf/sigmod/ReveszCKLLW00","_5qjkaGVCP8J")).
neg(eqo("conf/sigmod/RodriguezR00","tFfCZHHffocJ")).
neg(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
neg(eqo("conf/sigmod/RoussopoulosKV95","url:http://portal.acm.org/citation.cfm%3Fid%3D16857")).
neg(eqo("conf/sigmod/RundensteinerCLCZNJLW99","7JRwRy6VapMJ")).
neg(eqo("conf/sigmod/SeshadriLR94","ypHBb35DGMgJ")).
neg(eqo("conf/sigmod/ShklarSKT95","4IaWCBK6dMQJ")).
neg(eqo("conf/sigmod/ShouCTRH01","WrrEnOJswS4J")).
neg(eqo("conf/sigmod/SistlaW95","QVDW9nJubnAJ")).
neg(eqo("conf/sigmod/SistlaW95","_5vTibIifgMJ")).
neg(eqo("conf/sigmod/Smith01","vLYloZqZZXEJ")).
neg(eqo("conf/sigmod/Stonebraker98","ajP7a2ZOOa8J")).
neg(eqo("conf/sigmod/Tajima96","e0j-56kaeR4J")).
neg(eqo("conf/sigmod/TaoP02","fDWfHiQ6BR4J")).
neg(eqo("conf/sigmod/Team95a","kdU4iiwLli8J")).
neg(eqo("conf/sigmod/TheobaldW02","PsI2n6z5CBAJ")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","EPP4T-fp2MgJ")).
neg(eqo("conf/sigmod/ThomasDM95","4pZEi-wH49UJ")).
neg(eqo("conf/sigmod/ThomasDM95","8CKDKUPVOnwJ")).
neg(eqo("conf/sigmod/TsueiPK97","kMnS4wdzW7wJ")).
neg(eqo("conf/sigmod/VanceM96","-XugBF7u07EJ")).
neg(eqo("conf/sigmod/VingralekBW94","WuGlPonzYNYJ")).
neg(eqo("conf/sigmod/WoelkBJOTU95","6syclrA0QK8J")).
neg(eqo("conf/sigmod/Wu99","JWodDU0EKaUJ")).
neg(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
neg(eqo("conf/sigmod/YerneniLGU99","L9rzYv5OWpgJ")).
neg(eqo("conf/sigmod/ZhaoDN97","otiCho8rdNgJ")).
neg(eqo("conf/sigmod/ZhuSZ03","_OLNvAeDNyYJ")).
neg(eqo("conf/sigmod/ZhugeGHW95","YHqWRKR_lC8J")).
neg(eqo("conf/sigmod/ZhugeGHW95","_XLK2p-e2pYJ")).
neg(eqo("conf/sigmod/ZouS96","Ng8CP2M8eUQJ")).
neg(eqo("conf/sigmod/ZouS96","TUzhq1PjPsgJ")).
neg(eqo("conf/sigmod/ZuzartePMCLW03","qhIOMa1pk0gJ")).
neg(eqo("conf/vldb/AbiteboulBMMW02","AWT9oagMfNMJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","t0Asg9xms9YJ")).
neg(eqo("conf/vldb/AboulnagaAN01","a78Lxr80kJUJ")).
neg(eqo("conf/vldb/AgrawalPWZ95","-2Ib1nqgXbcJ")).
neg(eqo("conf/vldb/AgrawalS94","cUVJ8Svrad0J")).
neg(eqo("conf/vldb/AgrawalS94","vT6v9qSkI2UJ")).
neg(eqo("conf/vldb/AksoyZF01","z6Z1hQYHTAMJ")).
neg(eqo("conf/vldb/AmirKN01","Kh-cEER6s8QJ")).
neg(eqo("conf/vldb/AndreiV01","gIScA-hLMsIJ")).
neg(eqo("conf/vldb/ArunJ98","1dqeMksCm74J")).
neg(eqo("conf/vldb/BalminPP00","xWgxEU5Vop0J")).
neg(eqo("conf/vldb/BaumgartnerFG01a","3VhOqv3STbEJ")).
neg(eqo("conf/vldb/BawaBA03","r6hY-uJVxBYJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","bmgRzQitR1YJ")).
neg(eqo("conf/vldb/BerchtoldKK96","4Uf5sjXgwhoJ")).
neg(eqo("conf/vldb/Bernstein94","BmV2iPuXZeMJ")).
neg(eqo("conf/vldb/Bernstein94","Gr3-L-wyIOcJ")).
neg(eqo("conf/vldb/BernsteinHSSZ97","62aA4DYB0MQJ")).
neg(eqo("conf/vldb/BernsteinHSSZ97","nu55xP_Z81AJ")).
neg(eqo("conf/vldb/BestavrosB95","LDv4my6gWJQJ")).
neg(eqo("conf/vldb/Blecken00","bW4OLaAXzpUJ")).
neg(eqo("conf/vldb/BliujuteJSS98","JCQQgBm1c-UJ")).
neg(eqo("conf/vldb/Blum99","IYir-gWyKiUJ")).
neg(eqo("conf/vldb/BouganimCDDGS99","wP_GYyvWXaQJ")).
neg(eqo("conf/vldb/BouguettayaEMO01","oi0hNIHYZdcJ")).
neg(eqo("conf/vldb/Brodie00","KGJ7HF2bW6UJ")).
neg(eqo("conf/vldb/Brodie03","2jQpGJ9S_W0J")).
neg(eqo("conf/vldb/CarinoO98","Akh41zGLOowJ")).
neg(eqo("conf/vldb/CarusoCGLM00","_ANyhrnP3CoJ")).
neg(eqo("conf/vldb/ChaudhuriGS95","eHM4OCdJA9YJ")).
neg(eqo("conf/vldb/ChaudhuriGS95","jq5VkbTyBksJ")).
neg(eqo("conf/vldb/ChaudhuriS01","gKmW8q5OfUcJ")).
neg(eqo("conf/vldb/ChenCFGJMTW99","Hq3W65us8dkJ")).
neg(eqo("conf/vldb/ChienTZ01","eWCz_YJFqjcJ")).
neg(eqo("conf/vldb/ChoG00","ZeN3AHHMyq4J")).
neg(eqo("conf/vldb/ChoN02","woKvn2jTg08J")).
neg(eqo("conf/vldb/CosleyLP02","dm3xutmyi_0J")).
neg(eqo("conf/vldb/Dayal99","JM5T7TdjsGgJ")).
neg(eqo("conf/vldb/DayalHL01","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/DayalHL01","z9DFG107WCIJ")).
neg(eqo("conf/vldb/Deshpande00","qkJ_IyVmLfUJ")).
neg(eqo("conf/vldb/DongHLPW01","4GRFG5LsbKUJ")).
neg(eqo("conf/vldb/DonjerkovicR99","TofLoTnu3bgJ")).
neg(eqo("conf/vldb/Duranti01","nzWPEzJMdu0J")).
neg(eqo("conf/vldb/DyresonBJ99","X1MBCvIuINwJ")).
neg(eqo("conf/vldb/EsterKSWX98","dB1R_YRFtqsJ")).
neg(eqo("conf/vldb/EvangelidisLS95","-953Ij-RwjcJ")).
neg(eqo("conf/vldb/FaloutsosG96","uWpo8yp4RrQJ")).
neg(eqo("conf/vldb/FankhauserGLMT98","fIcZeXoZ4bIJ")).
neg(eqo("conf/vldb/Fecteau95","CQOvghgKDEkJ")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
neg(eqo("conf/vldb/Galindo-LegariaPK94","_dOpWA3QWOEJ")).
neg(eqo("conf/vldb/GardarinGT95","DAUHADa6RjQJ")).
neg(eqo("conf/vldb/GardarinGT96","i2KB69gKpXUJ")).
neg(eqo("conf/vldb/GardarinGT96","ywDvUjqsiPQJ")).
neg(eqo("conf/vldb/GarofalakisG01","i7AX4VpJJbYJ")).
neg(eqo("conf/vldb/Gawlick96","9JkvCy7xEd4J")).
neg(eqo("conf/vldb/GehaniJR94","U09WdB3GIK4J")).
neg(eqo("conf/vldb/GolabO03","k0o2GplHA7sJ")).
neg(eqo("conf/vldb/GoldmanW97","fttzmqUN3KsJ")).
neg(eqo("conf/vldb/GottlobKP02","1A06w64wjvcJ")).
neg(eqo("conf/vldb/GottlobKP02","mzzPi10C6dUJ")).
neg(eqo("conf/vldb/GravanoG97","nAJnhh70_0kJ")).
neg(eqo("conf/vldb/HaasKWY97","A8qZGxwlDiYJ")).
neg(eqo("conf/vldb/HoskingC99","n-7FAV7tJZYJ")).
neg(eqo("conf/vldb/HristidisP02","hzlid7szSu4J")).
neg(eqo("conf/vldb/HulgeriS02","U3sURDcacksJ")).
neg(eqo("conf/vldb/IlyasAE03","e6dXyX0MKEIJ")).
neg(eqo("conf/vldb/IoannidisP99","cxJXffJUdbsJ")).
neg(eqo("conf/vldb/IyerW94","IpgzF9NKp7gJ")).
neg(eqo("conf/vldb/JagadishLS99","YtMVuLN2XaYJ")).
neg(eqo("conf/vldb/JermaineDO99","tVmOLBhM_wgJ")).
neg(eqo("conf/vldb/JohnsonM98","tBnhQPI6yJoJ")).
neg(eqo("conf/vldb/JosifovskiR99","GwvN1w9_ZZoJ")).
neg(eqo("conf/vldb/KarayannidisTSPMRFEB02","9KiPVAodKnYJ")).
neg(eqo("conf/vldb/KemmeA00","X14g4few97QJ")).
neg(eqo("conf/vldb/King02","YIRQgC52QxQJ")).
neg(eqo("conf/vldb/KnorrN98","gQVLY8V1hekJ")).
neg(eqo("conf/vldb/KornackerB95","TjG5memyVWIJ")).
neg(eqo("conf/vldb/Korth95","JrUN4Z-H9IQJ")).
neg(eqo("conf/vldb/Korth95","L2c8XblCSicJ")).
neg(eqo("conf/vldb/KossmannRR02","kZFfJieudW4J")).
neg(eqo("conf/vldb/Kotidis01","qzjtGDo7OuMJ")).
neg(eqo("conf/vldb/KoudasGGSV03","VGe-IBWyMm4J")).
neg(eqo("conf/vldb/KoudasMJ99","KUYFJk7kXGEJ")).
neg(eqo("conf/vldb/LakshmananPH02","rNu93TfKkd4J")).
neg(eqo("conf/vldb/LeeLWS97","fHKhYR-6ksMJ")).
neg(eqo("conf/vldb/LempelM02","DcSYGPdhxwoJ")).
neg(eqo("conf/vldb/LernerS03","vhUs7wTpUOoJ")).
neg(eqo("conf/vldb/LeslieJBY95","VIe8nPSWDugJ")).
neg(eqo("conf/vldb/Leymann03","url:http://www.vldb.org/conf/2003/papers/S32P01.pdf")).
neg(eqo("conf/vldb/LimWPVP02","_-JZT1cOuZ8J")).
neg(eqo("conf/vldb/Lindsay95","H-KHwUmJu80J")).
neg(eqo("conf/vldb/LiuJ02","D45fvUWVon0J")).
neg(eqo("conf/vldb/LongS03","782hkUqD49wJ")).
neg(eqo("conf/vldb/Mattos03","ZFHbWjYE29gJ")).
neg(eqo("conf/vldb/MeccaCM01","Ph7ZpmdNOPEJ")).
neg(eqo("conf/vldb/MengLLA03","fANcvlGA8WAJ")).
neg(eqo("conf/vldb/MiloZ98","yBhP3HwdrwkJ")).
neg(eqo("conf/vldb/Mohan01","o8bKerLiMNAJ")).
neg(eqo("conf/vldb/Mohan01","wI6vEf7tAE0J")).
neg(eqo("conf/vldb/Mohan02","CbOhdik4ICgJ")).
neg(eqo("conf/vldb/Mohan02","lI_yxVw-IuAJ")).
neg(eqo("conf/vldb/Mohan96","13YTD5HGpF0J")).
neg(eqo("conf/vldb/Mohan96","SLXN7pkohF4J")).
neg(eqo("conf/vldb/NaumannLF99","QV20-69j6YYJ")).
neg(eqo("conf/vldb/NgH94","W1di9S0fUsEJ")).
neg(eqo("conf/vldb/NgH94","o0vnSBVzRQcJ")).
neg(eqo("conf/vldb/NicklasGS03","nkqfMWyPPH8J")).
neg(eqo("conf/vldb/NishioSTTL01","FokoqHPFTNcJ")).
neg(eqo("conf/vldb/Nori00","F-smuqHklwMJ")).
neg(eqo("conf/vldb/Novaretti01","kIB_O2vZPQwJ")).
neg(eqo("conf/vldb/Objectivity98","M3uRQflHiU4J")).
neg(eqo("conf/vldb/OoiYTJ01","QyBDbs7EpmsJ")).
neg(eqo("conf/vldb/OzdenBRS94","mClzTQppJE4J")).
neg(eqo("conf/vldb/Padmanabhan96","U6jh2mYq5HIJ")).
neg(eqo("conf/vldb/PanRAMOHAMV02","F9Fe5NfpK6MJ")).
neg(eqo("conf/vldb/PardonA00","Bax8yKEV6McJ")).
neg(eqo("conf/vldb/PedersenJD00","EevLzSKmRnIJ")).
neg(eqo("conf/vldb/PopaVMHF02","kyO1P49ldlEJ")).
neg(eqo("conf/vldb/PottingerL00","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3DN7626882AH")).
neg(eqo("conf/vldb/Pound99","31XqhKCe4wUJ")).
neg(eqo("conf/vldb/Pound99","zmHkVq-bkSAJ")).
neg(eqo("conf/vldb/RahmM95","5nlcD-T8P_oJ")).
neg(eqo("conf/vldb/RantzauCHM02","ZkLT6MjoY64J")).
neg(eqo("conf/vldb/SadriZZA01","jtWvNxTZ794J")).
neg(eqo("conf/vldb/SakuraiYUK00","7J-RvgQd8SMJ")).
neg(eqo("conf/vldb/SantiniG02","J3cfnmFB4lsJ")).
neg(eqo("conf/vldb/SantiniG02","sQ7ZJaXvTcUJ")).
neg(eqo("conf/vldb/Sarawagi00","0m9UgontmCsJ")).
neg(eqo("conf/vldb/Sarawagi00","Ndo_zcq-A-MJ")).
neg(eqo("conf/vldb/Sarawagi95","NedkvQncY6MJ")).
neg(eqo("conf/vldb/SatheS01","5RS8T9xjeLQJ")).
neg(eqo("conf/vldb/SavasereON95","XZgDbb1XypMJ")).
neg(eqo("conf/vldb/SavasereON95","rmfK2zWkuagJ")).
neg(eqo("conf/vldb/SavasereON95","yJPi5nBJmVYJ")).
neg(eqo("conf/vldb/SeligmanBNSW95","kxGdQhvpi_sJ")).
neg(eqo("conf/vldb/SenkulKT02","GvUM006N-EIJ")).
neg(eqo("conf/vldb/SeshadriLR97","K62EwWeSRKUJ")).
neg(eqo("conf/vldb/ShaferA97","1wpjWk9ESgIJ")).
neg(eqo("conf/vldb/ShashaB02","kG-k9420fGMJ")).
neg(eqo("conf/vldb/SistlaYH94","_jl3bN2QlE4J")).
neg(eqo("conf/vldb/Sol01","I6ijvPh4RJ8J")).
neg(eqo("conf/vldb/Spaccapietra94","7SVAQt_WxdkJ")).
neg(eqo("conf/vldb/SrikantA95","egCgEjikCgAJ")).
neg(eqo("conf/vldb/SripadaW94","QEK2BsKiXBcJ")).
neg(eqo("conf/vldb/StaudtJ96","lUHqn1TIzykJ")).
neg(eqo("conf/vldb/SubietaKL95","etdbE3X_Xo4J")).
neg(eqo("conf/vldb/Suciu96","O0rvK0GFmBEJ")).
neg(eqo("conf/vldb/TatbulCZCS03","6dAWUHYKqFUJ")).
neg(eqo("conf/vldb/TeisseirePC94","BJAlCQ-KciIJ")).
neg(eqo("conf/vldb/Tsur00","-EzT41hhP1MJ")).
neg(eqo("conf/vldb/VermeerA96","bEddMdwB2_4J")).
neg(eqo("conf/vldb/Wang95","ic9nuBu5xPoJ")).
neg(eqo("conf/vldb/WangZL99","cVgF0jn9q6MJ")).
neg(eqo("conf/vldb/WeberSB98","6OfJSMB4vOcJ")).
neg(eqo("conf/vldb/YanA94","aJVSrdFtpZoJ")).
neg(eqo("conf/vldb/YangKL97","mkSqbMLKznQJ")).
neg(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
neg(eqo("conf/vldb/ZhuS02","Ynt8Na5eF4sJ")).
neg(eqo("conf/vldb/ZimbraoS98","HNZUPXIIGzMJ")).
neg(eqo("conf/vldb/ZimbraoS98","NW7m94AW6nYJ")).
neg(eqo("conf/vldb/ZirintsisKM99","uSZS7Mdxzv8J")).
neg(eqo("journals/sigmod/Aberer02b","RAcoVQuEzD8J")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565129%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03c","M3ELKAZ4wBMJ")).
neg(eqo("journals/sigmod/Aberer03d","_hb7jvkdltcJ")).
neg(eqo("journals/sigmod/AbiteboulH95","m-l6e98xxOsJ")).
neg(eqo("journals/sigmod/Aggarwal01","aZMTodYgkNYJ")).
neg(eqo("journals/sigmod/Aggarwal01","igM_dVQLhtEJ")).
neg(eqo("journals/sigmod/AilamakiH03","rRvcD6HKhasJ")).
neg(eqo("journals/sigmod/ArenasKKKMM03","FVUr5EtAAFcJ")).
neg(eqo("journals/sigmod/AshishK97","GYR0v7CFkP0J")).
neg(eqo("journals/sigmod/AshishK97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083797%26type%3Dpdf")).
neg(eqo("journals/sigmod/BaaderJN97","Ribd7pekAfoJ")).
neg(eqo("journals/sigmod/BabuW01","n6IlcB19rtsJ")).
neg(eqo("journals/sigmod/BernsteinDK99","XhHcpBOYyDcJ")).
neg(eqo("journals/sigmod/BerraNT95","HtqrJuo7GSsJ")).
neg(eqo("journals/sigmod/BhargavaAP95","rGNdajM-asAJ")).
neg(eqo("journals/sigmod/Bohlen95","LwKKzfi_MpUJ")).
neg(eqo("journals/sigmod/BurtonM98","XbLMcy8ERwoJ")).
neg(eqo("journals/sigmod/BurtonM98","Z1hvKdsl1-8J")).
neg(eqo("journals/sigmod/ButtlerCCFHLPRX02","3F2N93KEyI0J")).
neg(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
neg(eqo("journals/sigmod/Camps96","emteilCdIiEJ")).
neg(eqo("journals/sigmod/Cardelli01","2gyvwLFPyfQJ")).
neg(eqo("journals/sigmod/CfP99","4abl38Q9iH4J")).
neg(eqo("journals/sigmod/ChaudhuriD97","jsapF3OoWXcJ")).
neg(eqo("journals/sigmod/Chen94","3nXBlVy0-HUJ")).
neg(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/citation.cfm%3Fid%3D101077.390002%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ChristoffelPSL98","uTTL711_oUcJ")).
neg(eqo("journals/sigmod/ChrysanthisSZ03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ConradHHKRSS99","LRiBvg5EPo4J")).
neg(eqo("journals/sigmod/CoxEH96","3ET_IEkoGjYJ")).
neg(eqo("journals/sigmod/CoxEH96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057808")).
neg(eqo("journals/sigmod/CrestaniG02","BT16LhOe6JkJ")).
neg(eqo("journals/sigmod/Critchlow01","1g03ZgCZpL8J")).
neg(eqo("journals/sigmod/Darwen96","U2j8nxn_SzYJ")).
neg(eqo("journals/sigmod/Datta94","hhu-mJ_l3fgJ")).
neg(eqo("journals/sigmod/Datta94","uaT2hY6421UJ")).
neg(eqo("journals/sigmod/DiazJPa94","KhaCqOhjIUsJ")).
neg(eqo("journals/sigmod/Dogac02","url:http://www.springerlink.com/index/H58452Q268H44281.pdf")).
neg(eqo("journals/sigmod/Dogac98","url:http://ieeexplore.ieee.org/iel5/69/29215/01318561.pdf%3Farnumber%3D1318561")).
neg(eqo("journals/sigmod/Eisenberg96","Ciq01lHglkAJ")).
neg(eqo("journals/sigmod/ElmagarmidJF95","CJK2SWLYrRYJ")).
neg(eqo("journals/sigmod/EnglertGH95","dAnyGPqToQEJ")).
neg(eqo("journals/sigmod/Fagin02","uzpyy9XRpgYJ")).
neg(eqo("journals/sigmod/Franklin00","nCRFjDfhOmcJ")).
neg(eqo("journals/sigmod/Franklin97","JHuJHooGoNUJ")).
neg(eqo("journals/sigmod/Franklin97","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin97a","FwO-8nS6IxQJ")).
neg(eqo("journals/sigmod/Franklin98","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin98a","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin98a","fNVk1Vq2txEJ")).
neg(eqo("journals/sigmod/Franklin98b","iDBvvrHwj7YJ")).
neg(eqo("journals/sigmod/Franklin99","-YhYDZ2AhfgJ")).
neg(eqo("journals/sigmod/Franklin99","q72T2LraKw4J")).
neg(eqo("journals/sigmod/FrewD97","RVxH3DIm47UJ")).
neg(eqo("journals/sigmod/FrewD97","q8jC682bYRUJ")).
neg(eqo("journals/sigmod/GolabO03","lC5GjK5OpD0J")).
neg(eqo("journals/sigmod/Grohe02","CiumYR8Q4WcJ")).
neg(eqo("journals/sigmod/Grohe02","jzwiskpRLOUJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","nsyZSZ78xm8J")).
neg(eqo("journals/sigmod/GuptaHR97","YSgaDQ95dfEJ")).
neg(eqo("journals/sigmod/Halevy03","vG5FK8BJkZgJ")).
neg(eqo("journals/sigmod/Hammer02a","CeQCT0Dqc08J")).
neg(eqo("journals/sigmod/HuangKL02","i1MpjpQXNvIJ")).
neg(eqo("journals/sigmod/Ioannidis96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1099556%26type%3Dpdf")).
neg(eqo("journals/sigmod/Jagadish00","BXB96UFPHn8J")).
neg(eqo("journals/sigmod/KeetonPH98","6MtRlhEClPEJ")).
neg(eqo("journals/sigmod/Keim96","ALk7huiKjWAJ")).
neg(eqo("journals/sigmod/Keim96","th84duaygi4J")).
neg(eqo("journals/sigmod/Kim94","lnl57OhZHz8J")).
neg(eqo("journals/sigmod/Kim99","5lfXNkRahEgJ")).
neg(eqo("journals/sigmod/KlasS94","mqZd0902CSAJ")).
neg(eqo("journals/sigmod/KoubarakisTID03","CiumYR8Q4WcJ")).
neg(eqo("journals/sigmod/KoubarakisTID03","ZjE4GZ7IjiUJ")).
neg(eqo("journals/sigmod/KuanL99","lkrtCULVA6oJ")).
neg(eqo("journals/sigmod/LabrinidisR00","url:http://doi.wiley.com/10.1002/he.10902")).
neg(eqo("journals/sigmod/LeeF01","LpXkGYq1FqMJ")).
neg(eqo("journals/sigmod/Libkin99a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083803%26type%3Dpdf")).
neg(eqo("journals/sigmod/Libkin99a","zSO1Y5W7WkwJ")).
neg(eqo("journals/sigmod/Liu01b","zSO1Y5W7WkwJ")).
neg(eqo("journals/sigmod/Liu02","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Liu02c","url:http://www.roc.noaa.gov/news/vol1is4.pdf")).
neg(eqo("journals/sigmod/Liu03","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Liu03a","DiWYJABnOuMJ")).
neg(eqo("journals/sigmod/Liu03c","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Loeffen94","bLbjFFkQJdIJ")).
neg(eqo("journals/sigmod/Lomet01","uAMYuoCerXAJ")).
neg(eqo("journals/sigmod/Lomet98","fI5o4MfWwzIJ")).
neg(eqo("journals/sigmod/Mackay99","tzUxfh8dD9sJ")).
neg(eqo("journals/sigmod/Manola98","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000002/art00012")).
neg(eqo("journals/sigmod/McHughW97","MuZnT5oVElQJ")).
neg(eqo("journals/sigmod/MeltonE01","619anaISuGEJ")).
neg(eqo("journals/sigmod/MeltzerC98","77mq-gn4LiAJ")).
neg(eqo("journals/sigmod/MukhopadhyayGS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776989%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/NadoH97","V__w6o558CAJ")).
neg(eqo("journals/sigmod/OoiST03","3PKVgwkcJGoJ")).
neg(eqo("journals/sigmod/Ouksel02","B-u4advaVBkJ")).
neg(eqo("journals/sigmod/OukselS99","8M_z-OUkoxYJ")).
neg(eqo("journals/sigmod/OukselS99","zGorEysLERAJ")).
neg(eqo("journals/sigmod/PhatakSSS96","url:http://portal.acm.org/citation.cfm%3Fid%3D333607.333616%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PourabbasR00","9NlVdFCl2ysJ")).
neg(eqo("journals/sigmod/PourabbasR00","y_11zv4cxasJ")).
neg(eqo("journals/sigmod/Qian94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D333608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96b","eyxIItge9MQJ")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","J7mY8RlpTKMJ")).
neg(eqo("journals/sigmod/RamirezSP94","PBtu7Xy2Z_cJ")).
neg(eqo("journals/sigmod/RoddickABDEGHLMMMW00","eA8gNVxHRJ4J")).
neg(eqo("journals/sigmod/Rosenthal98","url:http://portal.acm.org/citation.cfm%3Fid%3D277953")).
neg(eqo("journals/sigmod/Rosneblatt94","Ur6-XAMj3tIJ")).
neg(eqo("journals/sigmod/RossGN03","CMNhuOzf5jAJ")).
neg(eqo("journals/sigmod/RossGR03","uPBlQ76s_g4J")).
neg(eqo("journals/sigmod/RossIJP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossKMV02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossNO03","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/RossNO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Seligman97","dctCPm33OcwJ")).
neg(eqo("journals/sigmod/Seligman97","eA8gNVxHRJ4J")).
neg(eqo("journals/sigmod/ShethBS99","E82z5ALfjNQJ")).
neg(eqo("journals/sigmod/ShethMKA01","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://carfax/cjea/2001/00000009/00000002/art00007%26unc%3D")).
neg(eqo("journals/sigmod/ShethMKA01","zSO1Y5W7WkwJ")).
neg(eqo("journals/sigmod/Snodgrass01a","vUONDuuNNCQJ")).
neg(eqo("journals/sigmod/Snodgrass02a","_-_F8G6rb7oJ")).
neg(eqo("journals/sigmod/Snodgrass03c","KVRdG1SybT0J")).
neg(eqo("journals/sigmod/Snodgrass03c","url:http://doi.wiley.com/10.1002/tl.90")).
neg(eqo("journals/sigmod/Snodgrass97a","Ph1OTw-6Y6gJ")).
neg(eqo("journals/sigmod/SouzaS99","fnt5G2r4MaYJ")).
neg(eqo("journals/sigmod/SpynsMJ02","jD6nDNmhP3AJ")).
neg(eqo("journals/sigmod/StolfoLCFE01","z9WrxlYfVl0J")).
neg(eqo("journals/sigmod/Suciu02","tJtSq968rwgJ")).
neg(eqo("journals/sigmod/SycaraKWL99","YgouJdrCoZQJ")).
neg(eqo("journals/sigmod/TatarinovIMHSDDKMM03","url:http://doi.wiley.com/10.1002/tl.97")).
neg(eqo("journals/sigmod/TomasicS97","-MNdDpWC-sgJ")).
neg(eqo("journals/sigmod/UlusoyB96","3SHIgRrrL5QJ")).
neg(eqo("journals/sigmod/UrbanDG96","url:http://portal.acm.org/citation.cfm%3Fid%3D141818.141829%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/VelACM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/WestmannKHM00","Cm209Vuk17cJ")).
neg(eqo("journals/sigmod/WestmannKHM00","nsaD9s2iRy4J")).
neg(eqo("journals/sigmod/Widom95","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Widom95a","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Widom96","7mNCkZ7D-R8J")).
neg(eqo("journals/sigmod/Widom96","RFd0c3lXk1AJ")).
neg(eqo("journals/sigmod/Widom96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603872%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom96b","WsmdLCWZgakJ")).
neg(eqo("journals/sigmod/Widom96b","url:http://doi.wiley.com/10.1002/ev.1000")).
neg(eqo("journals/sigmod/Widom96b","xgdBJbatYcIJ")).
neg(eqo("journals/sigmod/Widom96b","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031579%26type%3Dpdf")).
neg(eqo("journals/sigmod/WinslettMY03","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601870%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/X94b","nL5wl20jB-kJ")).
neg(eqo("journals/sigmod/Yang94","eRSkDzxP1JcJ")).
neg(eqo("journals/sigmod/Zhang95","CxSOqrhx7iEJ")).
neg(eqo("journals/tods/AikenHW95","6M0HuqCMDlgJ")).
neg(eqo("journals/tods/BaekgaardM95","VGvV7aZcT1UJ")).
neg(eqo("journals/tods/BaralisW00","PcMqnvwNcBIJ")).
neg(eqo("journals/tods/CasatiCPP99","NskCVUwu5dUJ")).
neg(eqo("journals/tods/ChaudhuriS99","uRmyQBKcFAYJ")).
neg(eqo("journals/tods/Chen95","bjzr4k6RZywJ")).
neg(eqo("journals/tods/Chomicki03","ISlrJuO_FH0J")).
neg(eqo("journals/tods/GraefeC95","eDhTIn0OVl8J")).
neg(eqo("journals/tods/HjaltasonS03","9Wan9sPNUAYJ")).
neg(eqo("journals/tods/KarpSP03","k-MUWvAL2wQJ")).
neg(eqo("journals/tods/Keen97","Io4omPiDA94J")).
neg(eqo("journals/tods/Kim94","url:http://portal.acm.org/citation.cfm%3Fid%3D357775%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ777%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520Transactions%2520on%2520Database%2520Systems%2520(TODS)%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/KonopnickiS98","w420Zv-XO6kJ")).
neg(eqo("journals/tods/KotidisR01","ZknlFLRnqLYJ")).
neg(eqo("journals/tods/LechtenborgerV03","94m93uP4GM4J")).
neg(eqo("journals/tods/ParsonsW00","Z5rWzHBxtEEJ")).
neg(eqo("journals/tods/PolyzoisG94","W9d_Byr2GQMJ")).
neg(eqo("journals/tods/Revesz98","2IS_6MNp83YJ")).
neg(eqo("journals/tods/RosenthalR94","L9eva_gsxrIJ")).
neg(eqo("journals/tods/RosenthalR94","g4p3K22hY_oJ")).
neg(eqo("journals/tods/ShashaLSV95","DvasJn1LzQUJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/J805K662617N0160.pdf")).
neg(eqo("journals/tods/StoreyCDGS97","VHo2go6vjYsJ")).
neg(eqo("journals/tods/Suciu02","B8vWhwNP_kIJ")).
neg(eqo("journals/tods/TaoP03","7HvPXnU4DB8J")).
neg(eqo("journals/tods/TendickM94","FxCxfE4m1rUJ")).
neg(eqo("journals/vldb/AbadiCCCCLSTZ03","e_vUPQi8-xIJ")).
neg(eqo("journals/vldb/AbiteboulCM98","gjMbt7_ChmQJ")).
neg(eqo("journals/vldb/Amer-YahiaCLS02","7KawVN8Kj10J")).
neg(eqo("journals/vldb/AnGSVKI02","DBbZw9EPv4QJ")).
neg(eqo("journals/vldb/AslanM99","eFynrwKK_T0J")).
neg(eqo("journals/vldb/AtzeniM00","347oyb_b7DAJ")).
neg(eqo("journals/vldb/AtzeniM00","dEnVedNqyzsJ")).
neg(eqo("journals/vldb/BarbaraI95","fMuom_ogj4MJ")).
neg(eqo("journals/vldb/BernsteinPS00","ZN9dSoKI13UJ")).
neg(eqo("journals/vldb/BraumandlKKKKSS01","dURGvGhlWbsJ")).
neg(eqo("journals/vldb/C95a","PiQHmvFoBIAJ")).
neg(eqo("journals/vldb/C95a","xuabQnvu9l8J")).
neg(eqo("journals/vldb/ChakrabartiGRS01","jpJMa9UNggoJ")).
neg(eqo("journals/vldb/CliftonGB95","YkIvdNOC64cJ")).
neg(eqo("journals/vldb/DesslochHMMT98","PcadhxjbWhcJ")).
neg(eqo("journals/vldb/EyalM01","9e9JOgOv9yAJ")).
neg(eqo("journals/vldb/FiletoLPAM03","gGm5xFGbl2AJ")).
neg(eqo("journals/vldb/Halevy01","wgd8D53WoRkJ")).
neg(eqo("journals/vldb/Halevy02","cDN9oOqsTE0J")).
neg(eqo("journals/vldb/Han98","EWdjCIv1enwJ")).
neg(eqo("journals/vldb/HelmerM03","y2uZPpBjpjQJ")).
neg(eqo("journals/vldb/JiangE98","ZgzJ5wHD04UJ")).
neg(eqo("journals/vldb/KashyapS96","h_g4xOpUq6wJ")).
neg(eqo("journals/vldb/KellerB96","0WrCjHbA2v4J")).
neg(eqo("journals/vldb/LawLG99","kGB3pezWy-MJ")).
neg(eqo("journals/vldb/LinJF94","eFynrwKK_T0J")).
neg(eqo("journals/vldb/NgS98","HLu7MvWb5rMJ")).
neg(eqo("journals/vldb/OzsuC98","BsQtFZrn3fsJ")).
neg(eqo("journals/vldb/OzsuC98","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671850")).
neg(eqo("journals/vldb/PeckhamMD95","W34JQQUUM84J")).
neg(eqo("journals/vldb/PoulovassilisS96","HNDwkFGwM7EJ")).
neg(eqo("journals/vldb/ScheuermannWZ98","uPBlQ76s_g4J")).
neg(eqo("journals/vldb/TanGO00","za6ySySnGH8J")).
neg(eqo("journals/vldb/TenienteO95","BCdzhd17nKEJ")).
neg(eqo("journals/vldb/TsatalosSI96","PAwpwv-OCVYJ")).
neg(eqo("journals/vldb/TsatalosSI96","SHeVWt2HhgEJ")).
neg(eqo("journals/vldb/YangW03","A8rGBQif7MIJ")).
pos(eqo("conf/sigmod/AbadiCCCCEGHMRSSTXYZ03","eBnT7lhV2LwJ")).
pos(eqo("conf/sigmod/AbadiCCCCEGHMRSSTXYZ03","gBVNSFeS4P8J")).
pos(eqo("conf/sigmod/AcharyaAFZ95","2fO9nM2FoGYJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","h2z51QPXcSkJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","rO4-yA3tlfoJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","C221gFS5VVoJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","IkNOhDqEY18J")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/AdaliCPS96","uMmcsye0YCkJ")).
pos(eqo("conf/sigmod/AdaliCPS96","zE4iM0h4W2sJ")).
pos(eqo("conf/sigmod/AggarwalPWYP99","5uimonC4q_QJ")).
pos(eqo("conf/sigmod/AggarwalY00","dfSPs7YoyWsJ")).
pos(eqo("conf/sigmod/AgrawalCN01","2Ua-pWTof_YJ")).
pos(eqo("conf/sigmod/Ahn94","5s6b10Hik30J")).
pos(eqo("conf/sigmod/BarbaraI94","XfvqAOX1qo4J")).
pos(eqo("conf/sigmod/BarclaySG00","JTEJ-q3T1vsJ")).
pos(eqo("conf/sigmod/BarclaySG00","v6Rokk9Eht8J")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","2J_9scP1caYJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","cg01BqanXhUJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","tsQbSCfQTooJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","oulaZpEWkMQJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","uPx8w3k7NyQJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","wF2-sxlGAu4J")).
pos(eqo("conf/sigmod/BrinMUT97","FtMoh58D330J")).
pos(eqo("conf/sigmod/BrinMUT97","ZAjbM4H53aUJ")).
pos(eqo("conf/sigmod/BrinMUT97","bjZ8SxYnrd0J")).
pos(eqo("conf/sigmod/BrinMUT97","swPpkmm8SdYJ")).
pos(eqo("conf/sigmod/BrinMUT97","vIwsSOGQOWAJ")).
pos(eqo("conf/sigmod/BrownCL96","H4A7nUWyXtQJ")).
pos(eqo("conf/sigmod/BrunoKS02","2VpRW4Tf08EJ")).
pos(eqo("conf/sigmod/BryanMCLG94","nbU-wr3ivUIJ")).
pos(eqo("conf/sigmod/Bussler01","UYIeOe280OwJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/CatarciS94","ga4l4QhCXU4J")).
pos(eqo("conf/sigmod/CatarciS94","pryJrhEGI2sJ")).
pos(eqo("conf/sigmod/CeriFP98","iUGa3pKj-20J")).
pos(eqo("conf/sigmod/ChakrabartiM99","Jg81WYtxtZoJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","4zZ7Lxt4PPIJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","ClO4zHQ7RYsJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","gY652XXjHB8J")).
pos(eqo("conf/sigmod/ChaudhuriGN02","y461yNb2GEcJ")).
pos(eqo("conf/sigmod/ChaudhuriN98a","JyEX0YVMP5oJ")).
pos(eqo("conf/sigmod/ChawatheG97","JLeihu2aUqYJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","Xz0ZPMLOwcgJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","ilCT5UFnHxgJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","vBlDkLyxeQkJ")).
pos(eqo("conf/sigmod/ChenJDTW00","5Trj9q_RI8YJ")).
pos(eqo("conf/sigmod/ChenJDTW00","QiSf-FBUE8QJ")).
pos(eqo("conf/sigmod/ChenR94","7Edh53sUX7kJ")).
pos(eqo("conf/sigmod/Cohen98a","qfD_kxYt-dsJ")).
pos(eqo("conf/sigmod/CorralMTV00","TsShfxPwF6YJ")).
pos(eqo("conf/sigmod/Cotton02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564792%26type%3Dpdf")).
pos(eqo("conf/sigmod/CruzALRZ97","YWWvQnGCpDEJ")).
pos(eqo("conf/sigmod/CruzALRZ97","uh2lQGa6hQUJ")).
pos(eqo("conf/sigmod/CruzALRZ97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294187CI")).
pos(eqo("conf/sigmod/DavulcuFKR99","TDyW6V4cc7MJ")).
pos(eqo("conf/sigmod/DeutschFS99","9WLtxnKtm_EJ")).
pos(eqo("conf/sigmod/DeutschFS99","SR_yVgZnYpMJ")).
pos(eqo("conf/sigmod/DeutschFS99","Z9e9dqy5KBgJ")).
pos(eqo("conf/sigmod/DeutschFS99","twQNwr-jFmoJ")).
pos(eqo("conf/sigmod/DogacTPPLKTK02","VAOk1X8Ja30J")).
pos(eqo("conf/sigmod/DogacTPPLKTK02","juQlvnYuPxwJ")).
pos(eqo("conf/sigmod/DraperHW01","6csUZFROjIEJ")).
pos(eqo("conf/sigmod/DreyerDS95","Qf8OS1o2YM4J")).
pos(eqo("conf/sigmod/DuSD95","Vl7gY6FsOOYJ")).
pos(eqo("conf/sigmod/Dullmann99","5bp8rSFAkzEJ")).
pos(eqo("conf/sigmod/EmbleyJN99","x8uC_9_IzUEJ")).
pos(eqo("conf/sigmod/FaloutsosL95","RLjlTtFM36IJ")).
pos(eqo("conf/sigmod/FaloutsosL95","dRjSn10qk9wJ")).
pos(eqo("conf/sigmod/FaloutsosL95","j0EcM-BvshwJ")).
pos(eqo("conf/sigmod/FaloutsosL95","roK09GarWdcJ")).
pos(eqo("conf/sigmod/FernandezS96","66uAX5EPtKcJ")).
pos(eqo("conf/sigmod/FernandezS96","lMKrltuk53EJ")).
pos(eqo("conf/sigmod/Freeston95","Fr8CPbK-IFIJ")).
pos(eqo("conf/sigmod/FukudaMMT96","lmXiI4fB9vgJ")).
pos(eqo("conf/sigmod/Galindo-Legaria94","iEs59H5EFHwJ")).
pos(eqo("conf/sigmod/GarofalakisG02","r4a_VlMfu38J")).
pos(eqo("conf/sigmod/GarofalakisGR02","ImADir74KWIJ")).
pos(eqo("conf/sigmod/GarofalakisGR02","S6PWjHRFORYJ")).
pos(eqo("conf/sigmod/GatziuGD95","RvtHXIfsMasJ")).
pos(eqo("conf/sigmod/GatziuGD95","jC39CJrWKr8J")).
pos(eqo("conf/sigmod/GehrkeKS01","f6JFkfhawW8J")).
pos(eqo("conf/sigmod/GillmannWW02","Pbjz4-UPrZ8J")).
pos(eqo("conf/sigmod/Golding95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223865%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D223784%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/GravanoCGP97","8jTTpoQc2RkJ")).
pos(eqo("conf/sigmod/GravanoCGP97","IVXOHTW5Lt0J")).
pos(eqo("conf/sigmod/GravanoCGP97","yfb8p_tlSlsJ")).
pos(eqo("conf/sigmod/GrayHOS96","3mFpWorR_ucJ")).
pos(eqo("conf/sigmod/GrayHOS96","GFJeoxHwEnkJ")).
pos(eqo("conf/sigmod/GrayHOS96","J_QkWJ4HlOUJ")).
pos(eqo("conf/sigmod/GrayHOS96","Mopy3Yg3i60J")).
pos(eqo("conf/sigmod/GrayHOS96","imwZsCcZvFQJ")).
pos(eqo("conf/sigmod/GrayHOS96","jH3KeKroDfQJ")).
pos(eqo("conf/sigmod/GrayHOS96","pDjbDK0ZzsMJ")).
pos(eqo("conf/sigmod/GraySEBW94","SG9kpHg_arUJ")).
pos(eqo("conf/sigmod/GraySEBW94","bbWXEbBUueYJ")).
pos(eqo("conf/sigmod/GraySSU03","NnKrsx4j4pkJ")).
pos(eqo("conf/sigmod/GriffinL95","nXT3j4XaZxIJ")).
pos(eqo("conf/sigmod/GuoSBS03","p_PDgjVRUS4J")).
pos(eqo("conf/sigmod/GuptaS03","BLPcDzgX3iQJ")).
pos(eqo("conf/sigmod/HaasH99","fz1XAzoKPo0J")).
pos(eqo("conf/sigmod/Hammond99","-ndr_jftgFkJ")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
pos(eqo("conf/sigmod/Hellerstein94","r4adn1YKOFIJ")).
pos(eqo("conf/sigmod/HellersteinW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564788%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/HernandezS95","IHy3bqAuSOUJ")).
pos(eqo("conf/sigmod/HernandezS95","KJyo5lhO_vAJ")).
pos(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
pos(eqo("conf/sigmod/HjaltasonS98","hFnyy0PFe1MJ")).
pos(eqo("conf/sigmod/HouZ95","AeRUCf7iBqYJ")).
pos(eqo("conf/sigmod/HsuLG00","kxIpDxLD46gJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","1H_A7k3QsbQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","7qv9IC8F_WQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/IvesLPST00","4-FwpSOweRAJ")).
pos(eqo("conf/sigmod/IvesLPST00","rtnpqb22gGcJ")).
pos(eqo("conf/sigmod/Jagadish94","eH69_dCm18wJ")).
pos(eqo("conf/sigmod/JagadishLMSV99","946iAs3adDcJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","XpY2UPc6vP0J")).
pos(eqo("conf/sigmod/JarkeQCLFLVV00","AYtgczYwVnYJ")).
pos(eqo("conf/sigmod/JonssonFS98","t6-LjSlCUmcJ")).
pos(eqo("conf/sigmod/KabraD98","E0nhpX8pYsQJ")).
pos(eqo("conf/sigmod/KabraD98","V9XUvirmVEEJ")).
pos(eqo("conf/sigmod/Keim99","GBZiTCbChZQJ")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","909hLNR8130J")).
pos(eqo("conf/sigmod/Kim94","GzJII5F7OzAJ")).
pos(eqo("conf/sigmod/KimCK01","EYI-OULRIz8J")).
pos(eqo("conf/sigmod/KornMZ03","6VAQeD6muakJ")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/KotidisR99","nsASp-dCJBQJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","Hxnlcwm_RhMJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","uzpyy9XRpgYJ")).
pos(eqo("conf/sigmod/LakhamrajuRSS00","GveQLUTEle8J")).
pos(eqo("conf/sigmod/LakshmananNHP99","DfOLEzMoEaEJ")).
pos(eqo("conf/sigmod/LeeKC99","c-5n9qQKLaEJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","6jeHlSgjCskJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","oQtxPA_0PCYJ")).
pos(eqo("conf/sigmod/LiuFP03","_97cTemKZnMJ")).
pos(eqo("conf/sigmod/LiuHBPT99","BIox2W-EPfEJ")).
pos(eqo("conf/sigmod/LiuHBPT99","PKQ1dCQIwi0J")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/MaddenSHR02","7n7LvbccBZoJ")).
pos(eqo("conf/sigmod/MaddenSHR02","HTAP9c7dQagJ")).
pos(eqo("conf/sigmod/MaddenSHR02","WhBHQqg-7l8J")).
pos(eqo("conf/sigmod/MaddenSHR02","aFuBut1W_KEJ")).
pos(eqo("conf/sigmod/MaddenSHR02","zobnUjtYSe8J")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/MelnikRB03","bkpTodGryDAJ")).
pos(eqo("conf/sigmod/Miller98","r0ZzrEjVO4UJ")).
pos(eqo("conf/sigmod/MumickQM97","cvHvC7tUSrIJ")).
pos(eqo("conf/sigmod/Mylopoulos98","5eBjuTrKTwoJ")).
pos(eqo("conf/sigmod/NestorovAM98","5icRoG_Vmc0J")).
pos(eqo("conf/sigmod/NgLK98","kJVhJ4ruw6sJ")).
pos(eqo("conf/sigmod/Norrie95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D223883%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/NybergBCGL94","kd-0q-M1O2gJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D280357%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ONeilQ97","5iolWs79wEEJ")).
pos(eqo("conf/sigmod/ONeilQ97","6y9Er-083rIJ")).
pos(eqo("conf/sigmod/ONeilQ97","FOruO1PeowAJ")).
pos(eqo("conf/sigmod/ONeilQ97","rN34VXyq84YJ")).
pos(eqo("conf/sigmod/ONeilQ97","tK0HTC7qEmcJ")).
pos(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
pos(eqo("conf/sigmod/OlstonWACELSS98","UTYa5uf9zSIJ")).
pos(eqo("conf/sigmod/OrdonezC00","yWkfJz_YMPkJ")).
pos(eqo("conf/sigmod/OzdenRSS96","-NqtWdEMQkgJ")).
pos(eqo("conf/sigmod/ParkCY95","hLrdara3zskJ")).
pos(eqo("conf/sigmod/ParkCY95","ko0i4AzclBgJ")).
pos(eqo("conf/sigmod/ParkCY95","pN4pq6qELakJ")).
pos(eqo("conf/sigmod/ParkCY95","v9preswS6YUJ")).
pos(eqo("conf/sigmod/ParkKKLPC98","F8CacVSkztEJ")).
pos(eqo("conf/sigmod/Pirahesh94","VG96hL8afvgJ")).
pos(eqo("conf/sigmod/PonnekantiK00","IddFq2o4ZsoJ")).
pos(eqo("conf/sigmod/Rajaraman99","m_n55lcmF-sJ")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/citation.cfm%3Fid%3D375796")).
pos(eqo("conf/sigmod/RundensteinerKZWLLN99","2XRfNjwuDrsJ")).
pos(eqo("conf/sigmod/SagonasSW94a","ezmsDUMWUJEJ")).
pos(eqo("conf/sigmod/SagonasSW94a","nF5iGEtihWYJ")).
pos(eqo("conf/sigmod/Sahuguet01","1psqlswyLR0J")).
pos(eqo("conf/sigmod/Sahuguet01","xb63RaGQYmYJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","LMm4_4_uNNoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","e0UYPB4kRCYJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wISxjPqlwZoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wnMZjFGvYVQJ")).
pos(eqo("conf/sigmod/SchusterW01","59akjz-Qe9IJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","3OxZS395vDcJ")).
pos(eqo("conf/sigmod/ShenNSHS03","LjrsWIr3rhAJ")).
pos(eqo("conf/sigmod/ShouCTRH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375755%26type%3Dpdf%26dl%3DGUIDE%26dl%3DGUIDE%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ShuklaD00","kcrWfQEI9G8J")).
pos(eqo("conf/sigmod/SistlaW95","voZSiqM4epgJ")).
pos(eqo("conf/sigmod/SrikantA96","KVEv4thH4CgJ")).
pos(eqo("conf/sigmod/SrikantA96","ZBuWjiVOE94J")).
pos(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
pos(eqo("conf/sigmod/StoltePAG03","9WTNlminW6AJ")).
pos(eqo("conf/sigmod/SzalayGKT00","1kKap3JyndkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","2ikeMlH1BGsJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","1tKWKmyczaYJ")).
pos(eqo("conf/sigmod/ThomasDM95","1W3ieFgA2dUJ")).
pos(eqo("conf/sigmod/TsueiPK97","DpQGq6n1jnkJ")).
pos(eqo("conf/sigmod/WangPFY03","5JXKbI5l1FYJ")).
pos(eqo("conf/sigmod/WangPFY03","y5zNcYc9dqsJ")).
pos(eqo("conf/sigmod/WangZS95","86-DS0U0jY0J")).
pos(eqo("conf/sigmod/WangZS95","QHrpE-XaLoMJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","--PsNHvlpbIJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","v6QoWdFgBjwJ")).
pos(eqo("conf/sigmod/Wu99","xl1Jscb79KEJ")).
pos(eqo("conf/sigmod/WuAA01","QKlyEeIFW24J")).
pos(eqo("conf/sigmod/YanMHF01","w54gl9nDfcoJ")).
pos(eqo("conf/sigmod/YerneniLGU99","2MbaeG3IVV0J")).
pos(eqo("conf/sigmod/ZhangNDLL01","RkUnSP2Vkj0J")).
pos(eqo("conf/sigmod/ZhangNDLL01","ryaV3kTsJ2IJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","MjGo7AhsPSsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","XurM_pCyadcJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","mBC03oUT8yAJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","miytzHylgMAJ")).
pos(eqo("conf/sigmod/ZhouLP99","0OwKmPjQpd0J")).
pos(eqo("conf/vldb/AbiteboulBMMW02","mm3mXWb8QS0J")).
pos(eqo("conf/vldb/AbiteboulMRVW98","CDQHFdIK_cwJ")).
pos(eqo("conf/vldb/AcharyaFZ96","ccEW59Ac84MJ")).
pos(eqo("conf/vldb/Adler01","Tnuonq9Zi4cJ")).
pos(eqo("conf/vldb/AgrawalSX01","bpWvAVOZLbwJ")).
pos(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","-FP8UTv_smkJ")).
pos(eqo("conf/vldb/AlsabtiRS97","-0Lu8VIRYtEJ")).
pos(eqo("conf/vldb/Amer-YahiaCD98","W0L9nOcuhmIJ")).
pos(eqo("conf/vldb/Amer-YahiaCD98","uA2hKrKiu6cJ")).
pos(eqo("conf/vldb/AnSVKIG01","HosSI1GtRY8J")).
pos(eqo("conf/vldb/ArgePRSV98","A5Eiwdh71m0J")).
pos(eqo("conf/vldb/ArgePRSV98","c3yObnVI65cJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/BamfordBKM98","rfuptELfgLkJ")).
pos(eqo("conf/vldb/BarjaPFWD94","qhl9_KGvjcUJ")).
pos(eqo("conf/vldb/BassiliadesV95","B1kJzsffXEwJ")).
pos(eqo("conf/vldb/BaulierBKS98","dNK16sHm9eUJ")).
pos(eqo("conf/vldb/Bayer95","W3l3pQ62_YMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","G__T5t9i4ZwJ")).
pos(eqo("conf/vldb/BerchtoldKK96","KLzrIupmRloJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WnYVibh8fxUJ")).
pos(eqo("conf/vldb/BerchtoldKK96","pMqgAz_KzPgJ")).
pos(eqo("conf/vldb/BerckenS96","GfvntjAdvVYJ")).
pos(eqo("conf/vldb/Blecken00","hCSzil0nuVEJ")).
pos(eqo("conf/vldb/BliujuteJSS98","gybR2qK1ib8J")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/Blum99","EYfIweE8pHEJ")).
pos(eqo("conf/vldb/BouganimCDDGS99","Ult4nmnmJp8J")).
pos(eqo("conf/vldb/Bowker00","fAHjV8C1hLcJ")).
pos(eqo("conf/vldb/BridgeJKLLM97","8SYZpKAeTwQJ")).
pos(eqo("conf/vldb/CareyD96","5HV8kccLoZ4J")).
pos(eqo("conf/vldb/CareyD96","riS5qD1-odUJ")).
pos(eqo("conf/vldb/CareyKSSS00","gZtFMFjW2n0J")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChakrabartiSD98","oBDL7axDwG4J")).
pos(eqo("conf/vldb/ChakrabartiSD98","zDznH1GBa7UJ")).
pos(eqo("conf/vldb/ChanFFGR02","ZFI7XBuonJAJ")).
pos(eqo("conf/vldb/ChanGR02","7rn7AHVs1YUJ")).
pos(eqo("conf/vldb/ChaudhuriGS95","WYgQ_Mhdp9sJ")).
pos(eqo("conf/vldb/ChavdaW97","E9AsPVyCDlMJ")).
pos(eqo("conf/vldb/ChavdaW97","h3IiHna9R2gJ")).
pos(eqo("conf/vldb/Chawathe99","HiM9HOUxq0MJ")).
pos(eqo("conf/vldb/Chawathe99","w6VtZRVAZV8J")).
pos(eqo("conf/vldb/CiacciaPZ97","urL_oXzvBBUJ")).
pos(eqo("conf/vldb/Cluet03","faRBjw1op8YJ")).
pos(eqo("conf/vldb/ColletCS94","sZwecq6zUmMJ")).
pos(eqo("conf/vldb/ConradGJM02","gIm89AXuE4oJ")).
pos(eqo("conf/vldb/DarFJST96","8OsKvVqzz58J")).
pos(eqo("conf/vldb/Dayal99","url:http://portal.acm.org/citation.cfm%3Fid%3D645925.671502")).
pos(eqo("conf/vldb/DeWittKLPY94","ENb3jCRhOi8J")).
pos(eqo("conf/vldb/DeWittKLPY94","MbQoYPHe0V0J")).
pos(eqo("conf/vldb/DeWittKLPY94","WbnSYesbN8QJ")).
pos(eqo("conf/vldb/DeWittKLPY94","xcwQARsnK4gJ")).
pos(eqo("conf/vldb/DeutschPT99","0aJOXauNqYIJ")).
pos(eqo("conf/vldb/EicklerKK97","PCFJuVxYxtwJ")).
pos(eqo("conf/vldb/EleftheriouBCDHLPPABDDDGJHLRSVW03","hRToevpkaa0J")).
pos(eqo("conf/vldb/FangSGMU98","MdwCZg0RBHYJ")).
pos(eqo("conf/vldb/FlodinR95","b5vbAhJ4xxMJ")).
pos(eqo("conf/vldb/GardarinST96","RB2VKRwnXywJ")).
pos(eqo("conf/vldb/GarofalakisG01","SHDQQrfJ3BMJ")).
pos(eqo("conf/vldb/GarofalakisI97","SqECOHtHVaAJ")).
pos(eqo("conf/vldb/GarofalakisI97","aCvCz2wg854J")).
pos(eqo("conf/vldb/GarofalakisRS99","7BITau8qhpEJ")).
pos(eqo("conf/vldb/GarofalakisRS99","poso7AKokFMJ")).
pos(eqo("conf/vldb/Gentili01","2j1dalv3kCEJ")).
pos(eqo("conf/vldb/GohOST99","hK5EOo-Z7JMJ")).
pos(eqo("conf/vldb/GolabO03","6K9FhI2pFEgJ")).
pos(eqo("conf/vldb/GoldsteinR00","30fMB9_zBm0J")).
pos(eqo("conf/vldb/GoodmanRS94","8CCHAKnGJ1EJ")).
pos(eqo("conf/vldb/GravanoG95","4HVB6aRvsk8J")).
pos(eqo("conf/vldb/GravanoG95","F2mmoq6cRGMJ")).
pos(eqo("conf/vldb/Greco98","CCr8CUlHeNsJ")).
pos(eqo("conf/vldb/GuptaHQ95","CtRFDjCGDg8J")).
pos(eqo("conf/vldb/GuptaHQ95","tB1dhGkG-esJ")).
pos(eqo("conf/vldb/GuptaM96","I83l_B0knOgJ")).
pos(eqo("conf/vldb/HalversonBKKRTVWND03","oR7DmJ9JJDYJ")).
pos(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
pos(eqo("conf/vldb/HankinsP03","NsxXW_CvQpkJ")).
pos(eqo("conf/vldb/HasanM95","8cd64f0t0-EJ")).
pos(eqo("conf/vldb/HasanM95","JmlFFnMD_D0J")).
pos(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
pos(eqo("conf/vldb/IlyasAE03","Y385z1Dxp84J")).
pos(eqo("conf/vldb/IshikawaSF98","9MDCp_a1roUJ")).
pos(eqo("conf/vldb/JaedickeM99","TaaxQZajjqoJ")).
pos(eqo("conf/vldb/JaedickeM99","XR50nxmrvFcJ")).
pos(eqo("conf/vldb/JagadishLRSS94","em_mB-ifc80J")).
pos(eqo("conf/vldb/JermaineDO99","h6R5rXre-_QJ")).
pos(eqo("conf/vldb/JohnsonS94","1TMemq4kM3YJ")).
pos(eqo("conf/vldb/KaushikBNS02","dL5oJVHK10kJ")).
pos(eqo("conf/vldb/KemmeA00","-McZOyw__qQJ")).
pos(eqo("conf/vldb/Koch03","rhxIrsQkm5AJ")).
pos(eqo("conf/vldb/KochBG03","xCbXlJHLR48J")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/vldb/KornSFSP96","I8YNDqO9pg8J")).
pos(eqo("conf/vldb/KornSFSP96","VL_cnRotMQcJ")).
pos(eqo("conf/vldb/KornSFSP96","xQU9GXs4k50J")).
pos(eqo("conf/vldb/Korth95","UZAQL1o-c0MJ")).
pos(eqo("conf/vldb/KumarKA97","hhHVHYnMd6kJ")).
pos(eqo("conf/vldb/LabrinidisR01","9ZhDPDECMQ8J")).
pos(eqo("conf/vldb/LakshmananNWZJ02","qfw7Pu1wVcIJ")).
pos(eqo("conf/vldb/LakshmananSS96","0VHtbuWJCQUJ")).
pos(eqo("conf/vldb/LakshmananSS96","AVyGNVp-ENcJ")).
pos(eqo("conf/vldb/LakshmiZ98","3XwLBVHUBvAJ")).
pos(eqo("conf/vldb/LakshmiZ98","QmXB6EKu-pYJ")).
pos(eqo("conf/vldb/LiC94","O0rvK0GFmBEJ")).
pos(eqo("conf/vldb/LiM01","9vDm1Q41J8oJ")).
pos(eqo("conf/vldb/MahnkeMS02","VhxIKKG8oWYJ")).
pos(eqo("conf/vldb/ManegoldBK00","-7hYJxFD-AsJ")).
pos(eqo("conf/vldb/MaratheS97","HcgXkUDB-wYJ")).
pos(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
pos(eqo("conf/vldb/MargaritisFT01","WOiDxLKSioAJ")).
pos(eqo("conf/vldb/MarronL01","MiMYGwqrGY8J")).
pos(eqo("conf/vldb/MatiasVW00","VQbfg3MOm90J")).
pos(eqo("conf/vldb/MillerHH00","6vtHcpLApB8J")).
pos(eqo("conf/vldb/MillerHH00","wWG2iaq2tTgJ")).
pos(eqo("conf/vldb/Moni96","gbjXwFztQTsJ")).
pos(eqo("conf/vldb/MorimotoFMTY98","31YuS02mFq8J")).
pos(eqo("conf/vldb/MorimotoFMTY98","9sydmlCRr4cJ")).
pos(eqo("conf/vldb/MoserKK95","DFZ5hU-q0BIJ")).
pos(eqo("conf/vldb/NatsevCSLV01","173qcCip5coJ")).
pos(eqo("conf/vldb/NieKH03","0RaBCPWwApQJ")).
pos(eqo("conf/vldb/NiermanJ02","1NZsxf_zwF4J")).
pos(eqo("conf/vldb/NishioSTTL01","S30IXg4ClFIJ")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/OzdenBRS94","ARyxUwGOA10J")).
pos(eqo("conf/vldb/OzdenBRS94","T4zyjvy9GdcJ")).
pos(eqo("conf/vldb/OzdenGHNSDGGW01","ZzYmVTAjsnQJ")).
pos(eqo("conf/vldb/OzsuLON01","qqdXmdgAaMgJ")).
pos(eqo("conf/vldb/OzsuVU98","WAivXgeI8vIJ")).
pos(eqo("conf/vldb/PalpanasSCP02","nlh2WXZT3VIJ")).
pos(eqo("conf/vldb/PantiSG00","C7Vuxp5KVsAJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","vjZ89wZs27UJ")).
pos(eqo("conf/vldb/RamakrishnanGRSWZ95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.756661")).
pos(eqo("conf/vldb/RamakrishnanR96","3y1e-H-FdC0J")).
pos(eqo("conf/vldb/RaoR99","N8XkcmIO0ysJ")).
pos(eqo("conf/vldb/RaoR99","tv4rTR2Z-I8J")).
pos(eqo("conf/vldb/RastogiS98","gNSRjezd168J")).
pos(eqo("conf/vldb/RastogiS98","gkEOPxIM4GkJ")).
pos(eqo("conf/vldb/RisheYACLMVSV00","0WYMHga_bt4J")).
pos(eqo("conf/vldb/RisheYACLMVSV00","JGuPo8c_vZkJ")).
pos(eqo("conf/vldb/RothS97","nq7CSMVFjq8J")).
pos(eqo("conf/vldb/RothS97","xh4FaygNlGQJ")).
pos(eqo("conf/vldb/SakuraiYKU01","OQMYc3S0Ny8J")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/vldb/SavasereON95","ohjoG-bi4OgJ")).
pos(eqo("conf/vldb/SavasereON95","rHLmfJRQUu0J")).
pos(eqo("conf/vldb/SavasereON95","tX0hBHC5_UQJ")).
pos(eqo("conf/vldb/SayalCDS02","0acvmJtaI8QJ")).
pos(eqo("conf/vldb/SchaeferBBJ00","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671845")).
pos(eqo("conf/vldb/SeidlK97","HAG0kCjBu4EJ")).
pos(eqo("conf/vldb/SeidlK97","LZGFMX7pdCkJ")).
pos(eqo("conf/vldb/SellisRF97","moT0ba0vRKcJ")).
pos(eqo("conf/vldb/SetzerZ94","1tmW1mOCZqIJ")).
pos(eqo("conf/vldb/ShahabiFKF00","ln1yHhG7gdgJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GIlUG9H3gUUJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","NADaoJJSRfQJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","dycZ24ft99wJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","hYQ_6_v-Cd4J")).
pos(eqo("conf/vldb/ShatdalKN94","27-P8X0mjfcJ")).
pos(eqo("conf/vldb/SistlaYH94","QWD1EGMbTQYJ")).
pos(eqo("conf/vldb/SistlaYH94","bDH4OmzDSLEJ")).
pos(eqo("conf/vldb/Spaccapietra94","ZpVzTb1a7VoJ")).
pos(eqo("conf/vldb/SrikantA95","Jjk_Q4u0JiQJ")).
pos(eqo("conf/vldb/SrikantA95","OqO-ZxObnjgJ")).
pos(eqo("conf/vldb/SrikantA95","RE_sI8I74igJ")).
pos(eqo("conf/vldb/SrikantA95","Ve-JH2yNN0kJ")).
pos(eqo("conf/vldb/SrikantA95","bibMn8zFnksJ")).
pos(eqo("conf/vldb/SrikantA95","kAi6HssDySgJ")).
pos(eqo("conf/vldb/SrikantA95","nPkMLSiC3JQJ")).
pos(eqo("conf/vldb/SrikantA95","v7i1i5y_nHgJ")).
pos(eqo("conf/vldb/StohrMR00","7fCRAqLTNeUJ")).
pos(eqo("conf/vldb/Suciu96a","tJtSq968rwgJ")).
pos(eqo("conf/vldb/TamuraK99","rAHGAfoqookJ")).
pos(eqo("conf/vldb/TatbulCZCS03","TAsynkdIAfwJ")).
pos(eqo("conf/vldb/VelegrakisMP03","tYCCI2DndboJ")).
pos(eqo("conf/vldb/VieiraM03","sUtdmV9XsIcJ")).
pos(eqo("conf/vldb/ViverosNR96","lsY_rXfEDDIJ")).
pos(eqo("conf/vldb/VorugantiOU99","nlwMBvJt988J")).
pos(eqo("conf/vldb/WangC03","B1uNI67mfJcJ")).
pos(eqo("conf/vldb/WangC03","yjZolbzEP6wJ")).
pos(eqo("conf/vldb/WeikumMHZ02","W_b-Eo5VaOgJ")).
pos(eqo("conf/vldb/WienerN95","LJ4M8B9mNWAJ")).
pos(eqo("conf/vldb/WuFSP00","tr_rawv-6SMJ")).
pos(eqo("conf/vldb/XinHLW03","v0rD-1nzJmYJ")).
pos(eqo("conf/vldb/YagoubFIV00a","hMsWZU5TJWYJ")).
pos(eqo("conf/vldb/YangG01","LN1TWlAUa0wJ")).
pos(eqo("conf/vldb/YangG01","UZBoDXflaXoJ")).
pos(eqo("conf/vldb/ZouS98","fPzfCbyzqsoJ")).
pos(eqo("conf/vldb/ZurekS99","mEdoUlcnDsgJ")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/AilamakiG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AndlerHEMBE96","3Isoplo_hi0J")).
pos(eqo("journals/sigmod/AndlerHEMBE96","WZ823oj6x3cJ")).
pos(eqo("journals/sigmod/AndlerHEMBE96","oNYOKYvjoKgJ")).
pos(eqo("journals/sigmod/ArenasKKKMM03","rl50qPw8UaEJ")).
pos(eqo("journals/sigmod/Baeza-YatesN96","W3NucQtmzesJ")).
pos(eqo("journals/sigmod/BarclayBGS94","v1aol6mmLdMJ")).
pos(eqo("journals/sigmod/Bohlen95","WnwPjh0a0twJ")).
pos(eqo("journals/sigmod/Bohlen95","v5P_NFXdOR8J")).
pos(eqo("journals/sigmod/BonifatiC00","RR-e0fkaniQJ")).
pos(eqo("journals/sigmod/BonnetBDL03","aovCRhocZUcJ")).
pos(eqo("journals/sigmod/BoucelmaCGJLL02","I9JXY0-R4GgJ")).
pos(eqo("journals/sigmod/BurtonM98","LOXd8JPfhpwJ")).
pos(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187460%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CheungF98","ujeEtXpQFIsJ")).
pos(eqo("journals/sigmod/ChienTZ01","cjBpI3TcSWsJ")).
pos(eqo("journals/sigmod/ChristoffelPSL98","JXiJ0MIQSf0J")).
pos(eqo("journals/sigmod/ChristoffelPSL98","yC3NWP247K8J")).
pos(eqo("journals/sigmod/ClementiniF00","9_GTdteKEYsJ")).
pos(eqo("journals/sigmod/CoxEH96","pqzGz7zfpDgJ")).
pos(eqo("journals/sigmod/DarwenD95","EXwe9r79qxEJ")).
pos(eqo("journals/sigmod/Dogac02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507340%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","_4ARkdpRArQJ")).
pos(eqo("journals/sigmod/DomenigD99","S6TMGRGUq1IJ")).
pos(eqo("journals/sigmod/EisenbergM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290604%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FernandezFLS97","9NlVdFCl2ysJ")).
pos(eqo("journals/sigmod/FernandezFLS97","LJKpMU1tIlcJ")).
pos(eqo("journals/sigmod/FernandezFLS97","NBlCYs05V_EJ")).
pos(eqo("journals/sigmod/FowlerPNB99","IgAEpc8ulvYJ")).
pos(eqo("journals/sigmod/FowlerPNB99","Mo-tkboGfcoJ")).
pos(eqo("journals/sigmod/FowlerPNB99","OewAZ4AUDOQJ")).
pos(eqo("journals/sigmod/FowlerPNB99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310060%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","5PisY7JvbzQJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","93C5Prxx5YcJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","HJRR7GGfD6sJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ixz5LdVw9_8J")).
pos(eqo("journals/sigmod/FrewD97","5jMT1PENhSIJ")).
pos(eqo("journals/sigmod/Gaffney96","uaT2hY6421UJ")).
pos(eqo("journals/sigmod/GatziuKBF98","C8tPNXRbNnIJ")).
pos(eqo("journals/sigmod/GobleR02a","B-u4advaVBkJ")).
pos(eqo("journals/sigmod/GuptaHR97","-ha8fD8Kj_oJ")).
pos(eqo("journals/sigmod/HansonN99","O5m6UXQ_Xv4J")).
pos(eqo("journals/sigmod/HansonN99","b5uRDGKYrcMJ")).
pos(eqo("journals/sigmod/HasanFV96","vIBvTfMLL4UJ")).
pos(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
pos(eqo("journals/sigmod/HummerLW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Jannink95","22yR9rN5xuQJ")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","CFMujYunuKcJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","WJ_VcY3mmEkJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","ebvQpXWJZt0J")).
pos(eqo("journals/sigmod/JensenCEGHJ94","gwV15NcKT9IJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","rRrT0v_j7tkJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","uncXRzIdSjYJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JensenCEGHJ94","yK4VALoQjlgJ")).
pos(eqo("journals/sigmod/JukicNV03","eR43Urfx-hcJ")).
pos(eqo("journals/sigmod/KambhampatiK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/LeeC00","Knzz_bkGA00J")).
pos(eqo("journals/sigmod/Libkin99","V_FnUWKirh8J")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","IoNxL_rg2_cJ")).
pos(eqo("journals/sigmod/MeltonMJKSZ01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373709%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Neven02","xAXF0HSF4h8J")).
pos(eqo("journals/sigmod/OConnellW03","SeDkIL_DlRwJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","F7AdjoH_uTcJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","ZsUpDroAFBQJ")).
pos(eqo("journals/sigmod/PourabbasR00","odFtqwn5ZVcJ")).
pos(eqo("journals/sigmod/Qian94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187462%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Qian95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Rosneblatt94","D1RdxKP6_6YJ")).
pos(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
pos(eqo("journals/sigmod/SayginVC01","Tp9iVMsAzocJ")).
pos(eqo("journals/sigmod/SayginVC01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604271%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ShethBS99","cqlnSEkt12EJ")).
pos(eqo("journals/sigmod/ShinM94","hnpTcGMYR80J")).
pos(eqo("journals/sigmod/Snodgrass02","_qopgNiYmXQJ")).
pos(eqo("journals/sigmod/Stirling03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776997%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/TatarinovIMHSDDKMM03","0JPhnHlRGOoJ")).
pos(eqo("journals/sigmod/TatarinovIMHSDDKMM03","rrSZOoViGqoJ")).
pos(eqo("journals/sigmod/Yang94","sHJ914nPZtUJ")).
pos(eqo("journals/sigmod/YauLMS99","bhVBJw9Rp3QJ")).
pos(eqo("journals/sigmod/YauLMS99","vWwVQvcIrbEJ")).
pos(eqo("journals/sigmod/ZobelMR96","6NbNX8nSta0J")).
pos(eqo("journals/tods/BellNNS96","pz2VRTdXq1cJ")).
pos(eqo("journals/tods/BozkayaO99","CEKbSWc_C6UJ")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/tods/ChaudhuriS99","QCFUIVkspywJ")).
pos(eqo("journals/tods/Chen95a","qexCEm3QaUgJ")).
pos(eqo("journals/tods/CliffordC94","OY6BjHhbz2cJ")).
pos(eqo("journals/tods/DattaVCK99","3BbftjVsIEIJ")).
pos(eqo("journals/tods/EiterLLS01","lTwQVB8E7SIJ")).
pos(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
pos(eqo("journals/tods/FukudaMMT01","_2f7zWIzK0QJ")).
pos(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
pos(eqo("journals/tods/FukudaMMT01","lmXiI4fB9vgJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","TQ8M8qOzJO8J")).
pos(eqo("journals/tods/Galindo-LegariaR97","Vjga5yC23KIJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
pos(eqo("journals/tods/GuoSW96","V8Ls_TYs6mgJ")).
pos(eqo("journals/tods/KonopnickiS98","5cWufy7ZrAoJ")).
pos(eqo("journals/tods/KotidisR01","04utamFvle4J")).
pos(eqo("journals/tods/KrishnakumarB94","8ZjEDOBUd_QJ")).
pos(eqo("journals/tods/LitwinN96","l0W27c1C3NwJ")).
pos(eqo("journals/tods/Subrahmanian94","wl8Wa2O28_oJ")).
pos(eqo("journals/tods/Suciu02","Y7kHpHu3nP0J")).
pos(eqo("journals/tods/TaoSP03","FBp7oibu4ygJ")).
pos(eqo("journals/vldb/AbadiCCCCLSTZ03","gBVNSFeS4P8J")).
pos(eqo("journals/vldb/AlbanoGO95","vrD2aAK6G-wJ")).
pos(eqo("journals/vldb/AtkinsonM95","dahaBAYvs5AJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","Hc9uWxJu840J")).
pos(eqo("journals/vldb/Barbara-MillaG94","IvPHHa01uUkJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","md3DWyujCrQJ")).
pos(eqo("journals/vldb/BarbaraI95","XfvqAOX1qo4J")).
pos(eqo("journals/vldb/BerchtoldKK97","VHo2go6vjYsJ")).
pos(eqo("journals/vldb/BohmAnY97","XsTFqLpfsfgJ")).
pos(eqo("journals/vldb/CasatiSG01","347oyb_b7DAJ")).
pos(eqo("journals/vldb/ChakrabartiDAR98","0EbuWDceVnoJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","3mVAyjsRXiwJ")).
pos(eqo("journals/vldb/ClaussenKKW00","DSF-ukHbE64J")).
pos(eqo("journals/vldb/Cobb97","R6XK3NbfZrgJ")).
pos(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
pos(eqo("journals/vldb/DoanMDDH03","InzqepkG0W8J")).
pos(eqo("journals/vldb/FuCCM00","7kC8fo78d6sJ")).
pos(eqo("journals/vldb/Guting94","-7PP3rSp1UcJ")).
pos(eqo("journals/vldb/Guting94","hoNylhoOWr4J")).
pos(eqo("journals/vldb/Guting94","url:http://www.springerlink.com/index/P4Q0445827654287.pdf")).
pos(eqo("journals/vldb/HansonCDERTX98","F6Ko8ZvWypUJ")).
pos(eqo("journals/vldb/HuntAI02","LiYp5oaDwbMJ")).
pos(eqo("journals/vldb/KemperK95","5CZ1gTCb5Z4J")).
pos(eqo("journals/vldb/LandauST95","E8U_krxA1dsJ")).
pos(eqo("journals/vldb/LinJF94","8-USisLIGMMJ")).
pos(eqo("journals/vldb/LinJF94","EgX8AQ2wfhAJ")).
pos(eqo("journals/vldb/LinJF94","vmxFQL7lhKoJ")).
pos(eqo("journals/vldb/MaedcheMS03","qKJ1c8D-95wJ")).
pos(eqo("journals/vldb/MaratheS02","z6JEYoArZmsJ")).
pos(eqo("journals/vldb/PacittiS00","9ReaNbX2I-IJ")).
pos(eqo("journals/vldb/PacittiS00","ZmvL3_H6DqUJ")).
pos(eqo("journals/vldb/PapadiasS94","UM0nh_l5epoJ")).
pos(eqo("journals/vldb/PapadiasS94","_ANyhrnP3CoJ")).
pos(eqo("journals/vldb/PapadiasS94","kEte3P_QB60J")).
pos(eqo("journals/vldb/PottingerH01","M2zV0WBF7XYJ")).
pos(eqo("journals/vldb/PucheralBVB01","q42RuW4_FogJ")).
pos(eqo("journals/vldb/RafieiM02","kZFfJieudW4J")).
pos(eqo("journals/vldb/RahmB01","TBoS0CBe1vQJ")).
pos(eqo("journals/vldb/RamamohanaraoH94","UiWvxN_y9SAJ")).
pos(eqo("journals/vldb/SheikholeslamiCZ00","Eo0JhvpLGj0J")).
pos(eqo("journals/vldb/SivasankaranSTPR96","XX_3v0k3v6QJ")).
pos(eqo("journals/vldb/SivasankaranSTPR96","url:http://ieeexplore.ieee.org/iel2/997/7843/00331718.pdf%3Farnumber%3D331718")).
pos(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
