neg(eqo("conf/sigmod/AcharyaGPR99","czJmrc_4tZ4J")).
neg(eqo("conf/sigmod/AcharyaPR99","-k0cD5NwXnoJ")).
neg(eqo("conf/sigmod/AcharyaPR99","vCp9gBsnczgJ")).
neg(eqo("conf/sigmod/AdaliBSS98","rYC-j_j4Yv0J")).
neg(eqo("conf/sigmod/Aggarwal03","-ha8fD8Kj_oJ")).
neg(eqo("conf/sigmod/AgichteinGV01","Tw8-f4saqb0J")).
neg(eqo("conf/sigmod/AgichteinGV01","abZTdba56a4J")).
neg(eqo("conf/sigmod/AgrawalCFGHIIMMSS94","6scmBfFW0ngJ")).
neg(eqo("conf/sigmod/AgrawalCFGHIIMMSS94","zIbfdZRwsfEJ")).
neg(eqo("conf/sigmod/AgrawalES03","Wrue2IkpGyEJ")).
neg(eqo("conf/sigmod/AgrawalES03","cUHoPtgmTMgJ")).
neg(eqo("conf/sigmod/AgrawalK03","Yt-cq_4cfE8J")).
neg(eqo("conf/sigmod/ArefBV95","4OyxeTf6A3EJ")).
neg(eqo("conf/sigmod/Arpaci-DusseauACHP97","O-TrhFwhKM8J")).
neg(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
neg(eqo("conf/sigmod/BabcockO03","Z8SMCV3VZP8J")).
neg(eqo("conf/sigmod/BargaL99","WwiNzuiIqPMJ")).
neg(eqo("conf/sigmod/BaruFGHJPW95","AOP7teXoIYQJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","kCH4ZzrozMkJ")).
neg(eqo("conf/sigmod/BerchtoldK98","uUheX89cbr0J")).
neg(eqo("conf/sigmod/BergstraesserBPS99","bk4uP5Onwu8J")).
neg(eqo("conf/sigmod/BergstraesserBPS99","qcZ2tYThtK0J")).
neg(eqo("conf/sigmod/Bernstein96","fBxgr7b7PPgJ")).
neg(eqo("conf/sigmod/BertinoCF01","Jwegiego4ycJ")).
neg(eqo("conf/sigmod/BertinoCF01","bBvZMwOE1aYJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","aepGxosl6YoJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","c57d3rgd3IcJ")).
neg(eqo("conf/sigmod/BilirisFOP96","odFtqwn5ZVcJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","8pYDEOcgSMYJ")).
neg(eqo("conf/sigmod/BohannonMR01","MgphE2z3NqYJ")).
neg(eqo("conf/sigmod/BorkarDS01","cExZWIT9LZcJ")).
neg(eqo("conf/sigmod/BornhovdAKMPR03","uGXRy7xmoIYJ")).
neg(eqo("conf/sigmod/Bosworth03","Jtos3UQPkeEJ")).
neg(eqo("conf/sigmod/Bosworth03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637425%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
neg(eqo("conf/sigmod/BreunigKNS00","VY_BF4hZ9JQJ")).
neg(eqo("conf/sigmod/Brewer98","PjtgP4aQt00J")).
neg(eqo("conf/sigmod/Brewer98","h8WCSPS3psEJ")).
neg(eqo("conf/sigmod/BrinMUT97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637435%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BunemanKTT02","Pm3q5xaxlo0J")).
neg(eqo("conf/sigmod/BunemanKTT02","s54pMOqTUR8J")).
neg(eqo("conf/sigmod/BunemanM95","ciavnyh4U8UJ")).
neg(eqo("conf/sigmod/Bussler02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564801%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CallanCD99","-hUVSdRv5UUJ")).
neg(eqo("conf/sigmod/CallanCD99","xhOs8MMbLYMJ")).
neg(eqo("conf/sigmod/CareyFZ94","014dle23VE0J")).
neg(eqo("conf/sigmod/CeriFP98","cSEKNVCkb3sJ")).
neg(eqo("conf/sigmod/CeriFPP95","_97IHVhDq-YJ")).
neg(eqo("conf/sigmod/ChanI99","uLiEqn5nA_IJ")).
neg(eqo("conf/sigmod/Chaudhuri97","E3gvEEFL_AIJ")).
neg(eqo("conf/sigmod/Chaudhuri97","QkyXMep2bWsJ")).
neg(eqo("conf/sigmod/Chaudhuri97","aaQEdfkjWN8J")).
neg(eqo("conf/sigmod/ChaudhuriDN01","9PhYz-N58A8J")).
neg(eqo("conf/sigmod/ChaudhuriDN01","p6zcWuHfGd0J")).
neg(eqo("conf/sigmod/ChaudhuriDY95","darWCYZjZHcJ")).
neg(eqo("conf/sigmod/ChaudhuriGGM03","g6XLqjCRkFcJ")).
neg(eqo("conf/sigmod/ChaudhuriKN03","CkbwvUsMShsJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","8SH_0VwySnUJ")).
neg(eqo("conf/sigmod/ChenJDTW00","30i2w66KFhQJ")).
neg(eqo("conf/sigmod/ChenWZ98","LatjkQDqr6sJ")).
neg(eqo("conf/sigmod/ChristophidesACS94","dGbuUkhWNhMJ")).
neg(eqo("conf/sigmod/ColletC95","SG9kpHg_arUJ")).
neg(eqo("conf/sigmod/CookWZ94","DI_v0vb6784J")).
neg(eqo("conf/sigmod/CranorGJSS02","GYR0v7CFkP0J")).
neg(eqo("conf/sigmod/CruzALRZ97","YWWvQnGCpDEJ")).
neg(eqo("conf/sigmod/DasGR03","uPBlQ76s_g4J")).
neg(eqo("conf/sigmod/DasuJMS02","yZmDriG4-agJ")).
neg(eqo("conf/sigmod/DattaDTVSR02","VJPLu4mUiU4J")).
neg(eqo("conf/sigmod/DeHaanTCO03","url:http://www.springerlink.com/index/M421871538132Q56.pdf")).
neg(eqo("conf/sigmod/DeolaseeKPRS01","2TSv5fTfBVAJ")).
neg(eqo("conf/sigmod/DeolaseeKPRS01","ULJo4TD7B64J")).
neg(eqo("conf/sigmod/DeshpandeRSN98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1041434%26type%3Dpdf")).
neg(eqo("conf/sigmod/Deutsch95","c2UQ3AM5_f8J")).
neg(eqo("conf/sigmod/DogacAEOADAOS94","AgBMhm_0uEIJ")).
neg(eqo("conf/sigmod/FaloutsosRM94","IvmBi-V8RZ0J")).
neg(eqo("conf/sigmod/ForlizziGNS00","riugYzaMPjEJ")).
neg(eqo("conf/sigmod/FranklinJK96","B3PwhNu8Y6IJ")).
neg(eqo("conf/sigmod/FranklinJK96","USBXg-_E4FgJ")).
neg(eqo("conf/sigmod/Freeston95","C8RLbWKCgicJ")).
neg(eqo("conf/sigmod/FukudaMMT96","Y8UdbAPhYpUJ")).
neg(eqo("conf/sigmod/FukudaMMT96a","sOBRaiLLvZgJ")).
neg(eqo("conf/sigmod/Galhardas00","irPAXAFli2UJ")).
neg(eqo("conf/sigmod/GangulyGR03","L4aXHaUW3cUJ")).
neg(eqo("conf/sigmod/GebhardtJJ97","40m6Vt-S33AJ")).
neg(eqo("conf/sigmod/GehrkeGRL99","wMu3mOHrqfIJ")).
neg(eqo("conf/sigmod/GetoorTK01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D274461%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GionisGK01","i0DPBiVIRX8J")).
neg(eqo("conf/sigmod/GoldmanW00","3zf3WSt0B6UJ")).
neg(eqo("conf/sigmod/GoldmanW00","hBGcwElxNoQJ")).
neg(eqo("conf/sigmod/GrayHOS96","Pt8HNH8GrYwJ")).
neg(eqo("conf/sigmod/GrayHOS96","TUzhq1PjPsgJ")).
neg(eqo("conf/sigmod/GrayHOS96","g3qsNMr1_AwJ")).
neg(eqo("conf/sigmod/GraySSU03","NnKrsx4j4pkJ")).
neg(eqo("conf/sigmod/Greer99","oNPjyBZrURgJ")).
neg(eqo("conf/sigmod/GunopulosKTD00","VEDf7vb98i8J")).
neg(eqo("conf/sigmod/GuptaHR97","e-nYGVGiikkJ")).
neg(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
neg(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
neg(eqo("conf/sigmod/HanPY00","vXMwU21-7HMJ")).
neg(eqo("conf/sigmod/HellersteinN96","QyNfyYDySawJ")).
neg(eqo("conf/sigmod/HernandezS95","aX2C4QA7LV0J")).
neg(eqo("conf/sigmod/HinneburgK99","0apKW8XmvwsJ")).
neg(eqo("conf/sigmod/HinneburgKW02","vsgKNz-kktsJ")).
neg(eqo("conf/sigmod/HuangSW94","1tKWKmyczaYJ")).
neg(eqo("conf/sigmod/HwangLYMMGCSS94","flOTEP2XkyoJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","1lRZz4bZvxEJ")).
neg(eqo("conf/sigmod/IvesFFLW99","To_EjIKwfSAJ")).
neg(eqo("conf/sigmod/IvesFFLW99","f6JFkfhawW8J")).
neg(eqo("conf/sigmod/IvesLPST00","29btu5OspbAJ")).
neg(eqo("conf/sigmod/Ivinskis95","XxnZ72KAkIsJ")).
neg(eqo("conf/sigmod/JaedickeM98","qK-N8yVLSWUJ")).
neg(eqo("conf/sigmod/JagadishKS00","url:http://portal.acm.org/citation.cfm%3Fid%3D592202.592472")).
neg(eqo("conf/sigmod/KabraD98","0mZPhIiYP9IJ")).
neg(eqo("conf/sigmod/KalnisNOPT02","-YhMJ43VntgJ")).
neg(eqo("conf/sigmod/Keim99","t_8ES4SLNYQJ")).
neg(eqo("conf/sigmod/KeimK95","-ha8fD8Kj_oJ")).
neg(eqo("conf/sigmod/KotidisR99","OMqN9nFAR88J")).
neg(eqo("conf/sigmod/KoudasS03","D-ovsaXJxZgJ")).
neg(eqo("conf/sigmod/KoudasS03","q1d3zg1xc-4J")).
neg(eqo("conf/sigmod/KoudasS03","url:http://portal.acm.org/citation.cfm%3Fid%3D957137%26dl%3DACM%26coll%3Dportal%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LabioWGG00","EhR3fz7f7vcJ")).
neg(eqo("conf/sigmod/LabioYG99","wZwy4umq0FkJ")).
neg(eqo("conf/sigmod/LakshmananNHP99","egn46hGLw7gJ")).
neg(eqo("conf/sigmod/LazaridisM01","mLnQkcjOVtcJ")).
neg(eqo("conf/sigmod/LibkinMW96","3QgOnuIwVZMJ")).
neg(eqo("conf/sigmod/LiuPTBBZBHY98","ARlA724kukoJ")).
neg(eqo("conf/sigmod/LoR94","PpyOTK673dwJ")).
neg(eqo("conf/sigmod/LometT03","pFERU0azlgkJ")).
neg(eqo("conf/sigmod/Mamoulis03","yCQf5tQglE0J")).
neg(eqo("conf/sigmod/MankuRL99","CEMEibl31aIJ")).
neg(eqo("conf/sigmod/MattosM95","4ygpC0j5uugJ")).
neg(eqo("conf/sigmod/MiloAABN03","4zxRX5K-YSsJ")).
neg(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
neg(eqo("conf/sigmod/Mohan01","5C2yfBIpwDsJ")).
neg(eqo("conf/sigmod/Mohan01","EqF1i1bl7GIJ")).
neg(eqo("conf/sigmod/Mohan94","bfLZp1c7E1cJ")).
neg(eqo("conf/sigmod/MumickQM97","NWIELbagzysJ")).
neg(eqo("conf/sigmod/Mylopoulos98","LpUJhzsj7pIJ")).
neg(eqo("conf/sigmod/NazeriBO01","2E9I_lugGC4J")).
neg(eqo("conf/sigmod/OhHP00","Eq2AwWfNOwoJ")).
neg(eqo("conf/sigmod/OhHP00","Ln9Qv-Y92FoJ")).
neg(eqo("conf/sigmod/PapakonstantinouV99","YzlQnqjJvcYJ")).
neg(eqo("conf/sigmod/PatelD96","hWiIngXs5I0J")).
neg(eqo("conf/sigmod/PeiMHZ00","c0TSepqRwwMJ")).
neg(eqo("conf/sigmod/PolyzotisG02","FK5GEhwW7uQJ")).
neg(eqo("conf/sigmod/PolyzotisG02","k7RinzPIdhYJ")).
neg(eqo("conf/sigmod/Pruscino03","v0rD-1nzJmYJ")).
neg(eqo("conf/sigmod/RajagopalanML98","T3y7RiO95nUJ")).
neg(eqo("conf/sigmod/RaoR98","WlSXiMaxGlQJ")).
neg(eqo("conf/sigmod/RiedelFGN00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083793%26type%3Dpdf")).
neg(eqo("conf/sigmod/RiedewaldAA02","uUOJ1ozJGk0J")).
neg(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
neg(eqo("conf/sigmod/Ross00","IvPPfGjtao0J")).
neg(eqo("conf/sigmod/RothAHCCFSTW96","0TC6EBPaaIsJ")).
neg(eqo("conf/sigmod/RundensteinerKRCJM96","-KJJLp9JbcMJ")).
neg(eqo("conf/sigmod/Sahuguet01","OewAZ4AUDOQJ")).
neg(eqo("conf/sigmod/SalemBCL00","cM7u25ciwZUJ")).
neg(eqo("conf/sigmod/SaltenisJLL00","cvchvz9-m_oJ")).
neg(eqo("conf/sigmod/Seshadri03","N9NdxNRvMMkJ")).
neg(eqo("conf/sigmod/Seshadri03","xAXF0HSF4h8J")).
neg(eqo("conf/sigmod/SeshadriLR94","Zuvbr8Zn4xcJ")).
neg(eqo("conf/sigmod/ShklarSKT95","Q2y53UR0g6oJ")).
neg(eqo("conf/sigmod/SrikantA96","9t4Mce85HT4J")).
neg(eqo("conf/sigmod/SrikantA96","oAlX0rVQqlIJ")).
neg(eqo("conf/sigmod/Stonebraker98","ZflHZYysWAsJ")).
neg(eqo("conf/sigmod/Stonebraker98","aIowdqRMIZwJ")).
neg(eqo("conf/sigmod/SubramanianV98","KxwymZ2AGNQJ")).
neg(eqo("conf/sigmod/Suciu99","Kc7Y8VjKsZcJ")).
neg(eqo("conf/sigmod/Suciu99","l5DIpKYgodkJ")).
neg(eqo("conf/sigmod/Team95c","I9JXY0-R4GgJ")).
neg(eqo("conf/sigmod/TheobaldW02","O6CCKkRxAbwJ")).
neg(eqo("conf/sigmod/ThomasDM95","L6UVryx9SiQJ")).
neg(eqo("conf/sigmod/Ullman03","FHk2ADVAZ0oJ")).
neg(eqo("conf/sigmod/WangPFY03","5JXKbI5l1FYJ")).
neg(eqo("conf/sigmod/WangSCRZP97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107510%26type%3Dpdf")).
neg(eqo("conf/sigmod/WangSSZZW00","iBEI8pUanCEJ")).
neg(eqo("conf/sigmod/WangZS95","uzpyy9XRpgYJ")).
neg(eqo("conf/sigmod/WitkowskiBBDFGSS03","29btu5OspbAJ")).
neg(eqo("conf/sigmod/WuAA01","Kzhu2DS1g2oJ")).
neg(eqo("conf/sigmod/ZaharioudakisC97","12xRfc32PXoJ")).
neg(eqo("conf/sigmod/ZaharioudakisCLPU00","Pcf-_A85Vk0J")).
neg(eqo("conf/sigmod/ZhangDWEMPMDR03","-hDjIHYbgyUJ")).
neg(eqo("conf/sigmod/ZhangRL96","8UbrDL0jsOYJ")).
neg(eqo("conf/sigmod/ZhangRL96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D101082%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ZhouLP99","CCZANGBUDQUJ")).
neg(eqo("conf/sigmod/ZhouWGGZWXYF03","AwFxLUGiceUJ")).
neg(eqo("conf/sigmod/ZhuS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604271%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ZhuSZ03","iuyRrJJDBcIJ")).
neg(eqo("conf/vldb/AbiteboulACEMM99","1NZsxf_zwF4J")).
neg(eqo("conf/vldb/AbiteboulMRVW98","kuueK-yBQqMJ")).
neg(eqo("conf/vldb/AgarwalADGNRS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245908%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/AggarwalHWY03","url:http://doi.wiley.com/10.1002/ace.105")).
neg(eqo("conf/vldb/AgrawalKSX02","qOAebSfNGDEJ")).
neg(eqo("conf/vldb/AgrawalS94","2Z_X3zsf4CoJ")).
neg(eqo("conf/vldb/AmsalegFG95","DPVBuf0A4z0J")).
neg(eqo("conf/vldb/BalminPP00","1i6Px2N_3J0J")).
neg(eqo("conf/vldb/BaralisW94","2R6A5QJmMPYJ")).
neg(eqo("conf/vldb/BaumgartnerFG01a","GGyAHg9kwysJ")).
neg(eqo("conf/vldb/BaumgartnerFG01a","Pl0KQaoV5TQJ")).
neg(eqo("conf/vldb/BerchtoldKK96","vI9c-zUADl8J")).
neg(eqo("conf/vldb/Bhashyam96","cTuSm41U504J")).
neg(eqo("conf/vldb/BohannonGKNS02","VTDU8nvDyOUJ")).
neg(eqo("conf/vldb/BonczMK99","_Qx_bO92tZEJ")).
neg(eqo("conf/vldb/BouganimFV96","m9m0YpwaO4YJ")).
neg(eqo("conf/vldb/BouganimFV96","rT9Jb9sW6C4J")).
neg(eqo("conf/vldb/BrightR02","lovlkpxUzUsJ")).
neg(eqo("conf/vldb/Brin95","nK04Y68tRQ0J")).
neg(eqo("conf/vldb/BrinkhoffK94","7zBV3cTwybwJ")).
neg(eqo("conf/vldb/Brodie00","dLxEC1zbITQJ")).
neg(eqo("conf/vldb/Brodie00","url:http://www.springerlink.com/index/MV301H2472338044.pdf")).
neg(eqo("conf/vldb/Brodie03","DYZlq4rntjwJ")).
neg(eqo("conf/vldb/BrodieC99","X8NQL_-NIMgJ")).
neg(eqo("conf/vldb/BunemanDHOW95","gld2wLKYWpsJ")).
neg(eqo("conf/vldb/CasatiS00","k_O40ldI0LgJ")).
neg(eqo("conf/vldb/CasatiS00","zOgLngfe8iMJ")).
neg(eqo("conf/vldb/CatozziR01","x_mqIy3GCmAJ")).
neg(eqo("conf/vldb/CatozziR95","nQsk3GveFP0J")).
neg(eqo("conf/vldb/ChakrabartiM00","1R21hO7j9sQJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","wnke8ff8hYUJ")).
neg(eqo("conf/vldb/ChanFFGR02","sheXatSCreQJ")).
neg(eqo("conf/vldb/ChatziantoniouR97","XsTFqLpfsfgJ")).
neg(eqo("conf/vldb/ChaudhuriG99","4bS3tvLQ-LAJ")).
neg(eqo("conf/vldb/ChaudhuriG99","9GsZHpVf2_cJ")).
neg(eqo("conf/vldb/ChaudhuriN97","rUC9fLMNA2oJ")).
neg(eqo("conf/vldb/ChaudhuriW00","RYeFLYha0ewJ")).
neg(eqo("conf/vldb/CherniackFZ01","cSH0yhDfziQJ")).
neg(eqo("conf/vldb/ChienTZ01","eWCz_YJFqjcJ")).
neg(eqo("conf/vldb/ChoG00","YWWpljX0tQMJ")).
neg(eqo("conf/vldb/CormodeKMS03","HjwbHpPjvasJ")).
neg(eqo("conf/vldb/CosleyLP02","url:http://doi.wiley.com/10.1002/he.77")).
neg(eqo("conf/vldb/DayalHL01","WYcElJZgm5QJ")).
neg(eqo("conf/vldb/Deshpande00","jyPJLO8WnzgJ")).
neg(eqo("conf/vldb/DeutschPT99","xGW62ETeSQYJ")).
neg(eqo("conf/vldb/DiaoF03","Crt1JZ1eEj0J")).
neg(eqo("conf/vldb/DoDJJR98","krAZ7iDMEOQJ")).
neg(eqo("conf/vldb/DoR02","Va4zeo_AZ44J")).
neg(eqo("conf/vldb/DonjerkovicR99","6dAWUHYKqFUJ")).
neg(eqo("conf/vldb/DonjerkovicR99","OWe20vDyYO4J")).
neg(eqo("conf/vldb/EsterKSWX98","FBZw8n-gojUJ")).
neg(eqo("conf/vldb/FerrandinaMZ94","pj1mKocpW9QJ")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
neg(eqo("conf/vldb/FlorescuLS98","1R-a2apZxuUJ")).
neg(eqo("conf/vldb/FlorescuLSY99","1KSfxI44iGUJ")).
neg(eqo("conf/vldb/FlorescuLSY99","aUElZKC-txIJ")).
neg(eqo("conf/vldb/Fox02","_UvFtKx9HwQJ")).
neg(eqo("conf/vldb/GaoS03","4GVSHuHkWP0J")).
neg(eqo("conf/vldb/Garcia-MolinaLY98","lWVWAhlsyYYJ")).
neg(eqo("conf/vldb/GarofalakisG01","WS4ljty1ff8J")).
neg(eqo("conf/vldb/GarofalakisI97","8vJEjrhM7foJ")).
neg(eqo("conf/vldb/GoldmanW97","bI2pAZuEloQJ")).
neg(eqo("conf/vldb/GravanoIJKMS01","kxGdQhvpi_sJ")).
neg(eqo("conf/vldb/GuPS00","Wasfh3yBByAJ")).
neg(eqo("conf/vldb/GuptaHQ95","VCSbj6MwKlgJ")).
neg(eqo("conf/vldb/GutierrezPST94","wJjaZnzD6pAJ")).
neg(eqo("conf/vldb/Hammond96","-ndr_jftgFkJ")).
neg(eqo("conf/vldb/HanF95","7e_EwULfgusJ")).
neg(eqo("conf/vldb/HanF95","D48Ssn95H34J")).
neg(eqo("conf/vldb/HanF95","q1rkM5Gmek4J")).
neg(eqo("conf/vldb/HanF95","v9BdA55u_XMJ")).
neg(eqo("conf/vldb/HeMYW03","ButmJWjGXusJ")).
neg(eqo("conf/vldb/HeMYW03","LV6lOpI0U7QJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","7y9SomIIAG0J")).
neg(eqo("conf/vldb/IdrisGC94","uLUps8x_zWgJ")).
neg(eqo("conf/vldb/ImielinskiB02","OhQ-RU44ZVMJ")).
neg(eqo("conf/vldb/Ioannidis03","Fisbz3Xhpe0J")).
neg(eqo("conf/vldb/IwerksSS03","ts2UbC8iUd0J")).
neg(eqo("conf/vldb/JiangSLB00","XX7VcrTv0ZsJ")).
neg(eqo("conf/vldb/JohnsonM98","5lFmSD-p-jEJ")).
neg(eqo("conf/vldb/KaushikBNS02","_RMZmSBR_PUJ")).
neg(eqo("conf/vldb/KemmeA00","fIcZeXoZ4bIJ")).
neg(eqo("conf/vldb/KerstenWFKBC03","Q-wVevx1s5oJ")).
neg(eqo("conf/vldb/KiesslingK02","SdUYWRplKbIJ")).
neg(eqo("conf/vldb/KietzRS97","url:http://doi.ieeecomputersociety.org/10.1109/TKDE.2004.28")).
neg(eqo("conf/vldb/KilgerM94","3h0tvUkQFc4J")).
neg(eqo("conf/vldb/KnorrN98","_d2CERxUcNYJ")).
neg(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
neg(eqo("conf/vldb/KraftSRM03","iudgysm8LcgJ")).
neg(eqo("conf/vldb/Ladin00","kPTa4IiS_sgJ")).
neg(eqo("conf/vldb/LakshmiZ98","-k0cD5NwXnoJ")).
neg(eqo("conf/vldb/LeeL96","x4i6X_N1JBMJ")).
neg(eqo("conf/vldb/LingLL00","szHsyFiOuwAJ")).
neg(eqo("conf/vldb/LiuJ02","793XPMTdcBEJ")).
neg(eqo("conf/vldb/LockemannKKKN97","9numn7ZjHVQJ")).
neg(eqo("conf/vldb/LuSL95","9vDVrlE03kcJ")).
neg(eqo("conf/vldb/LudasaherGM00","_RMZmSBR_PUJ")).
neg(eqo("conf/vldb/MahnkeMS02","ujCYoqKS6BcJ")).
neg(eqo("conf/vldb/Malaika96","Wv-rqImFk_cJ")).
neg(eqo("conf/vldb/MatthesS94","SxhsoBnl-TsJ")).
neg(eqo("conf/vldb/McHughW99","QkyXMep2bWsJ")).
neg(eqo("conf/vldb/MeccaCM01","jSo5ezit0mgJ")).
neg(eqo("conf/vldb/MeekPK03","m1zguu2Ih30J")).
neg(eqo("conf/vldb/MengLLA03","ak63oe42C-oJ")).
neg(eqo("conf/vldb/Moerkotte02","-ypu5B-7y9YJ")).
neg(eqo("conf/vldb/MogiK95","2jqRKA8EJusJ")).
neg(eqo("conf/vldb/Mohan02a","AOfAOwaNqCYJ")).
neg(eqo("conf/vldb/Mohan02a","L9b9MvkOnWcJ")).
neg(eqo("conf/vldb/Mohan02a","aSGsk0TDJQoJ")).
neg(eqo("conf/vldb/Mohan02a","f9JfEpe5a24J")).
neg(eqo("conf/vldb/Mohan99","_2hj6snS3foJ")).
neg(eqo("conf/vldb/MurthyB03","P3CfoUrfYE0J")).
neg(eqo("conf/vldb/MuthOPW98","cuBZoXvIHy8J")).
neg(eqo("conf/vldb/NarayananS01","Wl7q-glMoFEJ")).
neg(eqo("conf/vldb/NetzCBF00","Jfbny6dw2awJ")).
neg(eqo("conf/vldb/NetzCBF00","mRIRFxOC8A8J")).
neg(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
neg(eqo("conf/vldb/NgH94","mX-oqtUEPZ4J")).
neg(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
neg(eqo("conf/vldb/Objectivity98","9FDqRUod4aMJ")).
neg(eqo("conf/vldb/OlstonW00","FuzSLPzjrokJ")).
neg(eqo("conf/vldb/OlstonW00","eVrwF0wcSfQJ")).
neg(eqo("conf/vldb/Orenstein98","VfWJDzGt9JYJ")).
neg(eqo("conf/vldb/Padmanabhan96","E02lExYdRYwJ")).
neg(eqo("conf/vldb/PapadiasMD98","7vbPCi-dbawJ")).
neg(eqo("conf/vldb/PapadiasTS03","i9KYmk14ATUJ")).
neg(eqo("conf/vldb/PardonA00","UUN-EcX8BisJ")).
neg(eqo("conf/vldb/PereiraFLS00","LWkKHDF9dEgJ")).
neg(eqo("conf/vldb/PereiraFLS00","X14g4few97QJ")).
neg(eqo("conf/vldb/PfoserJT00","8J1sLFcviQ0J")).
neg(eqo("conf/vldb/PfoserJT00","NtU4gusv7gEJ")).
neg(eqo("conf/vldb/Pogue98","bYLjqg3pPNgJ")).
neg(eqo("conf/vldb/PoosalaI97","99N4rXNdaqMJ")).
neg(eqo("conf/vldb/QianZXP03","EnycLFKkzpUJ")).
neg(eqo("conf/vldb/Ramanan03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D769815%26type%3Dhtml%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/RastogiS98","gNSRjezd168J")).
neg(eqo("conf/vldb/SadriZZA01","_xdKnndnOLMJ")).
neg(eqo("conf/vldb/SakuraiYUK00","5iohkq8tSIwJ")).
neg(eqo("conf/vldb/Sarawagi95","lOFly1WWz4EJ")).
neg(eqo("conf/vldb/Sarawagi95","nKNpemeXlikJ")).
neg(eqo("conf/vldb/SavasereON95","pN4pq6qELakJ")).
neg(eqo("conf/vldb/SchieferKBLF98","url:http://www.springerlink.com/index/CBHRGBHFTW90N54X.pdf")).
neg(eqo("conf/vldb/SchindlerAG03","CsWyDorgQF4J")).
neg(eqo("conf/vldb/Schnase00","KlPsHutXQi8J")).
neg(eqo("conf/vldb/Schnase00","Z9dkL1yphh8J")).
neg(eqo("conf/vldb/SeshadriLR97","jSAtXghimR0J")).
neg(eqo("conf/vldb/SevcikK96","03r6bm7AHH4J")).
neg(eqo("conf/vldb/SevcikK96","QMxbPo9Yv5oJ")).
neg(eqo("conf/vldb/ShaferAM96","url:http://doi.ieeecs.org/10.1109/WPDRTS.1996.557650")).
neg(eqo("conf/vldb/Shenker03","cS_J5LvlQBMJ")).
neg(eqo("conf/vldb/ShiSZ03","NffWJWoUDK0J")).
neg(eqo("conf/vldb/ShivakumarGC98","6moFnThDHW0J")).
neg(eqo("conf/vldb/Sol01","Ii2AoNilfEcJ")).
neg(eqo("conf/vldb/SrivastavaDJL96","yWyvTMAVVzwJ")).
neg(eqo("conf/vldb/StaudtJ96","hoEXxcXgqU4J")).
neg(eqo("conf/vldb/TaoPS02","FeOi0ph0KrAJ")).
neg(eqo("conf/vldb/TaoPS02","o0WQjRyBQ5kJ")).
neg(eqo("conf/vldb/VenkataramanZ98","GEBNdHM0xSgJ")).
neg(eqo("conf/vldb/VenkataramanZ98","fIcZeXoZ4bIJ")).
neg(eqo("conf/vldb/VermeerA96","Wl7q-glMoFEJ")).
neg(eqo("conf/vldb/VieiraM03","b9zAhFneX5YJ")).
neg(eqo("conf/vldb/VieiraM03","vB2-tiNWKpkJ")).
neg(eqo("conf/vldb/Wadler01","Isbc9SlTYT8J")).
neg(eqo("conf/vldb/Wang95","PJEn-Wr5PRsJ")).
neg(eqo("conf/vldb/Wang95","bnkP_MXjTPcJ")).
neg(eqo("conf/vldb/WangYM97","JubkWSUFbbcJ")).
neg(eqo("conf/vldb/WienerN95","nSOqc8sGGjcJ")).
neg(eqo("conf/vldb/WildfogelY97","j3gou1McdaAJ")).
neg(eqo("conf/vldb/XinHLW03","lZzzof2__9MJ")).
neg(eqo("conf/vldb/YagoubFIV00","195Hlqu94qEJ")).
neg(eqo("conf/vldb/YagoubFIV00a","NiyGvhgzXxAJ")).
neg(eqo("conf/vldb/YanG95","B-KfshhIPy4J")).
neg(eqo("conf/vldb/YangLH03","gF4nPxSCcOMJ")).
neg(eqo("conf/vldb/YuPM03","BNyOKJXXvDUJ")).
neg(eqo("conf/vldb/YuPM03","HGXaVrOM_NwJ")).
neg(eqo("conf/vldb/ZhangL98","36MkrLsTXHgJ")).
neg(eqo("conf/vldb/ZhangL98","ZjHAEBJYahAJ")).
neg(eqo("conf/vldb/ZurekS99","195Hlqu94qEJ")).
neg(eqo("journals/sigmod/AbelTK97","lvU4b-jL6-EJ")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/citation.cfm%3Fid%3D603867.603869%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02c","7MfXAAdBQ2EJ")).
neg(eqo("journals/sigmod/Aberer02c","NsIsEf3pjqUJ")).
neg(eqo("journals/sigmod/AdelbergKG96","3aPleydkcIoJ")).
neg(eqo("journals/sigmod/AilamakiFFSV03","ko4sYhwKPa4J")).
neg(eqo("journals/sigmod/AtkinsonDJPS96","yfjKkIhvfXcJ")).
neg(eqo("journals/sigmod/BallMRZ02","AUmbKDpid_IJ")).
neg(eqo("journals/sigmod/BarclayBGS94","wPhDoeiINQsJ")).
neg(eqo("journals/sigmod/BergamaschiCV99","4C9A2HGs4qsJ")).
neg(eqo("journals/sigmod/Bernstein01","Mw2MBOMo1_kJ")).
neg(eqo("journals/sigmod/BernsteinHP00","DSF-ukHbE64J")).
neg(eqo("journals/sigmod/BestavrosLS96","lQRNxqGvfEcJ")).
neg(eqo("journals/sigmod/BilirisP96","1WSTXNtfwJEJ")).
neg(eqo("journals/sigmod/BollKB98","IBg3vuolFUwJ")).
neg(eqo("journals/sigmod/BoulosO99","1qWnrA_8DUIJ")).
neg(eqo("journals/sigmod/CeriFP99","OewAZ4AUDOQJ")).
neg(eqo("journals/sigmod/CeriFP99","QyA8LLrWIloJ")).
neg(eqo("journals/sigmod/Chamberlin03","_F5D4QMbZ0sJ")).
neg(eqo("journals/sigmod/ChangGKRS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141831%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Chen94","ge5USB8ZSH0J")).
neg(eqo("journals/sigmod/ChengP03","2h7zqIfyfQMJ")).
neg(eqo("journals/sigmod/CiliaB02","7fktytkfeaQJ")).
neg(eqo("journals/sigmod/CoxEH96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057842")).
neg(eqo("journals/sigmod/DAndreaJ96","RUn5McMYx8YJ")).
neg(eqo("journals/sigmod/DarwenD95","4lIfeG724kkJ")).
neg(eqo("journals/sigmod/DarwenD95","EXwe9r79qxEJ")).
neg(eqo("journals/sigmod/DarwenD95","W3JPtW_ShgoJ")).
neg(eqo("journals/sigmod/Dogac98","url:http://www.springerlink.com/index/M034H4H63472723J.pdf")).
neg(eqo("journals/sigmod/DogacDATKCD98","fYMpjIpF8ckJ")).
neg(eqo("journals/sigmod/DongS00","7xa2FxbUh2cJ")).
neg(eqo("journals/sigmod/DongS00","gH_HDDJghbAJ")).
neg(eqo("journals/sigmod/EisenbergM00","-RAYAJbKLNUJ")).
neg(eqo("journals/sigmod/EisenbergM02","GKUflKzgAVEJ")).
neg(eqo("journals/sigmod/FengJH01","q6YVJJgD1uQJ")).
neg(eqo("journals/sigmod/FowlerPNB99","IgAEpc8ulvYJ")).
neg(eqo("journals/sigmod/Franklin00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/Franklin97a","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin98a","VGe-IBWyMm4J")).
neg(eqo("journals/sigmod/Gaffney96","MwqEpsCM5OQJ")).
neg(eqo("journals/sigmod/Gaffney96","xLM0YVcccUgJ")).
neg(eqo("journals/sigmod/GatziuJSV99","HyTQHQf6MGcJ")).
neg(eqo("journals/sigmod/Geller02","hfrMmlaE-vwJ")).
neg(eqo("journals/sigmod/GobleR02","fX2cmd-DJykJ")).
neg(eqo("journals/sigmod/GroskyFS94","AwLFPdDbObsJ")).
neg(eqo("journals/sigmod/GroskyFS94","gpjVvUtM6H8J")).
neg(eqo("journals/sigmod/GroskySF02","Sql66UDiVnwJ")).
neg(eqo("journals/sigmod/GroskySF02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988600%26type%3Dpdf")).
neg(eqo("journals/sigmod/Group94","7VSlB0yIt3YJ")).
neg(eqo("journals/sigmod/Group94","u-AtUIUfqkwJ")).
neg(eqo("journals/sigmod/GuptaHR97","eRSkDzxP1JcJ")).
neg(eqo("journals/sigmod/Hammer02","_-JZT1cOuZ8J")).
neg(eqo("journals/sigmod/Han98","_rlpIiNduaYJ")).
neg(eqo("journals/sigmod/Han98","qNLsbj_Fu5EJ")).
neg(eqo("journals/sigmod/HasanFV96","S3BkPvUCbXYJ")).
neg(eqo("journals/sigmod/JacobS99","jNjxe59ZOLAJ")).
neg(eqo("journals/sigmod/JensenCEGHJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
neg(eqo("journals/sigmod/KuokFW98","ALk7huiKjWAJ")).
neg(eqo("journals/sigmod/Labrinidis01","Wcbvsi-QDtcJ")).
neg(eqo("journals/sigmod/Labrinidis01","qmRmn_FF5R4J")).
neg(eqo("journals/sigmod/LeeF01","gtWXcs-6QzwJ")).
neg(eqo("journals/sigmod/Libkin99a","KUY0gZdsBlYJ")).
neg(eqo("journals/sigmod/Liu01","url:http://doi.wiley.com/10.1002/ev.1000")).
neg(eqo("journals/sigmod/Liu02a","CBxdOQgyPXcJ")).
neg(eqo("journals/sigmod/Liu02b","r3hFnyB0LAQJ")).
neg(eqo("journals/sigmod/Liu02c","_KKkrRdguAgJ")).
neg(eqo("journals/sigmod/Liu03a","36_Z5VHBVsgJ")).
neg(eqo("journals/sigmod/LometBCLN98","url:http://doi.wiley.com/10.1002/he.133")).
neg(eqo("journals/sigmod/MalaikaEM03","SbqQVRNWSPYJ")).
neg(eqo("journals/sigmod/Mani03","D-woVvSGh4cJ")).
neg(eqo("journals/sigmod/Mani03","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0804723CI")).
neg(eqo("journals/sigmod/Manola98","T9mhgoged8AJ")).
neg(eqo("journals/sigmod/MeltonE02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637435%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Neven02","6i0hHoSzqFkJ")).
neg(eqo("journals/sigmod/OrlandicLS02","0BeilGyr2iQJ")).
neg(eqo("journals/sigmod/PitouraB95","zSM0goBgDdsJ")).
neg(eqo("journals/sigmod/Qian94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187462%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian95a","4Y125m3-bsYJ")).
neg(eqo("journals/sigmod/Qian95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601877%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96a","6D-EwyacOIwJ")).
neg(eqo("journals/sigmod/Qian96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187462%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RamDD99","IQFTgS-nitYJ")).
neg(eqo("journals/sigmod/RiekertMW97","J6I08uuEyIcJ")).
neg(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","9Ai_9dZChG4J")).
neg(eqo("journals/sigmod/Segev94","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/SegevJS95","M1MgDozqNgAJ")).
neg(eqo("journals/sigmod/Seshadri98","7gJjI63FlyYJ")).
neg(eqo("journals/sigmod/SlivinskasJS02","xTPSs2k_pUIJ")).
neg(eqo("journals/sigmod/Snodgrass02","l7ElxBfCtFgJ")).
neg(eqo("journals/sigmod/Snodgrass02a","jaGnG-R3fUAJ")).
neg(eqo("journals/sigmod/Snodgrass03","lCw-7Q4LbsYJ")).
neg(eqo("journals/sigmod/Snodgrass03","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084832")).
neg(eqo("journals/sigmod/Snodgrass03b","Di-EjDZ_abYJ")).
neg(eqo("journals/sigmod/Snodgrass03b","rGfhB3UE5mYJ")).
neg(eqo("journals/sigmod/Snodgrass03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107521%26type%3Dpdf")).
neg(eqo("journals/sigmod/Snodgrass94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107521%26type%3Dpdf")).
neg(eqo("journals/sigmod/Stonebraker02","OiFyf-aJ80cJ")).
neg(eqo("journals/sigmod/Suciu01","7wR9m6I7AXIJ")).
neg(eqo("journals/sigmod/Suciu01","GwvN1w9_ZZoJ")).
neg(eqo("journals/sigmod/Suciu01","Z9e9dqy5KBgJ")).
neg(eqo("journals/sigmod/TanakaV01","kwL0VfhAT4EJ")).
neg(eqo("journals/sigmod/TsotrasK96","Pvh4vhSxHaIJ")).
neg(eqo("journals/sigmod/VelACM01","AB3gUCdE2j8J")).
neg(eqo("journals/sigmod/Vianu03","LiIWlw3oNgUJ")).
neg(eqo("journals/sigmod/Wade96","I9JXY0-R4GgJ")).
neg(eqo("journals/sigmod/WangD03","url:http://doi.wiley.com/10.1002/he.125")).
neg(eqo("journals/sigmod/Widom95","url:http://portal.acm.org/citation.cfm%3Fid%3D233269%26dl%3DGUIDE%26dl%3DGUIDE%26type%3Dproceeding%26idx%3D233269%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom95","vgcXH5aVpdgJ")).
neg(eqo("journals/sigmod/Widom95a","hqDtMiCwjGoJ")).
neg(eqo("journals/sigmod/Widom95a","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Widom96","vgcXH5aVpdgJ")).
neg(eqo("journals/sigmod/Widom96a","A_i4OxOjMe0J")).
neg(eqo("journals/sigmod/Widom96a","lAbG3uFZvVUJ")).
neg(eqo("journals/sigmod/Winslett94","UVsqO1tB5BkJ")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/citation.cfm%3Fid%3D1024694.1024713")).
neg(eqo("journals/sigmod/X94b","IGS3TtqfKUgJ")).
neg(eqo("journals/sigmod/YanG95","qaSgL5tVq1AJ")).
neg(eqo("journals/tods/BertinoBFS98","Vcpb8Hw_55EJ")).
neg(eqo("journals/tods/BohlenJS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083723%26type%3Dpdf")).
neg(eqo("journals/tods/BozkayaO99","PBQNcqSsnyEJ")).
neg(eqo("journals/tods/BozkayaO99","wydX47pzgigJ")).
neg(eqo("journals/tods/BrightHP94","g2a-s_ZYgl4J")).
neg(eqo("journals/tods/BunemanO96","rVC45yk8BEIJ")).
neg(eqo("journals/tods/CasatiCPP99","PsE2y5rdLDYJ")).
neg(eqo("journals/tods/Chen95a","81L35Gk4oiUJ")).
neg(eqo("journals/tods/ChoG03","D4MiKRaC-rEJ")).
neg(eqo("journals/tods/DattaVCK99","Fu5kekc4LesJ")).
neg(eqo("journals/tods/EiterLLS01","qC2R7o8q3tQJ")).
neg(eqo("journals/tods/FernandezKSMT02","qbQLwnrAZjQJ")).
neg(eqo("journals/tods/FormicaGM98","UvlvM-e5y2MJ")).
neg(eqo("journals/tods/FukudaMMT01","cFMtMf7bLzIJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","SSZ9P5EC_EYJ")).
neg(eqo("journals/tods/KarpSP03","_BQuO1XM-FwJ")).
neg(eqo("journals/tods/LechtenborgerV03","FqWSEStXZSAJ")).
neg(eqo("journals/tods/LeveneL99","5Chw6HN64vEJ")).
neg(eqo("journals/tods/LiuHD98","hmntS6affLQJ")).
neg(eqo("journals/tods/ParsonsW00","3teYZJkhCmQJ")).
neg(eqo("journals/tods/RaschidL96","LY3qhBvCAk0J")).
neg(eqo("journals/tods/SchuldtABS02","tp1_LRYeLcwJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/LD48KCXJWTCRACDL.pdf")).
neg(eqo("journals/tods/WandSW99","l5iQttdP9bEJ")).
neg(eqo("journals/tods/WangBBJ97","6yvQx-yzKBYJ")).
neg(eqo("journals/tods/Wijsen99","3o-rUvRsdUwJ")).
neg(eqo("journals/tods/ZobelMR98","TkPepQPPXpcJ")).
neg(eqo("journals/vldb/AbbadiSW01","3rwpLn-qoCoJ")).
neg(eqo("journals/vldb/AgrawalHK03","MsITCEjzWWAJ")).
neg(eqo("journals/vldb/AtluriJY03","347oyb_b7DAJ")).
neg(eqo("journals/vldb/Barbara-MillaG94","HosWQKWM8RkJ")).
neg(eqo("journals/vldb/Baumann94","ruVmVa1bhoUJ")).
neg(eqo("journals/vldb/C94a","IYG4xCCSrqkJ")).
neg(eqo("journals/vldb/C94b","rTJq0oP1cogJ")).
neg(eqo("journals/vldb/ChangG01","H4BAFnrsTbwJ")).
neg(eqo("journals/vldb/Cobb97","o1kWTuMxumgJ")).
neg(eqo("journals/vldb/DanYC95","VcQNe9SlIhQJ")).
neg(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
neg(eqo("journals/vldb/DeyBS96","ewiOz8HzOZUJ")).
neg(eqo("journals/vldb/DiazJ97","BIVKa5lteLEJ")).
neg(eqo("journals/vldb/DiazJ97","u8wK0QOS95IJ")).
neg(eqo("journals/vldb/EvangelidisS97","3TOqLeL1G64J")).
neg(eqo("journals/vldb/GeorgakopoulosRL94","EAZ5Gz22bIUJ")).
neg(eqo("journals/vldb/GutingS95","A4lUwOD7AeYJ")).
neg(eqo("journals/vldb/Halevy02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D990302%26type%3Dpdf")).
neg(eqo("journals/vldb/HarderST99","bEddMdwB2_4J")).
neg(eqo("journals/vldb/KornLKF00","PcAKDUTqlgoJ")).
neg(eqo("journals/vldb/KraissW98","yabWSyqur-8J")).
neg(eqo("journals/vldb/LeeSC01","Hz_TU6kUj08J")).
neg(eqo("journals/vldb/Li03","lNONjCNrKDcJ")).
neg(eqo("journals/vldb/LiCHH01","0FohHTWs5toJ")).
neg(eqo("journals/vldb/LometS97","csOZscyXQ4IJ")).
neg(eqo("journals/vldb/MaratheS02","m1ECCPPPUE8J")).
neg(eqo("journals/vldb/MedjahedBE03","Rpp3GTLdvG8J")).
neg(eqo("journals/vldb/MedjahedBE03","YqXx_xeZE2gJ")).
neg(eqo("journals/vldb/NanopoulosM02","icoWjIZ_6IIJ")).
neg(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
neg(eqo("journals/vldb/PoulovassilisS96","Tr0MxRKKUvwJ")).
neg(eqo("journals/vldb/RafieiM02","VYYKHi96iQkJ")).
neg(eqo("journals/vldb/RafieiM02","laSbNcPJmpYJ")).
neg(eqo("journals/vldb/RahmB01","GZjipB5AMeoJ")).
neg(eqo("journals/vldb/RahmB01","kF0v214JF1QJ")).
neg(eqo("journals/vldb/RamanRH00","8PPmw6A0XfkJ")).
neg(eqo("journals/vldb/RamanRH00","QszNQ-R3QsMJ")).
neg(eqo("journals/vldb/Sarawagi01","MOvQoZozEmcJ")).
neg(eqo("journals/vldb/ShegalovGW01","sCpLAZN7GPsJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","Snx8LBMXFJUJ")).
neg(eqo("journals/vldb/SwamiS95","9BuBq-Tj0TUJ")).
neg(eqo("journals/vldb/TurkerG01","LY3qhBvCAk0J")).
neg(eqo("journals/vldb/TurkerG01","qvvNAgVcQFsJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","C221gFS5VVoJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","IkNOhDqEY18J")).
pos(eqo("conf/sigmod/AcharyaGPR99a","VlVV2mEnoQ4J")).
pos(eqo("conf/sigmod/AcharyaGPR99a","czJmrc_4tZ4J")).
pos(eqo("conf/sigmod/AfratiLU01","U8adXFUIr3EJ")).
pos(eqo("conf/sigmod/Agarwal96","Ca-BABwlsQAJ")).
pos(eqo("conf/sigmod/Agarwal96","Fd0jPlSwFWcJ")).
pos(eqo("conf/sigmod/AgrawalCD02","iABZEL2Zoz8J")).
pos(eqo("conf/sigmod/AgrawalGGR98","_LE5T2vKPUcJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","rSTewQ1dQkYJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AgrawalS00","ufPUBsN4eg0J")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","YAkpVC1qgaIJ")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","DFubU20j1OIJ")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","wGxcAPsmHgIJ")).
pos(eqo("conf/sigmod/ArasuBBDIRW03","7D59wPTtkdcJ")).
pos(eqo("conf/sigmod/ArasuG03","zN8ngmWNDlgJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","6_FvrRYnxHYJ")).
pos(eqo("conf/sigmod/BabcockCD03","mbhZ3gSR3NMJ")).
pos(eqo("conf/sigmod/Bampahl95","MbgdgwgZCIUJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","3SHIgRrrL5QJ")).
pos(eqo("conf/sigmod/BenediktCFFR03","T5ZdpquqfJ0J")).
pos(eqo("conf/sigmod/BerchtoldK97","DNVHTz7tMywJ")).
pos(eqo("conf/sigmod/BerchtoldK97","lYpquDAEzrIJ")).
pos(eqo("conf/sigmod/BerchtoldK98","9UYo0M1RV7oJ")).
pos(eqo("conf/sigmod/BerchtoldK98","PKMN5Cdy7KcJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","-lYgZoLNtioJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","MOGnM6t6l3MJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","gWmqoNZHKAAJ")).
pos(eqo("conf/sigmod/BergstraesserBPS99","4Ha7Bs5Vq3MJ")).
pos(eqo("conf/sigmod/BersonGMJ94","bw_c9Mk0_7IJ")).
pos(eqo("conf/sigmod/BersonGMJ94","wsG_Q2jbgCAJ")).
pos(eqo("conf/sigmod/BettiniWBJ95","wZkNJJn90yAJ")).
pos(eqo("conf/sigmod/Bierman03","vQcfluHWCeAJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97a","NiBdZXS0TCMJ")).
pos(eqo("conf/sigmod/BorkarDS01","nsoA6Gcc_jsJ")).
pos(eqo("conf/sigmod/BratsbergT00","jVWhNoPA0CcJ")).
pos(eqo("conf/sigmod/BreitbartKRSS99","XV2lpkhWCsYJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","_1drQdYrtmsJ")).
pos(eqo("conf/sigmod/BreunigKKS01","3ET_IEkoGjYJ")).
pos(eqo("conf/sigmod/BreunigKKS01","h-tyLTytlh4J")).
pos(eqo("conf/sigmod/BreunigKNS00","4ZBs-U7sOk0J")).
pos(eqo("conf/sigmod/BreunigKNS00","8lIwxMfoZN4J")).
pos(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
pos(eqo("conf/sigmod/BrinDG95","JsKYXyM6IaEJ")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","qk4kfo7BXvUJ")).
pos(eqo("conf/sigmod/BumbulisB02","Ev27auQiecUJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","3_X-dmpUEWMJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","jMc3U-zRTPEJ")).
pos(eqo("conf/sigmod/CareyK97","2OPEy9_6BlEJ")).
pos(eqo("conf/sigmod/CareyK97","b_lpj8wu7BEJ")).
pos(eqo("conf/sigmod/CareyMN97","u64n4yMnma4J")).
pos(eqo("conf/sigmod/CarinoKKB01","a9HFF_bwiH4J")).
pos(eqo("conf/sigmod/CatarciS94","pryJrhEGI2sJ")).
pos(eqo("conf/sigmod/Cattell94","zSoTbEtLuqEJ")).
pos(eqo("conf/sigmod/Chakravarthy97","pCsAI2xXTPoJ")).
pos(eqo("conf/sigmod/Chakravarthy97","xAwNq-a4ju0J")).
pos(eqo("conf/sigmod/Chamberlin03","_F5D4QMbZ0sJ")).
pos(eqo("conf/sigmod/ChanI98","63t-u0Menw4J")).
pos(eqo("conf/sigmod/ChanI98","VC7Jbwgn_O0J")).
pos(eqo("conf/sigmod/ChaudhuriMN99","clNmwzm-5acJ")).
pos(eqo("conf/sigmod/ChenZCKR01","RHoy5iOHsJwJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","I0KBB-n-eF8J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D280357%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChristophidesCM96","nDl2k1YSi8AJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","q3Y-Mlx2sUsJ")).
pos(eqo("conf/sigmod/ChungMS02","UmPir9n5JloJ")).
pos(eqo("conf/sigmod/ColletC95","vP27NkXI4MEJ")).
pos(eqo("conf/sigmod/CorralMTV00","TsShfxPwF6YJ")).
pos(eqo("conf/sigmod/CrescenziMM02","pI0WktymowwJ")).
pos(eqo("conf/sigmod/DattaDTVSR02","0m_Q5tf3oDAJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","3PH--zwkZO8J")).
pos(eqo("conf/sigmod/DeHaanTCO03","CD_xefdItVkJ")).
pos(eqo("conf/sigmod/DeligiannakisR03","zMgbS5u_GwYJ")).
pos(eqo("conf/sigmod/DeutschFS99","SR_yVgZnYpMJ")).
pos(eqo("conf/sigmod/DeutschFS99","Z9e9dqy5KBgJ")).
pos(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
pos(eqo("conf/sigmod/DeutschFS99","kDYpG4mLjLkJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","fsa72WmA67kJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","p6ro8VCQBwcJ")).
pos(eqo("conf/sigmod/DreyerDS95","i1qU2OFSeloJ")).
pos(eqo("conf/sigmod/EmbleyJN99","O_SMlr3bFBMJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","XMC0W6CQJJIJ")).
pos(eqo("conf/sigmod/FernandezMS01","JYYcPQLrBw8J")).
pos(eqo("conf/sigmod/FernandezS96","lMKrltuk53EJ")).
pos(eqo("conf/sigmod/FranklinJK96","0e3bs1VFPvAJ")).
pos(eqo("conf/sigmod/FranklinJK96","40cq9ovvXn8J")).
pos(eqo("conf/sigmod/FranklinJK96","iDBvvrHwj7YJ")).
pos(eqo("conf/sigmod/FreireHRRS02","Pg-vbrBME1cJ")).
pos(eqo("conf/sigmod/FreireHRRS02","YKkMxZntSUQJ")).
pos(eqo("conf/sigmod/Galhardas00","GxDfgCi-rq4J")).
pos(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
pos(eqo("conf/sigmod/GardarinMP95","VOxehNSHEWQJ")).
pos(eqo("conf/sigmod/GillmannWSWW00","L61_1TEGBLYJ")).
pos(eqo("conf/sigmod/Golding95","uJj9OgotYeEJ")).
pos(eqo("conf/sigmod/Golding95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223865%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D223784%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/GriffinH97","UwOPyY_jchkJ")).
pos(eqo("conf/sigmod/GuptaHR97","pGix0qZ6Uz4J")).
pos(eqo("conf/sigmod/GuptaS03","6ditJPVnXAQJ")).
pos(eqo("conf/sigmod/HanWDPW02","nwWpGh3Mx7MJ")).
pos(eqo("conf/sigmod/HernandezMHYHT01","89WHY6hZ22UJ")).
pos(eqo("conf/sigmod/HernandezMHYHT01","pOFhgBVYVTkJ")).
pos(eqo("conf/sigmod/HernandezMHYHT01","wMa4fMryrt0J")).
pos(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
pos(eqo("conf/sigmod/HillyerS96","zonW-W8gJ3oJ")).
pos(eqo("conf/sigmod/HinneburgK99","C9imFvgrSvAJ")).
pos(eqo("conf/sigmod/HinneburgK99","OMqN9nFAR88J")).
pos(eqo("conf/sigmod/HinneburgK99","V3cZfG1Poo4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","1H_A7k3QsbQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","7qv9IC8F_WQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","RcmGrB81X-4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","cffLplmoKH4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","u5ForuTsW-YJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","bbr1Xk0-hH8J")).
pos(eqo("conf/sigmod/IoannidisLANT97","qb-jf_sQ_5kJ")).
pos(eqo("conf/sigmod/JaedickeM98","9eSx_Gd0JoQJ")).
pos(eqo("conf/sigmod/JaedickeM98","Py0wIlQRPCkJ")).
pos(eqo("conf/sigmod/JagadishKS00","OZRYdxoJqXMJ")).
pos(eqo("conf/sigmod/JagadishLMSV99","946iAs3adDcJ")).
pos(eqo("conf/sigmod/Jamil99","z5EfiutEfScJ")).
pos(eqo("conf/sigmod/JoshiA01","H9bMRYKnXMQJ")).
pos(eqo("conf/sigmod/KabraD98","E0nhpX8pYsQJ")).
pos(eqo("conf/sigmod/KaushikBNK02","8M2rLLD3DlQJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","A3TmzWOtgmYJ")).
pos(eqo("conf/sigmod/KeoghCMP01","Cy8VDlIamc8J")).
pos(eqo("conf/sigmod/KeoghCMP01","eHY42LnL_lsJ")).
pos(eqo("conf/sigmod/KimCK01","EYI-OULRIz8J")).
pos(eqo("conf/sigmod/Kulkarni94","eN_4FTimCKYJ")).
pos(eqo("conf/sigmod/LabrinidisR00","DKUouEkK_b4J")).
pos(eqo("conf/sigmod/LeeKOTM00","C8RLbWKCgicJ")).
pos(eqo("conf/sigmod/LehnerSPC00","HQRcmyswIHcJ")).
pos(eqo("conf/sigmod/LehnerSPC00","UFKz6Q0wVi4J")).
pos(eqo("conf/sigmod/LitwinS00","37yVRfSpM6MJ")).
pos(eqo("conf/sigmod/LitwinS00","HI2KgQdo39gJ")).
pos(eqo("conf/sigmod/LitwinS00","fx0s58TJ75EJ")).
pos(eqo("conf/sigmod/LiuHBPT99","BIox2W-EPfEJ")).
pos(eqo("conf/sigmod/LiuHBPT99","PKQ1dCQIwi0J")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","ezlAkB7ijDUJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","9Ho84Ho6xuIJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","UqI8eTF3k7sJ")).
pos(eqo("conf/sigmod/MaddenH02","NXakCefUcdUJ")).
pos(eqo("conf/sigmod/MankuRL99","X94gDE70Zn0J")).
pos(eqo("conf/sigmod/MankuRL99","wtJx5zluxC8J")).
pos(eqo("conf/sigmod/MassariPSC95","O2FrN68p5PUJ")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/Meseck01","hWiIngXs5I0J")).
pos(eqo("conf/sigmod/Miller98","0B1XRTZ8cHkJ")).
pos(eqo("conf/sigmod/Miller98","_ExuZq1BkEkJ")).
pos(eqo("conf/sigmod/MinPC03","JjrRZt4ONqMJ")).
pos(eqo("conf/sigmod/MumickQM97","8m_6OmUvYJwJ")).
pos(eqo("conf/sigmod/MumickQM97","c_n0wQe1FhAJ")).
pos(eqo("conf/sigmod/ONeilQ97","5iolWs79wEEJ")).
pos(eqo("conf/sigmod/ONeilQ97","FOruO1PeowAJ")).
pos(eqo("conf/sigmod/ONeilQ97","J9bYvZ3eKygJ")).
pos(eqo("conf/sigmod/ONeilQ97","cyNtXv744CQJ")).
pos(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
pos(eqo("conf/sigmod/PatelD96","Goan1fI4O_oJ")).
pos(eqo("conf/sigmod/PatelD96","SW5bcXhie_4J")).
pos(eqo("conf/sigmod/PatelD96","Y9z2OdhzSGQJ")).
pos(eqo("conf/sigmod/PatelD96","nmTGteLy8NAJ")).
pos(eqo("conf/sigmod/Perna95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D223872%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ProcopiucJAM02","k7RinzPIdhYJ")).
pos(eqo("conf/sigmod/QunLO03","eBXNcn6PwAEJ")).
pos(eqo("conf/sigmod/RajagopalanML98","AUR-p53CsK8J")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","PurSnqtdtCgJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","l1tbsG6UXaMJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","yfTTlN56sCUJ")).
pos(eqo("conf/sigmod/SagonasSW94","0hHYO7tQJUgJ")).
pos(eqo("conf/sigmod/SagonasSW94","nF5iGEtihWYJ")).
pos(eqo("conf/sigmod/SagonasSW94","xc8KEoeRT9sJ")).
pos(eqo("conf/sigmod/SagonasSW94","zOre6B5JTkoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","LMm4_4_uNNoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","Q1TF7XE9xkAJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wISxjPqlwZoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","zM0o4FoKRXIJ")).
pos(eqo("conf/sigmod/Sarawagi00","-cYYeoF2GwMJ")).
pos(eqo("conf/sigmod/Sarawagi00","H_bdYlpD79oJ")).
pos(eqo("conf/sigmod/ShanmugasundaramNSR99","DZI4GwpYBOcJ")).
pos(eqo("conf/sigmod/ShanmugasundaramNSR99","ODvDsK1VEicJ")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","Z2CAABdqG5UJ")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","ZJRIE5CMDZAJ")).
pos(eqo("conf/sigmod/ShuklaD00","kcrWfQEI9G8J")).
pos(eqo("conf/sigmod/ShuklaD00","yGz8BLxbPPcJ")).
pos(eqo("conf/sigmod/SrikantA96","KwgLlNLlaTcJ")).
pos(eqo("conf/sigmod/SrikantA96","WkXM8o_flrEJ")).
pos(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
pos(eqo("conf/sigmod/StonebrakerH01","opMsehfY-XoJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","kKk4xIJfQ70J")).
pos(eqo("conf/sigmod/TaoP02","fDWfHiQ6BR4J")).
pos(eqo("conf/sigmod/WangSCRZP97","chcojj8yN1sJ")).
pos(eqo("conf/sigmod/WitkowskiBBDFGSS03","ygCe1xRFuKgJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","TDIVG8_n_esJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","iFiv0xEJvIkJ")).
pos(eqo("conf/sigmod/YanMHF01","sz9ESx0D0IcJ")).
pos(eqo("conf/sigmod/YangM97","TUQ51ASLNI0J")).
pos(eqo("conf/sigmod/YangM97","d2tXju_pTkYJ")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","GfRmtB2qhgYJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VAX1F7QPNfsJ")).
pos(eqo("conf/sigmod/ZhangDWEMPMDR03","1hkVjoUg8hUJ")).
pos(eqo("conf/sigmod/ZhangDWEMPMDR03","gWslyEjd3BYJ")).
pos(eqo("conf/sigmod/ZhangZPTL03","S3lELcdpzTkJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","6AK0GF7jAtsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","Wg8o4cj8Cq4J")).
pos(eqo("conf/sigmod/ZhaoDNS98","miytzHylgMAJ")).
pos(eqo("conf/sigmod/ZhuSZ03","7VSlB0yIt3YJ")).
pos(eqo("conf/sigmod/ZuzartePMCLW03","url:http://portal.acm.org/citation.cfm%3Fid%3D872757.872840")).
pos(eqo("conf/vldb/AggarwalHWY03","ZFtAmPKKRBQJ")).
pos(eqo("conf/vldb/AgrawalS94","1lpNNpHnY_kJ")).
pos(eqo("conf/vldb/AgrawalS94","3MzTom30SiMJ")).
pos(eqo("conf/vldb/AgrawalS94","E7cKUUkwc1kJ")).
pos(eqo("conf/vldb/AgrawalS94","HfEQzVOD9tsJ")).
pos(eqo("conf/vldb/AgrawalS94","QlSaVou-Zt4J")).
pos(eqo("conf/vldb/AgrawalS94","RiQ-W5K0n6YJ")).
pos(eqo("conf/vldb/AgrawalS94","VwFLRQytbu4J")).
pos(eqo("conf/vldb/AgrawalS94","bKp266-v6gUJ")).
pos(eqo("conf/vldb/AgrawalS94","e5SJ3zgdwgEJ")).
pos(eqo("conf/vldb/AgrawalS94","ujWZNcj2qkgJ")).
pos(eqo("conf/vldb/AksoyZF01","z6Z1hQYHTAMJ")).
pos(eqo("conf/vldb/AmbiteKKMST01","F4DtzxvVZnoJ")).
pos(eqo("conf/vldb/AnSVKIG01","HosSI1GtRY8J")).
pos(eqo("conf/vldb/AnSVKIG01","kBzZ1GUoa1AJ")).
pos(eqo("conf/vldb/AndreiV01","Ms4IJoI6-34J")).
pos(eqo("conf/vldb/AshwinRSSS97","5VcKjo7jBOMJ")).
pos(eqo("conf/vldb/AshwinRSSS97","JB684f38DiwJ")).
pos(eqo("conf/vldb/BamfordBKM98","rfuptELfgLkJ")).
pos(eqo("conf/vldb/BaralisW94","nqaF5CzBelgJ")).
pos(eqo("conf/vldb/BaralisW94","q-td2YANr18J")).
pos(eqo("conf/vldb/BarjaPFWD94","qhl9_KGvjcUJ")).
pos(eqo("conf/vldb/BarjaPFWD94","yXC9t87hjwsJ")).
pos(eqo("conf/vldb/BaumannDFRW99","OV-zNC5uzHUJ")).
pos(eqo("conf/vldb/BaumannDFRW99","lmKF8hAYUkMJ")).
pos(eqo("conf/vldb/BenediktCFRZZ02","7xe6Gp9fIEEJ")).
pos(eqo("conf/vldb/BerchtoldKK96","DDX7y0WvbRMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WnYVibh8fxUJ")).
pos(eqo("conf/vldb/BerchtoldKK96","kCH4ZzrozMkJ")).
pos(eqo("conf/vldb/BerchtoldKK96","oKxmbGqneFwJ")).
pos(eqo("conf/vldb/BerckenS01","A46cpXEm-8AJ")).
pos(eqo("conf/vldb/BergerBSW03","Wjg_SYCySOsJ")).
pos(eqo("conf/vldb/BernsteinD94","rNNtyNCgHLoJ")).
pos(eqo("conf/vldb/BettiniJWW02","ghIMekzCkMQJ")).
pos(eqo("conf/vldb/BettiniJWW02","tFuA828CptUJ")).
pos(eqo("conf/vldb/BonczMK99","6GAoBRINv7kJ")).
pos(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
pos(eqo("conf/vldb/BonczMK99","xWYu2JWiF_kJ")).
pos(eqo("conf/vldb/BonczRK98","ts5vu2eNQgYJ")).
pos(eqo("conf/vldb/BraumandlCK98","rH5VOr1x-a8J")).
pos(eqo("conf/vldb/BridgeJKLLM97","8SYZpKAeTwQJ")).
pos(eqo("conf/vldb/BrinkhoffK94","egvBPvtoaMMJ")).
pos(eqo("conf/vldb/CareyKRLABFLOPQRSSUVWY01","_pAcjtd1nbEJ")).
pos(eqo("conf/vldb/CasatiS00","yGYyg3tCPEcJ")).
pos(eqo("conf/vldb/CeriCW00","HbrsuuNPd1QJ")).
pos(eqo("conf/vldb/CeriCW00","LlZwS4UrRtkJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","PAfIruwVVakJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChakrabartiM00","7P1LlDStRGYJ")).
pos(eqo("conf/vldb/ChakrabartiM00","tRBRXzjtm14J")).
pos(eqo("conf/vldb/ChandrasekaranF02","Yu4Tvuy_WiAJ")).
pos(eqo("conf/vldb/ChandrasekaranF02","b408sdGcY3UJ")).
pos(eqo("conf/vldb/ChaudhuriS01","-jtu5QeiAKQJ")).
pos(eqo("conf/vldb/ChaudhuriS96","hk2lzbke6hQJ")).
pos(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
pos(eqo("conf/vldb/ChienVZTZ02","7gDXEIuMUIIJ")).
pos(eqo("conf/vldb/ChienVZTZ02","SgUc7R0GR6QJ")).
pos(eqo("conf/vldb/ChienVZTZ02","uUmeAkW_FFUJ")).
pos(eqo("conf/vldb/ChirkovaHS01","NdmocXlpq9QJ")).
pos(eqo("conf/vldb/DarFJST96","57-MJmAVId8J")).
pos(eqo("conf/vldb/DarFJST96","ThLxMqqAxjIJ")).
pos(eqo("conf/vldb/DarFJST96","cM4adSkCTK0J")).
pos(eqo("conf/vldb/DattaRT99","gckQTLQjsj8J")).
pos(eqo("conf/vldb/DeckerK03","es2kSNccUGMJ")).
pos(eqo("conf/vldb/DingGS00","JxQZ0YrY-DAJ")).
pos(eqo("conf/vldb/DiwanRSS96","HjDa9on7LzoJ")).
pos(eqo("conf/vldb/Duranti01","gQW6iYG5Vh0J")).
pos(eqo("conf/vldb/EicklerKK97","PCFJuVxYxtwJ")).
pos(eqo("conf/vldb/EvangelidisLS95","5dnYlEMQTb0J")).
pos(eqo("conf/vldb/EvangelidisLS95","sXa76m0wBGYJ")).
pos(eqo("conf/vldb/FankhauserGLMT98","JnwUAxUMwvQJ")).
pos(eqo("conf/vldb/FlescaFM03","LXjSnbxB7EsJ")).
pos(eqo("conf/vldb/Galindo-LegariaPK94","47fE4F2kahEJ")).
pos(eqo("conf/vldb/GantiLR00","V7byawkFcZMJ")).
pos(eqo("conf/vldb/GantiLR00","Vd-lSpZc0cYJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","X-jmxnecLOEJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","jimNuiynSDIJ")).
pos(eqo("conf/vldb/GardarinST96","OHR5iQWPuyYJ")).
pos(eqo("conf/vldb/GardarinST96","RB2VKRwnXywJ")).
pos(eqo("conf/vldb/GarofalakisG01","rcSfDxBif40J")).
pos(eqo("conf/vldb/GarofalakisG02","S6PWjHRFORYJ")).
pos(eqo("conf/vldb/GarofalakisI97","-cCndG3a8ukJ")).
pos(eqo("conf/vldb/Gentili01","2j1dalv3kCEJ")).
pos(eqo("conf/vldb/GionisIM99","3RR94IxW5CUJ")).
pos(eqo("conf/vldb/GionisIM99","A8rGBQif7MIJ")).
pos(eqo("conf/vldb/GolabO03","-8IwyDJe7fgJ")).
pos(eqo("conf/vldb/GoldmanSVG98","b3H6Yt4f7hAJ")).
pos(eqo("conf/vldb/GoldsteinR00","FncQ86sO2agJ")).
pos(eqo("conf/vldb/GoldsteinR00","zydIJyhwgPEJ")).
pos(eqo("conf/vldb/GraefeBC98","v-kvo2hnsgkJ")).
pos(eqo("conf/vldb/GravanoG97","yWnzay_AV44J")).
pos(eqo("conf/vldb/GrumbachRS00","iQ3Zi3crc9wJ")).
pos(eqo("conf/vldb/GuntzerBK00","EdQ4M7GEnzoJ")).
pos(eqo("conf/vldb/HammelP02","SU2XS1MVb40J")).
pos(eqo("conf/vldb/HelalL00","LPapCvY4RFkJ")).
pos(eqo("conf/vldb/HelmerM97","xsh0C_nCllsJ")).
pos(eqo("conf/vldb/Ioannidis03","jELnwotIy9kJ")).
pos(eqo("conf/vldb/IoannidisP99","BlALg9KQCLAJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/vldb/JagadishLRSS94","Yiwh22hbTAcJ")).
pos(eqo("conf/vldb/JagadishLS99","FLHi5haA7AQJ")).
pos(eqo("conf/vldb/JagadishNSSK97","FzUYum7hqhQJ")).
pos(eqo("conf/vldb/JagadishNSSK97","ZG9yClLgWnsJ")).
pos(eqo("conf/vldb/JarkeKL00","6c3XQZ-_HDUJ")).
pos(eqo("conf/vldb/JarkeKL00","hRr_IBVG0-YJ")).
pos(eqo("conf/vldb/JiangSLB00","eZwzDZ7QhzoJ")).
pos(eqo("conf/vldb/JoshiBLL98","RufEbUPZNbYJ")).
pos(eqo("conf/vldb/KalusD95","r1xwwqWr2K0J")).
pos(eqo("conf/vldb/KiesslingK02","3VHepuiTGHUJ")).
pos(eqo("conf/vldb/KnorrN98","oCPpSbHhL3IJ")).
pos(eqo("conf/vldb/KnorrN98","r8uYvAGT6swJ")).
pos(eqo("conf/vldb/KnorrN98","yFmekFZgZmwJ")).
pos(eqo("conf/vldb/KonopnickiS95","VbPeo_JSln8J")).
pos(eqo("conf/vldb/KonopnickiS95","cA1Zsnlz-tIJ")).
pos(eqo("conf/vldb/LabrinidisR03","0GMNedjfVV0J")).
pos(eqo("conf/vldb/LeeL99","szHsyFiOuwAJ")).
pos(eqo("conf/vldb/LernerS03","GsTq8-R1uaMJ")).
pos(eqo("conf/vldb/Lesk94","nL5wl20jB-kJ")).
pos(eqo("conf/vldb/LevyRO96","biHvq8aD3_QJ")).
pos(eqo("conf/vldb/LiM01","9vDm1Q41J8oJ")).
pos(eqo("conf/vldb/LiM01","yXnK2wPwLzkJ")).
pos(eqo("conf/vldb/LinLYZ03","9rbctPoEdNUJ")).
pos(eqo("conf/vldb/LingLL00","yKnPPSNrDb0J")).
pos(eqo("conf/vldb/LuSL95","h24eSPFv8MoJ")).
pos(eqo("conf/vldb/MadhavanH03","ujCYoqKS6BcJ")).
pos(eqo("conf/vldb/Madnick95","UHLfs0GGqAAJ")).
pos(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
pos(eqo("conf/vldb/ManegoldBK00","JgdpgBpMDr4J")).
pos(eqo("conf/vldb/ManegoldBK00","sZmrat79cF0J")).
pos(eqo("conf/vldb/MartinC94","Ur6-XAMj3tIJ")).
pos(eqo("conf/vldb/MatthesS94","KRLEL-N4Ce8J")).
pos(eqo("conf/vldb/MeoPC96","Opm5VlTzQTAJ")).
pos(eqo("conf/vldb/MeoPC96","SNIbAV2EN0MJ")).
pos(eqo("conf/vldb/Moerkotte98","WIbtPXHpeHoJ")).
pos(eqo("conf/vldb/Mohan02a","ulDehVmIgfAJ")).
pos(eqo("conf/vldb/Mohan99","4N472VSotmMJ")).
pos(eqo("conf/vldb/NathDKGKS03","pF6EW_yKYyYJ")).
pos(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
pos(eqo("conf/vldb/NatsevCSLV01","lD7OgF3Xw6wJ")).
pos(eqo("conf/vldb/NishioSTTL01","S30IXg4ClFIJ")).
pos(eqo("conf/vldb/Objectivity98","o3fkxpcCBskJ")).
pos(eqo("conf/vldb/OlstonW00","QcUC-6OtvLMJ")).
pos(eqo("conf/vldb/OlstonW00","fzIAU5XQeo4J")).
pos(eqo("conf/vldb/OlstonW00","rrOV-TanTuYJ")).
pos(eqo("conf/vldb/OoiYTJ01","RFEE_MNM8IUJ")).
pos(eqo("conf/vldb/OzdenBRS94","ARyxUwGOA10J")).
pos(eqo("conf/vldb/PacittMS99","jJyGKE2N34gJ")).
pos(eqo("conf/vldb/Padmanabhan96","1IjlMvLBFC0J")).
pos(eqo("conf/vldb/PatonG01","mHCrMuxQnBsJ")).
pos(eqo("conf/vldb/PedersenJD00","bSRLP5_ErFMJ")).
pos(eqo("conf/vldb/PottingerL00","eXceb1SMqE4J")).
pos(eqo("conf/vldb/PottingerL00","mpnnRdFUUJQJ")).
pos(eqo("conf/vldb/RahmM95","m9m0YpwaO4YJ")).
pos(eqo("conf/vldb/RamamrithamABEGP00","jYGXFESkS-YJ")).
pos(eqo("conf/vldb/RamamurthyDS02","DAlyofX710AJ")).
pos(eqo("conf/vldb/RamamurthyDS02","vGFdY2gG8YsJ")).
pos(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
pos(eqo("conf/vldb/RamanRH99","QLJhG6Rz2T0J")).
pos(eqo("conf/vldb/SarawagiS96","GzBmx-QUxFYJ")).
pos(eqo("conf/vldb/SeidlK97","5Ine3RRoUCcJ")).
pos(eqo("conf/vldb/SeidlK97","HAG0kCjBu4EJ")).
pos(eqo("conf/vldb/SenkulKT02","g7HDbO4GCN4J")).
pos(eqo("conf/vldb/SeshadriLR97","ggV87TiwH04J")).
pos(eqo("conf/vldb/SevcikK96","GiHrMj3vbSAJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GIlUG9H3gUUJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","NADaoJJSRfQJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","wd9dp08MveIJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/SilversteinBMU98","bCj7bOIqDc0J")).
pos(eqo("conf/vldb/SistlaYH94","FT4Sfn-Z7GUJ")).
pos(eqo("conf/vldb/SistlaYH94","bDH4OmzDSLEJ")).
pos(eqo("conf/vldb/SizovGT03","UbQPXbPLMCAJ")).
pos(eqo("conf/vldb/SkubiszewskiV97","MJAw_2C6ErAJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","01ZVDudF4WAJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","8o0d8xLuwgUJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","WvvY_Ao19mAJ")).
pos(eqo("conf/vldb/StanoiRAA01","SBpUQ0L7KUgJ")).
pos(eqo("conf/vldb/StillgerLMK01","OYAPM1C1DW8J")).
pos(eqo("conf/vldb/StillgerLMK01","k8EsgEuKhQ0J")).
pos(eqo("conf/vldb/SubietaKL95","gEFY87Ma0XUJ")).
pos(eqo("conf/vldb/TaoP02","7ZyV9ivZySQJ")).
pos(eqo("conf/vldb/TianD03","l7glyH7ltuQJ")).
pos(eqo("conf/vldb/Toivonen96","fiDTOBR8njMJ")).
pos(eqo("conf/vldb/Toivonen96","yd2dxAbjvTAJ")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/VassalosP97","5DKaP73v7FQJ")).
pos(eqo("conf/vldb/VassalosP97","_Va8sQkrP2kJ")).
pos(eqo("conf/vldb/VassalosP97","jmYHA7e95XAJ")).
pos(eqo("conf/vldb/VeltriCV01","itG_XrygxXIJ")).
pos(eqo("conf/vldb/WangC03","yjZolbzEP6wJ")).
pos(eqo("conf/vldb/WeberSB98","K4rzmIbgF_sJ")).
pos(eqo("conf/vldb/WeberSB98","TkaEMuHGE9cJ")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/YanL95","VwsS71_KQX8J")).
pos(eqo("conf/vldb/YanL95","uy8MOTvPkOsJ")).
pos(eqo("conf/vldb/YangKL97","qN1APPIGZMMJ")).
pos(eqo("conf/vldb/YiF00","1XJk5BWEVe8J")).
pos(eqo("conf/vldb/YiF00","J8maiu6CF0EJ")).
pos(eqo("conf/vldb/YiF00","jlAeV2gH64QJ")).
pos(eqo("conf/vldb/ZhouR03","MvbChqWgFawJ")).
pos(eqo("journals/sigmod/ACT-NET96","AWM-7zzaO7wJ")).
pos(eqo("journals/sigmod/ACT-NET96","RzsJoG-0KaIJ")).
pos(eqo("journals/sigmod/Aberer02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AdelbergKG96","6gc5TN-yce8J")).
pos(eqo("journals/sigmod/AdelbergKG96","GfiQygac5twJ")).
pos(eqo("journals/sigmod/AilamakiFFSV03","rMV2yNFwvggJ")).
pos(eqo("journals/sigmod/ArpinarD00","YQQMvRraFBwJ")).
pos(eqo("journals/sigmod/BarbaraBFLS94","sF4xdH31mDAJ")).
pos(eqo("journals/sigmod/BernsteinHP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369289%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BertinoEH03","4m-WmWU5iGYJ")).
pos(eqo("journals/sigmod/BuchnerM98","SZwq84m3bGYJ")).
pos(eqo("journals/sigmod/BuchnerM98","dkWnTbi9xnEJ")).
pos(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
pos(eqo("journals/sigmod/Bussche00","abRCzV130REJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","Axu6UlX-pPYJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","MH0RCZvsQ1cJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","OhiGJ7Gy3KgJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","url:http://portal.acm.org/citation.cfm%3Fid%3D507338.507367%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CaplinskasEV02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507367%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Cardelli01","UYAoi4DYOXUJ")).
pos(eqo("journals/sigmod/CasatiDS00","pJsnj7fi9LIJ")).
pos(eqo("journals/sigmod/CatarciC96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245888%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CeriFP99","zCbDZVfxWhAJ")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D641006")).
pos(eqo("journals/sigmod/CiliaB02","Y1HVgTopekIJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","3aPleydkcIoJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","cjvOCqu3cJgJ")).
pos(eqo("journals/sigmod/DrewHKKLLLSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219769%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Eisenberg96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245907%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/EnglertGH95","JRXuKm3E_foJ")).
pos(eqo("journals/sigmod/Fong97","rgJU30QjbhkJ")).
pos(eqo("journals/sigmod/FowlerPNB99","2cbB8em2uAIJ")).
pos(eqo("journals/sigmod/FowlerPNB99","OewAZ4AUDOQJ")).
pos(eqo("journals/sigmod/GamacheS95","vqgfvx71hgQJ")).
pos(eqo("journals/sigmod/GatziuJSV99","HtqrJuo7GSsJ")).
pos(eqo("journals/sigmod/GolabO03","jGb8C7wu8aYJ")).
pos(eqo("journals/sigmod/GolabO03","lC5GjK5OpD0J")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","url:http://portal.acm.org/citation.cfm%3Fid%3D333607.333616%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HansonN99","O5m6UXQ_Xv4J")).
pos(eqo("journals/sigmod/HansonN99","vM_HYDYFeJ0J")).
pos(eqo("journals/sigmod/HuangKL02","g4mWc14U8m4J")).
pos(eqo("journals/sigmod/JainH94","iQMUP3fkvo4J")).
pos(eqo("journals/sigmod/JainH94","sj_7DWnVQ5gJ")).
pos(eqo("journals/sigmod/JukicNV03","eR43Urfx-hcJ")).
pos(eqo("journals/sigmod/KambhampatiK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/Konig-RiesL97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D262771%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KramerNKRLKLZ97","1sBvG9OXpMAJ")).
pos(eqo("journals/sigmod/Kumar03","VuNnpxJwvQkJ")).
pos(eqo("journals/sigmod/LightstoneLZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601873%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Loeffen94","gb-yIDOxaEkJ")).
pos(eqo("journals/sigmod/Loeffen94","jFNkGh68g6EJ")).
pos(eqo("journals/sigmod/Lomet98","xLM0YVcccUgJ")).
pos(eqo("journals/sigmod/Lomet98","ytRfS_upf-0J")).
pos(eqo("journals/sigmod/LometBCLN98","eCi5eTVzsoQJ")).
pos(eqo("journals/sigmod/LudascherMM01","16yr6uv8Rn8J")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Mani03","FgLCpqaf8C8J")).
pos(eqo("journals/sigmod/NadoH97","yN9f4dSKC9QJ")).
pos(eqo("journals/sigmod/NgH95","qolJkVC2MoYJ")).
pos(eqo("journals/sigmod/NobleS95","egn46hGLw7gJ")).
pos(eqo("journals/sigmod/NobleS95","rRvcD6HKhasJ")).
pos(eqo("journals/sigmod/OrlandicLS02","eLf0eStn5G4J")).
pos(eqo("journals/sigmod/OukselS99","YeVWiZOxB9IJ")).
pos(eqo("journals/sigmod/PapianiWDN99","EHBFbc1r9oIJ")).
pos(eqo("journals/sigmod/PapianiWDN99","aU7XlTpoxRgJ")).
pos(eqo("journals/sigmod/PoessF00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369291%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RosenthalSMBTL95","-_FyboGgZkkJ")).
pos(eqo("journals/sigmod/Seshadri98","N9NdxNRvMMkJ")).
pos(eqo("journals/sigmod/Seshadri98","XijyPb231fAJ")).
pos(eqo("journals/sigmod/SmithO99","-iis302p2MkJ")).
pos(eqo("journals/sigmod/Snodgrass94","SYVDufoTe_IJ")).
pos(eqo("journals/sigmod/Snodgrass98a","CGvD6Du5kaoJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","psdMY-oUz4cJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","vUONDuuNNCQJ")).
pos(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
pos(eqo("journals/sigmod/SycaraKWL99","YgouJdrCoZQJ")).
pos(eqo("journals/sigmod/TanK03","-JwOe0wd0HkJ")).
pos(eqo("journals/sigmod/TanK03","qIzj09N-Qr8J")).
pos(eqo("journals/sigmod/TanakaV01","sQu8znidi50J")).
pos(eqo("journals/sigmod/TheodoridisN00","NegSmYlF-awJ")).
pos(eqo("journals/sigmod/TsotrasK96","9HEdn3A13BQJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/Vassilakis00","e0j-56kaeR4J")).
pos(eqo("journals/sigmod/WestmannKHM00","BmJKyK7NlOoJ")).
pos(eqo("journals/sigmod/Widom94","lAbG3uFZvVUJ")).
pos(eqo("journals/sigmod/WinslettCDHZZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/WuY00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D362096%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/YanG95","tMXkkRDxvkQJ")).
pos(eqo("journals/tods/AikenHW95","XLld3hq3vt0J")).
pos(eqo("journals/tods/Alagic99","Gq6D6zMEPxoJ")).
pos(eqo("journals/tods/CliffordC94","9txS2mlA2DMJ")).
pos(eqo("journals/tods/CliffordDIJS97","1XXrXRdYiFQJ")).
pos(eqo("journals/tods/CliffordDIJS97","q9_l2Bqj5y4J")).
pos(eqo("journals/tods/CliffordDIJS97","rGfhB3UE5mYJ")).
pos(eqo("journals/tods/CliffordDIJS97","sflWMxkOH2cJ")).
pos(eqo("journals/tods/FormicaGM98","PtcmzsfKYrsJ")).
pos(eqo("journals/tods/FranklinCL97","-iaSLKFHwUkJ")).
pos(eqo("journals/tods/FranklinCL97","vqboZ3T4n4AJ")).
pos(eqo("journals/tods/GravanoGT99","NCv4Y_aV23EJ")).
pos(eqo("journals/tods/IoannidisR95","TJDMWbCXMtgJ")).
pos(eqo("journals/tods/KarpSP03","mAQIVsd2VOMJ")).
pos(eqo("journals/tods/KonopnickiS98","BKUtItHoTX8J")).
pos(eqo("journals/tods/KossmannS00","PnGVbzQCWY0J")).
pos(eqo("journals/tods/LiuM96","xeceK06Z5DIJ")).
pos(eqo("journals/tods/PolyzoisG94","LoL0Yu6h4VAJ")).
pos(eqo("journals/tods/PolyzoisG94","p7x1zGD_bkEJ")).
pos(eqo("journals/tods/ScioreSR94","RJt8UiSzDTkJ")).
pos(eqo("journals/tods/ScioreSR94","fW9j2V5gnUMJ")).
pos(eqo("journals/tods/ShashaLSV95","0aVKzjogLlAJ")).
pos(eqo("journals/tods/SistlaWYS98","3mLKQfhVh3cJ")).
pos(eqo("journals/tods/SistlaWYS98","4owPoyytTP4J")).
pos(eqo("journals/tods/SrivastavaSRN95","zm3D83ZiU4UJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","Cmq7lkkXNt4J")).
pos(eqo("journals/vldb/Barbara-MillaG94","Hc9uWxJu840J")).
pos(eqo("journals/vldb/Barbara-MillaG94","IvPHHa01uUkJ")).
pos(eqo("journals/vldb/BernsteinPS00","08d5th2jiqcJ")).
pos(eqo("journals/vldb/CatarciSC97","IIykL2NeD3UJ")).
pos(eqo("journals/vldb/ChandrasekaranF03","b9r9U3OwrkcJ")).
pos(eqo("journals/vldb/ChuIT94","IDo3ZQocZE4J")).
pos(eqo("journals/vldb/DanYC95","SsOLRJZrmtYJ")).
pos(eqo("journals/vldb/DiazJ97","RKAY1aZAeCoJ")).
pos(eqo("journals/vldb/EvangelidisS97","5dnYlEMQTb0J")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/GutingS95","CBHicx5w3ocJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/GutingS95","dm3xutmyi_0J")).
pos(eqo("journals/vldb/GutingS95","x02_XqK_fGMJ")).
pos(eqo("journals/vldb/HjaltasonS02","FH41DtWf_jAJ")).
pos(eqo("journals/vldb/HuntAI02","LiYp5oaDwbMJ")).
pos(eqo("journals/vldb/KraissW98","K0aOFYBWg3AJ")).
pos(eqo("journals/vldb/KraissW98","LMz7v87sxxYJ")).
pos(eqo("journals/vldb/Li03","HlXyqUIDobMJ")).
pos(eqo("journals/vldb/LiangOY00","ikw-En98LywJ")).
pos(eqo("journals/vldb/MecellaP01","_JwGwZUTAOEJ")).
pos(eqo("journals/vldb/MedjahedBBNE03","e2tY_GZIEv8J")).
pos(eqo("journals/vldb/PottingerH01","eXceb1SMqE4J")).
pos(eqo("journals/vldb/PottingerH01","mpnnRdFUUJQJ")).
pos(eqo("journals/vldb/PoulovassilisS96","B87s9MFTeZ8J")).
pos(eqo("journals/vldb/RamakrishnanSSS94","K9jUyjxRaCwJ")).
pos(eqo("journals/vldb/RamakrishnanSSS94","lH_n19yVmWgJ")).
pos(eqo("journals/vldb/RamamohanaraoH94","UiWvxN_y9SAJ")).
pos(eqo("journals/vldb/RamamurthyDS03","DAlyofX710AJ")).
pos(eqo("journals/vldb/RamamurthyDS03","vGFdY2gG8YsJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","HKM-zP0LT_UJ")).
pos(eqo("journals/vldb/SivasankaranSTPR96","url:http://ieeexplore.ieee.org/iel2/997/7843/00331718.pdf%3Farnumber%3D331718")).
pos(eqo("journals/vldb/SwamiS95","S6TmnZKgmxwJ")).
pos(eqo("journals/vldb/VaghaniRKSSLH94","B3E3_clrrrYJ")).
