neg(eqo("conf/sigmod/AbadiC02","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
neg(eqo("conf/sigmod/AbiteboulBCMM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D122052%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/AbiteboulBCMM03","vIwsSOGQOWAJ")).
neg(eqo("conf/sigmod/AbiteboulCM95","kc-IArRsvr0J")).
neg(eqo("conf/sigmod/AbiteboulCM95","zRzwh7_az94J")).
neg(eqo("conf/sigmod/AboulnagaC99","SG9kpHg_arUJ")).
neg(eqo("conf/sigmod/AcharyaPR99","99N4rXNdaqMJ")).
neg(eqo("conf/sigmod/AcharyaPR99","gKOsM57uFB4J")).
neg(eqo("conf/sigmod/Adelberg98","5wG_onaKnxwJ")).
neg(eqo("conf/sigmod/AdelbergGK95","NhNwtkE4jFEJ")).
neg(eqo("conf/sigmod/AdelbergGW97","zZo47Z-jVX4J")).
neg(eqo("conf/sigmod/Agarwal96","Q2y53UR0g6oJ")).
neg(eqo("conf/sigmod/Aggarwal02","f9MPbT0jUGsJ")).
neg(eqo("conf/sigmod/AggarwalY01","E0JFsdONHAYJ")).
neg(eqo("conf/sigmod/AgrawalCD02","rY8YFTWbvmEJ")).
neg(eqo("conf/sigmod/AmbiteABKMMMPT98","0sQVbohb7DcJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","LNUnAUo0_LcJ")).
neg(eqo("conf/sigmod/Bampahl95","e6llu4bIOxUJ")).
neg(eqo("conf/sigmod/BargaL99","Bf9f-weRWHMJ")).
neg(eqo("conf/sigmod/BerchtoldK97","irJbh9rrinoJ")).
neg(eqo("conf/sigmod/Bierman03","9dgFU6XaLrwJ")).
neg(eqo("conf/sigmod/Blakeley96","1fs-qN_SdH4J")).
neg(eqo("conf/sigmod/BohmA96","978pJCGhaGoJ")).
neg(eqo("conf/sigmod/BohmA96","s5rCMcRRRgAJ")).
neg(eqo("conf/sigmod/BohmBKK01","C4XcBh6anhAJ")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","KLwua49G8a0J")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","url:http://www.springerlink.com/index/MX55711106028504.pdf")).
neg(eqo("conf/sigmod/BorkarDS01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083797%26type%3Dpdf")).
neg(eqo("conf/sigmod/BozkayaO97","9QOCoTIXz9kJ")).
neg(eqo("conf/sigmod/BrinMS97","-tbXaORoThUJ")).
neg(eqo("conf/sigmod/BrinkhoffKSS94","7zBV3cTwybwJ")).
neg(eqo("conf/sigmod/BrinkhoffKSS94","FN5Faq5Glz0J")).
neg(eqo("conf/sigmod/BrinkhoffKSS94","yp82ArYEGxIJ")).
neg(eqo("conf/sigmod/BuchmannDZH95","7nl1Xaccf-0J")).
neg(eqo("conf/sigmod/BuchmannDZH95","lasxhCBiPGYJ")).
neg(eqo("conf/sigmod/BunemanDHS96","R128Of6zyGgJ")).
neg(eqo("conf/sigmod/BunemanKTT02","cKIQyzazkYEJ")).
neg(eqo("conf/sigmod/CallanCD99","igM_dVQLhtEJ")).
neg(eqo("conf/sigmod/Carey00","wr5pRI-iGqsJ")).
neg(eqo("conf/sigmod/ChanI98","VC7Jbwgn_O0J")).
neg(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","Chp-3UwMgTQJ")).
neg(eqo("conf/sigmod/Chaudhuri97","CWZ-rse9wAgJ")).
neg(eqo("conf/sigmod/Chaudhuri97","FfVQuWBFKZgJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","DsN8bgfQbM8J")).
neg(eqo("conf/sigmod/ChaudhuriG96","aDDbEmg7oYYJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","0rViZf2YXmAJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","OFGtGwUHhUQJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","hk2lzbke6hQJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","QkyXMep2bWsJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","RcMMgtO63REJ")).
neg(eqo("conf/sigmod/ChenJDTW00","fg5EE6R7xYwJ")).
neg(eqo("conf/sigmod/ChenR94","H7Pi4AQU00YJ")).
neg(eqo("conf/sigmod/CherniackZ96","ZsHfcZJwFQQJ")).
neg(eqo("conf/sigmod/CherniackZ98","gyfFLO3-bm8J")).
neg(eqo("conf/sigmod/CluetDSS98","LMz7v87sxxYJ")).
neg(eqo("conf/sigmod/CluetDSS98","oc6h69g4CAIJ")).
neg(eqo("conf/sigmod/Cohen98","SpFdUtWwvkQJ")).
neg(eqo("conf/sigmod/CohenM03","p8o5Aqoof7gJ")).
neg(eqo("conf/sigmod/ConsensM94","ZQG-8D6v7BoJ")).
neg(eqo("conf/sigmod/DavisonG95","tPG--ikWjGcJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03a","FirBsg8jxtkJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03a","G3dX_RTA26MJ")).
neg(eqo("conf/sigmod/DeutschFS99","QxtGOVsCF78J")).
neg(eqo("conf/sigmod/DoRD99","F2wVTEYkBWAJ")).
neg(eqo("conf/sigmod/DogacAEOADAOS94","OE8gpNwz8MkJ")).
neg(eqo("conf/sigmod/Dyreson03","XhtF-nL-a6wJ")).
neg(eqo("conf/sigmod/Dyreson03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/EmbleyJN99","CmdB816FL7MJ")).
neg(eqo("conf/sigmod/EmbleyJN99","Cyo90MIIXGYJ")).
neg(eqo("conf/sigmod/Epstein95","ESge0RjQQ40J")).
neg(eqo("conf/sigmod/Epstein95","url:http://portal.acm.org/citation.cfm%3Fid%3D277951")).
neg(eqo("conf/sigmod/FaloutsosSTT00","43K14Y5xa0YJ")).
neg(eqo("conf/sigmod/FegarasM95","cp82jd8YZAMJ")).
neg(eqo("conf/sigmod/FlorescuGKR02","z1YR8jZV7YkJ")).
neg(eqo("conf/sigmod/Galhardas00","296Uruyb5XcJ")).
neg(eqo("conf/sigmod/GangulyGMS96","Ah9B3bWU0jEJ")).
neg(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
neg(eqo("conf/sigmod/GarofalakisRRS99","DHnbaUmZMXsJ")).
neg(eqo("conf/sigmod/GatziuGD95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GebhardtJJ97","9mbr0dyW1NgJ")).
neg(eqo("conf/sigmod/GehrkeGRL99","jIzNNM6_h1UJ")).
neg(eqo("conf/sigmod/GehrkeGRL99","s3neqsFCVrAJ")).
neg(eqo("conf/sigmod/GodfreyGXZ01","xMRpOr8JfeUJ")).
neg(eqo("conf/sigmod/GoldmanW00","yjsXspk2XrgJ")).
neg(eqo("conf/sigmod/GoldsteinL01","KAf2DUUVabIJ")).
neg(eqo("conf/sigmod/GotoK03","yyvDh_KtEMoJ")).
neg(eqo("conf/sigmod/Gray95","Lj8CI8ALd9UJ")).
neg(eqo("conf/sigmod/GrayHOS96","iKmQWoUYl-0J")).
neg(eqo("conf/sigmod/Greer99","ztpceRBO43EJ")).
neg(eqo("conf/sigmod/GriffinH97","wrJrhWa5NXIJ")).
neg(eqo("conf/sigmod/GunopulosKTD00","jq5SbLenh4cJ")).
neg(eqo("conf/sigmod/HacigumusILM02","9vL7MRA7Up4J")).
neg(eqo("conf/sigmod/Han96","mxuqSQ4rAeEJ")).
neg(eqo("conf/sigmod/HanFHCC94","EWdjCIv1enwJ")).
neg(eqo("conf/sigmod/HanPY00","rLJSEgt6UbMJ")).
neg(eqo("conf/sigmod/HellersteinA00","-GYSZmXrx-UJ")).
neg(eqo("conf/sigmod/HellersteinA00","TsShfxPwF6YJ")).
neg(eqo("conf/sigmod/Hidber99","Rn-E82gM1RQJ")).
neg(eqo("conf/sigmod/Hidber99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
neg(eqo("conf/sigmod/HullZ96","rI-T6ppfITQJ")).
neg(eqo("conf/sigmod/IlyasRLGL03","AQOcKd6cVZsJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","yQv94p3tE1IJ")).
neg(eqo("conf/sigmod/IoannidisL94","a1JaxG-HKuwJ")).
neg(eqo("conf/sigmod/JagadishJOT01","7sAbsVtfJj8J")).
neg(eqo("conf/sigmod/JagadishLS99","XppwYYxOpksJ")).
neg(eqo("conf/sigmod/Jamil99","LmhHeeXKRAQJ")).
neg(eqo("conf/sigmod/JohnsonD03","5OYgUpRggiMJ")).
neg(eqo("conf/sigmod/JohnsonD03","Gy1Gf_x9YRYJ")).
neg(eqo("conf/sigmod/JohnsonD03","rbluxTXqUQwJ")).
neg(eqo("conf/sigmod/KabraD98","k4UNrsGeUuAJ")).
neg(eqo("conf/sigmod/KangN03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381897%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Keim96","vkUvhZOw-1YJ")).
neg(eqo("conf/sigmod/KemperMPS94","Lm25su-wny0J")).
neg(eqo("conf/sigmod/KemperMPS94","mr8XDkQ7adAJ")).
neg(eqo("conf/sigmod/Kennamer98","RQ9qLR4St8sJ")).
neg(eqo("conf/sigmod/KiesslingHFE01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107500%26type%3Dpdf")).
neg(eqo("conf/sigmod/Kim94","JHuJHooGoNUJ")).
neg(eqo("conf/sigmod/KornJF97","Q7mRCvhFsfEJ")).
neg(eqo("conf/sigmod/KornM00","p_-NN4HnbQ4J")).
neg(eqo("conf/sigmod/KotidisR98","c2UQ3AM5_f8J")).
neg(eqo("conf/sigmod/KotidisR99","RusJdYPDgQ4J")).
neg(eqo("conf/sigmod/KoudasS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083777%26type%3Dpdf")).
neg(eqo("conf/sigmod/KrollW94","2hHw3xrXq40J")).
neg(eqo("conf/sigmod/KuhnTS94","JnV4W3TKPxMJ")).
neg(eqo("conf/sigmod/LabrinidisR00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988603%26type%3Dpdf")).
neg(eqo("conf/sigmod/LahiriJJC98","gt83e4uB09wJ")).
neg(eqo("conf/sigmod/LarsonG98","6gWMPteHvosJ")).
neg(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
neg(eqo("conf/sigmod/Lassettre98","eH69_dCm18wJ")).
neg(eqo("conf/sigmod/LiBCS00","4abl38Q9iH4J")).
neg(eqo("conf/sigmod/LiS98","zMK02pxd4OEJ")).
neg(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
neg(eqo("conf/sigmod/LiuPTBBZBHY98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202671%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LoR96","9OcrAEypDhMJ")).
neg(eqo("conf/sigmod/LoR96","UrpPvOlm9RYJ")).
neg(eqo("conf/sigmod/LometT99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D51710%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Mamoulis03","3iVRJJMjVWUJ")).
neg(eqo("conf/sigmod/MamoulisP99","VWMCdCXctgAJ")).
neg(eqo("conf/sigmod/Mohan99","IWM2gExnQLkJ")).
neg(eqo("conf/sigmod/Mohan99","U0ndc4dAwIUJ")).
neg(eqo("conf/sigmod/Mohan99","v5RwghqO86sJ")).
neg(eqo("conf/sigmod/MohanN94","E2zhARKv5dsJ")).
neg(eqo("conf/sigmod/MumickQM97","rgJU30QjbhkJ")).
neg(eqo("conf/sigmod/NatsevRS99","CyzIFxmvc1cJ")).
neg(eqo("conf/sigmod/OoiTZGLLLNSWZ03","tK1_3wGUIHsJ")).
neg(eqo("conf/sigmod/OoiTZGLLLNSWZ03","url:http://www.springerlink.com/index/L4H4H12200406465.pdf")).
neg(eqo("conf/sigmod/Ozsu99","qfohkpyTawoJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","F8CacVSkztEJ")).
neg(eqo("conf/sigmod/PhanN02","LLIkm2GMqakJ")).
neg(eqo("conf/sigmod/PonnekantiK00","Dp-IVSNyOAEJ")).
neg(eqo("conf/sigmod/ProcopiucJAM02","9w4FLFcZm_0J")).
neg(eqo("conf/sigmod/RafieiM97","qq2lTNrNTBUJ")).
neg(eqo("conf/sigmod/RajagopalanML98","ouqvgPNWveYJ")).
neg(eqo("conf/sigmod/RoySSB00","CLD080j61G8J")).
neg(eqo("conf/sigmod/SaltenisJLL00","q49c-IEX7N8J")).
neg(eqo("conf/sigmod/SaltenisJLL00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130879%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Sarawagi00","AaKiSc1klw8J")).
neg(eqo("conf/sigmod/Sarawagi00","vexnRjaFR8kJ")).
neg(eqo("conf/sigmod/SchusterW01","6czAWapXkZYJ")).
neg(eqo("conf/sigmod/Seshadri99","cL_OKIQDvmQJ")).
neg(eqo("conf/sigmod/SeshadriP97","jSAtXghimR0J")).
neg(eqo("conf/sigmod/ShivakumarG97","GkwWJKTSdTwJ")).
neg(eqo("conf/sigmod/ShouCTRH01","PoVkG8nD28IJ")).
neg(eqo("conf/sigmod/Squire95","Y1HVgTopekIJ")).
neg(eqo("conf/sigmod/SrikantA96","WSVs3nCRe8EJ")).
neg(eqo("conf/sigmod/Stonebraker98","DDyZXuEtGiwJ")).
neg(eqo("conf/sigmod/Team02","IXOBKs9nvXwJ")).
neg(eqo("conf/sigmod/TheobaldW02","hulo0jCbUIMJ")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","8HmbQ7H151AJ")).
neg(eqo("conf/sigmod/TsurUACMNR98","0sQVbohb7DcJ")).
neg(eqo("conf/sigmod/Ubell94","lPxeU6-K_9EJ")).
neg(eqo("conf/sigmod/WangCMSSZ94","4VBAPd5PM9AJ")).
neg(eqo("conf/sigmod/WangCMSSZ94","_uAjDh22Y_EJ")).
neg(eqo("conf/sigmod/WangPFY03","8i1ulDTkSU4J")).
neg(eqo("conf/sigmod/WangSCRZP97","r5Bd_PrKpeQJ")).
neg(eqo("conf/sigmod/WangZS95","5VR8C6g8DNoJ")).
neg(eqo("conf/sigmod/WhitneyS01","JaC8ZOgaYU4J")).
neg(eqo("conf/sigmod/WoelkBJOTU95","G3QWq2T08SEJ")).
neg(eqo("conf/sigmod/YerneniLGU99","hnMltY0uSf0J")).
neg(eqo("conf/sigmod/ZaharioudakisCLPU00","bzILe3oHezgJ")).
neg(eqo("conf/sigmod/Zeller03","QFeUfn2QS5EJ")).
neg(eqo("conf/sigmod/ZhangMCMR02","Phcd3C1cfLcJ")).
neg(eqo("conf/sigmod/ZhangNBB94","GXApzwcGl78J")).
neg(eqo("conf/sigmod/ZhangRL96","Koo3549nY2kJ")).
neg(eqo("conf/sigmod/ZhangRL96","mbeIcD0N1rQJ")).
neg(eqo("conf/sigmod/ZhuS03","url:http://pubs.acs.org/cgi-bin/abstract.cgi/achre4/2003/36/i09/abs/ar020268q.html")).
neg(eqo("conf/vldb/AbiteboulMRVW98","18_r28t9ICYJ")).
neg(eqo("conf/vldb/AbrolLMMMRTWZ01","GRoJrzTWJs4J")).
neg(eqo("conf/vldb/AcharyaFZ96","qTCsXcCsI7UJ")).
neg(eqo("conf/vldb/Adler01","J3cfnmFB4lsJ")).
neg(eqo("conf/vldb/AgarwalADGNRS96","hemKMOVyS4UJ")).
neg(eqo("conf/vldb/AggarwalHWY03","J8VyjQ-1hbYJ")).
neg(eqo("conf/vldb/AgrawalK02","wivJNEQEWzMJ")).
neg(eqo("conf/vldb/AgrawalS94","NDKJPUgy_K4J")).
neg(eqo("conf/vldb/AgrawalS94","wivJNEQEWzMJ")).
neg(eqo("conf/vldb/AgrawalSX01","ewsBMN0qVa4J")).
neg(eqo("conf/vldb/AksoyZF01","E6D-UhwTP_EJ")).
neg(eqo("conf/vldb/AltinelF00","W1di9S0fUsEJ")).
neg(eqo("conf/vldb/Amer-YahiaFSX03","UwOgoqlmVyoJ")).
neg(eqo("conf/vldb/AmielBDS94","hBak02oe1GMJ")).
neg(eqo("conf/vldb/AnKR03","foIW8l---xQJ")).
neg(eqo("conf/vldb/AnanthakrishnaCG02","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565131%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/ArionBCDMP03","ea5jAqlGNIoJ")).
neg(eqo("conf/vldb/AshwinGG02","DK1HpJEO_mwJ")).
neg(eqo("conf/vldb/Bar-YossefBCFW00","q0Ovw6QUk3MJ")).
neg(eqo("conf/vldb/BaumannDFRW99","LPNhDh6p-wwJ")).
neg(eqo("conf/vldb/BaumannFRW97","ZP3wEgyGJroJ")).
neg(eqo("conf/vldb/BaumgartnerFG01","E1pYIBtTvIoJ")).
neg(eqo("conf/vldb/BerckenS01","KIcdXVHeIAEJ")).
neg(eqo("conf/vldb/BliujuteJSS98","IDqN11yoZf8J")).
neg(eqo("conf/vldb/BlottKS98","htMO0uWGzvoJ")).
neg(eqo("conf/vldb/BohmMSW01","n-tA57d7ydcJ")).
neg(eqo("conf/vldb/BonifatiCDS01","MlGBfhLPKSkJ")).
neg(eqo("conf/vldb/BouguettayaEMO01","U-Kd4GQ_vCMJ")).
neg(eqo("conf/vldb/BrinkhoffK94","13dQPU7Z73gJ")).
neg(eqo("conf/vldb/BrinkhoffK94","7eCKuoVcrDEJ")).
neg(eqo("conf/vldb/Brodie00","o-eBjd_Pe7IJ")).
neg(eqo("conf/vldb/BrodieC99","EMte57Ktmo8J")).
neg(eqo("conf/vldb/BrodieC99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066184%26type%3Dpdf")).
neg(eqo("conf/vldb/CarinoO98","dL06L6LhaUkJ")).
neg(eqo("conf/vldb/CeriFP99","iUGa3pKj-20J")).
neg(eqo("conf/vldb/ChakrabartiGRS00","2Pc6rKYB8ykJ")).
neg(eqo("conf/vldb/ChakrabartiGRS00","SHDQQrfJ3BMJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","2TVYDBNYioIJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","4tTQJrG4pn8J")).
neg(eqo("conf/vldb/ChakrabartiSD98","zDznH1GBa7UJ")).
neg(eqo("conf/vldb/ChatziantoniouR96","_N1BQELfUk0J")).
neg(eqo("conf/vldb/ChatziantoniouR97","HGXaVrOM_NwJ")).
neg(eqo("conf/vldb/ChaudhuriN97","OuM0E0BhEXIJ")).
neg(eqo("conf/vldb/ChaudhuriS96","31oH64SXpRcJ")).
neg(eqo("conf/vldb/ChaudhuriS96","ccBj_crE4I8J")).
neg(eqo("conf/vldb/ChaudhuriW00","jXxjB08qsTsJ")).
neg(eqo("conf/vldb/Chawathe99","62I9Xi01u_8J")).
neg(eqo("conf/vldb/CherniackFZ01","4ygpC0j5uugJ")).
neg(eqo("conf/vldb/CherniackZ98","-tWXs3DM8w0J")).
neg(eqo("conf/vldb/ChoALS02","epUf9ogilogJ")).
neg(eqo("conf/vldb/ChoG00","GEkf46wqTckJ")).
neg(eqo("conf/vldb/ChoG00","LPF_zzgFeJUJ")).
neg(eqo("conf/vldb/CochranePM96","kT7z4mcwLrYJ")).
neg(eqo("conf/vldb/ColletCS94","Iap8Eg0Sm8oJ")).
neg(eqo("conf/vldb/ColletCS94","bJi1sP0H7TsJ")).
neg(eqo("conf/vldb/CuiW01","SaOd6rDz5ZgJ")).
neg(eqo("conf/vldb/DattaRT99","olLWfYEBtmoJ")).
neg(eqo("conf/vldb/Dayal99","Jn04zNyJy3UJ")).
neg(eqo("conf/vldb/DayalHL01","url:http://portal.acm.org/citation.cfm%3Fid%3D38713")).
neg(eqo("conf/vldb/DaynesC02","url:http://doi.wiley.com/10.1002/he.89")).
neg(eqo("conf/vldb/Draluk01","hfrMmlaE-vwJ")).
neg(eqo("conf/vldb/EicklerGK95","sRcMuuo3-BEJ")).
neg(eqo("conf/vldb/EleftheriouBCDHLPPABDDDGJHLRSVW03","h7_7SZrI7M0J")).
neg(eqo("conf/vldb/FaloutsosJS97","dCSltH1rZ0YJ")).
neg(eqo("conf/vldb/FlorescuLSY99","DfOLEzMoEaEJ")).
neg(eqo("conf/vldb/GalanisWJD03","JvthmGX_uoQJ")).
neg(eqo("conf/vldb/Galindo-LegariaJWW03","kXON0eJukd4J")).
neg(eqo("conf/vldb/GardarinGT95","kOSE6UVijD8J")).
neg(eqo("conf/vldb/GarofalakisG02","xP05B8kLbyEJ")).
neg(eqo("conf/vldb/GehrkeRG98","G8JSWUAO2lMJ")).
neg(eqo("conf/vldb/George98","qv9JuA63NQMJ")).
neg(eqo("conf/vldb/GeorgeH98","RmyORCW6qn8J")).
neg(eqo("conf/vldb/Gibbons01","k3znuHyMD0oJ")).
neg(eqo("conf/vldb/GoldmanW97","Ol886Ck3jz4J")).
neg(eqo("conf/vldb/GoodmanRS94","kE0fOJ1UAOkJ")).
neg(eqo("conf/vldb/GyssensL97","5ZEYqz95ZRAJ")).
neg(eqo("conf/vldb/GyssensL97","Akh41zGLOowJ")).
neg(eqo("conf/vldb/HanF95","h0jX6zbYeeEJ")).
neg(eqo("conf/vldb/Hess96","VsMy-xvyAnMJ")).
neg(eqo("conf/vldb/HjelsvoldM94","08TsxdfR0vMJ")).
neg(eqo("conf/vldb/HristidisGP03","5k-GwvznWRUJ")).
neg(eqo("conf/vldb/HulgeriS02","1wCoLVGeNTAJ")).
neg(eqo("conf/vldb/Huyn97","uiL1ljfwt9IJ")).
neg(eqo("conf/vldb/HvasshovdBT00","uWpo8yp4RrQJ")).
neg(eqo("conf/vldb/JagadishNSSK97","xACnzf6RhVwJ")).
neg(eqo("conf/vldb/JohnsonM98","eFynrwKK_T0J")).
neg(eqo("conf/vldb/Keogh02","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D155956WS%26recid%3D199301530041MD")).
neg(eqo("conf/vldb/Kleewein96","rXaCSxty6AAJ")).
neg(eqo("conf/vldb/Klots96","H8ApxV0YtJkJ")).
neg(eqo("conf/vldb/KonopnickiS95","xYGs7tIreesJ")).
neg(eqo("conf/vldb/KornackerB95","cZsiuZAvlTUJ")).
neg(eqo("conf/vldb/KornackerB95","p-vhRwBl8kcJ")).
neg(eqo("conf/vldb/Korth95","ct1XLnOieGEJ")).
neg(eqo("conf/vldb/KoschBBHHLRT01","crm7SR8JORoJ")).
neg(eqo("conf/vldb/KossmannRR02","iGlztgiSTe4J")).
neg(eqo("conf/vldb/KoudasS03","PIaVLVH-JFUJ")).
neg(eqo("conf/vldb/LabioG96","DPVBuf0A4z0J")).
neg(eqo("conf/vldb/LabioYCGW00","6uJxkOy-gTMJ")).
neg(eqo("conf/vldb/LabrinidisR03","3Ozte0ucNJAJ")).
neg(eqo("conf/vldb/LakshmananJN00","YPn5OUTxF7MJ")).
neg(eqo("conf/vldb/LeeL96","tuVp_18tFv8J")).
neg(eqo("conf/vldb/LeeL99","8xz3v-RLsWQJ")).
neg(eqo("conf/vldb/LeslieJBY95","HxQoc9PkFOMJ")).
neg(eqo("conf/vldb/LeslieJBY95","kZFfJieudW4J")).
neg(eqo("conf/vldb/LiC94","AzXOY6FxAPYJ")).
neg(eqo("conf/vldb/LiC94","O0rvK0GFmBEJ")).
neg(eqo("conf/vldb/LuSL95","43cFE2_uPYIJ")).
neg(eqo("conf/vldb/LudasaherGM00","0Jxw-OUJSlIJ")).
neg(eqo("conf/vldb/MadhavanBR01","W1Wqm0F1KukJ")).
neg(eqo("conf/vldb/ManegoldBK02","Ug0Yk0QhILMJ")).
neg(eqo("conf/vldb/MankuM02","ZQyBjtpbhvIJ")).
neg(eqo("conf/vldb/MarianS03","x2hUcxkW4Z4J")).
neg(eqo("conf/vldb/Mattos03","81lIJ3XvGC8J")).
neg(eqo("conf/vldb/May01","Fb4oYRM9N4EJ")).
neg(eqo("conf/vldb/McHughW99","3KKDaXmc5LwJ")).
neg(eqo("conf/vldb/Mohan01","Hc029KXUhX8J")).
neg(eqo("conf/vldb/Mohan02a","CG-_La4oAYkJ")).
neg(eqo("conf/vldb/Mohan02a","e4YeA3IWjgYJ")).
neg(eqo("conf/vldb/MohaniaS94","E02lExYdRYwJ")).
neg(eqo("conf/vldb/NetzCBF00","9TpHm8FZiO8J")).
neg(eqo("conf/vldb/NinkHR99","C9imFvgrSvAJ")).
neg(eqo("conf/vldb/NipplM98","g-zpzYjVMI8J")).
neg(eqo("conf/vldb/Nori00","mWuPf5-HF_gJ")).
neg(eqo("conf/vldb/Norvag99","9MlAuURfKhYJ")).
neg(eqo("conf/vldb/PappasC00","jTD-gdUfEHEJ")).
neg(eqo("conf/vldb/PardonA00","TSje6z0ylUIJ")).
neg(eqo("conf/vldb/PereiraFLS00","GzZSEeVoAiUJ")).
neg(eqo("conf/vldb/PereiraFLS00","s_ETi_2fp-oJ")).
neg(eqo("conf/vldb/PoosalaI97","KrVgTXcNPPUJ")).
neg(eqo("conf/vldb/PoulovassilisS94","EMK8ZjQyjvoJ")).
neg(eqo("conf/vldb/RezendeH98","U04OC6OSBT0J")).
neg(eqo("conf/vldb/RezendeH98","xYUrn78qvEkJ")).
neg(eqo("conf/vldb/RezendeS98","8Ojx7Me_oz0J")).
neg(eqo("conf/vldb/RisheYACLMVSV00","GukaCxN-t58J")).
neg(eqo("conf/vldb/RoussopoulosK98","1UYnwxMInjsJ")).
neg(eqo("conf/vldb/SakuraiYUK00","_noDYv-nhjMJ")).
neg(eqo("conf/vldb/Sarawagi00","lOFly1WWz4EJ")).
neg(eqo("conf/vldb/Sarawagi95","AtjjFL5IdBcJ")).
neg(eqo("conf/vldb/Sarawagi99","9qOUH5DfZ64J")).
neg(eqo("conf/vldb/SchaeferBBJ00","QjsQzIa5jCUJ")).
neg(eqo("conf/vldb/SchmidtWKCMB02","LJgXl8u26jUJ")).
neg(eqo("conf/vldb/SchmidtWKCMB02","QyBDbs7EpmsJ")).
neg(eqo("conf/vldb/Schoning03","ygC4pAYSgsUJ")).
neg(eqo("conf/vldb/SeifertS02","uS-v_N8yu7MJ")).
neg(eqo("conf/vldb/SenkulKT02","MOO6fysJ1pUJ")).
neg(eqo("conf/vldb/SeshadriLR96","CYaZBTJNWhMJ")).
neg(eqo("conf/vldb/ShaferA97","He4kNWMxlcoJ")).
neg(eqo("conf/vldb/ShaferA97","JfxEos8BQDAJ")).
neg(eqo("conf/vldb/ShahDR03","rHLmfJRQUu0J")).
neg(eqo("conf/vldb/Shenker03","url:http://doi.wiley.com/10.1002/he.12.abs")).
neg(eqo("conf/vldb/ShiSZ03","-OjqoDQTIxMJ")).
neg(eqo("conf/vldb/SimonD95","F9x2JRvnRmYJ")).
neg(eqo("conf/vldb/SistlaYH94","_jl3bN2QlE4J")).
neg(eqo("conf/vldb/SteenhagenABB94","8vJEjrhM7foJ")).
neg(eqo("conf/vldb/Suciu96","Ikk1rb4o66UJ")).
neg(eqo("conf/vldb/Suciu96a","Ikk1rb4o66UJ")).
neg(eqo("conf/vldb/TsatalosSI94","IEDWZhQnwgUJ")).
neg(eqo("conf/vldb/TsoisS03","bF9YiKytTRgJ")).
neg(eqo("conf/vldb/TsurAADKW01","alLAvBYDr-EJ")).
neg(eqo("conf/vldb/TsurAADKW01","gUJrOpj89tQJ")).
neg(eqo("conf/vldb/Wadler01","dzD5B4A2OBQJ")).
neg(eqo("conf/vldb/Wang95","YHUN_yiwIOUJ")).
neg(eqo("conf/vldb/WangHH00","exlmxQKU2_UJ")).
neg(eqo("conf/vldb/WangZ00","R53pO6B3LhcJ")).
neg(eqo("conf/vldb/WiesnerK01","8p0ad6wEQcEJ")).
neg(eqo("conf/vldb/WildfogelY97","hOcniOdybHQJ")).
neg(eqo("conf/vldb/WuYCT95","E1lyWHgwZl4J")).
neg(eqo("conf/vldb/WuYCT95","JXI-CvxzElQJ")).
neg(eqo("conf/vldb/YagoubFIV00","ngDF4FZmhsMJ")).
neg(eqo("conf/vldb/YanA94","pPJsIkioV9wJ")).
neg(eqo("conf/vldb/YanG95","8AbhqDuUEd4J")).
neg(eqo("conf/vldb/YanG95","baVAtfo4WCoJ")).
neg(eqo("conf/vldb/YanL95","BNyeiu2AmWAJ")).
neg(eqo("conf/vldb/YangG01","jW-WtqeQ_tEJ")).
neg(eqo("conf/vldb/YangG01","lr_Kq9SZLY8J")).
neg(eqo("conf/vldb/YuPM03","ZEEZqsnVCyYJ")).
neg(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637423%26dl%3Dportal%26dl%3DACM%26type%3Dissue%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03c","KPTq63wCGV4J")).
neg(eqo("journals/sigmod/Aberer03c","dNM-avLn230J")).
neg(eqo("journals/sigmod/Aberer03d","fnt5G2r4MaYJ")).
neg(eqo("journals/sigmod/Aberer03d","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604274%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AbererCH02","RSNC3ApuY3AJ")).
neg(eqo("journals/sigmod/AilamakiG03","BQtJOT7gAIIJ")).
neg(eqo("journals/sigmod/AlonsoCIM95","fFCqy9V5XNgJ")).
neg(eqo("journals/sigmod/ArenasKKKMM03","wsJ1nllw0KAJ")).
neg(eqo("journals/sigmod/BallMRZ02","P0eGT4SuI0gJ")).
neg(eqo("journals/sigmod/Barbara01","0whivG_IK1wJ")).
neg(eqo("journals/sigmod/BarbaraBFLS94","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D8204540535MD")).
neg(eqo("journals/sigmod/BerraNT95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D156893%26type%3Dpdf")).
neg(eqo("journals/sigmod/Bestavros96","buE9XA1oF2UJ")).
neg(eqo("journals/sigmod/BollKB98","-NNuFjchxnMJ")).
neg(eqo("journals/sigmod/BollKB98","1QOF8F7robYJ")).
neg(eqo("journals/sigmod/BollKB98","kzsFgwFZl_IJ")).
neg(eqo("journals/sigmod/BonnetBDL03","pBKI-JCAlcIJ")).
neg(eqo("journals/sigmod/BuchnerM98","PF-rFkrW2nIJ")).
neg(eqo("journals/sigmod/BunemanLSTW94","q8MxrLeFlz8J")).
neg(eqo("journals/sigmod/BurtonM98","0mk_QzaJKHEJ")).
neg(eqo("journals/sigmod/BusslerFM02","A_CuTWh-U2MJ")).
neg(eqo("journals/sigmod/ButtlerCCFHLPRX02","biv7Nf9qwBYJ")).
neg(eqo("journals/sigmod/CalvaneseGLV03","UbQbEQ2byRYJ")).
neg(eqo("journals/sigmod/Cardelli01","UYAoi4DYOXUJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","0EbuWDceVnoJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","ihljCMaS2UsJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141827%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Chang03","BGagLieYacQJ")).
neg(eqo("journals/sigmod/CheungF98","wuQbvQAcACsJ")).
neg(eqo("journals/sigmod/ChongFTSYKDJJ03","dr4SzOhnLB8J")).
neg(eqo("journals/sigmod/ClementLGMK97","To_EjIKwfSAJ")).
neg(eqo("journals/sigmod/CruzKLSWY02","eIQIzryIl24J")).
neg(eqo("journals/sigmod/Darwen96","St8wEA8ZcLkJ")).
neg(eqo("journals/sigmod/DarwenD95","7jC5y7Krk9sJ")).
neg(eqo("journals/sigmod/Date03","RhExFXYXavMJ")).
neg(eqo("journals/sigmod/DoanPK95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1024696%26type%3Dpdf")).
neg(eqo("journals/sigmod/Dogac96","RuX0Qvu4YRUJ")).
neg(eqo("journals/sigmod/Dogac98","lpuErTjd6dQJ")).
neg(eqo("journals/sigmod/DunhamH95","tcE4Vg0cRm8J")).
neg(eqo("journals/sigmod/DunhamH95a","X9Z5cVGAD7YJ")).
neg(eqo("journals/sigmod/EisenbergM00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344819%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/EisenbergM99a","2y9m1qzVu4EJ")).
neg(eqo("journals/sigmod/ElmagarmidJF95","goq6Z9bDeSsJ")).
neg(eqo("journals/sigmod/Finkelstein95","biv7Nf9qwBYJ")).
neg(eqo("journals/sigmod/FlorescuLM98","q5OOyzSAlC8J")).
neg(eqo("journals/sigmod/Fong95","7AF2AGZOlAwJ")).
neg(eqo("journals/sigmod/Fong95","ciDxtQNYTsEJ")).
neg(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","Gc4SDdWXE9QJ")).
neg(eqo("journals/sigmod/Franklin00","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin00a","-YhYDZ2AhfgJ")).
neg(eqo("journals/sigmod/Franklin97b","url:http://portal.acm.org/citation.cfm%3Fid%3D197445")).
neg(eqo("journals/sigmod/Franklin97b","url:http://portal.acm.org/citation.cfm%3Fid%3D362084%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin97b","zQh4_G37HVQJ")).
neg(eqo("journals/sigmod/Franklin99","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin99","zc1TRuoDDwgJ")).
neg(eqo("journals/sigmod/GolabO03","lC5GjK5OpD0J")).
neg(eqo("journals/sigmod/GottlobKP03","-j7bzyIKuX0J")).
neg(eqo("journals/sigmod/GrayG97","fFCqy9V5XNgJ")).
neg(eqo("journals/sigmod/GriffinK98","ASfROcKWFmgJ")).
neg(eqo("journals/sigmod/GriffinK98","oMn0NXWTlNUJ")).
neg(eqo("journals/sigmod/Group94","zd_8s13rNRoJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","bEu_llku9NMJ")).
neg(eqo("journals/sigmod/GunopulosK01","KamrJHXS4JgJ")).
neg(eqo("journals/sigmod/Hainaut03","uEbdEtnaCXMJ")).
neg(eqo("journals/sigmod/Hainaut03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959087%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Han98","oGKKTxiRq9kJ")).
neg(eqo("journals/sigmod/Huyn01","EY2ObzVBgdIJ")).
neg(eqo("journals/sigmod/JacobS99","3-iiSyJLwLkJ")).
neg(eqo("journals/sigmod/JacobS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245906%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Keim96","Rbzw8I6aWRoJ")).
neg(eqo("journals/sigmod/Keim96","vkUvhZOw-1YJ")).
neg(eqo("journals/sigmod/KennedyMB96","79NKRYC6cAoJ")).
neg(eqo("journals/sigmod/Kim02","xZQZ4IzUmdoJ")).
neg(eqo("journals/sigmod/KoksalAD98","68kgfVBXccEJ")).
neg(eqo("journals/sigmod/LawderK01","_4ARkdpRArQJ")).
neg(eqo("journals/sigmod/LightstoneLZ02","BrO3XOrt66MJ")).
neg(eqo("journals/sigmod/Liu01b","uGmwRkan8EYJ")).
neg(eqo("journals/sigmod/Liu01b","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565142%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Liu02","dO8czlfdENQJ")).
neg(eqo("journals/sigmod/Liu02b","-YhYDZ2AhfgJ")).
neg(eqo("journals/sigmod/Liu02b","pBKI-JCAlcIJ")).
neg(eqo("journals/sigmod/Liu02c","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Liu03","pE4UwP5xQo4J")).
neg(eqo("journals/sigmod/Liu03","url:http://ieeexplore.ieee.org/iel3/3990/11481/00547836.pdf%3Farnumber%3D547836")).
neg(eqo("journals/sigmod/Liu03","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Lomet01","D4MiKRaC-rEJ")).
neg(eqo("journals/sigmod/MaelbranckeO95","c2PgXbSSAFcJ")).
neg(eqo("journals/sigmod/MalaikaEM03","Ng8CP2M8eUQJ")).
neg(eqo("journals/sigmod/Mani03","CY6IrePfW3kJ")).
neg(eqo("journals/sigmod/Mani03","hO_32Nq5uMkJ")).
neg(eqo("journals/sigmod/Manola98","-iis302p2MkJ")).
neg(eqo("journals/sigmod/MedskerCS95","4S8hl8TtKDsJ")).
neg(eqo("journals/sigmod/MedskerCS95","GZGUpgdV8kEJ")).
neg(eqo("journals/sigmod/MusickC99","wI75uFSs0bwJ")).
neg(eqo("journals/sigmod/NejdlSS03","y_BZyFdnEMUJ")).
neg(eqo("journals/sigmod/NestorovAM97","_lCYrsJ1UxEJ")).
neg(eqo("journals/sigmod/ONeilG95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107507%26type%3Dpdf")).
neg(eqo("journals/sigmod/OukselS99","vNW-Vb97R8gJ")).
neg(eqo("journals/sigmod/PhatakSSS96","IJyunaAcul8J")).
neg(eqo("journals/sigmod/Qian94a","tKeGALC3uFMJ")).
neg(eqo("journals/sigmod/Qian95a","mH0vNFMcLxsJ")).
neg(eqo("journals/sigmod/Qian96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187462%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/QuixSJ02","8KJ9XFv1ESAJ")).
neg(eqo("journals/sigmod/Rosenthal98","chmPCuLihZoJ")).
neg(eqo("journals/sigmod/RossGR03","Ylx_hGu1NrsJ")).
neg(eqo("journals/sigmod/RossGR03","ki6h8TZDRb4J")).
neg(eqo("journals/sigmod/RossIJP00","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/Roussopoulos98","GfjHZswtM0EJ")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","9DSjjiMXVFMJ")).
neg(eqo("journals/sigmod/Segev94","url:http://adsabs.harvard.edu/abs/1994mit..reptQ....L")).
neg(eqo("journals/sigmod/SegevJS95","2kiNfwTpqp4J")).
neg(eqo("journals/sigmod/ShahMFH01","gAmSzeXAcyQJ")).
neg(eqo("journals/sigmod/SilberschatzSU96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141004%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass02","V3C6Q9Ki3FAJ")).
neg(eqo("journals/sigmod/Snodgrass02b","2p2A5_qGf5cJ")).
neg(eqo("journals/sigmod/Snodgrass94","7F9iCGggYVgJ")).
neg(eqo("journals/sigmod/SonDT96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219769%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SouzaS99","WWaxLMIptTMJ")).
neg(eqo("journals/sigmod/SouzaS99","_VgLIyofOHAJ")).
neg(eqo("journals/sigmod/SpynsMJ02","-H_tozyCqk4J")).
neg(eqo("journals/sigmod/Stonebraker02","YXZ8kOo0wpEJ")).
neg(eqo("journals/sigmod/TomasicS97","lEQ4uPFcizcJ")).
neg(eqo("journals/sigmod/TsotrasJS98","f3-E7x12K4gJ")).
neg(eqo("journals/sigmod/VassiliadisS99","75BD5JhAlbsJ")).
neg(eqo("journals/sigmod/VassiliadisS99","Kv83PnRGpIwJ")).
neg(eqo("journals/sigmod/Widom95","tOlGOS5EIQYJ")).
neg(eqo("journals/sigmod/Widom95a","5Ca6WOB3X-wJ")).
neg(eqo("journals/sigmod/Widom95a","A_i4OxOjMe0J")).
neg(eqo("journals/sigmod/Widom95a","j-KmI7HKqGQJ")).
neg(eqo("journals/sigmod/Widom96","tOlGOS5EIQYJ")).
neg(eqo("journals/sigmod/Widom96a","V9hwlxLsHRsJ")).
neg(eqo("journals/sigmod/Widom96a","zWrQD-2VvWgJ")).
neg(eqo("journals/sigmod/Winslett02","IOayjaBtu_4J")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031579%26type%3Dpdf")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/citation.cfm%3Fid%3D1031570.1031579")).
neg(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/citation.cfm%3Fid%3D1083784.1083802")).
neg(eqo("journals/sigmod/WinslettCDHZZ02","LjrsWIr3rhAJ")).
neg(eqo("journals/sigmod/WuY00","6WlbpsI0PdUJ")).
neg(eqo("journals/tods/BozkayaO99","aQ8utUzZ7ToJ")).
neg(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
neg(eqo("journals/tods/CaldersNW02","uIs2PQwXg2AJ")).
neg(eqo("journals/tods/CasatiCPP99","9LFaQZ1v2m4J")).
neg(eqo("journals/tods/CeriFPT94","aphxPCo8qkgJ")).
neg(eqo("journals/tods/ChaudhuriS99","hglTCgKqzBAJ")).
neg(eqo("journals/tods/ChaudhuriS99","q2ZF-a_JbOoJ")).
neg(eqo("journals/tods/Chen95","175GVbHyl8wJ")).
neg(eqo("journals/tods/Chen95a","8JSwKJipBnIJ")).
neg(eqo("journals/tods/Chomicki03","pHuL-9kHWH0J")).
neg(eqo("journals/tods/Chomicki95","7qdukmr2FhAJ")).
neg(eqo("journals/tods/ChomickiTB01","MqgSlx1jbPsJ")).
neg(eqo("journals/tods/CliffordDIJS97","rGfhB3UE5mYJ")).
neg(eqo("journals/tods/DeyS96","UQNAaR6CBxcJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","Vjga5yC23KIJ")).
neg(eqo("journals/tods/GhandeharizadehHJ96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D320112%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/GibbonsMP02","jMku9rPCt9sJ")).
neg(eqo("journals/tods/HjaltasonS99","H6XGSfr9v6MJ")).
neg(eqo("journals/tods/HjaltasonS99","TNx5vnRHHxMJ")).
neg(eqo("journals/tods/HjaltasonS99","dgDrTf52fbgJ")).
neg(eqo("journals/tods/KemmeA00","TJDMWbCXMtgJ")).
neg(eqo("journals/tods/KemmeA00","esJUEq0b_EUJ")).
neg(eqo("journals/tods/KorthS94","mVK23-2iOugJ")).
neg(eqo("journals/tods/LakshmananSS01","en4hLhFwFPAJ")).
neg(eqo("journals/tods/LakshmananSS01","qmrGOToSJn0J")).
neg(eqo("journals/tods/Lerner00","LBoee-zlAggJ")).
neg(eqo("journals/tods/MokNE96","NG9LBxb8CCoJ")).
neg(eqo("journals/tods/MumickFPR96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D227624%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/RosenthalR94","ix1k9dPzH9EJ")).
neg(eqo("journals/tods/SchuldtABS02","EHWbn1YLsOcJ")).
neg(eqo("journals/tods/Snodgrass01a","5Pj1WwL3WI8J")).
neg(eqo("journals/vldb/AlbanoGO95","YMQanNdiBSsJ")).
neg(eqo("journals/vldb/Amer-YahiaCLS02","LJgXl8u26jUJ")).
neg(eqo("journals/vldb/Amer-YahiaCLS02","SdqZz-Rnmk4J")).
neg(eqo("journals/vldb/AntoshenkovZ96","pw234_REfHUJ")).
neg(eqo("journals/vldb/Atkinson00","cDN9oOqsTE0J")).
neg(eqo("journals/vldb/Atkinson00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D765219%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/RTCC57FUUW3CADRF.pdf")).
neg(eqo("journals/vldb/Baumann94","1sGr4qMsCeMJ")).
neg(eqo("journals/vldb/BunemanFS00","E_CQlx3K0W4J")).
neg(eqo("journals/vldb/CandanLS00","7ZyV9ivZySQJ")).
neg(eqo("journals/vldb/ChanGR03","whWOU1ebCC8J")).
neg(eqo("journals/vldb/ConstantopoulosJMV95","IPVnDaGydoIJ")).
neg(eqo("journals/vldb/DattaDVRN01","icK75z3VuGIJ")).
neg(eqo("journals/vldb/DattaDVRN01","yH8GRTxULRkJ")).
neg(eqo("journals/vldb/FiebigHKMNSW02","url:http://doi.wiley.com/10.1002/he.80")).
neg(eqo("journals/vldb/HansonCDERTX98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290607%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/HarderST99","LtcG8lMUYZIJ")).
neg(eqo("journals/vldb/IoannidisNSS97","b_gg3-xOwSIJ")).
neg(eqo("journals/vldb/IoannidisNSS97","url:http://portal.acm.org/citation.cfm%3Fid%3D592093.592142")).
neg(eqo("journals/vldb/LawLG99","rIqIRaIVpMMJ")).
neg(eqo("journals/vldb/LeeSC01","HcCevkoobDsJ")).
neg(eqo("journals/vldb/Li03","zWvzud6p3U4J")).
neg(eqo("journals/vldb/LometS97","csOZscyXQ4IJ")).
neg(eqo("journals/vldb/NgS98","3fKmWB1DCE8J")).
neg(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
neg(eqo("journals/vldb/Ozsu03","gndV1O-oEkMJ")).
neg(eqo("journals/vldb/PacittiS00","9ReaNbX2I-IJ")).
neg(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
neg(eqo("journals/vldb/RamamohanaraoH94","uWpo8yp4RrQJ")).
neg(eqo("journals/vldb/Seshadri98","JfxEos8BQDAJ")).
neg(eqo("journals/vldb/Seshadri98","c-p7pgwbwP0J")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","wTJy5XquCpsJ")).
neg(eqo("journals/vldb/ShegalovGW01","xYqCareagPwJ")).
neg(eqo("journals/vldb/ShethTP03","WvNsp5oCGgkJ")).
neg(eqo("journals/vldb/SinghalS97","dKeoD6npRBIJ")).
neg(eqo("journals/vldb/SinghalS97","tQ8saUTFsNsJ")).
neg(eqo("journals/vldb/SteinbrunnMK97","oGxLABq_hAoJ")).
neg(eqo("journals/vldb/WhangKW94","aOBNgdooDHAJ")).
neg(eqo("journals/vldb/YangW03","UEfbwqtTtlUJ")).
pos(eqo("conf/sigmod/AbadiCCCCEGHMRSSTXYZ03","gBVNSFeS4P8J")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","AxpQwgyRyLgJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","9OEjtHuRUzsJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","FDPwbRQbfIAJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","Hf3gZHIcm58J")).
pos(eqo("conf/sigmod/AcharyaFZ97","qdCTR7WpuFUJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","mOngiXbKrNkJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","s064OghlyIUJ")).
pos(eqo("conf/sigmod/AcharyaPR99","-k0cD5NwXnoJ")).
pos(eqo("conf/sigmod/AcharyaPR99","0dY1brFaEzgJ")).
pos(eqo("conf/sigmod/AcharyaPR99","2RuI2vzDUW8J")).
pos(eqo("conf/sigmod/Adelberg98","3hsPMPTl2msJ")).
pos(eqo("conf/sigmod/Adelberg98","UT0h0HcwLyUJ")).
pos(eqo("conf/sigmod/AgrawalASY97","3nxl8d4c0t4J")).
pos(eqo("conf/sigmod/AgrawalASY97","C85vtVHZmjUJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","Hj3vyh0TJVsJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","K1ZdQsRoNloJ")).
pos(eqo("conf/sigmod/AshleyFHLNP95","tL67lYBCRO4J")).
pos(eqo("conf/sigmod/AtzeniT97","KFmRUQEedY8J")).
pos(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
pos(eqo("conf/sigmod/BabuGR01","zQCRmiH6jo4J")).
pos(eqo("conf/sigmod/BarclaySG00","JTEJ-q3T1vsJ")).
pos(eqo("conf/sigmod/BarclaySG00","tKeGALC3uFMJ")).
pos(eqo("conf/sigmod/BargaL99","QGxyK7bJQOMJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","3SHIgRrrL5QJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","JYHcz-HpKjEJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","arQIThq-W4gJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wTXunETZhPwJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wsNuAYMG0QEJ")).
pos(eqo("conf/sigmod/Bayardo98","t7cKx4raSM0J")).
pos(eqo("conf/sigmod/BerchtoldBBKK97","BMkGN7AiGhYJ")).
pos(eqo("conf/sigmod/BerchtoldK97","DNVHTz7tMywJ")).
pos(eqo("conf/sigmod/BertinoCF01","JSzfxAgs4pgJ")).
pos(eqo("conf/sigmod/BlohsfeldKS99","PQbi3PaRh84J")).
pos(eqo("conf/sigmod/BohannonDGKLNS03","83wqw4ciNWoJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","oulaZpEWkMQJ")).
pos(eqo("conf/sigmod/BornhovdAKMPR03","7lPu8hBgKksJ")).
pos(eqo("conf/sigmod/BozkayaO97","gIZvbo_lu2IJ")).
pos(eqo("conf/sigmod/BraumandlKK99","4fjXoCHhe1kJ")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
pos(eqo("conf/sigmod/BreunigKNS00","4ZBs-U7sOk0J")).
pos(eqo("conf/sigmod/BreunigKNS00","8lIwxMfoZN4J")).
pos(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
pos(eqo("conf/sigmod/BrinMS97","41B5NuefLPsJ")).
pos(eqo("conf/sigmod/BrinMS97","OiHYG-Al8G8J")).
pos(eqo("conf/sigmod/BrinMS97","QrVdOEkY844J")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","e4s7pmZj8UAJ")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","qk4kfo7BXvUJ")).
pos(eqo("conf/sigmod/Brown99","itP4yy9sLUUJ")).
pos(eqo("conf/sigmod/BrunoKS02","GahdNMZNCWgJ")).
pos(eqo("conf/sigmod/BryanMCLG94","nbU-wr3ivUIJ")).
pos(eqo("conf/sigmod/BunemanDHS96","Wo7In8pIWJ4J")).
pos(eqo("conf/sigmod/BunemanDHS96","ngbxnQMSWfkJ")).
pos(eqo("conf/sigmod/BunemanDHS96","rNVPCLfguuMJ")).
pos(eqo("conf/sigmod/Bussler01","UYIeOe280OwJ")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/CandanLLHA01","E1oiXxVyfXwJ")).
pos(eqo("conf/sigmod/CandanLLHA01","efYVCK07AwMJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","Y1Z4i3_4l00J")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/ChanI99","kNT7yt823K8J")).
pos(eqo("conf/sigmod/ChanI99","uLiEqn5nA_IJ")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","MNuT46WJZaQJ")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","onlybp6SAAsJ")).
pos(eqo("conf/sigmod/ChangC01","XbmULzOYzZUJ")).
pos(eqo("conf/sigmod/ChaudhuriDY95","aaQEdfkjWN8J")).
pos(eqo("conf/sigmod/ChaudhuriG96","Fh1QPZpWHUMJ")).
pos(eqo("conf/sigmod/ChaudhuriGN02","y461yNb2GEcJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","CBKhTPuUL2kJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","hvMTb3FYOjQJ")).
pos(eqo("conf/sigmod/CherniackZ98","_wJZsVYdrr8J")).
pos(eqo("conf/sigmod/ChristophidesCS00","DJv_OAw-BcIJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","Xssa5A6mJ1UJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","g6fFCiX6GtMJ")).
pos(eqo("conf/sigmod/ChungMS02","2y_G8dmz1QkJ")).
pos(eqo("conf/sigmod/ChungMS02","n8tscFMeBtwJ")).
pos(eqo("conf/sigmod/CluetDSS98","63Y-t4R2RycJ")).
pos(eqo("conf/sigmod/CluetDSS98","VZreOrzvcYEJ")).
pos(eqo("conf/sigmod/CluetDSS98","W5KcKrhKY_YJ")).
pos(eqo("conf/sigmod/ConsensM94","u7rv6LAF8s8J")).
pos(eqo("conf/sigmod/CookWZ94","BYAEfUWtxgUJ")).
pos(eqo("conf/sigmod/DasuJMS02","POt1WbTBB4cJ")).
pos(eqo("conf/sigmod/DasuJMS02","Qywc8AsElxEJ")).
pos(eqo("conf/sigmod/DasuJMS02","zTF5z0v_nh0J")).
pos(eqo("conf/sigmod/DavisonG95","96SrVGnDmMoJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","3PH--zwkZO8J")).
pos(eqo("conf/sigmod/DeolaseeKPRS01","5OTQGZ1gb18J")).
pos(eqo("conf/sigmod/DeolaseeKPRS01","tEFUZn3tEMYJ")).
pos(eqo("conf/sigmod/DeshpandeGR01","0Ta25VSGl7kJ")).
pos(eqo("conf/sigmod/DoRD99","Rviij1nqEcoJ")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
pos(eqo("conf/sigmod/DreyerDS95","i1qU2OFSeloJ")).
pos(eqo("conf/sigmod/Faloutsos95","R0xUZUxSGmwJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","4bG39HmGrAQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","5fCkUaG8A-gJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","bL4szse-iCQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","qaoTK_zX3awJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","XMC0W6CQJJIJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","qsWDIfzBxiQJ")).
pos(eqo("conf/sigmod/Fegaras98","XVtlJYx2G_wJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","N9NHi5y3K38J")).
pos(eqo("conf/sigmod/FernandezFKLS98","RKh78Q-rJLMJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","fNDX0gaFmB0J")).
pos(eqo("conf/sigmod/FernandezFKLS98","rgk1HYJbTNEJ")).
pos(eqo("conf/sigmod/GarofalakisG02","6EaC2CmjsmAJ")).
pos(eqo("conf/sigmod/GarofalakisRRS99","z7J4u1sJ52cJ")).
pos(eqo("conf/sigmod/GibbonsM98","4EgMtIywBRUJ")).
pos(eqo("conf/sigmod/GibbsBT94","6oKFObEbS5oJ")).
pos(eqo("conf/sigmod/GorelikWD94","1QvhrpZ7KBgJ")).
pos(eqo("conf/sigmod/GravanoCGP97","8jTTpoQc2RkJ")).
pos(eqo("conf/sigmod/GravanoCGP97","FHEK09LJKfwJ")).
pos(eqo("conf/sigmod/GravanoCGP97","IVXOHTW5Lt0J")).
pos(eqo("conf/sigmod/GravanoCGP97","hs8rOlHD4K4J")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/GriffinH97","UwOPyY_jchkJ")).
pos(eqo("conf/sigmod/GuptaMR95","2GUwicKtWTUJ")).
pos(eqo("conf/sigmod/HacigumusILM02","NMgExE-JRD0J")).
pos(eqo("conf/sigmod/HammerGNYBV97","FEWg8Ea2CycJ")).
pos(eqo("conf/sigmod/HanKS97","nD_Yjp9TNuIJ")).
pos(eqo("conf/sigmod/HanKS97","yzL3Kfsz8scJ")).
pos(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
pos(eqo("conf/sigmod/HanPDW01","XyYCahzDAh8J")).
pos(eqo("conf/sigmod/HanPLJ01","H_tzR6yoJLEJ")).
pos(eqo("conf/sigmod/HanPY00","2xwKDuA0DI8J")).
pos(eqo("conf/sigmod/HanPY00","63XKDNdtzp8J")).
pos(eqo("conf/sigmod/HanPY00","GlNt7w28aE8J")).
pos(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
pos(eqo("conf/sigmod/HanPY00","mwSZ7Yejt8sJ")).
pos(eqo("conf/sigmod/Hellerstein00","rbluxTXqUQwJ")).
pos(eqo("conf/sigmod/HellersteinA00","iFbXSEmnpzgJ")).
pos(eqo("conf/sigmod/HellersteinN96","5vvOcgfpjUgJ")).
pos(eqo("conf/sigmod/HellersteinN96","_hDCldPyum0J")).
pos(eqo("conf/sigmod/HellersteinN96","vCvPdFwbKWkJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","1H_A7k3QsbQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","CuoOi5jJXxQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","YCP5tWRHS_EJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","cffLplmoKH4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
pos(eqo("conf/sigmod/IvesFFLW99","HwBwuLKlAiEJ")).
pos(eqo("conf/sigmod/JaedickeM98","LrJw7qiWElQJ")).
pos(eqo("conf/sigmod/JaedickeM98","MswqiEweEGUJ")).
pos(eqo("conf/sigmod/JaedickeM98","Py0wIlQRPCkJ")).
pos(eqo("conf/sigmod/Jamil99","z5EfiutEfScJ")).
pos(eqo("conf/sigmod/JoshiA01","H9bMRYKnXMQJ")).
pos(eqo("conf/sigmod/Keim96","AF9vuEJOr6cJ")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","909hLNR8130J")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","DDxRgcJirBMJ")).
pos(eqo("conf/sigmod/KornJF97","ZZUl2Dc1MPsJ")).
pos(eqo("conf/sigmod/KornJF97","atWqYF6LcuwJ")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/KornackerSH98","bV8_CDuW2gMJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","YWzkq7-TA5MJ")).
pos(eqo("conf/sigmod/LacroixSC98","MyaiGcr-oYkJ")).
pos(eqo("conf/sigmod/LazaridisM01","IvMJ4bK708kJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","L854PhEQPTsJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","P25_yh3lBhoJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","4zDGoqCAWOoJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","6jeHlSgjCskJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","8a9NXXE4xiwJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","fOQEOEdh-mcJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","izDXhqRW9AYJ")).
pos(eqo("conf/sigmod/LometW98","QPpUo7m3A7cJ")).
pos(eqo("conf/sigmod/MaddenSHR02","7n7LvbccBZoJ")).
pos(eqo("conf/sigmod/MaddenSHR02","DkgClKWAyEIJ")).
pos(eqo("conf/sigmod/MaddenSHR02","WhBHQqg-7l8J")).
pos(eqo("conf/sigmod/MaddenSHR02","kjtuCATx_uoJ")).
pos(eqo("conf/sigmod/MaddenSHR02","zobnUjtYSe8J")).
pos(eqo("conf/sigmod/MarklL02","b7IXEwTLIHAJ")).
pos(eqo("conf/sigmod/McAuliffeCS96","C0vLucG1HBMJ")).
pos(eqo("conf/sigmod/McAuliffeCS96","c__Nxyn_uvwJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","v2KwhRi-OrMJ")).
pos(eqo("conf/sigmod/MerialdoAMMP00","Qq0WheHyVv8J")).
pos(eqo("conf/sigmod/Miller98","0B1XRTZ8cHkJ")).
pos(eqo("conf/sigmod/Mohan96","14cgU3tAHtgJ")).
pos(eqo("conf/sigmod/Mohan96","JHJ-NMsTtL0J")).
pos(eqo("conf/sigmod/Mohan96","f9JfEpe5a24J")).
pos(eqo("conf/sigmod/Mohan99","XppwYYxOpksJ")).
pos(eqo("conf/sigmod/MoonWH02","rlfxeE4k2p4J")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/NguyenACP01","A57h1N3H3pgJ")).
pos(eqo("conf/sigmod/NguyenACP01","VCiXh8qcrIMJ")).
pos(eqo("conf/sigmod/NguyenS96","Cd4NNuZnIn8J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","5awQcPWFBrcJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","I0KBB-n-eF8J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D280357%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/citation.cfm%3Fid%3D304245%26coll%3Dportal%26dl%3DACM")).
pos(eqo("conf/sigmod/PalmerF00","cnNLe97Pd2sJ")).
pos(eqo("conf/sigmod/PalmerF00","eiA9HVOF2IsJ")).
pos(eqo("conf/sigmod/PapadiasTSE95","oIc_goYCwh4J")).
pos(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","gfRbQIzfux4J")).
pos(eqo("conf/sigmod/PoosalaIHS96","hHGQKstQ2PQJ")).
pos(eqo("conf/sigmod/ProcopiucJAM02","k7RinzPIdhYJ")).
pos(eqo("conf/sigmod/RajagopalanML98","AUR-p53CsK8J")).
pos(eqo("conf/sigmod/RajagopalanML98","M2bWqRDDfkUJ")).
pos(eqo("conf/sigmod/RajagopalanML98","vbi6XDjg0X8J")).
pos(eqo("conf/sigmod/Rajaraman99","m_n55lcmF-sJ")).
pos(eqo("conf/sigmod/RaoBG96","yh6y4XWemYUJ")).
pos(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
pos(eqo("conf/sigmod/RiedewaldAA02","AFKhL1I3L9AJ")).
pos(eqo("conf/sigmod/RodriguezR00","dVDzCb6fuJ0J")).
pos(eqo("conf/sigmod/Ross00","9sm_ptv5pmYJ")).
pos(eqo("conf/sigmod/RossSS96","iurxdvB6oLAJ")).
pos(eqo("conf/sigmod/RundensteinerCLCZNJLW99","SADcQZhMqgEJ")).
pos(eqo("conf/sigmod/SagonasSW94","nDGblldnEGAJ")).
pos(eqo("conf/sigmod/SagonasSW94a","nDGblldnEGAJ")).
pos(eqo("conf/sigmod/SeshadriLR94","60I0j0qUHVYJ")).
pos(eqo("conf/sigmod/SeshadriLR94","G4N8qaBAG4kJ")).
pos(eqo("conf/sigmod/SeshadriLR94","cL_OKIQDvmQJ")).
pos(eqo("conf/sigmod/SeshadriP97","f9POLlECN2gJ")).
pos(eqo("conf/sigmod/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/ShashaB02a","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/ShashaB02a","url:http://portal.acm.org/citation.cfm%3Fid%3D564691.564798%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D564691%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Sheth95","JrkRUbNsLwEJ")).
pos(eqo("conf/sigmod/Sheth95","TuZ-fjos6I0J")).
pos(eqo("conf/sigmod/ShklarSKT95","4IaWCBK6dMQJ")).
pos(eqo("conf/sigmod/SistlaW95","J3XZUbzCxjEJ")).
pos(eqo("conf/sigmod/Spiro98","u4ZAi-DRoHkJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","P8SQPINQRHQJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","kKk4xIJfQ70J")).
pos(eqo("conf/sigmod/Tajima96","IZSzLlgi8tUJ")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","0HlMHEPJRH4J")).
pos(eqo("conf/sigmod/Team02","r5oJTEjlOPgJ")).
pos(eqo("conf/sigmod/TomasicABKNR97","HopegqxaBtoJ")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/WangJLY03","EQsWWZdE45wJ")).
pos(eqo("conf/sigmod/WangPFY03","5JXKbI5l1FYJ")).
pos(eqo("conf/sigmod/WitkowskiBBDFGSS03","ygCe1xRFuKgJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","vwdWTx0dk7QJ")).
pos(eqo("conf/sigmod/WuAA01","Mj5XfzB2Rt8J")).
pos(eqo("conf/sigmod/YerneniLGU99","2MbaeG3IVV0J")).
pos(eqo("conf/sigmod/YerneniLGU99","Gnb52DoKdJwJ")).
pos(eqo("conf/sigmod/YerneniLGU99","L9rzYv5OWpgJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","Pbl_CbLYKWYJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qzxeS4RQAhwJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VAX1F7QPNfsJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VCc6IQulRJ4J")).
pos(eqo("conf/sigmod/ZaianeHLCC98","eauaGLr5uCUJ")).
pos(eqo("conf/sigmod/ZhangRL96","1ms09_UeEH4J")).
pos(eqo("conf/sigmod/ZhangRL96","CcBKCycL0gwJ")).
pos(eqo("conf/sigmod/ZhangRL96","KUGjzt-IgpoJ")).
pos(eqo("conf/sigmod/ZhangRL96","SQ02NlE587YJ")).
pos(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
pos(eqo("conf/sigmod/ZhangRL96","kBlynBey41QJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","mBC03oUT8yAJ")).
pos(eqo("conf/sigmod/ZouS96","DYFIQvOg7rgJ")).
pos(eqo("conf/vldb/AbiteboulABBNM03","TD1X4Bo-eYsJ")).
pos(eqo("conf/vldb/AltinelF00","JhWxdEDCPdUJ")).
pos(eqo("conf/vldb/AltinelF00","onPj3O8mJEAJ")).
pos(eqo("conf/vldb/AmbiteKKMST01","F4DtzxvVZnoJ")).
pos(eqo("conf/vldb/AmielBDS94","1fKcOU28PAEJ")).
pos(eqo("conf/vldb/ArionBCDMP03","CzpCERFYBikJ")).
pos(eqo("conf/vldb/ArionBCDMP03","LIjye8V-mM0J")).
pos(eqo("conf/vldb/AshwinRSSS97","vitgygjdz3AJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/BawaBA03","ZjIllDHwkSoJ")).
pos(eqo("conf/vldb/BawaBA03","bo1rnY4bU4kJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","62aA4DYB0MQJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BohlenSS96","MqokIdCr2oIJ")).
pos(eqo("conf/vldb/BohlenSS96","gcoLSYEk0HIJ")).
pos(eqo("conf/vldb/BridgeJKLLM97","8qlmryXP3BsJ")).
pos(eqo("conf/vldb/BrownCC94","jMku9rPCt9sJ")).
pos(eqo("conf/vldb/BrownCC94","oayI0FKl-nQJ")).
pos(eqo("conf/vldb/BrownG01","aJoPVuDNDSsJ")).
pos(eqo("conf/vldb/Campbell99","m1eeQnYWL0oJ")).
pos(eqo("conf/vldb/CareyD96","5HV8kccLoZ4J")).
pos(eqo("conf/vldb/CareyD96","g8jnRVyQukAJ")).
pos(eqo("conf/vldb/CareyD96","riS5qD1-odUJ")).
pos(eqo("conf/vldb/CareyD96","ulDUAu6vLr4J")).
pos(eqo("conf/vldb/CatozziR95","8ftKLh07LM0J")).
pos(eqo("conf/vldb/ChakrabartiDAR97","2LdUbNy0hWwJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","jNb5aoFeS7wJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChakrabartiGRS00","2TVYDBNYioIJ")).
pos(eqo("conf/vldb/ChakrabartiGRS00","Sd2EpYgsgYEJ")).
pos(eqo("conf/vldb/ChakravarthyKAK94","3M_0Kd8NNjgJ")).
pos(eqo("conf/vldb/ChanGR02","wUcXmf9G52gJ")).
pos(eqo("conf/vldb/ChaudhuriN97","0rViZf2YXmAJ")).
pos(eqo("conf/vldb/ChristopheBPV00","ci71yD2UE8oJ")).
pos(eqo("conf/vldb/ChristopheBPV00","q42RuW4_FogJ")).
pos(eqo("conf/vldb/CiacciaPZ97","FQE6cxYV12kJ")).
pos(eqo("conf/vldb/CiacciaPZ97","cnDPbkX4F2cJ")).
pos(eqo("conf/vldb/CohenMKS03","gRoNHWLN1WMJ")).
pos(eqo("conf/vldb/Dayal99","OoknnZ3rbfwJ")).
pos(eqo("conf/vldb/Dayal99","url:http://portal.acm.org/citation.cfm%3Fid%3D645925.671502")).
pos(eqo("conf/vldb/Deshpande00","2DiLFd0rgPgJ")).
pos(eqo("conf/vldb/DesslochM97","CjtIFow-OWcJ")).
pos(eqo("conf/vldb/DesslochM97","OY4EswVULVcJ")).
pos(eqo("conf/vldb/DiligentiCLGG00","XCP3p-Hk8bMJ")).
pos(eqo("conf/vldb/DoR02","-AsVP3NqvlAJ")).
pos(eqo("conf/vldb/DoR02","0oPfKUylwgEJ")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("conf/vldb/Duranti01","gQW6iYG5Vh0J")).
pos(eqo("conf/vldb/EicklerGK95","63QhLG57QssJ")).
pos(eqo("conf/vldb/Fecteau95","LhjvKpDcJKUJ")).
pos(eqo("conf/vldb/FlodinR95","WmtiDGY_BdoJ")).
pos(eqo("conf/vldb/FlodinR95","b5vbAhJ4xxMJ")).
pos(eqo("conf/vldb/FrohnLU94","xpreqF8k7N4J")).
pos(eqo("conf/vldb/Galindo-LegariaJWW03","znWqWhUfPp8J")).
pos(eqo("conf/vldb/GarofalakisRS99","7BITau8qhpEJ")).
pos(eqo("conf/vldb/GarofalakisRS99","poso7AKokFMJ")).
pos(eqo("conf/vldb/GarofalakisRS99","q87jrCR_GqQJ")).
pos(eqo("conf/vldb/Gentili01","2j1dalv3kCEJ")).
pos(eqo("conf/vldb/GhoshPSH02","2dlOojuSNeIJ")).
pos(eqo("conf/vldb/GoldmanSVG98","b3H6Yt4f7hAJ")).
pos(eqo("conf/vldb/GoldmanSVG98","pweOUtA2iTAJ")).
pos(eqo("conf/vldb/GoldsteinR00","FncQ86sO2agJ")).
pos(eqo("conf/vldb/GoldsteinR00","zydIJyhwgPEJ")).
pos(eqo("conf/vldb/GoodmanRS94","8CCHAKnGJ1EJ")).
pos(eqo("conf/vldb/GuptaM96","I0Kfdt6sh0gJ")).
pos(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
pos(eqo("conf/vldb/HaasKWY97","8Fy6YT12yIgJ")).
pos(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
pos(eqo("conf/vldb/HaasKWY97","ZQG-8D6v7BoJ")).
pos(eqo("conf/vldb/HaasKWY97","aDDbEmg7oYYJ")).
pos(eqo("conf/vldb/HaasKWY97","fsoE2pQM6G8J")).
pos(eqo("conf/vldb/HaasKWY97","olfbrDVhkoYJ")).
pos(eqo("conf/vldb/HaasKWY97","t9e1f-xi0VsJ")).
pos(eqo("conf/vldb/HaasKWY97","yIRQRtTEzSAJ")).
pos(eqo("conf/vldb/HammelP02","SU2XS1MVb40J")).
pos(eqo("conf/vldb/HankinsP03","NsxXW_CvQpkJ")).
pos(eqo("conf/vldb/HeMYW03","cBe5X4EKjIEJ")).
pos(eqo("conf/vldb/HoskingC99","8Pt19BiLeHEJ")).
pos(eqo("conf/vldb/HristidisGP03","B2rShDD99xwJ")).
pos(eqo("conf/vldb/HumborstadSHT97","TjJZGlCajbMJ")).
pos(eqo("conf/vldb/HuntAI01","0GT_dHqK5roJ")).
pos(eqo("conf/vldb/JagadishKMPSS98","0iiNS8BIbsUJ")).
pos(eqo("conf/vldb/JagadishLRSS94","Yiwh22hbTAcJ")).
pos(eqo("conf/vldb/JonscherD94","yv7vyZT9-YEJ")).
pos(eqo("conf/vldb/KamelF94","A7WoAzxOJ9YJ")).
pos(eqo("conf/vldb/KamelF94","ONuqAb6sM3oJ")).
pos(eqo("conf/vldb/KamelF94","SuPC457J-a0J")).
pos(eqo("conf/vldb/KamelF94","b9ey7z1gs2IJ")).
pos(eqo("conf/vldb/KochBG03","mZNcc1O3Nl8J")).
pos(eqo("conf/vldb/KonigW99","6HMffRHCspAJ")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/vldb/KornSFSP96","51VkEWUxxLIJ")).
pos(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
pos(eqo("conf/vldb/KoudasMJ99","dRemTC899xcJ")).
pos(eqo("conf/vldb/KumarKA97","EhTWppk6No8J")).
pos(eqo("conf/vldb/LakshmananPH02","_hNiD_QLDdAJ")).
pos(eqo("conf/vldb/LakshmananSS96","AVyGNVp-ENcJ")).
pos(eqo("conf/vldb/LakshmananSS96","IJyunaAcul8J")).
pos(eqo("conf/vldb/LakshmiZ98","QmXB6EKu-pYJ")).
pos(eqo("conf/vldb/LaneEN00","0O3JgOoSdIUJ")).
pos(eqo("conf/vldb/LeeLWS97","3k61gi_ld_UJ")).
pos(eqo("conf/vldb/LevyRO96","CWzG-HRtqZIJ")).
pos(eqo("conf/vldb/LevyRO96","e_vUPQi8-xIJ")).
pos(eqo("conf/vldb/LevyRO96","lrocSfnfPrMJ")).
pos(eqo("conf/vldb/LevySSZ94","MtScC-fTWCEJ")).
pos(eqo("conf/vldb/Leymann01","eRh9hA637AMJ")).
pos(eqo("conf/vldb/LiCHH97","DmGBKpaiyGEJ")).
pos(eqo("conf/vldb/LiCHPALHAY01","Nn0x6RmkrVwJ")).
pos(eqo("conf/vldb/LubbersGJ03","T3nGiiT3tbsJ")).
pos(eqo("conf/vldb/LudascherMP02","cxnuI54po5EJ")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/MankuM02","swhmRpwl9LQJ")).
pos(eqo("conf/vldb/ManolescuFK01","ckjlnFHOwd8J")).
pos(eqo("conf/vldb/ManolescuFK01","inDI0X1MJG4J")).
pos(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
pos(eqo("conf/vldb/MarronL01","MiMYGwqrGY8J")).
pos(eqo("conf/vldb/MatiasVW00","7SeTnikjovEJ")).
pos(eqo("conf/vldb/MeekPK03","BV6S1LOk4XwJ")).
pos(eqo("conf/vldb/Mina98","6SiX0ZUh1x0J")).
pos(eqo("conf/vldb/Mohan01","6rkYIagTMckJ")).
pos(eqo("conf/vldb/MohanBWSZ00","zCY0pFken7wJ")).
pos(eqo("conf/vldb/MoserKK95","DFZ5hU-q0BIJ")).
pos(eqo("conf/vldb/NathDKGKS03","FirBsg8jxtkJ")).
pos(eqo("conf/vldb/NathDKGKS03","ltxTkDtIbnAJ")).
pos(eqo("conf/vldb/NetzCBF00","mRIRFxOC8A8J")).
pos(eqo("conf/vldb/NicklasGS03","zApMW7wX5-AJ")).
pos(eqo("conf/vldb/Ogawa96","zQDbTpO9kH4J")).
pos(eqo("conf/vldb/OuzzaniAB94","CgoUJ7DogcwJ")).
pos(eqo("conf/vldb/PantiSG00","C7Vuxp5KVsAJ")).
pos(eqo("conf/vldb/PapadimitriouBF03","pAvCmcv_-lMJ")).
pos(eqo("conf/vldb/PedersenJD99","sAUncbolYJ8J")).
pos(eqo("conf/vldb/PereiraFLS00","KAW0nLm2wVAJ")).
pos(eqo("conf/vldb/PereiraFLS00","WvmKiLA-CqMJ")).
pos(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
pos(eqo("conf/vldb/RamaswamyMS98","WTYQ40Rn_tUJ")).
pos(eqo("conf/vldb/RastogiS98","AyWUeJ5k2IoJ")).
pos(eqo("conf/vldb/RastogiS98","yztQfwBZU6EJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","019zSr3Lx4EJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","T2fm7Wb1ak4J")).
pos(eqo("conf/vldb/Sacks-Davis96","GkINzG_IffAJ")).
pos(eqo("conf/vldb/SahuguetA99","Mi0eqxwTUwEJ")).
pos(eqo("conf/vldb/SahuguetA99","PAcS8vELrawJ")).
pos(eqo("conf/vldb/SchaeferBBJ00","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671845")).
pos(eqo("conf/vldb/SchieferKBLF98","1LATgSt5o_EJ")).
pos(eqo("conf/vldb/SchindlerAG03","CsWyDorgQF4J")).
pos(eqo("conf/vldb/SchmidtWKCMB02","SZLkVciImAIJ")).
pos(eqo("conf/vldb/SeifertS02","1VEHUogTMZMJ")).
pos(eqo("conf/vldb/SeshadriLR96","-Pmsximl_moJ")).
pos(eqo("conf/vldb/SeshadriLR96","kyUXzFPXzwIJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GIlUG9H3gUUJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","kaq5eLrzrQsJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
pos(eqo("conf/vldb/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/vldb/ShashaB02","url:http://portal.acm.org/citation.cfm%3Fid%3D564691.564798%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D564691%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/ShengBDM02","ZQdRRjCxEX0J")).
pos(eqo("conf/vldb/Sheth96","xoD5vxZQJ8AJ")).
pos(eqo("conf/vldb/ShethKMWDLPLS96","tKPVyvxSJA8J")).
pos(eqo("conf/vldb/ShuklaDN98","laYa1No1nisJ")).
pos(eqo("conf/vldb/SimonD95","lLARMvKaIQMJ")).
pos(eqo("conf/vldb/TanEO01","bTjeXC-1wf4J")).
pos(eqo("conf/vldb/Toivonen96","tZpeMfkDl8cJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/VieiraM03","sUtdmV9XsIcJ")).
pos(eqo("conf/vldb/WaasCB01","y_gKGtzupHIJ")).
pos(eqo("conf/vldb/WangHH00","qbxHq9qXVrUJ")).
pos(eqo("conf/vldb/WangYM97","hVRj_WzRqI4J")).
pos(eqo("conf/vldb/WangYM97","hcYKj7CHbWYJ")).
pos(eqo("conf/vldb/WiesnerK01","UrDwK2S7QVwJ")).
pos(eqo("conf/vldb/WuFSP00","tr_rawv-6SMJ")).
pos(eqo("conf/vldb/YanA94","OcLgpNTQxIsJ")).
pos(eqo("conf/vldb/YangG01","g8raVwL_ICIJ")).
pos(eqo("conf/vldb/YiF00","DpQrWnvO7rEJ")).
pos(eqo("conf/vldb/ZengBNN01","MA7NWFIgTaoJ")).
pos(eqo("conf/vldb/ZhouR03","MvbChqWgFawJ")).
pos(eqo("conf/vldb/ZimbraoS98","1KckBFVfgyMJ")).
pos(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604274%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637424%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/AndlerHEMBE96","J82SdCmczAcJ")).
pos(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
pos(eqo("journals/sigmod/BarbaraS97","l72i358_vjYJ")).
pos(eqo("journals/sigmod/BernsteinHP00","FFzJxlpy6TsJ")).
pos(eqo("journals/sigmod/BichlerSZ98","goq6Z9bDeSsJ")).
pos(eqo("journals/sigmod/Bohlen95","43K14Y5xa0YJ")).
pos(eqo("journals/sigmod/Bohlen95","LwKKzfi_MpUJ")).
pos(eqo("journals/sigmod/Bohlen95","v5P_NFXdOR8J")).
pos(eqo("journals/sigmod/BonnetBDL03","aovCRhocZUcJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","eKF1zVNKP0gJ")).
pos(eqo("journals/sigmod/CaleroPR03","zWoRcQffsq8J")).
pos(eqo("journals/sigmod/CeriKKLOSV00","nLbW09uNfmsJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","1oCTwvC32jkJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","LROAexi_0UEJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","Tagq11E6HfAJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","d7vY6vDq_7EJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","oahM5itk_dAJ")).
pos(eqo("journals/sigmod/DarwenD95","5Sg1yO3UqawJ")).
pos(eqo("journals/sigmod/DarwenD95","EXwe9r79qxEJ")).
pos(eqo("journals/sigmod/Date03","y4ZZN4xhKnUJ")).
pos(eqo("journals/sigmod/David03","vhUs7wTpUOoJ")).
pos(eqo("journals/sigmod/DogacAOD95","oUOuTMrB0esJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","-aWBDznLsQMJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","vG5FK8BJkZgJ")).
pos(eqo("journals/sigmod/DrewHKKLLLSW95","9fcJjh5vHn8J")).
pos(eqo("journals/sigmod/DunhamH95a","CyzIFxmvc1cJ")).
pos(eqo("journals/sigmod/Eisenberg96","ODNMCIJO6xMJ")).
pos(eqo("journals/sigmod/Eisenberg96","yzlys0OQkt8J")).
pos(eqo("journals/sigmod/FreemanG96","Em3qp7RGalkJ")).
pos(eqo("journals/sigmod/GatziuKBF98","YERfAnxw2RcJ")).
pos(eqo("journals/sigmod/GeppertD94","P9xX0UDXnRcJ")).
pos(eqo("journals/sigmod/GerlaX03","KKiefntReoUJ")).
pos(eqo("journals/sigmod/GobleR02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Grohe02","RnmBv4e85pMJ")).
pos(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
pos(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","_q3scPb8vbgJ")).
pos(eqo("journals/sigmod/HalkidiBV02a","SFs0XOMPphIJ")).
pos(eqo("journals/sigmod/Hampapur99","xW--Ei3c_qwJ")).
pos(eqo("journals/sigmod/Han98","fowjYeJoaxgJ")).
pos(eqo("journals/sigmod/Han98","lwZ7EjZwrZ0J")).
pos(eqo("journals/sigmod/HanBP01","-OEJgpIAScMJ")).
pos(eqo("journals/sigmod/HanBP01","FT5pSUb-uTYJ")).
pos(eqo("journals/sigmod/HasanFV96","m2CCumFeAWgJ")).
pos(eqo("journals/sigmod/Jhingran00","lrGge6mTVckJ")).
pos(eqo("journals/sigmod/KantM00","url:http://portal.acm.org/citation.cfm%3Fid%3D362084.362091%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
pos(eqo("journals/sigmod/KoksalAD98","c2UQ3AM5_f8J")).
pos(eqo("journals/sigmod/KoksalAD98","enYoi4XT7n0J")).
pos(eqo("journals/sigmod/KuanL99","BZfdROjhbhwJ")).
pos(eqo("journals/sigmod/KuanL99","lkrtCULVA6oJ")).
pos(eqo("journals/sigmod/KuokFW98","qyXhN3CrVQ8J")).
pos(eqo("journals/sigmod/LabrinidisM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603886%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LaenderRST02","eQPLe8gg-mIJ")).
pos(eqo("journals/sigmod/LaenderRST02","paQAZ2KXFgAJ")).
pos(eqo("journals/sigmod/LaenderRST02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LeeC00","3kSb_ooS1cgJ")).
pos(eqo("journals/sigmod/Lomet01","fI5o4MfWwzIJ")).
pos(eqo("journals/sigmod/LudascherMM01","16yr6uv8Rn8J")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601879%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MalaikaEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945739%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MattosD94","HhUCea7De6YJ")).
pos(eqo("journals/sigmod/MedskerCS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltzerC98","-wQ-mpGIWdMJ")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NascimentoSP03","G3QWq2T08SEJ")).
pos(eqo("journals/sigmod/NejdlSS03","lZGtV8TM9yoJ")).
pos(eqo("journals/sigmod/ONeilG95","51gKshu0CWcJ")).
pos(eqo("journals/sigmod/ONeilG95","MUXTIMdJLjgJ")).
pos(eqo("journals/sigmod/ONeilG95","ZF4UVaOvyTIJ")).
pos(eqo("journals/sigmod/RafanelliBT96","MfWZUBAVPFUJ")).
pos(eqo("journals/sigmod/RosenthalSMBTL95","-_FyboGgZkkJ")).
pos(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D202672")).
pos(eqo("journals/sigmod/ShethGJRSWW96","ub2wqqQgD40J")).
pos(eqo("journals/sigmod/SilberschatzZ97","7JRwRy6VapMJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","5JA4QR8rxq0J")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","vUONDuuNNCQJ")).
pos(eqo("journals/sigmod/Stirling03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776997%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SycaraKWL99","-IaXJNRxKVEJ")).
pos(eqo("journals/sigmod/SycaraKWL99","CfVOsnm-ebMJ")).
pos(eqo("journals/sigmod/SycaraKWL99","fdruJtO0F0UJ")).
pos(eqo("journals/sigmod/TheodoridisN00","NegSmYlF-awJ")).
pos(eqo("journals/sigmod/VassiliadisS99","uexel5Cdu4wJ")).
pos(eqo("journals/sigmod/WenLMZ03","5KdceadGf8cJ")).
pos(eqo("journals/sigmod/ZobelMR96","6NbNX8nSta0J")).
pos(eqo("journals/tods/BaekgaardM95","6UycFCZooDoJ")).
pos(eqo("journals/tods/BellNNS96","0MteXOu7gzcJ")).
pos(eqo("journals/tods/BeneventanoBS03","rRH6Z1oP78cJ")).
pos(eqo("journals/tods/CasatiCPP99","eD9q5emypy4J")).
pos(eqo("journals/tods/ChenHM95","pO6SFdVGt5QJ")).
pos(eqo("journals/tods/CliffordDIJS97","q9_l2Bqj5y4J")).
pos(eqo("journals/tods/CliffordDIJS97","yPVmmJpyYw4J")).
pos(eqo("journals/tods/DekhtyarRS01","5HstPUbtZ1QJ")).
pos(eqo("journals/tods/DekhtyarRS01","jZShiF9wrikJ")).
pos(eqo("journals/tods/FranklinCL97","vqboZ3T4n4AJ")).
pos(eqo("journals/tods/FraternaliT95","AH97X6QvKJ0J")).
pos(eqo("journals/tods/FraternaliT95","sh-E7oORhVMJ")).
pos(eqo("journals/tods/HjaltasonS99","wjKElSLd3lQJ")).
pos(eqo("journals/tods/KemmeA00","wiUPadLpCvoJ")).
pos(eqo("journals/tods/KorthS94","w40iTKlpWEQJ")).
pos(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
pos(eqo("journals/tods/LiuHD98","ts7DF925TR8J")).
pos(eqo("journals/tods/PetersO97","er0r8doAGUQJ")).
pos(eqo("journals/tods/RosenthalR94","zM422IjZcPgJ")).
pos(eqo("journals/tods/ScioreSR94","fW9j2V5gnUMJ")).
pos(eqo("journals/tods/TaoP03","faqaX7J_Kl8J")).
pos(eqo("journals/tods/WinslettSQ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D195675%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/WolfsonJH97","lcqKNOEczxsJ")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/tods/ZobelMR98","AvV6lMEBGWsJ")).
pos(eqo("journals/tods/ZobelMR98","nX85t01_KugJ")).
pos(eqo("journals/vldb/AgrawalHK03","NDKJPUgy_K4J")).
pos(eqo("journals/vldb/AilamakiDH02","J9MeFW0vDJAJ")).
pos(eqo("journals/vldb/BerendtS00","nm9rCU6yVNwJ")).
pos(eqo("journals/vldb/BohmAnY97","PALTnITURBcJ")).
pos(eqo("journals/vldb/ChanGR03","wUcXmf9G52gJ")).
pos(eqo("journals/vldb/DattaDVRN01","q0Ovw6QUk3MJ")).
pos(eqo("journals/vldb/FahlR97","zXSCJ9LzZ8cJ")).
pos(eqo("journals/vldb/FiletoLPAM03","jMQ_SiixnSEJ")).
pos(eqo("journals/vldb/JiangE98","PjtgP4aQt00J")).
pos(eqo("journals/vldb/LaurentLSV01","TTIgIh9uC_YJ")).
pos(eqo("journals/vldb/MehtaGPN98","7Zf8Y2idDb0J")).
pos(eqo("journals/vldb/MehtaGPN98","xd6denVlP5IJ")).
pos(eqo("journals/vldb/NguSHL01","djYvVVRYNTwJ")).
pos(eqo("journals/vldb/PapadiasS94","_ANyhrnP3CoJ")).
pos(eqo("journals/vldb/PeckhamMD95","zOfVTNgEwz0J")).
pos(eqo("journals/vldb/PucheralBVB01","ci71yD2UE8oJ")).
pos(eqo("journals/vldb/PucheralBVB01","q42RuW4_FogJ")).
pos(eqo("journals/vldb/RamakrishnanSSS94","lH_n19yVmWgJ")).
pos(eqo("journals/vldb/RamamurthyDS03","DAlyofX710AJ")).
pos(eqo("journals/vldb/RamamurthyDS03","uem5wXLoU0wJ")).
pos(eqo("journals/vldb/RoySSSA98","vitgygjdz3AJ")).
pos(eqo("journals/vldb/ShethTP03","Svbxes_XzdUJ")).
pos(eqo("journals/vldb/ShethTP03","tReKvTMB7pcJ")).
pos(eqo("journals/vldb/SuHHHLWLPLL01","IR6h-pIuL8MJ")).
pos(eqo("journals/vldb/SuHHHLWLPLL01","xcRKDHBIUb8J")).
pos(eqo("journals/vldb/TempletonHMB95","RKNGp2gmOTUJ")).
pos(eqo("journals/vldb/TenienteO95","aC-8qspy24wJ")).
pos(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
pos(eqo("journals/vldb/YangW03","Dpj8kCpIfSkJ")).
pos(eqo("journals/vldb/YangW03","IJDg4R1pw6EJ")).
