neg(eqo("conf/sigmod/AbiteboulBCMM03","rDRdlwdHGb0J")).
neg(eqo("conf/sigmod/AbiteboulCM95","HTWrZz969xwJ")).
neg(eqo("conf/sigmod/AdelbergGK95","5I0ArBmDRcEJ")).
neg(eqo("conf/sigmod/AdelbergGK95","mFVZqqx2yfMJ")).
neg(eqo("conf/sigmod/AfratiLU01","k7zpSukSfYsJ")).
neg(eqo("conf/sigmod/Agarwal96","k-JpH9KVizoJ")).
neg(eqo("conf/sigmod/AgrawalASY97","3nxl8d4c0t4J")).
neg(eqo("conf/sigmod/AgrawalES03","e5SJ3zgdwgEJ")).
neg(eqo("conf/sigmod/AgrawalS00","Yt-cq_4cfE8J")).
neg(eqo("conf/sigmod/AgrawalS00","bXnzC8MN_joJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","Ah9B3bWU0jEJ")).
neg(eqo("conf/sigmod/AnkerstBKS99","12xRfc32PXoJ")).
neg(eqo("conf/sigmod/AntonJLPZZ02","89P3EdEDuOEJ")).
neg(eqo("conf/sigmod/Arpaci-DusseauACHP97","pW8HOl_9Q8kJ")).
neg(eqo("conf/sigmod/Atkinson95","thNm2FeulksJ")).
neg(eqo("conf/sigmod/BabcockBDM03","dfSPs7YoyWsJ")).
neg(eqo("conf/sigmod/BabuGR01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D122053%26type%3Dpdf")).
neg(eqo("conf/sigmod/BaruGLMPVC99","RlH2shMtkfwJ")).
neg(eqo("conf/sigmod/Bayardo98","dMRIRjR_KAAJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","DVnOcHunv7MJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","pKKu82IYP9EJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","wyuJkhG9kW8J")).
neg(eqo("conf/sigmod/Blakeley96","t7V6EqtpXhIJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","OcGjVmFfr9kJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","hFnEDWudza8J")).
neg(eqo("conf/sigmod/BohmBKK01","C4XcBh6anhAJ")).
neg(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
neg(eqo("conf/sigmod/BryanMCLG94","asukNMVeZZYJ")).
neg(eqo("conf/sigmod/BuchmannDZH95","A3XUVoFAUc0J")).
neg(eqo("conf/sigmod/CandanLLHA01","E6D-UhwTP_EJ")).
neg(eqo("conf/sigmod/Carey00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Carey94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344819%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/CareyDNAGS97","uugDN9iyMB8J")).
neg(eqo("conf/sigmod/CareyDNAGS97","xc1E6MOfP80J")).
neg(eqo("conf/sigmod/CatarciS94","9nLj99_CwZcJ")).
neg(eqo("conf/sigmod/ChakrabartiDI98","P669YXakS1AJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959067%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Chakravarthy97","V3cZfG1Poo4J")).
neg(eqo("conf/sigmod/ChanI99","kNT7yt823K8J")).
neg(eqo("conf/sigmod/Chaudhuri97","url:http://portal.acm.org/citation.cfm%3Fid%3D244883")).
neg(eqo("conf/sigmod/ChaudhuriG96","H5IdN0_MQw4J")).
neg(eqo("conf/sigmod/ChaudhuriG96","p6zcWuHfGd0J")).
neg(eqo("conf/sigmod/ChaudhuriGN02","WYgQ_Mhdp9sJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","OFGtGwUHhUQJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","xxkUtjfGpvAJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","xAwNq-a4ju0J")).
neg(eqo("conf/sigmod/ChenGM01","aUhrABodKtcJ")).
neg(eqo("conf/sigmod/ClossmanSHKPB98","bKtuLUPjLqYJ")).
neg(eqo("conf/sigmod/CluetDSS98","igcvBI4EBhIJ")).
neg(eqo("conf/sigmod/Cohen98","sKQYWSpYg3sJ")).
neg(eqo("conf/sigmod/ColbyGLMT96","1kGIXDE6G90J")).
neg(eqo("conf/sigmod/ColbyGLMT96","MgphE2z3NqYJ")).
neg(eqo("conf/sigmod/ColbyKLMR97","hs8rOlHD4K4J")).
neg(eqo("conf/sigmod/CorralMTV00","23L2_CggtJkJ")).
neg(eqo("conf/sigmod/CranorGJSS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945727%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/DasGR03","rcSfDxBif40J")).
neg(eqo("conf/sigmod/DavulcuFKR99","hH84bJt5PUcJ")).
neg(eqo("conf/sigmod/DeHaanTCO03","jmTe2JwKfVYJ")).
neg(eqo("conf/sigmod/DeshpandeGR01","mzbabulPonMJ")).
neg(eqo("conf/sigmod/Dietterich94","1Eo8r0HttTUJ")).
neg(eqo("conf/sigmod/DoanDH01","Lv0bggWzgeoJ")).
neg(eqo("conf/sigmod/DogacHKOONDMAKE96","UAO4T_2ylPkJ")).
neg(eqo("conf/sigmod/FaloutsosL95","6gObqDQ3iwoJ")).
neg(eqo("conf/sigmod/FaloutsosSTT00","qsWDIfzBxiQJ")).
neg(eqo("conf/sigmod/FernandezFKLS97","ckrgSn0vBOMJ")).
neg(eqo("conf/sigmod/ForlizziGNS00","qEl7ZsZgAzQJ")).
neg(eqo("conf/sigmod/FranklinJK96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373713%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/FukudaMMT96","cifMTT3UYjQJ")).
neg(eqo("conf/sigmod/Gal00","jPx0tvkJ-fUJ")).
neg(eqo("conf/sigmod/Galhardas00","nlOAkKW_ry8J")).
neg(eqo("conf/sigmod/GangulyGMS96","URBTNMz6sd4J")).
neg(eqo("conf/sigmod/GangulyGR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565119%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GardarinMP95","VOxehNSHEWQJ")).
neg(eqo("conf/sigmod/GebhardtJJ97","D0qof1WXc_UJ")).
neg(eqo("conf/sigmod/GehrkeKS01","tKgGRc2SW8wJ")).
neg(eqo("conf/sigmod/Gerber95","wlxZ0FqTy_MJ")).
neg(eqo("conf/sigmod/GingrasLSPS97","0gKpyKEpyrkJ")).
neg(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
neg(eqo("conf/sigmod/Han96","rsI0sKgJzlsJ")).
neg(eqo("conf/sigmod/HanFHCC94","jQaZA3mmmakJ")).
neg(eqo("conf/sigmod/HanPY00","rqdq3L2hw7UJ")).
neg(eqo("conf/sigmod/Hellerstein00","Vl6qoNo6MhAJ")).
neg(eqo("conf/sigmod/HellersteinA00","ZvAJ8US6e0kJ")).
neg(eqo("conf/sigmod/HjaltasonS98","FH41DtWf_jAJ")).
neg(eqo("conf/sigmod/Hope95","pDZhu54mzewJ")).
neg(eqo("conf/sigmod/HullZ96","7W2mPROkePYJ")).
neg(eqo("conf/sigmod/HullZ96","mmRkNawGf1AJ")).
neg(eqo("conf/sigmod/ImielinskiVB94","IU17L5Il_2EJ")).
neg(eqo("conf/sigmod/Jagadish94","xXD5q6P9u2wJ")).
neg(eqo("conf/sigmod/JagatheesanR03","bqyt1789jJ8J")).
neg(eqo("conf/sigmod/JajodiaSSB97","7VOyoXOOPL4J")).
neg(eqo("conf/sigmod/JajodiaSSB97","s54pMOqTUR8J")).
neg(eqo("conf/sigmod/KanthAS98","LImRBeAtjMQJ")).
neg(eqo("conf/sigmod/KatayamaS97","GPEkH-UohLYJ")).
neg(eqo("conf/sigmod/Keim96","uypnc5Gb9iIJ")).
neg(eqo("conf/sigmod/KiesslingHFE01","D1h_jOHVyA4J")).
neg(eqo("conf/sigmod/KiesslingHFE01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D382400%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Kim94","F90sN5_2R-wJ")).
neg(eqo("conf/sigmod/Kulkarni94","nkW4iN6JqfAJ")).
neg(eqo("conf/sigmod/Kulkarni94","nouEWQwfYaEJ")).
neg(eqo("conf/sigmod/LabioZWGGW97","YemauUgIzlcJ")).
neg(eqo("conf/sigmod/LacroixSC98","z57bXI3FLTEJ")).
neg(eqo("conf/sigmod/LiS98","kxIpDxLD46gJ")).
neg(eqo("conf/sigmod/LiYVGPUV98","JDRDXDHRqpIJ")).
neg(eqo("conf/sigmod/LlirbatFS97","4aSEl4haaq4J")).
neg(eqo("conf/sigmod/MankuRL99","M2bWqRDDfkUJ")).
neg(eqo("conf/sigmod/Martin94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181569%26type%3Dpdf")).
neg(eqo("conf/sigmod/Melling94","c6rl6ppcrM0J")).
neg(eqo("conf/sigmod/Mohan96","f9JfEpe5a24J")).
neg(eqo("conf/sigmod/Mohan99","enYJ_2U2NdUJ")).
neg(eqo("conf/sigmod/Mohan99","pBTSyxiQA04J")).
neg(eqo("conf/sigmod/MohanN94","v5RwghqO86sJ")).
neg(eqo("conf/sigmod/MumickP94","CSZqQQPMXJIJ")).
neg(eqo("conf/sigmod/MumickP94","_uAjDh22Y_EJ")).
neg(eqo("conf/sigmod/MumickP94","fuRZHDk_Xf8J")).
neg(eqo("conf/sigmod/Mylopoulos98","jsJJXMHfgxAJ")).
neg(eqo("conf/sigmod/NguyenACP01","VCiXh8qcrIMJ")).
neg(eqo("conf/sigmod/NybergBCGL94","AaKiSc1klw8J")).
neg(eqo("conf/sigmod/OoiTZGLLLNSWZ03","tsqBH6P4jMcJ")).
neg(eqo("conf/sigmod/OriaOILY00","VefrIRnp95EJ")).
neg(eqo("conf/sigmod/Ozsu99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507340%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/PadmanabhanBMCH03","oWVdOJS4pDQJ")).
neg(eqo("conf/sigmod/PalmerF00","cnNLe97Pd2sJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","WTYQ40Rn_tUJ")).
neg(eqo("conf/sigmod/PatelD96","5HV8kccLoZ4J")).
neg(eqo("conf/sigmod/PonnekantiK00","1ryTVhXVMbsJ")).
neg(eqo("conf/sigmod/RamanH02","PoVkG8nD28IJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","S_jh-ZtVr08J")).
neg(eqo("conf/sigmod/RiedewaldAA02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344819%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Ross00","WbsAK4ZE17YJ")).
neg(eqo("conf/sigmod/RoussopoulosKV95","1WSTXNtfwJEJ")).
neg(eqo("conf/sigmod/RundensteinerKRCJM96","F9xcVC8QkpgJ")).
neg(eqo("conf/sigmod/Sahuguet01","iyQ4mc1VaA0J")).
neg(eqo("conf/sigmod/SaltenisJLL00","Klh7nU-G4-IJ")).
neg(eqo("conf/sigmod/Sarawagi00","eDaLc3S11YQJ")).
neg(eqo("conf/sigmod/SarawagiTA98","ggwMY-elIJwJ")).
neg(eqo("conf/sigmod/SarawagiTA98","ut4Y99B1094J")).
neg(eqo("conf/sigmod/SelfridgeSW96","pBKI-JCAlcIJ")).
neg(eqo("conf/sigmod/SelfridgeSW96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141405%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SengarH03","QyNfyYDySawJ")).
neg(eqo("conf/sigmod/Seshadri03","ypHBb35DGMgJ")).
neg(eqo("conf/sigmod/SeshadriP97","bEu_llku9NMJ")).
neg(eqo("conf/sigmod/ShatdalN95","Kzhu2DS1g2oJ")).
neg(eqo("conf/sigmod/ShenNSHS03","BZwHppfVN6kJ")).
neg(eqo("conf/sigmod/Shyy95","QESb6yoM8zEJ")).
neg(eqo("conf/sigmod/SistlaW95","4TMZhO1wdwsJ")).
neg(eqo("conf/sigmod/SistlaW95","pO6SFdVGt5QJ")).
neg(eqo("conf/sigmod/Stonebraker98","f5l7pBBr8foJ")).
neg(eqo("conf/sigmod/SunAA03","4yAAL7d2ePcJ")).
neg(eqo("conf/sigmod/SunAA03","7rgJu4BiChMJ")).
neg(eqo("conf/sigmod/TatarinovVBSSZ02","-jtu5QeiAKQJ")).
neg(eqo("conf/sigmod/Team95","QhiXXIHGhO8J")).
neg(eqo("conf/sigmod/Team95b","R2Gt4i2NsJ0J")).
neg(eqo("conf/sigmod/Team95c","pb4lxjPEBAIJ")).
neg(eqo("conf/sigmod/TheobaldW02","bfdZNz7ylx8J")).
neg(eqo("conf/sigmod/TrisoliniLN99","bLbjFFkQJdIJ")).
neg(eqo("conf/sigmod/TrisoliniLN99","k6ukzru4nX8J")).
neg(eqo("conf/sigmod/VanceM96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Weininger02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234900%26type%3Dpdf%26dl%3DGUIDE%26dl%3Dacm%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/WynblattN01","DPFUcTTFffYJ")).
neg(eqo("conf/sigmod/ZhangRL96","GmUD1o-uPvYJ")).
neg(eqo("conf/sigmod/ZhuS03","5FiyBEZ3v70J")).
neg(eqo("conf/sigmod/ZhuS03","QZs7L6Y94_UJ")).
neg(eqo("conf/vldb/AbiteboulABBNM03","7P1LlDStRGYJ")).
neg(eqo("conf/vldb/AbrolLMMMRTWZ01","VNILDnv9jmsJ")).
neg(eqo("conf/vldb/AcharyaFZ96","4AK08s31YqUJ")).
neg(eqo("conf/vldb/AdityaBCHNS02","Px4JslMPzwcJ")).
neg(eqo("conf/vldb/AggarwalHWY03","oUeII_zjHGAJ")).
neg(eqo("conf/vldb/AgrawalPWZ95","hO_7MgcawQ4J")).
neg(eqo("conf/vldb/AgrawalS94","WkXM8o_flrEJ")).
neg(eqo("conf/vldb/AgrawalS94","Yt-cq_4cfE8J")).
neg(eqo("conf/vldb/AgrawalS94","tINnZsjIUnwJ")).
neg(eqo("conf/vldb/AgrawalSX01","I-taeStropMJ")).
neg(eqo("conf/vldb/AgrawalSX02","gW1x2XGs6R8J")).
neg(eqo("conf/vldb/AgrawalSX02","kGcI8UNjcdgJ")).
neg(eqo("conf/vldb/AltinelBKMPR03","s3bawcAka-EJ")).
neg(eqo("conf/vldb/Amer-YahiaFSX03","fcB_7jx0pOMJ")).
neg(eqo("conf/vldb/BalminHKPSW03","8xRHvInl0_0J")).
neg(eqo("conf/vldb/BamfordBKM98","-GRrUCy3o2YJ")).
neg(eqo("conf/vldb/BaulierBKS98","-Hj9egalPJIJ")).
neg(eqo("conf/vldb/BaumannDFRW99","9efgMwFj1PkJ")).
neg(eqo("conf/vldb/Bayer95","_zHAz0-byccJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","lQnI0zKr5kYJ")).
neg(eqo("conf/vldb/BlottK02","xsh0C_nCllsJ")).
neg(eqo("conf/vldb/BlottKS98","_UFApxXRMvUJ")).
neg(eqo("conf/vldb/Blum99","PrGxSioaOcIJ")).
neg(eqo("conf/vldb/BohannonLRSSS97","RRXxf-M6DpYJ")).
neg(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
neg(eqo("conf/vldb/BridgeJKLLM97","iyHWaC-OBo0J")).
neg(eqo("conf/vldb/Brin95","uSUjB2k7b2wJ")).
neg(eqo("conf/vldb/Brin95","ytOUXklnAooJ")).
neg(eqo("conf/vldb/BrodieC99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066184%26type%3Dpdf")).
neg(eqo("conf/vldb/Campbell99","0ZXZVWpZNmkJ")).
neg(eqo("conf/vldb/CareyD96","4mE3qkyUHnUJ")).
neg(eqo("conf/vldb/CareyD96","vF-KpOq9TdIJ")).
neg(eqo("conf/vldb/CarinoJ98","MPOaM5dta1sJ")).
neg(eqo("conf/vldb/ChakrabartiRS02","ksMnxMtMViQJ")).
neg(eqo("conf/vldb/ChakravarthyKAK94","GsYRviPBlHcJ")).
neg(eqo("conf/vldb/ChanFFGR02","ZFI7XBuonJAJ")).
neg(eqo("conf/vldb/ChanGR02","kBzZ1GUoa1AJ")).
neg(eqo("conf/vldb/ChatziantoniouR97","Xx-pSjq7Mv8J")).
neg(eqo("conf/vldb/ChaudhuriG99","i8bNEKiFihYJ")).
neg(eqo("conf/vldb/ChaudhuriG99","qGTxTpQXTDsJ")).
neg(eqo("conf/vldb/ChaudhuriN97","JyEX0YVMP5oJ")).
neg(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
neg(eqo("conf/vldb/Chawathe99","HiM9HOUxq0MJ")).
neg(eqo("conf/vldb/ChirkovaHS01","f71CYhhk2RAJ")).
neg(eqo("conf/vldb/ChoN02","Nc1LMx13TAgJ")).
neg(eqo("conf/vldb/DattaDTVRF01","_RyWKB28b6oJ")).
neg(eqo("conf/vldb/DeutschPT99","MBqESPQVqs4J")).
neg(eqo("conf/vldb/EvangelidisLS95","EbGZKQPyH_4J")).
neg(eqo("conf/vldb/FaloutsosG96","qnQocRrApa4J")).
neg(eqo("conf/vldb/FegarasE01","pinPEM3Rvm0J")).
neg(eqo("conf/vldb/FukudaMMT96","TipUJPJMxOsJ")).
neg(eqo("conf/vldb/Galindo-LegariaJWW03","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/GallersdorferN95","8j5i7YJQnNAJ")).
neg(eqo("conf/vldb/GarciaLL98","NGmfDUfEgLwJ")).
neg(eqo("conf/vldb/GardarinGT96","icaXiCp7dF8J")).
neg(eqo("conf/vldb/GarofalakisG01","6EaC2CmjsmAJ")).
neg(eqo("conf/vldb/GarofalakisRS99","Xm3ygCvkmN8J")).
neg(eqo("conf/vldb/Gentili01","KuYNNvJtkeMJ")).
neg(eqo("conf/vldb/GolabO03","k2LFZSt_NcoJ")).
neg(eqo("conf/vldb/Guting94","b7MAEGL1CnUJ")).
neg(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
neg(eqo("conf/vldb/HaasKU99","YoA_wrlqXRcJ")).
neg(eqo("conf/vldb/Hammond96","LDxiVdRU6EEJ")).
neg(eqo("conf/vldb/HasanM95","-aml_OMAQNgJ")).
neg(eqo("conf/vldb/HasanM95","qy81IQ6F3MsJ")).
neg(eqo("conf/vldb/HellersteinNP95","UwOgoqlmVyoJ")).
neg(eqo("conf/vldb/HelmerNM03","FBT3TKOs5KQJ")).
neg(eqo("conf/vldb/HelmerWM98","CvGGYMrKR2sJ")).
neg(eqo("conf/vldb/HinneburgAK00","7v3f7Thmyw0J")).
neg(eqo("conf/vldb/HoelS94","1KckBFVfgyMJ")).
neg(eqo("conf/vldb/HristidisGP03","5k-GwvznWRUJ")).
neg(eqo("conf/vldb/HvasshovdBT00","vrxbzlpOiDAJ")).
neg(eqo("conf/vldb/Ioannidis03","u5LuBw2MsTYJ")).
neg(eqo("conf/vldb/JaedickeM99","LrJw7qiWElQJ")).
neg(eqo("conf/vldb/JagadishKMPSS98","0TmcLmakam0J")).
neg(eqo("conf/vldb/JagadishNSSK97","FzUYum7hqhQJ")).
neg(eqo("conf/vldb/JagadishNSSK97","UByN6paxEXwJ")).
neg(eqo("conf/vldb/JoshiBLL98","RufEbUPZNbYJ")).
neg(eqo("conf/vldb/KaushikBNS02","AhsHHld2KNYJ")).
neg(eqo("conf/vldb/KemperKW99","DfOLEzMoEaEJ")).
neg(eqo("conf/vldb/KonigW99","DnuTLLUbjWIJ")).
neg(eqo("conf/vldb/KonigW99","K0aOFYBWg3AJ")).
neg(eqo("conf/vldb/LabrinidisR01","3Ozte0ucNJAJ")).
neg(eqo("conf/vldb/Ladin00","Qp9jtkepF_8J")).
neg(eqo("conf/vldb/LakshmananPZ03","7Xoa7OiZLXMJ")).
neg(eqo("conf/vldb/LakshmananSS96","Xg5igdb3e4cJ")).
neg(eqo("conf/vldb/LakshmiZ98","j8KDWCTJN7AJ")).
neg(eqo("conf/vldb/LeeHJT03","Ft52Yx9kdnMJ")).
neg(eqo("conf/vldb/LeeL96","iFsr76th3iYJ")).
neg(eqo("conf/vldb/LeslieJBY95","UkIG8p5eCSsJ")).
neg(eqo("conf/vldb/LeslieJBY95","izKt_V3BxfoJ")).
neg(eqo("conf/vldb/Levy96","o_i4jWzc-zcJ")).
neg(eqo("conf/vldb/LifantsevC02","url:http://www.springerlink.com/index/1G697MXTU3M9MPL4.pdf")).
neg(eqo("conf/vldb/LimWV03","F14Ab4viu0MJ")).
neg(eqo("conf/vldb/LingLL00","2jTxT5mldPUJ")).
neg(eqo("conf/vldb/LuL00","c92hfzTG4RIJ")).
neg(eqo("conf/vldb/LudasaherGM00","HWFnrGXJ6IIJ")).
neg(eqo("conf/vldb/MadhavanBR01","2f7-ISogcpcJ")).
neg(eqo("conf/vldb/Madnick95","x3kLSd1FahoJ")).
neg(eqo("conf/vldb/MaedaT01","DX9x2eUPfHMJ")).
neg(eqo("conf/vldb/ManegoldBK02","sX5VObgm1aIJ")).
neg(eqo("conf/vldb/ManolescuFK01","OkCz_NK5cbMJ")).
neg(eqo("conf/vldb/ManolescuFK01","inDI0X1MJG4J")).
neg(eqo("conf/vldb/MaratheS97","dm3xutmyi_0J")).
neg(eqo("conf/vldb/MarronL01","1VEHUogTMZMJ")).
neg(eqo("conf/vldb/May01","nTK1ViJDYOcJ")).
neg(eqo("conf/vldb/McHughW99","51jDHTpl3HUJ")).
neg(eqo("conf/vldb/McHughW99","w91icO7E4noJ")).
neg(eqo("conf/vldb/MendelzonV00","ZFI7XBuonJAJ")).
neg(eqo("conf/vldb/MengLYWCR98","4weou-KgkM8J")).
neg(eqo("conf/vldb/MignetMAC01","3RDOeV-H7dkJ")).
neg(eqo("conf/vldb/MiloZ98","pVPYozcw2JoJ")).
neg(eqo("conf/vldb/Moerkotte98","Ih9F-nsUAVoJ")).
neg(eqo("conf/vldb/Mohan02a","ml-oFmPRY6AJ")).
neg(eqo("conf/vldb/Mohan02a","uCNkDoBniLgJ")).
neg(eqo("conf/vldb/MohaniaS94","1bBjnX0qrokJ")).
neg(eqo("conf/vldb/MorimotoIM97","-gQb5oEVQgYJ")).
neg(eqo("conf/vldb/MuthOPW98","Pa_ObVyi9TcJ")).
neg(eqo("conf/vldb/NicklasGS03","mJDpJQy22wwJ")).
neg(eqo("conf/vldb/Objectivity98","hrnqGMr9dXQJ")).
neg(eqo("conf/vldb/OhuraTPK02","ezYQT2_lJE8J")).
neg(eqo("conf/vldb/OoiYTJ01","3_uBZEm9dqAJ")).
neg(eqo("conf/vldb/PapadiasT01","531XkRrvqi8J")).
neg(eqo("conf/vldb/PapadiasT01","7ZyV9ivZySQJ")).
neg(eqo("conf/vldb/PoulovassilisS94","iCx1t8U5Y-gJ")).
neg(eqo("conf/vldb/RaghavanG03","GRQAnSkTZJ4J")).
neg(eqo("conf/vldb/RamakrishnanGRSWZ95","JFpnzAy3q7YJ")).
neg(eqo("conf/vldb/RamaswamyMS98","JvkYLFlA11cJ")).
neg(eqo("conf/vldb/RastogiS98","TFJDVDzs8-4J")).
neg(eqo("conf/vldb/SarawagiS96","GzBmx-QUxFYJ")).
neg(eqo("conf/vldb/ScheuermannSV96","TCAOiofZaFIJ")).
neg(eqo("conf/vldb/Schnase00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369277%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/SeidlK97","dBgA1e-6LvkJ")).
neg(eqo("conf/vldb/SeligmanBNSW95","01ZVDudF4WAJ")).
neg(eqo("conf/vldb/ShahDR03","Koo3549nY2kJ")).
neg(eqo("conf/vldb/ShahDR03","Zlk6Tn-sPxwJ")).
neg(eqo("conf/vldb/ShanmugasundaramKSFF01","nlh2WXZT3VIJ")).
neg(eqo("conf/vldb/Sheth96","ULJo4TD7B64J")).
neg(eqo("conf/vldb/SistlaYH94","tZBIZ9ZHdTkJ")).
neg(eqo("conf/vldb/SkubiszewskiV97","MJAw_2C6ErAJ")).
neg(eqo("conf/vldb/SkubiszewskiV97","pI2wFuoVRogJ")).
neg(eqo("conf/vldb/SrinivasaK03","KJ8d3evJm4oJ")).
neg(eqo("conf/vldb/StillgerLMK01","R43ssyRp674J")).
neg(eqo("conf/vldb/Suciu96","yysPPwId4XUJ")).
neg(eqo("conf/vldb/Suciu96a","tJtSq968rwgJ")).
neg(eqo("conf/vldb/Sullivan96","DKqzidwcAckJ")).
neg(eqo("conf/vldb/Sullivan96","fh16m_sffh4J")).
neg(eqo("conf/vldb/SumiyaYTSI95","eU3s0mVurJQJ")).
neg(eqo("conf/vldb/TorloneA03","m7WdGieTDYoJ")).
neg(eqo("conf/vldb/UrhanF01","f3Yp3CD3ipIJ")).
neg(eqo("conf/vldb/Wadler01","tY52PzLqN9oJ")).
neg(eqo("conf/vldb/WangHH00","f0T2bBwZ4NgJ")).
neg(eqo("conf/vldb/WangYM97","RiOvjzg_MJwJ")).
neg(eqo("conf/vldb/WuFSP00","XojbAfbtdvcJ")).
neg(eqo("conf/vldb/YuPM03","Td2l0X7TzH4J")).
neg(eqo("conf/vldb/YuPM03","ZEEZqsnVCyYJ")).
neg(eqo("conf/vldb/ZhouLZLZJT01","ywqM_Qst4qIJ")).
neg(eqo("conf/vldb/ZimbraoS98","PcadhxjbWhcJ")).
neg(eqo("conf/vldb/ZirintsisKM99","0-G78ioxas0J")).
neg(eqo("journals/sigmod/Aberer01","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/08830355/2001/00000035/00000002/art00018%26unc%3D")).
neg(eqo("journals/sigmod/Aberer03c","DJpFoidxWGMJ")).
neg(eqo("journals/sigmod/Aberer03d","WryeHhngM_oJ")).
neg(eqo("journals/sigmod/AdelbergKG96","D1h_jOHVyA4J")).
neg(eqo("journals/sigmod/AdelbergKG96","NhNwtkE4jFEJ")).
neg(eqo("journals/sigmod/ArpinarD00","5LlePa4wQmEJ")).
neg(eqo("journals/sigmod/ArpinarD00","Fm-NyVW9BqUJ")).
neg(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959085%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BoulosO99","url:http://adsabs.harvard.edu/abs/1976scom.nasa..840B")).
neg(eqo("journals/sigmod/BunemanRU97","ZTBiopwBpLgJ")).
neg(eqo("journals/sigmod/CabreraLM01","IoNxL_rg2_cJ")).
neg(eqo("journals/sigmod/CalvaneseGLV03","y2uZPpBjpjQJ")).
neg(eqo("journals/sigmod/Cardelli01","gtWXcs-6QzwJ")).
neg(eqo("journals/sigmod/Cetintemel01","biVrK7MrU4QJ")).
neg(eqo("journals/sigmod/Chen94","_q3scPb8vbgJ")).
neg(eqo("journals/sigmod/ChristoffelPSL98","W-dtWIGKQHcJ")).
neg(eqo("journals/sigmod/ClementiniF00","muQ-GWyFr2kJ")).
neg(eqo("journals/sigmod/Colliat96","RR-e0fkaniQJ")).
neg(eqo("journals/sigmod/ConradHHKRSS99","zJCsqgMH5bUJ")).
neg(eqo("journals/sigmod/DadamK97","XCdMiXLp41IJ")).
neg(eqo("journals/sigmod/David03","UTe8b9IiclUJ")).
neg(eqo("journals/sigmod/DiazJPa94","DXTczW8Dv4MJ")).
neg(eqo("journals/sigmod/DogacDATKCD98","H9bMRYKnXMQJ")).
neg(eqo("journals/sigmod/DogacDKOONEHAKKM95","i2LI1TWifbYJ")).
neg(eqo("journals/sigmod/DrewHKKLLLSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1024703%26type%3Dpdf")).
neg(eqo("journals/sigmod/EisenbergM02","Z1P9QnSfDuAJ")).
neg(eqo("journals/sigmod/EisenbergM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637435%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/EisenbergM99a","Z1P9QnSfDuAJ")).
neg(eqo("journals/sigmod/ErdurD02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603869%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Fong95","5k09A_rw8gcJ")).
neg(eqo("journals/sigmod/Franklin00","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin00a","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin97","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin97a","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin99","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin99","j3NIm0w0xA8J")).
neg(eqo("journals/sigmod/Franklin99a","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin99b","uexel5Cdu4wJ")).
neg(eqo("journals/sigmod/Gallagher94","7klHysbpdGwJ")).
neg(eqo("journals/sigmod/Geller02","dvfHVLLZo4MJ")).
neg(eqo("journals/sigmod/GottlobKP03","lmLjPf_m6jwJ")).
neg(eqo("journals/sigmod/GottlobKP03a","rDRdlwdHGb0J")).
neg(eqo("journals/sigmod/GottlobKP03a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776989%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Grohe02","B1F0Sv4j0zUJ")).
neg(eqo("journals/sigmod/GroskyFS94","Ryxayh3KcicJ")).
neg(eqo("journals/sigmod/Halevy03","sbKE5wvqQcsJ")).
neg(eqo("journals/sigmod/Han98","6YKL7sQWHgUJ")).
neg(eqo("journals/sigmod/Han98","bCp4rxObjCsJ")).
neg(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
neg(eqo("journals/sigmod/KannanKIK03","url:http://www.springerlink.com/index/J28W1152150707L7.pdf")).
neg(eqo("journals/sigmod/Keim96","9fd2xnY-CUYJ")).
neg(eqo("journals/sigmod/Kim99","url:http://portal.acm.org/citation.cfm%3Fid%3D202106.569784%26coll%3Dportal%26dl%3DACM%26idx%3DJ777%26part%3Dtransaction%26WantType%3Dtransaction%26title%3DACM%2520Transactions%2520on%2520Database%2520Systems%2520(TODS)%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/KuokFW98","21ZWY0PM8YAJ")).
neg(eqo("journals/sigmod/LabrinidisR00","DKUouEkK_b4J")).
neg(eqo("journals/sigmod/Ley00","url:http://journals.cambridge.org/action/displayFulltext%3Ftype%3D1%26fid%3D328165%26jid%3DUHY%26volumeId%3D32%26issueId%3D01%26aid%3D328164")).
neg(eqo("journals/sigmod/Libkin99a","GbuDRP9YYosJ")).
neg(eqo("journals/sigmod/Liu01a","5l2xUevEqhQJ")).
neg(eqo("journals/sigmod/Liu01a","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/Liu01a","KOEjbYynxl4J")).
neg(eqo("journals/sigmod/Liu01a","url:http://doi.wiley.com/10.1002/ace.53")).
neg(eqo("journals/sigmod/Liu02","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/Liu02a","HFGeD6kSIj4J")).
neg(eqo("journals/sigmod/Liu03","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/MalaikaEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601877%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MattosD94","bi68bm0miqkJ")).
neg(eqo("journals/sigmod/MedeirosP94","tnHDLJxMoQcJ")).
neg(eqo("journals/sigmod/MedskerCS95","O11wyIuGkoUJ")).
neg(eqo("journals/sigmod/MedskerCS95","WGv9zvnJ484J")).
neg(eqo("journals/sigmod/MedskerCS95","bs5PBKZy8QIJ")).
neg(eqo("journals/sigmod/MedskerCS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MeersmanS02","HbD44tqn70oJ")).
neg(eqo("journals/sigmod/MeersmanS02","N4nyJ3C99iMJ")).
neg(eqo("journals/sigmod/NorrieBSW94","ehYH-uHKKh4J")).
neg(eqo("journals/sigmod/OrlandicLS02","CUwratNa5rIJ")).
neg(eqo("journals/sigmod/Ozsu01","ohDewW00evcJ")).
neg(eqo("journals/sigmod/Ozsu02b","NN6yHiDFy4gJ")).
neg(eqo("journals/sigmod/PhatakSSS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381897%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian94a","Tolsoq0vIZMJ")).
neg(eqo("journals/sigmod/Qian95b","qedtE3Ujgd8J")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/citation.cfm%3Fid%3D248603.248618%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RamanathanH97","szwhpIF7vzkJ")).
neg(eqo("journals/sigmod/RossAJS02","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/RossAKSSY00","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/RossCGLLM01","BObJe9_6k0QJ")).
neg(eqo("journals/sigmod/RossCGLLM01","Ho67rkmdkQAJ")).
neg(eqo("journals/sigmod/RossHLW01","8o94HRMWbawJ")).
neg(eqo("journals/sigmod/RossNO03","ki6h8TZDRb4J")).
neg(eqo("journals/sigmod/Roussopoulos98","AbEa8UYjz6sJ")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","EdvdFgHsNCIJ")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","vwdWTx0dk7QJ")).
neg(eqo("journals/sigmod/SellisV95","J1CLaoEhUTwJ")).
neg(eqo("journals/sigmod/ShanmugasundaramSKKVNT01","4SF7XOBwsO4J")).
neg(eqo("journals/sigmod/ShanmugasundaramSKKVNT01","QOf55i6m6bUJ")).
neg(eqo("journals/sigmod/Sidell96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245906%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SilberschatzSU96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083748%26type%3Dpdf")).
neg(eqo("journals/sigmod/SlivinskasJS02","wF_GdZPkCnQJ")).
neg(eqo("journals/sigmod/Snodgrass02","cYLujHNwTTIJ")).
neg(eqo("journals/sigmod/Snodgrass02b","PmIVKWJ5_V4J")).
neg(eqo("journals/sigmod/Snodgrass02b","xT3mwY4t5kEJ")).
neg(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","XvKzOSXKGKUJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","47NSh5f6ox0J")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/StolfoLCFE01","RcrzvORoBc0J")).
neg(eqo("journals/sigmod/StolfoLCFE01","RgwmAixOp2AJ")).
neg(eqo("journals/sigmod/Stonebraker02","krlEX4LgXKIJ")).
neg(eqo("journals/sigmod/Stonebraker02","url:http://portal.acm.org/citation.cfm%3Fid%3D181551")).
neg(eqo("journals/sigmod/Suciu97","JxP-0xYMRUMJ")).
neg(eqo("journals/sigmod/SycaraKWL99","CfVOsnm-ebMJ")).
neg(eqo("journals/sigmod/TomasicS97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Ulusoy95","jvBTdbArrvkJ")).
neg(eqo("journals/sigmod/Widom95","url:http://portal.acm.org/citation.cfm%3Fid%3D233269%26dl%3DGUIDE%26dl%3DGUIDE%26type%3Dproceeding%26idx%3D233269%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom95a","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Winslett02a","hZOXZJ6x2xUJ")).
neg(eqo("journals/sigmod/Winslett02c","LNsWSlqILosJ")).
neg(eqo("journals/sigmod/Winslett94","sfQlMM3SXpAJ")).
neg(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
neg(eqo("journals/sigmod/X95a","To_EjIKwfSAJ")).
neg(eqo("journals/sigmod/X95a","bjtnGkW6L3kJ")).
neg(eqo("journals/sigmod/YeungHL94","pYELgNwS9z8J")).
neg(eqo("journals/tods/BaekgaardM95","url:http://portal.acm.org/citation.cfm%3Fid%3D1099554.1099626")).
neg(eqo("journals/tods/BohlenJS00","kiSzv2QyaAsJ")).
neg(eqo("journals/tods/BozkayaO99","c1i5HNdPOycJ")).
neg(eqo("journals/tods/BunemanO96","wH4tTEsgq58J")).
neg(eqo("journals/tods/CaldersNW02","RBk9oyDN9twJ")).
neg(eqo("journals/tods/CeriFPT94","goxkHU_NxnIJ")).
neg(eqo("journals/tods/CeriFPT94","xhOs8MMbLYMJ")).
neg(eqo("journals/tods/ChaudhuriS99","dtYwk-vb8DUJ")).
neg(eqo("journals/tods/ChoG03","s7K6rICx3fkJ")).
neg(eqo("journals/tods/CliffordDIJS97","aKPlDMXvHT8J")).
neg(eqo("journals/tods/EiterGM97","WXWcO2ulDQUJ")).
neg(eqo("journals/tods/KossmannFDA00","3Zt_PGo66c0J")).
neg(eqo("journals/tods/KossmannS00","PnGVbzQCWY0J")).
neg(eqo("journals/tods/KotidisR01","cOpfIBarLD0J")).
neg(eqo("journals/tods/Kuo96","p--jtVlva8AJ")).
neg(eqo("journals/tods/LakshmananLN03","PsXOoGuK0ogJ")).
neg(eqo("journals/tods/LitwinN96","ffkXKk8Hkt0J")).
neg(eqo("journals/tods/MayL02","FtWc55hx6LkJ")).
neg(eqo("journals/tods/MelnikG03","ZgFbf36-6OMJ")).
neg(eqo("journals/tods/Meo00","pPc_DDbX4VsJ")).
neg(eqo("journals/tods/MokNE96","YiAXPnIRAecJ")).
neg(eqo("journals/tods/Ng01","c1HLn78WvnUJ")).
neg(eqo("journals/tods/OliverS94","JgxX-Rlwcx0J")).
neg(eqo("journals/tods/PetersO97","zFgXEbLuJWIJ")).
neg(eqo("journals/tods/PolyzoisG94","poy1S5NG21AJ")).
neg(eqo("journals/tods/Suciu02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066303%26type%3Dpdf")).
neg(eqo("journals/tods/TaoP03","faqaX7J_Kl8J")).
neg(eqo("journals/vldb/AbadiCCCCLSTZ03","gBVNSFeS4P8J")).
neg(eqo("journals/vldb/AbbadiSW01","KX9tZqfLvrgJ")).
neg(eqo("journals/vldb/AbbadiSW01","N4nyJ3C99iMJ")).
neg(eqo("journals/vldb/AbiteboulCM98","WzT3S2G1FjcJ")).
neg(eqo("journals/vldb/AilamakiDH02","hRToevpkaa0J")).
neg(eqo("journals/vldb/AntoshenkovZ96","Zke78tzeDPUJ")).
neg(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/H58452Q268H44281.pdf")).
neg(eqo("journals/vldb/Barbara-MillaG94","N_XZCQemnDsJ")).
neg(eqo("journals/vldb/BarbaraI95","bMUUwjP72hwJ")).
neg(eqo("journals/vldb/BerchtoldKK97","vrlNTuVexE4J")).
neg(eqo("journals/vldb/BernsteinIR03","347oyb_b7DAJ")).
neg(eqo("journals/vldb/Bertino94","YK8K5uWmNcAJ")).
neg(eqo("journals/vldb/Bertino94","iyHWaC-OBo0J")).
neg(eqo("journals/vldb/BraumandlCKK00","DJiyWg5SpgAJ")).
neg(eqo("journals/vldb/C95a","QLeWwLgl5KsJ")).
neg(eqo("journals/vldb/C95c","cuBgKEsClakJ")).
neg(eqo("journals/vldb/CandanLS00","ssDeWaGRgTMJ")).
neg(eqo("journals/vldb/ChangG01","9Yvwv-riytgJ")).
neg(eqo("journals/vldb/ChenHY97","7y1DNkciIFQJ")).
neg(eqo("journals/vldb/ConstantopoulosJMV95","OYn8kYJyYJIJ")).
neg(eqo("journals/vldb/DeWittNSV96","RXWhkfjt95wJ")).
neg(eqo("journals/vldb/DeWittNSV96","lzbvXZxLKJIJ")).
neg(eqo("journals/vldb/DesslochHMMT98","sFYYcNsAMUYJ")).
neg(eqo("journals/vldb/DeyBS96","q8IL-AZTmcgJ")).
neg(eqo("journals/vldb/EyalM01","2sKfCfagQ90J")).
neg(eqo("journals/vldb/EyalM01","hrHLKxM0BSYJ")).
neg(eqo("journals/vldb/FahlR97","O2k6AXA-NpEJ")).
neg(eqo("journals/vldb/FengYLH02","u_9qWSpjaO4J")).
neg(eqo("journals/vldb/GeorgeH00","zuAl_DENZW0J")).
neg(eqo("journals/vldb/Han98","7CAA45TLpR0J")).
neg(eqo("journals/vldb/Han98","O8DGh42RLZYJ")).
neg(eqo("journals/vldb/HarderST99","ymzu_tyxk7gJ")).
neg(eqo("journals/vldb/IoannidisNSS97","HVIrvmhOTs4J")).
neg(eqo("journals/vldb/IoannidisNSS97","a3BrhYVFk_IJ")).
neg(eqo("journals/vldb/IshakbeyogluO98","ntsNTg6svygJ")).
neg(eqo("journals/vldb/KamelWS94","XMfYgcBvXM0J")).
neg(eqo("journals/vldb/KashyapS96","1WAVR-zTvXAJ")).
neg(eqo("journals/vldb/KellerB96","XTnTJ3s9yr0J")).
neg(eqo("journals/vldb/KnorrNT00","cBno_DjIDv4J")).
neg(eqo("journals/vldb/LiCHH01","UBbjyBOJXMwJ")).
neg(eqo("journals/vldb/LiR99","P_CkIKnb6JEJ")).
neg(eqo("journals/vldb/MaratheS02","xYQmZDKjXeEJ")).
neg(eqo("journals/vldb/MecellaP01","5ao36xjE30AJ")).
neg(eqo("journals/vldb/MedjahedBE03","0iiNS8BIbsUJ")).
neg(eqo("journals/vldb/MedjahedBE03","wP_GYyvWXaQJ")).
neg(eqo("journals/vldb/NgC98","gt44wy948iMJ")).
neg(eqo("journals/vldb/OoiHLT96","EclgEUrqHQAJ")).
neg(eqo("journals/vldb/Sarawagi01","Ndo_zcq-A-MJ")).
neg(eqo("journals/vldb/SinghalS97","mTjjvWPTO1oJ")).
neg(eqo("journals/vldb/SwamiS95","ftWHg08h9poJ")).
neg(eqo("journals/vldb/WangW01","CEKbSWc_C6UJ")).
pos(eqo("conf/sigmod/AbadiCCCCEGHMRSSTXYZ03","gBVNSFeS4P8J")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","AxpQwgyRyLgJ")).
pos(eqo("conf/sigmod/AbiteboulCM95","DakOA4Ew-poJ")).
pos(eqo("conf/sigmod/AdamY98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276350%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Adelberg98","JrU1gnfH1sYJ")).
pos(eqo("conf/sigmod/Adelberg98","UT0h0HcwLyUJ")).
pos(eqo("conf/sigmod/AdelbergGW97","XytbGy--8LMJ")).
pos(eqo("conf/sigmod/Aggarwal03","qbubaA6mQawJ")).
pos(eqo("conf/sigmod/AggarwalPWYP99","5uimonC4q_QJ")).
pos(eqo("conf/sigmod/AltinelLKMPLWB02","HtYTQ-fN8ccJ")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","L7XmLpQLXBIJ")).
pos(eqo("conf/sigmod/ArefBV95","ht_8Iq3SZ80J")).
pos(eqo("conf/sigmod/Atkinson95","url:http://portal.acm.org/citation.cfm%3Fid%3D223874")).
pos(eqo("conf/sigmod/BabcockBDM03","RFNZUHZBP_oJ")).
pos(eqo("conf/sigmod/BabcockBDM03","a2wqpKma5J4J")).
pos(eqo("conf/sigmod/BabuGR01","h_oXQ6ntHEUJ")).
pos(eqo("conf/sigmod/BabuGR01","zQCRmiH6jo4J")).
pos(eqo("conf/sigmod/BerchtoldBBKK97","BMkGN7AiGhYJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","1tZ74y0DNLIJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","fTYVIbi40sAJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","hoi0T_8So4gJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","vrlNTuVexE4J")).
pos(eqo("conf/sigmod/BerchtoldK97","lYpquDAEzrIJ")).
pos(eqo("conf/sigmod/BerchtoldK98","VuMPPr6k95AJ")).
pos(eqo("conf/sigmod/BerchtoldK98","pKKu82IYP9EJ")).
pos(eqo("conf/sigmod/BersonGMJ94","bw_c9Mk0_7IJ")).
pos(eqo("conf/sigmod/Blakeley96","37_iwO5NlgwJ")).
pos(eqo("conf/sigmod/Blakeley96","jQ6eIao6R0EJ")).
pos(eqo("conf/sigmod/Blakeley96","xZxFCI120eUJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","wF2-sxlGAu4J")).
pos(eqo("conf/sigmod/BouguettayaBH99","siO8kr7vvLEJ")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","_1drQdYrtmsJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","jJuSPh63bZ0J")).
pos(eqo("conf/sigmod/BrinDG95","QmhdqC_PIWsJ")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","IINRwK8hovkJ")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","cb1kf4z7hA4J")).
pos(eqo("conf/sigmod/BrunoC02","KAf2DUUVabIJ")).
pos(eqo("conf/sigmod/BuchmannDZH95","IU1cjdPVT6cJ")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/CandanLLHA01","efYVCK07AwMJ")).
pos(eqo("conf/sigmod/CatarciS94","pryJrhEGI2sJ")).
pos(eqo("conf/sigmod/CatarciS94","yaaZKZCP3soJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","CBKhTPuUL2kJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","GL8XEeYm7GsJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","qGTxTpQXTDsJ")).
pos(eqo("conf/sigmod/ChenRW02","05ShsIGjnKkJ")).
pos(eqo("conf/sigmod/CherniackZ98","7DFhNMAE13QJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","O-TrhFwhKM8J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/ChungMS02","2y_G8dmz1QkJ")).
pos(eqo("conf/sigmod/ClaypoolRZSK01","1VWOXPII9HUJ")).
pos(eqo("conf/sigmod/ClossmanSHKPB98","Q0Jr0CGWn5MJ")).
pos(eqo("conf/sigmod/ClossmanSHKPB98","evYlYFg5r9UJ")).
pos(eqo("conf/sigmod/CluetDSS98","W5KcKrhKY_YJ")).
pos(eqo("conf/sigmod/CluetDSS98","i2rbviV_9VgJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","qZppq83SJEYJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","tGBhWHHU7hsJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","0FohHTWs5toJ")).
pos(eqo("conf/sigmod/CranorJSS03","b0ayPKpqTwsJ")).
pos(eqo("conf/sigmod/CranorJSS03","nHesT9ADTdEJ")).
pos(eqo("conf/sigmod/DanielsDDEHJJLSSS94","fLNHwVFqnbIJ")).
pos(eqo("conf/sigmod/DeshpandeGR01","0Ta25VSGl7kJ")).
pos(eqo("conf/sigmod/Deutsch95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223880")).
pos(eqo("conf/sigmod/DeutschFS99","-KuX7UT0JIIJ")).
pos(eqo("conf/sigmod/DeutschFS99","9WLtxnKtm_EJ")).
pos(eqo("conf/sigmod/DeutschFS99","XrybyHOI16kJ")).
pos(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
pos(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
pos(eqo("conf/sigmod/FegarasM95","ZquXPssSY_EJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","ek26aiEheesJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","N9NHi5y3K38J")).
pos(eqo("conf/sigmod/FernandezFKLS98","i5coyXNfHCkJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","vVYs-3fNuZAJ")).
pos(eqo("conf/sigmod/FranklinJK96","0e3bs1VFPvAJ")).
pos(eqo("conf/sigmod/FranklinJK96","iDBvvrHwj7YJ")).
pos(eqo("conf/sigmod/FranklinJK96","yY5hMqazRHoJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","WOCgxlV_LgoJ")).
pos(eqo("conf/sigmod/GorelikWD94","X2URoOMjJv4J")).
pos(eqo("conf/sigmod/GorelikWD94","h10FxbLW6zAJ")).
pos(eqo("conf/sigmod/GotoK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D872837%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/GravanoCGP97","8jTTpoQc2RkJ")).
pos(eqo("conf/sigmod/GravanoCGP97","hs8rOlHD4K4J")).
pos(eqo("conf/sigmod/GravanoCGP97","yfb8p_tlSlsJ")).
pos(eqo("conf/sigmod/GravanoGT94","81oh7EDAYeoJ")).
pos(eqo("conf/sigmod/GravanoGT94","H6fWl-cSuY4J")).
pos(eqo("conf/sigmod/GravanoGT94","We2mw93oKL4J")).
pos(eqo("conf/sigmod/GravanoGT94","iwS7dFGYcyEJ")).
pos(eqo("conf/sigmod/GravanoGT94","nAJnhh70_0kJ")).
pos(eqo("conf/sigmod/Grust02","FYfyf-SjQNIJ")).
pos(eqo("conf/sigmod/GuptaHR97","pGix0qZ6Uz4J")).
pos(eqo("conf/sigmod/GuptaHR97","wu0var7zLkEJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","2rysKgS6lugJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","FEWg8Ea2CycJ")).
pos(eqo("conf/sigmod/HanPY00","GlNt7w28aE8J")).
pos(eqo("conf/sigmod/HanPY00","Ywgd3RbAfl0J")).
pos(eqo("conf/sigmod/HanPY00","hlrRtJigGbYJ")).
pos(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
pos(eqo("conf/sigmod/HanPY00","oeBeDPX7b9kJ")).
pos(eqo("conf/sigmod/HellersteinN96","_hDCldPyum0J")).
pos(eqo("conf/sigmod/HellersteinN96","tKewiQ5_kyIJ")).
pos(eqo("conf/sigmod/Hidber99","Rn-E82gM1RQJ")).
pos(eqo("conf/sigmod/HsiaoN00","iY5wlS4jsg0J")).
pos(eqo("conf/sigmod/HwangLYMMGCSS94","AWah9GLEFTAJ")).
pos(eqo("conf/sigmod/JonssonFS98","t6-LjSlCUmcJ")).
pos(eqo("conf/sigmod/JoshiA01","H9bMRYKnXMQJ")).
pos(eqo("conf/sigmod/JoshiA01","R-54DDaHDxoJ")).
pos(eqo("conf/sigmod/KabraD98","V9XUvirmVEEJ")).
pos(eqo("conf/sigmod/KanthRA02","RgDMwqhT30wJ")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","909hLNR8130J")).
pos(eqo("conf/sigmod/KornJF97","ZZUl2Dc1MPsJ")).
pos(eqo("conf/sigmod/KornJF97","o5T-Jfvv930J")).
pos(eqo("conf/sigmod/KoudasS97","sB-nvl5829EJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","uzpyy9XRpgYJ")).
pos(eqo("conf/sigmod/LabrinidisR00","DKUouEkK_b4J")).
pos(eqo("conf/sigmod/LarsonG98","QmBz3hMOFh4J")).
pos(eqo("conf/sigmod/LarsonG98","tPG--ikWjGcJ")).
pos(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
pos(eqo("conf/sigmod/LeeKC99","c-5n9qQKLaEJ")).
pos(eqo("conf/sigmod/LiBCS00","4abl38Q9iH4J")).
pos(eqo("conf/sigmod/LiS98","Vxg-4KP7FfEJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","4zDGoqCAWOoJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","6jeHlSgjCskJ")).
pos(eqo("conf/sigmod/LiYVGPUV98","xLs_uumSG84J")).
pos(eqo("conf/sigmod/LitwinS00","HI2KgQdo39gJ")).
pos(eqo("conf/sigmod/LitwinS00","R7Z-NlUo_YUJ")).
pos(eqo("conf/sigmod/LitwinS00","RQ9fpPAS2h8J")).
pos(eqo("conf/sigmod/LitwinS00","qzeu5GQ_2p0J")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","0e3PPUvtZ0MJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","ezlAkB7ijDUJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","1rcDwhVp-o8J")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/MaddenSHR02","DkgClKWAyEIJ")).
pos(eqo("conf/sigmod/MamoulisP99","fXHqHRgpG8sJ")).
pos(eqo("conf/sigmod/MamoulisP99","xdAsc3yVWvYJ")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/Melling94","j4O-xhs1QAgJ")).
pos(eqo("conf/sigmod/MelnikRB03","ntcjTU3hQiUJ")).
pos(eqo("conf/sigmod/Miller98","0B1XRTZ8cHkJ")).
pos(eqo("conf/sigmod/Miller98","7f6Q9GgXsmgJ")).
pos(eqo("conf/sigmod/MinPC03","JjrRZt4ONqMJ")).
pos(eqo("conf/sigmod/MogiK96","G-ggEZEKjT8J")).
pos(eqo("conf/sigmod/MoonWH02","rlfxeE4k2p4J")).
pos(eqo("conf/sigmod/MumickP94","hUQBQ_9ohcgJ")).
pos(eqo("conf/sigmod/NatsevRS99","Y3nejQSVKnUJ")).
pos(eqo("conf/sigmod/NatsevRS99","r2jkzqMSE0gJ")).
pos(eqo("conf/sigmod/NguyenS96","uD0NKv4AwaQJ")).
pos(eqo("conf/sigmod/OhHP00","o8cVWUElfUsJ")).
pos(eqo("conf/sigmod/OoiTZGLLLNSWZ03","l78OeieL4ZsJ")).
pos(eqo("conf/sigmod/OriaOILY00","9SbEzfHLSooJ")).
pos(eqo("conf/sigmod/PapadopoulosM98","dLzAJ-I1nCcJ")).
pos(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/ParkKKLPC98","F8CacVSkztEJ")).
pos(eqo("conf/sigmod/PatelD96","Goan1fI4O_oJ")).
pos(eqo("conf/sigmod/PhanN02","LLIkm2GMqakJ")).
pos(eqo("conf/sigmod/QuassW97","9nkD3JyhE1kJ")).
pos(eqo("conf/sigmod/QuassW97","u6Sx6E5i4L8J")).
pos(eqo("conf/sigmod/RafieiM97","Hd2lugurqEYJ")).
pos(eqo("conf/sigmod/RafieiM97","N-kEDX56ek0J")).
pos(eqo("conf/sigmod/RafieiM97","Z8kRr4T21JYJ")).
pos(eqo("conf/sigmod/RafieiM97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294143CI")).
pos(eqo("conf/sigmod/RajagopalanML98","6bxNVhIp7FAJ")).
pos(eqo("conf/sigmod/RajagopalanML98","AUR-p53CsK8J")).
pos(eqo("conf/sigmod/RajagopalanML98","vbi6XDjg0X8J")).
pos(eqo("conf/sigmod/RaoBG96","UmM1k4NoD2IJ")).
pos(eqo("conf/sigmod/RiedewaldAA02","AFKhL1I3L9AJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","efwTNo1wRnMJ")).
pos(eqo("conf/sigmod/RoySSB00","BJBeZ446Yc0J")).
pos(eqo("conf/sigmod/SarawagiTA98","0Vmsc0oib2kJ")).
pos(eqo("conf/sigmod/SarawagiTA98","SLmQWvsYtKYJ")).
pos(eqo("conf/sigmod/SarawagiTA98","ZLUo-gCGx5EJ")).
pos(eqo("conf/sigmod/SarawagiTA98","kT7z4mcwLrYJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","3OxZS395vDcJ")).
pos(eqo("conf/sigmod/SeshadriP97","f9POLlECN2gJ")).
pos(eqo("conf/sigmod/SeshadriP97","wozKEQCoZvwJ")).
pos(eqo("conf/sigmod/ShahC01","2wGOv6yh4yIJ")).
pos(eqo("conf/sigmod/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/ShashaB02a","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/ShashaB02a","url:http://portal.acm.org/citation.cfm%3Fid%3D564691.564798%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D564691%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Sheth95","JrkRUbNsLwEJ")).
pos(eqo("conf/sigmod/ShivakumarG97","4ioZ9JSSjVQJ")).
pos(eqo("conf/sigmod/SrikantA96","KVEv4thH4CgJ")).
pos(eqo("conf/sigmod/SrikantA96","OASIyc-vi9EJ")).
pos(eqo("conf/sigmod/SrikantA96","WkXM8o_flrEJ")).
pos(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
pos(eqo("conf/sigmod/SrikantA96","oAlX0rVQqlIJ")).
pos(eqo("conf/sigmod/SrikantA96","tTQpdbZYZGoJ")).
pos(eqo("conf/sigmod/Stonebraker98","LjfcoraomoEJ")).
pos(eqo("conf/sigmod/Team95b","v80FFBUTW_0J")).
pos(eqo("conf/sigmod/Team99","DphRY0uPqi8J")).
pos(eqo("conf/sigmod/TheobaldW02","w5_HkketH-wJ")).
pos(eqo("conf/sigmod/VossenW99","9PhYz-N58A8J")).
pos(eqo("conf/sigmod/WangPFY03","5JXKbI5l1FYJ")).
pos(eqo("conf/sigmod/Whelan98","Jp9LEvXjiJAJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","Pbl_CbLYKWYJ")).
pos(eqo("conf/sigmod/ZhangRL96","IVWPCLaGIPcJ")).
pos(eqo("conf/sigmod/ZhangRL96","KUGjzt-IgpoJ")).
pos(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
pos(eqo("conf/sigmod/ZhuS03","hIGjgc6mx0cJ")).
pos(eqo("conf/sigmod/ZouS96","DYFIQvOg7rgJ")).
pos(eqo("conf/sigmod/ZouS96","qPCh8M_RSwEJ")).
pos(eqo("conf/vldb/AboulnagaAN01","P6wBeL9DsREJ")).
pos(eqo("conf/vldb/Adler01","Tnuonq9Zi4cJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgrawalCN00","34SSHLGhNKsJ")).
pos(eqo("conf/vldb/AgrawalCN00","b9uF_OTTHIEJ")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","mB8W6em6zi8J")).
pos(eqo("conf/vldb/AgrawalPWZ95","x_ykbVlfyP8J")).
pos(eqo("conf/vldb/AmbiteKKMST01","9bzGIloFctIJ")).
pos(eqo("conf/vldb/Amer-YahiaCD98","9nmG2KCklEcJ")).
pos(eqo("conf/vldb/Amer-YahiaCD98","W0L9nOcuhmIJ")).
pos(eqo("conf/vldb/AnSVKIG01","kBzZ1GUoa1AJ")).
pos(eqo("conf/vldb/AnciauxBBPV01","PFEvlg2DiMkJ")).
pos(eqo("conf/vldb/ArunJ98","1dqeMksCm74J")).
pos(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
pos(eqo("conf/vldb/Baumann03","pJ2UEKVG_hoJ")).
pos(eqo("conf/vldb/BelussiF95","5FEmoD1TIdwJ")).
pos(eqo("conf/vldb/BerchtoldKK96","DDX7y0WvbRMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WcxbHqh4FfkJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WnYVibh8fxUJ")).
pos(eqo("conf/vldb/BerchtoldKK96","_oDfC1aR4CAJ")).
pos(eqo("conf/vldb/BerchtoldKK96","knyp-i1eDwwJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","L2c8XblCSicJ")).
pos(eqo("conf/vldb/BernsteinPS99","JcHiZlbsts0J")).
pos(eqo("conf/vldb/BonczRK98","965BXzMPxSoJ")).
pos(eqo("conf/vldb/BonczRK98","ts5vu2eNQgYJ")).
pos(eqo("conf/vldb/BonifatiCDS01","tCrfb27dXiwJ")).
pos(eqo("conf/vldb/BouganimNPW03","5oXuo8dJ6qAJ")).
pos(eqo("conf/vldb/BridgeJKLLM97","8SYZpKAeTwQJ")).
pos(eqo("conf/vldb/BrodieC99","PAahJo-PXsIJ")).
pos(eqo("conf/vldb/BrownCC94","E-1nAx7gc-8J")).
pos(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
pos(eqo("conf/vldb/CasatiDGS01","XQw3ADYCXdcJ")).
pos(eqo("conf/vldb/CeriM03","G2QuI5QYYMoJ")).
pos(eqo("conf/vldb/CeriM03","hFPNVe44A04J")).
pos(eqo("conf/vldb/ChakrabartiDAR97","QyBDbs7EpmsJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","jNb5aoFeS7wJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChakravarthyKAK94","L9eva_gsxrIJ")).
pos(eqo("conf/vldb/ChangG97","MY0MxW-_uksJ")).
pos(eqo("conf/vldb/ChangG97","mXye9G0HHEwJ")).
pos(eqo("conf/vldb/ChangG97","wDrwjYtI4uEJ")).
pos(eqo("conf/vldb/ChatziantoniouR96","46FVYbhr0WoJ")).
pos(eqo("conf/vldb/ChatziantoniouR97","UEvW-FsWASUJ")).
pos(eqo("conf/vldb/ChaudhuriW00","OuM0E0BhEXIJ")).
pos(eqo("conf/vldb/ChavdaW97","E9AsPVyCDlMJ")).
pos(eqo("conf/vldb/ChenRS95","4TMZhO1wdwsJ")).
pos(eqo("conf/vldb/CherniackFZ01","WHWa6vBvwJ0J")).
pos(eqo("conf/vldb/CherniackZ98","So_H9Oer6lsJ")).
pos(eqo("conf/vldb/ChienVZTZ02","uUmeAkW_FFUJ")).
pos(eqo("conf/vldb/DarFJST96","R9tpZP8C0xsJ")).
pos(eqo("conf/vldb/DarFJST96","ThLxMqqAxjIJ")).
pos(eqo("conf/vldb/DarFJST96","Ui5dxm-mCN8J")).
pos(eqo("conf/vldb/DarFJST96","cM4adSkCTK0J")).
pos(eqo("conf/vldb/DarFJST96","sRhjAJHtl-sJ")).
pos(eqo("conf/vldb/DiaoF03","Crt1JZ1eEj0J")).
pos(eqo("conf/vldb/DiwanRSS96","HjDa9on7LzoJ")).
pos(eqo("conf/vldb/DoR02","-AsVP3NqvlAJ")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("conf/vldb/DoR02","bey6io4rYbgJ")).
pos(eqo("conf/vldb/EicklerGK95","63QhLG57QssJ")).
pos(eqo("conf/vldb/FaloutsosJS97","C1Wu3OVlJCsJ")).
pos(eqo("conf/vldb/FaloutsosJS97","u_9qWSpjaO4J")).
pos(eqo("conf/vldb/FerrandinaMZFM95","9rofzgQ6HtcJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","ume4RGX6sI4J")).
pos(eqo("conf/vldb/Galindo-LegariaPK94","oMqPXsCl5gYJ")).
pos(eqo("conf/vldb/GantiLR00","Vd-lSpZc0cYJ")).
pos(eqo("conf/vldb/GardarinGT96","4NKqwzC5A_wJ")).
pos(eqo("conf/vldb/GehaniJR94","MxYiwR2f9UYJ")).
pos(eqo("conf/vldb/GehrkeRG98","G8JSWUAO2lMJ")).
pos(eqo("conf/vldb/GehrkeRG98","hobnzQKRlK4J")).
pos(eqo("conf/vldb/GoldsteinR00","30fMB9_zBm0J")).
pos(eqo("conf/vldb/GoldsteinR00","FncQ86sO2agJ")).
pos(eqo("conf/vldb/GoldsteinR00","zydIJyhwgPEJ")).
pos(eqo("conf/vldb/Greco98","CCr8CUlHeNsJ")).
pos(eqo("conf/vldb/GuPS00","mRWLGqueLNsJ")).
pos(eqo("conf/vldb/Guting94","DCUu4jysue0J")).
pos(eqo("conf/vldb/HaasKWY97","8Fy6YT12yIgJ")).
pos(eqo("conf/vldb/HaasKWY97","yIRQRtTEzSAJ")).
pos(eqo("conf/vldb/HanF95","76X91rVs8BQJ")).
pos(eqo("conf/vldb/HanF95","CZGjStvTkZUJ")).
pos(eqo("conf/vldb/HanF95","GeMycbLXZUkJ")).
pos(eqo("conf/vldb/HanF95","OdpKxDyMwhsJ")).
pos(eqo("conf/vldb/HanF95","_rlpIiNduaYJ")).
pos(eqo("conf/vldb/HanF95","h0jX6zbYeeEJ")).
pos(eqo("conf/vldb/HanF95","hDi8HKsDrV0J")).
pos(eqo("conf/vldb/HanF95","jQaZA3mmmakJ")).
pos(eqo("conf/vldb/HanF95","pNBgTa_UPDEJ")).
pos(eqo("conf/vldb/HanF95","ruAAx3U9Q-EJ")).
pos(eqo("conf/vldb/HoelS94","Id1cvsQURBAJ")).
pos(eqo("conf/vldb/HoelS94","PBMxFmEVlBQJ")).
pos(eqo("conf/vldb/HristidisGP03","B2rShDD99xwJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
pos(eqo("conf/vldb/HulgeriS02","xGcM9AuhrBMJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","o2qGdf4L94MJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/vldb/JonscherD94","yv7vyZT9-YEJ")).
pos(eqo("conf/vldb/KeidlSSK02","Wc1ViFeRa54J")).
pos(eqo("conf/vldb/KiesslingK02","Z8bBN2cO11UJ")).
pos(eqo("conf/vldb/KornackerB95","IN_sibgHb9MJ")).
pos(eqo("conf/vldb/KornackerB95","TjG5memyVWIJ")).
pos(eqo("conf/vldb/KoschBBHHLRT01","xvNBOkc3UkcJ")).
pos(eqo("conf/vldb/KoudasIM00","VSR4PwHmGWsJ")).
pos(eqo("conf/vldb/LakshmananPH02","_hNiD_QLDdAJ")).
pos(eqo("conf/vldb/LamKR02","GdvZvvRTXIAJ")).
pos(eqo("conf/vldb/LaneEN00","0O3JgOoSdIUJ")).
pos(eqo("conf/vldb/Levy96","lDTPyBMtHVwJ")).
pos(eqo("conf/vldb/LiC94","O0rvK0GFmBEJ")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/LuL00","Ih5hY-NRmFgJ")).
pos(eqo("conf/vldb/LuoN01","TRWSf77xoWsJ")).
pos(eqo("conf/vldb/LuoNEW03","8n1UIzMm4VMJ")).
pos(eqo("conf/vldb/Madnick95","CVQyvLe8w38J")).
pos(eqo("conf/vldb/MahnkeMS02","VhxIKKG8oWYJ")).
pos(eqo("conf/vldb/MaratheS97","HcgXkUDB-wYJ")).
pos(eqo("conf/vldb/MehtaD95","lRiSWgNjNtIJ")).
pos(eqo("conf/vldb/MillerHH00","Rqg_slyUMYMJ")).
pos(eqo("conf/vldb/MillerHH00","wWG2iaq2tTgJ")).
pos(eqo("conf/vldb/MillinerBP95","kYl-9cV8gloJ")).
pos(eqo("conf/vldb/MiloZ98","Nd7-CTB1lRgJ")).
pos(eqo("conf/vldb/MiloZ98","UF-Z2VPtU6sJ")).
pos(eqo("conf/vldb/Mina98","ButmJWjGXusJ")).
pos(eqo("conf/vldb/Moerkotte98","HcCevkoobDsJ")).
pos(eqo("conf/vldb/Mohan01","tAO-l_SkmSwJ")).
pos(eqo("conf/vldb/MoserKK95","A2OQAUw2OHIJ")).
pos(eqo("conf/vldb/MoserKK95","DFZ5hU-q0BIJ")).
pos(eqo("conf/vldb/MuthOPW98","cy0zVqmNba4J")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/Novaretti01","tZtnFoH5lY0J")).
pos(eqo("conf/vldb/PacittMS99","jJyGKE2N34gJ")).
pos(eqo("conf/vldb/PantiSG00","C7Vuxp5KVsAJ")).
pos(eqo("conf/vldb/PapadiasT01","2V2bnIgsY1kJ")).
pos(eqo("conf/vldb/PapadiasT01","JtQbB9D7zkwJ")).
pos(eqo("conf/vldb/PardonA00","k7G60pXtD58J")).
pos(eqo("conf/vldb/ParkMC02","WFmae47kgN4J")).
pos(eqo("conf/vldb/PedersenJD99","sAUncbolYJ8J")).
pos(eqo("conf/vldb/PereiraFJLS01","CZTJ00lolvYJ")).
pos(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
pos(eqo("conf/vldb/RahmM95","6ioboOxJvQIJ")).
pos(eqo("conf/vldb/RamanRH99","6uP3E_WEkCAJ")).
pos(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
pos(eqo("conf/vldb/Ramanan03","ruVmVa1bhoUJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","T2fm7Wb1ak4J")).
pos(eqo("conf/vldb/SahuguetA99","PAcS8vELrawJ")).
pos(eqo("conf/vldb/SahuguetA99","pK5bydjeZFIJ")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/ScheuermannSV96","42whesD5Rl8J")).
pos(eqo("conf/vldb/Schnase00","OdaRU442nm0J")).
pos(eqo("conf/vldb/SeshadriLR96","K62EwWeSRKUJ")).
pos(eqo("conf/vldb/SetzerZ94","1tmW1mOCZqIJ")).
pos(eqo("conf/vldb/ShahRS02","Q3MhG5RK29oJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GIlUG9H3gUUJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GcedmSsoWusJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","WkdIh9-e2WMJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","hYQ_6_v-Cd4J")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
pos(eqo("conf/vldb/ShethKMWDLPLS96","jWZkmgGziVoJ")).
pos(eqo("conf/vldb/ShiSZ03","-OjqoDQTIxMJ")).
pos(eqo("conf/vldb/SistlaYH94","QWD1EGMbTQYJ")).
pos(eqo("conf/vldb/SistlaYH94","bDH4OmzDSLEJ")).
pos(eqo("conf/vldb/SizovGT03","UbQPXbPLMCAJ")).
pos(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
pos(eqo("conf/vldb/Sol01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672038%26coll%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/SripadaW94","VqNz3sp638UJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","01ZVDudF4WAJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","8o0d8xLuwgUJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","WvvY_Ao19mAJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/TaoP02","7ZyV9ivZySQJ")).
pos(eqo("conf/vldb/Toivonen96","SVRZYX3nSGAJ")).
pos(eqo("conf/vldb/Toivonen96","tZpeMfkDl8cJ")).
pos(eqo("conf/vldb/Toivonen96","yd2dxAbjvTAJ")).
pos(eqo("conf/vldb/VelegrakisMP03","tYCCI2DndboJ")).
pos(eqo("conf/vldb/Wadler01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672033")).
pos(eqo("conf/vldb/WangYM97","OnLLKkgfyLUJ")).
pos(eqo("conf/vldb/WangYM97","hVRj_WzRqI4J")).
pos(eqo("conf/vldb/WangYM97","o5dSRIunsUUJ")).
pos(eqo("conf/vldb/WangYM97","xW3AafG2xKgJ")).
pos(eqo("conf/vldb/WeberSB98","6D0Qt6Sjp8cJ")).
pos(eqo("conf/vldb/YuSLJ02","Pdhfb0V9jM8J")).
pos(eqo("conf/vldb/YuSLJ02","qYGzjvmVjS8J")).
pos(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
pos(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565129%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aberer03c","url:http://portal.acm.org/citation.cfm%3Fid%3D945721.945727%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AdelbergKG96","6gc5TN-yce8J")).
pos(eqo("journals/sigmod/AdelbergKG96","GfiQygac5twJ")).
pos(eqo("journals/sigmod/AndlerHEMBE96","oNYOKYvjoKgJ")).
pos(eqo("journals/sigmod/BaaderJN97","dr4SzOhnLB8J")).
pos(eqo("journals/sigmod/BargaL02","QTzV3iNq2O8J")).
pos(eqo("journals/sigmod/BargaL02","fY3kkkzBLw8J")).
pos(eqo("journals/sigmod/BertinoEH01","Rba70P6SqQYJ")).
pos(eqo("journals/sigmod/BonifatiC00","XCdMiXLp41IJ")).
pos(eqo("journals/sigmod/BorgidaCS98","iPbD7vPHzgYJ")).
pos(eqo("journals/sigmod/BorgidaCS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290595%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BurtonM98","LOXd8JPfhpwJ")).
pos(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
pos(eqo("journals/sigmod/CaleroPR03","zWoRcQffsq8J")).
pos(eqo("journals/sigmod/CasatiDS00","jPx0tvkJ-fUJ")).
pos(eqo("journals/sigmod/ChangASS98","srJr-8rCZ4YJ")).
pos(eqo("journals/sigmod/ChangGKRS98","5FiyBEZ3v70J")).
pos(eqo("journals/sigmod/Colliat96","3FAQV305QD0J")).
pos(eqo("journals/sigmod/ConradEHRSSSV97","zJCsqgMH5bUJ")).
pos(eqo("journals/sigmod/DarwenD95","DVnOcHunv7MJ")).
pos(eqo("journals/sigmod/DarwenD95","EXwe9r79qxEJ")).
pos(eqo("journals/sigmod/Date96","url:http://portal.acm.org/citation.cfm%3Fid%3D245882.245885%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DogacDATKCD98","fYMpjIpF8ckJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","vG5FK8BJkZgJ")).
pos(eqo("journals/sigmod/DomenigD99","S6TMGRGUq1IJ")).
pos(eqo("journals/sigmod/DongS00","gH_HDDJghbAJ")).
pos(eqo("journals/sigmod/EisenbergM00","4mD1eFCHKKwJ")).
pos(eqo("journals/sigmod/EisenbergM00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344819%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FlorescuLM98","FCcDKONgJVYJ")).
pos(eqo("journals/sigmod/FlorescuLM98","q5OOyzSAlC8J")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","5PisY7JvbzQJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ERqqWPMwU2sJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ixz5LdVw9_8J")).
pos(eqo("journals/sigmod/GroskySF02","HA3wM_i-y3YJ")).
pos(eqo("journals/sigmod/GuptaHR97","YSgaDQ95dfEJ")).
pos(eqo("journals/sigmod/Han98","lwZ7EjZwrZ0J")).
pos(eqo("journals/sigmod/Han98","qmIdBy8oNgEJ")).
pos(eqo("journals/sigmod/HanBP01","FT5pSUb-uTYJ")).
pos(eqo("journals/sigmod/KoubarakisTID03","VtCTqej5JSQJ")).
pos(eqo("journals/sigmod/KuanL99","BZfdROjhbhwJ")).
pos(eqo("journals/sigmod/LaenderRST02","34QnrkmS0Y8J")).
pos(eqo("journals/sigmod/LaenderRST02","paQAZ2KXFgAJ")).
pos(eqo("journals/sigmod/LawderK01","eznFJ2e_pQQJ")).
pos(eqo("journals/sigmod/LeeC00","3kSb_ooS1cgJ")).
pos(eqo("journals/sigmod/LeeC00","Knzz_bkGA00J")).
pos(eqo("journals/sigmod/Loeffen94","jFNkGh68g6EJ")).
pos(eqo("journals/sigmod/LudascherMM01","PyzHbvS-dCkJ")).
pos(eqo("journals/sigmod/LudwigG00","T7hbL2VkOhsJ")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601879%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MaximilienS02","hgjhR8PwNVwJ")).
pos(eqo("journals/sigmod/McHughW97","dAnyGPqToQEJ")).
pos(eqo("journals/sigmod/MeltzerC98","-wQ-mpGIWdMJ")).
pos(eqo("journals/sigmod/MusickM98","gt83e4uB09wJ")).
pos(eqo("journals/sigmod/NgH95","qolJkVC2MoYJ")).
pos(eqo("journals/sigmod/NgH95","url:http://portal.acm.org/citation.cfm%3Fid%3D202660.202665%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NorrieBSW94","q6YVJJgD1uQJ")).
pos(eqo("journals/sigmod/ONeilG95","RlH2shMtkfwJ")).
pos(eqo("journals/sigmod/ONeilG95","YNkY3rC_4zQJ")).
pos(eqo("journals/sigmod/PaepckeGRC00","hxFRuvCtvGEJ")).
pos(eqo("journals/sigmod/Qian95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RamamrithamSSTX96","kezAM71rts0J")).
pos(eqo("journals/sigmod/RiekertMW97","M-3MGd3wPcsJ")).
pos(eqo("journals/sigmod/RosenthalS99","ZYnsLI6mz2cJ")).
pos(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","fc8y9x82jqAJ")).
pos(eqo("journals/sigmod/ShanmugasundaramSKKVNT01","wTJy5XquCpsJ")).
pos(eqo("journals/sigmod/SilberschatzSU96","_MXfp9GHEqQJ")).
pos(eqo("journals/sigmod/SilberschatzSU96","_ZsI_bVIJMwJ")).
pos(eqo("journals/sigmod/SilberschatzSU96","soiN2U4tXykJ")).
pos(eqo("journals/sigmod/SlivinskasJS02","xTPSs2k_pUIJ")).
pos(eqo("journals/sigmod/Snodgrass02b","KENWBobILMwJ")).
pos(eqo("journals/sigmod/Snodgrass03","m-l6e98xxOsJ")).
pos(eqo("journals/sigmod/SouzaS99","OmYc0wE1j4kJ")).
pos(eqo("journals/sigmod/Stirling03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776997%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Stonebraker02","0HMk-YUh4i8J")).
pos(eqo("journals/sigmod/SycaraKWL99","YgouJdrCoZQJ")).
pos(eqo("journals/sigmod/SycaraKWL99","fdruJtO0F0UJ")).
pos(eqo("journals/sigmod/SycaraKWL99","foOIj5nrS-gJ")).
pos(eqo("journals/sigmod/TheodoridisN00","DXTczW8Dv4MJ")).
pos(eqo("journals/sigmod/Vassilakis00","nZO8ZA4eYzYJ")).
pos(eqo("journals/sigmod/VassiliadisS99","6usYpcQMCgIJ")).
pos(eqo("journals/sigmod/VassiliadisS99","eGARASwVBrUJ")).
pos(eqo("journals/sigmod/VassiliadisS99","uexel5Cdu4wJ")).
pos(eqo("journals/sigmod/Winslett94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181569%26type%3Dpdf")).
pos(eqo("journals/sigmod/WinslettCDHZZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/CeriFPT94","aphxPCo8qkgJ")).
pos(eqo("journals/tods/ChenHM95","pO6SFdVGt5QJ")).
pos(eqo("journals/tods/DeyS96","Jfo57_VwkfUJ")).
pos(eqo("journals/tods/DeyS96","l2y2U5f48WcJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","-q1BFuUI27EJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","v5mRJmMZOTMJ")).
pos(eqo("journals/tods/HsuSY01","jNjxe59ZOLAJ")).
pos(eqo("journals/tods/LiuHD98","ts7DF925TR8J")).
pos(eqo("journals/tods/MuralidharS99","dKvepAPYBmcJ")).
pos(eqo("journals/tods/Ng01","npCKXD_vLM8J")).
pos(eqo("journals/tods/PetersO97","er0r8doAGUQJ")).
pos(eqo("journals/tods/PetersO97","mQp5jjo-npAJ")).
pos(eqo("journals/tods/RaschidL96","rUpu2pcFa8cJ")).
pos(eqo("journals/tods/SalemGS94","7IBL1cudvR0J")).
pos(eqo("journals/tods/SistlaWYS98","4owPoyytTP4J")).
pos(eqo("journals/tods/WandSW99","pYtOkFSgdXYJ")).
pos(eqo("journals/tods/ZobelMR98","AvV6lMEBGWsJ")).
pos(eqo("journals/vldb/AgrawalHK03","NDKJPUgy_K4J")).
pos(eqo("journals/vldb/Baumann94","2Yii02idzcUJ")).
pos(eqo("journals/vldb/Bertino94","oRWtcCo6xlAJ")).
pos(eqo("journals/vldb/ChanFGR02","LfS9Vr-FSZEJ")).
pos(eqo("journals/vldb/ChangG01","hYu2nw263UoJ")).
pos(eqo("journals/vldb/ClaussenKKW00","DSF-ukHbE64J")).
pos(eqo("journals/vldb/CuiW03","SaOd6rDz5ZgJ")).
pos(eqo("journals/vldb/DoanMDDH03","1WC2vYc_k3gJ")).
pos(eqo("journals/vldb/EvangelidisS97","5dnYlEMQTb0J")).
pos(eqo("journals/vldb/FiletoLPAM03","VWbm4EeeFNMJ")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/KabraD99","pWEfI0xFFcoJ")).
pos(eqo("journals/vldb/KellerB96","Y5-Iqr5NcY8J")).
pos(eqo("journals/vldb/KellerB96","tVoqZpEEHv8J")).
pos(eqo("journals/vldb/LaurentLSV01","TTIgIh9uC_YJ")).
pos(eqo("journals/vldb/Li03","XkdLpQ5x-YIJ")).
pos(eqo("journals/vldb/MedjahedBBNE03","18FFG2HC51oJ")).
pos(eqo("journals/vldb/MedjahedBBNE03","vtVf3hshlVIJ")).
pos(eqo("journals/vldb/NanopoulosM02","icoWjIZ_6IIJ")).
pos(eqo("journals/vldb/PapazogluK97","3k9vWWMJiWYJ")).
pos(eqo("journals/vldb/PapazogluK97","kFQl7LX8OQkJ")).
pos(eqo("journals/vldb/PeckhamMD95","nhU_8O_9SY0J")).
pos(eqo("journals/vldb/PottingerH01","Kv3ZFRUKCogJ")).
pos(eqo("journals/vldb/PottingerH01","mpnnRdFUUJQJ")).
pos(eqo("journals/vldb/ShegalovGW01","_6ErNQyZwXsJ")).
pos(eqo("journals/vldb/TempletonHMB95","RKNGp2gmOTUJ")).
pos(eqo("journals/vldb/TorpJS00","dMRIRjR_KAAJ")).
pos(eqo("journals/vldb/YangW03","Dpj8kCpIfSkJ")).
pos(eqo("journals/vldb/YangW03","IJDg4R1pw6EJ")).
