neg(eqo("conf/sigmod/AbiteboulBCMM03","78EbgloygSMJ")).
neg(eqo("conf/sigmod/AbiteboulCM95","sRFLSd3IXgMJ")).
neg(eqo("conf/sigmod/AcharyaGPR99","m8ZMx1EQVkMJ")).
neg(eqo("conf/sigmod/AchyutuniON96","UAO4T_2ylPkJ")).
neg(eqo("conf/sigmod/Adelberg98","JrU1gnfH1sYJ")).
neg(eqo("conf/sigmod/AdelbergGK95","3hsPMPTl2msJ")).
neg(eqo("conf/sigmod/AdelbergGK95","6gc5TN-yce8J")).
neg(eqo("conf/sigmod/AdelbergGK95","dhxU6uhAR6QJ")).
neg(eqo("conf/sigmod/AdyaGLM95","FlE1JdgElGQJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058166%26type%3Dpdf")).
neg(eqo("conf/sigmod/AggarwalWY99","s9hhR-EdDGgJ")).
neg(eqo("conf/sigmod/AgichteinGV01","6_FvrRYnxHYJ")).
neg(eqo("conf/sigmod/AgrawalGGR98","EQ0ys8s10vcJ")).
neg(eqo("conf/sigmod/AgrawalK03","_NISJ-0lKiAJ")).
neg(eqo("conf/sigmod/AgrawalW00","wivJNEQEWzMJ")).
neg(eqo("conf/sigmod/AndersonBKW98","TsShfxPwF6YJ")).
neg(eqo("conf/sigmod/BarbaraI94","F7azEOfg-Q0J")).
neg(eqo("conf/sigmod/BarbaraI94","nPEHo5w7PxwJ")).
neg(eqo("conf/sigmod/Bayardo98","tZxEL1caAGUJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","9UYo0M1RV7oJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","5_P2PLk8odYJ")).
neg(eqo("conf/sigmod/BilirisP94","ryyvz4-SdEMJ")).
neg(eqo("conf/sigmod/BlakeleyP98","5irgbROyqwIJ")).
neg(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97a","5Vi21D9qn6YJ")).
neg(eqo("conf/sigmod/BorkarDS01","2wGOv6yh4yIJ")).
neg(eqo("conf/sigmod/BorkarDS01","cExZWIT9LZcJ")).
neg(eqo("conf/sigmod/BozkayaO97","CEKbSWc_C6UJ")).
neg(eqo("conf/sigmod/BreunigKKS01","3ET_IEkoGjYJ")).
neg(eqo("conf/sigmod/BreunigKKS01","wR6CGftUyH0J")).
neg(eqo("conf/sigmod/BreunigKNS00","vezxTIGxNywJ")).
neg(eqo("conf/sigmod/BrinDG95","6uelfg3RgEoJ")).
neg(eqo("conf/sigmod/BrodskyK95","tVcdOs_e7bQJ")).
neg(eqo("conf/sigmod/Brown99","bHeWa5sSnFgJ")).
neg(eqo("conf/sigmod/Brown99","xyUzr5ouJyUJ")).
neg(eqo("conf/sigmod/BunemanM95","vIBvTfMLL4UJ")).
neg(eqo("conf/sigmod/Carey00","x6n6Ev8WnhEJ")).
neg(eqo("conf/sigmod/Carey00","zq5ro0OdlB8J")).
neg(eqo("conf/sigmod/CareyMN97","u64n4yMnma4J")).
neg(eqo("conf/sigmod/CarinoKKB01","UZShrxhltiEJ")).
neg(eqo("conf/sigmod/CasatiS01","CjHwRU64VswJ")).
neg(eqo("conf/sigmod/Chan98","jgrW--UTkacJ")).
neg(eqo("conf/sigmod/ChangBCLLS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637417%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ChaudhuriDY95","JyEX0YVMP5oJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","hvMTb3FYOjQJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","9GsZHpVf2_cJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","GL8XEeYm7GsJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","GL8XEeYm7GsJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","H5IdN0_MQw4J")).
neg(eqo("conf/sigmod/ChaudhuriMN99","Lm25su-wny0J")).
neg(eqo("conf/sigmod/ChaudhuriN98","jq5VkbTyBksJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066305%26type%3Dpdf")).
neg(eqo("conf/sigmod/ChenR94","4Hhh-d__bksJ")).
neg(eqo("conf/sigmod/CherniackZ96","wJcUU6m0ugQJ")).
neg(eqo("conf/sigmod/CherniackZ98","ikUruzAsI68J")).
neg(eqo("conf/sigmod/ChoG00","HqAWyuB11loJ")).
neg(eqo("conf/sigmod/Chong98","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057809")).
neg(eqo("conf/sigmod/ChooOLCGBPS96","Ljpkq7MPqeEJ")).
neg(eqo("conf/sigmod/ChristophidesCS00","9GsZHpVf2_cJ")).
neg(eqo("conf/sigmod/CluetDSS98","i2rbviV_9VgJ")).
neg(eqo("conf/sigmod/Cohen98a","2-Tbb1SnVYkJ")).
neg(eqo("conf/sigmod/Cohen98a","sZZVwXivu-kJ")).
neg(eqo("conf/sigmod/ColbyKLMR97","25hGiPZCMqoJ")).
neg(eqo("conf/sigmod/DasGR03","RalvsjDuKzsJ")).
neg(eqo("conf/sigmod/DeHaanTCO03","fqvw8m62q-8J")).
neg(eqo("conf/sigmod/DeligiannakisR03","E7qQp2vH66oJ")).
neg(eqo("conf/sigmod/DeshpandeGR01","eQjFv7QxsQQJ")).
neg(eqo("conf/sigmod/DewanSHH94","XoebKNSL_fsJ")).
neg(eqo("conf/sigmod/DogacHKOONDMAKE96","UAO4T_2ylPkJ")).
neg(eqo("conf/sigmod/Dyreson03","l7KC1qG6OGEJ")).
neg(eqo("conf/sigmod/Edelstein95","ChmNvjU9V5sJ")).
neg(eqo("conf/sigmod/Ellison95","FdkHUCk1ocUJ")).
neg(eqo("conf/sigmod/Englert94","IxbpxwykMXoJ")).
neg(eqo("conf/sigmod/FaloutsosL95","PoVkG8nD28IJ")).
neg(eqo("conf/sigmod/FaloutsosL95","vwcVawlOJn0J")).
neg(eqo("conf/sigmod/FaloutsosSTT00","qsWDIfzBxiQJ")).
neg(eqo("conf/sigmod/Freeston95","OETxfUaeLqEJ")).
neg(eqo("conf/sigmod/French95","m2Mf-4BgLP4J")).
neg(eqo("conf/sigmod/Galindo-Legaria94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107500%26type%3Dpdf")).
neg(eqo("conf/sigmod/Galindo-LegariaJ01","cy_Fe935WMAJ")).
neg(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
neg(eqo("conf/sigmod/GarofalakisG02","6lvBOS-XO3EJ")).
neg(eqo("conf/sigmod/GarofalakisI96","Hz7TBeGZRz8J")).
neg(eqo("conf/sigmod/GatziuGD95","I-r1LE1najAJ")).
neg(eqo("conf/sigmod/GehrkeGRL99","kcrWfQEI9G8J")).
neg(eqo("conf/sigmod/GeneserethKD97","LhniMvyMMogJ")).
neg(eqo("conf/sigmod/GionisGK01","HLu7MvWb5rMJ")).
neg(eqo("conf/sigmod/GionisGK01","pcUSk8BKMJYJ")).
neg(eqo("conf/sigmod/GoldsteinL01","rg8576nvnkUJ")).
neg(eqo("conf/sigmod/GravanoGT94","z26H2tQo7bkJ")).
neg(eqo("conf/sigmod/Greer99","emKrffY3yrwJ")).
neg(eqo("conf/sigmod/GriffinL95","ebJMvVO8zp0J")).
neg(eqo("conf/sigmod/Grust02","CKiAavnrRH4J")).
neg(eqo("conf/sigmod/GunopulosD01","JyfsEdgLoxYJ")).
neg(eqo("conf/sigmod/GuptaHR97","dGbuUkhWNhMJ")).
neg(eqo("conf/sigmod/GuptaHR97","wu0var7zLkEJ")).
neg(eqo("conf/sigmod/GuptaS03","5Tr5bIDpb98J")).
neg(eqo("conf/sigmod/Han96","eT9qoWFevVQJ")).
neg(eqo("conf/sigmod/Han96","iK5txf5TWI0J")).
neg(eqo("conf/sigmod/HanFHCC94","iurxdvB6oLAJ")).
neg(eqo("conf/sigmod/HanPLJ01","qq2lTNrNTBUJ")).
neg(eqo("conf/sigmod/Hellerstein00","dtYwk-vb8DUJ")).
neg(eqo("conf/sigmod/HjaltasonS98","NbU35wXNPhIJ")).
neg(eqo("conf/sigmod/HsiaoCY94","LEi_Rzm1iH0J")).
neg(eqo("conf/sigmod/HsuLG00","AyWUeJ5k2IoJ")).
neg(eqo("conf/sigmod/ImielinskiV95","7FHudYbEkF0J")).
neg(eqo("conf/sigmod/ImielinskiVB94","BMkGN7AiGhYJ")).
neg(eqo("conf/sigmod/IoannidisL94","icq7-lEBur8J")).
neg(eqo("conf/sigmod/IoannidisP95","23K90oRfbbsJ")).
neg(eqo("conf/sigmod/IpeirotisGS01","1WSTXNtfwJEJ")).
neg(eqo("conf/sigmod/IpeirotisGS01","4yp1EneQhT8J")).
neg(eqo("conf/sigmod/IvesFFLW99","2y9m1qzVu4EJ")).
neg(eqo("conf/sigmod/Jagadish94","7U5nAHQRjaYJ")).
neg(eqo("conf/sigmod/Jagadish94","Er6BubyniOYJ")).
neg(eqo("conf/sigmod/JarkeQCLFLVV00","NtU4gusv7gEJ")).
neg(eqo("conf/sigmod/Jhingran00","5Chw6HN64vEJ")).
neg(eqo("conf/sigmod/JonkerS95","x15Bvav_QmoJ")).
neg(eqo("conf/sigmod/JonssonFS98","5fb1l1MyGisJ")).
neg(eqo("conf/sigmod/JosifovskiSHL02","UQNt6tlbxaQJ")).
neg(eqo("conf/sigmod/KabraD98","pWEfI0xFFcoJ")).
neg(eqo("conf/sigmod/KanthAS98","RaOQG4YyzM4J")).
neg(eqo("conf/sigmod/Keim96","H6fWl-cSuY4J")).
neg(eqo("conf/sigmod/Keim96","Sg6fZ_cNZgUJ")).
neg(eqo("conf/sigmod/KeoghCMP01","QTzuiNlMnR4J")).
neg(eqo("conf/sigmod/KimCK01","EYI-OULRIz8J")).
neg(eqo("conf/sigmod/KornM00","qNi-OiqW3sIJ")).
neg(eqo("conf/sigmod/KornMZ03","mClzTQppJE4J")).
neg(eqo("conf/sigmod/KriegelMPS01","dr4SzOhnLB8J")).
neg(eqo("conf/sigmod/LakshmananPZ03","tcnjvKELfs0J")).
neg(eqo("conf/sigmod/LangS01","jQHrw-vSm7wJ")).
neg(eqo("conf/sigmod/LarsonG03","oPXBu1tWLpQJ")).
neg(eqo("conf/sigmod/Lassettre98","yGz8BLxbPPcJ")).
neg(eqo("conf/sigmod/Levine95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D223878%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LoR96","3CMnzSHX7KoJ")).
neg(eqo("conf/sigmod/LometT03","GtTFD2_X8uYJ")).
neg(eqo("conf/sigmod/MaddenH02","JclQFC-1s18J")).
neg(eqo("conf/sigmod/MaddenH02","S6PWjHRFORYJ")).
neg(eqo("conf/sigmod/MassariPSC95","AWM-7zzaO7wJ")).
neg(eqo("conf/sigmod/MelnikRB03","wfjeWtEY2NcJ")).
neg(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
neg(eqo("conf/sigmod/MistryRSR01","r62IMncHe0IJ")).
neg(eqo("conf/sigmod/MogiK96","4OiMyIIWl1UJ")).
neg(eqo("conf/sigmod/Mohan01","UPnLXp9wPKUJ")).
neg(eqo("conf/sigmod/Mohan01","aqeXgwGmvhgJ")).
neg(eqo("conf/sigmod/Mohan94","6rkYIagTMckJ")).
neg(eqo("conf/sigmod/Mohan99","AOfAOwaNqCYJ")).
neg(eqo("conf/sigmod/Mohan99","ml-oFmPRY6AJ")).
neg(eqo("conf/sigmod/MumickP94","oiVRpNXVOigJ")).
neg(eqo("conf/sigmod/MumickQM97","WkmtoFmIjVwJ")).
neg(eqo("conf/sigmod/MumickQM97","jsECrNuFiz8J")).
neg(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
neg(eqo("conf/sigmod/NguyenS96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057811")).
neg(eqo("conf/sigmod/Ojjeh99","8kTyf_8psWoJ")).
neg(eqo("conf/sigmod/Ojjeh99","afH6rYkjVgwJ")).
neg(eqo("conf/sigmod/Olson95","YDqWZ3SBMb4J")).
neg(eqo("conf/sigmod/PapadiasTFS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/PapadopoulosM98","icoWjIZ_6IIJ")).
neg(eqo("conf/sigmod/PaparizosACJLNPSWWY03","U4dofQxlfSIJ")).
neg(eqo("conf/sigmod/ParkCY95","ko0i4AzclBgJ")).
neg(eqo("conf/sigmod/ParkKKLPC98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083803%26type%3Dpdf")).
neg(eqo("conf/sigmod/Perna95","KhaCqOhjIUsJ")).
neg(eqo("conf/sigmod/ProcopiucJAM02","1_mk0EMIrwsJ")).
neg(eqo("conf/sigmod/RamakrishnanD98","LSNo-7ii1vEJ")).
neg(eqo("conf/sigmod/RamanH02","Bsn9nylMcXYJ")).
neg(eqo("conf/sigmod/RamanH02","RlH2shMtkfwJ")).
neg(eqo("conf/sigmod/RamaswamyK95","qP0jZsOBaCgJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","wKvSI4oZ8uEJ")).
neg(eqo("conf/sigmod/ReinwaldP98","ZQyBjtpbhvIJ")).
neg(eqo("conf/sigmod/ReinwaldP98","url:http://portal.acm.org/citation.cfm%3Fid%3D276304.276373%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D276304%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RossSS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D262763%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RoySSB00","OV6n7LhOe_cJ")).
neg(eqo("conf/sigmod/SagonasSW94","zOre6B5JTkoJ")).
neg(eqo("conf/sigmod/SalemBCL00","9EBKpmSLc_oJ")).
neg(eqo("conf/sigmod/Seshadri99","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D914832")).
neg(eqo("conf/sigmod/ShatdalN95","Mi53y5Rs0rEJ")).
neg(eqo("conf/sigmod/ShenNSHS03","eU-7sSXW5jEJ")).
neg(eqo("conf/sigmod/ShivakumarG97","z5tz9vybRmIJ")).
neg(eqo("conf/sigmod/ShuklaD00","xxoE3kJ73WsJ")).
neg(eqo("conf/sigmod/SrikantA96","v7i1i5y_nHgJ")).
neg(eqo("conf/sigmod/Stonebraker03","bG2fkpIapn4J")).
neg(eqo("conf/sigmod/Stonebraker03","url:http://portal.acm.org/citation.cfm%3Fid%3D582192")).
neg(eqo("conf/sigmod/SubramanianV98","jj8LgniKbsMJ")).
neg(eqo("conf/sigmod/Suciu99","url:http://portal.acm.org/citation.cfm%3Fid%3D645925%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SzalayGKT00","TUzhq1PjPsgJ")).
neg(eqo("conf/sigmod/SzalayGTKMRSv02","2-Tbb1SnVYkJ")).
neg(eqo("conf/sigmod/Team99","SeCy3GKewNgJ")).
neg(eqo("conf/sigmod/Vaskevitch94","W3O6iCnkCjoJ")).
neg(eqo("conf/sigmod/Wu99","Em19Rs4TqmIJ")).
neg(eqo("conf/sigmod/WuAA01","BdwCRmNO1FIJ")).
neg(eqo("conf/sigmod/WuAA01","sz3xAQyla9AJ")).
neg(eqo("conf/sigmod/YangWYH02","kTw6cwqa3qIJ")).
neg(eqo("conf/sigmod/ZaianeHLCC98","tFB9gJLG4_UJ")).
neg(eqo("conf/sigmod/ZhangMCMR02","rvZQMrCOQ1MJ")).
neg(eqo("conf/sigmod/ZhangZPTL03","g3sptFR4whsJ")).
neg(eqo("conf/sigmod/ZhouLP99","Vl7gY6FsOOYJ")).
neg(eqo("conf/sigmod/ZhouR02","iGekfyPYWk8J")).
neg(eqo("conf/sigmod/ZhouR02","tLpAE7ZSkLsJ")).
neg(eqo("conf/vldb/AdityaBCHNS02","2vzhAz4Yll4J")).
neg(eqo("conf/vldb/AggarwalHWY03","szlqyCesMpgJ")).
neg(eqo("conf/vldb/AgrawalK02","4weou-KgkM8J")).
neg(eqo("conf/vldb/AgrawalK02","RiQ-W5K0n6YJ")).
neg(eqo("conf/vldb/AgrawalK02","url:http://portal.acm.org/citation.cfm%3Fid%3D98749%26coll%3Dportal%26dl%3DACM")).
neg(eqo("conf/vldb/AgrawalKSX02","Ph7ZpmdNOPEJ")).
neg(eqo("conf/vldb/AgrawalSX01","hFd-mbjHDsoJ")).
neg(eqo("conf/vldb/AilamakiDHW99","dujCNb5_Dg4J")).
neg(eqo("conf/vldb/AksoyZF01","z6Z1hQYHTAMJ")).
neg(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","gndV1O-oEkMJ")).
neg(eqo("conf/vldb/AlonsoHST97","iRJV85kKVgwJ")).
neg(eqo("conf/vldb/AlsabtiRS97","nqOZsUydoQkJ")).
neg(eqo("conf/vldb/Baru96","B3unqvqyJrMJ")).
neg(eqo("conf/vldb/BawaBA03","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/BenediktCFRZZ02","zIzK75THxEEJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","qNTvSDkHYXIJ")).
neg(eqo("conf/vldb/BerckenS01","CvGGYMrKR2sJ")).
neg(eqo("conf/vldb/BerckenS01","GylkHu7AJ7sJ")).
neg(eqo("conf/vldb/BerckenS01","ONR-PgQGBRoJ")).
neg(eqo("conf/vldb/BerckenSW97","e5SJ3zgdwgEJ")).
neg(eqo("conf/vldb/BergerBSW03","X1UqyvzFlB8J")).
neg(eqo("conf/vldb/BernsteinPS99","HcCevkoobDsJ")).
neg(eqo("conf/vldb/BliujuteJSS98","PtcmzsfKYrsJ")).
neg(eqo("conf/vldb/BlokWZPAKJ01","25rE7-aq9WAJ")).
neg(eqo("conf/vldb/Brin95","e2tY_GZIEv8J")).
neg(eqo("conf/vldb/CabreraRH95","VSB1dhe6zOYJ")).
neg(eqo("conf/vldb/CandanALPH02","4zxRX5K-YSsJ")).
neg(eqo("conf/vldb/Carey00","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/CareyD96","47fE4F2kahEJ")).
neg(eqo("conf/vldb/CarinoJ98","rZcRXL6ueUMJ")).
neg(eqo("conf/vldb/ChakrabartiRS02","lkmdaFnW4eQJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","4zZ7Lxt4PPIJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","MRfEjJe2PzoJ")).
neg(eqo("conf/vldb/ChaudhuriGS95","AL-Tz4JxZFcJ")).
neg(eqo("conf/vldb/ChaudhuriS94","uRmyQBKcFAYJ")).
neg(eqo("conf/vldb/CherniackFZ01","okSXCoQ76_IJ")).
neg(eqo("conf/vldb/ChoG00","SByuGUSfTtYJ")).
neg(eqo("conf/vldb/CiliaHB02","e5SJ3zgdwgEJ")).
neg(eqo("conf/vldb/Cluet03","j9aM7gsxp4IJ")).
neg(eqo("conf/vldb/CooperSFHS01","0-4mW6TWJpUJ")).
neg(eqo("conf/vldb/Dasgupta96","hszebo7jiDoJ")).
neg(eqo("conf/vldb/DavisonG94","tPG--ikWjGcJ")).
neg(eqo("conf/vldb/Draluk01","0RaPx6Lka_IJ")).
neg(eqo("conf/vldb/DuttaDMRT00","ikJrOFv4o9QJ")).
neg(eqo("conf/vldb/DuttaDMRT00","q0Ovw6QUk3MJ")).
neg(eqo("conf/vldb/EvangelidisLS95","e5SJ3zgdwgEJ")).
neg(eqo("conf/vldb/FaloutsosG96","CETFNYmi9S0J")).
neg(eqo("conf/vldb/Fecteau95","LhjvKpDcJKUJ")).
neg(eqo("conf/vldb/FerrandinaMZFM95","QNDoZ9olwPkJ")).
neg(eqo("conf/vldb/FlorescuKLP97","kKwsIC5HmsUJ")).
neg(eqo("conf/vldb/FlorescuLSY99","xcgCeIl9qXUJ")).
neg(eqo("conf/vldb/FrohnLU94","zM422IjZcPgJ")).
neg(eqo("conf/vldb/GalanisWJD03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945725%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/GallersdorferN95","U8jfPCxfXicJ")).
neg(eqo("conf/vldb/Ganguly98","L4aXHaUW3cUJ")).
neg(eqo("conf/vldb/Ganguly98","bZiPDm6GqXwJ")).
neg(eqo("conf/vldb/GarofalakisIO98","Xm3ygCvkmN8J")).
neg(eqo("conf/vldb/GhoshPSH02","2dlOojuSNeIJ")).
neg(eqo("conf/vldb/GingrasL98","ZTPutS_MezMJ")).
neg(eqo("conf/vldb/GoldmanW97","l5GboAkBH1AJ")).
neg(eqo("conf/vldb/Graefe99","url:http://links.jstor.org/sici%3Fsici%3D0146-4949(196121%252F22)2%253A2%253C5%253A%2522PAPIF%253E2.CO%253B2-H")).
neg(eqo("conf/vldb/Graefe99","vP1Ipm2B9PYJ")).
neg(eqo("conf/vldb/GravanoG95","p6ro8VCQBwcJ")).
neg(eqo("conf/vldb/GravanoG97","VxiP2MuiMM0J")).
neg(eqo("conf/vldb/HaberIL95","0s6troo_Y1AJ")).
neg(eqo("conf/vldb/Hess96","pNReDInLSL0J")).
neg(eqo("conf/vldb/HeymannTKWRMF02","EAZ5Gz22bIUJ")).
neg(eqo("conf/vldb/HuangJR97","nBHS2BTx-GkJ")).
neg(eqo("conf/vldb/HvasshovdBT00","5bQQTE8d2acJ")).
neg(eqo("conf/vldb/HvasshovdBT00","af50lhGnD8gJ")).
neg(eqo("conf/vldb/ImielinskiB02","DqZEgt_ABcYJ")).
neg(eqo("conf/vldb/JagadishNSSK97","E8HHY_j2CigJ")).
neg(eqo("conf/vldb/JagadishNSSK97","zGTkptLuIuAJ")).
neg(eqo("conf/vldb/Johnson99","BEsA670lFdQJ")).
neg(eqo("conf/vldb/JohnsonS94","FqxbaJQMigIJ")).
neg(eqo("conf/vldb/KahveciS01","yCQf5tQglE0J")).
neg(eqo("conf/vldb/KamelF94","url:http://portal.acm.org/citation.cfm%3Fid%3D192593.197367%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D192593%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Multimedia%2520Conference%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/KeimH99","ExJOsE4lD8UJ")).
neg(eqo("conf/vldb/Kiessling02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066303%26type%3Dpdf")).
neg(eqo("conf/vldb/Kiessling02","xRyKVxRBTk8J")).
neg(eqo("conf/vldb/King02","lWI-TpbEklMJ")).
neg(eqo("conf/vldb/King02","mzxbJ2V6JlEJ")).
neg(eqo("conf/vldb/KnorrN99","oCPpSbHhL3IJ")).
neg(eqo("conf/vldb/KornMZ03","C69KCF-wlJMJ")).
neg(eqo("conf/vldb/Kornacker99","GIlUG9H3gUUJ")).
neg(eqo("conf/vldb/KornackerB95","IN_sibgHb9MJ")).
neg(eqo("conf/vldb/KoudasGGSV03","url:http://doi.wiley.com/10.1002/he.122")).
neg(eqo("conf/vldb/LabioG96","OmYc0wE1j4kJ")).
neg(eqo("conf/vldb/LakshmananPZ03","tcnjvKELfs0J")).
neg(eqo("conf/vldb/LakshmiZ98","WOjMKlT2eUAJ")).
neg(eqo("conf/vldb/LeeLWS97","4qdJwc-ZySsJ")).
neg(eqo("conf/vldb/LitwinNS94","kW0RhYOnStYJ")).
neg(eqo("conf/vldb/ManolescuFKXO00","299p7pOTQ1QJ")).
neg(eqo("conf/vldb/MargaritisFT01","b201QeqnlNkJ")).
neg(eqo("conf/vldb/MatthesS94","vLv480h49v8J")).
neg(eqo("conf/vldb/Mattos96","ZAhm4LqZfmcJ")).
neg(eqo("conf/vldb/MeoPC96","tAt5Nz4Mk9kJ")).
neg(eqo("conf/vldb/MillinerBP95","wPm8dQxiK5UJ")).
neg(eqo("conf/vldb/Mina98","ButmJWjGXusJ")).
neg(eqo("conf/vldb/MogiK95","OzgnxugGCWMJ")).
neg(eqo("conf/vldb/Mohan96","YLQPbM_N-icJ")).
neg(eqo("conf/vldb/MorimotoFMTY98","gQVLY8V1hekJ")).
neg(eqo("conf/vldb/MorimotoIM97","DPVBuf0A4z0J")).
neg(eqo("conf/vldb/MorishimaKKT01","pnNcrmhvUoMJ")).
neg(eqo("conf/vldb/NatsevCSLV01","4QHlHUAeliMJ")).
neg(eqo("conf/vldb/NetzCBF00","6GxdJ4jZUokJ")).
neg(eqo("conf/vldb/NgH94","5e8pCA8tKKAJ")).
neg(eqo("conf/vldb/NgH94","JA55PRiwrMQJ")).
neg(eqo("conf/vldb/Objectivity98","h4OQc4N4kjIJ")).
neg(eqo("conf/vldb/OoiYTJ01","y5rQJNMxx9gJ")).
neg(eqo("conf/vldb/OzsuLON01","Xm3ygCvkmN8J")).
neg(eqo("conf/vldb/PanRAMOHAMV02","-4UR6G523i0J")).
neg(eqo("conf/vldb/PapadiasT01","lp9YIXB3JBkJ")).
neg(eqo("conf/vldb/PardonA00","szlqyCesMpgJ")).
neg(eqo("conf/vldb/ParkMC02","jMRGwwxfXhUJ")).
neg(eqo("conf/vldb/PirotteZMY94","8s-SP8sAvQAJ")).
neg(eqo("conf/vldb/PottingerB03","1ambq2RMGMoJ")).
neg(eqo("conf/vldb/PottingerB03","Gq2yqOZGhBgJ")).
neg(eqo("conf/vldb/PoulovassilisS94","B87s9MFTeZ8J")).
neg(eqo("conf/vldb/Ramanan03","eU67ssiJ9GYJ")).
neg(eqo("conf/vldb/Rengarajan96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234900%26type%3Dpdf%26dl%3DGUIDE%26dl%3Dacm%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/RezendeS98","coNBTxEjQIUJ")).
neg(eqo("conf/vldb/RosenthalS94","rCxAgmY4ptEJ")).
neg(eqo("conf/vldb/SadriZZA01","mClzTQppJE4J")).
neg(eqo("conf/vldb/SakuraiYKU01","n1ixxafAD_EJ")).
neg(eqo("conf/vldb/SakuraiYKU01","ohDewW00evcJ")).
neg(eqo("conf/vldb/SakuraiYUK00","jpJMa9UNggoJ")).
neg(eqo("conf/vldb/Sarawagi00","QQy9ELvFcTEJ")).
neg(eqo("conf/vldb/Sarawagi95","0AwSc88rnUIJ")).
neg(eqo("conf/vldb/Sarawagi95","szMUNaxngCwJ")).
neg(eqo("conf/vldb/SavasereON95","enJfjyR_MLwJ")).
neg(eqo("conf/vldb/SchindlerAG03","BZwHppfVN6kJ")).
neg(eqo("conf/vldb/SchindlerAG03","JubkWSUFbbcJ")).
neg(eqo("conf/vldb/SeidlK97","JIe3yPnlZ7QJ")).
neg(eqo("conf/vldb/SeidlK97","o5V_jbeVe_IJ")).
neg(eqo("conf/vldb/Selinger02","GnZpu-fQzxEJ")).
neg(eqo("conf/vldb/Selinger02","OWe20vDyYO4J")).
neg(eqo("conf/vldb/Selinger02","j3yViR1Ob7YJ")).
neg(eqo("conf/vldb/SeshadriLR97","cL_OKIQDvmQJ")).
neg(eqo("conf/vldb/SeshadriLR97","ifOM4z6uxXUJ")).
neg(eqo("conf/vldb/ShahDR03","yjfWtiaDX0oJ")).
neg(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
neg(eqo("conf/vldb/ShanmugasundaramKSFF01","4lXbwhGTmPUJ")).
neg(eqo("conf/vldb/Shenker03","5yETsE57mzgJ")).
neg(eqo("conf/vldb/ShuklaDN98","zrMFWOX1h2MJ")).
neg(eqo("conf/vldb/SkubiszewskiV97","TkrlAK46U8kJ")).
neg(eqo("conf/vldb/SrikantA95","n-ftsEDVfcYJ")).
neg(eqo("conf/vldb/SrivastavaDJL96","01ZVDudF4WAJ")).
neg(eqo("conf/vldb/StanoiRAA01","SBpUQ0L7KUgJ")).
neg(eqo("conf/vldb/StohrMR00","9B_zuuJyou0J")).
neg(eqo("conf/vldb/Suciu96","8bcTG9YsbskJ")).
neg(eqo("conf/vldb/Suciu96","tJtSq968rwgJ")).
neg(eqo("conf/vldb/TamuraK99","HtKGRs3wrWYJ")).
neg(eqo("conf/vldb/TanSHCR01","Mw2MBOMo1_kJ")).
neg(eqo("conf/vldb/TheodoratosS97","jsapF3OoWXcJ")).
neg(eqo("conf/vldb/TianD03","gxVI54gVoEgJ")).
neg(eqo("conf/vldb/TorloneA03","url:http://portal.acm.org/citation.cfm%3Fid%3D1041410.1041433")).
neg(eqo("conf/vldb/WangHH00","casX2njLbDIJ")).
neg(eqo("conf/vldb/WangSG03","5nSsvC--8ioJ")).
neg(eqo("conf/vldb/WangZL99","E02lExYdRYwJ")).
neg(eqo("conf/vldb/WienerN94","PrUWsoySLGcJ")).
neg(eqo("conf/vldb/YanA94","8j5i7YJQnNAJ")).
neg(eqo("conf/vldb/YiF00","I0Kn3dzF4TgJ")).
neg(eqo("conf/vldb/ZengBNN01","0zdXnl9cQysJ")).
neg(eqo("conf/vldb/ZhouR03","iM6vRWljKpAJ")).
neg(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603869%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02c","RzsJoG-0KaIJ")).
neg(eqo("journals/sigmod/AbererCH02","IHPilG_MCDoJ")).
neg(eqo("journals/sigmod/Abiteboul99","OYOTbj4m7JYJ")).
neg(eqo("journals/sigmod/Aggarwal01","hUoyTdstE7sJ")).
neg(eqo("journals/sigmod/AlonsoCIM95","YBy_eZkJMxsJ")).
neg(eqo("journals/sigmod/BallMRZ02","q_A8Y8KY9WkJ")).
neg(eqo("journals/sigmod/BarbaraCJW01","5I2CrhUHaBsJ")).
neg(eqo("journals/sigmod/BarbaraCJW01","jGkspFTyYU8J")).
neg(eqo("journals/sigmod/BarbaraCJW01","nlna-xElM08J")).
neg(eqo("journals/sigmod/Bernstein98","0KiQzAIFlJkJ")).
neg(eqo("journals/sigmod/Bernstein98","1aXdu7iWXlQJ")).
neg(eqo("journals/sigmod/Bernstein98","eDKv7zEP0PIJ")).
neg(eqo("journals/sigmod/BernsteinHP00","L61_1TEGBLYJ")).
neg(eqo("journals/sigmod/Bestavros96","BIox2W-EPfEJ")).
neg(eqo("journals/sigmod/Bestavros96","NVgd3HFBZAQJ")).
neg(eqo("journals/sigmod/BiancheriPP01","iOxtnjbC4SEJ")).
neg(eqo("journals/sigmod/BichlerSZ98","hB-ZA0wX-fsJ")).
neg(eqo("journals/sigmod/Bohlen95","RMkZ2X-FCRsJ")).
neg(eqo("journals/sigmod/Bohlen95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BorgidaCS98","Z2Mk4a-kTDgJ")).
neg(eqo("journals/sigmod/Bussler02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564801%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ButtlerCCFHLPRX02","JScvAMYcsmoJ")).
neg(eqo("journals/sigmod/CaleroPR03","zWoRcQffsq8J")).
neg(eqo("journals/sigmod/Camps02","Fut7x82PlSgJ")).
neg(eqo("journals/sigmod/Camps96","UDBfc81ls0kJ")).
neg(eqo("journals/sigmod/CarmelMS01","Xx6kw0tCeQIJ")).
neg(eqo("journals/sigmod/Chang03","f5Wi6NxEki8J")).
neg(eqo("journals/sigmod/Chaudhri95","uMYecZGSCv4J")).
neg(eqo("journals/sigmod/ChaudhuriD97","GL8XEeYm7GsJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","k25oXJit8HoJ")).
neg(eqo("journals/sigmod/ChristoffelPSL98","zrMFWOX1h2MJ")).
neg(eqo("journals/sigmod/ChrysanthisSZ03","RalvsjDuKzsJ")).
neg(eqo("journals/sigmod/ChrysanthisSZ03","url:http://www.springerlink.com/index/M421871538132Q56.pdf")).
neg(eqo("journals/sigmod/ClementiniF00","6c3XQZ-_HDUJ")).
neg(eqo("journals/sigmod/Cruz00","xxoE3kJ73WsJ")).
neg(eqo("journals/sigmod/Darwen96","MyfePRxeiKoJ")).
neg(eqo("journals/sigmod/Darwen96","wpE1TRHh_KQJ")).
neg(eqo("journals/sigmod/Date03","url:http://doi.wiley.com/10.1002/tl.120")).
neg(eqo("journals/sigmod/DoanPSB97","xrTlYcyFKtwJ")).
neg(eqo("journals/sigmod/DogacDATKCD98","J6I08uuEyIcJ")).
neg(eqo("journals/sigmod/DomenigD99","y6gLSJhyXfcJ")).
neg(eqo("journals/sigmod/Domingo-FerrerH98","-t9ye_2wZFMJ")).
neg(eqo("journals/sigmod/EisenbergM00","yzlys0OQkt8J")).
neg(eqo("journals/sigmod/EisenbergM98","wgK6p4mDSIMJ")).
neg(eqo("journals/sigmod/EisenbergM99","e3s4OFTeBqwJ")).
neg(eqo("journals/sigmod/Etzion99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058166%26type%3Dpdf")).
neg(eqo("journals/sigmod/Fagin02","mr8XDkQ7adAJ")).
neg(eqo("journals/sigmod/Fagin02","vgDeuWNi7XYJ")).
neg(eqo("journals/sigmod/Fong95","kYl-9cV8gloJ")).
neg(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","5PisY7JvbzQJ")).
neg(eqo("journals/sigmod/Franklin00","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/Franklin00b","1Y-pKWumDNkJ")).
neg(eqo("journals/sigmod/Franklin00b","url:http://portal.acm.org/citation.cfm%3Fid%3D197445")).
neg(eqo("journals/sigmod/Franklin97","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin97a","fNVk1Vq2txEJ")).
neg(eqo("journals/sigmod/Franklin99","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin99a","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin99b","T-iPYaUf-iwJ")).
neg(eqo("journals/sigmod/Franklin99b","bxnOJqAOPiUJ")).
neg(eqo("journals/sigmod/GatziuJSV99","PPH2NlobSwsJ")).
neg(eqo("journals/sigmod/GatziuJSV99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219777%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/GlavitschSW94","pwf1p48HLJMJ")).
neg(eqo("journals/sigmod/GottlobKP03","O_11YxVvf8oJ")).
neg(eqo("journals/sigmod/Grohe02","a-FgFeI6GtEJ")).
neg(eqo("journals/sigmod/GroskyFS94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/GunopulosK01","Q0H0SDtHLQYJ")).
neg(eqo("journals/sigmod/GuptaHR97","uzpyy9XRpgYJ")).
neg(eqo("journals/sigmod/Hainaut03","hrHLKxM0BSYJ")).
neg(eqo("journals/sigmod/Halevy00","pnqY8ctPZYcJ")).
neg(eqo("journals/sigmod/Han98","qNLsbj_Fu5EJ")).
neg(eqo("journals/sigmod/Han98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D584455%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Hanson99","odFtqwn5ZVcJ")).
neg(eqo("journals/sigmod/HasanMV96","knAoAIpo7hYJ")).
neg(eqo("journals/sigmod/HasselbringHHKRRS00","DE_MK2KGbrQJ")).
neg(eqo("journals/sigmod/Hoffner03","9wQ6RWWcHRIJ")).
neg(eqo("journals/sigmod/Hoffner03","x7LOZSTegPwJ")).
neg(eqo("journals/sigmod/HummerLW02","rh75tsuGSm8J")).
neg(eqo("journals/sigmod/Huyn01","NVgd3HFBZAQJ")).
neg(eqo("journals/sigmod/Jagadish00","c54ZClhl5EMJ")).
neg(eqo("journals/sigmod/JainH94","wfjeWtEY2NcJ")).
neg(eqo("journals/sigmod/JajodiaBBKMSW97","6_FvrRYnxHYJ")).
neg(eqo("journals/sigmod/Jarke95","3kSb_ooS1cgJ")).
neg(eqo("journals/sigmod/Jarke95","pttiY8VSvogJ")).
neg(eqo("journals/sigmod/JenningsNF98","xHMtpgRoPcsJ")).
neg(eqo("journals/sigmod/Kim02","5lfXNkRahEgJ")).
neg(eqo("journals/sigmod/KlasS94","oNYOKYvjoKgJ")).
neg(eqo("journals/sigmod/Klein94","D1RdxKP6_6YJ")).
neg(eqo("journals/sigmod/Klein94","GufOZ5-h6CwJ")).
neg(eqo("journals/sigmod/KokkotosIPS95","OewAZ4AUDOQJ")).
neg(eqo("journals/sigmod/KoksalAD98","8KJ9XFv1ESAJ")).
neg(eqo("journals/sigmod/Kosch02","ODoq9cjzfogJ")).
neg(eqo("journals/sigmod/LeeF01","HWylSJiWUsgJ")).
neg(eqo("journals/sigmod/LinP96","i2KB69gKpXUJ")).
neg(eqo("journals/sigmod/Liu02a","fDWfHiQ6BR4J")).
neg(eqo("journals/sigmod/Liu02a","q5iyVZK8cE0J")).
neg(eqo("journals/sigmod/Liu03b","url:http://doi.wiley.com/10.1002/tl.7700")).
neg(eqo("journals/sigmod/LohmanGFS01","a2wqpKma5J4J")).
neg(eqo("journals/sigmod/Lomet98","6Bss5YygC2UJ")).
neg(eqo("journals/sigmod/Lomet98","SZwq84m3bGYJ")).
neg(eqo("journals/sigmod/Lomet98","url:http://ieeexplore.ieee.org/iel5/9217/29235/01320095.pdf%3Farnumber%3D1320095")).
neg(eqo("journals/sigmod/MaelbranckeO95","k00ik_MnlC8J")).
neg(eqo("journals/sigmod/Mani03","cvR8aKhqgUEJ")).
neg(eqo("journals/sigmod/McHughW97","moT0ba0vRKcJ")).
neg(eqo("journals/sigmod/MedskerCS95","url:http://www.springerlink.com/index/V65N53X12RV76426.pdf")).
neg(eqo("journals/sigmod/MeltonE01","-tZe06rxiUIJ")).
neg(eqo("journals/sigmod/MeltzerC98","-wQ-mpGIWdMJ")).
neg(eqo("journals/sigmod/MeltzerC98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130878%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Mendelzon00","_KhRTON1GyMJ")).
neg(eqo("journals/sigmod/Mendelzon98","Aiz7juadmHoJ")).
neg(eqo("journals/sigmod/MillerHHYHFP01","cKxVxbODsw0J")).
neg(eqo("journals/sigmod/Nascimento03","url:http://portal.acm.org/citation.cfm%3Fid%3D776985.776996%26dl%3Dportal%26dl%3DACM%26idx%3D776985%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/NgH95","qfohkpyTawoJ")).
neg(eqo("journals/sigmod/OrlandicLS02","eLf0eStn5G4J")).
neg(eqo("journals/sigmod/Ozsu02b","zYfyg0fCzEsJ")).
neg(eqo("journals/sigmod/PhatakSSS96","icq7-lEBur8J")).
neg(eqo("journals/sigmod/Qian95b","JHVWab3P4zIJ")).
neg(eqo("journals/sigmod/Qian97","fSKoYnVJbwwJ")).
neg(eqo("journals/sigmod/QuixSJ02","url:http://doi.wiley.com/10.1002/ace.78")).
neg(eqo("journals/sigmod/RamDD99","Zo7q8IpyCxYJ")).
neg(eqo("journals/sigmod/Richey95","Bn8s7u5T9SAJ")).
neg(eqo("journals/sigmod/Ritter98","4D2HQE6fXXEJ")).
neg(eqo("journals/sigmod/Rosenthal98","tbUQW4M8rrkJ")).
neg(eqo("journals/sigmod/Rosneblatt94","D1RdxKP6_6YJ")).
neg(eqo("journals/sigmod/Rosneblatt94","zkSIEVQ8lpwJ")).
neg(eqo("journals/sigmod/RossFLOSSVW00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossNO03","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/Roussopoulos98","XYBfAojuBzsJ")).
neg(eqo("journals/sigmod/SayginVC01","0PyiTSOYkoQJ")).
neg(eqo("journals/sigmod/SchmidtWKFCMB01","OhiGJ7Gy3KgJ")).
neg(eqo("journals/sigmod/SilberschatzSU96","F9DV57ns9yMJ")).
neg(eqo("journals/sigmod/Snodgrass02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603872%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass02b","m-l6e98xxOsJ")).
neg(eqo("journals/sigmod/Snodgrass03","pGcIRyDyFG8J")).
neg(eqo("journals/sigmod/Snodgrass94","QHLQZQwlbTsJ")).
neg(eqo("journals/sigmod/SommerGB02","mt8Q1YmVRkMJ")).
neg(eqo("journals/sigmod/TianDCZ02","OGsNK_g0ZYIJ")).
neg(eqo("journals/sigmod/TianDCZ02","btLl8c6wD1wJ")).
neg(eqo("journals/sigmod/TianDCZ02","yCSb05U8FHcJ")).
neg(eqo("journals/sigmod/WeikumSR03","Ltf5yQsl8sMJ")).
neg(eqo("journals/sigmod/Widom95a","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/Widom96","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Winslett01","zwax_59m8fgJ")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/citation.cfm%3Fid%3D1107499.1107519")).
neg(eqo("journals/sigmod/Winslett94","cehAAlTq4s8J")).
neg(eqo("journals/sigmod/Wong95","qrfBA723rYAJ")).
neg(eqo("journals/tods/BaekgaardM95","FlC-FF1hbbUJ")).
neg(eqo("journals/tods/BellNNS96","ilCT5UFnHxgJ")).
neg(eqo("journals/tods/BozkayaO99","6HcDunM0lJYJ")).
neg(eqo("journals/tods/Chen95","1px2xYEVMzwJ")).
neg(eqo("journals/tods/CliffordC94","5jeYhw8cpIAJ")).
neg(eqo("journals/tods/CliffordC94","HoDaq8PSs-UJ")).
neg(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","LHB0zsiIPFsJ")).
neg(eqo("journals/tods/GibbonsMP02","dKvepAPYBmcJ")).
neg(eqo("journals/tods/GutingBEJLSV00","cURCJR2xHE0J")).
neg(eqo("journals/tods/HjaltasonS99","wjKElSLd3lQJ")).
neg(eqo("journals/tods/LechtenborgerV03","E4fU9kpfXQsJ")).
neg(eqo("journals/tods/MamoulisP01","fXHqHRgpG8sJ")).
neg(eqo("journals/tods/MokNE96","8Dn4wESzjhoJ")).
neg(eqo("journals/tods/MuralidharS99","dKvepAPYBmcJ")).
neg(eqo("journals/tods/Revesz98","kLszvQykRXYJ")).
neg(eqo("journals/tods/ShashaLSV95","4K9b8PGZp6AJ")).
neg(eqo("journals/tods/ShashaLSV95","Zfdt0XzWDUIJ")).
neg(eqo("journals/tods/ShashaLSV95","lHS9z1A75f0J")).
neg(eqo("journals/tods/Snodgrass01","-5ehGhCEl4wJ")).
neg(eqo("journals/tods/Snodgrass01a","uOcOPUShONEJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/LD48KCXJWTCRACDL.pdf")).
neg(eqo("journals/tods/Subrahmanian94","KnKwXVSXN_wJ")).
neg(eqo("journals/tods/TaoSP03","2V2bnIgsY1kJ")).
neg(eqo("journals/tods/WolfsonJH97","VI7-LunfQ4UJ")).
neg(eqo("journals/tods/YanG94","q42rDNopMG0J")).
neg(eqo("journals/tods/ZaharioudakisCF97","3CIuTsEuOVcJ")).
neg(eqo("journals/tods/ZaharioudakisCF97","okwmZzzf-GoJ")).
neg(eqo("journals/vldb/AgrawalHK03","_NISJ-0lKiAJ")).
neg(eqo("journals/vldb/Antoshenkov97","C7yU79dhbqUJ")).
neg(eqo("journals/vldb/Atkinson00","KX9tZqfLvrgJ")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/08830355/2001/00000035/00000002/art00010%26unc%3D")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/13891286/2000/00000034/00000006/art00152%26unc%3D")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
neg(eqo("journals/vldb/Bertino94","6rU_Z_Sx1EgJ")).
neg(eqo("journals/vldb/Bertino94","YCNz-qSGj9kJ")).
neg(eqo("journals/vldb/BraumandlCKK00","ywe7qzk4E5MJ")).
neg(eqo("journals/vldb/C94","vQPQXPTTOOEJ")).
neg(eqo("journals/vldb/CatarciSC97","IIykL2NeD3UJ")).
neg(eqo("journals/vldb/ChuaCL03","MY0lTfhxnr4J")).
neg(eqo("journals/vldb/ConstantopoulosJMV95","x9bmOZxOlE8J")).
neg(eqo("journals/vldb/EvangelidisS97","EbGZKQPyH_4J")).
neg(eqo("journals/vldb/Halevy01","hrsc329vaaMJ")).
neg(eqo("journals/vldb/Halevy02","url:http://www.springerlink.com/index/6UEYKJ4UQTK18H6D.pdf")).
neg(eqo("journals/vldb/Han98","qNLsbj_Fu5EJ")).
neg(eqo("journals/vldb/MaratheS02","AAfuuc1tcoUJ")).
neg(eqo("journals/vldb/MaratheS02","aU271wSEEq0J")).
neg(eqo("journals/vldb/MedjahedBE03","Jml6flDOu7QJ")).
neg(eqo("journals/vldb/MehtaD97","4N472VSotmMJ")).
neg(eqo("journals/vldb/MehtaGPN98","JDU5tKGZrKMJ")).
neg(eqo("journals/vldb/Ozsu03","eZwzDZ7QhzoJ")).
neg(eqo("journals/vldb/ScheuermannWZ98","HWVg35YWaVsJ")).
neg(eqo("journals/vldb/ShegalovGW01","url:http://www.springerlink.com/index/V567337310361767.pdf")).
neg(eqo("journals/vldb/ShyyASL96","cExZWIT9LZcJ")).
neg(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
neg(eqo("journals/vldb/WhiteD95","qeHXdJ2x7eMJ")).
pos(eqo("conf/sigmod/AbiteboulCM95","4GT0Krd9RP0J")).
pos(eqo("conf/sigmod/AboulnagaC99","WWaxLMIptTMJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","_-yXA5HLnqoJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","s064OghlyIUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","t8KDgCSg9RIJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/Adelberg98","5I0ArBmDRcEJ")).
pos(eqo("conf/sigmod/Adelberg98","ahVfYoqGq6gJ")).
pos(eqo("conf/sigmod/Aggarwal02","tK1_3wGUIHsJ")).
pos(eqo("conf/sigmod/AgichteinGV01","GDoFPiEzEhQJ")).
pos(eqo("conf/sigmod/AgrawalCD02","iABZEL2Zoz8J")).
pos(eqo("conf/sigmod/AmbiteABKMMMPT98","YAkpVC1qgaIJ")).
pos(eqo("conf/sigmod/AndersonBKW98","H6eMdbXATmkJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","GFTU2PvKY_gJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","K1ZdQsRoNloJ")).
pos(eqo("conf/sigmod/AvnurHLORRRW98","bEu_llku9NMJ")).
pos(eqo("conf/sigmod/BarbosaMKL02","ueKnwQCE3nIJ")).
pos(eqo("conf/sigmod/BarbosaMKL02","wO-iR4jRq0UJ")).
pos(eqo("conf/sigmod/BergstraesserBPS99","4Ha7Bs5Vq3MJ")).
pos(eqo("conf/sigmod/BilirisDGJR94","lG6uSYhEGnQJ")).
pos(eqo("conf/sigmod/BorkarDS01","nsoA6Gcc_jsJ")).
pos(eqo("conf/sigmod/BornhovdAKMPR03","4qtu0-tW0IcJ")).
pos(eqo("conf/sigmod/BraumandlKK99","4fjXoCHhe1kJ")).
pos(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","_1drQdYrtmsJ")).
pos(eqo("conf/sigmod/BreunigKKS01","LxyVmHubIfUJ")).
pos(eqo("conf/sigmod/BreunigKKS01","h-tyLTytlh4J")).
pos(eqo("conf/sigmod/Brewer98","k4UNrsGeUuAJ")).
pos(eqo("conf/sigmod/BrinMUT97","A7Mm5kFK3zwJ")).
pos(eqo("conf/sigmod/BrinMUT97","CnTgirrsL3EJ")).
pos(eqo("conf/sigmod/BrinMUT97","swPpkmm8SdYJ")).
pos(eqo("conf/sigmod/BrunoKS02","GahdNMZNCWgJ")).
pos(eqo("conf/sigmod/BunemanDHS96","AtUsoMh8rY4J")).
pos(eqo("conf/sigmod/BunemanDHS96","rNVPCLfguuMJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","Zkgpz6ZsutsJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","xc1E6MOfP80J")).
pos(eqo("conf/sigmod/Cattell94","zSoTbEtLuqEJ")).
pos(eqo("conf/sigmod/CeriFP98","iUGa3pKj-20J")).
pos(eqo("conf/sigmod/ChakrabartiDI98","y88lIE5sgrwJ")).
pos(eqo("conf/sigmod/Chakravarthy97","pCsAI2xXTPoJ")).
pos(eqo("conf/sigmod/ChangG99","8Yt1Mba9-wQJ")).
pos(eqo("conf/sigmod/ChawatheG97","5O88Bum19wAJ")).
pos(eqo("conf/sigmod/ChawatheG97","oHUiSrycKdgJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","Xz0ZPMLOwcgJ")).
pos(eqo("conf/sigmod/ChenGMV02","IqV3EploPP4J")).
pos(eqo("conf/sigmod/ChenR94","WJDiW8pl0OcJ")).
pos(eqo("conf/sigmod/CherniackZ98","7DFhNMAE13QJ")).
pos(eqo("conf/sigmod/CherniackZ98","_wJZsVYdrr8J")).
pos(eqo("conf/sigmod/ChoG00","7TNK4262ozwJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","-LUnZ7Zwr1QJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","Xssa5A6mJ1UJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","hEOX0Vu4-JcJ")).
pos(eqo("conf/sigmod/Cohen98a","qfD_kxYt-dsJ")).
pos(eqo("conf/sigmod/ColeG94","z_W8jZ203sUJ")).
pos(eqo("conf/sigmod/CookKWZ96","5MTgNlhnyTgJ")).
pos(eqo("conf/sigmod/CorralMTV00","TsShfxPwF6YJ")).
pos(eqo("conf/sigmod/CranorGJSS02","Up9QQITiHzAJ")).
pos(eqo("conf/sigmod/DeutschFS99","2lypQEgzfb8J")).
pos(eqo("conf/sigmod/DeutschFS99","SR_yVgZnYpMJ")).
pos(eqo("conf/sigmod/DeutschFS99","SYaXErlVlcAJ")).
pos(eqo("conf/sigmod/DeutschFS99","XrybyHOI16kJ")).
pos(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
pos(eqo("conf/sigmod/DeutschFS99","twQNwr-jFmoJ")).
pos(eqo("conf/sigmod/DoRD99","Rviij1nqEcoJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","AgBMhm_0uEIJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","fsa72WmA67kJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","gt_wY6mYF_kJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","zf5eI7As5kAJ")).
pos(eqo("conf/sigmod/FaginKS03","dOY1djmoy04J")).
pos(eqo("conf/sigmod/FaloutsosL95","43b8e16YZlEJ")).
pos(eqo("conf/sigmod/FaloutsosL95","56AknoQlFB0J")).
pos(eqo("conf/sigmod/FaloutsosL95","I0Kn3dzF4TgJ")).
pos(eqo("conf/sigmod/FaloutsosL95","RLjlTtFM36IJ")).
pos(eqo("conf/sigmod/FaloutsosL95","dRjSn10qk9wJ")).
pos(eqo("conf/sigmod/FaloutsosL95","j0EcM-BvshwJ")).
pos(eqo("conf/sigmod/FaloutsosL95","vbvO-dB6wiIJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","4bG39HmGrAQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","ek26aiEheesJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","N9NHi5y3K38J")).
pos(eqo("conf/sigmod/FernandezFKLS98","W3H34LBUMtoJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","rgk1HYJbTNEJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","x-Xcm921UTMJ")).
pos(eqo("conf/sigmod/FernandezMS01","JYYcPQLrBw8J")).
pos(eqo("conf/sigmod/FreireHRRS02","1p-q7eofLWIJ")).
pos(eqo("conf/sigmod/FreireHRRS02","Pg-vbrBME1cJ")).
pos(eqo("conf/sigmod/GaoW02","PZTESZecfnQJ")).
pos(eqo("conf/sigmod/GarofalakisGRSS00","5uvR4kU1UOoJ")).
pos(eqo("conf/sigmod/GatziuGD95","jC39CJrWKr8J")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/GorelikWD94","X2URoOMjJv4J")).
pos(eqo("conf/sigmod/GorelikWD94","h10FxbLW6zAJ")).
pos(eqo("conf/sigmod/GravanoCGP97","8jTTpoQc2RkJ")).
pos(eqo("conf/sigmod/GravanoCGP97","FHEK09LJKfwJ")).
pos(eqo("conf/sigmod/GravanoCGP97","hs8rOlHD4K4J")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/GraySSU03","NnKrsx4j4pkJ")).
pos(eqo("conf/sigmod/GriffinL95","6QZGeKna5lgJ")).
pos(eqo("conf/sigmod/GriffinL95","RuYYq5xDgNYJ")).
pos(eqo("conf/sigmod/GrossmanHQ95","Z_kXgQsN0W0J")).
pos(eqo("conf/sigmod/GrossmanQ94","yjqdBeNw5WoJ")).
pos(eqo("conf/sigmod/GuhaRS98","-L22HvEHwH8J")).
pos(eqo("conf/sigmod/GuhaRS98","Dux-7sONElwJ")).
pos(eqo("conf/sigmod/GuhaRS98","LoR0K8QRGkgJ")).
pos(eqo("conf/sigmod/GuhaRS98","WHHfHdG_ougJ")).
pos(eqo("conf/sigmod/GuhaRS98","YCjIP8n8UnMJ")).
pos(eqo("conf/sigmod/GuhaRS98","ZStDO0kXD54J")).
pos(eqo("conf/sigmod/GuhaRS98","btOlpr6NZoIJ")).
pos(eqo("conf/sigmod/GuhaRS98","oWVyLUIy9JwJ")).
pos(eqo("conf/sigmod/GunopulosD01","LBp-UtmfcScJ")).
pos(eqo("conf/sigmod/GunopulosD01","kneUxV6J3nQJ")).
pos(eqo("conf/sigmod/GunopulosD01","mnUzHNE5eF0J")).
pos(eqo("conf/sigmod/GuoSBS03","p_PDgjVRUS4J")).
pos(eqo("conf/sigmod/GuptaMR95","2GUwicKtWTUJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","uPHrOdEDjlEJ")).
pos(eqo("conf/sigmod/HanFHCC94","dvmROCT52KoJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","-RzBfKSBxpgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","V6KNPMKdyagJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","cnjY261oL-4J")).
pos(eqo("conf/sigmod/HarinarayanRU96","ofxLw3VrJB8J")).
pos(eqo("conf/sigmod/HarinarayanRU96","sLvivSi__BcJ")).
pos(eqo("conf/sigmod/Hellerstein94","r4adn1YKOFIJ")).
pos(eqo("conf/sigmod/HellersteinHW97","8w5kj2G2c_oJ")).
pos(eqo("conf/sigmod/HellersteinHW97","K6752bGaG2QJ")).
pos(eqo("conf/sigmod/HernandezMHYHT01","pOFhgBVYVTkJ")).
pos(eqo("conf/sigmod/Hidber99","HkBKH9ZUJEcJ")).
pos(eqo("conf/sigmod/HinneburgKW02","VWd7jhLXfV0J")).
pos(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
pos(eqo("conf/sigmod/HullZ96","rI-T6ppfITQJ")).
pos(eqo("conf/sigmod/HungYK96","3gpc7dPy-ucJ")).
pos(eqo("conf/sigmod/HungYK96","P6VVKZUo4pgJ")).
pos(eqo("conf/sigmod/HwangLYMMGCSS94","AWah9GLEFTAJ")).
pos(eqo("conf/sigmod/IlyasRLGL03","qCnvlNwYp6cJ")).
pos(eqo("conf/sigmod/ImielinskiV95","dKMRgoNRQDgJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","U04OC6OSBT0J")).
pos(eqo("conf/sigmod/IoannidisLANT97","bbr1Xk0-hH8J")).
pos(eqo("conf/sigmod/JagadishJOT01","OM7n6h8R8CoJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","p-m7MMOS2aUJ")).
pos(eqo("conf/sigmod/KalnisNOPT02","Qyeg-VuH-2kJ")).
pos(eqo("conf/sigmod/KanthRA02","RgDMwqhT30wJ")).
pos(eqo("conf/sigmod/Keim99","GBZiTCbChZQJ")).
pos(eqo("conf/sigmod/KimC03","BWV2Oys1VXsJ")).
pos(eqo("conf/sigmod/KornackerSH98","bV8_CDuW2gMJ")).
pos(eqo("conf/sigmod/KriegelBKPS03","i0c65loyE60J")).
pos(eqo("conf/sigmod/KriegelBKPS03","tsqBH6P4jMcJ")).
pos(eqo("conf/sigmod/KrishnamurthyBN99","qS4jhfgPbm8J")).
pos(eqo("conf/sigmod/LamCKNH01","8hdQohffF48J")).
pos(eqo("conf/sigmod/LangS01","OubIayl1628J")).
pos(eqo("conf/sigmod/LarsonG03","14VyjJ0mnBMJ")).
pos(eqo("conf/sigmod/LazaridisM01","IvMJ4bK708kJ")).
pos(eqo("conf/sigmod/LehnerSPC00","HQRcmyswIHcJ")).
pos(eqo("conf/sigmod/LehnerSPC00","UFKz6Q0wVi4J")).
pos(eqo("conf/sigmod/LiefkeS00","SvVh9QQcgDwJ")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/LuMSS95","Kk87yanaI1AJ")).
pos(eqo("conf/sigmod/MaddenSHR02","kjtuCATx_uoJ")).
pos(eqo("conf/sigmod/MaddenSHR02","zobnUjtYSe8J")).
pos(eqo("conf/sigmod/MeccaAMMS98","I-fmtPvluKEJ")).
pos(eqo("conf/sigmod/MelnikRB03","HhdW2CaIIZwJ")).
pos(eqo("conf/sigmod/MelnikRB03","bkpTodGryDAJ")).
pos(eqo("conf/sigmod/MelnikRB03","ntcjTU3hQiUJ")).
pos(eqo("conf/sigmod/Moore95","uh57sQuxYuIJ")).
pos(eqo("conf/sigmod/MotakisZ97","8hMkXAIa8vEJ")).
pos(eqo("conf/sigmod/MotakisZ97","e8OIK3dEo6EJ")).
pos(eqo("conf/sigmod/MumickQM97","c_n0wQe1FhAJ")).
pos(eqo("conf/sigmod/NatsevRS99","Y3nejQSVKnUJ")).
pos(eqo("conf/sigmod/NguyenACP01","VCiXh8qcrIMJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","Ljpkq7MPqeEJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","O-TrhFwhKM8J")).
pos(eqo("conf/sigmod/ONeilQ97","lMTodOXT45MJ")).
pos(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
pos(eqo("conf/sigmod/OriaOILY00","9SbEzfHLSooJ")).
pos(eqo("conf/sigmod/PadmanabhanBMCH03","wI75uFSs0bwJ")).
pos(eqo("conf/sigmod/PapadiasTSE95","PogZLKV_bIsJ")).
pos(eqo("conf/sigmod/PatelD96","SW5bcXhie_4J")).
pos(eqo("conf/sigmod/PatelD96","nmTGteLy8NAJ")).
pos(eqo("conf/sigmod/PatelD96","oPdpBiAjcisJ")).
pos(eqo("conf/sigmod/RafieiM97","N-kEDX56ek0J")).
pos(eqo("conf/sigmod/RafieiM97","UBACGF9cQ2UJ")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/RajagopalanML98","iUtn70TmoZIJ")).
pos(eqo("conf/sigmod/RajagopalanML98","wO6VeeLIXAsJ")).
pos(eqo("conf/sigmod/RaoR98","WlSXiMaxGlQJ")).
pos(eqo("conf/sigmod/ReveszCKLLW00","qxShx7aNiuEJ")).
pos(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
pos(eqo("conf/sigmod/RiedewaldAA02","nQvBo5KHITYJ")).
pos(eqo("conf/sigmod/SeshadriLR94","60I0j0qUHVYJ")).
pos(eqo("conf/sigmod/ShashaB02","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/ShashaB02a","3HUnvGuXtZEJ")).
pos(eqo("conf/sigmod/ShashaB02a","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/Sheth95","JrkRUbNsLwEJ")).
pos(eqo("conf/sigmod/SistlaW95","J3XZUbzCxjEJ")).
pos(eqo("conf/sigmod/SistlaW95","gLjn4f4f63wJ")).
pos(eqo("conf/sigmod/SistlaW95","voZSiqM4epgJ")).
pos(eqo("conf/sigmod/Smith01","WfKk1v3VamgJ")).
pos(eqo("conf/sigmod/SrikantA96","Cm66C3yYtdgJ")).
pos(eqo("conf/sigmod/SrikantA96","OASIyc-vi9EJ")).
pos(eqo("conf/sigmod/SrikantA96","ZBuWjiVOE94J")).
pos(eqo("conf/sigmod/SrikantA96","oAlX0rVQqlIJ")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","0HlMHEPJRH4J")).
pos(eqo("conf/sigmod/TatarinovVBSSZ02","gYWmOPwa7mwJ")).
pos(eqo("conf/sigmod/Team99","DphRY0uPqi8J")).
pos(eqo("conf/sigmod/Team99","bcR9TErOrKQJ")).
pos(eqo("conf/sigmod/ThaperGIK02","6a1G1MBvuWcJ")).
pos(eqo("conf/sigmod/TheobaldW02","w5_HkketH-wJ")).
pos(eqo("conf/sigmod/Ullman03","TabFkjNTLMsJ")).
pos(eqo("conf/sigmod/VriesMNK02","dVn0Led5JLAJ")).
pos(eqo("conf/sigmod/WaasG00","xnoCdNeQykAJ")).
pos(eqo("conf/sigmod/YanMHF01","z1HqFeqNEjgJ")).
pos(eqo("conf/sigmod/YangM97","57m7NniyTrkJ")).
pos(eqo("conf/sigmod/YangM97","TUQ51ASLNI0J")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/ZhangRL96","1ms09_UeEH4J")).
pos(eqo("conf/sigmod/ZhangRL96","8UbrDL0jsOYJ")).
pos(eqo("conf/sigmod/ZhangRL96","ICoe8GLPWMIJ")).
pos(eqo("conf/sigmod/ZhangRL96","Koo3549nY2kJ")).
pos(eqo("conf/sigmod/ZhangRL96","NzUcyD-oMpQJ")).
pos(eqo("conf/sigmod/ZhangRL96","Q4JDSTBf5_oJ")).
pos(eqo("conf/sigmod/ZhangRL96","SQ02NlE587YJ")).
pos(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
pos(eqo("conf/sigmod/ZhangRL96","yoMojXfArHAJ")).
pos(eqo("conf/sigmod/ZhaoDN97","b-Va1c3t13gJ")).
pos(eqo("conf/sigmod/ZhaoDN97","chYdQDE8cPsJ")).
pos(eqo("conf/sigmod/ZhouLP99","0OwKmPjQpd0J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","jugePLZ8yKcJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/AggarwalHWY03","yFMUnqONfGwJ")).
pos(eqo("conf/vldb/AgrawalS94","2Z_X3zsf4CoJ")).
pos(eqo("conf/vldb/AgrawalS94","551mHiCJRjoJ")).
pos(eqo("conf/vldb/AgrawalS94","E7cKUUkwc1kJ")).
pos(eqo("conf/vldb/AgrawalS94","XzSqN32OqgMJ")).
pos(eqo("conf/vldb/AgrawalS94","cIJQ0qxrkMIJ")).
pos(eqo("conf/vldb/AgrawalS94","ujWZNcj2qkgJ")).
pos(eqo("conf/vldb/AilamakiDHS01","265Cu1i6gvQJ")).
pos(eqo("conf/vldb/AilamakiDHS01","7yQ28_L2uioJ")).
pos(eqo("conf/vldb/AilamakiDHS01","gUJrOpj89tQJ")).
pos(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","-FP8UTv_smkJ")).
pos(eqo("conf/vldb/AmsalegFG95","-9bXTTM_M4cJ")).
pos(eqo("conf/vldb/AmsalegFG95","F0a2V6Okkn0J")).
pos(eqo("conf/vldb/AmsalegFG95","XRTrTxnxvdYJ")).
pos(eqo("conf/vldb/AnanthakrishnaCG02","SByuGUSfTtYJ")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/vldb/ArgePRSV98","A5Eiwdh71m0J")).
pos(eqo("conf/vldb/ArgePRSV98","c3yObnVI65cJ")).
pos(eqo("conf/vldb/AshwinGG02","YiJojduGXXkJ")).
pos(eqo("conf/vldb/AshwinGG02","mObyCD3Jw0EJ")).
pos(eqo("conf/vldb/AtzeniMM97","HUIG38FY6zEJ")).
pos(eqo("conf/vldb/AtzeniMM97","QLI_xo-fBp4J")).
pos(eqo("conf/vldb/AtzeniMM97","nzG3d6r0BmcJ")).
pos(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
pos(eqo("conf/vldb/BaralisPT97","Cp7_R7yjRjQJ")).
pos(eqo("conf/vldb/BaralisPT97","tyNO4U-fmrIJ")).
pos(eqo("conf/vldb/BerchtoldKK96","2EJhvKyW8AoJ")).
pos(eqo("conf/vldb/BerchtoldKK96","G__T5t9i4ZwJ")).
pos(eqo("conf/vldb/BerchtoldKK96","S-aEcHjpLBMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WcxbHqh4FfkJ")).
pos(eqo("conf/vldb/BerckenSW97","NCWOdJkvqPoJ")).
pos(eqo("conf/vldb/BerckenSW97","w90oK0t46SAJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","L2c8XblCSicJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
pos(eqo("conf/vldb/BestavrosB95","LDv4my6gWJQJ")).
pos(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
pos(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
pos(eqo("conf/vldb/BouganimCDDGS99","Ult4nmnmJp8J")).
pos(eqo("conf/vldb/Brin95","CuCm_rmA28cJ")).
pos(eqo("conf/vldb/Brin95","dXegp-RmzXEJ")).
pos(eqo("conf/vldb/Brin95","ytOUXklnAooJ")).
pos(eqo("conf/vldb/CareyD96","g8jnRVyQukAJ")).
pos(eqo("conf/vldb/CareyD96","ulDUAu6vLr4J")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("conf/vldb/CarinoO98","iaOLRaqTWmEJ")).
pos(eqo("conf/vldb/CasatiDGS01","bFnDGrZ_4voJ")).
pos(eqo("conf/vldb/ChaHKK01","VyOa5Uqsj6AJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","-2Ib1nqgXbcJ")).
pos(eqo("conf/vldb/ChakrabartiSST00","eMCZN8ZXNJIJ")).
pos(eqo("conf/vldb/ChaudhuriG99","yniboichufIJ")).
pos(eqo("conf/vldb/ChenHWW02","kgXRJZKRxZQJ")).
pos(eqo("conf/vldb/ChenJLP03","BGcx_nZKM4wJ")).
pos(eqo("conf/vldb/ChenJLP03","p7wumIMn_2oJ")).
pos(eqo("conf/vldb/CherniackFZ01","WHWa6vBvwJ0J")).
pos(eqo("conf/vldb/ChirkovaHS01","NdmocXlpq9QJ")).
pos(eqo("conf/vldb/CosleyLP02","22ZTae8fNuIJ")).
pos(eqo("conf/vldb/CosleyLP02","BTalXWt3faUJ")).
pos(eqo("conf/vldb/CowleyP00","scg5F1reod0J")).
pos(eqo("conf/vldb/DattaDTVRF01","8_5A88ESaQ0J")).
pos(eqo("conf/vldb/DattaDTVRF01","rDObsYKVroMJ")).
pos(eqo("conf/vldb/DiaoF03","Crt1JZ1eEj0J")).
pos(eqo("conf/vldb/DidriksenGD95","0TNJ5d1tfkEJ")).
pos(eqo("conf/vldb/DillKMRST01","eZoS-yciSRsJ")).
pos(eqo("conf/vldb/DingGS00","I5fV3jpcrmAJ")).
pos(eqo("conf/vldb/Duranti01","gQW6iYG5Vh0J")).
pos(eqo("conf/vldb/EvangelidisLS95","3TOqLeL1G64J")).
pos(eqo("conf/vldb/EvangelidisLS95","EbGZKQPyH_4J")).
pos(eqo("conf/vldb/FaloutsosJS97","YOmjd7tKrWgJ")).
pos(eqo("conf/vldb/FegarasE01","pinPEM3Rvm0J")).
pos(eqo("conf/vldb/GardarinGT95","uMkO2KGQJwwJ")).
pos(eqo("conf/vldb/GardarinST96","BBKhPPAqasIJ")).
pos(eqo("conf/vldb/GardarinST96","OHR5iQWPuyYJ")).
pos(eqo("conf/vldb/GardarinST96","q0K1yN3kIs4J")).
pos(eqo("conf/vldb/Gibbons01","tYtl6ZxQ-_YJ")).
pos(eqo("conf/vldb/GilbertKMS02","kxGdQhvpi_sJ")).
pos(eqo("conf/vldb/GingrasL98","VSBQl2qbF8UJ")).
pos(eqo("conf/vldb/GoyalHSS95","2sGH4SLcdL4J")).
pos(eqo("conf/vldb/GoyalHSS95","fPgtEqv986IJ")).
pos(eqo("conf/vldb/GraefeBC98","v-kvo2hnsgkJ")).
pos(eqo("conf/vldb/Greco98","CCr8CUlHeNsJ")).
pos(eqo("conf/vldb/GuptaM96","I0Kfdt6sh0gJ")).
pos(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
pos(eqo("conf/vldb/HageJPST03","6dAWUHYKqFUJ")).
pos(eqo("conf/vldb/HageJPST03","xDDdtO9n_pwJ")).
pos(eqo("conf/vldb/Hammond96","LDxiVdRU6EEJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","7y9SomIIAG0J")).
pos(eqo("conf/vldb/HuebschHLLSS03","B_Gmn8T4IDQJ")).
pos(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
pos(eqo("conf/vldb/HuntAI01","0GT_dHqK5roJ")).
pos(eqo("conf/vldb/IshikawaSF98","V3c_ivUAs34J")).
pos(eqo("conf/vldb/JagadishKNS99","GtXc02EJjCgJ")).
pos(eqo("conf/vldb/JagatheesanMPW03","InqySB8bkKkJ")).
pos(eqo("conf/vldb/Jamil97","tLpAE7ZSkLsJ")).
pos(eqo("conf/vldb/JensenL01","yUDkYbmDTXIJ")).
pos(eqo("conf/vldb/KalusD95","r1xwwqWr2K0J")).
pos(eqo("conf/vldb/KeimH99","28GZ8M1ZPVYJ")).
pos(eqo("conf/vldb/KemperK94","qUfWV4VVxegJ")).
pos(eqo("conf/vldb/KemperK94","yt-MxJKEsL4J")).
pos(eqo("conf/vldb/KochBG03","mZNcc1O3Nl8J")).
pos(eqo("conf/vldb/KochBG03","xCbXlJHLR48J")).
pos(eqo("conf/vldb/KornMS02","mClzTQppJE4J")).
pos(eqo("conf/vldb/KornSFSP96","VL_cnRotMQcJ")).
pos(eqo("conf/vldb/KornSFSP96","XRtCyfosWhMJ")).
pos(eqo("conf/vldb/KumarKA97","EhTWppk6No8J")).
pos(eqo("conf/vldb/LakshmananSS96","0VHtbuWJCQUJ")).
pos(eqo("conf/vldb/LakshmananSS96","AVyGNVp-ENcJ")).
pos(eqo("conf/vldb/LakshmananSS96","UPYyrF0ofUUJ")).
pos(eqo("conf/vldb/LakshmananSS96","XPjpq3h5BhUJ")).
pos(eqo("conf/vldb/LakshmananSS96","Yuccv3uXgUQJ")).
pos(eqo("conf/vldb/LakshmananSS99","RSpmu6WtYBMJ")).
pos(eqo("conf/vldb/LakshmiZ98","3XwLBVHUBvAJ")).
pos(eqo("conf/vldb/LakshmiZ98","QmXB6EKu-pYJ")).
pos(eqo("conf/vldb/LeeLWS97","3k61gi_ld_UJ")).
pos(eqo("conf/vldb/LeeLWS97","fHKhYR-6ksMJ")).
pos(eqo("conf/vldb/LevySSZ94","MtScC-fTWCEJ")).
pos(eqo("conf/vldb/LiRS99","Bf44yXvb6EAJ")).
pos(eqo("conf/vldb/LimWPVP02","9kl_hTyQtmQJ")).
pos(eqo("conf/vldb/Lindsay95","RIpWKrKho0MJ")).
pos(eqo("conf/vldb/LometT95","7KawVN8Kj10J")).
pos(eqo("conf/vldb/LuSL95","AvfsXnSTA24J")).
pos(eqo("conf/vldb/LuSL95","xGK3seG0Mn4J")).
pos(eqo("conf/vldb/LuTD95","qX-uYKXVk7EJ")).
pos(eqo("conf/vldb/ManolescuFK01","O8eIfc2eSjcJ")).
pos(eqo("conf/vldb/ManolescuFK01","ckjlnFHOwd8J")).
pos(eqo("conf/vldb/ManolescuFK01","inDI0X1MJG4J")).
pos(eqo("conf/vldb/MaratheS97","vBUROMKYmQYJ")).
pos(eqo("conf/vldb/MarronL01","9z2MfdOAAdIJ")).
pos(eqo("conf/vldb/MarronL01","d7tnjNELumMJ")).
pos(eqo("conf/vldb/MeoPC96","SNIbAV2EN0MJ")).
pos(eqo("conf/vldb/MeoPC96","p2pzLkGmO9wJ")).
pos(eqo("conf/vldb/Mohan01","6rkYIagTMckJ")).
pos(eqo("conf/vldb/Novaretti01","tZtnFoH5lY0J")).
pos(eqo("conf/vldb/OuzzaniAB94","kZaX18AOqfQJ")).
pos(eqo("conf/vldb/OuzzaniAB94","p0TLPzS0K4oJ")).
pos(eqo("conf/vldb/PalpanasSCP02","nlh2WXZT3VIJ")).
pos(eqo("conf/vldb/ParkMC02","WFmae47kgN4J")).
pos(eqo("conf/vldb/PedersenJD99","sAUncbolYJ8J")).
pos(eqo("conf/vldb/PellenkoftLK97","793XPMTdcBEJ")).
pos(eqo("conf/vldb/PopaVMHF02","qJ4lzBFzjdgJ")).
pos(eqo("conf/vldb/RahmM95","6ioboOxJvQIJ")).
pos(eqo("conf/vldb/RamanRH99","6uP3E_WEkCAJ")).
pos(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
pos(eqo("conf/vldb/RamaswamyMS98","Qq2kFNELi_8J")).
pos(eqo("conf/vldb/RezendeH98","njuthCBUMPAJ")).
pos(eqo("conf/vldb/RiedelGF98","DFXKdJJtFsQJ")).
pos(eqo("conf/vldb/RiedelGF98","f2N_DxLirWIJ")).
pos(eqo("conf/vldb/RizviH02","3ku_XOqYuawJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","T2fm7Wb1ak4J")).
pos(eqo("conf/vldb/SahuguetA99","NrXmzugArgoJ")).
pos(eqo("conf/vldb/SahuguetA99","PAcS8vELrawJ")).
pos(eqo("conf/vldb/Sarawagi95","C8lF7grRFcMJ")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/vldb/SavasereON95","N-o3NPu-nbIJ")).
pos(eqo("conf/vldb/SavasereON95","ohjoG-bi4OgJ")).
pos(eqo("conf/vldb/SavasereON95","rmfK2zWkuagJ")).
pos(eqo("conf/vldb/SchaeferBBJ00","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671845")).
pos(eqo("conf/vldb/SeligmanBNSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.673303%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/SeshadriLR96","-Pmsximl_moJ")).
pos(eqo("conf/vldb/SeshadriLR96","K62EwWeSRKUJ")).
pos(eqo("conf/vldb/SetzerZ94","1tmW1mOCZqIJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","MSw9OnOdcVEJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","_bdp5T8SSuoJ")).
pos(eqo("conf/vldb/ShengBDM02","6GxdJ4jZUokJ")).
pos(eqo("conf/vldb/ShengBDM02","TdjMAASfHFoJ")).
pos(eqo("conf/vldb/Sheth96","xoD5vxZQJ8AJ")).
pos(eqo("conf/vldb/SrinivasanDFCJYKTDB00","RmyORCW6qn8J")).
pos(eqo("conf/vldb/SteenhagenABB94","IgWfWMn1_AAJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","aCZo57LF-4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","n5yJ4y54WbwJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","k-IlQ6VnmKsJ")).
pos(eqo("conf/vldb/StillgerLMK01","R43ssyRp674J")).
pos(eqo("conf/vldb/StillgerLMK01","k8EsgEuKhQ0J")).
pos(eqo("conf/vldb/SumiyaYTSI95","ZoMjwB0ps2kJ")).
pos(eqo("conf/vldb/TamuraK99","rAHGAfoqookJ")).
pos(eqo("conf/vldb/TamuraK99","w2W3fqz4M7IJ")).
pos(eqo("conf/vldb/TeisseirePC94","w17spSGfEXYJ")).
pos(eqo("conf/vldb/Tsur00","buI2V0eIcZoJ")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/Vaskevitch95","s6Ax0WdZp6IJ")).
pos(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
pos(eqo("conf/vldb/WeberSNSS03","wjrZrNrZl4kJ")).
pos(eqo("conf/vldb/WienerN95","LJ4M8B9mNWAJ")).
pos(eqo("conf/vldb/WienerN95","Y1lEnVPl6d8J")).
pos(eqo("conf/vldb/WitkowskiBBFGSS03","Oti_CoAPH9IJ")).
pos(eqo("conf/vldb/WuYCT95","A5s_U6Ixg3EJ")).
pos(eqo("conf/vldb/WuYCT95","uv6nMj7jEggJ")).
pos(eqo("conf/vldb/XieH94","7P8_zVPEW64J")).
pos(eqo("conf/vldb/YanL95","9B2oMksKaMMJ")).
pos(eqo("conf/vldb/YanL95","uy8MOTvPkOsJ")).
pos(eqo("conf/vldb/YuSLJ02","6EJ6A2y_U1IJ")).
pos(eqo("conf/vldb/YuSLJ02","qYGzjvmVjS8J")).
pos(eqo("conf/vldb/YuV00","j2gOIcgWxb4J")).
pos(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
pos(eqo("journals/sigmod/Aberer03a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aggarwal01","OE8gpNwz8MkJ")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/AshishK97","GiEo36f1syYJ")).
pos(eqo("journals/sigmod/AshishK97","kQOOd6RAo1AJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BargaL02","fY3kkkzBLw8J")).
pos(eqo("journals/sigmod/BergamaschiCV99","iiyN4FT7v90J")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","oFiEYaenxe4J")).
pos(eqo("journals/sigmod/Bhashyam96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245908%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Bohlen95","43K14Y5xa0YJ")).
pos(eqo("journals/sigmod/Bohlen95","WnwPjh0a0twJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","GruVHotOoPQJ")).
pos(eqo("journals/sigmod/BunemanRU97","5qg4BNiroqMJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","Axu6UlX-pPYJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","OhiGJ7Gy3KgJ")).
pos(eqo("journals/sigmod/CatarciC96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245888%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CeriKKLOSV00","nLbW09uNfmsJ")).
pos(eqo("journals/sigmod/ChangASS98","CPzROuDNZqgJ")).
pos(eqo("journals/sigmod/Chaudhri95","DY6x1fDAy9EJ")).
pos(eqo("journals/sigmod/CruzKLSWY02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Date03","y4ZZN4xhKnUJ")).
pos(eqo("journals/sigmod/Datta94","3TVyZeq1-i4J")).
pos(eqo("journals/sigmod/Datta94","PPH2NlobSwsJ")).
pos(eqo("journals/sigmod/DoanPK95","c0TSepqRwwMJ")).
pos(eqo("journals/sigmod/DoanPSB97","fdM1W8iEk_YJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","-aWBDznLsQMJ")).
pos(eqo("journals/sigmod/DogacDATKCD98","fYMpjIpF8ckJ")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","SYV3r4_a5EsJ")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","UAO4T_2ylPkJ")).
pos(eqo("journals/sigmod/Domingo-FerrerH98","9bRPA_aTYh4J")).
pos(eqo("journals/sigmod/EisenbergM00","4mD1eFCHKKwJ")).
pos(eqo("journals/sigmod/FininJ02","rg8576nvnkUJ")).
pos(eqo("journals/sigmod/FlorescuLM98","FCcDKONgJVYJ")).
pos(eqo("journals/sigmod/FlorescuLM98","oABGXQlfGKcJ")).
pos(eqo("journals/sigmod/FlorescuLM98","q5OOyzSAlC8J")).
pos(eqo("journals/sigmod/Fong95","zw3-t-veNvAJ")).
pos(eqo("journals/sigmod/FowlerPNB99","2cbB8em2uAIJ")).
pos(eqo("journals/sigmod/FowlerPNB99","IgAEpc8ulvYJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","HJRR7GGfD6sJ")).
pos(eqo("journals/sigmod/Gallagher94","PVm9r7wHzDAJ")).
pos(eqo("journals/sigmod/GerlhofKM96","eq249ewqsHMJ")).
pos(eqo("journals/sigmod/GerlhofKM96","xsV7dkJi-YMJ")).
pos(eqo("journals/sigmod/Grohe02","RnmBv4e85pMJ")).
pos(eqo("journals/sigmod/Hammer01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Hanna95","29btu5OspbAJ")).
pos(eqo("journals/sigmod/Hanna95","EKqpEdn3kDMJ")).
pos(eqo("journals/sigmod/Hoffner03","url:http://portal.acm.org/citation.cfm%3Fid%3D776985.776995%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HuangKL02","yyUMt1X2WXcJ")).
pos(eqo("journals/sigmod/JukicV97","yZbJS0Cd6cAJ")).
pos(eqo("journals/sigmod/KannanKIK03","h_tDfTvsR0QJ")).
pos(eqo("journals/sigmod/KennedyMB96","vBYtmDEYeK0J")).
pos(eqo("journals/sigmod/KiyokiKH94","xT3mwY4t5kEJ")).
pos(eqo("journals/sigmod/KoksalAD98","c2UQ3AM5_f8J")).
pos(eqo("journals/sigmod/KoksalAD98","enYoi4XT7n0J")).
pos(eqo("journals/sigmod/Konig-RiesL97","3fQBks2g-BMJ")).
pos(eqo("journals/sigmod/Konig-RiesMMPPRSVW02","FIxl60DSBqgJ")).
pos(eqo("journals/sigmod/LabrinidisM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603886%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LabrinidisR00","TppC2jA5UXMJ")).
pos(eqo("journals/sigmod/LabrinidisR00","Wcbvsi-QDtcJ")).
pos(eqo("journals/sigmod/LeeCL95","G1E5PwzwdSMJ")).
pos(eqo("journals/sigmod/LightstoneLZ02","7TYVQTwq9FIJ")).
pos(eqo("journals/sigmod/LightstoneLZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601873%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MaelbranckeO95","_FKSZiytB2AJ")).
pos(eqo("journals/sigmod/Manola98","VIjfH9f94xkJ")).
pos(eqo("journals/sigmod/MarchiLPT03","B0gGtPpx7uUJ")).
pos(eqo("journals/sigmod/MaximilienS02","HqytuZsDNx8J")).
pos(eqo("journals/sigmod/MaximilienS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637417%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MukhopadhyayGS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776989%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Palpanas00","wqWcfwbLjIYJ")).
pos(eqo("journals/sigmod/Qian96","NiswbODuzhAJ")).
pos(eqo("journals/sigmod/Richey95","2p2A5_qGf5cJ")).
pos(eqo("journals/sigmod/RisheSBDOALOSS95","pGU2Ew1AQkoJ")).
pos(eqo("journals/sigmod/RoantreeMH99","7-Suml1GqBQJ")).
pos(eqo("journals/sigmod/RoantreeS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637435%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603872%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ShethM02","B_axrPz8j5EJ")).
pos(eqo("journals/sigmod/ShethM02","uwGRgxWWCtUJ")).
pos(eqo("journals/sigmod/SlivinskasJS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565119%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Snodgrass03","m-l6e98xxOsJ")).
pos(eqo("journals/sigmod/SommerGB02","fFLey-_2UM4J")).
pos(eqo("journals/sigmod/SouzaS99","OmYc0wE1j4kJ")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
pos(eqo("journals/sigmod/TsotrasJS98","FBZw8n-gojUJ")).
pos(eqo("journals/sigmod/Winslett01","m2Mf-4BgLP4J")).
pos(eqo("journals/tods/BozkayaO99","0znTIa901S8J")).
pos(eqo("journals/tods/BrunoCG02","tkCWrg5OsIwJ")).
pos(eqo("journals/tods/CasatiCPP99","12JXvv17ugoJ")).
pos(eqo("journals/tods/CasatiCPP99","6F_cUJERo6sJ")).
pos(eqo("journals/tods/CeriFPT95","DoS7NkmUyYgJ")).
pos(eqo("journals/tods/ChaudhuriS99","31oH64SXpRcJ")).
pos(eqo("journals/tods/ChaudhuriS99","4MaErPILRq8J")).
pos(eqo("journals/tods/CliffordC94","9txS2mlA2DMJ")).
pos(eqo("journals/tods/DiaoAFZF03","fREDZIbZVdEJ")).
pos(eqo("journals/tods/EiterGM97","WXWcO2ulDQUJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","TQ8M8qOzJO8J")).
pos(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0252444CI")).
pos(eqo("journals/tods/GoldmanL94","VxMarpzwtzQJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","5cAIVZJShAEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","y5JyKlYjnI4J")).
pos(eqo("journals/tods/GuoSW96","KoI8CRWkAYsJ")).
pos(eqo("journals/tods/KotidisR01","04utamFvle4J")).
pos(eqo("journals/tods/MokNE96","xUeP4X8k5SoJ")).
pos(eqo("journals/tods/RaschidL96","rUpu2pcFa8cJ")).
pos(eqo("journals/tods/TaoP03","faqaX7J_Kl8J")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/tods/YanG99","y6gLSJhyXfcJ")).
pos(eqo("journals/vldb/Amer-YahiaCLS02","79CvVWsqYLcJ")).
pos(eqo("journals/vldb/Amer-YahiaCLS02","SdqZz-Rnmk4J")).
pos(eqo("journals/vldb/BeckerGOSW96","BNQ07kOYONgJ")).
pos(eqo("journals/vldb/BohmAnY97","O7IuKWfq4RYJ")).
pos(eqo("journals/vldb/BohmAnY97","wIFnnUw2yZ0J")).
pos(eqo("journals/vldb/BunemanFS00","E_CQlx3K0W4J")).
pos(eqo("journals/vldb/ChangG01","hYu2nw263UoJ")).
pos(eqo("journals/vldb/DesslochHMMT98","4D2HQE6fXXEJ")).
pos(eqo("journals/vldb/DoanMDDH03","InzqepkG0W8J")).
pos(eqo("journals/vldb/GeorgeH00","2L-UFpDof3UJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/GutingS95","rjQa8odFpMwJ")).
pos(eqo("journals/vldb/Han98","url:http://www.springerlink.com/index/YTPAB711B92NCE7J.pdf")).
pos(eqo("journals/vldb/JagadishKNS00","GtXc02EJjCgJ")).
pos(eqo("journals/vldb/JiangE98","PjtgP4aQt00J")).
pos(eqo("journals/vldb/KabraD99","pWEfI0xFFcoJ")).
pos(eqo("journals/vldb/LawLG99","TOXrbhbbNJ4J")).
pos(eqo("journals/vldb/Li03","XkdLpQ5x-YIJ")).
pos(eqo("journals/vldb/LometS97","QIv1JU2suAEJ")).
pos(eqo("journals/vldb/MedjahedBBNE03","vtVf3hshlVIJ")).
pos(eqo("journals/vldb/MihailaRT02","my7mYCzEEJAJ")).
pos(eqo("journals/vldb/Navarro02","UDQsHc_ps4IJ")).
pos(eqo("journals/vldb/RamamurthyDS03","uem5wXLoU0wJ")).
pos(eqo("journals/vldb/RamamurthyDS03","vGFdY2gG8YsJ")).
pos(eqo("journals/vldb/ScheuermannWZ98","Q_JRmsXFEM4J")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","HKM-zP0LT_UJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","MSw9OnOdcVEJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","_bdp5T8SSuoJ")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","xomFMCDegw8J")).
pos(eqo("journals/vldb/SuHHHLWLPLL01","xcRKDHBIUb8J")).
pos(eqo("journals/vldb/YangW03","IJDg4R1pw6EJ")).
