neg(eqo("conf/sigmod/AbiteboulCM95","gIKwrx708HMJ")).
neg(eqo("conf/sigmod/AcharyaFZ97","gJPWbysKyQgJ")).
neg(eqo("conf/sigmod/AdaliCPS96","oulaZpEWkMQJ")).
neg(eqo("conf/sigmod/AdaliSS99","hhzf0Ib9PNIJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","s5-YrXVuDCcJ")).
neg(eqo("conf/sigmod/AgrawalASY97","YgouJdrCoZQJ")).
neg(eqo("conf/sigmod/AgrawalCN01","34SSHLGhNKsJ")).
neg(eqo("conf/sigmod/AgrawalGGR98","pYd_oa0DxQ8J")).
neg(eqo("conf/sigmod/AgrawalS00","84mAZVIXtKsJ")).
neg(eqo("conf/sigmod/AmbiteABKMMMPT98","JDRDXDHRqpIJ")).
neg(eqo("conf/sigmod/AtzeniT97","Qu1sEXDXeHIJ")).
neg(eqo("conf/sigmod/AtzeniT97","mdgEygFyD54J")).
neg(eqo("conf/sigmod/BabcockBDM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BabcockCD03","VuNnpxJwvQkJ")).
neg(eqo("conf/sigmod/BabcockCD03","jpNXw9L7pxgJ")).
neg(eqo("conf/sigmod/BabuGR01","DL2-xldaXeoJ")).
neg(eqo("conf/sigmod/BaruGLMPVC99","4PztyCG8HFMJ")).
neg(eqo("conf/sigmod/BergstraesserBPS99","39Fq_VW6WO0J")).
neg(eqo("conf/sigmod/BersonGM95","YkPqPzGFnZIJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","24bBDJoQZwoJ")).
neg(eqo("conf/sigmod/BettiniWBJ95","tFuA828CptUJ")).
neg(eqo("conf/sigmod/BeyerR99","hxWB8uQMCdgJ")).
neg(eqo("conf/sigmod/BilirisP94","KAyi60nog2AJ")).
neg(eqo("conf/sigmod/BohannonMR01","WYyi09KarvwJ")).
neg(eqo("conf/sigmod/BohmBKK01","l_zxsYDPGU8J")).
neg(eqo("conf/sigmod/BonnetBCCCHKMMOSS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107515%26type%3Dpdf")).
neg(eqo("conf/sigmod/BressanGOT00","V5O37YacElIJ")).
neg(eqo("conf/sigmod/BreunigKKS01","ifvTHfEvE2oJ")).
neg(eqo("conf/sigmod/BreunigKNS00","abEzjLwwX4IJ")).
neg(eqo("conf/sigmod/Brewer98","k4UNrsGeUuAJ")).
neg(eqo("conf/sigmod/BrinkhoffKSS94","w-6_Y5sf1sUJ")).
neg(eqo("conf/sigmod/Brown99","url:http://portal.acm.org/citation.cfm%3Fid%3D171926.172028")).
neg(eqo("conf/sigmod/CallanCD99","ZvCgA0EEmzkJ")).
neg(eqo("conf/sigmod/ChakrabartiDI98","srJr-8rCZ4YJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","ODvDsK1VEicJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","PYmxUbU7ERYJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","_YwJir9pCvQJ")).
neg(eqo("conf/sigmod/Chamberlin03","FZSgcyh7IsIJ")).
neg(eqo("conf/sigmod/Chaudhuri97","QkyXMep2bWsJ")).
neg(eqo("conf/sigmod/ChaudhuriGN02","ci04dpI4WvYJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","5KdceadGf8cJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","pVsFKVZNgD4J")).
neg(eqo("conf/sigmod/ChaudhuriN98","M-eta-rskhgJ")).
neg(eqo("conf/sigmod/ChenGK01","1S-vlkBOdmkJ")).
neg(eqo("conf/sigmod/ChenGK01","hYu2nw263UoJ")).
neg(eqo("conf/sigmod/CherniackZ96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ColeG94","Lc5M1WVbdu4J")).
neg(eqo("conf/sigmod/ColletC95","vP27NkXI4MEJ")).
neg(eqo("conf/sigmod/ConsensM94","o_WTRsrkx_EJ")).
neg(eqo("conf/sigmod/CorralMTV00","uFVf0mEOih4J")).
neg(eqo("conf/sigmod/Cotton02","MD1nw-iA3mYJ")).
neg(eqo("conf/sigmod/Cotton02","sn_R4N1q2SwJ")).
neg(eqo("conf/sigmod/CruzJ99","vXMwU21-7HMJ")).
neg(eqo("conf/sigmod/DarEGP98","9fcJjh5vHn8J")).
neg(eqo("conf/sigmod/DasuJMS02","wnWf9OvR0O8J")).
neg(eqo("conf/sigmod/DavisonG95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D984537%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/DeligiannakisR03","rKbwxobcJZYJ")).
neg(eqo("conf/sigmod/DeshpandeRSN98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141002%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/DoRD99","jBOm9LJs9LwJ")).
neg(eqo("conf/sigmod/DoanDH01","bk4uP5Onwu8J")).
neg(eqo("conf/sigmod/DobraGGR02","7LqBuZpperIJ")).
neg(eqo("conf/sigmod/DohertyHR96","v3IA8Go4UjIJ")).
neg(eqo("conf/sigmod/Dyreson03","AfM_N94rVD0J")).
neg(eqo("conf/sigmod/EmbleyJN99","x8uC_9_IzUEJ")).
neg(eqo("conf/sigmod/FaloutsosRM94","SFs0XOMPphIJ")).
neg(eqo("conf/sigmod/FaloutsosSTT00","1gG_hIZaRNAJ")).
neg(eqo("conf/sigmod/FegarasSRM00","7ZORIhEmjicJ")).
neg(eqo("conf/sigmod/FlorescuLMS99","oHJaZrizZesJ")).
neg(eqo("conf/sigmod/GarofalakisG02","Cd4NNuZnIn8J")).
neg(eqo("conf/sigmod/GarofalakisG02","SdVmepmUgQIJ")).
neg(eqo("conf/sigmod/GarofalakisGR02","url:http://doi.wiley.com/10.1002/ace.60")).
neg(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
neg(eqo("conf/sigmod/GillmannWSWW00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245885%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GotoK03","V6H7t6K4MsQJ")).
neg(eqo("conf/sigmod/GrayHOS96","QsUsVqyi3j8J")).
neg(eqo("conf/sigmod/GriffinL95","kuueK-yBQqMJ")).
neg(eqo("conf/sigmod/GuhaJKSY02","gQIBl-LfWA8J")).
neg(eqo("conf/sigmod/GuptaS03","hUMTG7HNlyAJ")).
neg(eqo("conf/sigmod/HaasH99","MfWZUBAVPFUJ")).
neg(eqo("conf/sigmod/Han96","mQccJAbgRY0J")).
neg(eqo("conf/sigmod/HanFHCC94","6M-fnuhWEOIJ")).
neg(eqo("conf/sigmod/HanKK97","I9JXY0-R4GgJ")).
neg(eqo("conf/sigmod/HanPDW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066188%26type%3Dpdf")).
neg(eqo("conf/sigmod/HeC03","Gw060IxF8VQJ")).
neg(eqo("conf/sigmod/HeC03","jx2JENQYW-AJ")).
neg(eqo("conf/sigmod/Hellerstein00","zp--hf4KJMAJ")).
neg(eqo("conf/sigmod/HillyerS96","gIqKv68WTZIJ")).
neg(eqo("conf/sigmod/HinneburgK99","C9imFvgrSvAJ")).
neg(eqo("conf/sigmod/HristidisKP01","k_WEhF7DpYkJ")).
neg(eqo("conf/sigmod/IpeirotisGS01","jaBQWidSinMJ")).
neg(eqo("conf/sigmod/JagadishLS99","Rba70P6SqQYJ")).
neg(eqo("conf/sigmod/JajodiaSSB97","9h_VC_zBd2MJ")).
neg(eqo("conf/sigmod/JajodiaSSB97","VzQQwoEdG1sJ")).
neg(eqo("conf/sigmod/Jamil99","ospJVA6AD1sJ")).
neg(eqo("conf/sigmod/JonkerS95","JFOg1ntEUvMJ")).
neg(eqo("conf/sigmod/JonssonFS98","ezlAkB7ijDUJ")).
neg(eqo("conf/sigmod/Keim99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D200111010708MT%26recid%3DA0032643AH")).
neg(eqo("conf/sigmod/Kim94","5aSVaxWgGUMJ")).
neg(eqo("conf/sigmod/KimCK01","w9pelNvv6xsJ")).
neg(eqo("conf/sigmod/KotidisR99","CpHJwU8o-BkJ")).
neg(eqo("conf/sigmod/KoudasS03","_uAjDh22Y_EJ")).
neg(eqo("conf/sigmod/KriegelBKPS03","tsqBH6P4jMcJ")).
neg(eqo("conf/sigmod/KriegelMPS01","IWnfzq4zt3kJ")).
neg(eqo("conf/sigmod/KrishnanVI96","8tFA4ENYqKQJ")).
neg(eqo("conf/sigmod/KrishnanVI96","FnypYUw9pwEJ")).
neg(eqo("conf/sigmod/LacroixSC98","yrnhcMqsUVoJ")).
neg(eqo("conf/sigmod/LahiriG01","tO0OVpz2o9sJ")).
neg(eqo("conf/sigmod/LakshmananNHP99","DfOLEzMoEaEJ")).
neg(eqo("conf/sigmod/LiS98","JcnZJ-eE2XsJ")).
neg(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","P25_yh3lBhoJ")).
neg(eqo("conf/sigmod/LitwinS00","99nKpf7A4uIJ")).
neg(eqo("conf/sigmod/LitwinS00","HEpG2xCKijUJ")).
neg(eqo("conf/sigmod/LiuPBHPT00","PKQ1dCQIwi0J")).
neg(eqo("conf/sigmod/MaddenH02","JUsFf9Sx1UYJ")).
neg(eqo("conf/sigmod/MaddenH02","UIWreKZndVQJ")).
neg(eqo("conf/sigmod/MamoulisP99","Rg8V7NSK9tMJ")).
neg(eqo("conf/sigmod/MassariPSC95","5JA4QR8rxq0J")).
neg(eqo("conf/sigmod/MassariPSC95","lzDcGtahiYEJ")).
neg(eqo("conf/sigmod/MayrS99","iuZ4idi0sLsJ")).
neg(eqo("conf/sigmod/McIverK94","LMV_K5t2am0J")).
neg(eqo("conf/sigmod/Miller98","7f6Q9GgXsmgJ")).
neg(eqo("conf/sigmod/Mohan94","f9JfEpe5a24J")).
neg(eqo("conf/sigmod/Mohan99","bfLZp1c7E1cJ")).
neg(eqo("conf/sigmod/MoonSL00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/MumickP94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187462%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ONeilQ97","url:http://portal.acm.org/citation.cfm%3Fid%3D604292%26dl%3DACM%26coll%3Dportal%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/citation.cfm%3Fid%3D304245%26coll%3Dportal%26dl%3DACM")).
neg(eqo("conf/sigmod/OlstonWL01","di0fR_Qlv8EJ")).
neg(eqo("conf/sigmod/PadmanabhanBMCH03","f5cqkpUXl0kJ")).
neg(eqo("conf/sigmod/PapadopoulosM98","IIxXIgK58NoJ")).
neg(eqo("conf/sigmod/PatelD96","NLklGN91cZgJ")).
neg(eqo("conf/sigmod/Pirahesh94","mixfM7sBcH0J")).
neg(eqo("conf/sigmod/PopaDST00","YSgaDQ95dfEJ")).
neg(eqo("conf/sigmod/RadekeBBEKKN95","bDN03rZhUQEJ")).
neg(eqo("conf/sigmod/Raghavan03","P547hLKkZpQJ")).
neg(eqo("conf/sigmod/Ramanan02","gF4nPxSCcOMJ")).
neg(eqo("conf/sigmod/Rodriguez-Martinez00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1041416%26type%3Dpdf")).
neg(eqo("conf/sigmod/Rosenthal01","ZMMeRrWUlOoJ")).
neg(eqo("conf/sigmod/Ross00","yI5E8TGu5BwJ")).
neg(eqo("conf/sigmod/RossSS96","D1wP_f8yD5MJ")).
neg(eqo("conf/sigmod/RothAHCCFSTW96","VxAERlI5OVoJ")).
neg(eqo("conf/sigmod/RundensteinerKZWLLN99","WYE9fKutj70J")).
neg(eqo("conf/sigmod/RundensteinerWYD02","nyHFfFtClVsJ")).
neg(eqo("conf/sigmod/SagonasSW94","0hHYO7tQJUgJ")).
neg(eqo("conf/sigmod/SchusterW01","JrzYDC75O68J")).
neg(eqo("conf/sigmod/Seshadri03","U9tDRbbUCSYJ")).
neg(eqo("conf/sigmod/Seshadri03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031591%26type%3Dpdf")).
neg(eqo("conf/sigmod/ShashaB02","O-TrhFwhKM8J")).
neg(eqo("conf/sigmod/ShenoyHSBBS00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107506%26type%3Dpdf")).
neg(eqo("conf/sigmod/Shivakumar03","jN8ws_LDhNUJ")).
neg(eqo("conf/sigmod/Shivakumar03","ne4v3zrmFSQJ")).
neg(eqo("conf/sigmod/ShivakumarG97","NVRVKHZRrjAJ")).
neg(eqo("conf/sigmod/ShivakumarG97","z5tz9vybRmIJ")).
neg(eqo("conf/sigmod/SimmenSM96","-ogeftJL29AJ")).
neg(eqo("conf/sigmod/SrikantA96","5KdceadGf8cJ")).
neg(eqo("conf/sigmod/SrikantA96","RE_sI8I74igJ")).
neg(eqo("conf/sigmod/Stonebraker03","OiFyf-aJ80cJ")).
neg(eqo("conf/sigmod/Stonebraker03","SyOHqrZQEeYJ")).
neg(eqo("conf/sigmod/SwamiS94","7BDCL140Kx4J")).
neg(eqo("conf/sigmod/SzalayGTKMRSv02","1tKWKmyczaYJ")).
neg(eqo("conf/sigmod/TaoP02","19ridA84Q4gJ")).
neg(eqo("conf/sigmod/TaoP02","CxBJwFNdozAJ")).
neg(eqo("conf/sigmod/Vaskevitch94","s6Ax0WdZp6IJ")).
neg(eqo("conf/sigmod/Whelan98","ALk7huiKjWAJ")).
neg(eqo("conf/sigmod/WhiteD94","TNvF8X1XsSEJ")).
neg(eqo("conf/sigmod/WilschutFA95","nW1etYVHL-MJ")).
neg(eqo("conf/sigmod/Wu99","pmtY1d0NLe4J")).
neg(eqo("conf/sigmod/YangM97","YQ0D98oeJKMJ")).
neg(eqo("conf/sigmod/YangWYH02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/YerneniLGU99","hnMltY0uSf0J")).
neg(eqo("conf/sigmod/ZaharioudakisCLPU00","AQOcKd6cVZsJ")).
neg(eqo("conf/sigmod/ZhangRL96","KUGjzt-IgpoJ")).
neg(eqo("conf/vldb/AbiteboulACEMM99","Aqc3h0iFo_AJ")).
neg(eqo("conf/vldb/AbiteboulACEMM99","mm3mXWb8QS0J")).
neg(eqo("conf/vldb/AbiteboulBMMW02","VJVukBz-cOMJ")).
neg(eqo("conf/vldb/AcharyaFZ96","gJPWbysKyQgJ")).
neg(eqo("conf/vldb/Adler01","YCI9HkJhmKMJ")).
neg(eqo("conf/vldb/AgarwalADGNRS96","gkbvvgj8kdUJ")).
neg(eqo("conf/vldb/AggarwalHWY03","mXpwRLE8dZwJ")).
neg(eqo("conf/vldb/AgrawalSX02","n7y3qyLPMFQJ")).
neg(eqo("conf/vldb/AltinelF00","ebmulQBhqZEJ")).
neg(eqo("conf/vldb/Amer-YahiaCD98","W80_hO4TTCYJ")).
neg(eqo("conf/vldb/AmsalegFG95","F0a2V6Okkn0J")).
neg(eqo("conf/vldb/AnKR03","9VMJoiIcJIcJ")).
neg(eqo("conf/vldb/BalminPP00","1m9BmEzgbBYJ")).
neg(eqo("conf/vldb/BalminPP00","FoAVdcYe0tsJ")).
neg(eqo("conf/vldb/BamfordBKM98","rfuptELfgLkJ")).
neg(eqo("conf/vldb/BaulierBGJGKKMMNNRSS98","url:http://portal.acm.org/citation.cfm%3Fid%3D276304%26dl%3DACM%26coll%3Dportal%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/BelloDDFNSWZ98","zrMFWOX1h2MJ")).
neg(eqo("conf/vldb/BenediktCFRZZ02","F9Fe5NfpK6MJ")).
neg(eqo("conf/vldb/Bernstein94","TqLyg1wbo5UJ")).
neg(eqo("conf/vldb/BernsteinD94","gKdxwCWE4ssJ")).
neg(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
neg(eqo("conf/vldb/BertinoBFS96","zbzO-4fuIwUJ")).
neg(eqo("conf/vldb/BhattacharjeePMLCH03","hwhi2fTtG5oJ")).
neg(eqo("conf/vldb/Bowker00","rLbCv77h0pAJ")).
neg(eqo("conf/vldb/Brodie03","uPv-id9k6-QJ")).
neg(eqo("conf/vldb/BrodieC99","KqH0DkzaDQEJ")).
neg(eqo("conf/vldb/CabreraRH95","LSGRPb5EDlEJ")).
neg(eqo("conf/vldb/CabreraRH95","dYONiJ_YjTYJ")).
neg(eqo("conf/vldb/CareyCNVDRSM99","zOpbXn4P2zsJ")).
neg(eqo("conf/vldb/ChaHKK01","JO5qRbtiMSkJ")).
neg(eqo("conf/vldb/ChandrasekaranF02","b9r9U3OwrkcJ")).
neg(eqo("conf/vldb/ChangG00","SZbsK5kMevAJ")).
neg(eqo("conf/vldb/ChatziantoniouR96","4S1hW5qdiEYJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","gY652XXjHB8J")).
neg(eqo("conf/vldb/ChaudhuriGS95","qfohkpyTawoJ")).
neg(eqo("conf/vldb/ChaudhuriS94","KrfR8djb3C8J")).
neg(eqo("conf/vldb/ChaudhuriS94","qfohkpyTawoJ")).
neg(eqo("conf/vldb/ChaudhuriS96","Y-kXztd20YQJ")).
neg(eqo("conf/vldb/ChaudhuriS96","iP9s_nlGG9oJ")).
neg(eqo("conf/vldb/ChavdaW97","7P8_zVPEW64J")).
neg(eqo("conf/vldb/ChenDZ03","b5j94HGoI04J")).
neg(eqo("conf/vldb/ChenHWW02","KKiefntReoUJ")).
neg(eqo("conf/vldb/ChengGKLLQS99","z8UTEms4_WsJ")).
neg(eqo("conf/vldb/ChienVZTZ02","Xm3ygCvkmN8J")).
neg(eqo("conf/vldb/CuiW01","HLrteP7x0doJ")).
neg(eqo("conf/vldb/Dayal99","QJeM-SyIl2gJ")).
neg(eqo("conf/vldb/Deshpande00","E9eHIYcWjDMJ")).
neg(eqo("conf/vldb/DeutschT03","2DiLFd0rgPgJ")).
neg(eqo("conf/vldb/DingGS00","mlNoe-1jmygJ")).
neg(eqo("conf/vldb/DonjerkovicR99","fBJ5iYP1NxkJ")).
neg(eqo("conf/vldb/Dyreson96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1099634%26type%3Dpdf")).
neg(eqo("conf/vldb/FerrandinaMZFM95","QmkA__M9kqcJ")).
neg(eqo("conf/vldb/FlorescuKLP97","91X0HLAVjkEJ")).
neg(eqo("conf/vldb/GaasterlandL94","3Ozte0ucNJAJ")).
neg(eqo("conf/vldb/GaasterlandL94","chmPCuLihZoJ")).
neg(eqo("conf/vldb/Ganguly98","L4aXHaUW3cUJ")).
neg(eqo("conf/vldb/GarofalakisG02","mfJYK9hRSucJ")).
neg(eqo("conf/vldb/George98","uky90TOkkYgJ")).
neg(eqo("conf/vldb/GhoshPSH02","XrBZe-6QNAcJ")).
neg(eqo("conf/vldb/Gibbons01","6ubLGFYqCNIJ")).
neg(eqo("conf/vldb/GibsonKR98","7y9SomIIAG0J")).
neg(eqo("conf/vldb/GionisIM99","Ib7-RszznfIJ")).
neg(eqo("conf/vldb/GionisIM99","a1_mvYBrjyAJ")).
neg(eqo("conf/vldb/GoldmanW97","Ol886Ck3jz4J")).
neg(eqo("conf/vldb/GoodmanRS94","k1I5JesSrmoJ")).
neg(eqo("conf/vldb/GotoK02","2Pc6rKYB8ykJ")).
neg(eqo("conf/vldb/GotoK02","8EGg5qJZyBMJ")).
neg(eqo("conf/vldb/GottlobKP02","VYYKHi96iQkJ")).
neg(eqo("conf/vldb/GottlobKP02","e5Gm5upjQnkJ")).
neg(eqo("conf/vldb/GuntzerBK00","X5LKJRsuqgUJ")).
neg(eqo("conf/vldb/GuptaM96","793XPMTdcBEJ")).
neg(eqo("conf/vldb/HaasKU99","jteJcGoGxnMJ")).
neg(eqo("conf/vldb/HaasKU99","sm2H_15iqCsJ")).
neg(eqo("conf/vldb/HaasKWY97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066260%26type%3Dpdf")).
neg(eqo("conf/vldb/HelmerNM03","Uv3mhmUGwdcJ")).
neg(eqo("conf/vldb/HinneburgLH03","C9imFvgrSvAJ")).
neg(eqo("conf/vldb/HoelS94","gm2FRRPEVCYJ")).
neg(eqo("conf/vldb/HristidisP02","SdVmepmUgQIJ")).
neg(eqo("conf/vldb/HulgeriS03","zbzO-4fuIwUJ")).
neg(eqo("conf/vldb/HumborstadSHT97","N3Hyyb1Qw8sJ")).
neg(eqo("conf/vldb/Huyn97","YTgl21ATj54J")).
neg(eqo("conf/vldb/HvasshovdTBH95","V98z3uzuvpQJ")).
neg(eqo("conf/vldb/IshikawaSF98","9MDCp_a1roUJ")).
neg(eqo("conf/vldb/JagadishLS99","YtMVuLN2XaYJ")).
neg(eqo("conf/vldb/JarkeKL00","DDyZXuEtGiwJ")).
neg(eqo("conf/vldb/JarkeKL00","JdwWIABomPsJ")).
neg(eqo("conf/vldb/JarkeKL00","_RMZmSBR_PUJ")).
neg(eqo("conf/vldb/JosifovskiR99","b6jk0v8UYmkJ")).
neg(eqo("conf/vldb/KahveciS01","E0WRGO_PEfQJ")).
neg(eqo("conf/vldb/KangC02","wiND8YVYbNkJ")).
neg(eqo("conf/vldb/KeimH99","pH6zRbG6CZUJ")).
neg(eqo("conf/vldb/KerstenWFKBC03","h7_vmoCZRbIJ")).
neg(eqo("conf/vldb/Kiessling02","uS43GVHJ3jQJ")).
neg(eqo("conf/vldb/Kiessling02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066303%26type%3Dpdf")).
neg(eqo("conf/vldb/KornSFSP96","aqU5N6dO4KcJ")).
neg(eqo("conf/vldb/KornackerB95","ml-oFmPRY6AJ")).
neg(eqo("conf/vldb/Korth95","xT02IBtXCQAJ")).
neg(eqo("conf/vldb/Kotidis01","HY_y6yTOir8J")).
neg(eqo("conf/vldb/KraissW97","LMz7v87sxxYJ")).
neg(eqo("conf/vldb/KumarKA97","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/LabioG96","hOcniOdybHQJ")).
neg(eqo("conf/vldb/LakshmiZ98","4K4WSmubERcJ")).
neg(eqo("conf/vldb/LernerS03","lzlTKXb6RMUJ")).
neg(eqo("conf/vldb/LevySSZ94","9MI4jOOqkn4J")).
neg(eqo("conf/vldb/Leymann03","N9u28V6NZTIJ")).
neg(eqo("conf/vldb/LohmanL02","B8_0dK37qcsJ")).
neg(eqo("conf/vldb/MankuM02","JXz6DHDmIbAJ")).
neg(eqo("conf/vldb/MarronL01","k_WEhF7DpYkJ")).
neg(eqo("conf/vldb/MatiasVW00","iGKoS8f6vTIJ")).
neg(eqo("conf/vldb/May01","k_FES3grolQJ")).
neg(eqo("conf/vldb/McHughW99","6h712r6nl3QJ")).
neg(eqo("conf/vldb/McHughW99","QkyXMep2bWsJ")).
neg(eqo("conf/vldb/MengLLA03","yqXSZsWRzNQJ")).
neg(eqo("conf/vldb/MillinerBP95","p4IXF74uW6oJ")).
neg(eqo("conf/vldb/MiloZ98","Nd7-CTB1lRgJ")).
neg(eqo("conf/vldb/Moerkotte02","HcCevkoobDsJ")).
neg(eqo("conf/vldb/Mohan02","Dg19aLuRzcwJ")).
neg(eqo("conf/vldb/Mohan02a","N-o3NPu-nbIJ")).
neg(eqo("conf/vldb/Mohan02a","T91d5LI-xIwJ")).
neg(eqo("conf/vldb/Mohan99","0-G78ioxas0J")).
neg(eqo("conf/vldb/Mohan99","E2zhARKv5dsJ")).
neg(eqo("conf/vldb/Mohan99","bfLZp1c7E1cJ")).
neg(eqo("conf/vldb/MohanBWSZ00","hPWDomB8y6wJ")).
neg(eqo("conf/vldb/NaumannLF99","vNW-Vb97R8gJ")).
neg(eqo("conf/vldb/NgH94","6HlejBWokfkJ")).
neg(eqo("conf/vldb/NgH94","HJ9-1xT60k0J")).
neg(eqo("conf/vldb/NgH94","ORkxHLb7dvcJ")).
neg(eqo("conf/vldb/NgH94","j3gou1McdaAJ")).
neg(eqo("conf/vldb/Objectivity98","o3fkxpcCBskJ")).
neg(eqo("conf/vldb/OlstonW00","fzIAU5XQeo4J")).
neg(eqo("conf/vldb/OoiYTJ01","MCuFKbwcWIIJ")).
neg(eqo("conf/vldb/Orenstein98","QCLDOzkW4U4J")).
neg(eqo("conf/vldb/OzsuVU98","tftfK6qWKJcJ")).
neg(eqo("conf/vldb/PapadiasMD98","ZYpxZwJsDcQJ")).
neg(eqo("conf/vldb/PapakonstantinouAG96","5iBUkqCy-KAJ")).
neg(eqo("conf/vldb/PappasC00","-NNuFjchxnMJ")).
neg(eqo("conf/vldb/PardonA00","k7G60pXtD58J")).
neg(eqo("conf/vldb/PatonG01","c968fN8dF_QJ")).
neg(eqo("conf/vldb/PirotteZMY94","0BRPIr5yd80J")).
neg(eqo("conf/vldb/PitouraC99","2PEyKNA96x4J")).
neg(eqo("conf/vldb/PossP03","5smJVUm1KAYJ")).
neg(eqo("conf/vldb/PoulovassilisS94","HNDwkFGwM7EJ")).
neg(eqo("conf/vldb/Ramanan03","PqL6GM9-wQcJ")).
neg(eqo("conf/vldb/Rengarajan96","IhGTfd5ygQUJ")).
neg(eqo("conf/vldb/Rengarajan96","KMnEmQIYRm0J")).
neg(eqo("conf/vldb/RezendeH98","hJ8VP7FyOL0J")).
neg(eqo("conf/vldb/RizviH02","pwDF7X21wGcJ")).
neg(eqo("conf/vldb/Sarawagi99","w9je55hjOlwJ")).
neg(eqo("conf/vldb/Schek00","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/Schoning98","yp9N1FsxVlkJ")).
neg(eqo("conf/vldb/ShaferA97","EkmUvRCP29QJ")).
neg(eqo("conf/vldb/ShahDR03","JhY1cxsznKkJ")).
neg(eqo("conf/vldb/Shaw98","cR2OVl18j-gJ")).
neg(eqo("conf/vldb/Sheth96","CQOvghgKDEkJ")).
neg(eqo("conf/vldb/Sheth96","q4YYDWKhoZwJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","NiahIu-wQacJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","REXoXYDRw90J")).
neg(eqo("conf/vldb/ShuklaDN98","O8FpwNF0NM4J")).
neg(eqo("conf/vldb/SistlaYH94","AeEdqlDl4YgJ")).
neg(eqo("conf/vldb/SizovGT03","UbQPXbPLMCAJ")).
neg(eqo("conf/vldb/Sripada02","NNWQbYNLLrgJ")).
neg(eqo("conf/vldb/StaudtJ96","url:http://portal.acm.org/citation.cfm%3Fid%3D1099554.1099626")).
neg(eqo("conf/vldb/StolteA02","BaMc29XZSvsJ")).
neg(eqo("conf/vldb/Suciu96a","FmbZmXV7TSAJ")).
neg(eqo("conf/vldb/Suciu96a","Y7kHpHu3nP0J")).
neg(eqo("conf/vldb/TaoP02","fDWfHiQ6BR4J")).
neg(eqo("conf/vldb/TengCY03","7j1pKfzfgNYJ")).
neg(eqo("conf/vldb/TianD03","QsPxm6zhtecJ")).
neg(eqo("conf/vldb/Tygar98","p95knDnXZYQJ")).
neg(eqo("conf/vldb/VenkataramanZ98","bDJcfbalxoUJ")).
neg(eqo("conf/vldb/VermeerA96","F1bohDXUiJ4J")).
neg(eqo("conf/vldb/ViverosNR96","QggifcM-zvYJ")).
neg(eqo("conf/vldb/VorugantiOU99","ItOlYY7ITt0J")).
neg(eqo("conf/vldb/Wadler01","TyF71uAlnLsJ")).
neg(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
neg(eqo("conf/vldb/WuFSP00","tr_rawv-6SMJ")).
neg(eqo("conf/vldb/YagoubFIV00","_Uf0AFqiR94J")).
neg(eqo("conf/vldb/YanA94","2njaHdhfzAoJ")).
neg(eqo("conf/vldb/ZhouR03","MQU247rrJxsJ")).
neg(eqo("conf/vldb/ZurekS99","eub0smLOPOIJ")).
neg(eqo("journals/sigmod/ACT-NET96","MyjGXk9y9SMJ")).
neg(eqo("journals/sigmod/Aberer01","fJQ7Col2vYsJ")).
neg(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603869%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02a","WryeHhngM_oJ")).
neg(eqo("journals/sigmod/Aberer02a","jzwiskpRLOUJ")).
neg(eqo("journals/sigmod/Aberer02b","g2ZQ4_Qy228J")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565129%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637423%26dl%3Dportal%26dl%3DACM%26type%3Dissue%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03d","7CLhi_LOtoUJ")).
neg(eqo("journals/sigmod/Aberer03d","_hb7jvkdltcJ")).
neg(eqo("journals/sigmod/AbererCH02","7ML1mmPqIooJ")).
neg(eqo("journals/sigmod/Aggarwal01","hUoyTdstE7sJ")).
neg(eqo("journals/sigmod/AilamakiFFSV03","PKQ1dCQIwi0J")).
neg(eqo("journals/sigmod/AilamakiG03","YWJ2VNtpeIwJ")).
neg(eqo("journals/sigmod/Anonymous96","aBiqHXGXoJEJ")).
neg(eqo("journals/sigmod/AnyanwuS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Barbara01","vLYloZqZZXEJ")).
neg(eqo("journals/sigmod/BarbaraBFLS94","QjkfeBTH5xAJ")).
neg(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
neg(eqo("journals/sigmod/Bernstein98","Gr3-L-wyIOcJ")).
neg(eqo("journals/sigmod/BernsteinHP00","gKdxwCWE4ssJ")).
neg(eqo("journals/sigmod/BohmR94","N9NdxNRvMMkJ")).
neg(eqo("journals/sigmod/BoulosO99","PBQNcqSsnyEJ")).
neg(eqo("journals/sigmod/Camps96","fwxnTTJRPAYJ")).
neg(eqo("journals/sigmod/CarmelMS01","o55wCltO164J")).
neg(eqo("journals/sigmod/CeriFP99","39m5BLDo1zYJ")).
neg(eqo("journals/sigmod/Cetintemel01","Em3qp7RGalkJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D101077.390002%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Chang03","dLgD2isEjzYJ")).
neg(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/citation.cfm%3Fid%3D163090.163102%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187460%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/CheungF98","B-u4advaVBkJ")).
neg(eqo("journals/sigmod/Cingil02","y4Gl00kwT_UJ")).
neg(eqo("journals/sigmod/ClementLGMK97","J7Y20fYLGbcJ")).
neg(eqo("journals/sigmod/CrestaniG02","cvBAdEvcTSkJ")).
neg(eqo("journals/sigmod/Date03","PBtu7Xy2Z_cJ")).
neg(eqo("journals/sigmod/Datta94","lAbG3uFZvVUJ")).
neg(eqo("journals/sigmod/David03","wsJ1nllw0KAJ")).
neg(eqo("journals/sigmod/DiazJPa94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1024696%26type%3Dpdf")).
neg(eqo("journals/sigmod/Dogac02","Hf7kJ0hv9GwJ")).
neg(eqo("journals/sigmod/Dogac96","e32va7phxCoJ")).
neg(eqo("journals/sigmod/DogacAOD95","JW49QfQtuTMJ")).
neg(eqo("journals/sigmod/EisenbergM98a","Ciq01lHglkAJ")).
neg(eqo("journals/sigmod/ElmagarmidJF95","YPvsBWM890IJ")).
neg(eqo("journals/sigmod/Fong97","rgJU30QjbhkJ")).
neg(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107515%26type%3Dpdf")).
neg(eqo("journals/sigmod/Franklin00","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin00b","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin00b","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Franklin98","LqA0my9vAXQJ")).
neg(eqo("journals/sigmod/Franklin98","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin98","aaQEdfkjWN8J")).
neg(eqo("journals/sigmod/Franklin98a","JHuJHooGoNUJ")).
neg(eqo("journals/sigmod/Franklin98b","url:http://portal.acm.org/citation.cfm%3Fid%3D197445")).
neg(eqo("journals/sigmod/FrewD97","q8jC682bYRUJ")).
neg(eqo("journals/sigmod/GatziuKBF98","YERfAnxw2RcJ")).
neg(eqo("journals/sigmod/GeppertD94","O5CPLpCj5fQJ")).
neg(eqo("journals/sigmod/GroskySF02","XK-KPRa2qjcJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","q5OOyzSAlC8J")).
neg(eqo("journals/sigmod/GuptaHR97","qz24tfFNHuoJ")).
neg(eqo("journals/sigmod/Halevy00","fbMLEWe2pKMJ")).
neg(eqo("journals/sigmod/HummerLW02","FBZw8n-gojUJ")).
neg(eqo("journals/sigmod/Ioannidis96","3IEr_j-1YNIJ")).
neg(eqo("journals/sigmod/Jannink95","2p2A5_qGf5cJ")).
neg(eqo("journals/sigmod/JensenCEGHJ94","WJ_VcY3mmEkJ")).
neg(eqo("journals/sigmod/Keim96","vkUvhZOw-1YJ")).
neg(eqo("journals/sigmod/Kemper02","qMDN6enj0VgJ")).
neg(eqo("journals/sigmod/KennedyMB96","l-ucBkIljxoJ")).
neg(eqo("journals/sigmod/KennedyMB96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1024726%26type%3Dpdf")).
neg(eqo("journals/sigmod/Kim94","-xHBsk1Rux0J")).
neg(eqo("journals/sigmod/Kim94","SWAS0JhwtXoJ")).
neg(eqo("journals/sigmod/Klein94","xtyPP3R3VOEJ")).
neg(eqo("journals/sigmod/KoksalAD98","OjZoGJLFGqIJ")).
neg(eqo("journals/sigmod/KoksalAD98","enYoi4XT7n0J")).
neg(eqo("journals/sigmod/KoksalAD98","hK0H65llIKgJ")).
neg(eqo("journals/sigmod/KoksalAD98","qsUQ1OqOwl4J")).
neg(eqo("journals/sigmod/LabrinidisR00","3Ozte0ucNJAJ")).
neg(eqo("journals/sigmod/LawderK01","KAf2DUUVabIJ")).
neg(eqo("journals/sigmod/LenzVJS03","faRBjw1op8YJ")).
neg(eqo("journals/sigmod/LiefkeS00","tggdz7LP7SwJ")).
neg(eqo("journals/sigmod/Liu01","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Liu01","wDI1Xo3Fc7AJ")).
neg(eqo("journals/sigmod/Liu01b","tVDUYwBqJAcJ")).
neg(eqo("journals/sigmod/Liu02","G2Z2jScNrQMJ")).
neg(eqo("journals/sigmod/Liu03","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Liu03c","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu03c","bF9YiKytTRgJ")).
neg(eqo("journals/sigmod/Lomet01","1YpHQXqkPv4J")).
neg(eqo("journals/sigmod/MaelbranckeO95","hwBMsP8-fXcJ")).
neg(eqo("journals/sigmod/MaximilienS02","CAKcsKXFoCoJ")).
neg(eqo("journals/sigmod/MedeirosP94","qUfWV4VVxegJ")).
neg(eqo("journals/sigmod/MedskerCS95","WGv9zvnJ484J")).
neg(eqo("journals/sigmod/MeltonE01","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637432%26coll%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MeltonE01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/NascimentoM99","TkN47KAvoVsJ")).
neg(eqo("journals/sigmod/NobleS95","egn46hGLw7gJ")).
neg(eqo("journals/sigmod/ONeilG95","Sn5j6HJ-bA8J")).
neg(eqo("journals/sigmod/PalpanasPKG03","Q6pHDaV3sG4J")).
neg(eqo("journals/sigmod/PitouraAPSV03","gxVI54gVoEgJ")).
neg(eqo("journals/sigmod/PoessF00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369291%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PossasMCR00","url:http://doi.wiley.com/10.1002/he.11109")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234903%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/QuixSJ02","xufwWHmOf6IJ")).
neg(eqo("journals/sigmod/RamDD99","pqzGz7zfpDgJ")).
neg(eqo("journals/sigmod/RamirezSP94","TwMssljLk5cJ")).
neg(eqo("journals/sigmod/RisheSBDOALOSS95","VWd7jhLXfV0J")).
neg(eqo("journals/sigmod/RoddickABDEGHLMMMW00","IGS3TtqfKUgJ")).
neg(eqo("journals/sigmod/Rosenthal98","WXKRfa6HebkJ")).
neg(eqo("journals/sigmod/RosenthalSMBTL95","oABGXQlfGKcJ")).
neg(eqo("journals/sigmod/RossCGJBV99","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/Seligman97","2KImo8jkkSwJ")).
neg(eqo("journals/sigmod/Seligman97","BK7C2yvT-MwJ")).
neg(eqo("journals/sigmod/Sidell96","iZakw-9ZuvgJ")).
neg(eqo("journals/sigmod/Snodgrass01a","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/Snodgrass94","rEKcHMTrlSEJ")).
neg(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","ki6h8TZDRb4J")).
neg(eqo("journals/sigmod/StolfoLCFE01","QdPN-QtgceAJ")).
neg(eqo("journals/sigmod/Suciu01","Ut-7k_GZdXAJ")).
neg(eqo("journals/sigmod/Suciu01","_vOvQUzSV-gJ")).
neg(eqo("journals/sigmod/TanakaV01","XDGpuS06D3EJ")).
neg(eqo("journals/sigmod/UrbanDG96","FyaDdmU186MJ")).
neg(eqo("journals/sigmod/Weikum02","dTmYA-kedS0J")).
neg(eqo("journals/sigmod/Widom94","A_i4OxOjMe0J")).
neg(eqo("journals/sigmod/Widom94","zWrQD-2VvWgJ")).
neg(eqo("journals/sigmod/Winslett01","G4ZjAVmTOBoJ")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031579%26type%3Dpdf")).
neg(eqo("journals/sigmod/WolfsonSDNR95","LSWVPfB8TC4J")).
neg(eqo("journals/sigmod/Wong95","5YSd0SJmQfcJ")).
neg(eqo("journals/sigmod/X95a","ReOfuE1ytx4J")).
neg(eqo("journals/sigmod/YeungHL94","WBSs76JVL30J")).
neg(eqo("journals/sigmod/ZobelMR96","9AXYAHPj5J8J")).
neg(eqo("journals/tods/AndriesCPB01","kgtXyZkcwTYJ")).
neg(eqo("journals/tods/BaralisW00","eDaLc3S11YQJ")).
neg(eqo("journals/tods/BellNNS96","PW3D1gCJGGUJ")).
neg(eqo("journals/tods/Bohm00","xE4TTxPJP2YJ")).
neg(eqo("journals/tods/BozkayaO99","U2fYU71slN8J")).
neg(eqo("journals/tods/BunemanO96","url:http://portal.acm.org/citation.cfm%3Fid%3D237661.237707%26dl%3DACM%26dl%3DACM%26type%3Dseries%26idx%3D237661%26part%3DProceedings%26WantType%3DProceedings%26title%3DSymposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/ChomickiTB01","pHuL-9kHWH0J")).
neg(eqo("journals/tods/CiacciaP02","t_XrLlqtRckJ")).
neg(eqo("journals/tods/CliffordC94","DlHay0icnj4J")).
neg(eqo("journals/tods/CliffordC94","l4zJZIJGgyQJ")).
neg(eqo("journals/tods/DeySB99","RQbOReOI-tsJ")).
neg(eqo("journals/tods/EiterLLS01","5HstPUbtZ1QJ")).
neg(eqo("journals/tods/FernandezKSMT02","a0HYotCwQNQJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
neg(eqo("journals/tods/GravanoGT99","sxRUI1AVXywJ")).
neg(eqo("journals/tods/JacoxS03","4NM5WR1WtPcJ")).
neg(eqo("journals/tods/Kim94","930Uth7EArkJ")).
neg(eqo("journals/tods/LiC01","9rDLhwM_4mYJ")).
neg(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
neg(eqo("journals/tods/MehrotraRKS98","tAnONC5J2W8J")).
neg(eqo("journals/tods/StolboushkinT98","ZnWLup8HMkUJ")).
neg(eqo("journals/tods/Wijsen99","y16TSY8ZmqkJ")).
neg(eqo("journals/tods/WinslettSQ94","url:http://portal.acm.org/citation.cfm%3Fid%3D1084805.1084829")).
neg(eqo("journals/tods/YanG94","KP03Ic-R8SoJ")).
neg(eqo("journals/tods/YanG99","bWOjlvqMe20J")).
neg(eqo("journals/tods/ZaharioudakisCF97","oBrOuvCpMKMJ")).
neg(eqo("journals/vldb/AbiteboulB95","J_7kZS39msAJ")).
neg(eqo("journals/vldb/AbiteboulCM98","lV0HWh9QLUQJ")).
neg(eqo("journals/vldb/AgrawalHK03","P3GB0IRKc2IJ")).
neg(eqo("journals/vldb/ApersCS02","4lrUNCU4HkoJ")).
neg(eqo("journals/vldb/ApersCS02","PKGXc-nVZ_8J")).
neg(eqo("journals/vldb/ApersCS02","url:http://www.springerlink.com/index/LD48KCXJWTCRACDL.pdf")).
neg(eqo("journals/vldb/AtluriJY03","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
neg(eqo("journals/vldb/BalkirO98","DE2RQ1QTwasJ")).
neg(eqo("journals/vldb/BarbaraI95","fWJVaVcYtZMJ")).
neg(eqo("journals/vldb/Baumann94","pJ2UEKVG_hoJ")).
neg(eqo("journals/vldb/BohmAnY97","jsJJXMHfgxAJ")).
neg(eqo("journals/vldb/BohmAnY97","kEte3P_QB60J")).
neg(eqo("journals/vldb/C95","CnNejipGlmkJ")).
neg(eqo("journals/vldb/CasatiSG01","zp6wLbjXwYcJ")).
neg(eqo("journals/vldb/ChakrabartiDAR98","AyDb4G2EiGwJ")).
neg(eqo("journals/vldb/ChakrabartiGRS01","m5CI3voYs-0J")).
neg(eqo("journals/vldb/ChanFGR02","EBXh5GwbeNMJ")).
neg(eqo("journals/vldb/ChanGR03","Xm3ygCvkmN8J")).
neg(eqo("journals/vldb/CuiW03","CYvvzEe4yt0J")).
neg(eqo("journals/vldb/DanYC95","5hCT9LLkamMJ")).
neg(eqo("journals/vldb/DanYC95","vpHpX4gkv8QJ")).
neg(eqo("journals/vldb/DiazJ97","I-JIwzc5dHUJ")).
neg(eqo("journals/vldb/EvangelidisS97","EbGZKQPyH_4J")).
neg(eqo("journals/vldb/EyalM01","j31DFYaBvVoJ")).
neg(eqo("journals/vldb/FahlR97","jJym5UnL5poJ")).
neg(eqo("journals/vldb/Guting94","0XYRlW9tvw8J")).
neg(eqo("journals/vldb/Han98","5VcKjo7jBOMJ")).
neg(eqo("journals/vldb/Han98","Rzk-cOznW1sJ")).
neg(eqo("journals/vldb/Han98","oGKKTxiRq9kJ")).
neg(eqo("journals/vldb/HarderST99","c8UDWXzN9-MJ")).
neg(eqo("journals/vldb/KashyapS96","Uv3mhmUGwdcJ")).
neg(eqo("journals/vldb/KashyapS96","ic9nuBu5xPoJ")).
neg(eqo("journals/vldb/KemperK95","31XuRNIm2TMJ")).
neg(eqo("journals/vldb/KemperK95","3sxzBAGlNMgJ")).
neg(eqo("journals/vldb/KraissW98","aFyT1FS31BUJ")).
neg(eqo("journals/vldb/LawLG99","WOHxNqdNMZoJ")).
neg(eqo("journals/vldb/LometS97","qPCh8M_RSwEJ")).
neg(eqo("journals/vldb/MylopoulosCPST96","gQVLY8V1hekJ")).
neg(eqo("journals/vldb/Navarro02","G7-LX8jcePQJ")).
neg(eqo("journals/vldb/PanagosB97","hF6d0-SWSPcJ")).
neg(eqo("journals/vldb/PapadiasS94","SLTZN9O1_wUJ")).
neg(eqo("journals/vldb/ScheuermannWZ98","rCftPicwU5oJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","jid-5bmQu00J")).
neg(eqo("journals/vldb/TanGO00","AkeqieT-JTAJ")).
neg(eqo("journals/vldb/TsatalosSI96","44R_vYrStiQJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99","a1esMNRsK_UJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","VlVV2mEnoQ4J")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/AgrawalCD02","iABZEL2Zoz8J")).
pos(eqo("conf/sigmod/AgrawalES03","HypA8oN4PqsJ")).
pos(eqo("conf/sigmod/AgrawalES03","Wrue2IkpGyEJ")).
pos(eqo("conf/sigmod/ArasuBBDIRW03","7D59wPTtkdcJ")).
pos(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
pos(eqo("conf/sigmod/BabyCY01","rNoNn5hWsroJ")).
pos(eqo("conf/sigmod/BarclaySG00","6uaAB7bg6C8J")).
pos(eqo("conf/sigmod/BarclaySG00","v6Rokk9Eht8J")).
pos(eqo("conf/sigmod/BaruFGHJPW95","C60KJG_xVm0J")).
pos(eqo("conf/sigmod/BaruGLMPVC99","mXKKjAJUm-oJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","nTC3FQGaT_YJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wTXunETZhPwJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wsNuAYMG0QEJ")).
pos(eqo("conf/sigmod/BaumannDFRW98","k3WA-AE7Sh4J")).
pos(eqo("conf/sigmod/BerckenDS00","-3JQfRZsy8wJ")).
pos(eqo("conf/sigmod/BerckenDS00","Dy5Eeh8JzmgJ")).
pos(eqo("conf/sigmod/BilirisDGJR94","3Lzo6p8X-n4J")).
pos(eqo("conf/sigmod/Blakeley96","1fs-qN_SdH4J")).
pos(eqo("conf/sigmod/BlakeleyD00","ZSR-MThg9UEJ")).
pos(eqo("conf/sigmod/BlohsfeldKS99","PQbi3PaRh84J")).
pos(eqo("conf/sigmod/BorkarDS01","8fu2bhk_i9EJ")).
pos(eqo("conf/sigmod/BorkarDS01","8zFEVer1rBUJ")).
pos(eqo("conf/sigmod/BrinkhoffKSS94","e4s7pmZj8UAJ")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/BrodskyK95","SFmnhrhoQzgJ")).
pos(eqo("conf/sigmod/BrodskySCE99","_cUSf4sG_28J")).
pos(eqo("conf/sigmod/BrodskySCE99","jnBo-gBTmAcJ")).
pos(eqo("conf/sigmod/Brown99","itP4yy9sLUUJ")).
pos(eqo("conf/sigmod/BryanMCLG94","nbU-wr3ivUIJ")).
pos(eqo("conf/sigmod/CareyCNVDRSM99","W6ROObWo3bIJ")).
pos(eqo("conf/sigmod/CareyMN97","6YXYnLb8CyYJ")).
pos(eqo("conf/sigmod/CatarciS94","ga4l4QhCXU4J")).
pos(eqo("conf/sigmod/CatarciS94","yaaZKZCP3soJ")).
pos(eqo("conf/sigmod/ChangC01","XbmULzOYzZUJ")).
pos(eqo("conf/sigmod/ChangG99","8Yt1Mba9-wQJ")).
pos(eqo("conf/sigmod/ChaudhuriGGM03","H5IdN0_MQw4J")).
pos(eqo("conf/sigmod/ChaudhuriGGM03","mNdoyLMYPqgJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","3fEogSGG3wQJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","Lnp1RVSzInEJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","bFDFn3OmNAQJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","niAPzsMp2igJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","GL8XEeYm7GsJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","U0w9W7YcsZwJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","clNmwzm-5acJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","xPkLZK36UBUJ")).
pos(eqo("conf/sigmod/ChenCPPSTM00","Ab6MIDVDzhAJ")).
pos(eqo("conf/sigmod/ChenZCKR01","RHoy5iOHsJwJ")).
pos(eqo("conf/sigmod/CherniackZ96","ZsHfcZJwFQQJ")).
pos(eqo("conf/sigmod/CherniackZ96","aQc379dSLlIJ")).
pos(eqo("conf/sigmod/CherniackZ96","c9Humx2-EMgJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","MgphE2z3NqYJ")).
pos(eqo("conf/sigmod/ColeG94","_6wwPJEGUiAJ")).
pos(eqo("conf/sigmod/ColeG94","z_W8jZ203sUJ")).
pos(eqo("conf/sigmod/CranorJSS03","gya0M9b1KrgJ")).
pos(eqo("conf/sigmod/DasuJMS02","zTF5z0v_nh0J")).
pos(eqo("conf/sigmod/DattaDRTV01","qK-N8yVLSWUJ")).
pos(eqo("conf/sigmod/DavulcuFKR99","TDyW6V4cc7MJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","gyYBYgpB63sJ")).
pos(eqo("conf/sigmod/DeHaanTCO03","uq-pFFsnBusJ")).
pos(eqo("conf/sigmod/DeutschFS99","-KuX7UT0JIIJ")).
pos(eqo("conf/sigmod/DeutschFS99","2lypQEgzfb8J")).
pos(eqo("conf/sigmod/DeutschFS99","9WLtxnKtm_EJ")).
pos(eqo("conf/sigmod/DeutschFS99","De_3PkxkhzIJ")).
pos(eqo("conf/sigmod/DeutschFS99","kDYpG4mLjLkJ")).
pos(eqo("conf/sigmod/DewanSHH94","GUdXGx4blW8J")).
pos(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
pos(eqo("conf/sigmod/DraperHW01","6MdiqTp20aoJ")).
pos(eqo("conf/sigmod/DraperHW01","6csUZFROjIEJ")).
pos(eqo("conf/sigmod/Englert94","KOpz_NXJ3WUJ")).
pos(eqo("conf/sigmod/FreedmanD95","dt4Mxy8b2hwJ")).
pos(eqo("conf/sigmod/Gal00","SudUID_rEy0J")).
pos(eqo("conf/sigmod/GardarinMP95","IOqPoq2MSvQJ")).
pos(eqo("conf/sigmod/GardarinMP95","VOxehNSHEWQJ")).
pos(eqo("conf/sigmod/GardarinMP95","l-9pykkOVrkJ")).
pos(eqo("conf/sigmod/GarofalakisI96","MfPbk62EdyQJ")).
pos(eqo("conf/sigmod/GebhardtJJ97","zbxsamf4QY8J")).
pos(eqo("conf/sigmod/Gerber95","wlxZ0FqTy_MJ")).
pos(eqo("conf/sigmod/GodfreySE98","-H3tXntLhowJ")).
pos(eqo("conf/sigmod/Golding95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223865%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D223784%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/GravanoGT94","OYFpMlm5yCQJ")).
pos(eqo("conf/sigmod/GravanoGT94","VxiP2MuiMM0J")).
pos(eqo("conf/sigmod/GravanoGT94","nAJnhh70_0kJ")).
pos(eqo("conf/sigmod/GravanoGT94","sk7DIwcSZrwJ")).
pos(eqo("conf/sigmod/GravanoGT94","z26H2tQo7bkJ")).
pos(eqo("conf/sigmod/GriffinL95","6QZGeKna5lgJ")).
pos(eqo("conf/sigmod/GriffinL95","nXT3j4XaZxIJ")).
pos(eqo("conf/sigmod/GrossmanHQ95","Z_kXgQsN0W0J")).
pos(eqo("conf/sigmod/GuhaRS98","LoR0K8QRGkgJ")).
pos(eqo("conf/sigmod/GuhaRS98","btOlpr6NZoIJ")).
pos(eqo("conf/sigmod/GuhaRS98","dD4qUMoxnpEJ")).
pos(eqo("conf/sigmod/GuhaRS98","nMzsE-ScW4MJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","uPHrOdEDjlEJ")).
pos(eqo("conf/sigmod/HanFHCC94","dvmROCT52KoJ")).
pos(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
pos(eqo("conf/sigmod/HanPY00","2xwKDuA0DI8J")).
pos(eqo("conf/sigmod/HanPY00","63XKDNdtzp8J")).
pos(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
pos(eqo("conf/sigmod/HanPY00","oeBeDPX7b9kJ")).
pos(eqo("conf/sigmod/HanPY00","rLJSEgt6UbMJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","-RzBfKSBxpgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","ESZwkhGzOboJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","sLvivSi__BcJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","uKGmcc4xUG4J")).
pos(eqo("conf/sigmod/HellersteinA00","Gsb6dnkFBMoJ")).
pos(eqo("conf/sigmod/HellersteinA00","ZuCOw9hYVU8J")).
pos(eqo("conf/sigmod/HernandezS95","CckDkmI4U3wJ")).
pos(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
pos(eqo("conf/sigmod/HinneburgKW02","VWd7jhLXfV0J")).
pos(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
pos(eqo("conf/sigmod/HoAMS97","4YsYF_8QeogJ")).
pos(eqo("conf/sigmod/HoAMS97","LWXzOXyOy24J")).
pos(eqo("conf/sigmod/HoAMS97","r1um7d3ckAYJ")).
pos(eqo("conf/sigmod/HsuLG00","AvYMafGTVLEJ")).
pos(eqo("conf/sigmod/HungYK96","3gpc7dPy-ucJ")).
pos(eqo("conf/sigmod/HungYK96","NY5e4MkJ6VYJ")).
pos(eqo("conf/sigmod/HungYK96","P6VVKZUo4pgJ")).
pos(eqo("conf/sigmod/HungYK96","bTI28RjBpPwJ")).
pos(eqo("conf/sigmod/IoannidisL94","dDHNsS9sisEJ")).
pos(eqo("conf/sigmod/JagadishLS99","sh2u_UFoG74J")).
pos(eqo("conf/sigmod/KarbhariRXD02","TZsVVmiiHqEJ")).
pos(eqo("conf/sigmod/Kim94","GzJII5F7OzAJ")).
pos(eqo("conf/sigmod/KornackerMH97","J8sGEkYqAFcJ")).
pos(eqo("conf/sigmod/KornackerMH97","v34_ZFX7kZYJ")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/KriegelBKPS03","i0c65loyE60J")).
pos(eqo("conf/sigmod/LacroixSC98","MyaiGcr-oYkJ")).
pos(eqo("conf/sigmod/LehnerSPC00","UFKz6Q0wVi4J")).
pos(eqo("conf/sigmod/LehnerSPC00","xfWGb928UfcJ")).
pos(eqo("conf/sigmod/LiS98","Vxg-4KP7FfEJ")).
pos(eqo("conf/sigmod/LuoEHN02","7p7mpmvIBrYJ")).
pos(eqo("conf/sigmod/MaddenH02","NXakCefUcdUJ")).
pos(eqo("conf/sigmod/MamoulisP99","RusJdYPDgQ4J")).
pos(eqo("conf/sigmod/MamoulisP99","xdAsc3yVWvYJ")).
pos(eqo("conf/sigmod/MamoulisP99","z9MQwq7G3GYJ")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/McAuliffeCS96","C0vLucG1HBMJ")).
pos(eqo("conf/sigmod/MogiK96","ybgxHuCAS_8J")).
pos(eqo("conf/sigmod/Mohan02","eyxIItge9MQJ")).
pos(eqo("conf/sigmod/Mohan02","qbrkg2DRU3AJ")).
pos(eqo("conf/sigmod/Mohan94","Ft1YZIFfu0cJ")).
pos(eqo("conf/sigmod/Mohan94","IWM2gExnQLkJ")).
pos(eqo("conf/sigmod/Mohan94","enYJ_2U2NdUJ")).
pos(eqo("conf/sigmod/Mohan99","XppwYYxOpksJ")).
pos(eqo("conf/sigmod/MoleskyR95","mSR0bA8pIOwJ")).
pos(eqo("conf/sigmod/Mylopoulos98","vU_Vo2059VUJ")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","O-TrhFwhKM8J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/ONeilQ97","6twtfqrudGcJ")).
pos(eqo("conf/sigmod/ONeilQ97","FOruO1PeowAJ")).
pos(eqo("conf/sigmod/OriaOILY00","9SbEzfHLSooJ")).
pos(eqo("conf/sigmod/PalmerF00","eiA9HVOF2IsJ")).
pos(eqo("conf/sigmod/PangCL94","beMsu5ebf30J")).
pos(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/PatelYKTNBHRLEKGDN97","0inuMFZSQ50J")).
pos(eqo("conf/sigmod/PatelYKTNBHRLEKGDN97","qe3zCXe4dHQJ")).
pos(eqo("conf/sigmod/PiatkoYLS96","3NMPG1vUNgwJ")).
pos(eqo("conf/sigmod/QuassW97","9nkD3JyhE1kJ")).
pos(eqo("conf/sigmod/QuassW97","TfIJHxpZeJIJ")).
pos(eqo("conf/sigmod/RajagopalanML98","HVP6eYl30IgJ")).
pos(eqo("conf/sigmod/RajagopalanML98","M2bWqRDDfkUJ")).
pos(eqo("conf/sigmod/RaoZML02","7Ucs6vmjHN0J")).
pos(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
pos(eqo("conf/sigmod/RodriguezR00","MCDgDxsc8rcJ")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375796%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","QzW5By67KwcJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","00c1qmRdM5IJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","efwTNo1wRnMJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","imAsAkfukSYJ")).
pos(eqo("conf/sigmod/SagonasSW94","uAoWmK-jEGAJ")).
pos(eqo("conf/sigmod/SalemBCL00","FElMcikK2GUJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","a7v0bHRrpjMJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","wISxjPqlwZoJ")).
pos(eqo("conf/sigmod/SarawagiTA98","ZLUo-gCGx5EJ")).
pos(eqo("conf/sigmod/SarawagiTA98","wkgGoKqPVzQJ")).
pos(eqo("conf/sigmod/Seshadri99","url:http://portal.acm.org/citation.cfm%3Fid%3D304182.304226")).
pos(eqo("conf/sigmod/SeshadriLR94","G4N8qaBAG4kJ")).
pos(eqo("conf/sigmod/SeshadriP97","Df8s-N_5U3EJ")).
pos(eqo("conf/sigmod/ShintaniK98","Zd4RU49YmRgJ")).
pos(eqo("conf/sigmod/Spiro98","u4ZAi-DRoHkJ")).
pos(eqo("conf/sigmod/SrikantA96","9t4Mce85HT4J")).
pos(eqo("conf/sigmod/SrikantA96","WSVs3nCRe8EJ")).
pos(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
pos(eqo("conf/sigmod/SrikantA96","o8sObeHIA40J")).
pos(eqo("conf/sigmod/SrikantA96","tTQpdbZYZGoJ")).
pos(eqo("conf/sigmod/SzalayGKT00","1kKap3JyndkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","4yvrgPBJUBYJ")).
pos(eqo("conf/sigmod/SzalayGKT00","6Kdau1eh-hMJ")).
pos(eqo("conf/sigmod/SzalayGKT00","GYR0v7CFkP0J")).
pos(eqo("conf/sigmod/SzalayGKT00","zxOI0ZD8jeIJ")).
pos(eqo("conf/sigmod/Tajima96","IZSzLlgi8tUJ")).
pos(eqo("conf/sigmod/ThomasDM95","-NNuFjchxnMJ")).
pos(eqo("conf/sigmod/ThomasDM95","1zgqAaZv3NAJ")).
pos(eqo("conf/sigmod/TomasicGS94","kRHYZELNeoIJ")).
pos(eqo("conf/sigmod/TrisoliniLN99","cFMtMf7bLzIJ")).
pos(eqo("conf/sigmod/Ubell94","ZrMjnFuPnI0J")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/VanceM96","QgKRpqigXEsJ")).
pos(eqo("conf/sigmod/ViglasN02","2aeb_pBP7lcJ")).
pos(eqo("conf/sigmod/ViglasN02","4QupwyuXHi8J")).
pos(eqo("conf/sigmod/VossenW99","9PhYz-N58A8J")).
pos(eqo("conf/sigmod/Whelan98","Jp9LEvXjiJAJ")).
pos(eqo("conf/sigmod/WhiteD95","6SBwemr2zscJ")).
pos(eqo("conf/sigmod/YanMHF01","adm7QWgi-BAJ")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/YerneniLGU99","Gnb52DoKdJwJ")).
pos(eqo("conf/sigmod/ZhangDWEMPMDR03","gWslyEjd3BYJ")).
pos(eqo("conf/sigmod/ZhangNBB94","bymQ_6SSse4J")).
pos(eqo("conf/sigmod/ZhangNBB94","qOgXuRc7f4QJ")).
pos(eqo("conf/sigmod/ZhangRL96","46aixXBMD6sJ")).
pos(eqo("conf/sigmod/ZhangRL96","NzUcyD-oMpQJ")).
pos(eqo("conf/sigmod/ZhangRL96","PdBcau_cG-AJ")).
pos(eqo("conf/sigmod/ZhangRL96","kBlynBey41QJ")).
pos(eqo("conf/sigmod/ZhuS03","QZs7L6Y94_UJ")).
pos(eqo("conf/sigmod/ZouS96","qPCh8M_RSwEJ")).
pos(eqo("conf/vldb/AboulnagaAN01","P6wBeL9DsREJ")).
pos(eqo("conf/vldb/AcharyaGP99","-7tsGpHin24J")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","mB8W6em6zi8J")).
pos(eqo("conf/vldb/ArgePRSV98","A5Eiwdh71m0J")).
pos(eqo("conf/vldb/ArunJ98","1dqeMksCm74J")).
pos(eqo("conf/vldb/BalminHKPSW03","8xRHvInl0_0J")).
pos(eqo("conf/vldb/BaralisPT97","tyNO4U-fmrIJ")).
pos(eqo("conf/vldb/Baumann03","pJ2UEKVG_hoJ")).
pos(eqo("conf/vldb/Bayer95","W3l3pQ62_YMJ")).
pos(eqo("conf/vldb/BelussiF95","5FEmoD1TIdwJ")).
pos(eqo("conf/vldb/BelussiF95","a78Lxr80kJUJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","4AcfxYXwZnIJ")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BliujuteJSS98","wbGdc_RsI14J")).
pos(eqo("conf/vldb/BouganimCDDGS99","Ult4nmnmJp8J")).
pos(eqo("conf/vldb/BratsbergH01","x-oQarjjgccJ")).
pos(eqo("conf/vldb/BridgeJKLLM97","JO9Jnx_gGIUJ")).
pos(eqo("conf/vldb/BrodieC99","PAahJo-PXsIJ")).
pos(eqo("conf/vldb/BrownCC94","oayI0FKl-nQJ")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("conf/vldb/CarneyCCCLSSTZ02","HLd7exz0QagJ")).
pos(eqo("conf/vldb/CarneyCZRCS03","y5h2qhOGUSgJ")).
pos(eqo("conf/vldb/CasatiDGS01","bFnDGrZ_4voJ")).
pos(eqo("conf/vldb/CeriM03","G2QuI5QYYMoJ")).
pos(eqo("conf/vldb/ChanFFGR02","ZFI7XBuonJAJ")).
pos(eqo("conf/vldb/ChangG97","bZlpjMDZD5UJ")).
pos(eqo("conf/vldb/ChaudhuriGS95","WYgQ_Mhdp9sJ")).
pos(eqo("conf/vldb/Chawathe99","1-mxxSvIMB8J")).
pos(eqo("conf/vldb/Chawathe99","w6VtZRVAZV8J")).
pos(eqo("conf/vldb/ChenCFGJMTW99","Hq3W65us8dkJ")).
pos(eqo("conf/vldb/ChenCFGJMTW99","NHGP6JIxXjoJ")).
pos(eqo("conf/vldb/ChirkovaHS01","NdmocXlpq9QJ")).
pos(eqo("conf/vldb/DarmontS99","1GWsEQSvJmoJ")).
pos(eqo("conf/vldb/DarmontS99","Ebi8v9FZXcgJ")).
pos(eqo("conf/vldb/DeckerK03","es2kSNccUGMJ")).
pos(eqo("conf/vldb/DiaoLCT00","hdDsjafWJIwJ")).
pos(eqo("conf/vldb/Draluk01","FhNjU1YhINUJ")).
pos(eqo("conf/vldb/FaloutsosG96","ZMMhKani9O0J")).
pos(eqo("conf/vldb/FaloutsosG96","vwcVawlOJn0J")).
pos(eqo("conf/vldb/FaloutsosJS97","u_9qWSpjaO4J")).
pos(eqo("conf/vldb/FangSGMU98","F8EAXPxQQsIJ")).
pos(eqo("conf/vldb/FerrandinaMZ94","yQ2TMZ92GaIJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","X-jmxnecLOEJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","jimNuiynSDIJ")).
pos(eqo("conf/vldb/Garcia-MolinaLY98","lWVWAhlsyYYJ")).
pos(eqo("conf/vldb/GardarinGT95","DAUHADa6RjQJ")).
pos(eqo("conf/vldb/GardarinST96","OHR5iQWPuyYJ")).
pos(eqo("conf/vldb/GardarinST96","RB2VKRwnXywJ")).
pos(eqo("conf/vldb/GardarinST96","q0K1yN3kIs4J")).
pos(eqo("conf/vldb/GarofalakisIO98","ReV4xpbiC6EJ")).
pos(eqo("conf/vldb/GarofalakisIO98","i7AX4VpJJbYJ")).
pos(eqo("conf/vldb/GarofalakisRS99","7BITau8qhpEJ")).
pos(eqo("conf/vldb/GarofalakisRS99","poso7AKokFMJ")).
pos(eqo("conf/vldb/Gentili01","2j1dalv3kCEJ")).
pos(eqo("conf/vldb/GilbertKMS01","9rDLhwM_4mYJ")).
pos(eqo("conf/vldb/GilbertKMS01","Xy_RpFaaxtQJ")).
pos(eqo("conf/vldb/GilbertKMS02","xziY9wNuVzwJ")).
pos(eqo("conf/vldb/GinisHKMT97","GBVvAWWCTcgJ")).
pos(eqo("conf/vldb/GuPS00","W-hUzvTqikcJ")).
pos(eqo("conf/vldb/GuPS00","mRWLGqueLNsJ")).
pos(eqo("conf/vldb/GuntzerBK00","EdQ4M7GEnzoJ")).
pos(eqo("conf/vldb/GuntzerBK00","id3rk1JgWx0J")).
pos(eqo("conf/vldb/GutierrezPST94","VUU_DceCRXAJ")).
pos(eqo("conf/vldb/HaasNSS95","x70Y3qaTL40J")).
pos(eqo("conf/vldb/HalversonBKKRTVWND03","oR7DmJ9JJDYJ")).
pos(eqo("conf/vldb/HelmerM97","vInYFLVq0uIJ")).
pos(eqo("conf/vldb/HelmerWM98","7Ycm8V-i9g0J")).
pos(eqo("conf/vldb/HjelsvoldM94","5Wuyp1aLBocJ")).
pos(eqo("conf/vldb/HvasshovdBT00","af50lhGnD8gJ")).
pos(eqo("conf/vldb/IlyasAE02","nQsk3GveFP0J")).
pos(eqo("conf/vldb/ImielinskiB02","IQ_MbfJGh0kJ")).
pos(eqo("conf/vldb/JagadishLRSS94","em_mB-ifc80J")).
pos(eqo("conf/vldb/JosifovskiR99","a58OzgW7AvUJ")).
pos(eqo("conf/vldb/Kiessling02","6Rn6hsdao-wJ")).
pos(eqo("conf/vldb/Koch03","rhxIrsQkm5AJ")).
pos(eqo("conf/vldb/KonigW99","6HMffRHCspAJ")).
pos(eqo("conf/vldb/KornackerB95","TjG5memyVWIJ")).
pos(eqo("conf/vldb/KornackerB95","e1yWeerxOKMJ")).
pos(eqo("conf/vldb/KornackerB95","pFhk85qhZrgJ")).
pos(eqo("conf/vldb/Korth95","UZAQL1o-c0MJ")).
pos(eqo("conf/vldb/KoudasMJ99","dRemTC899xcJ")).
pos(eqo("conf/vldb/KoudasMJ99","wzae2lO15U8J")).
pos(eqo("conf/vldb/LiCHPALHAY01","Nn0x6RmkrVwJ")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/LuSL95","2g1GW3T-fVQJ")).
pos(eqo("conf/vldb/LuSL95","h7_7SZrI7M0J")).
pos(eqo("conf/vldb/LuSL95","xGK3seG0Mn4J")).
pos(eqo("conf/vldb/LuSL95","z7zkXK4G6YcJ")).
pos(eqo("conf/vldb/LudasaherGM00","H4hHa7dQdSAJ")).
pos(eqo("conf/vldb/MadhavanBR01","5mM4rpgyeNoJ")).
pos(eqo("conf/vldb/MadhavanBR01","66dWDpWjbbwJ")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/MadhavanH03","ujCYoqKS6BcJ")).
pos(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
pos(eqo("conf/vldb/ManolopoulosT01","BqSvyuGWls8J")).
pos(eqo("conf/vldb/MatiasVW00","7SeTnikjovEJ")).
pos(eqo("conf/vldb/McHughW99","bXRF6rASxhgJ")).
pos(eqo("conf/vldb/MengLLA03","_dOpWA3QWOEJ")).
pos(eqo("conf/vldb/MeoPC96","Opm5VlTzQTAJ")).
pos(eqo("conf/vldb/MeoPC96","SNIbAV2EN0MJ")).
pos(eqo("conf/vldb/MorimotoIM97","3enylshvOl8J")).
pos(eqo("conf/vldb/MorishimaKKT01","8hDo6qczOzMJ")).
pos(eqo("conf/vldb/NaumannLF99","MEQuU1E4vdoJ")).
pos(eqo("conf/vldb/NaumannLF99","spErtT_VfeEJ")).
pos(eqo("conf/vldb/NgH94","6OfJSMB4vOcJ")).
pos(eqo("conf/vldb/NgH94","9S2apUr1vPMJ")).
pos(eqo("conf/vldb/NgH94","YMluKoJrxMcJ")).
pos(eqo("conf/vldb/NgY94","5e8pCA8tKKAJ")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/OoiYTJ01","RFEE_MNM8IUJ")).
pos(eqo("conf/vldb/PacittMS99","jJyGKE2N34gJ")).
pos(eqo("conf/vldb/PardonA00","Bax8yKEV6McJ")).
pos(eqo("conf/vldb/PellenkoftLK97","793XPMTdcBEJ")).
pos(eqo("conf/vldb/PellenkoftLK97","mCU3zHcPfCsJ")).
pos(eqo("conf/vldb/PoosalaI97","QIG8th9DHbQJ")).
pos(eqo("conf/vldb/PottingerB03","Gq2yqOZGhBgJ")).
pos(eqo("conf/vldb/PottingerB03","rpAwxzbuM_oJ")).
pos(eqo("conf/vldb/Pound99","zWp_JdEQ8MgJ")).
pos(eqo("conf/vldb/RaghavanG01","LcX8Pm2ABJsJ")).
pos(eqo("conf/vldb/RaghavanG01","MytkkvQ5ieMJ")).
pos(eqo("conf/vldb/RahmM95","6ioboOxJvQIJ")).
pos(eqo("conf/vldb/ReuterCGSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.673318")).
pos(eqo("conf/vldb/RohmBSS02","YMcmy4FOXi8J")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","T2fm7Wb1ak4J")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/SchmidtWKCMB02","CvGGYMrKR2sJ")).
pos(eqo("conf/vldb/SchmidtWKCMB02","SZLkVciImAIJ")).
pos(eqo("conf/vldb/Schoning98","HEJ1Z4Q_xXMJ")).
pos(eqo("conf/vldb/SeligmanBNSW95","T6a86CQCuHoJ")).
pos(eqo("conf/vldb/SeligmanBNSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.673303%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/ShaferA97","O4UcgdEM7vYJ")).
pos(eqo("conf/vldb/ShahDR03","FR1h4tU9FosJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","JqfEbjic16sJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","iME-SCx_DIgJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","kaq5eLrzrQsJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
pos(eqo("conf/vldb/Shaw98","2CygtSE5o1UJ")).
pos(eqo("conf/vldb/Shmueli01","rEwEqoAns-gJ")).
pos(eqo("conf/vldb/ShuklaDN98","1eCp1f8DhasJ")).
pos(eqo("conf/vldb/ShuklaDN98","laYa1No1nisJ")).
pos(eqo("conf/vldb/SistlaYH94","FT4Sfn-Z7GUJ")).
pos(eqo("conf/vldb/SistlaYH94","_jl3bN2QlE4J")).
pos(eqo("conf/vldb/SistlaYLL95","lkNgibBst0MJ")).
pos(eqo("conf/vldb/Sol01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672038%26coll%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/SreenathS94","sUcJBJwvKTUJ")).
pos(eqo("conf/vldb/StanoiRAA01","SBpUQ0L7KUgJ")).
pos(eqo("conf/vldb/StaudtJ96","que4v9cvspwJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Xr2RguUzt-gJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/SteenhagenABB94","n5yJ4y54WbwJ")).
pos(eqo("conf/vldb/StohrR01","jn3pvb3hRzwJ")).
pos(eqo("conf/vldb/TanSHCR01","004z3CTw0DEJ")).
pos(eqo("conf/vldb/TatbulCZCS03","F42wOOy-KR0J")).
pos(eqo("conf/vldb/TatbulCZCS03","TAsynkdIAfwJ")).
pos(eqo("conf/vldb/Toivonen96","R3wCZGqY0nYJ")).
pos(eqo("conf/vldb/Toivonen96","yd2dxAbjvTAJ")).
pos(eqo("conf/vldb/TreschPL95","1rPUqMFsS3AJ")).
pos(eqo("conf/vldb/Tygar98","Q8cPIOWKZZ4J")).
pos(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
pos(eqo("conf/vldb/Vaskevitch95","s6Ax0WdZp6IJ")).
pos(eqo("conf/vldb/Wadler01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672033")).
pos(eqo("conf/vldb/WangSG03","T1TgIax4zVcJ")).
pos(eqo("conf/vldb/WangZL99","G4H0wLuSxaIJ")).
pos(eqo("conf/vldb/WuFSP00","XojbAfbtdvcJ")).
pos(eqo("conf/vldb/YagoubFIV00a","hMsWZU5TJWYJ")).
pos(eqo("conf/vldb/YangLH03","hUMTG7HNlyAJ")).
pos(eqo("conf/vldb/YuAA03","4bvjebYsdRkJ")).
pos(eqo("conf/vldb/ZhouS03","NlDvk5J0WwEJ")).
pos(eqo("conf/vldb/ZimbraoS98","1KckBFVfgyMJ")).
pos(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
pos(eqo("conf/vldb/ZouS98","fPzfCbyzqsoJ")).
pos(eqo("conf/vldb/ZurekS99","mEdoUlcnDsgJ")).
pos(eqo("journals/sigmod/Aberer01","7CLhi_LOtoUJ")).
pos(eqo("journals/sigmod/ArenasKKKMM03","rl50qPw8UaEJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","5tuINV43CDUJ")).
pos(eqo("journals/sigmod/BargaL02","QTzV3iNq2O8J")).
pos(eqo("journals/sigmod/BargaL02","fY3kkkzBLw8J")).
pos(eqo("journals/sigmod/BawaCCDGGKMSSVY03","7gJjI63FlyYJ")).
pos(eqo("journals/sigmod/BernsteinDK99","MsK0xHsckUIJ")).
pos(eqo("journals/sigmod/BernsteinDK99","Ye5fTBiMoUwJ")).
pos(eqo("journals/sigmod/BernsteinHP00","FFzJxlpy6TsJ")).
pos(eqo("journals/sigmod/BernsteinHP00","oHXkI3GgweIJ")).
pos(eqo("journals/sigmod/BertinoEH03","4m-WmWU5iGYJ")).
pos(eqo("journals/sigmod/BonnetBDL03","aovCRhocZUcJ")).
pos(eqo("journals/sigmod/BrunieK96","spI2g7jFHuYJ")).
pos(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
pos(eqo("journals/sigmod/BusslerFM02","RaOQG4YyzM4J")).
pos(eqo("journals/sigmod/CampbellEM03","N9u28V6NZTIJ")).
pos(eqo("journals/sigmod/CarmelMS01","bolov3CrMYwJ")).
pos(eqo("journals/sigmod/ChangGKRS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290607%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChristoffelPSL98","F7QAoJ5PGekJ")).
pos(eqo("journals/sigmod/Cingil02","2K6rhX16hXwJ")).
pos(eqo("journals/sigmod/DrewHKKLLLSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219769%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Eisenberg96","tFbkjO2wcFMJ")).
pos(eqo("journals/sigmod/EnglertGH95","JRXuKm3E_foJ")).
pos(eqo("journals/sigmod/FernandezFLS97","9NlVdFCl2ysJ")).
pos(eqo("journals/sigmod/GatziuKBF98","C8tPNXRbNnIJ")).
pos(eqo("journals/sigmod/GobleR02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
pos(eqo("journals/sigmod/Hainaut03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959087%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HansonN99","id1te58YJlUJ")).
pos(eqo("journals/sigmod/HellersteinHM03","6ussAgzdL6oJ")).
pos(eqo("journals/sigmod/HuangKL02","g4mWc14U8m4J")).
pos(eqo("journals/sigmod/HuangKL02","yyUMt1X2WXcJ")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/JenningsNF98","vgi1l8lbDcsJ")).
pos(eqo("journals/sigmod/KantM00","url:http://portal.acm.org/citation.cfm%3Fid%3D362084.362091%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KaradimitriouT97","SrCBkHnIFL8J")).
pos(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/KoksalAD98","c2UQ3AM5_f8J")).
pos(eqo("journals/sigmod/Konig-RiesL97","3fQBks2g-BMJ")).
pos(eqo("journals/sigmod/Kosch02","_avm808LQocJ")).
pos(eqo("journals/sigmod/LacroixB03","url:http://portal.acm.org/citation.cfm%3Fid%3D640990.641003%26dl%3Dportal%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LaenderRST02","34QnrkmS0Y8J")).
pos(eqo("journals/sigmod/LaenderRST02","eQPLe8gg-mIJ")).
pos(eqo("journals/sigmod/Lee95","ozmSjoqqFtwJ")).
pos(eqo("journals/sigmod/Loeffen94","gb-yIDOxaEkJ")).
pos(eqo("journals/sigmod/Loeffen94","jFNkGh68g6EJ")).
pos(eqo("journals/sigmod/Loeffen94","nSkolxxp1y0J")).
pos(eqo("journals/sigmod/LudascherMM01","16yr6uv8Rn8J")).
pos(eqo("journals/sigmod/LudascherMM01","PyzHbvS-dCkJ")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MedeirosP94","chmPCuLihZoJ")).
pos(eqo("journals/sigmod/MedeirosP94","tnHDLJxMoQcJ")).
pos(eqo("journals/sigmod/MedskerCS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Nascimento03","url:http://portal.acm.org/citation.cfm%3Fid%3D776985.776996%26dl%3Dportal%26dl%3DACM%26idx%3D776985%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NorrieBSW94","ctEdyJRdTbkJ")).
pos(eqo("journals/sigmod/OukselS99","S-LYnzS1K70J")).
pos(eqo("journals/sigmod/PapazoglouH99","d5BG9F7_LGMJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","ZsUpDroAFBQJ")).
pos(eqo("journals/sigmod/PitouraAPSV03","hn2MANNgz9sJ")).
pos(eqo("journals/sigmod/RisheSBDOALOSS95","pGU2Ew1AQkoJ")).
pos(eqo("journals/sigmod/RoantreeMH99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RoantreeS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637435%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RoantreeS02","xfrOR_G4_UoJ")).
pos(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/citation.cfm%3Fid%3D202672")).
pos(eqo("journals/sigmod/SlivinskasJS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565119%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Snodgrass03b","PmIVKWJ5_V4J")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","psdMY-oUz4cJ")).
pos(eqo("journals/sigmod/SommerGB02","8l5_eKZcCh8J")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/SycaraKWL99","7OyvdUHeptMJ")).
pos(eqo("journals/sigmod/SycaraKWL99","CfVOsnm-ebMJ")).
pos(eqo("journals/sigmod/SycaraKWL99","foOIj5nrS-gJ")).
pos(eqo("journals/sigmod/TsotrasJS98","FBZw8n-gojUJ")).
pos(eqo("journals/sigmod/TsotrasJS98","f3-E7x12K4gJ")).
pos(eqo("journals/sigmod/Vassilakis00","e0j-56kaeR4J")).
pos(eqo("journals/sigmod/Vassilakis00","nZO8ZA4eYzYJ")).
pos(eqo("journals/sigmod/VetterliVS00","h7RBOvmQHhEJ")).
pos(eqo("journals/sigmod/Yang94","sHJ914nPZtUJ")).
pos(eqo("journals/sigmod/YauLMS99","bhVBJw9Rp3QJ")).
pos(eqo("journals/tods/BaralisW00","4RrNbX-RjpsJ")).
pos(eqo("journals/tods/BeneventanoBS03","rRH6Z1oP78cJ")).
pos(eqo("journals/tods/BrightHP94","BHvvo_nJxucJ")).
pos(eqo("journals/tods/CeriFPT94","aphxPCo8qkgJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","_nOW6fmEcTEJ")).
pos(eqo("journals/tods/DekhtyarRS01","jZShiF9wrikJ")).
pos(eqo("journals/tods/DekhtyarRS01","ywEAyex_frMJ")).
pos(eqo("journals/tods/FraternaliT95","sh-E7oORhVMJ")).
pos(eqo("journals/tods/FukudaMMT01","Bcuo4_yr2p0J")).
pos(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
pos(eqo("journals/tods/FukudaMMT01","lmXiI4fB9vgJ")).
pos(eqo("journals/tods/FukudaMMT01","sOBRaiLLvZgJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","axMI0TqrxxQJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0252444CI")).
pos(eqo("journals/tods/GhandeharizadehHJ96","vMVuIqz5BiwJ")).
pos(eqo("journals/tods/GraefeC95","Bn8s7u5T9SAJ")).
pos(eqo("journals/tods/GuoSW96","V8Ls_TYs6mgJ")).
pos(eqo("journals/tods/GutingBEJLSV00","1qV5-83rTyUJ")).
pos(eqo("journals/tods/HjaltasonS03","9Wan9sPNUAYJ")).
pos(eqo("journals/tods/KarpSP03","mAQIVsd2VOMJ")).
pos(eqo("journals/tods/KossmannFDA00","8tDPAHGDRggJ")).
pos(eqo("journals/tods/KrishnakumarB94","8ZjEDOBUd_QJ")).
pos(eqo("journals/tods/LiuM96","TNx5vnRHHxMJ")).
pos(eqo("journals/tods/LiuM96","xeceK06Z5DIJ")).
pos(eqo("journals/tods/Meo00","NQShGztSLaoJ")).
pos(eqo("journals/tods/MuralidharS99","dKvepAPYBmcJ")).
pos(eqo("journals/tods/Ng01","npCKXD_vLM8J")).
pos(eqo("journals/tods/RaschidL96","rUpu2pcFa8cJ")).
pos(eqo("journals/tods/Ross96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D232628%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/ScioreSR94","RJt8UiSzDTkJ")).
pos(eqo("journals/tods/ScioreSR94","fB2xVdlMTtwJ")).
pos(eqo("journals/tods/ScioreSR94","fW9j2V5gnUMJ")).
pos(eqo("journals/tods/SrivastavaSRN95","zm3D83ZiU4UJ")).
pos(eqo("journals/tods/Suciu02","Y7kHpHu3nP0J")).
pos(eqo("journals/tods/TariSS97","iMM-Ho95algJ")).
pos(eqo("journals/tods/WinslettSQ94","lvZTVlP7s7oJ")).
pos(eqo("journals/tods/WinslettSQ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D195675%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/ZaharioudakisCF97","EN1nFWJxnoIJ")).
pos(eqo("journals/tods/ZobelMR98","nX85t01_KugJ")).
pos(eqo("journals/vldb/AgrawalHK03","NDKJPUgy_K4J")).
pos(eqo("journals/vldb/AlbanoGO95","vrD2aAK6G-wJ")).
pos(eqo("journals/vldb/Antoshenkov97","gleX-n_dgkcJ")).
pos(eqo("journals/vldb/AtkinsonM95","MRgoVIYcARoJ")).
pos(eqo("journals/vldb/AtkinsonM95","dahaBAYvs5AJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","IvPHHa01uUkJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","mFHdV09MfG8J")).
pos(eqo("journals/vldb/Barbara-MillaG94","md3DWyujCrQJ")).
pos(eqo("journals/vldb/ChangG01","hYu2nw263UoJ")).
pos(eqo("journals/vldb/ChenHY97","IWZsSVPC6HMJ")).
pos(eqo("journals/vldb/ChidlovskiiB00","ysC3V2Lu3M8J")).
pos(eqo("journals/vldb/CombiP01","8YoYzQtOgYoJ")).
pos(eqo("journals/vldb/DerrMP94","SZbsK5kMevAJ")).
pos(eqo("journals/vldb/DerrMP94","a-QMCFr5yJYJ")).
pos(eqo("journals/vldb/EvangelidisS97","5dnYlEMQTb0J")).
pos(eqo("journals/vldb/FahlR97","zXSCJ9LzZ8cJ")).
pos(eqo("journals/vldb/FuCCM00","7kC8fo78d6sJ")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/HarrisR96","S8x6zjXc9oAJ")).
pos(eqo("journals/vldb/HjaltasonS02","Z24x2fvsNQgJ")).
pos(eqo("journals/vldb/IoannidisNSS97","if5vzPT-qIAJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","lURUgKLK9kAJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","vQVMrRkJwSIJ")).
pos(eqo("journals/vldb/Li03","nsFFKjYz19cJ")).
pos(eqo("journals/vldb/LometS97","QIv1JU2suAEJ")).
pos(eqo("journals/vldb/LometS97","qjLiaKLJ6eQJ")).
pos(eqo("journals/vldb/MehtaD97","VPX141ia9EcJ")).
pos(eqo("journals/vldb/MehtaGPN98","7Zf8Y2idDb0J")).
pos(eqo("journals/vldb/MehtaGPN98","sS3KWBs3gEcJ")).
pos(eqo("journals/vldb/NybergBCGL95","A1phylxPkl4J")).
pos(eqo("journals/vldb/OzsuPSILM95","epUf9ogilogJ")).
pos(eqo("journals/vldb/PacittiS00","UvvmhI5lqbsJ")).
pos(eqo("journals/vldb/PacittiS00","yXCROrOo320J")).
pos(eqo("journals/vldb/PapadiasS94","_ANyhrnP3CoJ")).
pos(eqo("journals/vldb/PucheralBVB01","ci71yD2UE8oJ")).
pos(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
pos(eqo("journals/vldb/Sciore94","qHn6nrbVow8J")).
pos(eqo("journals/vldb/ShyyASL96","1J2ubL0l2UMJ")).
pos(eqo("journals/vldb/ShyyASL96","n8EWz5rQancJ")).
pos(eqo("journals/vldb/SteinbrunnMK97","nwwVf5FGX4QJ")).
pos(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
pos(eqo("journals/vldb/ZezulaSAR98","DM9hrpKpqmMJ")).
