neg(eqo("conf/sigmod/AbadiC02","9vL7MRA7Up4J")).
neg(eqo("conf/sigmod/AcharyaFZ97","rO4-yA3tlfoJ")).
neg(eqo("conf/sigmod/Agarwal96","HfEQzVOD9tsJ")).
neg(eqo("conf/sigmod/AgrawalCD02","d8gRjk3iEi0J")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","IgRat6Xyu2EJ")).
neg(eqo("conf/sigmod/BarclaySG00","7br3WXwZRQ4J")).
neg(eqo("conf/sigmod/BrinMS97","url:http://doi.wiley.com/10.1002/ace.7509")).
neg(eqo("conf/sigmod/BrinMUT97","cr7xWKidCnYJ")).
neg(eqo("conf/sigmod/BunemanM95","KOH0XCxknEMJ")).
neg(eqo("conf/sigmod/ChoiC02","QIG8th9DHbQJ")).
neg(eqo("conf/sigmod/CranorGJSS02","D8a4umAppIcJ")).
neg(eqo("conf/sigmod/DeligiannakisR03","6rcTxplRGoEJ")).
neg(eqo("conf/sigmod/Faloutsos95","dgSoOglJTw0J")).
neg(eqo("conf/sigmod/Golding95","uJj9OgotYeEJ")).
neg(eqo("conf/sigmod/GraySSU03","eYiIHvpcnFQJ")).
neg(eqo("conf/sigmod/HaasH99","toOI_Kd4dFEJ")).
neg(eqo("conf/sigmod/HellersteinA00","-GYSZmXrx-UJ")).
neg(eqo("conf/sigmod/JonssonFS98","IAgpKYC73pIJ")).
neg(eqo("conf/sigmod/Keim99","icoWjIZ_6IIJ")).
neg(eqo("conf/sigmod/KotidisR98","04utamFvle4J")).
neg(eqo("conf/sigmod/Kramer97","EaLfi8_2ygsJ")).
neg(eqo("conf/sigmod/Larson01","3mnAsl4ebRsJ")).
neg(eqo("conf/sigmod/Larson01","qnbfdzE--oQJ")).
neg(eqo("conf/sigmod/Lassettre98","u6SUM1C_ocwJ")).
neg(eqo("conf/sigmod/LoR94","gAwckIiPpTEJ")).
neg(eqo("conf/sigmod/Mohan99","wNyW9PnlpwMJ")).
neg(eqo("conf/sigmod/NguyenACP01","rPB2NYjIGfQJ")).
neg(eqo("conf/sigmod/Norrie95","Fr8CPbK-IFIJ")).
neg(eqo("conf/sigmod/Olson95","z7RgWI_XqrAJ")).
neg(eqo("conf/sigmod/OlstonWACELSS98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083798%26type%3Dpdf")).
neg(eqo("conf/sigmod/RamaswamyRS00","HxmnEeCigX8J")).
neg(eqo("conf/sigmod/RundensteinerKZWLLN99","uibe8EM86AQJ")).
neg(eqo("conf/sigmod/SchusterW01","oRy7-BbwJdkJ")).
neg(eqo("conf/sigmod/Seshadri03","eFDQJo4KK6QJ")).
neg(eqo("conf/sigmod/SunAA03","qsWDIfzBxiQJ")).
neg(eqo("conf/sigmod/WhiteD95","isueaYy3pm4J")).
neg(eqo("conf/sigmod/WolfsonSXZC99","bEu_llku9NMJ")).
neg(eqo("conf/sigmod/ZaianeHLCC98","0inuMFZSQ50J")).
neg(eqo("conf/vldb/AbiteboulMRVW98","kRHYZELNeoIJ")).
neg(eqo("conf/vldb/AgrawalK02","OYvAGoQatHsJ")).
neg(eqo("conf/vldb/AgrawalK02","m_Nqh_H0dekJ")).
neg(eqo("conf/vldb/AlexandrovABBBCDFHJKKKLLMMMPNPPRRSSW02","hHeeDo6tEX0J")).
neg(eqo("conf/vldb/AltinelF00","dxE8D6KprTYJ")).
neg(eqo("conf/vldb/AtzeniMM97","nzG3d6r0BmcJ")).
neg(eqo("conf/vldb/BelussiF95","C-Hz6btw11gJ")).
neg(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
neg(eqo("conf/vldb/Brodie00","mAQ6BedgjXQJ")).
neg(eqo("conf/vldb/BrownS95","g6RcUSd0XrgJ")).
neg(eqo("conf/vldb/CherniackFZ01","F42wOOy-KR0J")).
neg(eqo("conf/vldb/CherniackZ98","So_H9Oer6lsJ")).
neg(eqo("conf/vldb/ChoenniV00","8CKDKUPVOnwJ")).
neg(eqo("conf/vldb/ChoenniV00","Pa_ObVyi9TcJ")).
neg(eqo("conf/vldb/CiacciaPZ97","urL_oXzvBBUJ")).
neg(eqo("conf/vldb/DuttaDMRT00","hMsWZU5TJWYJ")).
neg(eqo("conf/vldb/FaloutsosG96","R0xUZUxSGmwJ")).
neg(eqo("conf/vldb/GardarinGT95","DAUHADa6RjQJ")).
neg(eqo("conf/vldb/GoldmanSVG98","_UFNFNjKRd0J")).
neg(eqo("conf/vldb/ImielinskiB02","-Pmsximl_moJ")).
neg(eqo("conf/vldb/IpeirotisG02","87OlEJpxkCoJ")).
neg(eqo("conf/vldb/JaedickeM99","XR50nxmrvFcJ")).
neg(eqo("conf/vldb/JohnsonA00","vxM5JgZVoZIJ")).
neg(eqo("conf/vldb/KerstenWFKBC03","gIMus2K4DkEJ")).
neg(eqo("conf/vldb/KietzRS97","ALUZrQuCABQJ")).
neg(eqo("conf/vldb/KietzRS97","HpeeMa5TJeQJ")).
neg(eqo("conf/vldb/KietzRS97","L4k3lAWc-JgJ")).
neg(eqo("conf/vldb/Klots96","Saya98XX7_MJ")).
neg(eqo("conf/vldb/LeslieJBY95","8-eaDTdtfY4J")).
neg(eqo("conf/vldb/LiHKSPAC02","K1o894GE6S0J")).
neg(eqo("conf/vldb/LiRS99","h4AUUfPAGz8J")).
neg(eqo("conf/vldb/LinR98","WnXP0p_egbwJ")).
neg(eqo("conf/vldb/LitwinNS94","LcX8Pm2ABJsJ")).
neg(eqo("conf/vldb/LudasaherGM00","yzk4AvDKlhgJ")).
neg(eqo("conf/vldb/MaedaT01","dipeGpTdsoQJ")).
neg(eqo("conf/vldb/Mattos03","P7GUGC5bz7wJ")).
neg(eqo("conf/vldb/May01","Fb4oYRM9N4EJ")).
neg(eqo("conf/vldb/Meier95","eH0glugbivcJ")).
neg(eqo("conf/vldb/NgH94","N3Bry6sSMw8J")).
neg(eqo("conf/vldb/NieKH03","gPvyDDUyrg4J")).
neg(eqo("conf/vldb/NiermanJ02","Y799jSppkKEJ")).
neg(eqo("conf/vldb/Ogawa96","YK-UoQVALEwJ")).
neg(eqo("conf/vldb/RantzauCHM02","iYUUcNXDZXgJ")).
neg(eqo("conf/vldb/RisheYACLMVSV00","E3wq5NhPhKoJ")).
neg(eqo("conf/vldb/Schnase00","MC7KlhmEQt8J")).
neg(eqo("conf/vldb/SellisRF97","VOh3TEnjkjIJ")).
neg(eqo("conf/vldb/SeshadriLR96","url:http://portal.acm.org/citation.cfm%3Fid%3D837848%26dl%3DACM%26coll%3Dportal%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/ShahDR03","r-BkIPtpff4J")).
neg(eqo("conf/vldb/Sheth96","0CD9uUPdnbUJ")).
neg(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
neg(eqo("conf/vldb/SrinivasaK03","gUJrOpj89tQJ")).
neg(eqo("conf/vldb/SteenhagenABB94","zcEfhybN-hYJ")).
neg(eqo("conf/vldb/ZhouR03","MvbChqWgFawJ")).
neg(eqo("journals/sigmod/Aberer03c","YG9Js5mJbV0J")).
neg(eqo("journals/sigmod/BoulosO99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945739%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
neg(eqo("journals/sigmod/CaleroPR03","BtX5mdMhVUkJ")).
neg(eqo("journals/sigmod/Colliat96","rNu93TfKkd4J")).
neg(eqo("journals/sigmod/DogacAOD95","Ecbt7UAThe8J")).
neg(eqo("journals/sigmod/FlorescuLM98","url:http://portal.acm.org/citation.cfm%3Fid%3D163090.163102%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin00a","url:http://doi.wiley.com/10.1002/he.21")).
neg(eqo("journals/sigmod/Franklin99a","url:http://portal.acm.org/citation.cfm%3Fid%3D197445")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","AFDI-XMdl5YJ")).
neg(eqo("journals/sigmod/GunopulosK01","52CzovbNEuEJ")).
neg(eqo("journals/sigmod/GunopulosK01","oYtmj53qV0UJ")).
neg(eqo("journals/sigmod/JacobS99","PejT0m0yUR0J")).
neg(eqo("journals/sigmod/Keim96","vkUvhZOw-1YJ")).
neg(eqo("journals/sigmod/LeeCL95","xmE1380_4E4J")).
neg(eqo("journals/sigmod/Liu02b","n9WCwauSTTsJ")).
neg(eqo("journals/sigmod/LometBCLN98","ycyOGNNmFUkJ")).
neg(eqo("journals/sigmod/PourabbasR02","V9XUvirmVEEJ")).
neg(eqo("journals/sigmod/Qian95b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian97","4J5CvdomBmsJ")).
neg(eqo("journals/sigmod/RosenthalSMBTL95","kNT7yt823K8J")).
neg(eqo("journals/sigmod/ShethMKA01","cKxVxbODsw0J")).
neg(eqo("journals/sigmod/Snodgrass94","4J5CvdomBmsJ")).
neg(eqo("journals/sigmod/Snodgrass94","KVRdG1SybT0J")).
neg(eqo("journals/sigmod/SofferMC02","url:http://portal.acm.org/citation.cfm%3Fcoll%3DGUIDE%26dl%3DGUIDE%26id%3D543638")).
neg(eqo("journals/sigmod/Stonebraker94","url:http://portal.acm.org/citation.cfm%3Fid%3D181551")).
neg(eqo("journals/sigmod/ZobelMR96","PRL0iaGOqUQJ")).
neg(eqo("journals/tods/DeyS96","JZT0efWSjp8J")).
neg(eqo("journals/tods/EiterGM97","QRAB3ST1q90J")).
neg(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
neg(eqo("journals/tods/HsuSY01","dkdzE1VG71sJ")).
neg(eqo("journals/tods/Lerner00","WIg9kgdVp9IJ")).
neg(eqo("journals/tods/MamoulisP01","xdAsc3yVWvYJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/J805K662617N0160.pdf")).
neg(eqo("journals/tods/TaoSP03","YXZ8kOo0wpEJ")).
neg(eqo("journals/tods/WinslettSQ94","n-oY_4nnoQcJ")).
neg(eqo("journals/tods/ZobelMR98","Zc2GVC89wbgJ")).
neg(eqo("journals/vldb/AbbadiSW01","3rwpLn-qoCoJ")).
neg(eqo("journals/vldb/AntoshenkovZ96","N8syKKPN6IoJ")).
neg(eqo("journals/vldb/BernsteinIR03","3rwpLn-qoCoJ")).
neg(eqo("journals/vldb/ChienTZ02","Ls7vkMLcYmkJ")).
neg(eqo("journals/vldb/FerrariAABC02","IFN4xGRCE_0J")).
neg(eqo("journals/vldb/FiebigHKMNSW02","AFmuM3PcFD8J")).
neg(eqo("journals/vldb/FiebigHKMNSW02","w_FOwUavk0kJ")).
neg(eqo("journals/vldb/NgS98","_ANyhrnP3CoJ")).
pos(eqo("conf/sigmod/AbadiC02","f2Lea-RN8dsJ")).
pos(eqo("conf/sigmod/AcharyaPR99","KrVgTXcNPPUJ")).
pos(eqo("conf/sigmod/AdaliBSS98","YQ90BYSVqbsJ")).
pos(eqo("conf/sigmod/AggarwalPWYP99","G3dX_RTA26MJ")).
pos(eqo("conf/sigmod/AgichteinG03","url:http://portal.acm.org/citation.cfm%3Fid%3D872851")).
pos(eqo("conf/sigmod/BerchtoldK98","VuMPPr6k95AJ")).
pos(eqo("conf/sigmod/BouguettayaBH99","U-Kd4GQ_vCMJ")).
pos(eqo("conf/sigmod/BrodskySCE99","34a4H8ATLxcJ")).
pos(eqo("conf/sigmod/BrodskySCE99","jnBo-gBTmAcJ")).
pos(eqo("conf/sigmod/BuchmannDZH95","MoNBLfTlYg0J")).
pos(eqo("conf/sigmod/ChangG99","BYkCvtDCxzcJ")).
pos(eqo("conf/sigmod/ChaudhuriN98","qGTxTpQXTDsJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","g6fFCiX6GtMJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","hEOX0Vu4-JcJ")).
pos(eqo("conf/sigmod/ChungMS02","2y_G8dmz1QkJ")).
pos(eqo("conf/sigmod/ChungMS02","mEfTTKdu6soJ")).
pos(eqo("conf/sigmod/ChungMS02","n8tscFMeBtwJ")).
pos(eqo("conf/sigmod/CorralMTV00","TsShfxPwF6YJ")).
pos(eqo("conf/sigmod/CranorJSS03","gya0M9b1KrgJ")).
pos(eqo("conf/sigmod/Galindo-Legaria94","iEs59H5EFHwJ")).
pos(eqo("conf/sigmod/GibbonsM98","4EgMtIywBRUJ")).
pos(eqo("conf/sigmod/GibbonsM98","7jANIPngJrIJ")).
pos(eqo("conf/sigmod/GoyalHKMSZ97","OcGPxRYxbsUJ")).
pos(eqo("conf/sigmod/GravanoCGP97","1xxRTUP64bwJ")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/GrayHOS96","_pjwP11t_y8J")).
pos(eqo("conf/sigmod/HanPDW01","CnAw9v-vEjwJ")).
pos(eqo("conf/sigmod/HinneburgKW02","7v3f7Thmyw0J")).
pos(eqo("conf/sigmod/JagadishJOT01","OM7n6h8R8CoJ")).
pos(eqo("conf/sigmod/JagadishLMSV99","946iAs3adDcJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","4_fm8LWVWHMJ")).
pos(eqo("conf/sigmod/KanthAS98","eTqBO4EcCNIJ")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/KornackerSH98","bV8_CDuW2gMJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","YWzkq7-TA5MJ")).
pos(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
pos(eqo("conf/sigmod/LometT99","JvZ9JWtn72QJ")).
pos(eqo("conf/sigmod/MamoulisP99","fXHqHRgpG8sJ")).
pos(eqo("conf/sigmod/MamoulisP99","z9MQwq7G3GYJ")).
pos(eqo("conf/sigmod/PapadopoulosM98","dLzAJ-I1nCcJ")).
pos(eqo("conf/sigmod/QuassW97","9nkD3JyhE1kJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","imAsAkfukSYJ")).
pos(eqo("conf/sigmod/SagonasSW94a","nF5iGEtihWYJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","3OxZS395vDcJ")).
pos(eqo("conf/sigmod/Smith01","WfKk1v3VamgJ")).
pos(eqo("conf/sigmod/StonebrakerH01","opMsehfY-XoJ")).
pos(eqo("conf/sigmod/SzalayGKT00","2ikeMlH1BGsJ")).
pos(eqo("conf/sigmod/SzalayGKT00","T4os1oo8vT4J")).
pos(eqo("conf/sigmod/SzalayGKT00","ZXB1xI2h-HkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","oPgy1SYoptgJ")).
pos(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
pos(eqo("conf/vldb/AbrolLMMMRTWZ01","w9Ma-YjZHYkJ")).
pos(eqo("conf/vldb/AshwinGG02","mObyCD3Jw0EJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WcxbHqh4FfkJ")).
pos(eqo("conf/vldb/BerchtoldKK96","pMqgAz_KzPgJ")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BliujuteJSS98","wbGdc_RsI14J")).
pos(eqo("conf/vldb/Brin95","srjTPThCwrwJ")).
pos(eqo("conf/vldb/CareyD96","5HV8kccLoZ4J")).
pos(eqo("conf/vldb/CareyD96","5xe-dQqXfI8J")).
pos(eqo("conf/vldb/CareyD96","ulDUAu6vLr4J")).
pos(eqo("conf/vldb/ChakrabartiDAR97","2LdUbNy0hWwJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/DarEGP98","D6gxih90YU4J")).
pos(eqo("conf/vldb/DaynesC02","Ug0Yk0QhILMJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","9rofzgQ6HtcJ")).
pos(eqo("conf/vldb/GehaniJR94","ndpqwnLwAWUJ")).
pos(eqo("conf/vldb/HelmerNM03","8-HpAN0xpjcJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","zbaMbE17LyQJ")).
pos(eqo("conf/vldb/Ioannidis03","jELnwotIy9kJ")).
pos(eqo("conf/vldb/JagadishLS99","5d1R2mD-7MkJ")).
pos(eqo("conf/vldb/JagadishNSSK97","FzUYum7hqhQJ")).
pos(eqo("conf/vldb/JohnsonM98","V4PVzPaBOBUJ")).
pos(eqo("conf/vldb/JohnsonM98","eFynrwKK_T0J")).
pos(eqo("conf/vldb/KemperK94","jQYEiVS0CIgJ")).
pos(eqo("conf/vldb/KoschBBHHLRT01","xvNBOkc3UkcJ")).
pos(eqo("conf/vldb/KumarKA97","EhTWppk6No8J")).
pos(eqo("conf/vldb/LabrinidisR03","0GMNedjfVV0J")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/Madnick95","CVQyvLe8w38J")).
pos(eqo("conf/vldb/MaratheS97","HcgXkUDB-wYJ")).
pos(eqo("conf/vldb/MillinerBP95","kYl-9cV8gloJ")).
pos(eqo("conf/vldb/OlstonW00","rrOV-TanTuYJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","BIF2jRwmL0EJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","gkbvvgj8kdUJ")).
pos(eqo("conf/vldb/PereiraFJLS01","Cd6A4nsDnkQJ")).
pos(eqo("conf/vldb/PereiraFLS00","GzZSEeVoAiUJ")).
pos(eqo("conf/vldb/Pound99","zWp_JdEQ8MgJ")).
pos(eqo("conf/vldb/RamamurthyDS02","DAlyofX710AJ")).
pos(eqo("conf/vldb/SahuguetA99","NrXmzugArgoJ")).
pos(eqo("conf/vldb/SahuguetA99","VT_vPPmEIEIJ")).
pos(eqo("conf/vldb/SahuguetA99","pK5bydjeZFIJ")).
pos(eqo("conf/vldb/Sarawagi95","w9je55hjOlwJ")).
pos(eqo("conf/vldb/SistlaYH94","_jl3bN2QlE4J")).
pos(eqo("conf/vldb/WangC03","nXj_8Y7lmHsJ")).
pos(eqo("conf/vldb/WangYM97","bnkP_MXjTPcJ")).
pos(eqo("conf/vldb/WangYM97","hVRj_WzRqI4J")).
pos(eqo("journals/sigmod/AilamakiH03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945725%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AndlerHEMBE96","xpaAdEJShEoJ")).
pos(eqo("journals/sigmod/BarclayBGS94","v1aol6mmLdMJ")).
pos(eqo("journals/sigmod/BarclayBGS94","wPhDoeiINQsJ")).
pos(eqo("journals/sigmod/BernsteinHP00","FFzJxlpy6TsJ")).
pos(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373708%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959085%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BuchnerM98","4J5CvdomBmsJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","GruVHotOoPQJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","eKF1zVNKP0gJ")).
pos(eqo("journals/sigmod/CatarciC96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245888%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Gal99","mOsVdVKwhjwJ")).
pos(eqo("journals/sigmod/Gardels97","PlitMluIJyYJ")).
pos(eqo("journals/sigmod/HanBP01","FT5pSUb-uTYJ")).
pos(eqo("journals/sigmod/JenningsNF98","YiZVv5kVDb4J")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/LaenderRST02","34QnrkmS0Y8J")).
pos(eqo("journals/sigmod/MaelbranckeO95","_FKSZiytB2AJ")).
pos(eqo("journals/sigmod/MotroA03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959085%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NorrieBSW94","ctEdyJRdTbkJ")).
pos(eqo("journals/sigmod/PapianiWDN99","EHBFbc1r9oIJ")).
pos(eqo("journals/sigmod/Richey95","2p2A5_qGf5cJ")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/TsotrasJS98","f3-E7x12K4gJ")).
pos(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
pos(eqo("journals/tods/ChomickiTB01","MqgSlx1jbPsJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
pos(eqo("journals/tods/OliverS94","zAczQV37xxsJ")).
pos(eqo("journals/tods/RosenthalR94","zM422IjZcPgJ")).
pos(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
pos(eqo("journals/vldb/Barbara-MillaG94","Cmq7lkkXNt4J")).
pos(eqo("journals/vldb/C95b","url:http://www.springerlink.com/index/J267M1G774146066.pdf")).
pos(eqo("journals/vldb/HalkidiNVV03","J0hrpRuvSgMJ")).
pos(eqo("journals/vldb/Li03","nsFFKjYz19cJ")).
pos(eqo("journals/vldb/MedjahedBE03","M0FH31YCEU0J")).
pos(eqo("journals/vldb/NgC98","J7mY8RlpTKMJ")).
pos(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
pos(eqo("journals/vldb/PanagosB97","Ht4Yl1kJuxIJ")).
pos(eqo("journals/vldb/PapazogluK97","3k9vWWMJiWYJ")).
pos(eqo("journals/vldb/PapazogluK97","kFQl7LX8OQkJ")).
pos(eqo("journals/vldb/RamamurthyDS03","DAlyofX710AJ")).
