neg(eqo("conf/sigmod/AbiteboulCM95","3k9vWWMJiWYJ")).
neg(eqo("conf/sigmod/AbiteboulCM95","WzT3S2G1FjcJ")).
neg(eqo("conf/sigmod/AcharyaAFZ95","ZdWKBKSoMUQJ")).
neg(eqo("conf/sigmod/AcharyaFZ97","qTCsXcCsI7UJ")).
neg(eqo("conf/sigmod/AdelbergD99","5I0ArBmDRcEJ")).
neg(eqo("conf/sigmod/AdiBEY01","zWuNqBAhc80J")).
neg(eqo("conf/sigmod/AdyaGLM95","FlE1JdgElGQJ")).
neg(eqo("conf/sigmod/AgichteinG03","1HwyWUB6M50J")).
neg(eqo("conf/sigmod/AgrawalCD02","TUzhq1PjPsgJ")).
neg(eqo("conf/sigmod/AgrawalES03","e4NIjDTn_fsJ")).
neg(eqo("conf/sigmod/AgrawalK03","HfEQzVOD9tsJ")).
neg(eqo("conf/sigmod/AgrawalS00","cUVJ8Svrad0J")).
neg(eqo("conf/sigmod/Ahn94","sus2UQS_MSkJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","DFubU20j1OIJ")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","8M_z-OUkoxYJ")).
neg(eqo("conf/sigmod/Aulakh98","mt8Q1YmVRkMJ")).
neg(eqo("conf/sigmod/BabcockCD03","shHIGwa3MoUJ")).
neg(eqo("conf/sigmod/Ballinger94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("conf/sigmod/BarbaraI94","7OQlv9Ry1SkJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","8_ZvLWzd8cEJ")).
neg(eqo("conf/sigmod/BerchtoldBK98","VHo2go6vjYsJ")).
neg(eqo("conf/sigmod/BerchtoldK98","j46yGNUAS-IJ")).
neg(eqo("conf/sigmod/BerensonBGMOO95","-lYgZoLNtioJ")).
neg(eqo("conf/sigmod/BergstraesserBPS99","3SHIgRrrL5QJ")).
neg(eqo("conf/sigmod/BergstraesserBPS99","WrWKsjAj_58J")).
neg(eqo("conf/sigmod/BettiniWBJ95","YkIvdNOC64cJ")).
neg(eqo("conf/sigmod/BuchmannDZH95","c-7qcQYgR_4J")).
neg(eqo("conf/sigmod/BunemanM95","lgCzXE4LjkIJ")).
neg(eqo("conf/sigmod/CallanCD99","_UYteGcmBKIJ")).
neg(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","jMc3U-zRTPEJ")).
neg(eqo("conf/sigmod/CareyMN97","zdKktGvX4BwJ")).
neg(eqo("conf/sigmod/CatarciS01","Fu9Ra1Az2JoJ")).
neg(eqo("conf/sigmod/Chamberlin03","0ZXZVWpZNmkJ")).
neg(eqo("conf/sigmod/Chamberlin03","Jjob6_YGJSQJ")).
neg(eqo("conf/sigmod/ChangH02","4eHVZHcQvdMJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","lCQ0HZYyYNcJ")).
neg(eqo("conf/sigmod/ChaudhuriG96","OFGtGwUHhUQJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","hk2lzbke6hQJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","jsapF3OoWXcJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","QkyXMep2bWsJ")).
neg(eqo("conf/sigmod/ChenCPPSTM00","O6fER2UwriIJ")).
neg(eqo("conf/sigmod/ChenCPPSTM00","url:http://www.springerlink.com/index/P074T33638T88V55.pdf")).
neg(eqo("conf/sigmod/ChenGK01","mzqmEYGGT_IJ")).
neg(eqo("conf/sigmod/ChenR94","hlQJGQCSurIJ")).
neg(eqo("conf/sigmod/ChenRW02","U5qUqJePkTYJ")).
neg(eqo("conf/sigmod/ChengKP03","N9NdxNRvMMkJ")).
neg(eqo("conf/sigmod/Chong98","TtV6gGLQ9NMJ")).
neg(eqo("conf/sigmod/Chong98","gRzWUg_txCEJ")).
neg(eqo("conf/sigmod/CruzALRZ97","Pbjz4-UPrZ8J")).
neg(eqo("conf/sigmod/DavisonG95","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0177775CI")).
neg(eqo("conf/sigmod/DavulcuFKR99","_EqIkhlGUaEJ")).
neg(eqo("conf/sigmod/DeligiannakisR03","zMgbS5u_GwYJ")).
neg(eqo("conf/sigmod/DogacHKOONDMAKE96","UAO4T_2ylPkJ")).
neg(eqo("conf/sigmod/DohertyHR96","aAquT4Ws6fcJ")).
neg(eqo("conf/sigmod/Edelstein95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Ellison95","Q7s0qKBrWL8J")).
neg(eqo("conf/sigmod/FaginKS03","xqY29rV7EWMJ")).
neg(eqo("conf/sigmod/FernandezMS01","iXkSngvyu08J")).
neg(eqo("conf/sigmod/FlokstraKS94","KfZ6OR_Rvc8J")).
neg(eqo("conf/sigmod/FranklinJK96","iDBvvrHwj7YJ")).
neg(eqo("conf/sigmod/Freeston95","fgWP0K0eYGQJ")).
neg(eqo("conf/sigmod/French95","url:http://portal.acm.org/citation.cfm%3Fid%3D217279.215319%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3DSERIES316%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Multimedia%2520Conference%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/FukudaMMT96","QdPN-QtgceAJ")).
neg(eqo("conf/sigmod/GangulyGR03","GBZiTCbChZQJ")).
neg(eqo("conf/sigmod/GarofalakisI96","6lvBOS-XO3EJ")).
neg(eqo("conf/sigmod/GarofalakisI96","ReOfuE1ytx4J")).
neg(eqo("conf/sigmod/GarofalakisI96","url:http://portal.acm.org/citation.cfm%3Fid%3D882082.882084%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GatziuGD95","ewnL82c8kiMJ")).
neg(eqo("conf/sigmod/GehrkeKS01","fUcObvsH1G8J")).
neg(eqo("conf/sigmod/GoldmanW00","Ol886Ck3jz4J")).
neg(eqo("conf/sigmod/GotoK03","bF9t6EpjL14J")).
neg(eqo("conf/sigmod/GraySEBW94","SG9kpHg_arUJ")).
neg(eqo("conf/sigmod/GriffinH97","1hiebPD7DhoJ")).
neg(eqo("conf/sigmod/GunopulosKTD00","VIjfH9f94xkJ")).
neg(eqo("conf/sigmod/GunopulosKTD00","nLbW09uNfmsJ")).
neg(eqo("conf/sigmod/HaasH99","nvU7kbiEb24J")).
neg(eqo("conf/sigmod/Han96","bCp4rxObjCsJ")).
neg(eqo("conf/sigmod/HanPDW01","qyXhN3CrVQ8J")).
neg(eqo("conf/sigmod/HanWDPW02","nwWpGh3Mx7MJ")).
neg(eqo("conf/sigmod/HanWDPW02","v9BdA55u_XMJ")).
neg(eqo("conf/sigmod/HeC03","jVjUfPerJHMJ")).
neg(eqo("conf/sigmod/HernandezMHYHT01","3ET_IEkoGjYJ")).
neg(eqo("conf/sigmod/HernandezMHYHT01","GUdXGx4blW8J")).
neg(eqo("conf/sigmod/Hope95","qaSgL5tVq1AJ")).
neg(eqo("conf/sigmod/HullZ96","6mnNnra-BPoJ")).
neg(eqo("conf/sigmod/HullZ96","H1E3GuQcoUAJ")).
neg(eqo("conf/sigmod/HullZ96","vM8TnB6ToEcJ")).
neg(eqo("conf/sigmod/IoannidisLANT97","zNuhEWxo2iUJ")).
neg(eqo("conf/sigmod/IvesLPST00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974142%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/JajodiaSSB97","61cw9DcC6qsJ")).
neg(eqo("conf/sigmod/JoshiA01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637417%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KalnisNOPT02","nlna-xElM08J")).
neg(eqo("conf/sigmod/KanthRSB99","url:http://doi.wiley.com/10.1002/tl.7904")).
neg(eqo("conf/sigmod/KeimK95","E0_INl_086kJ")).
neg(eqo("conf/sigmod/KeoghCMP01","QTzuiNlMnR4J")).
neg(eqo("conf/sigmod/Kim94","PX_FW-eZoUYJ")).
neg(eqo("conf/sigmod/KimCK01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1086271%26type%3Dpdf")).
neg(eqo("conf/sigmod/KotidisR98","ZknlFLRnqLYJ")).
neg(eqo("conf/sigmod/KotidisR99","EWDPecQbT1AJ")).
neg(eqo("conf/sigmod/KriegelMPS01","oi0hNIHYZdcJ")).
neg(eqo("conf/sigmod/KrishnamurthyBN99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D200111010674MT%26recid%3DA0032577AH")).
neg(eqo("conf/sigmod/Kulkarni94","Aa9t5-2FNM4J")).
neg(eqo("conf/sigmod/LabioWGG00","JYYcPQLrBw8J")).
neg(eqo("conf/sigmod/LabioWGG00","QsmO94ilmrEJ")).
neg(eqo("conf/sigmod/LabioYG99","Z5kfiPj7fGMJ")).
neg(eqo("conf/sigmod/LabioZWGGW97","TVx7zsQQGYUJ")).
neg(eqo("conf/sigmod/LabrinidisR00","DKUouEkK_b4J")).
neg(eqo("conf/sigmod/LakshmananPZ03","ZUMidTbSKiEJ")).
neg(eqo("conf/sigmod/Larson01","hgjhR8PwNVwJ")).
neg(eqo("conf/sigmod/LeeKC99","SGxbkJFLa3oJ")).
neg(eqo("conf/sigmod/LeeWMS01","OFXL5KsJiWcJ")).
neg(eqo("conf/sigmod/LometT03","s54pMOqTUR8J")).
neg(eqo("conf/sigmod/MaddenFHH03","3coQH5OOvxkJ")).
neg(eqo("conf/sigmod/MaddenH02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/MankuRL99","wO6VeeLIXAsJ")).
neg(eqo("conf/sigmod/MerialdoAMMP00","pRVaNHzGELQJ")).
neg(eqo("conf/sigmod/Miller98","8SN4aiuMLU4J")).
neg(eqo("conf/sigmod/Mohan01","x5Po0pdoKcQJ")).
neg(eqo("conf/sigmod/Mohan94","IGS3TtqfKUgJ")).
neg(eqo("conf/sigmod/Mohan99","OR63ctWfuTgJ")).
neg(eqo("conf/sigmod/Mohan99","eE98qv4oVnQJ")).
neg(eqo("conf/sigmod/Moore95","Z7_b_rGINPsJ")).
neg(eqo("conf/sigmod/NazeriBO01","2E9I_lugGC4J")).
neg(eqo("conf/sigmod/NazeriBO01","K8zARc0Bno0J")).
neg(eqo("conf/sigmod/NestorovAM98","Ah9B3bWU0jEJ")).
neg(eqo("conf/sigmod/OrdonezC00","OHPcamwtQe4J")).
neg(eqo("conf/sigmod/Ozsu99","09nCxGk1-_cJ")).
neg(eqo("conf/sigmod/Ozsu99","9PhYz-N58A8J")).
neg(eqo("conf/sigmod/PalmerF00","eiA9HVOF2IsJ")).
neg(eqo("conf/sigmod/PalmerF00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/PoosalaIHS96","4q4PDOS45uIJ")).
neg(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
neg(eqo("conf/sigmod/Pruscino03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187460%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/QunLO03","AatoNnELw78J")).
neg(eqo("conf/sigmod/RadekeBBEKKN95","IN_sibgHb9MJ")).
neg(eqo("conf/sigmod/Raghavan03","CMNhuOzf5jAJ")).
neg(eqo("conf/sigmod/RamaswamyK95","L0RF8_kTmVAJ")).
neg(eqo("conf/sigmod/RamaswamyK95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375792%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RaoR00","WPHbE_W7e9oJ")).
neg(eqo("conf/sigmod/RiedewaldAA02","g-iBIIhuRnYJ")).
neg(eqo("conf/sigmod/RodriguezR00","bfCz9XEzfy0J")).
neg(eqo("conf/sigmod/RodriguezR00","fL_WoorIDAoJ")).
neg(eqo("conf/sigmod/Rosenthal01","oD81g1krEKEJ")).
neg(eqo("conf/sigmod/Rosenthal01","uybXau8dCnkJ")).
neg(eqo("conf/sigmod/RoySSB00","okgKDPbDOmAJ")).
neg(eqo("conf/sigmod/RundensteinerCCSO00","YwLoGdTgG-sJ")).
neg(eqo("conf/sigmod/RundensteinerCCSO00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335496%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/SaltenisJLL00","GpyFkjtQggIJ")).
neg(eqo("conf/sigmod/Sarawagi00","7GpYSr7yaWAJ")).
neg(eqo("conf/sigmod/SeidlK98","TodiMgxv4vMJ")).
neg(eqo("conf/sigmod/SeidlK98","_1b7BDzq5DgJ")).
neg(eqo("conf/sigmod/ShenNSHS03","LjrsWIr3rhAJ")).
neg(eqo("conf/sigmod/SismanisDRK02","hzlid7szSu4J")).
neg(eqo("conf/sigmod/SlivinskasJS01","7H9j9z0x_3UJ")).
neg(eqo("conf/sigmod/Smith01","5wh3Y-mBqJQJ")).
neg(eqo("conf/sigmod/Stonebraker98","0s68uZWLQogJ")).
neg(eqo("conf/sigmod/Stonebraker98","dC-3OuqOpuYJ")).
neg(eqo("conf/sigmod/StonebrakerH01","DLlqNIxFXQkJ")).
neg(eqo("conf/sigmod/StonebrakerH01","url:http://portal.acm.org/citation.cfm%3Fid%3D582192")).
neg(eqo("conf/sigmod/SunAA03","wR6CGftUyH0J")).
neg(eqo("conf/sigmod/SzalayGKT00","Gx-502x6n0sJ")).
neg(eqo("conf/sigmod/Team95b","v80FFBUTW_0J")).
neg(eqo("conf/sigmod/TheodoulidisAACKS94","JceK-ywXk8UJ")).
neg(eqo("conf/sigmod/VanceM96","q8IL-AZTmcgJ")).
neg(eqo("conf/sigmod/Vaskevitch94","3eSwRxf3-3sJ")).
neg(eqo("conf/sigmod/VingralekBW94","d8poO41sobYJ")).
neg(eqo("conf/sigmod/WangPFY03","5JXKbI5l1FYJ")).
neg(eqo("conf/sigmod/WattezCBFF00","bhPPRnnbrAwJ")).
neg(eqo("conf/sigmod/WolfsonSXZC99","hxmINi8RFQgJ")).
neg(eqo("conf/sigmod/Wu99","a-C2JKH4Ck4J")).
neg(eqo("conf/sigmod/WuAA01","Zya3QdSVGygJ")).
neg(eqo("conf/sigmod/YanMHF01","sz9ESx0D0IcJ")).
neg(eqo("conf/sigmod/YuMWL01","h95306-8rjEJ")).
neg(eqo("conf/sigmod/ZaianeHLCC98","tFB9gJLG4_UJ")).
neg(eqo("conf/sigmod/ZhaoDN97","dWdpjQfW7HsJ")).
neg(eqo("conf/sigmod/ZhuS03","HOKwwvgAvDMJ")).
neg(eqo("conf/vldb/Adler01","jJym5UnL5poJ")).
neg(eqo("conf/vldb/AgrawalLSS95","JnCZDIqNNTUJ")).
neg(eqo("conf/vldb/AksoyZF01","rCxAgmY4ptEJ")).
neg(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
neg(eqo("conf/vldb/AshwinGG02","2aeb_pBP7lcJ")).
neg(eqo("conf/vldb/AshwinRSSS97","AC19Z_yOCTUJ")).
neg(eqo("conf/vldb/BalminHKPSW03","NB-nK8bAKqYJ")).
neg(eqo("conf/vldb/BaralisW94","url:http://portal.acm.org/citation.cfm%3Fid%3D192593.197423")).
neg(eqo("conf/vldb/BaralisW94","wP_GYyvWXaQJ")).
neg(eqo("conf/vldb/BargaP95","h_EKR1nrXV0J")).
neg(eqo("conf/vldb/Baru96","6nW9chDK2YsJ")).
neg(eqo("conf/vldb/Baru96","P7GUGC5bz7wJ")).
neg(eqo("conf/vldb/BaulierBKS98","dNK16sHm9eUJ")).
neg(eqo("conf/vldb/BaumgartnerFG01a","OuM0E0BhEXIJ")).
neg(eqo("conf/vldb/BawaBA03","531XkRrvqi8J")).
neg(eqo("conf/vldb/BerchtoldKK96","RO5oBaYCifMJ")).
neg(eqo("conf/vldb/BerckenS96","MOvQoZozEmcJ")).
neg(eqo("conf/vldb/BernsteinD94","rNNtyNCgHLoJ")).
neg(eqo("conf/vldb/BernsteinPS99","l3dkEoj-xNcJ")).
neg(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
neg(eqo("conf/vldb/BonczRK98","sRcMuuo3-BEJ")).
neg(eqo("conf/vldb/Brin95","ficuvb1Q0aUJ")).
neg(eqo("conf/vldb/Brodie00","PWWjg7p6pjQJ")).
neg(eqo("conf/vldb/Brodie03","deEJ1JsF8RwJ")).
neg(eqo("conf/vldb/BrownCC94","7P8_zVPEW64J")).
neg(eqo("conf/vldb/BrownG01","E7H04svX7v8J")).
neg(eqo("conf/vldb/BunemanDHOW95","llVBkO6kYZoJ")).
neg(eqo("conf/vldb/Carey00","Y8OcI0fNMYEJ")).
neg(eqo("conf/vldb/Carey00","rfuptELfgLkJ")).
neg(eqo("conf/vldb/CarinoJ98","P7GUGC5bz7wJ")).
neg(eqo("conf/vldb/CarneyCCCLSSTZ02","OZFZwSFb0TkJ")).
neg(eqo("conf/vldb/CarneyCZRCS03","JubkWSUFbbcJ")).
neg(eqo("conf/vldb/CarneyCZRCS03","y5h2qhOGUSgJ")).
neg(eqo("conf/vldb/CatozziR01","hUMTG7HNlyAJ")).
neg(eqo("conf/vldb/CatozziR01","url:http://portal.acm.org/citation.cfm%3Fid%3D500141.500268%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D500141%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Multimedia%2520Conference%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/CatozziR01","x_mqIy3GCmAJ")).
neg(eqo("conf/vldb/CeriCW00","LlZwS4UrRtkJ")).
neg(eqo("conf/vldb/CeriCW00","Yvpk-M9_u-AJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","2LdUbNy0hWwJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","AyDb4G2EiGwJ")).
neg(eqo("conf/vldb/ChakrabartiSST00","CUJBQO0I2h4J")).
neg(eqo("conf/vldb/ChakrabartiSST00","eMCZN8ZXNJIJ")).
neg(eqo("conf/vldb/ChakravarthyKAK94","8B-KY_3fXlkJ")).
neg(eqo("conf/vldb/ChakravarthyKAK94","LyiusaDRx0MJ")).
neg(eqo("conf/vldb/ChatziantoniouR96","ZTH7OGW9FogJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","LROAexi_0UEJ")).
neg(eqo("conf/vldb/ChaudhuriGN03","Q8UBGvwM2pgJ")).
neg(eqo("conf/vldb/ChaudhuriGS95","eHM4OCdJA9YJ")).
neg(eqo("conf/vldb/ChaudhuriS96","U0w9W7YcsZwJ")).
neg(eqo("conf/vldb/ChavdaW97","JubkWSUFbbcJ")).
neg(eqo("conf/vldb/Chawathe99","R7A24ys_F-wJ")).
neg(eqo("conf/vldb/Chawathe99","uvbrfBGnqbAJ")).
neg(eqo("conf/vldb/ChienVZTZ02","QsPxm6zhtecJ")).
neg(eqo("conf/vldb/Chiueh94","OuM0E0BhEXIJ")).
neg(eqo("conf/vldb/ChoenniV00","Ha8MmWZEkeQJ")).
neg(eqo("conf/vldb/ChristodoulakisTZ97","yNW8MWPkB_gJ")).
neg(eqo("conf/vldb/CochranePM96","ETnV04h-79oJ")).
neg(eqo("conf/vldb/CooperSFHS01","R63Nez_SNlAJ")).
neg(eqo("conf/vldb/CormodeKMS03","0iCKhGXsQTEJ")).
neg(eqo("conf/vldb/Dasgupta96","E078BW9a0EoJ")).
neg(eqo("conf/vldb/DattaDTVRF01","_zPTedzhFhQJ")).
neg(eqo("conf/vldb/DattaDTVRF01","mDzxiQVJQAsJ")).
neg(eqo("conf/vldb/DattaRT99","PejT0m0yUR0J")).
neg(eqo("conf/vldb/DeutschPT99","6D0Qt6Sjp8cJ")).
neg(eqo("conf/vldb/DoDJJR98","69kmXg9nRZkJ")).
neg(eqo("conf/vldb/FerrandinaMZ94","qwjRkZuiMHsJ")).
neg(eqo("conf/vldb/FlescaFM03","cN-uloKeQKkJ")).
neg(eqo("conf/vldb/FlescaFM03","urKua_D0KVoJ")).
neg(eqo("conf/vldb/FukudaMMT96","Bcuo4_yr2p0J")).
neg(eqo("conf/vldb/GalanisWJD03","V1j7Ssmd06MJ")).
neg(eqo("conf/vldb/Galindo-LegariaJWW03","w0x5DJZFElgJ")).
neg(eqo("conf/vldb/GehaniJR94","Je6SzJajy8oJ")).
neg(eqo("conf/vldb/Gentili01","2j1dalv3kCEJ")).
neg(eqo("conf/vldb/George98","xACnzf6RhVwJ")).
neg(eqo("conf/vldb/GibsonKR98","YiZVv5kVDb4J")).
neg(eqo("conf/vldb/GilbertKMS01","DqZEgt_ABcYJ")).
neg(eqo("conf/vldb/GingrasL98","CaI_f0ZnY0IJ")).
neg(eqo("conf/vldb/GoldmanSVG98","pweOUtA2iTAJ")).
neg(eqo("conf/vldb/GoldmanW97","vsbOhouYmEgJ")).
neg(eqo("conf/vldb/GottlobKP02","0YTOHF51qi8J")).
neg(eqo("conf/vldb/GottlobKP02","ORkxHLb7dvcJ")).
neg(eqo("conf/vldb/GraefeBC98","rZcRXL6ueUMJ")).
neg(eqo("conf/vldb/GravanoG97","fw5XfUh15osJ")).
neg(eqo("conf/vldb/Greco98","_mZlLWokuhwJ")).
neg(eqo("conf/vldb/HammelP02","ipAB8UMS7QkJ")).
neg(eqo("conf/vldb/HanF95","INrtkhaMZoMJ")).
neg(eqo("conf/vldb/Hess96","Gia7489k5t4J")).
neg(eqo("conf/vldb/HoelS95","7KsyQNj74A4J")).
neg(eqo("conf/vldb/HoelS95","btydMRJMBqoJ")).
neg(eqo("conf/vldb/HoelS95","epUf9ogilogJ")).
neg(eqo("conf/vldb/Huyn01","4JBCp5CxRxgJ")).
neg(eqo("conf/vldb/Ioannidis03","jELnwotIy9kJ")).
neg(eqo("conf/vldb/JagadishNSSK97","xt5rv136XsgJ")).
neg(eqo("conf/vldb/JohnsonA00","SByuGUSfTtYJ")).
neg(eqo("conf/vldb/JohnsonA00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066260%26type%3Dpdf")).
neg(eqo("conf/vldb/JosifovskiR99","2JeOY01wVQEJ")).
neg(eqo("conf/vldb/JosifovskiR99","KUYFJk7kXGEJ")).
neg(eqo("conf/vldb/Keogh02","GhGLKe4-qS8J")).
neg(eqo("conf/vldb/Keogh02","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D155956WS%26recid%3D199301530041MD")).
neg(eqo("conf/vldb/KnorrN98","CVUC4Rc5JU8J")).
neg(eqo("conf/vldb/KnorrN99","9KiPVAodKnYJ")).
neg(eqo("conf/vldb/KonopnickiS95","j2GYY75JSWsJ")).
neg(eqo("conf/vldb/KornLKF98","ewsBMN0qVa4J")).
neg(eqo("conf/vldb/LabrinidisR03","0GMNedjfVV0J")).
neg(eqo("conf/vldb/LakshmananSS99","oQwbs_kHvysJ")).
neg(eqo("conf/vldb/LeeL96","tuVp_18tFv8J")).
neg(eqo("conf/vldb/LevyMS94","_aINhLup2FgJ")).
neg(eqo("conf/vldb/LevySSZ94","lAWovPdchyUJ")).
neg(eqo("conf/vldb/LifantsevC02","gPvyDDUyrg4J")).
neg(eqo("conf/vldb/LlirbatST97","-zcXkmCqXLAJ")).
neg(eqo("conf/vldb/LuL00","Ih5hY-NRmFgJ")).
neg(eqo("conf/vldb/LuOT94","BNyOKJXXvDUJ")).
neg(eqo("conf/vldb/LuoNEW03","4NM5WR1WtPcJ")).
neg(eqo("conf/vldb/MadhavanH03","yhfwhXxLc_YJ")).
neg(eqo("conf/vldb/ManegoldBK00","G9DGYRD0cnMJ")).
neg(eqo("conf/vldb/ManegoldBK00","ZnbELiAcSJEJ")).
neg(eqo("conf/vldb/MaratheS97","0oPfKUylwgEJ")).
neg(eqo("conf/vldb/Mattos03","X4SawDz_jf8J")).
neg(eqo("conf/vldb/MignetMAC01","IoNxL_rg2_cJ")).
neg(eqo("conf/vldb/MignetMAC01","JCQQgBm1c-UJ")).
neg(eqo("conf/vldb/MillerHH00","pOFhgBVYVTkJ")).
neg(eqo("conf/vldb/Moerkotte98","HcCevkoobDsJ")).
neg(eqo("conf/vldb/Mohan01","IWM2gExnQLkJ")).
neg(eqo("conf/vldb/Mohan02a","IGS3TtqfKUgJ")).
neg(eqo("conf/vldb/Mohan02a","XG4Y1UB1rhAJ")).
neg(eqo("conf/vldb/MuntzR94","o9DfGI9zsloJ")).
neg(eqo("conf/vldb/MuthOPW98","cpoDCxpjl1wJ")).
neg(eqo("conf/vldb/NarayananS01","wTkEL2iBRtUJ")).
neg(eqo("conf/vldb/NaumannLF99","xbCgS61JHlYJ")).
neg(eqo("conf/vldb/NieKH03","EMhPgeKZ8wgJ")).
neg(eqo("conf/vldb/NishioSTTL01","PjfBTUeLnMAJ")).
neg(eqo("conf/vldb/Objectivity98","9rDLhwM_4mYJ")).
neg(eqo("conf/vldb/OhuraTPK02","yVBY95eCjkkJ")).
neg(eqo("conf/vldb/OoiGT98","LJdSx1Di81MJ")).
neg(eqo("conf/vldb/OrensteinK95","VSQ0v1UlIvoJ")).
neg(eqo("conf/vldb/OzsuLON01","CG-_La4oAYkJ")).
neg(eqo("conf/vldb/PalpanasSCP02","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/PantiSG00","qnTeRoB_Uw8J")).
neg(eqo("conf/vldb/PapadiasMD98","dXExoKaZC-sJ")).
neg(eqo("conf/vldb/PossP03","DYZlq4rntjwJ")).
neg(eqo("conf/vldb/RamamurthyDS02","4bvjebYsdRkJ")).
neg(eqo("conf/vldb/RamanH01","2DGc2z5xBlwJ")).
neg(eqo("conf/vldb/RastogiS98","Opm5VlTzQTAJ")).
neg(eqo("conf/vldb/Sacks-Davis96","FuzSLPzjrokJ")).
neg(eqo("conf/vldb/SadriZZA01","H6XGSfr9v6MJ")).
neg(eqo("conf/vldb/SahuguetA99","bDeV7QFno8IJ")).
neg(eqo("conf/vldb/SahuguetA99","ylSQWkUrmxoJ")).
neg(eqo("conf/vldb/SakuraiYUK00","HREx16E-ZDYJ")).
neg(eqo("conf/vldb/Sarawagi00","lOFly1WWz4EJ")).
neg(eqo("conf/vldb/Sarawagi95","7GpYSr7yaWAJ")).
neg(eqo("conf/vldb/Sarawagi99","49BUF_66HgcJ")).
neg(eqo("conf/vldb/SarawagiBKM02","Cnin2J-8JzkJ")).
neg(eqo("conf/vldb/SavasereON95","hLrdara3zskJ")).
neg(eqo("conf/vldb/SavasereON95","ko0i4AzclBgJ")).
neg(eqo("conf/vldb/SayalCDS02","xYQmZDKjXeEJ")).
neg(eqo("conf/vldb/Schnase00","url:http://portal.acm.org/citation.cfm%3Fid%3D984399")).
neg(eqo("conf/vldb/Schoning03","p0Wvdn9apRsJ")).
neg(eqo("conf/vldb/SeidlK97","HGXaVrOM_NwJ")).
neg(eqo("conf/vldb/SenkulKT02","X1MBCvIuINwJ")).
neg(eqo("conf/vldb/SeshadriLR97","ggV87TiwH04J")).
neg(eqo("conf/vldb/Shaw98","Q-KG8a3_BmIJ")).
neg(eqo("conf/vldb/SheikholeslamiCZ98","C2VEa-WmIt0J")).
neg(eqo("conf/vldb/Shenker03","Ki6xgXL7ap4J")).
neg(eqo("conf/vldb/Shmueli01","cA1Zsnlz-tIJ")).
neg(eqo("conf/vldb/Sripada02","uB5xSNxu3V0J")).
neg(eqo("conf/vldb/StanoiRAA01","tkDKXqcmDYMJ")).
neg(eqo("conf/vldb/SundaraHCAS01","QrUMLUMSougJ")).
neg(eqo("conf/vldb/TaoP02","CxBJwFNdozAJ")).
neg(eqo("conf/vldb/TaoP02","tyU_7GA-dtUJ")).
neg(eqo("conf/vldb/Toivonen96","ut53pjEsmxEJ")).
neg(eqo("conf/vldb/TorloneA03","url:http://portal.acm.org/citation.cfm%3Fid%3D1041410.1041433")).
neg(eqo("conf/vldb/VassalosP97","W34JQQUUM84J")).
neg(eqo("conf/vldb/Wadler01","TyF71uAlnLsJ")).
neg(eqo("conf/vldb/Wang95","dfOqJZmGhAgJ")).
neg(eqo("conf/vldb/WeikumMHZ02","hjh9Ck2r0LgJ")).
neg(eqo("conf/vldb/WildfogelY97","D0L3ufxOyx4J")).
neg(eqo("conf/vldb/X00a","48O7UQtGDg4J")).
neg(eqo("conf/vldb/X00a","url:http://portal.acm.org/citation.cfm%3Fid%3D592200.592435")).
neg(eqo("conf/vldb/YanL95","VwsS71_KQX8J")).
neg(eqo("conf/vldb/YangG01","zWthBBfpT80J")).
neg(eqo("conf/vldb/YangKL97","CduLyvAaxVsJ")).
neg(eqo("conf/vldb/YangKL97","Fg0Y-u39c7oJ")).
neg(eqo("conf/vldb/YuAA03","T9f2Eh-ZQogJ")).
neg(eqo("conf/vldb/YuAA03","lNt3ITCIsfQJ")).
neg(eqo("conf/vldb/YuSLJ02","g6aNdUkkljIJ")).
neg(eqo("conf/vldb/ZengBNN01","NKMvpoBB01oJ")).
neg(eqo("conf/vldb/ZhangL98","ZjHAEBJYahAJ")).
neg(eqo("conf/vldb/ZhouLZLZJT01","AwFxLUGiceUJ")).
neg(eqo("conf/vldb/ZhouLZLZJT01","c_0dAY8stz8J")).
neg(eqo("conf/vldb/ZirintsisKM99","wFn2slRHDU4J")).
neg(eqo("journals/sigmod/AbelTK97","cMaooygNzdgJ")).
neg(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637424%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02","_hb7jvkdltcJ")).
neg(eqo("journals/sigmod/Aberer02b","2r6t9GEZb28J")).
neg(eqo("journals/sigmod/Aberer03","9p1lvACa-sYJ")).
neg(eqo("journals/sigmod/Aberer03b","y7pjn8bVOe0J")).
neg(eqo("journals/sigmod/Aberer03c","MvTlkPfVEUIJ")).
neg(eqo("journals/sigmod/Aberer03c","url:http://portal.acm.org/citation.cfm%3Fid%3D945721.945727%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AbererCH02","3axhCWXQQN0J")).
neg(eqo("journals/sigmod/Abiteboul99","J_7kZS39msAJ")).
neg(eqo("journals/sigmod/AdelbergKG96","6gc5TN-yce8J")).
neg(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
neg(eqo("journals/sigmod/AlonsoCIM95","OAGE_9ItK1AJ")).
neg(eqo("journals/sigmod/ArpinarD00","lCfSw3J1Z2sJ")).
neg(eqo("journals/sigmod/AtkinsonDJPS96","s73cork-8iIJ")).
neg(eqo("journals/sigmod/BallMRZ02","NiswbODuzhAJ")).
neg(eqo("journals/sigmod/BergamaschiCV99","GDoFPiEzEhQJ")).
neg(eqo("journals/sigmod/Bernstein98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D126485%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BertinoEH01","_CpNV6dqRmEJ")).
neg(eqo("journals/sigmod/Bestavros96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141831%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BiancheriPP01","eznFJ2e_pQQJ")).
neg(eqo("journals/sigmod/BilirisP96","gt44wy948iMJ")).
neg(eqo("journals/sigmod/Bohlen95","IBg3vuolFUwJ")).
neg(eqo("journals/sigmod/BollKB98","R1j3CdeOlwsJ")).
neg(eqo("journals/sigmod/BonifatiC00","lrGge6mTVckJ")).
neg(eqo("journals/sigmod/BorgidaCS98","R6TFDuu4ojoJ")).
neg(eqo("journals/sigmod/BuchnerM98","bTm8WlpGFQcJ")).
neg(eqo("journals/sigmod/Bussler02","nkqJapMxKAAJ")).
neg(eqo("journals/sigmod/BusslerFM02","m56HUW18JKAJ")).
neg(eqo("journals/sigmod/Cardelli01","LAkxIFGnZzYJ")).
neg(eqo("journals/sigmod/Cardelli01","vwdWTx0dk7QJ")).
neg(eqo("journals/sigmod/Chang03","1KSfxI44iGUJ")).
neg(eqo("journals/sigmod/ChangGKRS98","ge5USB8ZSH0J")).
neg(eqo("journals/sigmod/Chaudhri98","ig7B9agTOMAJ")).
neg(eqo("journals/sigmod/ChaudhuriD97","qfohkpyTawoJ")).
neg(eqo("journals/sigmod/Chen94","7MfXAAdBQ2EJ")).
neg(eqo("journals/sigmod/Chen94","LZZJe-aHFnQJ")).
neg(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141004%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ChenHKPW94","Opow89YK6a8J")).
neg(eqo("journals/sigmod/ChienTZ01","N9NdxNRvMMkJ")).
neg(eqo("journals/sigmod/ChienTZ01","cjBpI3TcSWsJ")).
neg(eqo("journals/sigmod/ChristoffelPSL98","MNvk8SChYf0J")).
neg(eqo("journals/sigmod/DemersGRTY03","XYBfAojuBzsJ")).
neg(eqo("journals/sigmod/Dogac02","gETqmiI3Y2cJ")).
neg(eqo("journals/sigmod/DogacAOD95","url:http://ieeexplore.ieee.org/iel4/5812/15497/00718124.pdf%3Farnumber%3D718124")).
neg(eqo("journals/sigmod/DongS00","VvZfyQsZuNUJ")).
neg(eqo("journals/sigmod/DrewHKKLLLSW95","KxwymZ2AGNQJ")).
neg(eqo("journals/sigmod/EisenbergM00","75BD5JhAlbsJ")).
neg(eqo("journals/sigmod/EisenbergM01","YQQMvRraFBwJ")).
neg(eqo("journals/sigmod/EisenbergM98a","6uelfg3RgEoJ")).
neg(eqo("journals/sigmod/ElmagarmidJF95","aXzSTzaiPJwJ")).
neg(eqo("journals/sigmod/FengJH01","SUT-QTwqFNkJ")).
neg(eqo("journals/sigmod/ForteHWDCVHFS99","Sg5UhqcDrS0J")).
neg(eqo("journals/sigmod/ForteHWDCVHFS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245885%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin00","url:http://portal.acm.org/citation.cfm%3Fid%3D362084%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin00a","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin00a","url:http://portal.acm.org/citation.cfm%3Fid%3D362084%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin00b","DE_MK2KGbrQJ")).
neg(eqo("journals/sigmod/Franklin97b","CtkIgyH-WvMJ")).
neg(eqo("journals/sigmod/Franklin97b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/Franklin98a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/Franklin99","sXxcvIfzTx0J")).
neg(eqo("journals/sigmod/Franklin99","url:http://portal.acm.org/citation.cfm%3Fid%3D362084%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin99a","url:http://portal.acm.org/citation.cfm%3Fid%3D362084%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Gal99","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/Geller02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/GerlaX03","sfQlMM3SXpAJ")).
neg(eqo("journals/sigmod/Goethals02","nSKzTBqurCwJ")).
neg(eqo("journals/sigmod/GunopulosK01","zSO1Y5W7WkwJ")).
neg(eqo("journals/sigmod/GuptaHR97","Yrv_J8sm-FAJ")).
neg(eqo("journals/sigmod/HadzilacosT97","176Z1JFhdTwJ")).
neg(eqo("journals/sigmod/Halevy03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1031591%26type%3Dpdf")).
neg(eqo("journals/sigmod/Hammer01","KWGZbkptTxgJ")).
neg(eqo("journals/sigmod/Hammer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Hammer03","buygIvAzKfkJ")).
neg(eqo("journals/sigmod/Han98","ehSjmvsHTmMJ")).
neg(eqo("journals/sigmod/Hanson99","AatoNnELw78J")).
neg(eqo("journals/sigmod/HansonN99","b5uRDGKYrcMJ")).
neg(eqo("journals/sigmod/Hellerstein03","olIysX6gdKcJ")).
neg(eqo("journals/sigmod/HuangKL02","JKQ1qE-naxQJ")).
neg(eqo("journals/sigmod/JenningsNF98","cL06_NviyTQJ")).
neg(eqo("journals/sigmod/JukicNV03","HhUCea7De6YJ")).
neg(eqo("journals/sigmod/Keim96","75BD5JhAlbsJ")).
neg(eqo("journals/sigmod/KempsterST99","McorMeCrkHgJ")).
neg(eqo("journals/sigmod/Kim94","CO1WDbPzS0wJ")).
neg(eqo("journals/sigmod/KiyokiKH94","OzgnxugGCWMJ")).
neg(eqo("journals/sigmod/Kosch02","87kheB4QiIsJ")).
neg(eqo("journals/sigmod/KuoM96","eJ_B_aWFR48J")).
neg(eqo("journals/sigmod/Labrinidis01","6aj9I6CnpEgJ")).
neg(eqo("journals/sigmod/LeeCL95","p6ro8VCQBwcJ")).
neg(eqo("journals/sigmod/Libkin99","e0j-56kaeR4J")).
neg(eqo("journals/sigmod/LiefkeS00","4q4PDOS45uIJ")).
neg(eqo("journals/sigmod/LinP96","oNYOKYvjoKgJ")).
neg(eqo("journals/sigmod/Liu02","C84rFQN_ug0J")).
neg(eqo("journals/sigmod/Liu02a","_qopgNiYmXQJ")).
neg(eqo("journals/sigmod/Liu02b","url:http://doi.wiley.com/10.1002/he.48")).
neg(eqo("journals/sigmod/Liu03a","url:http://doi.wiley.com/10.1002/ev.1000")).
neg(eqo("journals/sigmod/Loeffen94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271095%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/LometBCLN98","url:http://doi.wiley.com/10.1002/he.133")).
neg(eqo("journals/sigmod/MaximilienS02","TabFkjNTLMsJ")).
neg(eqo("journals/sigmod/MedskerCS95","p_-uWY9S6AAJ")).
neg(eqo("journals/sigmod/MeltzerC98","EXrpbVnCDjMJ")).
neg(eqo("journals/sigmod/Nascimento03","bRrivrepz-UJ")).
neg(eqo("journals/sigmod/Naughton00","ZjxilICcJ94J")).
neg(eqo("journals/sigmod/Neven02","0komEtlfzzMJ")).
neg(eqo("journals/sigmod/OrlandicLS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245907%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/PissinouSEMOPSTD94","1hazaAEoGTAJ")).
neg(eqo("journals/sigmod/PitouraAPSV03","K84OAzFimWgJ")).
neg(eqo("journals/sigmod/Qian95","url:http://portal.acm.org/citation.cfm%3Fid%3D645921.756661")).
neg(eqo("journals/sigmod/Qian95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96","dkdyz41-JesJ")).
neg(eqo("journals/sigmod/Qian96a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219772%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
neg(eqo("journals/sigmod/RamanathanH97","3Isoplo_hi0J")).
neg(eqo("journals/sigmod/Ritter98","mzqmEYGGT_IJ")).
neg(eqo("journals/sigmod/Rosenthal98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D277953%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossGN03","3HUnvGuXtZEJ")).
neg(eqo("journals/sigmod/RossIJP00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Roussopoulos98","uPBlQ76s_g4J")).
neg(eqo("journals/sigmod/Roussopoulos98","url:http://portal.acm.org/citation.cfm%3Fid%3D16857")).
neg(eqo("journals/sigmod/Roussopoulos98","v_f-DhtOLkkJ")).
neg(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
neg(eqo("journals/sigmod/Seshadri98","GfiQygac5twJ")).
neg(eqo("journals/sigmod/Sidell96","qGdD5aJIicIJ")).
neg(eqo("journals/sigmod/SmithO99","09nCxGk1-_cJ")).
neg(eqo("journals/sigmod/Snodgrass01a","-OEJgpIAScMJ")).
neg(eqo("journals/sigmod/Snodgrass02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107521%26type%3Dpdf")).
neg(eqo("journals/sigmod/Snodgrass03","ReOfuE1ytx4J")).
neg(eqo("journals/sigmod/Snodgrass03c","vUONDuuNNCQJ")).
neg(eqo("journals/sigmod/Snodgrass94","VwZQmafqkE0J")).
neg(eqo("journals/sigmod/Snodgrass97a","omhk81_X_mQJ")).
neg(eqo("journals/sigmod/Snodgrass99b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/Stonebraker02","url:http://portal.acm.org/citation.cfm%3Fid%3D582192")).
neg(eqo("journals/sigmod/Suciu02","dAzjpkhh8lUJ")).
neg(eqo("journals/sigmod/SycaraKWL99","KvsmVlCdtKAJ")).
neg(eqo("journals/sigmod/TanK03","P9xX0UDXnRcJ")).
neg(eqo("journals/sigmod/TanK03","gCsPS_1fwmYJ")).
neg(eqo("journals/sigmod/TaninBS96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057821")).
neg(eqo("journals/sigmod/TomasicS97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D984520%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/VetterliVS00","zZo47Z-jVX4J")).
neg(eqo("journals/sigmod/Vianu03","x9lckGlDfAEJ")).
neg(eqo("journals/sigmod/WestmannKHM00","_hDCldPyum0J")).
neg(eqo("journals/sigmod/Widom95","VKDhNI5dc5oJ")).
neg(eqo("journals/sigmod/Widom95","url:http://portal.acm.org/citation.cfm%3Fid%3D233269%26dl%3DGUIDE%26dl%3DGUIDE%26type%3Dproceeding%26idx%3D233269%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom95a","5Ca6WOB3X-wJ")).
neg(eqo("journals/sigmod/Widom96","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Widom96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974756%26type%3Dpdf%26dl%3DACM%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Widom96","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Widom96b","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565127%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083803%26type%3Dpdf")).
neg(eqo("journals/sigmod/Winslett03c","FV-aBnwWv7IJ")).
neg(eqo("journals/sigmod/Winslett94","dx3lTV6KnpQJ")).
neg(eqo("journals/sigmod/WolfsonSDNR95","hjYbadIKcBcJ")).
neg(eqo("journals/sigmod/X94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974142%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/Alagic99","2X3tlHHtdCYJ")).
neg(eqo("journals/tods/BaralisW00","h4TkmhS263gJ")).
neg(eqo("journals/tods/BaralisW00","tCGDtRSBeT0J")).
neg(eqo("journals/tods/BeneventanoBS03","kck9dlmwO0kJ")).
neg(eqo("journals/tods/BohlenJS00","6eheB6Kct4MJ")).
neg(eqo("journals/tods/CasatiCPP99","G85jgJ0oWQMJ")).
neg(eqo("journals/tods/ChaudhuriS99","xxkUtjfGpvAJ")).
neg(eqo("journals/tods/Chen95a","5VzWV9tSVIMJ")).
neg(eqo("journals/tods/ChenHM95","2Mm5-9sYYfEJ")).
neg(eqo("journals/tods/ChoG03","zIvpO1L9YaEJ")).
neg(eqo("journals/tods/CliffordC94","l4zJZIJGgyQJ")).
neg(eqo("journals/tods/DekhtyarRS01","tVDUYwBqJAcJ")).
neg(eqo("journals/tods/DeySB99","qbQLwnrAZjQJ")).
neg(eqo("journals/tods/GunopulosKMSTS03","EGl2738Pn3YJ")).
neg(eqo("journals/tods/HsuSY01","jNjxe59ZOLAJ")).
neg(eqo("journals/tods/Kim94","FVPFM7RKdG0J")).
neg(eqo("journals/tods/Lerner00","EEs2CkSayQMJ")).
neg(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
neg(eqo("journals/tods/LiuDL02","0SjMEzMYlEIJ")).
neg(eqo("journals/tods/PolyzoisG94","p7x1zGD_bkEJ")).
neg(eqo("journals/tods/ScioreSR94","fB2xVdlMTtwJ")).
neg(eqo("journals/tods/ScioreSR94","u-4YLOGmAy4J")).
neg(eqo("journals/tods/ShashaLSV95","0aVKzjogLlAJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/RV67P1J713229350.pdf")).
neg(eqo("journals/tods/WangBBJ97","tAnONC5J2W8J")).
neg(eqo("journals/tods/Wijsen99","-sg0_DCr6ugJ")).
neg(eqo("journals/tods/ZobelMR98","JirHvF5eQp4J")).
neg(eqo("journals/vldb/AtzeniM00","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
neg(eqo("journals/vldb/BarbaraI95","GXhaGGajWZkJ")).
neg(eqo("journals/vldb/BeckerGOSW96","7TPtwxigrc0J")).
neg(eqo("journals/vldb/BernsteinPS00","1Xo59nOfVKoJ")).
neg(eqo("journals/vldb/Bertino94","l-QHiSxClXcJ")).
neg(eqo("journals/vldb/ChandrasekaranF03","k3znuHyMD0oJ")).
neg(eqo("journals/vldb/ChangG01","JEYdnFjCT6MJ")).
neg(eqo("journals/vldb/DattaDVRN01","GH3UmB-SLb0J")).
neg(eqo("journals/vldb/EvangelidisS97","-953Ij-RwjcJ")).
neg(eqo("journals/vldb/EvangelidisS97","3TOqLeL1G64J")).
neg(eqo("journals/vldb/FiebigHKMNSW02","flSUunhe1Q4J")).
neg(eqo("journals/vldb/Halevy02","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/13891286/2000/00000034/00000006/art00152%26unc%3D")).
neg(eqo("journals/vldb/HarderST99","tLIvGUXgK4cJ")).
neg(eqo("journals/vldb/HjaltasonS02","wMYmuCfsFksJ")).
neg(eqo("journals/vldb/JiangE98","9xH94cKF-CYJ")).
neg(eqo("journals/vldb/LawLG99","xmE1380_4E4J")).
neg(eqo("journals/vldb/ManegoldBK00","JgdpgBpMDr4J")).
neg(eqo("journals/vldb/MehrotraKS97","lV-Wz1Tc72gJ")).
neg(eqo("journals/vldb/MihailaRT02","jlzv21qakdoJ")).
neg(eqo("journals/vldb/MylopoulosCPST96","M8Eh286-D0wJ")).
neg(eqo("journals/vldb/NanopoulosM02","F9Fe5NfpK6MJ")).
neg(eqo("journals/vldb/NgC98","AuLP3kEXgVgJ")).
neg(eqo("journals/vldb/NybergBCGL95","A1phylxPkl4J")).
neg(eqo("journals/vldb/PanagosB97","8b1nk87L2KoJ")).
neg(eqo("journals/vldb/PanagosB97","hF6d0-SWSPcJ")).
neg(eqo("journals/vldb/PapadiasS94","c1uGCkJXMs8J")).
neg(eqo("journals/vldb/RafieiM02","3iVRJJMjVWUJ")).
neg(eqo("journals/vldb/RafieiM02","Ls7vkMLcYmkJ")).
neg(eqo("journals/vldb/RamakrishnanSSS94","P_97uhnD9TwJ")).
neg(eqo("journals/vldb/RamamohanaraoH94","4wHLoLkVcS8J")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","Jm8lRWYv2Y4J")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","btydMRJMBqoJ")).
neg(eqo("journals/vldb/SivasankaranSTPR96","x2c_pMyVtCoJ")).
neg(eqo("journals/vldb/TurkerG01","Rba70P6SqQYJ")).
pos(eqo("conf/sigmod/AbiteboulCM95","cu9DXtjeF24J")).
pos(eqo("conf/sigmod/AboulnagaC99","WWaxLMIptTMJ")).
pos(eqo("conf/sigmod/AboulnagaC99","xnDzelm2t1QJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","0lAHCM-lcjIJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","2fO9nM2FoGYJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","GOguWgH6D_UJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","_-yXA5HLnqoJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","h2z51QPXcSkJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","y74PIIvb_GMJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","C221gFS5VVoJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","czJmrc_4tZ4J")).
pos(eqo("conf/sigmod/AcharyaPR99","-k0cD5NwXnoJ")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/AdelbergD99","s40fqzss4woJ")).
pos(eqo("conf/sigmod/Agarwal96","Ca-BABwlsQAJ")).
pos(eqo("conf/sigmod/Agarwal96","Fd0jPlSwFWcJ")).
pos(eqo("conf/sigmod/AgrawalES03","Wrue2IkpGyEJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","EQ0ys8s10vcJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","rSTewQ1dQkYJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","x92Yw8H9uH4J")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","7-b5YXuGJS0J")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","fm69LHjS4T0J")).
pos(eqo("conf/sigmod/AndersonBKW98","j6v2b9hN-R4J")).
pos(eqo("conf/sigmod/ArasuBBDIRW03","7D59wPTtkdcJ")).
pos(eqo("conf/sigmod/ArefBV95","K7mfVCHc3noJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","E_eOZJYat6IJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","OaNzji_-7tsJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","aCCAyNhJFtsJ")).
pos(eqo("conf/sigmod/AshleyFHLNP95","t0Wd_YW4n3cJ")).
pos(eqo("conf/sigmod/AshleyFHLNP95","tL67lYBCRO4J")).
pos(eqo("conf/sigmod/BaruGLMPVC99","arQIThq-W4gJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","mXKKjAJUm-oJ")).
pos(eqo("conf/sigmod/Bayardo98","htTH8PrZ0dYJ")).
pos(eqo("conf/sigmod/Bayardo98","mvD-z59XDYoJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","1tZ74y0DNLIJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","5bjtbk4ZdZIJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","fTYVIbi40sAJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","hoi0T_8So4gJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","MOGnM6t6l3MJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","gWmqoNZHKAAJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","zguNkU2zLY0J")).
pos(eqo("conf/sigmod/BergstraesserBPS99","4Ha7Bs5Vq3MJ")).
pos(eqo("conf/sigmod/Bernstein96","EvuLCpyVqWgJ")).
pos(eqo("conf/sigmod/BettiniWBJ95","c57d3rgd3IcJ")).
pos(eqo("conf/sigmod/Blakeley94","VLd1PgYIoN8J")).
pos(eqo("conf/sigmod/BlakeleyD00","ZSR-MThg9UEJ")).
pos(eqo("conf/sigmod/BorkarDS01","8zFEVer1rBUJ")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","jJuSPh63bZ0J")).
pos(eqo("conf/sigmod/BrinDG95","QmhdqC_PIWsJ")).
pos(eqo("conf/sigmod/BrodskyK95","6t_N5axEm7cJ")).
pos(eqo("conf/sigmod/BrunoC02","KAf2DUUVabIJ")).
pos(eqo("conf/sigmod/BuchmannDZH95","MoNBLfTlYg0J")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/CareyFZ94","UBpDljYCfGgJ")).
pos(eqo("conf/sigmod/CarinoKKB01","a9HFF_bwiH4J")).
pos(eqo("conf/sigmod/CasatiS01","7H9j9z0x_3UJ")).
pos(eqo("conf/sigmod/CatarciS01","frbExwv4DiwJ")).
pos(eqo("conf/sigmod/CatarciS94","yaaZKZCP3soJ")).
pos(eqo("conf/sigmod/Chakrabarti99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304231%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChanI98","39AOIRe9qSQJ")).
pos(eqo("conf/sigmod/ChanI98","VC7Jbwgn_O0J")).
pos(eqo("conf/sigmod/ChangC01","XbmULzOYzZUJ")).
pos(eqo("conf/sigmod/ChangH02","4zxRX5K-YSsJ")).
pos(eqo("conf/sigmod/Chaudhuri97","QkyXMep2bWsJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","4zZ7Lxt4PPIJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","gY652XXjHB8J")).
pos(eqo("conf/sigmod/ChaudhuriD97","jsapF3OoWXcJ")).
pos(eqo("conf/sigmod/ChaudhuriDN01","lCQ0HZYyYNcJ")).
pos(eqo("conf/sigmod/ChaudhuriDN01","qfohkpyTawoJ")).
pos(eqo("conf/sigmod/ChaudhuriGS03","OFGtGwUHhUQJ")).
pos(eqo("conf/sigmod/ChaudhuriMN99","U0w9W7YcsZwJ")).
pos(eqo("conf/sigmod/ChenDLT00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.336560")).
pos(eqo("conf/sigmod/CluetDSS98","lOZF0Ee3rUQJ")).
pos(eqo("conf/sigmod/ColbyKLMR97","0FohHTWs5toJ")).
pos(eqo("conf/sigmod/ConsensM94","u7rv6LAF8s8J")).
pos(eqo("conf/sigmod/CookWZ94","LiIWlw3oNgUJ")).
pos(eqo("conf/sigmod/DarR94","TtV6gGLQ9NMJ")).
pos(eqo("conf/sigmod/DoanDH01","Lv0bggWzgeoJ")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","AgBMhm_0uEIJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","fsa72WmA67kJ")).
pos(eqo("conf/sigmod/EmbleyJN99","O_SMlr3bFBMJ")).
pos(eqo("conf/sigmod/Englert94","KOpz_NXJ3WUJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","4bG39HmGrAQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","NqewK_dmRawJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","R4fVVmv_YvoJ")).
pos(eqo("conf/sigmod/FaloutsosSTT00","Sqy1tqGEnxsJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","RKh78Q-rJLMJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","W3H34LBUMtoJ")).
pos(eqo("conf/sigmod/FernandezFKLS98","x-Xcm921UTMJ")).
pos(eqo("conf/sigmod/FlorescuGKR02","uam2rv99rxsJ")).
pos(eqo("conf/sigmod/FreireHRRS02","YKkMxZntSUQJ")).
pos(eqo("conf/sigmod/Galhardas00","GxDfgCi-rq4J")).
pos(eqo("conf/sigmod/Galhardas00","QhUFQCApL8wJ")).
pos(eqo("conf/sigmod/GarofalakisG02","r4a_VlMfu38J")).
pos(eqo("conf/sigmod/GarofalakisGR02","ImADir74KWIJ")).
pos(eqo("conf/sigmod/GeneserethKD97","vRxd72o2PdoJ")).
pos(eqo("conf/sigmod/GionisGK01","cy_Fe935WMAJ")).
pos(eqo("conf/sigmod/GravanoCGP97","IVXOHTW5Lt0J")).
pos(eqo("conf/sigmod/GravanoCGP97","sBVErKh0FqMJ")).
pos(eqo("conf/sigmod/GravanoCGP97","yfb8p_tlSlsJ")).
pos(eqo("conf/sigmod/GreenwaldK01","8but_7FuryIJ")).
pos(eqo("conf/sigmod/GreenwaldK01","zlHamuvyxIwJ")).
pos(eqo("conf/sigmod/GunopulosD01","LBp-UtmfcScJ")).
pos(eqo("conf/sigmod/GunopulosD01","kneUxV6J3nQJ")).
pos(eqo("conf/sigmod/GunopulosD01","mnUzHNE5eF0J")).
pos(eqo("conf/sigmod/GuptaHR97","pGix0qZ6Uz4J")).
pos(eqo("conf/sigmod/GuptaMR95","2GUwicKtWTUJ")).
pos(eqo("conf/sigmod/GuptaMR95","7ggq-jY7UEYJ")).
pos(eqo("conf/sigmod/GuptaMR95","ELtcV7mOQDgJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","FEWg8Ea2CycJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","lmhkvir9Z84J")).
pos(eqo("conf/sigmod/HanFHCC94","6M-fnuhWEOIJ")).
pos(eqo("conf/sigmod/HanKS97","XFCkL9QhTjIJ")).
pos(eqo("conf/sigmod/HanKS97","_EEZCcB1BPYJ")).
pos(eqo("conf/sigmod/HanKS97","nD_Yjp9TNuIJ")).
pos(eqo("conf/sigmod/HanPDW01","ue3gCyIirokJ")).
pos(eqo("conf/sigmod/HanPY00","63XKDNdtzp8J")).
pos(eqo("conf/sigmod/HanPY00","R-ERjYdCskcJ")).
pos(eqo("conf/sigmod/HanPY00","YkKV8PCox8IJ")).
pos(eqo("conf/sigmod/HanPY00","mwSZ7Yejt8sJ")).
pos(eqo("conf/sigmod/HernandezMHYHT01","wMa4fMryrt0J")).
pos(eqo("conf/sigmod/HinneburgK99","C9imFvgrSvAJ")).
pos(eqo("conf/sigmod/HwangLYMMGCSS94","AWah9GLEFTAJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","1H_A7k3QsbQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","RcmGrB81X-4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","cffLplmoKH4J")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
pos(eqo("conf/sigmod/IvesFFLW99","yrnhcMqsUVoJ")).
pos(eqo("conf/sigmod/JaedickeM98","LrJw7qiWElQJ")).
pos(eqo("conf/sigmod/KabraD98","E0nhpX8pYsQJ")).
pos(eqo("conf/sigmod/KeoghCMP01","Cy8VDlIamc8J")).
pos(eqo("conf/sigmod/Kleissner95","DB8lVC2D9fcJ")).
pos(eqo("conf/sigmod/KornM00","HlhXdvHzlvwJ")).
pos(eqo("conf/sigmod/KornM00","N11b8vV9qIkJ")).
pos(eqo("conf/sigmod/KornackerMH97","J8sGEkYqAFcJ")).
pos(eqo("conf/sigmod/KornackerMH97","v34_ZFX7kZYJ")).
pos(eqo("conf/sigmod/KornackerMH97","w5tLFDyhdm8J")).
pos(eqo("conf/sigmod/KotidisR99","nsASp-dCJBQJ")).
pos(eqo("conf/sigmod/KoudasS97","0u8r8MJWgKAJ")).
pos(eqo("conf/sigmod/KoudasS97","Z3hu6UPm8eQJ")).
pos(eqo("conf/sigmod/KoudasS97","sB-nvl5829EJ")).
pos(eqo("conf/sigmod/KrollW94","AMvcOVWQiNEJ")).
pos(eqo("conf/sigmod/KuhnTS94","JnV4W3TKPxMJ")).
pos(eqo("conf/sigmod/LabioZWGGW97","uzpyy9XRpgYJ")).
pos(eqo("conf/sigmod/LacroixSC98","MyaiGcr-oYkJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","fZSRCe60AUcJ")).
pos(eqo("conf/sigmod/LakshmananPZ03","rNu93TfKkd4J")).
pos(eqo("conf/sigmod/LangS01","FFQc9XpGFRsJ")).
pos(eqo("conf/sigmod/LarsonG03","14VyjJ0mnBMJ")).
pos(eqo("conf/sigmod/LarsonG03","vmQeUKFzhAEJ")).
pos(eqo("conf/sigmod/LeeKOTM00","C8RLbWKCgicJ")).
pos(eqo("conf/sigmod/LiBKN03","micx2kyGfKIJ")).
pos(eqo("conf/sigmod/LiC95","yJPi5nBJmVYJ")).
pos(eqo("conf/sigmod/LiGS02","DZzqgw2TJ-MJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","P25_yh3lBhoJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","WSQzzj42AkEJ")).
pos(eqo("conf/sigmod/LiuHBPT99","BIox2W-EPfEJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","9Ho84Ho6xuIJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","UqI8eTF3k7sJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","izDXhqRW9AYJ")).
pos(eqo("conf/sigmod/LuoKMPWLN02","zQfzn1t6Xq8J")).
pos(eqo("conf/sigmod/MaddenFHH03","qz24tfFNHuoJ")).
pos(eqo("conf/sigmod/MaheshwariL97","VcVAYDLTty8J")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/Melling94","j4O-xhs1QAgJ")).
pos(eqo("conf/sigmod/Meseck01","hWiIngXs5I0J")).
pos(eqo("conf/sigmod/MiloAABN03","P7vZf4MkRO4J")).
pos(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
pos(eqo("conf/sigmod/Mohan01","IGS3TtqfKUgJ")).
pos(eqo("conf/sigmod/Mohan94","enYJ_2U2NdUJ")).
pos(eqo("conf/sigmod/MumickQM97","cvHvC7tUSrIJ")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/Mylopoulos98","5eBjuTrKTwoJ")).
pos(eqo("conf/sigmod/NatsevRS99","Y3nejQSVKnUJ")).
pos(eqo("conf/sigmod/OlstonWL01","I_YprPVQ45QJ")).
pos(eqo("conf/sigmod/OriaOILY00","xdUDA920uhMJ")).
pos(eqo("conf/sigmod/PangCL94","beMsu5ebf30J")).
pos(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
pos(eqo("conf/sigmod/PapakonstantinouV99","Y7J0sm6WO2kJ")).
pos(eqo("conf/sigmod/PatelD96","nmTGteLy8NAJ")).
pos(eqo("conf/sigmod/Pirahesh94","VG96hL8afvgJ")).
pos(eqo("conf/sigmod/PolyzotisG02","FK5GEhwW7uQJ")).
pos(eqo("conf/sigmod/ProcopiucJAM02","k7RinzPIdhYJ")).
pos(eqo("conf/sigmod/QunLO03","eBXNcn6PwAEJ")).
pos(eqo("conf/sigmod/RadekeBBEKKN95","Tkq6NymsVxsJ")).
pos(eqo("conf/sigmod/RadekeBBEKKN95","bDN03rZhUQEJ")).
pos(eqo("conf/sigmod/RajagopalanML98","HVP6eYl30IgJ")).
pos(eqo("conf/sigmod/RajagopalanML98","vbi6XDjg0X8J")).
pos(eqo("conf/sigmod/RajagopalanML98","wO6VeeLIXAsJ")).
pos(eqo("conf/sigmod/RamanH02","4692SthNStUJ")).
pos(eqo("conf/sigmod/RaoZML02","7Ucs6vmjHN0J")).
pos(eqo("conf/sigmod/ReinwaldP98","y_H9p9Lqj3IJ")).
pos(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
pos(eqo("conf/sigmod/RodriguezR00","dVDzCb6fuJ0J")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/citation.cfm%3Fid%3D375796")).
pos(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","fKiXyCQ0LNgJ")).
pos(eqo("conf/sigmod/RundensteinerCLCZNJLW99","SADcQZhMqgEJ")).
pos(eqo("conf/sigmod/SagonasSW94","0hHYO7tQJUgJ")).
pos(eqo("conf/sigmod/SagonasSW94","ezmsDUMWUJEJ")).
pos(eqo("conf/sigmod/SagonasSW94","xc8KEoeRT9sJ")).
pos(eqo("conf/sigmod/SalemBCL00","FElMcikK2GUJ")).
pos(eqo("conf/sigmod/SelfridgeSW96","4ucV5h3-YvMJ")).
pos(eqo("conf/sigmod/Seshadri99","url:http://portal.acm.org/citation.cfm%3Fid%3D304182.304226")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","1tKWKmyczaYJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","P8SQPINQRHQJ")).
pos(eqo("conf/sigmod/ThomasDM95","1zgqAaZv3NAJ")).
pos(eqo("conf/sigmod/TsurUACMNR98","w5i-zY0c1jAJ")).
pos(eqo("conf/sigmod/Ullman03","TabFkjNTLMsJ")).
pos(eqo("conf/sigmod/Vaskevitch94","cr7xWKidCnYJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
pos(eqo("conf/sigmod/WangPFY03","jpNXw9L7pxgJ")).
pos(eqo("conf/sigmod/WangPFY03","y5zNcYc9dqsJ")).
pos(eqo("conf/sigmod/WattezCBFF00","1SA9LhktHsUJ")).
pos(eqo("conf/sigmod/WitkowskiBBDFGSS03","ygCe1xRFuKgJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","TDIVG8_n_esJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","iFiv0xEJvIkJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","v6QoWdFgBjwJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","4dbCEDwsluQJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","SHi3jbyB9t0J")).
pos(eqo("conf/sigmod/Wu99","oIDF-Jhm9CYJ")).
pos(eqo("conf/sigmod/Wu99","xl1Jscb79KEJ")).
pos(eqo("conf/sigmod/YangM97","TUQ51ASLNI0J")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/YuMWL01","X3pjISS_wtcJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","Pbl_CbLYKWYJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","qW_oF_qWmvQJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VCc6IQulRJ4J")).
pos(eqo("conf/sigmod/ZhangNBB94","bymQ_6SSse4J")).
pos(eqo("conf/sigmod/ZhangNBB94","qOgXuRc7f4QJ")).
pos(eqo("conf/sigmod/ZhangRL96","NzUcyD-oMpQJ")).
pos(eqo("conf/sigmod/ZhangRL96","YpH8PvdL5awJ")).
pos(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
pos(eqo("conf/sigmod/ZhangRL96","mbeIcD0N1rQJ")).
pos(eqo("conf/sigmod/ZhangRL96","yoMojXfArHAJ")).
pos(eqo("conf/sigmod/ZhaoDN97","b-Va1c3t13gJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","MjGo7AhsPSsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","Wg8o4cj8Cq4J")).
pos(eqo("conf/sigmod/ZhaoDNS98","miytzHylgMAJ")).
pos(eqo("conf/sigmod/ZhouWGGZWXYF03","AwFxLUGiceUJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","2BGKvm5UIqAJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","KjM8fKqooDQJ")).
pos(eqo("conf/sigmod/ZhugeGHW95","SSwR2rhkJk0J")).
pos(eqo("conf/sigmod/ZhugeGHW95","lUxILYnWlLYJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","zSvWnSVwLUYJ")).
pos(eqo("conf/vldb/AcharyaFZ96","4AK08s31YqUJ")).
pos(eqo("conf/vldb/AcharyaFZ96","oH_xfQI8wIgJ")).
pos(eqo("conf/vldb/AcharyaFZ96","qTCsXcCsI7UJ")).
pos(eqo("conf/vldb/AcharyaGP99","-7tsGpHin24J")).
pos(eqo("conf/vldb/AdiBEY00","RkjggE7xhN0J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","E4fU9kpfXQsJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AggarwalHWY03","ZympjYazs6QJ")).
pos(eqo("conf/vldb/AggarwalHWY03","szlqyCesMpgJ")).
pos(eqo("conf/vldb/AggarwalHWY03","yFMUnqONfGwJ")).
pos(eqo("conf/vldb/AgrawalK02","5GDHzHaNiscJ")).
pos(eqo("conf/vldb/AgrawalK02","NDKJPUgy_K4J")).
pos(eqo("conf/vldb/AgrawalK02","qCvXLXmB6J8J")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AgrawalS94","551mHiCJRjoJ")).
pos(eqo("conf/vldb/AgrawalS94","RiQ-W5K0n6YJ")).
pos(eqo("conf/vldb/AgrawalS94","vT6v9qSkI2UJ")).
pos(eqo("conf/vldb/Amer-YahiaFSX03","fcB_7jx0pOMJ")).
pos(eqo("conf/vldb/AnSVKIG01","4Q5ikiCy82UJ")).
pos(eqo("conf/vldb/AnSVKIG01","HosSI1GtRY8J")).
pos(eqo("conf/vldb/Atal96","PaW8zjiNR9cJ")).
pos(eqo("conf/vldb/AtzeniMM97","25kJ4dWczjEJ")).
pos(eqo("conf/vldb/AtzeniMM97","HUIG38FY6zEJ")).
pos(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
pos(eqo("conf/vldb/BaralisW94","nqaF5CzBelgJ")).
pos(eqo("conf/vldb/BaumgartnerFG01a","GGyAHg9kwysJ")).
pos(eqo("conf/vldb/BenediktCFRZZ02","7xe6Gp9fIEEJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","AgqQVeQ7A0AJ")).
pos(eqo("conf/vldb/BerchtoldKK96","DDX7y0WvbRMJ")).
pos(eqo("conf/vldb/BerchtoldKK96","_oDfC1aR4CAJ")).
pos(eqo("conf/vldb/BernsteinHJRW00","KlPsHutXQi8J")).
pos(eqo("conf/vldb/BernsteinHJRW00","YvKC62tCWkQJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","IROKbaAxI6QJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","thTt2lg4_Z8J")).
pos(eqo("conf/vldb/BouganimP02","PhERWOcOkOgJ")).
pos(eqo("conf/vldb/CareyK98","MCuFKbwcWIIJ")).
pos(eqo("conf/vldb/CareyKRLABFLOPQRSSUVWY01","_pAcjtd1nbEJ")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("conf/vldb/CarneyCCCLSSTZ02","1J26mBTxdS0J")).
pos(eqo("conf/vldb/CarneyCCCLSSTZ02","4-igDwZdi-QJ")).
pos(eqo("conf/vldb/CarusoCGLM00","1Xo59nOfVKoJ")).
pos(eqo("conf/vldb/CasatiDGS01","bFnDGrZ_4voJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChakrabartiRS02","idfox84uNHUJ")).
pos(eqo("conf/vldb/ChanI99","KuA45Oh0rkYJ")).
pos(eqo("conf/vldb/ChaudhuriG99","l-Sn0enuHxkJ")).
pos(eqo("conf/vldb/ChaudhuriS96","QCFUIVkspywJ")).
pos(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
pos(eqo("conf/vldb/Chawathe99","w6VtZRVAZV8J")).
pos(eqo("conf/vldb/CherniackFZ01","49EWG8vzsXUJ")).
pos(eqo("conf/vldb/ChristodoulakisTZ97","D0z0BDnbnFcJ")).
pos(eqo("conf/vldb/ChristodoulakisTZ97","lojHMj5xWEwJ")).
pos(eqo("conf/vldb/Cluet03","faRBjw1op8YJ")).
pos(eqo("conf/vldb/CosleyLP02","22ZTae8fNuIJ")).
pos(eqo("conf/vldb/DeutschT03","qkJ_IyVmLfUJ")).
pos(eqo("conf/vldb/DidriksenGD95","0TNJ5d1tfkEJ")).
pos(eqo("conf/vldb/Dyreson96","AfM_N94rVD0J")).
pos(eqo("conf/vldb/EicklerGK95","63QhLG57QssJ")).
pos(eqo("conf/vldb/FankhauserGLMT98","JnwUAxUMwvQJ")).
pos(eqo("conf/vldb/FankhauserGLMT98","jGFfS5lAyLQJ")).
pos(eqo("conf/vldb/GalhardasFSSS01","RZZjZ_7yJb8J")).
pos(eqo("conf/vldb/GalhardasFSSS01","nlOAkKW_ry8J")).
pos(eqo("conf/vldb/GantiLR00","Vd-lSpZc0cYJ")).
pos(eqo("conf/vldb/GardarinGT96","4NKqwzC5A_wJ")).
pos(eqo("conf/vldb/GarofalakisG02","ImADir74KWIJ")).
pos(eqo("conf/vldb/GarofalakisOS97","3p2a2ZKrCjcJ")).
pos(eqo("conf/vldb/GehaniJR94","ndpqwnLwAWUJ")).
pos(eqo("conf/vldb/GolabO03","6K9FhI2pFEgJ")).
pos(eqo("conf/vldb/GoldmanSVG98","4qYPBQ1l07YJ")).
pos(eqo("conf/vldb/GoldsteinR00","FncQ86sO2agJ")).
pos(eqo("conf/vldb/GoldsteinR00","ylZFc8RNoeQJ")).
pos(eqo("conf/vldb/GrustKT03","25xRkmL_4BsJ")).
pos(eqo("conf/vldb/GuptaHQ95","VCSbj6MwKlgJ")).
pos(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
pos(eqo("conf/vldb/Hallmark95","xTKZ6OuegIEJ")).
pos(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
pos(eqo("conf/vldb/HammelP02","SU2XS1MVb40J")).
pos(eqo("conf/vldb/HanF95","889ULwUj6XUJ")).
pos(eqo("conf/vldb/HankinsP03","NsxXW_CvQpkJ")).
pos(eqo("conf/vldb/HasanM95","-aml_OMAQNgJ")).
pos(eqo("conf/vldb/HoskingC99","8Pt19BiLeHEJ")).
pos(eqo("conf/vldb/HuangJR97","nBHS2BTx-GkJ")).
pos(eqo("conf/vldb/Huyn01","SbL4xw4mCewJ")).
pos(eqo("conf/vldb/IpeirotisG02","JmGdMWsJuK0J")).
pos(eqo("conf/vldb/JagatheesanMPW03","InqySB8bkKkJ")).
pos(eqo("conf/vldb/JarkeKL00","6c3XQZ-_HDUJ")).
pos(eqo("conf/vldb/KamelF94","A7WoAzxOJ9YJ")).
pos(eqo("conf/vldb/KamelF94","Gr7nw0PAH1sJ")).
pos(eqo("conf/vldb/KemperK94","jQYEiVS0CIgJ")).
pos(eqo("conf/vldb/KemperK94","qUfWV4VVxegJ")).
pos(eqo("conf/vldb/KiesslingK02","3VHepuiTGHUJ")).
pos(eqo("conf/vldb/KiesslingK02","Z8bBN2cO11UJ")).
pos(eqo("conf/vldb/Koch03","rhxIrsQkm5AJ")).
pos(eqo("conf/vldb/KochBG03","xCbXlJHLR48J")).
pos(eqo("conf/vldb/KoudasS03","jqWSQmw8ScEJ")).
pos(eqo("conf/vldb/KumarRRT99","1xbD4ssSjjUJ")).
pos(eqo("conf/vldb/KumarRRT99","fJn_2E8aihYJ")).
pos(eqo("conf/vldb/LakshmananNWZJ02","qfw7Pu1wVcIJ")).
pos(eqo("conf/vldb/LevyRO96","bbeft23FHAkJ")).
pos(eqo("conf/vldb/LevyRO96","lrocSfnfPrMJ")).
pos(eqo("conf/vldb/LiRS99","Bf44yXvb6EAJ")).
pos(eqo("conf/vldb/LimWV03","aPJnWocHLUwJ")).
pos(eqo("conf/vldb/LingLL00","yKnPPSNrDb0J")).
pos(eqo("conf/vldb/LometT95","P7GUGC5bz7wJ")).
pos(eqo("conf/vldb/LuoN01","TRWSf77xoWsJ")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/Mattos96","EpBlTCJ0_dUJ")).
pos(eqo("conf/vldb/MeoPC96","Opm5VlTzQTAJ")).
pos(eqo("conf/vldb/MeoPC96","SNIbAV2EN0MJ")).
pos(eqo("conf/vldb/MeoPC96","p2pzLkGmO9wJ")).
pos(eqo("conf/vldb/MignetMAC01","KkI-NuyDkDQJ")).
pos(eqo("conf/vldb/Moerkotte98","WIbtPXHpeHoJ")).
pos(eqo("conf/vldb/MorishimaKKT01","8hDo6qczOzMJ")).
pos(eqo("conf/vldb/NatsevCSLV01","2CYtbbiwv-AJ")).
pos(eqo("conf/vldb/NatsevCSLV01","e6dXyX0MKEIJ")).
pos(eqo("conf/vldb/NishioSTTL01","S30IXg4ClFIJ")).
pos(eqo("conf/vldb/Objectivity98","o3fkxpcCBskJ")).
pos(eqo("conf/vldb/Ogawa96","my4BalOLmAsJ")).
pos(eqo("conf/vldb/OoiYTJ01","RFEE_MNM8IUJ")).
pos(eqo("conf/vldb/Orenstein98","VfWJDzGt9JYJ")).
pos(eqo("conf/vldb/OuzzaniAB94","CgoUJ7DogcwJ")).
pos(eqo("conf/vldb/OuzzaniAB94","kZaX18AOqfQJ")).
pos(eqo("conf/vldb/OuzzaniAB94","p0TLPzS0K4oJ")).
pos(eqo("conf/vldb/Padmanabhan96","1IjlMvLBFC0J")).
pos(eqo("conf/vldb/PanRAMOHAMV02","F9Fe5NfpK6MJ")).
pos(eqo("conf/vldb/PantiSG00","C7Vuxp5KVsAJ")).
pos(eqo("conf/vldb/PapadiasT01","JtQbB9D7zkwJ")).
pos(eqo("conf/vldb/PappasC00","BsQtFZrn3fsJ")).
pos(eqo("conf/vldb/PappasC00","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671850")).
pos(eqo("conf/vldb/PedersenJD00","bSRLP5_ErFMJ")).
pos(eqo("conf/vldb/PereiraFJLS01","CZTJ00lolvYJ")).
pos(eqo("conf/vldb/PirotteZMY94","8s-SP8sAvQAJ")).
pos(eqo("conf/vldb/PopaVMHF02","kyO1P49ldlEJ")).
pos(eqo("conf/vldb/PopaVMHF02","qJ4lzBFzjdgJ")).
pos(eqo("conf/vldb/PottingerL00","mpnnRdFUUJQJ")).
pos(eqo("conf/vldb/RamanRH99","HQuS5fNPqZYJ")).
pos(eqo("conf/vldb/RamanRH99","QLJhG6Rz2T0J")).
pos(eqo("conf/vldb/Ramanan03","ruVmVa1bhoUJ")).
pos(eqo("conf/vldb/RastogiS98","GDlHdL-s4tIJ")).
pos(eqo("conf/vldb/RastogiS98","gkEOPxIM4GkJ")).
pos(eqo("conf/vldb/RizviH02","2pPdWgF69ZoJ")).
pos(eqo("conf/vldb/RothOH99","OslUAjJi_B4J")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","T2fm7Wb1ak4J")).
pos(eqo("conf/vldb/RysNS96","pwxPfVlOqQUJ")).
pos(eqo("conf/vldb/Sacks-Davis96","GkINzG_IffAJ")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/vldb/SavasereON95","CG-_La4oAYkJ")).
pos(eqo("conf/vldb/SavasereON95","rmfK2zWkuagJ")).
pos(eqo("conf/vldb/SchieferKBLF98","1LATgSt5o_EJ")).
pos(eqo("conf/vldb/Schnase00","OdaRU442nm0J")).
pos(eqo("conf/vldb/SeshadriLR97","o-fZP19Hu2IJ")).
pos(eqo("conf/vldb/ShahRS02","ByAk0yD64SYJ")).
pos(eqo("conf/vldb/ShahRS02","Q3MhG5RK29oJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GIlUG9H3gUUJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","GcedmSsoWusJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","WkdIh9-e2WMJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","iME-SCx_DIgJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","w6I2bU61UDYJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","_bdp5T8SSuoJ")).
pos(eqo("conf/vldb/SheikholeslamiCZ98","Snx8LBMXFJUJ")).
pos(eqo("conf/vldb/SheikholeslamiCZ98","btydMRJMBqoJ")).
pos(eqo("conf/vldb/Shmueli01","JhPPFNFWJ1UJ")).
pos(eqo("conf/vldb/ShuklaDNR96","Qdw5iM0aKwAJ")).
pos(eqo("conf/vldb/ShuklaDNR96","gTSn7nMr9dQJ")).
pos(eqo("conf/vldb/ShuklaDNR96","vnezjPI8jYIJ")).
pos(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
pos(eqo("conf/vldb/Sripada02","UXm0EWCXxpIJ")).
pos(eqo("conf/vldb/StathatosRB97","JH2hiRXPJcEJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","EPtaqugcCyMJ")).
pos(eqo("conf/vldb/SteinbrunnPMK95","k-IlQ6VnmKsJ")).
pos(eqo("conf/vldb/StohrMR00","7fCRAqLTNeUJ")).
pos(eqo("conf/vldb/TanEO01","1A06w64wjvcJ")).
pos(eqo("conf/vldb/TaoPS02","o0WQjRyBQ5kJ")).
pos(eqo("conf/vldb/TengCY03","wJjaZnzD6pAJ")).
pos(eqo("conf/vldb/TianD03","l7glyH7ltuQJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/TsurAADKW01","PvNI0yqRqtQJ")).
pos(eqo("conf/vldb/VassalosP97","jmYHA7e95XAJ")).
pos(eqo("conf/vldb/ViverosNR96","YWG9plUEbigJ")).
pos(eqo("conf/vldb/ViverosNR96","lsY_rXfEDDIJ")).
pos(eqo("conf/vldb/WangYM97","RiOvjzg_MJwJ")).
pos(eqo("conf/vldb/WangYM97","hcYKj7CHbWYJ")).
pos(eqo("conf/vldb/WangYM97","sXn3gsd_5TAJ")).
pos(eqo("conf/vldb/WangYM97","xW3AafG2xKgJ")).
pos(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
pos(eqo("conf/vldb/WangZL99","G4H0wLuSxaIJ")).
pos(eqo("conf/vldb/WeberSB98","6D0Qt6Sjp8cJ")).
pos(eqo("conf/vldb/WeberSB98","K4rzmIbgF_sJ")).
pos(eqo("conf/vldb/WeberSB98","TkaEMuHGE9cJ")).
pos(eqo("conf/vldb/WeberSB98","km3WVXUGhhsJ")).
pos(eqo("conf/vldb/WeikumMHZ02","uNwtCAfL3T4J")).
pos(eqo("conf/vldb/WiesnerK01","UrDwK2S7QVwJ")).
pos(eqo("conf/vldb/WildfogelY97","uqYakLN84x0J")).
pos(eqo("conf/vldb/WuYCT95","uv6nMj7jEggJ")).
pos(eqo("conf/vldb/XieH94","jlnGGhVJ438J")).
pos(eqo("conf/vldb/YagoubFIV00","195Hlqu94qEJ")).
pos(eqo("conf/vldb/YagoubFIV00","oHJaZrizZesJ")).
pos(eqo("conf/vldb/YanL95","JLzIM-AHdW8J")).
pos(eqo("conf/vldb/YuPM03","ZEEZqsnVCyYJ")).
pos(eqo("conf/vldb/ZirintsisKM99","_UYteGcmBKIJ")).
pos(eqo("conf/vldb/ZirintsisKM99","sldCppj0qOEJ")).
pos(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604274%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aberer03a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AilamakiG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AlonsoCIM95","5LlePa4wQmEJ")).
pos(eqo("journals/sigmod/AndersonS94","aDk2IS_xwToJ")).
pos(eqo("journals/sigmod/AnyanwuS02","LoDGuFLlvsAJ")).
pos(eqo("journals/sigmod/ArenasKKKMM03","rl50qPw8UaEJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","yfjKkIhvfXcJ")).
pos(eqo("journals/sigmod/BaaderJN97","SxT807RR-NsJ")).
pos(eqo("journals/sigmod/BaaderJN97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D274461%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarbaraCJW01","asukNMVeZZYJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
pos(eqo("journals/sigmod/BawaCCDGGKMSSVY03","7gJjI63FlyYJ")).
pos(eqo("journals/sigmod/BerndtssonH96","8Dj_i69XP60J")).
pos(eqo("journals/sigmod/BerndtssonH96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381889%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","Syu5W-3uFFAJ")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","oFiEYaenxe4J")).
pos(eqo("journals/sigmod/BorgidaCS98","iPbD7vPHzgYJ")).
pos(eqo("journals/sigmod/BuchnerM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D306124%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BunemanRU97","5qg4BNiroqMJ")).
pos(eqo("journals/sigmod/BunemanRU97","V6CmNS2__nUJ")).
pos(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
pos(eqo("journals/sigmod/CampbellEM03","N9u28V6NZTIJ")).
pos(eqo("journals/sigmod/Camps02","JclQFC-1s18J")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D641006")).
pos(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641006%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187460%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChristoffelPSL98","F7QAoJ5PGekJ")).
pos(eqo("journals/sigmod/CrestaniG02","tyZxVraNgTsJ")).
pos(eqo("journals/sigmod/Danish98","mKZyoPZArGcJ")).
pos(eqo("journals/sigmod/DarwenD95","EXwe9r79qxEJ")).
pos(eqo("journals/sigmod/DarwenD95","Xa_whOlvG7gJ")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","XE1zjDexb64J")).
pos(eqo("journals/sigmod/Eisenberg96","tFbkjO2wcFMJ")).
pos(eqo("journals/sigmod/EisenbergM98a","AatoNnELw78J")).
pos(eqo("journals/sigmod/FreemanG96","RzHjAQK7XTsJ")).
pos(eqo("journals/sigmod/GatziuJSV99","HtqrJuo7GSsJ")).
pos(eqo("journals/sigmod/Hampapur99","I-r1LE1najAJ")).
pos(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
pos(eqo("journals/sigmod/Jarke95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202671%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JenningsNF98","YiZVv5kVDb4J")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","DOW5UL3FQk8J")).
pos(eqo("journals/sigmod/JensenCEGHJ94","NdeiWfmwM00J")).
pos(eqo("journals/sigmod/JensenCEGHJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KappelR98","tbZ0J3HLI18J")).
pos(eqo("journals/sigmod/KarlapalemLS95","B_m0Yp4aycUJ")).
pos(eqo("journals/sigmod/KempsterST99","JfmkT9KvKWoJ")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/KlasS94","bViLh5-jVsAJ")).
pos(eqo("journals/sigmod/KokkotosIPS95","-IvY8_ki_psJ")).
pos(eqo("journals/sigmod/KoksalAD98","c2UQ3AM5_f8J")).
pos(eqo("journals/sigmod/Kosch02","_avm808LQocJ")).
pos(eqo("journals/sigmod/Kuijpers02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601866%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/KuoM96","vmwgqLkw0NUJ")).
pos(eqo("journals/sigmod/LeeCL95","G1E5PwzwdSMJ")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltonE02","6uelfg3RgEoJ")).
pos(eqo("journals/sigmod/MeltonMJKS02","cvBAdEvcTSkJ")).
pos(eqo("journals/sigmod/NascimentoSP03","G3QWq2T08SEJ")).
pos(eqo("journals/sigmod/NorrieBSW94","q6YVJJgD1uQJ")).
pos(eqo("journals/sigmod/PapianiWDN99","EHBFbc1r9oIJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","F7AdjoH_uTcJ")).
pos(eqo("journals/sigmod/PitouraAPSV03","hn2MANNgz9sJ")).
pos(eqo("journals/sigmod/PitouraAPSV03","jKxELUmoSkEJ")).
pos(eqo("journals/sigmod/RoddickABDEGHLMMMW00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344789%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Seshadri98","XijyPb231fAJ")).
pos(eqo("journals/sigmod/SilberschatzZ97","7JRwRy6VapMJ")).
pos(eqo("journals/sigmod/SilberschatzZ97","7ne6Kriy0mEJ")).
pos(eqo("journals/sigmod/Snodgrass02b","KENWBobILMwJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","vUONDuuNNCQJ")).
pos(eqo("journals/sigmod/SouzaS99","OmYc0wE1j4kJ")).
pos(eqo("journals/sigmod/SouzaS99","lSJVvYYknn0J")).
pos(eqo("journals/sigmod/TanakaV01","sQu8znidi50J")).
pos(eqo("journals/sigmod/TsotrasJS98","f3-E7x12K4gJ")).
pos(eqo("journals/sigmod/TsotrasK96","-FGfZQ_8TxIJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/UlusoyB96","LclVYrb7vJoJ")).
pos(eqo("journals/sigmod/VenkatraoP95","qk3LVAuS2SUJ")).
pos(eqo("journals/sigmod/Wade96","AYtrcxExrbkJ")).
pos(eqo("journals/sigmod/Wu02","zCrDiwnKRHIJ")).
pos(eqo("journals/tods/BrightHP94","m9DBN5PHWDAJ")).
pos(eqo("journals/tods/CastanoAFP98","X7wtR1g63qEJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","Cy8VDlIamc8J")).
pos(eqo("journals/tods/FranklinCL97","-iaSLKFHwUkJ")).
pos(eqo("journals/tods/GraefeC95","Bn8s7u5T9SAJ")).
pos(eqo("journals/tods/KossmannS00","PnGVbzQCWY0J")).
pos(eqo("journals/tods/LeveneL99","iwPgaJ1eQrkJ")).
pos(eqo("journals/tods/MamoulisP01","Rg8V7NSK9tMJ")).
pos(eqo("journals/tods/MehrotraRKS98","tAnONC5J2W8J")).
pos(eqo("journals/tods/MokNE96","xUeP4X8k5SoJ")).
pos(eqo("journals/tods/Suciu02","Y7kHpHu3nP0J")).
pos(eqo("journals/tods/WijesekeraJPH03","oui-frSWZCAJ")).
pos(eqo("journals/tods/WinslettSQ94","lvZTVlP7s7oJ")).
pos(eqo("journals/tods/WinslettSQ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D195675%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/WolfsonJH97","lcqKNOEczxsJ")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/vldb/AbiteboulCM98","WzT3S2G1FjcJ")).
pos(eqo("journals/vldb/CasatiSG01","347oyb_b7DAJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","3mVAyjsRXiwJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","PTmCbogNUpAJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","Sd2EpYgsgYEJ")).
pos(eqo("journals/vldb/ChakrabartiRS03","idfox84uNHUJ")).
pos(eqo("journals/vldb/ChanGR03","7rn7AHVs1YUJ")).
pos(eqo("journals/vldb/ChangG01","hYu2nw263UoJ")).
pos(eqo("journals/vldb/ChenHY97","IWZsSVPC6HMJ")).
pos(eqo("journals/vldb/ChienTZ02","j4wcclZqY0oJ")).
pos(eqo("journals/vldb/FengYLH02","Uxh3R2hfBOAJ")).
pos(eqo("journals/vldb/GutingS95","A4lUwOD7AeYJ")).
pos(eqo("journals/vldb/GutingS95","CBHicx5w3ocJ")).
pos(eqo("journals/vldb/GutingS95","x02_XqK_fGMJ")).
pos(eqo("journals/vldb/LometS97","qjLiaKLJ6eQJ")).
pos(eqo("journals/vldb/MedjahedBBNE03","18FFG2HC51oJ")).
pos(eqo("journals/vldb/MedjahedBBNE03","Jml6flDOu7QJ")).
pos(eqo("journals/vldb/MedjahedBE03","M0FH31YCEU0J")).
pos(eqo("journals/vldb/MedjahedBE03","YqXx_xeZE2gJ")).
pos(eqo("journals/vldb/NanopoulosM02","icoWjIZ_6IIJ")).
pos(eqo("journals/vldb/NybergBCGL95","RhKSGU-DhQUJ")).
pos(eqo("journals/vldb/PeckhamMD95","zOfVTNgEwz0J")).
pos(eqo("journals/vldb/PucheralBVB01","8DRB_dYz2CgJ")).
pos(eqo("journals/vldb/PucheralBVB01","K9Qbh3haBCMJ")).
pos(eqo("journals/vldb/PucheralBVB01","hNOti13KB_8J")).
pos(eqo("journals/vldb/SaltenisJ02","HSEOZDaC8ZUJ")).
pos(eqo("journals/vldb/ShethTP03","tReKvTMB7pcJ")).
pos(eqo("journals/vldb/ShyyASL96","cZ5JZQyhb1MJ")).
pos(eqo("journals/vldb/SwamiS95","S6TmnZKgmxwJ")).
pos(eqo("journals/vldb/TanGO00","url:http://www.springerlink.com/index/4N8LT3XHXGCR8DLW.pdf")).
pos(eqo("journals/vldb/TenienteO95","Y7ICKU_J4WsJ")).
