neg(eqo("conf/sigmod/AcharyaFZ97","To_EjIKwfSAJ")).
neg(eqo("conf/sigmod/AcharyaGPR99","EpUtXEhwDaUJ")).
neg(eqo("conf/sigmod/AdaliSS99","fZ0pM8XvHWYJ")).
neg(eqo("conf/sigmod/Adelberg98","dpaaxBauFS0J")).
neg(eqo("conf/sigmod/AfratiLU01","wCvjgB90JJsJ")).
neg(eqo("conf/sigmod/Aggarwal02","QkTd5WogN-AJ")).
neg(eqo("conf/sigmod/AggarwalWY99","P5oJUiow7lsJ")).
neg(eqo("conf/sigmod/AgrawalK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D141401%26type%3Dpdf")).
neg(eqo("conf/sigmod/AgrawalS00","uGXRy7xmoIYJ")).
neg(eqo("conf/sigmod/AgrawalS00","ufPUBsN4eg0J")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D1269671")).
neg(eqo("conf/sigmod/ArasuG03","5FJjEO5B31AJ")).
neg(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
neg(eqo("conf/sigmod/AtzeniT97","oUOuTMrB0esJ")).
neg(eqo("conf/sigmod/BarbaraI94","bMUUwjP72hwJ")).
neg(eqo("conf/sigmod/BarclaySG00","nLbW09uNfmsJ")).
neg(eqo("conf/sigmod/BerchtoldBBKK97","Ymx00_iKLR4J")).
neg(eqo("conf/sigmod/BerchtoldK97","nM9bJESsWNoJ")).
neg(eqo("conf/sigmod/BertinoCF01","9GEqG82yca4J")).
neg(eqo("conf/sigmod/BeyerR99","2kHUkb0x3C0J")).
neg(eqo("conf/sigmod/Bierman03","8-V5f3h85YwJ")).
neg(eqo("conf/sigmod/BilirisFOP96","01ZVDudF4WAJ")).
neg(eqo("conf/sigmod/BohmBKK01","BIxlUx2y38AJ")).
neg(eqo("conf/sigmod/BornhovdAKMPR03","7lPu8hBgKksJ")).
neg(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
neg(eqo("conf/sigmod/BrunoC02","f5cqkpUXl0kJ")).
neg(eqo("conf/sigmod/Cabrera03","46myxoqwDLwJ")).
neg(eqo("conf/sigmod/CallanCD99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083786%26type%3Dpdf")).
neg(eqo("conf/sigmod/ChakrabartiM99","CLD080j61G8J")).
neg(eqo("conf/sigmod/ChangBCLLS00","5qg4BNiroqMJ")).
neg(eqo("conf/sigmod/ChangG99","4tGGVDHTmGEJ")).
neg(eqo("conf/sigmod/Chaudhuri97","97o0rfRHu9MJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","99oqRZGWAYMJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","Tagq11E6HfAJ")).
neg(eqo("conf/sigmod/ChaudhuriDN01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ChaudhuriMN99","gq-LxEeXCnUJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","p6zcWuHfGd0J")).
neg(eqo("conf/sigmod/ChaudhuriN98a","JyEX0YVMP5oJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","Xud-KgE4stEJ")).
neg(eqo("conf/sigmod/ChenDLT00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.336560")).
neg(eqo("conf/sigmod/ChenJDTW00","QE2m-MkYUIsJ")).
neg(eqo("conf/sigmod/CherniackZ96","So_H9Oer6lsJ")).
neg(eqo("conf/sigmod/CherniackZ98","7DFhNMAE13QJ")).
neg(eqo("conf/sigmod/Cohen98","e0GH54HirssJ")).
neg(eqo("conf/sigmod/Cohen98a","FyaDdmU186MJ")).
neg(eqo("conf/sigmod/Cohen98a","qfD_kxYt-dsJ")).
neg(eqo("conf/sigmod/CohenM03","uLGZJiB9AiAJ")).
neg(eqo("conf/sigmod/ColbyGLMT96","RlH2shMtkfwJ")).
neg(eqo("conf/sigmod/ConsensM94","X8aW3tR7uPYJ")).
neg(eqo("conf/sigmod/CookWZ94","SrCBkHnIFL8J")).
neg(eqo("conf/sigmod/CookWZ94","eKF1zVNKP0gJ")).
neg(eqo("conf/sigmod/DeligiannakisR03","3Ozte0ucNJAJ")).
neg(eqo("conf/sigmod/Deutsch95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223880")).
neg(eqo("conf/sigmod/DobraGGR02","qf4764Q6M6YJ")).
neg(eqo("conf/sigmod/Englert94","KOpz_NXJ3WUJ")).
neg(eqo("conf/sigmod/Englert94","bbWXEbBUueYJ")).
neg(eqo("conf/sigmod/FaloutsosSTT00","-MNdDpWC-sgJ")).
neg(eqo("conf/sigmod/FaloutsosSTT00","5lhdwbt8HX0J")).
neg(eqo("conf/sigmod/FegarasSRM00","4_4Jg_EQ8EkJ")).
neg(eqo("conf/sigmod/FernandezFKLS98","Qx9xzKpLhiMJ")).
neg(eqo("conf/sigmod/FernandezFKLS98","ek26aiEheesJ")).
neg(eqo("conf/sigmod/GarofalakisI96","-cCndG3a8ukJ")).
neg(eqo("conf/sigmod/GebhardtJJ97","ks4Wxa8dHNIJ")).
neg(eqo("conf/sigmod/Gerber95","FwllK-CnWZ0J")).
neg(eqo("conf/sigmod/GorelikWD94","1QvhrpZ7KBgJ")).
neg(eqo("conf/sigmod/GraySEBW94","VFV6o8xMlnIJ")).
neg(eqo("conf/sigmod/GraySSU03","FmyDV5eTnvsJ")).
neg(eqo("conf/sigmod/GreenwaldK01","HLqmreti7SQJ")).
neg(eqo("conf/sigmod/GriffinH97","6QZGeKna5lgJ")).
neg(eqo("conf/sigmod/GriffinH97","I6UI3qWKdAsJ")).
neg(eqo("conf/sigmod/GrossmanQ94","CTvc34ghAtkJ")).
neg(eqo("conf/sigmod/GrossmanQ94","url:http://portal.acm.org/citation.cfm%3Fid%3D192661")).
neg(eqo("conf/sigmod/GuhaRS98","Dux-7sONElwJ")).
neg(eqo("conf/sigmod/GuhaRS98","WHHfHdG_ougJ")).
neg(eqo("conf/sigmod/GuhaRS98","dV7p-cfTjUQJ")).
neg(eqo("conf/sigmod/Han96","EWdjCIv1enwJ")).
neg(eqo("conf/sigmod/HanFHCC94","6M-fnuhWEOIJ")).
neg(eqo("conf/sigmod/HanPY00","XFn7qNtlSvAJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","t4JoRwvUNZoJ")).
neg(eqo("conf/sigmod/Hellerstein94","131hiUdWYSQJ")).
neg(eqo("conf/sigmod/HellersteinN96","Ikk1rb4o66UJ")).
neg(eqo("conf/sigmod/HillyerS96","N9NdxNRvMMkJ")).
neg(eqo("conf/sigmod/HinneburgK99","V3cZfG1Poo4J")).
neg(eqo("conf/sigmod/HinneburgK99","VWd7jhLXfV0J")).
neg(eqo("conf/sigmod/HjaltasonS98","3mwWUz_ORNYJ")).
neg(eqo("conf/sigmod/HsiaoN00","f-BMhdW_E6UJ")).
neg(eqo("conf/sigmod/IoannidisL94","dDHNsS9sisEJ")).
neg(eqo("conf/sigmod/JohnsonD03","5OYgUpRggiMJ")).
neg(eqo("conf/sigmod/JohnsonD03","z1YR8jZV7YkJ")).
neg(eqo("conf/sigmod/KatayamaS97","PCFJuVxYxtwJ")).
neg(eqo("conf/sigmod/KatayamaS97","cF4jzvngOVgJ")).
neg(eqo("conf/sigmod/Keim96","uypnc5Gb9iIJ")).
neg(eqo("conf/sigmod/KiesslingHFE01","Y1HVgTopekIJ")).
neg(eqo("conf/sigmod/Kim94","930Uth7EArkJ")).
neg(eqo("conf/sigmod/KimCK01","FJbf43XXF_UJ")).
neg(eqo("conf/sigmod/Kohler99","BmJKyK7NlOoJ")).
neg(eqo("conf/sigmod/KornJF97","2CVKpInvzusJ")).
neg(eqo("conf/sigmod/KornJF97","TT5lSHZcN4IJ")).
neg(eqo("conf/sigmod/KornJF97","b9GtXCCfowsJ")).
neg(eqo("conf/sigmod/KornM00","6VAQeD6muakJ")).
neg(eqo("conf/sigmod/KornackerSH98","bV8_CDuW2gMJ")).
neg(eqo("conf/sigmod/Kramer97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/KriegelMPS01","zSoTbEtLuqEJ")).
neg(eqo("conf/sigmod/LabioWGG00","iXkSngvyu08J")).
neg(eqo("conf/sigmod/Larson01","IrTKBa0mgEsJ")).
neg(eqo("conf/sigmod/Larson01","QmBz3hMOFh4J")).
neg(eqo("conf/sigmod/LeeKC99","c-5n9qQKLaEJ")).
neg(eqo("conf/sigmod/LeflerSW96","4b12cZc8QK4J")).
neg(eqo("conf/sigmod/Levine95","BXB96UFPHn8J")).
neg(eqo("conf/sigmod/LibkinMW96","dGbuUkhWNhMJ")).
neg(eqo("conf/sigmod/LitwinS00","KOpz_NXJ3WUJ")).
neg(eqo("conf/sigmod/LiuHBPT99","QFeUfn2QS5EJ")).
neg(eqo("conf/sigmod/LiuPBHPT00","H9bMRYKnXMQJ")).
neg(eqo("conf/sigmod/LiuPBHPT00","ilVNunYZ04sJ")).
neg(eqo("conf/sigmod/Lomet00","wJTN8d8md7oJ")).
neg(eqo("conf/sigmod/LuWYBLY02","C9imFvgrSvAJ")).
neg(eqo("conf/sigmod/MaddenH02","HdyClBmT7BoJ")).
neg(eqo("conf/sigmod/Maguire01","3eSwRxf3-3sJ")).
neg(eqo("conf/sigmod/MaheshwariL97","zth-25wD1b8J")).
neg(eqo("conf/sigmod/MassariPSC95","ywQwkD1ov7IJ")).
neg(eqo("conf/sigmod/MattosM95","EB8OpXv-PXUJ")).
neg(eqo("conf/sigmod/MattosM95","ZHT0Ufwg038J")).
neg(eqo("conf/sigmod/MinPC03","WFmae47kgN4J")).
neg(eqo("conf/sigmod/Mohan94","XppwYYxOpksJ")).
neg(eqo("conf/sigmod/MohanN94","VT0oJBgVFosJ")).
neg(eqo("conf/sigmod/MumickP94","z64xI0F_eZQJ")).
neg(eqo("conf/sigmod/NgLK98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D163092%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/NgLK98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D369291%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/OhHP00","kj7_0qQq_48J")).
neg(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
neg(eqo("conf/sigmod/OlstonW02","DHnbaUmZMXsJ")).
neg(eqo("conf/sigmod/OoiTZGLLLNSWZ03","rPFgPOAANuQJ")).
neg(eqo("conf/sigmod/ParkCY95","7fegm0jsd4IJ")).
neg(eqo("conf/sigmod/PhanN02","pTTTsrWGBvQJ")).
neg(eqo("conf/sigmod/PonnekantiK00","url:http://portal.acm.org/citation.cfm%3Fid%3D335191.335494%26dl%3DGUIDE%26dl%3DACM%26idx%3D335191%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","xnNIRajBihoJ")).
neg(eqo("conf/sigmod/RaoR98","WlSXiMaxGlQJ")).
neg(eqo("conf/sigmod/ReveszCKLLW00","QMNReKSpAPYJ")).
neg(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959087%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RossSS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130872%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RoySSB00","ORkxHLb7dvcJ")).
neg(eqo("conf/sigmod/RundensteinerWYD02","YOkKQGPzKgcJ")).
neg(eqo("conf/sigmod/SeshadriP97","N9NdxNRvMMkJ")).
neg(eqo("conf/sigmod/ShahC01","OuUUuk369jQJ")).
neg(eqo("conf/sigmod/ShashaB02","m7ksiYu5pi4J")).
neg(eqo("conf/sigmod/ShashaB02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245885%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ShenoyHSBBS00","SipDBj3SOb4J")).
neg(eqo("conf/sigmod/SlivinskasJS01","oAVbM_vepr8J")).
neg(eqo("conf/sigmod/SrikantA96","ZcsYVbukXTsJ")).
neg(eqo("conf/sigmod/Stonebraker03","9VQXJ5C5lsYJ")).
neg(eqo("conf/sigmod/Stonebraker98","LMo4h0gdnKoJ")).
neg(eqo("conf/sigmod/Suciu99","NhC1d3X7bl0J")).
neg(eqo("conf/sigmod/Team99","kszqw3ST4rAJ")).
neg(eqo("conf/sigmod/Toyama98","vUvNBChnmacJ")).
neg(eqo("conf/sigmod/TsurUACMNR98","ij8LH1U0bgQJ")).
neg(eqo("conf/sigmod/Ullman03","UTe8b9IiclUJ")).
neg(eqo("conf/sigmod/VanceM96","CMMaMlYwgPkJ")).
neg(eqo("conf/sigmod/Vaskevitch94","OzgnxugGCWMJ")).
neg(eqo("conf/sigmod/ViglasN02","b5TqRnEMMGkJ")).
neg(eqo("conf/sigmod/WaasG00","url:http://www.ingentaconnect.com/content/els/09505849/2000/00000042/00000007/art00103")).
neg(eqo("conf/sigmod/WangJLY03","RiOvjzg_MJwJ")).
neg(eqo("conf/sigmod/Weininger00","url:http://portal.acm.org/citation.cfm%3Fid%3D335465")).
neg(eqo("conf/sigmod/Weininger02","WbsAK4ZE17YJ")).
neg(eqo("conf/sigmod/WitkowskiBBDFGSS03","PwLOEpwyyDwJ")).
neg(eqo("conf/sigmod/WynblattN01","UWeF9RvOhwkJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","WJPZUaY6IxoJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","5c8VicTjai4J")).
neg(eqo("conf/vldb/AgarwalADGNRS96","E4fU9kpfXQsJ")).
neg(eqo("conf/vldb/AgrawalK02","2Z_X3zsf4CoJ")).
neg(eqo("conf/vldb/AgrawalKSX02","P0age7qyZacJ")).
neg(eqo("conf/vldb/AgrawalKSX02","TmXE_bpkL98J")).
neg(eqo("conf/vldb/AgrawalLSS95","Zbv89s2eSnwJ")).
neg(eqo("conf/vldb/AgrawalS94","DLymXxpy2qYJ")).
neg(eqo("conf/vldb/AgrawalSX02","JV8yJIRlYcUJ")).
neg(eqo("conf/vldb/Amer-YahiaFSX03","iubeta9kU6AJ")).
neg(eqo("conf/vldb/AndreiV01","YiJojduGXXkJ")).
neg(eqo("conf/vldb/AnkerstBKS98","K1ZdQsRoNloJ")).
neg(eqo("conf/vldb/ArgePRSV98","KIL883gYkCcJ")).
neg(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
neg(eqo("conf/vldb/BaralisPT97","tyNO4U-fmrIJ")).
neg(eqo("conf/vldb/Baumann03","Q28u7TpTgI0J")).
neg(eqo("conf/vldb/BawaBA03","6mbu5T69NFEJ")).
neg(eqo("conf/vldb/Bayer95","_IHfyZ9tY0wJ")).
neg(eqo("conf/vldb/BerchtoldKK96","2sWwPk5uNKwJ")).
neg(eqo("conf/vldb/BerckenS01","fRo4fx_Q6gIJ")).
neg(eqo("conf/vldb/Bernstein94","5lFmSD-p-jEJ")).
neg(eqo("conf/vldb/BettiniJWW02","tFuA828CptUJ")).
neg(eqo("conf/vldb/BhattacharjeePMLCH03","htMO0uWGzvoJ")).
neg(eqo("conf/vldb/BonifatiCDS01","rZ2_UFZ4ALoJ")).
neg(eqo("conf/vldb/Brin95","_BpijjBtOkgJ")).
neg(eqo("conf/vldb/BrownG01","Fh3lch5AGEUJ")).
neg(eqo("conf/vldb/Carey00","0iiNS8BIbsUJ")).
neg(eqo("conf/vldb/CareyCNVDRSM99","JpMllVmmnkAJ")).
neg(eqo("conf/vldb/CarinoJ98","GIlUG9H3gUUJ")).
neg(eqo("conf/vldb/CarinoOBS99","eEiaTP9KCMwJ")).
neg(eqo("conf/vldb/ChaHKK01","zkovTILW6QkJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","2LdUbNy0hWwJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","MSWcLmCvEO4J")).
neg(eqo("conf/vldb/ChakrabartiM00","f1h0J1_ELisJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","xhle0bk7qsMJ")).
neg(eqo("conf/vldb/ChakrabartiSD98","zJ6gN0riEsQJ")).
neg(eqo("conf/vldb/ChakravarthyKAK94","XL_tG38DUJQJ")).
neg(eqo("conf/vldb/ChandrasekaranF02","8p0ad6wEQcEJ")).
neg(eqo("conf/vldb/ChangG00","rcSfDxBif40J")).
neg(eqo("conf/vldb/ChenHWW02","kgXRJZKRxZQJ")).
neg(eqo("conf/vldb/ChenRS95","-McZOyw__qQJ")).
neg(eqo("conf/vldb/ChengGKLLQS99","UzI57qu_ztwJ")).
neg(eqo("conf/vldb/CherniackZ98","SU9-zg4pdt8J")).
neg(eqo("conf/vldb/ChienVZTZ02","SgUc7R0GR6QJ")).
neg(eqo("conf/vldb/ChienVZTZ02","uUmeAkW_FFUJ")).
neg(eqo("conf/vldb/CiacciaPZ97","lG_CPUQrdxsJ")).
neg(eqo("conf/vldb/CooperSFHS01","uTTqPSoH_YgJ")).
neg(eqo("conf/vldb/DagevilleZ02","B1uNI67mfJcJ")).
neg(eqo("conf/vldb/Dayal99","OoknnZ3rbfwJ")).
neg(eqo("conf/vldb/DeRose99","wYjcw9dg5lIJ")).
neg(eqo("conf/vldb/EicklerKK97","prk9WMC8mgAJ")).
neg(eqo("conf/vldb/EsterKSWX98","CzVyfZe-kj0J")).
neg(eqo("conf/vldb/FaloutsosJS97","rWiBJ-IBcDsJ")).
neg(eqo("conf/vldb/FaloutsosMS96","MxkjWOlLhlYJ")).
neg(eqo("conf/vldb/FaloutsosMS96","s-BT0x6h2qUJ")).
neg(eqo("conf/vldb/FegarasE01","pinPEM3Rvm0J")).
neg(eqo("conf/vldb/FernandezSCMS03","DdsknXBlL3UJ")).
neg(eqo("conf/vldb/FernandezSCMS03","piVAR0_E0IEJ")).
neg(eqo("conf/vldb/FlorescuHKLRWCSA03","EmoELruF2scJ")).
neg(eqo("conf/vldb/FlorescuLSY99","9VvN0Pfp3woJ")).
neg(eqo("conf/vldb/FlorescuLSY99","DfOLEzMoEaEJ")).
neg(eqo("conf/vldb/FlorescuLSY99","UxA-jW1jlnoJ")).
neg(eqo("conf/vldb/GaasterlandL94","url:http://www.springerlink.com/index/H0488Q1WR73X4L80.pdf")).
neg(eqo("conf/vldb/GarciaLL98","5MO7a6e0-GQJ")).
neg(eqo("conf/vldb/GarofalakisOS97","Xm3ygCvkmN8J")).
neg(eqo("conf/vldb/GarofalakisOS97","dW_pRNemQfsJ")).
neg(eqo("conf/vldb/Gentili01","OZFZwSFb0TkJ")).
neg(eqo("conf/vldb/GionisIM99","oedVPUUsKEQJ")).
neg(eqo("conf/vldb/HasanM94","csipTqN6VZQJ")).
neg(eqo("conf/vldb/HeymannTKWRMF02","EAZ5Gz22bIUJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","QfqykiFRwyYJ")).
neg(eqo("conf/vldb/HvasshovdBT00","rqS9AFJFBlsJ")).
neg(eqo("conf/vldb/IlyasAE02","VSB1dhe6zOYJ")).
neg(eqo("conf/vldb/IpeirotisG02","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/IshikawaSF98","V3c_ivUAs34J")).
neg(eqo("conf/vldb/IwerksSS03","TcSLnozhpgkJ")).
neg(eqo("conf/vldb/IyerW94","_RyWKB28b6oJ")).
neg(eqo("conf/vldb/JagadishLS99","tdqKRRf9ytUJ")).
neg(eqo("conf/vldb/JarkeKL00","LAvs6Oe0ygMJ")).
neg(eqo("conf/vldb/Johnson99","nc8zcSajWKkJ")).
neg(eqo("conf/vldb/JosifovskiR99","dORkkFWNFUUJ")).
neg(eqo("conf/vldb/KalusD95","g7HDbO4GCN4J")).
neg(eqo("conf/vldb/KangC02","NiP5L8NfLrcJ")).
neg(eqo("conf/vldb/KarayannidisTSPMRFEB02","8FwTno3QyAoJ")).
neg(eqo("conf/vldb/Keogh02","iFJwVZqHRCwJ")).
neg(eqo("conf/vldb/KilgerM94","R0xUZUxSGmwJ")).
neg(eqo("conf/vldb/KonigW99","c-VaonA7Z7EJ")).
neg(eqo("conf/vldb/KornLKF98","h4AUUfPAGz8J")).
neg(eqo("conf/vldb/KounevB02","tN97O2TH4b0J")).
neg(eqo("conf/vldb/KraissW97","MdwM2JqbNgUJ")).
neg(eqo("conf/vldb/LabioG96","axQOpycfxqQJ")).
neg(eqo("conf/vldb/LabrinidisR01","j7MecwDe3MYJ")).
neg(eqo("conf/vldb/LabrinidisR03","DKUouEkK_b4J")).
neg(eqo("conf/vldb/LevySSZ94","fCOITsrY8I4J")).
neg(eqo("conf/vldb/LiM01","yXnK2wPwLzkJ")).
neg(eqo("conf/vldb/LinLYZ03","zR8IMPIrrYAJ")).
neg(eqo("conf/vldb/LuoNEW03","JqdsmEPoDacJ")).
neg(eqo("conf/vldb/MalonM97","FFMZknx6GBoJ")).
neg(eqo("conf/vldb/ManolescuFK01","_7GYrw1HJlYJ")).
neg(eqo("conf/vldb/ManolescuFKXO00","PP4jpqdyYWgJ")).
neg(eqo("conf/vldb/MarronL01","a3aecJJ58NIJ")).
neg(eqo("conf/vldb/MarronL01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373684%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/MeccaCM01","E02lExYdRYwJ")).
neg(eqo("conf/vldb/MehtaD95","lRiSWgNjNtIJ")).
neg(eqo("conf/vldb/MignetMAC01","VaDXNMtPZ4oJ")).
neg(eqo("conf/vldb/MiloZ98","EsxIZrdYYGYJ")).
neg(eqo("conf/vldb/Mina98","pVsFKVZNgD4J")).
neg(eqo("conf/vldb/Mohan02a","x5Po0pdoKcQJ")).
neg(eqo("conf/vldb/Mohan96","ZEh9UFMj3-EJ")).
neg(eqo("conf/vldb/MorimotoIM97","j8KDWCTJN7AJ")).
neg(eqo("conf/vldb/MoserKK95","tCmECmVF2lIJ")).
neg(eqo("conf/vldb/NaumannLF99","c1uGCkJXMs8J")).
neg(eqo("conf/vldb/Nori00","DmGBKpaiyGEJ")).
neg(eqo("conf/vldb/OConnellWG01","xgK6t4_WoNwJ")).
neg(eqo("conf/vldb/Orenstein98","BaY5_PAatAQJ")).
neg(eqo("conf/vldb/Orenstein98","M-b0kaZFbiQJ")).
neg(eqo("conf/vldb/Padmanabhan96","MqDNCsx8TYkJ")).
neg(eqo("conf/vldb/PapadiasZMT03","JKdP9nJlez8J")).
neg(eqo("conf/vldb/PatonG01","mHCrMuxQnBsJ")).
neg(eqo("conf/vldb/PereiraFJLS01","NDTjtWuhzbQJ")).
neg(eqo("conf/vldb/Pound99","QUBHka6wMH8J")).
neg(eqo("conf/vldb/RamanRH99","x-QdTszm6l4J")).
neg(eqo("conf/vldb/RantzauCHM02","793XPMTdcBEJ")).
neg(eqo("conf/vldb/RaoR99","N8XkcmIO0ysJ")).
neg(eqo("conf/vldb/RisheYACLMVSV00","X-m9DFH7PvsJ")).
neg(eqo("conf/vldb/Sarawagi95","QVmWvrI3myQJ")).
neg(eqo("conf/vldb/ScheuermannSV96","kxebBNLKWl4J")).
neg(eqo("conf/vldb/ScheuermannSV96","u0156H5pB9gJ")).
neg(eqo("conf/vldb/Schoning03","HEJ1Z4Q_xXMJ")).
neg(eqo("conf/vldb/ShahDR03","CG-_La4oAYkJ")).
neg(eqo("conf/vldb/ShanmugasundaramSBCLPR00","drPFy869PjUJ")).
neg(eqo("conf/vldb/Shaw98","HdvwCpWzB4YJ")).
neg(eqo("conf/vldb/Shenker03","IaGkRwoDY2sJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","e5SJ3zgdwgEJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","jWZkmgGziVoJ")).
neg(eqo("conf/vldb/ShiSZ03","2KYx0g-05UcJ")).
neg(eqo("conf/vldb/SilversteinBMU98","-tbXaORoThUJ")).
neg(eqo("conf/vldb/SilversteinBMU98","02mWIBvIsVwJ")).
neg(eqo("conf/vldb/SizovGT03","W80_hO4TTCYJ")).
neg(eqo("conf/vldb/Sondag01","U09WdB3GIK4J")).
neg(eqo("conf/vldb/SrikantA95","Ve-JH2yNN0kJ")).
neg(eqo("conf/vldb/SrikantA95","fIcZeXoZ4bIJ")).
neg(eqo("conf/vldb/Sripada02","8FyI8g1x6gQJ")).
neg(eqo("conf/vldb/SripadaW94","GM-rQKHqbHwJ")).
neg(eqo("conf/vldb/StathatosRB97","qjl6LeTJRroJ")).
neg(eqo("conf/vldb/StaudtJ96","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/SteenhagenABB94","Xr2RguUzt-gJ")).
neg(eqo("conf/vldb/Sterling98","LlP2Fn3bzUMJ")).
neg(eqo("conf/vldb/StolteA02","44IiDc-laTUJ")).
neg(eqo("conf/vldb/Suciu96","Y7kHpHu3nP0J")).
neg(eqo("conf/vldb/SundaraHCAS01","1KckBFVfgyMJ")).
neg(eqo("conf/vldb/Taylor00","5HHRNLsy0sAJ")).
neg(eqo("conf/vldb/Taylor00","zmfryq7n7EwJ")).
neg(eqo("conf/vldb/Tygar98","mlNoe-1jmygJ")).
neg(eqo("conf/vldb/VelegrakisMP03","tYCCI2DndboJ")).
neg(eqo("conf/vldb/VermeerA96","url:http://doi.wiley.com/10.1002/he.172")).
neg(eqo("conf/vldb/Wadler01","Q_xa40BC5mIJ")).
neg(eqo("conf/vldb/WangZL99","csgD6L3ktD8J")).
neg(eqo("conf/vldb/WienerN94","UPnLXp9wPKUJ")).
neg(eqo("conf/vldb/X00a","2ldp3J-x0ioJ")).
neg(eqo("conf/vldb/YanG95","UkIG8p5eCSsJ")).
neg(eqo("conf/vldb/YuAA03","iRJV85kKVgwJ")).
neg(eqo("conf/vldb/ZhuS02","QZs7L6Y94_UJ")).
neg(eqo("journals/sigmod/Aberer01","hBrgosYDi3oJ")).
neg(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02b","BSlaDX5r0HQJ")).
neg(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03d","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603869%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AdelbergKG96","GfiQygac5twJ")).
neg(eqo("journals/sigmod/Aggarwal01","d2-sWScqaywJ")).
neg(eqo("journals/sigmod/Ahlberg96","XpKpYTKUL6IJ")).
neg(eqo("journals/sigmod/AilamakiFFSV03","url:http://doi.wiley.com/10.1002/ace.113")).
neg(eqo("journals/sigmod/AnyanwuS02","tA1HEgZGgrsJ")).
neg(eqo("journals/sigmod/ArpinarD00","YQQMvRraFBwJ")).
neg(eqo("journals/sigmod/AtzeniMM97","sARbiNQPPWQJ")).
neg(eqo("journals/sigmod/BarbaraBFLS94","egvBPvtoaMMJ")).
neg(eqo("journals/sigmod/BargaL02","yXiRu4XZIBAJ")).
neg(eqo("journals/sigmod/BawaCCDGGKMSSVY03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107503%26type%3Dpdf")).
neg(eqo("journals/sigmod/BawaCCDGGKMSSVY03","v1aol6mmLdMJ")).
neg(eqo("journals/sigmod/BergamaschiCV99","tp1_LRYeLcwJ")).
neg(eqo("journals/sigmod/BergamaschiCV99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BerraNT95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202670%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BerzalM02","ALk7huiKjWAJ")).
neg(eqo("journals/sigmod/BilirisP96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1053425")).
neg(eqo("journals/sigmod/Bohlen95","BIox2W-EPfEJ")).
neg(eqo("journals/sigmod/BoucelmaCGJLL02","NiP5L8NfLrcJ")).
neg(eqo("journals/sigmod/Bussler02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564801%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Cetintemel01","CAKcsKXFoCoJ")).
neg(eqo("journals/sigmod/ChangGKRS98","u2jFZnoPLM8J")).
neg(eqo("journals/sigmod/CherniakV03","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/ChongFTSYKDJJ03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219766%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ClementiniF00","f8tissaJVi8J")).
neg(eqo("journals/sigmod/DarwenD95","4lSYHV6XUkQJ")).
neg(eqo("journals/sigmod/Datta94","zJCsqgMH5bUJ")).
neg(eqo("journals/sigmod/DiazJPa94","W6T8UnS2cFUJ")).
neg(eqo("journals/sigmod/Dogac02","url:http://www.springerlink.com/index/H58452Q268H44281.pdf")).
neg(eqo("journals/sigmod/Dogac98","X2sk3f5h6JEJ")).
neg(eqo("journals/sigmod/DomenigD99","bi68bm0miqkJ")).
neg(eqo("journals/sigmod/DongS00","1DQ24XICaxwJ")).
neg(eqo("journals/sigmod/EisenbergM02","AatoNnELw78J")).
neg(eqo("journals/sigmod/EisenbergM02","GKUflKzgAVEJ")).
neg(eqo("journals/sigmod/EnglertGH95","KOpz_NXJ3WUJ")).
neg(eqo("journals/sigmod/Fankhauser01","kozqYxa0b1cJ")).
neg(eqo("journals/sigmod/Finkelstein95","7YMi5qKSe2EJ")).
neg(eqo("journals/sigmod/Franklin00b","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Franklin97b","EHV3m64Jj0cJ")).
neg(eqo("journals/sigmod/Franklin99a","MmgmzLbsqI0J")).
neg(eqo("journals/sigmod/Gardels97","V3LZdq417gsJ")).
neg(eqo("journals/sigmod/GobleR02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507366%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/GolabO03","XCdMiXLp41IJ")).
neg(eqo("journals/sigmod/GottlobKP03","YGzSkYiibuIJ")).
neg(eqo("journals/sigmod/Grohe02","VTKLV-WvOxcJ")).
neg(eqo("journals/sigmod/GroskySF02","8GZyHNOo69EJ")).
neg(eqo("journals/sigmod/GroskySF02","url:http://doi.wiley.com/10.1002/tl.79")).
neg(eqo("journals/sigmod/GuptaHR97","-ha8fD8Kj_oJ")).
neg(eqo("journals/sigmod/HaritsaS96","5Ep0lkiWzmAJ")).
neg(eqo("journals/sigmod/Hoffner03","Sql66UDiVnwJ")).
neg(eqo("journals/sigmod/Ioannidis96","3IEr_j-1YNIJ")).
neg(eqo("journals/sigmod/JaegerF95","Ito_dZR1laQJ")).
neg(eqo("journals/sigmod/JaegerF95","brY-7gB2QUsJ")).
neg(eqo("journals/sigmod/Jannink95","oacFELqmw0cJ")).
neg(eqo("journals/sigmod/Kemper02","jQYEiVS0CIgJ")).
neg(eqo("journals/sigmod/Kim02","q49c-IEX7N8J")).
neg(eqo("journals/sigmod/KimballS95","k4UNrsGeUuAJ")).
neg(eqo("journals/sigmod/KiyokiKH94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D344819%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Konig-RiesL97","t4JoRwvUNZoJ")).
neg(eqo("journals/sigmod/KuanL99","QjaQmETq2j8J")).
neg(eqo("journals/sigmod/KuanL99","lkrtCULVA6oJ")).
neg(eqo("journals/sigmod/LabrinidisM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D603886%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/LaenderRST02","aZa9Vq7sHikJ")).
neg(eqo("journals/sigmod/LeeF01","oUisL_YUScYJ")).
neg(eqo("journals/sigmod/Libkin99a","GugnlR-FHQ0J")).
neg(eqo("journals/sigmod/Liu01","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu01a","uy491GhrFloJ")).
neg(eqo("journals/sigmod/Liu01b","Jab63JLU3N0J")).
neg(eqo("journals/sigmod/Liu01b","url:http://doi.wiley.com/10.1002/ev.1658")).
neg(eqo("journals/sigmod/Liu02b","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu02c","r3hFnyB0LAQJ")).
neg(eqo("journals/sigmod/Liu03a","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Mani03","Cs4K1ZOWRtAJ")).
neg(eqo("journals/sigmod/MaximilienS02","hgjhR8PwNVwJ")).
neg(eqo("journals/sigmod/McHughW97","fFCqy9V5XNgJ")).
neg(eqo("journals/sigmod/MedeirosP94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276355%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/MukhopadhyayGS03","UGuGeLM3cToJ")).
neg(eqo("journals/sigmod/Nascimento03","Vq7f0l22jDUJ")).
neg(eqo("journals/sigmod/Nascimento03","url:http://portal.acm.org/citation.cfm%3Fid%3D776985.776996%26dl%3Dportal%26dl%3DACM%26idx%3D776985%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/OrlandicLS02","vGBA3aJ8EDsJ")).
neg(eqo("journals/sigmod/OukselS99","2Ua-pWTof_YJ")).
neg(eqo("journals/sigmod/OukselS99","yZbJS0Cd6cAJ")).
neg(eqo("journals/sigmod/PitouraAPSV03","zCbDZVfxWhAJ")).
neg(eqo("journals/sigmod/PourabbasR00","z1PBiP8whIQJ")).
neg(eqo("journals/sigmod/PourabbasR02","QyNfyYDySawJ")).
neg(eqo("journals/sigmod/Qian94","ipzkzXB-LcEJ")).
neg(eqo("journals/sigmod/ReichB98","PXeRyZhZvC8J")).
neg(eqo("journals/sigmod/RisheSBDOALOSS95","_OiJpjTV4D0J")).
neg(eqo("journals/sigmod/Ritter98","sfQlMM3SXpAJ")).
neg(eqo("journals/sigmod/RoantreeMH99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RoantreeS02","83jzZgKzLGwJ")).
neg(eqo("journals/sigmod/RoantreeS02","NBlCYs05V_EJ")).
neg(eqo("journals/sigmod/RosenthalS99","TUzhq1PjPsgJ")).
neg(eqo("journals/sigmod/RossCGJBV99","MF-ixFwqMqoJ")).
neg(eqo("journals/sigmod/RossCGJBV99","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/RossFLOSSVW00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/RossHLW01","tOa0zXK5Ba4J")).
neg(eqo("journals/sigmod/RossNO03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D390004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Seshadri98","yXXD9DeXoAgJ")).
neg(eqo("journals/sigmod/Snodgrass00b","bmsONqxQp80J")).
neg(eqo("journals/sigmod/Snodgrass94","SYVDufoTe_IJ")).
neg(eqo("journals/sigmod/Snodgrass99","W6ROObWo3bIJ")).
neg(eqo("journals/sigmod/Stacey95","c2dH5RxNj6kJ")).
neg(eqo("journals/sigmod/StolfoLCFE01","EmwIr5gFFRAJ")).
neg(eqo("journals/sigmod/Suciu01","YwLoGdTgG-sJ")).
neg(eqo("journals/sigmod/Suciu01","hWiIngXs5I0J")).
neg(eqo("journals/sigmod/TianDCZ02","71_-ScDZuHUJ")).
neg(eqo("journals/sigmod/TomasicS97","CkNAY9iebmMJ")).
neg(eqo("journals/sigmod/TsotrasJS98","N0eowMtIAukJ")).
neg(eqo("journals/sigmod/VetterliVS00","51gKshu0CWcJ")).
neg(eqo("journals/sigmod/Winslett02a","ALUZrQuCABQJ")).
neg(eqo("journals/sigmod/Winslett02c","v8INcw15JWcJ")).
neg(eqo("journals/sigmod/Winslett03b","jmLAJ5R_Kc4J")).
neg(eqo("journals/sigmod/WinslettMY03","url:http://portal.acm.org/citation.cfm%3Fid%3D1041410.1041425")).
neg(eqo("journals/sigmod/X94","cJRWis64ghgJ")).
neg(eqo("journals/sigmod/YanG95","tMXkkRDxvkQJ")).
neg(eqo("journals/sigmod/Yang94","8nRpGe6u3XgJ")).
neg(eqo("journals/sigmod/YeungHL94","G0jD1_M5UkEJ")).
neg(eqo("journals/sigmod/Zhang95","CxSOqrhx7iEJ")).
neg(eqo("journals/sigmod/Zhang95","mxuqSQ4rAeEJ")).
neg(eqo("journals/sigmod/Zhang95","uEbdEtnaCXMJ")).
neg(eqo("journals/tods/BaralisW00","wUKL835XgAEJ")).
neg(eqo("journals/tods/ChaudhuriS99","NNPQHezwGuAJ")).
neg(eqo("journals/tods/Chen95a","qNi-OiqW3sIJ")).
neg(eqo("journals/tods/Chomicki95","pHuL-9kHWH0J")).
neg(eqo("journals/tods/CliffordC94","hszVxktuM6gJ")).
neg(eqo("journals/tods/DeySB99","8ZzzqjH7yBMJ")).
neg(eqo("journals/tods/FegarasM00","eCQjRu0EiagJ")).
neg(eqo("journals/tods/FegarasM00","fIwTQ2PSMycJ")).
neg(eqo("journals/tods/FraternaliT95","FEnoIcB6GwsJ")).
neg(eqo("journals/tods/FraternaliT95","fB2xVdlMTtwJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","TQ8M8qOzJO8J")).
neg(eqo("journals/tods/GravanoGT99","aXLcAfb2y5kJ")).
neg(eqo("journals/tods/GuoSW96","uaaJl906vYoJ")).
neg(eqo("journals/tods/Hellerstein98","rEu4oz68ZLAJ")).
neg(eqo("journals/tods/HjaltasonS03","h7_vmoCZRbIJ")).
neg(eqo("journals/tods/HjaltasonS99","RHJjRlVhi78J")).
neg(eqo("journals/tods/IoannidisR95","u5LuBw2MsTYJ")).
neg(eqo("journals/tods/KemmeA00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1093387%26type%3Dpdf")).
neg(eqo("journals/tods/KossmannFDA00","hMVhQ07qD9EJ")).
neg(eqo("journals/tods/KotidisR01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/tods/Ross96","d2qdkaHDRSMJ")).
neg(eqo("journals/tods/ScioreSR94","wGY37gGuigcJ")).
neg(eqo("journals/tods/Snodgrass01","url:http://www.springerlink.com/index/JJJG5825415765X2.pdf")).
neg(eqo("journals/tods/WolfsonJH97","url:http://portal.acm.org/citation.cfm%3Fid%3D335484")).
neg(eqo("journals/tods/ZaharioudakisCF97","4Y125m3-bsYJ")).
neg(eqo("journals/tods/ZaharioudakisCF97","JB7MefN0f9UJ")).
neg(eqo("journals/vldb/AbbadiSW01","N4nyJ3C99iMJ")).
neg(eqo("journals/vldb/AbbadiSW01","UF-RyjST87cJ")).
neg(eqo("journals/vldb/AbiteboulCM98","kUA9e6YP8igJ")).
neg(eqo("journals/vldb/AbiteboulCM98","oFnBgxMAKuQJ")).
neg(eqo("journals/vldb/AgrawalHK03","FF4u5cqjanQJ")).
neg(eqo("journals/vldb/AgrawalHK03","cHWAzKustmkJ")).
neg(eqo("journals/vldb/AgrawalHK03","z_KvJGRMO5QJ")).
neg(eqo("journals/vldb/AilamakiDH02","kWo0SSIKp3kJ")).
neg(eqo("journals/vldb/ApersCS02","zvcs9bbyoi0J")).
neg(eqo("journals/vldb/Atkinson00","dNM-avLn230J")).
neg(eqo("journals/vldb/AtzeniM00","dEnVedNqyzsJ")).
neg(eqo("journals/vldb/Barbara-MillaG94","FJ0OABPbFuAJ")).
neg(eqo("journals/vldb/BarbaraI95","gU-dOX4-eeYJ")).
neg(eqo("journals/vldb/Baumann94","eGyxXPOtJZYJ")).
neg(eqo("journals/vldb/BernsteinPS00","-mTrpy_n8PYJ")).
neg(eqo("journals/vldb/BernsteinPS00","WWP-Y_2_QhgJ")).
neg(eqo("journals/vldb/BraumandlCKK00","ywe7qzk4E5MJ")).
neg(eqo("journals/vldb/C95","TXkO2vKRHkoJ")).
neg(eqo("journals/vldb/C95a","vqOAj_RFlNIJ")).
neg(eqo("journals/vldb/ChakrabartiDAR98","T2fr86fsQcsJ")).
neg(eqo("journals/vldb/ChakrabartiGRS01","PIhBWXtNTvUJ")).
neg(eqo("journals/vldb/ChanGR03","qkJ_IyVmLfUJ")).
neg(eqo("journals/vldb/ChandrasekaranF03","se5CKFbG3cAJ")).
neg(eqo("journals/vldb/ChangG01","m9eI-g89UagJ")).
neg(eqo("journals/vldb/ChienTZ02","0komEtlfzzMJ")).
neg(eqo("journals/vldb/Cobb97","rnFt_--hj10J")).
neg(eqo("journals/vldb/CuiW03","FX8Cf3-C5NgJ")).
neg(eqo("journals/vldb/CuiW03","Nn9a9gdUCpIJ")).
neg(eqo("journals/vldb/DattaDVRN01","IxfAar-uKB4J")).
neg(eqo("journals/vldb/EyalM01","ntrSSBumclMJ")).
neg(eqo("journals/vldb/Guting94","SelRfxBb2oMJ")).
neg(eqo("journals/vldb/Halevy01","0XWjlzHVMdMJ")).
neg(eqo("journals/vldb/Halevy01","isFtaxSMR2YJ")).
neg(eqo("journals/vldb/HarderST99","5J51gD5ZgZgJ")).
neg(eqo("journals/vldb/HarderST99","AT7rtd-fVvgJ")).
neg(eqo("journals/vldb/HarderST99","e3x1gQOsmMkJ")).
neg(eqo("journals/vldb/HarderST99","ymzu_tyxk7gJ")).
neg(eqo("journals/vldb/IoannidisNSS97","syoqNSarAscJ")).
neg(eqo("journals/vldb/IshakbeyogluO98","Q3MhG5RK29oJ")).
neg(eqo("journals/vldb/IvesHW02","bKH_ifNDjdoJ")).
neg(eqo("journals/vldb/KraissW98","pcx9Kj5rtsIJ")).
neg(eqo("journals/vldb/LawLG99","lctWtZ1v_KQJ")).
neg(eqo("journals/vldb/LeeSC01","sRcMuuo3-BEJ")).
neg(eqo("journals/vldb/MuthOPW00","1Mpsn1MK7ZQJ")).
neg(eqo("journals/vldb/MylopoulosCPST96","rJnFYWAzp18J")).
neg(eqo("journals/vldb/NanopoulosM02","kwEsurUQqDgJ")).
neg(eqo("journals/vldb/NgS98","url:http://www.springerlink.com/index/85D6LYCWB48DWBKW.pdf")).
neg(eqo("journals/vldb/Ozsu03","IGGw3SjQsTkJ")).
neg(eqo("journals/vldb/PapadiasS94","OU0JYnv9z_UJ")).
neg(eqo("journals/vldb/PoulovassilisS96","fysIkDChSzgJ")).
neg(eqo("journals/vldb/RafieiM02","RovnC1D7mTsJ")).
neg(eqo("journals/vldb/RafieiM02","S_jh-ZtVr08J")).
neg(eqo("journals/vldb/RafieiM02","wMhXlYbxeZ8J")).
neg(eqo("journals/vldb/ScheuermannWZ98","Q_JRmsXFEM4J")).
neg(eqo("journals/vldb/Seshadri98","beti2EIiVaMJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","7gDXEIuMUIIJ")).
neg(eqo("journals/vldb/SivasankaranSTPR96","QSo3pDLmwv4J")).
neg(eqo("journals/vldb/SwamiS95","DB8lVC2D9fcJ")).
neg(eqo("journals/vldb/YangW03","sZ7E67GiRIsJ")).
neg(eqo("journals/vldb/YangW03","tpRKY5_U2f8J")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","Rjb06zlxbLIJ")).
pos(eqo("conf/sigmod/AcharyaGP00","smzeHDQ3zbMJ")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/AdaliSS99","bhWLVCoDuNQJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/Aggarwal02","tK1_3wGUIHsJ")).
pos(eqo("conf/sigmod/AggarwalWY99","wjKnsQWl5ZoJ")).
pos(eqo("conf/sigmod/AggarwalY01","QkTd5WogN-AJ")).
pos(eqo("conf/sigmod/AndersonBKW98","H6eMdbXATmkJ")).
pos(eqo("conf/sigmod/AshleyFHLNP95","9uxj2XzGt9UJ")).
pos(eqo("conf/sigmod/AshleyFHLNP95","FnnILIjz08EJ")).
pos(eqo("conf/sigmod/BarbosaMKL02","ueKnwQCE3nIJ")).
pos(eqo("conf/sigmod/BergstraesserBPS99","qcZ2tYThtK0J")).
pos(eqo("conf/sigmod/BersonGMJ94","wsG_Q2jbgCAJ")).
pos(eqo("conf/sigmod/BertinoCF01","JSzfxAgs4pgJ")).
pos(eqo("conf/sigmod/BettiniWBJ95","c57d3rgd3IcJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","cg01BqanXhUJ")).
pos(eqo("conf/sigmod/BhattacharyaMBNHS02","tsQbSCfQTooJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","oulaZpEWkMQJ")).
pos(eqo("conf/sigmod/BozkayaO97","37lliRw_cOQJ")).
pos(eqo("conf/sigmod/BraumandlKK99","ywe7qzk4E5MJ")).
pos(eqo("conf/sigmod/BressanGFJHKLMPQSS97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294191CI")).
pos(eqo("conf/sigmod/BressanGOT00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D336587%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BreunigKNS00","4ZBs-U7sOk0J")).
pos(eqo("conf/sigmod/BreunigKNS00","KILdAgEb2OsJ")).
pos(eqo("conf/sigmod/BrodskySCE99","jnBo-gBTmAcJ")).
pos(eqo("conf/sigmod/Bussler01","UYIeOe280OwJ")).
pos(eqo("conf/sigmod/Bussler02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564801%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Carey00","x6n6Ev8WnhEJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","mt8Q1YmVRkMJ")).
pos(eqo("conf/sigmod/CareyDNAGS97","xc1E6MOfP80J")).
pos(eqo("conf/sigmod/Cattell94","QgR0DgMbdgIJ")).
pos(eqo("conf/sigmod/Cattell94","zSoTbEtLuqEJ")).
pos(eqo("conf/sigmod/ChangBCLLS00","bqtRaOoJ87AJ")).
pos(eqo("conf/sigmod/ChangBCLLS00","dM9iTzhspEUJ")).
pos(eqo("conf/sigmod/ChangG99","8Yt1Mba9-wQJ")).
pos(eqo("conf/sigmod/ChangG99","BYkCvtDCxzcJ")).
pos(eqo("conf/sigmod/ChaudhuriGS03","OFGtGwUHhUQJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","3fEogSGG3wQJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","TqXFdQBTW6kJ")).
pos(eqo("conf/sigmod/ChenGMV02","IqV3EploPP4J")).
pos(eqo("conf/sigmod/ChenJDTW00","EKNLKC2nEGwJ")).
pos(eqo("conf/sigmod/ChenJDTW00","OsfWKJek9L8J")).
pos(eqo("conf/sigmod/ChenRW02","05ShsIGjnKkJ")).
pos(eqo("conf/sigmod/ChenZCKR01","q49c-IEX7N8J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D280357%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChristophidesCM96","GpGg0czXSQcJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","nDl2k1YSi8AJ")).
pos(eqo("conf/sigmod/ChristophidesCM96","q3Y-Mlx2sUsJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","R7tBLAw0O3wJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","1kGIXDE6G90J")).
pos(eqo("conf/sigmod/ColbyGLMT96","MgphE2z3NqYJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","qZppq83SJEYJ")).
pos(eqo("conf/sigmod/ColbyGLMT96","tGBhWHHU7hsJ")).
pos(eqo("conf/sigmod/CranorJSS03","eXt7Nvd060MJ")).
pos(eqo("conf/sigmod/DattaDTVSR02","5N2k30IYlWoJ")).
pos(eqo("conf/sigmod/DattaDTVSR02","RKbKtLWjDLEJ")).
pos(eqo("conf/sigmod/DeutschFS99","-KuX7UT0JIIJ")).
pos(eqo("conf/sigmod/DeutschFS99","QxtGOVsCF78J")).
pos(eqo("conf/sigmod/DeutschFS99","SR_yVgZnYpMJ")).
pos(eqo("conf/sigmod/DeutschFS99","kDYpG4mLjLkJ")).
pos(eqo("conf/sigmod/DeutschFS99","twQNwr-jFmoJ")).
pos(eqo("conf/sigmod/DewanSHH94","GUdXGx4blW8J")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","_4ARkdpRArQJ")).
pos(eqo("conf/sigmod/DohertyHR96","v3IA8Go4UjIJ")).
pos(eqo("conf/sigmod/DraperHW01","sURGDemFSsUJ")).
pos(eqo("conf/sigmod/FabretJLPRS01","NDTjtWuhzbQJ")).
pos(eqo("conf/sigmod/FaginKS03","dOY1djmoy04J")).
pos(eqo("conf/sigmod/FaginKS03","tQZWeE_nsa0J")).
pos(eqo("conf/sigmod/FaloutsosRM94","4bG39HmGrAQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","NqewK_dmRawJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","bL4szse-iCQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","qaoTK_zX3awJ")).
pos(eqo("conf/sigmod/Fegaras98","XVtlJYx2G_wJ")).
pos(eqo("conf/sigmod/Fernandez94","PmrthJYk66cJ")).
pos(eqo("conf/sigmod/FernandezS96","66uAX5EPtKcJ")).
pos(eqo("conf/sigmod/GaoW02","PZTESZecfnQJ")).
pos(eqo("conf/sigmod/GodfreySE98","-H3tXntLhowJ")).
pos(eqo("conf/sigmod/GoelI96","_Vn4nSui5UMJ")).
pos(eqo("conf/sigmod/GoelI96","hD6w1eBfjWcJ")).
pos(eqo("conf/sigmod/GravanoCGP97","PsoYENGEh9cJ")).
pos(eqo("conf/sigmod/GravanoCGP97","hs8rOlHD4K4J")).
pos(eqo("conf/sigmod/GreenwaldK01","zlHamuvyxIwJ")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanKS97","XFCkL9QhTjIJ")).
pos(eqo("conf/sigmod/HanWDPW02","nwWpGh3Mx7MJ")).
pos(eqo("conf/sigmod/HellersteinA00","Gsb6dnkFBMoJ")).
pos(eqo("conf/sigmod/HellersteinA00","VlRO0WwUy3wJ")).
pos(eqo("conf/sigmod/HellersteinA00","ZuCOw9hYVU8J")).
pos(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
pos(eqo("conf/sigmod/IpeirotisGS01","bo7ArXlXypQJ")).
pos(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
pos(eqo("conf/sigmod/IvesFFLW99","V4NASwqZ530J")).
pos(eqo("conf/sigmod/JagadishLS99","p5n3KKoHgMgJ")).
pos(eqo("conf/sigmod/KabraD98","V9XUvirmVEEJ")).
pos(eqo("conf/sigmod/KabraD98","WOHxNqdNMZoJ")).
pos(eqo("conf/sigmod/KanthRSB99","I48hanU3OR4J")).
pos(eqo("conf/sigmod/KaushikBNK02","xJQAjLzvlB0J")).
pos(eqo("conf/sigmod/KornJF97","ZZUl2Dc1MPsJ")).
pos(eqo("conf/sigmod/KornJF97","o5T-Jfvv930J")).
pos(eqo("conf/sigmod/KornMZ03","6VAQeD6muakJ")).
pos(eqo("conf/sigmod/KriegelMPS01","tsPOU-H3A94J")).
pos(eqo("conf/sigmod/LabrinidisR00","DKUouEkK_b4J")).
pos(eqo("conf/sigmod/LamCKNH01","8hdQohffF48J")).
pos(eqo("conf/sigmod/LarsonG98","QmBz3hMOFh4J")).
pos(eqo("conf/sigmod/LibkinMW96","OfZWx8jhQvwJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","0e3PPUvtZ0MJ")).
pos(eqo("conf/sigmod/LiuPTBBZBHY98","ezlAkB7ijDUJ")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/LoR96","em5eiGpRZFkJ")).
pos(eqo("conf/sigmod/LometW98","QPpUo7m3A7cJ")).
pos(eqo("conf/sigmod/LuoEHN02","7p7mpmvIBrYJ")).
pos(eqo("conf/sigmod/MaheshwariL97","1hXAkApUm3kJ")).
pos(eqo("conf/sigmod/MaheshwariL97","DI_v0vb6784J")).
pos(eqo("conf/sigmod/MamoulisP99","xdAsc3yVWvYJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","I-fmtPvluKEJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","J-7xdqqW5RwJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","v2KwhRi-OrMJ")).
pos(eqo("conf/sigmod/MelnikRB03","wfjeWtEY2NcJ")).
pos(eqo("conf/sigmod/MogiK96","hxWB8uQMCdgJ")).
pos(eqo("conf/sigmod/Mohan02","YJlUtEk7zwkJ")).
pos(eqo("conf/sigmod/Mohan02","qbrkg2DRU3AJ")).
pos(eqo("conf/sigmod/MohanN94","_2hj6snS3foJ")).
pos(eqo("conf/sigmod/MumickP94","hUQBQ_9ohcgJ")).
pos(eqo("conf/sigmod/MumickQM97","8m_6OmUvYJwJ")).
pos(eqo("conf/sigmod/MumickQM97","cvHvC7tUSrIJ")).
pos(eqo("conf/sigmod/NgLHM99","YemauUgIzlcJ")).
pos(eqo("conf/sigmod/NgLK98","kJVhJ4ruw6sJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","WrrEnOJswS4J")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D280357%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Ojjeh99","url:http://portal.acm.org/citation.cfm%3Fid%3D304245%26coll%3Dportal%26dl%3DACM")).
pos(eqo("conf/sigmod/OriaOILY00","xdUDA920uhMJ")).
pos(eqo("conf/sigmod/PadmanabhanBMCH03","wI75uFSs0bwJ")).
pos(eqo("conf/sigmod/PangCL94","beMsu5ebf30J")).
pos(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
pos(eqo("conf/sigmod/ParkCY95","A3XtQdi1j5UJ")).
pos(eqo("conf/sigmod/ParkCY95","v9preswS6YUJ")).
pos(eqo("conf/sigmod/PatelYKTNBHRLEKGDN97","0inuMFZSQ50J")).
pos(eqo("conf/sigmod/PossSKL02","c3QptREmhgAJ")).
pos(eqo("conf/sigmod/QuassW97","RFd0c3lXk1AJ")).
pos(eqo("conf/sigmod/QuassW97","TfIJHxpZeJIJ")).
pos(eqo("conf/sigmod/QuassWGHLMNRRAUW96","oB7qYK3HKiEJ")).
pos(eqo("conf/sigmod/RafieiM97","IlN1Z8UC688J")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/RaoZML02","7Ucs6vmjHN0J")).
pos(eqo("conf/sigmod/RinfretOO01","pyqtmrPg24YJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","QzW5By67KwcJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","00c1qmRdM5IJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","Dd0_gi74jCQJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","efwTNo1wRnMJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","imAsAkfukSYJ")).
pos(eqo("conf/sigmod/SagonasSW94","0hHYO7tQJUgJ")).
pos(eqo("conf/sigmod/SagonasSW94","uAoWmK-jEGAJ")).
pos(eqo("conf/sigmod/SagonasSW94","xc8KEoeRT9sJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","a7v0bHRrpjMJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","tuMjUVnPdXAJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","zM0o4FoKRXIJ")).
pos(eqo("conf/sigmod/SeidlK98","B8MoLkcvms4J")).
pos(eqo("conf/sigmod/SengarH03","7Mtanhr8EKoJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","Elpbl8vygYoJ")).
pos(eqo("conf/sigmod/ShklarSKT95","4IaWCBK6dMQJ")).
pos(eqo("conf/sigmod/ShouCTRH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375755%26type%3Dpdf%26dl%3DGUIDE%26dl%3DGUIDE%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/SwamiS94","S6TmnZKgmxwJ")).
pos(eqo("conf/sigmod/SzalayGKT00","T4os1oo8vT4J")).
pos(eqo("conf/sigmod/SzalayGKT00","YVCi81Vp9KAJ")).
pos(eqo("conf/sigmod/SzalayGKT00","ZXB1xI2h-HkJ")).
pos(eqo("conf/sigmod/SzalayGTKMRSv02","1tKWKmyczaYJ")).
pos(eqo("conf/sigmod/Tajima96","IZSzLlgi8tUJ")).
pos(eqo("conf/sigmod/TaoP02","fDWfHiQ6BR4J")).
pos(eqo("conf/sigmod/TrisoliniLN99","cFMtMf7bLzIJ")).
pos(eqo("conf/sigmod/VingralekBW94","qtSeY_1Q5YUJ")).
pos(eqo("conf/sigmod/VingralekBW94","rM8Ecg1WL4kJ")).
pos(eqo("conf/sigmod/VitterW99","1UFq52qqErUJ")).
pos(eqo("conf/sigmod/VitterW99","P5oJUiow7lsJ")).
pos(eqo("conf/sigmod/WangWYY02","KQJW4bzA8coJ")).
pos(eqo("conf/sigmod/Weininger02","iXkSngvyu08J")).
pos(eqo("conf/sigmod/WhiteD94","jKBaGqWJK2oJ")).
pos(eqo("conf/sigmod/ZadorozhnyRVUB02","xmE1380_4E4J")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VAX1F7QPNfsJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","VCc6IQulRJ4J")).
pos(eqo("conf/sigmod/ZaianeHLCC98","eauaGLr5uCUJ")).
pos(eqo("conf/sigmod/ZaianeHLCC98","tFB9gJLG4_UJ")).
pos(eqo("conf/sigmod/ZhangRL96","1ms09_UeEH4J")).
pos(eqo("conf/sigmod/ZhangRL96","IVWPCLaGIPcJ")).
pos(eqo("conf/sigmod/ZhangRL96","KUGjzt-IgpoJ")).
pos(eqo("conf/sigmod/ZhangRL96","PdBcau_cG-AJ")).
pos(eqo("conf/sigmod/ZhangRL96","Q4JDSTBf5_oJ")).
pos(eqo("conf/sigmod/ZhangRL96","kBlynBey41QJ")).
pos(eqo("conf/sigmod/ZhuSZ03","7VSlB0yIt3YJ")).
pos(eqo("conf/sigmod/ZouS96","qPCh8M_RSwEJ")).
pos(eqo("conf/vldb/AbiteboulBBCCDMMP03","fANcvlGA8WAJ")).
pos(eqo("conf/vldb/AboulnagaAN01","P6wBeL9DsREJ")).
pos(eqo("conf/vldb/AcharyaGP99","-7tsGpHin24J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","1bXX8uOvfQAJ")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AgrawalSX01","P3GB0IRKc2IJ")).
pos(eqo("conf/vldb/AgrawalSX01","bpWvAVOZLbwJ")).
pos(eqo("conf/vldb/AgrawalSX02","a1CLM5GoVtYJ")).
pos(eqo("conf/vldb/AilamakiDHW99","-mTrpy_n8PYJ")).
pos(eqo("conf/vldb/AilamakiDHW99","4bTXoodYyHMJ")).
pos(eqo("conf/vldb/AlsabtiRS97","-0Lu8VIRYtEJ")).
pos(eqo("conf/vldb/AlsabtiRS97","nqOZsUydoQkJ")).
pos(eqo("conf/vldb/AltinelF00","SXHPvzZDrFMJ")).
pos(eqo("conf/vldb/AnciauxBBPV01","PFEvlg2DiMkJ")).
pos(eqo("conf/vldb/ArionBCDMP03","CzpCERFYBikJ")).
pos(eqo("conf/vldb/ArionBCDMP03","LIjye8V-mM0J")).
pos(eqo("conf/vldb/BassiliadesV95","B1kJzsffXEwJ")).
pos(eqo("conf/vldb/BawaBA03","bo1rnY4bU4kJ")).
pos(eqo("conf/vldb/Bayer95","W3l3pQ62_YMJ")).
pos(eqo("conf/vldb/BelussiF95","5FEmoD1TIdwJ")).
pos(eqo("conf/vldb/BelussiF95","7BDCL140Kx4J")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","AgqQVeQ7A0AJ")).
pos(eqo("conf/vldb/BerchtoldKK96","WnYVibh8fxUJ")).
pos(eqo("conf/vldb/BerchtoldKK96","_oDfC1aR4CAJ")).
pos(eqo("conf/vldb/BerchtoldKK96","kCH4ZzrozMkJ")).
pos(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
pos(eqo("conf/vldb/BettiniJWW02","Aq_TE_cWEQkJ")).
pos(eqo("conf/vldb/BonczRK98","965BXzMPxSoJ")).
pos(eqo("conf/vldb/Brodie03","deEJ1JsF8RwJ")).
pos(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
pos(eqo("conf/vldb/CarneyCCCLSSTZ02","1J26mBTxdS0J")).
pos(eqo("conf/vldb/Celis96","Bg5vcyRBKd8J")).
pos(eqo("conf/vldb/CeriCW00","K1psyoQRPpgJ")).
pos(eqo("conf/vldb/CeriCW00","bDuu6x2n1tgJ")).
pos(eqo("conf/vldb/ChakrabartiM00","7P1LlDStRGYJ")).
pos(eqo("conf/vldb/ChaudhuriS96","4MaErPILRq8J")).
pos(eqo("conf/vldb/Chawathe99","w6VtZRVAZV8J")).
pos(eqo("conf/vldb/ChenCFGJMTW99","NHGP6JIxXjoJ")).
pos(eqo("conf/vldb/ChenDZ03","5MbqS0-RzBIJ")).
pos(eqo("conf/vldb/ChoN02","GzOK_PJlOwQJ")).
pos(eqo("conf/vldb/ChristopheBPV00","q42RuW4_FogJ")).
pos(eqo("conf/vldb/CochinwalaB94","Bp69wMYw9DAJ")).
pos(eqo("conf/vldb/CosleyLP02","22ZTae8fNuIJ")).
pos(eqo("conf/vldb/CosleyLP02","BTalXWt3faUJ")).
pos(eqo("conf/vldb/CotterB00","SJ6PiY04ebMJ")).
pos(eqo("conf/vldb/DayalHL01","0XYRlW9tvw8J")).
pos(eqo("conf/vldb/DeRose99","_7DyRIjTceAJ")).
pos(eqo("conf/vldb/DesslochM97","OY4EswVULVcJ")).
pos(eqo("conf/vldb/DillKMRST01","XagphbDrGQMJ")).
pos(eqo("conf/vldb/DillKMRST01","_dtqcPU4NdkJ")).
pos(eqo("conf/vldb/DongHLPW01","C_H34ddegI8J")).
pos(eqo("conf/vldb/DongHLPW01","HWylSJiWUsgJ")).
pos(eqo("conf/vldb/DonjerkovicR99","SgokkSrdkyAJ")).
pos(eqo("conf/vldb/Duranti01","gQW6iYG5Vh0J")).
pos(eqo("conf/vldb/DyresonBJ99","FkPcMtplo18J")).
pos(eqo("conf/vldb/EicklerKK97","PCFJuVxYxtwJ")).
pos(eqo("conf/vldb/EleftheriouBCDHLPPABDDDGJHLRSVW03","hRToevpkaa0J")).
pos(eqo("conf/vldb/FaloutsosG96","vwcVawlOJn0J")).
pos(eqo("conf/vldb/FankhauserGLMT98","JnwUAxUMwvQJ")).
pos(eqo("conf/vldb/FernandezSCMS03","sn_R4N1q2SwJ")).
pos(eqo("conf/vldb/Fox02","eybUiurX77sJ")).
pos(eqo("conf/vldb/GaasterlandL94","oIFrkS2rPrcJ")).
pos(eqo("conf/vldb/GarofalakisG01","PIhBWXtNTvUJ")).
pos(eqo("conf/vldb/GarofalakisG01","SHDQQrfJ3BMJ")).
pos(eqo("conf/vldb/GarofalakisG01","rcSfDxBif40J")).
pos(eqo("conf/vldb/Gentili01","2j1dalv3kCEJ")).
pos(eqo("conf/vldb/GhoshPSH02","2dlOojuSNeIJ")).
pos(eqo("conf/vldb/GoldmanW97","EM5uAeHdNEIJ")).
pos(eqo("conf/vldb/GoldmanW97","UeLjlfHU_gkJ")).
pos(eqo("conf/vldb/GoldmanW97","Ye9iUyg5mL0J")).
pos(eqo("conf/vldb/GoldmanW97","l5GboAkBH1AJ")).
pos(eqo("conf/vldb/GottlobKP02","Pk09A5EmsOoJ")).
pos(eqo("conf/vldb/GuptaHQ95","CtRFDjCGDg8J")).
pos(eqo("conf/vldb/GuptaHQ95","dP1tJuCiK2cJ")).
pos(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
pos(eqo("conf/vldb/HammelP02","SU2XS1MVb40J")).
pos(eqo("conf/vldb/HasanM94","JW7LRQwx_goJ")).
pos(eqo("conf/vldb/HasanM94","e7N82yYp8UIJ")).
pos(eqo("conf/vldb/HinneburgAK00","wQy061nMBCgJ")).
pos(eqo("conf/vldb/Huyn01","SbL4xw4mCewJ")).
pos(eqo("conf/vldb/IdrisGC94","Xf7TnMxlGTkJ")).
pos(eqo("conf/vldb/IdrisGC94","esWYQTXHBfUJ")).
pos(eqo("conf/vldb/IwerksSS03","4B_LhCns0WoJ")).
pos(eqo("conf/vldb/JagadishKNS99","GtXc02EJjCgJ")).
pos(eqo("conf/vldb/JagadishMN99","9rDll5YAQnoJ")).
pos(eqo("conf/vldb/JagadishMN99","RPWDtUmq6_QJ")).
pos(eqo("conf/vldb/JoshiBLL98","RufEbUPZNbYJ")).
pos(eqo("conf/vldb/KiesslingK02","4XP24_IFvPsJ")).
pos(eqo("conf/vldb/KiesslingK02","Z8bBN2cO11UJ")).
pos(eqo("conf/vldb/KochBG03","mZNcc1O3Nl8J")).
pos(eqo("conf/vldb/KornSFSP96","51VkEWUxxLIJ")).
pos(eqo("conf/vldb/KornSFSP96","I8YNDqO9pg8J")).
pos(eqo("conf/vldb/KriegelPS00","DOOggMfdGYoJ")).
pos(eqo("conf/vldb/LabrinidisR01","3Ozte0ucNJAJ")).
pos(eqo("conf/vldb/LabrinidisR01","MNDAemDpS3cJ")).
pos(eqo("conf/vldb/LeeHJT03","BSE2se70OMYJ")).
pos(eqo("conf/vldb/LeslieJBY95","zmwPMSd8rGgJ")).
pos(eqo("conf/vldb/LevyRO96","CWzG-HRtqZIJ")).
pos(eqo("conf/vldb/LiM01","vkMYwC5tzUgJ")).
pos(eqo("conf/vldb/LimWPVP02","9kl_hTyQtmQJ")).
pos(eqo("conf/vldb/LongS03","zU4MULiFRrYJ")).
pos(eqo("conf/vldb/MadhavanBR01","5mM4rpgyeNoJ")).
pos(eqo("conf/vldb/MadhavanBR01","QZyUtlmyn1UJ")).
pos(eqo("conf/vldb/MadhavanBR01","wRHapJxb_-QJ")).
pos(eqo("conf/vldb/MadhavanH03","ujCYoqKS6BcJ")).
pos(eqo("conf/vldb/ManolescuFKXO00","uWqGLwi8VOgJ")).
pos(eqo("conf/vldb/ManolopoulosT01","hr5OGCJqc2MJ")).
pos(eqo("conf/vldb/McHughW99","bXRF6rASxhgJ")).
pos(eqo("conf/vldb/MiloZ98","a7XtgKiAJFMJ")).
pos(eqo("conf/vldb/Moerkotte98","HcCevkoobDsJ")).
pos(eqo("conf/vldb/MorimotoIM97","3enylshvOl8J")).
pos(eqo("conf/vldb/MorimotoIM97","wkD289iFVAIJ")).
pos(eqo("conf/vldb/MoserKK95","53hNU_r6-jgJ")).
pos(eqo("conf/vldb/MoserKK95","A2OQAUw2OHIJ")).
pos(eqo("conf/vldb/NathDKGKS03","pF6EW_yKYyYJ")).
pos(eqo("conf/vldb/NatsevCSLV01","e6dXyX0MKEIJ")).
pos(eqo("conf/vldb/NgC97","J7mY8RlpTKMJ")).
pos(eqo("conf/vldb/NgC97","eTDBrdfpGNEJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("conf/vldb/NgH94","6OfJSMB4vOcJ")).
pos(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
pos(eqo("conf/vldb/NgH94","JA55PRiwrMQJ")).
pos(eqo("conf/vldb/NgH94","XfblD8N3jT8J")).
pos(eqo("conf/vldb/OoiYTJ01","T8BPorXB1VsJ")).
pos(eqo("conf/vldb/PalpanasSCP02","nlh2WXZT3VIJ")).
pos(eqo("conf/vldb/PapadiasMD98","_6JbypCpDqgJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","Aiy1CuDyBNQJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","FdZnUd2bYYwJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","gkbvvgj8kdUJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","vjZ89wZs27UJ")).
pos(eqo("conf/vldb/PereiraFJLS01","Cd6A4nsDnkQJ")).
pos(eqo("conf/vldb/PottingerL00","mpnnRdFUUJQJ")).
pos(eqo("conf/vldb/QianZXP03","Chp-3UwMgTQJ")).
pos(eqo("conf/vldb/RosenthalS94","NFUWsBXtCncJ")).
pos(eqo("conf/vldb/RusinkiewiczKTWM95","019zSr3Lx4EJ")).
pos(eqo("conf/vldb/SahuguetA99","Mi0eqxwTUwEJ")).
pos(eqo("conf/vldb/SahuguetA99","NrXmzugArgoJ")).
pos(eqo("conf/vldb/SahuguetA99","PAcS8vELrawJ")).
pos(eqo("conf/vldb/SahuguetA99","VT_vPPmEIEIJ")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/SchmidtWKCMB02","CvGGYMrKR2sJ")).
pos(eqo("conf/vldb/SenkulKT02","g7HDbO4GCN4J")).
pos(eqo("conf/vldb/SevcikK96","GiHrMj3vbSAJ")).
pos(eqo("conf/vldb/ShahDR03","FR1h4tU9FosJ")).
pos(eqo("conf/vldb/ShahDR03","HGJu1Uyq-OcJ")).
pos(eqo("conf/vldb/ShahRS02","ByAk0yD64SYJ")).
pos(eqo("conf/vldb/ShahRS02","Q3MhG5RK29oJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","C5EoaXfZ7BsJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","NADaoJJSRfQJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","iME-SCx_DIgJ")).
pos(eqo("conf/vldb/ShanmugasundaramGTZDN99","mduVymV8jNYJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","HKM-zP0LT_UJ")).
pos(eqo("conf/vldb/SheikholeslamiCZ98","C2VEa-WmIt0J")).
pos(eqo("conf/vldb/ShethKMWDLPLS96","tKPVyvxSJA8J")).
pos(eqo("conf/vldb/ShuklaDNR96","Qdw5iM0aKwAJ")).
pos(eqo("conf/vldb/SilversteinBMU98","_GLI7Izv17cJ")).
pos(eqo("conf/vldb/SindoniTABFGMPPT01","0zdXnl9cQysJ")).
pos(eqo("conf/vldb/SrikantA95","08bwdEy_OY8J")).
pos(eqo("conf/vldb/SrikantA95","KIPDo6ym8BUJ")).
pos(eqo("conf/vldb/SrikantA95","bibMn8zFnksJ")).
pos(eqo("conf/vldb/SrikantA95","kAi6HssDySgJ")).
pos(eqo("conf/vldb/SrikantA95","nPkMLSiC3JQJ")).
pos(eqo("conf/vldb/SrikantA95","rnfILQoQrBYJ")).
pos(eqo("conf/vldb/StathatosRB97","JH2hiRXPJcEJ")).
pos(eqo("conf/vldb/StathatosRB97","PJ755vWjC9MJ")).
pos(eqo("conf/vldb/StohrR01","jn3pvb3hRzwJ")).
pos(eqo("conf/vldb/TheodoratosS97","inPPL3lI3CcJ")).
pos(eqo("conf/vldb/Toivonen96","R3wCZGqY0nYJ")).
pos(eqo("conf/vldb/TreschPL95","1rPUqMFsS3AJ")).
pos(eqo("conf/vldb/TsatalosSI94","--1aoAaGkgQJ")).
pos(eqo("conf/vldb/VassalosP97","2DJipXynj5wJ")).
pos(eqo("conf/vldb/VassalosP97","5DKaP73v7FQJ")).
pos(eqo("conf/vldb/VassalosP97","kG-k9420fGMJ")).
pos(eqo("conf/vldb/VriesDBA99","3o-rUvRsdUwJ")).
pos(eqo("conf/vldb/WaasCB01","y_gKGtzupHIJ")).
pos(eqo("conf/vldb/Wadler01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672033")).
pos(eqo("conf/vldb/WangZ00","eDa9jQWsTMoJ")).
pos(eqo("conf/vldb/YagoubFIV00a","hMsWZU5TJWYJ")).
pos(eqo("conf/vldb/YanA94","WG-3vX59MvIJ")).
pos(eqo("conf/vldb/YanL95","9B2oMksKaMMJ")).
pos(eqo("conf/vldb/YanL95","gHMpuR5VHJ4J")).
pos(eqo("conf/vldb/YangG01","g8raVwL_ICIJ")).
pos(eqo("conf/vldb/YuSLJ02","6EJ6A2y_U1IJ")).
pos(eqo("conf/vldb/YuSLJ02","qYGzjvmVjS8J")).
pos(eqo("conf/vldb/ZengBNN01","3TivNLIErRkJ")).
pos(eqo("conf/vldb/ZhouR03","MvbChqWgFawJ")).
pos(eqo("conf/vldb/ZhouS03","NlDvk5J0WwEJ")).
pos(eqo("conf/vldb/ZouS98","Hov18raBHwIJ")).
pos(eqo("conf/vldb/ZouS98","fPzfCbyzqsoJ")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/ArenasKKKMM03","biVrK7MrU4QJ")).
pos(eqo("journals/sigmod/AtzeniM98","HtxGbMkTXdsJ")).
pos(eqo("journals/sigmod/BaaderJN97","SxT807RR-NsJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","asukNMVeZZYJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
pos(eqo("journals/sigmod/BhargavaAP95","Sql66UDiVnwJ")).
pos(eqo("journals/sigmod/BichlerSZ98","fQNdA5cjapAJ")).
pos(eqo("journals/sigmod/BichlerSZ98","goq6Z9bDeSsJ")).
pos(eqo("journals/sigmod/Bohlen95","43K14Y5xa0YJ")).
pos(eqo("journals/sigmod/Bohlen95","v5P_NFXdOR8J")).
pos(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373708%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BuchnerM98","dkWnTbi9xnEJ")).
pos(eqo("journals/sigmod/BunemanRU97","lgCzXE4LjkIJ")).
pos(eqo("journals/sigmod/BusslerFM02","NvS2ZIeX3MUJ")).
pos(eqo("journals/sigmod/BusslerFM02","RaOQG4YyzM4J")).
pos(eqo("journals/sigmod/CalvaneseGLV03","pGcIRyDyFG8J")).
pos(eqo("journals/sigmod/CaplinskasEV02","Axu6UlX-pPYJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","url:http://portal.acm.org/citation.cfm%3Fid%3D507338.507367%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CaplinskasEV02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507367%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CeriFP99","mr8XDkQ7adAJ")).
pos(eqo("journals/sigmod/ConradEHRSSSV97","SBnqbyQF3SoJ")).
pos(eqo("journals/sigmod/CruzKLSWY02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DarwenD95","EXwe9r79qxEJ")).
pos(eqo("journals/sigmod/DarwenD95","Ppe_v5Zt140J")).
pos(eqo("journals/sigmod/DarwenD95","Xa_whOlvG7gJ")).
pos(eqo("journals/sigmod/DiazJPa94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181555%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DrewHKKLLLSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219769%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/EnglertGH95","WYE9fKutj70J")).
pos(eqo("journals/sigmod/FininJ02","rg8576nvnkUJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","93C5Prxx5YcJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","HJRR7GGfD6sJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ixz5LdVw9_8J")).
pos(eqo("journals/sigmod/FreemanG96","VlHke7OkYwQJ")).
pos(eqo("journals/sigmod/GatziuKBF98","GlHmit1yw6AJ")).
pos(eqo("journals/sigmod/GatziuKBF98","YERfAnxw2RcJ")).
pos(eqo("journals/sigmod/Grohe02","jzwiskpRLOUJ")).
pos(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
pos(eqo("journals/sigmod/GroskyFS94","zMK02pxd4OEJ")).
pos(eqo("journals/sigmod/HanBP01","FT5pSUb-uTYJ")).
pos(eqo("journals/sigmod/HasselbringHHKRRS00","JW49QfQtuTMJ")).
pos(eqo("journals/sigmod/HasselbringHHKRRS00","X9PsaiaoDJ4J")).
pos(eqo("journals/sigmod/Hellerstein03","5FSG85HbUygJ")).
pos(eqo("journals/sigmod/HuangKL02","g4mWc14U8m4J")).
pos(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
pos(eqo("journals/sigmod/HummerLW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507345%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Huyn01","KNYDz76C_HsJ")).
pos(eqo("journals/sigmod/Jagadish01","url:http://portal.acm.org/citation.cfm%3Fid%3D604264.604276%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JenningsNF98","tYXzABUZYxQJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","DOW5UL3FQk8J")).
pos(eqo("journals/sigmod/JensenCEGHJ94","WJ_VcY3mmEkJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","rRrT0v_j7tkJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D181560%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/JensenCEGHJ94","xFQWX4M8E2YJ")).
pos(eqo("journals/sigmod/JensenCEGHJ94","yK4VALoQjlgJ")).
pos(eqo("journals/sigmod/KaradimitriouT97","SrCBkHnIFL8J")).
pos(eqo("journals/sigmod/KarlapalemLS95","B_m0Yp4aycUJ")).
pos(eqo("journals/sigmod/Kim94","930Uth7EArkJ")).
pos(eqo("journals/sigmod/KimballS95","E6Z68tQL1BsJ")).
pos(eqo("journals/sigmod/KimballS95","ga66OWjHdoUJ")).
pos(eqo("journals/sigmod/Klein94","kG86HB6N1xEJ")).
pos(eqo("journals/sigmod/LuoI02","url:http://portal.acm.org/citation.cfm%3Fid%3D601858.601879%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/McClatcheyV97","mbFxAqrWXbYJ")).
pos(eqo("journals/sigmod/McClatcheyV97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D271087%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MeltonE01","619anaISuGEJ")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NascimentoSP03","G3QWq2T08SEJ")).
pos(eqo("journals/sigmod/NgH95","url:http://portal.acm.org/citation.cfm%3Fid%3D202660.202665%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/NorrieBSW94","q6YVJJgD1uQJ")).
pos(eqo("journals/sigmod/PapazoglouH99","WbsAK4ZE17YJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","F7AdjoH_uTcJ")).
pos(eqo("journals/sigmod/PissinouSEMOPSTD94","fSKoYnVJbwwJ")).
pos(eqo("journals/sigmod/PuSW01","nkW4iN6JqfAJ")).
pos(eqo("journals/sigmod/RamDD99","kHE9-cv77fwJ")).
pos(eqo("journals/sigmod/RashidS00","e0GH54HirssJ")).
pos(eqo("journals/sigmod/RisheSBDOALOSS95","pGU2Ew1AQkoJ")).
pos(eqo("journals/sigmod/RoantreeS02","xfrOR_G4_UoJ")).
pos(eqo("journals/sigmod/RosenthalSMBTL95","-_FyboGgZkkJ")).
pos(eqo("journals/sigmod/Seshadri98","N9NdxNRvMMkJ")).
pos(eqo("journals/sigmod/Seshadri98","XijyPb231fAJ")).
pos(eqo("journals/sigmod/Snodgrass03b","PmIVKWJ5_V4J")).
pos(eqo("journals/sigmod/SycaraKWL99","YgouJdrCoZQJ")).
pos(eqo("journals/sigmod/TatarinovIMHSDDKMM03","rrSZOoViGqoJ")).
pos(eqo("journals/sigmod/TheodoridisN00","DXTczW8Dv4MJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/Vassilakis00","nZO8ZA4eYzYJ")).
pos(eqo("journals/sigmod/VassiliadisS99","uexel5Cdu4wJ")).
pos(eqo("journals/sigmod/WestmannKHM00","9jyzas_rFd4J")).
pos(eqo("journals/sigmod/WestmannKHM00","aLDnCruGaqYJ")).
pos(eqo("journals/sigmod/Widom94","lAbG3uFZvVUJ")).
pos(eqo("journals/sigmod/WolfsonSDNR95","R51Yi7sWJ6EJ")).
pos(eqo("journals/sigmod/YauLMS99","bhVBJw9Rp3QJ")).
pos(eqo("journals/sigmod/Zhang95","f86VsMJZ9gAJ")).
pos(eqo("journals/tods/BellNNS96","pz2VRTdXq1cJ")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/tods/ChakrabartiKMP02","QTzuiNlMnR4J")).
pos(eqo("journals/tods/ChakrabartiKMP02","_nOW6fmEcTEJ")).
pos(eqo("journals/tods/Chen95a","qexCEm3QaUgJ")).
pos(eqo("journals/tods/DiaoAFZF03","fREDZIbZVdEJ")).
pos(eqo("journals/tods/EiterLLS01","tEZIquYevQoJ")).
pos(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
pos(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
pos(eqo("journals/tods/FukudaMMT01","sOBRaiLLvZgJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","axMI0TqrxxQJ")).
pos(eqo("journals/tods/GhandeharizadehHJ96","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0252444CI")).
pos(eqo("journals/tods/GhandeharizadehHJ96","vMVuIqz5BiwJ")).
pos(eqo("journals/tods/GibbonsMP02","QKnjF3UgncMJ")).
pos(eqo("journals/tods/GraefeC95","Bn8s7u5T9SAJ")).
pos(eqo("journals/tods/OliverS94","zAczQV37xxsJ")).
pos(eqo("journals/tods/PetersO97","er0r8doAGUQJ")).
pos(eqo("journals/tods/PetersO97","mQp5jjo-npAJ")).
pos(eqo("journals/tods/PolyzoisG94","p7x1zGD_bkEJ")).
pos(eqo("journals/tods/ScioreSR94","RJt8UiSzDTkJ")).
pos(eqo("journals/tods/ScioreSR94","fW9j2V5gnUMJ")).
pos(eqo("journals/vldb/AmielBDS96","RtYWYRjBUmEJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","Cmq7lkkXNt4J")).
pos(eqo("journals/vldb/Barbara-MillaG94","Hc9uWxJu840J")).
pos(eqo("journals/vldb/Barbara-MillaG94","mFHdV09MfG8J")).
pos(eqo("journals/vldb/Barbara-MillaG94","md3DWyujCrQJ")).
pos(eqo("journals/vldb/BarbaraI95","F7azEOfg-Q0J")).
pos(eqo("journals/vldb/BarbaraI95","kooQijVBMscJ")).
pos(eqo("journals/vldb/BenzakenD95","rF3edU2oNcEJ")).
pos(eqo("journals/vldb/BohmAnY97","O7IuKWfq4RYJ")).
pos(eqo("journals/vldb/CandanLS00","v1MIy7nisZMJ")).
pos(eqo("journals/vldb/ChakrabartiDAR98","0EbuWDceVnoJ")).
pos(eqo("journals/vldb/ChenHY97","IWZsSVPC6HMJ")).
pos(eqo("journals/vldb/ChidlovskiiB00","ysC3V2Lu3M8J")).
pos(eqo("journals/vldb/FengYLH02","Uxh3R2hfBOAJ")).
pos(eqo("journals/vldb/FuCCM00","7kC8fo78d6sJ")).
pos(eqo("journals/vldb/GeorgeH00","2L-UFpDof3UJ")).
pos(eqo("journals/vldb/Halevy02","url:http://www.springerlink.com/index/6UEYKJ4UQTK18H6D.pdf")).
pos(eqo("journals/vldb/Han98","url:http://www.springerlink.com/index/YTPAB711B92NCE7J.pdf")).
pos(eqo("journals/vldb/HarrisR96","S8x6zjXc9oAJ")).
pos(eqo("journals/vldb/HuntAI02","LiYp5oaDwbMJ")).
pos(eqo("journals/vldb/IoannidisNSS97","if5vzPT-qIAJ")).
pos(eqo("journals/vldb/KashyapS96","AaTvigmNyAcJ")).
pos(eqo("journals/vldb/KashyapS96","GlmJMsfDgXwJ")).
pos(eqo("journals/vldb/KashyapS96","h_g4xOpUq6wJ")).
pos(eqo("journals/vldb/KashyapS96","yWyvTMAVVzwJ")).
pos(eqo("journals/vldb/KraissW98","K0aOFYBWg3AJ")).
pos(eqo("journals/vldb/KraissW98","LMz7v87sxxYJ")).
pos(eqo("journals/vldb/LandauST95","SoejoqQZHg0J")).
pos(eqo("journals/vldb/LeeSC01","Hz_TU6kUj08J")).
pos(eqo("journals/vldb/LometS97","5EjrRrS54fsJ")).
pos(eqo("journals/vldb/MecellaP01","_JwGwZUTAOEJ")).
pos(eqo("journals/vldb/Navarro02","UDQsHc_ps4IJ")).
pos(eqo("journals/vldb/Navarro02","ZAtWrc5XBlQJ")).
pos(eqo("journals/vldb/PanagosB97","Ht4Yl1kJuxIJ")).
pos(eqo("journals/vldb/PapadiasS94","_ANyhrnP3CoJ")).
pos(eqo("journals/vldb/RamakrishnanSSS94","K9jUyjxRaCwJ")).
pos(eqo("journals/vldb/RamamurthyDS03","vGFdY2gG8YsJ")).
pos(eqo("journals/vldb/SaltenisJ02","HSEOZDaC8ZUJ")).
pos(eqo("journals/vldb/SwamiS95","S6TmnZKgmxwJ")).
pos(eqo("journals/vldb/TempletonHMB95","RKNGp2gmOTUJ")).
pos(eqo("journals/vldb/TsatalosSI96","--1aoAaGkgQJ")).
pos(eqo("journals/vldb/WidomS00","url:http://www.springerlink.com/index/JWGUMV8YDL893E3V.pdf")).
pos(eqo("journals/vldb/YangW03","Dpj8kCpIfSkJ")).
