pos(eqo("conf/vldb/KaushikBNS02","dL5oJVHK10kJ")).
pos(eqo("conf/vldb/YanL95","gHMpuR5VHJ4J")).
pos(eqo("conf/vldb/JarkeKL00","6c3XQZ-_HDUJ")).
pos(eqo("conf/sigmod/Wu99","oIDF-Jhm9CYJ")).
pos(eqo("conf/sigmod/AdaliBSS98","rYC-j_j4Yv0J")).
pos(eqo("journals/sigmod/BusslerFM02","MkHxLPaNdqoJ")).
pos(eqo("conf/sigmod/LiS98","Vxg-4KP7FfEJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","QOf55i6m6bUJ")).
pos(eqo("conf/vldb/SahuguetA99","VT_vPPmEIEIJ")).
pos(eqo("journals/sigmod/CampbellEM03","N9u28V6NZTIJ")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/sigmod/AnkerstBKS99","Hj3vyh0TJVsJ")).
pos(eqo("conf/vldb/AmielBDS94","hBak02oe1GMJ")).
pos(eqo("journals/vldb/BernsteinIR03","url:http://www.springerlink.com/index/RTCC57FUUW3CADRF.pdf")).
pos(eqo("journals/tods/Hellerstein98","q8m4M7OxSSAJ")).
pos(eqo("journals/sigmod/ACT-NET96","AWM-7zzaO7wJ")).
pos(eqo("conf/sigmod/ChenJDTW00","5Trj9q_RI8YJ")).
pos(eqo("journals/vldb/LinJF94","EgX8AQ2wfhAJ")).
pos(eqo("conf/vldb/WangYM97","0qth0oGxonUJ")).
pos(eqo("journals/sigmod/BoulosO99","yzbCsw2erkcJ")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("journals/sigmod/DogacDKOONEHAKKM95","_4ARkdpRArQJ")).
pos(eqo("conf/vldb/BrinkhoffK94","egvBPvtoaMMJ")).
pos(eqo("journals/vldb/ChanFGR02","LfS9Vr-FSZEJ")).
pos(eqo("conf/sigmod/ChristophidesACS94","g_ccBI89OZwJ")).
pos(eqo("conf/sigmod/GuhaRS98","ZStDO0kXD54J")).
pos(eqo("journals/sigmod/BergamaschiCV99","4C9A2HGs4qsJ")).
pos(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
pos(eqo("conf/sigmod/KornJF97","QLMiox_WLF4J")).
pos(eqo("journals/sigmod/RoantreeMH99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/CatozziR01","x_mqIy3GCmAJ")).
pos(eqo("conf/vldb/AgrawalS94","ujWZNcj2qkgJ")).
pos(eqo("journals/sigmod/PapazoglouH99","d5BG9F7_LGMJ")).
pos(eqo("conf/vldb/Shaw98","2CygtSE5o1UJ")).
pos(eqo("journals/sigmod/GerlaX03","KKiefntReoUJ")).
pos(eqo("conf/sigmod/Adelberg98","lyTJMJmpo8IJ")).
pos(eqo("conf/vldb/SrikantA95","KIPDo6ym8BUJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","LitNePng-ckJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","kDWGwVa8dykJ")).
pos(eqo("conf/sigmod/AdyaGLM95","bfcbZlt6vngJ")).
pos(eqo("conf/vldb/GarciaLL98","eJrqu6I2pHkJ")).
pos(eqo("journals/sigmod/HuangKL02","yyUMt1X2WXcJ")).
pos(eqo("conf/vldb/NiermanJ02","1NZsxf_zwF4J")).
pos(eqo("conf/vldb/Norvag99","6kiYvzSHBvEJ")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/sigmod/GrayHOS96","_pjwP11t_y8J")).
pos(eqo("journals/tods/Ross96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D232628%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/vldb/BohmAnY97","wIFnnUw2yZ0J")).
pos(eqo("conf/vldb/PapakonstantinouAG96","FdZnUd2bYYwJ")).
pos(eqo("conf/sigmod/OlstonJW03","D1h_jOHVyA4J")).
pos(eqo("conf/sigmod/BarclaySG00","Yiyko_0KiEIJ")).
pos(eqo("journals/sigmod/Halevy03","706PCMwA_E4J")).
pos(eqo("conf/vldb/LeeLWS97","3k61gi_ld_UJ")).
pos(eqo("conf/sigmod/SelfridgeSW96","V2Wysmw3ti4J")).
pos(eqo("conf/vldb/VassalosP97","2DJipXynj5wJ")).
pos(eqo("journals/vldb/PeckhamMD95","nhU_8O_9SY0J")).
pos(eqo("conf/vldb/Guting94","DCUu4jysue0J")).
pos(eqo("conf/sigmod/Brown99","itP4yy9sLUUJ")).
pos(eqo("journals/vldb/ShanmugasundaramSBCLPR01","ZQyBjtpbhvIJ")).
pos(eqo("conf/sigmod/FaloutsosL95","56AknoQlFB0J")).
pos(eqo("conf/sigmod/SionAP03","_L0DhCpFaXMJ")).
pos(eqo("conf/vldb/StolteA02","N3Bry6sSMw8J")).
pos(eqo("conf/vldb/WangZL99","9PJWqPPVlQwJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","lkreWUl_euYJ")).
pos(eqo("conf/vldb/JohnsonM98","gm9Ist67nJQJ")).
pos(eqo("conf/vldb/BaralisPT97","tyNO4U-fmrIJ")).
pos(eqo("conf/sigmod/KornJF97","atWqYF6LcuwJ")).
pos(eqo("conf/vldb/DyresonBJ99","FkPcMtplo18J")).
pos(eqo("journals/tods/MehrotraRKS98","tAnONC5J2W8J")).
pos(eqo("journals/sigmod/DarwenD95","Xa_whOlvG7gJ")).
pos(eqo("conf/vldb/StohrR01","jn3pvb3hRzwJ")).
pos(eqo("conf/vldb/Mohan02","eyxIItge9MQJ")).
pos(eqo("journals/tods/FukudaMMT01","lmXiI4fB9vgJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/sigmod/FaginKS03","tQZWeE_nsa0J")).
pos(eqo("conf/sigmod/AdaliCPS96","rmtEGXAXHKIJ")).
pos(eqo("journals/sigmod/UlusoyB96","LclVYrb7vJoJ")).
pos(eqo("journals/tods/DiaoAFZF03","lES-P-Whyd4J")).
pos(eqo("conf/vldb/IyerW94","5smJVUm1KAYJ")).
pos(eqo("journals/sigmod/Mani03","FgLCpqaf8C8J")).
pos(eqo("journals/tods/CeriFPT95","DoS7NkmUyYgJ")).
pos(eqo("journals/sigmod/MeltzerC98","-wQ-mpGIWdMJ")).
pos(eqo("conf/vldb/DesslochM97","CjtIFow-OWcJ")).
pos(eqo("conf/sigmod/RoussopoulosKV95","iIF6sbKPp30J")).
pos(eqo("conf/vldb/ChangG97","bZlpjMDZD5UJ")).
pos(eqo("journals/sigmod/Domingo-FerrerH98","9bRPA_aTYh4J")).
pos(eqo("conf/sigmod/BuchmannDZH95","4pl5VSwjXj0J")).
pos(eqo("journals/vldb/Sarawagi01","Xx6kw0tCeQIJ")).
pos(eqo("journals/sigmod/RoantreeMH99","7-Suml1GqBQJ")).
pos(eqo("conf/vldb/HeMYW03","cBe5X4EKjIEJ")).
pos(eqo("conf/sigmod/SzalayGKT00","5Q_6HLwZ2YIJ")).
pos(eqo("journals/vldb/CombiP01","8YoYzQtOgYoJ")).
pos(eqo("conf/vldb/NaumannLF99","gvua8jbnHPkJ")).
pos(eqo("journals/sigmod/GatziuKBF98","GlHmit1yw6AJ")).
pos(eqo("conf/sigmod/CherniackZ96","ZsHfcZJwFQQJ")).
pos(eqo("journals/sigmod/FreemanG96","RzHjAQK7XTsJ")).
pos(eqo("conf/vldb/WhiteheadSM97","CiYPfP3-5_kJ")).
pos(eqo("journals/sigmod/SilberschatzSU96","soiN2U4tXykJ")).
pos(eqo("conf/sigmod/Bonnet02","bqyt1789jJ8J")).
pos(eqo("journals/vldb/KieslingSSD94","bvFRYOianJUJ")).
pos(eqo("journals/vldb/ChakrabartiGRS01","PTmCbogNUpAJ")).
pos(eqo("journals/tods/CasatiCPP99","vFYKSBlZfK4J")).
pos(eqo("conf/vldb/LitwinNS94","FhyWT1pyLnUJ")).
pos(eqo("conf/sigmod/ViglasN02","2aeb_pBP7lcJ")).
pos(eqo("conf/sigmod/ChawatheRGW96","Xz0ZPMLOwcgJ")).
pos(eqo("conf/vldb/HaasKWY97","8Fy6YT12yIgJ")).
pos(eqo("conf/vldb/HaasKWY97","o_WTRsrkx_EJ")).
pos(eqo("conf/sigmod/CorralMTV00","TsShfxPwF6YJ")).
pos(eqo("conf/vldb/BunkerCCMMW01","bKfF2TdyKDwJ")).
pos(eqo("journals/vldb/FernandezFLS00","uo79zyqUB10J")).
pos(eqo("conf/sigmod/DeutschFS99","kDYpG4mLjLkJ")).
pos(eqo("conf/sigmod/Doherty98","7aUag74jtdIJ")).
pos(eqo("conf/sigmod/FegarasM95","MHubEDlndWYJ")).
pos(eqo("conf/vldb/LimWPVP02","HOmqQ9Na8wgJ")).
pos(eqo("conf/vldb/SchaeferBBJ00","url:http://portal.acm.org/citation.cfm%3Fid%3D645926.671845")).
pos(eqo("conf/vldb/LevyMS94","l-QHiSxClXcJ")).
pos(eqo("conf/vldb/ChaudhuriGN03","sAYCyUcugbYJ")).
pos(eqo("conf/sigmod/RiedewaldAA02","nQvBo5KHITYJ")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/citation.cfm%3Fid%3D375796")).
pos(eqo("conf/vldb/AilamakiDHS01","BQtJOT7gAIIJ")).
pos(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
pos(eqo("conf/vldb/HanF95","889ULwUj6XUJ")).
pos(eqo("journals/sigmod/Mackay99","PcnfzFfEY1wJ")).
pos(eqo("conf/vldb/SteenhagenABB94","Z3GUdeVh_4sJ")).
pos(eqo("conf/vldb/Schnase00","OdaRU442nm0J")).
pos(eqo("conf/vldb/ChristodoulakisTZ97","D0z0BDnbnFcJ")).
pos(eqo("conf/sigmod/JosifovskiSHL02","xA9KNostV4cJ")).
pos(eqo("conf/vldb/CarinoO98","lDNAWc5SrmIJ")).
pos(eqo("conf/vldb/Taylor00","Af_4cNCu3MwJ")).
pos(eqo("conf/vldb/ManolescuFKXO00","uJpbvfvNrW8J")).
pos(eqo("conf/vldb/OzdenBRS94","ARyxUwGOA10J")).
pos(eqo("journals/tods/GutingBEJLSV00","cURCJR2xHE0J")).
pos(eqo("conf/sigmod/AdaliCPS96","I8qFyTX4FhoJ")).
pos(eqo("conf/vldb/WeberSB98","6D0Qt6Sjp8cJ")).
pos(eqo("conf/sigmod/BraumandlKK99","X7jjMIXx8qUJ")).
pos(eqo("conf/sigmod/LakshmananNHP99","lduaYmELtHoJ")).
pos(eqo("journals/sigmod/LabrinidisR00","Wcbvsi-QDtcJ")).
pos(eqo("conf/sigmod/Team95a","P-jrIizJxEgJ")).
pos(eqo("conf/vldb/PoulovassilisS94","0BMQ7HirTaUJ")).
pos(eqo("conf/sigmod/BilirisDGJR94","lG6uSYhEGnQJ")).
pos(eqo("conf/vldb/SrinivasaK03","4iJ3Fd2xnUYJ")).
pos(eqo("conf/vldb/AgrawalLSS95","Zbv89s2eSnwJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","Elpbl8vygYoJ")).
pos(eqo("conf/sigmod/BarbaraI94","bMUUwjP72hwJ")).
pos(eqo("conf/sigmod/SarawagiTA98","SLmQWvsYtKYJ")).
pos(eqo("conf/sigmod/GillmannWSWW00","3bYCefUMXr8J")).
pos(eqo("conf/vldb/MarronL01","a3aecJJ58NIJ")).
pos(eqo("conf/vldb/GrustKT03","25xRkmL_4BsJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("journals/sigmod/Colliat96","y0HXub5QzkYJ")).
pos(eqo("conf/sigmod/AgrawalASY97","bDiNQAdf8nEJ")).
pos(eqo("journals/sigmod/Jhingran00","lrGge6mTVckJ")).
pos(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
pos(eqo("conf/sigmod/Jhingran00","uguuV9ATE1YJ")).
pos(eqo("conf/vldb/AilamakiDHS01","gUJrOpj89tQJ")).
pos(eqo("conf/sigmod/RafieiM97","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294143CI")).
pos(eqo("conf/vldb/CosleyLP02","BTalXWt3faUJ")).
pos(eqo("conf/sigmod/FegarasM95","LSWVPfB8TC4J")).
pos(eqo("conf/sigmod/ParkCY95","v9preswS6YUJ")).
pos(eqo("journals/sigmod/KappelR98","XmQ-hlR_wwkJ")).
pos(eqo("conf/vldb/ManegoldBK00","-7hYJxFD-AsJ")).
pos(eqo("journals/sigmod/BonifatiC00","EP5trsliqVMJ")).
pos(eqo("conf/vldb/GarofalakisG02","Hz7TBeGZRz8J")).
pos(eqo("journals/sigmod/LometBCLN98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/PopaVMHF02","qJ4lzBFzjdgJ")).
pos(eqo("conf/sigmod/DeutschFS99","De_3PkxkhzIJ")).
pos(eqo("conf/vldb/ChienTZ01","NoMSxmHAQ9YJ")).
pos(eqo("journals/sigmod/FlorescuLM98","rGNdajM-asAJ")).
pos(eqo("conf/vldb/Fecteau95","LhjvKpDcJKUJ")).
pos(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
pos(eqo("conf/sigmod/AgichteinG03","url:http://portal.acm.org/citation.cfm%3Fid%3D872851")).
pos(eqo("journals/sigmod/CaplinskasEV02","OhiGJ7Gy3KgJ")).
pos(eqo("conf/vldb/GarofalakisIO98","ReV4xpbiC6EJ")).
pos(eqo("conf/sigmod/BorkarDS01","8zFEVer1rBUJ")).
pos(eqo("conf/sigmod/GuptaHR97","wu0var7zLkEJ")).
pos(eqo("conf/vldb/MohanBWSZ00","zCY0pFken7wJ")).
pos(eqo("journals/sigmod/Giorgini03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959084%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Darwen96","url:http://portal.acm.org/citation.cfm%3Fid%3D245882.245886%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BertinoEH01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373684%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/KochBG03","xCbXlJHLR48J")).
pos(eqo("journals/vldb/AbiteboulCM98","XTa-ElbpjZ8J")).
pos(eqo("conf/sigmod/ImielinskiVB94","YCP5tWRHS_EJ")).
pos(eqo("conf/vldb/DattaDTVRF01","mPBmOUreSecJ")).
pos(eqo("journals/sigmod/SnodgrassAABCDEGJKKKLLRSSS94","64iWa-ZiPRcJ")).
pos(eqo("conf/vldb/AbiteboulBBCCDMMP03","fANcvlGA8WAJ")).
pos(eqo("journals/tods/WangBBJ97","I-yhgAxp9OQJ")).
pos(eqo("conf/vldb/Toivonen96","SVRZYX3nSGAJ")).
pos(eqo("conf/vldb/JiangSLB00","eZwzDZ7QhzoJ")).
pos(eqo("conf/sigmod/NgLK98","kJVhJ4ruw6sJ")).
pos(eqo("journals/sigmod/BoulosO99","0mk_QzaJKHEJ")).
pos(eqo("conf/sigmod/BarbosaMKL02","ueKnwQCE3nIJ")).
pos(eqo("journals/sigmod/Mackay99","tzUxfh8dD9sJ")).
pos(eqo("conf/vldb/GeorgeH98","2L-UFpDof3UJ")).
pos(eqo("journals/sigmod/EisenbergM99","ciavnyh4U8UJ")).
pos(eqo("conf/sigmod/VanceM96","-tCYCLPZLvYJ")).
pos(eqo("conf/sigmod/AdelbergGW97","zZo47Z-jVX4J")).
pos(eqo("conf/vldb/NipplM98","C5jVmNqIE4IJ")).
pos(eqo("conf/vldb/XieH94","jlnGGhVJ438J")).
pos(eqo("conf/vldb/Greco98","CCr8CUlHeNsJ")).
pos(eqo("journals/sigmod/JaegerF95","r1xWRhy7WVUJ")).
pos(eqo("conf/vldb/GarofalakisOS97","3p2a2ZKrCjcJ")).
pos(eqo("conf/sigmod/ChangG99","vjxJ_rBwdMkJ")).
pos(eqo("conf/sigmod/MarklL02","5fSqMJg7FV4J")).
pos(eqo("conf/vldb/BrownS95","yP4hDOd65VUJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","fsa72WmA67kJ")).
pos(eqo("conf/sigmod/YangYW00","JQuwW88-2_0J")).
pos(eqo("conf/vldb/FaloutsosG96","vwcVawlOJn0J")).
pos(eqo("conf/sigmod/ChooOLCGBPS96","I0KBB-n-eF8J")).
pos(eqo("conf/sigmod/ChangBCLLS00","dM9iTzhspEUJ")).
pos(eqo("conf/sigmod/ReveszCKLLW00","bx_A3QEqKhEJ")).
pos(eqo("conf/vldb/AgrawalS94","0haDaGr-V3oJ")).
pos(eqo("conf/sigmod/LitwinS00","fx0s58TJ75EJ")).
pos(eqo("conf/vldb/PetrovicBJ03","nIuz3dc8yHMJ")).
pos(eqo("journals/vldb/SteinbrunnMK97","nwwVf5FGX4QJ")).
pos(eqo("conf/vldb/RamaswamyMS98","WTYQ40Rn_tUJ")).
pos(eqo("conf/vldb/LaneEN00","EUNYWV7uBTwJ")).
pos(eqo("conf/vldb/AggarwalHWY03","ZFtAmPKKRBQJ")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","fm69LHjS4T0J")).
pos(eqo("conf/vldb/AilamakiDHW99","4bTXoodYyHMJ")).
pos(eqo("journals/sigmod/RamamrithamSSTX96","kezAM71rts0J")).
pos(eqo("conf/sigmod/SzalayGKT00","4yvrgPBJUBYJ")).
pos(eqo("journals/sigmod/BohmR94","wLNJcNvsulkJ")).
pos(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
pos(eqo("conf/sigmod/CruzALRZ97","YWWvQnGCpDEJ")).
pos(eqo("conf/vldb/FangSGMU98","z5tz9vybRmIJ")).
pos(eqo("conf/sigmod/BenediktCFFR03","T5ZdpquqfJ0J")).
pos(eqo("journals/sigmod/WestmannKHM00","aLDnCruGaqYJ")).
pos(eqo("conf/sigmod/Mohan02","eyxIItge9MQJ")).
pos(eqo("conf/sigmod/BreunigKKS01","h-tyLTytlh4J")).
pos(eqo("conf/vldb/GyssensL97","5ZEYqz95ZRAJ")).
pos(eqo("conf/vldb/AgrawalK02","qCvXLXmB6J8J")).
pos(eqo("journals/sigmod/SmithO99","-iis302p2MkJ")).
pos(eqo("conf/vldb/WienerN95","Y1lEnVPl6d8J")).
pos(eqo("conf/vldb/AnanthakrishnaCG02","FFKP2GRm2LEJ")).
pos(eqo("conf/sigmod/SchusterW01","59akjz-Qe9IJ")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","Syu5W-3uFFAJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ERqqWPMwU2sJ")).
pos(eqo("journals/vldb/WhiteD95","jKBaGqWJK2oJ")).
pos(eqo("conf/sigmod/BozkayaO97","37lliRw_cOQJ")).
pos(eqo("journals/sigmod/HanBP01","-OEJgpIAScMJ")).
pos(eqo("conf/vldb/NgC97","J7mY8RlpTKMJ")).
pos(eqo("journals/tods/Ng01","npCKXD_vLM8J")).
pos(eqo("conf/vldb/IshikawaSF98","TggGsXfF7PAJ")).
pos(eqo("conf/sigmod/BettiniWBJ95","wZkNJJn90yAJ")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/DraperHW01","sURGDemFSsUJ")).
pos(eqo("conf/vldb/VorugantiOU99","ItOlYY7ITt0J")).
pos(eqo("conf/sigmod/ONeilQ97","tK0HTC7qEmcJ")).
pos(eqo("conf/sigmod/GuhaRS98","Y8HMa1ZZE6sJ")).
pos(eqo("conf/sigmod/OConnellISWABCCLPWW96","O-TrhFwhKM8J")).
pos(eqo("conf/vldb/BerchtoldKK96","G__T5t9i4ZwJ")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/sigmod/TaninBS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245891%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/Cluet03","faRBjw1op8YJ")).
pos(eqo("journals/sigmod/RoantreeS02","xfrOR_G4_UoJ")).
pos(eqo("conf/vldb/AbiteboulAAACHHMMMMSTV99","zHCrzBCoweAJ")).
pos(eqo("conf/sigmod/Stonebraker98","LjfcoraomoEJ")).
pos(eqo("conf/sigmod/LuoKMPWLN02","zQfzn1t6Xq8J")).
pos(eqo("conf/vldb/GilbertKMS01","Xy_RpFaaxtQJ")).
pos(eqo("conf/vldb/KossmannRR02","iGlztgiSTe4J")).
pos(eqo("journals/sigmod/FrankNS02","YeD6vittJSMJ")).
pos(eqo("conf/vldb/KemperK94","qUfWV4VVxegJ")).
pos(eqo("conf/sigmod/MaddenH02","NXakCefUcdUJ")).
pos(eqo("conf/sigmod/BlakeleyP98","yotsUgKBK44J")).
pos(eqo("conf/vldb/LudasaherGM00","H4hHa7dQdSAJ")).
pos(eqo("journals/vldb/ChirkovaHS02","NdmocXlpq9QJ")).
pos(eqo("journals/sigmod/BernsteinHP00","FFzJxlpy6TsJ")).
pos(eqo("journals/tods/CaldersNW02","DSl0gT8EgR0J")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","_q3scPb8vbgJ")).
pos(eqo("conf/sigmod/RamaswamyK95","xnNIRajBihoJ")).
pos(eqo("conf/sigmod/IoannidisP95","bv21uJEzUwAJ")).
pos(eqo("conf/vldb/GrustKT03","CKiAavnrRH4J")).
pos(eqo("conf/sigmod/LangS01","OubIayl1628J")).
pos(eqo("conf/sigmod/NgLHM99","YemauUgIzlcJ")).
pos(eqo("conf/vldb/Mohan02","qbrkg2DRU3AJ")).
pos(eqo("journals/sigmod/FlorescuLM98","FCcDKONgJVYJ")).
pos(eqo("conf/vldb/Chiueh94","_YFIPoyVC3UJ")).
pos(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
pos(eqo("journals/sigmod/Bestavros96","Q2y53UR0g6oJ")).
pos(eqo("conf/sigmod/ClossmanSHKPB98","__YO1CE_aKcJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","I5JNUp7RoGgJ")).
pos(eqo("conf/vldb/SeegerBBKSDS01","WYGjQDmRwt8J")).
pos(eqo("conf/vldb/LitwinNS94","SnkWnX5WoKwJ")).
pos(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245909%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/AbrolLMMMRTWZ01","w9Ma-YjZHYkJ")).
pos(eqo("conf/vldb/BelussiF95","7BDCL140Kx4J")).
pos(eqo("conf/sigmod/ZhugeGHW95","2BGKvm5UIqAJ")).
pos(eqo("conf/vldb/BassiliadesV95","B1kJzsffXEwJ")).
pos(eqo("conf/vldb/YuV00","43N2r_SuYccJ")).
pos(eqo("journals/vldb/PucheralBVB01","q42RuW4_FogJ")).
pos(eqo("conf/vldb/Sheth96","xoD5vxZQJ8AJ")).
pos(eqo("conf/sigmod/ChawatheG97","5O88Bum19wAJ")).
pos(eqo("conf/sigmod/PatelD96","Y9z2OdhzSGQJ")).
pos(eqo("conf/sigmod/QuassWGHLMNRRAUW96","cJgYQWElaAgJ")).
pos(eqo("journals/sigmod/AndersonS94","aDk2IS_xwToJ")).
pos(eqo("conf/vldb/HuangJR97","WafY0er_xewJ")).
pos(eqo("conf/vldb/SistlaYH94","_jl3bN2QlE4J")).
pos(eqo("conf/vldb/MahnkeMS02","VhxIKKG8oWYJ")).
pos(eqo("conf/vldb/GravanoG97","CduLyvAaxVsJ")).
pos(eqo("conf/sigmod/BergstraesserBPS99","4Ha7Bs5Vq3MJ")).
pos(eqo("conf/vldb/Toivonen96","R3wCZGqY0nYJ")).
pos(eqo("journals/sigmod/Han98","qmIdBy8oNgEJ")).
pos(eqo("journals/sigmod/KambhampatiK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959086%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/LitwinN96","eKvrxzDXW0AJ")).
pos(eqo("conf/vldb/JensenL01","yUDkYbmDTXIJ")).
pos(eqo("conf/vldb/GantiLR00","V7byawkFcZMJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","2LdUbNy0hWwJ")).
pos(eqo("conf/vldb/McKennaBHT96","0tZaTV3W05wJ")).
pos(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
pos(eqo("journals/tods/Wijsen99","1C4Uh8BlYaEJ")).
pos(eqo("conf/vldb/EvangelidisLS95","hR9tpdTkYkcJ")).
pos(eqo("conf/sigmod/FaginKS03","dOY1djmoy04J")).
pos(eqo("conf/sigmod/GravanoCGP97","1xxRTUP64bwJ")).
pos(eqo("conf/sigmod/SagonasSW94a","ezmsDUMWUJEJ")).
pos(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
pos(eqo("journals/tods/ChaudhuriS99","QCFUIVkspywJ")).
pos(eqo("conf/vldb/FukudaMMT96","B8_0dK37qcsJ")).
pos(eqo("journals/sigmod/ShethBS99","uTsHgv9-zdUJ")).
pos(eqo("journals/vldb/FerrariAABC02","74D4YiDcxfcJ")).
pos(eqo("conf/vldb/ColletCS94","sZwecq6zUmMJ")).
pos(eqo("journals/vldb/VerykiosME03","khdP4spNnPoJ")).
pos(eqo("journals/vldb/MehtaGPN98","xd6denVlP5IJ")).
pos(eqo("conf/vldb/FlorescuLSY99","aUElZKC-txIJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/SubramanianV98","KxwymZ2AGNQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/LehnerSPC00","HQRcmyswIHcJ")).
pos(eqo("conf/sigmod/LiefkeS00","GFCznyVaj5UJ")).
pos(eqo("conf/vldb/Toivonen96","ut53pjEsmxEJ")).
pos(eqo("conf/vldb/HanF95","hDi8HKsDrV0J")).
pos(eqo("conf/sigmod/GrayHOS96","jH3KeKroDfQJ")).
pos(eqo("conf/vldb/SeshadriLR97","sw-iP0i7y6cJ")).
pos(eqo("conf/vldb/OzdenBRS94","vmqBhGBa8o0J")).
pos(eqo("conf/vldb/MignetMAC01","KkI-NuyDkDQJ")).
pos(eqo("conf/vldb/Mina98","ButmJWjGXusJ")).
pos(eqo("conf/vldb/GoldmanW97","vsbOhouYmEgJ")).
pos(eqo("journals/sigmod/PourabbasR00","odFtqwn5ZVcJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("journals/tods/KotidisR01","04utamFvle4J")).
pos(eqo("journals/vldb/PacittiS00","yXCROrOo320J")).
pos(eqo("journals/tods/CasatiCPP99","6F_cUJERo6sJ")).
pos(eqo("journals/sigmod/KuokFW98","3oLpUbHFATsJ")).
pos(eqo("conf/sigmod/Hidber99","Rn-E82gM1RQJ")).
pos(eqo("journals/vldb/HelmerM03","lqAgqxpXpxMJ")).
pos(eqo("conf/vldb/ChenJLP03","p7wumIMn_2oJ")).
pos(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
pos(eqo("conf/sigmod/BerchtoldK97","DNVHTz7tMywJ")).
pos(eqo("journals/sigmod/Date96","url:http://portal.acm.org/citation.cfm%3Fid%3D245882.245885%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BusslerFM02","RaOQG4YyzM4J")).
pos(eqo("conf/vldb/YiF00","DpQrWnvO7rEJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","5PisY7JvbzQJ")).
pos(eqo("conf/vldb/LakshmananSS96","0VHtbuWJCQUJ")).
pos(eqo("conf/vldb/KnorrN99","7lkCBMe603kJ")).
pos(eqo("journals/sigmod/Seshadri98","N9NdxNRvMMkJ")).
pos(eqo("conf/sigmod/KornackerMH97","J8sGEkYqAFcJ")).
pos(eqo("journals/tods/CliffordC94","OY6BjHhbz2cJ")).
pos(eqo("conf/vldb/SellisRF97","-ISlDUVRtjcJ")).
pos(eqo("journals/tods/GuoSW96","KoI8CRWkAYsJ")).
pos(eqo("journals/tods/BertinoBFS98","BTIrFatQWQsJ")).
pos(eqo("conf/sigmod/ChaudhuriDY95","0LRr6nTypA4J")).
pos(eqo("journals/sigmod/YaoG02","50aU57yUHVAJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","wTXunETZhPwJ")).
pos(eqo("conf/sigmod/KornackerMH97","O81USJg2EhwJ")).
pos(eqo("conf/vldb/AtzeniMM97","7Ivl47egSlUJ")).
pos(eqo("conf/sigmod/BrinMS97","COUbnKv6QeMJ")).
pos(eqo("conf/vldb/Slutz98","1blbGQk5ZpUJ")).
pos(eqo("conf/vldb/BaralisPT97","Cp7_R7yjRjQJ")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","wGxcAPsmHgIJ")).
pos(eqo("journals/sigmod/ShethBS99","NLklGN91cZgJ")).
pos(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
pos(eqo("conf/sigmod/ForlizziGNS00","4k4fUbwNV8UJ")).
pos(eqo("conf/vldb/CochranePM96","NRLEnDsPlOkJ")).
pos(eqo("conf/vldb/RothS97","eo2xdvfnpzsJ")).
pos(eqo("conf/vldb/PapakonstantinouAG96","Aiy1CuDyBNQJ")).
pos(eqo("journals/vldb/ShyyASL96","n8EWz5rQancJ")).
pos(eqo("conf/vldb/BohmMSW01","Uv3mhmUGwdcJ")).
pos(eqo("conf/vldb/BassiliadesV95","url:http://portal.acm.org/citation.cfm%3Fid%3D673137")).
pos(eqo("journals/sigmod/BernsteinBCDFGGHHJLMNPSU98","SRemicnI-ncJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("conf/sigmod/Mohan96","14cgU3tAHtgJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","PAfIruwVVakJ")).
pos(eqo("conf/sigmod/MamoulisP99","z9MQwq7G3GYJ")).
pos(eqo("conf/sigmod/AfratiLU01","k7zpSukSfYsJ")).
pos(eqo("conf/sigmod/HacigumusILM02","zMRWZaFMRhQJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
pos(eqo("conf/vldb/HuangJR97","nBHS2BTx-GkJ")).
pos(eqo("journals/sigmod/Abiteboul99","13NBtnaNfIEJ")).
pos(eqo("conf/sigmod/Kennamer98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D276373%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/BrinMUT97","A7Mm5kFK3zwJ")).
pos(eqo("conf/vldb/MendelzonV00","AQLsLBctUI4J")).
pos(eqo("journals/sigmod/MillerHHYHFP01","Zb2SExJNfkMJ")).
pos(eqo("conf/vldb/AcharyaFZ96","sSwdOhIGec0J")).
pos(eqo("conf/sigmod/LehnerSPC00","UFKz6Q0wVi4J")).
pos(eqo("conf/vldb/LuTD95","U9EN84liiRoJ")).
pos(eqo("journals/sigmod/Seshadri98","_nIg_hi8PAAJ")).
pos(eqo("conf/sigmod/ChungMS02","n8tscFMeBtwJ")).
pos(eqo("conf/sigmod/ZhaoDN97","b-Va1c3t13gJ")).
pos(eqo("conf/sigmod/ZhangZPTL03","S3lELcdpzTkJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","GruVHotOoPQJ")).
pos(eqo("conf/sigmod/BrunoCG01","SGmfFHnOf4IJ")).
pos(eqo("conf/vldb/ImielinskiB02","IQ_MbfJGh0kJ")).
pos(eqo("conf/vldb/HoelS95","7KsyQNj74A4J")).
pos(eqo("conf/vldb/PapadiasT01","2V2bnIgsY1kJ")).
pos(eqo("conf/sigmod/CluetDSS98","VZreOrzvcYEJ")).
pos(eqo("journals/tods/FormicaGM98","PtcmzsfKYrsJ")).
pos(eqo("journals/vldb/AbiteboulB95","Pkocuf5hMjYJ")).
pos(eqo("conf/vldb/BliujuteJSS98","wbGdc_RsI14J")).
pos(eqo("conf/vldb/MignetMAC01","XirELrPeTd4J")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/sigmod/TsotrasK96","9HEdn3A13BQJ")).
pos(eqo("conf/vldb/HelalL00","LPapCvY4RFkJ")).
pos(eqo("journals/sigmod/KiyokiKH94","xT3mwY4t5kEJ")).
pos(eqo("journals/tods/ChenHM95","pO6SFdVGt5QJ")).
pos(eqo("conf/sigmod/KimCK01","EYI-OULRIz8J")).
pos(eqo("conf/vldb/AbiteboulMRVW98","CDQHFdIK_cwJ")).
pos(eqo("journals/vldb/Navarro02","ZAtWrc5XBlQJ")).
pos(eqo("journals/vldb/AnGSVKI02","kBzZ1GUoa1AJ")).
pos(eqo("conf/vldb/AtzeniMM97","25kJ4dWczjEJ")).
pos(eqo("conf/vldb/GravanoG95","2nMktwioqOYJ")).
pos(eqo("conf/sigmod/GodfreySE98","-H3tXntLhowJ")).
pos(eqo("conf/vldb/Sullivan96","zGRQ_2im_9MJ")).
pos(eqo("conf/vldb/DoR02","bey6io4rYbgJ")).
pos(eqo("conf/sigmod/ZhangRL96","Koo3549nY2kJ")).
pos(eqo("journals/vldb/RamamrithamC96","xbpaZ5AHFV0J")).
pos(eqo("conf/sigmod/PapakonstantinouV99","Y7J0sm6WO2kJ")).
pos(eqo("conf/vldb/BlokWZPAKJ01","jxPqWIuxhvwJ")).
pos(eqo("conf/sigmod/MaddenFHH03","qz24tfFNHuoJ")).
pos(eqo("journals/sigmod/HalkidiBV02","SFs0XOMPphIJ")).
pos(eqo("conf/vldb/ZhouS03","NlDvk5J0WwEJ")).
pos(eqo("journals/sigmod/DiazJPa94","sG7PCEiN2xAJ")).
pos(eqo("journals/vldb/HalkidiNVV03","J0hrpRuvSgMJ")).
pos(eqo("conf/sigmod/GrayHOS96","J_QkWJ4HlOUJ")).
pos(eqo("conf/sigmod/GrayHOS96","Mopy3Yg3i60J")).
pos(eqo("journals/sigmod/Widom94","lAbG3uFZvVUJ")).
pos(eqo("journals/sigmod/Manola98","YFIXfqGgvL8J")).
pos(eqo("conf/vldb/ShaferA97","O4UcgdEM7vYJ")).
pos(eqo("journals/sigmod/BergamaschiCV99","rIm9uDX6PHUJ")).
pos(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
pos(eqo("conf/vldb/Brodie00","uFCOiVkDZE8J")).
pos(eqo("conf/sigmod/GardarinMP95","l-9pykkOVrkJ")).
pos(eqo("conf/sigmod/Arpaci-DusseauACHP97","OaNzji_-7tsJ")).
pos(eqo("conf/sigmod/DeshpandeNGS03a","pF6EW_yKYyYJ")).
pos(eqo("conf/sigmod/ThomasDM95","-NNuFjchxnMJ")).
pos(eqo("conf/sigmod/MaheshwariL97","VcVAYDLTty8J")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97","wF2-sxlGAu4J")).
pos(eqo("conf/vldb/BerchtoldKK96","KLzrIupmRloJ")).
pos(eqo("conf/sigmod/AgrawalCD02","iABZEL2Zoz8J")).
pos(eqo("conf/vldb/BerchtoldKK96","oKxmbGqneFwJ")).
pos(eqo("conf/vldb/ChengGKLLQS99","_pYZZxn2SjYJ")).
pos(eqo("journals/sigmod/VassiliadisS99","uexel5Cdu4wJ")).
pos(eqo("conf/sigmod/BlottRS96","pS2unAe-n_gJ")).
pos(eqo("conf/sigmod/YanMHF01","8hRWaIVZ2ykJ")).
pos(eqo("conf/sigmod/ChoALS03","MAdjH9lCsysJ")).
pos(eqo("conf/sigmod/RaoZML02","7Ucs6vmjHN0J")).
pos(eqo("conf/sigmod/CareyMN97","nM9bJESsWNoJ")).
pos(eqo("journals/tods/StoreyCDGS97","NL_8pNIYC-0J")).
pos(eqo("conf/sigmod/ColeG94","_6wwPJEGUiAJ")).
pos(eqo("conf/sigmod/HellersteinHW97","7dcgPQxHuCMJ")).
pos(eqo("journals/vldb/CuiW03","SaOd6rDz5ZgJ")).
pos(eqo("journals/sigmod/Lomet98","ytRfS_upf-0J")).
pos(eqo("conf/sigmod/CluetDSS98","q9yRMEgjLOAJ")).
pos(eqo("conf/sigmod/AgrawalES03","HypA8oN4PqsJ")).
pos(eqo("conf/sigmod/SarawagiTA98","wkgGoKqPVzQJ")).
pos(eqo("conf/sigmod/Sheth95","0CD9uUPdnbUJ")).
pos(eqo("conf/sigmod/CluetDSS98","W5KcKrhKY_YJ")).
pos(eqo("conf/sigmod/HanPY00","oeBeDPX7b9kJ")).
pos(eqo("journals/vldb/NgS98","I6aKO-jLBmgJ")).
pos(eqo("journals/vldb/MaedcheMS03","qKJ1c8D-95wJ")).
pos(eqo("journals/vldb/MehrotraKS97","6XxswNrUSk4J")).
pos(eqo("conf/sigmod/Grust02","F3sNx_8p3McJ")).
pos(eqo("conf/vldb/AgrawalCN00","Jx63MEaw52oJ")).
pos(eqo("conf/vldb/Tsur00","buI2V0eIcZoJ")).
pos(eqo("journals/vldb/RoySSSA98","vitgygjdz3AJ")).
pos(eqo("conf/sigmod/HeC03","MNmlxFx4l-8J")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/sigmod/FaloutsosL95","yFaUjmOQp1wJ")).
pos(eqo("conf/sigmod/RajagopalanML98","M2bWqRDDfkUJ")).
pos(eqo("conf/vldb/BargaP95","-lqp87W0EZ4J")).
pos(eqo("conf/vldb/LevyMS94","oHdZmd_4AaAJ")).
pos(eqo("conf/vldb/HammadFAE03","vfCFumS9QtkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","V6KNPMKdyagJ")).
pos(eqo("journals/sigmod/EisenbergM00","4mD1eFCHKKwJ")).
pos(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
pos(eqo("journals/sigmod/RashidS00","e0GH54HirssJ")).
pos(eqo("journals/sigmod/CaplinskasEV02","url:http://portal.acm.org/citation.cfm%3Fid%3D507338.507367%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/vldb/AgrawalAJL95","EyOHVek12P0J")).
pos(eqo("journals/sigmod/Qian95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D212022%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/PapadiasTSE95","oIc_goYCwh4J")).
pos(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/citation.cfm%3Fid%3D603867.603869%26coll%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/HulgeriS02","syoqNSarAscJ")).
pos(eqo("conf/sigmod/KotidisR99","ZknlFLRnqLYJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","r3GI5ly9cuIJ")).
pos(eqo("journals/sigmod/CarmelMS01","bolov3CrMYwJ")).
pos(eqo("conf/vldb/SavasereON95","N-o3NPu-nbIJ")).
pos(eqo("conf/vldb/CarinoJ98","LF2aUSIWko4J")).
pos(eqo("journals/sigmod/CeriFP99","zCbDZVfxWhAJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","yfTTlN56sCUJ")).
pos(eqo("conf/sigmod/HjaltasonS98","hFnyy0PFe1MJ")).
pos(eqo("conf/sigmod/GrayHOS96","imwZsCcZvFQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","lmhkvir9Z84J")).
pos(eqo("conf/vldb/HanF95","AOXjUq9H2cwJ")).
pos(eqo("journals/tods/FraternaliT95","8k0tS22xvPcJ")).
pos(eqo("conf/sigmod/WoelkBJOTU95","iFiv0xEJvIkJ")).
pos(eqo("conf/vldb/ManolescuFKXO00","uWqGLwi8VOgJ")).
pos(eqo("conf/sigmod/GarofalakisGRSS00","Kw_1o5V8Ot4J")).
pos(eqo("conf/vldb/ManolescuFKXO00","c22l_WX_ADwJ")).
pos(eqo("conf/sigmod/ShenoyHSBBS00","Z2CAABdqG5UJ")).
pos(eqo("conf/vldb/TreschPL95","1rPUqMFsS3AJ")).
pos(eqo("conf/sigmod/FernandezS96","iLwFjrX22vYJ")).
pos(eqo("conf/sigmod/TaoP02","fDWfHiQ6BR4J")).
pos(eqo("journals/sigmod/ConradHHKRSS99","nmEhI0tiWGAJ")).
pos(eqo("conf/vldb/GarofalakisI97","aCvCz2wg854J")).
pos(eqo("conf/vldb/GalhardasFSSS01","RZZjZ_7yJb8J")).
pos(eqo("journals/vldb/SteinbrunnMK97","0WXQjwXCy0QJ")).
pos(eqo("conf/vldb/SenkulKT02","g7HDbO4GCN4J")).
pos(eqo("conf/sigmod/BarbaraI94","F7azEOfg-Q0J")).
pos(eqo("conf/sigmod/ImielinskiVB94","cffLplmoKH4J")).
pos(eqo("conf/sigmod/AndersonBKW98","H6eMdbXATmkJ")).
pos(eqo("journals/sigmod/ChristoffelPSL98","F7QAoJ5PGekJ")).
pos(eqo("conf/vldb/CareyKSSS00","gZtFMFjW2n0J")).
pos(eqo("conf/sigmod/JagadishLS99","sh2u_UFoG74J")).
pos(eqo("conf/vldb/LuTD95","qX-uYKXVk7EJ")).
pos(eqo("journals/sigmod/McHughAGQW97","-i2fQfLpX2wJ")).
pos(eqo("conf/sigmod/WangSSZZW00","CaplZan57x4J")).
pos(eqo("conf/vldb/Brodie03","deEJ1JsF8RwJ")).
pos(eqo("conf/vldb/HeymannTKWRMF02","EAZ5Gz22bIUJ")).
pos(eqo("conf/vldb/HristidisGP03","B2rShDD99xwJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","zSvWnSVwLUYJ")).
pos(eqo("conf/vldb/DarFJST96","QdWd_yg3YGMJ")).
pos(eqo("journals/tods/BozkayaO99","0znTIa901S8J")).
pos(eqo("conf/sigmod/FaloutsosL95","j0EcM-BvshwJ")).
pos(eqo("conf/sigmod/RamaswamyRS00","o0vnSBVzRQcJ")).
pos(eqo("journals/vldb/ChakrabartiDAR98","AyDb4G2EiGwJ")).
pos(eqo("journals/vldb/CasatiSG01","347oyb_b7DAJ")).
neg(eqo("conf/sigmod/Epstein95","3QHHa4wNmMkJ")).
neg(eqo("conf/sigmod/Seshadri99","KrMPd4I9tUoJ")).
neg(eqo("conf/sigmod/SlivinskasJS01","url:http://www.springerlink.com/index/J805K662617N0160.pdf")).
neg(eqo("journals/sigmod/Snodgrass98c","6bV3NkpdPgQJ")).
neg(eqo("journals/sigmod/Barbara01","Ph7ZpmdNOPEJ")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","mg9ABNG06O4J")).
neg(eqo("conf/sigmod/Chakrabarti99","wSMRX5CsNVoJ")).
neg(eqo("journals/sigmod/AtzeniMM97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/FrankNS02","455gAnS7KvAJ")).
neg(eqo("conf/vldb/DongHLPW01","h7L27d2nzv8J")).
neg(eqo("conf/vldb/JagadishKNS99","dtWNJ3H4rS0J")).
neg(eqo("journals/sigmod/Hammer00","url:http://www.springerlink.com/index/V36953V81722J623.pdf")).
neg(eqo("journals/sigmod/MusickC99","url:http://doi.wiley.com/10.1002/tl.8007")).
neg(eqo("journals/tods/LiuM96","0fWnweML2ksJ")).
neg(eqo("journals/vldb/Antoshenkov97","url:http://portal.acm.org/citation.cfm%3Fdoid%3D263690.264347")).
neg(eqo("conf/vldb/Nori02","2OqatZYy5q4J")).
neg(eqo("conf/sigmod/ParkKKLPC98","DD1BqYiDyJEJ")).
neg(eqo("conf/vldb/BawaBA03","xrik_nC9RkkJ")).
neg(eqo("journals/vldb/WhiteD95","XmafDfYJdPUJ")).
neg(eqo("journals/sigmod/Ozsu03","hLgmkfsE_90J")).
neg(eqo("journals/sigmod/BoucelmaCGJLL02","Ecb0zBG1Y5cJ")).
neg(eqo("conf/vldb/May01","TJyp_PuBAWoJ")).
neg(eqo("journals/sigmod/OukselS99","atNo_T9JmBMJ")).
neg(eqo("journals/sigmod/WangD03","LumPK8L02WoJ")).
neg(eqo("journals/vldb/C94b","xAe8AYoG1qYJ")).
neg(eqo("journals/sigmod/Wedekind94","tzN6jRgEfdsJ")).
neg(eqo("conf/vldb/SimonD95","AfAPeJ_mK3kJ")).
neg(eqo("journals/sigmod/Ozsoyoglu99","sPNULY3x94UJ")).
neg(eqo("conf/sigmod/Bussler01","jBbj1ebPsV8J")).
neg(eqo("conf/vldb/PapadimitriouBF03","a2wqpKma5J4J")).
neg(eqo("conf/vldb/DeutschPT99","Vmeu18ccSHgJ")).
neg(eqo("journals/tods/CastanoAFP98","LMz7v87sxxYJ")).
neg(eqo("journals/vldb/GibsonKR00","odFtqwn5ZVcJ")).
neg(eqo("conf/vldb/GarofalakisG02","PZTESZecfnQJ")).
neg(eqo("conf/vldb/LuoNEW03","CN7qRr53peIJ")).
neg(eqo("conf/sigmod/ZaharioudakisC97","CmaQDIARCj0J")).
neg(eqo("journals/sigmod/Mendelzon98","vUvNBChnmacJ")).
neg(eqo("conf/vldb/Padmanabhan96","wlSdeqz9ub4J")).
neg(eqo("conf/vldb/ChienTZ01","dahew3ICBNgJ")).
neg(eqo("journals/vldb/SheikholeslamiCZ00","h0m2v7zwL7sJ")).
neg(eqo("journals/sigmod/Alonso94a","eKWFiVpjZtoJ")).
neg(eqo("journals/sigmod/Sidell96","bLbjFFkQJdIJ")).
neg(eqo("conf/sigmod/DattaDTVSR02","vXMwU21-7HMJ")).
neg(eqo("journals/sigmod/CoxEH96","F9xcVC8QkpgJ")).
neg(eqo("journals/sigmod/KuokFW98","VVMg76qMBuMJ")).
neg(eqo("journals/sigmod/Bussche00","xa435QKJZHcJ")).
neg(eqo("journals/sigmod/SommerGB02","IkX9Qqyf_kAJ")).
neg(eqo("conf/vldb/StohrMR00","y1L98Gk6XS8J")).
neg(eqo("conf/vldb/Chakrabarti02","ZrfHBiOdT-YJ")).
neg(eqo("journals/sigmod/Jonsson03","131hiUdWYSQJ")).
neg(eqo("journals/sigmod/KantM00","g3bpVfaBRZgJ")).
neg(eqo("conf/sigmod/AdiBEY01","cSCaEZboCIgJ")).
neg(eqo("journals/vldb/C94","bawpOoteZVIJ")).
neg(eqo("journals/sigmod/Franklin99b","UAjZbCsSEA8J")).
neg(eqo("conf/vldb/LaneEN00","cGZYJTMNdCEJ")).
neg(eqo("conf/vldb/DingGS00","NumTPN7NDIoJ")).
neg(eqo("journals/sigmod/Snodgrass00a","Aya8al-WXJMJ")).
neg(eqo("conf/sigmod/Mohan01","_mrRwbUbrwAJ")).
neg(eqo("journals/sigmod/JaegerF95","LubnrpJzrtAJ")).
neg(eqo("conf/sigmod/ChaudhuriN98","X5N075lVgBMJ")).
neg(eqo("conf/vldb/Sarawagi00","tjQHmHwUVyMJ")).
neg(eqo("journals/vldb/AtzeniM00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D130290%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/JaedickeM98","u99HqlQt9jEJ")).
neg(eqo("conf/vldb/GarofalakisG02","KP2snzQojpwJ")).
neg(eqo("conf/vldb/HasanM94","P0age7qyZacJ")).
neg(eqo("conf/sigmod/PapakonstantinouPV02","KLy1NRk4__MJ")).
neg(eqo("journals/sigmod/Liu03a","201dEhaoIQEJ")).
neg(eqo("journals/vldb/C95c","hhtp7i7oO6UJ")).
neg(eqo("conf/vldb/TaoPS02","VNILDnv9jmsJ")).
neg(eqo("conf/vldb/Mihalisin98","MdwCZg0RBHYJ")).
neg(eqo("conf/sigmod/KoudasS97","url:http://portal.acm.org/citation.cfm%3Fid%3D244461")).
neg(eqo("conf/vldb/BernsteinHJRW00","azGenr45ZMoJ")).
neg(eqo("conf/vldb/CarusoCGLM00","Uq6TyvdJBsYJ")).
neg(eqo("conf/vldb/SrinivasanDFCJYKTDB00","sA7TNyWDhPAJ")).
neg(eqo("journals/tods/BaralisW00","yxo4sa8_vQoJ")).
neg(eqo("journals/vldb/WidomS00","jHjguru02Z0J")).
neg(eqo("journals/sigmod/ForteHWDCVHFS99","-JJv3UyhH-8J")).
neg(eqo("conf/sigmod/Aggarwal03","c2PgXbSSAFcJ")).
neg(eqo("journals/vldb/AtluriJY03","FnuWr-EHhOUJ")).
neg(eqo("journals/sigmod/Qian95","Sbwz6V1QFqEJ")).
neg(eqo("journals/vldb/C95b","vZp7IW23xc0J")).
neg(eqo("conf/vldb/CeriM03","QJZ6O0CyRi4J")).
neg(eqo("conf/vldb/KraftSRM03","uVposQ8rUNQJ")).
neg(eqo("conf/vldb/AgrawalCN00","ylZFc8RNoeQJ")).
neg(eqo("journals/sigmod/McClatcheyV97","xoAU8DNc8fQJ")).
neg(eqo("journals/sigmod/Snodgrass98","lZcOENwQ108J")).
neg(eqo("conf/sigmod/RaoR98","tQZWeE_nsa0J")).
neg(eqo("journals/vldb/Amer-YahiaCLS02","url:http://doi.wiley.com/10.1002/tl.62")).
neg(eqo("conf/sigmod/StoltePAG03","uVposQ8rUNQJ")).
neg(eqo("journals/sigmod/LacroixB03","XDJnoNZzlGUJ")).
neg(eqo("journals/vldb/KraissW98","NJGZ_86lklEJ")).
neg(eqo("journals/sigmod/Snodgrass99","NzWzA4oLLi4J")).
neg(eqo("journals/sigmod/HalkidiBV02a","aJ9pQXEwRdUJ")).
neg(eqo("conf/vldb/MarronL01","c9pkCWR5tAQJ")).
neg(eqo("conf/sigmod/Bonnet02","url:http://www.springerlink.com/index/G541544051U4243L.pdf")).
neg(eqo("conf/vldb/Shmueli01","2cJnR7ZMqOcJ")).
neg(eqo("journals/sigmod/BestavrosLS96","lwbB467LzwEJ")).
neg(eqo("conf/sigmod/ShklarSKT95","F2ecYx97F2sJ")).
neg(eqo("journals/sigmod/Winslett03c","fIuGhhcZl-4J")).
neg(eqo("conf/vldb/PanRAMOHAMV02","PZTESZecfnQJ")).
neg(eqo("conf/sigmod/RadekeBBEKKN95","url:http://portal.acm.org/citation.cfm%3Fid%3D223784.223865%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3D223784%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/BaumgartnerFG01a","WdhkPQb0YJYJ")).
neg(eqo("journals/tods/BaralisW00","CgiCp6N9XZQJ")).
neg(eqo("conf/vldb/Malaika96","VkBiVwnSpjkJ")).
neg(eqo("journals/tods/GunopulosKMSTS03","8qxQypKxpe0J")).
neg(eqo("journals/vldb/C95c","9r8Vs6hyPsUJ")).
neg(eqo("journals/sigmod/Alonso95a","H4oUe4yfCsAJ")).
neg(eqo("conf/sigmod/Chamberlin03","rC41k8rY2nUJ")).
neg(eqo("conf/vldb/DarEGP98","uky90TOkkYgJ")).
neg(eqo("conf/sigmod/LahiriG01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D373713%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ConstantopoulosCP01","qjF9-b78VjIJ")).
neg(eqo("conf/vldb/IlyasAE03","8dOx0htEBGoJ")).
neg(eqo("journals/sigmod/Anisimov03","ne-Q_N17XJgJ")).
neg(eqo("conf/vldb/Koch03","R3uCcvIe63EJ")).
neg(eqo("conf/vldb/LakshmananNWZJ02","yyekAWZJtcYJ")).
neg(eqo("conf/vldb/Taylor00","mrG1M5J3c6UJ")).
neg(eqo("journals/sigmod/HasselbringHHKRRS00","0TmLofHcXyIJ")).
neg(eqo("journals/sigmod/MotroA03","oJVGBlXisiQJ")).
neg(eqo("journals/sigmod/Danish98","L7V3pn1XTykJ")).
neg(eqo("conf/vldb/StolteA02","eXOPAPjZPEkJ")).
neg(eqo("journals/sigmod/Chamberlin03","30i2w66KFhQJ")).
neg(eqo("journals/sigmod/Winslett01","oyg-YVIsxhkJ")).
neg(eqo("journals/sigmod/Liu02","url:http://ieeexplore.ieee.org/xpl/abs_free.jsp%3FarNumber%3D994411")).
neg(eqo("journals/vldb/C95b","Io-arejZMJgJ")).
neg(eqo("conf/vldb/CiliaHB02","Vt6DK4ikLpEJ")).
neg(eqo("journals/sigmod/PitouraAPSV03","6LDUEAXXk4UJ")).
neg(eqo("journals/sigmod/X95","MIlnlvL0q1YJ")).
neg(eqo("conf/sigmod/Colliat03","url:http://www.springerlink.com/index/G54431563W0L2845.pdf")).
neg(eqo("conf/vldb/BaralisW94","x-k7JsynxU4J")).
neg(eqo("conf/vldb/ChawatheCY94","mh2Lc6l9gwAJ")).
neg(eqo("journals/sigmod/CabreraLM01","NOXOEk0Adq8J")).
neg(eqo("conf/sigmod/Chakrabarti99","KGBUafE_0dMJ")).
neg(eqo("conf/vldb/QianZXP03","3xcsKWPVcCoJ")).
neg(eqo("journals/sigmod/Jonsson03","qOsozIYCBxgJ")).
neg(eqo("journals/sigmod/Dogac98","AQqDjGIpqOoJ")).
neg(eqo("conf/vldb/UrhanF01","FmKHpL60PJ8J")).
neg(eqo("conf/vldb/Sol01","H-AQePr2evUJ")).
neg(eqo("conf/vldb/CarinoOBS99","GRCHBH2Z2skJ")).
neg(eqo("conf/vldb/WangHH00","-aWBDznLsQMJ")).
neg(eqo("conf/vldb/Gupta96","QsPxm6zhtecJ")).
neg(eqo("journals/sigmod/DunhamH95","BAl7_FZ3gKIJ")).
neg(eqo("journals/sigmod/BestavrosLS96","P7VGXBo_mlsJ")).
neg(eqo("journals/vldb/WidomS00","Gwpc573207YJ")).
neg(eqo("conf/vldb/X00a","1c4CLqEV9IoJ")).
neg(eqo("conf/sigmod/ChenGK01","eH69_dCm18wJ")).
neg(eqo("journals/sigmod/Wiegand02","jPxhY-ThVL4J")).
neg(eqo("conf/vldb/SchaeferBBJ00","CJQX2idcM9wJ")).
neg(eqo("conf/sigmod/SeidlK98","rR4QSJHqOLMJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","oXiCtqK6qLsJ")).
neg(eqo("conf/vldb/Sripada02","HTT0I67Tf24J")).
neg(eqo("conf/vldb/Sarawagi00","GsYRviPBlHcJ")).
neg(eqo("conf/vldb/Bowker00","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D468964CI")).
neg(eqo("conf/vldb/SakuraiYKU01","6YjcqP0JAHAJ")).
neg(eqo("conf/sigmod/2003","SPYEQdkemmMJ")).
neg(eqo("journals/sigmod/Colliat96","gctYweHeMVwJ")).
neg(eqo("journals/tods/Galindo-LegariaR97","V__w6o558CAJ")).
neg(eqo("conf/sigmod/RamanH02","jszge3vBLGEJ")).
neg(eqo("journals/sigmod/Snodgrass00b","i5nEuutK3H4J")).
neg(eqo("conf/sigmod/IvesFFLW99","5A9npXKM5P8J")).
neg(eqo("journals/vldb/DeWittNSV96","Rb53udk1FmsJ")).
neg(eqo("journals/sigmod/Etzion99","RZSxYPTAJqMJ")).
neg(eqo("conf/vldb/WangZL03","HEzlZqo5xK8J")).
neg(eqo("journals/sigmod/ChengP03","0ZQnv8tOzBwJ")).
neg(eqo("conf/vldb/Gawlick96","UkGyMZnhiG8J")).
neg(eqo("conf/vldb/LeslieJBY95","dL5oJVHK10kJ")).
neg(eqo("conf/vldb/AdiBEY00","SudUID_rEy0J")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","yqPHOdEjWgkJ")).
neg(eqo("journals/sigmod/KantM00","EreE9p9OaicJ")).
neg(eqo("conf/sigmod/BohannonDGKLNS03","vzy-kP-XbyUJ")).
neg(eqo("conf/sigmod/BrodskySCE99","Sg3YKchNirgJ")).
neg(eqo("conf/vldb/MadhavanH03","GRQAnSkTZJ4J")).
neg(eqo("conf/sigmod/TsueiPK97","w855SyqMa9kJ")).
neg(eqo("journals/sigmod/PissinouSEMOPSTD94","url:http://portal.acm.org/citation.cfm%3Fid%3D192593.197420")).
neg(eqo("conf/sigmod/AshleyFHLNP95","I6M08XOGU6cJ")).
neg(eqo("journals/sigmod/CareyS99","abF7hKUAoH8J")).
neg(eqo("journals/sigmod/NgH95","r1q0mcu-uiEJ")).
neg(eqo("journals/sigmod/MeltonMJKSZ01","ywqM_Qst4qIJ")).
neg(eqo("conf/vldb/Shaw98","c5hUxotaynAJ")).
neg(eqo("conf/vldb/ChaHKK01","OZDdHHL-VukJ")).
neg(eqo("conf/vldb/BenediktCFRZZ02","_09-Ce4H5bkJ")).
neg(eqo("conf/sigmod/BressanGFJHKLMPQSS97","GwkmuRGwrKIJ")).
neg(eqo("conf/sigmod/PopaDST00","-o4L21BnoFIJ")).
neg(eqo("journals/tods/WandSW99","Eq1w4LPv_igJ")).
neg(eqo("journals/sigmod/SchmidtWKFCMB01","u8EpAoSCH4gJ")).
neg(eqo("conf/vldb/RamakrishnanR96","-NqtWdEMQkgJ")).
neg(eqo("conf/vldb/Amer-YahiaCD98","xFK4CkKj14EJ")).
neg(eqo("conf/sigmod/OzdenRSS96","uaT2hY6421UJ")).
neg(eqo("journals/sigmod/Date03","j7PjREB9HXcJ")).
neg(eqo("conf/vldb/OzsuVU98","z1csj57svuMJ")).
neg(eqo("conf/sigmod/Mohan96","mUMcLjidABoJ")).
neg(eqo("journals/sigmod/GalianoM03","W6IuS_2kJJgJ")).
neg(eqo("conf/vldb/CareyKSSS00","EkDalcUP3b0J")).
neg(eqo("conf/sigmod/Mylopoulos98","Lm2gLxYCbcwJ")).
neg(eqo("journals/vldb/C95b","VgK4bGeYKvQJ")).
neg(eqo("conf/sigmod/ArasuG03","InHODkK6LAIJ")).
neg(eqo("journals/tods/KrishnakumarB94","ociytUa_VLcJ")).
neg(eqo("conf/vldb/DeRose99","url:http://www.springerlink.com/index/R187542R1Q703R74.pdf")).
neg(eqo("conf/sigmod/NguyenS96","PAwpwv-OCVYJ")).
neg(eqo("conf/sigmod/ArefBV95","XX1ME2gtiWkJ")).
neg(eqo("journals/vldb/PanagosB97","YzTpzTyqn6sJ")).
neg(eqo("conf/vldb/MatiasVW00","CJZb0e9vmxAJ")).
neg(eqo("journals/vldb/KamelWS94","Ub1spyecCm0J")).
neg(eqo("conf/vldb/AnciauxBP03","BLPcDzgX3iQJ")).
neg(eqo("conf/vldb/AltinelBKMPR03","tsqBH6P4jMcJ")).
neg(eqo("conf/sigmod/IoannidisL94","ZxYlVKM6krAJ")).
neg(eqo("conf/vldb/DeWittKLPY94","2cnL-gQPLdcJ")).
neg(eqo("conf/vldb/Wadler01","url:http://doi.wiley.com/10.1002/he.17.abs")).
neg(eqo("conf/vldb/HuntAI01","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D560244CI")).
neg(eqo("conf/sigmod/WangPFY03","bqtRaOoJ87AJ")).
neg(eqo("conf/sigmod/BerchtoldK98","CPzROuDNZqgJ")).
neg(eqo("conf/vldb/Atal96","oH83TkzDt4cJ")).
neg(eqo("journals/tods/MayL02","tK1_3wGUIHsJ")).
neg(eqo("journals/sigmod/LenzVJS03","cUYJjeShqowJ")).
neg(eqo("conf/sigmod/ChenJDTW00","KbkYtYLFMCgJ")).
neg(eqo("conf/sigmod/Blakeley94","hAUDrHDhSlwJ")).
neg(eqo("journals/sigmod/Rosenthal98","4abl38Q9iH4J")).
neg(eqo("journals/sigmod/Widom96a","PrTq2V6nJdYJ")).
neg(eqo("conf/vldb/GyssensL97","n-OGL8lhX5MJ")).
neg(eqo("journals/vldb/CatarciSC97","UByN6paxEXwJ")).
neg(eqo("journals/sigmod/Snodgrass00b","2XdrxI20F-gJ")).
neg(eqo("journals/sigmod/Suciu97","QUqXK8yiAS4J")).
neg(eqo("journals/sigmod/Baeza-YatesN96","q8IL-AZTmcgJ")).
neg(eqo("conf/sigmod/Martin94","dTHfvsLNE3wJ")).
neg(eqo("journals/sigmod/NascimentoM99","vfTH6FzOpDAJ")).
neg(eqo("conf/vldb/ChaudhuriW00","6O_iRczxPCYJ")).
neg(eqo("journals/sigmod/CasatiDS00","fjCYNldsY88J")).
neg(eqo("conf/sigmod/DasuJMS02","gYWmOPwa7mwJ")).
neg(eqo("conf/vldb/DavisonG94","m3wyVzXgF4kJ")).
neg(eqo("journals/sigmod/WeikumSR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1099642%26type%3Dpdf")).
neg(eqo("conf/vldb/RusinkiewiczKTWM95","FQ3hcYpUtnwJ")).
neg(eqo("journals/sigmod/RossNO03","url:http://www.springerlink.com/index/KH080M1804080137.pdf")).
neg(eqo("journals/vldb/EvangelidisS97","r-0Pf3JmTvAJ")).
neg(eqo("conf/sigmod/ZadorozhnyRVUB02","tsQbSCfQTooJ")).
neg(eqo("journals/sigmod/Winslett03c","8mXNpMJzeQUJ")).
neg(eqo("conf/sigmod/2002","3hfYlLT5RyEJ")).
neg(eqo("journals/tods/HjaltasonS99","IVSbDCXr5OUJ")).
neg(eqo("journals/sigmod/SchlageterBHMSW95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245898%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/McHughW99","Pf0k8vsuiBIJ")).
neg(eqo("journals/sigmod/Ozsu02","1gz6awAKaR8J")).
neg(eqo("journals/sigmod/Jagadish01","bKfF2TdyKDwJ")).
neg(eqo("conf/vldb/WangHH00","BmJKyK7NlOoJ")).
neg(eqo("conf/vldb/JoshiBLL98","url:http://portal.acm.org/citation.cfm%3Fid%3D353053.353136%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3DSERIES406%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Information%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Franklin98a","vy7TejUX72kJ")).
neg(eqo("journals/vldb/TorpJS00","url:http://doi.wiley.com/10.1002/he.11002")).
neg(eqo("conf/vldb/Celis96","1FI22EuOk_8J")).
neg(eqo("conf/vldb/DeckerK03","WfIsfXAMl2UJ")).
neg(eqo("conf/sigmod/Shasha97","0tkyK_cWlbwJ")).
neg(eqo("journals/sigmod/GroskySF02","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637432%26coll%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/MuthOPW98","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D2109007CI")).
neg(eqo("journals/sigmod/Badia02","kXX7Qh-wElIJ")).
neg(eqo("journals/sigmod/Manola98","Mxb3c8sTLMkJ")).
neg(eqo("journals/vldb/RoySSSA98","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/09505849/1998/00000040/00000002/art00030%26unc%3D")).
neg(eqo("conf/vldb/Schnase00","gGTcBcX5FKsJ")).
neg(eqo("conf/sigmod/Ramanan02","tn5DPbAXvqQJ")).
neg(eqo("conf/sigmod/McAuliffeCS96","4bBje8qkHVgJ")).
neg(eqo("conf/vldb/WangSG03","gbJ8YaXGJvQJ")).
neg(eqo("conf/sigmod/FegarasSRM00","rbIVctdttUYJ")).
neg(eqo("conf/vldb/UrhanF01","itG_XrygxXIJ")).
neg(eqo("journals/sigmod/Jarke95","YkIvdNOC64cJ")).
neg(eqo("conf/vldb/KarayannidisTSPMRFEB02","MdwM2JqbNgUJ")).
neg(eqo("conf/sigmod/BohannonMR01","PMYJqNEwetwJ")).
neg(eqo("conf/sigmod/TatarinovIHW01","Z2ox6xDfA_8J")).
neg(eqo("conf/vldb/GarofalakisI97","ed9UPBsL0iQJ")).
neg(eqo("conf/sigmod/Suciu99","jIPGTMtgMTMJ")).
neg(eqo("conf/sigmod/ForlizziGNS00","Rhh7boxG52IJ")).
neg(eqo("conf/vldb/SeidlK97","FEtpgY3KSrQJ")).
neg(eqo("journals/sigmod/Snodgrass00c","url:http://www.springerlink.com/index/H618761246483650.pdf")).
neg(eqo("conf/vldb/LaudBCSR02","iF1fiu4T6OoJ")).
neg(eqo("conf/sigmod/Galindo-LegariaJ01","GisTIsix_zcJ")).
neg(eqo("conf/vldb/RezendeH98","kN3G2d6hk4YJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","p8W7eozXEfwJ")).
neg(eqo("journals/vldb/C95b","hrJxxxIpCYgJ")).
neg(eqo("conf/sigmod/GrayHOS96","1ReLrV51aOEJ")).
neg(eqo("conf/sigmod/KoudasS97","rjgIRwE0YBYJ")).
neg(eqo("conf/sigmod/Shasha97","rlGCB68tTMgJ")).
neg(eqo("journals/sigmod/Hammer03","ZeZn8fQkloUJ")).
neg(eqo("journals/sigmod/CalvaneseGLV03","G4d72hAN0q4J")).
neg(eqo("conf/vldb/Pound99","sQxIAZeq1bgJ")).
neg(eqo("journals/sigmod/PaepckeGRC00","4WOFIjjAJPgJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","xmcB4QG3GMsJ")).
neg(eqo("journals/sigmod/Snodgrass00b","xk9L_Fs8hAoJ")).
neg(eqo("conf/sigmod/DeshpandeNGS03","lrdmc8aOL50J")).
neg(eqo("conf/vldb/IyerW94","UwOgoqlmVyoJ")).
neg(eqo("journals/sigmod/Mendelzon98","7vPnh22isLwJ")).
neg(eqo("conf/sigmod/Norrie95","yUJoXttRVs4J")).
neg(eqo("conf/vldb/RamaswamyMS98","_aEC8CgKod0J")).
neg(eqo("journals/sigmod/RossCGLLM01","rpu1-jeYiO8J")).
neg(eqo("conf/sigmod/KaushikBNK02","81MDU6ycKvgJ")).
neg(eqo("conf/vldb/HaasKU99","6F_cUJERo6sJ")).
neg(eqo("conf/sigmod/JaedickeM98","fb50Eco-otgJ")).
neg(eqo("conf/sigmod/CruzJ99","HfcQDqmzCXoJ")).
neg(eqo("journals/sigmod/Bernstein98","qyXhN3CrVQ8J")).
neg(eqo("journals/sigmod/SayginVC01","yH8GRTxULRkJ")).
neg(eqo("journals/sigmod/MalaikaEM03","WmyHSqKKh8UJ")).
neg(eqo("conf/vldb/MehtaD95","piF2Jz9NkiAJ")).
neg(eqo("conf/sigmod/Galindo-Legaria94","BO9aC0ljMVgJ")).
neg(eqo("conf/vldb/JagadishKMPSS98","A4lUwOD7AeYJ")).
neg(eqo("conf/vldb/HardingLM03","1IGUgJnhCpoJ")).
neg(eqo("conf/sigmod/GravanoGT94","PAbiNlcxQGsJ")).
neg(eqo("journals/sigmod/GrayG97","f1wgD54UUKwJ")).
neg(eqo("journals/sigmod/Franklin98b","lsm05WjMep4J")).
neg(eqo("conf/sigmod/GuptaHR97","IM6PNCXCHScJ")).
neg(eqo("conf/vldb/CasatiDGS01","cAIvcFCeB6oJ")).
neg(eqo("journals/sigmod/Scholl01","ubuIOAT8m9MJ")).
neg(eqo("journals/sigmod/GottlobKP03","JZBxsPVHEbUJ")).
neg(eqo("conf/vldb/MengLLA03","GfoOVv_p1McJ")).
neg(eqo("journals/sigmod/VenkatraoP95","22yR9rN5xuQJ")).
neg(eqo("conf/sigmod/LeflerSW96","8JMn0KvLc-IJ")).
neg(eqo("journals/vldb/ClaussenKKW00","url:http://portal.acm.org/citation.cfm%3Fid%3D354546%26coll%3Dportal%26dl%3DACM")).
neg(eqo("conf/vldb/Garcia-MolinaLY98","U_1RdxVUZIAJ")).
neg(eqo("journals/vldb/C94","5oXHnCIXC4kJ")).
neg(eqo("conf/vldb/LaneEN00","83wqw4ciNWoJ")).
neg(eqo("conf/sigmod/LoR94","iuH1y5tciagJ")).
neg(eqo("journals/vldb/FangGM96","8_HtXom0CVgJ")).
neg(eqo("conf/vldb/TsoisS03","5JYRccSMeUwJ")).
neg(eqo("conf/sigmod/GarofalakisGR02","G_FNkKTfydkJ")).
neg(eqo("journals/sigmod/Franklin97","HwvBtBFSVPwJ")).
neg(eqo("journals/sigmod/Ozsu03a","1J7sfVUPBsgJ")).
neg(eqo("journals/sigmod/Roussopoulos98","ne-Q_N17XJgJ")).
neg(eqo("journals/sigmod/GatziuKBF98","9yn1lJyGJ0cJ")).
neg(eqo("journals/sigmod/RossGR03","u6SUM1C_ocwJ")).
neg(eqo("conf/vldb/AcharyaFZ96","Ymri5_WeKqkJ")).
neg(eqo("journals/vldb/C94b","pks3M2moxN0J")).
neg(eqo("conf/sigmod/BabcockO03","-wtySVIu85gJ")).
neg(eqo("conf/sigmod/QuassW97","6HZ5Of_s864J")).
neg(eqo("journals/sigmod/CfP99","Uxi_1uE_7z8J")).
neg(eqo("conf/sigmod/LiBCS00","mRIRFxOC8A8J")).
neg(eqo("conf/sigmod/CluetDSS98","8VPhLiWBzPsJ")).
neg(eqo("conf/vldb/FlorescuLS98","Eq1w4LPv_igJ")).
neg(eqo("conf/sigmod/LazaridisM01","QpzrKBh9U7wJ")).
neg(eqo("journals/tods/GoldmanL94","5Ilu35w-h5UJ")).
neg(eqo("journals/sigmod/ButtlerCCFHLPRX02","JX1Eda-ya_YJ")).
neg(eqo("journals/vldb/Antoshenkov97","YzTpzTyqn6sJ")).
neg(eqo("journals/sigmod/Winslett03","5J51gD5ZgZgJ")).
neg(eqo("conf/vldb/DeRose99","Hj3vyh0TJVsJ")).
neg(eqo("journals/sigmod/Cruz00","UwVwB-QdyjUJ")).
neg(eqo("journals/tods/HsuSY01","QqzkolVjPUoJ")).
neg(eqo("conf/sigmod/DeHaanTCO03","mZNcc1O3Nl8J")).
neg(eqo("journals/sigmod/Jonsson03","LmCMoEhIOCkJ")).
neg(eqo("journals/sigmod/BestavrosLS96","76X91rVs8BQJ")).
neg(eqo("journals/sigmod/Winslett03b","A97Nx4HBpK4J")).
neg(eqo("conf/vldb/GarofalakisOS97","yWTSDaRdSTcJ")).
neg(eqo("conf/sigmod/Chong98","SRSVoWsycEQJ")).
neg(eqo("conf/vldb/CeriFP99","mAa3Z0nZY1AJ")).
neg(eqo("journals/tods/CiacciaP02","XY4YyEglOssJ")).
neg(eqo("journals/vldb/RafieiM02","wVkpqzhO5eUJ")).
neg(eqo("conf/vldb/HvasshovdTBH95","VlDUc66xwCIJ")).
neg(eqo("conf/sigmod/Smith01","RJG51SMOacwJ")).
neg(eqo("journals/vldb/RamanRH00","BI4ZJqle2OcJ")).
neg(eqo("conf/vldb/ShivakumarGC98","a9r7oCYd7xIJ")).
neg(eqo("conf/vldb/DesslochM97","yZbJS0Cd6cAJ")).
neg(eqo("journals/sigmod/FreemanG96","KWriLe_1nBwJ")).
neg(eqo("journals/sigmod/Fong97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/LenzVJS03","AQwh4cJmh8IJ")).
neg(eqo("conf/vldb/BrownCC94","Hu4SI0SyZxEJ")).
neg(eqo("conf/vldb/KoudasMJ99","qN1APPIGZMMJ")).
neg(eqo("conf/vldb/KalusD95","TnI-lXrcUhgJ")).
neg(eqo("journals/sigmod/Vassilakis00","e1VDtDlm44oJ")).
neg(eqo("conf/vldb/TatbulCZCS03","n63MkRrhLIUJ")).
neg(eqo("journals/sigmod/ZobelMR96","Ip82P4QfKyEJ")).
neg(eqo("journals/sigmod/Aberer03c","Lmv5vIC6UTkJ")).
neg(eqo("journals/vldb/GarofalakisOS98","gtEB_lsPqZkJ")).
neg(eqo("journals/sigmod/Segev94b","VM1LnO9kjuoJ")).
neg(eqo("conf/vldb/ChaudhuriS01","E11cnBW7b3sJ")).
neg(eqo("conf/sigmod/ZaharioudakisCLPU00","qEl7ZsZgAzQJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97","J8j8ehIQMBMJ")).
neg(eqo("conf/sigmod/BouguettayaBH99","CmupOWMOqzkJ")).
neg(eqo("conf/sigmod/AvnurHLORRRW98","url:http://portal.acm.org/citation.cfm%3Fid%3D592192.592240")).
neg(eqo("journals/sigmod/WangD03","f30GUu7IhAcJ")).
neg(eqo("journals/sigmod/MeltonE02","zjqjS0Ol0OEJ")).
neg(eqo("conf/sigmod/KiesslingHFE01","FMRgogzzFKgJ")).
neg(eqo("conf/vldb/JohnsonA00","GpAP0Mj1zusJ")).
neg(eqo("conf/sigmod/GunopulosKTD00","gG3KqvrYi3IJ")).
neg(eqo("journals/tods/BeneventanoBS03","RWrhmPd907kJ")).
neg(eqo("conf/sigmod/Aggarwal03","F23uT_7Y0AkJ")).
neg(eqo("conf/sigmod/AgichteinGV01","url:http://portal.acm.org/citation.cfm%3Fid%3D500141.500228")).
neg(eqo("conf/vldb/ScheuermannSV96","98GD-x4I6Y4J")).
neg(eqo("journals/vldb/DeyBS96","29RpukpwmIQJ")).
neg(eqo("conf/vldb/HelmerWM98","BViQy6T_LWgJ")).
neg(eqo("conf/sigmod/AggarwalWY99","7ML1mmPqIooJ")).
neg(eqo("journals/tods/LiC01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000004/art00031")).
neg(eqo("conf/sigmod/Chong98","TOL8CzLs984J")).
neg(eqo("conf/sigmod/Bayardo98","Q1HQ5nAzZYkJ")).
neg(eqo("conf/vldb/YagoubFIV00","xfclJ4Dlt1MJ")).
neg(eqo("journals/sigmod/ShethGJRSWW96","RMTa8uQqH68J")).
neg(eqo("journals/sigmod/Winslett02","-H_tozyCqk4J")).
neg(eqo("journals/vldb/CasatiSG01","VfKOqNP73HYJ")).
neg(eqo("conf/vldb/ScheuermannSV96","MVpWlKy8HCgJ")).
neg(eqo("conf/sigmod/JagadishJOT01","8Yt1Mba9-wQJ")).
neg(eqo("conf/vldb/ChungCLL01","VfA2X4yzTmgJ")).
neg(eqo("conf/vldb/PoulovassilisS94","UeLjlfHU_gkJ")).
neg(eqo("journals/sigmod/Aberer03c","Ft6-PMWJb5gJ")).
neg(eqo("conf/vldb/ManolescuFKXO00","bSRLP5_ErFMJ")).
neg(eqo("conf/vldb/Nori02","owyHY5_wQg0J")).
neg(eqo("journals/tods/BertinoBFS98","xACnzf6RhVwJ")).
neg(eqo("journals/sigmod/Hanson99","qoX3FrqtN0IJ")).
neg(eqo("journals/vldb/HjaltasonS02","E4Doqfl7-DQJ")).
neg(eqo("conf/vldb/DidriksenGD95","qUfWV4VVxegJ")).
neg(eqo("conf/vldb/ChakravarthyKAK94","c_kkE1dO4g8J")).
neg(eqo("journals/vldb/AbbadiSW01","JYOv-gfnfcwJ")).
neg(eqo("journals/sigmod/RossHLW01","3oBT47PmeloJ")).
neg(eqo("journals/sigmod/BoucelmaCGJLL02","lIzeOJ5cqeMJ")).
neg(eqo("journals/sigmod/SnodgrassACFLLORRSV99","Kec3-6CGSxwJ")).
neg(eqo("conf/sigmod/SchusterW01","XNmtRWXQ9_4J")).
neg(eqo("conf/vldb/BaumgartnerFG01","iM5fj7fRHdsJ")).
neg(eqo("conf/vldb/ShatdalKN94","WMaO3Pdq85gJ")).
neg(eqo("conf/sigmod/Rodriguez-Martinez00","Jmc-99EyBKkJ")).
neg(eqo("conf/sigmod/Aulakh98","GZwDHAB2Eb8J")).
neg(eqo("journals/sigmod/LacroixB03","7JFq7k71BfUJ")).
neg(eqo("conf/sigmod/Mohan02","l44NsDIq2s8J")).
neg(eqo("conf/vldb/AgrawalK02","gvLGWTHk4S4J")).
neg(eqo("conf/sigmod/BryanMCLG94","BrNguNfeoMMJ")).
neg(eqo("conf/vldb/OhuraTPK02","94AZQoNhGrwJ")).
neg(eqo("journals/sigmod/BarbaraBFLS94","NlyAEteK5pMJ")).
neg(eqo("conf/vldb/CareyCNVDRSM99","_Qx_bO92tZEJ")).
neg(eqo("journals/sigmod/RossHKRRSS01","f0M4GzpWOIAJ")).
neg(eqo("conf/sigmod/ZhangMCMR02","Yt5y8_eGwTcJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","kTsQr81E7IoJ")).
neg(eqo("journals/tods/LechtenborgerV03","pY72Y49i-PsJ")).
neg(eqo("journals/sigmod/Ozsu02","zfiX8lsNrk8J")).
neg(eqo("journals/sigmod/CherniakV03","rNVEVKiw_o4J")).
neg(eqo("conf/vldb/FangSGMU98","btydMRJMBqoJ")).
neg(eqo("journals/sigmod/Snodgrass00b","FesYM2dcWWUJ")).
neg(eqo("journals/vldb/TanGO00","TPpmqOP1RHsJ")).
neg(eqo("conf/vldb/FlorescuLSY99","yUKk52rXf60J")).
neg(eqo("journals/sigmod/Chaudhri98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335477%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/NgWY01","1k2MLBqRtHoJ")).
neg(eqo("journals/vldb/GeorgeH00","BFR57Va2pL8J")).
neg(eqo("journals/sigmod/Etzion99","zmo6L4llsfkJ")).
neg(eqo("journals/sigmod/JenningsNF98","WExy9z3LgH0J")).
neg(eqo("conf/sigmod/TsueiPK97","uLe9IDz5U4cJ")).
neg(eqo("journals/sigmod/Bernstein98","oc6h69g4CAIJ")).
neg(eqo("journals/sigmod/RossAJS02","jl7UmF7Fs88J")).
neg(eqo("conf/vldb/LakshmananPH02","-hUVSdRv5UUJ")).
neg(eqo("conf/vldb/Deshpande00","O1Fhf_Xbrz0J")).
neg(eqo("conf/vldb/DagevilleZ02","Ws4VA2J2mwsJ")).
neg(eqo("conf/sigmod/Agarwal96","odS49u1Di0AJ")).
neg(eqo("journals/sigmod/Ahlberg96","PRL0iaGOqUQJ")).
neg(eqo("conf/vldb/GottlobKP02","OWe20vDyYO4J")).
neg(eqo("journals/sigmod/Snodgrass02","U7OwxK6Bpy4J")).
neg(eqo("conf/sigmod/2003","PIMQV7PK7gQJ")).
neg(eqo("conf/vldb/LempelM02","Vketm4E79yIJ")).
neg(eqo("journals/vldb/BenzakenD95","YeO04rpHehEJ")).
neg(eqo("journals/sigmod/LacroixB03","ZWgXFNaM2SUJ")).
neg(eqo("journals/sigmod/Eisenberg96","Iki6m7QwxGQJ")).
neg(eqo("conf/vldb/AlsabtiRS97","dkdyz41-JesJ")).
neg(eqo("journals/sigmod/Winslett03","x8s3QpPxgGYJ")).
neg(eqo("conf/sigmod/BressanGOT00","nvqnfbMzE64J")).
neg(eqo("conf/vldb/CareyCNVDRSM99","D878TsBWKV4J")).
neg(eqo("journals/sigmod/Franklin00a","E3wq5NhPhKoJ")).
neg(eqo("conf/vldb/Atal96","0N5RiRyC1esJ")).
neg(eqo("journals/sigmod/Abiteboul99","Z8zZYBJYVusJ")).
neg(eqo("journals/sigmod/Segev95","O71fxUOmV6oJ")).
neg(eqo("journals/vldb/DoanMDDH03","DS-teRqDvGgJ")).
neg(eqo("journals/sigmod/FrankNS02","FxmlwzOmNScJ")).
neg(eqo("journals/sigmod/Giorgini03","a6p2Lvm8YUIJ")).
neg(eqo("conf/vldb/MendelzonV00","PeGfdZFMJbwJ")).
neg(eqo("conf/sigmod/Ballinger94","ZXB1xI2h-HkJ")).
neg(eqo("journals/sigmod/JukicNV03","uEdEqdgiF_sJ")).
neg(eqo("conf/vldb/LingLL00","Z5rWzHBxtEEJ")).
neg(eqo("conf/vldb/Nori00","url:http://www.springerlink.com/index/M2P6764105750155.pdf")).
neg(eqo("conf/vldb/RamaswamyMS98","5nlcD-T8P_oJ")).
neg(eqo("journals/sigmod/Naughton00","wt0Qa1pYrqIJ")).
neg(eqo("journals/sigmod/OukselS99","7JRwRy6VapMJ")).
neg(eqo("conf/vldb/HalversonBKKRTVWND03","3fCNsAXb9RAJ")).
neg(eqo("journals/sigmod/Alonso94a","rBG6qX7DXL8J")).
neg(eqo("conf/sigmod/ZaianeHLCC98","897NTVaanAcJ")).
neg(eqo("conf/vldb/Keogh02","k3znuHyMD0oJ")).
neg(eqo("journals/tods/Ross96","JqV63F6w9GkJ")).
neg(eqo("conf/sigmod/ChristophidesCM96","aT1s65kGeT4J")).
neg(eqo("journals/sigmod/Suciu97","hcSwh21OUjYJ")).
neg(eqo("journals/sigmod/KuoM96","oB7qYK3HKiEJ")).
neg(eqo("conf/vldb/LeeWMS02","_iGkapqiXRMJ")).
neg(eqo("conf/sigmod/ChawatheRGW96","Urnpu4L7HQcJ")).
neg(eqo("conf/sigmod/Aggarwal03","Nn9a9gdUCpIJ")).
neg(eqo("journals/sigmod/Winslett03a","CIQYleTMMrAJ")).
neg(eqo("conf/vldb/BohannonLRSSS97","OuM0E0BhEXIJ")).
neg(eqo("conf/vldb/VenkataramanZ98","cuw2U0h7MmEJ")).
neg(eqo("conf/sigmod/RothAHCCFSTW96","8-Q8b0ufqK0J")).
neg(eqo("journals/vldb/Ozsu03","cCpHMzAXRnsJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","96SrVGnDmMoJ")).
neg(eqo("conf/sigmod/Toyama98","myKhIppwLC8J")).
neg(eqo("conf/vldb/KemperKW99","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D200111010672MT%26recid%3DA0032575AH")).
neg(eqo("conf/sigmod/KiepuszewskiMO98","url:http://portal.acm.org/citation.cfm%3Fid%3D592192.592247")).
neg(eqo("journals/sigmod/GobleR02","7MfXAAdBQ2EJ")).
neg(eqo("conf/vldb/StolteA02","3rBlVqEbkbcJ")).
neg(eqo("journals/sigmod/PuSW01","0lf4Qcm71JMJ")).
neg(eqo("journals/tods/LiuHD98","LrDcynd-pF8J")).
neg(eqo("conf/vldb/BaulierBKS98","gGspso3luCUJ")).
neg(eqo("conf/vldb/ChengGKLLQS99","SNX-QhXeObMJ")).
neg(eqo("journals/vldb/RamamrithamC96","SUAzZoGwCZsJ")).
neg(eqo("conf/sigmod/NguyenACP01","hItkYzZBjIkJ")).
neg(eqo("conf/sigmod/GarofalakisGR02","iCCdKyRrMeIJ")).
neg(eqo("journals/vldb/C95c","yPSayjo8q90J")).
neg(eqo("journals/vldb/WhiteD95","C2GyH8OmiwwJ")).
neg(eqo("journals/sigmod/KoksalAD98","YSQbMPHnheoJ")).
neg(eqo("journals/sigmod/McClatcheyV97","fBu3ZpBbd7oJ")).
neg(eqo("journals/sigmod/Weikum02","mFRMp2y5e-oJ")).
neg(eqo("conf/vldb/AltinelF00","nQniAn4VTpYJ")).
neg(eqo("conf/sigmod/BohannonMR01","eHxSWsqE8aQJ")).
neg(eqo("conf/sigmod/KemperKM98","tO0OVpz2o9sJ")).
neg(eqo("journals/sigmod/LudwigG00","H_yE_do5UCYJ")).
neg(eqo("journals/sigmod/Critchlow01","vbRBaexgiHIJ")).
neg(eqo("journals/vldb/SofferS98","CvdFz6_OjaEJ")).
neg(eqo("conf/sigmod/SimmenSM96","dfGNbob2p5sJ")).
neg(eqo("conf/sigmod/BarbaraI94","XIkChsdw3CoJ")).
neg(eqo("journals/sigmod/AbererCDDHPS03","PlYka1nkARYJ")).
neg(eqo("conf/vldb/GrustKT03","FiwkY7I9M70J")).
neg(eqo("journals/sigmod/Hammer00","VgbpNdSnE8gJ")).
neg(eqo("journals/sigmod/Ozsu02a","d9irNnP3q1YJ")).
neg(eqo("journals/sigmod/VassiliadisS99","am9zrb5azUQJ")).
neg(eqo("journals/sigmod/Winslett02b","yCQf5tQglE0J")).
neg(eqo("conf/sigmod/AmbiteABKMMMPT98","F7QAoJ5PGekJ")).
neg(eqo("conf/vldb/Hamilton99","url:http://www.springerlink.com/index/P13QGW28761T2060.pdf")).
neg(eqo("journals/sigmod/McClatcheyV97","5s7IbGEo_RIJ")).
neg(eqo("journals/sigmod/BergamaschiCV99","R7T2EvHC8kEJ")).
neg(eqo("conf/vldb/LeeLWS97","_fF5I-bkUSQJ")).
neg(eqo("journals/sigmod/Wu02","fVHqSuVlgPkJ")).
neg(eqo("journals/sigmod/BerzalM02","tMXkkRDxvkQJ")).
neg(eqo("conf/sigmod/FegarasSRM00","buI2V0eIcZoJ")).
neg(eqo("conf/vldb/GantiLR00","Bmzu3Zi62wYJ")).
neg(eqo("journals/tods/LakshmananLRS97","8EqLarkGNhwJ")).
neg(eqo("journals/sigmod/YanG95","e1rc9XS6rqkJ")).
neg(eqo("conf/vldb/StaudtJ96","NtuwSut1Pu4J")).
neg(eqo("conf/vldb/GalhardasFSSS01","NXLLAB_vdwsJ")).
neg(eqo("journals/sigmod/Snodgrass00a","mIySSspWhWwJ")).
neg(eqo("journals/vldb/BalkirO98","9numn7ZjHVQJ")).
neg(eqo("conf/vldb/ChatziantoniouR97","fxSDVtoN8gMJ")).
neg(eqo("conf/vldb/JagadishLRSS94","UU-Q_hMcN4kJ")).
neg(eqo("journals/sigmod/Ozsu02b","0qkVGJdL7OkJ")).
neg(eqo("conf/sigmod/CherniackZ98","ZgzJ5wHD04UJ")).
neg(eqo("journals/sigmod/Snodgrass00b","fJw9sVGiTRAJ")).
neg(eqo("conf/vldb/SeligmanBNSW95","BpgooVG4L34J")).
neg(eqo("journals/sigmod/Badia02","eja6xD6g_l4J")).
