neg(eqo("conf/sigmod/AchyutuniON96","eRSkDzxP1JcJ")).
neg(eqo("conf/sigmod/Adelberg98","lyTJMJmpo8IJ")).
neg(eqo("conf/sigmod/AggarwalPWYP99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219766%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BarbaraI94","l72i358_vjYJ")).
neg(eqo("conf/sigmod/BrodskyK95","TabFkjNTLMsJ")).
neg(eqo("conf/sigmod/Bussler01","ws5nhH_kMf4J")).
neg(eqo("conf/sigmod/ChanI99","fc8y9x82jqAJ")).
neg(eqo("conf/sigmod/Chaudhuri97","Lm25su-wny0J")).
neg(eqo("conf/sigmod/ChaudhuriMN98","Q8UBGvwM2pgJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","Y-kXztd20YQJ")).
neg(eqo("conf/sigmod/ChaudhuriMN99","clNmwzm-5acJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1066305%26type%3Dpdf")).
neg(eqo("conf/sigmod/ChenGM01","KFWBlRElPP0J")).
neg(eqo("conf/sigmod/ColbyGLMT96","E0_INl_086kJ")).
neg(eqo("conf/sigmod/ColeG94","pdPT2xonmkoJ")).
neg(eqo("conf/sigmod/GardarinMP95","0HMk-YUh4i8J")).
neg(eqo("conf/sigmod/Gettys95","PDPcuS1wtK4J")).
neg(eqo("conf/sigmod/HanKS97","lOoL6LtMxbQJ")).
neg(eqo("conf/sigmod/HeC03","MNmlxFx4l-8J")).
neg(eqo("conf/sigmod/HillyerS96","V-pwJ8K5ZTEJ")).
neg(eqo("conf/sigmod/IpeirotisGS01","V1dC_dJMWcUJ")).
neg(eqo("conf/sigmod/KanthRSB99","dxwn_0cdvRcJ")).
neg(eqo("conf/sigmod/KornackerMH97","1_skLvRBSbkJ")).
neg(eqo("conf/sigmod/LabioWGG00","xmE1380_4E4J")).
neg(eqo("conf/sigmod/LakhamrajuRSS00","qCvPRNWJZNEJ")).
neg(eqo("conf/sigmod/Larson01","CTvc34ghAtkJ")).
neg(eqo("conf/sigmod/Larson01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LiS98","TwMssljLk5cJ")).
neg(eqo("conf/sigmod/Mohan96","iXVERLO3KkQJ")).
neg(eqo("conf/sigmod/Mohan99","IWM2gExnQLkJ")).
neg(eqo("conf/sigmod/Mohan99","PKQ1dCQIwi0J")).
neg(eqo("conf/sigmod/Mohan99","enYJ_2U2NdUJ")).
neg(eqo("conf/sigmod/MoonSL00","wlsVclANhuQJ")).
neg(eqo("conf/sigmod/OlstonWL01","6MtRlhEClPEJ")).
neg(eqo("conf/sigmod/RoussopoulosKR97","Mg0A5yz-_wYJ")).
neg(eqo("conf/sigmod/SimmenSM96","qK-N8yVLSWUJ")).
neg(eqo("conf/sigmod/SrikantA96","b2CpxrjOMvEJ")).
neg(eqo("conf/sigmod/Stonebraker03","-IsKQcTBYi4J")).
neg(eqo("conf/sigmod/Stonebraker98","Z8zZYBJYVusJ")).
neg(eqo("conf/sigmod/Tajima96","zkbTv93Zp1UJ")).
neg(eqo("conf/sigmod/Team02","GJFDWzzCwGsJ")).
neg(eqo("conf/sigmod/WangWYY02","CTH39oyH-2IJ")).
neg(eqo("conf/sigmod/Weininger02","NAlOJiLQH34J")).
neg(eqo("conf/sigmod/Weininger02","iXkSngvyu08J")).
neg(eqo("conf/sigmod/Wu99","97o0rfRHu9MJ")).
neg(eqo("conf/vldb/AgrawalS94","3MzTom30SiMJ")).
neg(eqo("conf/vldb/BawaBA03","5BY1upUmSTUJ")).
neg(eqo("conf/vldb/BonczMK99","-qqHe0aRiAcJ")).
neg(eqo("conf/vldb/BunemanDHOW95","95LnCs7V35YJ")).
neg(eqo("conf/vldb/CarneyCCCLSSTZ02","1J26mBTxdS0J")).
neg(eqo("conf/vldb/CatozziR01","HghuvpVSK0AJ")).
neg(eqo("conf/vldb/ChawatheCY94","z_W8jZ203sUJ")).
neg(eqo("conf/vldb/ChoenniV00","AzH6iBXLchQJ")).
neg(eqo("conf/vldb/DattaRT99","8V2dT2HQ5PAJ")).
neg(eqo("conf/vldb/GardarinGT95","qRl7qbcdOjIJ")).
neg(eqo("conf/vldb/GarofalakisG01","zJ6gN0riEsQJ")).
neg(eqo("conf/vldb/GuptaHQ95","8Ojx7Me_oz0J")).
neg(eqo("conf/vldb/Hamilton99","faJ3Wc9vlzEJ")).
neg(eqo("conf/vldb/HellersteinNP95","KB9ZbekVNzoJ")).
neg(eqo("conf/vldb/HelmerM97","wBAI_ELrXkUJ")).
neg(eqo("conf/vldb/HinneburgLH03","xC2efRb-WrQJ")).
neg(eqo("conf/vldb/HumborstadSHT97","MdwCZg0RBHYJ")).
neg(eqo("conf/vldb/Ioannidis03","lHlbUdvFKBoJ")).
neg(eqo("conf/vldb/Johnson99","mjXz-bYKbTwJ")).
neg(eqo("conf/vldb/JosifovskiR99","rZJLf9oQ_hEJ")).
neg(eqo("conf/vldb/KemperK94","MCuFKbwcWIIJ")).
neg(eqo("conf/vldb/MaedaT01","ZDYplnfWlTgJ")).
neg(eqo("conf/vldb/MarronL01","9z2MfdOAAdIJ")).
neg(eqo("conf/vldb/MeoPC96","Opm5VlTzQTAJ")).
neg(eqo("conf/vldb/Mihalisin98","n_rTuaGP3gQJ")).
neg(eqo("conf/vldb/MillerHH00","RsafIbniZIMJ")).
neg(eqo("conf/vldb/MillinerBP95","FT4Sfn-Z7GUJ")).
neg(eqo("conf/vldb/Moerkotte02","fNRa-wXrLkkJ")).
neg(eqo("conf/vldb/MuthOPW98","Ycf_6A62gXoJ")).
neg(eqo("conf/vldb/NipplM98","Krm_iqCzlwsJ")).
neg(eqo("conf/vldb/PirotteZMY94","r-Jx4g42sfgJ")).
neg(eqo("conf/vldb/PossP03","t0AE_Iti5R0J")).
neg(eqo("conf/vldb/RamasamyPNK00","wR0R0jS5J6oJ")).
neg(eqo("conf/vldb/Selinger02","rYI3Unjq4LIJ")).
neg(eqo("conf/vldb/SripadaW94","cehAAlTq4s8J")).
neg(eqo("conf/vldb/Taylor00","BmAHJeWpLOEJ")).
neg(eqo("conf/vldb/WangSG03","mNdoyLMYPqgJ")).
neg(eqo("conf/vldb/XinHLW03","REXoXYDRw90J")).
neg(eqo("conf/vldb/ZellerK02","Y799jSppkKEJ")).
neg(eqo("journals/sigmod/Ahlberg96","_uAjDh22Y_EJ")).
neg(eqo("journals/sigmod/AlonsoCIM95","cRcH80h76hsJ")).
neg(eqo("journals/sigmod/AnyanwuS02","XGNIDg2kbnsJ")).
neg(eqo("journals/sigmod/AtkinsonDJPS96","aRP0U3sAp_wJ")).
neg(eqo("journals/sigmod/BargaL02","url:http://www.ingentaconnect.com/content/els/13891286/2002/00000038/00000004/art00263")).
neg(eqo("journals/sigmod/BorgidaCS98","iPbD7vPHzgYJ")).
neg(eqo("journals/sigmod/Chang03","kYYJq-JrCn0J")).
neg(eqo("journals/sigmod/Chaudhri98","lpuErTjd6dQJ")).
neg(eqo("journals/sigmod/Datta94","3TVyZeq1-i4J")).
neg(eqo("journals/sigmod/Dogac98","DJpFoidxWGMJ")).
neg(eqo("journals/sigmod/EisenbergM98a","4mD1eFCHKKwJ")).
neg(eqo("journals/sigmod/Fong95","sfQlMM3SXpAJ")).
neg(eqo("journals/sigmod/Franklin00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/Franklin97","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Franklin98b","ChmNvjU9V5sJ")).
neg(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
neg(eqo("journals/sigmod/Jagadish01","Ee-5tM_QosAJ")).
neg(eqo("journals/sigmod/JajodiaBBKMSW97","Re88E4BS2PAJ")).
neg(eqo("journals/sigmod/KuanL99","_qJmw0C7hQoJ")).
neg(eqo("journals/sigmod/Labrinidis01","FokoqHPFTNcJ")).
neg(eqo("journals/sigmod/Libkin99a","5Chw6HN64vEJ")).
neg(eqo("journals/sigmod/Liu03","FHm8-JUFIm4J")).
neg(eqo("journals/sigmod/NejdlSS03","GhCgLiSfDvcJ")).
neg(eqo("journals/sigmod/NestorovAM97","_RpELIR-GU8J")).
neg(eqo("journals/sigmod/Qian95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1058154%26type%3Dpdf")).
neg(eqo("journals/sigmod/Qian97","mH0vNFMcLxsJ")).
neg(eqo("journals/sigmod/Rosneblatt94","1ytPCccZhc8J")).
neg(eqo("journals/sigmod/Snodgrass99b","SOFwgIGjLnkJ")).
neg(eqo("journals/sigmod/Widom96","ntqMqfgRXM4J")).
neg(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601871%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/YauLMS99","url:http://www.springerlink.com/index/X10JQ5521256H588.pdf")).
neg(eqo("journals/sigmod/Zhang95","ql3mj0XUchsJ")).
neg(eqo("journals/tods/BohlenJS00","v5P_NFXdOR8J")).
neg(eqo("journals/tods/ChaudhuriS99","xxkUtjfGpvAJ")).
neg(eqo("journals/tods/Chen95","qNi-OiqW3sIJ")).
neg(eqo("journals/tods/FormicaGM98","UqcpU38WBwQJ")).
neg(eqo("journals/tods/GravanoGT99","nAJnhh70_0kJ")).
neg(eqo("journals/vldb/AgrawalHK03","A5qgqEDykVwJ")).
neg(eqo("journals/vldb/AslanM99","JTsL0MtwHLAJ")).
neg(eqo("journals/vldb/BeckerGOSW96","pK5bydjeZFIJ")).
neg(eqo("journals/vldb/EyalM01","url:http://www.springerlink.com/index/W52U41M0514161K2.pdf")).
neg(eqo("journals/vldb/KashyapS96","fmU5T2ppD5QJ")).
neg(eqo("journals/vldb/LinJF94","AygQeIp71_YJ")).
neg(eqo("journals/vldb/PeckhamMD95","url:http://www.ingentaconnect.com/content/els/09505849/1995/00000037/00000008/art98037")).
pos(eqo("conf/sigmod/AbadiC02","f2Lea-RN8dsJ")).
pos(eqo("conf/sigmod/AggarwalWY99","wjKnsQWl5ZoJ")).
pos(eqo("conf/sigmod/AgichteinGV01","z8s4kW1y7LMJ")).
pos(eqo("conf/sigmod/ChakrabartiM99","Jg81WYtxtZoJ")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","MNuT46WJZaQJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","D7w6TQwatE0J")).
pos(eqo("conf/sigmod/ChaudhuriD97","gY652XXjHB8J")).
pos(eqo("conf/sigmod/DeligiannakisR03","zMgbS5u_GwYJ")).
pos(eqo("conf/sigmod/DewanSHH94","GUdXGx4blW8J")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","SYV3r4_a5EsJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","_4ARkdpRArQJ")).
pos(eqo("conf/sigmod/FegarasM95","LSWVPfB8TC4J")).
pos(eqo("conf/sigmod/FegarasM95","ykGQlI-IaJkJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","WOCgxlV_LgoJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","fSKep047pbgJ")).
pos(eqo("conf/sigmod/GaoW02","PZTESZecfnQJ")).
pos(eqo("conf/sigmod/GeorgeH97","Ah9B3bWU0jEJ")).
pos(eqo("conf/sigmod/GotoK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D872837%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/GrayHOS96","5cw83MyqYrMJ")).
pos(eqo("conf/sigmod/GrayHOS96","_EUlTfqD0q0J")).
pos(eqo("conf/sigmod/GrayHOS96","jH3KeKroDfQJ")).
pos(eqo("conf/sigmod/GreenwaldK01","8but_7FuryIJ")).
pos(eqo("conf/sigmod/HanPY00","l4SlX8_cAeQJ")).
pos(eqo("conf/sigmod/HanWDPW02","nwWpGh3Mx7MJ")).
pos(eqo("conf/sigmod/IpeirotisGS01","bo7ArXlXypQJ")).
pos(eqo("conf/sigmod/Ivinskis95","9FaaDi_zGnEJ")).
pos(eqo("conf/sigmod/Jagadish94","eH69_dCm18wJ")).
pos(eqo("conf/sigmod/JajodiaSSB97","s3CWa_4OiW0J")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/MogiK96","ybgxHuCAS_8J")).
pos(eqo("conf/sigmod/Mohan96","14cgU3tAHtgJ")).
pos(eqo("conf/sigmod/Mohan96","f9JfEpe5a24J")).
pos(eqo("conf/sigmod/Mylopoulos98","2R-2i60g4MsJ")).
pos(eqo("conf/sigmod/NgWY01","TShyzmLNvtoJ")).
pos(eqo("conf/sigmod/QuassW97","9nkD3JyhE1kJ")).
pos(eqo("conf/sigmod/QuassW97","TfIJHxpZeJIJ")).
pos(eqo("conf/sigmod/RafieiM97","IlN1Z8UC688J")).
pos(eqo("conf/sigmod/SelfridgeSW96","V2Wysmw3ti4J")).
pos(eqo("conf/sigmod/SzalayGKT00","1kKap3JyndkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","4yvrgPBJUBYJ")).
pos(eqo("conf/sigmod/SzalayGKT00","YVCi81Vp9KAJ")).
pos(eqo("conf/sigmod/SzalayGKT00","zxOI0ZD8jeIJ")).
pos(eqo("conf/sigmod/TheodoulidisAACKS94","JFOg1ntEUvMJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","OMzQ1Ah1IVQJ")).
pos(eqo("conf/vldb/AggarwalHWY03","yFMUnqONfGwJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","mB8W6em6zi8J")).
pos(eqo("conf/vldb/AgrawalS94","551mHiCJRjoJ")).
pos(eqo("conf/vldb/AgrawalS94","XzSqN32OqgMJ")).
pos(eqo("conf/vldb/AgrawalS94","e5SJ3zgdwgEJ")).
pos(eqo("conf/vldb/Amer-YahiaCD98","W0L9nOcuhmIJ")).
pos(eqo("conf/vldb/AmsalegFG95","-9bXTTM_M4cJ")).
pos(eqo("conf/vldb/BettiniJWW02","tFuA828CptUJ")).
pos(eqo("conf/vldb/BohannonGKNS02","9BuBq-Tj0TUJ")).
pos(eqo("conf/vldb/ChakrabartiDAR97","zuIhKVPjN_IJ")).
pos(eqo("conf/vldb/ChakrabartiRS02","idfox84uNHUJ")).
pos(eqo("conf/vldb/ChangG97","bZlpjMDZD5UJ")).
pos(eqo("conf/vldb/ChangG97","wDrwjYtI4uEJ")).
pos(eqo("conf/vldb/ChatziantoniouR96","46FVYbhr0WoJ")).
pos(eqo("conf/vldb/DillKMRST01","_dtqcPU4NdkJ")).
pos(eqo("conf/vldb/FlodinR95","WmtiDGY_BdoJ")).
pos(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
pos(eqo("conf/vldb/GarofalakisG01","rcSfDxBif40J")).
pos(eqo("conf/vldb/GoldmanSVG98","b3H6Yt4f7hAJ")).
pos(eqo("conf/vldb/HvasshovdTBH95","LVitsyrkl9AJ")).
pos(eqo("conf/vldb/IpeirotisG02","3CSFFlEVviMJ")).
pos(eqo("conf/vldb/KamelF94","Gr7nw0PAH1sJ")).
pos(eqo("conf/vldb/KnorrN98","oCPpSbHhL3IJ")).
pos(eqo("conf/vldb/LakshmiZ98","3XwLBVHUBvAJ")).
pos(eqo("conf/vldb/LevyRO96","bbeft23FHAkJ")).
pos(eqo("conf/vldb/LevyRO96","biHvq8aD3_QJ")).
pos(eqo("conf/vldb/LuSL95","AvfsXnSTA24J")).
pos(eqo("conf/vldb/LuSL95","h7_7SZrI7M0J")).
pos(eqo("conf/vldb/NaumannLF99","gvua8jbnHPkJ")).
pos(eqo("conf/vldb/NaumannLF99","spErtT_VfeEJ")).
pos(eqo("conf/vldb/OuzzaniAB94","CgoUJ7DogcwJ")).
pos(eqo("conf/vldb/PapadimitriouBF03","pAvCmcv_-lMJ")).
pos(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
pos(eqo("conf/vldb/PolyzotisG02","krAZ7iDMEOQJ")).
pos(eqo("conf/vldb/RaoR99","N8XkcmIO0ysJ")).
pos(eqo("conf/vldb/RastogiS98","yztQfwBZU6EJ")).
pos(eqo("conf/vldb/SavasereON95","c4m40zywvWsJ")).
pos(eqo("conf/vldb/SavasereON95","r-BkIPtpff4J")).
pos(eqo("conf/vldb/SavasereON95","y1hmJODjq7UJ")).
pos(eqo("conf/vldb/Schoning03","4NM5WR1WtPcJ")).
pos(eqo("conf/vldb/SeligmanBNSW95","T6a86CQCuHoJ")).
pos(eqo("conf/vldb/SimonD95","lLARMvKaIQMJ")).
pos(eqo("conf/vldb/SrikantA95","nPkMLSiC3JQJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/Tygar98","Q8cPIOWKZZ4J")).
pos(eqo("conf/vldb/Tygar98","lWMzZgqNlSEJ")).
pos(eqo("conf/vldb/VenkataramanZ98","RGh6Gep4ym8J")).
pos(eqo("conf/vldb/YanA94","8j5i7YJQnNAJ")).
pos(eqo("journals/sigmod/AtkinsonDJPS96","5tuINV43CDUJ")).
pos(eqo("journals/sigmod/BestavrosLS96","RalvsjDuKzsJ")).
pos(eqo("journals/sigmod/BoscMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959085%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CaplinskasEV02","Axu6UlX-pPYJ")).
pos(eqo("journals/sigmod/ChienTZ01","cjBpI3TcSWsJ")).
pos(eqo("journals/sigmod/EisenbergM99","Ciq01lHglkAJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ERqqWPMwU2sJ")).
pos(eqo("journals/sigmod/FreemanG96","RzHjAQK7XTsJ")).
pos(eqo("journals/sigmod/GruenwaldBDGSSV99","url:http://portal.acm.org/citation.cfm%3Fid%3D333607.333616%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LeeC00","Knzz_bkGA00J")).
pos(eqo("journals/sigmod/ONeilG95","51gKshu0CWcJ")).
pos(eqo("journals/sigmod/OukselS99","S-LYnzS1K70J")).
pos(eqo("journals/sigmod/RashidS00","e0GH54HirssJ")).
pos(eqo("journals/sigmod/RosenthalS99","ZYnsLI6mz2cJ")).
pos(eqo("journals/sigmod/SlivinskasJS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565119%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Suciu01","KuYVVTlHVXcJ")).
pos(eqo("journals/sigmod/TianDCZ02","O6CCKkRxAbwJ")).
pos(eqo("journals/sigmod/TsotrasJS98","f3-E7x12K4gJ")).
pos(eqo("journals/sigmod/VetterliVS00","dAF5Z861mZgJ")).
pos(eqo("journals/tods/Hellerstein98","q8m4M7OxSSAJ")).
pos(eqo("journals/tods/Kuo96","VnenpXoUAmwJ")).
pos(eqo("journals/vldb/AbiteboulCM98","WzT3S2G1FjcJ")).
pos(eqo("journals/vldb/AtluriJY03","url:http://www.springerlink.com/index/589TQRPPVBXQ6LJN.pdf")).
pos(eqo("journals/vldb/BeckerGOSW96","BNQ07kOYONgJ")).
pos(eqo("journals/vldb/BeckerGOSW96","K53EIcG4ta8J")).
pos(eqo("journals/vldb/ChenHY97","IWZsSVPC6HMJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/HuntAI02","LiYp5oaDwbMJ")).
pos(eqo("journals/vldb/MecellaP01","_JwGwZUTAOEJ")).
pos(eqo("journals/vldb/PacittiS00","UvvmhI5lqbsJ")).
pos(eqo("journals/vldb/PacittiS00","yXCROrOo320J")).
pos(eqo("journals/vldb/PottingerH01","mpnnRdFUUJQJ")).
pos(eqo("journals/vldb/Sciore94","qHn6nrbVow8J")).
pos(eqo("journals/vldb/SivasankaranSTPR96","XX_3v0k3v6QJ")).
pos(eqo("journals/vldb/StonebrakerALPSSSY96","FnypYUw9pwEJ")).
pos(eqo("journals/vldb/WhangKW94","gLSOYwdwIQ8J")).
