neg(eqo("conf/sigmod/2003","7rn7AHVs1YUJ")).
neg(eqo("conf/sigmod/AbiteboulBCMM03","VJVukBz-cOMJ")).
neg(eqo("conf/sigmod/AbiteboulCM95","cu9DXtjeF24J")).
neg(eqo("conf/sigmod/AdaliBSS98","Vjh8QOeqfukJ")).
neg(eqo("conf/sigmod/Agarwal96","Yt-cq_4cfE8J")).
neg(eqo("conf/sigmod/AgrawalASY97","jZFEInt2ea8J")).
neg(eqo("conf/sigmod/Amer-YahiaCLS01","79CvVWsqYLcJ")).
neg(eqo("conf/sigmod/AntonJLPZZ02","E6Z68tQL1BsJ")).
neg(eqo("conf/sigmod/BertinoCF01","JSzfxAgs4pgJ")).
neg(eqo("conf/sigmod/BohmA96","qtwJ7XWG9JIJ")).
neg(eqo("conf/sigmod/BozkayaO97","5MTgNlhnyTgJ")).
neg(eqo("conf/sigmod/BozkayaO97","x2sLaJlFxAEJ")).
neg(eqo("conf/sigmod/BrinDG95","wgK6p4mDSIMJ")).
neg(eqo("conf/sigmod/CallanCD99","7qibwjtEf_UJ")).
neg(eqo("conf/sigmod/ChakrabartiM99","2TVYDBNYioIJ")).
neg(eqo("conf/sigmod/Chaudhuri97","hWiIngXs5I0J")).
neg(eqo("conf/sigmod/ChaudhuriGN02","CkbwvUsMShsJ")).
neg(eqo("conf/sigmod/ChenGK01","IGS3TtqfKUgJ")).
neg(eqo("conf/sigmod/ColbyKLMR97","0FohHTWs5toJ")).
neg(eqo("conf/sigmod/Galindo-Legaria94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083748%26type%3Dpdf")).
neg(eqo("conf/sigmod/GrayHOS96","HVLU2REPd4UJ")).
neg(eqo("conf/sigmod/GuptaS03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D984530%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ImielinskiVB94","DDyZXuEtGiwJ")).
neg(eqo("conf/sigmod/JoshiA01","H9bMRYKnXMQJ")).
neg(eqo("conf/sigmod/KemperMPS94","EPtaqugcCyMJ")).
neg(eqo("conf/sigmod/KoudasS03","VolW8qOYQWcJ")).
neg(eqo("conf/sigmod/LacroixSC98","6VAQeD6muakJ")).
neg(eqo("conf/sigmod/LaursenOP94","fTbCV3Lh8W0J")).
neg(eqo("conf/sigmod/LitwinS00","w9dSqojWgDAJ")).
neg(eqo("conf/sigmod/Meseck01","lDIliHA20WgJ")).
neg(eqo("conf/sigmod/NguyenACP01","j1SWzb-LThkJ")).
neg(eqo("conf/sigmod/PapadiasTFS03","MkRJhOROQjsJ")).
neg(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375796%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RothAHCCFSTW96","b5uRDGKYrcMJ")).
neg(eqo("conf/sigmod/SubramanianV98","url:http://www.springerlink.com/index/W14N79X43372P151.pdf")).
neg(eqo("conf/sigmod/Team95","ryaV3kTsJ2IJ")).
neg(eqo("conf/sigmod/WangCMSSZ94","ZM65itnp_E4J")).
neg(eqo("conf/sigmod/Weininger02","N3Bry6sSMw8J")).
neg(eqo("conf/sigmod/Zeller03","16tlmwHi2EwJ")).
neg(eqo("conf/vldb/AlonsoHST97","yPl_qJuXiNUJ")).
neg(eqo("conf/vldb/AnKR03","YUnPE4LSoR8J")).
neg(eqo("conf/vldb/Bar-YossefBCFW00","REXoXYDRw90J")).
neg(eqo("conf/vldb/BaralisPT97","5ESxDtUylD4J")).
neg(eqo("conf/vldb/BerckenS01","BJ8i-uzFQi4J")).
neg(eqo("conf/vldb/BertinoBFS96","RLes3oK5dI0J")).
neg(eqo("conf/vldb/BlottK02","4YHwRE1-slkJ")).
neg(eqo("conf/vldb/BohlenSS96","gcoLSYEk0HIJ")).
neg(eqo("conf/vldb/BouguettayaEMO01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604286%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/ChaudhuriS01","9GyNRTDkuqYJ")).
neg(eqo("conf/vldb/ChoG00","IiFIwlf39vIJ")).
neg(eqo("conf/vldb/ChristodoulakisTZ97","biOXpzHUZR4J")).
neg(eqo("conf/vldb/ClaussenKMP97","LAvs6Oe0ygMJ")).
neg(eqo("conf/vldb/Dayal99","VA8Ayx04ecIJ")).
neg(eqo("conf/vldb/DayalHL01","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/DeRose99","l7glyH7ltuQJ")).
neg(eqo("conf/vldb/DongHLPW01","XJPduAQD1PkJ")).
neg(eqo("conf/vldb/DongHLPW01","dMGxu3C4o2UJ")).
neg(eqo("conf/vldb/DonjerkovicR99","A9H8Y_FuONcJ")).
neg(eqo("conf/vldb/FlodinR95","WmtiDGY_BdoJ")).
neg(eqo("conf/vldb/Galindo-LegariaPK94","-CWAIqdOmwsJ")).
neg(eqo("conf/vldb/George98","xACnzf6RhVwJ")).
neg(eqo("conf/vldb/GuntzerBK00","EdQ4M7GEnzoJ")).
neg(eqo("conf/vldb/HoelS95","g_GL0oqW0_MJ")).
neg(eqo("conf/vldb/JensenL01","x02_XqK_fGMJ")).
neg(eqo("conf/vldb/KochBG03","1WAVR-zTvXAJ")).
neg(eqo("conf/vldb/KochBG03","aYDgo028zY8J")).
neg(eqo("conf/vldb/LabioG96","wKvSI4oZ8uEJ")).
neg(eqo("conf/vldb/LabrinidisR01","0GMNedjfVV0J")).
neg(eqo("conf/vldb/MillerHH00","ryYRSSmdBqIJ")).
neg(eqo("conf/vldb/Mohan02a","uCNkDoBniLgJ")).
neg(eqo("conf/vldb/NetzCBF00","Kz20knx0y5oJ")).
neg(eqo("conf/vldb/Pound99","iFsr76th3iYJ")).
neg(eqo("conf/vldb/RamaswamyMS98","GHxVWKcXxakJ")).
neg(eqo("conf/vldb/RamsakMFZEB00","ciNaUBiURnAJ")).
neg(eqo("conf/vldb/SeshadriLR96","CjHl-lb-eVsJ")).
neg(eqo("conf/vldb/ShahRS02","1burEBcmpyQJ")).
neg(eqo("conf/vldb/ShahRS02","GDmbzrUbyzAJ")).
neg(eqo("conf/vldb/UrhanF01","yAXWq_FbBEwJ")).
neg(eqo("conf/vldb/VelegrakisMP03","qv9JuA63NQMJ")).
neg(eqo("conf/vldb/VermeerA96","Z9mXIC2tjJ0J")).
neg(eqo("conf/vldb/WiesnerK01","29-iOCctAVgJ")).
neg(eqo("conf/vldb/WitkowskiBBFGSS03","lZGtV8TM9yoJ")).
neg(eqo("conf/vldb/YagoubFIV00","FJgqsdBgCX0J")).
neg(eqo("conf/vldb/ZimbraoS98","D6gxih90YU4J")).
neg(eqo("conf/vldb/ZouS98","nyQr22Sw804J")).
neg(eqo("journals/sigmod/Aberer01a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer02c","hjh9Ck2r0LgJ")).
neg(eqo("journals/sigmod/BarbaraBFLS94","3g09b2fr00wJ")).
neg(eqo("journals/sigmod/Bohlen95","6eheB6Kct4MJ")).
neg(eqo("journals/sigmod/Chen94","jgrW--UTkacJ")).
neg(eqo("journals/sigmod/DreyerDS94","2k9b6PGWBQIJ")).
neg(eqo("journals/sigmod/EisenbergM99a","e3s4OFTeBqwJ")).
neg(eqo("journals/sigmod/Franklin00","1Y-pKWumDNkJ")).
neg(eqo("journals/sigmod/Geller02","XWto9ZaCrPcJ")).
neg(eqo("journals/sigmod/GruenwaldBDGSSV99","jQ6eIao6R0EJ")).
neg(eqo("journals/sigmod/Han98","c_FpIBgyyN4J")).
neg(eqo("journals/sigmod/HaritsaS96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107512%26type%3Dpdf")).
neg(eqo("journals/sigmod/HellersteinHM03","LwZe_nTD__UJ")).
neg(eqo("journals/sigmod/KoubarakisTID03","J0hrpRuvSgMJ")).
neg(eqo("journals/sigmod/Liu01a","zc1TRuoDDwgJ")).
neg(eqo("journals/sigmod/Liu02","qyXhN3CrVQ8J")).
neg(eqo("journals/sigmod/Manola98","uM3ppXHRTtwJ")).
neg(eqo("journals/sigmod/NestorovAM97","M-1Nbw1n-PQJ")).
neg(eqo("journals/sigmod/OrlandicLS02","JosgAhRxCywJ")).
neg(eqo("journals/sigmod/OukselS99","gUeae8fAJc0J")).
neg(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
neg(eqo("journals/sigmod/Ritter98","kvg5RI6lxmcJ")).
neg(eqo("journals/sigmod/Snodgrass03","m-l6e98xxOsJ")).
neg(eqo("journals/sigmod/Widom96a","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/X94","Rba70P6SqQYJ")).
neg(eqo("journals/tods/CastanoAFP98","mU7LYYM7VN8J")).
neg(eqo("journals/tods/ChaudhuriS99","OSBjEyCgYUQJ")).
neg(eqo("journals/tods/KossmannS00","iGlztgiSTe4J")).
neg(eqo("journals/tods/LakshmananLN03","O05yYxasf6UJ")).
neg(eqo("journals/tods/LakshmananSS01","GDmbzrUbyzAJ")).
neg(eqo("journals/tods/TaoP03","T0AMa56Q7uIJ")).
neg(eqo("journals/vldb/AbbadiSW01","url:http://www.springerlink.com/index/589TQRPPVBXQ6LJN.pdf")).
neg(eqo("journals/vldb/BerchtoldKK97","rEBRhujejpIJ")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D765219%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.springerlink.com/index/589TQRPPVBXQ6LJN.pdf")).
neg(eqo("journals/vldb/Bertino94","NaZOZwlOw5UJ")).
neg(eqo("journals/vldb/GeorgeH00","ntvFXbc8gQwJ")).
neg(eqo("journals/vldb/Halevy02","dNM-avLn230J")).
neg(eqo("journals/vldb/HarderST99","hUXePN3VnYcJ")).
neg(eqo("journals/vldb/KamelWS94","BYoMaze-EQoJ")).
neg(eqo("journals/vldb/KraissW98","ufjnZovcIb4J")).
neg(eqo("journals/vldb/Li03","GfoOVv_p1McJ")).
neg(eqo("journals/vldb/LometS97","fI5o4MfWwzIJ")).
neg(eqo("journals/vldb/NgC98","hPWDomB8y6wJ")).
neg(eqo("journals/vldb/RoySSSA98","yC3NWP247K8J")).
neg(eqo("journals/vldb/ShethTP03","7glKHynv0xAJ")).
neg(eqo("journals/vldb/ShethTP03","tReKvTMB7pcJ")).
pos(eqo("conf/sigmod/AggarwalWY99","wjKnsQWl5ZoJ")).
pos(eqo("conf/sigmod/AgrawalASY97","7Of1HyK-VnkJ")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","WsCqveNDjjUJ")).
pos(eqo("conf/sigmod/Amer-YahiaFSX03","7-b5YXuGJS0J")).
pos(eqo("conf/sigmod/AntonJLPZZ02","89P3EdEDuOEJ")).
pos(eqo("conf/sigmod/AtzeniT97","i2LI1TWifbYJ")).
pos(eqo("conf/sigmod/BarclaySG00","Yiyko_0KiEIJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","arQIThq-W4gJ")).
pos(eqo("conf/sigmod/BaruGLMPVC99","nTC3FQGaT_YJ")).
pos(eqo("conf/sigmod/BaumannDFRW98","k3WA-AE7Sh4J")).
pos(eqo("conf/sigmod/Blakeley96","1fs-qN_SdH4J")).
pos(eqo("conf/sigmod/Blakeley96","xZxFCI120eUJ")).
pos(eqo("conf/sigmod/Bonnet02","bqyt1789jJ8J")).
pos(eqo("conf/sigmod/BrinDG95","7mNCkZ7D-R8J")).
pos(eqo("conf/sigmod/CareyDNAGS97","GmUD1o-uPvYJ")).
pos(eqo("conf/sigmod/CatarciS94","pryJrhEGI2sJ")).
pos(eqo("conf/sigmod/ChenR94","4Hhh-d__bksJ")).
pos(eqo("conf/sigmod/ChenWZ98","NuwRNfDPpTcJ")).
pos(eqo("conf/sigmod/ChristophidesCS00","hEOX0Vu4-JcJ")).
pos(eqo("conf/sigmod/DasuJMS02","zTF5z0v_nh0J")).
pos(eqo("conf/sigmod/DeutschFS99","2lypQEgzfb8J")).
pos(eqo("conf/sigmod/DeutschFS99","SYaXErlVlcAJ")).
pos(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
pos(eqo("conf/sigmod/DogacAEOADAOS94","AgBMhm_0uEIJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","oAO74aolStoJ")).
pos(eqo("conf/sigmod/DuSD95","Vl7gY6FsOOYJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","4bG39HmGrAQJ")).
pos(eqo("conf/sigmod/FukudaMMT96a","fSKep047pbgJ")).
pos(eqo("conf/sigmod/GarofalakisRRS99","z7J4u1sJ52cJ")).
pos(eqo("conf/sigmod/GrayHOS96","GFJeoxHwEnkJ")).
pos(eqo("conf/sigmod/GrayHOS96","_EUlTfqD0q0J")).
pos(eqo("conf/sigmod/Grust02","F3sNx_8p3McJ")).
pos(eqo("conf/sigmod/HullZ96","rI-T6ppfITQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","AhacU8AzwSUJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","CuoOi5jJXxQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","WkcdtG_5kfgJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","YCP5tWRHS_EJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","909hLNR8130J")).
pos(eqo("conf/sigmod/KotidisR99","nsASp-dCJBQJ")).
pos(eqo("conf/sigmod/KotidisR99","qzjtGDo7OuMJ")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/MotakisZ97","HPPJQPCzTEcJ")).
pos(eqo("conf/sigmod/Olson95","nJycrIdh5E4J")).
pos(eqo("conf/sigmod/PadmanabhanBMCH03","wI75uFSs0bwJ")).
pos(eqo("conf/sigmod/PalmerF00","eiA9HVOF2IsJ")).
pos(eqo("conf/sigmod/QuassW97","9nkD3JyhE1kJ")).
pos(eqo("conf/sigmod/SzalayGKT00","1kKap3JyndkJ")).
pos(eqo("conf/sigmod/SzalayGKT00","2ikeMlH1BGsJ")).
pos(eqo("conf/sigmod/SzalayGKT00","4yvrgPBJUBYJ")).
pos(eqo("conf/sigmod/SzalayGKT00","T4os1oo8vT4J")).
pos(eqo("conf/sigmod/UrhanFA98","ufjnZovcIb4J")).
pos(eqo("conf/sigmod/WolfsonSXZC99","Mib0RzjUNC0J")).
pos(eqo("conf/sigmod/WolfsonSXZC99","vwdWTx0dk7QJ")).
pos(eqo("conf/vldb/AbiteboulMRVW98","OqpwlRWdIMgJ")).
pos(eqo("conf/vldb/AltinelF00","SXHPvzZDrFMJ")).
pos(eqo("conf/vldb/BerckenS01","A46cpXEm-8AJ")).
pos(eqo("conf/vldb/BernsteinHSSZ97","d3QEeO83FmcJ")).
pos(eqo("conf/vldb/BrinkhoffK94","iZnVYeTnUbgJ")).
pos(eqo("conf/vldb/ChenDZ03","cCpHMzAXRnsJ")).
pos(eqo("conf/vldb/ChenJLP03","BGcx_nZKM4wJ")).
pos(eqo("conf/vldb/CherniackFZ01","WHWa6vBvwJ0J")).
pos(eqo("conf/vldb/DarmontS99","1GWsEQSvJmoJ")).
pos(eqo("conf/vldb/DattaRT99","gckQTLQjsj8J")).
pos(eqo("conf/vldb/Deshpande00","2DiLFd0rgPgJ")).
pos(eqo("conf/vldb/DiwanRSS96","HjDa9on7LzoJ")).
pos(eqo("conf/vldb/EsterKSWX98","MC7KlhmEQt8J")).
pos(eqo("conf/vldb/FaloutsosJS97","YOmjd7tKrWgJ")).
pos(eqo("conf/vldb/FerrandinaMZFM95","9rofzgQ6HtcJ")).
pos(eqo("conf/vldb/GarofalakisRS99","poso7AKokFMJ")).
pos(eqo("conf/vldb/Hallmark95","tiAgO7G7YuAJ")).
pos(eqo("conf/vldb/HelmerNM03","8-HpAN0xpjcJ")).
pos(eqo("conf/vldb/LuSL95","h7_7SZrI7M0J")).
pos(eqo("conf/vldb/MadhavanBR01","66dWDpWjbbwJ")).
pos(eqo("conf/vldb/MohaniaS94","JORYEDHKYSMJ")).
pos(eqo("conf/vldb/Moni96","gbjXwFztQTsJ")).
pos(eqo("conf/vldb/NaumannLF99","MEQuU1E4vdoJ")).
pos(eqo("conf/vldb/PapadiasT01","2V2bnIgsY1kJ")).
pos(eqo("conf/vldb/RossS97","5Y_l1wlPo04J")).
pos(eqo("conf/vldb/ShengBDM02","ZQdRRjCxEX0J")).
pos(eqo("conf/vldb/SkubiszewskiV97","MJAw_2C6ErAJ")).
pos(eqo("conf/vldb/SubietaKL95","gEFY87Ma0XUJ")).
pos(eqo("journals/sigmod/ACT-NET96","FTDeavdkHpsJ")).
pos(eqo("journals/sigmod/ACT-NET96","RzsJoG-0KaIJ")).
pos(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776994%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Barbara01","U8tEHzJ2Xj0J")).
pos(eqo("journals/sigmod/BarbaraS97","l72i358_vjYJ")).
pos(eqo("journals/sigmod/BarclayBGS94","v1aol6mmLdMJ")).
pos(eqo("journals/sigmod/BuchnerM98","PF-rFkrW2nIJ")).
pos(eqo("journals/sigmod/BuchnerM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D306124%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BusslerFM02","ql3mj0XUchsJ")).
pos(eqo("journals/sigmod/CaleroPR03","zWoRcQffsq8J")).
pos(eqo("journals/sigmod/ChaudhuriD97","1oCTwvC32jkJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","Tagq11E6HfAJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","mzlMwJTYaDcJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","oahM5itk_dAJ")).
pos(eqo("journals/sigmod/Cingil02","2K6rhX16hXwJ")).
pos(eqo("journals/sigmod/Colliat96","3FAQV305QD0J")).
pos(eqo("journals/sigmod/Finkelstein95","gbnxN3MpucMJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","93C5Prxx5YcJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","HJRR7GGfD6sJ")).
pos(eqo("journals/sigmod/GatziuKBF98","YERfAnxw2RcJ")).
pos(eqo("journals/sigmod/GerlaX03","KKiefntReoUJ")).
pos(eqo("journals/sigmod/HasanMV96","bLbjFFkQJdIJ")).
pos(eqo("journals/sigmod/LightstoneLZ02","7TYVQTwq9FIJ")).
pos(eqo("journals/sigmod/MeltzerC98","-wQ-mpGIWdMJ")).
pos(eqo("journals/sigmod/PapianiWDN99","EHBFbc1r9oIJ")).
pos(eqo("journals/sigmod/Qian97","url:http://portal.acm.org/citation.cfm%3Fid%3D248603.248618%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/RoddickABDEGHLMMMW00","eA8gNVxHRJ4J")).
pos(eqo("journals/sigmod/Snodgrass03b","PmIVKWJ5_V4J")).
pos(eqo("journals/sigmod/Suciu02","Ikk1rb4o66UJ")).
pos(eqo("journals/sigmod/Winslett02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565127%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/WinslettCDHZZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601881%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/BaralisCP96","hiNs_zWcwlgJ")).
pos(eqo("journals/tods/FranklinCL97","-iaSLKFHwUkJ")).
pos(eqo("journals/tods/Galindo-LegariaR97","g4p3K22hY_oJ")).
pos(eqo("journals/tods/HjaltasonS99","wjKElSLd3lQJ")).
pos(eqo("journals/tods/Ross96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D232628%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/tods/YanG94","Xh9AnV9p-REJ")).
pos(eqo("journals/vldb/AgrawalHK03","NDKJPUgy_K4J")).
pos(eqo("journals/vldb/BarbaraI95","UI4WYndJlyIJ")).
pos(eqo("journals/vldb/BarbaraI95","bTYTn8VG5hIJ")).
pos(eqo("journals/vldb/BerendtS00","_0meUij3ZJEJ")).
pos(eqo("journals/vldb/BerendtS00","zh9CAewEvisJ")).
pos(eqo("journals/vldb/GutingS95","CBHicx5w3ocJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/GutingS95","dm3xutmyi_0J")).
pos(eqo("journals/vldb/HalkidiNVV03","C_X4Frh2wHIJ")).
pos(eqo("journals/vldb/HalkidiNVV03","J0hrpRuvSgMJ")).
pos(eqo("journals/vldb/HalkidiNVV03","tFe0FjHYe2MJ")).
pos(eqo("journals/vldb/HarderST99","KGyKFmRfspAJ")).
pos(eqo("journals/vldb/LometS97","qjLiaKLJ6eQJ")).
pos(eqo("journals/vldb/PoulovassilisS96","B87s9MFTeZ8J")).
