neg(eqo("conf/sigmod/AbiteboulCM95","WzT3S2G1FjcJ")).
neg(eqo("conf/sigmod/Aggarwal02","YfRa7vdel-kJ")).
neg(eqo("conf/sigmod/AggarwalWY99","a_85EbhFlUIJ")).
neg(eqo("conf/sigmod/AggarwalY01","1YpHQXqkPv4J")).
neg(eqo("conf/sigmod/BerckenDS00","3IFlpeKgLlAJ")).
neg(eqo("conf/sigmod/BerensonBGMOO95","N3FQmFIHkT4J")).
neg(eqo("conf/sigmod/BrodskyK95","zNuhEWxo2iUJ")).
neg(eqo("conf/sigmod/BrownCL96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107512%26type%3Dpdf")).
neg(eqo("conf/sigmod/CallanCD99","ZvCgA0EEmzkJ")).
neg(eqo("conf/sigmod/ChanI99","hLrdara3zskJ")).
neg(eqo("conf/sigmod/Chaudhuri97","AiXOfJPvvpUJ")).
neg(eqo("conf/sigmod/ChaudhuriGN02","0rViZf2YXmAJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","RYeFLYha0ewJ")).
neg(eqo("conf/sigmod/ChawatheRGW96","C427EHSXEDYJ")).
neg(eqo("conf/sigmod/ChenZCKR01","pwpmrHLw1U8J")).
neg(eqo("conf/sigmod/ChoG00","s7K6rICx3fkJ")).
neg(eqo("conf/sigmod/CruzALRZ97","cJRWis64ghgJ")).
neg(eqo("conf/sigmod/DanS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234900%26type%3Dpdf%26dl%3DGUIDE%26dl%3Dacm%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/DasuJMS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959067%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/DavisonG95","96SrVGnDmMoJ")).
neg(eqo("conf/sigmod/FernandezMS01","JYYcPQLrBw8J")).
neg(eqo("conf/sigmod/FernandezS96","UVXbn_l6IAUJ")).
neg(eqo("conf/sigmod/FranklinZ98","K_qOxjIJWpQJ")).
neg(eqo("conf/sigmod/GeneserethKD97","LhniMvyMMogJ")).
neg(eqo("conf/sigmod/GibbonsM98","Kk87yanaI1AJ")).
neg(eqo("conf/sigmod/Greer99","denME85YhRQJ")).
neg(eqo("conf/sigmod/Hidber99","Rn-E82gM1RQJ")).
neg(eqo("conf/sigmod/Jhingran00","u03oQbB0y-oJ")).
neg(eqo("conf/sigmod/JonssonFS98","f4W03dvh19EJ")).
neg(eqo("conf/sigmod/JoshiA01","CXXD8FE-zpIJ")).
neg(eqo("conf/sigmod/KeoghCMP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D381889%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LabrinidisR00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245909%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Larson01","6pecJqDApv8J")).
neg(eqo("conf/sigmod/Levine95","iNp6OM8GywoJ")).
neg(eqo("conf/sigmod/Mamoulis03","g8e0xiRUkIwJ")).
neg(eqo("conf/sigmod/MerialdoAMMP00","3U6KCyD-uEIJ")).
neg(eqo("conf/sigmod/MohanN94","c2PgXbSSAFcJ")).
neg(eqo("conf/sigmod/MumickQM97","IBg3vuolFUwJ")).
neg(eqo("conf/sigmod/OriaOILY00","y5sZ3lDhg4QJ")).
neg(eqo("conf/sigmod/PoosalaIHS96","8f0YPrw1eOwJ")).
neg(eqo("conf/sigmod/Ramakrishnan00","4U31XD8P478J")).
neg(eqo("conf/sigmod/ReveszCKLLW00","url:http://portal.acm.org/citation.cfm%3Fid%3D126482.126494%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
neg(eqo("conf/sigmod/Rosenthal01","GVtEykbgl1AJ")).
neg(eqo("conf/sigmod/Rosenthal01","UICEZQcUzq8J")).
neg(eqo("conf/sigmod/ShashaB02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/Shivakumar03","i4GsTI2sumYJ")).
neg(eqo("conf/sigmod/TatarinovVBSSZ02","Nc-229YCpUIJ")).
neg(eqo("conf/sigmod/ZhangZPTL03","uJj9OgotYeEJ")).
neg(eqo("conf/sigmod/ZhouR02","3rMCofZbFcgJ")).
neg(eqo("conf/vldb/AbiteboulMRVW98","DMq7N94C6DoJ")).
neg(eqo("conf/vldb/AbrolLMMMRTWZ01","w9Ma-YjZHYkJ")).
neg(eqo("conf/vldb/AgarwalADGNRS96","8YmeyTPHctYJ")).
neg(eqo("conf/vldb/AgrawalPWZ95","LJgXl8u26jUJ")).
neg(eqo("conf/vldb/AgrawalSX02","GBXjNUn2GJEJ")).
neg(eqo("conf/vldb/AnKR03","url:http://www.springerlink.com/index/P60TR286834Q08Q6.pdf")).
neg(eqo("conf/vldb/BernsteinHSSZ97","L2c8XblCSicJ")).
neg(eqo("conf/vldb/BonifatiCDS01","PMYJqNEwetwJ")).
neg(eqo("conf/vldb/Celis96","I6ijvPh4RJ8J")).
neg(eqo("conf/vldb/ChaudhuriN97","4MaErPILRq8J")).
neg(eqo("conf/vldb/ChaudhuriS96","rVC45yk8BEIJ")).
neg(eqo("conf/vldb/ChaudhuriS96","xxkUtjfGpvAJ")).
neg(eqo("conf/vldb/ChoG00","F36WaS34gacJ")).
neg(eqo("conf/vldb/CiacciaPZ97","30GmNaTvXkgJ")).
neg(eqo("conf/vldb/CiacciaPZ97","LZAE3r3rxbsJ")).
neg(eqo("conf/vldb/CiliaHB02","0LBy7I0K6vsJ")).
neg(eqo("conf/vldb/DattaDTVRF01","PpNTP8bK3_0J")).
neg(eqo("conf/vldb/DavisonG94","url:http://portal.acm.org/citation.cfm%3Fid%3D192593.197379%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D192593%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Multimedia%2520Conference%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/DingGS00","BB3nxHP-7qMJ")).
neg(eqo("conf/vldb/Fecteau95","AQI1U6sr5dgJ")).
neg(eqo("conf/vldb/FlescaFM03","hpkD8AsRxfoJ")).
neg(eqo("conf/vldb/GardarinGT96","aqU5N6dO4KcJ")).
neg(eqo("conf/vldb/GohOST99","ByLIysfX5_cJ")).
neg(eqo("conf/vldb/GoyalHSS95","2sGH4SLcdL4J")).
neg(eqo("conf/vldb/HasanM95","JW7LRQwx_goJ")).
neg(eqo("conf/vldb/HerlekarDRGS02","hjuGWEzCIB4J")).
neg(eqo("conf/vldb/JoshiBLL98","EkmUvRCP29QJ")).
neg(eqo("conf/vldb/KalusD95","KhXr0XyvziIJ")).
neg(eqo("conf/vldb/KnorrN99","qy81IQ6F3MsJ")).
neg(eqo("conf/vldb/Malaika96","LNGZsCHYRuwJ")).
neg(eqo("conf/vldb/ManegoldBK02","bAxUjxF0f4EJ")).
neg(eqo("conf/vldb/MarronL01","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/08830355/2001/00000035/00000002/art00010%26unc%3D")).
neg(eqo("conf/vldb/MartinC94","cvUoF_C23nMJ")).
neg(eqo("conf/vldb/MignetMAC01","a_JkQ75RHYIJ")).
neg(eqo("conf/vldb/Moerkotte02","jiGdThcReckJ")).
neg(eqo("conf/vldb/NgH94","HJ9-1xT60k0J")).
neg(eqo("conf/vldb/NipplM98","yQ2TMZ92GaIJ")).
neg(eqo("conf/vldb/PalpanasSCP02","nlh2WXZT3VIJ")).
neg(eqo("conf/vldb/PellenkoftLK97","793XPMTdcBEJ")).
neg(eqo("conf/vldb/RamasamyPNK00","wR0R0jS5J6oJ")).
neg(eqo("conf/vldb/Ramaswamy00","-f2FsG-EC9IJ")).
neg(eqo("conf/vldb/RastogiS98","FFKP2GRm2LEJ")).
neg(eqo("conf/vldb/RezendeS98","9UM3b_U8NMIJ")).
neg(eqo("conf/vldb/SeshadriLR96","egvBPvtoaMMJ")).
neg(eqo("conf/vldb/SeshadriLR97","ad-TVNZBg8YJ")).
neg(eqo("conf/vldb/SkubiszewskiV97","TkrlAK46U8kJ")).
neg(eqo("conf/vldb/Slutz98","NxXs51ZpSGQJ")).
neg(eqo("conf/vldb/Slutz98","SRjydzka_HAJ")).
neg(eqo("conf/vldb/SrikantA95","KwgLlNLlaTcJ")).
neg(eqo("conf/vldb/StolteA02","QOf55i6m6bUJ")).
neg(eqo("conf/vldb/TeisseirePC94","MNblOIClWpAJ")).
neg(eqo("conf/vldb/VelegrakisMP03","BTalXWt3faUJ")).
neg(eqo("journals/sigmod/Aberer02b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AndersonS94","nfStjl_evfkJ")).
neg(eqo("journals/sigmod/AnyanwuS02","LoDGuFLlvsAJ")).
neg(eqo("journals/sigmod/BabuW01","NNCJiGVzTBEJ")).
neg(eqo("journals/sigmod/BernsteinHP00","WLq4CqRENwMJ")).
neg(eqo("journals/sigmod/BertinoEH01","rRvcD6HKhasJ")).
neg(eqo("journals/sigmod/BuchnerM98","23L2_CggtJkJ")).
neg(eqo("journals/sigmod/Chaudhri95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310060%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ClementLGMK97","WkldV8dE4ncJ")).
neg(eqo("journals/sigmod/CruzKLSWY02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601879%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Fankhauser01","nJycrIdh5E4J")).
neg(eqo("journals/sigmod/FengJH01","pBKI-JCAlcIJ")).
neg(eqo("journals/sigmod/GamacheS95","QFeUfn2QS5EJ")).
neg(eqo("journals/sigmod/Goethals02","TH1-xsSW23UJ")).
neg(eqo("journals/sigmod/GunopulosK01","V1dC_dJMWcUJ")).
neg(eqo("journals/sigmod/Halevy00","b38Lp5XCBDYJ")).
neg(eqo("journals/sigmod/KantM00","biq65UhiKF8J")).
neg(eqo("journals/sigmod/Kim94","xSKOmExpWy8J")).
neg(eqo("journals/sigmod/Liu02","moMP8RcSDhgJ")).
neg(eqo("journals/sigmod/Mani03","FgLCpqaf8C8J")).
neg(eqo("journals/sigmod/MeersmanS02","rm1zlNg-SMsJ")).
neg(eqo("journals/sigmod/RamDD99","rM8Ecg1WL4kJ")).
neg(eqo("journals/sigmod/Snodgrass03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Stonebraker02","8OvGNqrl8bEJ")).
neg(eqo("journals/sigmod/Suciu02","KxwymZ2AGNQJ")).
neg(eqo("journals/sigmod/Suciu97","y8Jg6nzTXC4J")).
neg(eqo("journals/sigmod/Wade96","et7qrerDPrYJ")).
neg(eqo("journals/sigmod/Widom96","ilPPZCpzLmkJ")).
neg(eqo("journals/sigmod/Winslett94","0hFtl2Gx-68J")).
neg(eqo("journals/sigmod/Wong95","YrR7nYIYctMJ")).
neg(eqo("journals/tods/CaldersNW02","DSl0gT8EgR0J")).
neg(eqo("journals/tods/GuoSW96","H6XGSfr9v6MJ")).
neg(eqo("journals/tods/LechtenborgerV03","pRIP3vfQtpEJ")).
neg(eqo("journals/tods/LeveneL99","qDx2SICqs0gJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/JJJG5825415765X2.pdf")).
neg(eqo("journals/tods/Subrahmanian94","MWxdDHB-vH8J")).
neg(eqo("journals/tods/WinslettSQ94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1107519%26type%3Dpdf")).
neg(eqo("journals/vldb/AntoshenkovZ96","C7yU79dhbqUJ")).
neg(eqo("journals/vldb/AslanM99","6EJ6A2y_U1IJ")).
neg(eqo("journals/vldb/Bertino94","sjBDpB-ntxYJ")).
neg(eqo("journals/vldb/DesslochHMMT98","LatjkQDqr6sJ")).
neg(eqo("journals/vldb/GrefenVA01","GfF5BCk5tAQJ")).
neg(eqo("journals/vldb/GrefenVA01","nN1i435jxxIJ")).
neg(eqo("journals/vldb/HaasCLS97","2cVl0I8NFHQJ")).
neg(eqo("journals/vldb/HarrisR96","yYoDwjrVaUcJ")).
neg(eqo("journals/vldb/LandauST95","8Ub3e7l0WDsJ")).
neg(eqo("journals/vldb/MehrotraKS97","7qqy0kvU0ukJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","BF1530nSQNsJ")).
neg(eqo("journals/vldb/ShyyASL96","aEhVgTfCykUJ")).
neg(eqo("journals/vldb/WhangKW94","vNxnMHNfRt8J")).
pos(eqo("conf/sigmod/AbiteboulCM95","DakOA4Ew-poJ")).
pos(eqo("conf/sigmod/AcharyaAFZ95","_-yXA5HLnqoJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","EpUtXEhwDaUJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","y55xkFQJvxAJ")).
pos(eqo("conf/sigmod/BabuGR01","zQCRmiH6jo4J")).
pos(eqo("conf/sigmod/BreitbartKRSS99","XV2lpkhWCsYJ")).
pos(eqo("conf/sigmod/BrinMS97","OiHYG-Al8G8J")).
pos(eqo("conf/sigmod/BrinMUT97","aOBNgdooDHAJ")).
pos(eqo("conf/sigmod/BrinMUT97","vIwsSOGQOWAJ")).
pos(eqo("conf/sigmod/Carey00","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D335476%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChaudhuriN98a","AiXOfJPvvpUJ")).
pos(eqo("conf/sigmod/CherniackZ96","ZsHfcZJwFQQJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","SYV3r4_a5EsJ")).
pos(eqo("conf/sigmod/DogacHKOONDMAKE96","UAO4T_2ylPkJ")).
pos(eqo("conf/sigmod/FernandezS96","9bgA6C_HqvQJ")).
pos(eqo("conf/sigmod/Gal00","SudUID_rEy0J")).
pos(eqo("conf/sigmod/GraySEBW94","JT61IMQEZ-QJ")).
pos(eqo("conf/sigmod/GriffinL95","6QZGeKna5lgJ")).
pos(eqo("conf/sigmod/HaasH01","tHEP1S1typgJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","4OrM17Osz64J")).
pos(eqo("conf/sigmod/HarinarayanRU96","ESZwkhGzOboJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","JM1X7hho718J")).
pos(eqo("conf/sigmod/HarinarayanRU96","Qv7KYn9x-SQJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","ofxLw3VrJB8J")).
pos(eqo("conf/sigmod/HarinarayanRU96","sLvivSi__BcJ")).
pos(eqo("conf/sigmod/Hope95","w3Aykr4vDVwJ")).
pos(eqo("conf/sigmod/HungYK96","bTI28RjBpPwJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","kDWGwVa8dykJ")).
pos(eqo("conf/sigmod/IoannidisLANT97","qb-jf_sQ_5kJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","vO7aBWspoyMJ")).
pos(eqo("conf/sigmod/KiepuszewskiMO98","T3Zm8WKD_FYJ")).
pos(eqo("conf/sigmod/KrollW94","SX1_Z3Z000YJ")).
pos(eqo("conf/sigmod/LabrinidisR00","DKUouEkK_b4J")).
pos(eqo("conf/sigmod/LahiriG01","2eJIgKjsQF4J")).
pos(eqo("conf/sigmod/LazaridisM01","IvMJ4bK708kJ")).
pos(eqo("conf/sigmod/LehnerSPC00","UFKz6Q0wVi4J")).
pos(eqo("conf/sigmod/LiBKN03","micx2kyGfKIJ")).
pos(eqo("conf/sigmod/LiefkeS00","SvVh9QQcgDwJ")).
pos(eqo("conf/sigmod/LiefkeS00","vnc0Ml_3BFsJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/LuoEHN02","7p7mpmvIBrYJ")).
pos(eqo("conf/sigmod/MaddenFHH03","qz24tfFNHuoJ")).
pos(eqo("conf/sigmod/MaheshwariL97","1hXAkApUm3kJ")).
pos(eqo("conf/sigmod/MeccaAMMS98","I-fmtPvluKEJ")).
pos(eqo("conf/sigmod/MoonWH02","rlfxeE4k2p4J")).
pos(eqo("conf/sigmod/OlstonJW03","D1h_jOHVyA4J")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","4eUqHKdkGNoJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","bvyqSciFIjcJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","PurSnqtdtCgJ")).
pos(eqo("conf/sigmod/SelfridgeSW96","4ucV5h3-YvMJ")).
pos(eqo("conf/sigmod/SeshadriHPLRSSS96","Elpbl8vygYoJ")).
pos(eqo("conf/sigmod/SeshadriLR94","60I0j0qUHVYJ")).
pos(eqo("conf/sigmod/SeshadriLR94","cL_OKIQDvmQJ")).
pos(eqo("conf/sigmod/ShanmugasundaramNSR99","Nia28ZMfCpEJ")).
pos(eqo("conf/sigmod/ShanmugasundaramNSR99","eQjFv7QxsQQJ")).
pos(eqo("conf/sigmod/ShanmugasundaramNSR99","w_oXiQ-bR70J")).
pos(eqo("conf/sigmod/Shasha97","Q-KG8a3_BmIJ")).
pos(eqo("conf/sigmod/ShashaB02","DEl2TsijDYEJ")).
pos(eqo("conf/sigmod/ShenNSHS03","LjrsWIr3rhAJ")).
pos(eqo("conf/sigmod/SwamiS94","S6TmnZKgmxwJ")).
pos(eqo("conf/sigmod/Team99","DphRY0uPqi8J")).
pos(eqo("conf/sigmod/Team99","bcR9TErOrKQJ")).
pos(eqo("conf/sigmod/ThaperGIK02","855tuDOhjl4J")).
pos(eqo("conf/sigmod/Ubell94","lphlTARDI9YJ")).
pos(eqo("conf/sigmod/VanceM96","5eHH3hxffFUJ")).
pos(eqo("conf/sigmod/WolfsonSXZC99","4dbCEDwsluQJ")).
pos(eqo("conf/sigmod/YanMHF01","w54gl9nDfcoJ")).
pos(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
pos(eqo("conf/vldb/AdiBEY00","RkjggE7xhN0J")).
pos(eqo("conf/vldb/Adler01","Tnuonq9Zi4cJ")).
pos(eqo("conf/vldb/AgrawalPWZ95","mB8W6em6zi8J")).
pos(eqo("conf/vldb/AnciauxBP03","RLZc9c2-6_oJ")).
pos(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","AgqQVeQ7A0AJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","h73uxQEBESwJ")).
pos(eqo("conf/vldb/BestavrosB95","lGyhpsPV6ogJ")).
pos(eqo("conf/vldb/BliujuteJSS98","oBpe7jg0YHYJ")).
pos(eqo("conf/vldb/BliujuteJSS98","qWGJZFXi414J")).
pos(eqo("conf/vldb/CareyD96","5xe-dQqXfI8J")).
pos(eqo("conf/vldb/CareyD96","g8jnRVyQukAJ")).
pos(eqo("conf/vldb/ChenJLP03","p7wumIMn_2oJ")).
pos(eqo("conf/vldb/ColletCS94","sZwecq6zUmMJ")).
pos(eqo("conf/vldb/FlodinR95","WmtiDGY_BdoJ")).
pos(eqo("conf/vldb/GoodmanRS94","8CCHAKnGJ1EJ")).
pos(eqo("conf/vldb/GottlobKP02","Pk09A5EmsOoJ")).
pos(eqo("conf/vldb/GottlobKP02","gF4nPxSCcOMJ")).
pos(eqo("conf/vldb/GottlobKP02","vEFwZXLJ49EJ")).
pos(eqo("conf/vldb/GravanoIJKMS01","iAYjhuQV_qMJ")).
pos(eqo("conf/vldb/HaasKU99","jteJcGoGxnMJ")).
pos(eqo("conf/vldb/HasanM94","e7N82yYp8UIJ")).
pos(eqo("conf/vldb/JaedickeM99","TaaxQZajjqoJ")).
pos(eqo("conf/vldb/JaedickeM99","XR50nxmrvFcJ")).
pos(eqo("conf/vldb/JaedickeM99","zh6yaOX2xiQJ")).
pos(eqo("conf/vldb/JonscherD94","yv7vyZT9-YEJ")).
pos(eqo("conf/vldb/Klots96","dTORuW_9YRoJ")).
pos(eqo("conf/vldb/KornackerB95","e1yWeerxOKMJ")).
pos(eqo("conf/vldb/Levy96","G7CJNSIBp10J")).
pos(eqo("conf/vldb/MadhavanH03","mu31RuCR_E4J")).
pos(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
pos(eqo("conf/vldb/MiloZ98","UF-Z2VPtU6sJ")).
pos(eqo("conf/vldb/NgH94","JA55PRiwrMQJ")).
pos(eqo("conf/vldb/NgH94","XfblD8N3jT8J")).
pos(eqo("conf/vldb/RamanRH99","6uP3E_WEkCAJ")).
pos(eqo("conf/vldb/RastogiS98","GDlHdL-s4tIJ")).
pos(eqo("conf/vldb/RothS97","GRLUYc-u9X8J")).
pos(eqo("conf/vldb/RothS97","gIFZWp_iCmUJ")).
pos(eqo("conf/vldb/SantiniG02","J3cfnmFB4lsJ")).
pos(eqo("conf/vldb/SavasereON95","1WArdj4NhEoJ")).
pos(eqo("conf/vldb/SavasereON95","rmfK2zWkuagJ")).
pos(eqo("conf/vldb/SavasereON95","tX0hBHC5_UQJ")).
pos(eqo("conf/vldb/SavasereON95","y1hmJODjq7UJ")).
pos(eqo("conf/vldb/SrikantA95","KIPDo6ym8BUJ")).
pos(eqo("conf/vldb/SrikantA95","bibMn8zFnksJ")).
pos(eqo("conf/vldb/TeisseirePC94","w17spSGfEXYJ")).
pos(eqo("conf/vldb/VenkataramanZ98","RGh6Gep4ym8J")).
pos(eqo("conf/vldb/YiF00","J8maiu6CF0EJ")).
pos(eqo("journals/sigmod/AndlerHEMBE96","J82SdCmczAcJ")).
pos(eqo("journals/sigmod/BonnetBDL03","aovCRhocZUcJ")).
pos(eqo("journals/sigmod/David03","vhUs7wTpUOoJ")).
pos(eqo("journals/sigmod/DemersGRTY03","QObLZuX-xBMJ")).
pos(eqo("journals/sigmod/DomenigD99","bi68bm0miqkJ")).
pos(eqo("journals/sigmod/FernandezFLS97","LJKpMU1tIlcJ")).
pos(eqo("journals/sigmod/GeppertD94","P9xX0UDXnRcJ")).
pos(eqo("journals/sigmod/GroskyFS94","sWM6PKw-JaQJ")).
pos(eqo("journals/sigmod/Halevy03","706PCMwA_E4J")).
pos(eqo("journals/sigmod/KlasS94","c1vjKqGLkp4J")).
pos(eqo("journals/sigmod/LightstoneLZ02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601873%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Lomet98","xLM0YVcccUgJ")).
pos(eqo("journals/sigmod/SayginVC01","OALLzL4DQXsJ")).
pos(eqo("journals/sigmod/SayginVC01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604271%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/SpynsMJ02","QWfa2xEybLcJ")).
pos(eqo("journals/sigmod/SpynsMJ02","jD6nDNmhP3AJ")).
pos(eqo("journals/sigmod/TanakaV01","sQu8znidi50J")).
pos(eqo("journals/sigmod/YauLMS99","vWwVQvcIrbEJ")).
pos(eqo("journals/tods/BunemanO96","-ZDi1Wdy_DoJ")).
pos(eqo("journals/tods/BunemanO96","xT4l9LBtTcUJ")).
pos(eqo("journals/tods/GuoSW96","V8Ls_TYs6mgJ")).
pos(eqo("journals/tods/HjaltasonS03","9Wan9sPNUAYJ")).
pos(eqo("journals/tods/WolfsonJH97","tjSQMcZ1iIcJ")).
pos(eqo("journals/vldb/Atkinson00","url:http://www.springerlink.com/index/CFM1025XF89JLNH8.pdf")).
pos(eqo("journals/vldb/BerchtoldKK97","VHo2go6vjYsJ")).
pos(eqo("journals/vldb/BraumandlKKKKSS01","dURGvGhlWbsJ")).
pos(eqo("journals/vldb/DeWittNSV96","WTuHfc-D3TwJ")).
pos(eqo("journals/vldb/FerrariAABC02","74D4YiDcxfcJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","zaDlTkyGASQJ")).
pos(eqo("journals/vldb/ManegoldBK00","xWYu2JWiF_kJ")).
pos(eqo("journals/vldb/RoySSSA98","JB684f38DiwJ")).
pos(eqo("journals/vldb/RoySSSA98","vitgygjdz3AJ")).
pos(eqo("journals/vldb/SteinbrunnMK97","nwwVf5FGX4QJ")).
pos(eqo("journals/vldb/WangW01","4eHVZHcQvdMJ")).
