neg(eqo("conf/sigmod/AcharyaGPR99a","IkNOhDqEY18J")).
neg(eqo("conf/sigmod/AggarwalY00","os704sArqZUJ")).
neg(eqo("conf/sigmod/AnnamalaiCD00","7qv9IC8F_WQJ")).
neg(eqo("conf/sigmod/ArefBV95","AYEI8XDoY9wJ")).
neg(eqo("conf/sigmod/BarbosaMKL02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959084%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BerckenDS00","3IFlpeKgLlAJ")).
neg(eqo("conf/sigmod/BhargavaGI95","TXvfEP4WTD0J")).
neg(eqo("conf/sigmod/BhattacharyaMBNHS02","Vl7gY6FsOOYJ")).
neg(eqo("conf/sigmod/BouguettayaBH99","SeDkIL_DlRwJ")).
neg(eqo("conf/sigmod/BreunigKKS01","url:http://portal.acm.org/citation.cfm%3Fdoid%3D375663.375759")).
neg(eqo("conf/sigmod/ChakrabartiM99","url:http://doi.wiley.com/10.1002/ace.8207")).
neg(eqo("conf/sigmod/Chan98","IBg3vuolFUwJ")).
neg(eqo("conf/sigmod/Chan98","sfmnW-c9d9IJ")).
neg(eqo("conf/sigmod/ChaudhuriKN03","H5IdN0_MQw4J")).
neg(eqo("conf/sigmod/ChenGK01","pw234_REfHUJ")).
neg(eqo("conf/sigmod/DavisonG95","uXvRo9fefgoJ")).
neg(eqo("conf/sigmod/Deutsch95","E9WYK5aZNYQJ")).
neg(eqo("conf/sigmod/DogacAEOADAOS94","gt_wY6mYF_kJ")).
neg(eqo("conf/sigmod/FernandezMS01","xqo8QahjsN0J")).
neg(eqo("conf/sigmod/FlorescuLMS99","UkIG8p5eCSsJ")).
neg(eqo("conf/sigmod/FranklinZ98","0ll9HCfghT8J")).
neg(eqo("conf/sigmod/Galhardas00","4J5CvdomBmsJ")).
neg(eqo("conf/sigmod/GangulyGR03","h_oXQ6ntHEUJ")).
neg(eqo("conf/sigmod/GodfreyGXZ01","78EbgloygSMJ")).
neg(eqo("conf/sigmod/GuptaMR95","7OQlv9Ry1SkJ")).
neg(eqo("conf/sigmod/HammerGNYBV97","h1HujKXawRMJ")).
neg(eqo("conf/sigmod/Han96","kj7_0qQq_48J")).
neg(eqo("conf/sigmod/HanFHCC94","RzsJoG-0KaIJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","-_FyboGgZkkJ")).
neg(eqo("conf/sigmod/HarinarayanRU96","QHUtoLECZzgJ")).
neg(eqo("conf/sigmod/IvesFFLW99","UqUezrGVDPkJ")).
neg(eqo("conf/sigmod/KimCK01","EYI-OULRIz8J")).
neg(eqo("conf/sigmod/LabioZWGGW97","Y0GdVVrbzfQJ")).
neg(eqo("conf/sigmod/LacroixSC98","e3s4OFTeBqwJ")).
neg(eqo("conf/sigmod/LehnerSPC00","url:http://doi.wiley.com/10.1002/he.11209")).
neg(eqo("conf/sigmod/LiGS02","l7KC1qG6OGEJ")).
neg(eqo("conf/sigmod/LiYVGPUV98","nDa7ddSZEIIJ")).
neg(eqo("conf/sigmod/LitwinS00","Yk4p2NDktz0J")).
neg(eqo("conf/sigmod/LuoKMPWLN02","anxrt7GCrscJ")).
neg(eqo("conf/sigmod/MerialdoAMMP00","F5ii9m2WQbAJ")).
neg(eqo("conf/sigmod/Meseck01","Dmua8faBijAJ")).
neg(eqo("conf/sigmod/Mohan01","8i4I4K2N5dMJ")).
neg(eqo("conf/sigmod/Mohan96","Xn6OdNl_YAIJ")).
neg(eqo("conf/sigmod/Mohan96","f9JfEpe5a24J")).
neg(eqo("conf/sigmod/NazeriBO01","xT3mwY4t5kEJ")).
neg(eqo("conf/sigmod/PapakonstantinouPV02","5XmfwqNDii8J")).
neg(eqo("conf/sigmod/ParkCY95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310066%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/RajagopalanML98","M2bWqRDDfkUJ")).
neg(eqo("conf/sigmod/RamanH02","4692SthNStUJ")).
neg(eqo("conf/sigmod/RundensteinerWYD02","kdU4iiwLli8J")).
neg(eqo("conf/sigmod/ShouCTRH01","bCsX4nnVy00J")).
neg(eqo("conf/sigmod/SrikantA96","1QEIyHrrR0gJ")).
neg(eqo("conf/sigmod/Stonebraker98","Syqabdl4M5IJ")).
neg(eqo("conf/sigmod/Team95","uA-E1lBgLe0J")).
neg(eqo("conf/sigmod/Team95c","zIHTjbpJkWoJ")).
neg(eqo("conf/sigmod/TrisoliniLN99","Bo5Lu6t9X0wJ")).
neg(eqo("conf/sigmod/Ullman03","f9JfEpe5a24J")).
neg(eqo("conf/sigmod/WuAA01","Z1P9QnSfDuAJ")).
neg(eqo("conf/sigmod/YerneniLGU99","b7pl2-7mOQIJ")).
neg(eqo("conf/vldb/AgrawalK02","5GDHzHaNiscJ")).
neg(eqo("conf/vldb/AgrawalKSX02","J_4A9G0S41UJ")).
neg(eqo("conf/vldb/AgrawalKSX02","YpCjqxVSd-YJ")).
neg(eqo("conf/vldb/ArgePRSV98","a763Ng-Wqh8J")).
neg(eqo("conf/vldb/BaralisPT97","UUiSb7q5PHgJ")).
neg(eqo("conf/vldb/BaumgartnerFG01","2njaHdhfzAoJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","Rf12p4gOaMgJ")).
neg(eqo("conf/vldb/BerchtoldKK96","0acvmJtaI8QJ")).
neg(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
neg(eqo("conf/vldb/BestavrosB95","q4YYDWKhoZwJ")).
neg(eqo("conf/vldb/BrownS95","cxMY2sN8wi0J")).
neg(eqo("conf/vldb/ChakrabartiSD98","F9Fe5NfpK6MJ")).
neg(eqo("conf/vldb/ChaudhuriS96","4bS3tvLQ-LAJ")).
neg(eqo("conf/vldb/ChenHWW02","Hf9iPuXlb-IJ")).
neg(eqo("conf/vldb/ChengGKLLQS99","o_0fke6HFesJ")).
neg(eqo("conf/vldb/ChristodoulakisTZ97","IPT7DU1wqRYJ")).
neg(eqo("conf/vldb/Dasgupta96","xYcOA_AAXNAJ")).
neg(eqo("conf/vldb/DaynesC02","Ug0Yk0QhILMJ")).
neg(eqo("conf/vldb/EvangelidisLS95","-953Ij-RwjcJ")).
neg(eqo("conf/vldb/GalanisWJD03","qzVrSkgBsNMJ")).
neg(eqo("conf/vldb/Ganguly98","lPWuMxTX9yYJ")).
neg(eqo("conf/vldb/GardarinGT96","RB2VKRwnXywJ")).
neg(eqo("conf/vldb/GarofalakisRS99","q87jrCR_GqQJ")).
neg(eqo("conf/vldb/GehrkeRG98","793XPMTdcBEJ")).
neg(eqo("conf/vldb/GoldmanW97","jJym5UnL5poJ")).
neg(eqo("conf/vldb/GottlobKP02","s0KWjFDzKAIJ")).
neg(eqo("conf/vldb/Graefe99","N2Q6TnVleTIJ")).
neg(eqo("conf/vldb/Graefe99","vP1Ipm2B9PYJ")).
neg(eqo("conf/vldb/GuptaM96","I0Kfdt6sh0gJ")).
neg(eqo("conf/vldb/HanF95","qNLsbj_Fu5EJ")).
neg(eqo("conf/vldb/HellersteinNP95","V1M4safuoecJ")).
neg(eqo("conf/vldb/KonopnickiS95","1CH42dal6-oJ")).
neg(eqo("conf/vldb/Lesk94","url:http://portal.acm.org/citation.cfm%3Fid%3D144111.144160")).
neg(eqo("conf/vldb/Levy96","fbMLEWe2pKMJ")).
neg(eqo("conf/vldb/LuSL95","8XpICeyGC2YJ")).
neg(eqo("conf/vldb/Malaika96","_NuSLghE2kkJ")).
neg(eqo("conf/vldb/MalonM97","ogRpbFNQTSkJ")).
neg(eqo("conf/vldb/ManolescuFKXO00","t19PsyGam1EJ")).
neg(eqo("conf/vldb/Mattos96","9KiPVAodKnYJ")).
neg(eqo("conf/vldb/MengLYWCR98","sUcJBJwvKTUJ")).
neg(eqo("conf/vldb/MiloZ98","5bsmOwr6zjIJ")).
neg(eqo("conf/vldb/Mina98","LnNHfHLFsEcJ")).
neg(eqo("conf/vldb/NieKH03","Ltf5yQsl8sMJ")).
neg(eqo("conf/vldb/PapadiasT01","2V2bnIgsY1kJ")).
neg(eqo("conf/vldb/PfoserJT00","ZjxilICcJ94J")).
neg(eqo("conf/vldb/Pound99","JIx9mf-5dpoJ")).
neg(eqo("conf/vldb/RamasamyPNK00","kxIpDxLD46gJ")).
neg(eqo("conf/vldb/SakuraiYUK00","eLf0eStn5G4J")).
neg(eqo("conf/vldb/SeshadriLR96","srDgEOADv7cJ")).
neg(eqo("conf/vldb/ShanmugasundaramSBCLPR00","_bdp5T8SSuoJ")).
neg(eqo("conf/vldb/ShivakumarGC98","z5tz9vybRmIJ")).
neg(eqo("conf/vldb/Sripada02","url:http://portal.acm.org/citation.cfm%3Fid%3D74120.74125%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/StohrR01","SJ-uErR3pv8J")).
neg(eqo("conf/vldb/StolteA02","mvD-z59XDYoJ")).
neg(eqo("conf/vldb/VelegrakisMP03","JYQUV-XahekJ")).
neg(eqo("conf/vldb/VenkataramanZ98","ku_ZRWKDMjUJ")).
neg(eqo("conf/vldb/Vieille98","6OfJSMB4vOcJ")).
neg(eqo("conf/vldb/WangHH00","qbxHq9qXVrUJ")).
neg(eqo("conf/vldb/WangZL03","tbuNzuDUSFYJ")).
neg(eqo("conf/vldb/WienerN94","ABztkd0E9lUJ")).
neg(eqo("conf/vldb/WildfogelY97","XLyfgjG_fOIJ")).
neg(eqo("conf/vldb/YuAA03","4bvjebYsdRkJ")).
neg(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601865%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/AdelbergKG96","GpYZAL6HBlIJ")).
neg(eqo("journals/sigmod/Anonymous96","WkldV8dE4ncJ")).
neg(eqo("journals/sigmod/ArenasKKKMM03","FVUr5EtAAFcJ")).
neg(eqo("journals/sigmod/BawaCCDGGKMSSVY03","w5YdMlyYwDUJ")).
neg(eqo("journals/sigmod/CeriFP99","iUGa3pKj-20J")).
neg(eqo("journals/sigmod/Chang03","yC4Dc6Q1ggoJ")).
neg(eqo("journals/sigmod/ChenHKPW94","jN8ws_LDhNUJ")).
neg(eqo("journals/sigmod/Cruz00","url:http://portal.acm.org/citation.cfm%3Fid%3D335168.335220%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D335168%26part%3DProceedings%26WantType%3DProceedings%26title%3DSymposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/CruzKLSWY02","B_axrPz8j5EJ")).
neg(eqo("journals/sigmod/Danish98","qRnB_07lQVMJ")).
neg(eqo("journals/sigmod/EisenbergM98","4mD1eFCHKKwJ")).
neg(eqo("journals/sigmod/EisenbergM99","e3s4OFTeBqwJ")).
neg(eqo("journals/sigmod/GroskyFS94","nouEWQwfYaEJ")).
neg(eqo("journals/sigmod/Gunther97","L2c8XblCSicJ")).
neg(eqo("journals/sigmod/Jagadish00","4b7LM9NCKt4J")).
neg(eqo("journals/sigmod/KokkotosIPS95","T5ZdpquqfJ0J")).
neg(eqo("journals/sigmod/Liu01b","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Liu02","fJ3CscgIKSkJ")).
neg(eqo("journals/sigmod/MaximilienS02","Pmcq3TVYuYMJ")).
neg(eqo("journals/sigmod/Nascimento03","XdWK2yxBBrUJ")).
neg(eqo("journals/sigmod/PaepckeGRC00","fg5EE6R7xYwJ")).
neg(eqo("journals/sigmod/Ritter98","mBC03oUT8yAJ")).
neg(eqo("journals/sigmod/RossHKRRSS01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D290599%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/SonDT96","62uEWBKYqgoJ")).
neg(eqo("journals/sigmod/Stonebraker02","goxkHU_NxnIJ")).
neg(eqo("journals/sigmod/TianDCZ02","0acvmJtaI8QJ")).
neg(eqo("journals/sigmod/TsotrasK96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D51710%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/UrbanDG96","BX8MQPuFurwJ")).
neg(eqo("journals/sigmod/Winslett02","IOayjaBtu_4J")).
neg(eqo("journals/sigmod/Winslett02a","2hfDw1b0VgcJ")).
neg(eqo("journals/sigmod/YanG95","tMXkkRDxvkQJ")).
neg(eqo("journals/sigmod/ZobelMR96","v2lUuojatx0J")).
neg(eqo("journals/tods/BaralisW00","7MSK1wdUU50J")).
neg(eqo("journals/tods/CeriFPT95","jVY0apLcSIsJ")).
neg(eqo("journals/tods/FranklinCL97","WHWa6vBvwJ0J")).
neg(eqo("journals/tods/GutingBEJLSV00","4pZEi-wH49UJ")).
neg(eqo("journals/tods/IoannidisR95","kDWGwVa8dykJ")).
neg(eqo("journals/tods/Kim94","eY1qV1u890AJ")).
neg(eqo("journals/tods/LiC01","01ZVDudF4WAJ")).
neg(eqo("journals/tods/Meo00","NQShGztSLaoJ")).
neg(eqo("journals/tods/TaoP03","url:http://www.springerlink.com/index/K756M46120606K62.pdf")).
neg(eqo("journals/tods/WangBBJ97","uaaJl906vYoJ")).
neg(eqo("journals/vldb/ChirkovaHS02","4RrCiVMO9IIJ")).
neg(eqo("journals/vldb/DattaDVRN01","efYVCK07AwMJ")).
neg(eqo("journals/vldb/Guting94","nCbk5djejmEJ")).
neg(eqo("journals/vldb/IoannidisNSS97","U3sURDcacksJ")).
neg(eqo("journals/vldb/KabraD99","QUBHka6wMH8J")).
neg(eqo("journals/vldb/MaedcheMS03","oeMU1XoJSesJ")).
neg(eqo("journals/vldb/RafieiM02","4weou-KgkM8J")).
neg(eqo("journals/vldb/WhangKW94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1086288%26type%3Dpdf")).
pos(eqo("conf/sigmod/AcharyaAFZ95","_-yXA5HLnqoJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","NDzryNtTyL8J")).
pos(eqo("conf/sigmod/AdaliBSS98","YQ90BYSVqbsJ")).
pos(eqo("conf/sigmod/AggarwalY00","dfSPs7YoyWsJ")).
pos(eqo("conf/sigmod/AgrawalCD02","iABZEL2Zoz8J")).
pos(eqo("conf/sigmod/BarbaraI94","7N0H3ra1FFsJ")).
pos(eqo("conf/sigmod/BarbaraI94","kooQijVBMscJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","fTYVIbi40sAJ")).
pos(eqo("conf/sigmod/BerchtoldBK98","j46yGNUAS-IJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","-lYgZoLNtioJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","MOGnM6t6l3MJ")).
pos(eqo("conf/sigmod/BerensonBGMOO95","gWmqoNZHKAAJ")).
pos(eqo("conf/sigmod/Blakeley96","37_iwO5NlgwJ")).
pos(eqo("conf/sigmod/BlohsfeldKS99","PQbi3PaRh84J")).
pos(eqo("conf/sigmod/BlottRS96","jq_F3lCmTaIJ")).
pos(eqo("conf/sigmod/BlottRS96","pS2unAe-n_gJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97a","JntLVX4TPi0J")).
pos(eqo("conf/sigmod/BratsbergT00","356Jyb4b6rYJ")).
pos(eqo("conf/sigmod/BrinMS97","6sRWyw06gJIJ")).
pos(eqo("conf/sigmod/BrinMS97","COUbnKv6QeMJ")).
pos(eqo("conf/sigmod/BrinMS97","Innqdf1794AJ")).
pos(eqo("conf/sigmod/BrinMS97","OiHYG-Al8G8J")).
pos(eqo("conf/sigmod/BrinMUT97","CnTgirrsL3EJ")).
pos(eqo("conf/sigmod/BunemanDHS96","Wo7In8pIWJ4J")).
pos(eqo("conf/sigmod/CallanCD99","hqItKlvGzJIJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","dP-pHDZ7oawJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","vF-KpOq9TdIJ")).
pos(eqo("conf/sigmod/ChakrabartiM99","Jg81WYtxtZoJ")).
pos(eqo("conf/sigmod/ChanI98","63t-u0Menw4J")).
pos(eqo("conf/sigmod/ChaudhuriD97","gY652XXjHB8J")).
pos(eqo("conf/sigmod/ChenJDTW00","QiSf-FBUE8QJ")).
pos(eqo("conf/sigmod/ChoG00","yUZCropW2lQJ")).
pos(eqo("conf/sigmod/DasGR03","JaJKfzmaEBYJ")).
pos(eqo("conf/sigmod/DeshpandeGR01","0Ta25VSGl7kJ")).
pos(eqo("conf/sigmod/DeutschFS99","QxtGOVsCF78J")).
pos(eqo("conf/sigmod/DeutschFS99","SR_yVgZnYpMJ")).
pos(eqo("conf/sigmod/DeutschFS99","fuitKuyY3l8J")).
pos(eqo("conf/sigmod/FaloutsosRM94","4bG39HmGrAQJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","5fCkUaG8A-gJ")).
pos(eqo("conf/sigmod/FaloutsosRM94","AHu54TOP-eoJ")).
pos(eqo("conf/sigmod/FegarasM95","ZquXPssSY_EJ")).
pos(eqo("conf/sigmod/FernandezFKLS97","zjrD8FvY6TgJ")).
pos(eqo("conf/sigmod/GuhaRS98","Dux-7sONElwJ")).
pos(eqo("conf/sigmod/GuhaRS98","iSkco-aumngJ")).
pos(eqo("conf/sigmod/GuhaRS98","nMzsE-ScW4MJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","PziDM429oXQJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","W0IbuSAyBcoJ")).
pos(eqo("conf/sigmod/HammerGNYBV97","ahrxo47nJtMJ")).
pos(eqo("conf/sigmod/Han96","uEbdEtnaCXMJ")).
pos(eqo("conf/sigmod/HanPLJ01","H_tzR6yoJLEJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","ESZwkhGzOboJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","Fyek_kCB-qkJ")).
pos(eqo("conf/sigmod/HarinarayanRU96","S-7KOPYObKcJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","1H_A7k3QsbQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","7qv9IC8F_WQJ")).
pos(eqo("conf/sigmod/JarkeQBLMS99","nSKzTBqurCwJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","jCudeTapg5IJ")).
pos(eqo("conf/sigmod/KementsietsidisAM03","vO7aBWspoyMJ")).
pos(eqo("conf/sigmod/KornM00","N11b8vV9qIkJ")).
pos(eqo("conf/sigmod/KotidisR99","qzjtGDo7OuMJ")).
pos(eqo("conf/sigmod/LangS01","OubIayl1628J")).
pos(eqo("conf/sigmod/LarsonG98","tPG--ikWjGcJ")).
pos(eqo("conf/sigmod/LitwinS00","RQ9fpPAS2h8J")).
pos(eqo("conf/sigmod/LiuFP03","5BY1upUmSTUJ")).
pos(eqo("conf/sigmod/MerialdoAMMP00","Qq0WheHyVv8J")).
pos(eqo("conf/sigmod/Mohan01","IGS3TtqfKUgJ")).
pos(eqo("conf/sigmod/Mohan94","E2zhARKv5dsJ")).
pos(eqo("conf/sigmod/MohanN94","_2hj6snS3foJ")).
pos(eqo("conf/sigmod/Nori00","url:http://portal.acm.org/citation.cfm%3Fid%3D342009.335474")).
pos(eqo("conf/sigmod/ParkCY95","A3XtQdi1j5UJ")).
pos(eqo("conf/sigmod/ParkCY95","hLrdara3zskJ")).
pos(eqo("conf/sigmod/PeiMHZ00","UyhrqiH_-MoJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","l1tbsG6UXaMJ")).
pos(eqo("conf/sigmod/RothAHCCFSTW96","r3GI5ly9cuIJ")).
pos(eqo("conf/sigmod/RundensteinerKRCJM96","38HoFGLnxkQJ")).
pos(eqo("conf/sigmod/SagonasSW94","zOre6B5JTkoJ")).
pos(eqo("conf/sigmod/SistlaW95","J3XZUbzCxjEJ")).
pos(eqo("conf/sigmod/ZhangRL96","8UbrDL0jsOYJ")).
pos(eqo("conf/sigmod/ZhangRL96","NzUcyD-oMpQJ")).
pos(eqo("conf/sigmod/ZhangRL96","Q4JDSTBf5_oJ")).
pos(eqo("conf/sigmod/ZhangRL96","hk9P76dJfcAJ")).
pos(eqo("conf/sigmod/ZhangRL96","yoMojXfArHAJ")).
pos(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
pos(eqo("conf/sigmod/ZhaoDN97","chYdQDE8cPsJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","MKZ1bbmP6HgJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","mm3mXWb8QS0J")).
pos(eqo("conf/vldb/AgarwalADGNRS96","OMzQ1Ah1IVQJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/AilamakiDHS01","gUJrOpj89tQJ")).
pos(eqo("conf/vldb/BerckenSW97","w90oK0t46SAJ")).
pos(eqo("conf/vldb/CareyD96","5xe-dQqXfI8J")).
pos(eqo("conf/vldb/CareyD96","riS5qD1-odUJ")).
pos(eqo("conf/vldb/CareyD96","ulDUAu6vLr4J")).
pos(eqo("conf/vldb/CarinoO98","iaOLRaqTWmEJ")).
pos(eqo("conf/vldb/CatozziR95","8ftKLh07LM0J")).
pos(eqo("conf/vldb/ChaudhuriS96","4MaErPILRq8J")).
pos(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
pos(eqo("conf/vldb/CiacciaPZ97","LZAE3r3rxbsJ")).
pos(eqo("conf/vldb/CiacciaPZ97","V9DtLHHIBxEJ")).
pos(eqo("conf/vldb/DiaoF03","Crt1JZ1eEj0J")).
pos(eqo("conf/vldb/DoR02","56U_HeDJYggJ")).
pos(eqo("conf/vldb/DonjerkovicR99","SgokkSrdkyAJ")).
pos(eqo("conf/vldb/GallersdorferN95","U8jfPCxfXicJ")).
pos(eqo("conf/vldb/GingrasL98","9rJeZSGswxYJ")).
pos(eqo("conf/vldb/GraefeBC98","v-kvo2hnsgkJ")).
pos(eqo("conf/vldb/HaasKWY97","yIRQRtTEzSAJ")).
pos(eqo("conf/vldb/Hamilton99","_zPTedzhFhQJ")).
pos(eqo("conf/vldb/HasanM95","8cd64f0t0-EJ")).
pos(eqo("conf/vldb/HellersteinNP95","DqyvTE-PXg0J")).
pos(eqo("conf/vldb/HellersteinNP95","iLRI5OqO94UJ")).
pos(eqo("conf/vldb/KamelF94","A7WoAzxOJ9YJ")).
pos(eqo("conf/vldb/KiesslingK02","Z8bBN2cO11UJ")).
pos(eqo("conf/vldb/KonigW99","6HMffRHCspAJ")).
pos(eqo("conf/vldb/KornSFSP96","QjbxSG6_-WIJ")).
pos(eqo("conf/vldb/LakshmananSS96","IJyunaAcul8J")).
pos(eqo("conf/vldb/LakshmananSS96","UPYyrF0ofUUJ")).
pos(eqo("conf/vldb/LakshmananSS96","XPjpq3h5BhUJ")).
pos(eqo("conf/vldb/LeeLWS97","3k61gi_ld_UJ")).
pos(eqo("conf/vldb/LevyRO96","3v8fGnfTuVMJ")).
pos(eqo("conf/vldb/LevyRO96","CWzG-HRtqZIJ")).
pos(eqo("conf/vldb/LevyRO96","QTsbBZX9zrAJ")).
pos(eqo("conf/vldb/LevyRO96","bbeft23FHAkJ")).
pos(eqo("conf/vldb/LiRS99","Bf44yXvb6EAJ")).
pos(eqo("conf/vldb/LifantsevC02","gPvyDDUyrg4J")).
pos(eqo("conf/vldb/Meier95","C_lenwvj88AJ")).
pos(eqo("conf/vldb/PalpanasSCP02","nlh2WXZT3VIJ")).
pos(eqo("conf/vldb/PardonA00","k7G60pXtD58J")).
pos(eqo("conf/vldb/PopaVMHF02","kyO1P49ldlEJ")).
pos(eqo("conf/vldb/PopaVMHF02","qJ4lzBFzjdgJ")).
pos(eqo("conf/vldb/RamamurthyDS02","uem5wXLoU0wJ")).
pos(eqo("conf/vldb/RamamurthyDS02","vGFdY2gG8YsJ")).
pos(eqo("conf/vldb/ShanmugasundaramSBCLPR00","MSw9OnOdcVEJ")).
pos(eqo("conf/vldb/SrivastavaDJL96","4bf1BkOuUNAJ")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/Tygar98","kKwsIC5HmsUJ")).
pos(eqo("conf/vldb/WangC03","B1uNI67mfJcJ")).
pos(eqo("conf/vldb/WangC03","yjZolbzEP6wJ")).
pos(eqo("conf/vldb/WienerN95","LJ4M8B9mNWAJ")).
pos(eqo("conf/vldb/ZellerK02","UIWreKZndVQJ")).
pos(eqo("journals/sigmod/AndlerHEMBE96","J82SdCmczAcJ")).
pos(eqo("journals/sigmod/AndlerHEMBE96","xpaAdEJShEoJ")).
pos(eqo("journals/sigmod/BarbaraCJW01","asukNMVeZZYJ")).
pos(eqo("journals/sigmod/Bohlen95","WnwPjh0a0twJ")).
pos(eqo("journals/sigmod/Eisenberg96","tFbkjO2wcFMJ")).
pos(eqo("journals/sigmod/FlorescuLM98","q5OOyzSAlC8J")).
pos(eqo("journals/sigmod/FlorescuLM98","xfzQQjDwnfcJ")).
pos(eqo("journals/sigmod/GuptaHR97","-ha8fD8Kj_oJ")).
pos(eqo("journals/sigmod/Hammer01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601859%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HummerLW02","W1IcM8IUwAEJ")).
pos(eqo("journals/sigmod/Konig-RiesL97","3fQBks2g-BMJ")).
pos(eqo("journals/sigmod/TianDCZ02","eeCoB5sDWK4J")).
pos(eqo("journals/sigmod/Wu02","url:http://portal.acm.org/citation.cfm%3Fid%3D637411.637426%26dl%3DGUIDE%26dl%3DACM%26idx%3D637411%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/YaoG02","50aU57yUHVAJ")).
pos(eqo("journals/tods/BaralisCP96","6Njy0-27w5cJ")).
pos(eqo("journals/tods/BellNNS96","0MteXOu7gzcJ")).
pos(eqo("journals/tods/DeyS96","l2y2U5f48WcJ")).
pos(eqo("journals/tods/HjaltasonS99","RHJjRlVhi78J")).
pos(eqo("journals/tods/HjaltasonS99","wjKElSLd3lQJ")).
pos(eqo("journals/tods/HjaltasonS99","xuoJNqOArTsJ")).
pos(eqo("journals/tods/Kuo96","VnenpXoUAmwJ")).
pos(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
pos(eqo("journals/tods/PetersO97","er0r8doAGUQJ")).
pos(eqo("journals/tods/YanG99","y6gLSJhyXfcJ")).
pos(eqo("journals/vldb/GeorgakopoulosRL94","G85JsnuAjzMJ")).
pos(eqo("journals/vldb/GibsonKR00","9FBwT6XFOssJ")).
pos(eqo("journals/vldb/LiR99","Ko9e8CH2Si4J")).
pos(eqo("journals/vldb/RahmB01","707RPzHAB8YJ")).
pos(eqo("journals/vldb/RoySSSA98","vitgygjdz3AJ")).
pos(eqo("journals/vldb/TenienteO95","Y7ICKU_J4WsJ")).
pos(eqo("journals/vldb/TurkerG01","Jab63JLU3N0J")).
pos(eqo("journals/vldb/WidomS00","url:http://www.springerlink.com/index/JWGUMV8YDL893E3V.pdf")).
