neg(eqo("conf/sigmod/AdaliCPS96","biZDMJV6XHgJ")).
neg(eqo("conf/sigmod/AtzeniT97","url:http://www.springerlink.com/index/0YKCKU5LKG6G102T.pdf")).
neg(eqo("conf/sigmod/BhargavaGI95","62uEWBKYqgoJ")).
neg(eqo("conf/sigmod/BorkarDS01","2CYtbbiwv-AJ")).
neg(eqo("conf/sigmod/BouguettayaBH99","cDqghE6axksJ")).
neg(eqo("conf/sigmod/BraumandlKK99","OQf4E4E3AD0J")).
neg(eqo("conf/sigmod/CareyDNAGS97","_q3scPb8vbgJ")).
neg(eqo("conf/sigmod/Chaudhuri97","N9NdxNRvMMkJ")).
neg(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
neg(eqo("conf/sigmod/FukudaMMT96","lmXiI4fB9vgJ")).
neg(eqo("conf/sigmod/GravanoCGP97","nAJnhh70_0kJ")).
neg(eqo("conf/sigmod/GunopulosKTD00","05HatAOXWRIJ")).
neg(eqo("conf/sigmod/GuoSBS03","YrezQaVZ_VgJ")).
neg(eqo("conf/sigmod/Han96","Ywgd3RbAfl0J")).
neg(eqo("conf/sigmod/HernandezMHYHT01","KOpz_NXJ3WUJ")).
neg(eqo("conf/sigmod/Jagadish94","eH69_dCm18wJ")).
neg(eqo("conf/sigmod/JagatheesanR03","wpkfVgLxqWEJ")).
neg(eqo("conf/sigmod/JarkeQCLFLVV00","AYtgczYwVnYJ")).
neg(eqo("conf/sigmod/KanthRSB99","6NBDemQboWwJ")).
neg(eqo("conf/sigmod/KotidisR99","12xRfc32PXoJ")).
neg(eqo("conf/sigmod/LabrinidisR00","_SR_pRTnA6IJ")).
neg(eqo("conf/sigmod/LamCKNH01","oulaZpEWkMQJ")).
neg(eqo("conf/sigmod/Larson01","lJyrTngp_KkJ")).
neg(eqo("conf/sigmod/LiBCS00","_F-Z-tr1rfAJ")).
neg(eqo("conf/sigmod/Moore95","ALk7huiKjWAJ")).
neg(eqo("conf/sigmod/PapakonstantinouPV02","Q91XQ6gnhrwJ")).
neg(eqo("conf/sigmod/Rajaraman99","1WSTXNtfwJEJ")).
neg(eqo("conf/sigmod/RundensteinerKZWLLN99","HzOZXA_VJk8J")).
neg(eqo("conf/sigmod/SzalayGKT00","CyzIFxmvc1cJ")).
neg(eqo("conf/sigmod/TomasicABKNR97","6CpWnsUqJNIJ")).
neg(eqo("conf/sigmod/TrisoliniLN99","YeD6vittJSMJ")).
neg(eqo("conf/sigmod/WangSSZZW00","2I65vgufa3UJ")).
neg(eqo("conf/sigmod/ZhaoDN97","YwLoGdTgG-sJ")).
neg(eqo("conf/vldb/AcharyaFZ96","9OEjtHuRUzsJ")).
neg(eqo("conf/vldb/AgrawalLSS95","ewoQO00BuFoJ")).
neg(eqo("conf/vldb/BalminPP00","url:http://portal.acm.org/citation.cfm%3Fid%3D592202.592472")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","KJhLzQw_-BkJ")).
neg(eqo("conf/vldb/BernsteinD94","rNNtyNCgHLoJ")).
neg(eqo("conf/vldb/BertinoBFS96","5Zpm_QmAfv4J")).
neg(eqo("conf/vldb/BohannonGKNS02","U7OwxK6Bpy4J")).
neg(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
neg(eqo("conf/vldb/BouganimP02","3I2LabT9FJsJ")).
neg(eqo("conf/vldb/Carey00","-gm97JzyHJsJ")).
neg(eqo("conf/vldb/ChenHWW02","63sUaS1_ALsJ")).
neg(eqo("conf/vldb/Dasgupta96","jjhaBNByh5QJ")).
neg(eqo("conf/vldb/FaloutsosG96","XY33_pzEvUoJ")).
neg(eqo("conf/vldb/GhoshPSH02","L9UCldUEnxQJ")).
neg(eqo("conf/vldb/GinisHKMT97","jj64xkk75ZIJ")).
neg(eqo("conf/vldb/GuPS00","wnke8ff8hYUJ")).
neg(eqo("conf/vldb/HaasKWY97","fsoE2pQM6G8J")).
neg(eqo("conf/vldb/HoelS95","MkUxY32K5aoJ")).
neg(eqo("conf/vldb/HulgeriS03","l5_H15LkpCsJ")).
neg(eqo("conf/vldb/JonscherD94","ubJ57pbu2KwJ")).
neg(eqo("conf/vldb/JosifovskiR99","b4XxIzOVVy0J")).
neg(eqo("conf/vldb/KangC02","gndV1O-oEkMJ")).
neg(eqo("conf/vldb/KriegelPS00","9Be3ok0Ff0kJ")).
neg(eqo("conf/vldb/LakshmiZ98","QIG8th9DHbQJ")).
neg(eqo("conf/vldb/LeslieJBY95","t4qJ1rlU01sJ")).
neg(eqo("conf/vldb/LuTD95","U9EN84liiRoJ")).
neg(eqo("conf/vldb/ManolopoulosT01","url:http://www.ingentaconnect.com/content/els/08830355/2001/00000035/00000004/art00036")).
neg(eqo("conf/vldb/MargaritisFT01","WOiDxLKSioAJ")).
neg(eqo("conf/vldb/Mattos03","EpBlTCJ0_dUJ")).
neg(eqo("conf/vldb/Moni96","hRToevpkaa0J")).
neg(eqo("conf/vldb/NishioSTTL01","S30IXg4ClFIJ")).
neg(eqo("conf/vldb/Padmanabhan96","6oGIgK6aIi8J")).
neg(eqo("conf/vldb/RastogiS98","cSEKNVCkb3sJ")).
neg(eqo("conf/vldb/RastogiS98","dqmR4pZd9oQJ")).
neg(eqo("conf/vldb/RothS97","H5bVePnEohQJ")).
neg(eqo("conf/vldb/Sacks-Davis96","4w_6_iLYHIkJ")).
neg(eqo("conf/vldb/Sarawagi95","7GpYSr7yaWAJ")).
neg(eqo("conf/vldb/SayalCDS02","2njaHdhfzAoJ")).
neg(eqo("conf/vldb/SellisRF97","moT0ba0vRKcJ")).
neg(eqo("conf/vldb/SeshadriLR96","url:http://portal.acm.org/citation.cfm%3Fid%3D304182.304226")).
neg(eqo("conf/vldb/ShaferAM96","3Ozte0ucNJAJ")).
neg(eqo("conf/vldb/ShanmugasundaramSBCLPR00","3IFlpeKgLlAJ")).
neg(eqo("conf/vldb/ShethKMWDLPLS96","HWylSJiWUsgJ")).
neg(eqo("conf/vldb/ShiSZ03","_RyWKB28b6oJ")).
neg(eqo("conf/vldb/SreenathS94","reFDs4Up9ksJ")).
neg(eqo("conf/vldb/SreenathS94","tdqKRRf9ytUJ")).
neg(eqo("conf/vldb/SrikantA95","KVEv4thH4CgJ")).
neg(eqo("conf/vldb/Suciu96","GwvN1w9_ZZoJ")).
neg(eqo("conf/vldb/Tygar98","5JKmsN-7Q9UJ")).
neg(eqo("journals/sigmod/Aberer02c","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03d","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/BuchnerM98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D306124%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ChengP03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083747%26type%3Dpdf")).
neg(eqo("journals/sigmod/DogacDATKCD98","sFXqpBTXGkkJ")).
neg(eqo("journals/sigmod/HasanFV96","vIBvTfMLL4UJ")).
neg(eqo("journals/sigmod/HummerLW02","DbJdRHd_HGQJ")).
neg(eqo("journals/sigmod/Ioannidis96","98QxJB9bUL0J")).
neg(eqo("journals/sigmod/JukicNV03","iZakw-9ZuvgJ")).
neg(eqo("journals/sigmod/KannanKIK03","vBYtmDEYeK0J")).
neg(eqo("journals/sigmod/KempsterST99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D776997%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Klein94","8-eaDTdtfY4J")).
neg(eqo("journals/sigmod/Kumar03","vLsj0AQ4ee4J")).
neg(eqo("journals/sigmod/LiefkeS00","vnc0Ml_3BFsJ")).
neg(eqo("journals/sigmod/Liu01b","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/MalaikaEM03","wjj60T2PxhgJ")).
neg(eqo("journals/sigmod/MedeirosP94","chmPCuLihZoJ")).
neg(eqo("journals/sigmod/OrlandicLS02","rqZOBLs-GwkJ")).
neg(eqo("journals/sigmod/PitouraB95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604268%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian96a","4Y125m3-bsYJ")).
neg(eqo("journals/sigmod/Qian96a","hqz0_ldbdfIJ")).
neg(eqo("journals/sigmod/Qian96b","url:http://portal.acm.org/citation.cfm%3Fid%3D248603.248618%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Qian97","4Y125m3-bsYJ")).
neg(eqo("journals/sigmod/Segev94b","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/ShethBS99","uTsHgv9-zdUJ")).
neg(eqo("journals/sigmod/Stirling03","_OCaYbP2adoJ")).
neg(eqo("journals/sigmod/Suciu02","61cw9DcC6qsJ")).
neg(eqo("journals/sigmod/Suciu97","fJACk48ag-4J")).
neg(eqo("journals/sigmod/WenLMZ03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/WuY00","m8LM82GWhNwJ")).
neg(eqo("journals/tods/Chen95a","CZkreaBp75kJ")).
neg(eqo("journals/tods/DeySB99","W5Ch7V5niEEJ")).
neg(eqo("journals/tods/GibbonsMP02","duH4hvvHFfwJ")).
neg(eqo("journals/tods/LeveneL99","zzg3KI_fyyIJ")).
neg(eqo("journals/tods/Snodgrass01a","JHuJHooGoNUJ")).
neg(eqo("journals/tods/Subrahmanian94","kULyCNLRaZwJ")).
neg(eqo("journals/tods/Suciu02","_vOvQUzSV-gJ")).
neg(eqo("journals/vldb/AntoshenkovZ96","c-MP8R47zVIJ")).
neg(eqo("journals/vldb/ChenHY97","IWZsSVPC6HMJ")).
neg(eqo("journals/vldb/FiebigHKMNSW02","w_FOwUavk0kJ")).
neg(eqo("journals/vldb/StonebrakerALPSSSY96","dWgXDMGuFd4J")).
neg(eqo("journals/vldb/SwamiS95","0cL5blQvky0J")).
pos(eqo("conf/sigmod/AcharyaAFZ95","GOguWgH6D_UJ")).
pos(eqo("conf/sigmod/AcharyaGPR99a","IkNOhDqEY18J")).
pos(eqo("conf/sigmod/AcharyaGPR99a","mYFf63cZ4lUJ")).
pos(eqo("conf/sigmod/AdaliCPS96","BpZjLfob1eIJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","DHbEJyv20WMJ")).
pos(eqo("conf/sigmod/AgrawalGGR98","v9JW-UJCD-YJ")).
pos(eqo("conf/sigmod/Bampahl95","MbgdgwgZCIUJ")).
pos(eqo("conf/sigmod/BerchtoldK98","9UYo0M1RV7oJ")).
pos(eqo("conf/sigmod/BorkarDS01","8zFEVer1rBUJ")).
pos(eqo("conf/sigmod/BouguettayaBH99","siO8kr7vvLEJ")).
pos(eqo("conf/sigmod/BrinMUT97","CnTgirrsL3EJ")).
pos(eqo("conf/sigmod/BrinMUT97","FtMoh58D330J")).
pos(eqo("conf/sigmod/BrinMUT97","ZAjbM4H53aUJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","0oPBNo-ofPkJ")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","GJ_7cqL0d70J")).
pos(eqo("conf/sigmod/CareyDFHMNSSTTWZ94","dP-pHDZ7oawJ")).
pos(eqo("conf/sigmod/Chakrabarti99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304231%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChawatheG97","5O88Bum19wAJ")).
pos(eqo("conf/sigmod/ChawatheG97","JLeihu2aUqYJ")).
pos(eqo("conf/sigmod/CohenM03","bQv5hYB-JIEJ")).
pos(eqo("conf/sigmod/Cotton02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564792%26type%3Dpdf")).
pos(eqo("conf/sigmod/DoanDH01","Lv0bggWzgeoJ")).
pos(eqo("conf/sigmod/Freeston95","Fr8CPbK-IFIJ")).
pos(eqo("conf/sigmod/GravanoGT94","We2mw93oKL4J")).
pos(eqo("conf/sigmod/GravanoGT94","nAJnhh70_0kJ")).
pos(eqo("conf/sigmod/GriffinH97","UwOPyY_jchkJ")).
pos(eqo("conf/sigmod/GriffinL95","6QZGeKna5lgJ")).
pos(eqo("conf/sigmod/GriffinL95","RuYYq5xDgNYJ")).
pos(eqo("conf/sigmod/KanthRSB99","yPFlbrVJFJoJ")).
pos(eqo("conf/sigmod/LakshmananPZ03a","pci2lDLAWzMJ")).
pos(eqo("conf/sigmod/LarsonG03","14VyjJ0mnBMJ")).
pos(eqo("conf/sigmod/LitwinS00","R7Z-NlUo_YUJ")).
pos(eqo("conf/sigmod/LiuPBHPT00","q_o5zij9nCEJ")).
pos(eqo("conf/sigmod/MaddenSHR02","DkgClKWAyEIJ")).
pos(eqo("conf/sigmod/MiloAABN03","P7vZf4MkRO4J")).
pos(eqo("conf/sigmod/Mohan94","Ft1YZIFfu0cJ")).
pos(eqo("conf/sigmod/OlstonJW03","fW0CpIqoV7QJ")).
pos(eqo("conf/sigmod/QunLO03","eBXNcn6PwAEJ")).
pos(eqo("conf/sigmod/RafieiM97","Z8kRr4T21JYJ")).
pos(eqo("conf/sigmod/RafieiM97","otOkT3t9kUQJ")).
pos(eqo("conf/sigmod/RajagopalanML98","M2bWqRDDfkUJ")).
pos(eqo("conf/sigmod/RaoR98","WlSXiMaxGlQJ")).
pos(eqo("conf/sigmod/RaoR98","uHX7_KIw8uYJ")).
pos(eqo("conf/sigmod/Rosenthal01","url:http://portal.acm.org/citation.cfm%3Fid%3D375796")).
pos(eqo("conf/sigmod/SaltenisJLL00","LMm4_4_uNNoJ")).
pos(eqo("conf/sigmod/SaltenisJLL00","e0UYPB4kRCYJ")).
pos(eqo("conf/sigmod/Toyama98","h4OQc4N4kjIJ")).
pos(eqo("conf/sigmod/ViglasN02","2aeb_pBP7lcJ")).
pos(eqo("conf/sigmod/YangM97","xrTlYcyFKtwJ")).
pos(eqo("conf/sigmod/ZouS96","DYFIQvOg7rgJ")).
pos(eqo("conf/vldb/AcharyaFZ96","ccEW59Ac84MJ")).
pos(eqo("conf/vldb/AcharyaFZ96","oH_xfQI8wIgJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","1bXX8uOvfQAJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","jugePLZ8yKcJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","pRIP3vfQtpEJ")).
pos(eqo("conf/vldb/AltinelF00","JhWxdEDCPdUJ")).
pos(eqo("conf/vldb/AmmannJR95","x-H7BqZ0Hw8J")).
pos(eqo("conf/vldb/AshwinRSSS97","JB684f38DiwJ")).
pos(eqo("conf/vldb/AshwinRSSS97","vitgygjdz3AJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","4AcfxYXwZnIJ")).
pos(eqo("conf/vldb/BeneventanoBCCGMMV00","h73uxQEBESwJ")).
pos(eqo("conf/vldb/BertinoBFS96","s0v9B-K8owEJ")).
pos(eqo("conf/vldb/BonczRK98","ts5vu2eNQgYJ")).
pos(eqo("conf/vldb/CareyHMW96","Nz8zwxjBoyYJ")).
pos(eqo("conf/vldb/CuiW01","SaOd6rDz5ZgJ")).
pos(eqo("conf/vldb/EvangelidisLS95","5dnYlEMQTb0J")).
pos(eqo("conf/vldb/FangSGMU98","E7yZtVJa2xAJ")).
pos(eqo("conf/vldb/FangSGMU98","HFpxyLAucfMJ")).
pos(eqo("conf/vldb/GilbertKMS02","xziY9wNuVzwJ")).
pos(eqo("conf/vldb/GingrasL98","VSBQl2qbF8UJ")).
pos(eqo("conf/vldb/GrustKT03","25xRkmL_4BsJ")).
pos(eqo("conf/vldb/KahveciS01","bYV1jynEEO8J")).
pos(eqo("conf/vldb/KahveciS01","i6KmypFd39AJ")).
pos(eqo("conf/vldb/KeidlSSK02","Wc1ViFeRa54J")).
pos(eqo("conf/vldb/KriegelPS00","VSQ0v1UlIvoJ")).
pos(eqo("conf/vldb/KumarRRT99","1xbD4ssSjjUJ")).
pos(eqo("conf/vldb/MahnkeMS02","VhxIKKG8oWYJ")).
pos(eqo("conf/vldb/MeccaCM01","Ph7ZpmdNOPEJ")).
pos(eqo("conf/vldb/MeccaCM01","eynVF0FSPjkJ")).
pos(eqo("conf/vldb/MeccaCM01","zd9Ql77Uk2gJ")).
pos(eqo("conf/vldb/MeoPC96","4j5ryW5xA7YJ")).
pos(eqo("conf/vldb/MoserKK95","A2OQAUw2OHIJ")).
pos(eqo("conf/vldb/NetzCBF00","mRIRFxOC8A8J")).
pos(eqo("conf/vldb/RamaswamyMS98","WTYQ40Rn_tUJ")).
pos(eqo("conf/vldb/Sarawagi99","gz92a8BdTLUJ")).
pos(eqo("conf/vldb/SeshadriLR96","K62EwWeSRKUJ")).
pos(eqo("conf/vldb/ShahDR03","FR1h4tU9FosJ")).
pos(eqo("conf/vldb/ShahDR03","HGJu1Uyq-OcJ")).
pos(eqo("conf/vldb/WienerN95","LJ4M8B9mNWAJ")).
pos(eqo("conf/vldb/YangG01","LN1TWlAUa0wJ")).
pos(eqo("conf/vldb/YangG01","xQYKEHCggZQJ")).
pos(eqo("conf/vldb/ZimbraoS98","NW7m94AW6nYJ")).
pos(eqo("journals/sigmod/BernsteinDK99","Ye5fTBiMoUwJ")).
pos(eqo("journals/sigmod/BerraNT95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202670%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/EisenbergM99a","e3s4OFTeBqwJ")).
pos(eqo("journals/sigmod/EisenbergM99a","ne4v3zrmFSQJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ERqqWPMwU2sJ")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ixz5LdVw9_8J")).
pos(eqo("journals/sigmod/Hampapur99","I-r1LE1najAJ")).
pos(eqo("journals/sigmod/HasanFV96","ybOBcBXRBqUJ")).
pos(eqo("journals/sigmod/Hellerstein03","5FSG85HbUygJ")).
pos(eqo("journals/sigmod/PapazoglouH99","d5BG9F7_LGMJ")).
pos(eqo("journals/sigmod/TsotrasK96","url:http://www.springerlink.com/index/MG76EHFRC3CMWL1X.pdf")).
pos(eqo("journals/sigmod/Wong95","7F9iCGggYVgJ")).
pos(eqo("journals/sigmod/YaoG02","ARLe7W8EvDoJ")).
pos(eqo("journals/sigmod/YaoG02","M7PRDh2-0EIJ")).
pos(eqo("journals/tods/Alagic99","Gq6D6zMEPxoJ")).
pos(eqo("journals/tods/CliffordC94","OY6BjHhbz2cJ")).
pos(eqo("journals/tods/GunopulosKMSTS03","dPCeWiiqfvEJ")).
pos(eqo("journals/tods/Kuo96","VnenpXoUAmwJ")).
pos(eqo("journals/tods/MayL02","ky-2yjNGtW8J")).
pos(eqo("journals/tods/OliverS94","zAczQV37xxsJ")).
pos(eqo("journals/tods/PolyzoisG94","p7x1zGD_bkEJ")).
pos(eqo("journals/tods/WolfsonJH97","FlC-FF1hbbUJ")).
pos(eqo("journals/vldb/BerchtoldKK97","VHo2go6vjYsJ")).
pos(eqo("journals/vldb/ChanFGR02","ORkxHLb7dvcJ")).
pos(eqo("journals/vldb/EvangelidisS97","5dnYlEMQTb0J")).
pos(eqo("journals/vldb/KamelWS94","tYBrsGkj1a0J")).
pos(eqo("journals/vldb/NanopoulosM02","icoWjIZ_6IIJ")).
pos(eqo("journals/vldb/OzsuPSILM95","gld2wLKYWpsJ")).
pos(eqo("journals/vldb/PapadiasS94","_ANyhrnP3CoJ")).
pos(eqo("journals/vldb/RafieiM02","kZFfJieudW4J")).
pos(eqo("journals/vldb/RamanRH00","CgiCp6N9XZQJ")).
pos(eqo("journals/vldb/TempletonHMB95","RKNGp2gmOTUJ")).
