neg(eqo("conf/sigmod/AboulnagaC99","xzD9v9IKf54J")).
neg(eqo("conf/sigmod/AcharyaPR99","_r6fTVXSbn4J")).
neg(eqo("conf/sigmod/AdamY98","4xBgO4KaVEYJ")).
neg(eqo("conf/sigmod/AdamY98","8YuEubZX_cEJ")).
neg(eqo("conf/sigmod/Agarwal96","e5SJ3zgdwgEJ")).
neg(eqo("conf/sigmod/Aggarwal02","HAaZcc7-vqAJ")).
neg(eqo("conf/sigmod/Aggarwal03","lYRcmubWIbMJ")).
neg(eqo("conf/sigmod/AgrawalCD02","hulo0jCbUIMJ")).
neg(eqo("conf/sigmod/AgrawalES03","bL4jBJECdB0J")).
neg(eqo("conf/sigmod/AmbiteABKMMMPT98","url:http://portal.acm.org/citation.cfm%3Fid%3D288549")).
neg(eqo("conf/sigmod/Amer-YahiaFSX03","z1YR8jZV7YkJ")).
neg(eqo("conf/sigmod/Atkinson95","UASrATyuui4J")).
neg(eqo("conf/sigmod/AtzeniT97","oUOuTMrB0esJ")).
neg(eqo("conf/sigmod/BabcockCD03","BYAyZpRK7k0J")).
neg(eqo("conf/sigmod/BerchtoldK98","pKKu82IYP9EJ")).
neg(eqo("conf/sigmod/BertinoCF01","oRWtcCo6xlAJ")).
neg(eqo("conf/sigmod/BeyerR99","ZxG6NtFHRC8J")).
neg(eqo("conf/sigmod/Blakeley96","url:http://portal.acm.org/citation.cfm%3Fid%3D603867.603883%26dl%3DGUIDE%26dl%3DACM%26type%3Dissue%26idx%3D603867%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/BlohsfeldKS99","jmTe2JwKfVYJ")).
neg(eqo("conf/sigmod/BlohsfeldKS99","uibe8EM86AQJ")).
neg(eqo("conf/sigmod/BohmBKK01","SUT-QTwqFNkJ")).
neg(eqo("conf/sigmod/Bonnet02","QuxjJV86heUJ")).
neg(eqo("conf/sigmod/BorkarDS01","8zFEVer1rBUJ")).
neg(eqo("conf/sigmod/BornhovdAKMPR03","u64n4yMnma4J")).
neg(eqo("conf/sigmod/BressanGFJHKLMPQSS97","r62IMncHe0IJ")).
neg(eqo("conf/sigmod/BrinMS97","3-iiSyJLwLkJ")).
neg(eqo("conf/sigmod/BrinMS97","F90sN5_2R-wJ")).
neg(eqo("conf/sigmod/BrinkhoffKSS94","vKRAglMStUMJ")).
neg(eqo("conf/sigmod/BrodskyK95","A5s_U6Ixg3EJ")).
neg(eqo("conf/sigmod/CareyDNAGS97","oehMZf9BDZoJ")).
neg(eqo("conf/sigmod/CatarciS01","hFjyiww4Py8J")).
neg(eqo("conf/sigmod/CeriFPP95","h_g4xOpUq6wJ")).
neg(eqo("conf/sigmod/ChakrabartiDI98","2LdUbNy0hWwJ")).
neg(eqo("conf/sigmod/ChanI99","KuA45Oh0rkYJ")).
neg(eqo("conf/sigmod/ChaudhuriDY95","jq5VkbTyBksJ")).
neg(eqo("conf/sigmod/ChaudhuriGS03","oahM5itk_dAJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","GL8XEeYm7GsJ")).
neg(eqo("conf/sigmod/ChaudhuriMN98","vWVZ65WQKtoJ")).
neg(eqo("conf/sigmod/ChaudhuriN98a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D375755%26type%3Dpdf%26dl%3DGUIDE%26dl%3DGUIDE%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ChenCPPSTM00","5BK4tIRJ3wwJ")).
neg(eqo("conf/sigmod/ChenGM01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D1083795%26type%3Dpdf")).
neg(eqo("conf/sigmod/ChenJDTW00","5Trj9q_RI8YJ")).
neg(eqo("conf/sigmod/ChenR94","f6JFkfhawW8J")).
neg(eqo("conf/sigmod/ChenR94","vifclP3m_JMJ")).
neg(eqo("conf/sigmod/ChenWZ98","eBoENxLSBz8J")).
neg(eqo("conf/sigmod/ChoiC02","D8a4umAppIcJ")).
neg(eqo("conf/sigmod/ChoiC02","QIG8th9DHbQJ")).
neg(eqo("conf/sigmod/Cohen98","PSQ-qYD4aiAJ")).
neg(eqo("conf/sigmod/Cohen98","_ICk4vgjlgsJ")).
neg(eqo("conf/sigmod/DanielsDDEHJJLSSS94","iCg06Oc9DV8J")).
neg(eqo("conf/sigmod/DasGR03","inuIcjK-wgEJ")).
neg(eqo("conf/sigmod/DeutschFS99","Jg81WYtxtZoJ")).
neg(eqo("conf/sigmod/FranklinJK96","lkrtCULVA6oJ")).
neg(eqo("conf/sigmod/Freeston95","Fr8CPbK-IFIJ")).
neg(eqo("conf/sigmod/Freeston95","VgNVmDpq6zkJ")).
neg(eqo("conf/sigmod/GebhardtJJ97","9mbr0dyW1NgJ")).
neg(eqo("conf/sigmod/GehrkeKS01","f6JFkfhawW8J")).
neg(eqo("conf/sigmod/GingrasLSPS97","hlbdfqaXdkAJ")).
neg(eqo("conf/sigmod/GotoK03","umqiMNB4904J")).
neg(eqo("conf/sigmod/GotoK03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D872837%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/GravanoCGP97","lwbB467LzwEJ")).
neg(eqo("conf/sigmod/GravanoGT94","aXLcAfb2y5kJ")).
neg(eqo("conf/sigmod/Gray95","HVMK4a5mtlwJ")).
neg(eqo("conf/sigmod/GrayHOS96","eRXTKT6GvM8J")).
neg(eqo("conf/sigmod/Greer99","3mgk6qNKT9QJ")).
neg(eqo("conf/sigmod/Greer99","dAnyGPqToQEJ")).
neg(eqo("conf/sigmod/Grust02","uTVqF9CbsZMJ")).
neg(eqo("conf/sigmod/Han96","U7glO1ebLPYJ")).
neg(eqo("conf/sigmod/HanFHCC94","3MLMQVmYAKcJ")).
neg(eqo("conf/sigmod/HanKK97","TDCRuRgnWDIJ")).
neg(eqo("conf/sigmod/HanWDPW02","CnAw9v-vEjwJ")).
neg(eqo("conf/sigmod/Hellerstein00","vCvPdFwbKWkJ")).
neg(eqo("conf/sigmod/HellersteinA00","ZvAJ8US6e0kJ")).
neg(eqo("conf/sigmod/HernandezS95","qOsozIYCBxgJ")).
neg(eqo("conf/sigmod/Hidber99","4n3d9sH99XsJ")).
neg(eqo("conf/sigmod/HoAMS97","HCPysSEoHZ0J")).
neg(eqo("conf/sigmod/Hope95","inuBdxKX-1wJ")).
neg(eqo("conf/sigmod/IlyasRLGL03","iubeta9kU6AJ")).
neg(eqo("conf/sigmod/ImielinskiV95","Vw5YZGwajh4J")).
neg(eqo("conf/sigmod/JaedickeM98","wVbMknDFKIsJ")).
neg(eqo("conf/sigmod/Jagadish94","ILpAqeFXv58J")).
neg(eqo("conf/sigmod/JagadishJOT01","aU7XlTpoxRgJ")).
neg(eqo("conf/sigmod/Jamil99","NLFmYaDhYccJ")).
neg(eqo("conf/sigmod/Jamil99","VJIHPbki2uAJ")).
neg(eqo("conf/sigmod/JarkeQBLMS99","q87jrCR_GqQJ")).
neg(eqo("conf/sigmod/JarkeQCLFLVV00","Rqg_slyUMYMJ")).
neg(eqo("conf/sigmod/JonkerS95","eSPpim_OX4QJ")).
neg(eqo("conf/sigmod/JosifovskiSHL02","xA9KNostV4cJ")).
neg(eqo("conf/sigmod/KabraD98","KKiefntReoUJ")).
neg(eqo("conf/sigmod/KanthRSB99","y9kXMZjBMZgJ")).
neg(eqo("conf/sigmod/KornJF97","AygQeIp71_YJ")).
neg(eqo("conf/sigmod/KornackerMH97","mBC03oUT8yAJ")).
neg(eqo("conf/sigmod/KotidisR99","JBQdOatWia0J")).
neg(eqo("conf/sigmod/KotidisR99","u6kojfiogY8J")).
neg(eqo("conf/sigmod/KriegelBKPS03","PsoYENGEh9cJ")).
neg(eqo("conf/sigmod/KriegelBKPS03","rgJU30QjbhkJ")).
neg(eqo("conf/sigmod/Krishnamurthy03","UYAoi4DYOXUJ")).
neg(eqo("conf/sigmod/Krishnamurthy03","url:http://ieeexplore.ieee.org/iel1/2206/2685/00081889.pdf%3Farnumber%3D81889")).
neg(eqo("conf/sigmod/KuhnTS94","IBg3vuolFUwJ")).
neg(eqo("conf/sigmod/LarsonG03","goq6Z9bDeSsJ")).
neg(eqo("conf/sigmod/LarsonG03","lJvM7i4RgpAJ")).
neg(eqo("conf/sigmod/Lassettre98","7p2MaOtr7u8J")).
neg(eqo("conf/sigmod/LaursenOP94","XAWxqf9fnOMJ")).
neg(eqo("conf/sigmod/LeeWMS01","ExOv1ThwJiYJ")).
neg(eqo("conf/sigmod/LiBCS00","5az0lEu2-FIJ")).
neg(eqo("conf/sigmod/LiefkeS00","epCsER2LDJgJ")).
neg(eqo("conf/sigmod/LivnyRBCDLMW97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D122052%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/LlirbatFS97","rgJU30QjbhkJ")).
neg(eqo("conf/sigmod/LoR94","7-Suml1GqBQJ")).
neg(eqo("conf/sigmod/LometT03","P7GUGC5bz7wJ")).
neg(eqo("conf/sigmod/LometT03","fI5o4MfWwzIJ")).
neg(eqo("conf/sigmod/LometW98","F2ecYx97F2sJ")).
neg(eqo("conf/sigmod/LuWYBLY02","jN8ws_LDhNUJ")).
neg(eqo("conf/sigmod/MamoulisP99","IvMJ4bK708kJ")).
neg(eqo("conf/sigmod/Martin94","_HtX2ujjOf0J")).
neg(eqo("conf/sigmod/Martin94","rnFt_--hj10J")).
neg(eqo("conf/sigmod/Martin94","wSMRX5CsNVoJ")).
neg(eqo("conf/sigmod/MelnikRB03","veL-zDfjXrEJ")).
neg(eqo("conf/sigmod/Miller98","ButmJWjGXusJ")).
neg(eqo("conf/sigmod/MiloAABN03","8TcpKdIK1r0J")).
neg(eqo("conf/sigmod/MohanN94","E2zhARKv5dsJ")).
neg(eqo("conf/sigmod/MohanN94","KvhuIhTTj_YJ")).
neg(eqo("conf/sigmod/NatsevRS99","4DkDEOrojB0J")).
neg(eqo("conf/sigmod/NybergBCGL94","7MW-Zq2-on4J")).
neg(eqo("conf/sigmod/OhHP00","HzOZXA_VJk8J")).
neg(eqo("conf/sigmod/OhHP00","e1VDtDlm44oJ")).
neg(eqo("conf/sigmod/Olson95","iRY7WP0MByAJ")).
neg(eqo("conf/sigmod/Ozsu99","okSXCoQ76_IJ")).
neg(eqo("conf/sigmod/PapadiasTSE95","oIc_goYCwh4J")).
neg(eqo("conf/sigmod/PapakonstantinouV99","UrpPvOlm9RYJ")).
neg(eqo("conf/sigmod/PatelD96","nmTGteLy8NAJ")).
neg(eqo("conf/sigmod/Pirahesh94","FRh7wTjbGAcJ")).
neg(eqo("conf/sigmod/PoosalaIHS96","-NB01PtLzKYJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","VJIHPbki2uAJ")).
neg(eqo("conf/sigmod/RamaswamyRS00","o0vnSBVzRQcJ")).
neg(eqo("conf/sigmod/Rodriguez-Martinez00","dVDzCb6fuJ0J")).
neg(eqo("conf/sigmod/Ross00","RbBzMy1XNyQJ")).
neg(eqo("conf/sigmod/RoussopoulosKS99","s-BNLG-eGlYJ")).
neg(eqo("conf/sigmod/RoySSB00","VJIHPbki2uAJ")).
neg(eqo("conf/sigmod/SaltenisJLL00","VSQ0v1UlIvoJ")).
neg(eqo("conf/sigmod/Seshadri99","agDPIoUHAxMJ")).
neg(eqo("conf/sigmod/ShashaB02","oFFoTV3tb24J")).
neg(eqo("conf/sigmod/ShashaB02","uaOB9o42w5AJ")).
neg(eqo("conf/sigmod/SzalayGTKMRSv02","AY4SsaPul-AJ")).
neg(eqo("conf/sigmod/Tajima96","IZSzLlgi8tUJ")).
neg(eqo("conf/sigmod/Team95a","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D0294191CI")).
neg(eqo("conf/sigmod/Team95b","v80FFBUTW_0J")).
neg(eqo("conf/sigmod/TomasicABKNR97","IgAEpc8ulvYJ")).
neg(eqo("conf/sigmod/TsueiPK97","0HqTsg3Fcr8J")).
neg(eqo("conf/sigmod/Vaskevitch94","fW9j2V5gnUMJ")).
neg(eqo("conf/sigmod/WangTYGWP02","E6PirEnjajUJ")).
neg(eqo("conf/sigmod/Whelan98","46L_OgVDfJoJ")).
neg(eqo("conf/sigmod/WhiteD95","6SBwemr2zscJ")).
neg(eqo("conf/sigmod/WynblattN01","LVitsyrkl9AJ")).
neg(eqo("conf/sigmod/YangWYH02","wQ0ZDLJm79YJ")).
neg(eqo("conf/sigmod/ZhangDWEMPMDR03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D769815%26type%3Dhtml%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/sigmod/ZhaoDNS98","c0D02SzWH9MJ")).
neg(eqo("conf/sigmod/ZhouLP99","Kv83PnRGpIwJ")).
neg(eqo("conf/sigmod/ZouS96","_OimKPnidhsJ")).
neg(eqo("conf/vldb/AggarwalY02","x5jeMyauzWgJ")).
neg(eqo("conf/vldb/AgrawalCN00","_dFbKZPCblQJ")).
neg(eqo("conf/vldb/AgrawalCN00","_tle794_iKcJ")).
neg(eqo("conf/vldb/AgrawalKSX02","P3GB0IRKc2IJ")).
neg(eqo("conf/vldb/AgrawalS94","-fXblp3TRRoJ")).
neg(eqo("conf/vldb/AgrawalSX01","J3bObN0lQwMJ")).
neg(eqo("conf/vldb/AgrawalSX01","P3GB0IRKc2IJ")).
neg(eqo("conf/vldb/AgrawalSX01","Y799jSppkKEJ")).
neg(eqo("conf/vldb/AgrawalSX02","E9AsPVyCDlMJ")).
neg(eqo("conf/vldb/AlonsoHST97","2IXVkURyXPsJ")).
neg(eqo("conf/vldb/AlonsoHST97","_UTAtx9zoaAJ")).
neg(eqo("conf/vldb/AmbiteKKMST01","F4DtzxvVZnoJ")).
neg(eqo("conf/vldb/Amer-YahiaCD98","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D306124%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("conf/vldb/Amer-YahiaFSX03","fcB_7jx0pOMJ")).
neg(eqo("conf/vldb/AmielBDS94","CFCPelD0aAMJ")).
neg(eqo("conf/vldb/AnciauxBBPV01","WyQYXAH1Zp8J")).
neg(eqo("conf/vldb/AtzeniMM97","r90B-sIjtEwJ")).
neg(eqo("conf/vldb/BamfordAP99","2y9m1qzVu4EJ")).
neg(eqo("conf/vldb/BaralisW94","cz8TiCxFsxsJ")).
neg(eqo("conf/vldb/BaumannFRW97","7BgXVuviUvoJ")).
neg(eqo("conf/vldb/BawaBA03","ZjIllDHwkSoJ")).
neg(eqo("conf/vldb/BawaBA03","mrbnuRR0u14J")).
neg(eqo("conf/vldb/BenediktCFRZZ02","7xe6Gp9fIEEJ")).
neg(eqo("conf/vldb/BeneventanoBCCGMMV00","YPYbFZ4-1UQJ")).
neg(eqo("conf/vldb/Bernstein94","0KiQzAIFlJkJ")).
neg(eqo("conf/vldb/BertinoBFS96","zWm1GKhwGeUJ")).
neg(eqo("conf/vldb/Blum99","sg4AkUiRIVgJ")).
neg(eqo("conf/vldb/BohannonLRSSS97","rFdqdXVhLooJ")).
neg(eqo("conf/vldb/BonczMK99","qv9JuA63NQMJ")).
neg(eqo("conf/vldb/BonifatiCDS01","Es_3dP3hpQcJ")).
neg(eqo("conf/vldb/BridgeJKLLM97","0gGp8UvP8QQJ")).
neg(eqo("conf/vldb/BrightR02","k3znuHyMD0oJ")).
neg(eqo("conf/vldb/BrinkhoffK94","Sid6kFl9M7oJ")).
neg(eqo("conf/vldb/CareyK98","2KGSQBJMexIJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","QyBDbs7EpmsJ")).
neg(eqo("conf/vldb/ChakrabartiDAR97","x4KMrZ-ES70J")).
neg(eqo("conf/vldb/ChanGR02","eHY42LnL_lsJ")).
neg(eqo("conf/vldb/ChangG00","rcSfDxBif40J")).
neg(eqo("conf/vldb/Chawathe99","JLeihu2aUqYJ")).
neg(eqo("conf/vldb/Chawathe99","eyl8gnuvxDUJ")).
neg(eqo("conf/vldb/ChenCFGJMTW99","ZHcRBZlVlwoJ")).
neg(eqo("conf/vldb/ChenJLP03","BGcx_nZKM4wJ")).
neg(eqo("conf/vldb/CherniackZ98","ptjj-czWemUJ")).
neg(eqo("conf/vldb/ChoALS02","eCQjRu0EiagJ")).
neg(eqo("conf/vldb/ChoG00","0DBJI3YNzzQJ")).
neg(eqo("conf/vldb/ChoN02","fjyuOyUdGGcJ")).
neg(eqo("conf/vldb/ConradGJM02","4H2Plsrv1AkJ")).
neg(eqo("conf/vldb/CooperSFHS01","64mYZX3mXKMJ")).
neg(eqo("conf/vldb/CormodeKMS03","rrHUOuKLn1gJ")).
neg(eqo("conf/vldb/CowleyP00","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3D468964CI")).
neg(eqo("conf/vldb/DarEGP98","D6gxih90YU4J")).
neg(eqo("conf/vldb/DayalHL01","XwzOOLb-ZMIJ")).
neg(eqo("conf/vldb/DayalHL01","lBq7bzIzng4J")).
neg(eqo("conf/vldb/DayalHL01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672352")).
neg(eqo("conf/vldb/DeenJNNW00","l9NZjT2PQpcJ")).
neg(eqo("conf/vldb/DesslochM97","V5O37YacElIJ")).
neg(eqo("conf/vldb/DonjerkovicR99","4U31XD8P478J")).
neg(eqo("conf/vldb/EleftheriouBCDHLPPABDDDGJHLRSVW03","sRgUm7BR9EAJ")).
neg(eqo("conf/vldb/EsterKSWX98","A9DRpN1hJUgJ")).
neg(eqo("conf/vldb/FaloutsosMS96","MxkjWOlLhlYJ")).
neg(eqo("conf/vldb/FerrandinaMZFM95","goBF44NbvooJ")).
neg(eqo("conf/vldb/GalhardasFSSS01","OEpwAcnqlWwJ")).
neg(eqo("conf/vldb/GalhardasFSSS01","Y9hnVmMeigcJ")).
neg(eqo("conf/vldb/GardarinST96","HKIrMyH9booJ")).
neg(eqo("conf/vldb/GarofalakisG01","2TVYDBNYioIJ")).
neg(eqo("conf/vldb/GeorgeH98","nlh2WXZT3VIJ")).
neg(eqo("conf/vldb/GravanoIJKMS01","JaC8ZOgaYU4J")).
neg(eqo("conf/vldb/GuptaM96","hPWDomB8y6wJ")).
neg(eqo("conf/vldb/HoelS95","uS-v_N8yu7MJ")).
neg(eqo("conf/vldb/HuebschHLLSS03","Fg0Y-u39c7oJ")).
neg(eqo("conf/vldb/IlyasAE03","4K4WSmubERcJ")).
neg(eqo("conf/vldb/IlyasAE03","zWgsO3kf0fMJ")).
neg(eqo("conf/vldb/IshikawaSF98","5nSsvC--8ioJ")).
neg(eqo("conf/vldb/JiangWL03","GahdNMZNCWgJ")).
neg(eqo("conf/vldb/JiangWL03","s3bawcAka-EJ")).
neg(eqo("conf/vldb/KamelF94","B9qkCvLOE8sJ")).
neg(eqo("conf/vldb/KaushikBNS02","dL5oJVHK10kJ")).
neg(eqo("conf/vldb/KemperK94","qUfWV4VVxegJ")).
neg(eqo("conf/vldb/Keogh02","iFJwVZqHRCwJ")).
neg(eqo("conf/vldb/KerstenWFKBC03","R46DoTW4ul8J")).
neg(eqo("conf/vldb/KerstenWFKBC03","cZsiuZAvlTUJ")).
neg(eqo("conf/vldb/KietzRS97","qyXhN3CrVQ8J")).
neg(eqo("conf/vldb/KonigW99","W26hEZGq9uMJ")).
neg(eqo("conf/vldb/Korth95","ET_i3QwZryQJ")).
neg(eqo("conf/vldb/Korth95","q9FSSXk_4vcJ")).
neg(eqo("conf/vldb/KoschBBHHLRT01","1CYEGct952YJ")).
neg(eqo("conf/vldb/KoschBBHHLRT01","4Ns56TPqqcsJ")).
neg(eqo("conf/vldb/KoudasMJ99","6uP3E_WEkCAJ")).
neg(eqo("conf/vldb/KoudasMJ99","cVfK4i2ubN4J")).
neg(eqo("conf/vldb/KumarKA97","8bLd-1l1at4J")).
neg(eqo("conf/vldb/KumarKA97","LJgXl8u26jUJ")).
neg(eqo("conf/vldb/LabioYCGW00","9qOUH5DfZ64J")).
neg(eqo("conf/vldb/Ladin00","nkZCOasEJyMJ")).
neg(eqo("conf/vldb/LakshmananJN00","1n7AY641YyAJ")).
neg(eqo("conf/vldb/LakshmananPH02","OYOTbj4m7JYJ")).
neg(eqo("conf/vldb/LakshmananPZ03","01ZVDudF4WAJ")).
neg(eqo("conf/vldb/LakshmananPZ03","7Xoa7OiZLXMJ")).
neg(eqo("conf/vldb/LakshmiZ98","krAZ7iDMEOQJ")).
neg(eqo("conf/vldb/LernerS03","Xs8A5V9n3okJ")).
neg(eqo("conf/vldb/Lesk94","pYd_oa0DxQ8J")).
neg(eqo("conf/vldb/LeslieJBY95","kZFfJieudW4J")).
neg(eqo("conf/vldb/LimWV03","jD2MXT_dgZgJ")).
neg(eqo("conf/vldb/MadhavanBR01","5mM4rpgyeNoJ")).
neg(eqo("conf/vldb/MaedaT01","dipeGpTdsoQJ")).
neg(eqo("conf/vldb/Malaika96","PH1Zo2uG8V0J")).
neg(eqo("conf/vldb/Mattos96","EpBlTCJ0_dUJ")).
neg(eqo("conf/vldb/Mina98","hiAb_9RGvQUJ")).
neg(eqo("conf/vldb/MiningGroup96","htMO0uWGzvoJ")).
neg(eqo("conf/vldb/Mohan02a","IGS3TtqfKUgJ")).
neg(eqo("conf/vldb/Mohan02a","NwBwLRnC0QkJ")).
neg(eqo("conf/vldb/MohanBWSZ00","-gQb5oEVQgYJ")).
neg(eqo("conf/vldb/MohanBWSZ00","EAZ5Gz22bIUJ")).
neg(eqo("conf/vldb/MorishimaKKT01","hRToevpkaa0J")).
neg(eqo("conf/vldb/MuthOPW98","S0joKxiOuiAJ")).
neg(eqo("conf/vldb/NaumannLF99","Nh9dbjE8qGcJ")).
neg(eqo("conf/vldb/NetzCBF00","-p-fOcHnFuQJ")).
neg(eqo("conf/vldb/NishioSTTL01","X2aoxVe31rgJ")).
neg(eqo("conf/vldb/NishioSTTL01","epUf9ogilogJ")).
neg(eqo("conf/vldb/OConnellWG01","nUFhC9syaNsJ")).
neg(eqo("conf/vldb/Ogawa96","W80_hO4TTCYJ")).
neg(eqo("conf/vldb/OlstonW00","pBKI-JCAlcIJ")).
neg(eqo("conf/vldb/OoiYTJ01","jsJJXMHfgxAJ")).
neg(eqo("conf/vldb/OrensteinK95","Trw6DEZeqTsJ")).
neg(eqo("conf/vldb/PalpanasSCP02","5DHjdE0sKzgJ")).
neg(eqo("conf/vldb/PanRAMOHAMV02","0HlMHEPJRH4J")).
neg(eqo("conf/vldb/PapadimitriouBF03","xYUrn78qvEkJ")).
neg(eqo("conf/vldb/PedersenJD99","sAUncbolYJ8J")).
neg(eqo("conf/vldb/PellenkoftLK97","6fpcAWvCcy4J")).
neg(eqo("conf/vldb/PereiraFLS00","jELnwotIy9kJ")).
neg(eqo("conf/vldb/Pogue98","bYLjqg3pPNgJ")).
neg(eqo("conf/vldb/PoosalaI97","Qmv55n1HpkAJ")).
neg(eqo("conf/vldb/PopaVMHF02","url:http://portal.acm.org/citation.cfm%3Fid%3D641077")).
neg(eqo("conf/vldb/RaghavanG03","eKWSSO16E4EJ")).
neg(eqo("conf/vldb/RamakrishnanR96","k7G60pXtD58J")).
neg(eqo("conf/vldb/RamanRH99","QLJhG6Rz2T0J")).
neg(eqo("conf/vldb/Ramanan03","QCJEyGp-iZcJ")).
neg(eqo("conf/vldb/Rengarajan96","Opm5VlTzQTAJ")).
neg(eqo("conf/vldb/ReuterCGSW95","pN4pq6qELakJ")).
neg(eqo("conf/vldb/RisheYACLMVSV00","0WYMHga_bt4J")).
neg(eqo("conf/vldb/RossS97","QqbsSnFuq_gJ")).
neg(eqo("conf/vldb/RoussopoulosK98","VVIikp7RNGcJ")).
neg(eqo("conf/vldb/SahuguetA99","NrXmzugArgoJ")).
neg(eqo("conf/vldb/SakuraiYUK00","_MFspYlUSiMJ")).
neg(eqo("conf/vldb/Schoning03","url:http://www.csa.com/partners/viewrecord.php%3Frequester%3Dgs%26collection%3DTRD%26recid%3DN7626882AH")).
neg(eqo("conf/vldb/Selinger02","url:http://portal.acm.org/citation.cfm%3Fid%3D641269")).
neg(eqo("conf/vldb/SeshadriLR96","N9NdxNRvMMkJ")).
neg(eqo("conf/vldb/ShahDR03","McBDUjHnS7YJ")).
neg(eqo("conf/vldb/ShahDR03","Zlk6Tn-sPxwJ")).
neg(eqo("conf/vldb/ShanmugasundaramGTZDN99","rJR-VyAF77wJ")).
neg(eqo("conf/vldb/SimonD95","lLARMvKaIQMJ")).
neg(eqo("conf/vldb/SreenathS94","dTHfvsLNE3wJ")).
neg(eqo("conf/vldb/Suciu96a","1sGr4qMsCeMJ")).
neg(eqo("conf/vldb/TsoisS03","ErsJTNGOScsJ")).
neg(eqo("conf/vldb/TsoisS03","g3sptFR4whsJ")).
neg(eqo("conf/vldb/TsoisS03","gIFZWp_iCmUJ")).
neg(eqo("conf/vldb/TsurAADKW01","q4c6LosfU7YJ")).
neg(eqo("conf/vldb/VermeerA96","Z9mXIC2tjJ0J")).
neg(eqo("conf/vldb/VermeerA96","ZDE6Z3CnuDsJ")).
neg(eqo("conf/vldb/Vieille98","tFwhdyBRe78J")).
neg(eqo("conf/vldb/VorugantiOU99","ismgfqU0OJQJ")).
neg(eqo("conf/vldb/Wadler01","uAdfU0W_T-UJ")).
neg(eqo("conf/vldb/Wang95","sqOG0h5o8RYJ")).
neg(eqo("conf/vldb/WangSG03","kxGdQhvpi_sJ")).
neg(eqo("conf/vldb/WangZ00","eDa9jQWsTMoJ")).
neg(eqo("conf/vldb/WienerN94","eFynrwKK_T0J")).
neg(eqo("conf/vldb/WiesnerK01","url:http://portal.acm.org/citation.cfm%3Fid%3D645927.672352")).
neg(eqo("conf/vldb/WuYCT95","JXI-CvxzElQJ")).
neg(eqo("conf/vldb/YagoubFIV00","195Hlqu94qEJ")).
neg(eqo("conf/vldb/YanL95","VwsS71_KQX8J")).
neg(eqo("conf/vldb/YangKL97","Z1Lb7YfN8vUJ")).
neg(eqo("conf/vldb/ZellerK02","bAxUjxF0f4EJ")).
neg(eqo("conf/vldb/ZhouR03","WFXMYflMtBYJ")).
neg(eqo("conf/vldb/ZouS98","02mWIBvIsVwJ")).
neg(eqo("journals/sigmod/AbelTK97","0lon2YPMr9oJ")).
neg(eqo("journals/sigmod/Aberer01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D126493%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer01a","oacFELqmw0cJ")).
neg(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D507353%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03b","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D641004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Aberer03c","DJpFoidxWGMJ")).
neg(eqo("journals/sigmod/Aberer03d","hBrgosYDi3oJ")).
neg(eqo("journals/sigmod/AbererCH02","IHPilG_MCDoJ")).
neg(eqo("journals/sigmod/Abiteboul99","zHCrzBCoweAJ")).
neg(eqo("journals/sigmod/Abiteboul99","zRzwh7_az94J")).
neg(eqo("journals/sigmod/AdelbergKG96","GpYZAL6HBlIJ")).
neg(eqo("journals/sigmod/Aggarwal01","qbubaA6mQawJ")).
neg(eqo("journals/sigmod/Badia02","-kRcfFF9-wEJ")).
neg(eqo("journals/sigmod/BargaL02","qIBrxCTdrUMJ")).
neg(eqo("journals/sigmod/BerndtssonH96","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057808")).
neg(eqo("journals/sigmod/Bernstein98","AYEI8XDoY9wJ")).
neg(eqo("journals/sigmod/BerraNT95","eQPLe8gg-mIJ")).
neg(eqo("journals/sigmod/Bestavros96","b-HPvd6xzsoJ")).
neg(eqo("journals/sigmod/BohmR94","HTvxhMKB69AJ")).
neg(eqo("journals/sigmod/BohmR94","wLNJcNvsulkJ")).
neg(eqo("journals/sigmod/BonnetBDL03","aovCRhocZUcJ")).
neg(eqo("journals/sigmod/BoulosO99","yzbCsw2erkcJ")).
neg(eqo("journals/sigmod/BunemanFSW01","gBFjCncGaXMJ")).
neg(eqo("journals/sigmod/BurtonM98","coNBTxEjQIUJ")).
neg(eqo("journals/sigmod/CalvaneseGLV03","nIuz3dc8yHMJ")).
neg(eqo("journals/sigmod/CeriFP99","iUGa3pKj-20J")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","48tNIIhyVtsJ")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","iY5wlS4jsg0J")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","nlna-xElM08J")).
neg(eqo("journals/sigmod/ChakravarthyAEFO03","url:http://portal.acm.org/citation.cfm%3Fid%3D163090.163102%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ChangASS98","1sBvG9OXpMAJ")).
neg(eqo("journals/sigmod/ChangGKRS98","J-wCX3qr5ugJ")).
neg(eqo("journals/sigmod/ChienTZ01","cjBpI3TcSWsJ")).
neg(eqo("journals/sigmod/ClementLGMK97","jS3lxgrUXyEJ")).
neg(eqo("journals/sigmod/Colliat96","y0HXub5QzkYJ")).
neg(eqo("journals/sigmod/DoanPK95","Pa_ObVyi9TcJ")).
neg(eqo("journals/sigmod/Dogac96","-LIxgdLhgEYJ")).
neg(eqo("journals/sigmod/DogacAOD95","Wcbvsi-QDtcJ")).
neg(eqo("journals/sigmod/DunhamH95a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D988600%26type%3Dpdf")).
neg(eqo("journals/sigmod/EisenbergM01","7aUag74jtdIJ")).
neg(eqo("journals/sigmod/ElmagarmidJF95","-O2gEZDOEWYJ")).
neg(eqo("journals/sigmod/FininJ02","t3GxPAGPqDoJ")).
neg(eqo("journals/sigmod/Fong95","zw3-t-veNvAJ")).
neg(eqo("journals/sigmod/Fong97","JlS5P7ZUhp0J")).
neg(eqo("journals/sigmod/Fong97","m2CCumFeAWgJ")).
neg(eqo("journals/sigmod/Fong97","rgJU30QjbhkJ")).
neg(eqo("journals/sigmod/Franklin00","TUOBVMb4PBsJ")).
neg(eqo("journals/sigmod/Franklin00","eU-7sSXW5jEJ")).
neg(eqo("journals/sigmod/Franklin99","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Franklin99a","9slyrfHHIwoJ")).
neg(eqo("journals/sigmod/Franklin99b","qq2lTNrNTBUJ")).
neg(eqo("journals/sigmod/GobleR02","igXfXik3h7EJ")).
neg(eqo("journals/sigmod/GottlobKP03","fnIXflrczOEJ")).
neg(eqo("journals/sigmod/GrayG97","fFCqy9V5XNgJ")).
neg(eqo("journals/sigmod/GrayG97","zo5i5LKtKHEJ")).
neg(eqo("journals/sigmod/Grefen02","prmPWENxyWwJ")).
neg(eqo("journals/sigmod/GunopulosK01","o3Lll6m9RBAJ")).
neg(eqo("journals/sigmod/Hainaut03","url:http://www.springerlink.com/index/U04R834455V753R5.pdf")).
neg(eqo("journals/sigmod/Hammer00","2LHYBL13jCoJ")).
neg(eqo("journals/sigmod/Han98","rPB2NYjIGfQJ")).
neg(eqo("journals/sigmod/Hoffner03","Ltf5yQsl8sMJ")).
neg(eqo("journals/sigmod/Hoffner03","UAO4T_2ylPkJ")).
neg(eqo("journals/sigmod/Huyn01","I2Md2kGPQ6cJ")).
neg(eqo("journals/sigmod/Huyn01","OrTCIFg9fBIJ")).
neg(eqo("journals/sigmod/Jannink95","u2y1FpwC6cgJ")).
neg(eqo("journals/sigmod/KarlapalemLS95","NjLKM1vuiXsJ")).
neg(eqo("journals/sigmod/KennedyMB96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D604286%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Kim94","7TYVQTwq9FIJ")).
neg(eqo("journals/sigmod/KlasS94","Opow89YK6a8J")).
neg(eqo("journals/sigmod/KokkotosIPS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D974142%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Konig-RiesMMPPRSVW02","9kl_hTyQtmQJ")).
neg(eqo("journals/sigmod/LabrinidisM01","ll8GRo5AxaMJ")).
neg(eqo("journals/sigmod/LenzeriniNNS01","5B6AOvbnUTMJ")).
neg(eqo("journals/sigmod/Ley00","yY3aV9CpCjwJ")).
neg(eqo("journals/sigmod/Libkin99a","UYAoi4DYOXUJ")).
neg(eqo("journals/sigmod/Liu01a","qq2lTNrNTBUJ")).
neg(eqo("journals/sigmod/Liu02a","_SsvlmhsusEJ")).
neg(eqo("journals/sigmod/Liu02c","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Liu03","vgcXH5aVpdgJ")).
neg(eqo("journals/sigmod/Liu03b","5l2xUevEqhQJ")).
neg(eqo("journals/sigmod/Lomet01","PW6NoDiVVlUJ")).
neg(eqo("journals/sigmod/MattosD94","oNYOKYvjoKgJ")).
neg(eqo("journals/sigmod/MedskerCS95","Nb-E5IXv5HcJ")).
neg(eqo("journals/sigmod/MillerHHYHFP01","OG2h8CIVhkUJ")).
neg(eqo("journals/sigmod/MillerHHYHFP01","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D234902%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ONeilG95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D945725%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Ozsu02","J5HQj5rH5icJ")).
neg(eqo("journals/sigmod/Ozsu02b","vvVvm0UATYQJ")).
neg(eqo("journals/sigmod/Palpanas00","VgTAaMMYkvAJ")).
neg(eqo("journals/sigmod/PossasMCR00","SZwq84m3bGYJ")).
neg(eqo("journals/sigmod/Qian95","-TPeMEC6_UkJ")).
neg(eqo("journals/sigmod/Qian95b","Jg81WYtxtZoJ")).
neg(eqo("journals/sigmod/Qian95b","fTbCV3Lh8W0J")).
neg(eqo("journals/sigmod/Qian96","mH0vNFMcLxsJ")).
neg(eqo("journals/sigmod/Qian96a","kj7_0qQq_48J")).
neg(eqo("journals/sigmod/Qian96b","mH0vNFMcLxsJ")).
neg(eqo("journals/sigmod/RamamrithamSSTX96","Jg81WYtxtZoJ")).
neg(eqo("journals/sigmod/RiekertMW97","Wcbvsi-QDtcJ")).
neg(eqo("journals/sigmod/RossIJP00","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/Segev94","FN5Faq5Glz0J")).
neg(eqo("journals/sigmod/SellisV95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D219766%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/ShanmugasundaramSKKVNT01","QOf55i6m6bUJ")).
neg(eqo("journals/sigmod/Sidell96","0JPhnHlRGOoJ")).
neg(eqo("journals/sigmod/Sidell96","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D245906%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Snodgrass02","ZraSxoh9ZZoJ")).
neg(eqo("journals/sigmod/Snodgrass03","m-l6e98xxOsJ")).
neg(eqo("journals/sigmod/Snodgrass99b","hhzf0Ib9PNIJ")).
neg(eqo("journals/sigmod/SnodgrassHMOPRRWY98","CGvD6Du5kaoJ")).
neg(eqo("journals/sigmod/SommerGB02","8l5_eKZcCh8J")).
neg(eqo("journals/sigmod/SouzaS99","aAWLUJOwAksJ")).
neg(eqo("journals/sigmod/SpynsMJ02","gAwckIiPpTEJ")).
neg(eqo("journals/sigmod/Stirling03","Ycj2VYHPX3IJ")).
neg(eqo("journals/sigmod/Stonebraker02","_CGWFOx5yt0J")).
neg(eqo("journals/sigmod/TatarinovIMHSDDKMM03","mr8XDkQ7adAJ")).
neg(eqo("journals/sigmod/Wedekind94","rYL2KvUqWCgJ")).
neg(eqo("journals/sigmod/WenLMZ03","url:http://doi.wiley.com/10.1002/ange.200390621")).
neg(eqo("journals/sigmod/Widom94","l1Ur1mJ3-nQJ")).
neg(eqo("journals/sigmod/Widom95","tOlGOS5EIQYJ")).
neg(eqo("journals/sigmod/Widom95a","zMW_rq3S6VgJ")).
neg(eqo("journals/sigmod/Widom96","vgcXH5aVpdgJ")).
neg(eqo("journals/sigmod/Widom96a","url:http://portal.acm.org/citation.cfm%3Fid%3D234286.1057838")).
neg(eqo("journals/sigmod/Winslett02","CxwaKCGa6ysJ")).
neg(eqo("journals/sigmod/Winslett02a","dMNA36iCZl0J")).
neg(eqo("journals/sigmod/Winslett02b","url:http://portal.acm.org/citation.cfm%3Fid%3D507338.507358%26coll%3DGUIDE%26dl%3Dacm%26idx%3D984378%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/sigmod/Winslett94","dMNA36iCZl0J")).
neg(eqo("journals/sigmod/Winslett94","rRvcD6HKhasJ")).
neg(eqo("journals/sigmod/WinslettCDHZZ02","_ZsI_bVIJMwJ")).
neg(eqo("journals/sigmod/WolfsonSDNR95","vwdWTx0dk7QJ")).
neg(eqo("journals/sigmod/YeungHL94","H8Mwd8YSUvwJ")).
neg(eqo("journals/tods/CeriFPT94","CpA5QWyIRr4J")).
neg(eqo("journals/tods/ChakrabartiKMP02","9eonVZte2BUJ")).
neg(eqo("journals/tods/ChenHM95","Y_n5kSZ0pOsJ")).
neg(eqo("journals/tods/ChenHM95","hyiOE1eACxMJ")).
neg(eqo("journals/tods/Chomicki03","lYxTi5i2dCYJ")).
neg(eqo("journals/tods/Chomicki95","SXHPvzZDrFMJ")).
neg(eqo("journals/tods/DattaVCK99","uaGQ4mXKYdcJ")).
neg(eqo("journals/tods/DeyS96","uZVc1wSi3y4J")).
neg(eqo("journals/tods/EiterGM97","36y_7fnJdDQJ")).
neg(eqo("journals/tods/EiterLLS01","cWU6kJdYjk4J")).
neg(eqo("journals/tods/FukudaMMT01","cFMtMf7bLzIJ")).
neg(eqo("journals/tods/GhandeharizadehHJ96","vMVuIqz5BiwJ")).
neg(eqo("journals/tods/GunopulosKMSTS03","-q1BFuUI27EJ")).
neg(eqo("journals/tods/GunopulosKMSTS03","YrezQaVZ_VgJ")).
neg(eqo("journals/tods/HjaltasonS99","3mwWUz_ORNYJ")).
neg(eqo("journals/tods/HsuSY01","HaeavXvGp1QJ")).
neg(eqo("journals/tods/KarpSP03","fVr7PLWB3noJ")).
neg(eqo("journals/tods/KossmannS00","_cnnB6UdemAJ")).
neg(eqo("journals/tods/LakshmananLN03","RWrhmPd907kJ")).
neg(eqo("journals/tods/MelnikG03","Zgi7AqRx3YgJ")).
neg(eqo("journals/tods/Ng01","iNm_ihZLMlEJ")).
neg(eqo("journals/tods/Ng01","o0BVCw-vPa4J")).
neg(eqo("journals/tods/PetersO97","E688ACygfTEJ")).
neg(eqo("journals/tods/Snodgrass01a","eW3sswNykJoJ")).
neg(eqo("journals/tods/Snodgrass01a","url:http://www.springerlink.com/index/N2VQ4NK4H736R74T.pdf")).
neg(eqo("journals/tods/Snodgrass01a","zvcs9bbyoi0J")).
neg(eqo("journals/tods/TaoSP03","v7hQCqKepzwJ")).
neg(eqo("journals/tods/TendickM94","FxCxfE4m1rUJ")).
neg(eqo("journals/tods/WolfsonJH97","3mEkVA4_lCIJ")).
neg(eqo("journals/tods/YanG94","X7w4rQXqf70J")).
neg(eqo("journals/tods/YanG99","Ub8WpbDUaVoJ")).
neg(eqo("journals/tods/ZaharioudakisCF97","g5qOYlZLZ9QJ")).
neg(eqo("journals/tods/ZobelMR98","PAPZmtE9kFUJ")).
neg(eqo("journals/vldb/AbbadiSW01","dNM-avLn230J")).
neg(eqo("journals/vldb/AgrawalHK03","ujWZNcj2qkgJ")).
neg(eqo("journals/vldb/Amer-YahiaCLS02","DFubU20j1OIJ")).
neg(eqo("journals/vldb/ApersCS02","-5ehGhCEl4wJ")).
neg(eqo("journals/vldb/Baumann94","V9DIFmU3vi8J")).
neg(eqo("journals/vldb/BerchtoldKK97","hrHLKxM0BSYJ")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.ingentaconnect.com/search/expand%3Fpub%3Dinfobike://els/13891286/2000/00000034/00000006/art00152%26unc%3D")).
neg(eqo("journals/vldb/BernsteinIR03","url:http://www.springerlink.com/index/CWANCL0VWN1MKL0M.pdf")).
neg(eqo("journals/vldb/C95a","r9tT5zsNnCQJ")).
neg(eqo("journals/vldb/C95b","IXHSgunh9bgJ")).
neg(eqo("journals/vldb/ChanFGR02","lDNAWc5SrmIJ")).
neg(eqo("journals/vldb/DattaDVRN01","RKbKtLWjDLEJ")).
neg(eqo("journals/vldb/FahlR97","Cim5KsWPjgoJ")).
neg(eqo("journals/vldb/FahlR97","url:http://portal.acm.org/citation.cfm%3Fid%3D263690.264350%26dl%3Dportal%26dl%3DACM%26type%3Dseries%26idx%3DSERIES492%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Digital%2520Libraries%26CFID%3D11111111%26CFTOKEN%3D2222222")).
neg(eqo("journals/vldb/FangGM96","AWGtiQgXS7QJ")).
neg(eqo("journals/vldb/FerrariAABC02","bxaZFDffhqoJ")).
neg(eqo("journals/vldb/HansonCDERTX98","S38ugVwOqkUJ")).
neg(eqo("journals/vldb/HuangDT99","rezPILwiUSgJ")).
neg(eqo("journals/vldb/KabraD99","UAjZbCsSEA8J")).
neg(eqo("journals/vldb/KemperK95","2OPEy9_6BlEJ")).
neg(eqo("journals/vldb/Li03","8cxfqvYDcVwJ")).
neg(eqo("journals/vldb/LiR99","IWEa-GPfwXEJ")).
neg(eqo("journals/vldb/LiR99","XS0g9j8J7woJ")).
neg(eqo("journals/vldb/MedjahedBE03","6mbu5T69NFEJ")).
neg(eqo("journals/vldb/MehrotraKS97","1S5f4QMKowYJ")).
neg(eqo("journals/vldb/MehrotraKS97","tp1_LRYeLcwJ")).
neg(eqo("journals/vldb/NgS98","6OfJSMB4vOcJ")).
neg(eqo("journals/vldb/NguSHL01","6HMffRHCspAJ")).
neg(eqo("journals/vldb/PapadiasS94","Fg0Y-u39c7oJ")).
neg(eqo("journals/vldb/RafieiM02","wKvSI4oZ8uEJ")).
neg(eqo("journals/vldb/RamamohanaraoH94","2HXoDqKjpXYJ")).
neg(eqo("journals/vldb/RamanRH00","CztsJoNNFgIJ")).
neg(eqo("journals/vldb/ShanmugasundaramSBCLPR01","vnezjPI8jYIJ")).
neg(eqo("journals/vldb/SofferS98","e-QcwiFmkNkJ")).
neg(eqo("journals/vldb/SuHHHLWLPLL01","Z0l7zr67jb0J")).
neg(eqo("journals/vldb/TurkerG01","F-IqOVJqJ5EJ")).
neg(eqo("journals/vldb/TurkerG01","url:http://www.ingentaconnect.com/content/els/09505849/2001/00000043/00000010/art00167")).
neg(eqo("journals/vldb/VaghaniRKSSLH94","zjNzW7mkizMJ")).
pos(eqo("conf/sigmod/AbiteboulBCMM03","AxpQwgyRyLgJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","QCAu6wPhnAAJ")).
pos(eqo("conf/sigmod/AcharyaFZ97","umGxlKvzLoUJ")).
pos(eqo("conf/sigmod/AdaliSS99","bhWLVCoDuNQJ")).
pos(eqo("conf/sigmod/AdaliSS99","c2dH5RxNj6kJ")).
pos(eqo("conf/sigmod/AdelbergGW97","XytbGy--8LMJ")).
pos(eqo("conf/sigmod/AdelbergGW97","zZo47Z-jVX4J")).
pos(eqo("conf/sigmod/Aggarwal03","qbubaA6mQawJ")).
pos(eqo("conf/sigmod/AgrawalASY97","3nxl8d4c0t4J")).
pos(eqo("conf/sigmod/AgrawalASY97","7Of1HyK-VnkJ")).
pos(eqo("conf/sigmod/AgrawalASY97","C85vtVHZmjUJ")).
pos(eqo("conf/sigmod/AltinelLKMPLWB02","zzg3KI_fyyIJ")).
pos(eqo("conf/sigmod/Amer-YahiaCLS01","WsCqveNDjjUJ")).
pos(eqo("conf/sigmod/ArefBV95","ht_8Iq3SZ80J")).
pos(eqo("conf/sigmod/AshleyFHLNP95","ZkK-ilu3tY0J")).
pos(eqo("conf/sigmod/BabcockCD03","mbhZ3gSR3NMJ")).
pos(eqo("conf/sigmod/BabyCY01","rNoNn5hWsroJ")).
pos(eqo("conf/sigmod/BarclaySG00","6uaAB7bg6C8J")).
pos(eqo("conf/sigmod/BarclaySG00","7br3WXwZRQ4J")).
pos(eqo("conf/sigmod/BaruFGHJPW95","C60KJG_xVm0J")).
pos(eqo("conf/sigmod/Bayardo98","O05yYxasf6UJ")).
pos(eqo("conf/sigmod/Bayardo98","t7cKx4raSM0J")).
pos(eqo("conf/sigmod/Bayardo98","wHaeR7DBDTUJ")).
pos(eqo("conf/sigmod/BerchtoldK97","DNVHTz7tMywJ")).
pos(eqo("conf/sigmod/Bernstein96","EvuLCpyVqWgJ")).
pos(eqo("conf/sigmod/BettiniWBJ95","c57d3rgd3IcJ")).
pos(eqo("conf/sigmod/BohrerBBCFHKKMNRRSUUW97a","NiBdZXS0TCMJ")).
pos(eqo("conf/sigmod/BouguettayaBH99","ER8571wXl6EJ")).
pos(eqo("conf/sigmod/BouguettayaBH99","U-Kd4GQ_vCMJ")).
pos(eqo("conf/sigmod/BouguettayaBH99","siO8kr7vvLEJ")).
pos(eqo("conf/sigmod/BrinDG95","7mNCkZ7D-R8J")).
pos(eqo("conf/sigmod/BrinDG95","QmhdqC_PIWsJ")).
pos(eqo("conf/sigmod/BrodskyK95","SFmnhrhoQzgJ")).
pos(eqo("conf/sigmod/BrunoKS02","4pZ4Shr2bMwJ")).
pos(eqo("conf/sigmod/BuchmannDZH95","MoNBLfTlYg0J")).
pos(eqo("conf/sigmod/BuchmannDZH95","QzpePwRoku8J")).
pos(eqo("conf/sigmod/CandanLLHA01","E1oiXxVyfXwJ")).
pos(eqo("conf/sigmod/CareyK97","yuAO6FZOXmQJ")).
pos(eqo("conf/sigmod/Chakrabarti99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D304231%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/ChandrasekaranCDFHHKMRS03","eOhZfLS25AsJ")).
pos(eqo("conf/sigmod/ChangC01","XbmULzOYzZUJ")).
pos(eqo("conf/sigmod/ChaudhuriD97","4zZ7Lxt4PPIJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","TqXFdQBTW6kJ")).
pos(eqo("conf/sigmod/ChaudhuriMN98","niAPzsMp2igJ")).
pos(eqo("conf/sigmod/ChenCPPSTM00","Ab6MIDVDzhAJ")).
pos(eqo("conf/sigmod/ChenGMV02","IqV3EploPP4J")).
pos(eqo("conf/sigmod/ChenR94","7Edh53sUX7kJ")).
pos(eqo("conf/sigmod/ChenR94","WJDiW8pl0OcJ")).
pos(eqo("conf/sigmod/ChenZCKR01","RHoy5iOHsJwJ")).
pos(eqo("conf/sigmod/CherniackZ96","ZsHfcZJwFQQJ")).
pos(eqo("conf/sigmod/ChungMS02","mEfTTKdu6soJ")).
pos(eqo("conf/sigmod/CluetDSS98","63Y-t4R2RycJ")).
pos(eqo("conf/sigmod/CluetDSS98","VZreOrzvcYEJ")).
pos(eqo("conf/sigmod/CluetDSS98","q9yRMEgjLOAJ")).
pos(eqo("conf/sigmod/CranorGJSS02","89Avc7qz9YoJ")).
pos(eqo("conf/sigmod/CruzALRZ97","YWWvQnGCpDEJ")).
pos(eqo("conf/sigmod/DanS95","qYsoOX4e1noJ")).
pos(eqo("conf/sigmod/DasuJMS02","zTF5z0v_nh0J")).
pos(eqo("conf/sigmod/DeolaseeKPRS01","5OTQGZ1gb18J")).
pos(eqo("conf/sigmod/DoRD99","Q4N41koenF8J")).
pos(eqo("conf/sigmod/DobraGGR02","v7A9Otp7OjsJ")).
pos(eqo("conf/sigmod/DobraGGR02","wuIyUXOQP7AJ")).
pos(eqo("conf/sigmod/DreyerDS95","i1qU2OFSeloJ")).
pos(eqo("conf/sigmod/FranklinJK96","2KXhx32GEzIJ")).
pos(eqo("conf/sigmod/FranklinJK96","40cq9ovvXn8J")).
pos(eqo("conf/sigmod/FukudaMMT96","lmXiI4fB9vgJ")).
pos(eqo("conf/sigmod/Galindo-LegariaJ01","BSlaDX5r0HQJ")).
pos(eqo("conf/sigmod/GangulyGR03","Di-EjDZ_abYJ")).
pos(eqo("conf/sigmod/GarofalakisG02","6EaC2CmjsmAJ")).
pos(eqo("conf/sigmod/GatziuGD95","NU4yPbIkZpsJ")).
pos(eqo("conf/sigmod/Gerber95","Cha3zvFBfDsJ")).
pos(eqo("conf/sigmod/GibbonsM98","GEBNdHM0xSgJ")).
pos(eqo("conf/sigmod/GibbonsM98","HrdG_-EcnP8J")).
pos(eqo("conf/sigmod/GibbonsM98","x4HkJDEYFmYJ")).
pos(eqo("conf/sigmod/GibbsBT94","28mTFsC-KCIJ")).
pos(eqo("conf/sigmod/GibbsBT94","6oKFObEbS5oJ")).
pos(eqo("conf/sigmod/Golding95","uJj9OgotYeEJ")).
pos(eqo("conf/sigmod/GravanoCGP97","FHEK09LJKfwJ")).
pos(eqo("conf/sigmod/GravanoCGP97","IVXOHTW5Lt0J")).
pos(eqo("conf/sigmod/GravanoCGP97","yfb8p_tlSlsJ")).
pos(eqo("conf/sigmod/GravanoGT94","81oh7EDAYeoJ")).
pos(eqo("conf/sigmod/GravanoGT94","OYFpMlm5yCQJ")).
pos(eqo("conf/sigmod/GravanoGT94","mO77XJl45iEJ")).
pos(eqo("conf/sigmod/GravanoGT94","nAJnhh70_0kJ")).
pos(eqo("conf/sigmod/GrayHOS96","3mFpWorR_ucJ")).
pos(eqo("conf/sigmod/GrayHOS96","5cw83MyqYrMJ")).
pos(eqo("conf/sigmod/GrayHOS96","92XgZkibRYwJ")).
pos(eqo("conf/sigmod/GrayHOS96","GFJeoxHwEnkJ")).
pos(eqo("conf/sigmod/GrayHOS96","J_QkWJ4HlOUJ")).
pos(eqo("conf/sigmod/GrayHOS96","M5jLOXpuFacJ")).
pos(eqo("conf/sigmod/GrayHOS96","_EUlTfqD0q0J")).
pos(eqo("conf/sigmod/GrayHOS96","iKmQWoUYl-0J")).
pos(eqo("conf/sigmod/GrayHOS96","pDjbDK0ZzsMJ")).
pos(eqo("conf/sigmod/GraySEBW94","bbWXEbBUueYJ")).
pos(eqo("conf/sigmod/GrumbachRS98","RQTFVFT_w9gJ")).
pos(eqo("conf/sigmod/GuptaHR97","pGix0qZ6Uz4J")).
pos(eqo("conf/sigmod/GuptaHR97","wu0var7zLkEJ")).
pos(eqo("conf/sigmod/GuptaMR95","2GUwicKtWTUJ")).
pos(eqo("conf/sigmod/HaasH99","UHF2uPETWC8J")).
pos(eqo("conf/sigmod/HaasH99","fz1XAzoKPo0J")).
pos(eqo("conf/sigmod/HacigumusILM02","NMgExE-JRD0J")).
pos(eqo("conf/sigmod/HanKS97","XFCkL9QhTjIJ")).
pos(eqo("conf/sigmod/Hellerstein00","rbluxTXqUQwJ")).
pos(eqo("conf/sigmod/HellersteinW02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D564788%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/HernandezS95","7EYR1qDwKg0J")).
pos(eqo("conf/sigmod/HoAMS97","1HAB-tuw7N4J")).
pos(eqo("conf/sigmod/HoAMS97","4YsYF_8QeogJ")).
pos(eqo("conf/sigmod/HoAMS97","rUNHnYf8TtEJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","8EC1IBh8MZkJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","CuoOi5jJXxQJ")).
pos(eqo("conf/sigmod/ImielinskiVB94","ib4ebmBQW4kJ")).
pos(eqo("conf/sigmod/IvesFFLW99","0087thkugMUJ")).
pos(eqo("conf/sigmod/IvesFFLW99","HwBwuLKlAiEJ")).
pos(eqo("conf/sigmod/JaedickeM98","MswqiEweEGUJ")).
pos(eqo("conf/sigmod/Jagadish94","eH69_dCm18wJ")).
pos(eqo("conf/sigmod/JoshiA01","R-54DDaHDxoJ")).
pos(eqo("conf/sigmod/KabraD98","V9XUvirmVEEJ")).
pos(eqo("conf/sigmod/KalnisNOPT02","ipAB8UMS7QkJ")).
pos(eqo("conf/sigmod/Kennamer98","RQ9qLR4St8sJ")).
pos(eqo("conf/sigmod/KornackerSH98","08hpWyqMTqAJ")).
pos(eqo("conf/sigmod/Kulkarni94","eN_4FTimCKYJ")).
pos(eqo("conf/sigmod/LarsonG98","tPG--ikWjGcJ")).
pos(eqo("conf/sigmod/LaursenOP94","fTbCV3Lh8W0J")).
pos(eqo("conf/sigmod/LehnerSPC00","xfWGb928UfcJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","L854PhEQPTsJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","P25_yh3lBhoJ")).
pos(eqo("conf/sigmod/LiVCAHMWBCHIKSS99","WSQzzj42AkEJ")).
pos(eqo("conf/sigmod/LitwinS00","Ad5NAPgWIIUJ")).
pos(eqo("conf/sigmod/LitwinS00","R7Z-NlUo_YUJ")).
pos(eqo("conf/sigmod/LitwinS00","RQ9fpPAS2h8J")).
pos(eqo("conf/sigmod/LitwinS00","f1h0J1_ELisJ")).
pos(eqo("conf/sigmod/LitwinS00","qzeu5GQ_2p0J")).
pos(eqo("conf/sigmod/LitwinS00","w9dSqojWgDAJ")).
pos(eqo("conf/sigmod/LiuHBPT99","BIox2W-EPfEJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","UqI8eTF3k7sJ")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/LivnyRBCDLMW97a","sN-m3iBA6Y4J")).
pos(eqo("conf/sigmod/LlirbatFS97","hJiwQ2CQRBkJ")).
pos(eqo("conf/sigmod/LoR96","-hXhDlel--wJ")).
pos(eqo("conf/sigmod/LometW98","QPpUo7m3A7cJ")).
pos(eqo("conf/sigmod/MamoulisP99","RusJdYPDgQ4J")).
pos(eqo("conf/sigmod/MattosM95","wF_GdZPkCnQJ")).
pos(eqo("conf/sigmod/Miller98","fW6JIoNRqAQJ")).
pos(eqo("conf/sigmod/MiloAABN03","fHp5E4Rxt7cJ")).
pos(eqo("conf/sigmod/MissikoffT94","nxNSfctbGWAJ")).
pos(eqo("conf/sigmod/Mohan02","YJlUtEk7zwkJ")).
pos(eqo("conf/sigmod/Mohan96","14cgU3tAHtgJ")).
pos(eqo("conf/sigmod/Mohan96","C-yzbvoAg00J")).
pos(eqo("conf/sigmod/Mohan96","JHJ-NMsTtL0J")).
pos(eqo("conf/sigmod/Mohan96","ZEh9UFMj3-EJ")).
pos(eqo("conf/sigmod/NatsevRS99","Y3nejQSVKnUJ")).
pos(eqo("conf/sigmod/OoiTZGLLLNSWZ03","l78OeieL4ZsJ")).
pos(eqo("conf/sigmod/PapadiasTFS03","MkRJhOROQjsJ")).
pos(eqo("conf/sigmod/PapadiasTSE95","PogZLKV_bIsJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","5iBUkqCy-KAJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","Y7J0sm6WO2kJ")).
pos(eqo("conf/sigmod/PapakonstantinouV99","du5GsqT0_vQJ")).
pos(eqo("conf/sigmod/PatelD96","Goan1fI4O_oJ")).
pos(eqo("conf/sigmod/PatelD96","oPdpBiAjcisJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","7arvzxTqC9MJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","HKPOQm4QcQcJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","gfRbQIzfux4J")).
pos(eqo("conf/sigmod/PoosalaIHS96","hHGQKstQ2PQJ")).
pos(eqo("conf/sigmod/PoosalaIHS96","uveOdmVtqRMJ")).
pos(eqo("conf/sigmod/Rajaraman99","m_n55lcmF-sJ")).
pos(eqo("conf/sigmod/RamanH02","F0T3KimkbGcJ")).
pos(eqo("conf/sigmod/RamanH02","Oh2u3cZ3zJ0J")).
pos(eqo("conf/sigmod/RaoBG96","yh6y4XWemYUJ")).
pos(eqo("conf/sigmod/RiedelFGN00","ospJVA6AD1sJ")).
pos(eqo("conf/sigmod/RiedewaldAA02","AFKhL1I3L9AJ")).
pos(eqo("conf/sigmod/RodriguezR00","UF4wxbIa6FMJ")).
pos(eqo("conf/sigmod/RodriguezR00","dVDzCb6fuJ0J")).
pos(eqo("conf/sigmod/RodriguezR00","gi7N9eQiTx4J")).
pos(eqo("conf/sigmod/RossSS96","iurxdvB6oLAJ")).
pos(eqo("conf/sigmod/RundensteinerCLCZNJLW99","SADcQZhMqgEJ")).
pos(eqo("conf/sigmod/SeshadriLR94","cL_OKIQDvmQJ")).
pos(eqo("conf/sigmod/ShashaB02a","url:http://portal.acm.org/citation.cfm%3Fid%3D564691.564798%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D564691%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/sigmod/Sheth95","JrkRUbNsLwEJ")).
pos(eqo("conf/sigmod/ShuklaD00","07dT02YX07AJ")).
pos(eqo("conf/sigmod/ShuklaD00","kcrWfQEI9G8J")).
pos(eqo("conf/sigmod/SistlaW95","J3XZUbzCxjEJ")).
pos(eqo("conf/sigmod/TatarinovIHW01","YiEpyN4HDEsJ")).
pos(eqo("conf/sigmod/TomasicABKNR97","_fF5I-bkUSQJ")).
pos(eqo("conf/sigmod/WangZS95","86-DS0U0jY0J")).
pos(eqo("conf/sigmod/WattezCBFF00","1SA9LhktHsUJ")).
pos(eqo("conf/sigmod/WhitneyS01","bZj9gl0_YUIJ")).
pos(eqo("conf/sigmod/YerneniLGU99","2MbaeG3IVV0J")).
pos(eqo("conf/sigmod/YerneniLGU99","Gnb52DoKdJwJ")).
pos(eqo("conf/sigmod/ZaharioudakisCLPU00","Pbl_CbLYKWYJ")).
pos(eqo("conf/sigmod/ZhaoDN97","chYdQDE8cPsJ")).
pos(eqo("conf/sigmod/ZhaoDNS98","Wg8o4cj8Cq4J")).
pos(eqo("conf/sigmod/ZhaoDNS98","mBC03oUT8yAJ")).
pos(eqo("conf/vldb/AbiteboulACEMM99","OYOTbj4m7JYJ")).
pos(eqo("conf/vldb/AbiteboulBMMW02","MKZ1bbmP6HgJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","iX8lBZBEgSwJ")).
pos(eqo("conf/vldb/AgarwalADGNRS96","xjlz3nY-EZsJ")).
pos(eqo("conf/vldb/AgrawalKSX02","XK-KPRa2qjcJ")).
pos(eqo("conf/vldb/AgrawalS94","1lpNNpHnY_kJ")).
pos(eqo("conf/vldb/AgrawalS94","2Z_X3zsf4CoJ")).
pos(eqo("conf/vldb/AgrawalS94","3MzTom30SiMJ")).
pos(eqo("conf/vldb/AgrawalS94","E7cKUUkwc1kJ")).
pos(eqo("conf/vldb/AgrawalS94","P0age7qyZacJ")).
pos(eqo("conf/vldb/AgrawalS94","QlSaVou-Zt4J")).
pos(eqo("conf/vldb/AgrawalS94","RiQ-W5K0n6YJ")).
pos(eqo("conf/vldb/AgrawalS94","XzSqN32OqgMJ")).
pos(eqo("conf/vldb/AgrawalS94","kAi6HssDySgJ")).
pos(eqo("conf/vldb/AltinelF00","JhWxdEDCPdUJ")).
pos(eqo("conf/vldb/AltinelF00","SXHPvzZDrFMJ")).
pos(eqo("conf/vldb/Amer-YahiaCD98","9nmG2KCklEcJ")).
pos(eqo("conf/vldb/AmielBDS94","hBak02oe1GMJ")).
pos(eqo("conf/vldb/AnciauxBBPV01","PFEvlg2DiMkJ")).
pos(eqo("conf/vldb/AshwinRSSS97","JB684f38DiwJ")).
pos(eqo("conf/vldb/Banerjee00","owfPKT5ip68J")).
pos(eqo("conf/vldb/BaralisW94","q-td2YANr18J")).
pos(eqo("conf/vldb/BarjaPFWD94","qhl9_KGvjcUJ")).
pos(eqo("conf/vldb/BarjaPFWD94","yXC9t87hjwsJ")).
pos(eqo("conf/vldb/BerchtoldKK96","2EJhvKyW8AoJ")).
pos(eqo("conf/vldb/BohannonFHRRS02","zYfyg0fCzEsJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","GzK2N5eQ0pQJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","IROKbaAxI6QJ")).
pos(eqo("conf/vldb/BohannonLRSSS97","thTt2lg4_Z8J")).
pos(eqo("conf/vldb/BonczMK99","8yhbBSPKZEoJ")).
pos(eqo("conf/vldb/Brin95","CuCm_rmA28cJ")).
pos(eqo("conf/vldb/Brin95","dXegp-RmzXEJ")).
pos(eqo("conf/vldb/Brin95","ytOUXklnAooJ")).
pos(eqo("conf/vldb/BrownCC94","E-1nAx7gc-8J")).
pos(eqo("conf/vldb/BrownCC94","jMku9rPCt9sJ")).
pos(eqo("conf/vldb/BrownCC94","oayI0FKl-nQJ")).
pos(eqo("conf/vldb/Cabrera03","url:http://wwwdb.informatik.uni-rostock.de/vldb2003/papers/S31P01.pdf")).
pos(eqo("conf/vldb/Campbell99","m1eeQnYWL0oJ")).
pos(eqo("conf/vldb/CareyD96","5xe-dQqXfI8J")).
pos(eqo("conf/vldb/CasatiDGS01","XQw3ADYCXdcJ")).
pos(eqo("conf/vldb/CatozziR95","8ftKLh07LM0J")).
pos(eqo("conf/vldb/CeriFP99","8OrOAQnaveIJ")).
pos(eqo("conf/vldb/CeriM03","hFPNVe44A04J")).
pos(eqo("conf/vldb/ChakrabartiM00","tRBRXzjtm14J")).
pos(eqo("conf/vldb/ChakrabartiRS02","idfox84uNHUJ")).
pos(eqo("conf/vldb/ChanGR02","7rn7AHVs1YUJ")).
pos(eqo("conf/vldb/ChanGR02","wUcXmf9G52gJ")).
pos(eqo("conf/vldb/ChatziantoniouR97","UEvW-FsWASUJ")).
pos(eqo("conf/vldb/ChatziantoniouR97","Xx-pSjq7Mv8J")).
pos(eqo("conf/vldb/ChaudhuriS01","4bS3tvLQ-LAJ")).
pos(eqo("conf/vldb/ChaudhuriS96","4MaErPILRq8J")).
pos(eqo("conf/vldb/ChaudhuriS96","QCFUIVkspywJ")).
pos(eqo("conf/vldb/ChaudhuriS96","uRmyQBKcFAYJ")).
pos(eqo("conf/vldb/Chawathe99","HiM9HOUxq0MJ")).
pos(eqo("conf/vldb/CherniackFZ01","49EWG8vzsXUJ")).
pos(eqo("conf/vldb/ChoALS02","_-JZT1cOuZ8J")).
pos(eqo("conf/vldb/ChoN02","4tTQJrG4pn8J")).
pos(eqo("conf/vldb/ClaussenKMP97","EyTvjJCb5WkJ")).
pos(eqo("conf/vldb/CotterB00","SJ6PiY04ebMJ")).
pos(eqo("conf/vldb/Dayal99","OoknnZ3rbfwJ")).
pos(eqo("conf/vldb/DayalHL01","0XYRlW9tvw8J")).
pos(eqo("conf/vldb/DesslochM97","CjtIFow-OWcJ")).
pos(eqo("conf/vldb/DesslochM97","OY4EswVULVcJ")).
pos(eqo("conf/vldb/DiaoF03","Crt1JZ1eEj0J")).
pos(eqo("conf/vldb/DiligentiCLGG00","XCP3p-Hk8bMJ")).
pos(eqo("conf/vldb/DonjerkovicR99","Eq1w4LPv_igJ")).
pos(eqo("conf/vldb/Draluk01","xQzrilMR-QQJ")).
pos(eqo("conf/vldb/DuttaDMRT00","q0Ovw6QUk3MJ")).
pos(eqo("conf/vldb/EsterKSWX98","MC7KlhmEQt8J")).
pos(eqo("conf/vldb/FaloutsosG96","1T0QEMsUItoJ")).
pos(eqo("conf/vldb/FaloutsosG96","vwcVawlOJn0J")).
pos(eqo("conf/vldb/Fecteau95","LhjvKpDcJKUJ")).
pos(eqo("conf/vldb/FegarasE01","pinPEM3Rvm0J")).
pos(eqo("conf/vldb/FlescaFM03","LXjSnbxB7EsJ")).
pos(eqo("conf/vldb/FlorescuHKLRWCSA03","1KSfxI44iGUJ")).
pos(eqo("conf/vldb/FuC94","ReboDjzo5y0J")).
pos(eqo("conf/vldb/GarofalakisG01","rcSfDxBif40J")).
pos(eqo("conf/vldb/GehrkeRG98","G8JSWUAO2lMJ")).
pos(eqo("conf/vldb/GoldmanSVG98","pweOUtA2iTAJ")).
pos(eqo("conf/vldb/GoldmanW97","EM5uAeHdNEIJ")).
pos(eqo("conf/vldb/GoldmanW97","UeLjlfHU_gkJ")).
pos(eqo("conf/vldb/GoldmanW97","l5GboAkBH1AJ")).
pos(eqo("conf/vldb/GoyalHSS95","2sGH4SLcdL4J")).
pos(eqo("conf/vldb/GuntzerBK00","EdQ4M7GEnzoJ")).
pos(eqo("conf/vldb/GuntzerBK00","id3rk1JgWx0J")).
pos(eqo("conf/vldb/HaasB03","-sWlL27yCP0J")).
pos(eqo("conf/vldb/HaasB03","52x78w6qgcwJ")).
pos(eqo("conf/vldb/HaasKWY97","U09WdB3GIK4J")).
pos(eqo("conf/vldb/HaasKWY97","o_WTRsrkx_EJ")).
pos(eqo("conf/vldb/HaasKWY97","olfbrDVhkoYJ")).
pos(eqo("conf/vldb/HellersteinNP95","AC19Z_yOCTUJ")).
pos(eqo("conf/vldb/HellersteinNP95","iLRI5OqO94UJ")).
pos(eqo("conf/vldb/HjelsvoldM94","5Wuyp1aLBocJ")).
pos(eqo("conf/vldb/HristidisGP03","B2rShDD99xwJ")).
pos(eqo("conf/vldb/HumborstadSHT97","TjJZGlCajbMJ")).
pos(eqo("conf/vldb/HvasshovdBT00","af50lhGnD8gJ")).
pos(eqo("conf/vldb/IdrisGC94","Xf7TnMxlGTkJ")).
pos(eqo("conf/vldb/IoannidisP99","2k9bgRJC-hYJ")).
pos(eqo("conf/vldb/IshikawaSF98","D1HCBThHOkcJ")).
pos(eqo("conf/vldb/IshikawaSF98","V3c_ivUAs34J")).
pos(eqo("conf/vldb/JagadishLS99","5d1R2mD-7MkJ")).
pos(eqo("conf/vldb/JagadishNSSK97","FzUYum7hqhQJ")).
pos(eqo("conf/vldb/JohnsonA00","EPVkQkFM2osJ")).
pos(eqo("conf/vldb/JoshiBLL98","RufEbUPZNbYJ")).
pos(eqo("conf/vldb/KiesslingK02","OuVZjeR64pMJ")).
pos(eqo("conf/vldb/KochBG03","mZNcc1O3Nl8J")).
pos(eqo("conf/vldb/KornMS02","mClzTQppJE4J")).
pos(eqo("conf/vldb/KornSFSP96","1zxdq0otm4gJ")).
pos(eqo("conf/vldb/KornSFSP96","QjbxSG6_-WIJ")).
pos(eqo("conf/vldb/KornSFSP96","xQU9GXs4k50J")).
pos(eqo("conf/vldb/Kotidis01","lRL4LmMtwnYJ")).
pos(eqo("conf/vldb/KoudasMJ99","dRemTC899xcJ")).
pos(eqo("conf/vldb/KoudasMJ99","wzae2lO15U8J")).
pos(eqo("conf/vldb/LakshmananSS96","Yuccv3uXgUQJ")).
pos(eqo("conf/vldb/LakshmiZ98","QmXB6EKu-pYJ")).
pos(eqo("conf/vldb/LevyRO96","CWzG-HRtqZIJ")).
pos(eqo("conf/vldb/LevyRO96","QTsbBZX9zrAJ")).
pos(eqo("conf/vldb/LevyRO96","VYN0FaeVomUJ")).
pos(eqo("conf/vldb/LiM01","9vDm1Q41J8oJ")).
pos(eqo("conf/vldb/LuL00","Ih5hY-NRmFgJ")).
pos(eqo("conf/vldb/LuSL95","AvfsXnSTA24J")).
pos(eqo("conf/vldb/LuSL95","xGK3seG0Mn4J")).
pos(eqo("conf/vldb/Madnick95","UHLfs0GGqAAJ")).
pos(eqo("conf/vldb/MarianS03","JVvFcEnXBmkJ")).
pos(eqo("conf/vldb/MatiasVW00","7SeTnikjovEJ")).
pos(eqo("conf/vldb/Mattos03","HeE1NxaX5t8J")).
pos(eqo("conf/vldb/MignetMAC01","VaDXNMtPZ4oJ")).
pos(eqo("conf/vldb/Mina98","6SiX0ZUh1x0J")).
pos(eqo("conf/vldb/Mina98","ButmJWjGXusJ")).
pos(eqo("conf/vldb/NaumannLF99","spErtT_VfeEJ")).
pos(eqo("conf/vldb/NgH94","32AYdsd8K3kJ")).
pos(eqo("conf/vldb/NgH94","EBXh5GwbeNMJ")).
pos(eqo("conf/vldb/NgH94","W1di9S0fUsEJ")).
pos(eqo("conf/vldb/NgH94","WjnMy2NiG10J")).
pos(eqo("conf/vldb/NgH94","ltzWlNOJavwJ")).
pos(eqo("conf/vldb/NieKH03","9javzlSee8oJ")).
pos(eqo("conf/vldb/OuzzaniAB94","CgoUJ7DogcwJ")).
pos(eqo("conf/vldb/OzdenGHNSDGGW01","ZzYmVTAjsnQJ")).
pos(eqo("conf/vldb/PellenkoftLK97","mCU3zHcPfCsJ")).
pos(eqo("conf/vldb/PereiraFLS00","KAW0nLm2wVAJ")).
pos(eqo("conf/vldb/PereiraFLS00","e60hJN21ZO0J")).
pos(eqo("conf/vldb/PoosalaI97","QIG8th9DHbQJ")).
pos(eqo("conf/vldb/PottingerL00","Kv3ZFRUKCogJ")).
pos(eqo("conf/vldb/Pound99","zWp_JdEQ8MgJ")).
pos(eqo("conf/vldb/RamakrishnanGRSWZ95","JAMaus2HrE0J")).
pos(eqo("conf/vldb/RamakrishnanR96","3y1e-H-FdC0J")).
pos(eqo("conf/vldb/RamamurthyDS02","DAlyofX710AJ")).
pos(eqo("conf/vldb/RamamurthyDS02","uem5wXLoU0wJ")).
pos(eqo("conf/vldb/RastogiS98","AyWUeJ5k2IoJ")).
pos(eqo("conf/vldb/RastogiS98","gkEOPxIM4GkJ")).
pos(eqo("conf/vldb/RastogiS98","yztQfwBZU6EJ")).
pos(eqo("conf/vldb/RiedelGF98","xAph8JHK5WsJ")).
pos(eqo("conf/vldb/RothS97","gIFZWp_iCmUJ")).
pos(eqo("conf/vldb/RothS97","xh4FaygNlGQJ")).
pos(eqo("conf/vldb/Sarawagi95","w9je55hjOlwJ")).
pos(eqo("conf/vldb/ShashaB02","6nTs7QjnfDcJ")).
pos(eqo("conf/vldb/ShashaB02","url:http://portal.acm.org/citation.cfm%3Fid%3D564691.564798%26dl%3DGUIDE%26dl%3DACM%26type%3Dseries%26idx%3D564691%26part%3DProceedings%26WantType%3DProceedings%26title%3DInternational%2520Conference%2520on%2520Management%2520of%2520Data%2520and%2520Symposium%2520on%2520Principles%2520of%2520Database%2520Systems%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("conf/vldb/Shenker03","5yETsE57mzgJ")).
pos(eqo("conf/vldb/SindoniTABFGMPPT01","0zdXnl9cQysJ")).
pos(eqo("conf/vldb/SistlaYLL95","lkNgibBst0MJ")).
pos(eqo("conf/vldb/SkubiszewskiV97","MJAw_2C6ErAJ")).
pos(eqo("conf/vldb/SripadaW94","VqNz3sp638UJ")).
pos(eqo("conf/vldb/Suciu96","GwvN1w9_ZZoJ")).
pos(eqo("conf/vldb/TatbulCZCS03","F42wOOy-KR0J")).
pos(eqo("conf/vldb/TorloneA03","v6kudD3ItEoJ")).
pos(eqo("conf/vldb/TsoisS03","_2oz5poi5asJ")).
pos(eqo("conf/vldb/Tsur00","buI2V0eIcZoJ")).
pos(eqo("conf/vldb/UrhanF01","0-FUXURm1FQJ")).
pos(eqo("conf/vldb/VelegrakisMP03","JYQUV-XahekJ")).
pos(eqo("conf/vldb/VieiraM03","b9zAhFneX5YJ")).
pos(eqo("conf/vldb/VieiraM03","sUtdmV9XsIcJ")).
pos(eqo("conf/vldb/Wang95","kYYJq-JrCn0J")).
pos(eqo("conf/vldb/WeberSB98","6D0Qt6Sjp8cJ")).
pos(eqo("conf/vldb/WeberSNSS03","TMPrfw4VcFAJ")).
pos(eqo("conf/vldb/WiesnerK01","UrDwK2S7QVwJ")).
pos(eqo("conf/vldb/YagoubFIV00","oHJaZrizZesJ")).
pos(eqo("conf/vldb/YuAA03","4bvjebYsdRkJ")).
pos(eqo("conf/vldb/ZhangL97","v-O39agJIB4J")).
pos(eqo("conf/vldb/ZhouLZLZJT01","fJQ7Col2vYsJ")).
pos(eqo("conf/vldb/ZimbraoS98","1KckBFVfgyMJ")).
pos(eqo("conf/vldb/ZouS98","_OimKPnidhsJ")).
pos(eqo("journals/sigmod/Aberer02a","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565129%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/Aggarwal01","JKGSOO_3GjUJ")).
pos(eqo("journals/sigmod/Aggarwal01","OE8gpNwz8MkJ")).
pos(eqo("journals/sigmod/Ahlberg96","4bBje8qkHVgJ")).
pos(eqo("journals/sigmod/AilamakiG03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777004%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/AtzeniMM97","Mb78Vc7skzMJ")).
pos(eqo("journals/sigmod/BaaderJN97","dr4SzOhnLB8J")).
pos(eqo("journals/sigmod/BaaderJN97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D274461%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/BarbaraBFLS94","sF4xdH31mDAJ")).
pos(eqo("journals/sigmod/BarbaraS97","Iw5bYR098o4J")).
pos(eqo("journals/sigmod/BarbaraS97","iOxtnjbC4SEJ")).
pos(eqo("journals/sigmod/BarclayBGS94","v1aol6mmLdMJ")).
pos(eqo("journals/sigmod/BarclayBGS94","wPhDoeiINQsJ")).
pos(eqo("journals/sigmod/Bernstein98","qCvPRNWJZNEJ")).
pos(eqo("journals/sigmod/BichlerSZ98","goq6Z9bDeSsJ")).
pos(eqo("journals/sigmod/BoucelmaCGJLL02","I9JXY0-R4GgJ")).
pos(eqo("journals/sigmod/BuchnerM98","-3LEFj2dY-UJ")).
pos(eqo("journals/sigmod/BuchnerM98","4J5CvdomBmsJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","GruVHotOoPQJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","eKF1zVNKP0gJ")).
pos(eqo("journals/sigmod/BunemanLSTW94","q8MxrLeFlz8J")).
pos(eqo("journals/sigmod/BusslerFM02","MkHxLPaNdqoJ")).
pos(eqo("journals/sigmod/BusslerFM02","m56HUW18JKAJ")).
pos(eqo("journals/sigmod/ButtlerCCFHLPRX02","JScvAMYcsmoJ")).
pos(eqo("journals/sigmod/CabreraLM01","b201QeqnlNkJ")).
pos(eqo("journals/sigmod/CaleroPR03","zWoRcQffsq8J")).
pos(eqo("journals/sigmod/CalvaneseGLV03","pGcIRyDyFG8J")).
pos(eqo("journals/sigmod/CampbellEM03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D777002%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ChaudhuriD97","d7vY6vDq_7EJ")).
pos(eqo("journals/sigmod/ChaudhuriD97","zO0DfwHqXKUJ")).
pos(eqo("journals/sigmod/Chen94","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D187460%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CiliaB02","Y1HVgTopekIJ")).
pos(eqo("journals/sigmod/ClementLGMK97","J7Y20fYLGbcJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","3aPleydkcIoJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","cjvOCqu3cJgJ")).
pos(eqo("journals/sigmod/ConradHHKRSS99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D333608%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/CruzKLSWY02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D601882%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/DogacDATKCD98","fYMpjIpF8ckJ")).
pos(eqo("journals/sigmod/DongS00","gH_HDDJghbAJ")).
pos(eqo("journals/sigmod/DunhamH95a","ShXp0F0h7Z4J")).
pos(eqo("journals/sigmod/Eisenberg96","ODNMCIJO6xMJ")).
pos(eqo("journals/sigmod/Eisenberg96","yzlys0OQkt8J")).
pos(eqo("journals/sigmod/EisenbergM02","wgK6p4mDSIMJ")).
pos(eqo("journals/sigmod/FernandezFLS97","9NlVdFCl2ysJ")).
pos(eqo("journals/sigmod/FernandezFLS97","LJKpMU1tIlcJ")).
pos(eqo("journals/sigmod/FernandezFLS97","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D262763%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FlorescuLM98","FCcDKONgJVYJ")).
pos(eqo("journals/sigmod/FlorescuLM98","_SR_pRTnA6IJ")).
pos(eqo("journals/sigmod/FowlerPNB99","2cbB8em2uAIJ")).
pos(eqo("journals/sigmod/FowlerPNB99","OewAZ4AUDOQJ")).
pos(eqo("journals/sigmod/FowlerPNB99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310060%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/FrankGGJKLMNPSSSTW99","ERqqWPMwU2sJ")).
pos(eqo("journals/sigmod/FreemanG96","Em3qp7RGalkJ")).
pos(eqo("journals/sigmod/Giorgini03","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D959084%26type%3Dpdf%26dl%3Dportal%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/HellersteinHM03","6ussAgzdL6oJ")).
pos(eqo("journals/sigmod/Huyn01","KNYDz76C_HsJ")).
pos(eqo("journals/sigmod/KramerNKRLKLZ97","1sBvG9OXpMAJ")).
pos(eqo("journals/sigmod/KuokFW98","qyXhN3CrVQ8J")).
pos(eqo("journals/sigmod/LaenderRST02","eQPLe8gg-mIJ")).
pos(eqo("journals/sigmod/LaenderRST02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D565137%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/LawderK01","eznFJ2e_pQQJ")).
pos(eqo("journals/sigmod/LiefkeS00","4q4PDOS45uIJ")).
pos(eqo("journals/sigmod/LiefkeS00","N0eowMtIAukJ")).
pos(eqo("journals/sigmod/Loeffen94","jFNkGh68g6EJ")).
pos(eqo("journals/sigmod/Loeffen94","nSkolxxp1y0J")).
pos(eqo("journals/sigmod/MaximilienS02","hgjhR8PwNVwJ")).
pos(eqo("journals/sigmod/MaximilienS02","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D637417%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MedskerCS95","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D202673%26type%3Dpdf%26coll%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/MillerHHYHFP01","Zb2SExJNfkMJ")).
pos(eqo("journals/sigmod/NascimentoM99","url:http://portal.acm.org/ft_gateway.cfm%3Fid%3D310062%26type%3Dpdf%26dl%3DGUIDE%26dl%3DACM%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/ONeilG95","51gKshu0CWcJ")).
pos(eqo("journals/sigmod/ONeilG95","MUXTIMdJLjgJ")).
pos(eqo("journals/sigmod/Ouksel02","url:http://portal.acm.org/citation.cfm%3Fid%3D565117.565131%26dl%3DGUIDE%26dl%3DACM%26idx%3DJ689%26part%3Dperiodical%26WantType%3Dperiodical%26title%3DACM%2520SIGMOD%2520Record%26CFID%3D11111111%26CFTOKEN%3D2222222")).
pos(eqo("journals/sigmod/PourabbasR02","QyNfyYDySawJ")).
pos(eqo("journals/sigmod/QuixSJ02","BrO3XOrt66MJ")).
pos(eqo("journals/sigmod/RamDD99","uA-E1lBgLe0J")).
pos(eqo("journals/sigmod/RamamrithamSSTX96","kezAM71rts0J")).
pos(eqo("journals/sigmod/SchmidtWKFCMB01","mkfP-JNsNZoJ")).
pos(eqo("journals/sigmod/SegevJS95","2kiNfwTpqp4J")).
pos(eqo("journals/sigmod/ShethBS99","cqlnSEkt12EJ")).
pos(eqo("journals/sigmod/Snodgrass03b","PmIVKWJ5_V4J")).
pos(eqo("journals/sigmod/Stonebraker94","url:http://portal.acm.org/citation.cfm%3Fid%3D181551")).
pos(eqo("journals/sigmod/SycaraKWL99","-IaXJNRxKVEJ")).
pos(eqo("journals/sigmod/SycaraKWL99","7OyvdUHeptMJ")).
pos(eqo("journals/sigmod/SycaraKWL99","YgouJdrCoZQJ")).
pos(eqo("journals/sigmod/SycaraKWL99","foOIj5nrS-gJ")).
pos(eqo("journals/sigmod/VassiliadisS99","eGARASwVBrUJ")).
pos(eqo("journals/sigmod/VetterliVS00","ZUMidTbSKiEJ")).
pos(eqo("journals/sigmod/VetterliVS00","dAF5Z861mZgJ")).
pos(eqo("journals/tods/BaekgaardM95","6UycFCZooDoJ")).
pos(eqo("journals/tods/BaralisW00","4RrNbX-RjpsJ")).
pos(eqo("journals/tods/BunemanO96","Q28u7TpTgI0J")).
pos(eqo("journals/tods/BunemanO96","xT4l9LBtTcUJ")).
pos(eqo("journals/tods/CastanoAFP98","tm7SUvdcOHYJ")).
pos(eqo("journals/tods/CeriFPT95","DoS7NkmUyYgJ")).
pos(eqo("journals/tods/ChakrabartiKMP02","Cy8VDlIamc8J")).
pos(eqo("journals/tods/CliffordDIJS97","aKPlDMXvHT8J")).
pos(eqo("journals/tods/DattaVCK99","3BbftjVsIEIJ")).
pos(eqo("journals/tods/DekhtyarRS01","5HstPUbtZ1QJ")).
pos(eqo("journals/tods/FranklinCL97","-iaSLKFHwUkJ")).
pos(eqo("journals/tods/FranklinCL97","vqboZ3T4n4AJ")).
pos(eqo("journals/tods/FraternaliT95","sh-E7oORhVMJ")).
pos(eqo("journals/tods/FukudaMMT01","QdPN-QtgceAJ")).
pos(eqo("journals/tods/FukudaMMT01","_2f7zWIzK0QJ")).
pos(eqo("journals/tods/FukudaMMT01","lP571q5eN4gJ")).
pos(eqo("journals/tods/FukudaMMT01","lmXiI4fB9vgJ")).
pos(eqo("journals/tods/GravanoGT99","aXLcAfb2y5kJ")).
pos(eqo("journals/tods/KemmeA00","wiUPadLpCvoJ")).
pos(eqo("journals/tods/LechtenborgerV03","94m93uP4GM4J")).
pos(eqo("journals/tods/LiC01","_gwfttQaTEkJ")).
pos(eqo("journals/tods/MayL02","ky-2yjNGtW8J")).
pos(eqo("journals/tods/MelnikG03","iyliEUBEyhwJ")).
pos(eqo("journals/tods/MelnikG03","y2dZ5cRja_IJ")).
pos(eqo("journals/tods/PetersO97","er0r8doAGUQJ")).
pos(eqo("journals/tods/RosenthalR94","zM422IjZcPgJ")).
pos(eqo("journals/tods/TaoP03","faqaX7J_Kl8J")).
pos(eqo("journals/tods/WandSW99","pYtOkFSgdXYJ")).
pos(eqo("journals/tods/ZaharioudakisCF97","naUCkadkOekJ")).
pos(eqo("journals/tods/ZobelMR98","AvV6lMEBGWsJ")).
pos(eqo("journals/vldb/AgrawalHK03","NDKJPUgy_K4J")).
pos(eqo("journals/vldb/AntoshenkovZ96","N8syKKPN6IoJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","Cmq7lkkXNt4J")).
pos(eqo("journals/vldb/Barbara-MillaG94","Hc9uWxJu840J")).
pos(eqo("journals/vldb/Barbara-MillaG94","IvPHHa01uUkJ")).
pos(eqo("journals/vldb/Barbara-MillaG94","mFHdV09MfG8J")).
pos(eqo("journals/vldb/BarbaraI95","UI4WYndJlyIJ")).
pos(eqo("journals/vldb/BarbaraI95","bTYTn8VG5hIJ")).
pos(eqo("journals/vldb/BarbaraI95","gyC0D8oJbQMJ")).
pos(eqo("journals/vldb/ClaussenKKW00","DSF-ukHbE64J")).
pos(eqo("journals/vldb/FahlR97","zXSCJ9LzZ8cJ")).
pos(eqo("journals/vldb/FengYLH02","Uxh3R2hfBOAJ")).
pos(eqo("journals/vldb/GruserRZZ00","9EBKpmSLc_oJ")).
pos(eqo("journals/vldb/GutingS95","CBHicx5w3ocJ")).
pos(eqo("journals/vldb/GutingS95","ceBWKDUmKDAJ")).
pos(eqo("journals/vldb/GutingS95","dm3xutmyi_0J")).
pos(eqo("journals/vldb/HansonCDERTX98","F6Ko8ZvWypUJ")).
pos(eqo("journals/vldb/JagadishACLNPPSWWY02","zaDlTkyGASQJ")).
pos(eqo("journals/vldb/KashyapS96","AaTvigmNyAcJ")).
pos(eqo("journals/vldb/KashyapS96","GlmJMsfDgXwJ")).
pos(eqo("journals/vldb/KashyapS96","h_g4xOpUq6wJ")).
pos(eqo("journals/vldb/KraissW98","K0aOFYBWg3AJ")).
pos(eqo("journals/vldb/KraissW98","LMz7v87sxxYJ")).
pos(eqo("journals/vldb/KraissW98","yabWSyqur-8J")).
pos(eqo("journals/vldb/LaurentLSV01","TTIgIh9uC_YJ")).
pos(eqo("journals/vldb/LawLG99","TOXrbhbbNJ4J")).
pos(eqo("journals/vldb/Li03","XkdLpQ5x-YIJ")).
pos(eqo("journals/vldb/MaratheS02","z6JEYoArZmsJ")).
pos(eqo("journals/vldb/MehtaGPN98","7Zf8Y2idDb0J")).
pos(eqo("journals/vldb/MehtaGPN98","xd6denVlP5IJ")).
pos(eqo("journals/vldb/NgC98","eTDBrdfpGNEJ")).
pos(eqo("journals/vldb/PanagosB97","Ht4Yl1kJuxIJ")).
pos(eqo("journals/vldb/RamakrishnanSSS94","lH_n19yVmWgJ")).
pos(eqo("journals/vldb/RamakrishnanSSS94","rgA2DgNVPBUJ")).
pos(eqo("journals/vldb/RamamurthyDS03","DAlyofX710AJ")).
pos(eqo("journals/vldb/RamamurthyDS03","uem5wXLoU0wJ")).
pos(eqo("journals/vldb/RoySSSA98","JB684f38DiwJ")).
pos(eqo("journals/vldb/ScheuermannWZ98","Q_JRmsXFEM4J")).
pos(eqo("journals/vldb/SofferS98","miubKxLrikUJ")).
pos(eqo("journals/vldb/SuHHHLWLPLL01","GRzquCzL_OUJ")).
pos(eqo("journals/vldb/TenienteO95","aC-8qspy24wJ")).
pos(eqo("journals/vldb/VaghaniRKSSLH94","B3E3_clrrrYJ")).
pos(eqo("journals/vldb/WhiteD95","qeHXdJ2x7eMJ")).
